DataDog/documentation

- content/en/agent/docker/apm.md
corrects the example setup for .net apm on docker, adds a table for how you're meant to set the variable depending on your system
support request
https://docs-staging.datadoghq.com/cswatt/docker-apm-net-correction/agent/docker/apm
---
> DOCS-3002 update docker apm .net instructions

- content/en/serverless/distributed_tracing/_index.md
- content/en/serverless/distributed_tracing/serverless_trace_merging.md
- content/en/serverless/distributed_tracing/serverless_trace_propagation.md
We recently released Tracing and Monitoring for AWS Managed Services (https://www.datadoghq.com/blog/monitor-aws-fully-managed-services-datadog-serverless-monitoring/).
These docs reflect the previous state, where trace context was propagated manually. Now this is automatic for Python and Node!
https://docs-staging.datadoghq.com/aj.stuyvenberg/bump-datadog-lambda-python-version-52/serverless/distributed_tracing/serverless_trace_propagation/
---
> Refactor docs to account for managed service monitoring and tracing

- content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
Links this guide to the Troubleshooting page for Browser RUM + copy nits.
DOCS-3135 (Hotjar)
https://docs-staging.datadoghq.com/alai97/real-user-monitoring-source-maps-guide-update/real_user_monitoring/guide/upload-javascript-source-maps
---
> DOCS-3135 Upload Javascript source maps Edits

- content/en/tracing/profiler/enabling/dotnet.md
- content/en/tracing/profiler/enabling/go.md
- content/en/tracing/profiler/enabling/java.md
- content/en/tracing/profiler/enabling/linux.md
- content/en/tracing/profiler/enabling/nodejs.md
- content/en/tracing/profiler/enabling/php.md
- content/en/tracing/profiler/enabling/python.md
- content/en/tracing/profiler/enabling/ruby.md
Adds text clarifying that the profiling product does not support serverless.
Customers not finding out that profiling doesn't support serverless without a lot of hassle.
https://docs-staging.datadoghq.com/henrik.dafgard/profiling-serverless/tracing/profiler/enabling/go
https://docs-staging.datadoghq.com/henrik.dafgard/profiling-serverless/tracing/profiler/enabling/java
https://docs-staging.datadoghq.com/henrik.dafgard/profiling-serverless/tracing/profiler/enabling/python
https://docs-staging.datadoghq.com/henrik.dafgard/profiling-serverless/tracing/profiler/enabling/ruby
https://docs-staging.datadoghq.com/henrik.dafgard/profiling-serverless/tracing/profiler/enabling/nodejs
https://docs-staging.datadoghq.com/henrik.dafgard/profiling-serverless/tracing/profiler/enabling/dotnet …
> Clarify that profiling is not supported on serverless.

- content/en/logs/guide/logs-rbac-permissions.md
This line is no longer accurate after “log permission flattening”.
Removes outdated note from Logs RBAC Permissions.
```
Note: This permission also grants [Logs Write Processors](https://docs.datadoghq.com/logs/guide/logs-rbac-permissions/?tab=ui#logs_write_processors) (for all processors on all pipelines) permissions behind the scenes.
```
https://datadoghq.atlassian.net/browse/ACCESS-650
https://docs-staging.datadoghq.com/alexa.liaskovski/access-650/logs/guide/logs-rbac-permissions
cc @DataDog/team-aaa-access 
---
> [ACCESS-650] Update public docs to reflect log permission flattening.

- content/en/security_platform/application_security/getting_started/ruby.md
Updates AppSec onboarding for Ruby clients for the upcoming [`ddtrace` 1.0](https://github.com/DataDog/dd-trace-rb/milestone/79) release.
This will be the first release with official AppSec support.
https://docs-staging.datadoghq.com/marcotc/ruby-appsec-namespacing-1.0/security_platform/application_security/getting_started/ruby
---
> AppSec:Ruby:Update installation instructions for ddtrace 1.0

- content/en/continuous_integration/setup_pipelines/jenkins.md
This PR adds a new section in the Jenkins docs for CIViz explaining how to propagate Git information to the Datadog Plugin if the customer is not using a Jenkinsfile.
https://docs-staging.datadoghq.com/drodriguezhdez/gitinfo_jenkins/continuous_integration/setup_pipelines/jenkins/?tab=usingui
---
> [ciapp] Add section to propagate git info in Jenkins

- content/en/agent/proxy.md
Add proxy settings doc for network devices metadata
Missing doc for network devices metadata
https://docs-staging.datadoghq.com/alex/ndm_proxy/agent/proxy/
---
> Add proxy settings doc for network devices metadata

- content/en/agent/guide/agent-log-files.md
Update `$pwd` to `$(pwd)`.
`$pwd` is considered as an environment variable.
```bash
vagrant@vagrant:~$ cat $pwd/ddagent-install.log
cat: /ddagent-install.log: No such file or directory
```
`$pwd` should be `$(pwd)`.
---
> Enclose `pwd` in Agent installation log files

- content/en/agent/troubleshooting/send_a_flare.md
- content/en/security_platform/cloud_workload_security/troubleshooting.md
https://docs-staging.datadoghq.com/paulcacheux/cws-secagent-flare
https://docs-staging.datadoghq.com/paulcacheux/cws-secagent-flare/agent/troubleshooting/send_a_flare/?tab=agentv6v7
https://docs-staging.datadoghq.com/paulcacheux/cws-secagent-flare/security_platform/cloud_workload_security/troubleshooting
---
> [CWS] add troubleshooting section about security-agent flare

- content/en/security_platform/application_security/setup_and_configure.md
Adds a section for exclusion filters and uninstallation to the App Sec setup + config section
Q1 OKR
https://docs-staging.datadoghq.com/sarina/appsec-setup-edits/security_platform/application_security/setup_and_configure/#exclusion-filters
It looks like the formatter formatted some white space for us, magic ✨ 
---
> Add exclusion filters and uninstall to App Sec docs

- content/en/continuous_integration/setup_pipelines/buildkite.md
Documents the usage of `dd_metrics` metadata tags in buildkite.
This together with the `dd_tags` allows setting string metadata tags and float metrics tag to cover uses of measures and facets.
https://docs-staging.datadoghq.com/carlos.gonzalez/add-dd-metrics-to-buildkite-pipeline/continuous_integration/setup_pipelines/buildkite/
---
> [CIAPP] Document dd_metrics for buildkite pipelines

- content/en/logs/log_collection/csharp.md
Need to explicitly call out the URL/port setting for setting up agentless serilog logging in US3
URL: http-intake.logs.us3.datadoghq.com
Port: 443
as seen here - https://docs.datadoghq.com/logs/log_collection/?tab=host#supported-endpoints
---
> Clearer configs needed for US3 agentless logging

- content/en/agent/docker/_index.md
- content/en/agent/docker/apm.md
- content/en/agent/docker/log.md
- content/en/agent/docker/prometheus.md
- content/en/developers/dogstatsd/_index.md
- content/en/logs/faq/how-to-tail-logs-from-host-using-a-container-agent.md
- content/en/logs/guide/how-to-set-up-only-logs.md
- content/en/network_monitoring/performance/setup.md
- content/en/security_platform/cloud_workload_security/getting_started.md
- content/en/tracing/guide/ignoring_apm_resources.md
Add `--cgroupns host` parameter to all Docker commands to make sure Agent keeps working when users migrate to `cgroupv2`
https://docs-staging.datadoghq.com/vboulineau/cgroupv2
---
> Add cgroupns host to all Docker commands to keep the Agent working with cgroupv2

- content/en/tracing/trace_retention/usage_metrics.md
Correct what seems to be a missing edit where the text refers to "three" metrics but lists four.
I was reading the docs and this seemed like a simple mistake
https://docs-staging.datadoghq.com/ajgajg1134-four-metrics/<PATH>
---
> four standard metrics not three

- content/en/account_management/multi_organization.md
Creates a section in the Multi Organization doc that tells users what steps to take so they can properly access a child organization created from a parent organization that is SAML strict.
Éanna, a Solutions Engineer, reported [DOCS-3140](https://datadoghq.atlassian.net/browse/DOCS-3140). When creating a child org from a SAML strict parent org, users have to configure a user that bypasses SAML and can log in with a username and password. Child orgs do not inherit SAML settings from their parents, so the default behavior leaves no way to log in to the newly created child org.
https://docs-staging.datadoghq.com/uchen/saml-child/account_management/multi_organization/#saml-strict-parent-organizations
---
> DOCS-3140 instruct users about child of SAML strict parent org

- content/en/agent/kubernetes/_index.md
- Removed Step2 `Create a secret that contains your Datadog API Key.`
Because this secret is defined in `datadog-agent.yaml` and it causing this error when a user follow this doc.
```Error from server (AlreadyExists): error when creating "datadog.yaml": secrets "datadog-agent" already exists```
- Added a step to get base64 encoded API key and replace it in manifest. This is aligned with Cluster agent install step. (https://docs.datadoghq.com/agent/kubernetes/?tab=daemonset#overview)
- Added a step to define a token for Secret named `datadog-agent-cluster-agent` because it is not explained.
> Update Install steps for Daemonset

- content/en/developers/custom_checks/write_agent_check.md
Renames the `checkvalue.py` tutorial file to `custom_checkvalue.py`.
We literally tell people to prefix custom checks with `custom_` in _this_ documentation. 😉 
https://docs-staging.datadoghq.com/phrawzty/custom_check_name/developers/custom_checks/write_agent_check/
---
> rename tutorial custom check as recommended by docs

- content/en/synthetics/guide/or-logic-api-tests-assertions.md
Small doc edit with Jules.
Introduction to Docs!
https://docs-staging.datadoghq.com/alai97/synthetics-guide-nit/synthetics/guide/or-logic-api-tests-assertions/
---
> Perform OR logic in API tests assertions Edit

- content/en/integrations/faq/how-do-i-pull-my-ec2-tags-without-using-the-aws-integration.md
> fix typo in config parameter name

- assets/styles/components/_header.scss
- removes `margin-bottom` from the product dropdown menu's category titles – a result of reboot styles on Docs
- recent changes to product dropdown menu
https://docs-staging.datadoghq.com/carlos/product-menu-spacing-fix/
---
> Fix margin-bottom on product category titles

- content/en/agent/troubleshooting/agent_check_status.md
Added a new symlink:  [4] integrations
Previous link ` integration’s documentation` directed to /help/
Corrected: the integrations tab misdirection
https://a.cl.ly/GGuED7W9 
Now directs to /integrations/
-> https://docs.datadoghq.com/integrations/ 
Correct broken link paths
---
> Fixed integrations documentation link

- content/en/continuous_integration/setup_pipelines/jenkins.md
This PR adds a clarification about the fact the HTTP mode is not supported for CI App for the Jenkins plugin.
We had some customers wondering if they could use the HTTP mode, so we clarify it here.
https://docs-staging.datadoghq.com/alexc/CIAPP-jenkins-http/continuous_integration/setup_pipelines/jenkins/?tab=usingui
---
> [CIAPP] explicitly exclude http mode for jenkins

- content/en/notebooks/_index.md
Adds link to Notebooks docs to Blog post
on-call tasks
https://docs-staging.datadoghq.com/kari/add-notebooks-blog-link/notebooks/
> Add notebooks blog link

- content/en/tracing/setup_overview/setup/php.md
INI settings are not supported by the PHP tracer but were not documented. This PR adds their definitions.
https://docs-staging.datadoghq.com/php/ini-settings/tracing/setup_overview/setup/php/?tab=containers#configuration
---
> Document ini settings for APM php

- content/en/api/latest/rate-limits/_index.md
- content/en/api/v1/rate-limits/_index.md
- content/en/api/v2/rate-limits/_index.md
Update language on rate limits to be generic and refer to X-Ratelimit-Name for increase requests.
These are being reflected to have shorter time-to-recovery windows and different datacenters had different values. This language is more generic and provides details on where to find information for additional requests beyond default rate limits.
Difficult to keep this documentation in line for every datacenter as it's not tied to the source of truth and was missing the large majority of endpoints. This provides a more general response to `api(.*)?.datadoghq.(com|eu)` && govcloud while maintaining intake + event aggregation specifics
https://docs-staging.datadoghq.com/rate-limits-fix/api/latest/rate-limits
---
> update language on rate limits to be generic and refer to X-Ratelimit-Name for increase requests

- content/en/tracing/setup_overview/compatibility_requirements/php.md
Requirements page was not up to date with PHP 8.1
[Preview](https://docs-staging.datadoghq.com/apm/php/8.1/tracing/setup_overview/compatibility_requirements/php/)
---
> [APM/PHP] Update requirements page to include support for PHP 8.1

- content/en/security_platform/cloud_siem/log_detection_rules.md
Adds documentation for the new "impossible travel" detection method for
log detection rules.
https://docs-staging.datadoghq.com/bjorn.marschollek/SEC-1639/security_platform/cloud_siem/log_detection_rules?tab=impossibletravel
---
> [SEC-1639] Add impossible travel detection methods

- content/en/tracing/setup_overview/setup/dotnet-core.md
- content/en/tracing/setup_overview/setup/dotnet-framework.md
To clarify that the stop and start commands must always be used to start the .NET tracing library for IIS. Pressing the buttons on the IIS UI does not fully stop the process so no tracing occurs when the UI is used.
Clarify that that the commands in the docs must be used to start getting .NET traces in IIS.
https://docs-staging.datadoghq.com/wantsui/dotnet-setup-docs/tracing/setup_overview/setup/dotnet-core?tab=windows
https://docs-staging.datadoghq.com/wantsui/dotnet-setup-docs/tracing/setup_overview/setup/dotnet-framework?tab=windows
This should be reviewed by a member of the .NET APM team first. Edit: PR has been looked at by a .NET APM team member ✅  
---
> [APM][dotnet] Clarify that IIS UI cannot be used to start the .NET tracing library

- content/en/tracing/trace_retention/_index.md
I saw that a link wasn't being rendered in these docs, because the corresponding footnote-style link wasn't in the markdown, so I added what I think the link intended to refer to.
Preview: https://docs-staging.datadoghq.com/dgoffredo-patch-1/tracing/trace_retention/
> add missing link to trace retention docs

- content/en/monitors/create/types/log.md
The minimum logs monitor evaluation time is 5min (recommended). Though in the UI customer can set custom time below 5min (all the way down to 1min). Time evaluation less than 5min cause the monitor to through `BADPARAM` error and the monitor goes to infinite `NO DATA` state. There are multiple escalations from the customer related to this issue and our engineering is aware of it. They are working on a fix which is a bit complicated and may take time. Which is why in the meantime we are going to update the logs monitor doc so that at least we can go back to the customer and say please use 5min or more as per the doc.
Issue 1: https://datadoghq.atlassian.net/browse/LOGSS-5430
Issue 2: https://datadoghq.atlassian.net/browse/LOGSS-5551 …
> Change custom time set minimum 5min from 1min

- content/en/metrics/_index.md
Changing the Configure Time Aggregation to match the image of the metric query. It has 3600 seconds in the image, has 360 seconds in the Configure Time Aggregation
https://docs.datadoghq.com/metrics/#configure-time-aggregation
Small typo in the docs
https://docs.datadoghq.com/metrics/
---
> ross-macwilliam/update_configure_time_aggregation

- content/en/developers/dogstatsd/_index.md
Fix typos and broken links on DogStatsD page
[DOCS-3178](https://datadoghq.atlassian.net/browse/DOCS-3178) A translator noticed some broken links on this page.
https://docs-staging.datadoghq.com/uchen/dogstatsd-links/developers/dogstatsd/?tab=hostagent
---
> DOCS-3178 Simplify Javadoc links for DogStatsD clients

- layouts/shortcodes/appsec-getstarted-2-canary.md
Remove the part about the version because customers don't have access to that information.
Eng requested it.
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/java/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/dotnet/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/ruby/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/php/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/nodejs/
---
> Remove note about version

- content/en/security_platform/application_security/getting_started/_index.md
- content/en/security_platform/application_security/getting_started/dotnet.md
- content/en/security_platform/application_security/getting_started/go.md
- content/en/security_platform/application_security/getting_started/java.md
- content/en/security_platform/application_security/getting_started/nodejs.md
- content/en/security_platform/application_security/getting_started/php.md
- content/en/security_platform/application_security/getting_started/ruby.md
- content/en/security_platform/application_security/setup_and_configure.md
Adds the AppSec troubleshooting link to the further reading sections of the Getting Started and Setup / Config pages.
DOCS-3040
https://docs-staging.datadoghq.com/may/add-troubleshooting-link/security_platform/application_security/getting_started/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/java/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/dotnet/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/ruby/
https://docs-staging.datadoghq.com/may/remove-version-note/security_platform/application_security/getting_started/php/
https://docs-staging.datadoghq.com/may/remove-version-note/security_pla …
> [DOCS-3040] Add AppSec troubleshooting links

- content/en/agent/cluster_agent/setup.md
- content/en/agent/troubleshooting/windows_containers.md
adds info about how you can monitor windows containers with the cluster agent
https://docs-staging.datadoghq.com/cswatt/windows-cluster/agent/troubleshooting/windows_containers/#mixed-clusters-linux--windows
https://docs-staging.datadoghq.com/cswatt/windows-cluster/agent/cluster_agent/setup/?tab=helm#windows-containers
---
> DOCS 2971 - adding cluster agent windows info

- content/en/agent/kubernetes/integrations.md
Updates 2 outdated links for Autodiscovery Container Identifiers.
I was using the documentation for a sandbox project and was unable to find the latest Helm chart because the link was out of date.
https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=helm
https://docs-staging.datadoghq.com/nathanandersen-path-1/agent/kubernetes/integrations/?tab=helm
It's just updating 2 URLs.
---
> Updating outdated Helm links

- content/en/tracing/trace_retention/usage_metrics.md
Change APM dashboard link to go to the actual dashboard.
DOCS-3199
https://docs-staging.datadoghq.com/may/update-apm-dashboard-link/tracing/trace_retention/usage_metrics
---
> [DOCS-3199] Update APM dashboard link

- content/en/tracing/setup_overview/setup/python.md
Fix the flag to get information once you've setup tracing.
The flag was incorrect and status does not exist, it should be info
> zachg fixing command from status to info

- content/en/tracing/setup_overview/setup/python.md
Document an existing `DD_TRACE_RATE_LIMIT` environment variable/configuration for the Python tracing client.
This is currently only documented on the tracing client's own API docs, but we want it to be present/available here as well.
https://docs-staging.datadoghq.com/brettlangdon/rate.limit.doc/tracing/setup_overview/setup/python#configuration
---
> chore(tracing/python): add documentation for DD_TRACE_RATE_LIMIT

- assets/styles/pages/_global.scss
- fixes a nav overlap issue with the main content container on tablet-sized (< 1200 > 991px) viewports
https://datadoghq.atlassian.net/browse/WEB-2192
https://docs-staging.datadoghq.com/carlos/global-padding-top-tablet/
---
> Adjust global padding-top for tablet viewports

- content/en/synthetics/browser_tests/_index.md
Adds specific recording dimensions for devices in Synthetic browser tests.
DOCS-3210
https://docs-staging.datadoghq.com/alai97/synthetic-browser-tests-device-dimensions-update/synthetics/browser_tests/
---
> DOCS-3210 Browser Tests Edit

- content/en/developers/dogstatsd/unix_socket.md
Document origin detection over UDS on EKS Fargate
https://docs-staging.datadoghq.com/ahmed/uds-origin-eks-fargate/developers/dogstatsd/unix_socket
---
> Document origin detection over UDS on EKS Fargate

- translate.yaml
Ignore `rapdev_services` in the translation config so the file will not be sent to Transifex.
https://datadoghq.atlassian.net/browse/WEB-2196
n/a
The resource was deleted directly in Transifex, and there is a marketplace PR to hide the tile from the Docs site.  https://github.com/DataDog/marketplace/pull/352.   When this work is ready to go public we will have to remove the redirect from CloudOps as well.
---
> [WEB-2196] Adding rapdev_services md to ignored files config

- content/en/synthetics/guide/manually-adding-chrome-extension.md
Copy edits + adds new links to the CRX file and in-app workflow.
Slack with Alex
https://docs-staging.datadoghq.com/alai97/synthetics-manual-chrome-extension-guide-update/synthetics/guide/manually-adding-chrome-extension/
---
> Manually Adding the Browser Test Chrome Extension to Internal Applications Stores Guide Edits

- content/en/getting_started/integrations/aws.md
Remove a duplicate image from step 6 displaying outdated parameters.
DOCS-3222
https://docs-staging.datadoghq.com/bryce/remove-duplicate-image-from-aws-getting-started-guide/getting_started/integrations/aws/
---
> Remove duplicate image from step 6

- content/en/agent/troubleshooting/send_a_flare.md
Update the docker flare command because the Datadog agent container is named `dd-agent` and not `datadog-agent`.
DOCS-3184
https://docs-staging.datadoghq.com/may/update-docker-flare-command/agent/troubleshooting/send_a_flare/?tab=agentv6v7#pagetitle
---
> [DOCS-3184] Update docker flare command

- content/en/logs/log_configuration/pipelines.md
Update the link to the trace remapper which is now in the logs processors' page.
DOCS-3211
https://docs-staging.datadoghq.com/may/update-trace-remapper-link/logs/log_configuration/pipelines/?tab=traceid#trace-id-attribute
---
> [DOCS-3211] Update trace remapper link

- content/en/serverless/installation/nodejs.md
Looks like when node14 support was released, this was missed (in the custom section, it's listed in the other methods as supported)
---
> docs: Ensure node-14 is documented in the custom config section

- content/en/agent/versions/upgrade_to_agent_v6.md
- content/en/agent/versions/upgrade_to_agent_v7.md
Removes multiple instances of the exact same command for multiple Linux distros - we can just say the same command works for all of them.
https://docs-staging.datadoghq.com/slavek.kabrda/agent-upgrade-deduplicate/agent/versions/upgrade_to_agent_v6/?tab=linux
https://docs-staging.datadoghq.com/slavek.kabrda/agent-upgrade-deduplicate/agent/versions/upgrade_to_agent_v7/?tab=linux
---
> Deduplicate instances of agent upgrade command

- content/en/continuous_integration/guides/flaky_test_management.md
This PR adds a disclaimer in the flaky tests management section informing that there is a limit in the flaky tests we're showing in that table of 1000 flaky tests.
https://docs-staging.datadoghq.com/drodriguezhdez/add_disclaimer_max_1k_flaky_tests/continuous_integration/guides/flaky_test_management
---
> [CIAPP] Show a disclaimer about 1k flaky tests limit in the flaky tests management page.

- content/en/tracing/setup_overview/setup/java.md
Default UDS support has been added to the trace clients.
https://docs-staging.datadoghq.com/mcculls/java_uds_support/tracing/setup_overview/setup/java/?tab=containers#configure-the-datadog-agent-for-apm
Aligned the container section examples to better match with [Python](https://docs-staging.datadoghq.com/mcculls/java_uds_support/tracing/setup_overview/setup/python/?tab=containers#configure-the-datadog-agent-for-apm) where `DD_TRACE_AGENT_URL` is now preferred over the individual host and port variables
---
> apm(java): update docs for UDS defaults

- content/en/tracing/connect_logs_and_traces/dotnet.md
Adds note about setting up a trace remapper to parse the trace id for correlating traces with logs.
DOCS-3162. Customer brought up the issue in a Zendesk ticket.
https://docs-staging.datadoghq.com/may/parse-dotnet-trace-id/tracing/connect_logs_and_traces/dotnet/?tab=serilog
---
> [DOCS-3162] Add note about parsing trace id

- content/en/tracing/setup_overview/setup/php.md
Add `DD_TRACE_SPANS_LIMIT` property description to our docs.
https://docs-staging.datadoghq.com/apm/php/span-limit/tracing/setup_overview/setup/php/?tab=containers#configuration
---
> [APM/PHP] Add spans limit property

- content/en/tracing/profiler/profiler_troubleshooting.md
Adds a word to clarify the sentence describing low-fidelity profiles
question from translator
https://docs-staging.datadoghq.com/kari/linux-prof-fix/tracing/profiler/profiler_troubleshooting/#profiles-are-empty-or-sparse
---
> Tiny fix to linux profiler troubleshooting

- content/en/agent/amazon_ecs/tags.md
Add Out-of-the-box tags table for ECS
https://docs-staging.datadoghq.com/ahmed/ecs-ec2-ootb-tags/agent/amazon_ecs/tags/
---
> ECS Out-of-the-box tags

- content/en/continuous_integration/setup_tests/junit_upload.md
Include instructions for the usage of `datadog-ci`'s standalone binary.
Make it simpler to use `datadog-ci`, without needing to install `node` in your environment. 
https://docs-staging.datadoghq.com/juan-fernandez/standalone-binary-datadog-ci/continuous_integration/setup_tests/junit_upload/#standalone-binary-beta
---
> [ci-visibility] Instructions for `datadog-ci` standalone binary

- config/_default/menus/menus.en.yaml
- content/en/agent/versions/_index.md
- content/en/agent/versions/upgrade_between_agent_minor_versions.md
Provides instructions for Agent minor version upgrades.
This will need https://github.com/DataDog/datadog-agent/pull/11079 merged and released first before merging.
https://docs-staging.datadoghq.com/slavek.kabrda/agent-minor-upgrades/agent/versions/upgrade_between_agent_minor_versions/?tab=linux
https://docs-staging.datadoghq.com/slavek.kabrda/agent-minor-upgrades/agent/versions?tab=agentv7vsv6
---
> Provide instructions on Agent minor version upgrades

- content/en/continuous_integration/explore_pipelines.md
Add job logs collection mention to exploring pipelines page
This is particularly needed to link to it from the UI (see context in https://datadoghq.atlassian.net/browse/CIAPP-3783).
https://docs-staging.datadoghq.com/ramon/ci-app_job-log-collection/continuous_integration/explore_pipelines/#explore-connections-to-logs
---
> [CIAPP-3783] Add job logs collection mention to exploring pipelines page

- content/en/monitors/guide/_index.md
- content/en/monitors/guide/monitor_api_options.md
- Change all of the "None" values in the Monitor API Options Guide to "null".
- Add the Monitor API Options Guide to the Monitors Guide index
A translator asked whether "None" in this document was a literal "None" or meant no value. I followed up with the Alerting team, and Phillip Baker, a team lead, said that all of those values should be "null". The API uses JSON, not Python. The API was recently migrated to JSON, so this page must have been missed during the migration.
While previewing the changes to the Monitor API Options Guide, I also noticed that it is missing from the Monitors Guide index, and added it.
https://docs-staging.datadoghq.com/uchen/monitor-api-null/monitors/guide/monitor_api_options/
https://docs-staging.datadoghq.com/uchen/monitor-api-null/monitors/guide/
---
> DOCS-3240 Replace 'None' in monitor api options with 'null'

- content/en/monitors/service_level_objectives/error_budget.md
Correcting syntax for thresholds
Correct terraform syntax error
faced issues when referring 
---
> Correcting the syntax

- content/en/tracing/trace_ingestion/mechanisms.md
Fix 2 wrong env variables. The same fix will be shipped on agent 7.36 config template https://github.com/DataDog/datadog-agent/pull/11271/files
---
> APM ingestion control: fix env variables

- content/en/tracing/faq/_index.md
- content/en/tracing/faq/service_definition_api.md
Publishes beta API docs for service definition endpoints
docs-3216
https://docs-staging.datadoghq.com/kari/docs-3216-svc-catalog-api/tracing/faq/service_definition_api/
---
> Service Definition API doc

- content/en/tracing/setup_overview/custom_instrumentation/go.md
WithServiceName has been deprecated and no longer works.
See: https://github.com/DataDog/dd-trace-go/blob/2414cdc7dad50aefc51bd94cee9a84c1f698b370/ddtrace/tracer/option.go#L520-L523
Keep the example up to date with the latest specifications.
I happened to notice it.
The documentation here has already been updated.
https://docs.datadoghq.com/tracing/setup_overview/setup/go/?tab=containers
---
> Use WithService instead of WithServiceName in the example

- content/en/agent/cluster_agent/commands.md
the old link was pointing to the wrong place
also made the link language a bit clearer
https://docs-staging.datadoghq.com/cswatt/cluster-agent-linkfix/agent/cluster_agent/commands
> DOCS-3191 - fixing link in cluster agent command section

- content/en/account_management/api-app-keys.md
Adds a subsection providing instructions for remediation of exposed private API or Application keys.
Clarifying instructions in leaked key alerts sent to users. Also to be referenced by Datadog 101 training question.
https://docs-staging.datadoghq.com/jake.hooker/TAS-84-exposed-key-remediation/account_management/api-app-keys/
---
> Add exposed secret key remediation steps

- static/config/99datadog-amazon-linux-2.config
Adds a line to change the owner of `datadog.yaml` since the `install_script.sh` only does this the first time, when creating the file.
Customer report issue. Bug introduced in #13071
---
> Fix EBS sample config

- content/en/synthetics/api_tests/dns_tests.md
- content/en/synthetics/api_tests/http_tests.md
- content/en/synthetics/api_tests/icmp_tests.md
- content/en/synthetics/api_tests/ssl_tests.md
- content/en/synthetics/api_tests/tcp_tests.md
- content/en/synthetics/api_tests/udp_tests.md
- content/en/synthetics/api_tests/websocket_tests.md
- content/en/synthetics/browser_tests/_index.md
- content/en/synthetics/multistep.md
- content/en/synthetics/private_locations/_index.md
- content/en/synthetics/settings/_index.md
Updates the wording of the Permissions section of Synthetics pages to reflect the GA (Generally Available) status of Custom Roles.
Custom Roles will be GA in the next 1-2 weeks.
https://docs-staging.datadoghq.com/uchen/admin-synthetics
---
> Update synthetics pages for custom roles GA

- content/en/metrics/dogstatsd_metrics_submission.md
Histogram missing Java code example
Added Java to the Histogram code example list
needed java code example for ticket
---
> [doc] corrected missing java button

- content/fr/tracing/profiler/getting_started.md
- content/ja/tracing/profiler/getting_started.md
- content/ja/tracing/profiling/getting_started.md
Changes the ja/fr profiling getting started pages to use the correct java tracer download link
The old link in these pages have been changed for all other pages, and today the old link stopped working.
https://docs-staging.datadoghq.com/ban/use-official-java-tracer-link-in-jp-fr-docs/fr/tracing/profiler/getting_started
https://docs-staging.datadoghq.com/ban/use-official-java-tracer-link-in-jp-fr-docs/ja/tracing/profiler/getting_started
https://docs-staging.datadoghq.com/ban/use-official-java-tracer-link-in-jp-fr-docs/ja/tracing/profiling/getting_started
---
> Change ja/fr Java profiling pages to use correct tracer link

- content/en/tracing/setup_overview/setup/dotnet-framework.md
Makes it clear where you can find older .NET Framework versions. 
---
> clarify historical compatibility for .NET tracer

- content/en/tracing/setup_overview/setup/dotnet-core.md
- content/en/tracing/setup_overview/setup/dotnet-framework.md
Documents DD_TRACE_RATE_LIMIT to match other tracers (https://github.com/DataDog/documentation/pull/13286)
Consistency
https://docs-staging.datadoghq.com/pierre/net-fix-trace-limit-param/tracing/setup_overview/setup/dotnet-framework/?tab=windows
> [APM .NET] Document DD_TRACE_RATE_LIMIT

- content/en/monitors/create/types/ci_pipelines.md
This PR changes the status for CI Pipeline monitors from "Beta" to "Alpha"
https://docs-staging.datadoghq.com/drodriguezhdez/use_alpha_label_for_cipipelines/monitors/create/types/ci_pipelines
---
> [CIAPP] Use "Alpha" for ci pipeline monitors

- content/en/agent/basic_agent_usage/_index.md
- content/en/agent/guide/agent-commands.md
Add `stream-logs` command to CLI of basic agent usage.
It doesn't mention `stream-logs` command, even we can use it.
https://github.com/DataDog/datadog-agent/pull/7163 added this feature.
```
vagrant@vagrant:~$ sudo datadog-agent stream-logs -h
Stream the logs being processed by a running agent
Usage:
datadog-agent stream-logs [flags]
Flags:
-h, --help            help for stream-logs
--name string     Filter by name
--source string   Filter by source
--type string     Filter by type
Global Flags:
-c, --cfgpath string           path to directory containing datadog.yaml
-n, --no-color                 disable color output
--sysprobecfgpath string   path to directory containing system-probe.yaml
```
---
> add `stream-logs` command to Agent pages

- content/en/serverless/guide/datadog_forwarder_java.md
- content/en/serverless/installation/java.md
Update the instructions for adding dd-trace-java to a Lambda function to include setting up tiered compilation. This will improve cold start performance of the functions.
---
> [serverless] Include tiered compilation settings in JAVA_TOOL_OPTIONS

- content/en/agent/docker/_index.md
Removes links to some missing code files. These files have moved in the repo, but they're not particularly useful for users.
https://docs-staging.datadoghq.com/heston/docs-3256/agent/docker/?tab=standard#tagging
Nope.
---
> [DOCS-3256] Remove links for missing code files

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Ruby tracing library setup page Edit button was pointing to `master` branch but reusing from `release` branch. This fixes that.
Wondering why my changes weren't showing up.
https://docs-staging.datadoghq.com/kari/fix-dd-trace-rb-edit-link/tracing/setup_overview/setup/ruby/, and the Edit button should point to `https://github.com/DataDog/dd-trace-rb/edit/release/docs/GettingStarted.md`
---
> Fix ruby tracing library edit link

- content/en/agent/guide/linux-agent-2022-key-rotation.md
Clarifies the situation around datadog-signing-keys package versions and recommends that customers upgrade to 1.1.0.
https://docs-staging.datadoghq.com/slavek.kabrda/update-datadog-signing-keys-version/agent/guide/linux-agent-2022-key-rotation
---
> Recommend and explain datadog-signing-keys version 1.1.0

- content/en/monitors/notify/variables.md
This PR adds a disclaimer for Formulas&Functions monitors in the `Matching attribute/tag variables` section of the monitor variables.
https://docs-staging.datadoghq.com/drodriguezhdez/template_variables_fnf_monitors/monitors/notify/variables/?tab=is_alert#matching-attributetag-variables
---
> Add disclaimer for F&F monitors in the monitor template variables section.

- content/en/account_management/billing/pricing.md
Adds CI Visibility to the billing/pricing page.
https://docs-staging.datadoghq.com/jorie/DOCS-2708/account_management/billing/pricing/
---
> (DOCS-2708) Add CI Visibility to pricing page

- content/en/tracing/runtime_metrics/dotnet.md
- content/en/tracing/runtime_metrics/go.md
- content/en/tracing/runtime_metrics/java.md
- content/en/tracing/runtime_metrics/nodejs.md
- content/en/tracing/runtime_metrics/python.md
- content/en/tracing/runtime_metrics/ruby.md
- content/en/tracing/setup_overview/setup/java.md
Fixes incorrect link
DOCS-3294
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/runtime_metrics/dotnet
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/runtime_metrics/go
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/runtime_metrics/java
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/runtime_metrics/nodejs
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/runtime_metrics/python
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/runtime_metrics/ruby
https://docs-staging.datadoghq.com/kari/docs-3294/tracing/setup_overview/setup/java
---
> Fix links to ECS create a task information

- content/en/agent/kubernetes/log.md
Applying log configurations via the file method (file, configMap, helm) is only supported when the Docker socket is being used to collect logs. This does not work when the Kubernetes log launcher is used.
Customer believed this should work based on the documentation, so adding a note to clarify this behavior.
https://docs-staging.datadoghq.com/kaitlavs-kubernetes-log/agent/kubernetes/log
---
> File log configs supported only with Docker socket

- content/en/security_platform/application_security/_index.md
- content/en/security_platform/application_security/getting_started/_index.md
- content/en/security_platform/application_security/getting_started/dotnet.md
- content/en/security_platform/application_security/getting_started/go.md
- content/en/security_platform/application_security/getting_started/java.md
- content/en/security_platform/application_security/getting_started/nodejs.md
- content/en/security_platform/application_security/getting_started/php.md
- content/en/security_platform/application_security/getting_started/ruby.md
- content/en/security_platform/application_security/setup_and_configure.md
Ensures people see that Fargate (and other cloud/container infra) is supported by AppSec
DOCS-3289
https://docs-staging.datadoghq.com/kari/docs-3289/security_platform/application_security/
https://docs-staging.datadoghq.com/kari/docs-3289/security_platform/application_security/getting_started/
https://docs-staging.datadoghq.com/kari/docs-3289/security_platform/application_security/setup_and_configure/
---
> Add note about infra support esp Fargate

- content/en/tracing/setup_overview/setup/go.md
This adds documentation to the corp doc site for the `DD_TRACE_RATE_LIMIT` variable.
Part of scheduled OKR work.
https://docs-staging.datadoghq.com/knusbaum/rate-limit/tracing/setup_overview/setup/go
> content/en/tracing/setup_overview/setup: add documentation for DD_TRACE_RATE_LIMIT

- .gitlab-ci.yml
- .vale.ini
Trademark checker on prod vs preview differs, while the new one is faster the old one is more reliable.
Turning the old one back on for previews until we can plan a better solution for speed + reliability.
Recent pr that passed its preview trademark check but once merged failed the live deploy check.
Doesn't impact the site built only the post deploy checking job
https://docs-staging.datadoghq.com/david.jones/old-tms/
---
> switch back to the old tms on previews

- content/en/tracing/setup_overview/setup/dotnet-core.md
- content/en/tracing/setup_overview/setup/dotnet-framework.md
Updates the `DD_TRACE_METHODS` documentation with feedback from the engineering team
The engineering team had further feedback on the documentation recently added in #13516 
https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-trace-methods-update/tracing/setup_overview/setup/dotnet-framework?tab=windows#automatic-instrumentation-optional-configuration
https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-trace-methods-update/tracing/setup_overview/setup/dotnet-core?tab=windows#automatic-instrumentation-optional-configuration
---
> APM > .NET > Update DD_TRACE_METHODS configuration documentation

- .gitlab-ci.yml
- src/scripts/config/config-docs.js
- yarn.lock
Updates local and preview environments to use Algolia sandbox
Separates staging workloads from Production indexes
Test search functions: 
https://docs-staging.datadoghq.com/nsollecito/algolia-sandbox/
Once corp-ci PR has been reviewed and merged, gitlab file needs to be updated to point back to main branch image for builds
Sometime after this is merged, we will want to cleanup old indexes in Algolia prod application 
---
> Update Docs preview to use Algolia sandbox

- content/en/account_management/billing/serverless.md
Document the way for customers to quickly verify the filtering rules.
It takes time for serverless and usage page to reflect the filtering. Customers often need to wait a long time to troubleshoot the filtering rules and make adjustments. Using the aws lambda invocations metric provides a shorter feedback loop.
https://docs-staging.datadoghq.com/tian.chu/verify-sls-filtering-rules/account_management/billing/serverless/
---
> Document the way for customers to quickly verify the filtering rules

- content/en/security_platform/explorer.md
"overview" got included in the content listing even though it's redundant. a bit difficult to explain here, but the error and fix are pretty clear if you look at the changed file.
https://docs-staging.datadoghq.com/cswatt/small-list-fix/security_platform/explorer/
> fixing table of contents thing

- content/en/security_platform/cloud_workload_security/getting_started.md
- content/en/serverless/_index.md
addin blog links to relevant pages
https://docs-staging.datadoghq.com/cswatt/blog-links/security_platform/cloud_workload_security/getting_started
https://docs-staging.datadoghq.com/cswatt/blog-links/serverless
> adding blog links

- content/en/tracing/setup_overview/setup/dotnet-core.md
- content/en/tracing/setup_overview/setup/dotnet-framework.md
Removes the DD_TRACE_METHODS documentation, which is a recently added feature in the .NET Tracer
We are putting the feature through more rigorous testing and don't want to promote its usage via the public docs for the moment.
...
The preview branch hasn't been generated but this can be merged as soon as a Documentation team member signs off on it. The engineering team agrees that this should be removed for now.
---
> APM > .NET > DD_TRACE_METHODS documentation update

- content/en/logs/guide/commonly-used-log-processing-rules.md
transifex editor noted that the french version of this page specifically says "numéros de sécurité social américains," since the french NIRPP is also common referred to as un numéro de sécurité social. 
we should also disambiguate in english.
https://docs-staging.datadoghq.com/cswatt/us-transifex/logs/guide/commonly-used-log-processing-rules/#social-security-numbers
---
> adding disambiguation for transifex

- content/en/continuous_integration/troubleshooting.md
This PR updates the docs about how we calculate the wall time in CI App when there are several jobs reporting tests in the same pipeline.
https://docs-staging.datadoghq.com/drodriguezhdez/wall_time_docs_gha/continuous_integration/troubleshooting/#how-wall-time-is-calculated
---
> [CIAPP] Update docs about how we calculate the wall time in CI App

- content/en/monitors/guide/monitor_api_options.md
Update pages under "Monitors" for the deprecation of the admin permission.
Users need the "Org Management" permission to do administrator tasks now, since the "admin" permission is being deprecated.
https://docs-staging.datadoghq.com/uchen/admin-monitors/monitors/guide/monitor_api_options/
https://docs-staging.datadoghq.com/uchen/admin-monitors/monitors/notify/
---
> Update monitors pages for deprecation of admin permission

- content/en/developers/dogstatsd/_index.md
Remove the word "as default" from https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent#how-it-works 
"as default" seems to suggest that it is configurable, but I think there is no configurations for it.
---
> Remove "as default" from DogStatsD How it works

- content/en/continuous_integration/guides/flaky_test_management.md
- content/en/continuous_integration/guides/rum_integration.md
- content/ja/continuous_integration/guides/flaky_test_management.md
converting some `aliases` frontmatter objects to be array instead of str.
issue that was found when translating one of these files.    
these aren't broken now as Hugo seems to accept a string also, but for uniformity i'm changing these to be arrays.
pages redirect normally based on the alias
- https://docs-staging.datadoghq.com/brian.deutsch/alias-array/continuous_integration/guides/find_flaky_tests/
- https://docs-staging.datadoghq.com/brian.deutsch/alias-array/ja/continuous_integration/guides/find_flaky_tests/
removed alias from this page as it was referencing itself, nothing should have changed here
- https://docs-staging.datadoghq.com/brian.deutsch/alias-array/continuous_integration/guides/rum_integration/
---
> convert alias fm to array

- content/en/tracing/profiler/connect_traces_and_profiles.md
The feature is no longer off by default so we can remove that sentence.
---
> profiler: remove incorrect line about Hotspots being off by default

- content/en/account_management/rbac/_index.md
Replaces the erroneous word "delete" with the correct word, "clone".
noticed a mistake
https://docs-staging.datadoghq.com/uchen/delete-to-clone/account_management/rbac/?tab=datadogapplication
---
> Fix a silly copy-paste mistake

- content/en/tracing/profiler/profiler_troubleshooting.md
The previous URL ["_profilesIngestionEndpoint_url"]="https://intake.profile.datadoghq.com/v1/input", was for sending profiles directly to the backend however this is not supported so the correct URL would be ["_profilesIngestionEndpoint_url"]="http://127.0.0.1:8126/profiling/v1/input" where the profiles would be sent to the Agent.
This will update the Ingestion URL to be the Agent URL as opposed to the backend URL that was previously there.
[Slack thread](https://dd.slack.com/archives/C019FJ8Q2QJ/p1647613653607099?thread_ts=1647550452.010119&cid=C019FJ8Q2QJ) where there was confusion about what the expected URL should be, and that it should be the Agent URL instead
https://a.cl.ly/jkuvL7dj [Slack link](https://dd.slack.com/archives/C019FJ8Q2QJ/p1647592772261219?thread_ts=1647550452.010119& …
> Update the endpoint ingestion URL

- content/en/agent/guide/network.md
Regionalize logs endpoint sections so that TCP endpoints are not shown for US3, US5, and Gov (not supported for those regions).
Also alphabetized the first part of the "Destinations" section.
DOCS-3167
https://docs-staging.datadoghq.com/may/regionalize-tcp-logs-endpoint/agent/guide/network/
---
> [DOCS-3167] Regionalize logs endpoint sections

- content/en/dashboards/functions/rollup.md
A customer wanted us to make it clear in this table/earlier in the page that avg is the default enforced interval. 
Also updated some link text to be more specific for the blog post.
Customer request
https://docs-staging.datadoghq.com/jorie/DOCS-3290/dashboards/functions/rollup/
---
> (DOCS-3290) make default enforced interval more clear

- package.json
- yarn.lock
bumps `datadog-ci` package version
dependabot identified a critical vulnerability in `url-parse`, a dependency of the previous `datadog-ci` version (thru `dd-trace`).   https://github.com/DataDog/documentation/security/dependabot/41
- nothing on the preview site should be affected: https://docs-staging.datadoghq.com/brian.deutsch/package-bump/
- source maps upload job ran successfully: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/126975924
---
> Bumps `datadog-ci` package

- content/en/tracing/setup_overview/compatibility_requirements/ruby.md
Updates to ruby tracing compatibility. 
https://docs-staging.datadoghq.com/kaylyn/ruby-compatibility/tracing/setup_overview/compatibility_requirements/ruby
---
> updates ruby tracing compatibility page

- .gitignore
- Makefile
- config/_default/menus/menus.en.yaml
- content/en/synthetics/cicd_integrations/_index.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Adds single sourcing logic for CircleCI Orb documentation. 
DOCS-3296
https://docs-staging.datadoghq.com/alai97/single-sourcing-ci-orb-docs/synthetics/cicd_integrations/circleci_orb/
Remember to add single sourcing logic to the `pull_config.yaml` file before merging! 
---
> DOCS-3296 Adds the Synthetics CircleCI Orb README into Documentation

- content/en/continuous_integration/setup_pipelines/jenkins.md
This PR adds a disclaimer about UDS support in the Jenkins plugin for CI Visibility
https://docs-staging.datadoghq.com/drodriguezhdez/jenkins_uds_limitation/continuous_integration/setup_pipelines/jenkins/?tab=usingui
---
> [CIAPP] Add a disclaimer about UDS support in the Jenkins plugin for CI Visibility

- content/en/continuous_integration/setup_pipelines/github.md
Add instructions on how to disable the GitHub Actions CI Visibility integration
The process is not obvious so customers have been having doubts on how to do this.
https://docs-staging.datadoghq.com/carlos.gonzalez/add-gha-disable-instructions/continuous_integration/setup_pipelines/github/#disabling-github-actions-tracing
---
> Explain how to disable GitHub Actions CI Viz integration

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
updates default branch name for `dd-sdk-ios`, `dd-sdk-reactnative`, `dd-sdk-android` entries in pull config.
the default branch changed for `dd-sdk-ios`, `dd-sdk-reactnative`, `dd-sdk-android` repos so the data we pull is out of date.   
caused a build error here: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/127691306
https://docs-staging.datadoghq.com/brian.deutsch/repo-fix/
---
> updates default branch name for `dd-sdk-ios` in pull config

- Makefile
> Fix Ruby and Python examples

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
> Docs Build Fix: Revert Default Branches

- content/en/tracing/setup_overview/compatibility_requirements/python.md
Update documented aiohttp support
The aiohttp integration has been updated https://github.com/DataDog/dd-trace-py/pull/3362
PR on hold until the upstream PR is merged and released.
---
> tracing(python): update aiohttp support

- content/en/tracing/setup_overview/setup/dotnet-core.md
- content/en/tracing/setup_overview/setup/dotnet-framework.md
Restore the `DD_TRACE_METHODS` configuration documentation for the .NET Tracer 2.6.0 release now that it is stable.
The .NET Tracer just made a 2.6.0 release that improves usage of the `DD_TRACE_METHODS` configuration.
https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-trace-methods-restore/tracing/setup_overview/setup/dotnet-framework?tab=windows#automatic-instrumentation-optional-configuration
https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-trace-methods-restore/tracing/setup_overview/setup/dotnet-core?tab=windows#automatic-instrumentation-optional-configuration
The wording has previously been approved by Docs and Engineering (before being retracted due to feature bugs) so I hope this can be merged right away, now that the feature is ready for public consumption.
---
> APM > .NET > Restore DD_TRACE_METHODS documentation

- content/en/synthetics/private_locations/_index.md
Adds instructions for OpenShift users to run private locations with anyuid SCC.
DOCS-1188
https://docs-staging.datadoghq.com/alai97/private-locations-kubernetes-openshift-specification/synthetics/private_locations/?tab=kubernetesdeployment#install-your-private-location
---
> DOCS-1188 Run Synthetic Tests from Private Locations Edit

- content/en/continuous_integration/setup_tests/dotnet.md
Adds a new section for configuring Agentless mode for .NET in CI Visibility mode.
There's a new feature to allow users to send test results without installing the Datadog agent, this PR adds the instructions to enable this feature in .NET
https://docs-staging.datadoghq.com/tony/ciapp-dotnet-agentless/continuous_integration/setup_tests/dotnet/#prerequisites
https://docs-staging.datadoghq.com/tony/ciapp-dotnet-agentless/continuous_integration/setup_tests/dotnet/#agentless-beta
---
> CI Visibility - dotnet agentless beta documentation

- config/_default/menus/menus.en.yaml
- content/en/database_monitoring/guide/_index.md
- content/en/database_monitoring/guide/heroku-postgres.md
Signed-off-by: Ara Pulido <ara.pulido@datadoghq.com>
It creates a new DB Monitoring guide section, and adds a Heroku Postgres set up guide.
https://docs-staging.datadoghq.com/ara.pulido/heroku_db_guide/database_monitoring/guide/
---
> Add Heroku Postgres DB monitoring guide

- content/en/serverless/libraries_integrations/extension.md
Fixes log filtering regex pattern.
reported by johanan lai
https://docs-staging.datadoghq.com/cswatt/serverless-log-filtering/serverless/libraries_integrations/extension/#log-collection
---
> DOCS-3305 correct log filtering regex

- content/en/getting_started/tagging/_index.md
Removing an unnecessary statement because it was causing confusion according to hotjar.
https://docs-staging.datadoghq.com/cswatt/key-value-tags/getting_started/tagging
> DOCS-3312 tagging getting started - key:value clarity

- content/en/monitors/service_level_objectives/metric.md
Updates the metric-based SLO docs to include info about Threshold Queries.
Threshold Queries recently GA'd
https://docs-staging.datadoghq.com/markazerdd/threshold-queries-slos/monitors/service_level_objectives/metric/#define-queries
---
> Add info about Threshold Queries to Metric-based SLOs

- content/en/logs/explorer/facets.md
Removes two facets incorrectly listed as OOTB facets. 
https://docs-staging.datadoghq.com/usman.khan/ootb_facets/logs/explorer/facets/#out-of-the-box-facets
---
> Remove incorrectly listed "OOTB" facets

- content/en/agent/vector_aggregation.md
Add doc for https://github.com/DataDog/datadog-agent/pull/10860
Keep doc up to date, user experience consistency W.R.T. Vector integration.
https://docs-staging.datadoghq.com/prognant/update-vector-aggregation/agent/vector_aggregation/
To be merged after agent release 7.35.0.
> [Agent] Vector aggregation update with new config key

- content/en/metrics/type_modifiers.md
We've introduced weighted to remove potential double counting that can be seen for  gauge metrics
We're releasing docs on the new .weighted modifier() that properly accounts for short-lived tags when summing gauges
---
> Add weighted modifier to modifiers doc

- content/en/tracing/setup_overview/compatibility_requirements/dotnet-core.md
- content/en/tracing/setup_overview/compatibility_requirements/dotnet-framework.md
Updates .NET Runtime policy in accordance to https://github.com/DataDog/architecture/pull/992
Make it straightforward for customers to know what versions we do support.
https://docs-staging.datadoghq.com/pierre/net-runtime-policy/tracing/setup_overview/compatibility_requirements/dotnet-core
---
> Update APM .NET runtime policy

- content/en/tracing/profiler/enabling/nodejs.md
Node.js profiler is GA. The banner should be removed now.
> Remove Node.js profiler public beta banner

- content/en/logs/log_configuration/archives.md
Remove principal parameter in IAM policy. 
IAM policies do not support the principal parameter. The [previous text](https://github.com/DataDog/documentation/blob/6fe5e0637797836bb0d2b56293d1e7dcb98854ed/content/en/logs/log_configuration/archives.md?plain=1#L119) implies you should add the permission statements to the IAM policies attached to the role, which is not possible.
---
> Remove principal parameter in IAM policy

- content/en/database_monitoring/setup_mysql/selfhosted.md
Replace `performance_schema` with `performance_schema_max_sql_text_length`.
DOCS-3319
https://docs-staging.datadoghq.com/may/dbm-replace-performance-schema/database_monitoring/setup_mysql/selfhosted/
---
> [DOCS-3319] Replace performance_schema with performance_schema_max_sql_text_length

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
`service` seems to be a required field to tie RUM to APM traces but this doesn't seem to be documented yet
adds documentation around the `service` field for connecting RUM to APM traces
confusion around why I wasn't seeing traces from client requests by following the doc
---
> [DOCS-3376] Connect RUM and Traces Edits

- content/en/serverless/azure_app_services.md
Fix support of AAS Functions for NET6
https://docs-staging.datadoghq.com/pierre/apm-net6-functions/serverless/azure_app_services?tab=net
---
> [APM] .NET 6 is supported for functions

- content/en/metrics/types.md
- content/fr/developers/metrics/types.md
- content/ja/developers/metrics/types.md
- content/ja/metrics/types.md
This PR fixes a link in to the Python StatsD documentation. The documentation currently links to https://statsd.readthedocs.io/en/v3.2.1/types.html#sets, which is a page that does not exist anymore. The new page is https://statsd.readthedocs.io/en/v3.2.2/types.html#sets.
To remove the 404 when following links from the documentation.
---
> Fixed link to Python StatsD documentation about metric type Set

- content/en/real_user_monitoring/session_replay/_index.md
A lot of customers and SEs miss this important point, causing frustration.
Adds a third step to disabling Session Replay section of the document.
A customer is terribly unhappy because they were instructed to make the configuration change according to what's in the doc now, but due to an old SDK these configuration changes did not prevent them from being charged the higher replay rate. I see multiple tickets dealing with this problem.
https://docs-staging.datadoghq.com/KateYoak-patch-1/real_user_monitoring/session_replay/#how-do-you-disable-session-replay (I get a 404, sorry if I did something wrong.)
---
- [ x] Review the changed files.
> disable Session Replay document correction

- content/en/metrics/dogstatsd_metrics_submission.md
java missing from CODE EXAMPLES - "Emit a SET metric-stored as a GAUGE metric-to Datadog."
Added Java to programming lang wrapper - set metric-stored as a gauge
Missing from documentation options
---
> Update dogstatsd_metrics_submission.md code examples

- content/en/security_platform/application_security/getting_started/php.md
- content/en/security_platform/application_security/troubleshooting.md
This PR updates the PHP appsec troubleshooting and installation instructions, which are currently out of date.
Keep the instructions up to date.
https://docs-staging.datadoghq.com/anilm3/php-docs-update/security_platform/application_security/getting_started/php/?tab=dockercli
https://docs-staging.datadoghq.com/anilm3/php-docs-update/security_platform/application_security/troubleshooting
---
> Update PHP AppSec documentation

- content/en/agent/kubernetes/integrations.md
Adds missing colon to integrations.md for Redis conf yaml section. 
---
> add missing colon to integrations yaml file for Kubernetes

- .gitlab-ci.yml
In preparation for more translation updates, this change updates the Gitlab config so that it points to the `master` branch of `corp-ci`, where a new helper function has been added.
https://datadoghq.atlassian.net/browse/WEB-1247
No frontend is impacted.
---
> Point CI image to default branch to include new helper function

- content/en/database_monitoring/setup_postgres/gcsql.md
As per [the docs](https://cloud.google.com/sql/docs/postgres/flags), the approved values for `pg_stat_statements.track` are `none | top | all`.
Fix incorrect example value. 
https://docs-staging.datadoghq.com/djova/gcp-update-db-setting-value
---
> Fix incorrect `pg_stat_statements.track` value

- content/en/logs/log_configuration/archives.md
Makes the fact that an App Registration is still required for an Azure Blob Archive (EVEN IN US3) more obvious.
Customer complained about setting this up - it was not obvious for them and required a support ticket.
---
> Update to make the app registration more obvious

- content/en/monitors/notify/_index.md
This PR clarifies that all users have read permissions on all monitors.
https://docs-staging.datadoghq.com/margot.lepizzera/monitor_read_permissions/monitors/notify/#notify-your-team
---
> Document that all users have read permissions on all monitors

- content/en/agent/basic_agent_usage/redhat.md
On `initctl`-based systems: `sudo initctl start/stop/restart/status datadog-agent`
I worked with a customer where the command needed to be: sudo initctl start datadog-agent
in order for the trace agent and the process agent to also start properly on Red Hat Linux 6 ( 6.10 specifically )
So adding the comment:
sudo initctl start/stop/restart/status datadog-agent
Took a while during a PoV to solve this problem
---
> added initctl comment. some Linux 6 systems use initctl instead of systemctl

- content/en/agent/basic_agent_usage/redhat.md
- content/fr/agent/basic_agent_usage/redhat.md
- content/ja/agent/basic_agent_usage/redhat.md
fixed end of tabs so this comment shows for all agents
Makes it show the comments about systemctl and initctl for all versions of the agent
(moved where the tabs markers end)
This used to only show for 'Agent 5' it applies to all versions of the agent. 
---
> fixed end of tabs so that comments about systemctl initctl show all the time (for all languages)

- content/en/dashboards/widgets/service_summary.md
Just a note to make the customer's journey more clear.
It is so easy to miss that the Resources checkbox turns up only when you select Large widget size. Stonkered me!
https://docs-staging.datadoghq.com/KateYoak-patch-1/dashboards/widgets/service_summary/#pagetitle
---
> Include an edge case for Service Summary config

- local/bin/py/build/actions/integrations.py
allow pricing and setup content to build for integrations pages
docs builds broken as a result of updated integrations content from another repo
https://docs-staging.datadoghq.com/brian.deutsch/fix-integrations/
https://docs-staging.datadoghq.com/brian.deutsch/fix-integrations/integrations/rapdev-snmp-profiles/
---
> Temporarily disable validating integration content

- content/en/agent/guide/linux-agent-2022-key-rotation.md
Updates key rotation docs with information on Agent 7.35.1 release.
https://docs-staging.datadoghq.com/slavek.kabrda/signing-keys-7.35.1/agent/guide/linux-agent-2022-key-rotation/?tab=debianubuntu
---
> Update key rotation docs with information on Agent 7.35.1 release

- content/en/security/guide/tls_deprecation_1_2.md
Update the docs to say that page contains the instructions to use their SSL check API and it is not the check API itself.
https://docs-staging.datadoghq.com/albertvaka/fix-howmyssl-link/security/guide/tls_deprecation_1_2/
---
> Update instructions pointing to How's my SSL

- content/en/integrations/faq/snmp.md
Fix the outdated link in SNMP FAQ
https://github.com/DataDog/documentation/issues/12461
---
> Fix the outdated link in SNMP FAQ

- content/en/security/_index.md
As the directory structure security has no index but has a nested folder it conflicts with the `/security/` alias defined in `/data_security/` and ends up being a blank page.
This PR brings back `_index.md` an external redirects it to data_security
Blank page with title `Securities` instead of a redirect without this change
https://docs-staging.datadoghq.com/david.jones/security-redirect/security/
should go do `/data_security/`
---
> redirect security

- content/en/developers/marketplace/_index.md
Fixing a broken link and updating the language surrounding what types of offerings can use the media carousel.
https://docs-staging.datadoghq.com/anawishnoff/mktplace-media-carousel-patch/developers/marketplace/
---
> Updating media carousel requirements

- content/en/developers/guide/_index.md
Removes some tags that show up as text that looks like it hasn't actually been styled properly with CSS padding. And it looks like we're not using these tags on other guide indexes, especially since we seem to be breaking longer guide indexes out into categorized sections.... Anyway, this will make it prettier/less awful looking.
I am a mouse looking for cookies that are easy to eat
https://docs-staging.datadoghq.com/jorie/remove-tags-guides-index
---
> Remove tags from this guides index

- content/en/database_monitoring/_index.md
- layouts/partials/dbm/dbm-setup-mysql.html
- layouts/partials/dbm/dbm-setup-postgres.html
- layouts/partials/dbm/dbm-setup-sql-server.html
Adds SQL Server to the list of self-hosted available dbm options, and since we're referring to it as "self-hosted" in the body, updates the link texts to also be "self-hosted" with the hyphen instead of a space.
nitpicky nitpicking
https://docs-staging.datadoghq.com/jorie/fix-dbm-text/database_monitoring/
---
> Add sqlserver to list, make self-hosted usage consistent.

- content/en/tracing/visualization/_index.md
Fix link to adding span tags in the /tracing/visualization page
The previous link for span tags redirected to the custom instrumentation page, which is not very clear.
N/A
N/A
---
> Fix link to span tags in visualizations page

- content/en/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent.md
Open's otlp ingest port on the core agent, not the trace agent.
The otlp ingest port should be opened on the core agent, not the trace agent.
> Open OTLP ingest port on core agent rather than trace agent

- content/en/getting_started/logs/_index.md
Removes an outdated learning center link in Further Reading section. Added two valid courses.
The Learning Center link pointed me to a course that is no longer available to learners. Instead I found to relevant active courses for logs.
https://docs-staging.datadoghq.com/KateYoak/patch-1/getting_started/logs/
---
> Update Further Reading for Getting Started w Logs

- content/en/security_platform/application_security/setup_and_configure.md
Adds documentation about the obfuscator feature now build into the app sec libraries.
Documents a feature that will be part of our GA release.
https://docs-staging.datadoghq.com/robert/appsec-obfuscation/security_platform/application_security/setup_and_configure/
---
> Documentation for the obfuscator built into the app sec library

- content/en/continuous_integration/setup_tests/javascript.md
Adds a new section for configuring Agentless mode for Javascript in CI Visibility.
There's a new feature to allow users to send test results without installing the Datadog agent, this PR adds the instructions to enable this feature in Javascript.
https://docs-staging.datadoghq.com/juan-fernandez/add-agentless-instructions/continuous_integration/setup_tests/javascript/?tab=jest#agentless-beta
---
> [ci-visibility] Add Javascript Agentless Instructions

- content/en/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent.md
The `--set` command to open up the ports is currently in section `2. Set environment variables for the Agent` rather than section `3. Map the container ports (`4317` for gRPC or `4318` for HTTP) to the host port for the core Agent container.`
> Fix OTLP Ingest helm --set instructions

- content/en/logs/log_configuration/archives.md
Adds that Glacier Instant Retrieval is supported to our archive documentation.
Cutsomer occasionally ask if this is supprted since our documentation mentions we don't support Glacier.
Approved by log pm Anshum Garg in [this #support-logs thread](https://dd.slack.com/archives/C6QR6DXJ4/p1650655075092819?thread_ts=1650578423.153339&cid=C6QR6DXJ4)
Tested by Stephen Lechner (used to be a product solutions architect for logs, no longer works here) and noted internally [here](https://datadoghq.atlassian.net/wiki/spaces/TS/pages/348525510/Logs+Archives+FAQ+Troubleshooting#:~:text=And%20btw%2C%20our%20rehydration%20does%20support%20the%20%E2%80%9CGlacier%20Instant%20Retrieval%E2%80%9D%20class%20(since%20it%E2%80%99s%20got%20the%20%E2%80%9CGlacier%E2%80%9D%20word%20in%20it%20and%20since%20we%20don% …
> [doc] Include support of Glacier Instant Retrieval

- content/en/tracing/setup_overview/open_standards/otel_collector_datadog_exporter.md
Change `tags` setting to reflect the new `host_metadata` section from open-telemetry/opentelemetry-collector-contrib/pull/9100, available from v0.49.0
As documented in open-telemetry/opentelemetry-collector-contrib/issues/9099, the `tags` setting is deprecated and will eventually be removed in favor of the `host_metadata::tags` section.
---
> [OpenTelemetry Collector] Update example with new configuration

- content/en/monitors/create/types/event.md
Update the event monitor page to reflect the fact that all sites now use the new Events backend, with updated query syntax.
- Removes the site specific sections. All sites now use the Events Explorer backend.
- Made two small edits requested by Sacha: linking to the Events Explorer search syntax rather than Logs, and using a simpler example group for multi-alert.
Requested by Sacha on DOCS-3407
https://docs-staging.datadoghq.com/uchen/event-monitors/monitors/create/types/event/
---
> Event monitor uses event explorer for all sites

- content/en/security_platform/application_security/setup_and_configure.md
Documents how to add authenticated user info to spans so that ASM (and APM) analysis can include user info.
DOCS-3322
https://docs-staging.datadoghq.com/kari/docs-3322-asm-user-info/security_platform/application_security/setup_and_configure/#add-user-information-to-traces
---
> [DOCS-3322] Adding user info to traces for ASM

- content/en/logs/guide/enrichment-tables.md
Update the size
The size limit was changed and we were still referring to the old one.
https://docs-staging.datadoghq.com/nils/enrichment-tables-size-limit-update/logs/guide/enrichment-tables/?tab=manualupload#overview
---
> Change enrichment table size limit for uploads

- content/en/database_monitoring/setup_mysql/selfhosted.md
The parameter for enabling MySQL's performance_schema is incorrect. It should be:
`performance_schema = ON` instead of `performance_schema_max_sql_text_length = ON`
https://docs-staging.datadoghq.com/alex.barksdale/fix-mysql-docs
---
> dbm: Fix incorrect MySQL parameter for enabling performance_schema

- content/en/dashboards/widgets/heat_map.md
Updates the Event Overlays instructions for the heat map widget to use the new Event Explorer syntax. 
- Updates the table of examples. 
- Changes a link to go to the Event Explorer search syntax
- Minor wording fixes for problems I noticed while editing the page
The Event Explorer is now the system of record for Events in Datadog. All systems that rely on Events, including the heat map widget, now use the Event Explorer search syntax rather than the older Event Stream syntax.
Requested by a support engineer via Slack.
https://docs-staging.datadoghq.com/uchen/heat-map/dashboards/widgets/heat_map/
---
> Update heat map widget event overlays instructions for Event Explorer

- content/en/tracing/setup_overview/custom_instrumentation/java.md
Adds missing imports used in Java examples
Certain missing imports are hard to find since the library to be used is also not mentioned. Saves time for future users.
N/A
N/A
---
> Add missing java imports for custom instrumentation

- content/en/tracing/troubleshooting/agent_rate_limits.md
Document `apm_config.max_memory`.
`apm_config.max_memory` is only documented the [config_template.yaml](https://github.com/DataDog/datadog-agent/blob/9f8ee2e2c489eed9b4a47b1f9b704bb94d21939d/pkg/config/config_template.yaml#L1078-L1085).
---
> Add Max Memory limit section for trace-agent

- content/en/integrations/kubernetes_state_core.md
Document backwards incompatible `kube_job` tag in KSM core
https://docs-staging.datadoghq.com/juliogreff/ksm-job/integrations/kubernetes_state_core/
---
> Document backwards incompatible `kube_job` tag in KSM core

- content/en/continuous_integration/_index.md
- content/en/synthetics/cicd_integrations/_index.md
- content/en/synthetics/cicd_integrations/configuration.md
I added the banner to the 2 landing pages and the config page for
synthetics. The CI Visibility config pages didn't seem like they needed it
as much.
https://docs-staging.datadoghq.com/heston/DOCS-2988/continuous_integration/
https://docs-staging.datadoghq.com/heston/DOCS-2988/synthetics/cicd_integrations/
https://docs-staging.datadoghq.com/heston/DOCS-2988/synthetics/cicd_integrations/configuration
---
> (DOCS-2988) Add cross-link banner for CI Vis and Synthetics

- content/en/network_monitoring/performance/setup.md
Fixes an incorrect link to the NPM DNS docs 
It's currently the wrong link :(
https://docs-staging.datadoghq.com/stephen.pinkerton/fix-npm-docs-link/network_monitoring/performance/setup/
> Fix link to DNS docs

- content/en/agent/kubernetes/integrations.md
Adds a missing link target.
Support Engineer Mohammad Islam noticed this error. I examined the doc and concluded that the link target was missing. I added the missing link target and reordered the others on the Helm tab. Also fixed up some nearby wording to conform to our style guide.
DOCS-3417
https://docs-staging.datadoghq.com/uchen/short-image/agent/kubernetes/integrations/?tab=helm
---
> Fix the autodiscovery container link

- content/en/developers/guide/dogwrap.md
Adds a note and adjusts the example command for the EU region.
https://docs-staging.datadoghq.com/heston/DOCS-1917/developers/guide/dogwrap/
---
> Add  option to dogwrap command for EU

- content/en/agent/kubernetes/control_plane.md
Fixes the link to the AWS EKS control plane monitoring documentation.
[This link](https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane.html#monitor-control-plane-metrics) leads the reader to a dead-end. Instead, [this link](https://aws.github.io/aws-eks-best-practices/reliability/docs/controlplane/#monitor-control-plane-metrics) should be used.
https://docs-staging.datadoghq.com/codyborders/codyborders-patch-1/agent/kubernetes/control_plane/
---
> Fix link to AWS EKS control plane docs

- content/en/monitors/notify/variables.md
This PR adapts the note related to the usage of template variables for F&F monitors now that this feature is supported.
https://docs-staging.datadoghq.com/drodriguezhdez/update_docs_fnf_template_variables/monitors/notify/variables/?tab=is_alert
---
> [Alerting] Update template variables for F&F monitors

- content/en/agent/vector_aggregation.md
Metrics should be sent to `datadog_metrics` not `datadog_logs`.
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
> Fix copy/paste error in Vector config for Datadog Agent aggregation

- content/en/real_user_monitoring/guide/send-rum-custom-actions.md
This PR shows an explicit import in a code snippet that was previously missing.
From an initial read through of the docs it wasn't clear what `DD_RUM` was or where it came from.  Poking around in the TS types it seems this was actually `datadogRum` from '@datadog/browser-rum'
I'm on a team using DD so I don't believe I have access to this.
N/A
---
> [DOCS-3408] Clarify where DD_RUM.addAction comes from

- content/en/monitors/guide/monitor_api_options.md
Documents the limits of the `timeout_h` option for Monitors to mirror what the [API documentation](https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor) already displays for `timeout_h`.
https://docs-staging.datadoghq.com/daljeet/timeout_h_doc_fix/monitors/guide/monitor_api_options/
---
> Dcument limits of timeout_h option

- content/en/tracing/guide/trace_ingestion_volume_control.md
- content/en/tracing/trace_ingestion/mechanisms.md
- content/ja/tracing/guide/trace_ingestion_volume_control.md
- content/ja/tracing/trace_ingestion/mechanisms.md
Fixes missing link.
The links to the head based sampling section of the ingestion mechanisms page were incorrect.
---
> fix head-based-default-mechanism links

- content/en/continuous_integration/setup_tests/javascript.md
Fix instructions when using `jest@28`
Keep up to date with the latest `jest` release.
https://docs-staging.datadoghq.com/juan-fernandez/update-jest-instructions/continuous_integration/setup_tests/javascript/?tab=jest
---
> [ci-visibility] Update `jest` instructions for `jest@28`

- content/en/tracing/setup_overview/setup/dotnet-core.md
- content/en/tracing/setup_overview/setup/dotnet-framework.md
Fixes the config value to use to rely on W3C headers
https://docs-staging.datadoghq.com/pierre/fix-b3/tracing/setup_overview/setup/dotnet-core?tab=windows
---
> [Tracer][W3C] Fix configuration know to use

- content/en/agent/guide/linux-agent-2022-key-rotation.md
On the section where we list the errors, remove OS tabs and add more errors so it shows up more often when searching for them.
SEO.
https://docs-staging.datadoghq.com/albertvaka/key-rotation-seo/agent/guide/linux-agent-2022-key-rotation
> Key rotation docs: improve SEO by listing more errors

- content/en/tracing/profiler/_index.md
Adds default retention info to profiler overview page, adds link to retention page
request from support
https://docs-staging.datadoghq.com/kari-profile-retention-info/tracing/profiler/
---
> Increase visibility of profile retention info

- content/en/security_platform/security_signal_management/_index.md
The security signal side panel now supports assigning users to signals for CWS and Cloud SIEM. Added directions to this.
---
> User assignee instructions

- config/_default/menus/menus.en.yaml
- content/en/account_management/org_settings/custom_landing.md
Add a new page to document how to set a custom landing page for an org. Add the page to the left menu under Org Settings.
https://datadoghq.atlassian.net/browse/DOCS-3328
Feature is going GA this week.
https://docs-staging.datadoghq.com/uchen/custom-landing/account_management/org_settings/custom_landing/
A screen recording of setting and unsetting a custom landing page can be found on Slack in the #org-configs channel. Here is a direct link: https://dd.enterprise.slack.com/files/U02SY76473J/F03BT2EF5RT/screen_recording_2022-04-12_at_12.50.20_pm.mov
---
> Add custom landing page documentation

- content/en/tracing/profiler/enabling/dotnet.md
Add a `warning note` to inform customers to avoid setting environment variables at machine-level.
We had customers lately that reported a huge overhead (CPU and memory) incurred by the profiler. After investigating, we discovered that they set the required environment variables at machine-level. This is not recommended and should be avoid.
https://docs-staging.datadoghq.com/gleocadie/add-warning-for-dotnet-profiler-for-global-configuration/tracing/profiler/enabling/dotnet/?tab=internetinformationservicesiis
---
> Profiler .NET - Add an explicit comment on "configuring environment variables at machine level

- content/en/agent/vector_aggregation.md
fixed typo flagged by a customer. `mutiple` fixed to `multiple`
---
> Typo fix: `mutiple` fixed to `multiple`

- content/en/security_platform/application_security/setup_and_configure.md
Add 3.0 and 3.1 + simplify as range instead of listing each version.
Incorrect list
https://docs-staging.datadoghq.com/fix-ruby-supported-versions/documentation/content/en/security_platform/application_security/setup_and_configure
---
> Fix Ruby supported versions for AppSec

- content/en/tracing/profiler/enabling/ruby.md
- content/en/tracing/profiler/profiler_troubleshooting.md
- content/en/tracing/setup_overview/_index.md
* Update list of languages that Profiler is available for
* Remove references to Windows and macOS from Ruby profiler docs
* Update Ruby SystemStackError profiler troubleshooting instructions
I was reviewing the Ruby profiler documentation and spotted these issues/improvements.
https://docs-staging.datadoghq.com/ivoanjo/profiling-doc-improvements
---
> Ruby profiler documentation improvements

- content/en/logs/guide/lambda-logs-collection-troubleshooting-guide.md
Remove the note about CW logs subscriptions.
[Amazon CloudWatch Logs now supports two subscription filters per log group](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-cloudwatch-logs-now-supports-two-subscription-filters-per-log-group/)
---
> Remove the note about CW logs subscription limitataion

- content/en/serverless/azure_app_services.md
Function support will be GA on May 1st. We should remove the language here suggesting it is still in beta.
Also generalizing "web app" to read just "app" in a few places where it could be referring to either a web app or a function app.
---
> Remove messaging about Functions being in Beta (DOCS-3439)

- content/en/developers/marketplace/_index.md
Cleans up the linking used in the marketplace developers page
broken/non-functioning links found by PM
https://docs-staging.datadoghq.com/kari/marketplace-dev-links/developers/marketplace
Don't make headings into links please!
---
> Fix Marketplace developer page links

- content/en/developers/dogstatsd/_index.md
- content/en/developers/dogstatsd/high_throughput.md
Remove outdated warnings.
As of 5.x (April 2021), DogStatsD-Ruby automatically starts a thread in
each sub-process, so this warning is no longer required.
---
> Remove outdated warnings about Ruby and processes

- content/en/security_platform/application_security/getting_started/dotnet.md
- content/en/security_platform/application_security/getting_started/go.md
- content/en/security_platform/application_security/getting_started/java.md
- content/en/security_platform/application_security/getting_started/nodejs.md
- content/en/security_platform/application_security/getting_started/php.md
- content/en/security_platform/application_security/getting_started/ruby.md
Add syntax highlighting to application security onboarding pages.
I noticed these were missing in these pages, so did a quick pass to
add them.
* https://docs-staging.datadoghq.com/ivoanjo/syntax-highlight-asm-onboarding/security_platform/application_security/getting_started/ruby/
* https://docs-staging.datadoghq.com/ivoanjo/syntax-highlight-asm-onboarding/security_platform/application_security/getting_started/java/
* https://docs-staging.datadoghq.com/ivoanjo/syntax-highlight-asm-onboarding/security_platform/application_security/getting_started/dotnet/
* https://docs-staging.datadoghq.com/ivoanjo/syntax-highlight-asm-onboarding/security_platform/application_security/getting_started/php/
* https://docs-staging.datadoghq.com/ivoanjo/syntax-highlight-asm-onboarding/security_platform/applicat …
> Add syntax highlighting to application security onboarding pages

- static/resources/python/api_query_data.py
This change fixes a typo in the Python API query snippet.
I was following the documentation on how to query metrics values and discovered a typo in the sample snippet.
https://docs-staging.datadoghq.com/gabriele.tornetta/fix-query-snippet/
---
> fix(python): typo in API query snippet

- .github/workflows/preview_link.yml
Adds a Github action that automatically posts a comment with preview (staging) links for all files changed or added on a PR, if they match the pattern `content/en/**.md`. 
This is how it looks:
When more commits are pushed to the same PR, the same comment gets updated with the new list of files.
If I'm not mistaken, this Action should only trigger for PRs from this same repo (not external PRs from forks) which are the ones that will have a preview on staging.
Not having to create the preview links manually, at least in most cases.
> [Github Action] Automatically generate preview links

- content/en/real_user_monitoring/browser/data_collected.md
Removes the `country_subdivision_iso_code` facet.
RUM Docs Slack
This PR is a batch update with https://github.com/DataDog/dd-sdk-ios/pull/838 and https://github.com/DataDog/dd-sdk-android/pull/921.
---
> DOCS-3465 Browser Data Collected Edit

- content/en/logs/log_configuration/archives.md
Moves the note about Azure app registrations being required for log archives
DOCS-3410
https://docs-staging.datadoghq.com/bryce/docs3410-update-azure-us3/logs/log_configuration/archives/?tab=awss3#route-your-logs-to-a-bucket
---
> (DOCS-3410) Move app registrations note

- .github/workflows/preview_link.yml
Users are confused when the preview links in the GitHub comment don't immediately work. They're only available once the `build_preview` check passes.
~~Note: I'm going to make a small edit to a markdown file to check if this is working. I'll back the change out when I'm done.~~
> Update preview_links action

- content/en/tracing/troubleshooting/tracer_debug_logs.md
With the 1.0 release of the Python tracer we stopped automatically calling logging.basic_config(), which means that we need customers to enable it via an envar in order for us to enable debug logging via an envar. 
The code snippet way of doing this is for customers who already have a logging configuration.
Just setting `DD_TRACE_DEBUG=true` for Python tracer >1.0 won't enable debug logging.
---
> zachg update how to set debug logging with Python tracer >1.0

- content/en/tracing/connect_logs_and_traces/opentelemetry.md
Updates the current docs to show customer's an example of how to convert their .NET OTEL trace & span IDs into the Datadog used format.
Customer reached out asking bout how they could do this.
https://docs-staging.datadoghq.com/maximo/otel-traces-logs-injection-dotnet/tracing/connect_logs_and_traces/opentelemetry/
> Adding Example On How to Inject OTEL IDs in .NET

- content/en/developers/dogstatsd/high_throughput.md
Document using multiple pipelines for DogStatsD server, this feature make the Agent use more CPU (if procs available) in order to process more packets, which leads to decrease the amount of packets drop.
New feature available in the Agent.
https://docs-staging.datadoghq.com/remeh/multi-pipelines/developers/dogstatsd/high_throughput/
---
> [dogstatsd] document using multiple pipelines to limit packets drop

- content/en/monitors/notify/downtimes.md
This PR adds a note for how to apply a Downtime to All groups of a multi-alert monitor
Zendesk ticket `803387`
---
> add note for All groups option

- content/en/serverless/installation/nodejs.md
> fixing a link that was breaking the thingy

- content/en/continuous_integration/setup_pipelines/codefresh.md
Remove the beta status warning from the Codefresh CI Visibility integration documentation page.
This is part of the plan to GA and start billing for codefresh.
https://docs-staging.datadoghq.com/carlos.gonzalez/codefresh-remove-no-billing-notice/continuous_integration/setup_pipelines/codefresh/
---
> [CIAPP] Remove beta warning from Codefresh docs

- package.json
- yarn.lock
This PR updates Hugo from version `0.96.0` to version `0.98.0`
See https://github.com/gohugoio/hugo/releases for changelog
Keeping hugo up to date and making use of new features
Various pages need spot checking that no new issues have crept in
https://docs-staging.datadoghq.com/david.jones/hugo-updatelatest/
---
> update to hugo 0.98.0

- .github/workflows/preview_link.yml
Fixes `line 4: fname: command not found` in workflow run
> Fix bash syntax in preview_link workflow

- .github/workflows/preview_link.yml
Removing the curly braces and using single quotes seems to fix the
conditional. I've added the workflow file to `paths` so it always runs
when we make modifications.
Also, I've switched out `jitterbit/get-changed-files` for
`tj-actions/changed-files`, which has an open issue to fix our renamed
files issue.
> Update preview links workflow conditional

- content/en/agent/cluster_agent/endpointschecks.md
Add Helm and Operator instructions for setting up Endpoint dispatching. For the most part this is "set this one line to enabled" and re-deploy.
As well as clean up some of the examples we use and provide a little more context towards the goal of endpoint checks.
Encourage use of Helm/Operator by adding these instructions and showing simplicity of enabling. As well as provide more context to users the goals of the Endpoint Check.
Preview:
- https://docs-staging.datadoghq.com/jack.davenport/endpoint_check/agent/cluster_agent/endpointschecks/?tab=helm
Current:
- https://docs.datadoghq.com/agent/cluster_agent/endpointschecks/
Similar / follow up to the adjustments made to the Cluster Checks doc:
- https://github.com/DataDog/documentation/pull/13441
---
> Add Helm/Operator instructions & Cleanup

- content/en/agent/proxy.md
Adjust some lines about ports on HAproxy and conf.yaml to NGINX.
Customers difficulty to configure reverse proxys.
That's just for US1 first, if it will be aproved need to do the same for other Datadog datacenters.
---
> Adjust URLs and Nginx conf.yaml

- content/en/monitors/create/types/audit_logs.md
This PR fixes the name of a variable supported in audit log monitors and changes a link.
User confusion
---
> Audit log monitor notifications - Fixes

- layouts/shortcodes/aws-permissions.md
Adds the permissions used by the AWS integration
DOCS-3392
https://docs-staging.datadoghq.com/bryce/add-aws-permissions/
---
> (DOCS-3392) Add shortcode for AWS permissions

- content/en/agent/guide/network.md
makes the database monitoring endpoints only show up for the regions that have database monitoring.
and moved it down so it looks less wonky
---
> only show dbm endpoint for regions that have it

- content/en/continuous_integration/setup_tests/javascript.md
Clarify compatibility with latest version of `jest`
Let users know that if they want `jest@28` support they have to use a specific version of `dd-trace`
https://docs-staging.datadoghq.com/juan-fernandez/clarify-jest-compatibility/continuous_integration/setup_tests/javascript/?tab=jest
---
> [ci-visibility] Clarify `jest` version compatibility 

- content/en/agent/docker/tag.md
- content/en/integrations/guide/source-code-integration.md
This PR updates the source code integration documentation page and the docker tags page to take into account the agent auto-discovering the `git.repository_url` tag. ([PR](https://github.com/DataDog/datadog-agent/pull/10966))
See agent version 7.35 release notes:
https://github.com/DataDog/datadog-agent/releases/tag/7.35.0
Up-to-date documentation.
N/A
---
> Update SCI documentation with latest agent information

- content/en/agent/kubernetes/apm.md
Add a warning message when using TCP for APM
https://docs-staging.datadoghq.com/yrobin/APM_HostPort_warning/agent/kubernetes/apm/
---
> Add hostPort warning in TCP approach

- layouts/shortcodes/aws-permissions.md
Adds a note about needing to attach the IAM policy to the IAM role for the Datadog integration. Also, minor edits to the description of the policy.
DOCS-3392
See pull/75777 in dogweb to view SME feedback which motivated this change.
---
> (DOCS-3392) Update instructions in shortcode

- content/en/serverless/azure_app_services.md
Updates the AAS extension docs page with links to the agentless logging introduced in #13907
We recently introduced a new logging capability in the .NET Tracer, and this update links to it from the Azure App Service docs page
https://docs-staging.datadoghq.com/zach.montoya/aas-application-logging/serverless/azure_app_services/?tab=net#application-logging
This requires #13907 to be merged first.
---
> Serverless > Azure App Services > Logging updates

- content/en/tracing/runtime_metrics/go.md
This clarifies the configuration of DogStatsD for use with runtime metrics in the Go tracer.
https://docs-staging.datadoghq.com/knusbaum/update-dogstatsd-doc/tracing/runtime_metrics/go
---
> tracing/runtime_metrics/go.md: clarify the configuration of dogstatsd including UDS.

- content/en/database_monitoring/setup_mysql/selfhosted.md
Reverts the changes made on PR [13660](https://github.com/DataDog/documentation/pull/13660)
A user tried to set up DBM, but it failed. I talked to the DBM Engineering team. Justin Iso investigated and determined that the PR 13660 introduced some bad configuration.
---
> Revert incorrect changes to DBM config variables

- content/en/synthetics/api_tests/dns_tests.md
- content/en/synthetics/api_tests/grpc_tests.md
- content/en/synthetics/api_tests/http_tests.md
- content/en/synthetics/api_tests/icmp_tests.md
- content/en/synthetics/api_tests/ssl_tests.md
- content/en/synthetics/api_tests/tcp_tests.md
- content/en/synthetics/api_tests/udp_tests.md
- content/en/synthetics/api_tests/websocket_tests.md
- content/en/synthetics/browser_tests/actions.md
- content/en/synthetics/multistep.md
Adds information describing test behavior when there is/is not a response body assertion.
DOCS-2890
https://docs-staging.datadoghq.com/alai97/synthetics-general-tests-assertions-response-size-note/synthetics/browser_tests/actions/#assertion/
https://docs-staging.datadoghq.com/alai97/synthetics-general-tests-assertions-response-size-note/synthetics/multistep/?tab=requestoptions#add-assertions/
---
> DOCS-2890 Synthetics API, Multistep, and Browser Tests Edit

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
Update the section for manually adding triggers to the Datadog Forwarder.
DOCS-3111
https://docs-staging.datadoghq.com/bryce/update-manual-triggers/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole#manually-set-up-triggers
Changes have been validated by a member of the serverless team.
> (DOCS-3111) Update manual trigger steps

- Makefile
We have all examples committed in repo now, we don't need the extrat
command anywhere.
---
> Remove last extract call for SDK examples

- content/en/continuous_integration/setup_tests/junit_upload.md
Document the current 250MiB junit report limit.
Currently reports that are larger than 250MiB may not be processed completely resulting in missing tests and/or logs.
---
> [CIAPP] Document junit upload limits

- content/en/continuous_integration/setup_tests/dotnet.md
The PR adds instructions to download the standalone version of the `dd-trace` CLI tool.
The APM tracer team started to release the standalone version of the tool, because CI Visibility uses the tool we update the documentation to give that option to customers.
---
> [CI Visibility] Add instructions to download standalone version of dd-trace

- layouts/security_rules/list.html
- local/bin/py/build/actions/security_rules.py
Hardcoded rules appear under their own group under Cloud SIem.
This works by processing rules with no source to be grouped together.
> Hardcoded rules can span several different log sources because they may not focus on a specific log source such as Cloudtrail or Apache. Instead they do not include a source
https://datadoghq.atlassian.net/browse/WEB-2367
See `Multi Log Sources`
https://docs-staging.datadoghq.com/david.jones/hardcoded/security_platform/default_rules/?q=#cat-cloud-siem
---
> WEB-2367 - hardcoded ootb rules

- translate.yaml
adds languages to legacy translation config before its phased out
To support further languages
https://datadoghq.atlassian.net/browse/WEB-2282
There is no change to the site
https://docs-staging.datadoghq.com/david.jones/translate-config-update/
---
> WEB-2282 - add languages to legacy config

- static/resources/yaml/datadog-agent-aks.yaml
- static/resources/yaml/datadog-agent-all-features.yaml
- static/resources/yaml/datadog-agent-apm.yaml
- static/resources/yaml/datadog-agent-logs-apm.yaml
- static/resources/yaml/datadog-agent-logs.yaml
- static/resources/yaml/datadog-agent-npm.yaml
- static/resources/yaml/datadog-agent-vanilla.yaml
- static/resources/yaml/datadog-agent-windows-all-features.yaml
- static/resources/yaml/datadog-agent-windows-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs.yaml
- static/resources/yaml/datadog-agent-windows-vanilla.yaml
Regenerate the sample docker manifests from the latest Helm chart version.
The Helm charts received some changes since last time we generated the sample manifests.
PR to regenerate the sample manifests in the `datadog-agent` repo: DataDog/datadog-agent#12039
---
> Regenerate the sample docker manifests from the latest Helm chart version

- content/en/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent.md
Adds a link about the OTLP Trace Ingestion blog post to the OTLP Ingestion doc.
Docs team Tuesday tasks.
---
> Add blog post link to OTLP ingest doc

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps datadog-lambda-js layer version to 78
---
> Bump datadog-lambda-js layer to version 78

- content/en/tracing/setup_overview/compatibility_requirements/go.md
- Customer wants the Fiber Framework in the Officially Supported Documentation.
Updates the GoLang Supported Frameworks list, adding our Fiber Tracer Library to the list
During a trial, the customer asked for the official documentation showing we support Fiber Framework on Golang.
Tracer Library is https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/gofiber/fiber.v2
---
> Adding Fiber Framework to the Documentation

- content/en/logs/log_configuration/parsing.md
Added note that makes it clear that integers must be sent into Grok Parser as strings. Grok Parser only works on strings.
Added note that made it clear that Grok Parser can only parse strings.
Logs backend eng and support folks reached out to product about customers being confused by not being able to parse ints with the Grok Parser. We want to make clear that it can parse numerical values, they just must be sent in as strings.
---
> Updated docs for parsing to make Grok Parser inputs more clear

- assets/scripts/components/platforms.js
Fix Javascript reference error for popper we are receiving.
This occurs when you are on mobile at `/agent/` and choose a platform. A popup appears but throws an error at the same time. Functionally you shouldn't see a difference between this pr and production as it still works despite the error.
reduce noise / fix js error
https://docs-staging.datadoghq.com/david.jones/popper-fix/agent/
---
> fix popper js error

- content/en/tracing/profiler/enabling/java.md
Adds a short recommendation to use the Datadog Profiler library with a LTS JDK version.
Non-LTS versions are not getting any new fixes backported and as such having users running on such versions results in weird bugs originating in JDK reported to Datadog.
---
> Add a recommendation to use LTS JDK versions

- content/en/real_user_monitoring/browser/modifying_data_and_context.md
Adds a sentence about adding multiple key-value pairs in calls to the Global Context API.
DOCS-3519
---
> DOCS-3519 Modifying Data and Context Edit

- content/en/serverless/configuration/_index.md
1. Document the support of dual shipping in serverless environment
2. Link to the existing dual shipping doc for instructions
3. Stop nesting certain trace and log configuration sections and bring them up to the TOC
4. Notes about lambda tags enrichment
5. Configure the Datadog Lambda extension for local testing
---
> Serverless configurations updates (dual shipping, lambda tags enrichment)

- content/en/tracing/runtime_metrics/nodejs.md
instructions on how to enable the runtime metrics are a bit confusing so I added tabs for Environment and In code similar to how we did it for profiling.
https://docs.datadoghq.com/tracing/profiler/enabling/nodejs/?tab=incode
---
> (Docs) Enable Nodejs Runtime Services Examples

- content/en/serverless/guide/datadog_forwarder_node.md
- content/en/serverless/guide/serverless_package_too_large.md
- content/en/serverless/installation/nodejs.md
Adds Node16 lambda runtime support to our documentation. It also removed Node10, which is no longer available from AWS.
We now support Node16
---
> Add Node16 runtime for lambda to docs

- content/en/database_monitoring/setup_mysql/troubleshooting.md
- content/en/database_monitoring/setup_postgres/troubleshooting.md
In the refactoring to have permanent links for database setup errors, we ended up duplicating the `Queries are missing explain plans` section. The content was mostly duplicate except for one additional entry in the postgres troubleshooting docs that I moved over to the permanentlink-compatible section.
We noticed that we had duplicate content.
---
> Fix duplicate explain plan section in troubleshooting docs

- content/en/getting_started/tagging/using_tags.md
Updates the Event search examples on the "Using Tags" getting started guide to use the new Event Explorer syntax. 
Reported by Solutions Engineer Ollie Harrison on https://datadoghq.atlassian.net/browse/DOCS-3520
---
> Add the event explorer search syntax to "Using Tags"

- content/en/real_user_monitoring/browser/data_collected.md
- content/en/real_user_monitoring/browser/monitoring_page_performance.md
- content/en/real_user_monitoring/browser/tracking_user_actions.md
Add detailed documentation on Page Activity and how to use the `excludedActivityUrls` initialization parameter.
We are introducing the new `excludedActivityUrls` initialization parameter, and we need to give more context, example and use cases on how to use it, since it's rather technical.
https://docs-staging.datadoghq.com/benoit/page-activity-documentation/real_user_monitoring/browser/monitoring_page_performance/#how-is-page-activity-calculated
---
> [RUMF-1262] add centralized documentation on page activity

- content/en/tracing/setup_overview/custom_instrumentation/go.md
There are some slanted quotes under the tracing custom_instrumentation documentations for go that won't compile properly if users directly copy/paste the code. Updates these slanted quotes to use straight quotes instead.
Makes it easier for users to directly copy/paste code.
---
> Update slanted quotes to straight ones under go custom_instrumentation

- content/en/agent/guide/can-i-set-up-the-dd-agent-mysql-check-on-my-google-cloudsql.md
https://docs.datadoghq.com/integrations/faq/can-i-set-up-the-dd-agent-mysql-check-on-my-google-cloudsql/ is broken too
---
> it was a double redirect

- content/en/integrations/guide/source-code-integration.md
Fix the wording of a sentence only mentioning the `git.commit.sha` tag while just above both tags were mentioned.
Fix SCI doc.
---
> Fix: Mention git.repository_url

- content/en/tracing/setup_overview/custom_instrumentation/dotnet.md
Fixes a minor typo in the environment variable mention here. 
---
> fix minor typo in environment var spec

- content/en/agent/kubernetes/installation.md
Specifies for the DaemonSet installation of the Agent (on Kubernetes) that the Cluster Agent Auth token should be at least 32 characters long.
* A shorter token will lead to an error message in the logs such as `Could not initialise the communication with the cluster agent: temporary failure in clusterAgentClient, will retry later: cluster agent authentication token length must be greater than 32, curently: 23`
* Lines up with other documentation specifying this requirement : 
* https://docs.datadoghq.com/agent/cluster_agent/commands/#cluster-agent-options : `DD_CLUSTER_AGENT_AUTH_TOKEN` ***32 characters long token that needs to be shared between the node Agent and the Datadog Cluster Agent.***
* https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=daemonset#secure-cluster-agent-to-ag …
> Adds the 32 characters requirement on the Cluster Agent Token

- content/en/monitors/create/types/composite.md
Add examples on how new_group_delay works for composite monitors
new group delay was not supported so far for composite monitors and was recently added. 
It's behaviour in case of conflict with child monitors needed to be explicit.
https://docs-staging.datadoghq.com/nils/new-group-delay-composite/monitors/create/types/composite
---
> add examples for new group delay and composite

- go.mod
- go.sum
hugo module changes update localStorage values to include a time-to-live
there should be no change visible on documentation
changes were made to modules to meet this request: https://datadoghq.atlassian.net/browse/WEB-2096
the documentation site should be unaffected - there are no references to locally stored values
this is a sync to bump the module version being consumed
https://docs-staging.datadoghq.com/brooklyne.finni/bump_mod_version/
---
> [WEB-2096]bump module version

- content/en/agent/kubernetes/installation.md
Fixes some incorrect link references in k8s docs. 
I clicked on a link for more information about monitoring the control plane, and ended up in the live containers overview page.
---
> Fixed a couple incorrect link references in k8s docs

- content/en/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent.md
deleting the warning section about being in beta version because it's release with agent 7.36
---
> Lutao / update otlp_ingest_in_the_agent.md

- content/en/synthetics/browser_tests/_index.md
The assertions link was sending users to the RBAC page, not the Browser Test Steps page.
#documentation Slack
---
> Browser Tests Edit

- content/en/real_user_monitoring/session_replay/_index.md
Renames billing plan from Session Replay to Browser Premium.
Slack
---
> Session Replay Edit

- content/en/security_platform/application_security/getting_started/ruby.md
- content/en/security_platform/application_security/setup_and_configure.md
Fixes some elements, and adds 1.1.0 features.
Upcoming ddtrace 1.1.0 for Ruby release.
Do not merge until 1.1.0 is released.
---
> Update docs for AppSec on Ruby 1.1.0

- content/en/database_monitoring/setup_mysql/azure.md
- content/en/database_monitoring/setup_mysql/gcsql.md
- content/en/database_monitoring/setup_postgres/azure.md
- content/en/database_monitoring/setup_postgres/gcsql.md
Adds config doc for new cloud related configs that were added to support proper DBM -> cloud resource linking for displaying metrics that are collected by DD crawlers like CPU, IO, memory, etc in the new DB list page 
Example doc from the [agent spec](https://github.com/DataDog/integrations-core/blob/master/postgres/assets/configuration/spec.yaml#L446-L474) 
---
> Add additional config documentation for cloud Azure/GCP cloud instances

- content/en/integrations/faq/troubleshooting-and-deep-dive-for-kafka.md
Match the Kafka context limitation to match our integration : 
https://github.com/DataDog/integrations-core/blob/c943a73bb72bfd23d2e9c20914650c90ca7eeef7/kafka_consumer/datadog_checks/kafka_consumer/kafka_consumer.py#L33
https://github.com/DataDog/integrations-core/blob/c943a73bb72bfd23d2e9c20914650c90ca7eeef7/kafka_consumer/datadog_checks/kafka_consumer/constants.py#L6
---
> Bumping Kafka max context to 500

- static/config/99datadog-windows.config
This is a config file that users with Windows nodes can use to
configure their Elastic Beanstalk environments. This accompanies a
separate PR that guides a user through the configuration steps.
> (DOCS-3460) Add hosted config file for Windows

- content/en/tracing/troubleshooting/agent_apm_metrics.md
Remove `datadog.trace_agent.receiver.traces_dropped` from [APM metrics sent by the Datadog Agent](https://docs.datadoghq.com/tracing/troubleshooting/agent_apm_metrics/)
`datadog.trace_agent.receiver.traces_dropped` has not been reported since https://github.com/DataDog/datadog-agent/pull/3738 was released. The metric was switched to `datadog.trace_agent.normalizer.traces_dropped`.
---
> Remove `datadog.trace_agent.receiver.traces_dropped`

- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/gcsql.md
- content/en/database_monitoring/setup_sql_server/rds.md
- content/en/database_monitoring/setup_sql_server/selfhosted.md
- layouts/shortcodes/dbm-sqlserver-before-you-begin.md
This makes the following changes: 
1. Updates SQLServer for RDS setup docs to correctly create the DD user without getting an error in the script. RDS does not allow even the root user to create users in the master database, and requires that this be done in the special `msdb` database. 
[RDS docs on creating a user](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.SQLServer.CommonDBATasks.CreateUser.html)
2. Removes official support for SQLServer 2012 on RDS. Amazon has deprecated this support (and requiring upgrades by end of year), and we can no longer provision any instances with this version so we not able to fully support it. Microsoft is EOL'ing support for this version by the end of the year.  
3. Fixes self-hosted and azure MI docs for versions that are older than …
> Update SQLServer RDS docs for DD user creation + remove support for 2012

- content/en/logs/log_configuration/archives.md
Adds that S3 Intelligent-Tiering is supported to our archive documentation.
Customer asked if we support this storage class (ticket `645331`).
S3 Intelligent-Tiering has been tested by Tim Molard (Product Management Intern) [here](https://datadoghq.atlassian.net/browse/FRLOGSS-1696?focusedCommentId=672303). 
---
> Include support of S3 Intelligent-Tiering

- content/en/monitors/create/configuration.md
Add a block to reflect that monitors are evaluated every minute
Monitor evaluation frequency is currently fixed but is now reflected in the UI and will soon be customisable. We therefore prepare the documentation to first better reflect the current behaviour and prepare the section so we can add all details about the customisation there once available. 
https://docs-staging.datadoghq.com/nils/monitor-evaluation-frequency/monitors/create/configuration/?tab=thresholdalert#evaluation-frequency
We can close https://github.com/DataDog/documentation/pull/13508 as it's a duplicate
---
> Update monitor configuration to reflect evaluation frequency

- content/en/tracing/connect_logs_and_traces/opentelemetry.md
Introduces a fix to the attributes necessary to enable correlation of logs using Serilog in .NET with the traces in Datadog.
As it is currently documented, the attributes do not enable the correlation.
None
---
> Fix attributes for log correlation in .NET

- content/en/agent/basic_agent_usage/_index.md
- content/en/agent/basic_agent_usage/deb.md
Because https://github.com/DataDog/datadog-agent/pull/11311 was merged, Agent 6.36.0/7.36.0 will drop Debian 7 support. This PR updates docs accordingly (it basically does for Debian exactly what https://github.com/DataDog/documentation/pull/12112 did for SUSE).
To be merged when 6.36.0/7.36.0 get released.
https://docs-staging.datadoghq.com/slavek.kabrda/debian-support-update/agent/basic_agent_usage/?tab=agentv6v7
https://docs-staging.datadoghq.com/slavek.kabrda/debian-support-update/agent/basic_agent_usage/deb/?tab=agentv6v7
---
> Update information about supported Debian versions

- content/en/serverless/installation/nodejs.md
Fix a mistake I probably made in the previous big doc refresh. The node installation instructions for serverless should use the layer version for Node instead of Python.
---
> Fix node layer version number

- content/en/tracing/setup_overview/compatibility_requirements/dotnet-framework.md
Fixes links to the Datadog Agent docs
The current docs do not render correctly.
https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-dd-agent-fix/tracing/setup_overview/compatibility_requirements/dotnet-framework/
N/A
---
> APM > .NET Framework > Fix Fix Datadog Agent links on the compatibility requirements page

- content/en/agent/proxy.md
The intake where we receive profiles has changed as per the network traffic documentation:
https://docs.datadoghq.com/agent/guide/network/?tab=agentv6v7
It used to be profile.agent.datadoghq.com while now it is intake.profile.datadoghq.com
Changes the intake link in the NGINX example configuration
The intake has changed.
---
> NGINX Example configuration profile intake.

- content/en/agent/kubernetes/distributions.md
Change documentation around `tlsVerify` on AKS.
Improve documentation.
---
> Add information about tlsVerify: false on AKS with new Agent versions

- local/bin/py/build/actions/integrations.py
All classifier tags are now moved under the `tile` key. We should be clear to stop looking under the old location! 
Completes the classifier_tag migration and removes dead code. 
---
> All classifier tags are moved, stop looking at old location

- content/en/continuous_integration/setup_pipelines/gitlab.md
Document how to enable collection of job logs in GitLab through the integration with CI Visibility.
This was added in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/74725 GitLab milestone 14.8.
https://docs-staging.datadoghq.com/adrian.lopezcalvo%2Fci-visibility-gitlab-logs
> [CIAPP] Add instructions to enable logs collection for gitlab

- content/en/events/guides/migrating_to_new_events_features.md
Explain that JSON events are automatically parsed in new event feature.
Some customers are seeing issue in v2 monitors because their JSON event is getting parsed automatically by Datadog and text search does not work for event attribute. (They need to manually add Facet for automatically parsed event attribute to make it work.) 
Need to clarify that JSON is parsed automatically like Logs document.
Logs document says "Datadog automatically parses JSON-formatted logs. When logs are not JSON-formatted, you can add value to your raw logs by sending them through a processing pipeline."
---
> Explain that JSON events are parsed

- content/en/synthetics/private_locations/_index.md
Shifts around the recommended method of installing private locations with status probes + updates the code snippets in the Additional Health Check Configurations section.
DOCS-3506
---
> DOCS-3506 Run Synthetic Tests from Private Locations Edits

- content/en/continuous_integration/setup_pipelines/github.md
Clarifies that GHES is not supported.
The working is a bit confusing as GitHub SaaS has Enterprise accounts. This improves the wording so it is clear that we do not support the self-hosted version.
---
> Clarify that GHES is not supported

- content/en/continuous_integration/setup_pipelines/github.md
Removes the warning box at the top of the page that says the integration is in beta.
---
> Remove beta notice from GitHub Actions integration

- content/en/logs/guide/how-to-set-up-only-logs.md
This adds backslashes to the shell example, to correctly escape its newlines.
I was using this documentation, and noticed the shell example did not correctly escape all newlines.
---
> Add backslashes to multiline shell example

- content/en/database_monitoring/setup_mysql/aurora.md
- content/en/database_monitoring/setup_mysql/gcsql.md
- content/en/database_monitoring/setup_mysql/rds.md
- content/en/database_monitoring/setup_mysql/selfhosted.md
- content/en/database_monitoring/setup_mysql/troubleshooting.md
Adds troubleshooting docs for MySQL query activity.
Added [docs](https://docs-staging.datadoghq.com/alex.barksdale/add-mysql-query-activity-troubleshooting/database_monitoring/setup_mysql/troubleshooting/#query-activity-is-missing)
---
> DBM-1360: Add MySQL query activity troubleshooting

- content/en/database_monitoring/setup_mysql/aurora.md
- content/en/database_monitoring/setup_mysql/gcsql.md
- content/en/database_monitoring/setup_mysql/rds.md
- content/en/database_monitoring/setup_mysql/selfhosted.md
- content/en/database_monitoring/setup_mysql/troubleshooting.md
Addresses a small nit in the docs. The runtime stored procedure now additionally enables `events_waits_current`, so this changes the following wording:
```
ability to enable `performance_schema.events_statements_*`
```
- Which indicates that we're only enabling `events_statements_*`
To:
```
ability to enable `performance_schema.events_*`
```
- Now inclusive of either `events_statements_*` or `events_waits_*`
---
> Improve DBM MySQL runtime setup consumer docs 

- data/partials/requests.yaml
Fixes an old link to where metrics used to live. It got missed because it lives in partials.
It actually 404's on staging previews...which is kinda weird. Otherwise I probably wouldn't have found it.
---
> Fix old link

- content/en/getting_started/agent/_index.md
Removes the "tags" from this whats next section at the end of this page. It's styled weirdly and the tags are not needed anyway. I removed these from another page a while back but forgot to go looking for other instances of it and came across this one.
This bothers me:
---
> Test changing tag to type in whats-next div

- content/en/agent/kubernetes/log.md
Volume name should be `pointerdir` instead of `pointdir`
Update Docs
---
> Documentation: Update container logs volume name

- content/en/account_management/billing/containers.md
explicitly saying that billing/metering GKE Autopilot is no different from billing/metering of GKE Standard. no actual numbers are mentioned.
> DOCS-3578 - add note about billing in GKE Autopilot

- content/en/infrastructure/livecontainers/configuration.md
It updates the compatibility matrix for live containers monitoring now that we collect new resources.
Also, reordered by name for clarity.
The matrix is outdated, we're missing resources collected by default for cluster agents >= 1.19.
Link to relevant PRs:
- https://github.com/DataDog/datadog-agent/pull/10856
- https://github.com/DataDog/helm-charts/pull/356
---
> [live containers] Update the compatibility matrix

- content/en/agent/proxy.md
Some integrations file contains the parameter use_agent_proxy instead of skip_proxy
---
> added the use_agent_proxy

- content/en/agent/docker/_index.md
See [DOCS-3530](https://datadoghq.atlassian.net/browse/DOCS-3530).
---
> (DOCS-3530) Add docker environment variable to Agent docs

- content/en/agent/kubernetes/integrations.md
- content/en/getting_started/containers/autodiscovery.md
Documents Autodiscovery Annotations v2, available when Agent 7.36 is released.
New feature implemented in https://github.com/DataDog/datadog-agent/pull/11274
https://docs-staging.datadoghq.com/juliogreff/adv2/getting_started/agent/autodiscovery/
https://docs-staging.datadoghq.com/juliogreff/adv2/agent/kubernetes/integrations/
Merge this after the release of Agent 7.36.
---
> Document AD annotations v2 (Agent 7.36+)

- content/en/account_management/billing/usage_metrics.md
This PR addresses a change to usage_metrics.md. New usage metrics added to the metrics list. 
datadog.estimated_usage.metrics.custom.by_tag, datadog.estimated_usage.metrics.custom.by_metric
datadog.estimated_usage.metrics.custom.ingested, datadog.estimated_usage.metrics.custom.ingested.by_tag, datadog.estimated_usage.metrics.custom.ingested.by_metric
Keeping our documentations up-to-date
---
> Updated table with new usage metrics under Custom Metrics

- content/en/database_monitoring/setup_postgres/rds.md
While integrating RDS Postgres instances, we need to add dbinstanceidentifier tag to add the correlation to the default OOTB dashboards.
Add the `dbinstanceidentifier` tags to the DBM on RDS configuration.
Information was lacking during trial process.  
---
> Adding dbinstanceidentifier into the configuration

- assets/scripts/components/async-loading.js
- assets/scripts/components/codetabs.js
- assets/scripts/datadog-docs.js
- assets/styles/pages/_global.scss
- layouts/shortcodes/tabs.html
- Updates `code-tabs` shortcode style to be more consistent with `code-lang-tabs`.
- Refactors related jQuery code to vanilla JS.
https://datadoghq.atlassian.net/browse/WEB-2260
https://docs-staging.datadoghq.com/brian.deutsch/tab-style-update/tracing/setup_overview/setup/dotnet-framework/
- when no `tab` query param is present in URL, the first tab in each code tabs should be selected.  a `tab` query parameter should be appended to the URL with the title of the first tab on the page.  i.e. `windows` in this example: https://docs-staging.datadoghq.com/brian.deutsch/tab-style-update/tracing/setup_overview/setup/dotnet-framework
- when a `tab` query param IS present, those tabs should be selected on page load (`response` tabs should be active here): …
> [WEB-2260] Code tabs refactor

- content/en/real_user_monitoring/explorer/watchdog_insights.md
Removes an outdated beta notice on the Watchdog Insights for RUM page. Watchdog Insights has been GA for months.
Noticed an outdated beta notice. Confirmed with the PM, Samir, that the product is GA.
---
> Remove beta message from Watchdog Insights for RUM page

- content/en/monitors/create/types/event.md
Update multi-alert group limit for Event Monitor.
According to the event migration document, limit is up to 1000 instead of 100.
https://docs.datadoghq.com/events/guides/migrating_to_new_events_features/#you-can-group-by-only-up-to-4-facets
> One facet results in a limit of 1000 top values.
> Two facets results in a limit of 30 top values per facet (at most 900 groups)
> Three facets results in a limit of 10 top values per facet (at most 1000 groups)
> Four facets results in a limit of 5 top values per group (at most 625 groups)
> 
---
>  Update multi-alert group limit

- content/en/agent/kubernetes/prometheus.md
Adds DaemonSet configuration when using `prometheusScrape` option, i.e. automatic Prometheus pods scraping
Support
Configuration missing despite being supported in DaemonSet
`serviceEndpoints: true` added in the Helm configuration (and DaemonSet) to align with the quote in the article : 
> It also instructs the Datadog Cluster Agent (if enabled) to detect the services that have native Prometheus annotations and generate corresponding OpenMetrics checks.
---
> Adds DaemonSet configuration for prometheusScrape

- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_postgres/gcsql.md
New instances of postgres 9.6 on CloudSQL don't allow access to `pg_stat_statements.query_text` for any user. This prevents a core part of dbm from working so it's probably best to deprecated support for postgres 9.6 on CloudSQL. 
Support cases that prompted the investigation that concluded with the inability to access required data for dbm on postgres 9.6 running on CloudSQL. 
---
> Remove Postgres 9.6 from supported versions on CloudSQL

- content/en/continuous_integration/_index.md
Add a promotional video to the landing page of the CI Visibility docs
Now that we have a promotional video for the product, we could align with other pages, like the APM one, by adding this video.
---
> [ci-app] Add promotional video to landing page

- layouts/partials/rum/rum-getting-started.html
Reshuffles ordering of RUM getting started partial.
#rum-docs Slack
---
> Reshuffling Tile Order in Product Landing Page

- content/en/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent.md
- Updating the dynamic Environment Variables on Kubernetes
- Splitting Configuration into (Agent/Application) settings with two sections
- Splitting Helm into (values.yaml/set) commands section
- Adding a Notice about the endpoint address
- Fixing small typos
- Faced some customers with difficulties reading this documentation
---
> Update OTLP Documentation

- content/en/dashboards/template_variables.md
Modifies the description and example for using dynamic template variable values in widget queries. Provides a new example to better illustrate the limitation of needing to place these values at the end of the template.
DOCS-3564
https://docs-staging.datadoghq.com/bryce/clarify-template-variable-syntax/dashboards/template_variables/#widgets
---
> (DOCS-3550) Add template variable detail and new example

- content/en/agent/cluster_agent/admission_controller.md
Update doc as Admission controller is on by default with Helm chart 2.35.0 
---
> Helm chart admission controller on by default

- content/en/integrations/faq/i-have-a-matching-bean-for-my-jmx-integration-but-nothing-on-collect.md
Update the link for collecting composite-type JMX attributes to point to its new location in the `guide` directory
DOCS-3484
https://docs-staging.datadoghq.com/bryce/update-jmx-composite-attribute-faq-link/integrations/faq/i-have-a-matching-bean-for-my-jmx-integration-but-nothing-on-collect/
Depends on the following PR being merged in first:
https://github.com/DataDog/documentation/pull/14284
---
> (DOCS-3484) Update link to point to guide

- content/en/database_monitoring/_index.md
- content/en/database_monitoring/setup_sql_server/_index.md
- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/gcsql.md
- content/en/database_monitoring/setup_sql_server/rds.md
- content/en/database_monitoring/setup_sql_server/selfhosted.md
Removes SQL Server private beta banner as we are now officially GA'd 
https://www.datadoghq.com/blog/sql-server-and-azure-managed-services-database-monitoring/
---
> Remove private beta banners in prep for SQL Server GA

- .gitignore
- Makefile
- config/_default/menus/menus.en.yaml
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Adds Expo and Expo Go in React Native Monitoring (https://github.com/DataDog/dd-sdk-reactnative/pull/216) and single sourcing logic for the child page.
DOCS-3603
Remember to apply changes to the `pull_config.yaml` file before merging!
---
> DOCS-3603 Expo Support for React Native Monitoring

- content/en/agent/docker/prometheus.md
- content/en/continuous_integration/setup_pipelines/gitlab.md
- layouts/shortcodes/tab.html
set `safeHTML` on tab titles to allow special chars
https://datadoghq.atlassian.net/browse/WEB-2462
https://docs-staging.datadoghq.com/brian.deutsch/gitlab-tabs/continuous_integration/setup_pipelines/gitlab/?tab=gitlabcom
---
> [WEB-2462] Safe html in tab titles

- assets/scripts/components/code-languages.js
- assets/scripts/components/codetabs.js
Updates URL after a code lang tab has been clicked, appending a query string to the URL so it will be easier to share the link out.
https://datadoghq.atlassian.net/browse/WEB-2451
- https://docs-staging.datadoghq.com/brian.deutsch/tab-update-url/security_platform/application_security/setup_and_configure
- https://docs-staging.datadoghq.com/brian.deutsch/tab-update-url/developers/dogstatsd
click on a different programming language tab, the URL should be updated with a query param containing the selected language.
I chose not to set this query param when the page first loads.    Not every docs page with tabs has the same languages list.   So a user could have their cookie set to `python`, go to a page that doesn't have `python` and on page load their cookie could get changed to something …
> [WEB-2451] Updates url when code lang tab is clicked

- content/en/tracing/setup_overview/setup/go.md
dd-trace-go now supports only the 3 latest go versions which is currently 1.16-1.18
---
> Update support go version to 1.16+

- content/en/agent/guide/network.md
- content/fr/agent/guide/network.md
- content/ja/agent/guide/network.md
We are updating the advertised IP ranges pointing to the Synthetics Private Location endpoints. This PR update the docs to change JSON format our customers will expect.
---
> [synthetics] add synthetics-private-location ip ranges in documented JSON schema

- content/en/tracing/trace_ingestion/mechanisms.md
Adds a note in the section "In the Agent" 
It's not clear currently that the agent traces-per-second param doesn't affect non-DD tracing libraries
> Note added in section "In the Agent"

- .github/workflows/preview_link.yml
- .gitignore
- local/bin/py/preview-links-template.mako
- local/bin/py/preview_links.py
This replaces the bash script in the workflow with a call to a python script. The script builds a markdown template with categories, which makes it easier to figure out what happened in the PR, and what to expect when you click on a preview link.
---
> Improve preview links action

- content/en/monitors/service_level_objectives/monitor.md
Fix sentence in monitor-based SLO page
https://docs-staging.datadoghq.com/kai/monitor-based-slo-groups/monitors/service_level_objectives/monitor/#define-queries
---
> Small tweak to groups mention on the monitor-based SLO page

- content/en/logs/log_configuration/parsing.md
curly quotes cause a formatting error for users when copying/pasting into parsing rule configuration
---
> Replace curly quotes in list to array parser rule

- content/en/events/guides/migrating_to_new_events_features.md
Adds more details about reserved attributes in events.
We have had several escalations and questions from customers asking why they could not filter by or create a facet on the attributes they didn't know were reserved.
---
> Add reserved attributes to event migration doc

- content/en/agent/kubernetes/prometheus.md
Update the link referenced as: 
> Every [configuration field](https://github.com/DataDog/integrations-core/blob/7.27.x/openmetrics/datadog_checks/openmetrics/data/conf.yaml.example) supported by the OpenMetrics check can be passed in the configurations list.
To link to the `master` branch of this instead of pinning to `7.27.x`. This is done in both the `Helm` and `DaemonSet` tab.
This was previously pinned to `7.27.x` as the Prometheus Scrape integration was creating the `openmetrics` checks with `prometheus_url` as the endpoint, so it was using the old OpenMetrics V1 version of the check. So it made sense to pin these docs to the old check configuration in `7.27.x`.
In `7.34.0` the Agent was upgraded to use `openmetrics_endpoint` so it is now creating these using the now OpenMetrics V2 …
> Update link to latest openmetrics v2 check configuration

- content/en/logs/log_configuration/indexes.md
Improves language and clarifies the Multiple Indexes section.
Several users have been reaching out because they misunderstood the fact that multiple indexes were already enabled by default and that they did not need our help to add new indexes.
---
> Improving language for Multiple Indexes

- content/en/tracing/trace_ingestion/mechanisms.md
It should NOT be (what we have in our docs):
@params apm_config.disable_rare_sample - boolean - optional - default: false
But instead it SHOULD be (add an r to sampler):
@params apm_config.disable_rare_sampler - boolean - optional - default: false
Just noticed that we have a typo in our ingestion control page under the rare traces here: 
https://docs.datadoghq.com/tracing/trace_ingestion/mechanisms/?tab=environmentvariables&tabs=environmentvariables#rare-traces
Had a ticket where customer was setting @params apm_config.disable_rare_sample and no changes were happening. 
---
> barbara-bontempo/Fix typo that is under rare traces

- content/en/agent/guide/dual-shipping.md
This setting was previously disabled by default. After testing and validation, we decided to make it `true` by default as it provides a better out of the box UX. 
---
> Agent `is_reliable` default to true for logs endpoints

- content/en/tracing/profiler/enabling/linux.md
One of the links was not pointing to the profiler. This fixes the link.
---
> Native profiler : fix link to profiler

- content/en/tracing/troubleshooting/connection_errors.md
For the tracers that work with UDS, they will detect the unix domain sockets if configured for Kubernetes: https://docs.datadoghq.com/containers/kubernetes/apm/?tabs=uds#configure-your-application-pods-to-submit-traces-to-datadog-agent, so this is an option to add to the connection setup . (Exception listed for now is PHP).
Show another path for Kubernetes users. 
---
> add uds to connection errors doc

- content/en/getting_started/synthetics/private_location.md
- content/en/real_user_monitoring/session_replay/_index.md
- content/en/synthetics/browser_tests/_index.md
- content/en/synthetics/guide/identify_synthetics_bots.md
- content/en/synthetics/private_locations/_index.md
- content/en/synthetics/settings/_index.md
> remove ie11 from docs

- content/en/continuous_integration/setup_tests/junit_upload.md
- content/fr/continuous_integration/setup_tests/junit_upload.md
- content/ja/continuous_integration/setup_tests/junit_upload.md
Add `test.bundle` tag to the list of test configuration tags that users can specify manually in junit upload.
We had this temporarily hidden while we did some internal changes, but now it works like the others and should be documented.
---
> Add test.bundle to documented test configuration tags in junit upload

- content/en/real_user_monitoring/session_replay/_index.md
- content/en/real_user_monitoring/session_replay/privacy_options.md
`replaySampleRate` is a deprecated configuration for RUM, this replaces some instances of the old deprecated option with the current option `premiumSampleRate`.
---
> replace replaySampleRate (deprecated) with premiumSampleRate

- content/en/serverless/guide/serverless_tracing_and_webpack.md
According to https://floydspace.github.io/serverless-esbuild/#configure, `aws-sdk` is the default value for the `exclude` field, so it needs to be included, otherwise by defining `exclude` explicitly people are effectively dropping `aws-sdk` from the `exclude` list.
Realized this issue based on a customer report.
---
> Need to exclude aws-sdk

- content/en/real_user_monitoring/frustration_signals/_index.md
I updated two things:
- got rid of the contact support banner (we are GAing today, this is not needed)
- Updated the SDK version a user would need to be on
---
> frustration_ga_release

- assets/scripts/components/dd-browser-logs-rum.js
Temporary removal of `trackSessionAcrossSubdomains` config for DD RUM
requested via Slack 
No visual impact 
---
> Updates RUM config to disable tracking across subdomains

- content/en/containers/cluster_agent/troubleshooting.md
Changes port for Cluster Agent to 8443 to be consistent with other docs and defaults.
Making the docs consistent and less confusing.
---
> cluster troubleshooting - update port to 8443

- content/en/metrics/custom_metrics/dogstatsd_metrics_submission.md
The sample made it look like you had to repeat environment tag for every metric you send, but especially for the `environment` tag it would make a lot of sense to set it when instantiating the sender, I think.
Code samples matter a lot for how users approach new tools.
---
> Tweak ruby sample to show standard tags adding

- content/en/continuous_integration/setup_pipelines/jenkins.md
This PR adds a specific section for HTTP 504 errors on the Jenkins integration page.
---
> [CI Visibility] Add section for HTTP 504 errors on the Jenkins integration page

- content/en/tracing/connect_logs_and_traces/dotnet.md
Some notes about using Serilog through ILogger and how source relates to traceid.
Struggling with integration APM traces and logs in my day job and having the answer be unintuitive made me want to add some notes.
---
> Notes about ILogger calling serilogger and traceid notes

- content/en/tracing/setup_overview/setup/java.md
- Update `DD_TRACE_SAMPLE_RATE` explanation.
- Add `DD_TRACE_SAMPLING_SERVICE_RULES`, `dd.trace.sampling.service.rules` explanations.
`DD_TRACE_SAMPLING_SERVICE_RULES`, `dd.trace.sampling.service.rules` should be documented because they are introduced in the in-app document.
---
> Add config explanations to control sampling rate in Java

- content/en/tracing/setup_overview/compatibility_requirements/python.md
Shows the Python tracer's known supported versions for pymysql
An SE noted that we don't have it on our compatibility page
> add that we support pymysql

- content/en/real_user_monitoring/error_tracking/browser_errors.md
- local/bin/py/build/configurations/pull_config_preview.yaml
Batch formatting update for RUM Error Tracking docs.
DOCS-2578
---
> DOCS-2578 Track Browser Errors Edits

- content/en/agent/guide/secrets-management.md
Clarify that `configcheck` does not print decrypted passwords
---
> Clarify configcheck

- content/en/serverless/configuration/_index.md
hey! so i'm not sure if everyone else knew this already, but here's a thing i didn't know you had to do in markdown!
basically: remember that when you are using anchor links, it has to all be lowercase
if your heading is something like `We love APM`, your anchor link is `#we-love-apm`. (it is probably documented somewhere that all heading ids in markdown are lowercased, but i'm gonna be honest here, i have not read the markdown documentation.) urls are case-sensitive, so linking to `#we-love-APM` will not work.
actually now that i'm thinking about it i suspect all urls have to be lowercased
> fix a subtle link bug

- content/en/database_monitoring/setup_sql_server/azure.md
- layouts/shortcodes/dbm-sqlserver-agent-setup-windows.md
The ADO Provider is configured using the `adoprovider` key, not the `provider` key.
Fix wrong docs. 
---
> fix wrong key in sqlserver docs

- content/en/integrations/amazon_cloudhsm.md
- content/en/integrations/amazon_guardduty.md
- Updates the logs collection section for AWS services docs because they are out of date.
- Removes images because they are out of date. We shouldn't include images of third-party apps in our docs, because it's difficult to maintain.
DOCS-3317
---
> [DOCS-3317] Update AWS services log collection section

- content/en/integrations/guide/source-code-integration.md
Update the [Source Code Integration documentation page](https://docs.datadoghq.com/integrations/guide/source-code-integration) to favour setting up the GitHub Apps integration.
New alternative setup.
Still a draft as the feature is not enabled to customers yet.
---
> Update SCI documentation

- content/en/agent/guide/agent-log-files.md
on my mac, the files are in /opt/datadog-agent/logs not /opt/datadog-agent/log (plural v singular)
---
> (DOCS-3245) Update agent-log-files.md

- content/en/monitors/create/types/ci.md
This PR adds a section to indicate how to leverage `test.codeowners` info to select to which team the notification needs to be sent. This section is added in the CITest monitors tab on the CI monitors page.
---
> [CIAPP] Add `CODEOWNERS` control section for CITest monitors.

- content/en/getting_started/tagging/unified_service_tagging.md
This PR fixes the ecs configuration example by moving the dockerLabels block outside of the environment array.
The dockerLabel section was incorrectly included as an environment variable
---
> (DOCS-3686) Update ECS configuration example in UST

- content/en/tracing/setup_overview/compatibility_requirements/python.md
Updates the pymysql versions we support to show we support up to latest
It's good to show users that we support the latest versions of libraries.
PR showing tracer testing changes:
https://github.com/DataDog/dd-trace-py/pull/3911
---
> Update Pymysql supported versions

- content/en/tracing/guide/metrics_namespace.md
Right now the "outdated" warning applies to all metrics, but it only affects the ones related to latency distribution/percentiles that have a DDSketch variant.
To improve clarification which metrics to use.
---
> move deprecation warning for trace metrics page

- content/en/containers/kubernetes/_index.md
- content/en/getting_started/containers/autodiscovery.md
Moves autodiscovery redirect from Kubernetes to the containers GS
---
> Move autodiscovery redirect

- content/en/monitors/incident_management/incident_details.md
Changes "The" to "An" in the description of "Communication Lead"
An incident can have multiple communication leads so this wording makes that more clear
---
> Change "The" to "An"

- layouts/shortcodes/latest-lambda-layer-version.html
Bump dd-trace-dotnet layer version to 4 (https://github.com/DataDog/dd-trace-dotnet-for-lambda/releases/tag/v4)
---
> Bump dd-trace-dotnet layer to version 4

- content/en/tracing/setup_overview/setup/php.md
This PR updates the PHP APM configuration section to include new environment variables which the user should be aware of in order to opt-out of the new tags introduced for backend ASM.
Provide the user the option to disable some of the new tags introduced for backend ASM.
---
> Update PHP APM configuration documentation for version 0.76.0

- content/en/tracing/setup_overview/open_standards/otlp_ingest_in_the_agent.md
Updates documentation for how to setup OTLP ingest in the Datadog Agent Helm Chart.
DataDog/helm-charts/pull/619 adds support for OTLP ingest in a more automatic way.
---
> [OTLP ingest] Update documentation for Helm chart

- content/en/serverless/installation/dotnet.md
- content/en/serverless/installation/go.md
- content/en/serverless/installation/java.md
- content/en/serverless/installation/nodejs.md
- content/en/serverless/installation/python.md
Use the `{{< region-param key="dd_site" code="true" >}}` parameter to embed the correct DD_SITE value inline.
Currently people are linked to https://docs.datadoghq.com/getting_started/site/ and cause them to set the DD_SITE with the subdomain such as `app.` and break the installation.
---
> Use the dd_site parameter instead

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
A new parameter allows RUM/APM users to control the sampling of APM backend traces from the sdks
Add documentation for this config parameter in the `Connect RUM and Traces` article
---
> Configuration of trace sampling for RUM backend traces

- content/en/agent/guide/compose-and-the-datadog-agent.md
When installing the agent on my personal host, using docker-compose, I used the provided snippet, but it was not working.
This PR add `privileged: true` to allow collection of other containers data.
In the [Docker agent installation doc](https://docs.datadoghq.com/agent/docker/?tab=standard) it states that agent should be run with `--cgroupns host`, which is `privileged: true` in compose.
I wanted to change `build: datadog` which is supposed to be used to build a local container to `image: datadog/agent` which pulls the image from docker repository, but did not.
I'm balanced between the "it works out of the box" approach (`image: datadog/agent`) and the "in the real world you will customise it anyway" one (`image:` + `Dockerfile`).
---
> DOCS-3666 Fix docker-compose integration installation doc

- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/rds.md
The previous PR which added the `track_io_timing` config parameter (#14567) had the wrong value for Amazon databases.  This PR fixes that value.
---
> Fix value for track_io_timing with Amazon Postgres databases

- local/bin/py/build/actions/security_rules.py
For OOTB rules, we need a way to DEPRECATE a rule, keep the markdown available inside the product but not show on the documentation.
This PR updates the documentation to no longer display rules that have a `isDeprecated` flag set to true.
The logic is as follows, If one or more of these occurs in the file `isStaged:true`, `isDeleted:true`, `isEnabled:false`, `isDeprecated: true` then the rule does not display
https://datadoghq.atlassian.net/browse/DOCS-3230
Nothing to see as of yet as rules haven't been updated.
https://docs-staging.datadoghq.com/david.jones/deprecate-rule/security_platform/default_rules/
(upstream) So the process is essentially:
- Update markdown with deprecation warning
- Update the rule with `isDeprecated: true`
- Wait X days until deprecation date
- Set `isEnabled: …
> DOCS-3230 - isDeprecated also removes rule

- content/en/tracing/trace_collection/dd_libraries/java.md
Previous implementation "group: 'com.datadoghq', name: 'dd-trace-api', version: {version}" resulted in build errors as the endpoint returned 404.
---
> Update build.gradle dd-trace-api implementation

- content/en/dashboards/widgets/timeseries.md
- layouts/shortcodes/img.html
- Allows `img.html` shortcode to render height and width parameters.
- Update timeseries widget docs page images to include height and width parameters, improving CLS score from yellow to green.
https://datadoghq.atlassian.net/browse/WEB-2435
Google Search Console core web vitals report identified this page as having a CLS score needing improvement
https://docs-staging.datadoghq.com/brian.deutsch/cwv-fixes/dashboards/widgets/timeseries/
- running Lighthouse for Desktop should show CLS score in green (~0.01), opposed to the live version of this page which is in yellow (needs improvement).
- the image size and quality should be unchanged.
This was the only page specifically identified by the report, but we'll keep an eye out as Google validates our pages for CWV frequently.
---
> [WEB-2435] Allow img shortcode to render height and width parameters

- content/en/logs/log_collection/ruby.md
Rails.root support `#join` method
> Better syntax for rails initializer

- content/en/tracing/trace_collection/proxy_setup/_index.md
Clarifies that `--set values.pilot.traceSampling=100.0` must be configured when trying to follow the Istio sampling section. 
Ensure that `--set values.pilot.traceSampling=100.0` is set for Istio. If it isn't, then the defaul sampling mechanism will lead to the `DD_TRACE_SAMPLING_RULES` parameter being ignored.
---
> update istio sampling wording

- content/en/logs/log_configuration/parsing.md
The extraction in the image is "date" for the example "MyParsingRule %{word:user} connected on %{date("MM/dd/yyyy"):connect_date}"
Remove "connect_" to reflect the key in the image.
Changing documentation for the example at the top of the page to reflect the key in the image below it.
Noticing the key wasn't connect_date in the image.
---
> Make sure key in example reflects image below

- content/en/logs/log_collection/_index.md
Corrects the us1-fed https logs endpoint
https://dd.slack.com/archives/C6QR6DXJ4/p1657574897009779
https://a.cl.ly/wbuXvG9N
---
> Correct the us1-fed https logs endpoint

- content/en/tracing/trace_collection/dd_libraries/python.md
protocol is incorrect and if followed generates error:
```
/lib/python3.7/site-packages/ddtrace/internal/dogstatsd.py", line 28, in get_dogstatsd_client
raise ValueError("Unknown scheme `%s` for DogStatsD URL `{}`".format(parsed.scheme))
ValueError: Unknown scheme `%s` for DogStatsD URL `http`
```
fixes incorrect documentation example of env var
fix incorrect information
---
> Update python.md to correct DD_DOGSTATSD_URL protocol

- .gitlab-ci.yml
- assets/scripts/tests/api-redirect.test.js
- assets/scripts/tests/build-api-pages.test.js
- package.json
fix jest tests and configure jest to run in the preview build pipeline
https://datadoghq.atlassian.net/browse/WEB-2482
n/a
- job ran successfully and unit tests passed: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/153000483#L3969-L3979
- `yarn run jest-test` works locally
---
> [WEB-2482] fix jest tests + add to preview pipeline

- content/en/account_management/faq/access-your-support-ticket.md
- i18n/en.json
- Adds info and link to page on how to log into Support Website.
- Title case for Access Your Support Ticket page, and fix link list.
DOCS-3732
Previews: 
https://docs-staging.datadoghq.com/may/update-help-page/help/
https://docs-staging.datadoghq.com/may/update-help-page/account_management/faq/access-your-support-ticket/
---
> [DOCS-3732] Update help page

- content/en/tracing/guide/ignoring_apm_resources.md
Reference https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#processing-pipeline
The old configuration block is no longer valid for version 1.x of Ruby ddtracer-rb. 
This is the link to the reference: https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#processing-pipeline 
I am a customer and suffering wrong configurations that affects my billing because this part is outdated. 
---
> Update instruction to ignore some apm resources ruby tracer

- content/en/integrations/observability_pipelines/guide/_index.md
- content/en/integrations/observability_pipelines/guide/custom-metrics-governance-drop-metrics-missing-specific-tags.md
- content/en/integrations/observability_pipelines/integrations.md
- content/en/integrations/observability_pipelines/setup.md
- content/en/integrations/observability_pipelines/vector_configurations.md
- content/en/integrations/observability_pipelines/working_with_data.md
The Observability Pipelines are currently under Integrations, and because of how the Integrations are setup, those docs don't have an Edit button. I added dependencies to the frontmatter so that there is an Edit button for Obs Pipelines docs.
Also made the Guide index private and disabled the sidebar, because it looks like that's what it should be based on other Guide indexes.
DOCS-3709
---
> [DOCS-3709] Add dependencies for obs pipelines docs

- content/en/database_monitoring/setup_mysql/troubleshooting.md
Adds a troubleshooting guide for customers missing explain plans due to a missing event statements consumer. 
---
> dbm: Add MySQL troubleshooting for missing event statements consumer

- content/en/account_management/billing/containers.md
adds a note to containers billing page that the container is monitored by default
---
> DOCS-3785 container billing note

- content/en/dashboards/widgets/treemap.md
- Includes a table of "props" table from the OpenAPI definition for the treemap, similar to what we have for the [distributions](https://docs.datadoghq.com/dashboards/widgets/distribution/#api) widget.
- Improve understanding of the Treemap API for consumers that are programmatically defining their treemaps
---
> feat(dataviz): include treemap generated properties table in the Treemap documentation

- assets/scripts/components/codetabs.js
Fixes links inside tab containers.
https://datadoghq.atlassian.net/browse/WEB-2534
https://docs-staging.datadoghq.com/brian.deutsch/tab-links-1/logs/log_collection
---
> [WEB-2534] fixes nested links inside tab containers

- content/en/continuous_integration/troubleshooting.md
This PR clarifies that only default branches are displayed in the Pipelines list. This follows a change that we are doing to remove non-default branches from that list.
---
> [CIAPP] add clarification on pipelines list

- content/en/tracing/trace_collection/compatibility/dotnet-framework.md
State the EOL versions of the Tracer.
Clarify that the runtime version is what matters for auto instrumentation
I've also added a link to our last 1.x release to avoid to have to look for it.
For accuracy and as the later is an often asked question.
---
> [Tracer][.NET] State the EOL versions and clarify that the runtime version is what matters for auto instrumentation

- assets/scripts/components/codetabs.js
fixes handling of tabs query parameter.
https://datadoghq.atlassian.net/browse/WEB-2528
- https://docs-staging.datadoghq.com/brian.deutsch/tabs-query-param-fix/getting_started/tagging/unified_service_tagging/?tab=custommetrics#non-containerized-environment
- https://docs-staging.datadoghq.com/brian.deutsch/tabs-query-param-fix/getting_started/tagging/unified_service_tagging/?tabs=custommetrics#non-containerized-environment
---
> [WEB-2528] tabs query param fix

- content/en/tracing/services/service_page.md
Adds a small paragraph to the Service Page docs explaining the new APM Resource Panel
The resource panel was recently GAed
---
> [apm] Add Resource Panel information to the Service Page docs

- content/en/containers/kubernetes/log.md
now that we have troubleshooting content, we can have a troubleshooting section
---
> DOCS-3569 Add troubleshooting section to k8s logs page

- content/en/getting_started/logs/_index.md
Links in the guides section pointed to our old LMS which we migrated from yesterday. This PR updates the links to point to the home of the new courses.
404's from current Guide links
There are probable other LMS links in Guides that are broken
---
> Updates the links to lead to the new LMS

- content/en/tracing/other_telemetry/connect_logs_and_traces/java.md
remove line tab=jsonlogs#trace_id-option which is causing the URL references to be rendered as plaintext on the docs page
Remove an unnecessary line causing link reference objects to be rendered as plaintext on the docs page.
Resolve broken links in the docs page to properly route readers to the proper documentation links
---
> Update java.md to resolve broken links

- content/en/agent/proxy.md
- Updates the Agent config example for DBM when using revere proxies (nginx, haproxy)
- AGENT-8252
- `dd_url` under `network_devices` might need the same changes but I have personally not tested them.
---
> Update examples for DBM reverse proxy

- content/en/getting_started/agent/_index.md
It appears there should at least be an apostrophe at the end of "processes" to make it possessive plural in the original sentence.  I think the replacement sentence is a bit more clear.
---
> fix agent doc punctuation

- content/en/agent/proxy.md
- Updates the Agent config example for NDM when using revere proxies (nginx, haproxy)
- Similar to #14704
- confirmation that `network_devices` also needs the same changes from ZD#858400
---
> update `network_devices` reverse proxy example

- content/en/tracing/configure_data_security/_index.md
This adds a small note about the required SQL string format for obfuscation.
Some customers were using double-quoted strings in their SQL statements and were unsure why their strings were not obfuscated as they expected.
---
> content/en/tracing/configure_data_security: add note about sql strings formatting.

- content/en/integrations/observability_pipelines/guide/control_log_volume_and_size.md
- Adds dependency to front matter so the Edit button shows up.
- Edit title for SEO.
Because the doc is in the Integration section, the Edit but won't show up automatically.
H1s should have words that are in the nav.
---
> Add dependencies and edit title of Obs Pipelines guide

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Unnecessary action to single source this folder from the dd-sdk-ios repo that does not exist anymore.
Configuration Page Cleanup
---
> Removes Pull-And-Push Folder Action for Error Tracking

- Makefile
With the makefile changes the placeholders need to run after completion of sourcing the other repos not at the same time.
some security rules pages were being deleted in other langs
---
> placeholder fix

- content/en/continuous_integration/setup_tests/junit_upload.md
* Makes more visible the recommendation to use native test instrumentation instead of JUnitXML.
* Rewords the text so it talks about the positives of using native instrumentation instead of the negatives of JUnitXML.
Test instrumentation provides a better user experience and we want to recommend it.
---
> [Tracing Tests] More visibly recommend instrumentation over JUnitXML

- content/en/events/guides/migrating_to_new_events_features.md
Reserved Attributes table has an extra line in the table: https://docs.datadoghq.com/events/guides/migrating_to_new_events_features/#reserved-attributes 
---
> Fix formatting for Reserved Attributes table

- content/en/events/explorer/_index.md
Add a table of reserved attributes in events.
Customers need to know that there are specific attributes that they cannot create facets on.
---
> Add Reserved Attributes to main Events Explorer doc

- content/en/events/explorer/_index.md
Add steps on searching tags and creating facets for tags that share the same key as reserved attributes.
Customers have reported issues related to this
---
> Add notes on reserved attributes to Events Explorer doc

- content/en/logs/log_configuration/archives.md
Clarifies that logs archive upload time can vary.
DOCS-3518
---
> [DOCS-3518] Clarify logs archive upload time

- content/en/logs/log_collection/php.md
- content/fr/logs/log_collection/php.md
- content/ja/logs/log_collection/php.md
Fix and make more obvious/clear that the service parameter in conf.yaml (for PHP) needs to be adjusted. 
I copied the configuration but didn't realized that this parameter needed adjustment. As it is written is looks like a "good default" instead of "you need to adjust this" kind of parameter.
So instead of 
> service: "php"
I propose
> service: "<SERVICE_NAME>"
to make it clearer.
---
> make more clear/obvious that service parameter needs to be adjusted

- content/en/watchdog/_index.md
Adds a note to the top level Watchdog page saying that Watchdog requires two weeks of baseline data before it can report anomalies.
Discussion in #support-data-science Slack channel.
---
> Add note about 2 week Watchdog baseline

- content/en/agent/guide/how-do-i-uninstall-the-agent.md
Adds instructions to remove systemwide macOS installation. I introduced another section for this, because I think it's more comfortable for users to C&P instead of having to go through one set of instructions and figure out what instruction to run when.
We added the systemwide installation feature in https://github.com/DataDog/datadog-agent/pull/10621 and want to document how to uninstall agent in this scenario.
---
> Provide uninstall instructions for macOS systemwide installation

- content/en/synthetics/multistep.md
Clarifies the limit on variables in multistep API tests.
DOCS-3844
---
> DOCS-3844 Multistep API Test Edit

- content/en/containers/kubernetes/installation.md
Add a compatibility matrix between Kubernetes version and Datadog Agent/Cluster-Agent version.
If a lower Agent/Cluster-Agent version is use, some features will not work properly.
---
> feat(kubernetes): add compatibility matrix

- content/en/monitors/service_level_objectives/burn_rate.md
- content/en/monitors/service_level_objectives/error_budget.md
For the change to the burn rate alerts section: 
For the change to the error budget alerts section:
https://datadoghq.atlassian.net/browse/DOCS-3617
---
> Update SLO monitor docs

- content/en/agent/troubleshooting/agent_check_status.md
- content/fr/agent/troubleshooting/agent_check_status.md
- content/ja/agent/troubleshooting/agent_check_status.md
This PR updates the link to the integrations docs on the Agent Check Status page.
Previously, the current link would lead to the homepage of our docs.
A customer complained about this specific link, and I think it makes sense to update it.
---
> integrations link update

- content/en/tracing/faq/service_definition_api.md
Changing the filename and code block to JSON instead of YAML.
Updates some code block examples to be JSON instead of YAML to match the file format.
Consistent documentation.
---
> service catalog documentation update

- content/en/tracing/profiler/profiler_troubleshooting.md
Document an issue that has come up with running the Ruby profiler on older operating system images that include old versions of the GCC compiler.
This issue has come up a couple of times now, so I think it's time to add it to the troubleshooting doc.
---
> Document issue with installing profiler with older versions of GCC

- content/en/logs/log_configuration/rehydrating.md
Previous statement (90 days) was not correct, we can see deleted historical views for up to a year in the UI.
> Update number of days deleted views stay in the UI

- Makefile
- README.md
- local/bin/py/build/content_manager.py
Followup to #14603 with a slightly different approach. 
Update the pre-build setup to check if dependent repos are available locally. (This was partially done before by checking if the user manually cloned them, but this can do one better by using the version of the repo pulled from the last local build)
There's an environment variable check that will ensure that all external repos get pulled on each build, so this behavior should only impact local dev
Updates the error handling during local dev to print out the underlying exception to aid in debugging
Updates the Makefile to make cleaning external repos its own target command, and updates the README to note this behavior. 
Speed up local builds when trying to build with external dependencies
---
> Avoid continuously repulling dependent repos

- content/en/logs/guide/reference-tables.md
Adding details on how to delete a Reference Table and implication on lookup processor.
Adds description on deleting Reference Tables
Added support for 'deleting' Reference tables
None
---
- [x ] Review the changed files.
- [x ] Review the URLs listed in the [Preview](#preview) section.
- [x ] Check images for PII
- [x ] Review any mentions of "Contact Datadog support" for internal support documentation.
> Update Reference Table with Delete feature

- content/en/tracing/trace_collection/tracing_naming_convention/_index.md
Change table header from `fullname` to `name` because it should be `name`.
---
> Update table name header

- content/en/tracing/profiler/enabling/dotnet.md
Add the minimum required version to the .NET profiler documentation.
At least one customer tried to use the profiler with an older version and couldn't figure why it wasn't working.
---
> Add the minimum required version to the .NET profiler documentation

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
- content/fr/real_user_monitoring/connect_rum_and_traces/_index.md
- content/ja/real_user_monitoring/connect_rum_and_traces/_index.md
This parameter is unused and deprecated since 3y+
> RUM: remove mention of x-datadog-sampled

- local/bin/py/build/actions/integrations.py
Hardcodes a sentence at the bottom of generated marketplace documentation to note that it was created by a partner, and where to go to make the purchase
I also updated some inline comments that my editor were complaining about 🙂 
This was previously expected to be placed in every marketplace README. However we had no validations around this which led to:
* Some integrations forgetting to include the sentence completely
* Some copy/paste issues where the link would be there, but point to a different tile
Additionally, we don't need this copy in the in-app tile, only in the documentation, so including it here directly is beneficial.
Some good examples to view are:
* rapdev_zoom - This will have the generated copy at the bottom 
* rapdev_sophos - This will have the generated copy at the …
> Write link to in-app tile for purchasing marketplace integrations in generated docs

- content/en/agent/guide/_index.md
- content/en/continuous_integration/guides/_index.md
- content/en/dashboards/guide/_index.md
- content/en/data_security/guide/_index.md
- content/en/database_monitoring/guide/_index.md
- content/en/developers/guide/_index.md
- content/en/events/guides/_index.md
- content/en/integrations/guide/_index.md
- content/en/logs/guide/_index.md
- content/en/metrics/guide/_index.md
- content/en/monitors/guide/_index.md
- content/en/network_monitoring/devices/guide/_index.md
- content/en/network_monitoring/performance/guide/_index.md
- content/en/real_user_monitoring/guide/_index.md
- content/en/security_platform/guide/_index.md
- content/en/serverless/guide/_index.md
- content/en/synthetics/guide/_index.md
- content/en/tracing/guide/_index.md
Update all front matter for guide indexes so that they have:
private: true
disable_toc: true
DOCS-3794
---
> [DOCS-3794] Make front matter for guide indexes consistent

- content/en/tracing/profiler/enabling/dotnet.md
Adjust the documentation according to the new support of CentOS 7.
---
> [.NET Profiler] Update .net profiler documentation according new support of CentOS 7

- content/en/tracing/trace_pipeline/ingestion_controls.md
- content/en/tracing/troubleshooting/agent_rate_limits.md
Customers seeing "Limited Resource" as a warning while having plenty of memory and CPU available on their host get confused by this. This documentation clarifies the meaning of this warning and makes it clearer that this refers to internal limitations of the configuration rather than actual host resources.
> Clarify exactly what "Limited Resource" means.

- content/en/agent/basic_agent_usage/_index.md
The minimum version of Windows that Agent v5 supports is Windows 2008, not 2008r2, see https://app.datadoghq.com/account/settings?agent_version=5#agent/windows
---
> Fix minimum Windows version supported by Agent v5

- content/en/agent/troubleshooting/agent_check_status.md
Explain how to disable a service check.
I may want to temporarily disable check when troubleshooting. This was not in the documentation so I added it.
How Agent get configuration files.
https://github.com/DataDog/datadog-agent/blob/edc2559d7167466ccf010d7f4a6bd42908ac6116/pkg/autodiscovery/providers/config_reader.go#L217-L278
---
> [agent] disable service check

- content/en/agent/guide/private-link.md
Lambda Extension requires the VPC Endpoint for Secrets Manager when using PrivateLink and loading Datadog API Key from Secretes Manager (recommended by Datadog).
Based on customer feedback.
---
> Lambda Extension may require VPC Endpoint for Secrets Manager

- local/bin/py/build/actions/security_rules.py
Support skipping rules with both `isStaged` to `isShadowDeployed` flags until upstream switches completely to `isShadowDeployed`
https://github.com/DataDog/security-monitoring/pull/1589
https://docs-staging.datadoghq.com/david.jones/shadow-deploy/security_platform/default_rules#all
---
> isStaged switching to isShadowDeployed

- content/en/monitors/notify/variables.md
This PR adds the explanation of the `urlencode` function helper for the monitor message.
---
> [monitors] Add `urlencode` helper docs.

- content/en/containers/docker/_index.md
- content/en/containers/docker/apm.md
- content/en/containers/docker/log.md
- content/en/containers/docker/prometheus.md
- content/en/developers/dogstatsd/_index.md
- content/en/logs/guide/container-agent-to-tail-logs-from-host.md
- content/en/logs/guide/how-to-set-up-only-logs.md
- content/en/network_monitoring/performance/setup.md
- content/en/security_platform/cloud_workload_security/getting_started.md
- content/en/tracing/guide/ignoring_apm_resources.md
This PR adds the `--pid host` flag to all relevant docker commands in our corporate documentation.
Following from https://github.com/DataDog/datadog-agent/pull/11584, the agent needs to be run in the host's pid namespace in order to successfully retrieve UDS credentials for container tagging with cgroup v2. 
---
> all: add --pid host to all applicable docker agent commands

- package.json
- yarn.lock
Updates the hugo version to 0.101.0
Staying up to date with the latest features
QA as much as possible, looking for anything out of the ordinary
https://docs-staging.datadoghq.com/david.jones/hugo-latest/
---
> update hugo version

- content/en/dashboards/reporting.md
- Drop `Service Summary` from the list of supported widget types.
- (Also reorder `Query Value` for alphabetical ordering.)
- Missed this in the initial review, figured I'd fix it directly since it's small.
---
> Update widget type details for Dashboard Reporting docs

- layouts/partials/integrations-logo.html
- layouts/security_rules/list.html
- Updates the wording on security rule grouped sections so that aws or gcp appears capitalized.
- Sets up a fallback to generic cloud logos where possible
https://datadoghq.atlassian.net/browse/WEB-2564
https://docs-staging.datadoghq.com/david.jones/rules-gcp/security_platform/default_rules/?q=gcp#all
---
> WEB-2564 - set a default cloud logo for security rules when missing

- package.json
- yarn.lock
rollback a recent hugo version upgrade
it seems `jqmath-vanilla` (or something to do with it's implementation) was somehow broken by the latest version upgrade.
see these pages versus their live counterparts.   the jq math rendering should be working and there should not be a JS alert error popping up on page load.
- https://docs-staging.datadoghq.com/brian.deutsch/rollback-hugo-version/tracing/guide/span_and_trace_id_format/
- https://docs-staging.datadoghq.com/brian.deutsch/rollback-hugo-version/tracing/glossary/#execution-time
- https://docs-staging.datadoghq.com/brian.deutsch/rollback-hugo-version/monitors/service_level_objectives/burn_rate/
vs.
- https://docs.datadoghq.com/tracing/guide/span_and_trace_id_format/
- https://docs.datadoghq.com/tracing/glossary/#execution-time
- …
> rollback hugo bin version

- content/en/monitors/create/types/metric.md
Removes `exclude` from the list of steps for creating this monitor type, and removes an outdated, unnecessary image.
DOCS-2853
---
> (DOCS-2853) Remove 'exclude' from monitor create metrics page

- content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
This PR does two things:
- Mentions browser logs unminification
- Supports all Datadog sites, instead of only US / EU
Today, this page incorrectly mentions that we only support unminification of events from the RUM SDK. We also support unminification of error stack traces attached to logs collected by the browser logs SDK.
---
> [SC-987] Add browser logs unminification instructions

- content/en/tracing/service_catalog/service_definition_api.md
Amends a JSON code block's invalid format.
While unlikely to be copy-pasted in a detrimental way, it breaks syntax highlighting.
---
> Fix missing and extraneous dangling commas

- content/en/tracing/profiler/profiler_troubleshooting.md
Update the profiler troubleshooting page to indicate the expected CPU overhead for the .NET profiler.
Some customers had issues because they enabled the profiler in containers that weren't properly sized.
---
> Add the expected overhead for the .NET profiler

- content/en/tracing/trace_collection/library_config/php.md
Updates the default value of `DD_PROFILING_EXPERIMENTAL_CPU_TIME_ENABLED` to reflect the upcoming v0.77.0 release.
Gotta keep the docs up-to-date :)
Shouldn't merge until dd-trace-php v0.77.0 is released in case the release process stalls or delayed due to issues found late in the process.
---
> [PHP] DD_PROFILING_EXPERIMENTAL_CPU_TIME_ENABLED defaults to on

- content/en/continuous_integration/setup_pipelines/github.md
Updates the list of supported GitHub versions to include GHES 3.5.0+
---
> Update docs for ghes 3.5.0+ support

- content/en/account_management/billing/aws.md
Specifies the customer needs to use the API to exclude resources other than EC2 : T
https://docs.datadoghq.com/api/latest/aws-integration/#set-an-aws-tag-filter
Many many tickets :) 
---
> nsarfaty - explain how to exclude instances

- content/en/tracing/profiler/search_profiles.md
Removes the img links, but not the .png file because FR and JA still temporarily point to them.
Request from PM in slack
> Remove images links from Searching Profiles page

- content/en/tracing/profiler/enabling/go.md
- content/fr/tracing/profiler/getting_started.md
- content/ja/tracing/profiler/enabling.md
- content/ja/tracing/profiler/getting_started.md
- content/ja/tracing/profiling/getting_started.md
Corrects a typo in the Go continuous profiling example. Each tag passed to
profiler.WithTags should be a separate argument.
---
> Fix typo in Go profiler example

- content/en/serverless/custom_metrics/_index.md
- content/en/serverless/guide/upgrade_java_instrumentation.md
- content/en/serverless/installation/dotnet.md
- content/en/serverless/installation/java.md
- content/en/serverless/installation/nodejs.md
- content/en/serverless/installation/python.md
1. Guide for upgrading serverless java instrumentation to the latest versions
2. Update all DD_SITE references to use the site parameter to show the correct value
Serverless java instrumentation was recently simplified, for existing users't we need a guide to summarize the steps to upgrade. 
---
> Guide for Serverless Java instrumentation upgrade

- content/en/monitors/notify/variables.md
It documents the fact that `is_exact_match` supports matching multiple strings, the same way it is supported for `is_match`.
https://github.com/DataDog/documentation/issues/14781
Since it wasn't clear from the documentation I had set up a dummy monitor to confirm it. Having it documented would have saved me that _hassle_.
I only confirmed it by testing it. It might be good to get it confirmed from the code as well.
---
> Documents that is_exact_match supports matching multiple strings

- content/en/tracing/trace_collection/proxy_setup/_index.md
Correct inconsistencies in the "sampling" section of the getting started instructions for tracing the Nginx Ingress Controller for Kubernetes. See https://datadoghq.atlassian.net/browse/APMS-7568
The docs were inaccurate, as a customer learned.
---
> David.goffredo/fix nginx ingress controller sampling

- content/en/agent/basic_agent_usage/aix.md
Adds note that there's no trace agent in AIX Agent.
Conversation with T2 who had a customer try this.
> Update aix agent docs to indicate no APM support

- content/en/monitors/guide/monitor-for-value-within-a-range.md
This PR corrects the appropriate formula for creating a monitor within a range of values in the documentation.
I created a monitor that was having the opposite effect of the intended behavior after following the documentation. The previous example in the same document had the correct formula described.
---
> Correct range formula descriptions

- content/en/profiler/enabling/go.md
Corrects the Go profiler configuration documentation. For the Go profiling
client library API, tags are passed as a list of strings of the form
`"<key>:<value>"`, rather than a single comma-separated string of tags (as is the case for
the "DD_TAGS" environment variable).
---
> Correct WithTags option for Go profiling client library

- content/en/monitors/create/types/composite.md
Adds a descriptions on how composites, child monitors, and downtimes all play together.
---
> Add docs about composites and downtimes behaviour

- content/en/monitors/service_level_objectives/monitor.md
Clarify how the overall monitor-based SLO status is calculated. One of the sentences was inaccurate before. 
https://docs-staging.datadoghq.com/kai/monitor-slos/monitors/service_level_objectives/monitor/
---
> Update section on how monitor SLO status is calculated

- content/en/database_monitoring/setup_sql_server/azure.md
- layouts/shortcodes/dbm-sqlserver-before-you-begin.md
This reverts commit https://github.com/DataDog/documentation/commit/96356a4586148b2a1f76a8a34464111436fdf2b2.
Since https://github.com/DataDog/integrations-core/pull/12397 (released in 7.38.0) these custom Azure SQL Database configuration instructions are no longer neccessary.
Simplify documentation. 
---
> Remove now-unnecessary custom Azure instructions

- content/en/real_user_monitoring/browser/monitoring_page_performance.md
`DD_RUM.addTiming` has a second parameter that the user can use to provide their own timing. This PR add documentation for that.
The documentation was missing.
---
> Document DD_RUM.addTiming second parameter

- assets/scripts/main-dd-js.js
- layouts/partials/css.html
- layouts/partials/footer-scripts.html
- layouts/partials/integrations-logo.html
- layouts/shortcodes/jqmath-vanilla.html
- package.json
- yarn.lock
We updated hugo in #14800 which we had to rollback due to `err_scanTokP_` alert popups that were appearing from jqmath.
This PR:
- updates hugo to the latest again 
- fixes the popup issues by loading the jqmath js file on the pages its needed instead of in-lining it on the page which hugo was disrupting somehow.
- removes a warnf i left from a previous task
To get us back to the latest hugo
**Pages with jqmath to test**
https://docs-staging.datadoghq.com/david.jones/hugo-latest-retry/tracing/guide/span_and_trace_id_format/
https://docs-staging.datadoghq.com/david.jones/hugo-latest-retry/monitors/service_level_objectives/burn_rate/
(Also try starting on a non jqmath page and then navigating to one)
**Please check other random docs pages again** …
> hugo latest retry

- content/en/tracing/guide/trace_ingestion_volume_control.md
Removes an extra backslash that was causing a link to 404.
Noticed by a translator.
---
> Fix typo'd broken link in an APM guide

- content/en/tracing/trace_collection/library_config/ruby.md
Fixes a broken link on "Configuring the Ruby Tracing Library"
Hotjar comment
---
> Fixes broken link to Ruby tracing source

- content/en/continuous_integration/explore_pipelines.md
Updates the list of CI Visibility Providers from which you can ship logs to Datadog
Hotjar comment
---
> Update list of log providers in CI Visibility

- content/en/account_management/rbac/permissions.md
- layouts/partials/rbac-permissions-table.html
- layouts/shortcodes/permissions.html
- local/bin/py/build/pull_rbac.py
- Removes hardcoded `Logs` section from RBAC permissions page.
- Moves legacy logs definitions under `Log Management` section.
https://datadoghq.atlassian.net/browse/WEB-2573
https://docs-staging.datadoghq.com/brian.deutsch/rbac-empty-table/account_management/rbac/permissions/
---
> [WEB-2573] RBAC permissions page updates

- content/en/tracing/other_telemetry/connect_logs_and_traces/nodejs.md
This PR add's a comment to the tracer initialisation code snippet mentioning the tracer needs to be initialised before the logger is imported.
[APMS-7662](https://datadoghq.atlassian.net/browse/APMS-7662)
---
> Node: Tracer needs to be initialised before logger is imported

- content/en/continuous_integration/setup_tests/javascript.md
Add section to javascript's test instrumentation (CI Visibility) about adding custom tags and metrics to test spans.
Allow users more flexibility on their tests.
* [`jest/mocha`](https://docs-staging.datadoghq.com/juan-fernandez/add-custom-instrumentation-instructions/continuous_integration/setup_tests/javascript/?tab=onpremisesciproviderdatadogagent#add-extra-tags-to-your-tests)
* [`cucumber`](https://docs-staging.datadoghq.com/juan-fernandez/add-custom-instrumentation-instructions/continuous_integration/setup_tests/javascript/?tab=cucumber#add-extra-tags-to-your-tests)
* [`cypress` (works slightly differently)](https://docs-staging.datadoghq.com/juan-fernandez/add-custom-instrumentation-instructions/continuous_integration/setup_tests/javascript/?tab=cypress#add-extra-tags-to-your-test) …
> [ci-visibility] Add Instructions to set custom tags and metrics

- content/en/continuous_integration/setup_pipelines/github.md
- content/en/infrastructure/livecontainers/_index.md
Adds two Datadog blog post links to the public docs.
- GitHub Actions in CI Visibility
- K8s anomalies in Live Containers
Docs team Tuesday tasks. Help direct users to the blog.
---
> Add blog links to docs for Tuesday tasks

- content/en/developers/community/libraries.md
Updates Dynatrace Plugin broken link
- KO: https://github.com/Dynatrace/Dynatrace-AppMon-Datadog-Plugin
- OK: https://github.com/sworisbreathing/Dynatrace-Datadog-Plugin
Current link is broken.
I'm not sure this is a replacement for the old link but it's the closest I found.
---
> Update Community Dynatrace Plugin broken link

- content/en/serverless/installation/java.md
Correct the agent jar location.
Motivated by this PR: https://github.com/DataDog/documentation/pull/14724
---
> [Serverless Java] correct jar location

- content/en/logs/guide/reference-tables.md
Add documentation for audit trail, change events, and setting up event monitor for reference tables
---
> Add documentation for Reference Table audit trail and change events

- content/en/monitors/notify/variables.md
Adds documentation on the `status` variable of individual monitors within a composite.
---
> Add docs on composite a.status variable

- .gitlab-ci.yml
- Makefile
- Make sure we download examples fresh on live
- Improve the ref selection when cloning example client repos
master branches always use the version from sdk version
other branches attempt to use the current branch name in the client repo, if that associated branch doesn't exist it falls back to the sdk version
Api discussion
https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/161950791
---
> clean examples on live & better branch selection

- content/en/serverless/enhanced_lambda_metrics/_index.md
Add description of the `aws.lambda.enhanced.post_runtime_duration` metric.
The Lambda Extension will now create the `aws.lambda.enhanced.post_runtime_duration` which is the time after the function returns the response to when the function finishes executing. We expect this metric to be released in the next version of the extension.
---
> Add `post_runtime_duration` metric

- content/en/monitors/create/configuration.md
- content/en/monitors/create/types/metric.md
- content/en/monitors/guide/reduce-alert-flapping.md
We renamed monitor query aggregations in the UI and this is the corresponding docs change. Here's a mapping of the new names:
`on average` -> `average`
`at least once` -> `max`
`at all times` -> `min`
`in total` -> `sum`
---
> Rename monitor query aggregations

- local/bin/py/build/actions/format_link.py
The precommit was moving links inside the `site-region` sections to the
end of the document, causing them to break. This alters that behavior
to mimic links that are in tabs or `programming-lang` sections.
---
> Add region sections to format-links precommit

- local/bin/py/build/actions/format_link.py
This change caused the build to fail on some integrations.
This reverts commit 291653b3362b777f85654f04d6c203284f2a3602.
---
> Revert "Add region sections to format-links precommit (#14818)"

- content/en/tracing/trace_collection/library_config/go.md
Adds a mention of the `DD_TRACE_AGENT_PORT` environment variable used by dd-trace-go. The current documentation mentions only the `DD_DOGSTATSD_PORT`, which only applied to dogstatsd metrics, not DD APM traces.
Ported over changes from https://github.com/DataDog/documentation/pull/14079. 
Thanks @moskyb for your PR!
---
> Configuring the Go Tracing Library Edit

- content/en/tracing/trace_collection/library_config/python.md
Fix env var names that were incorrect in our docs. This is what the tracer actually looks for: https://github.com/DataDog/dd-trace-py/blob/9061e297ed22d50e30b0c90d1c013f4b183927f3/ddtrace/settings/config.py#L188-L194
Raised by a customer in a support ticket
---
> [DOCS-3936] Fix propagation env var names

- content/en/real_user_monitoring/frustration_signals/_index.md
Fixing a typo in the documentation that resulted in an unvalid filter for frustration-signals.
---
> Fix typo in documentation for frustration-signal filter

- .gitlab-ci.yml
- local/etc/algolia/docs_datadoghq.json
- local/etc/algolia/docs_datadoghq_preview.json
Since the reorg of the continuous profiler docs we aren't surfacing the same search results. 
This PR should fix this and also fixes the preview indexing job.
Slack
https://docs-staging.datadoghq.com/david.jones/profiler-search/
---
> Update search config for profiler

- content/en/agent/guide/dual-shipping.md
Add a section about how to configure CI Visibility for dual shipping.
**DO NOT MERGE**: There's no Agent nor tracer version released that uses this yet.
API added in https://github.com/DataDog/datadog-agent/pull/12271
We might use it for other products in the future, but the first user will
be CI Visibility so I've documented it like that.
---
> Update dual shipping instructions for CI Visibility API

- content/en/containers/kubernetes/log.md
Update the example where you can collect logs from a log file within another application container. The current log sample used a "dummy" container, the new sample can be actually deployed to create these logs in a way that the Agent can access them. So a much more "real" example a customer can follow.
Additionally changes the formatting a bit to better highlight requirements of this, rather than including them as bullet point notes. 
Clear up the example
https://docs-staging.datadoghq.com/jack.davenport/k8s-logs/containers/kubernetes/log/?tab=daemonset#examples---log-collection-from-file-configured-in-an-annotation
_Current:_
- https://docs.datadoghq.com/containers/kubernetes/log/?tab=daemonset#examples---log-collection-from-file-configured-in-an-annotation
---
> Update container log file example

- content/en/api/latest/_index.md
Add the header names for the API and application keys to the API intro doc to save users some time looking for them.
---
> Add API and app key header names to intro doc

- content/en/tracing/service_catalog/service_definition_api.md
The param for "name of a service" in the Service Definition API is "dd-service", not "dd-version". It's correct elsewhere on the page, so I think it's just a typo here =] This PR fixes the typo!
I was copying example code from the docs and it didn't work! Then, I realized the typo.
Thank you for the docs!
---
> Fix typo in example code

- content/en/tracing/troubleshooting/tracer_startup_logs.md
Directs readers of the startup logs to refer to debug tracer log instructions when trying to figure out how to log to a file.
To avoid duplicating instructions, but to ensure https://docs.datadoghq.com/tracing/troubleshooting/tracer_debug_logs/?code-lang=python gets referenced.
Should be reviewed by someone from the Python APM team.
---
> Direct startup logs docs to debug tracer logs for file instructions

- layouts/api/list.html
- layouts/partials/api/endpoint-visibility.html
It can be confusing when a v2 api endpoint goes GA as the docs will suddenly display the existing v1 tab as `v1 (deprecated)`. This kind of labeling can cause customers to believe the api they are using is soon to be disabled which isn't the case.
This PR keeps the deprecated label on endpoints using `x-deprecated` but anything else will just display the version.
API discussions
https://docs-staging.datadoghq.com/david.jones/version-tablabel/api/latest/metrics/#submit-metrics
---
> API tab labels only say deprecated when x-deprecated flag set

- assets/scripts/components/async-loading.js
- assets/scripts/components/grouped-item-listings.js
- assets/scripts/datadog-docs.js
- layouts/partials/grouped-item-listings.html
- layouts/security_rules/list.html
This PR makes the security rules layout more reusable:
- Renames the js and initialize
- Splits out the layout into its own partial
Initial step towards
https://datadoghq.atlassian.net/browse/WEB-2572
Check that the ootb rules pages are working as expected still
https://docs-staging.datadoghq.com/david.jones/update-rules/security_platform/default_rules/#all
---
> WEB-2572 - security rules layout more reusable

- content/en/tracing/trace_collection/library_config/python.md
Add documentation for `DD_TRACE_SAMPLING_RULES` for Python tracing configuration in all languages
For translations, in addition to adding `DD_TRACE_SAMPLING_RULES` above for the Python configs, these `DD_TRACE_SAMPLE_RATE` and `DD_TRACE_RATE_LIMIT` are missing from the French and Japanese translations.
---
> docs(apm): add python configuration for trace sampling rules

- content/en/logs/log_configuration/archives.md
Remove unsupported storage class S3 Intelligent Tiering
---
> Remove unspported storage class

- content/en/tracing/trace_collection/library_config/python.md
Missing definition list directive.
---
> Fix formatting in python library config

- content/en/monitors/notify/variables.md
Follow up PR of #14958
Fixes status names and changes their order.
---
> reorder and fix status names

- content/en/tracing/trace_collection/dd_libraries/php.md
Just add a remark on appsec module being loaded even if not enabled. 
This follows questions asked on #support-apm
---
> [Tracer][PHP] Add remark on appsec module being loaded even if not enabled

- local/etc/algolia/docs_datadoghq.json
- local/etc/algolia/docs_datadoghq_preview.json
indexes `containers/` pages in Algolia.
https://datadoghq.atlassian.net/browse/WEB-2626
- There should be 1 search result for the `containers/kubernetes/data_collected` page: https://docs-staging.datadoghq.com/brian.deutsch/containers-indexing/search/?s=kubernetes.liveness_probe.success.total
- Searching for `kubernetes` from either the search page or home/left-side nav dropdowns should surface some results from `containers/` pages.   Same for `amazon ecs`, `cluster agent`, etc.
---
> [WEB-2626] Index top-level containers pages

- content/en/profiler/enabling/nodejs.md
- content/en/security_platform/application_security/setup_and_configure.md
- content/en/tracing/trace_collection/compatibility/nodejs.md
- content/en/tracing/trace_collection/dd_libraries/nodejs.md
Update compatibility information for dd-trace-js 3.0 release.
Update compatibility information for dd-trace-js 3.0 release. This includes dropping support for Node 12 and documenting our OS support policy.
Node 12 is end of life, and our OS support policy was never properly documented.
---
> update compatibility information for dd-trace-js 3.0 release

- content/en/agent/guide/dual-shipping.md
Update the recommended configuration. Logs agent doesn't support the `https://` prefix for additional endpoint URLs. 
Correctness
---
> remove HTTPS from logs dual shipping urls

- static/resources/yaml/datadog-agent-aks.yaml
- static/resources/yaml/datadog-agent-all-features.yaml
- static/resources/yaml/datadog-agent-apm.yaml
- static/resources/yaml/datadog-agent-logs-apm.yaml
- static/resources/yaml/datadog-agent-logs.yaml
- static/resources/yaml/datadog-agent-npm.yaml
- static/resources/yaml/datadog-agent-vanilla.yaml
- static/resources/yaml/datadog-agent-windows-all-features.yaml
- static/resources/yaml/datadog-agent-windows-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs.yaml
- static/resources/yaml/datadog-agent-windows-vanilla.yaml
Update sample manifests to go from Agent `7.35.2` -> `7.38.2`, Helm `2.33.6` -> `2.37.4`.
Keep up to date
https://docs-staging.datadoghq.com/jack.davenport/k8s-daemonset-7.38/containers/kubernetes/installation?tab=daemonset
---
> Update sample manifests for 7.38.2

- content/en/real_user_monitoring/guide/proxy-rum-data.md
This PR updates the RUM SDK proxy configuration guide to clearly warn the reader about the security risk of not validating the `ddforward` attrbute.
Not ensuring the ddforward parameter points to a valid Datadog RUM URL can lead to SSRF/XSS attacks.
- The list of URL patterns was taken from the [SDK source code](https://github.com/DataDog/browser-sdk/blob/e88668449d898b549e3168c79e96cf744c9e1324/developer-extension/src/background/intakeUrlPatterns.ts), omitting URLs used in older versions of the SDK.
- Formatting (i.e: writing **important**) was inspired from the [AWS Integration Billing](https://docs.datadoghq.com/account_management/billing/aws/#overview) page.
---
> Update RUM SDK proxy configuration guide

- content/en/profiler/enabling/dotnet.md
- content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
- content/en/tracing/trace_collection/dd_libraries/dotnet-framework.md
Simplifies the .NET tracer/profiler install instructions 
After [this PR](https://github.com/DataDog/dd-trace-dotnet/pull/3060), the MSI sets the `COR_PROFILER` and `CORECLR_PROFILER` variables globally, so there's no need to set them manually. Only applies to Windows MSI install option
https://docs-staging.datadoghq.com/andrew/update-env-vars/profiler/enabling/dotnet
https://docs-staging.datadoghq.com/andrew/update-env-vars/tracing/trace_collection/dd_libraries/dotnet-core.md
https://docs-staging.datadoghq.com/andrew/update-env-vars/tracing/trace_collection/dd_libraries/dotnet-framework.md
N/A
> Remove references to `COR_PROFILER` that are no longer needed with MSI

- content/en/real_user_monitoring/browser/modifying_data_and_context.md
- Update RUM Global Context APIs
- Update/Add Session User APIs
- Document the name changes
We have expanded the API behaviour of Session User APIs and used this as an occasion to fix some of the issues present in the underlying code. We expanded the changes to also to fix similar issues in RUM Global Context.
- Relates to changes made Logs Global context https://github.com/DataDog/browser-sdk/pull/1695
---
> Update Session User and RUM Global Context APIs

- content/en/tracing/trace_collection/compatibility/python.md
Documents graphql integration in the python tracer. The graphql-core integration was introduced in the ddtrace v1.4.0.
Sync corp docs with dd-trace-py in-app docs.
---
> add graphql-core integration to docs

- content/en/serverless/installation/java.md
Adds a minimum recommended memory configuration when using datadog-lambda-java.
Increasing memory significantly improves Java performance in Lambda, and 1024 provides a safe base line for our tracer.
---
> Add minimum memory recommendation to Lambda Java

- content/en/agent/basic_agent_usage/_index.md
- content/en/agent/basic_agent_usage/osx.md
Updates documentation about the macOS Agent, detailing which versions of the Agent support which version.
Better documentation on supported versions of the macOS Agent.
[Basic Agent usage page](https://docs-staging.datadoghq.com/kylian.serrania/update-macos-agent-versions/agent/basic_agent_usage/?tab=agentv6v7)
[macOS page](https://docs-staging.datadoghq.com/kylian.serrania/update-macos-agent-versions/agent/basic_agent_usage/osx/?tab=agentv6v7)
---
> [agent] Update supported macOS versions

- content/en/real_user_monitoring/guide/proxy-rum-data.md
List intake url patterns for sdk version < v4
Follow up of #15074 
---
> RUM proxy configuration: add intake url for previous sdk version

- content/en/agent/basic_agent_usage/windows.md
- content/en/agent/faq/agent_v6_changes.md
- content/en/agent/faq/log4j_mitigation.md
- content/en/agent/guide/datadog-agent-manager-windows.md
- content/en/agent/guide/integration-management.md
- content/en/agent/guide/secrets-management.md
- content/en/agent/troubleshooting/agent_check_status.md
- content/en/developers/dogstatsd/datagram_shell.md
- content/en/developers/guide/custom-python-package.md
- content/en/integrations/guide/running-jmx-commands-in-windows.md
Fixes the environment variable syntax in PowerShell commands. `%ProgramFiles%` is for `cmd.exe`. `$env:ProgramFiles` is for `powershell.exe`.
Normalizes the case of the environment variables for consistency between pages and commands, for example `PROGRAMFILES` -> `ProgramFiles`. Though env vars are case insensitive on Windows the latter case matches what is reported by the `env` command in `cmd.exe` and `dir env:` in `powershell.exe`.
Normalizes "PowerShell" case (https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7.2)
PowerShell throws an error if you try to use env vars like `%ProgramFiles%`. The proper syntax is `$env:ProgramFiles`.
xref [WA-44](https://datadoghq.atlassian.net/browse/WA-44)
I think these commands should be updated in the other languages, …
> [WA-44] Fix env var syntax in PowerShell commands

- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/azure.md
- content/en/database_monitoring/setup_postgres/gcsql.md
- content/en/database_monitoring/setup_postgres/rds.md
- content/en/database_monitoring/setup_postgres/selfhosted.md
Adds Postgres 14 to the DBM supported versions lists on each provider page, and on the postgres index.
Support request
---
> (DOCS-3969) Add Postgres v14 to list of supported versions.

- content/en/containers/kubernetes/distributions.md
resource/limit was not apply because is agent key is not present 
https://github.com/DataDog/helm-charts/blob/c75a5effa46d934f5f9952d2bf658823e9170135/charts/datadog/values.yaml#L987
add agents: key to the datadog yaml file, because the resource/limit are not setting ok in gke autopilot
and datadog pod is setting with the default resource/limit and  die by oom
help the gke autopilot users :) 
---
> gke autopilot datadog.yaml missing agents: key

- content/en/dashboards/scheduled_reports.md
Add an alias to the frontmatter of the new scheduled reports documentation to redirect users using the old URL
Mentioned in Slack
https://docs-staging.datadoghq.com/bryce/add-reporting-alias/dashboards/
---
> Add alias to frontmatter

- content/en/dashboards/scheduled_reports.md
Add a trailing slash to the reporting alias
Slack conversation
https://docs-staging.datadoghq.com/bryce/update-alias-format/dashboards/reporting/
---
> Add trailing slash to alias

- content/en/account_management/audit_trail/_index.md
Fixes the visualization from log stream, which does not support Audit Trail events, to the list.
a support case https://datadoghq.atlassian.net/browse/LOGSS-6077
Approved by one of our Log PMs
---
> Fix audit trail viz to list

- content/en/tracing/trace_collection/open_standards/otel_collector_datadog_exporter.md
Some corrections as agreed upon:
> content/en/tracing/trace_collection/open_standards: corrections

- content/en/getting_started/tagging/assigning_tags.md
Update on the wait time for metric tags to appear in the UI.
DOCS-3915
---
> DOCS-3915 Assigning Tags Edit

- content/en/tracing/trace_collection/compatibility/php.md
Adds arm64 support notes to PHP documentation
---
> add arm64 to php documentation

- content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
As of at least @opentelemetry/api@1.1.0, `opentelemetry.getSpan` needs to be `opentelemetry.trace.getSpan`. Looks like the changed happened here: https://github.com/open-telemetry/opentelemetry-js-api/commit/e1745d19b9bdfd1af7d805a6b2c32a5a5dbf4d15
Working on an custom OTEL integration and a subtle hiccup trying to figure out where the `getSpan` comes from. Minor change but can be a little frustrating to new comers.
---
> [DOCS-3983] getSpan is now apart of TraceAPI

- content/en/logs/log_collection/java.md
The documentation and the Getting Started guide of the web-ui differ.
The information from the web-ui is the correct one and the one from the docs is incorrect (or maybe obsolete).
Therefore I have changed the documentation so that it is consistent again
I tried to configure a datadog agent to send logs to Datadog. 
This has not worked because the configuration path from the documentation was wrong:
> Create a file java.yaml in the Agent’s conf.d/ directory with the following content:
[Configure the Datadog Agent](https://docs.datadoghq.com/logs/log_collection/java/?tab=logback#configure-the-datadog-agent)
<br />
Afterwards I tried the path described in the Web-UI and it worked successfully with:
> Create a file java.d/conf.yaml in the Agent’s conf.d/ directory with the following content: …
> [DOCS-3986] Correct datadog agent configuration path

- content/en/continuous_integration/setup_tests/dotnet.md
Add section to dotnet's test instrumentation (CI Visibility) about adding custom tags to test spans.
Same as we did for javascript here: https://github.com/DataDog/documentation/pull/14866
---
> [ci-visibility] Add Instructions to set custom tags in dotnet

- content/en/tracing/troubleshooting/agent_apm_metrics.md
Fix the description of the following Trace Agent metrics
- `datadog.trace_agent.receiver.spans_dropped`
- `datadog.trace_agent.receiver.spans_filtered`
- `datadog.trace_agent.receiver.spans_received`
The descriptions were inaccurate.
The metric descriptions in the Agent code are here 
https://github.com/DataDog/datadog-agent/blob/773dd33dca5887425b90085a8809e289db118ae0/pkg/trace/info/stats.go#L362-L367
---
> Trace Agent metrics: fix spans metric descriptions

- content/en/continuous_integration/setup_tests/python.md
Add section to python's test instrumentation (CI Visibility) about adding custom tags to test spans.
Same as we did for javascript here: https://github.com/DataDog/documentation/pull/14866
---
> [ci-visibility] Add Instructions to set custom tags in python

- content/en/continuous_integration/setup_tests/ruby.md
Add section to ruby's test instrumentation (CI Visibility) about adding custom tags to test spans.
Same as we did for javascript here: https://github.com/DataDog/documentation/pull/14866
---
> [ci-visibility] Add Instructions to set custom tags in ruby

- content/en/agent/proxy.md
- Add guidelines on raw/encrypted communication between the Agent,  proxy and Datadog intake.
- Add Datadog certificate verification on the proxy host.
- Add docs on when and how to encrypt communication between the Agent and the proxy
- Fix some errors :
- telemetry HAProxy frontend was missing after a merge
- AppSec port was different on HAProxy and Nginx + missing in one `datadog.yaml` config
- update the part about `skip_ssl_validation` (which was previously useless because HTTP was used between the Agent and the proxy)
Give better guidelines to customers
https://docs-staging.datadoghq.com/nicolas.guerguadj/aml-100-add-https-guideline-for-proxy-setup/agent/proxy/?tab=agentv6v7
- Did not test `network_devices` but as it is using the same component as `database_monitoring`, the behavior …
> docs(proxy): add ssl guidelines for communication between Agent and Datadog when using a proxy

- content/en/real_user_monitoring/browser/tracking_user_actions.md
- content/en/real_user_monitoring/guide/send-rum-custom-actions.md
Simplifies "custom actions" section and adds a link to the RUM Send Custom Actions guide.
DOCS-3996
---
> DOCS-3996 Tracking User Actions Edit

- content/en/getting_started/tagging/unified_service_tagging.md
URL is pointing to the wrong key (should be `join_standard_tags`).
Incorrect documentation
---
> Use permalink for join_standard_tags integration

- content/en/synthetics/browser_tests/actions.md
Update synthetics email references because they've been moved to another page
The existing links in the public doc were not working anymore.
---
> Synthetics email link rot

- content/en/getting_started/tagging/unified_service_tagging.md
Links specific documentation to the general top of the example config file, rather than trying to maintain the correct line number and version of the example file.
Discussion in https://github.com/DataDog/documentation/pull/15150 
---
> Change permalink to general top-of-file link

- content/en/containers/kubernetes/apm.md
PHP has support for UDS by now, a customer was confused by this obsolete comment. Removed it.
---
> Drop a now obsolete comment about PHP not supporting UDS

- content/en/agent/guide/heroku-ruby.md
Improves the `prerun.sh` sample code for configuring Redis in Heroku to account for secure URLs.
I got an error as follows after following the steps in the setup documentation;
```
2022-08-31 13:18:12 UTC | CORE | ERROR | (pkg/collector/worker/check_logger.go:69 in Error) | check:redisdb | Error running check: [{"message": "invalid literal for int() with base 10: '<YOUR_REDIS_PORT>'", "traceback": "Traceback (most recent call last):
File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py\", line 1120, in run
self.check(instance)
File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/redisdb/redisdb.py\", line 552, in check
self._check_db()
File \"/app/.apt/opt/datadog-agent/embedded/lib/python2.7/site-packag …
```
> Handle secure redis URLs

- content/en/containers/docker/_index.md
Adds a note in the containers page about filtering by namespace when using containerd.
---
> [containers] Add note about filtering by namespace in containerd

- content/en/synthetics/api_tests/http_tests.md
- content/en/synthetics/browser_tests/actions.md
- content/en/synthetics/multistep.md
enrich the sigv4 section following customer feedback
---
> add sha256 empty string for sigv4

- content/en/continuous_integration/setup_pipelines/jenkins.md
This PR adds the instructions to correlate pipelines executed in Jenkins workers with infrastructure metrics for CI Visibility.
---
> [CIAPP] Add instructions to correlate pipelines executed in Jenkins workers with infrastructure metrics.

- content/en/monitors/service_level_objectives/burn_rate.md
- content/en/monitors/service_level_objectives/error_budget.md
Fixes a link 
Link to the [datadog_monitor Terraform resource](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor) was broken on the SLO alerts pages
https://docs-staging.datadoghq.com/kai/slo_alert_tf/monitors/service_level_objectives/error_budget/#api-and-terraform
https://docs-staging.datadoghq.com/kai/slo_alert_tf/monitors/service_level_objectives/burn_rate/#api-and-terraform
---
> Fix broken links on SLO Alerts pages

- content/en/agent/guide/dual-shipping.md
Update DD domains to the standard domains that are used by the standard DD intakes,
which should be relevant for most customers.
This will make the examples on this page easier-to-use out of the box.
Follow ups planned to make a similar update on this page for the other data types documented on the page.
---
> [dual-shipping] Update DD domains for metrics, traces and logs

- content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
Adding an additional comment/note under step 3 for Configure the Datadog Agent for APM. The notes addresses the required version of .NET in order for UDS to work, which was discovered in debug logs from ticket (https://datadog.zendesk.com/agent/tickets/888404)
Adds an additional note for the .NET tracer configuration for UDS
A customer was setting up .NET tracer for UDS, but was using .NET 2.1. The discrete error in their debug logs showed that .NET 3.1 or higher is required so APM T2 and I thought it would be useful to call this out on our public-facing documentation.
Related ticket: https://datadog.zendesk.com/agent/tickets/888404
---
> Update .NET version required for UDS

- content/en/monitors/create/types/metric.md
- Move the steps currently under `Define the metric` in the UI to the `Define the metric` section in the documentation.
- Updates the `Steps` and `Definitions` tables under the `Threshold` tab accordingly.
- Removes `Threshold`/`Change` tab section from `Set alert conditions` section, because the difference is now listed under the `Define a metric` section.
- Removes outdated information about timeframe constraints.
- Copy edits as per our [contributing guidelines](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md).
DOCS-3933
DOCS-3951
https://docs-staging.datadoghq.com/bryce/update-metric-monitor-docs/monitors/create/types/metric/
This change involves significant restructuring of the documentation to match the UI options, and I'm open to feedback or additional …
> (DOCS-3933) Update metric monitor doc for new UI

- content/en/monitors/create/types/apm.md
- content/en/monitors/create/types/log.md
- content/en/monitors/create/types/real_user_monitoring.md
Update the warning notes on event-based monitors that mention the default limit of 1000 monitors per account. This is to achieve consistency with the recently updated event monitor documentation:
https://github.com/DataDog/documentation/pull/15145
DOCS-3944
[APM monitors](https://docs-staging.datadoghq.com/bryce/update-monitor-limit-notes/monitors/create/types/apm/?tab=traceanalytics)
[Log monitors](https://docs-staging.datadoghq.com/bryce/update-monitor-limit-notes/monitors/create/types/log/#monitor-creation)
[RUM monitors](https://docs-staging.datadoghq.com/bryce/update-monitor-limit-notes/monitors/create/types/real_user_monitoring/#create-a-rum-monitor)
---
> (DOCS-3944) Update monitor limit note

- content/en/synthetics/settings/_index.md
Updating to make this more clear.
Global variables need to be imported before they can be used in a test. Users will face a "Unknown variable" error if they do not import them first.
Customers facing error
---
> Sarah_Hart/Add information on importing variables

- content/en/database_monitoring/setup_mysql/aurora.md
Fix docs to specify the correct value of the DB parameter group settings for Aurora.
Several of these fields should be "1" instead of "ON" according to AWS documentation. Setting them to "ON" gets them coerced to "1", resulting in never-ending dirty plans if the customer is using Terraform.
---
> Fix DB parameter group settings for Aurora

- content/en/getting_started/tagging/_index.md
Remove an outdated note about certain tags being excluded from lower-casing when sent to Datadog. Details about how these tags can be excluded from lower-casing have been moved to the API docs:
https://docs.datadoghq.com/api/latest/metrics/#submit-metrics
DOCS-3795
https://docs-staging.datadoghq.com/bryce/update-tag-note/getting_started/tagging/#define-tags
---
> (DOCS-3795) Remove outdated tagging note

- content/en/continuous_integration/setup_tests/containers.md
Updates the list of environment variables set by the distinct CI providers we ask our users to forward inside a container when our tracer runs containerized, to match [the env vars that our tracers read](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/ext/ci.py).
A customer realized some were missing.
---
> Update list of CI env vars to be passed to containers

- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
This PR removes the code snippet instructions for Sampling Rate settings for the Ruby language: environment variables are recommended instead. They are simple and accomplish the same goal.
The previous language documented a more verbose and error prone approach to sampling configuration.
https://docs-staging.datadoghq.com/marcotc/sampling-docs/tracing/trace_pipeline/ingestion_mechanisms/?tab=ruby
---
> APM:Recommend Ruby environment variables only for sampling rates

- content/en/tracing/guide/ignoring_apm_resources.md
This corrects the misleading/invalid documentation for filtering spans.
When I attempted to use `delete_if` in my code I got a NoMethodError: 
```
#<NoMethodError: undefined method `delete_if' for #<Datadog::Tracing::TraceSegment:0x000000012056f560>>
```
From looking at the Post processing traces section in the Ruby Custom Instrumentation doc (https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/ruby/?tab=activespan#filtering), I found that the correct way to do this was with a Span Filter.
---
> Remove `delete_if` from Ruby example of post-processing spans

- content/en/serverless/installation/python.md
Fixes a copy-pasted variable that the python CDK construct doesn't accept.
Wanting the variable to be correct.
---
> fix incorrect Python CDK variable

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
These doc pages were previously marked as `beta: true`, they are generally available now, so these pages should be indexed by Google Search.
Discussion with @louiszawadzki!
---
> Make RUM & Session Replay Docs Searchable 

- layouts/shortcodes/integrations.html
This is to fix the yaml data file dependency on Corp, allowing Integration tiles to be referenced again by DG landing pages
Integration partial no longer loading proper data because this id value is missing
https://docs-staging.datadoghq.com/nsollecito/integrations-id/integrations/
---
> Add id to integrations card

- content/en/tracing/trace_collection/library_config/nodejs.md
Adds docs for the `DD_TRACE_SAMPLING_RULES` feature in dd-trace-js.
The feature was just released, should have docs for it.
---
> Add DD_TRACE_SAMPLING_RULES to Node.js

- content/en/profiler/connect_traces_and_profiles.md
Adds PHP information to the section on endpoint profiling.
I added this feature and it ships in v0.79.0 of the PHP tracer, which is in draft at this time.
Is there an order we ought to be putting these languages in? Order by general APM usage? Alphabetical? Order they were added?
---
> Add PHP to endpoint profiling

- content/en/containers/kubernetes/distributions.md
Updates the note about the OOM kill and TCP queue length checks on GKE because they're working now.
---
> [kubernetes/distributions] Update note about OOM kill and TCP queue length on GKE

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
- Fix the incorrect policy in the document `kinesis:PutRecordBatch` to `kinesis:PutRecords`. `kinesis:PutRecordBatch` does not exist.
- ~~Add note for pushing logs directly to Kinesis Firehose delivery stream. Reference: [AWS doc](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html).~~ (removed)
- See those problem when try to implement CloudWatch logs subscription myself
---
> Fix incorrect policy in the document and add note

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
Adds the automatic triggers link to API Gatway
DOCS-3670
https://docs-staging.datadoghq.com/bryce/add-api-gateway-automatic-triggers-link/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole#enable-logging-for-your-aws-service
---
> (DOCS-3670) Update API Gateway log collection options

- content/en/containers/kubernetes/prometheus.md
* Adds curly brackets `{}` around the instance to have a valid JSON and thus have the check working
* Removes `init_config` from the annotations as it doesn't add anything and is not necessary
* Lines up the items in `metrics`
* Testing the example in my sandbox resulted in a failure, thus it misleads customers
* To Q/A, run a local cluster, deploy with the updated annotations and the Agent, ensure an `openmetrics` gets correctly scheduled
---
> Fixes V2 annotations to have an actual working example

- content/en/serverless/installation/dotnet.md
ARNs listed do not exist and result in an error on the AWS side.
https://datadog.zendesk.com/agent/tickets/941757 
https://github.com/DataDog/dd-trace-dotnet-for-lambda/releases/tag/v5
---
> Fix: Remove "Datadog-" from ARNs for dd-trace-dotnet

- content/en/tracing/trace_collection/library_config/python.md
Fix the default port according to source: https://github.com/DataDog/dd-trace-py/blob/685b0b46e21517b4dfd06a70e41ddb8e5a0d7253/ddtrace/internal/agent.py#L16
> Correct default for DD_DOGSTATSD_PORT

- content/en/integrations/observability_pipelines/integrate_vector_with_datadog.md
Vector doesn't provide full support of traces yet, as we've discovered a few issues that need to be addressed next quarter. As it's only beta support, removing mentions of traces for now
---
> Remove mention of traces

- .gitignore
This integration lives in integrations-core, so it looks like we can remove it from the gitignore exclusions list. It keeps showing up in local builds.
---
> Remove iam_access_analyzer.md from .gitignore exclusions

- layouts/partials/rum/rum-getting-started.html
Removes beta header for the Flutter tile on the RUM & Session Replay product landing page.
#dd-sdk-flutter Slack
---
> Flutter SDK GA Release

- content/en/logs/log_configuration/archives.md
Adds a reminder to refer to AWS inter-region data transfer pricing for consideration when choosing the region for your storage bucket.
Beachbody LLC | 394476 | tier 0 | https://datadoghq.atlassian.net/browse/LOGSS-6148
---
> Adds data-transfer fee consideration when creating S3 bucket

- .gitignore
- config/_default/menus/menus.en.yaml
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Single sources a doc page for Appcenter Codepush into the React Native Monitoring docs.
DOCS-4056
https://docs-staging.datadoghq.com/alai97/reactnative-codepush-doc-update/real_user_monitoring/reactnative/codepush
Remember to update the `pull_config.yaml` file back to `main` before merging!
---
> DOCS-4056 Adds CodePush Documentation

- content/en/tracing/other_telemetry/connect_logs_and_traces/php.md
```php
sprintf(
' [dd.trace_id=%d dd.span_id=%d]',
$context['trace_id'],
$context['span_id']
);
```
- By using this `%d` specifier, the `$context['trace_id']` will be considered as an integer.
- In case the `trace_id` is greater than `9223372036854775807` (the max value), it always return `9223372036854775807` in the output message
- The result is the Log can't be connected with the APM Trace, because actual `trace_id` is different than `9223372036854775807`
- I had an issue when connecting the log and APM Trace in some cases, and found out that there are duplicated trace_id appeared with the id `9223372036854775807`.
- Hope this PR can help.
---
> Update Monolog Message Format

- content/en/monitors/create/configuration.md
Documents maximum value for evaluation delay in monitor docs.
---
> [Monitors] Add upper bounds of evaluation delay in documentation

- content/en/developers/dogstatsd/_index.md
this updates the dogstatsd setup docs with a note on the Kubernetes tab regarding how to set the hostPort option with the operator
from customer request on this ticket: https://datadog.zendesk.com/agent/tickets/925042
> update dogstatsd docs with note on operator config

- content/en/metrics/otlp.md
Adds disclaimer about histograms being approximations.
slack
---
> [DOCS 3916] - add disclaimer for otlp histograms

- translate.yaml
Re-enable the github-transifex pipeline
Needed to disable temporarily for a large PR #15314 
n/a
---
> Enable github-transifex syncing again

- local/bin/py/build/actions/pull_and_push_file.py
- local/bin/py/build/actions/pull_and_push_folder.py
Some shortcodes that are in files in external repos have indentation issues.
This PR cleans spaces or tabs before a shortcode during import to avoid broken pages.
This came to light while testing shortcode usage swap.
https://docs-staging.datadoghq.com/david.jones/cleanup-indent/logs/log_collection/ios/
---
> indent cleanup

- local/bin/py/build/actions/integrations.py
Make sure integrations content containing markdown shortcode `aws-permissions` is not converted to use `< >` delimiter yet.
This is a quick fix, we will need a better long-term solution ensuring markdown shortcodes are handled properly when pulling content into the docs build.
Slack: https://dd.slack.com/archives/C0DESMBQU/p1663847183212829
https://docs-staging.datadoghq.com/brian.deutsch/aws-integration-fix/integrations/amazon_web_services/#manual
---
> AWS integrations page unrendered markdown quick fix

- content/en/integrations/syslog_ng.md
Add region shortcode for logs tcp intake and shortcode for port
https://datadog.zendesk.com/agent/tickets/906530
- Customer could not see logs as they were sending it to the wrong site and port based on the configuration.
---
> Add configuration options based on region

- content/en/getting_started/containers/datadog_operator.md
> Remove unnecessary 'agent_spec' from kubectl apply comamand

- content/en/agent/logs/_index.md
In the docs current state, it isn't clear how a Windows user would tail a custom log file. This gets tricky since the syntax is not clear considering even if they knew to use the Windows file path, they have to use two slashes and also verify the ddagentuser has the proper permissions to access the file.
Adds an example path for Windows user for tailing custom log files. 
https://datadog.zendesk.com/agent/tickets/942473
I recently worked with my peer on this ticket here. I found no documentation for tailing custom logs on Windows. After some sandboxing I found that the proper way to configure the log file was with double backslashes. 
Once I figured out the backslash issue, I still struggled with the permissions. So I included that as well! 
---
> added path example for windows users

- content/en/tracing/trace_collection/open_standards/otlp_ingest_in_the_agent.md
Tested with the latest release candidate of the agent, note this brings this tab into alignment with the `host` tab
---
> OTLP CONFIG vars take full endpoints not ports

- content/en/containers/kubernetes/log.md
Provide an example of the environment variable and the expected value type
https://datadog.zendesk.com/agent/tickets/859823
Customer on this ticket used an unsupported value type for this variable (ex. '5s'), which disrupted their logging configuration. They requested that the value type be listed in the documentation.
There was a PR for a config change which the customer referenced https://github.com/DataDog/datadog-agent/pull/12583
---
> Provide explicit example of the env variable value

- content/en/continuous_integration/setup_pipelines/custom_tags_and_metrics.md
This PR adds `Jenkins` as a supported provider in the `Custom tags and metrics` section with a link to its specific instructions.
---
> [ci visibility] Add link to Jenkins instructions in custom tags and metrics

- content/en/tracing/guide/trace_ingestion_volume_control.md
- content/en/tracing/metrics/metrics_namespace.md
When setting up some trace sampling with OpenTelemetry (sdk / collector level), APM metrics are affected. Adding a note about this behaviour in the ingestion volume control guide and in the APM metrics docs
---
> call-out of OpenTelemetry sampling effect on APM metrics accuracy

- content/en/tracing/trace_collection/compatibility/java.md
- content/en/tracing/trace_collection/dd_libraries/java.md
This PR describes the JVM compatibility for Java tracer.
Additionally, it introduces the new download link for major versions.
We need to define clear statement about supported JVM for the current and coming versions of the Java tracer.
@bantonsson Can you review the content to check it matches what you expected?
Compared to the original document, I added mentions to Oracle JDK and OpenJDK, and also the non-support rule for early access builds.
---
> Add Java tracer compatibility matrix and new download links

- content/en/logs/explorer/facets.md
This edit was suggested by a customer when I found out that facets can't be added to Array objects (after consultation with T2 in Logs OH). The workaround is to extract the attribute in Array object and then remap it. The extracted attribute will have the 'create facet' option.
---
> Adding a note about Array objects

- content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
- content/fr/real_user_monitoring/guide/compute-apdex-with-rum-data.md
- content/ja/real_user_monitoring/guide/compute-apdex-with-rum-data.md
It fixes json definition for the appdex graph
Current json code is broken
---
> fix apdex graph json definition

- local/bin/py/build/content_manager.py
When sourcing local adjacent repos some of the scripts would manipulate the files.
Slack conversation seeing some files deleted
https://docs-staging.datadoghq.com/david.jones/fix-local-deleting-files/
Test local development trying
```
make clean-dependent-repos
make start
```
and then
```
make start
```
---
> local dev fix removing files from adjacent repos

- Makefile
- Makefile.config.example
- README.md
Reintroduces `FULL_BUILD` parameter to `Makefile.config` to build the full docs with Docker.
https://datadoghq.atlassian.net/browse/WEB-2737
https://docs-staging.datadoghq.com/brian.deutsch/docker-full-build/   (nothing should be affected in preview)
testing locally: 
in `Makefile.config` add `FULL_BUILD := true` and follow instructions in readme to start Docker.   this should build the full docs including all external content.   change `FULL_BUILD := false` or remove the parameter.   the lightweight docs should run without the prebuild content.
---
> [WEB-2737] Allow full docs build when running in Docker container

- .github/workflows/approved_status.yml
- .github/workflows/bump_versions.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- content/en/tracing/guide/ignoring_apm_resources.md
Document backend added span tags as unusable to exclude traces at the Agent Level
https://datadoghq.atlassian.net/browse/APMS-7745
---
> Backend added tags documentation

- content/en/network_monitoring/devices/guide/migrating-to-snmp-core-check.md
Code spacing was off and made a customers config fail. It was: 
metrics:
-MIB: HOST-RESOURCES-MIB
symbol:
It is now:
metrics:
- MIB: HOST-RESOURCES-MIB symbol:
Updates the public documentation
Errors customer was running into:
https://a.cl.ly/xQuxj5db
Check the alignment of the last code block, I wasn't sure about it but it still looks off to me
---
> Fixed Spacing and alignment issues in code samples

- content/en/continuous_integration/setup_tests/python.md
Fix the instructions to get the current test span from a `pytest` test.
Current instructions are wrong.
https://docs-staging.datadoghq.com/juan-fernandez/fix-python-ci-docs/continuous_integration/setup_tests/python/?tab=azurepipelines#adding-custom-tags-to-tests
---
> [ci-visibility] Fix active test span in python docs

- content/en/containers/docker/_index.md
The document lists the environment variable DD_DOGSTATSD_DISABLE to disable sending custom StatsD metrics. The customer had used this variable, but they got this error - "Unknown environment variable: DD_DOGSTATSD_DISABLE".
After discussing with engineering, I was advised to use DD_USE_DOGSTATSD instead. This must be set to false to disable the custom metrics. The customer tried this and it worked fine.
Replace the environment variable DD_DOGSTATSD_DISABLE in the document with DD_USE_DOGSTATSD
---
> Replace DD_DOGSTATSD_DISABLE with DD_USE_DOGSTATSD

- content/en/monitors/notify/_index.md
- content/en/security_platform/notifications/_index.md
- layouts/shortcodes/notifications-email.md
- layouts/shortcodes/notifications-integrations.md
Adds a general reuse short code for Alerting notifications and Security notifications docs.
DOCS-3885
---
> [DOCS-3885] Add general reuse code for notification docs

- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
Tweaks the wording around "maps" in configuration environment variables
We had an issue raised on the .NET Tracer indicating this wording was confusing: https://github.com/DataDog/dd-trace-dotnet/issues/3278
https://docs-staging.datadoghq.com/andrewlock/dotnet-tweak-map-wording/tracing/trace_collection/library_config/dotnet-core
https://docs-staging.datadoghq.com/andrewlock/dotnet-tweak-map-wording/tracing/trace_collection/library_config/dotnet-framework
> APM > .NET > Update wording around maps in config

- content/en/developers/_index.md
- content/en/getting_started/application/_index.md
Adds a link to the DRUIDS blog post to the Datadog Developer docs as well as the `Getting Started with Datadog` page. 
As a side note, I'm not totally convinced that `Getting Started with Datadog` is a good place for this link, so I'm open to feedback in that regard.
Spread awareness of the new Datadog blog post.
Developer doc:
https://docs-staging.datadoghq.com/bryce/add-druids-blog-link-to-further-reading-section/developers/#further-reading
Getting Started with Datadog:
https://docs-staging.datadoghq.com/bryce/add-druids-blog-link-to-further-reading-section/getting_started/application/#further-reading
---
> Add blog link to Further Reading section

- content/en/serverless/google_cloud_run/_index.md
Updated instructions based on a couple recent customer questions to state what they need to accomplish with the Dockerfile changes instead of setting expectation that it will always be copy and paste. Broke into two sections: 1. Build your Container, 2. Deploy to Cloud Run have a clearer split point where customers may begin using their own CI/CD and secrets tooling instead of the basic GCP ones.
---
> Cloud Run edits

- assets/scripts/datadog-docs.js
fixes the scroll to top functionality on the left nav. A top-level nav item should come into view when opened.
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-2516
https://docs-staging.datadoghq.com/stefon.simmons/fix-scroll-left-to-selected-pg/getting_started/agent/
---
> Fixed left nav scrolls to top - [WEB-2516]

- translate.yaml
Temporarily exclude some file paths from being included in the Transifex-Github sync.  We will re-enable these after running some data cleanup scripts in Transifex.
https://datadoghq.atlassian.net/browse/WEB-2718
n/a
---
> [WEB-2718] Exclude files from Transifex syncing

- content/en/containers/docker/_index.md
This PR updates the documentation with the supported Windows versions for containers.
We are ending support for EOLd Windows container versions 1909, 2004 and 20H2 with 7.39.x as the last supported Windows Agent version for these versions. Therefore, the documentation needs to be updated with the new supported versions.
xref [WA-86](https://datadoghq.atlassian.net/browse/WA-86)
---
> Update public documentation for Windows container support

- content/en/tracing/trace_collection/custom_instrumentation/cpp.md
The C++ tracer was recently [updated][1] with changes that affect how `error.*` tags are handled. This is the corresponding documentation update.
---
[1]: https://github.com/DataDog/dd-opentracing-cpp/pull/244
> more detail in the C++ tracing error tagging section

- content/en/monitors/service_level_objectives/monitor.md
Add a sentence explaining how SLOs treat Synthetic no data periods, following the release of the new unified no data monitor settings
https://docs-staging.datadoghq.com/kai/synthetic-slo-no-data/monitors/service_level_objectives/monitor/#missing-data
---
> Add note on Synthetics no data

- content/en/monitors/create/types/error_tracking.md
- content/ja/monitors/create/types/error_tracking.md
Removes documentation on a feature not supported by the Error Tracking monitors
[Zendesk ticket](https://datadog.zendesk.com/agent/tickets/956252) from a customer reporting the mistake on our documentation website
N/A
---
> Remove toplist documentation from ET monitors (feature not supported)

- config/_default/menus/menus.en.yaml
- content/en/continuous_integration/setup_tests/javascript.md
* Add note about CI Visibility support for typescript. 
* Move cypress>=10 instructions above cypress<10. 
* Fix minor issues with cypress docs.
* Make it clearer that we support typescript
* Make it easier for cypress users
---
> [ci-visibility] Add note about TypeScript and fix minor issues with cypress docs

- content/en/profiler/connect_traces_and_profiles.md
Updates a warning in the Go Code Hotspots documentation. This warning called out several bugs that
could affect the accuracy of Code Hotspots. These bugs have been fixed for the past few Go
releases.
The warning is no longer necessary, though it's still worth noting that the feature works
best with more recent Go versions.
---
> go: Update Go version required in Code Hotspots documentation

- content/en/monitors/create/configuration.md
Clarify further that the "Group Retention Time" only works with multi-alert monitors THAT ARE ALSO monitors that support the "On missing data" feature (APM Trace Analytics, Audit Logs, CI Pipelines, Error Tracking, Events, Logs, and RUM monitors).
https://docs.datadoghq.com/monitors/create/configuration/?tab=othermonitortypes#group-retention-time
---
> Clarification on supported monitors for "Group Retention Time"

- content/en/tracing/troubleshooting/tracer_debug_logs.md
Fix Broken link:
Change: https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html
To: https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html
> Fix Broken slf4j link

- content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
- content/en/tracing/trace_collection/dd_libraries/dotnet-framework.md
Rename Datadog.Monitoring.Distrib into Datadog.Trace.Bundle. It simplifies the documentation as we make it leave in our repo or on the package documentation itself. cf https://github.com/DataDog/dd-trace-dotnet/pull/3263
This setup is now GA.
---
> Rename Datadog.Monitoring.Distrib into Datadog.Trace.Bundle

- content/en/tracing/guide/agent-5-tracing-setup.md
Changes "blacklist" to "exclude list" to match our style guide rules for inclusive language.
DOCS-4188
Exclude list appears in our docs twice. Not seeing any use of the term "disallow list".
---
> Change blacklist to exclude list

- content/en/continuous_integration/guides/_index.md
- content/en/continuous_integration/guides/pull_request_comments.md
Change guide title for GitHub pull request comment integration
The titles didn't align on the two pages affected
---
> Change guide title

- content/en/monitors/notify/downtimes.md
Adding the information that when downtimes are manually canceled, no notifications are sent.
Remove the sentence "If a downtime is manually canceled, notifications will not be sent, even if the monitor has entered an alert-worthy state" after it was added in https://github.com/DataDog/documentation/pull/14694.
Downtimes had a bug and were behaving in an unexpected way. We didn't catch this in the first escalation.
escalation with bug fix: https://datadoghq.atlassian.net/browse/MNTS-89107
initial escalation: https://datadoghq.atlassian.net/browse/MNTS-88918
[link](https://docs-staging.datadoghq.com/dan.chiniara/remove-downtime-sentence-about-manual-cancels/monitors/notify/downtimes/?tab=bymonitorname#expiration) | [screenshot](https://a.cl.ly/4gueevBw)
> dan.chiniara/remove downtime sentence about manual cancels

- layouts/shortcodes/latest-lambda-layer-version.html
Changes dotnet version from 5 to 6.
We released a new version of the lambda dotnet layer.
---
> Bump dd-trace-dotnet layer to version 6

- layouts/index.html
- layouts/sitemap.xml
This PR is to add a verification meta tag within the `<head>` tag on the Documentation homepage to allow Zendesk to verify our domain for their [search crawler](https://support.zendesk.com/hc/en-us/articles/4593564000410). 
Additionally, this PR also adds an additional check to remove `url` tags with empty `loc` in our sitemap.xml. As per the [Sitemap protocol](https://www.sitemaps.org/protocol.html), `loc` must contain a URL string, otherwise it's considered as an invalid value. Please see screenshot below for example:
Due to this Sitemap XML issue, it's also preventing Zendesk from detecting our page indices and thus cannot crawl our documentation.
I am part of the Technical Solutions team and I need this added in relation to this Support Ops Jira card: …
> Add verification meta tag into our Docs and remove invalid values in Sitemap

- content/en/tracing/trace_collection/open_standards/otlp_ingest_in_the_agent.md
Changes recommendations for OTLP ingest endpoint on local installs to recommend using `localhost`.
Follow recommendations proposed over at open-telemetry/opentelemetry-collector/issues/6151.
---
> Recommend using localhost on host installs for OTLP ingest

- content/en/security_platform/cloud_security_management/troubleshooting.md
- content/en/security_platform/cloud_workload_security/getting_started.md
This PR adds a paragraph in the troubleshooting guide for CWS to help configure CWS Network when a custom Kubernetes Network plugin is in use.
There is a known race with Cilium 1.9 and lower that customers need to be made aware of. More generally speaking, this race may happen with any third party tool that rely on the Traffic Control of the Linux kernel.
---
> [CWS] Add requirement and troubleshooting sections for CWS network

- content/en/dashboards/faq/historical-data.md
Tags in Template Variables are only guaranteed for 48 hours.  We have supported 7 days in the past but we are phasing that out, but we never supported 30 days.
Customer referenced the 30 days.
---
- [ x] Review any mentions of "Contact Datadog support" for internal support documentation.
> Template variables 48 hours

- content/en/tracing/trace_collection/compatibility/nodejs.md
Add `mariadb` in the list of Node.js APM supported integrations.
Support for `mariadb` was recently added to dd-trace.
---
> add mariadb in the list of nodejs apm supported integrations

- content/en/dashboards/widgets/alert_value.md
specifying metric monitor as the input for the alert value widget
https://datadoghq.atlassian.net/browse/MNTS-89208
https://docs-staging.datadoghq.com/dan.chiniara/specify_metric_monitor_for_alert_value_widget/dashboards/widgets/alert_value/#pagetitle
> dan.chiniara/specify metric monitor for alert value widget

- content/en/tracing/trace_pipeline/ingestion_controls.md
- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Specify that service name case must match for per-service sampling rules
DOCS-4200
---
> DOCS-4200 Per Service sampling rule name is case sensitive

- content/en/tracing/trace_collection/library_config/php.md
Add public documentation for `DD_TRACE_RESOURCE_URI_QUERY_PARAM_ALLOWED`
Fixes datadog/dd-trace-php#1758
---
> Add public documentation for DD_TRACE_RESOURCE_URI_QUERY_PARAM_ALLOWED

- config/_default/menus/menus.en.yaml
- content/en/containers/cluster_agent/admission_controller.md
- content/en/tracing/trace_collection/admission_controller.md
- content/en/tracing/trace_collection/dd_libraries/java.md
- content/en/tracing/trace_collection/dd_libraries/nodejs.md
Moves instructions for injecting tracing libraries into kubernetes applications to its own page in /tracing
DOCS-4220, conversation with PM
No real new content, just moving it around and linking it up.
---
> Give APM Admission Controller docs its own page

- content/en/continuous_integration/setup_tests/javascript.md
Add instructions to keep value of `NODE_OPTIONS` when using CI Visibility for javascript.
Reduce the likelihood of the user overwriting `NODE_OPTIONS`.
[Link to preview](https://docs-staging.datadoghq.com/juan-fernandez/improve-node-options-docs/continuous_integration/setup_tests/javascript/?tab=onpremisesciproviderdatadogagent#instrument-your-tests)
---
> [ci-visibility] Improve `NODE_OPTIONS` instructions

- content/en/account_management/audit_trail/events.md
Add a row to the "Access Management events" table for the audit event of changing password. This audit event was added in this PR: https://github.com/DataDog/dogweb/pull/83568
---
> Update "Access Management events" table

- local/bin/py/build/actions/security_rules.py
Updates OOTB default security rules so Cloud SIEM is broken out into two categories, Log Detection and Signal Correlation.
https://datadoghq.atlassian.net/browse/WEB-2770
https://docs-staging.datadoghq.com/brian.deutsch/ootb-correlated/security_platform/default_rules/
- Cloud SIEM should be separated into two categories, `Cloud SIEM (Log Detection)` and `Cloud SIEM (Signal Correlation)`
- Detail pages under any `Cloud SIEM` category should be unaffected i.e. https://docs-staging.datadoghq.com/brian.deutsch/ootb-correlated/security_platform/default_rules/aws-signal-correlation-login-assumed-role/
- No errors are present
---
> [WEB-2770] Updates OOTB default security rules Cloud SIEM categories

- layouts/shortcodes/dbm-sqlserver-agent-setup-kubernetes.md
Agent is unable to connect to SQL Server on AWS RDS when set up with k8s annotations because the python driver cannot concatenate the port int value to str.
Adds quotes in port variable value in k8s annotations.
Agent is unable to connect to SQL Server on AWS RDS when set up with k8s annotations because the python driver cannot concatenate the port int value to str. See error below as taken from agent logs:
```
[
{
"message": "can only concatenate str (not \"int\") to str",
"traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 1116, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/sqlserver/sqlserver.py\", line 624, in …
```
> Add required quotes in port variable

- content/en/tracing/troubleshooting/tracer_startup_logs.md
We found out that the search was not simplified as much as we hoped for by the given keywords, because newer versions of ddtrace-rb (at least 1.5) do log under the key "DATADOG CONFIGURATION". Thus we didn't find the startup logs when we were looking for them.
> What inspired you to submit this pull request?
Incorrect documentation.
\-
---
> Add new search term for datadog config

- config/_default/menus/menus.en.yaml
- content/en/workflows/setup.md
Adds a page to the Workflows product documentation about Authentication. Originally, this section was called Setup, but I realized that it only has to do with authentication, so I renamed it.
This section corresponds to the following outline, agreed upon by the Documentation team and Sarjeel:
Setup/Prerequisites
1. Explain that workflows use integration configurations
2. Manage Workflow Integrations via Workflow Connections
a. (P1) Create New Connection 
b. (P1) Restrict Workflow Connection Usage
c. (P2) Edit Workflow Connection
d. (P3) Delete Workflow Connection
---
> Add Workflows Authentication page

- content/en/infrastructure/process.md
The command suggested to enable Live Process collection by editing the Agent main configuration file is deprecated according to the config file in GitHub (https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml), I updated the command to match this config file.
Change one deprecated command with its updated version, according to the official config file found on GitHub.
Customer feedback about misalignment between documentation and GitHub config file.
Reach out to me on slack if needed.
---
> Corrected Linux/Windows section in process.md

- content/en/account_management/billing/rum_units.md
- content/en/glossary/_index.md
- content/en/logs/log_configuration/online_archives.md
- content/en/real_user_monitoring/error_tracking/explorer.md
- content/en/real_user_monitoring/guide/send-rum-custom-actions.md
- content/en/tracing/error_tracking/explorer.md
- layouts/partials/noindex.html
Removes condition where `is_beta` excludes content from being searchable and indexed by crawlers
https://datadoghq.atlassian.net/browse/WEB-2783
https://docs-staging.datadoghq.com/nsollecito/web-2783/
No visible changes. Check for a doc with is_beta and confirm there is no longer a `noindex, no follow` meta tag
---
> WEB-2783 Frontmatter param `is_beta` no longer adds noindex meta tags on Docs pages

- config/_default/menus/menus.en.yaml
- content/en/workflows/debug.md
- Remove the Debug workflows left nav menu item and the markdown page.
- Move Authentication to below Build in the left nav.
---
> Remove Debug Workflows page, update left nav

- content/en/workflows/setup.md
Correct the link to generic actions in the workflows authentication page
found a problem while testing
---
> fix a link in workflows authentication

- content/en/getting_started/api/_index.md
This PR updates a link that pointed towards the wrong API docs (https://docs.datadoghq.com/api/latest/organizations/ instead of the API reference https://docs.datadoghq.com/api/latest/#api-reference)
Flagged by a customer.
---
> Wrong API docs link update

- content/en/continuous_integration/troubleshooting.md
Last minute change on the message needed to force-disable test skipping in Intelligent Test Runner
Internal team feedback
---
> [ci-app] Change ITR test skipping message

- content/en/tracing/error_tracking/_index.md
Fix wrong tag mentioned for APM spans and Error Tracking integration after support noticed the discrepancy in our public and internal docs ([slack thread](https://dd.slack.com/archives/C017T36E0SH/p1666112931497669)).
---
> Fix typo in tags used by Error Tracking for APM

- go.mod
- go.sum
- get new product dropdown updates from websites-modules
- update product dropdown menu
https://docs-staging.datadoghq.com/carlos/bump-mod-version/
---
> Bump mod version for new product dropdown updates

- .gitlab-ci.yml
Increases the timeout on Algolia indexing by half an hour to 2 hours and 30 minutes. Modeled after the commit from the last bump: https://github.com/DataDog/documentation/commit/96ee7dea49d1dfa38046b7bdc3efd822c141a93f.
The Algolia indexing job timed out Tuesday night, presumably because of the large number of new Workflow files. Over Slack, Brian from the Websites team says they usually bump it by 30 each time.
---
> Bump algolia indexing timeout to 2h 30m due to new workflows pages

- content/en/agent/proxy.md
Adds Squid Proxy configuration steps to this documentation page. 
Squid is typically easier to configure than Nginx/HAproxy as a means for proxying agent traffic but is not mentioned explicitly in our documentation. The steps included here were transcribed from some internal guides we have on the subject. 
---
> Add Squid Proxy instructions

- content/en/account_management/billing/pricing.md
Updated session pricing count from 10,000 to 1,000
---
> rum pricing_small change.md

- config/_default/menus/menus.en.yaml
- content/en/tracing/troubleshooting/quantization.md
Adds a page to explain APM quantization: what it is, why it happens, and how to use quantized data.
To provide documentation on the APM quantization feature.
---
> [DOCS-4226][apm] add page on APM quantization

- content/en/continuous_integration/pipelines/github.md
- content/en/continuous_integration/pipelines/gitlab.md
Adds a notice of the maximum log size file supported by CI Visibility log forwarding.
---
> Add log file size limit for CI Visibility forwarding

- content/en/security_platform/notifications/variables.md
Adds note about HIPAA-enabled accounts having access to only template variables.
DOCS-4231
---
> [DOCS-4231] Add note about HIPAA-enabled accounts

- content/en/tracing/service_catalog/service_definition_api.md
adding link to new API reference link
---
> service catalog API doc update

- content/en/continuous_integration/troubleshooting.md
Add a step to the troubleshooting instructions for the Datadog Jenkins Plugin.
Customers who had problems were not doing this.
---
> Document how to enable debug-level logs on the Jenkins Plugin

- content/en/database_monitoring/setup_postgres/troubleshooting.md
Fixes a link
When some info got removed from this page it got messed up
---
> (DOCS-4254) Fix incorrect link in dbm docs

- content/en/continuous_integration/intelligent_test_runner/_index.md
Adds a blog link to further reading
went live wednesday instead of monday, so adding blog link now
---
> Add ITR blog link to index

- content/en/logs/log_collection/java.md
Old version (2.17.0) had a moderate security vulnerability that was patched in new version (2.17.1)
Guessing I missed a few spots where this is used. Please let me know if you'd like me to update the remaining locations to match :)
---
> Increment log4j-core version

- content/en/network_monitoring/devices/netflow.md
Small changes to netflow docs to list as private beta, and make a few tweaks to the Agent configuration recommendations
Updates the docs to list NetFlow monitoring as a public beta, instead of private, and change the Agent version required to 7.39, instead of 7.40.
---
> Update NetFlow Monitoring beta docs

- content/en/security_platform/application_security/setup_and_configure.md
- content/en/tracing/configure_data_security/_index.md
This PR moves the existing documentation of this feature into the ASM setup and configure page.
Following up on a SEV-1 incident, it has been decided to report the APM span tag `http.client_ip` only with ASM.
How do you deal with existing translations?
---
> Tracing http client ip documentation update

- content/en/agent/logs/advanced_log_collection.md
Based on this ticket https://datadog.zendesk.com/agent/tickets/973398, labels should be added to the container sending the logs in question and not the Agent container.
Based on this ticket https://datadog.zendesk.com/agent/tickets/973398, labels should be added to the container sending logs and not the Agent container.
Based on this ticket https://datadog.zendesk.com/agent/tickets/973398
Tiphaine/TSE
---
> Labels added to the container sending logs

- content/en/continuous_integration/tests/swift.md
Update instructions  to add the Application Key by default
Also add specific instructions for using Swift Package projects
For enabling Intelligent Test Runner, setting application key will be needed, so we can already add it to the list of environment variables here for the future.
Also clarifies installation and configuration for a specific kind of problems, we has a support question that was solved with this specific instructios
https://docs-staging.datadoghq.com/nachoBonafonte/update-instructions-for-ITR-needs/continuous_integration/setup_tests/swift
---
> CI Visibility - Swift - Update instructions

- content/en/tracing/configure_data_security/_index.md
Adds info for PCI compliance for APM, which is only available for US1. Good to merge, once approved by docs.
DOC-4239
---
> [DOCS-4239] Add PCI compliance for APM info

- content/en/integrations/guide/reference-tables.md
Adds a note about which server-side encryption methods are supported for reference table uploads from S3.
DOCS-4275
---
> (DOCS-4275) Add note about supported S3 encryption
