DataDog/documentation

content/en/events/guides/dogstatsd.md
Adds the default value to the `source_type_name` parameter
DOCS-3734
---
=> Add default value to source_type_name parameter

content/en/integrations/kubernetes_state_core.md
* Adds an entry to the tag migration table to showcase the behaviour of the Core check vs its legacy version : the `hpa` tag (legacy) is now `horizontalpodautoscaler` (core)
* Customer reaching out about this undocumented change
* Can be replicated using an old chart version like `2.36.1` (legacy) and newer chart version like `3.1.0` (core) and see the transition : 
---
=> Adds depreciation of hpa tag to horizontalpodautoscaler when migrating

content/en/integrations/guide/source-code-integration.md
The method described in the first tab to automatically extract tags from container labels is not supported for containers running on AWS Fargate. This updates the message box to mention it.
---
=> [Source Code Integration] Mention non-support of tag extraction for AWS fargate

content/en/synthetics/private_locations/_index.md
Add the us5 intake to the PL documentation page
---
=> SYN. add private loc intake

content/en/agent/logs/proxy.md
The example haproxy config has a typo which sets the `connect` timeout to 5 (unitless, I suspect milliseconds). It should be set to 5s for consistency with the other timeouts.
Connections sent will fail with code `sC`.
Extracted from haproxy [docs](https://www.haproxy.com/documentation/hapee/1-8r1/onepage/#8.2.2):
```
s : the server-side timeout expired while waiting for the server to
send or receive data.
C : the proxy was waiting for the CONNECTION to establish on the
server. The server might at most have noticed a connection attempt.
```
---
=> Corrects typo with haproxy connect timeout

local/bin/sh/nohooks.sh
Adds a small script that writers can use to toggle pre-commit hooks on and off. 
To test:
1. Check out this branch
2. Follow the instructions in [Docs4Docs](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1896808601/Troubleshooting+Local+Doc+Build#Disable-pre-commit-hooks)
---
=> Adds a script to toggle the commit hook

content/en/data_security/logs.md
- Adds a header for the encrypted endpoints section.
- Moves "Note" to go at the end of the intro.
- Vale cleanup
After adding the PCI info for logs, I noticed that some of the info on the page needed to be separated out.
---
=> [DOCS-4294] Update logs data security page

translate.yaml
Removes some file path glob patterns that were previously being excluded from translation syncing.
We had excluded these files from translation syncing to prepare for updates/data migration in Transifex.   The original PR was #15453.  
n/a this shouldn't affect the site.
---
=> Removes ignored files from translation config

content/en/observability_pipelines/setup.md
Updating setup instructions, as service account is no longer required to setup OP
---
=> Update - Service Account no longer required

content/en/tracing/trace_collection/admission_controller.md
Update the lib version for auto-instrumentation (the old ones were missing the `v` prefix)
The old values are invalid
---
=> Update lib versions

content/en/agent/proxy.md
Remove all references to the old appsecevt intake.
This backend intake API is no longer available and its documentation can be removed.
---
=> agent/proxy.md: remove the appsecevt configuration

content/en/containers/docker/_index.md
Moves a paragraph with a link that wasn't working. I suspect the tabs processing is causing the link to render incorrectly. Will open a WEB ticket to track.
report in documentation channel.
---
=> Move link to work around rendering problem

content/en/tracing/service_catalog/service_definition_api.md
Make example compliant with our rules + match the in app example
error message "expected array, but got null" when using this example
---
=> Update service_definition_api.md - tags should be an array

content/en/serverless/configuration/_index.md
Adds better serverless-specific instructions for dual shipping.
We've had complaints from some users that the dual shipping documentation was a bit confusing so we're adding serverless-specific instructions because it's a little different than the normal flow.
---
=> SLS-2505: Add better instructions for dual shipping

content/en/real_user_monitoring/session_replay/_index.md
Explained in detail on Jira card https://datadoghq.atlassian.net/browse/REPLAY-1102
Some customers were misled by the wording about a "service worker", which is a (very specific concept)[https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API] that we don't use. Instead we should explicitly talk about a "dedicated web worker".
---
=> [RUM][REPLAY]: Rephrase mention about service worker

layouts/_default/404-baseof.html, layouts/_default/baseof.html, layouts/api/baseof.html, layouts/index.html
Update the `html` lang attribute from **en** to **en-US** by checking the `.Site.Language.Lang` variable
This is related to my previous PR: https://github.com/DataDog/documentation/pull/15332
Zendesk crawler is unable to index our pages because it's not able to detect our locale language according to our Zendesk Help Portal chosen language. We have configured our Zendesk to use English (United States). According to Zendesk support, en-US should be used instead of just en. Here's a snippet of my conversation with them:
I tested this change locally and it seems fine. Thanks!
---
=> Updating lang attribute from en to en-US for Zendesk search crawler

assets/scripts/components/algolia.js, assets/scripts/components/search.js, package.json, yarn.lock
Fixes broken front end search components which broke due to the `lang` html attribute changing from `en` to `en-US`.
Search results always empty for english users
https://docs-staging.datadoghq.com/brian.deutsch/broken-search
---
=> Fixes broken front-end search components

content/en/database_monitoring/setup_mysql/azure.md, content/en/database_monitoring/setup_postgres/azure.md, content/en/database_monitoring/setup_sql_server/azure.md, content/en/database_monitoring/setup_sql_server/gcsql.md, layouts/shortcodes/dbm-sqlserver-agent-setup-docker.md
Improves the consistency of our docker examples and fixes an incorrect url used in some examples (`datadoghq/agent` -> `gcr.io/datadoghq/agent`).
---
=> Improve and fix DBM docker examples

package.json, yarn.lock
Update the hugo version to `0.105.0`
Keeping up with hugo version bumps to avoid deprecation
https://docs-staging.datadoghq.com/devin.ford/upgrade_hugo_version/
Try to check as many templates as you can think of to make sure there is no wonkiness 
---
=> WEB-2808 | Update hugo version

assets/scripts/components/algolia.js, assets/scripts/components/search.js
Fixes frontend search.   Previously we used `en` as the english language facet when querying.   The previous change told our frontend search to look for that, however after the algolia indexing job finished it had scraped the html `lang` attribute and updated all records to match `en-us`.
The staging index will need to be updated so all indexes use `en-us`
Broken search.
https://docs-staging.datadoghq.com/brian.deutsch/broken-search-2
---
=> Updates site language logic for algolia environments

content/en/containers/kubernetes/log.md
* Slightly alters https://github.com/DataDog/documentation/pull/15600 to use the correct syntax to collect logs with custom tags
* Modifies `tags` entry to be a proper list (`.yaml`) or an array (JSON annotations) to ensure the Agent understands the syntax
* Following a call with a customer, I found out the documentation was recently updated with a slight syntax typo, which causes the annotations to be ignored, and thus logs not to be collected
---
=> Fixes log collection with custom tags on K8s

assets/scripts/components/algolia.js, assets/scripts/components/search.js
Following up on #15803, this updates the front-end search for preview sites to look for `en-us` as the language identifier for english when querying Algolia.   At this time the approach should be consistent for both preview and live environments.
Preview and live environments inconsistent in how they handle querying Algolia on the front end.
https://docs-staging.datadoghq.com/brian.deutsch/algolia-preview-update
searching should work correctly from the homepage/sidenav as well as search page itself.
---
=> Updates algolia preview logic

content/en/monitors/create/types/composite.md
Adds a link in the Composite monitors to the Composite monitor variables so users can have clarity on what notification and variable options are available.
[DOCS-1695](https://datadoghq.atlassian.net/browse/DOCS-1695)
---
=> Added link for clarity on Composite monitor variables

content/en/logs/log_configuration/archives.md
updates the Logs Archives docs to mention we don't support Azure ChinaCloud storage accounts 
motivated by a support case: https://datadoghq.atlassian.net/browse/LOGSS-6257
---
=> [logs] Note that archives don't support ChinaCloud

translate.yaml
Ignores `api/v1` and `api/v2` content from the translation pipeline.   These pages are currently in Transifex, but they don't reflect any content that exists on the site (the live content is all under `api/latest`, these pages are headless ), and only the document title is ever sent to Transifex.
https://datadoghq.atlassian.net/browse/WEB-2831
n/a, translation config change only
---
=> [WEB-2831] Ignore api v1 and v2 directories from translation pipeline

content/en/tracing/trace_collection/library_config/php.md
Add public documentation for rate limiting in PHP tracer
---
=> Add public documentation for rate limiting in PHP tracer

content/en/real_user_monitoring/connect_rum_and_traces/_index.md
Mobile SDKs are currently setting the tracing sampling rate default value to 20%, not 100% as is stated.  Also changed the examples to show how to configure to 100%.
Incorrect information. 
---
=> Fix default sampling rate for Android & iOS SDKs

content/fr/security_platform/application_security/troubleshooting.md
Copy / Paste to config will trigger errors on php-fpm daemon
---
=> [DOCS-4332] Use real simple quotes instead of mac os quote

assets/styles/pages/_global.scss, content/en/containers/docker/_index.md
Links that were placed right before a header in the body content were not clickable. This is because of the margin/padding hack that allows headers visited via hashes to their ID to show up below the sticky navbar, which extends the height of the header over the top of content that comes right before it.
The solution was to make the header pass through click events so as not to block the links. This works without breaking the links in the headers themselves.
Fix for reported issue in https://datadoghq.atlassian.net/browse/WEB-2828
I've moved the link in question from [this previous preview branch](https://docs-staging.datadoghq.com/jorie/DOCS-4241/containers/docker/?tab=standard#setup) back to that location so you can see that it's working. The link in question is the one in the paragraph …
=> fixed links right before headers not being clickable [WEB-2828]

content/en/developers/authorization/oauth2_in_datadog.md
Updating the OAuth docs to include a note about authorizing from outside of the Datadog integration tile. 
A partner ran into this issue.
---
=> Adding note to OAuth docs

layouts/shortcodes/latest-lambda-layer-version.html
Increase python layer version to 64.
---
=> Bump datadog-lambda-python layer to version 64

config/_default/menus/menus.en.yaml, content/en/dashboards/widgets/_index.md, content/en/dashboards/widgets/topology_map.md
- Add topology map to menus.en.yaml file
- Remove the Service Map widget from the menu and the index list
- Add information about the widget in the Topology Map page
[DOCS-4081](https://datadoghq.atlassian.net/browse/DOCS-4081)
Will remove the Service Map page in a separate [PR](https://github.com/DataDog/documentation/pull/15769)
---
=> Add Topology Map and remove Service Map widget

content/en/database_monitoring/guide/apm-linking.md, content/en/database_monitoring/guide/connect_dbm_and_apm.md
This adds a new database monitoring guide describing how to enable dbm propagation in tracers to use dbm/apm linking features. 
Note that this page is meant to be hidden for the time being as this is still in beta. This first version of the page is filling in the technical details for the first supported tracer language (Go). @iFallUpHill will follow-up soon to add some content to describe the product and features. 
We'd like to have the docs publicly accessible for when we get customers to trial apm/dbm linking features. 
https://docs-staging.datadoghq.com/alex.normand/dbm-1695/database_monitoring/guide/connect_dbm_and_apm
---
=> [DOCS-4331] Add dbm guide for setting up dbm/apm linking

config/_default/menus/menus.en.yaml, content/en/serverless/azure_container_apps/_index.md
Adds a page for Azure Container Apps.
---
=> Add serverless page for azure container apps

content/en/database_monitoring/setup_sql_server/azure.md, content/en/database_monitoring/setup_sql_server/gcsql.md, content/en/database_monitoring/setup_sql_server/rds.md, layouts/shortcodes/dbm-sqlserver-agent-setup-docker.md, layouts/shortcodes/dbm-sqlserver-agent-setup-kubernetes.md, layouts/shortcodes/dbm-sqlserver-agent-setup-linux.md, layouts/shortcodes/dbm-sqlserver-agent-setup-windows.md
Updates the docs to include instructions for enabling AlwaysOn metrics. Note, Azure & GCP sections will not include it because those providers don't have an AO offering, only RDS.
---
=> DBM-1700: Include AO config 

content/en/profiler/enabling/dotnet.md, content/en/profiler/search_profiles.md
Adding new allocations and contention profilers configuration
Allow customers to enable new allocations/contention profilers
---
=> Update documentation for .NET Profiler release 2.18

config/_default/menus/menus.en.yaml, content/en/security_platform/cloud_siem/investigator.md
- Renames doc.
- Drop "Cloud SIEM" in "Cloud SIEM Investigator" in the nav and title.
- Add alias.
Redundant to have "Cloud SIEM". It will also will only be "Investigator" in the app.
---
=> Rename Cloud SIEM Investigator to Investigator

content/en/tracing/trace_pipeline/trace_retention.md
We are no longer indexing all the service entry spans with the intelligence Filter. Updating doc.
removes a line in the documentation that is no longer relevant
change in the Intelligence filter https://datadoghq.atlassian.net/browse/SESP-609
---
=> Removed line in Intelligence Filter section

content/en/monitors/create/types/ci.md
We're releasing CI monitors to GA, in this PR removing `Alpha` section, and updating the notification section up to date.
JIRA issue: https://datadoghq.atlassian.net/browse/CIAPP-5265
CI monitors GA.
---
=> [CI Visibility] Adapt CI monitors documentation for GA

content/en/continuous_integration/guides/pull_request_comments.md
Changing note on GH comments for GHA triggered by `pull_request*` events
Clarifying the current state of Github Coments
---
=> [CI Visibility] Changing note on GH comments for GHA triggered by pull_request* events

content/en/continuous_integration/tests/junit_upload.md
New section explaining new feature for custom tags with XPath syntax in junit upload command from CI Visibility.
We need to explain a new feature
---
=> [DOCS-4333][CI Visibility] Add doc for junit upload detailing XPath tags feature

content/en/continuous_integration/guides/flaky_test_management.md
This PR adds documentation for a new feature: we are adding `new_flaky` and `known_flaky` attributes to test runs, and this PR adds ways to find relevant test runs for both facets.
We need to document that change so that customers are aware.
---
=> [CIAPP-5225] Add information about flaky facets in Test Runs page.

content/en/agent/basic_agent_usage/_index.md, content/en/agent/basic_agent_usage/windows.md, content/en/agent/guide/agent-commands.md
Removes the `install-service` and `remove-service` Windows agent commands.
Depends on https://github.com/DataDog/datadog-agent/pull/14253
---
=> Remove install/remove service Windows agent commands

content/en/containers/kubernetes/data_collected.md
fixed dead link to 'leader election option' in kubernetes/data_collected
Closing #15854
---
=> fixed dead link to leader election option in kubernetes/data_collected

content/en/agent/guide/agent-commands.md
This PR adds the `--` in the `kubectl exec` commands
To avoid the following deprecation warning:
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
=> Add -- to kubernetes exec command

content/en/containers/kubernetes/prometheus.md
We ran into problems using a proper regular expression when we wanted all metrics scraped. That is, "*" is a shell glob not a regular expression.
Adds a sentence about how to scrape all metrics for an openmetrics integration. Specifically, using `".*"` does not work whereas `"*"` does. This is surprising given the documentation says to use regular expressions.
Letting others avoid the pain of troubleshooting this surprising behavior.
---
=> Scraping all metrics requires a shell-style glob

content/en/agent/faq/agent-downgrade-major.md, content/en/agent/iot/_index.md, content/en/agent/versions/upgrade_between_agent_minor_versions.md, content/en/agent/versions/upgrade_to_agent_v6.md, content/en/agent/versions/upgrade_to_agent_v7.md, content/en/getting_started/agent/_index.md, content/en/getting_started/tracing/_index.md, static/config/99datadog-amazon-linux-2.config, static/config/99datadog.config, static/resources/json/dd-agent-install-eu-site.json, static/resources/json/dd-agent-install-us-site.json
Point to new install_script_agent6.sh and install_script_agent7.sh
We've moved install_script to https://github.com/DataDog/agent-linux-install-script and started releasing the two above mentioned flavors, this updates docs to reflect that.
---
=> Update documentation that mentions install_script.sh

content/en/integrations/faq/powershell-command-to-install-azure-datadog-extension.md
Adds documentation about the `agentConfiguration` setting that was added to the Linux Azure extension in version 6.0.
Updates the Windows `TypeHandlerVersion` and Linux `version` to the latest Azure extension versions.
Updates `agentVersion` in the example commands from `7.39` to `7.40`.
`agentConfiguration` feature added to Linux Azure extension.
https://datadoghq.atlassian.net/browse/WA-131
---
=> Add agentConfiguration setting to Linux Azure extension documentation

content/en/account_management/billing/custom_metrics.md
Adds guidance for the treatment of metrics as Custom Metrics when using DogStatsD or Agent Checks.
This language appears in /metrics/custom_metrics/ but is separately useful in the context of billing.
I encountered conflicting information when researching this topic--this language from the Custom Metrics page helped me clarify categorization of Custom Metrics. For example, the Node.js StatsD client (`npm/hot-shots`) appears in the list of "more than 500 integrations" but ultimately produces Custom Metrics via DogStatsD.
I avoided reorganizing the links in this document to avoid a large diff.
---
=> Clarify classification of metrics submitted via DogStatsD or Agent

content/en/dynamic_instrumentation/_index.md
Fix a typo: "Dynamic Instrumentation ~~in~~ **is** enabled on only ..."
Documentation without typos.
=> Fix typo "in" vs "is"

content/en/containers/amazon_ecs/apm.md
IMDSv2 is a security mechanism that is recommended to enable in AWS (c.f. https://securitylabs.datadoghq.com/articles/state-of-aws-cloud-security-followup/#enforce-usage-of-the-ec2-instance-metadata-service-v2-(imdsv2))
Consequently we should have instructions for customers who enforce it according to best practices
=> Add instructions for IMDSv2 in ECS docs

content/en/profiler/enabling/ddprof.md
This PR tweaks the `ddprof` onboarding documentation to mention that `ddprof` is the native profiler.
This PR started from the following observation: In the Datadog web app, we present profiles from the "Profiler for Compiled Languages" as coming from the `native` runtime.
Nowhere in the documentation do we make the connection between "Profiler for Compiled Languages" and `native`. And nowhere else we seem to call it "the Profiler for Compiled Languages".
Unfortunately, we seem to have decided to name this profiler in three different ways, and all three seem to be user-visibile:
* ddprof: repository, binary, docs
* native profiler: web app, [repository](https://github.com/DataDog/ddprof/blob/8cfee2c1482e9eb14ec8615b229924118564bb0b/Readme.md?plain=1#L3)
* profiler for compiled languages: …
=> Add "native" name to ddprof documentation

content/en/agent/guide/private-link.md
fixes refrence to `use_http` setting for agent `log_config`. Option is now called `force_use_http`, looks like this was changed in DD agent [#11381](https://github.com/DataDog/datadog-agent/commit/42f52e8f8eaf999147c91763746fbee774dcaaad)
This was confusing for me until I did a git blame on the example agent config file. Figured it would be good to get updated for anyone who comes after.
---
=> update privatelink docs

config/_default/menus/menus.en.yaml
Noticed that a nav link wasn't going to the right spot
misc
---
=> Fix broken nav entry

content/en/account_management/org_settings.md, content/en/account_management/saml/troubleshooting.md
Updates wording around SAML login mapping to clarify the permanence of the role changes.
Request from Support
---
=> DOCS-4366 Clarifying permanent role stripping with SAML login

content/en/tracing/universal_service_monitoring/_index.md
Removes a link that loops back to the same docs page.
---
=> Remove request access link from USM beta callout

content/en/real_user_monitoring/generate_metrics/_index.md
It removes a yellow bar at the top of the article that lets readers know the feature is in beta.
Amina requested that this be removed on 11/15/22 since the feature will no longer be in beta.
---
=> removed yellow beta bar

content/en/account_management/billing/usage_attribution.md
Adds a colored alert box warning users that daily usage attribution reports will be deprecated in February.
Screenshot: https://share.getcloudapp.com/JruyPBe0
Product manager request.
---
=> Add deprecation warning on daily usage attribution

content/en/account_management/billing/custom_metrics.md
Adds Prometheus back to this billing table
This used to exist in the table but I think accidentally got replaced with OpenMetrics instead of OpenMetrics getting added to the list. Adding it back in due to internal request. We do also state on the prometheus integration itself that all metrics collected by prometheus are considered custom metrics, so hopefully this section of the docs is more of a backup notification for folx reading through the docs worried about billing implications. 
---
=> (DOCS-4317) Add prometheus back to this table

content/en/synthetics/settings/_index.md
Removes Enforced Tags section from the Synthetics Settings doc page.
DOCS-4406
---
=> DOCS-4406 Synthetic Monitoring Settings Doc Edit 

content/en/tracing/trace_collection/custom_instrumentation/python.md
This updates the link to the `wrap()` decorator such that the user gets taken directly to the appropriate documentation.
---
=> Fix link to wrap decorator documentation

content/en/account_management/billing/serverless.md
Fix typo
“Datadog charges by calculating the sum of your AWS Lambda function invocations at the end of the month.”
---
=> Fix typo on Serverless Invocations page

content/en/agent/guide/agent-configuration-files.md
Removes the link to the configuration template in the Agent's repo from the agent/guide page
This configuration that was linked before is not usable as-is since it includes various template conditionals and sections that are based on Agent's build tags. To prevent user confusion, the link removal is warranted.
https://docs-staging.datadoghq.com/srdjan.grubor/remove-link-to-agent-config-template/agent/guide/agent-configuration-files/?tab=agentv6v7#agent-main-configuration-file
Upstream bug report: https://github.com/DataDog/datadog-agent/issues/14295#issuecomment-1312786813
---
=> [agent/guide] Remove link to the configuration template in Agent repo

content/en/tracing/trace_collection/compatibility/java.md
This PR update the Java tracer compatibility matrix.
A new major version of the Java tracer is being released.
---
=> feat: Update Java tracer compatibility matrix

content/en/metrics/open_telemetry/otlp_metric_types.md
The default behavior of most OTEL SDK implementations is CUMULATIVE temporality. This is very unexpected in comparison with default Datadog implementation as the first reported datapoints of some Metric types are "discarded". The OTLP standard allows to configure the temporality to DELTA which works optimally with Datadog yet it's not mentioned in the documentation
We got stuck on this for a few days to find out that it's just OTEL configuration. I'm not sure if this is the best place to mention it but I'd love to see it in the Datadog documentation.
---
=> Mention configurable Temporality of OTEL with direct Datadog Agent integration

content/en/database_monitoring/guide/connect_dbm_and_apm.md
This adds instructions for the ruby tracer to our DBM/APM linking guide. 
---
=> Add ruby instructions to dbm/apm linking guide

content/en/logs/log_configuration/logs_to_metrics.md
The Further Reading link entitled "Control the volume of logs indexed by Datadog" is linked to https://docs.datadoghq.com/logs/logging_without_limits. That, however, redirects to https://docs.datadoghq.com/logs/ which is a general introduction of Logs. This is the link removed by this PR.
I was doing research for a Health Check and followed the link, a couple of times until I realized it wasn't relevant.
https://docs.datadoghq.com/KateYoak/patch-1/logs/log_configuration/logs_to_metrics/
---
=> Remove a misleading link

content/en/integrations/kubernetes_state_core.md
Adds change of type for job.succeeded metric
Report from SE
---
=> Add type change to list of breaking changes

content/en/integrations/rsyslog.md
- Moves TLC encryption step (Step 4 in original) to end (Step 8 in revised doc) and make it optional.
- Remove TLC encryption for US3, US5, and US1-FED because those endpoints aren't available.
No new information is added.
DOCS-3754
---
=> [DOCS-3754] Move optional step to end in Rsyslogs doc

content/en/containers/kubernetes/control_plane.md
Just a quick update to add `yaml` formatting where it was missing , for easier reading.
Cleaning up Containers docs.
---
=> Fix yaml formatting for control-plane documentation

content/en/agent/basic_agent_usage/_index.md, content/en/agent/basic_agent_usage/aix.md, content/en/agent/basic_agent_usage/amazonlinux.md, content/en/agent/basic_agent_usage/centos.md, content/en/agent/basic_agent_usage/deb.md, content/en/agent/basic_agent_usage/fedora.md, content/en/agent/basic_agent_usage/osx.md, content/en/agent/basic_agent_usage/redhat.md, content/en/agent/basic_agent_usage/source.md, content/en/agent/basic_agent_usage/suse.md, content/en/agent/basic_agent_usage/ubuntu.md, content/en/agent/basic_agent_usage/windows.md, content/en/agent/guide/network.md
Adds information on configuring inbound ports to the Agent network doc and links to it from architecture. Also adds related information links to all of basic usage docs for OS / Windows / Linux.
[DOCS-4430](https://datadoghq.atlassian.net/browse/DOCS-4430)
---
=> (DOCS-4430) Add guidance on configuring Agent ports

content/en/network_monitoring/performance/setup.md
system-probe.yaml.example is read-only, and using the current command, the destination system-probe.yaml will also be read only, requiring a `chmod 644 system-probe.yaml` in order to edit the file (line 105). 
As an alternative, we could instead have a line with `chmod 0644 /etc/datadog-agent/system-probe.yaml` rather than doing this in one line.
---
=> Update cp command example for system-probe.yaml

content/en/monitors/create/types/custom_check.md
Update the [Service Check Monitor](https://docs.datadoghq.com/monitors/create/types/custom_check/?tab=checkalert) page 
- Removed the `WARN` option for triggering alerts since it's not available as an option
- Added the Service Check overview as another resource
- Shifted information around for Cluster Alerts
[DOCS-4395](https://datadoghq.atlassian.net/browse/DOCS-4395)
---
=> Update Service check monitor

assets/styles/pages/_glossary.scss
Style adjustment for Japanese Glossary page, fixing nav overlapping with content.
https://datadoghq.atlassian.net/browse/WEB-2882
https://docs-staging.datadoghq.com/brian.deutsch/ja-glossary-fix/ja/glossary/ - the sticky nav (with the letters) does not overlap with content across all screen sizes
https://docs-staging.datadoghq.com/brian.deutsch/ja-glossary-fix/glossary/ - the english site is unaffected.
There is a bug w/ the JA glossary nav where clicking the JA chars dont get highlighted, we will fix that in a separate PR.
---
=> [WEB-2882] JA glossary style fix

local/bin/sh/nohooks.sh
This adds a "status" flag which tells you the status of your hooks without enabling/disabling them.
---
=> (maint) Adds a "status" flag to the script

content/en/logs/log_configuration/forwarding_custom_destinations.md
Makes "Forwarding Logs to Custom Destinations" doc searchable.
T2/PM request in #documentation.
---
=> Remove private flag to make doc searchable

content/en/account_management/_index.md
The weekly trends report is turned down, we should remove it from documentation as well
https://datadoghq.atlassian.net/browse/MA-3454
---
=> [account management] Remove weekly report references

content/en/account_management/saml/_index.md
Adds instructions for users to follow for configuring SAML when the UI differs from our documentation.
Some organizations see a different configuration page for SAML that has led to some confusion on how to enable SAML. For organizations that have never uploaded IdP metadata, there is a `upload and enable` button on the SAML configuration page, but for organizations that have previously, there is not. To enable SAML in both cases they need to enable the method by default for all users to enable SAML. This is to address that possibility and give users direction if it applies to them.
---
=> Update SAML configuration documentation

content/en/tracing/trace_collection/dd_libraries/java.md
Parameters after -jar are not considered JVM options. They are taken as Java application parameters.
=> Update to order of JVM parameters

content/en/tracing/trace_collection/dd_libraries/java.md
Since the release of Java tracer v1.x, Java 8 is the minimum requirement, making the following misleading:
"The latest Java Tracer supports all JVMs version 7 and higher on all platforms."
This PR removed our previous language "The latest Java Tracer supports all JVMs version 7 and higher on all platforms."
[https://github.com/DataDog/dd-trace-java/releases/tag/v1.0.0](url)
---
=> [doc] Corrected misleading Java compatibility

content/en/continuous_testing/cicd_integrations/_index.md, content/en/continuous_testing/settings/_index.md
Clarify that the NPM package is another integration that can be used if a CI provider is not documented.
---
=> Update Continuous Testing integration docs

content/en/dashboards/template_variables.md
This updates the link for using template variables to point to the `#usage` heading instead of the nonexistent `#use` heading.
The current link is dead and comes back to the top of the page.
---
=> point use template variables to #usage heading

content/en/containers/kubernetes/prometheus.md
Add a disclaimer to double check which pods and services have the prometheus scrape annotation before enabling the prometheus scrape feature. As well as provide some sample commands to do so.
The prometheus scrape annotation can often be present on pods/services which customers were not aware of. Which means the Agent will start collecting billable custom metrics from these pods/services that they were not anticipating. Adding this to avoid that pain point when enabling this feature for the first time.
https://docs-staging.datadoghq.com/jack.davenport/prometheus-scrape-disclaimer/containers/kubernetes/prometheus/?tab=kubernetesadv2#configuration-1
Sample output:
```shell
$ kubectl get pods -o=jsonpath='{.items[?(@.metadata.annotations.prometheus\.io/scrape=="true")].metadata.name}' …
```
=> Add scrape disclaimer to check before enabling

content/en/agent/basic_agent_usage/windows.md
Add [Windows Agent installer list](https://s3.amazonaws.com/ddagent-windows-stable/installers.json).
The current doc misses the case users want to keep Agent v6 or specify the version.
---
=> [DOCS-4483] Add Windows Agent installer list

.github/CODEOWNERS
Adds specific files and directories to the corpweb scope in CODEOWNERS
Certain files can have unseen ripple effects when changed that may not be noticed or caught in preview branches. In an attempt to do some proactive checks, the websites team would like to provide review on any build related files for the documentation site. The scope of this shouldn't effect any current workflows for the docs and other outside teams since these files are 90% of the time maintained by the websites team. 
These changes will hopefully allows us to catch any unintended changed before they go out, but in the event something does go through and causes some kind of issues or outage of docs, we should at least have a better context around it allowing us to get a fix out for it quicker.
If there is any …
=> Add Websites to some files for reviews

content/en/continuous_integration/tests/java.md
Cucumber v2 and later, which use JUnit v5, don't work at the moment despite JUnit v5 being supported.
We never tested Cucumber with JUnit 5. I tested it and our instrumentation doesn't work.
---
=> Cucumber versions using JUnit5 are not supported

content/en/database_monitoring/setup_postgres/troubleshooting.md
Explains how to diagnose an edge case where pg_stat_statements is not accessible to the datadog user in dbm.
---
=> [DBM] Update troubleshooting pg_stat_statements not in search_path

.github/workflows/approved_status.yml, .github/workflows/bump_versions.yml, .github/workflows/label.yml, .github/workflows/preview_link.yml
Update (most) of the github workflows so they are in compliance with the Node 12 deprecation in GH actions.
I believe the only one 
Github Actions is deprecating Node 12 which a lot of these actions used
N/A
The actions maintained by Datadog will need PRs to be updated first, then we can update them here.
Specifically `DataDog/labeler@glob-all` used in the label job and `DataDog/github-actions/post-review-status` in the PR approval status job
---
=> WEB-2889 | Update Github Workflows

content/en/metrics/types.md
Fixed the link to statsd's sets documentation
The link was broken
---
=> Fix link to statsd sets documentation

.github/workflows/label.yml
Moves to using the Github maintained labeler
Node 12 is being deprecated by github actions, the github maintained label action is current and up to date.
---
=> Update labeler to use gh action

content/en/database_monitoring/setup_postgres/troubleshooting.md
The postgres integration is now going to start emitting a new warning as part of [this fix](https://github.com/DataDog/integrations-core/pull/13426) and this warning will point to the troubleshooting documentation for more details. This adds the new troubleshooting entry along. Note that it very importantly has a anchor so that the permanent link is stable and valid when users follow this link for help.
---
=> DBM-1895 Add troubleshooting entry for high-pg-stat-statements-max-configuration

content/en/tracing/trace_collection/tracing_naming_convention/_index.md
Changes error.type and error.message so that the values accurately match the description. It looks like they were swapped!
Ticket about error messages on traces: https://datadog.zendesk.com/agent/tickets/1023409
---
=> Swapping error.type and error.message to match description

content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
Add a small note to prevent customers to fall into a known pitfall.
We had an escalation recently on this topic.
---
=> [Tracer][.NET] IIS app pools should have `No Managed Code` options to run .net core apps.

content/en/continuous_testing/_index.md, layouts/partials/continuous_testing/ct-getting-started.html
Adds a tile selector for the CI/CD integrations.
The RUM product landing page, chat with Beth.
---
=> Adds Integration Tile Partial in Continuous Testing Product Landing Page

content/en/database_monitoring/setup_sql_server/troubleshooting.md
Adds a new `Diagnosing common SQL Server driver issues` section to the SQL Server troubleshooting docs to support additional agent warnings we are adding the integration. Also adds permanent anchors for headers so we can use that as links in our agent warnings.
Adding this additional context for diagnosing known connection issues can be used to support emitting agent warnings in the SQL Server integration. PR for that work is here https://github.com/DataDog/integrations-core/pull/13436.
---
=> Add additional troubleshooting documentation for sqlserver connection issues

.gitlab-ci.yml
- Update the `index_algolia` jobs to use the shared image from the base template
- Job failing due to the before script looking for git which wasn't installed on the image it was pulling from
---
=> feat: update index_algolia jobs to use base template

content/en/account_management/rbac/_index.md, content/en/security_platform/detection_rules/_index.md
Adds documentation for the new granular access controls on security rules:
- security rule permission section under "Security detection rules"
- Reorganize granular access section on RBAC page and add link to security rules permissions
Alert from Product that this feature will be generally available in early December after the code freeze is lifted.
---
=> Document granular access controls for security rules

content/en/dashboards/functions/timeshift.md
- Fix the format of the Further Reading section in Timeshift page
Noticed it as I was browsing
---
=> Fix the format of the Timeshift Further reading section

content/en/database_monitoring/guide/connect_dbm_and_apm.md
Go was the first tracer to get dbm propagation and this was initially using a different naming than what we settled on with other tracers. With [release 1.44.0](https://github.com/DataDog/dd-trace-go/releases/tag/v1.44.0), the Go tracer adopted the standard naming used for other tracers so this updates the documentation for the Go tracer to match the standard naming. 
---
=> Update Go instructions in dbm/apm connect guide to match latest naming

content/en/tracing/guide/instrument_custom_method.md, content/en/tracing/trace_collection/custom_instrumentation/java.md
Adds an explanatory comment to Java code examples that the `scope` returned when activating a `span` needs to be closed.
Customer escalations with broken traces where they had missed that part since the code in the samples uses a _try with resource_ block that will close the `scope` automatically.
---
=> Add explanation that trace scopes need to be closed

content/en/security_platform/cloud_siem/_index.md
Adds a link to the AWS configuration for Cloud SIEM doc.
DOCS-4512, PM request.
---
=> [DOCS-4512] Add link to AWS config for Cloud SIEM doc

content/en/agent/guide/auto_conf.md
Adding Helm options for auto_conf `datadog.ignoreAutoConfig`
Getting documentation updated with relevant Helm config
---
=> Updating Helm options for Auto_conf

go.mod, go.sum
Bump module version on Documentation
Careers has been moved off of corp and now lives on it's own domain https://careers.datadoghq.com/
Links to careers in the nav and footer have been updated to reflect that change and the Documentation site can consume the most recent version of modules.
https://docs-staging.datadoghq.com/brooklyne.finni/module_bump/
---
=> [WEB-2847]module bump

content/en/agent/logs/advanced_log_collection.md
Previously, the rule displayed included an ending "\s" for the regex pattern to match for Java logging formats that start with a timestamp in yyyy-dd-mm format - however, the log examples provided actually have a "yyyy-mm-ddThh:mm:sssZ" format that does not match (because of the "T" separator that doesn't match as a whitespace character).
I'm updating the rule example to remove this so that the match truly applies for a pattern of yyyy-mm-dd.
---
=> Update multi_line_aggregation code example

content/en/profiler/enabling/php.md, content/en/tracing/trace_collection/library_config/php.md
Update PHP profiling configuration:
1. ddtrace v0.82.0 has profiling INI support, so update those. It also makes the profiler enabled by default (if it's installed, it is not installed by default).
2. Add missing `DD_PROFILING_ENDPOINT_COLLECTION_ENABLED`.
3. Add missing `trace` level for `DD_PROFILING_LOG_LEVEL`. It has been there for quite a few versions.
A new ddtrace version was released.
I would like to also update the profiling and tracing installation docs to prefer setting INI settings in a file over doing it in Apache and nginx configuration files. However, it's not easy to tell users where these files are. I'm hoping we can fix this in a future update of `datadog-setup.php`.
---
=> Update PHP profiling configuration

layouts/partials/api/code-example.html
Some of the legacy code examples were not showing. The reason being we were limiting to the first 3, however because we included examples in the slice that don't exist we would limit to the first 3 non existant examples and then show nothing because the existing example is index 4. This PR makes sure we are dealing with existing examples only when iterating.
Api channel
Check `python[legacy]` or `ruby[legacy]` code examples in various places. E.g create a monitor or create a dashboard are good examples
https://docs-staging.datadoghq.com/david.jones/legacy-example/api/latest/monitors/?code-lang=python-legacy#create-a-monitor
https://docs-staging.datadoghq.com/david.jones/legacy-example/api/latest/dashboards/?code-lang=python-legacy#create-a-new-dashboard
---
=> legacy code examples fix

content/en/containers/amazon_ecs/logs.md, static/resources/json/datadog-agent-ecs-logs.json, static/resources/json/datadog-agent-ecs-win-logs.json
Make some large changes to the ECS Log Collection doc similar to the recent one for the core ECS Agent setup:
- https://github.com/DataDog/documentation/pull/15999
The main goal here was to provide simpler instructions with more detailed examples configurations. While also providing more context into some of the important details for the configuration. Changes like:
- Cleaning up and referencing the `datadog-agent-ecs-logs.json` Task Definition file (existed but unreferenced)
- Adding an example Task Definition file for Windows log collection `datadog-agent-ecs-win-logs.json`
- Provide example Task Definitions for customizing autodiscovery labels
- Provide example Task Definition for file collection / file and stream collection
- Re-frame the context towards what the Agent is collecting …
=> Cleanup and add more samples for ECS/EC2 log collection

translate.yaml
Re-enables the translation pipeline, which was frozen temporarily while migrating `security_platform/` URLs to `security/`
URL migration completed
---
=> Re-enable translations

content/en/containers/kubernetes/distributions.md
Adding documentation for the AKS kubernetes distributions page in reference to new `envar` `DD_ADMISSION_CONTROLLER_ADD_AKS_SELECTORS` needed: 
https://github.com/DataDog/datadog-agent/pull/11367
Updating AKS specific documentation
---
=> adding AKS admission controller add selector

layouts/shortcodes/dbm-sqlserver-agent-setup-windows.md
Starting in agent version 7.41, we will support SQL Server Browser Service. This change adds a note about how to configure SQL Server for Windows to enable SSBS. 
Note: this is prepped but won't get merged until mid-Nov, when we are closer to Agent 7.41 release. 
---
=> sqlserver: add note about sql server browser service

assets/styles/components/_grouped-item-listings.scss, layouts/partials/grouped-item-listings.html
Adds the ability to link directly to items in the Workflow Action Catalog.
https://datadoghq.atlassian.net/browse/WEB-2816
Here are some examples. The links are easily constructed by just adding the item you want to link to at the end and replacing spaces with hyphens.
https://docs-staging.datadoghq.com/fitzage/action-catalog-anchors/workflows/actions_catalog/#aws-eventbridge
https://docs-staging.datadoghq.com/fitzage/action-catalog-anchors/workflows/actions_catalog/#aws-resources-tagging
---
=> Action catalog anchors

content/en/profiler/enabling/ruby.md
Update minimum supported Ruby version for Ruby profiler from 2.1 to 2.2.
We've dropped support for Ruby 2.1 some time ago
(<https://github.com/DataDog/dd-trace-rb/pull/2140>) and I spotted that the documentation was outdated.
(N/A)
---
=> Update minimum supported Ruby version for Ruby profiler

content/en/logs/log_configuration/indexes.md
- Initially, the permissions required to delete and index where "Modify index" and "User manage access."
- There's now a [Logs delete data](https://docs.datadoghq.com/account_management/rbac/permissions/#log-management) permission that is required. Having "Modify index" does not allow you to delete. 
- I found this out through one of my customers who was stuck trying to get their roles to work such that they could delete an index.
---
=> Update Required Permissions to Delete an Index

assets/styles/components/_grouped-item-listings.scss, layouts/partials/grouped-item-listings.html
CSS fix so the search input is not disabled on Chrome.
https://datadoghq.atlassian.net/browse/WEB-2986
https://docs-staging.datadoghq.com/brian.deutsch/ootb-rules-search/security/default_rules/
https://docs-staging.datadoghq.com/brian.deutsch/ootb-rules-search/workflows/actions_catalog/
Search bar is not disabled and it is working properly on both Chrome and FF
---
=> [WEB-2986] Fixes search input on Default Rules page

content/en/monitors/types/ci.md
Add information on new and existing flaky tests to CI monitors page
There was a clarifying question in the #ci-app channel about flaky test monitors
---
=> Add information on new and existing flaky tests to CI monitors page

.gitlab-ci.yml, package.json
Adds debugging to the build_site script in the gitlab runner
We need to try and identify why some build fail to complete before deploying
---
=> Add debugging to build site script 

.gitignore, .gitlab-ci.yml
Adds the public folder so that it is always in the directory (still excludes all the files except for the `.gitkeep` file)
A possible workaround for how we handle static assets. This was a [hugo issue](https://github.com/gohugoio/hugo/issues/8166) that was somewhat similar to what we have. Due to how we place the `static` directory into `assets` I'm wondering if this may possibly be the issue. This change may mitigate our problem or it may not, but this will not effect anything negatively having the empty directory in the repo prior to build.
---
=> Add public folder

config/_default/params.yaml
- Update the accepted code-lang parameter for Node.js, following this doc: https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1182958054/Markdown?src=search#Programming-languages
- This change is related to this [PR](https://github.com/DataDog/documentation/pull/16232), to standardize `NodeJS` to `Node.js`
---
=> Update NodeJS to Node.js

content/en/containers/amazon_ecs/apm.md, content/en/continuous_integration/tests/javascript.md, content/en/continuous_integration/tests/junit_upload.md, content/en/continuous_testing/cicd_integrations/jenkins.md, content/en/database_monitoring/guide/connect_dbm_and_apm.md, content/en/logs/error_tracking/backend.md, content/en/logs/log_collection/nodejs.md, content/en/security/application_security/add-user-info.md, content/en/security/application_security/getting_started/nodejs.md, content/en/security/application_security/setup_and_configure.md, content/en/security/application_security/troubleshooting.md, content/en/serverless/azure_container_apps/_index.md, content/en/serverless/google_cloud_run/_index.md, content/en/tracing/guide/configuring-primary-operation.md, content/en/tracing/metrics/runtime_metrics/nodejs.md, content/en/tracing/other_telemetry/connect_logs_and_traces/nodejs.md, content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md, content/en/tracing/trace_collection/compatibility/nodejs.md, content/en/tracing/trace_collection/custom_instrumentation/nodejs.md, content/en/tracing/trace_collection/library_config/nodejs.md, content/en/tracing/trace_collection/open_standards/nodejs.md, content/en/tracing/trace_pipeline/ingestion_mechanisms.md, content/en/tracing/troubleshooting/tracer_startup_logs.md
- renames all human-readable instances of "NodeJS" to "Node.js"
- does not rename the isntances that are used for stating language name or for tabs
- the correct spelling is Node.js, see https://nodejs.org/en/
- the documentation did use Node.js in some places so this fixes consistency
---
=> rename human-readable NodeJS to Node.js

local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
Adds an alias for the single-sourced ruby APM setup page
DOCS-4562, 404s report
The following links should redirect to a real page, not 404: https://docs-staging.datadoghq.com/kari/docs-4562-ruby-redirect/tracing/trace_collection/ruby
---
=> DOCS-4562 add redirect that is getting 404s

content/en/profiler/enabling/python.md, content/en/profiler/profiler_troubleshooting.md
Ensure pip requirement is described in the install. If pip is at an older version we are getting the following error 
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-ymqm0401/ddtrace/setup.py", line 11, in <module>
from Cython.Build import cythonize  # noqa: I100
ModuleNotFoundError: No module named 'Cython'
```
I was failing during installation for unknown reasons.
---
=> APM Python - Decribe pip requirement for profiling

layouts/shortcodes/dbm-sqlserver-agent-config-examples.md
Adds an example config for connecting to sql server instances that utilize port autodiscovery for connections, e.g.: named instances or sql server browser service
Based on discussion from this PR https://github.com/DataDog/integrations-core/pull/13148#discussion_r1047195535
---
=> Add configuration example for connecting to sql server named instances

content/en/security/application_security/add-user-info.md, content/en/tracing/trace_collection/library_config/nodejs.md
- previously, the node.js APM team treated [this page](https://datadog.github.io/dd-trace-js/#tracer-settings) as the source of truth for configuration docs
- that information is being brought over to this repository and removed from the other website
- hoping to make things more consistent
- maintaining docs in two places is silly
https://docs-staging.datadoghq.com/tlhunter/migrate-nodejs-config/tracing/trace_collection/library_config/nodejs
---
=> migrating node.js APM configuration

content/en/tracing/trace_collection/open_standards/_index.md
Fixes a navigation problem with the language tabs at https://docs.datadoghq.com/tracing/trace_collection/open_standards/java/ (If you click the other language tabs, nothing happens). This is fixed by adding a mostly blank "parent page" for the multi-code-lang pages. They seem to need it to function properly.
To test, go to https://docs-staging.datadoghq.com/kari/fix-otrace-nav/tracing/trace_collection/open_standards/java and check that the language tabs at the top take you to other pages.
Product manager reported the issue.
---
=> fix otracing nav bug

content/en/agent/proxy.md
This PR adds `/api/v2/profile` to `profiling_dd_url` as it's not added by [the code here](https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/api/profiles.go#L38-L43)
We got a 404 when sending profiles through the proxy with the current config (see https://github.com/DataDog/haproxy-dd-profiling for an example)
https://docs-staging.datadoghq.com/nicolas.guerguadj/update-profiling-dd-url-when-using-proxy/agent/proxy/?tab=linux#datadog-agent-configuration-1
https://docs-staging.datadoghq.com/nicolas.guerguadj/update-profiling-dd-url-when-using-proxy/agent/proxy/?tab=linux#datadog-agent-configuration-2
---
=> Fix missing endpoint for profiling on the Agent proxy documentation

content/en/network_monitoring/devices/snmp_metrics.md
- Easy to have an accidental error if you take things litearlly:
```
error: Error building params for device 192.168.19.119: Unsupported privacy protocol: AES (128 bits)
```
Removes the extra space and brackets around 
All the other examples can be added 'as is' but the 128 option doesnt, leading to a hard to figure out error: 
```
error: Error building params for device [192.168.19.119](http://192.168.19.119/): Unsupported privacy protocol: AES (128 bits)
```
---
=> Clarified aes example option

content/en/security/cloud_siem/investigator.md
> slack:
I'm wondering where I can report a broken link on a public facing blog post? The "documentation" link at the end of the following article leads to a 404 Error page: https://www.datadoghq.com/blog/visualize-cloud-activity-datadog-cloud-siem-investigator/. Thanks!
=> add redirect for blog link

content/en/logs/explorer/search_syntax.md
Added the phrase "case sensitive" for Boolean operators - at least that's how it's behaving for me
Added the phrase "case sensitive" for boolean operators.
The boolean operators are working only in uppercase for me.
---
=> Added the phrase "case sensitive"

content/en/containers/kubernetes/distributions.md
Removed references to host and hostCAPath as those are actually not required when disabling tlsVerify.
Having host and hostCAPath wth tlsVerify shouldn't actually be an issue since the CA isn't going to be used if tls verify is disabled. However, it seems that it had some side effects where the security agent was attempting tls verification due to the presence of hostCAPath. References to host and hostCAPath should be removed as it is misleading and not required.
---
=> Clarify Required Configurations for AKS

content/en/profiler/enabling/dotnet.md, content/en/profiler/search_profiles.md
Add runtime version requirement for .NET profiling
Customers support cases have shown that version requirement was missing 
---
=> [.NET Profiler] Add requirements for .NET allocation and lock contention profiling

content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
Typo has been highlighted by the customer. The value 3 was incorrectly input instead of 8.
---
=> Updating doc to fix typo

content/en/profiler/enabling/dotnet.md, content/en/profiler/search_profiles.md
Fix .NET version requirement for allocation profiling
Should be .NET 6+ instead of .NET 5+
---
=> [.NET Profiler] Fix version error for .NET allocation profiling

content/en/tracing/trace_collection/library_config/java.md
Adds documentation about baggage mapping configuration parameters implemented by PR:  https://github.com/DataDog/dd-trace-java/pull/4404
I created the implementation, therefore the documentation must be kept up to date.
---
=> Add dd.trace.header.baggage config description for java tracing.

content/en/opentelemetry/otel_collector_datadog_exporter.md
Updates OpenTelemetry Collector examples to use new `${env:ENV}` style syntax.
See open-telemetry/opentelemetry-collector-contrib/issues/17299
---
=> [opentelemetry] Use new style ${env:ENV} syntax on Collector examples

config/_default/menus/menus.en.yaml
Updates **sidenav** item "Cloud Security Management" icon to the new icon currently used in the main nav product dropdown
https://datadoghq.atlassian.net/browse/WEB-3011
Sidenav icon updated for CSM: https://docs-staging.datadoghq.com/davidweid/web-3011-csm-sidenav-icon/security/cloud_security_management
---
=> Update Sidenav Icon - Cloud Sec Management

content/en/security/cspm/getting_started.md
CSPM for GCP is now GA, updated docs to reflect this change
---
=> removed beta warning banner

static/resources/json/datadog-agent-ecs.json
Updated the readOnly values from `null` to `true`.
[DOCS-4519](https://datadoghq.atlassian.net/browse/DOCS-4519), which is reader feedback pointing out that the JSON file provides an invalid value for the property called `MountPoint` in Amazon AWS.
---
[DOCS-4519]: https://datadoghq.atlassian.net/browse/DOCS-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-4519]: https://datadoghq.atlassian.net/browse/DOCS-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> updated readOnly values

content/en/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md, content/fr/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md, content/ja/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md
`dog dashboard` is a supported command but not listed in the docs.
Add reference to `dog dashboard` as a valid command.
[#750](https://github.com/DataDog/datadogpy/issues/750)  where I read the web docs and didn't notice there was an additional command available in the cli, which caused some confusion.
---
=> Add cli dog dashboard reference

content/en/synthetics/_index.md, content/en/synthetics/dashboards/_index.md, content/en/synthetics/dashboards/api_test.md, content/en/synthetics/dashboards/browser_test.md, content/en/synthetics/dashboards/test_summary.md
Standardize "Synthetic" as the modifier for the Synthetic Monitoring product.
Conversation in Transifex with Spanish translators (https://www.transifex.com/datadog/documentation_loc/translate/#es_ES/content_en_getting_started_synthetics_private_location_md/190359746).
---
=> Standardize "Synthetic" Modifier in Dashboard Docs

content/en/cloud_cost_management/_index.md
Indicates that Parquet format is acceptable for reports ingested by CCM (in addition to GZIP csv)
We want to make it clear that we support both formats.
Here's what the setup screen looks like
---
=> [ccm] add support for parquet format

content/en/integrations/guide/azure-troubleshooting.md
Also remove reference to decommissioned classic portal
Update instructions on how to find Tenant Name.
Saw out of date content.
https://docs-staging.datadoghq.com/islam/az-troubleshooting-update/integrations/guide/azure-troubleshooting/
N/A.
---
=> Update the instructions for finding Tenant Name

content/en/security/application_security/how-appsec-works.md, content/en/security/application_security/setup_and_configure.md, layouts/shortcodes/asm-protection-page-configuration.md
=> Revamp the ASM blocking page configuration section to include in 2 pages

i18n/ja.json
Updates the JA support page to indicate that you no longer email support. 
This is one of the rare things NOT handled by transifex, but it is officially translated. 
---
=> updating to reflect that you no longer email support

i18n/ja.json
I forgot to make https://github.com/DataDog/documentation/pull/16371 a href 🙃
---
=> forgot to make it an href

content/en/agent/guide/private-link.md
Adds a note to clarify that additional configuration is not required for setting up PrivateLink with agents using versioned endpoints.
Make it easier to configure and setup PrivateLink.
https://docs-staging.datadoghq.com/bobmshannon/privatelink_docs_enhancement/agent/guide/private-link
N/A
---
=> Document versioned endpoint behavior for PrivateLink setup

content/en/tracing/trace_collection/custom_instrumentation/go.md
Update the documentation for configuring B3 header injection and extraction for
the Go tracer.
The Go tracer has changed the environment variables for configuring B3
headers injection and extraction, including a new environment variable
to configure both. See https://github.com/DataDog/dd-trace-go/pull/1603.
=> [go] Update B3 header environment variable documentation

content/en/database_monitoring/setup_mysql/rds.md, content/fr/database_monitoring/setup_mysql/rds.md, content/ja/database_monitoring/setup_mysql/rds.md
The mysql monitoring account doesn't require CREATE TEMP TABLE privilege anymore. The documentation has been updated to reflect that.
The SQL statement sampling has been redesigned in https://github.com/DataDog/integrations-core/pull/13561 .
---
=> removed CREATE TEMP TABLE from mysql instructions

content/en/dashboards/widgets/pie_chart.md, content/en/dashboards/widgets/treemap.md
- Updated wording on data sources for pie chart and tree map widgets.
- User can only select one data source per query.
[DOCS-4643](https://datadoghq.atlassian.net/browse/DOCS-4643)
---
[DOCS-4643]: https://datadoghq.atlassian.net/browse/DOCS-4643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update wording regarding available data sources

assets/scripts/components/dd-browser-logs-rum.js, assets/scripts/config/config-docs.js, package.json, yarn.lock
- bumps package version for DD Rum & Logs
- adds IA subdomain param to config
- updates config so data populates in the `Documentation - Prod` RUM application in DD
https://datadoghq.atlassian.net/browse/WEB-2989
https://docs-staging.datadoghq.com/brian.deutsch/rum-bump
We'll remove the `Documentation - Staging` app in DD once the current data is no longer retained
---
[WEB-2989]: https://datadoghq.atlassian.net/browse/WEB-2989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RUM & Logs package bump

content/en/tracing/trace_explorer/visualize.md
Adds information about the "latency breakdown" column in the public docs
[](https://datadoghq.atlassian.net/browse/APMS-8435)
---
[APMS-8435]: https://datadoghq.atlassian.net/browse/APMS-8435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Mtoff add latency breakdown info

config/live/config.yaml, config/preview/config.yaml
Some resources aren't being deployed because of an exclusion
e.g https://docs.datadoghq.com/resources/sh/rpm_check.sh
Fixing a 404
clicking `this script` shouldn't 404
https://docs-staging.datadoghq.com/david.jones/deploy-resource/agent/faq/circleci-incident-impact-on-datadog-agent/#verifying-installed-agent-packages
This script links to `https://docs-staging.datadoghq.com/david.jones/deploy-resource/resources/sh/rpm_check.sh`
---
=> Fixing broken resource link

content/en/database_monitoring/setup_mysql/aurora.md
We didn't have documentation/support listed for mysql 8 in for aws aurora but this works and should be included. This came up as a support question and we validated that a new aurora mysql 8 instance works without problems. 
---
=> Update database monitoring aurora setup docs to include missing support for mysql 8

.gitlab-ci.yml
Changes our CI files to utilize the newest version of the shared image, as well as new commands for deploy. It also adds environments where missing for certain jobs that will need it for deploys.
We're attempting to have one image used for both corp and docs
https://docs-staging.datadoghq.com/devin.ford/WEB-2929/
This one will just require some QA and a lot of combing over the gitlab-ci as another set of eyes to ensure all functions have been converted and that anything running the `deploy_site` command has an environment tagged in the job.
---
=> WEB-2929 | Image and CI updates

content/en/agent/guide/network.md, content/en/tracing/trace_collection/library_config/cpp.md, content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md, content/en/tracing/trace_collection/library_config/go.md, content/en/tracing/trace_collection/library_config/java.md, content/en/tracing/trace_collection/library_config/nodejs.md, content/en/tracing/trace_collection/library_config/php.md, content/en/tracing/trace_collection/library_config/python.md
Clarifies in Agent config and APM config docs that the Agent's APM port and the tracing library's port must match
DOCS-4628
---
=> DOCS-4628 mention that ports in agent and library config must match

content/en/logs/explorer/search_syntax.md, content/en/metrics/advanced-filtering.md
- Added information regarding Logs query syntax, specifically the exclusion query and needing to apply it to each individual raw text search
- Added a reference link to the logs query page in the Metrics Advanced Filtering, users are applying the metrics filtering to events queries and they are not the same.
[DOCS-4625](https://datadoghq.atlassian.net/browse/DOCS-4625)
---
[DOCS-4625]: https://datadoghq.atlassian.net/browse/DOCS-4625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added info on logs exlusion query

content/en/tracing/trace_collection/dd_libraries/dotnet-framework.md
Found a dead github link when trying to find docs for a customer. 
Fixed the URL with the correct link 👍 
Dead URL - https://github.com/DataDog/dd-trace-dotnet/tree/master/docs.Datadog.Trace.Bundle/README.md
Fixed URL - https://github.com/DataDog/dd-trace-dotnet/blob/master/docs/Datadog.Trace.Bundle/README.md
Keep public docs up-to-date
---
=> Dead URL Fix

content/en/agent/faq/agent-downgrade-major.md, content/en/agent/faq/rpm-gpg-key-rotation-agent-6.md, content/en/agent/versions/upgrade_to_agent_v6.md, content/en/data_security/agent.md
Removes mentions of the old Agent RPM GPG key that was used to sign old versions of Agent 5 and 6.
---
=> Remove mentions of the old Agent RPM GPG key

Makefile, layouts/partials/footer/footer.html
We picked up some inconsistencies with the footer language links when using partialCached
This PR attempts to solve these by directing to the home page.
This update also includes a change to the pip install to avoid some bdist_wheel errors we have seen in the build.
FIxing incorrect language links in footer
Check the toggle language at the very bottom of the footer
https://docs-staging.datadoghq.com/david.jones/footer-lang/
---
=> footer lang link updates

content/en/tracing/configure_data_security/_index.md
- Add configuration example for `error.msg` in the `replace_tags` setting/`DD_APM_REPLACE_TAGS` environment variable to replace sensitive data in spans
[DOCS-4638](https://datadoghq.atlassian.net/browse/DOCS-4638)
---
[DOCS-4638]: https://datadoghq.atlassian.net/browse/DOCS-4638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added example of `error.msg` to scrub APM span

content/en/tracing/trace_collection/library_config/php.md
Adds `DD_TRACE_FORKED_PROCESS` and describe how to re-enable if set to 0.
---
=> Add DD_TRACE_FORKED_PROCESS env var to PHP config

content/en/tracing/trace_collection/compatibility/java.md
Adds GraphQL to the list of supported Java frameworks.
[DOCS-4614](https://datadoghq.atlassian.net/browse/DOCS-4614) (internal feedback).
---
[DOCS-4614]: https://datadoghq.atlassian.net/browse/DOCS-4614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOCS-4614 Add GraphQL to list of supported Java frameworks

content/en/account_management/api-app-keys.md
Replaces outdated information on the API and application key page about transferring keys. Now that Datadog supports service accounts, there is no need to transfer keys or create fake service accounts.
Stacey Csikos, a Solutions Engineer, raised the issue in the #documentation channel.
---
=> Link to service account instructions on application key page

content/en/opentelemetry/otel_collector_datadog_exporter.md
- Partially reverts #16318 because of open-telemetry/opentelemetry-collector/issues/6932.
- Adds `tls::insecure: true` to configuration since it will otherwise not work OOTB. Customers may optionally configure TLS if required by their environment.
Make the example ready to copy and paste.
---
=> [content/en/opentelemetry] Fix OTLP exporter configuration on Collector + Agent setup

content/en/watchdog/faulty_deployment_detection.md
Minor updates to include extension to the feature, which now also cover error rate increases. See also [this doc](https://docs.google.com/document/d/1IGNesQthu1EEDewt9vgdgBU2jIhVx2W2z2HRgcAKbSU/edit#) for a more detailed description.
Ideally, we would also update the screenshots to include the new Watchdog design for the Faulty Deployments UI. If we do, we should also update the text to say that the banner is purple rather than yellow.
- [New banner design](https://app.datadoghq.com/apm/resource/inventory-api/http.request/19b3b005b24dcb6b?query=env%3Aprod%20cluster-name%3Ademo-11287-us-prod-west%20service%3Ainventory-api%20operation_name%3Ahttp.request%20resource_name%3A%22PUT%20%2Finventory%22&env=prod&hostGroup=demo-11287-us-prod-west&spanType=all&topGraphs=latency%3Ahistorical%2Cerrors% …
=> [DSFL-1101] Update faulty_deployment_detection.md

.gitlab-ci.yml
Remove allow failure flag from preview link check job
Remove a deprecated tag
Now that the link check preview job has been passing consistently, only true failures should trigger an actual failure, so we want to block deploys if links are broken.
The tag removal is a tac on, and has no effect on the CI
---
=> feat: remove allow failure flag

content/en/getting_started/site/_index.md
Adds text to make it clear that the domains are for RUM traffic.
[DOCS-4478](https://datadoghq.atlassian.net/browse/DOCS-4478)
---
[DOCS-4478]: https://datadoghq.atlassian.net/browse/DOCS-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4478] Clarify domains are for RUM traffic

static/resources/sh/rpm_check.sh
Updates the `rpm_check.sh` script to fix an issue on hosts where `grep` output is colored by default.
Prevent the script from erroring in some edge cases where it shouldn't.
---
=> Update rpm_check.sh script with grep fixes

content/en/metrics/guide/interpolation-the-fill-modifier-explained.md
- Move the **Interpolation and the Fill Modifier** FAQ doc to the Metrics Guide
- Add alias of former location
- Noticed this was not discoverable outside of a link
- Will add this to Guides index in a separate PR
---
=> Move the interpolation FAQ to Metrics Guides

content/en/real_user_monitoring/guide/sampling-browser-plans.md
Remove `open` attribute on code snippets that are not the latest version
Avoid to open multiple snippets for the same case.
---
=> RUM sampling guide: fix multiple snippets opened

config/_default/menus/menus.en.yaml, content/en/observability_pipelines/installation.md
- Adds new Installation doc with alias to old Setup doc
- Adds to nav
[DOCS-4585](https://datadoghq.atlassian.net/browse/DOCS-4585)
I will update links to old setup doc to the new installation doc in the may/replace-vector-op PR (current branch is a branch off of may/replace-vector-op).
---
[DOCS-4585]: https://datadoghq.atlassian.net/browse/DOCS-4585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4585 ]Add OP Worker installation doc

content/en/real_user_monitoring/connect_rum_and_traces/_index.md
RUM now supports correlation with APM through Open Telemetry. This PR updates the documentation with new configuration parameters to use the functionality.
This is the PR for Browser RUM. iOS and Android will soon follow.
---
=> Configuration for OTel support in Browser RUM

config/_default/menus/menus.en.yaml, content/en/observability_pipelines/production_deployment_overview/aggregator_architecture.md
Adds the new Obs Pipelines Worker Aggregator Architecture doc. 
DOCS-4556, PM request.
This branch is created off of may/opw-production-deployment. Once this PR looks good, the plan is to merge this PR into the original branch.
Images won't be ready until 1/20. Since we are planning to publish this doc by 1/18, I will create a separate PR to add the images and content that refer to the images.
---
=> [DOCS-4556] Add Observability Pipelines Worker Aggregator Architecture doc

content/en/agent/guide/network.md
DBM supports US5. This just adds DBM to the networking pages for the US5 datacenter.
---
=> Fix US5 support for DBM network info in docs

content/en/serverless/installation/nodejs.md
Updates the documentation to give users the option of choosing the Node18 runtime for a managed service layer
Upgrading company project to Node18 and went to look at the managed service layer docs for a similar version. 
---
=> chore: Add Node18 as runtime option

content/en/tracing/trace_collection/library_config/go.md
Updates trace context propagation docs in Go.
-  Includes **new** W3c and B3 single header styles. 
- Includes an option to disable propagation. 
Relates to changes in [dd-trace-go PR]( https://github.com/DataDog/dd-trace-go/pull/1630)
---
=> tracing/trace_collector/library_config: updated propagation in go tracer

content/en/tracing/troubleshooting/correlated-logs-not-showing-up-in-the-trace-id-panel.md
Fixes a typo in the number of logs that are available in a Traces side panel.
Typo flagged from translators in Transifex
---
=> Correlated Logs Are Not Showing Up In The Trace ID Panel Edit

content/en/observability_pipelines/installation.md
- Adds a tab on the Installation page for Obs Pipelines Worker Helm instructions.
[DOCS-4693](https://datadoghq.atlassian.net/browse/DOCS-4693)
---
[DOCS-4693]: https://datadoghq.atlassian.net/browse/DOCS-4693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4693] Add OP Worker Helm instructions

.github/CODEOWNERS
Adds marketplace as code owners of /marketplace
---
=> Add marketplace as codeowners

content/en/serverless/installation/go.md
Adds a tab for instructions on setting up a Lambda using a container image for Go.
Did not have instructions for Go.
---
=> [serverless] Add section for container image setup for Go

content/en/database_monitoring/_index.md, content/en/database_monitoring/architecture.md, content/en/database_monitoring/guide/_index.md, content/en/database_monitoring/guide/connect_dbm_and_apm.md, content/en/database_monitoring/setup_sql_server/troubleshooting.md
Adds warnings in some pages that were missing them that DBM is not available for govcloud
support request
---
=> (DOCS-4563) Add missing govcloud warnings to some DBM pages

.gitlab-ci.yml
Datadoc has been deprecated in favor of GCS. Removing the indexing job
=> Removing datadoc job

content/en/watchdog/_index.md
I am Datadog's Trademark Attorney and we need to use the full trademark "Datadog Watchdog" (not just "Watchdog") in a few spots on our website in order to keep the Trademark registered and avoid it going abandoned.  I'm making this change myself since I'm able to submit edits to our public documentation.
---
=> Change to use the full Datadog Watchdog Trademark

content/en/containers/amazon_ecs/_index.md
Add more explicit steps for the DogStatsD setup in ECS. DogStatsD setup is often a two step process:
1. Make sure the Agent container can receive that data
2. Make sure the App container can send that data
In this case making it more explicit that the DogStatsD client needs the EC2 Instance's private IP Address as the endpoint for the DogStatsD data. This leans on the existing documentation for setting this in APM, as the strategy / steps are pretty much exactly the same. 
Clear up setup steps / support cases
https://docs-staging.datadoghq.com/jack.davenport/ecs-dogstatsd/containers/amazon_ecs/?tab=awscli#dogstatsd
---
=> Add more explicit ECS/EC2 DogStatsD instructions for endpoint

content/en/integrations/vmware_tanzu_application_service.md
Removes references to the deprecated cloud foundry buildpack environment variable RUN_AGENT in the PCF docs
It no longer needs to be set in the buildpack
https://docs-staging.datadoghq.com/sarah.witt/remove-deprecated-param/integrations/vmware_tanzu_application_service/
---
=> Remove references to deprecated cloud foundry buildpack environment variable

content/en/account_management/rbac/_index.md, content/en/notebooks/_index.md
Documents the granular access control feature for Notebooks. It's being released this week. Copied from the docs on security rules: https://docs.datadoghq.com/security/detection_rules/#limit-edit-access
Product manager request. 
---
=> Add granular access control docs to Notebooks page

content/en/observability_pipelines/guide/configure_observability_pipelines_with_datadog.md
Add missing alias.
This link should work: https://docs.datadoghq.com/observability_pipelines/integrations/integrate_vector_with_datadog/?tab=yaml
---
=> Add missing alias

content/en/tracing/trace_collection/dd_libraries/nodejs.md
As referred by engineering, customers who upgrade from previous versions of the agent to the latest version should use the migration documentation to avoid any issues in terms of upgrading. Therefore, updating documentation to allow customers to be aware of this migration in case they are upgrading from the previous version.
Adds line similar to ASM documentation highlighting the migration documentation: https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md 
Ticket where customer raised this inquiry and reflected on importance of documentation not being visible in main installation guide. 
---
=> Adding Migration documentation to Node.js Setup

content/en/continuous_integration/tests/junit_upload.md
Fixes a typo in the `Test Suite from @classname` example CLI command
I noticed the typo while working with the example CLI usage
---
=> Fix Test Suite from @classname code snippet

content/en/containers/kubernetes/distributions.md
removing a parameter that no longer exists in the helm chart
---
=> DOCS-4622 - removing outdated param

content/en/agent/guide/dual-shipping.md
Updates a 404 link to the Configuration file (https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.md) that is now divided into V1 and V2.
Hotjar
---
=> Dual Shipping Link Fix

content/en/database_monitoring/setup_postgres/troubleshooting.md
Updates DBM's Postgres extended query protocol troubleshooting docs to include a new feature that enables the Agent to explain parameterized queries for Postgres version 12 or newer.
---
=> Update DBM's Postgres extended query protocol troubleshooting

assets/scripts/datadog-docs.js
Update redirect script to highlight new **Integrate Datadog and the Worker** section under **Observability Pipelines** when **Aggregating Agents** is selected in the nav
https://datadoghq.atlassian.net/browse/WEB-3093
https://docs-staging.datadoghq.com/brooklyne.finni/update_nav/
---
=> [WEB-3093]update redirect support script for 'Aggregating Agents'

content/en/profiler/enabling/dotnet.md
This PR update the Nuget-based setup for the .NET profiler
Customer reported that the doc did not help and we figured out that it was out-of-date or missing important information
---
=> Update .NET profiler doc on Nuget setup

content/en/tracing/trace_collection/library_config/nodejs.md
Add new configuration (remote configuration polling interval) for NodeJs tracer.
---
=> Add RC polling interval configuration for NodeJs

assets/scripts/datadog-docs.js, config/_default/menus/menus.en.yaml, content/en/observability_pipelines/_index.md, content/en/observability_pipelines/configurations.md, content/en/observability_pipelines/guide/_index.md, content/en/observability_pipelines/production_deployment_overview/integrate_datadog_and_the_observability_pipelines_worker.md, content/en/observability_pipelines/working_with_data.md
- Moves "Configure OP with Datadog" out of Guide section and  under Production Deployment Overview.
- Renames doc to "Integrate Datadog and the Observability Pipelines Worker"
- Adds alias
- Adds nav entry
- Update old links
- The JS script update is to make Agent > Aggregating Agents in the nav jump down to the "Integrate Datadog and the Worker" in the Obs Pipelines section of the nav.
[DOCS-4692](https://datadoghq.atlassian.net/browse/DOCS-4692)
---
[DOCS-4692]: https://datadoghq.atlassian.net/browse/DOCS-4692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4692] Move and rename Configure OP with Datadog 

content/en/serverless/google_cloud_run/_index.md
hotjar question asked about the [pack](https://buildpacks.io/docs/tools/pack/) command, updating with context and a link to pack
---
=> DOCS-4249 add pack command in google cloud run

assets/scripts/components/mobile-nav.js
Updates the nav menu so that clicking on "Agent> Aggregating Agents" in the nav jumps down to "Integrate Datadog and the Worker" in the Obs Pipelines section of the nav.
[DOCS-4692](https://datadoghq.atlassian.net/browse/DOCS-4692)
[WEB-3093](https://datadoghq.atlassian.net/browse/WEB-3093)
https://docs-staging.datadoghq.com/may/update-mobile-menu-op/observability_pipelines/production_deployment_overview/integrate_datadog_and_the_observability_pipelines_worker/
---
[DOCS-4692]: https://datadoghq.atlassian.net/browse/DOCS-4692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3093]: https://datadoghq.atlassian.net/browse/WEB-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update mobile menu link for Integrate Datadog and the Worker

content/en/real_user_monitoring/browser/monitoring_page_performance.md
Specifically callout lab metrics in the Monitoring Page Performance page.
Beth's feedback in #16522.
---
=> Monitoring Page Performance Edit

content/en/database_monitoring/setup_sql_server/troubleshooting.md, layouts/shortcodes/dbm-sqlserver-before-you-begin.md
Splits out the different types of TCP error messages we see in the agent since as of 7.40 we no longer allow the agent to emit the "Invalid connection string attribute" error. I am leaving the reference to it for people who are using older versions of the agent, but this error is due to a tcp connection issue & so it should be documented that way. 
**Also** bumps min agent version to 7.41 (latest release, which includes this fix https://github.com/DataDog/integrations-core/pull/13089)
Support request where customer was seeing
```
TCP-connection(ERROR: getaddrinfo failed). Exception: unable to connect: could not open database requested by login
```
due to a port misconfiguration && was not able to troubleshoot on their own. Had they tried to telnet on port 1433 they would've figured out …
=> Make troubleshooting TCP errors easier to follow

assets/styles/pages/_reference.scss
Moves a styling override for code block margins into the correct scope so it doesn’t override the standard code block margins.
Spacing issues between code blocks and following content reported on Slack. You can see [an example here](https://docs.datadoghq.com/database_monitoring/setup_sql_server/selfhosted/). 
https://docs-staging.datadoghq.com/fitzage/code-spacing/database_monitoring/setup_sql_server/selfhosted/?tab=sqlserver2014
---
=> fixed spacing after code blocks

content/en/opentelemetry/otel_collector_datadog_exporter.md
Remind the readers that they may need different batch sizes for batch processor for different signal types (traces/metrics/logs) when using datadog exporter.
The previous comment and config in the batch processor only refers to the payload size limit of trace intake. When customers use the same config for metrics or logs pipeline, they may get 413 errors because metrics and logs have a smaller payload size limit than that in trace. This led to customer confusions and issues being filed in https://github.com/open-telemetry/opentelemetry-collector-contrib.
Related customer issues:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16834
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/17566
Also note that the payload size limits in metrics …
=> [content/en/opentelemetry] Mention different signals request different batch processor configs

content/en/monitors/guide/create-monitor-dependencies.md
- Reference the correct image source in [docs](https://docs.datadoghq.com/monitors/guide/create-monitor-dependencies/)
- I tried renaming the image path name at first, but the reference would not load the image. However, renaming the source somehow works.
---
=> Fixed reference link to image

content/en/agent/guide/private-link.md
- Makes docs only available for US1, the only supported site.
- Consolidate unsupported alert box.
[DOCS-4712](https://datadoghq.atlassian.net/browse/DOCS-4712)
---
[DOCS-4712]: https://datadoghq.atlassian.net/browse/DOCS-4712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4712] Make AWS PrivateLink doc available only for us1

assets/scripts/components/table-of-contents.js
fix to scroll-to anchor for pages using hash params loaded on Chrome browsers 
https://datadoghq.atlassian.net/browse/WEB-3105
https://docs-staging.datadoghq.com/stefon.simmons/fix-scrollto-page-load/serverless/google_cloud_run/#advanced-options-and-configurations
---
=> fix chrome scroll to issue - [WEB-3105]

content/en/profiler/enabling/ruby.md
This PR updates the "Enabling the Ruby profiler" page to list that the Ruby profiler requires the `pkg-config` tool installed.
It also lists out common names for this system tool in common Linux distributions.
Finally, it removes the "profiling features list" table, because the 0.54.0 version mentioned is by now 15 months old, and 0.49.0 is 20 months old, so I don't think it's relevant anymore to mention them -- customers should be on the 1.x release, and all 1.x releases include these features.
We've had the `pkg-config` dependency for quite some time, and unfortunately some customers discovered that we need it because we check and emit an error message.
To improve this experience, I'm listing this on the documentation so that customers can refer back to it if they run into issues.
(N/A) …
=> Document that Ruby profiler depends on pkg-config

.gitignore, config/_default/menus/menus.en.yaml, content/en/real_user_monitoring/flutter/otel_support.md, local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
Adds a new page about Open Telemetry Support for RUM Flutter and single sources it from the `dd-sdk-flutter` repo.
[DOCS-4654](https://datadoghq.atlassian.net/browse/DOCS-4654), which is an internal contribution.
---
[DOCS-4654]: https://datadoghq.atlassian.net/browse/DOCS-4654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOCS-4654 Otel support for RUM Flutter

content/en/agent/troubleshooting/hostname_containers.md
Document new hostname option introduced in https://github.com/DataDog/datadog-agent/pull/14569
---
=> Document new Agent option (hostname_trust_uts_namespace)

layouts/partials/header-scripts.html
Stop inlining the dd libs to reduce html size, we don't need to inline it anymore
After reviewing artifacts seeing the difference
Preview should be the same, check that rum data still appears
https://docs-staging.datadoghq.com/david.jones/reduce-html-size/
---
=> remove inline js

content/en/continuous_integration/tests/javascript.md
Improve instructions around support file for `cypress`.
Make it easier to use `cypress` plugin for CI Visibility. 
[Link to cypress instructions](https://docs-staging.datadoghq.com/juan-fernandez/more-explicit-about-cypress-config/continuous_integration/tests/javascript/?tab=cypress#cypress-10)
---
=> [ci-visibility] Improve `cypress` configuration instructions

content/en/real_user_monitoring/heatmaps/_index.md
- Remove the optional attributes for beta-callout, this was causing the button to open the Sign Up modal, rather than opening up the Google form.
- Request to documentation [[slack](https://dd.slack.com/archives/C0DESMBQU/p1674831245279849)]
=> Fix Heatmaps request for access beta callout

content/en/serverless/distributed_tracing/_index.md
Before was pointing to alias /serverless/distributed_tracing/serverless_trace_merging instead of the anchor one
Fixes a link that was just reloading the page, now it's pointing to the proper anchor.
Good docs FTW
---
=> [cayetano.delgado] fixing broken link to #trace-merging

content/en/serverless/configuration/_index.md
Fixing broken links to trace propagaiion and merging anchors
Updates the links to use the anchors
Good docs FTW!
---
=> [cayetano.delgado] fixing broken links to anchors

.gitlab-ci.yml
Adds the `in-isolation` flag to artifact jobs on the live pipeline
Due to changes in the k8 system, these functions need to run isolated for permissions
---
=> Hotfix: run artifact jobs in isolation for live

content/en/tracing/trace_collection/library_config/java.md
Add documentation for `DD_INSTRUMENTATION_TELEMETRY_ENABLED` for the Java tracer.
We've been using these for a while, and already announced them in release notes.
---
=> Add telemetry config in Java

content/en/account_management/api-app-keys.md
App keys scopes are generally available. Remove the beta callout asking customers to contact support to allow scopes.
Pointed out over Slack by a support engineer.
---
=> DOCS-4678 remove beta callout on scopes because they are public now

content/en/synthetics/private_locations/_index.md
It moves the reference about `DATADOG_API_KEY`, `DATADOG_ACCESS_KEY`, `DATADOG_SECRET_ACCESS_KEY`, `DATADOG_PUBLIC_KEY_PEM` and `DATADOG_PRIVATE_KEY` to inside the ECS tab and makes a note explaining that they don't need to be referenced inside the command section.
Frustration while trying to deploy. I was creating environment variables but they couldn't be accessed inside the command and couldn't figure out why I was getting a 403 error.
---
=> make ECS instructions clearer when using environment variables 

content/en/continuous_integration/tests/java.md
This PR updates CI visibility config instructions for Java with a new section that explains how to configure Java compiler plugin.
The Java compiler plugin is a new component of the CI visibility system.
Datadog clients who use CI visibility will need to add the plugin to their projects' compilation step, and this PR adds the necessary instructions to do so.
---
=> [DOCS-4730] Add instructions for Java compiler plugin configuration

content/en/account_management/billing/containers.md
New container SKU with allotments of 5 (pro) and 10 (enterprise) does not count Datadog agents against the allotment. This updates the answer in the FAQ.
The answer was out of date.
---
=> Update container billing FAQ to be consistent with new container allocation SKU

.gitlab-ci.yml
Points at the versioned image instead of latest
Due to what appears to be caching in the CI pipelines, periodically there is an older version of the `latest` image being pulled and causing errors.
The way image versioning works currently for the private image is by using the pipeline ID from gitlab when the image is built: https://gitlab.ddbuild.io/DataDog/websites-images/-/pipelines/12899749
---
=> Fix | Use versioned image

content/en/tracing/trace_collection/compatibility/python.md
This change adds a line item and link describing [`dd-trace-py`](https://github.com/DataDog/dd-trace-py)'s support for the `gunicorn` web framework. The link currently points to a nonexistent anchor, which will exist once the current [`latest`](https://ddtrace.readthedocs.io/en/stable/integrations.html#gunicorn) documentation becomes `stable`.
My work in https://github.com/DataDog/dd-trace-py/pull/4962 uncovered some new guidelines for using `dd-trace-py` with gunicorn and I want to make them as accessible to users as possible.
---
=> add line item about ddtracepy gunicorn support to python trace compatibility listing

content/en/tracing/trace_pipeline/ingestion_mechanisms.md
This PR updates the ingestion mechanisms to explain how it is configured based on these this Datadog Agent PR for 7.41.0: https://github.com/DataDog/datadog-agent/pull/14102
Explain how the error sampler works. 
https://docs-staging.datadoghq.com/wantsui/error-sampler-update/tracing/trace_pipeline/ingestion_mechanisms
---
=> explain the updates to error sampler in 7.41.x and fix manual drop examples

content/en/observability_pipelines/working_with_data.md
Removes link to Vector doc
---
=> Remove vector link

content/en/containers/cluster_agent/admission_controller.md
=> adding blog link to admission controller docs

content/en/tracing/trace_explorer/_index.md, content/en/tracing/trace_explorer/facets.md
Remove the **Creating Facets** section from the Trace Explorer's Span Facets doc page.
DOCS-4709
---
=> DOCS-4709 Span Facets Doc Edits

content/en/agent/logs/_index.md
On Windows we don't need to escape the backslash in the logs configuration.
Better docs.
---
=> Remove escape backslash for Windows paths in the logs configuration

content/en/tracing/trace_collection/dd_libraries/cpp.md, content/en/tracing/trace_collection/dd_libraries/go.md, content/en/tracing/trace_collection/dd_libraries/nodejs.md, content/en/tracing/trace_collection/dd_libraries/php.md, content/en/tracing/trace_collection/dd_libraries/python.md
Previously the tracing library docs were vague about Azure App Service support. This removes it from pages for languages that aren't supported with it.
DOCS-4791
---
=> Be more specific about what langs support Azure App Svc

content/en/monitors/types/anomaly.md
Removing all references to monthly seasonality for anomaly monitors. 
Monthly seasonality is a private beta feature that is not available to all customers.  More details on this [here](https://datadoghq.atlassian.net/wiki/spaces/DA/pages/2828994062/FADO+-+Monthly+Seasonality+-+Q1+2023+-+Current+state+and+next+steps?atlOrigin=eyJpIjoiMjQ1Njk0NTkxZmI4NDMxZGJiYzhmYjJhOTA1MDUyZjYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ). The option in the monitors creation form is gated behind a feature flag and only available for a couple of beta customers. 
---
=> Removing all references to monthly seasonality for anomaly monitors

content/en/logs/explorer/group.md
Current documentation states that for the Timeseries and Table logging views we only support grouping based on 3 dimensions but we seem to currently support 4 for each of them.
Just updates documentation to reflect the number of supported dimensions for these log views.
=> Change Fields info for 4 dimension support

content/en/tracing/trace_collection/compatibility/php.md
States that we support Symfony 6 in the PHP tracer
---
=> [Tracing] [PHP] Symfony 6 support

content/en/profiler/enabling/ruby.md
This PR updates the requirements listed for Ruby profiling to mention that Ruby 2.3+ is required.
Also, rather than saying "you need MRI Ruby" -- not all Rubyists may know what MRI means -- I've changed it to explicitly say we don't support JRuby or TruffleRuby, which hopefully is clearer.
Make sure documentation is up-to-date with the library support.
(N/A)
---
=> Update Ruby profiler requirements

content/en/tracing/other_telemetry/connect_logs_and_traces/dotnet.md
Change the layout of the doc to have instructions appear in chronological order
It's more logical and also allows to show a warning panel early in the page as we had an escalation about that use case, where this information was missed.
---
=> [Tracing][Logs][.NET] Change order of instructions 

content/en/universal_service_monitoring/_index.md
Adds installation methods of USM for ansible, puppet, and chef.
Relevant PRs:
1. https://github.com/DataDog/puppet-datadog-agent/pull/766
2. https://github.com/DataDog/ansible-datadog/pull/458
3. https://github.com/DataDog/chef-datadog/pull/876
---
=> usm: Added chef, puppet, ansible

content/en/dashboards/sharing.md
- Add clarification on the sharing modal that opens up when users want to share a dashboard.
[DOCS-4775](https://datadoghq.atlassian.net/browse/DOCS-4775)
---
[DOCS-4775]: https://datadoghq.atlassian.net/browse/DOCS-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added specific modal where the sharing options are configured

content/en/agent/troubleshooting/send_a_flare.md
Customers tend to consider <POD_NAME> as the node agent pod and not the cluster agent one. I believe adjusting it like this would save a lot of confusion in the future.
Adjusting <POD_NAME> to <CLUSTER_POD_NAME> will allow customers to use the correct cluster pod name to send cluster agent flares. Often customers have this confusion and this would save some time in support tickets. 
Reduce MTTR for support tickets. 
---
=> Less confusing for customers

content/en/account_management/rbac/_index.md
Changes the Notebooks permissions link to the specific right section
The other links link to the exact section in our docs, while the Notebooks link was the entire Notebooks page
---
=> Update Notebooks permissions link to right section

content/en/account_management/saml/okta.md
Update the order of mentioning which Okta doc to refer to.
Support Case Ticket Number 1057108. Documentation was not clear that the recommended way is actually to setup Okta manually instead of pre-configured.
https://docs.datadoghq.com/account_management/saml/okta/
https://docs-staging.datadoghq.com/mecsantos/propose-change-okta-docs/account_management/saml/okta/
Kindly check have AAA product team to review.
---
=> Clarify which Okta setup doc to use

content/en/continuous_integration/tests/javascript.md
Add instructions to run `playwright` tests with CI Visibility.
Expand support for CI Visibility.
[Link to preview](https://docs-staging.datadoghq.com/juan-fernandez/add-playwright-support/continuous_integration/tests/javascript/?tab=playwright)
---
=> [ci-visibility] Add playwright instructions

.gitlab-ci.yml
Adds a single retry to the live build job. 
Due to heavy usage, it seems like we believe we are periodically hitting a rate-limit with our git token, and it's causing integrations to not get pulled and builds to fail. 
Since they usually work when we manually rerun the job a second time, adding this flag will automatically rerun the job one time in the event of  failure. 
This is a temporary solution while we investigate if we are in fact hitting a rate limit, or if it's something else related to how we source integrations.
Docs for the CI retry flag: https://docs.gitlab.com/ee/ci/yaml/#retry
---
=> Add retry to live job

assets/scripts/components/dd-browser-logs-rum.js
generates a `device_id` cookie and connects it with RUM
https://datadoghq.atlassian.net/browse/WEB-3032
https://docs-staging.datadoghq.com/brian.deutsch/rum-device-id/
---
=> [WEB-3032] adds `device_id` cookie logic

content/en/monitors/manage/status.md
- Add information on the Declare incident option in a Monitor header to match the UI descriptions that already exist
[DOCS-4809](https://datadoghq.atlassian.net/browse/DOCS-4809)
The UI might be changing again, between the Sandbox and Demo accounts, the Declare Incident might be shifting to another button.
---
[DOCS-4809]: https://datadoghq.atlassian.net/browse/DOCS-4809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added info on declaring an incident from monitor

content/en/containers/amazon_ecs/_index.md, content/en/network_monitoring/performance/setup.md, content/fr/containers/amazon_ecs/_index.md, content/fr/network_monitoring/performance/setup.md, content/ja/containers/amazon_ecs/_index.md, content/ja/network_monitoring/performance/setup.md, static/resources/json/datadog-agent-sysprobe-ecs.json, static/resources/json/datadog-agent-sysprobe-ecs1.json
The older env variable, `DD_SYSTEM_PROBE_ENABLED` has been deprecated for a while now and this env variable (`DD_SYSTEM_PROBE_NETWORK_ENABLED`) will actually correspond to the config used on the other tabs.
---
=> Update to use new env variable for enabling system-probe

content/en/tracing/troubleshooting/connection_errors.md
Adds a bit more details in the network troubleshooting doc. It aims at guiding the users to troubleshoot more easily connectivity issues in containerized environments.
We had a customer call where the users had an egress rule that prevented them to connect the tracer to the agent.
---
=> [APM] Add a bit more details in the network troubleshooting doc

content/en/universal_service_monitoring/_index.md
Updates the USM setup documentation in order for containerized environments to support kernel header downloading.
This information is missing from our current documentation
---
=> Update USM docs to support kernel header downloading

content/en/integrations/guide/source-code-integration.md
The delimiter for DD_TAGS is changed from "space" to "comma"
https://dd.slack.com/archives/C04MFJ05CSH/p1675361333229209 for details
---
=> changed the delimiter for DD__TAGS

content/en/tracing/trace_collection/compatibility/java.md
Adds Spring Boot 3 to the server support matrix once https://github.com/DataDog/dd-trace-java/pull/4605/ is merged.
DOCS-4762
---
=> DOCS-4762 Java Compatibility Requirements Edit

content/en/containers/datadog_operator.md
Changing links on Further Reading section: `Datadog Operator: Configuration` should go to the v1alpha1 page
reasoning:
datadog-operator repo uses v1alpha1, 
Helm by default installs version with v1alpha1
v2alpha1 is reserved for GA, TBD.
Changing links on Datadog Operator: Configuration to go to the v1alpha1 page
---
=> Update datadog_operator docs

content/en/account_management/saml/_index.md
Adds a note saying that a particular in-app link only works if you are signed in. Fixes related capitalization and unclear acronym.
Hotjar complaint. User said that the link gives an error for non US1 sites. An engineer on AAA Identity told me that the error means you're not signed in to the site.
---
=> DOCS-4794 add note about signing in for service provider metadata

content/en/containers/kubernetes/prometheus.md
This is a proposed change based on a successful ticket wherein the client pulled all metrics with the annotation below: 
"metrics": [".*"]
https://datadog.zendesk.com/agent/tickets/1088777
This is a proposed change based on a successful ticket wherein the client pulled all metrics with the annotation below: 
"metrics": [".*"]
https://datadog.zendesk.com/agent/tickets/1088777
---
=> Update Note on how to pull ALL metrics

content/en/profiler/profile_types.md, content/en/tracing/trace_collection/library_config/php.md
Document allocation profiling feature in upcoming PHP profiler release.
With the upcoming release of the PHP profiler and tracer we will bring allocation profiling support as a beta release to PHP and we should have documentation for this 🎉 
---
=> document php allocation profiling

content/en/tracing/trace_collection/dd_libraries/java.md
This was still saying DD_TRACE_SAMPLING_SERVICE_RULES in the Java docs.
---
=> updated sampling config to DD_TRACE_SAMPLING_RULES

content/en/database_monitoring/guide/connect_dbm_and_apm.md
The [last release](https://github.com/DataDog/dd-trace-js/releases/tag/v3.13.0) of the node tracer includes support for mysql so this change updates the version and how mysql is now also currently supported. 
---
=> Update node.js info / version with mysql support

content/en/account_management/audit_trail/events.md
Added the Security Notification AuditCategory as well as added an Audit event for when a token leaks
See above
---
=> Add Security Notification Category with token leak event

content/en/containers/docker/integrations.md
adds an example of how to escape JSON, if necessary, while configuring docker labels
---
=> DOCS-3701 - escaping json

content/en/serverless/guide/extension_motivation.md
Recommend using the extension over the forwarder for serverless monitoring, while the forwarder may still make sense for centralized log collection.
This doc was written while the Extension was in beta with lots of uncertainties. Given the growing adoption and confidence, it makes sense to recommend the extension over forwarder for serverless monitoring.
---
=> [serverless] recommend extension over forwarder

content/en/serverless/installation/go.md, content/en/serverless/installation/java.md, content/en/serverless/installation/nodejs.md, content/en/serverless/installation/python.md
Make it explicit that generally speaking people should use the extension instead of the forwarder.
Some users are unsure whether we recommend using the extension or the forwarder.
---
=> Recommend extension over the forwarder

assets/scripts/datadog-docs.js, layouts/shortcodes/img.html
remove lazy loading from img shortcode as temporary scroll issue fix
https://docs-staging.datadoghq.com/renzo.renteria/hash-scroll-bug/integrations/guide/pivotal-cloud-foundry-manual-setup/#deploy-the-datadog-firehose-nozzle
tested on chrome, firefox, and safari
---
=> Renzo.renteria/hash scroll bug

content/en/profiler/profile_types.md
Add version information to the PHP allocation profiling types.
Make sure that folks to not assume that this feature is existing in older version.
=> Add version information for PHP allocation profiling

assets/styles/base/_variables.scss, assets/styles/pages/_home.scss, assets/styles/style.scss, config/preview/config.yaml, layouts/partials/css.html
- Updates the config for previews to no longer upload assets to the bucket
- Adds the img url as an SCSS variable
- Updates the CSS to execute as a template (so we can use the hugo param in the scss files) https://gohugo.io/hugo-pipes/resource-from-template/
https://datadoghq.atlassian.net/browse/WEB-3175
https://docs-staging.datadoghq.com/devin.ford/config-adjustment/
---
=> feat: remove images from previews

content/en/containers/kubernetes/log.md
Makes the operator configuration equivalent with the other two by adding `logsConfigContainerCollectAll`.
---
=> DOCS-4811 - add config to operator docs for log collection

content/en/dynamic_instrumentation/_index.md
Fixed a small typo: redployment -> redeployment.
https://docs.datadoghq.com/dynamic_instrumentation/
=> Fixed a typo in Dynamic Instrumentation docs

content/en/agent/basic_agent_usage/_index.md, content/en/agent/basic_agent_usage/windows.md, content/en/agent/guide/agent-commands.md
Removes the `regimport` command from the documentation. The `regimport` command was removed in Agent version 7.27.
---
=> remove deprecated regimport command

content/en/tracing/trace_collection/compatibility/java.md
The minimum version of spring-boot we know we support is 1.5 instead of 3, we also don't have a specific config for spring-boot, it depends on which spring web implementation you use
=> Update spring-boot minimum supported version

content/en/containers/kubernetes/installation.md
adds a link to changing container registry guide
---
=> DOCS-3965 add operator deployment for kubernetes agent to install page

content/en/tracing/trace_collection/proxy_setup/_index.md
Recent [changes][1] to the nginx tracing module added support for Amazon Linux deployments of nginx.
...I also [forgot to update][2] the code example and this public documentation.
This PR modifies the nginx module section of "Tracing a Proxy" to reflect the changes above, and in particular fixes the install script snippet.
[1]: https://github.com/DataDog/nginx-datadog/pull/11
[2]: https://github.com/DataDog/nginx-datadog/issues/12
=> Support Amazon Linux in the nginx tracing module

content/en/security/cspm/frameworks_and_benchmarks.md
Adds GCP CIS compliance report to the list of compliance reports in public docs
We have the GCP CIS report on the app but not on the docs, so it's misleading to customers.
---
=> Add GCP CIS compliance report to CSPM docs

content/en/account_management/saml/_index.md
Adds a link to the docs describing login overrrides.
Request from a Solutions Engineer. The doc for setting up SAML talks about overriding the strict login methods so you have a backdoor, but doesn't actually tell you how to set an override. This adds a link to our docs about login overrides so the user can click instead of searching.
Ready to merge
---
=> DOCS-4844 Add a link about overriding login methods

content/en/observability_pipelines/installation.md
=> [OPB-582] Fix the OP Worker repo name

content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Update minimal required version for single span mechanism in Java
Follow-up from incident 18687
---
=> update minimal required version java single span

content/en/containers/docker/integrations.md
Adds ADv2 syntax for Docker, bringing it up to parity with the Kubernetes docs. ready to merge
---
=> DOCS-4579 AD v2 syntax for Docker docs

content/en/tracing/trace_collection/custom_instrumentation/go.md
It looks like the Go docs originally had the incorrect envar name. If we look at their code base they never have `DD_PROPAGATION_STYLE` as an envar, only `DD_TRACE_PROPAGATION_STYLE` https://github.com/DataDog/dd-trace-go/search?q=DD_TRACE_PROPAGATION_STYLE
---
=> fix envar config

content/en/logs/guide/collect-heroku-logs.md
Update the docs regarding heroku logs. 
Nowadays the option says to use single quotes , where it actually should be double quotes
=> [US-PROD]-update-heroku-logs

content/en/tracing/trace_collection/library_config/java.md
It updates the documentation of Java Tracing Library, namely the default value for one of the configuration parameters (`dd.http.server.tag.query-string`).
Current version of the documentation does not reflect accurately how one of the configuration parameters is handled. Here [in the code](https://github.com/DataDog/dd-trace-java/blob/v1.3.0/dd-trace-api/src/main/java/datadog/trace/api/ConfigDefaults.java#L48) we can see that an actual default value is `true` but [the documentation says](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/) that it's `false`. It looks like it was changed in the code from `false` to `true` in [this commit](https://github.com/DataDog/dd-trace-java/commit/5e21cc217673ac6c84bc9f344bd37fef853d623c#diff-334fc9f6f4ddff0730a0861096a18ebc01c5a8 …
=> [Java Tracing Library] Update the default value for dd.http.server.tag.query-string

content/en/profiler/enabling/dotnet.md
The aim is to have the note about instrumenting machine wide be more visible and to include runtime version requirements in the feature table
---
=> Update Installation docs

content/en/tracing/trace_collection/library_config/java.md
the link was going to the wrong place, amazon ECS docs. flagged by hotjar
ready to merge!
---
=> DOCS-4517 fixing link in java tracing library docs

content/en/security/application_security/threats/add-user-info.md
This PR fixes a typo on the application security management user login examples.
---
=> Fix typo on PHP ASM user login examples

content/en/containers/guide/cluster_agent_autoscaling_metrics.md
Include some additional HPA examples using a more recent apiVersion.
Customer reached out on a ticket requesting this update.
Provided the new examples based off of the examples provided in the Kubernetes documentation:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-metrics-not-related-to-kubernetes-objects
---
=> Update HPA doc to include more HPA examples

content/en/observability_pipelines/installation.md
This updates the Observability Pipelines Worker installation steps for the new 1.1 release.
=> [OPB-582] Update installation documentation for OP Worker 1.1

content/en/dashboards/sharing.md
Update old links: public graph sharing (embeds).
The old links were fine and redirect to the new location, but this makes it faster
I read the docs and noticed they went to old links.
---
=> Update old links: public graph sharing (embeds)

content/en/profiler/enabling/php.md
Remove the note about the PHP Profiler not supporting INI settings, as this is not true anymore.
Having an up to date documentation 🚀 
---
=> Remove notes about INI-Settings as this is not true anymore

content/en/logs/log_configuration/online_archives.md
Removes region shortcode. Online Archives is available for all regions. Ready to merge.
[DOCS-4863](https://datadoghq.atlassian.net/browse/DOCS-4863), PM and SE request.
---
[DOCS-4863]: https://datadoghq.atlassian.net/browse/DOCS-4863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4863] Remove regions for Online Archives

content/en/integrations/guide/collect-sql-server-custom-metrics.md
This PR restores the guidance for collecting sql server metrics with `stored_procedure` but makes clear that it is a legacy mechanism. 
---
=> Re-add guidance for collecting sql server metrics with `stored_procedure`

content/en/logs/log_configuration/archives.md
- Adds info about webhook IPs
Read to merge
[DOCS-4887](https://datadoghq.atlassian.net/browse/DOCS-4887)
---
[DOCS-4887]: https://datadoghq.atlassian.net/browse/DOCS-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4887] Add webhook IPs info to Log Archives doc

content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
Use [BigInt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) to convert hex strings to 64bit unsigned int strings.
The amount of custom logic currently documented was quite large, perhaps BigInt() was not available at the time.
There is an example where this code is duplicated [here](https://github.com/DataDog/trace-examples/blob/98626d924f82666de60d6b2d6a65d87eebebdff1/opentelemetry/node-microservice/logger.js#L86)
The PR to change it is https://github.com/DataDog/trace-examples/pull/124
---
=> refactor connect logs and traces - Node.js

content/en/monitors/configuration/_index.md, content/en/monitors/manage/status.md
- Moved alert grouping to Notify your team section
- Add Further Reading section to Monitor Configure page
- Added blurb about new status group UI change to the Monitor Status page
[DOCS-4601](https://datadoghq.atlassian.net/browse/DOCS-4601)
- Plan to add UI images once the feature is available in the demo org
- Ready to merge after review
---
[DOCS-4601]: https://datadoghq.atlassian.net/browse/DOCS-4601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Separate alert grouping from monitor query grouping

content/en/security/cspm/detection_rules.md
Adds a note to clarify that rules with notifications enabled appear in the Signals Explorer. Ready to merge.
---
=> Add note about signals explorer

content/en/observability_pipelines/installation.md
Small change to add placeholders for the env vars required to start the Observability Pipelines Worker.
=> [OPW] Add placeholders for env vars required to start the OP Worker

content/en/agent/basic_agent_usage/_index.md
Our Microsoft partner requested a name change on our docs to refer to 'Windows Azure Stack HCI OS' as 'Azure Stack HCI OS'
---
=> Name Change for Azure Stack HCI

content/en/database_monitoring/guide/connect_dbm_and_apm.md
We updated the ruby version in the detailed instructions to version 1.8.0 but forgot to update the minimum required version in the _before you being_ section.
---
=> Update ruby tracer version requirement to 1.8.0

content/en/getting_started/integrations/_index.md
The hyphen is causing a placeholder bug in Transifex and isn't necessary anyway.
=> Fix transifex string bug

content/en/account_management/guide/hourly-usage-migration.md
This PR adds the new field session_count_flutter as part of the product taxonomy in the hourly-usage v2
Document the new field for v2 migration
n/a
---
=> [RQ3110] Add new field session_count_flutter as part of the v2 API

content/en/account_management/billing/serverless.md
Updating account management docs to remove specific reference to legacy invocation SKU, and include info on how to manage Functions that are monitored via our Lambda Extension or other direct instrumentation tools.
---
=> Update Serverless Account Management detail

content/en/monitors/configuration/_index.md, content/en/monitors/manage/status.md, content/en/monitors/types/metric.md
- Remove the alert grouping in the define the metric section under the table of steps
- Move Alert grouping below notifications
Ready to merge after Review
[DOCS-4909](https://datadoghq.atlassian.net/browse/DOCS-4909)
---
[DOCS-4909]: https://datadoghq.atlassian.net/browse/DOCS-4909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Edits to metric monitor config

content/en/logs/explorer/search_syntax.md
Bullets the information so it's clearer. Customer said docs doesn't mention having to use `?` for spaces in search syntax, but it is in the docs, just a little buried.
[DOCS-4657](https://datadoghq.atlassian.net/browse/DOCS-4657). Customer feedback.
---
[DOCS-4657]: https://datadoghq.atlassian.net/browse/DOCS-4657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4657] Separate out info so it's clearer

content/en/observability_pipelines/configurations.md, content/en/observability_pipelines/reference/sources.md
Makes `/observability_pipelines/reference/` go to `/observability_pipelines/configurations/` instead of sources
https://datadoghq.atlassian.net/browse/WEB-3227
visiting reference should go to the direct child subpage configurations
https://docs-staging.datadoghq.com/david.jone/redirect-reference/observability_pipelines/reference/
---
=> WEB-3227 - redirect reference to configurations

config/_default/menus/menus.en.yaml
Removes Aggregating Agents from the nav.
[DOCS-4919](https://datadoghq.atlassian.net/browse/DOCS-4919)
The associated doc, Integrate Datadog with OPW, was removed because it had incorrect info and links and is currently going through an overhaul. I'll add Aggregating Agents back once the new doc is ready.
---
[DOCS-4919]: https://datadoghq.atlassian.net/browse/DOCS-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4919] Remove Aggregating Agents from nav

content/en/containers/amazon_ecs/_index.md, content/fr/containers/amazon_ecs/_index.md, content/ja/containers/amazon_ecs/_index.md, content/kr/containers/amazon_ecs/_index.md
Add `file://` before `<path to datadog-agent-ecs.json>` in "aws ecs register-task-definition" command.
Before:
`aws ecs register-task-definition --cli-input-json <path to datadog-agent-ecs.json>`
After:
`aws ecs register-task-definition --cli-input-json file://<path to datadog-agent-ecs.json>`
A user who is unfamiliar with aws command may run the command incorrectly.
Without `file://` aws command will fail.
```
$ aws ecs register-task-definition --cli-input-json datadog-agent-ecs.json
Error parsing parameter 'cli-input-json': Invalid JSON received.
$ aws ecs register-task-definition --cli-input-json file://datadog-agent-ecs.json
{
"taskDefinition": {
"taskDefinitionArn": "arn:aws:ecs:ap-northeast-1:601427279990:task-definition/datadog-agent-task:24",
... snip ...
"registeredAt": …
```
=> Add supplemental explanation of cli-input-json arguments

content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
Clarify [SubscriptionFilter](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/SubscriptionFilters.html#LambdaFunctionExample) will not be created by [DatadogForwarder](https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole#automatically-set-up-triggers) CloudFormation. `SubscriptionFilter` needs for people using DatadogForwarder and CloudWatch Log Group. But, it is not created by this CloudFormation template.
Some users mistakenly believe that a SubscriptionFilter is created.
Cannot find the definition of [AWS::Logs::SubscriptionFilter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html) in https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitori …
=> Clarify `SubscriptionFilter` will not be created by DatadogForwarder CloudFormation

content/en/tracing/trace_collection/library_config/nodejs.md
Documents trace propagation style configs for W3C Trace Context support.
Header extraction priority has been made configurable and W3C Trace Context support has been added.
=> Add docs for Node.js W3C Trace Context header configs

content/en/monitors/guide/export-monitor-alerts-to-csv.md
Minor formatting to the app_key line, removing extra spaces to match the api_key line. The command was tested and did not work in its previous form, with these extra spaces. 
screenshot for reference: https://a.cl.ly/llu7jEYZ
This command was tested for a [support ticket](https://datadog.zendesk.com/agent/tickets/1107356) as the customer reported not having any results. Upon testing, it did not work until the command was run again with the extra spaces removed. 
---
=> Update Export Monitor Alerts to CSV

content/en/database_monitoring/setup_mysql/troubleshooting.md
This change updates our documentation to match updates GCP has made to their docs. [Previously](https://web.archive.org/web/20220125094341/https://cloud.google.com/sql/docs/mysql/flags#tips) 26gb RAM was required to enable the `performance_schema` flag on GCP Cloud SQL instances for MySQL. This requirement changed to 16gb RAM in [March 2022](https://web.archive.org/web/20220318025316/https://cloud.google.com/sql/docs/mysql/flags#tips).
=> Update GCP instance requirements for DBM

content/en/getting_started/integrations/_index.md
Apostrophe missing from the phrase "in that integrations `metadata.csv`" on line 175
---
=> Adding an apostrophe

content/en/data_security/logs.md
We have signed a new Business Associate Agreement that allows us to remove the restrictions on group-bys for Logs to Metrics
Changes to support this have been made in this [PR](https://github.com/DataDog/logs-backend/pull/46357)
Removes a restriction for HIPAA-enabled customers
Changes have been made to enable HIPAA-enabled customers to use any dimensions for group-by in Log-based Metrics. 
---
=> Update restrictions for HIPAA enabled customers

content/en/tracing/trace_collection/library_config/go.md
Adds documentation for `DD_TRACE_CLIENT_IP_ENABLED `environment variable for the Go Tracer
This flag should be documented for all tracers
---
=> Add documentation for DD_TRACE_CLIENT_IP_ENABLED

content/en/continuous_integration/tests/dotnet.md
Adds a new section to include the support of a new testing framework to CI Visibility.
We added support to a benchmark testing framework for .NET in CI Visibility.
https://docs-staging.datadoghq.com/tony/ci-visibility-tests-benchmarkdotnet/continuous_integration/tests/dotnet
---
=> [CI Visibility] - Add new section for BenchmarkDotnet support.

content/en/security/cspm/getting_started.md
Adds a note to the CSPM setup docs to clarify that you must enable metric collection for GCP. Ready to merge.
---
=> Add GCP metric collection note

.gitlab-ci.yml
- points gitlab to latest build image
- adds `create_artifact_cached` to live build process
`create_artifact_cached` is needed for the build caching we intend to test out in preview soon.
making the preview build more performant
no UI changes here
verifying changes:
- latest build ran the job without issues: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/234349582#L810
---
=> adds new build artifact upload

content/en/tracing/services/deployment_tracking.md
added mentions of automatic faulty deployment notification and linking watchdog documentation.
---
=> add section on faulty deployment notification

content/en/profiler/enabling/dotnet.md, content/en/profiler/profiler_troubleshooting.md
Update default logs directory path for the profiler since the 2.24
To simplify support cases, the profiler stores its log files at the same location as the tracer. 
---
=> .NET Profiler: update documentation

content/en/agent/faq/how-datadog-agent-determines-the-hostname.md
Add a note clarifying that it's not possible to search or filter using hostname aliases.
I'm in the process of setting up the Datadog agent for some EC2 instances, and I wasted some time because I was searching for a host by using one of its hostname aliases and couldn't find it. 
---
=> Add a note about hostname aliases to the FAQ

content/en/account_management/billing/usage_attribution.md
remove daily usage attribution section and replace with hourly usage attribution information
need to update usage attribution documentation
n/a
---
=> usage attribution update

content/en/getting_started/integrations/aws.md
current list of permissions is not complete - adding in missing ones which allow for the running of the CF template and rolling back on failure.
---
=> Update prerequisite permissions for CF

content/en/developers/dogstatsd/datagram_shell.md
Document an incoming change in the DogStatsD protocol introducing a new optional field to set timestamp on metrics.
Change has not been released yet, I'll keep this PR on-hold until the feature lands a release.
=> [dogstatsd] document dogstatsd protocol v1.3 with timestamp support.

content/en/agent/guide/build-container-agent.md, content/fr/agent/guide/build-container-agent.md, content/ja/agent/guide/build-container-agent.md, content/kr/agent/guide/build-container-agent.md
Fix errors in build-container-agent documentation
`datadog-agent/Dockerfile/agent/` -> `datadog-agent/Dockerfiles/agent/`
---
=> fix build-container-agent.md

content/en/serverless/custom_metrics/_index.md
The third param is the metric date, not the last one: https://github.com/DataDog/datadog-lambda-js/blob/38453fd6375cd70f7b8f26fae2134bb7a248ddfc/src/index.ts#L185
=> Fix `sendDistributionMetricWithDate` param order

content/en/data_security/agent.md
It replaces a reference to the configuration parameter `force_tls_12` by `min_tls_version`
`force_tls_12` is depreciated since 7.39 and will be remove (probably, [see here](https://github.com/DataDog/datadog-agent/pull/13867)) in 7.41. The new parameter that should be used is `min_tls_version`
https://docs-staging.datadoghq.com/nicolas.guerguadj/replace-reference-to-force-tls-12-by-min-tls-version/data_security/agent/
---
=> remove reference to deprecated `force_tls_12` configuration parameter and replace it by the new parameter `min_tls_version`

assets/scripts/components/table-of-contents.js
Anchor links often aren't scrolling to the appropriate position on Chrome browser on first page load. While a fix had been implemented previously, it doesn't seem to be consistent. 
https://datadoghq.atlassian.net/browse/WEB-3124
https://docs-staging.datadoghq.com/nsollecito/web-3124/tracing/trace_collection/compatibility/nodejs/#web-framework-compatibility
vs: 
https://docs.datadoghq.com/tracing/trace_collection/compatibility/nodejs/#web-framework-compatibility
Make sure functionality is working in all major browsers and mobile. Not 100% this is going to work because I'm seeing different behavior in the dev environment vs the live site and it's difficult to reproduce outside of the live environment. It does seem more susceptible on links to the site in a new session/window/tab
---
=> [WEB-3124] Flaky anchors on Chrome

content/en/continuous_integration/tests/containers.md
Updates the TeamCity env vars, adds missing custom env var for Jenkins and sorts the CI providers alphabetically.
---
=> Update docs for TeamCity and Jenkins in Docker

content/en/data_security/real_user_monitoring.md
=> Add link to Event Mapper APIs for React Native

content/en/serverless/configuration/_index.md
Syntax fix in the example for enabling source code integration. The code snippet and text display the wrong syntax for enabling source code integration using the cli.
Attempting to use the current documentation's examples produces the following error.
```sh
Unknown Syntax Error: Extraneous positional argument ("true").
```
I followed the incorrect docs and it caused this error. I don't want others to have to find out the same way.
We could also suggest using `-s` or not including true at all `--source-code-integration`. 
Mentioned in https://docs.datadoghq.com/serverless/libraries_integrations/cli/#arguments
---
=> Fixes serverless source code integration syntax error

.gitlab-ci.yml
Adds a new function to the CI to allow better metrics in the app to get insight into the average time
We want to keep more granular track of how long things are taking
Not really much to test on the site it's self
[Docs Preview Job](https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines/13808474)
[Metrics Dashboard](https://dd-corpsite.datadoghq.com/dashboard/4jg-n7c-9kt/pipeline-durations?from_ts=1677783347223&to_ts=1677786947223&live=true) - depending on when you check this, you may need to update the time. The Function times will be a bit messy since the old metric definitions are running on all other branches, but you should look for any function listed that ends with _preview
---
=> Update CI to report more granular metrics

content/en/network_monitoring/performance/guide/_index.md, content/en/network_monitoring/performance/guide/azure_supported_services.md, local/bin/py/build/actions/integrations.py, local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml, local/bin/py/build/update_pre_build.py
Adds a page describing NPMs support for automatic service tagging from domain for **Azure**. It was already supported/documented for GCP/AWS
https://datadoghq.atlassian.net/browse/NET-3053
---
=> [NET-3053] update docs to include npm domain discovery for azure

content/en/continuous_integration/guides/pull_request_comments.md
Removes pull_request trigger limitation for test summaries
We now added support for pull_request triggers
---
=> [CIAPP-5990] Removing pull_request trigger limitation for test summaries

content/en/data_security/logs.md
The restriction is now removed.
---
=> Remove group by clause on log monitors for hipaa

content/en/infrastructure/list.md
Updates docs for current UI labels for the "Status" field in the Infrastructure List
Let's call it a "personality quirk", and noticed it while reading some docs
=> minor docs correction to infra list

assets/styles/pages/_global.scss
Styles shell code blocks with dollar signs at the beginning of each line to indicate they are commands to be run, without affecting the copy button.
https://datadoghq.atlassian.net/browse/WEB-3254
https://docs-staging.datadoghq.com/fitzage/code-styling/developers/integrations/api_integration/
1. Using `lang=“bash”` allows for shell syntax highlighting, but disables the dollar signs. This could be useful for blocks of code that also include shell command output.
2. I will write up documentation for this to make that capability clear.
---
=> added $ to beginning of shell language code blocks

content/en/security/application_security/threats/add-user-info.md
* Be more consistent for signup event accross language
* Remove the block ip call in python as it's already done in set_user
Will help our customer to setup correctly the SDK
---
=> (ASM) Improve asm SDK usage

content/en/continuous_integration/intelligent_test_runner/_index.md, content/en/continuous_integration/tests/javascript.md
* Remove `DD_CIVISIBILITY_GIT_UPLOAD_ENABLED` as a necessary parameter to intelligent test runner initialization.
* Add informative `Git metadata upload` section and explain how users can opt out of it.
* Now that git upload is an opt out in CI Visibility, we need to update the necessary configuration for intelligent test runner.
* We also want to be clear to users that we're uploading git information.
* [Changes to configuration parameters](https://docs-staging.datadoghq.com/juan-fernandez/change-git-upload-info/continuous_integration/intelligent_test_runner/?tab=dotnettest#javascript)
* [Git upload section](https://docs-staging.datadoghq.com/juan-fernandez/change-git-upload-info/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#git-metadata-upload)
---
=> [ci-visibility] Add note about git upload

content/en/tracing/trace_collection/compatibility/dotnet-core.md, content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Bump HotChocolate integration version support from min to max support version.
DOCS-5005; request from Support
---
=> DOCS-5005 .NET Framework and .NET Core Compatibility Edit

content/en/infrastructure/livecontainers/configuration.md
Add Vertical Pod Autoscalers to the configuration docs
Update our docs to include vertical pod autoscalers
---
=> Add Vertical Pod Autoscalers to docs

content/en/getting_started/tagging/assigning_tags.md
A tagging example in a YAML file is formatted like a shell command. I added the array element `-` prefix because env vars are always in arrays in yaml files.
---
=> Format example as YAML

content/en/dashboards/scheduled_reports.md
This PR fixes a broken link in the **Dashboards | Scheduled Reports** docs.
The link is broken! https://docs.datadoghq.com/dashboards/scheduled_reports/#permissions
---
=> fix broken link in scheduled reports docs

content/en/agent/guide/auto_conf.md
Adds RabbitMQ to the table of Autodiscovery integrations.
Chat with Alex on Slack; ready to merge
---
=> Autodiscovery Auto-Configuration Edit

content/en/account_management/billing/usage_monitor_apm.md, content/en/tracing/guide/add_span_md_and_graph_it.md, content/en/tracing/guide/apm_dashboard.md, content/en/tracing/guide/instrument_custom_method.md
Updates links from the deprecated Analytics view to the Trace Explorer page.
DOCS-4348
[If you give a mouse a cookie...](https://www.youtube.com/watch?v=QCDPkGjMBro) 🍪
---
=> DOCS-4348 Cleanup Legacy Analytics Link

config/_default/menus/menus.en.yaml, content/en/security/application_security/terms.md, content/en/security/application_security/threats/_index.md, content/en/security/application_security/threats/inapp_waf_rules.md
rebranding event rules to In-App WAF rules
---
=> Rebrand event rules to In-App WAF rules

layouts/partials/apm/apm-manual-instrumentation.html
Changes the current logo for .NET used in the Custom Instrumentation main page.
https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/#pagetitle
This way it simply says .NET instead of .NET Framework or .NET Core since the steps for both live in the same page.
---
=> Changed image to be dotnet_text.png

content/en/tracing/trace_collection/library_injection.md
Describes how to enable ASM and Profiler using library injection config
Suggestion from evangelism team
---
=> DOCS-4908 APM Library injection: add info about enabling ASM or Profiler

layouts/shortcodes/latest-lambda-layer-version.html
Revert recommended Datadog extension to 38, after a regression was discovered
---
=> fix: revert extension version to 38

content/en/tracing/troubleshooting/agent_apm_metrics.md
`datadog.trace_agent.ratelimit` is actually `datadog.trace_agent.receiver.ratelimit`
see https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/api/api.go#L676
Having a correct doc
---
=> Fix trace agent metric name (ratelimit)

.gitlab-ci.yml, config/_default/config.yaml, config/_default/languages.yaml, content/en/containers/cluster_agent/_index.md, content/en/developers/guide/unified-tagging-advanced-usage.md, content/en/getting_started/agent/_index.md, content/en/getting_started/integrations/_index.md, content/en/getting_started/tagging/assigning_tags.md, content/en/getting_started/tagging/unified_service_tagging.md, content/en/integrations/guide/jmx_integrations.md, content/en/logs/explorer/export.md, content/en/logs/explorer/search.md, content/en/logs/explorer/visualize.md, content/en/monitors/guide/monitor-arithmetic-and-sparse-metrics.md, content/en/profiler/compare_profiles.md, content/en/synthetics/apm/_index.md, layouts/_default/list.redirects.txt, local/bin/py/build/actions/integrations.py, local/bin/py/build/actions/security_rules.py, local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
- Adds redirect logic to documentation
- Removes redundant redirects
- Adds logic for integrations to remove redundant redirects that may exist 
- Removes logic that was creating approx 1500 redirects for OOTB security rules that were not in used (verified via logs that the redirects have not been hit)
I'm open to input, but would like to just roll the CI job out on previews for the time being to ensure we are not missing anything before we push this to live (maybe Monday?)
In an effort to get the correct status code of `301` for redirects from aliases. Hugo handles it with data in a temporary page that redirects to the alias, but gives a status code of `200`
https://docs-staging.datadoghq.com/devin.ford/WEB-3203/
Check different areas of the site and ensure redirects are behaving as we …
=> WEB-3203 | Add redirect metadata job to Docs

Makefile, layouts/shortcodes/integration_categories.md, local/bin/py/build/actions/integrations.py, local/bin/py/build/configurations/pull_config_preview.yaml
This PR:
- Uses the classifiers in the assetlib as a reference to only allow valid categorization of integrations
- Write to the `layouts/shortcodes/integration_categories.md` file with the classifiers so that they can be used by the `https://docs.datadoghq.com/developers/integrations/check_references/` page
https://datadoghq.atlassian.net/browse/WEB-3284
- Test https://docs-staging.datadoghq.com/david.jones/validate-categories/integrations/ loads the same integrations.
- Test local build still works despite installing lib that isn't always available
---
=> WEB-3284 - remove invalid integration categorization

content/en/monitors/notify/downtimes.md
Fixed a small typo in explaining the new behavior which was added in this PR: https://github.com/DataDog/documentation/pull/17247
---
=> Fix typo in end of downtime behavior

content/en/metrics/open_telemetry/otlp_metric_types.md, content/en/opentelemetry/guide/_index.md, content/en/opentelemetry/guide/otlp_delta_temporality.md
Adds guidelines on how to export OTLP metrics using delta aggregation temporality.
As described on the Overview section, the choice of aggregation temporality has implications on the statefulness of the Collector/Agent deployments.
---
=> [content/en/opentelemetry] Guide on how to use delta temporality

content/en/tracing/trace_collection/library_injection.md, layouts/shortcodes/tracer-version.html
Docs were written a while back and were referencing a version of the tracing client that was released Oct 2022. I've updated to the latest version of the java tracer. This however is only a short term measure. The prospect should always be using the latest/greatest of the tracing clients for better support/performance etc. 
I also added - INSERT LINK TO VARIOUS REPOS FOR TRACING CLIENT. It would be good to have a clear link to the dd-trace-java or the other repos so the customer can go look at the versions they may be most interested in.
---
=> Updated tracer version to 1.10.0

content/en/monitors/notify/variables.md
Update Monitor Template Variable Description
- There is currently no description of which monitors can reference the `{{ok_threshold}}` template variable.
- Added a description to the monitor template variable `{{ok_threshold}}` that this template variable can only be used for ServiceCheck monitors.
Customer reached out to us why `{{ok_threshold}}` is not working for metric alerts.
- https://datadog.zendesk.com/agent/tickets/1106640 
Escalation:
- https://datadoghq.atlassian.net/browse/MNTS-89602
Waiting review from the monitor team to merge.
=> Updated montior template variable description

content/en/agent/_index.md, content/en/getting_started/observability_pipelines/_index.md, content/en/observability_pipelines/_index.md, content/en/observability_pipelines/configurations.md, content/en/observability_pipelines/installation.md, content/en/observability_pipelines/working_with_data.md
- Adds previous aliases in Integrate Observability Pipelines Worker and Datadog to the new Getting Started with Obs Pipelines.
- Add links to Getting Started with Obs Pipelines in further reading sections.
[Docs-4903](https://datadoghq.atlassian.net/browse/DOCS-4903)
---
=> [DOCS-4903] Add aliases and links to Getting Started with Obs Pipelines  

content/en/database_monitoring/guide/connect_dbm_and_apm.md
This fixes the python trace instructions that were referring to an earlier iteration that was never used/committed when the python tracer implementation was in development. 
The correct env variable is `DD_DBM_PROPAGATION_MODE`.
---
=> Fix wrong env variable to enable dbm propagation in python instructions

assets/styles/pages/_api.scss
When using table syntax in markdown on api generated pages we use the regular docs style tables however it looks out of place on the api where all the generated tables are using a purple color scheme.
https://datadoghq.atlassian.net/browse/WEB-3342
There isn't currently any usage of this to show on the preview site but it ends up looking like this (from my testing)
https://docs-staging.datadoghq.com/david.jones/md-table-style/
---
=> WEB-3342 - update api md table style to be similar to generated tables

content/en/database_monitoring/guide/connect_dbm_and_apm.md
[dd-trace-py v1.9.0](https://ddtrace.readthedocs.io/en/stable/release_notes.html#v1-9-0) introduced support for appending dbm comments to queries with the type byte. Previously we would only append DBM comments to unicode strings. Although this is an edge case that should not impact most customers it's worth calling out.
---
=> apm_dbm: bump minimum supported version of the python tracer

layouts/partials/footer/footer.html
vertically  align google play and apple store footer icons on large screens
https://datadoghq.atlassian.net/browse/WEB-3231?focusedCommentId=994816
https://docs-staging.datadoghq.com/stefon.simmons/vertically-align-footer-icons/
---
=> vertically align footer download icons

content/en/getting_started/containers/datadog_operator.md
Changing the Configuration link under Further Reading to reference `v1alpha1` one as we are referencing that in the Getting started guide and `v2alpha1` is reserved for GA which is not yet GA'd.
---
=> Updating_getting_started_guide_operator

content/en/serverless/azure_app_services.md
Removes the statement "and out-of-process (isolated) functions are not supported"
We will soon support isolated functions in https://github.com/DataDog/dd-trace-dotnet/pull/3900
=> [Tracing][.NET] Remove isolated Azure Functions from unsupported

content/en/continuous_integration/tests/containers.md
Document the env vars from Codefresh that are used for CI Visibility.
---
=> CI Visibility: Add Codefresh env vars

content/ja/tracing/trace_collection/dd_libraries/java.md
Change DD_TRACE_SAMPLING_SERVICE_RULES to DD_TRACE_SAMPLING_RULES in the Japanese documentation.
Same as https://github.com/DataDog/documentation/pull/16820
---
=> Change config option name to DD_TRACE_SAMPLING_RULES

.gitlab-ci.yml
Add the redirect meta job to the live site in CI
Now that we have been running the redirect meta job in preview for a few days, and haven't seen odd behavior on redirects, we want to roll it out to the live site. 
For context:
This job runs post deploy, hugo will use the current alias pages while this job is still working to make sure redirects are always live on site. As the job works, it replaces the redirects in the bucket with metadata that will redirect as the link is hit and serve the proper `301` code. This job has built in logic to not allow redirects to the same page (causing redirect loops, hugo bypasses these for alias pages to avoid the same) and will inform the user at the end of the job what aliases should be removed since they are redundant. If you have any questions or …
=> WEB-3346 | Add redirect CI job for live

content/en/agent/guide/podman-support-with-docker-integration.md
@kennonkwok 
Removed note about Podman not being able to collect logs:
"Container logs aggregation is not supported"
Removes note about Podman not being able to collect logs.
Tested a Podman deployment with log collection. Showed that logs were being collected. 
---
=> Remove Podman Log Note

Makefile, local/bin/py/integration-finder.py, local/etc/requirements3.txt
Integration finder:
- looks for local copies of all integrations repos and either updates them or clones them
- searches for a given integration (use the integration spelling from the docs url)
I have some TODOs listed. I'm planning on eventually building a little docs CLI tool in a different repo. For now, I'd like to get this merged in though, cos I don't know when I'll get to the CLI stuff (maybe next hackathon).
To test:
```shell
make find-int int=<integration_name>
```
For example:
```shell
make find-int int=btrfs
Updating dogweb: prod
Updating integrations-core: master
Updating integrations-extras: master
Updating integrations-internal-core: main
Updating marketplace: master
More than one integration with that name was found. Check the following: …
```
=> (hackathon) integration finder

content/en/logs/log_collection/python.md
- Updates doc to fix docs style (title case, etc)
- Removes examples because it's take directly from the third-party doc and the example is not up to date
- Add info about django paramenter, related to [DOCS-4920](https://datadoghq.atlassian.net/browse/DOCS-4920)
- Move "Connect traces and logs" to after "Configure the Datadog Agent"
[DOCS-2844](https://datadoghq.atlassian.net/browse/DOCS-2844)
---
[DOCS-4920]: https://datadoghq.atlassian.net/browse/DOCS-4920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-2844]: https://datadoghq.atlassian.net/browse/DOCS-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-2844] Update Python log collection 

content/en/database_monitoring/guide/connect_dbm_and_apm.md, content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md
1. Adds setup instructions to the DBM <-> APM link guide for compatibility with .NET
2. Adds the DBM configuration setting `DD_DBM_PROPAGATION_MODE` to the .NET tracing configuration pages
.NET has recently implemented the ability to link spans to DBM.
DBM guide page: https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-configuration-dbm/database_monitoring/guide/connect_dbm_and_apm/?tab=net#setup
.NET Framework APM configuration page: https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-configuration-dbm/tracing/trace_collection/library_config/dotnet-framework/?tab=environmentvariables#automatic-instrumentation-optional-configuration
.NET Core APM configuration page: https://docs-staging.datadoghq.com/zach.montoya/apm-dotnet-configuration-dbm/tracing/trace_collection/library_c …
=> APM > .NET > Add initial DBM configuration key to APM configuration page.

content/en/continuous_integration/tests/javascript.md
Warn about usage of `cypress open`
Do not confuse customers that are trying cypress interactive mode with CI Visibility.
https://docs-staging.datadoghq.com/juan-fernandez/update-cypress-instructions/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#known-limitations
---
=> [ci-visibility] Update cypress instructions to warn about `cypress open`

layouts/shortcodes/site-region.html, local/bin/py/build/actions/integrations.py, local/bin/py/build/configurations/pull_config_preview.yaml
Revert integrations page `site-region` shortcode updates as they were causing issues with the link formatting script.
https://dd.slack.com/archives/C3CT8QA11/p1678986335840829
links are correct: https://docs-staging.datadoghq.com/brian.deutsch/integrations-site-region-format/integrations/azure
check some other pages for sanity: links/site region shortcode should still work
https://docs-staging.datadoghq.com/brian.deutsch/integrations-site-region-format/integrations/vmware_tanzu_application_service/
https://docs-staging.datadoghq.com/brian.deutsch/integrations-site-region-format/integrations/syslog_ng
---
=> revert integrations site region changes

content/en/dashboards/widgets/log_stream.md
Change the link for measure to point to subheading.
Widget audit, noticed both facet and measure point to the same link, which seemed redundant.
---
=> Small link change

content/en/account_management/teams.md
Support reported that a customer was confused because the Teams feature is documented, but does not appear in their org.
The Teams launch was delayed by the recent Datadog outage and subsequent freeze. Adding a beta notice to the docs to inform customers that the product has not yet launched. I used a regular info box instead of the special callout because we don't want people to contact Support or attempt to sign up.
I'll remove the beta notice once Teams becomes generally available. 
---
=> Add beta alert box to Teams page because the launch was delayed

content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
Customer in this ticket (https://datadog.zendesk.com/agent/tickets/1129215) pointed out that the link in the docs is missing a `-` before the <TRACER_VERSION>
https://a.cl.ly/wbuDWnAr
Add a dash before <TRACER_VERSION> for musl download link
Customer in this ticket (https://datadog.zendesk.com/agent/tickets/1129215) pointed out that the link in the docs was incorrect. https://a.cl.ly/wbuDWnAr
---
=> Correcting syntax for musl download link

.github/styles/Datadog/links.yml
The "Documentation" rule was popping up for instances of "See the [Company] documentation" or "the Service Level Objectives documentation", when both instances of using the word "documentation" in the link were appropriate.
Docs Style Council
---
=> Snooze Vale Linter Rule About Documentation Links

content/en/opentelemetry/otlp_ingest_in_the_agent.md, content/en/security/application_security/enabling/dotnet.md, content/en/security/application_security/enabling/go.md, content/en/security/application_security/enabling/java.md, content/en/security/application_security/enabling/nodejs.md, content/en/security/application_security/enabling/python.md, content/en/security/application_security/enabling/ruby.md, content/en/security/application_security/how-appsec-works.md, content/en/tracing/trace_collection/library_injection.md
Standardizes "Datadog library" to have a capital D, lowercase l.
When I corrected the capitalization on an unrelated pull request, the author mentioned that "Datadog Library" exists in several other places in the codebase.
Sorry about all the link renumbering! I glanced at them and thought they looked okay. Some of the pages do have tabs. I can back them out if you prefer.
---
=> Standardize the capitalization of Datadog library

config/_default/menus/menus.en.yaml
- Remove the individual widgets from the menu (these aren't visible from the left nav currently)
- Renumber the Dashboard child menu items starting from 1 instead of 4
- [DOCS-5054](https://datadoghq.atlassian.net/browse/DOCS-5054)
- Ready for release after review
---
[DOCS-5054]: https://datadoghq.atlassian.net/browse/DOCS-5054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cleanup the left nav menu for Dashboards

content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md
Updates the .NET tracing documentation about the default injected distributed headers..-->
In v2.22.0, we changed which header styles we injected by default
Related to https://github.com/DataDog/dd-trace-dotnet/issues/3832
---
=> [Tracing] [.NET] Update default injection style

content/en/continuous_integration/tests/javascript.md
Add note about compatibility with mocha's parallel mode.
Make it explicit that we are not compatible.
https://docs-staging.datadoghq.com/juan-fernandez/add-note-about-mocha-parallel-mode/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#mocha-parallel-tests
---
=> [ci-visibility] Add note about compatibility with `mocha` parallel mode

.github/CODEOWNERS
Add @Datadog/rum-browser as owner of browser related files
Be notified when those files are updated to have a chance to review the edits
---
=> Add codeowners on articles related to browser

.gitlab-ci.yml
Adds `allow_faulure: true` to `set_redirect_metadata_preview`
https://datadoghq.atlassian.net/browse/WEB-3368
This job is not (technically) required to consider a build pipeline successful, since we rely on the aliases as a backup to redirect metadata, and any redirect loops from redundant aliases are bypassed and not uploaded to S3 and just outputted to the console. With that in mind if the job did fail, it would not block a deployment, and the redundant alias could be cleaned up in a follow up PR.
---
=> WEB-3368 | Allow redirect preview job to fail

content/en/database_monitoring/setup_sql_server/azure.md, content/en/database_monitoring/setup_sql_server/gcsql.md, layouts/shortcodes/dbm-sqlserver-agent-setup-windows.md
Update adoprovider parameter to use MSOLEDBSQL19 instead of MSOLEDBSQL.
Microsoft OLE DB Driver for SQL Server 19 is now the default download on the linked [Microsoft ODBC Driver](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server) page, meaning that without this change Datadog's SQL Server integration will always fail with an error "Provider cannot be found. It may not be properly installed". This follows the same changes made to spec.yaml and conf.yaml.example in https://github.com/DataDog/integrations-core/pull/12916
---
=> Update SQL Server adoprovider to use MSOLEDBSQL19 instead

content/en/developers/community/libraries.md
This integration is no longer working with current agent versions as per ticket: https://datadog.zendesk.com/agent/tickets/1082256 
Last update was about 4 years ago: https://github.com/bithauschile/datadog-ga 
Because of these two points, we shouldn't advertise this community integration anymore
Remove bithaus google analytics integration from our list as it is no longer working
Ticket 1082256
---
=> [DOCS-5027] Remove bithuas google analytics integration

content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
After discussing this with Ryan internally, it's better to remove the S3 bucket mention in the doc as it can be misleading for customers. 
We had one customer asking clarification about this: he was not sure he could use the kinesis firehose to forward his S3 bucket objects to datadog. Only CW is supported. 
(https://a.cl.ly/llu72vKp)
This should be reviewed by Bryce Eadie as asked by Ryan 
---
=> Remove the S3 bucket mention as it's misleading

content/en/account_management/billing/_index.md
Adds Heroku dyno as a unit for hosts counting for billing
A lot of people coming to Heroku is confused on how we count hosts when it comes to Heroku. This PR makes it clear in the Billing page.
https://docs-staging.datadoghq.com/arapulido/heroku-dynos-billing-docs/account_management/billing/
---
=> Add Heroku dyno to the hosts section

content/en/monitors/service_level_objectives/metric.md, content/en/notebooks/_index.md
- Add SLO Summary link to the list of Notebook vizualizations
- Remove section on SLO metric indicators 
- Both changes requested by PM
[DOCS-4704](https://datadoghq.atlassian.net/browse/DOCS-4704)
- part of a larger update request
[DOCS-4704]: https://datadoghq.atlassian.net/browse/DOCS-4704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLO quick fix updates

content/en/dashboards/_index.md
- Add a quick start section with links to docs pages customers frequently look for, similar to the [Metrics page](https://docs.datadoghq.com/metrics/#what-are-metrics)
[DOCS-5102](https://datadoghq.atlassian.net/browse/DOCS-5102)
Ready for release after review
[DOCS-5102]: https://datadoghq.atlassian.net/browse/DOCS-5102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a partial for links in dashboard overview

Makefile, layouts/shortcodes/integration_categories.md, local/bin/py/build/actions/integrations.py
Use `get_non_deprecated_classifier_names` data instead when writing to shortcode
Currently we are outputting all our classifiers in the shortcode however some of these exist temporarily while we transition off them. We don't want them to appear in the docs and perpetuate its usage so switching to this different dataset should only include the items we want to publically display.
Nothing to preview as this shortcode isn't used yet. 
Prerequisite to merging:
- [This PR is merged ](https://github.com/DataDog/dd-source/pull/28235)
- The assetlib version used in this pr is bumped to the version including above changes
---
=> use public definition classifiers

content/en/integrations/kubernetes_state_core.md
Resolves the merge conflict in https://github.com/DataDog/integrations-core/pull/14154.
DOCS-4924
This is a hardcoded integration in the `documentation` repo.
---
=> DOCS-4924 Add Supported OS for the Kubernetes State Metrics Core Integration Documentation

content/en/logs/explorer/facets.md
Update the page so that US3, US5, and Gov specific info is the same as US and EU. There is no need to distinguish between the sites.
Archives and Rehydration is available for all sites.
---
=> Remove specific site info for log facets

content/en/tracing/trace_collection/library_injection.md
Clarifies that we need to look at the container image tag when referencing the image the init container pulls from.
Pulling the "tracer version" when trying to pull images isn't correct because the container image tags start with `v`. This PR aims to clarify that the value of the tracing library version used depends on the container image tags available.
https://docs-staging.datadoghq.com/wantsui/lib-injection-container-image/tracing/trace_collection/library_injection
This should be reviewed by the APM team.
---
=> [DRAFT] Library Injection Setup: Update how to reference the container image

content/en/logs/explorer/search.md, content/en/logs/explorer/search_syntax.md, content/en/logs/explorer/visualize.md
- Remove site regions from log docs because the information should be the same for all regions.
[DOCS-5126](https://datadoghq.atlassian.net/browse/DOCS-5126)
---
[DOCS-5126]: https://datadoghq.atlassian.net/browse/DOCS-5126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-5126] Remove site regions from logs docs

content/en/logs/log_configuration/processors.md
This PR makes a minor correction on Logs Message remapper documentation: it removes the `long` `target_format` as this is not supported anymore.
The error in the documentation has been reported internally.
---
=> Logs Message remapper correction (long is not a valid target_format).

content/en/serverless/_index.md
- Add a reference link to the AWS Lambda Custom metrics page from the main Serverless page.
https://datadoghq.atlassian.net/jira/software/projects/DOCS/boards/199?selectedIssue=DOCS-5115
=> Add a link to the Custom metrics page from the Serverless main page

content/en/profiler/profiler_troubleshooting.md
This PR documents, in the "Profiler Troubleshooting" page, what to do if customers run into issues due to the new Ruby profiler using `SIGPROF` signals for working.
We currently don't know of any cases where this may be needed (other than `mysql2`, which is already autodetected and worked around in the library), so I've also added a note asking for customers to report any such cases.
From dd-trace-rb 1.11.0+, the new profiler will be the default so it's important to document this caveat and its workaround, in the rare case that customers run into it.
N/A
---
=> [PROF-7359] Document workaround for Ruby profiler signal usage

content/en/account_management/org_settings/sensitive_data_detection.md
Hi ! We released a new SDS UI on Monday, and we need to align the pictures in the public doc. This PR is dependent on this one: https://github.com/DataDog/documentation/pull/17450, which adds the images to the repo.
---
=> Update pictures on SDS public documentation

content/en/database_monitoring/guide/connect_dbm_and_apm.md
Add documentation for enabling the DBM-APM linking feature for applications that use the java tracer. Related to this PR https://github.com/DataDog/dd-trace-java/pull/4847, which implements the feature && was just released. 
---
=> [APM-DBM] Add documentation for the java tracer

.gitlab-ci.yml
Updates docs to the latest image to allow for the cache header to be set when the redirect metadata job runs
Users browser cache holding onto bad redirects 
successful pipeline run: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/245905666
---
=> Update to latest image

layouts/_default/404-baseof.html
Fixed announcement banner overlap on nav for 404 page
https://datadoghq.atlassian.net/browse/WEB-3403
https://docs-staging.datadoghq.com/renzo.renteria/404-banner-overlap/404.html
---
=> fixed banner overlap on 404

content/en/containers/kubernetes/distributions.md
Add back in the steps to use Kubelet TLS Verification. This wasn't possible for awhile due to the format of the certificates. However, was fixed by AKS in late October. Adding as (ideally) customer's have been able to upgrade their Node Pools by now. 
Tried to adjust it to add more context so it's less multiple bullets of, "if this then do this". 
Provide steps for TLS Verification now that it's possible again. As well as provide a little more context.
Preview: TBD
Current: https://docs.datadoghq.com/containers/kubernetes/distributions/?tab=helm#AKS
---
=> Update AKS Connection Setup for TLS Verification

content/en/containers/guide/cluster_agent_autoscaling_metrics.md
Make some decent sized changes to our HPA doc. Most notably to reframe the order and sections to recommend using the `DatadogMetric` Custom Resource Definition (CRD) instead of using the native format. So the order was changed to put the setup with `DatadogMetric` first. 
The headers were changed corresponding to this too. As the headers are:
- Setup (for Cluster Agent)
- Usage (HPA without DatadogMetric)
- Autoscaling (HPA with DatadogMetric)
Which isn't that clear, "usage" vs "autoscaling". As you are using the autoscaling functionality either way, it's just a matter of which option you are using. Modified to:
- Setup
- Autoscaling with DatadogMetric queries
- Autoscaling without DatadogMetric queries
Clear up autoscaling options and push more towards usage of the `DatadogMetric` …
=> HPA Cleanup and DatadogMetric recommendation

content/en/real_user_monitoring/browser/_index.md
Changed URLs on the RUM browser index page to relative instead of absolute.
This page was recently moved from a single-sourced repo to the documentation repo, and I realized I had forgotten to do this.
---
=> Changed URLs to relative instead of absolute

content/en/security/application_security/threats/add-user-info.md
Clarify the wording on the PHP user blocking section of application security management.
---
=> Clarify user blocking in PHP

content/en/real_user_monitoring/browser/modifying_data_and_context.md
- Removes alerts about deprecations because they are 7+ months old
- Removes links that refer to the logs naming convention because they are confusing
- Adds back some API examples that were removed
- Updates some other examples that were missing
Internal feedback (see [DOCS-5055](https://datadoghq.atlassian.net/browse/DOCS-5055)).
---
[DOCS-5055]: https://datadoghq.atlassian.net/browse/DOCS-5055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove deprecation alerts and naming convention refs

assets/styles/_icons.scss, assets/styles/components/_language-region-select.scss
fixes the number styling on the region selector button (US1, US3 US5).
Issue seems to be contained to Chrome browsers in a recent Chrome update.
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3371
https://docs-staging.datadoghq.com/stefon.simmons/fix-font-variant-numeric/getting_started/agent/
---
=> fix font variant numeric -[WEB-3371]

.gitlab-ci.yml
- Updates the CI to point at the latest image
- Updates the TM test on previews to only run against changed html files (speed it up a ton)
- Update the redirect job to run in isolation (due to an image change)
Attempting to speed up post-deploy CI jobs for previews
Successful pipeline run: https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines/14529457
---
=> Update CI to point at latest image

config/_default/menus/menus.en.yaml
Add Aggregating Agents back to nav and link to the new Getting Started with Observability Pipelines
Task as part of [DOCS-4939](https://datadoghq.atlassian.net/browse/DOCS-4939)
---
[DOCS-4939]: https://datadoghq.atlassian.net/browse/DOCS-4939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4939] Add Aggregating Agents back to nav

content/en/integrations/guide/powershell-command-to-install-azure-datadog-extension.md
This PR fixes the type handler for the Azure Extension. Version `6.4` doesn't exists and the last major release was version `5`.
---
=> Set type handler to 5.0 for Windows Azure Extension

content/en/continuous_integration/pipelines/github.md
Adds queue time support for GitHub docs
---
=> [CIAPP-6189] Add queue time support for GitHub

content/en/real_user_monitoring/heatmaps/_index.md
When using heatmap, the SDK needs to be configured with the ability to track user action, otherwise, no heatmap will be generated.
We received cases from customer asking why the heatmap were not generated and their configuration did not contain trackUserInteractions: true
https://github.com/amedeobussi/documentation/blob/RUMS-1457/content/en/real_user_monitoring/heatmaps/_index.md
---
=> Enabled action tracking for Heatmap by setting trackUserInteractions: true

content/en/logs/guide/access-your-log-data-programmatically.md
The "from" value needs to be further in the past than the "to" value. Running the API call with the values as shown in the doc currently results in an error.
---
=> Fix issue with request example

content/en/tracing/other_telemetry/connect_logs_and_traces/php.md
Add an updated code snippet on how to connect logs and traces together when using monolog v3. 
In this version, the manual injection should make use of the [`extra`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/LogRecord.php#L24) field accessible from the `LogRecord` class.
---
=> Add documentation about connecting logs and traces

content/en/monitors/guide/as-count-in-monitor-evaluations.md
Consolidating "does not make sense" and "cannot be used" into one line, and removing reference to "in total" notation, which is no longer accurate
Cleaning up the section on using non-sum aggregation with as_count(), and making it more accurate by removing outdated reference to "in total" notation, which has been removed from the UI.
Just happened to look at this doc and it was repetitive and inaccurate.
---
=> as_count/aggregation cleanup

content/en/monitors/configuration/_index.md
Clarifying that "Evaluate as zero" does not work with default_zero. Including quotes for formatting.
---
=> david.grashton/evaluate as zero incompatible with default zero

assets/scripts/components/codetabs.js
default to first tab if tab param doesnt exist
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3378
set `tab` param in url to equal the name of a tab that doesn't exist on the page.
page should reset the `tab` param to equal the first tab of the `tabs` section.
https://docs-staging.datadoghq.com/stefon.simmons/default-tab/tracing/trace_collection/dd_libraries/nodejs/?tab=foo
---
=> default tab - [WEB-3378]

content/en/tracing/trace_collection/library_injection.md
Update the lib injection docs about uWSGI.
The Python injection mechanism does not currently support uWSGI so we should call it out to avoid confusion.
---
=> Update lib injection with lack of uWSGI support

content/en/metrics/open_telemetry/otlp_metric_types.md
Updates documented mapping for OTLP Histograms.
In DataDog/opentelemetry-mapping-go/pull/23 we 
- Updated the mapping to support sending `.min` and `.max` metrics on delta OTLP Histograms that have these fields set.
- Renamed `send_count_sum_metrics` to `send_aggregation_metrics`.
---
=> [OTLP] Update mapping for OTLP Histograms

content/en/profiler/profiler_troubleshooting.md
This PR extends the troubleshooting steps added in #17370 with a new known incompatiblity with the `rugged` gem.
(Originally reported in
https://github.com/DataDog/dd-trace-rb/issues/2721 )
Document the known incompatibility.
---
=> [PROF-7409] Document Ruby profiler incompatibility with rugged gem

content/en/account_management/saml/google.md
- Format the service provider details into a description list for easier reading
- Update the instructions for the entity ID to be site-aware
- Update the wording and formatting in the service provider details to meet documentation standards.
https://datadoghq.atlassian.net/browse/DOCS-5111
Report from a solutions engineer that the entity ID in the Google SAML instructions is wrong for sites other than US1.
---
=> DOCS-5111 Update Google SAML IdP page

content/en/universal_service_monitoring/_index.md
Fixes docker-compose installation for USM
The documentation was wrong as the syntax for environment variable was invalid. Furthermore, we had duplicated mount which causes a failure. Eventually removing HOST_PROC as it is a default setting when running a container.
---
=> usm: Fixed docker compose

content/en/logs/log_configuration/indexes.md
Add a link to the organisation setting where user can enable the option to use retention outside of their contract
Users look mostly in the index page to learn about the index and how to set the retention and there was no link toward this option
---
=> add link to index retention organisation setting

content/en/account_management/guide/hourly-usage-migration.md
This PR adds to the logs family of product taxonomy the logs_forwarding_events_bytes usage type.
New product to be displayed as usage for our customers: https://datadoghq.atlassian.net/browse/RQ-3362
---
=> Add to product taxonomy the logs_forwarding to logs family

content/en/containers/cluster_agent/commands.md
Adding the proxy variables to the documentation since you may get proxy type errors in the DCA, and adding these variables would address the issue.  These proxy variables were added in the DCA last 2019 but not added to the documentation.
https://github.com/DataDog/datadog-agent/pull/4191
---
=> Add proxy variables in DCA

content/en/database_monitoring/setup_sql_server/azure.md
Adds extra section to the example sql database instance config, this is important for us detecting if the instance is an azure host so we can enable resource linking of integration metrics to cloud crawler metrics. The config already existed for managed instance and virtual machines, but was missing for sql database
```yaml
azure:
deployment_type: 'sql_database'
name: '<DATABASE_2>'
```
---
=> Add azure deployment_type/name section to azure sql db instance config

assets/scripts/components/mobile-nav.js, assets/scripts/datadog-docs.js
Removes scripts that highlighted and redirected to `observability_pipelines/production_deployment_overview/integrate_datadog_and_the_observability_pipelines_worker`  when "Aggregating Agents" under "Agent" was selected
Redirects and documentation for observability pipelines configuration has been updated and this scripted behavior is no longer required.
https://datadoghq.atlassian.net/browse/WEB-3418
https://docs-staging.datadoghq.com/brooklyne.finni/obs_pipelines_redir/
On the preview branch, please select Agent and then Aggregating Agents. You should be redirected to "Getting Started with Observability Pipelines". (This is the same behavior that is on live now- so there should be no change evident on the site)
---
=> [WEB-3418]Brooklyne.finni/obs pipelines redir

content/en/logs/log_configuration/archives.md
Updates the info for AWS encryption and removes outdated image.
[DOCS-4935](https://datadoghq.atlassian.net/browse/DOCS-4935)
---
[DOCS-4935]: https://datadoghq.atlassian.net/browse/DOCS-4935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-4935] Update info and remove image in logs archive encryption section

assets/scripts/components/codetabs.js
This makes it so clicking a tab no longer brings you to the top of the screen.
JIRA Ticket: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3432
---
=> [WEB-3432] Update Code Tabs behavior

content/en/tracing/trace_collection/library_config/go.md
latest version of dd-trace-go(v1.49.0) will change the default value here to true
---
=> telemetry: now enabled by default

content/en/serverless/installation/java.md
Adds aws cdk installation instructions to the serverless java installation page. Essentially copied over from the [node](https://docs.datadoghq.com/serverless/installation/nodejs/?tab=awscdk) and [python](https://docs.datadoghq.com/serverless/installation/python/?tab=awscdk) installation guides, but with an updated layer version property.
The instructions include a banner note, saying that the Datadog CDK is only available for AWS CDK python and node.js apps.
Added java tracing layer support to datadog-cdk-constructs for both v1 and v2.
Customers writing AWS CDK apps in node or python can now use the datadog cdk construct to instrument java functions included in their app.
I thought it made more sense to include both Node + Python CDK app instructions in a single AWS CDK tab (since nested …
=> [Serverless] Add AWS CDK instructions to java installation page

local/bin/py/build/actions/integrations.py, local/bin/py/build/configurations/pull_config_preview.yaml
fail and exit the build if the `format_link_file()` function fails when processing links for integration readmes.
https://dd.slack.com/archives/C3CT8QA11/p1680640924358629
azure integrations page deployed as blank due to issues with the link formatting script
n/a
we have additional work on going to improve the link formatting, this is a more immediate fix to prevent blank integrations pages from being deployed
---
=> [web-3431] fail and exit the build if link formatting fails for integrations

content/en/logs/log_collection/_index.md
Clarify logs submission timestamp.
[DOCS-5082](https://datadoghq.atlassian.net/browse/DOCS-5082), Eng request.
---
[DOCS-5082]: https://datadoghq.atlassian.net/browse/DOCS-5082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-5082] Clarify logs submission timestamp

content/en/database_monitoring/guide/connect_dbm_and_apm.md
This changes the minimum required version of the Node.js tracer. 
There was an issue with the Node.js tracer's initial implementation of dbm propagation which was fixed in [3.17.0](https://github.com/DataDog/dd-trace-js/releases/tag/v3.17.0)/[2.30.0](https://github.com/DataDog/dd-trace-js/releases/tag/v2.30.0). 
Since the bug was preventing the basic dbm propagation functionality, we're setting the minimum required version to the releases with the fix. 
---
=> Update node.js tracer version required for apm/dbm 🔗

layouts/shortcodes/latest-lambda-layer-version.html
Bump serverless java layer version
https://github.com/DataDog/datadog-lambda-java/releases/tag/v1.4.11
=> bump java version

content/en/logs/log_collection/javascript.md, content/en/real_user_monitoring/browser/_index.md, content/en/real_user_monitoring/browser/collecting_browser_errors.md, content/en/real_user_monitoring/browser/modifying_data_and_context.md, content/en/real_user_monitoring/browser/monitoring_page_performance.md, content/en/real_user_monitoring/browser/tracking_user_actions.md, content/en/real_user_monitoring/frustration_signals/_index.md, content/en/real_user_monitoring/guide/proxy-rum-data.md, content/en/real_user_monitoring/guide/send-rum-custom-actions.md, content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md, content/en/real_user_monitoring/guide/setup-rum-deployment-tracking.md, content/en/real_user_monitoring/session_replay/_index.md
Consistently use `window` for `DD_RUM`/`DD_LOGS` usages
Customer request https://github.com/DataDog/browser-sdk/issues/2067
---
=> [RUMF-1519] browser sdk: consistent usage of window

.github/CODEOWNERS
Make CorpWeb required to approve PRs that have changes to anything within the `/assets/` directory.
https://datadoghq.atlassian.net/browse/WEB-3471
n/a
---
=> [web-3471] make corpweb required to approve changes inside assets folder

content/en/tracing/trace_collection/custom_instrumentation/dotnet.md
Adds the logic to extract the propagated span context from SQS messages. This is needed because we can't automatically connect the spans between SQS send/receive for .NET automatic instrumentation (and likely other languages) because the SQS API doesn't give us the right hooks to close the receive spans correctly and reliably 100% of the time.
We have header extraction logic for Kafka and RabbitMQ, so we should also have one for SQS.
N/A
---
=> APM > Custom Instrumentation > .NET > Add SQS header extraction logic

content/en/security/cloud_siem/guide/how-to-setup-security-filters-using-cloud-siem-api.md, content/en/security/cspm/custom_rules/schema.md, content/en/security/cspm/detection_rules.md, content/en/security/cspm/setup.md
Changes GCP to Google Cloud in 4 security docs.
DOCS-4738
---
=> DOCS-4738: Change GCP to Google Cloud in Security docs

assets/scripts/datadog-docs.js
Fixes sidebar navigation not expanding if visiting via a link with a hash.
Problem can be viewed by visiting this link: https://docs.datadoghq.com/account_management/org_settings/service_accounts/#overview
Visiting this link is fine: https://docs.datadoghq.com/account_management/org_settings/service_accounts/
https://datadoghq.atlassian.net/browse/WEB-3461
This link should now correctly expand the sidenav: https://docs-staging.datadoghq.com/fitzage/subnav-expansion/account_management/org_settings/service_accounts/#overview
And this link should still work correctly also: https://docs-staging.datadoghq.com/fitzage/subnav-expansion/account_management/org_settings/service_accounts/
---
=> removing hash conditional for onload nav functions

layouts/partials/api/code-example.html, layouts/partials/api/curl.html
Updates the generated curl examples to use the header params provided too.
We will try and use the schema.example for the header value. Note that because we try and sync the curl generated examples accordion tab with a python,ruby etc. the title might not match the intention of the example exactly. In this case i've checked for the compression content-encoding in the accordion title to determine what compression to show to help avoid this.
slack / https://datadoghq.atlassian.net/browse/DOCS-3960
https://docs-staging.datadoghq.com/david.jones/content-encoding/api/latest/logs/?code-lang=curl#send-logs
https://docs-staging.datadoghq.com/david.jones/content-encoding/api/latest/metrics/?code-lang=curl#submit-metrics
---
=> WEB-2855 - curl generate api example content encoding

content/en/monitors/types/forecasts.md
Removes double-spacing that's being replicated in the translated docs
---
=> Remove double-spacing

content/en/containers/cluster_agent/admission_controller.md, content/en/containers/cluster_agent/setup.md, content/en/containers/guide/cluster_agent_autoscaling_metrics.md, content/en/containers/guide/clustercheckrunners.md, content/en/containers/kubernetes/apm.md, content/en/containers/kubernetes/configuration.md, content/en/containers/kubernetes/log.md
Update the remaining Kubernetes docs with the Operator `v2alpha1` spec corresponding to the GA `1.0.0` release of the Datadog Operator. Changing the yaml snippets and the descriptions accordingly.
Some minor additional changes were made to the Helm side too just to ensure consistency in the language surrounding the two.
Get docs on the GA release instructions instead of the beta instructions.
CC: @CharlyF from our discussion
---
=> Update remaining docs for Operator v2alpha1 spec

assets/scripts/components/algolia.js, assets/styles/instantsearch/searchbar-mobile.scss
removes closing mobile nav function on resize. 
increases z-index on `.searchbox-container`
There was a small bug introduced [here](https://github.com/DataDog/documentation/pull/17230) where the mobile menu was being closed when the window was resized to 991px or less. This resulted in losing the mobile menu opened state that should match the equivalent opened left side nav
mobile menus on the api docs and main docs should open to the appropriate section.
https://docs-staging.datadoghq.com/stefon.simmons/fix-api-mobile-menu-2/api/latest/azure-integration/#update-azure-integration-host-filters
n/a
---
=> fix mobile nav on api docs and main docs

content/en/serverless/aws_lambda/configuration.md
as requested by tian, these tabs were in the wrong section
ready to merge
=> moving content on serverless lambda config page

content/en/getting_started/site/_index.md
- Split RUM domains section into mobile and browse SDKs domains
- add `US1-FED` missing domains
Difference identified between mobile and browser SDKs
---
=> Rework SDKs intake domains section

content/en/account_management/teams.md
Removes the note at the top of the Teams page announcing its beta status.
Teams is in the process of going GA. Only Gov remains in beta, and Teams will be turned on for it next week.
Don't merge yet.
---
=> Remove beta note from Teams page

content/en/continuous_integration/tests/javascript.md
Add a known limitation to CI Visibility and `test.concurrent`.
Let users know.
https://docs-staging.datadoghq.com/juan-fernandez/test-concurrent-limitation/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#jests-testconcurrent
---
=> [ci-visibility] Add known limitation with jest's `test.concurrent`

content/en/serverless/google_cloud_run/_index.md, content/fr/serverless/google_cloud_run/_index.md, content/ja/serverless/google_cloud_run/_index.md
Add the `latest` tag explicitely for serverless-buildpack
The command won't work otherwise
---
=> add latest tag for serverless-buidpack

content/en/continuous_integration/pipelines/gitlab.md
This PR is a one-line change to clarify the required GitLab version customers must have in order to see specific error messages for pipeline execution failures. 
We received a support request about a customer only seeing `error:true`, and the reason behind this was that they were not on an updated version of GitLab.
=> Add version required for GitLab error messages

layouts/partials/api/curl.html
This PR avoids using endpoint specific wording in the deflate message
Slack + https://github.com/DataDog/documentation/pull/15656#issuecomment-1511343233
https://docs-staging.datadoghq.com/david.jones/api-typo/api/latest/metrics/#submit-metrics
---
=> Update api messaging

content/en/tracing/trace_collection/dd_libraries/cpp.md
The JSON endpoint `https://api.github.com/repos/DataDog/dd-opentracing-cpp/releases/latest` used to return pretty-printed JSON. We could then parse the output using standard line-based unix tools.
It is now returning a single line of JSON. This revision modifies the build example to parse the JSON using the non-standard `jq` command line tool instead.
=> use the "jq" command in dd-opentracing-cpp build instructions

content/en/integrations/guide/source-code-integration.md
Update source-code-integration.md - Fix typo
"https://github.con/example_repo"  => "https://github.com/example_repo"
---
=> Fix typo in Datadog Source Code Integration page

assets/scripts/components/algolia/getHitData.js, assets/scripts/components/algolia/searchbarHits.js, assets/scripts/helpers/helpers.js
- API results should be rendered first when users perform a search from the dropdown while on an `api` page.
- the `API` header in the dropdown should have emphasized styling (bold/primary color) 
post-launch item from the search migration 
https://docs-staging.datadoghq.com/brian.deutsch/api-focused-dropdown-results/api/latest/?s=synthetics: API results should be first in the dropdown when on an API page
https://docs-staging.datadoghq.com/brian.deutsch/api-focused-dropdown-results/?s=synthetics: API results should not be first in the dropdown from home page
https://docs-staging.datadoghq.com/brian.deutsch/api-focused-dropdown-results/agent/?s=synthetics: API results should not be first in the dropdown from non-API docs pages
all of the above should be the same for mobile views as well, …
=> enhance API results in the search dropdown on API pages

layouts/shortcodes/vimeo.html
This adds `preload=none` to all vimeo player embeds so the mp4 files are fetched when the user interacts with the vimeo player, and not on page load
Notified of an increased Vimeo bandwith usage https://datadoghq.atlassian.net/browse/WEB-3491
Current live site: https://docs.datadoghq.com/serverless/
1. Open up the dev console -> network
2. Filter for `.mp4`
3. Reload the page
You should see that the `file.mp4?loc=...` is fetched on page load
vs
Preview site: https://docs-staging.datadoghq.com/ccole/vimeo-player-fix/serverless/
1. Open up the dev console -> network
2. Filter for `.mp4`
3. Reload the page
You should see that the `file.mp4?loc=...` is *not* fetched on page load
5. Click play button on video
You should see the  `file.mp4?loc=...` now being fetched, as expected
=> Lazy load vimeo player

content/en/getting_started/_index.md
Adds missing guides to the Getting Started landing page.
DOCS-5292
---
=> DOCS-5292: Add missing guides to Getting Started landing page

content/en/tracing/trace_collection/library_injection_local.md
Adds python info to library injection docs
DOCS-5258
---
=> DOCS-5258 add python to host-container injection docs

content/en/logs/guide/log-collection-troubleshooting-guide.md
Removes MacOS from the tab because the information is only for Linux.
[DOCS-5228](https://datadoghq.atlassian.net/browse/DOCS-5228)
---
[DOCS-5228]: https://datadoghq.atlassian.net/browse/DOCS-5228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-5228] Remove MacOS from tab in log troubleshooting guide

content/en/containers/kubernetes/installation.md
Add a new entry in the agent vs kubernetes versions compatibility: Document the minimum agent version requires to support Kubernetes dynamic service account token feature introduced in Kubernetes 1.22+ (at beta stage)
keep doc up-to-date
---
=> [agent][kubernetes] update compatibility matrix

assets/scripts/components/async-loading.js
`sidenavSearchbarMount` can sometimes be null, this pr accounts for this
https://datadoghq.atlassian.net/browse/WEB-3501
https://docs-staging.datadoghq.com/david.jones/fix-js-bug/profiler/
---
=> WEB-3501 - fix error when el non existant

assets/scripts/components/algolia/getHitData.js
fix translated search relative permalinks
slack https://dd.slack.com/archives/C3CT8QA11/p1681992680647369
searching from the dropdown and from the search page should have correct links in all languages
https://docs-staging.datadoghq.com/brian.deutsch/translated-search-links
https://docs-staging.datadoghq.com/brian.deutsch/translated-search-links/fr
https://docs-staging.datadoghq.com/brian.deutsch/translated-search-links/ja
---
=> fix translated search links

content/en/tracing/trace_collection/custom_instrumentation/java.md, content/en/tracing/trace_collection/library_config/java.md
Cleans up the Java Tracer propagation settings documentation so it is consistent on both pages that it is mentioned.
Customers got confused by conflicting documentation.
---
=> Clean up Java trace propagation documentation

content/en/developers/faq/deploying-the-agent-on-raspberrypi.md
Fixed the display of the images in deploying-the-agent-on-raspberrypi.md
The PR includes the fix of display of images contained into deploying-the-agent-on-raspberrypi.md
I would like to solve the simple problem
---
=> Fixed displaying images in documentation

content/en/getting_started/containers/datadog_operator.md
* Moves `spec.credentials` to `spec.global.credentials` per `v2alpha1` spec
* Self-testing, noticed the doc is incorrect and leads to the error : 
```
Error from server (BadRequest): error when creating "op.yaml": DatadogAgent in version "v2alpha1" cannot be handled as a DatadogAgent: strict decoding error: unknown field "spec.credentials"
```
* When the Operator spec was moved from `v1alpha1` to `v2alpha1`, some fields were modified and the previous snippet is now invalid.
* Spec reference (`v2alpha1`) : https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md
---
=> [K8s Operator] Moves credentials to global per v2alpha1 spec

content/en/getting_started/site/_index.md
Updates the `Location` value associated with the AP1 datacenter in the [Access the Datadog site](https://docs.datadoghq.com/getting_started/site/#access-the-datadog-site) table.
"AP1" is the name of the datacenter, which is not quite the same as the `Location`. "JP" is more specific and in line with what we list in the `Location` column for other DCs (e.g. "US" for "US1").
---
=> Update AP1 `Location` to "JP"

content/en/integrations/kubernetes_state_core.md
The current documentation inaccurately implies that the `kubernetes_state.node.by_condition` metric is not available in the Legacy check. This is untrue; it was introduced to the Legacy check as KSM Core was being developed. The doc change here makes this distinction a bit more clear.
[This escalation
](https://datadoghq.atlassian.net/browse/CONS-5522) noted the existance of the `node.by_condition` metric in Legacy KSM.
---
=> Update KSM documentation regarding nodes.by_condition

content/en/continuous_integration/guides/github_gating.md
Add link to GitHub's blog post in our docs guide for partner launch 
GitHub provided us with their blog post link 
---
=> Add GitHub blog post link

content/en/monitors/case_management/_index.md
Clarifies that Case Management integration is currently only available for Error Tracking for Logs, and not for Error Tracking for APM or RUM.
The current wording may lead users to believe that Case Management integration is enabled for all Error Tracking products.
---
=> Minor clarification on Case Management / Error Tracking

config/_default/params.en.yaml
Update announcement banner for new 2023 appsec report on corpsite
https://datadoghq.atlassian.net/browse/WEB-3489
[Docs preview](https://docs-staging.datadoghq.com/davidweid/new-2023-stateof-report)
- Only the banner has updated
- To be merged in after the report goes live on corpsite
---
=> Update Announcement Banner for Appsec Report

content/en/tracing/trace_pipeline/_index.md
Previous commit removed the retention filters page screenshot, here: https://github.com/DataDog/documentation/commit/ad8cbf18d7dc0efdedf31eb8044ef7d64755ecba and added a new one under a different name, from `retention_filter_page.png` to `retention_filters.png`.
For reference, the old media was this one: https://github.com/DataDog/documentation/blob/e1144a46536b8da588d57333e90b5657f5ce3118/static/images/tracing/trace_indexing_and_ingestion/retention_filters/retention_filter_page.png
With this being the new one: https://github.com/DataDog/documentation/blob/ad8cbf18d7dc0efdedf31eb8044ef7d64755ecba/static/images/tracing/trace_indexing_and_ingestion/retention_filters/retention_filters.png
---
=> Fix retention filters screenshot image broken path

content/en/tracing/trace_collection/otel_instrumentation/python.md
Replaces `ddttrace-run` with `ddtrace-run`
---
=> opentelemetry: fix typo in python tracing docs

content/en/security/cloud_workload_security/setup.md
This PR adds a new page in the installation documentation for CWS explaining on to enable it when using the operator v1.
---
=> [SEC-8217] add new tab on how to enable CWS using the operator for the agent

content/en/database_monitoring/guide/connect_dbm_and_apm.md
Node is now fully supported for mysql & postgres; update docs accordingly. 
---
=> Node.js tracer is out of alpha for apm-dbm link

content/en/monitors/notify/variables.md
Add Error tracking example of tag variables customers can use in their Monitor messages.
[DOCS-5286](https://datadoghq.atlassian.net/browse/DOCS-5286)
---
[DOCS-5286]: https://datadoghq.atlassian.net/browse/DOCS-5286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Error tracking tag variables

content/en/security/application_security/enabling/compatibility/go.md
This adds the ASM Go library version starting from which Suspicious Request Blocking is supported.
---
=> ASM/Compatibilty: add supported version for Suspicious Request Blocking

layouts/shortcodes/latest-lambda-layer-version.html
See https://github.com/DataDog/dd-trace-java/pull/4844
Downgrade java tracing layer version to 8.
See https://github.com/DataDog/dd-trace-java/pull/4844
---
=> Downgrade java lambda layer version from v9 to v8.

content/en/tracing/trace_collection/library_injection_local.md, content/en/tracing/troubleshooting/tracer_debug_logs.md, content/en/tracing/troubleshooting/tracer_startup_logs.md
Adds the information for users to set up library injection for their .NET containers in Kubernetes
In the next release of the Datadog agent (7.44.0), .NET will be a supported language for library injection, so this updates the documentation to allow customers to use it.
@elee0625 I would like your input on how we differentiate between the two different containers that cover our Linux support. The main `musl` distribution is Alpine. For reference, you can see how we have previously described the .NET Tracer setup for different separate Linux distributions [here](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/dotnet-core?tab=linux#install-the-tracer).
---
=> APM > Library Injection > Add .NET instructions

layouts/partials/rbac-permissions-table.html
After getting questions several times, I wrote an internal wiki article on "scopable" permissions: https://datadoghq.atlassian.net/wiki/spaces/AAA/pages/2963967417/Scoped+Permissions (only accessible inside Datadog)
In doing the research, I noticed that the list of scopable permissions in our public docs is wrong. This PR should correct the error.
Want to fix an error!
https://docs-staging.datadoghq.com/stephen.rosenthal/fix-error-about-scopable-permissions/account_management/rbac/permissions/#log-management
n/a
---
=> Fix list of scopable permissions

content/en/tracing/trace_collection/compatibility/nodejs.md
Remove `fs` from the Node.js compatibilities doc.
Release notes for 3.0.0 of the node.js tracer that we dropped support for fs:
> fs: remove fs plugin (#2137)
Ask on #support-apm before the change: https://dd.slack.com/archives/C4WC8C39Q/p1682595786121409
=> Remove fs from the public doc

layouts/shortcodes/latest-lambda-layer-version.html
Bump datadog-lambda-python layer to version 72 
---
=> Bump datadog-lambda-python layer to version 72

content/en/logs/log_configuration/parsing.md
This PR removed a bullet point from our Grok Parsing documentation. This bullet point may be accurate but I do not think it belongs in this section. I'm happy to move it to another page if anyone is aware of a more appropriate location. Thanks!
---
=> Remove message about agent from Grok Parser notes

content/en/tracing/trace_collection/trace_context_propagation/java.md
Update the Java tracer library context propagation documentation to use the latest settings available.
`DD_PROPAGATION_STYLE_INJECT` and `DD_PROPAGATION_STYLE_EXTRACT` are the old and now deprecated settings.
Moreover, they do not support all the propagation styles listed in the documentation page (`tracecontext` is missing) so this lead to confusion for customers.
---
=> Fix Java tracer library context propagation

content/en/real_user_monitoring/browser/modifying_data_and_context.md
`DD_RUM.startView` can be used with a single string name argument (ex: `DD_RUM.startView("cart")`).
Starting from v4.13.0, this function can also be used with an object to optionally specify version and service for the view (ex: `DD_RUM.startView({name: "cart", version: "1.2.3"})`).
Some customers are using the "new" object signature with outdated versions of the SDK, which is unexpected, and might crash the datadog app.
---
=> clarify `DD_RUM.startView` API history

content/en/security/application_security/_index.md
Adding back side bar on App sec page
---
=> fixed sidebar on appsec page

content/en/continuous_integration/tests/junit_upload.md
Add a note that will be removed soon about measures values being strings.
DOCS-5298
---
=> DOCS-5298 Uploading JUnit test report files to Datadog Edit

content/en/integrations/syslog_ng.md
Remove note about US3 not being supported.
US3 is supported with the http module.
---
=> Remove note about US3

content/en/monitors/settings/_index.md
This functionality was removed due to an incident : https://dd.slack.com/archives/C050UQCJM0F 
Remove mention of Synthetics from Monitor Tag Policies
---
=> Remove mention of Synthetics from Monitor Tag Policies

i18n/en.json, layouts/partials/integration-labels/integration-labels.html
changes "v" to "version" at the top of Integrations pages in the docs 
Slack convo
---
=> Change version presentation in integrations pages

content/en/database_monitoring/_index.md, content/en/integrations/_index.md
Adds algolia tags for two pages to bump the search relevancy 
https://datadoghq.atlassian.net/browse/WEB-2006
https://docs-staging.datadoghq.com/brian.deutsch/more-search-relevance/search/?s=gcp `integrations/google_cloud_platform` should be first in results
https://docs-staging.datadoghq.com/brian.deutsch/more-search-relevance/search/?s=npm
`network_monitoring/performance` should be first in results
https://docs-staging.datadoghq.com/brian.deutsch/more-search-relevance/search/?s=dbm
`database_monitoring` should be first in results
---
=> [web-2006] Search relevance update

content/en/tracing/trace_collection/library_config/java.md
Document DD_TRACE_OBFUSCATION_QUERY_STRING_REGEXP, introduced by https://github.com/DataDog/dd-trace-java/pull/3595 in 0.104
---
=> Document dd.trace.obfuscation.query.string.regexp in java tracer

content/ja/tracing/troubleshooting/tracer_debug_logs.md
Documentation link for SL4J SimpleLogger on the Japanese page has been corrected.
Because the link was incorrect.
---
=> SL4J SimpleLogger documentation link corrected

content/en/monitors/notify/variables.md
Extends the documentation on reserved attributes in monitor notifications with Event, CI Pipeline, and CI Test monitors. 
---
=> Extend list of reserved attributes with Event, CI Pipeline, and CI Test

content/en/agent/guide/operator-advanced.md, content/es/agent/guide/operator-advanced.md, content/fr/agent/guide/operator-advanced.md, content/fr/containers/datadog_operator.md, content/ja/agent/guide/operator-advanced.md, content/ja/containers/datadog_operator.md, content/kr/agent/guide/operator-advanced.md
PR is related to earlier Operator GA PR https://github.com/DataDog/documentation/pull/17513 and remove several remaining "Operator in Beta" banners.
---
=> Remove Operator in Beta banner from various pages

content/en/watchdog/faulty_deployment_detection.md
Banner at the top of the APM services page  is falid collor.
Banner at the top of the APM services page  is falid collor.
Changed from YELLOW to PINK.
---
=> Banner at the top  is falid collor.

CONTRIBUTING.md
👋 It was pointed out this wording feels a bit pejorative toward the corporate blog so wanted to ask if we could tweak this.
Small language tweak to the Docs contribution guidelines
---
=> Small tweak to contribution language

config/_default/menus/menus.en.yaml, content/en/real_user_monitoring/error_tracking/custom_grouping.md
Reverts DataDog/documentation#17297 and specifies the functionality is currently available only for the browser RUM SDK that's been introduced in https://github.com/DataDog/browser-sdk/pull/2189.
Docs for Android and iOS SKDs will follow when they'll be released.
=> [error tracking] Add custom fingerprint docs for browser RUM

content/en/logs/log_collection/_index.md
Remove text about sending logs 2h in the future.
DOCS-5082. Eng requested, PM approved.
---
=> [DOCS-5082] Remove 2h in the future for logs

content/en/data_streams/troubleshooting.md
Add section on cluster tags to the DSM troubleshooting docs: https://docs.datadoghq.com/data_streams/troubleshooting/
---
=> add cluster tag section in DSM docs

content/en/logs/log_configuration/processors.md
Added a Note to indicate date the ISO date format now requires the `T` separator in front of the HH.
Decided against linking to the newer [ISO](https://www.iso.org/standard/70907.html) documentation as their docs note it is a "paid" document. So hence just adding a note to help avoid confusion.
https://datadoghq.atlassian.net/browse/LOGSS-6783
---
=> [DOCS-5423] updating ISO date format

content/en/developers/dogstatsd/_index.md, content/fr/developers/dogstatsd/_index.md, content/ja/developers/dogstatsd/_index.md
Moves the blurb regarding using `DD_DOGSTATSD_SOCKET` environment variable under Ruby language as it currently only applies to dogstatsd-ruby.
All other other official DSD libraries (csharp, go, python, java, php) makes use of `DD_AGENT_HOST` for either UDP or UDS
AGENT-9656
---
=> DD_DOGSTATSD_SOCKET is dogstatsd-ruby only

data/partials/home.yaml
Add the Data Streams Monitoring tile to the docs landing page
https://a.cl.ly/mXuDgwqx 
[DOCS-5420](https://datadoghq.atlassian.net/browse/DOCS-5420)
Do not merge, would like to get PM review of copy.
---
[DOCS-5420]: https://datadoghq.atlassian.net/browse/DOCS-5420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Data streams monitoring tile to landing page

content/en/database_monitoring/setup_mysql/azure.md, content/en/database_monitoring/setup_postgres/azure.md, content/en/database_monitoring/setup_sql_server/azure.md
The documentation for the azure's name configuration used to specify the server name rather than the fully qualified domain name which is the thing we need. This is now made clearer in the integrations in the related PRs below. While the configuration key is being renamed to `fully_qualified_domain_name`, this will be in future releases so the documentation examples here are keeping the `name` configuration key which is going to remain valid. 
Reference PRs:
* https://github.com/DataDog/integrations-core/pull/14534
* https://github.com/DataDog/integrations-core/pull/14536
* https://github.com/DataDog/integrations-core/pull/14532
---
=> Update documentation for azure cloud metadata configuration

content/en/integrations/guide/collect-sql-server-custom-metrics.md
Remove current image of postgresql metrics from a SQL Server guide.
Will not replace as the link to the Metrics Explorer takes the user directly to the Explorer page.
[DOCS-5440](https://datadoghq.atlassian.net/browse/DOCS-5440)
---
[DOCS-5440]: https://datadoghq.atlassian.net/browse/DOCS-5440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove SQLServer unrelated image

content/en/agent/guide/how-to-import-datadog-resources-into-terraform.md
Add previously unmentioned `--api-url` flag, and remove the api/app keys from the `main.tf` file since they aren't needed to use terraformer to import.
Docs are out of date and can lead to errors when following it.
---
=> Update Terraformer docs to include api-url and remove unneeded config

layouts/shortcodes/semantic-color.html
semantic-color.md is generated in the build but it also used to exist locally to avoid local build errors such as cannot find file.
Recent changes mean that this file no longer exists locally by default, in order to avoid the build errors we now instead use a shortcode that will include the file if it exists.
Local build errors due to recent reconfigurations
Check this page is still working
https://docs-staging.datadoghq.com/david.jones/fix-semantic-error/dashboards/guide/compatible_semantic_tags/
Check local build doesn't throw any errors
---
=> semantic color build error

content/en/integrations/faq/list-of-api-source-attribute-value.md
Corrects the search term under API source attributes for Amazon Security Hub.
I actually changed this yesterday based on what I found in the code, which was different from the original request. The requestor got back to me today with proof that his original request is correct. Updating the line to the correct value.
---
=> DOCS-5282 Fix API source search term for Amazon Security Hub

config/_default/menus/menus.en.yaml
triggering a change to the menus yaml file in order to test recent changes to the translation pipeline supporting yaml files.
`.yaml` file uploads haven't been successfully uploaded by the translation lambda due to an issue in the way that file type is handled in Transifex.   this PR is testing the changes we recently made to ensure they are working properly.
should be nothing to preview as this change is just adding a newline to the end of the file
---
=> trigger a change to test Transifex changes

content/en/tracing/trace_collection/library_config/php.md
This PR aims to documented a newly introduced option that was added as part of [#1971](https://github.com/DataDog/dd-trace-php/pull/1971) in dd-trace-php.
---
=> Add DD_TRACE_HTTP_POST_DATA_PARAM_ALLOWED's doc

content/en/tracing/trace_collection/compatibility/php.md
This version is now officially supported (web integration test added in ddtrace-php)
---
=> Update ZF1 v1.21 support

content/en/continuous_integration/tests/java.md
Update CI Visibility docs for Java:
- onboarding instructions are simplified taking into account the latest automatic configuration features in the Java tracer
- configuration section is updated accordingly
- troubleshooting section is updated accordingly
A new version of DD Java Tracer is being released, which contains automatic configuration logic, that allows to simplify customer onboarding process.
The PR removes those onboarding steps that are now redundant.
---
=> Update CI Visibility Java onboarding instructions

content/en/real_user_monitoring/connect_rum_and_traces/_index.md
- Adds a reference to the iOS tracing page for customers who want to go straight into tracing their iOS app in Swift
- Renumbers all links
Reduce customer confusion by making it clear they can trace their iOS app. [DOCS-5430](https://datadoghq.atlassian.net/browse/DOCS-5430)
---
[DOCS-5430]: https://datadoghq.atlassian.net/browse/DOCS-5430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add reference to iOS tracing link

content/en/developers/community/libraries.md
URL of jira doc has been changed.
Because I found an error in the link.
=> URL of jira doc has been changed.

content/en/opentelemetry/otel_collector_datadog_exporter.md
Prometheus receiver was not enabled via pipelines in the service section.
=> Enable prometheus receiver

content/en/account_management/rbac/_index.md, content/en/account_management/teams.md, content/en/dashboards/guide/slo_data_source.md, content/en/dashboards/widgets/event_stream.md, content/en/dashboards/widgets/slo.md, content/en/dashboards/widgets/slo_list.md, content/en/developers/_index.md, content/en/getting_started/application/_index.md, content/en/getting_started/incident_management/_index.md, content/en/getting_started/tagging/using_tags.md, content/en/logs/guide/best-practices-for-log-management.md, content/en/logs/log_configuration/archives.md, content/en/monitors/_index.md, content/en/monitors/guide/integrate-monitors-with-statuspage.md, content/en/monitors/guide/slo-checklist.md, content/en/monitors/notify/downtimes.md, content/en/monitors/types/event.md, content/en/monitors/types/slo.md, content/en/service_management/events/explorer/_index.md, content/en/service_management/service_level_objectives/_index.md, content/en/service_management/service_level_objectives/error_budget.md, content/en/service_management/service_level_objectives/metric.md, content/en/service_management/service_level_objectives/monitor.md, content/en/synthetics/search/_index.md, content/en/tracing/service_catalog/scorecards.md, content/en/tracing/services/service_page.md, content/en/universal_service_monitoring/guide/using_usm_metrics.md, content/en/watchdog/faulty_deployment_detection.md
Fix the alias for event explorer. Mistakenly changed the URL in the frontmatter which would cause a circular reference.
Build pointed out the error.
Original PR: https://github.com/DataDog/documentation/pull/17847
---
=> Fix alias for event explorer in the left nav update

content/en/serverless/installation/java.md
there was a whole stack of alerts here that don't need to be alerts. i've changed them to not be alerts.
ready to merge.
=> change excessive alerts to just regular text on Java Lambda instrumentation page

content/en/database_monitoring/guide/connect_dbm_and_apm.md
Table and tab were out of sync with regards to required Python tracer version. 
---
=> fix inconsistent Python tracer version in APM-DBM docs

content/en/continuous_integration/tests/javascript.md
Remove mention of `jest-jasmine2`, now that it's not supported for dd-trace-js>=4
Keep up with changes in dd-trace-js
https://docs-staging.datadoghq.com/juan-fernandez/remove-jest-jasmine2/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#compatibility
---
=> [ci-visibility] Remove mention of `jest-jasmine2`

content/en/continuous_integration/tests/junit_upload.md
Add git metadata upload section to junit
Align with the native libraries. 
https://docs-staging.datadoghq.com/juan-fernandez/add-git-metadata-to-junit/continuous_integration/tests/junit_upload/?tab=linux#git-metadata-upload
---
=> [ci-visibility] Add git metadata upload section to junit

content/en/database_monitoring/troubleshooting.md
Adds the site address shortcode to to the DBM Troubleshooting page. Ready to merge.
DOCS-5458
---
=> DOCS-5458: Add site address shortcode to DBM Troubleshooting

content/en/tracing/guide/send_traces_to_agent_by_api.md
Adds a powershell command equivalent to the curl one
To make it easier for windows users
---
=> [Tracing][Guides] Add a powershell command equivalent to the curl one

.gitlab-ci.yml, .htmltest.yml, layouts/shortcodes/integrations.html
Enables the internal hash checks on a link checking job that runs on a schedule.
Its currently too noisy to run on every preview until we reduce the reports.
https://datadoghq.atlassian.net/browse/WEB-1761
Not much to see but when released the scheduled run should trigger a full link check
https://docs-staging.datadoghq.com/david.jones/test-link/
---
=> WEB-1761 - anchor link checking

.github/workflows/synthetics.yml, .gitlab-ci.yml
Moves synthetics to a github action that only runs on PRs to lessen the amount of runs we perform
We are currently running synthetics on every branch push, which is adding up quickly
Successful action run https://github.com/DataDog/documentation/actions/runs/5006537461/jobs/8971948050
---
=> Move synthetic testing to github

content/en/profiler/enabling/dotnet.md
Image files were changed in this [PR](https://github.com/DataDog/documentation/pull/17811), but the image src in other files were not which caused this [page](https://docs.datadoghq.com/profiler/enabling/dotnet/?tab=internetinformationservicesiis#enabling-the-profiler) to show broken [images](https://a.cl.ly/L1uD0WLL).
documentation on call
---
=> Fix broken image src

assets/scripts/region-redirects.js, content/en/agent/guide/how_remote_config_works.md, content/en/agent/guide/network.md, content/en/agent/guide/private-link.md, content/en/agent/logs/proxy.md, layouts/_default/baseof.html, layouts/shortcodes/site-region.html
updates site-region shortcode syntax on en `/agent` pages to allow for `.
As a part of this card: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3279
Check that the TOC items are showing for the preview links below
Check that the hyperlinks on the modified files take you to the appropriate place: 
https://docs-staging.datadoghq.com/stefon.simmons/fix-site-region-agent-pgs/
Specifically, notice that the TOC appears now on this page: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-region-agent-pgs/agent/guide/private-link/?tab=vpcpeering
---
=> fix-toc-site-region-updates-agent pgs

.gitlab-ci.yml
removes the after_script step on the scheduled anchor link check job
To avoid an error we were seeing
No changes to site
---
=> link check remove after_script

content/en/agent/logs/advanced_log_collection.md
It looks like the Kubernetes AD collection for logs hasn’t been updated in a couple of years, The way it’s currently documented is not technically wrong as even though these have an explicit name in the annotation,  they all have a matching container like:
metadata:
annotations:
ad.datadoghq.com/postgres.logs: >-
[{
"source": "postgresql",
"service": "database",
"log_processing_rules": [{
"type": "multi_line",
"name": "log_start_with_date",
"pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"
}]
}]          
labels:
app: database
name: postgres
spec:
containers:
- name: postgres --> container name matches
image: postgres:latest
So we can go ahead and make an update to have the Logs page use the <CONTAINER_IDENTIFIER>  format like we do in the  [Integration AD …
=> [DOCS-5473] updating Container Identifier AD info on Logs page

content/en/getting_started/database_monitoring/_index.md, content/en/getting_started/incident_management/_index.md, content/en/getting_started/site/_index.md, content/en/network_monitoring/performance/setup.md, layouts/shortcodes/site-region.html
updates site-region shortcode syntax on en `/getting_started` pages.
As a part of this card: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3279
Check that the TOC items are showing for the preview links below
Check that the hyperlinks on the modified files take you to the appropriate place:
https://docs-staging.datadoghq.com/stefon.simmons/fix-site-gettingstarted-pgs/
Specifically, notice on the `US1-FED` site region that the `Access the Datadog for Government site` TOC items appears on this page now: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-gettingstarted-pgs/getting_started/site/
---
=> Stefon.simmons/fix site gettingstarted pgs

.gitlab-ci.yml
Updates the CI to the latest image for an upcoming slack notification change
---
=> Use new image for preview notifs

content/en/network_monitoring/performance/network_page.md, content/en/network_monitoring/performance/setup.md
This PR mentions the fact that we now support application gateways for Azure. It also includes the set of tags available for azure resources.
https://datadoghq.atlassian.net/jira/software/projects/NET/boards/133?selectedIssue=NET-3152
---
=> [NET-3152] add public documentation Azure loadbalancers and application gateways

content/en/security/cspm/custom_rules/schema.md
Fixes an issue with the CSPM Google Cloud schemas not displaying as expected. Ready to merge.
We changed the word GCP to Google Cloud in a previous PR, but it turns out the single sourcing for the cloud schemas is tied directly to the term "GCP".
---
=> Fix GCP cloud schemas

config/_default/menus/menus.en.yaml, content/en/monitors/types/_index.md, content/en/monitors/types/cloud_cost.md
- Add Cloud Cost to the Monitor Types page
- Add Cloud Cost to the left navigation
- Remove the private beta banner
https://datadoghq.atlassian.net/browse/DOCS-5173
---
=> Add cloud cost monitor to navigation

content/en/real_user_monitoring/flutter/advanced_configuration.md, content/en/real_user_monitoring/flutter/setup.md
- Moves the **Sample RUM sessions** section from the **Flutter > Advanced Configuration** page to **Flutter > Setup** page.
To make it inline with other SDK pages, per [DOCS-5487](https://datadoghq.atlassian.net/browse/DOCS-5487).
---
[DOCS-5487]: https://datadoghq.atlassian.net/browse/DOCS-5487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move sample RUM sessions section for flutter

assets/scripts/cookie-banner.js, assets/scripts/main-dd-js.js, layouts/_default/baseof.html, layouts/partials/header-scripts.html
Adds TrustArc dependent scripts and logic for cookie consent banner. No visible changes except from EU-region
https://docs-staging.datadoghq.com/nsollecito/cookie-banner/
---
=> [WEB-3464] Adds TrustArc cookie consent banner to Docs site

.github/workflows/linting.yml
There seems to be a bug in the Vale action that makes the `files` and `filter_mode` variables mutually exclusive. The check was finding errors in parts of the files that had not been modified in the commits, which was leading to confusion. It was especially annoying in large PRs like the translation PRs. This removes the `files` logic from the action so that the checks will pass as long as there are no errors in directly modified lines.
---
=> (DOCS-5548) Fix Vale

content/en/developers/community/libraries.md
We found out due to a customer request, that there is a 3rd party maintaining a Heroku Buildpack which adds the PHP tracer (and with [this PR](https://github.com/SpeedCurve-Metrics/heroku-buildpack-php-ddtrace/pull/3) also the profiler) to Heroku.
Have customers on Heroku find this and enable them to use the PHP tracer and profiler
---
=> Add heroku buildpack for PHP

content/en/tracing/trace_collection/library_config/java.md
This PR adds the java tracer configuration documentation about the two new settings for 128-bit trace ID.
It should help the customers to discover and use the feature.
---
=> Add java tracer configuration documentation about 128-bit trace ID

content/en/account_management/rbac/permissions.md
A product manager requested that we remove the "Scoped" column from the permissions on this page. The Websites team is doing that. This change removes the accompanying text.
https://datadoghq.atlassian.net/browse/WEB-3646
ready to merge
---
=> Remove line about scoped permissions

layouts/sitemap.xml
fix docs sitemap formatting for multilingual sites: 
https://datadoghq.atlassian.net/browse/WEB-3466
ja: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-map/ja/sitemap.xml
fr: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-map/fr/sitemap.xml
en: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-map/en/sitemap.xml
root: https://docs-staging.datadoghq.com/stefon.simmons/fix-site-map/sitemap.xml
---
=> update sitemap - [WEB-3466]

content/en/real_user_monitoring/connect_rum_and_traces/_index.md
Adds a code sample with the `allowedTracingUrls` for CDN install so that users know it works for that as well, and not just for NPM install.
To reduce customer confusion, as documented in [DOCS-5456](https://datadoghq.atlassian.net/browse/DOCS-5456).
---
[DOCS-5456]: https://datadoghq.atlassian.net/browse/DOCS-5456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add cdn install example

content/en/agent/guide/heroku-ruby.md
- Add DD_SITE configuration on docs for heroku
Since datadog support multiple zones we need to set the DD_SITE env.
Perhaps I should provide guidance on how to get the right zone?
---
=> Add DD_SITE config on heroku-ruby

content/en/real_user_monitoring/browser/_index.md
Fixes RUM browser SDK CDN sync snippets
Incorrect doc
---
=> 🐛 Add missing global check on CDN sync snippets

content/en/tracing/service_catalog/_index.md
update to reflect new env* dropdown option and clarify second primary tag
---
=> Update Service Catalog Explorer View

content/en/containers/cluster_agent/clusterchecks.md, content/en/containers/cluster_agent/endpointschecks.md
Cluster checks and Endpoint checks documentation were not up to date, as they didn't include v2 of the AD annotations, which are recommended from Agent 7.36.
This PR adds this.
---
=> Add AD v2 annotations documentation to cluster and endpoint checks

content/en/tracing/metrics/metrics_namespace.md
Update tags supported on trace.<SPAN_NAME>.hits
---
=> Correction on Trace Metrics Tags

content/en/getting_started/site/_index.md, content/en/real_user_monitoring/_index.md
- Moves the list of SDK domains for RUM from the Getting Started > Sites page to the Real User Monitoring index page
It was the only product-specific list of sites left on the Getting Started page. It makes more sense to be in the RUM section. [DOCS-5840](https://datadoghq.atlassian.net/browse/DOCS-4840).
---
=> Moved SDK domains to RUM index page

content/en/monitors/types/metric.md
- Remove the alert grouping option from the [Metric monitor page](https://docs.datadoghq.com/monitors/types/metric/?tab=threshold#overview) as this configuration is now in the Notification section of the monitor config not in the query configuration
- Notification docs: https://docs.datadoghq.com/monitors/configuration/?tab=thresholdalert#alert-grouping
- 
- dead link was brought up in #documentation
---
=> Remove alert grouping from metric monitor query

content/en/containers/amazon_ecs/_index.md
Add an Agent option in the FIPS section for ECS
`DD_FIPS_ENABLED` is needed to correctly configure the Agent
https://docs-staging.datadoghq.com/nicolas.guerguadj/add-fips-enabled-for-ecs/containers/amazon_ecs/?tab=awscli#fips-proxy-for-govcloud-environments
---
=> Add fips enabled options in Agent definition when using FIPS on ECS

assets/styles/pages/_glossary.scss, content/fr/glossary/_index.md, layouts/glossary/list.html
1. removes restrictive height on glossary nav
- adjusts the scroll to positioning
2.  removes duplicate letter headers in ja glossary
3. add 'All' button text to the france glossary
https://datadoghq.atlassian.net/browse/WEB-3672
https://docs-staging.datadoghq.com/stefon.simmons/fix-glossary-ja/ja/glossary/
---
=> fix glossary ja - [WEB-3672]

local/bin/js/algolia-index-sync.js
Enable [advancedSyntax searching](https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/) so that exact strings can be searched
Somewhat related to [WEB-3641](https://datadoghq.atlassian.net/browse/WEB-3641) , [WEB-3658](https://datadoghq.atlassian.net/browse/WEB-3658) 
It gives more accurate results when searching exact strings
Try searching for `"image name instead of the regular"` including quotes and you will get the exact page vs without quotes where it may pickup others
https://docs-staging.datadoghq.com/david.jones/advanced-syntax/
---
[WEB-3641]: https://datadoghq.atlassian.net/browse/WEB-3641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3658]: https://datadoghq.atlassian.net/browse/WEB-3658?atlOrigin=eyJpIjoiNW …
=> use advanced syntax on index

content/en/security/application_security/vulnerability_management/_index.md
"Disabling" heading doesn't need to be h2
=> ASM vuln det heading nit

content/en/security/application_security/threats/add-user-info.md
Corrects the import statement in the java example
https://github.com/DataDog/documentation/issues/18103 
---
=> DOCS-5470 Fix java example import statement

content/en/tracing/trace_collection/library_injection_local.md
Gets specific about where to set certain env vars for kub library injection
Chat with support in slack
Can be merged now
---
=> Clarify where to set Appsec, profiler env vars for kubernetes library injection

.vale.ini, content/en/agent/guide/agent-5-autodiscovery.md
Fixes the Vale linter. Unfortunately, the config file doesn't like it when we use a file path glob. It only expects file extensions there. So the action will check everything, which takes a little longer. The action itself is still confined to content/en, so it shouldn't run on the translation PRs. And it should only fail on errors added in the PR.
Should be good to merge. 
---
=> (maint) Fix Vale

content/en/metrics/custom_metrics/dogstatsd_metrics_submission.md
Add note that Rate metric type is shown as gauge for DogstatsD submissions
https://datadoghq.atlassian.net/browse/DOCS-5133
Resolves Issue #17427 
---
=> Clarify rate metric type submission for dogstatsd

content/en/profiler/profiler_troubleshooting/ruby.md
**What does this PR do?**:
In #17552 we documented that the new Ruby "CPU Profiling 2.0" profiler uses unix signals, and that in rare cases this can cause incompatibilities with some other Ruby gems.
At the time, the recommended workaround was to fall back to the legacy profiler.
For `dd-trace-rb` 1.12.0 we'll have a better solution, a new setting that we're calling the "no signals" workaround (https://github.com/DataDog/dd-trace-rb/pull/2873).
This PR updates the documentation to point customers at this better solution, and drops references to using the legacy profiler as we're planning to deprecate it soon.
**Motivation**:
Update the customer guidance for dealing with signal-based incompatibilities.
**Additional Notes**:
This PR is in good shape for review (I hope), but we should hold …
=> [PROF-7321] Recomend using Ruby profiler "no signals" workaround if needed

content/en/opentelemetry/otel_collector_datadog_exporter.md, content/en/opentelemetry/otlp_ingest_in_the_agent.md
Adds "Install OTel integration" as a step before viewing Otel dashboards
DOCS-5489
Also looking into why the OTel integration is hidden in the docs site (but not the product)
---
=> DOCS-5489 Mention otel integration requirement for looking at dashboards

content/en/dashboards/widgets/timeseries.md
- Add a reference link to the guide for graph color palletes.
Just noticed that these pages should be linked.
---
=> Add reference links to graph color guide

content/en/account_management/billing/rum.md
Adds a new Q&A to the Account Management section about Session Replay lengths.
Reduce customer confusion about short Session Replays, per [DOCS-5499](https://datadoghq.atlassian.net/browse/DOCS-5499).
Ready for merge.
---
[DOCS-5499]: https://datadoghq.atlassian.net/browse/DOCS-5499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> session replay recording length question

layouts/glossary/list.html
add data-products attribute to 'glossary-term-container'.
- exposes the associated `core-products` of a glossary term for synthetic testing use
need to monitor and test glossary functionality via synthetics
there should be no visual change: https://docs-staging.datadoghq.com/stefon.simmons/add-data-attr-to-glossary-terms/glossary
---
=> expose associated core-products in term container

content/en/serverless/aws_lambda/configuration.md
Add profiling information to AWS lambda advanced config page
Adds a brief description of how to enable/disable the public beta
Link #41 is already being used in another part of the page
---
=> add profiling public beta to lambda advanced config page

content/en/agent/guide/dual-shipping.md
Fix wrong examples for profiling dual shipping. 
Also separated profiling dual shipping instructions into its own section, separate from APM for extra clarity that one doesn't necessarily require the other.
Finally, fixed wrong URLs in tracing additional endpoints, yaml version.
Fix wrong instructions.
---
=> [profiling] Fix dualshipping instructions.

content/en/tracing/trace_collection/proxy_setup/_index.md
This reverts commit 6dd624fb762cb8dc8a2d3ff217720429d1733610. The associated customer issue referred to an older version of this documentation. The change made in #16939 then made the installation instructions incorrect. This revision undoes that change, as the "before" of the diff was correct (and more recent than that to which the customer was referring, which is what caused the mix-up).
---
=> Revert "DOCS-4870 update name of module tarball (#16939)"

content/en/tracing/trace_collection/dd_libraries/nodejs.md
- adds a section to a Node.js page with instructions regarding bundling
- this is a new feature that users will likely have questions about using
- https://docs-staging.datadoghq.com/tlhunter/nodejs-bundlers/tracing/trace_collection/dd_libraries/nodejs/?tab=containers#bundling
- these docs are copied from the dd-trace-js README
- probably shouldn't land until dd-trace-js cuts a new release
- should the documentation mention the library version number that introduces the feature?
---
=> Node.js: add instruction for bundlers/esbuild

content/en/tracing/trace_collection/proxy_setup/_index.md
This revision alters the "tracing a proxy" section of the APM/tracing documentation to account for [recent changes][1] to our nginx module.
The `nginx-datadog` module is now configured differently. Additionally, the underlying tracing module is now `dd-trace-cpp` instead of `dd-opentracing-cpp`. One consequence of this is that now the underlying tracer of `nginx-datadog` is different than the underlying tracer of `ingress-nginx`, which still uses `dd-opentracing-cpp`.
I propose the following documentation changes:
- The section on our nginx module, `nginx-datadog`, includes an updated example and refers to the source repository for further information.
- The section on sampling with nginx is now specific to the OpenTracing module (with our plugin). Previously, it applied to both the …
=> nginx-datadog v1.0.0

content/en/security/application_security/enabling/compatibility/serverless.md, content/en/serverless/guide/serverless_tracing_and_webpack.md
- adds a cross reference to the new esbuild page from the existing serverless page
- the serverless page doesn't mention the new plugin which is helpful to users
---
=> Node.js: add cross reference to esbuild page from serverless page

content/en/containers/kubernetes/distributions.md
Makes a few minor tweaks to the GKE Autopilot docs based on information submitted on [this card](https://datadoghq.atlassian.net/browse/CONS-5598), which comes from a Google employee working to test our product on autopilot. 
Specifically it removes `resources.limits` from the spec since Autopilot doesn't use them, and adds a priority class to the agent to help it get scheduled. 
---
=> GKE Autopilot doc changes. 

content/en/serverless/azure_container_apps/_index.md
I believe it is missing `RUN`.
Error message when running azure build commands:
```
> az acr build --registry $ACR_NAME --image $API_NAME .
Packing source code into tar to upload...
Uploading archived source code from '/var/folders/kz/xqpbjdv964s74w6w3j4q8vxm0000gq/T/build_archive_8d4eabac2a3043a5a891b3c24595603f.tar.gz'...
Sending context (8.998 KiB) to registry: acaalbumskimip...
Queued a build with ID: cxk
Waiting for an agent...
2023/05/18 15:01:48 Downloading source code...
2023/05/18 15:01:49 Finished downloading source code
2023/05/18 15:01:49 Using acb_vol_00a33031-4589-4472-88cc-5b877588d786 as the home volume
2023/05/18 15:01:49 Setting up Docker configuration...
2023/05/18 15:01:50 Successfully set up Docker configuration
2023/05/18 15:01:50 Logging in to registry: …
```
=> Update instrumentation command of Azure Container Apps

content/en/containers/amazon_ecs/_index.md
A new version is out to fix CVE
https://docs-staging.datadoghq.com/nicolas.guerguadj/ecs-fips-0.5.3/containers/amazon_ecs/?tab=awscli#fips-proxy-for-govcloud-environments (FED-US1 only)
---
=> Update FIPS proxy version to 0.5.3

content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
Adds additional code snippets to showcase how to report Amplitude's feature flags to Datadog through RUM
---
=> Add Amplitude code snippet for RUM Feature Flag integration

content/en/containers/docker/log.md
Docker log collection was missing `DD_SITE` in the installation instructions, this needed updating to notify the reader to change the value from the default if they are not on us1 (i.e. us5).
https://datadoghq.atlassian.net/browse/DOCS-5601
---
=> [DOCS-5601] adding DD_SITE to Docker log collection

content/en/real_user_monitoring/feature_flag_tracking/_index.md, content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
Removes the word "currently" from the Feature Flag Tracking article and guide.
A kind Vale reminder reminded me to remove this language.
---
=> Remove the word "currently" from feature flag docs

content/en/monitors/types/forecasts.md
Adding warning threshold as the list of parameter which can be configured. 
Warning threshold just got added to forecast monitors.
https://docs-staging.datadoghq.com/nils/forecast-and-warning/monitors/types/forecasts/?tab=linear#set-alert-conditions
---
=> Add warning threshold in the forecast monitor

config/_default/menus/menus.en.yaml, content/en/monitors/types/_index.md
Adds the DBM monitor type to the monitor type landing page. Also moves the corresponding article in the left nav.
Request by PM.
---
=> Add DBM monitor type

content/en/profiler/enabling/dotnet.md, content/en/profiler/profile_types.md
Update the exception and lock contention profiler to GA since 2.31
GA Features are implemented
---
=> [dotnet profiler] Exception and lock contention profilers are GA for .NET in 2.31

content/en/network_monitoring/devices/profiles.md, content/fr/network_monitoring/devices/profiles.md, content/ja/network_monitoring/devices/profiles.md
Rename `generic-router` to `generic-device`
We are renaming the profile `generic-router` to `generic-device`. This PR updates the documentation to reflect this change.
Depends on this PR [Rename generic-router to generic-profile](https://github.com/DataDog/integrations-core/pull/14723#top)
---
=> Update documentation to rename generic-router to generic-device

content/en/continuous_integration/intelligent_test_runner/javascript.md
Add instructions for Intelligent Test Runner (ITR) for Cypress.
Allow cypress users to use ITR.
https://docs-staging.datadoghq.com/juan-fernandez/add-itr-cypress-instructions/continuous_integration/intelligent_test_runner/javascript/#cypress-setup
---
=> [ci-visibility] Add reference to ITR for cypress

content/en/serverless/azure_container_apps/_index.md, content/en/serverless/google_cloud_run/_index.md, content/ja/serverless/azure_container_apps/_index.md, content/ja/serverless/google_cloud_run/_index.md
There are two places in the docs where we are trying to point to the Go tab of instrumentation but it instead points to Ruby, this PR fixes those
---
=> Fix links for instrumenting Go tracing

content/en/dashboards/functions/smoothing.md
Replace broken link with a github repo link
[DOCS-5627](https://datadoghq.atlassian.net/browse/DOCS-5627)
Resolves issue <a href="https://github.com/DataDog/documentation/issues/18434">[Smoothing: Broken link to Stanford ASAP algorithm page](https://github.com/DataDog/documentation/issues/18434)</a>
---
[DOCS-5627]: https://datadoghq.atlassian.net/browse/DOCS-5627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Resolves issue #18434, replace broken link

content/en/continuous_integration/troubleshooting.md
Add troubleshooting item to reflect that old timestamps will be discarded. 
Make it easier to customer to find issues.
https://docs-staging.datadoghq.com/juan-fernandez/add-note-about-junit-timestamps/continuous_integration/troubleshooting/#you-are-uploading-junit-test-reports-with-datadog-ci-but-some-or-all-tests-are-missing
---
=> [ci-visibility] Add troubleshooting item about JUnit reports timestamps

content/en/agent/troubleshooting/permissions.md
Adds some more context on what is meant by using visudo. Requested by translators.
=> Add some visudo context for translators

content/en/getting_started/containers/autodiscovery.md
adds a little section to talk about potential delays. 
getting added here because this getting started guide is basically the central hub of autodiscovery related topics
ready to merge
=> DOCS-3979 add note on potential delay in autodiscovery

config/_default/menus/menus.en.yaml, content/en/tracing/trace_collection/otel_instrumentation/nodejs.md, layouts/partials/apm/apm-otel-instrumentation.html
blocked by https://github.com/DataDog/dd-trace-js/pull/2498
What does this PR do?
Adds docs for using OTel with Node.js. Rebranch of https://github.com/DataDog/documentation/pull/18403 
Motivation
The OTel SDK for Node.js is landing soon, this provides docs for it.
=> Add doc for using OTel with Node.js

content/en/account_management/audit_trail/events.md
Added `Login method override` event under `Security Notifications` category in the Audit Trail docs.
---
=> Update audit trail docs to include login method override security notification event

content/en/database_monitoring/setup_postgres/aurora.md, content/en/database_monitoring/setup_postgres/azure.md, content/en/database_monitoring/setup_postgres/gcsql.md, content/en/database_monitoring/setup_postgres/rds.md, content/en/database_monitoring/setup_postgres/selfhosted.md
Addresses a "bug" (unintended behavior) of many `PREPARE` statements aggregating in pg_stat_statements.
---
=> [DBM] Instruct customers to disable track utility

content/en/continuous_integration/pipelines/gitlab.md, content/en/continuous_integration/tests/junit_upload.md
This has been marked as beta for too long so I think it's okay to remove now
---
=> [CIAPP] Remove (beta) note from logs collection for junitxml and gitlab

content/en/tracing/trace_pipeline/ingestion_mechanisms.md
`DD_TRACE_SAMPLING_RULES` is currently not supported in Ruby.
The documentation listed it as such, which could confuse users.
This PR removes the documentation of this feature for Ruby only.
https://docs-staging.datadoghq.com/marco.costa/ruby-DD_TRACE_SAMPLING_RULES/tracing/trace_pipeline/ingestion_mechanisms
---
=> Ruby: Remove doc for unsupported DD_TRACE_SAMPLING_RULES

content/en/monitors/downtimes/_index.md
updated the document by adding an additional line regarding default behaviour for API [MNTS-89814]
---
[MNTS-89814]: https://datadoghq.atlassian.net/browse/MNTS-89814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [doc] Updated manual cancellation behaviour

assets/scripts/components/algolia.js, assets/scripts/components/algolia/getHitData.js, assets/scripts/components/algolia/searchbarHits.js, assets/scripts/components/algolia/searchpageHits.js, local/bin/js/algolia-index-sync.js
- Updates `algolia.js` to use the `api_index` from the config for algolia search if it is an API page
- Updates `algolia-index-sync.js` to correctly apply the `customRanking` value to the replica index
https://datadoghq.atlassian.net/browse/WEB-3732
Preview: https://docs-staging.datadoghq.com/davidweid/update-api-search/
---
=> If api page, use api_index from algolia

assets/styles/pages/_global.scss
enable horizontal scroll on fenced codeblocks (markdown codeblocks)
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3688
all codeblocks with content that was wrapped should now overflow the container. you should be able to horizontally scroll for more content:
- https://docs-staging.datadoghq.com/stefon.simmons/web-3688/containers/amazon_ecs/apm/?tab=ec2metadataendpoint#configure-the-trace-agent-endpoint
- https://docs-staging.datadoghq.com/stefon.simmons/web-3688/account_management/saml/troubleshooting/#roles-errors
- https://docs-staging.datadoghq.com/stefon.simmons/web-3688/security/default_rules/aws-iam-role-trust-policy-misconfigured-github/#remediation
---
=> horizontal scroll on code blocks "```"

content/en/serverless/guide/serverless_package_too_large.md
Adds a workaround for the package too large error
Met with a customer having this issue who wasn't aware this is an option
---
=> [serverless] Add datadog-ci workaround for package too large error

content/en/profiler/enabling/php.md, content/en/tracing/trace_collection/dd_libraries/php.md
With the latest release (`0.88.0`) there is a new dependency that needs to be installed, which customers on Alpine won't have. This PR adds this.
Customers should be able to install the latest and greatest tools
Customer issue: https://github.com/DataDog/dd-trace-php/issues/2109
---
=> Add missing alpine dependencies

config/_default/menus/menus.en.yaml, content/en/serverless/azure_app_services/azure_app_services_container.md, content/en/serverless/azure_app_services/azure_app_services_linux.md, content/en/serverless/azure_app_services/azure_app_services_windows.md
This PR adds a new page Serverless -> Azure App Service -> Container for the containerized azure app service use case. It explains how to instrument and configure your application in order to receive traces, logs, and metrics. So far there are examples for Node.js, python, and go.
The integration was added to the `datadog-agent` in these two PRs:
* https://github.com/DataDog/datadog-agent/pull/17591
* https://github.com/DataDog/datadog-agent/pull/17483
---
=> Add 'Azure App Service - Container' page

content/en/tracing/trace_collection/compatibility/python.md
Adds `snowflake-connector-python` to the list of supported datastores in the Python tracer compatibility list.
@wantsui pointed out an inconsistency between this document and the Python tracer's documentation.
---
=> add table listing for python tracer compatibility with snowflake

content/en/account_management/audit_trail/events.md
Add an entry for restriction policy audit trail events. Reference: https://docs.datadoghq.com/api/latest/restriction-policies/
---
=> Add restriction_policy to audit trail documentation

content/en/integrations/guide/source-code-integration.md
SCI now support Ruby. Update the doc to indicate it.
---
=> [Source Code Integration] Now support ruby

content/en/profiler/profile_types.md, content/en/tracing/trace_collection/library_config/php.md
With the PHP profiler `0.88.0` allocation profiling is GA.
Have up to date docs :-D 
---
=> Add GA PHP allocation profiling version number

content/en/account_management/org_settings/ip_allowlist.md
Adds that it needs user-generated API key, it cannot generate an API key itself under the IP allowlist
https://datadoghq.atlassian.net/browse/ACCESS-1604
Comment from Marketplace/Integration PMs
---
=> Add IP allowlist stipulation about API key access

layouts/shortcodes/api-scopes.html
This PR is bugfixing the api scopes page where due to the logic some of the entries were not coming through
Slack
See users appears now at the bottom
https://docs-staging.datadoghq.com/david.jones/scopes-fix/api/latest/scopes/
---
=> api scopes bugfix

content/en/logs/explorer/search_syntax.md
This PR adds an example to match all logs that do not contain a particular attribute.
I saw someone asking about this particular use case. I knew the answer but it is not in the docs, so I figured it might be good to add it there.
---
=> Add example for log not containing an attribute

content/en/continuous_integration/troubleshooting.md
Documents that GitHub's repo synchronization feature doesn't play well with ITR for now.
---
=> [ci-app] Document fork sync limitation

content/en/continuous_integration/tests/python.md
* Convert agent/agentless instructions to tabs
* Update environment variables to reflect agentless mode
Python CI visibility should use agentless mode when running in cloud CI providers.
---
=> CIAPP-6501 Use agentless mode for Cloud CI python CI visbility

content/en/dashboards/widgets/event_stream.md, content/en/dashboards/widgets/event_timeline.md, content/en/dashboards/widgets/list.md
- Add Event Stream and Event Timeline widget redirect alerts to List and Timeseries respectively.
- Add algolia tag for List for 'event stream'
- Make event stream and timeline pages private for search
[DOCS-5653](https://datadoghq.atlassian.net/browse/DOCS-5653)
---
[DOCS-5653]: https://datadoghq.atlassian.net/browse/DOCS-5653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Redirect event widgets to list or timeseries

content/en/metrics/open_telemetry/otlp_metric_types.md
Update OpenTelemetry hostname resolution section to match the current code behavior: https://github.com/DataDog/opentelemetry-mapping-go/blob/122da4eec9f525d602ca7090e05bd19cd2505509/pkg/otlp/attributes/source.go#L52-L85.
Keep the doc in sync with current code logic.
---
=> [OpenTelemetry] Update hostname resolution

content/en/tracing/guide/instrument_custom_method.md
the second argument for `tracer.trace` is missing the `span` argument which is used to add custom tags.
---
=> fix missing span argument in nodejs instrument example

config/_default/menus/menus.en.yaml, content/en/account_management/billing/_index.md, content/en/account_management/billing/custom_metrics.md, content/en/account_management/multi_organization.md, content/en/account_management/plan_and_usage/usage_details.md, content/en/metrics/_index.md
Moves the Usage Details page to nest under Plan and Usage. Was previously under Billing. Updates the location of the page, adds an alias, and updates incoming links.
Requested by the Revenue Engineering product manager, Katherine Broner. Her reasoning is that Usage Details and the new Cost Details page logically belong together, under Plan and Usage.
Will create a follow-on PR to move the images.
---
=> Move usage details to nest under Plan and Usage

content/en/monitors/types/log.md
Adds a note in the Log monitor documentation to outline the fact that samples are only included in monitor notifications for logs that include a message. 
---
=> Add note for log samples in monitors

assets/styles/pages/_global.scss, layouts/_default/single.html
adds table wrapper to scroll tables on mobile. prevents broken layout on mobile
fix broken layout on mobile
on viewport 365px < 768px you should be able to horizontally scroll tables.
ex: 
- https://docs-staging.datadoghq.com/stefon.simmons/scroll-tables-on-mobile/real_user_monitoring/browser/data_collected/#session-metrics
- http://localhost:1313/logs/log_configuration/attributes_naming_convention/#web-access
---
=> add table wrapper to x-scroll

content/en/logs/log_configuration/archives.md
Be more specific on what type of storage account we support for azure archives.
Standard performance is enough, but in case they specify Premium performance, they also need to select Block blobs for the archive to work.
Feel free to reword as needed 🙂 
---
=> Precision on azure storage account type for external archives

content/en/service_management/workflows/build.md
Adds a note indicating the syntax used for referencing context variables in workflows
I had difficulty accessing a variable within an array because I wasn't sure which syntax to adhere to
---
=> add note regarding syntax

config/_default/menus/menus.en.yaml
Adds a `dashboards` prefix to the Guides identifier. I think having multiple guides identifiers interferes with the left nav menu.
Noticed that the Guides options was missing on the left navigation.
---
=> Specified identifier of the Dashboard guides

content/en/real_user_monitoring/android/data_collected.md, content/en/real_user_monitoring/ios/data_collected.md, content/en/real_user_monitoring/roku/data_collected.md
Add precision on the RUM connectivity attribute as they're not available on *all* the RUM events.
A customer got confused and thought some data was missing.
---
=> Add precision on RUM connectivity attributes

content/en/serverless/aws_lambda/configuration.md
instead of disable logs and disable traces, changed them to enable/disable
jira issue 
---
=> DOCS 5692 - adding two sections to aws lambda config page

content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps the version of Azure App Service LInux
New release of Azure App Service LInux
---
=> Bump AAS Linux version to 1.3.0
