DataDog/documentation

- content/en/developers/marketplace/_index.md
- content/en/observability_pipelines/_index.md
- content/en/tracing/service_catalog/_index.md
> DOCS-5251 adding flags to pages without fed support

- content/en/real_user_monitoring/feature_flag_tracking/_index.md
- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
- layouts/partials/rum/rum-feature-flag-tracking.html
- Fixes a partials issue that caused the Feature Flag Tracking pages to be funky
- Obeys the Gremlins tracker
PM pointed out this issue, as documented in [DOCS-5278](https://datadoghq.atlassian.net/browse/DOCS-5278)
---
[DOCS-5278]: https://datadoghq.atlassian.net/browse/DOCS-5278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix partial issue

- content/en/workflows/_index.md
- content/en/workflows/access.md
- content/en/workflows/actions_catalog/_index.md
- content/en/workflows/build.md
- content/en/workflows/connections.md
- content/en/workflows/trigger.md
- local/etc/algolia/docs_datadoghq.json
Removes the beta labels + callouts and adds Workflows to Algolia
Don't merge til GA
---
> Workflows GA

- content/en/tracing/service_catalog/setup.md
switch order of sections to put the least used section at the bottom
---
> service catalog setup section order

- content/en/tracing/service_catalog/troubleshooting.md
> add FAQ for service catalog

- content/en/integrations/rsyslog.md
- Add separate instructions for US3/US5/AP1/Gov
- Add site-region shortcodes
DOCS-4912
---
> [DOCS-4912] Add site regions to Rsyslogs doc

- layouts/_default/404-baseof.html
- layouts/_default/baseof.html
- layouts/api/baseof.html
- layouts/index.html
Cache headerscripts partial
https://datadoghq.atlassian.net/browse/WEB-3479
General test that js functions still work, dropdowns/tabs/collapsables etc.
https://docs-staging.datadoghq.com/david.jones/cache-headerscripts/
---
> WEB-3479 - cache headerscripts partial

- content/en/logs/log_configuration/online_archives.md
- content/en/security/cloud_siem/guide/automate-the-remediation-of-detected-threats.md
Vale is picking these up as errors.
Good to merge
---
> Fix some style errors

- content/en/agent/guide/dual-shipping.md
update dual shipping endpoints for process, orchestrator, dbm, and ndm not sure what to set for CSPM, CWS, or CI Vis endpoints
---
> update dual shipping endpoints

- layouts/shortcodes/latest-lambda-layer-version.html
Bump datadog-lambda-python layer to version 71
---
> Bump datadog-lambda-python layer to version 71

- content/en/tracing/trace_collection/otel_instrumentation/dotnet.md
This PR adds .NET specific language documentation for custom OpenTelemetry instrumentation.
Adds .NET instructions for the new OTEL custom instrumentation we are supporting
N/A
---
> feat(otel): Update .NET OTEL page with setup instructions

- content/en/account_management/login_methods.md
> editing alt text

- content/en/security/cloud_security_management/_index.md
> adding blog link

- snippets/markdown.json
> Update snippets with region-param

- content/en/tracing/trace_collection/proxy_setup/_index.md
Document dd-opentracing-cpp versions in envoy/istio
having up to date doc
---
> updates on dd-opentracing-cpp versions for envoy/istio

- content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
- content/en/tracing/trace_collection/dd_libraries/dotnet-framework.md
Updates the Powershell command from:
```
RUN Start-Process -Wait msiexec -ArgumentList '/qn /i datadog-apm.msi'
```
to
```
Start-Process -Wait msiexec -ArgumentList '/qn /i datadog-apm.msi'
```
This is because `RUN` is usually used in the context of Dockerfiles, not Powershell.
---
> Update powershell command used in the .NET Framework documentation

- .gitlab-ci.yml
Due to current issues with timeouts in synthetics, we are allowing this job to fail to not block pipelines
---
> Allow synthetics to fail

- content/en/tracing/service_catalog/_index.md
clean up content to reflect the latest UI changes
---
> reflect recent UI changes

- content/en/security/application_security/threats/custom_rules.md
Updates the suppression info.
[DOCS-5244](https://datadoghq.atlassian.net/browse/DOCS-5244)
---
[DOCS-5244]: https://datadoghq.atlassian.net/browse/DOCS-5244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5244] Update suppression queries in ASM Customer Detection Rules doc

- content/en/logs/log_configuration/forwarding_custom_destinations.md
Adds note that Log Forwarding is not available for Gov.
Feature is not available.
---
> Add note to Log Forwarding about US1-FED

- content/en/containers/kubernetes/log.md
Fix the dead link [8] and update the missed Operator snippet for setup with unprivileged mode. 
Above
---
> Update Operator example for unprivileged setup

- content/en/monitors/case_management/_index.md
- content/en/monitors/incident_management/_index.md
- content/en/notebooks/_index.md
- content/en/workflows/_index.md
Adds a [blog link](https://www.datadoghq.com/blog/automate-security-tasks-with-workflows-and-cloud-siem/) to all linked pages.
Tuesday Tasks.
---
> Added blog links

- content/en/logs/explorer/export.md
Updates info
Ready to merge
[DOCS-5307](https://datadoghq.atlassian.net/browse/DOCS-5307), PM request
---
[DOCS-5307]: https://datadoghq.atlassian.net/browse/DOCS-5307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5307] Update CSV info in Export Logs doc

- content/en/continuous_integration/guides/_index.md
- content/en/continuous_integration/guides/ingestion_control.md
- content/en/continuous_integration/pipelines/azure.md
- content/en/continuous_integration/pipelines/buildkite.md
- content/en/continuous_integration/pipelines/circleci.md
- content/en/continuous_integration/pipelines/github.md
- content/en/continuous_integration/pipelines/gitlab.md
- content/en/continuous_integration/pipelines/jenkins.md
- Fix broken section links in our CI provider integration documentation
- Update the title of a docs guide 
- Remove text from a guide that was not supposed to be there
Fixing errors
---
> Fixing broken links & updating wording 

- content/en/cloud_cost_management/_index.md
- Updating links that were redirecting to the wrong places 
- Adding in information about the billing account scope
- Adding cost metrics
- Updating docs to say you don't need to keep storage account in the subscription
---
> Update Azure CCM Docs

- content/en/agent/troubleshooting/windows_containers.md
Update supported Windows version
---
> Update supported Windows version

- content/en/security/cloud_siem/log_detection_rules.md
- Remove line saying Third Party is only available for Guardduty because it is no longer true.
- Clean up links. A lot of links in the main link list aren't being used anymore.
PM request.
---
> Update third party in Cloud SIEM Log Detection doc

- content/en/security/application_security/vulnerability_management/_index.md
Removes beta notes. Ready to merge
Request by PM.
---
> Remove beta notes from ASM Vuln. Management

- content/en/tracing/service_catalog/service_metadata_structure.md
add helpful use cases to schema 2.1
---
> service catalog add helpful use cases

- content/en/security/application_security/vulnerability_management/_index.md
Adds a note that I removed in another PR, deletes a different note.
Conversation with PM.
---
> Application Vuln. Management beta notes

- content/en/continuous_integration/guides/github_gating.md
- content/en/getting_started/monitors/_index.md
- content/en/monitors/_index.md
- content/en/monitors/types/_index.md
Adds a new blog link to the relevant pages.
Tuesday Tasks.
---
> Add blog links to relevant pages

- content/en/data_security/guide/_index.md
- content/en/data_security/guide/tls_cert_chain_of_trust.md
SEE [DOCS-5277](https://datadoghq.atlassian.net/browse/DOCS-5277)
Good to merge
---
[DOCS-5277]: https://datadoghq.atlassian.net/browse/DOCS-5277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (DOCS-5277) Add doc for TLS cert changes

- content/en/logs/log_configuration/processors.md
> fix formatting error string builder

- content/en/agent/faq/agent-downgrade-major.md
- Updates the casing of `agent`
- Minor punctuation update
Noticed while making unrelated changes.
---
> Update Agent casing

- content/en/security/cloud_siem/_index.md
Add link to Google Cloud Config Guide for Cloud SIEM
Ready to merge
Ready to merge
---
> Add link to Google Cloud Config Guide for Cloud SIEM

- .github/CODEOWNERS
- .gitignore
Makes sure all the pages that need rum-mobile and documentation reviews appear as expected.
I undid single-sourcing for four different repositories as part of [DOCS-5210](https://datadoghq.atlassian.net/browse/DOCS-5210), so naturally, a few things got messy.
---
[DOCS-5210]: https://datadoghq.atlassian.net/browse/DOCS-5210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cleanup codeowners and gitignore

- content/en/agent/basic_agent_usage/_index.md
* Adds a link to the Sites documentation which explains the purpose of the `site` parameter and the correct one to use
* Bolds **note** to align with the other **note** on this page and other pages
---
> Adds site documentation + bolds note nit

- content/en/dashboards/widgets/slo.md
Remove the beta banner 
Requested by product team.
---
> Remove the private beta banner

- content/en/real_user_monitoring/android/data_collected.md
- content/en/real_user_monitoring/browser/data_collected.md
- content/en/real_user_monitoring/explorer/search.md
- content/en/real_user_monitoring/guide/compute-apdex-with-rum-data.md
- content/en/real_user_monitoring/guide/tracking-rum-usage-with-usage-attribution-tags.md
- content/en/real_user_monitoring/guide/understanding-the-rum-event-hierarchy.md
- content/en/real_user_monitoring/ios/data_collected.md
> Add application.name facet to documentation

- content/en/security/application_security/threats/protection.md
* Fix a type
* Improve the link setup remote configuration
See dogfooding https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2958264696/24-04-2023+ASM+dogfooding
---
> (asm) Improve remote config instruction for ASM

- content/en/monitors/types/anomaly.md
See the support that originated this here:
https://datadoghq.atlassian.net/browse/DTSS-264
---
> DTSS-264 Fix wrong documentation

- content/en/real_user_monitoring/heatmaps/_index.md
We are updating the configuration of heatmaps and as such, I removed the snippet from the docs
> config-update

- .gitignore
Remove Cloudability from the .gitignore file.
DOCS-5332 -- related PR has been merged:
https://github.com/DataDog/documentation/pull/17843
---
> Remove Cloudability

- content/en/data_streams/_index.md
> small typo in link to image - DSM Docs

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-extension layer to version 42

- content/en/database_monitoring/setup_mysql/aurora.md
- content/en/database_monitoring/setup_mysql/azure.md
- content/en/database_monitoring/setup_mysql/gcsql.md
- content/en/database_monitoring/setup_mysql/rds.md
- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/azure.md
- content/en/database_monitoring/setup_postgres/gcsql.md
- content/en/database_monitoring/setup_postgres/rds.md
- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/gcsql.md
fixes Helm command syntax to correctly balance quotation marks. Confirmed by DBM engineer.
DOCS-5314
---
> DOCS-5314 Correct quotation marks in Helm commands

- content/en/monitors/notify/downtimes.md
revert https://github.com/DataDog/documentation/pull/15508
https://datadoghq.atlassian.net/browse/MNTS-89107?focusedCommentId=795627
> add-downtime-sentence-about-manual-cancels

- content/en/monitors/case_management/_index.md
- Add specific details from each supported product area on how to create/update cases.
- Blog link
[DOCS-5304](https://datadoghq.atlassian.net/browse/DOCS-5304)
---
[DOCS-5304]: https://datadoghq.atlassian.net/browse/DOCS-5304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add more details on how to create cases

- content/en/security/explorer.md
- content/en/workflows/trigger.md
Correct the info, should be you can trigger a workflow for a security signal, and not from.
PM request
---
> Triggering workflow for a security signal

- content/en/real_user_monitoring/_index.md
- Adds a line describing how to navigate to RUM in the UI.
- Updates links to make sure they're all consecutive.
Addressing reader frustration [DOCS-4153](https://datadoghq.atlassian.net/browse/DOCS-4153)
---
[DOCS-4153]: https://datadoghq.atlassian.net/browse/DOCS-4153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Where to access RUM and update links

- content/en/real_user_monitoring/session_replay/privacy_options.md
added an extra clarification for a customer with governance concerns
> masking update

- content/en/tracing/service_catalog/setup.md
add link for terraform resource
---
> service catalog update terraform link

- content/en/logs/log_configuration/forwarding_custom_destinations.md
Removes limited availability note.
GA for all sites except Gov.
---
> [DOCS-5124] Remove limited availability note for log forwarding

- config/_default/menus/menus.en.yaml
- content/en/tracing/trace_collection/otel_instrumentation/go.md
- layouts/partials/apm/apm-otel-instrumentation.html
Adds Go
DOCS-4321 continued
---
> DOCS-4321 Add Go instructions for OTel inst

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Source nested directories in security-monitoring
Slack, to fix issues with
https://docs.datadoghq.com/security/default_rules/#cat-application-security
https://docs-staging.datadoghq.com/david.jones/sec-config-update/security/default_rules/#cat-application-security
---
> Update application security sourcing

- content/en/tracing/trace_collection/library_injection_local.md
Adds error messages and troubleshooting for .NET installation issues so users can correctly set up their library injection.
The feature is going GA soon and if the user follows the setup steps incorrectly, they may fall into some of these issues.
N/A
---
> APM > Library Injection > k8s troubleshooting for .NET

- content/en/getting_started/incident_management/_index.md
> fix typo '3f' to 'of'

- content/en/data_streams/_index.md
Add blog link for Data Streams Monitoring
Tuesday tasks
---
> Add blog link for Data Streams Monitoring

- content/en/logs/log_configuration/rehydrating.md
Log Rehydration is now available in AP1
PM request
---
> Remove note about AP1

- assets/scripts/components/algolia.js
updates docs search rum action
- normalize query (i.e. `toLowerCase()`)
- ignore synthetic runs
- send a clickthrough link (allows us to visualize what links users are clicking in search results)
better understand and visualize user searches
https://docs-staging.datadoghq.com/brian.deutsch/search-analytics/
do a search from the dropdown and from the search page, click one of the links in the results.
[in the rum explorer confirm the rum action was sent](https://dd-corpsite.datadoghq.com/rum/explorer?query=%40type%3Aaction%20%40application.id%3A3493b4e7-ab12-4852-8836-ba96af7bc745%20env%3Apreview%20%40action.name%3AuserSearch%20%40session.type%3Auser&cols=&viz=stream&from_ts=1682863655360&to_ts=1682950055360&live=true)
click into the action in datadog, scroll down to `Custom Attributes` …
> updates search rum action

- content/en/partners/delivering-value.md
- content/fr/partners/delivering-value.md
- content/ja/partners/delivering-value.md
The previous monitoring course has been retired. This links to the new course.
The previous course was retired.
---
> Updates link to new Observability course

- content/en/security/application_security/threats/add-user-info.md
> Fix broken link in ASM docs

- content/en/integrations/guide/collect-sql-server-custom-metrics.md
Adds quotes around the example value for tags. Confirmed with Engineering.
DOCS-5375
---
> DOCS-5375: Add quotes around example value

- content/en/agent/guide/how_remote_config_works.md
Update lib compatibility for ASM features
---
> Update lib compatibility for ASM features

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
Adds a tab in the "Connecting RUM and Traces" documentation for our Roku library
---
> RUMM-3241 Add documentation on connecting traces with RUM Roku

- content/en/real_user_monitoring/roku/_index.md
Fix text referring to advanced section regarding resource tracking. 
---
> Fix text referring to resource tracking in Roku

- content/en/tracing/guide/add_span_md_and_graph_it.md
Updates wording to match correct code example
DOCS-5356 - user feedback
---
> DOCS-5356 - correct intro sentence in php example

- config/_default/menus/menus.en.yaml
- content/en/logs/log_collection/roku.md
- content/en/real_user_monitoring/roku/_index.md
Adds the documentation for Logs collection using Datadog's Roku library
---
> RUMM-3252 Roku logs documentation

- content/en/developers/ide_integrations/vscode/_index.md
Update Setup instruction for the VSCode Extension.
Chat with Vidur on Slack
---
> Setup VSCode Integration Edit

- content/en/cloud_cost_management/_index.md
> Azure GA - remove beta form!

- layouts/partials/grouped-item-listings.html
- layouts/security_rules/single.html
- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config_preview.yaml
Adds beta labels to rules 
https://datadoghq.atlassian.net/browse/WEB-3517
https://docs-staging.datadoghq.com/david.jones/beta/security/default_rules/#cat-workload-security
---
> WEB-3517 - beta labels

- content/en/dashboards/guide/widget_colors.md
Quick fix for a reference link
The link is broken and leads to a 404
---
> Fix reference hyperlink

- content/en/agent/guide/how_remote_config_works.md
Fix a typo
@Moutix and @BouysselCamille requested it
---
> [ASM] Fix Compatability -> Compatibility

- content/en/synthetics/guide/browser-tests-passkeys.md
change "step 2" in  (see section above).
as there are no step 2 in the docs
---
> update passkey doc

- CONTRIBUTING.md
Update link to gobwords style guide
We've migrated lots of stuff into Confluence, so the page this doc currently links to will likely be deprecated soon.
---
> Update link to gobwords style guide

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps lambda extension to v43 to match https://github.com/DataDog/datadog-lambda-extension/releases/tag/v43
---
> Bump datadog-lambda-extension layer to version 43

- content/en/security/application_security/threats/protection.md
> Minor update to passlist section

- content/en/tracing/trace_collection/compatibility/python.md
> update elasticsearch supported versions

- .github/styles/Datadog/headings.yml
This Vale linter rule checks for sentence case in headers and enables exceptions that we define for most product names and SKUs from the Pricing page.
✨ Q2 Docs Hackathon ✨
---
> Adds SKUs to Product Name Capitalization Style Rule

- content/en/database_monitoring/setup_sql_server/azure.md
> [DBM] SDBM-451 Update azure.md for correct azure server name

- content/en/opentelemetry/_index.md
- content/en/real_user_monitoring/feature_flag_tracking/_index.md
- content/en/security/application_security/_index.md
- content/en/tracing/trace_collection/trace_context_propagation/_index.md
Adds published Monitor blog posts links.
Docs Tuesday Tasks, #writing Slack
---
> Add Writing Blog Posts

- content/en/monitors/types/metric.md
Add a note regarding min/max threshold behavior. This information is available in monitor configuration, but not in the metric monitor information.
Resolves https://github.com/DataDog/documentation/pull/18017
[DOCS-5427](https://datadoghq.atlassian.net/browse/DOCS-5427)
---
[DOCS-5427]: https://datadoghq.atlassian.net/browse/DOCS-5427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added note on min/max behavior

- content/en/account_management/guide/usage-attribution-migration.md
- Update the title of [this documentation page](https://docs.datadoghq.com/account_management/guide/usage-attribution-migration/) to remove the usage of v1/v2 to distinguish the affected APIs
- Add a note to the summary clarifying how v1/v2 are used in the document
This document has created some confusion and questions from customers about the use of the terms v1 and v2. In the document the new "v2" APIs are still under the v1 path; `https://api.datadoghq.com/api/v1/usage/monthly-attribution` and `https://api.datadoghq.com/api/v1/usage/hourly-attribution` are considered the v2 APIs for the purpose of the document but they still have `v1` in the path. This disconnect leads to customer confusion.
In the initial draft of this document, we opted to use v1/v2 as the moniker for the respective …
> update title and add sentence to reduce confusion about v1/v2

- content/en/logs/log_collection/php.md
Updates Laravel code.
[DOCS-5414](https://datadoghq.atlassian.net/browse/DOCS-5414)
---
[DOCS-5414]: https://datadoghq.atlassian.net/browse/DOCS-5414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5414] Update Laravel code in PHP log collection doc

- layouts/partials/logs/logs-containers.html
Update link to ECS log collection tile.
[DOCS-5408](https://datadoghq.atlassian.net/browse/DOCS-5408)
---
[DOCS-5408]: https://datadoghq.atlassian.net/browse/DOCS-5408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5408] Update link to ECS log collection tile

- content/en/continuous_integration/tests/junit_upload.md
Update note into a sentence about using the `--metrics` flag and the `DD_METRICS` environment variable. Ready to merge.
DOCS-5405, chat with Bryan on Slack
---
> DOCS-5405 Uploading JUnit test report files to Datadog Edit

- content/en/integrations/guide/source-code-integration.md
Adds a tab for Java with embedding git information instructions. Ready to merge.
DOCS-5442 
---
> DOCS-5442 Source Code Integration Update

- content/en/mobile/_index.md
Removes inactive QR code from Mobile App docs
---
> Remove deactivated QR code

- layouts/shortcodes/latest-lambda-layer-version.html
Bump datadog-lambda-js layer to version 91
---
> Bump datadog-lambda-js layer to version 91

- content/en/account_management/audit_trail/events.md
https://datadoghq.atlassian.net/browse/APPSEC-7028
> [ASM] Update audit log entries

- content/en/glossary/terms/indexed.md
- content/en/monitors/guide/suppress-alert-with-downtimes.md
- content/en/tracing/trace_collection/dd_libraries/android.md
Fix a couple more of these double spaces.
Good to merge.
---
> Double-spacing fixes

- content/en/opentelemetry/guide/otlp_delta_temporality.md
Add .NET instructions on how to produce OTLP delta metrics. JIRA ticket: [OTEL-518](https://datadoghq.atlassian.net/browse/OTEL-518)
.NET example is asked by multiple customers in recent support tickets.
---
[OTEL-518]: https://datadoghq.atlassian.net/browse/OTEL-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> content/en/opentelemetry/guide: add .NET example on delta metrics

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-rb layer to version 19

- layouts/shortcodes/latest-lambda-layer-version.html
Bump latest lambda layer version for Java to 10
---
> Bump latest lambda layer version for Java to 10

- content/en/network_monitoring/performance/network_page.md
> Add CIDR notation to network page

- content/en/monitors/service_level_objectives/metric.md
Add a reference link to the SLO overview page, this include information on how SLO Error budgets are calculated
https://datadoghq.atlassian.net/browse/DOCS-5475
---
> Add reference to SLO overview

- content/en/security/application_security/enabling/compatibility/serverless.md
- content/en/serverless/guide/datadog_forwarder_java.md
- content/en/serverless/installation/java.md
- content/fr/serverless/guide/datadog_forwarder_java.md
- content/fr/serverless/installation/java.md
⚠️ those files need to be changed as well 
- content/ja/security/application_security/enabling/compatibility/serverless.md
- content/ja/serverless/guide/datadog_forwarder_java.md
- content/ja/serverless/installation/java.md
Add support for java17 in the doc
---
> add java 17 support

- content/en/dashboards/guide/slo_graph_query.md
- content/en/glossary/terms/slo.md
- content/en/service_management/service_level_objectives/_index.md
- data/partials/requests.yaml
> Fix some broken links

- content/en/logs/log_configuration/parsing.md
Adds example for parsing TSV.
Clarify note for TSVs.
[DOCS-5463](https://datadoghq.atlassian.net/browse/DOCS-5463)
---
[DOCS-5463]: https://datadoghq.atlassian.net/browse/DOCS-5463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5463] Add TSV parsing example

- content/en/agent/proxy.md
> (rcm) multiple fixes to the RC proxy configuration

- content/en/profiler/enabling/dotnet.md
- content/en/serverless/azure_app_services/azure_app_services_windows.md
> Add setup instruction for .NET profiler on AAS

- content/en/continuous_integration/tests/javascript.md
Add cucumber parallel mode known limitation
Let customers know about this limitation.
https://docs-staging.datadoghq.com/juan-fernandez/add-cucumber-known-limitation/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent
---
> [ci-visibility] Add cucumber parallel mode known limitation

- content/en/containers/docker/_index.md
update the registry order to be aligned with registry preference.
keep documentation up to date
---
> Update docker registry documentation

- content/en/logs/guide/control-sensitive-logs-data.md
Update title with title case.
Docs style
---
> Update Control Sensitive Logs Data with title case

- content/en/integrations/guide/source-code-integration.md
Reverts DataDog/documentation#18070
> Revert "DOCS-5442 Source Code Integration Update"

- content/en/security/explorer.md
> Update instructions for creating a case from Cloud SIEM signal

- content/en/integrations/guide/source-code-integration.md
Tab update. Ready to merge.
DOCS-5495
---
> DOCS-5495 Link in Banner Update

- content/en/containers/guide/_index.md
- content/en/containers/guide/kubernetes_daemonset.md
- content/en/containers/kubernetes/configuration.md
- content/en/containers/kubernetes/installation.md
- content/en/containers/kubernetes/log.md
i'm moving things around because i have nefarious plans (i.e. other parts of this KR)
please review for possible broken links etc., content doesn't need to be reviewed. ready to merge
> DOCS 5348 - containers daemonset refactor

- content/en/account_management/billing/_index.md
add UTC to billing cycle sentence
---
> update billing page

- content/en/containers/kubernetes/integrations.md
> DOCS-5477 - remove outdated link on kubernetes integrations page

- content/en/synthetics/test_coverage/_index.md
Updates the Overview section of the Test Coverage doc page.
DOCS-5502
---
> DOCS-5502 Test Coverage Edit

- content/en/real_user_monitoring/android/advanced_configuration.md
Provides a code example of a ComponentPredicate usage within a tracking strategy.
Align with iOS documentation and provide a usable example to users. 
---
> RUMM-3161 - Add example of ComponentPredicate

- content/en/service_management/incident_management/datadog_clipboard.md
Replace the UI term "toast" with user friendly "popup"
[DOCS-5512](https://datadoghq.atlassian.net/browse/DOCS-5512)
---
[DOCS-5512]: https://datadoghq.atlassian.net/browse/DOCS-5512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replace toast with popup

- content/en/security/cspm/frameworks_and_benchmarks.md
Updates the AWS CIS benchmark version. Ready to merge.
PM request.
---
> Update AWS CIS benchmark version

- content/en/agent/guide/agent-configuration-files.md
Improves search for Agent configuration guide.
---
> Improve search for Agent config

- content/en/security/default_rules/_index.md
Default rules overwhelming some search results
---
> Bump down default_rules rank

- content/en/security/_index.md
Removes an outdated video in the security docs.
Request from Product Marketing.
---
> Remove outdated video

- content/en/real_user_monitoring/error_tracking/reactnative.md
- content/en/real_user_monitoring/reactnative/_index.md
- content/en/real_user_monitoring/reactnative/advanced_configuration.md
- content/en/real_user_monitoring/reactnative/codepush.md
- content/en/real_user_monitoring/reactnative/expo.md
Add a few improvements to the RN docs before un-single sourcing.
Also ports the following PRs that were not merged:
- https://github.com/DataDog/dd-sdk-reactnative/pull/456
- https://github.com/DataDog/dd-sdk-reactnative/pull/458
> DOCS-5291 React Native docs improvements

- content/en/containers/kubernetes/installation.md
> DOCS-5227 - Add site parameter to k8s install docs

- CONTRIBUTING.md
> (DOCS-4650) Update CONTRIBUTING with Vale info

- content/en/profiler/compare_profiles.md
Remove profiling comparison combined view. 
This feature has been removed.
---
> Remove profiling comparison combined view

- content/en/agent/basic_agent_usage/windows.md
Quick typo fix. Good to merge.
---
> Fix typo in product name

- content/en/observability_pipelines/setup.md
- static/resources/yaml/observability_pipelines/quickstart/aws_eks.yaml
- static/resources/yaml/observability_pipelines/quickstart/azure_aks.yaml
- static/resources/yaml/observability_pipelines/quickstart/google_gke.yaml
- static/resources/yaml/observability_pipelines/quickstart/linux.yaml
This PR fixes bugs identified in OBPS-32 and OBPS-33.
> Update the install instructions to use env vars.

- content/en/serverless/azure_app_services/_index.md
> Update AAS Beta/GA Status

- content/en/tracing/service_catalog/_index.md
minor update to rearrange things to make more sense
---
> service catalog sentence sequence

- .gitignore
Fixes dirty working tree after full build.
---
> Adjust .gitignore for new workflows location

- content/en/developers/community/libraries.md
[DOCS-5552](https://datadoghq.atlassian.net/browse/DOCS-5552)
---
[DOCS-5552]: https://datadoghq.atlassian.net/browse/DOCS-5552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (DOCS-5552) Fix broken link

- content/en/agent/guide/windows-agent-ddagent-user.md
Lowercases the words "core" and "trace". Ready to merge.
The inconsistency was pointed out in Transifex.
---
> Fix case-sensitive spelling

- content/en/agent/guide/windows-agent-ddagent-user.md
Fixes group names in the Windows Agent article. Ready to merge.
Inconsistency was pointed out in Transifex.
---
> Fix group names

- content/en/dashboards/guide/version_history.md
- content/en/notebooks/guide/version_history.md
Adds a blog post link for the dashboards and notebooks version history feature.
Tuesday Tasks
---
> Add dashboards and notebooks version history blog post link

- content/en/observability_pipelines/setup.md
Fixes a bug I found in the setup instructions.
---
> Update setup instructions with correct environment vars

- content/en/security/cloud_workload_security/setup.md
Removes an incorrect/outdated line from the CWS Remote Config instructions. Ready to merge.
Discrepancy was noted by an engineer.
---
> Remove incorrect code comment from CWS Remote Config instructions

- content/en/agent/guide/agent-fips-proxy.md
https://docs-staging.datadoghq.com/nicolas.guerguadj/add-fips-faq/agent/guide/agent-fips-proxy/?tab=baremetalvm#faq
---
> Add FAQ to the FIPS proxy page

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 73

- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/azure.md
- content/en/database_monitoring/setup_postgres/gcsql.md
- content/en/database_monitoring/setup_postgres/rds.md
- content/en/database_monitoring/setup_postgres/selfhosted.md
Some customers were confused about where to run the SQL commands in a replicated cluster. This clarifies that the writer is the destination of the commands.
---
> Clarify the postgres documentation to run setup on the primary

- content/en/service_management/workflows/build.md
Fix broken image reference
video led to a 404 
---
> Fix workflows broken image link

- content/en/agent/guide/autodiscovery-management.md
Adding another example to containers include behavior and changed the wording to be more clear.
Didn't want to add too many examples to avoid cluttering the page, but this should be more clear now.
---
> [DOCS-5539] adding more examples to containers include behavior

- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
Fixes two small typos in the DevCycle RUM integration documentation
Noticed similar typos in our integration tile.
> fixes typos in devcycle rum integration

- content/en/database_monitoring/setup_mysql/aurora.md
- content/en/database_monitoring/setup_mysql/azure.md
- content/en/database_monitoring/setup_mysql/gcsql.md
- content/en/database_monitoring/setup_mysql/rds.md
- content/en/database_monitoring/setup_mysql/selfhosted.md
Apply same change as PR#14653(Merged) against the same contents on the different MYSQL docs
Apply the same change which has been merged against the same contents on the different MYSQL docs.
Thanks to this comment > https://github.com/DataDog/integrations-core/pull/14653#issuecomment-1578862362
I've only updated en version.
---
> Apply same change as PR#14653 against same contents on the MySQL docs

- content/en/security/cloud_workload_security/_index.md
- content/en/security/cspm/_index.md
Adds a link to the RBAC permissions article in the CWS and CSPM docs. Ready to merge.
---
> Add links to RBAC permissions article

- content/en/cloud_cost_management/_index.md
> Add Azure Tag Pipelines to CCM docs

- config/_default/menus/menus.en.yaml
Fixes the CSPM side menu (updates the path to the compliance rules article).
Forgot to do this as part of my earlier PR. 
---
> Fix side menu

- content/en/developers/custom_checks/write_agent_check.md
Fixes an indentation issue when the code block is copied.
---
> Fix indentation in code block

- content/en/api/latest/_index.md
- content/en/getting_started/api/_index.md
Update Postman links to point to the latest Postman collection
DOCS-5631
Ready to merge
---
> (DOCS-5631) Update Postman links

- content/en/serverless/azure_app_services/_index.md
Fix several invalid links and add Support list on Windows-Java
Links lead user to wrong site and lack of docs information of Windows-Java
---
> Update Azure_App_Services_index.md to fix several links and add win-java to the support list

- content/en/developers/custom_checks/write_agent_check.md
We got some feedback that the indentation was off in some of the examples in this file. I tested them and fixed up the indentation where necessary. Also fixed a link and cleaned up some language.
Good to merge.
---
> Clean up examples in custom Agent check doc

- content/en/agent/guide/_index.md
- content/en/containers/guide/_index.md
- content/en/containers/guide/ad_identifiers.md
- content/en/containers/guide/auto_conf.md
- content/en/containers/guide/autodiscovery-management.md
- content/en/containers/guide/autodiscovery-with-jmx.md
- content/en/containers/guide/build-container-agent.md
- content/en/containers/guide/changing_container_registry.md
- content/en/containers/guide/compose-and-the-datadog-agent.md
- content/en/containers/guide/container-images-for-docker-environments.md
- content/en/containers/guide/docker-deprecation.md
- content/en/containers/guide/how-to-import-datadog-resources-into-terraform.md
- content/en/containers/guide/kubernetes-cluster-name-detection.md
- content/en/containers/guide/kubernetes-legacy.md
- content/en/containers/guide/operator-advanced.md
- content/en/containers/guide/podman-support-with-docker-integration.md
- content/en/containers/guide/template_variables.md
just moving some agent guides into the containers section where they belong
ready to merge!
> migrating over some guides

- content/en/tracing/service_catalog/troubleshooting.md
> Update service catalog troubleshooting.md

- package.json
- yarn.lock
bumps hugo to the latest version
There are some features in the new hugo version the team is looking to take advantage of
https://docs-staging.datadoghq.com/devin.ford/hugo-version-bump/
Please check multiple pages/areas. Especially areas that have a good amount of Hugo logic to ensure everything is still working as expected.
---
> Bump hugo version to latest

- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
- content/en/real_user_monitoring/reactnative/_index.md
- content/en/real_user_monitoring/reactnative/advanced_configuration.md
Adds documentation for the new features introduced in the React Native SDK version 1.7.0:
- Feature flag evaluation
- Upload frequency parameter
- Batch size parameter
- Background events tracking parameter
The release is not yet out, I will remove the "Do not merge" label once it is ready to be merged :) 
---
> [RUMM-3306] Document react native SDK release 1.7.0

- .github/workflows/code-freeze.yml
Edits the code freeze instructions for clarity.
Discussion with websites team.
> Update code freeze instructions

- content/en/serverless/guide/serverless_tracing_and_bundlers.md
> [serverless] fix typos in Bundlers guide page

- content/en/dashboards/widgets/_index.md
Moved widget around and added new headers to match the UI widgets page
[DOCS-5607](https://datadoghq.atlassian.net/browse/DOCS-5607)
---
[DOCS-5607]: https://datadoghq.atlassian.net/browse/DOCS-5607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Placed widgets under the appropriate header to match UI

- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
> statsig docs

- content/en/logs/explorer/search_syntax.md
> Update search_syntax.md for CIDR

- content/en/tracing/trace_explorer/search.md
writing more detailed alt text, flagged by transifex
> expanded alt text for trace explorer search spans

- content/en/integrations/kubernetes_state_core.md
Fixes docs to reference the correct tag
---
> kubernetes_state_core: update kube_endpoint tag for endpoint metric

- content/en/containers/amazon_ecs/logs.md
just adds a little section with a link to better direct people.
ready to merge.
> DOCS-5651 link to fargate logs from ecs log collection

- .github/workflows/code-freeze.yml
Enables the codefreeze
https://health.aws.amazon.com/health/status
---
> Enable codefreeze due to aws outage

- .github/workflows/code-freeze.yml
Removes the code freeze
Services recovered
---
> Remove freeze

- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
fixes link
Report in slack
---
> Fix link to RC docs

- content/en/containers/guide/kubernetes_daemonset.md
just clarifies some stuff in the daemonset install
ready to merge
> DOCS-4946 update daemonset instructions

- content/en/tracing/trace_collection/trace_context_propagation/cpp.md
- content/en/tracing/trace_collection/trace_context_propagation/dotnet.md
- content/en/tracing/trace_collection/trace_context_propagation/go.md
- content/en/tracing/trace_collection/trace_context_propagation/java.md
- content/en/tracing/trace_collection/trace_context_propagation/nodejs.md
- content/en/tracing/trace_collection/trace_context_propagation/php.md
- content/en/tracing/trace_collection/trace_context_propagation/python.md
- content/en/tracing/trace_collection/trace_context_propagation/ruby.md
Adds links to blog 
Conversation with TEE
---
> Add blog links to each language context propagation page

- assets/styles/_bootstrap-custom.scss
- assets/styles/pages/_global.scss
This reverts commit 06747a2a40826ae471e93e788a73527c97d5187c.
---
> Revert "[WEB-3712] Introduce XXL container width (#18479)"

- content/en/agent/logs/advanced_log_collection.md
for the translators!
ready to merge.
> rephrasing sentence in advanced log collection

- content/en/containers/cluster_agent/admission_controller.md
uses the internal docs to add details to the public docs
ready to merge
> DOCS-4336 update admission controller docs

- content/en/data_streams/_index.md
- content/en/data_streams/python.md
- layouts/partials/data_streams/setup-languages.html
Adds Python in the setup section of the DSM docs
---
> Update DSM docs to include Python

- content/en/agent/guide/dual-shipping.md
Highlight caveats of profiling dual shipping, namely the priorities involving main and additional endpoints.
Clarifying operational details of profiling dual shipping.
---
> [profiling] Dual-shipping notes.

- content/en/network_monitoring/devices/netflow.md
In preparation for the Netflow GA
> Remove beta label in Netflow docs

- content/en/logs/explorer/search_syntax.md
> Examples for CIDR

- content/en/containers/kubernetes/data_collected.md
> DOCS-5347: update kuberetes data collected page with all metrics

- content/en/dashboards/_index.md
- content/en/dashboards/functions/algorithms.md
Making a couple of pages a little easier to find.
---
> Add some search keywords

- content/en/continuous_integration/tests/_index.md
- content/en/continuous_integration/tests/javascript.md
* Remove agentless requirement for test suite level visibility.
* Improve compatibility section for javascript. 
* Show updated information.
* Improve clarity. 
https://docs-staging.datadoghq.com/juan-fernandez/remove-agentless-requirement/continuous_integration/tests/#compatibility
https://docs-staging.datadoghq.com/juan-fernandez/remove-agentless-requirement/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#compatibility
---
> [ci-visibility] Minor updates to ci visibility instructions

- content/en/logs/_index.md
- content/en/logs/log_configuration/attributes_naming_convention.md
- content/en/logs/log_configuration/logs_to_metrics.md
- content/en/monitors/_index.md
- content/en/monitors/types/log.md
Adds the following blog posts to relevant docs:
- https://www.datadoghq.com/blog/aws-recommended-monitors/
- https://www.datadoghq.com/blog/cidr-queries-datadog-log-management/
Ready for merge
Tuesday tasks
---
> Add CIDR queries and preconfigured alerts blog posts

- content/en/account_management/billing/apm_tracing_profiler.md
Cleans up some messy linking on the APM billing page
DOCS-5682
---
> DOCS-5682 Links maintenance

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
- content/en/tracing/trace_collection/compatibility/dotnet-framework.md
- content/en/tracing/trace_collection/dd_libraries/dotnet-core.md
Updates documentation to reflect changes in 2.32.0 tracer release.
2.32.0 tracer release.
---
> [Tracer][.NET] Release 2.32.0

- content/en/dashboards/functions/algorithms.md
- content/en/monitors/types/anomaly.md
Clarify the required amount of data required for the different seasonality
The info header was apparently not clear enough as there was many questions about required history to apply the anomaly algorithm.
---
> Clarify required history for anomaly algorithm

- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
adding information about characters that should not be used in feature flag names
---
> Update to the feature flag set up guide FAQ

- content/en/getting_started/integrations/aws.md
- Adds a link to the dedicated troubleshooting guide for permissions issues
- Removes unused reference links
DOCS-5654
---
> (DOCS-5654) Add link, remove unused links

- content/en/agent/remote_config/_index.md
Adds CWS custom Agent rules private beta to Remote Config article. Ready to merge.
Request by engineering.
---
> Add note for custom Agent rules private beta

- content/fr/tracing/trace_collection/dd_libraries/python.md
it's a very simple 5 characters fix.
> python tracer incorrectly designed "PHP tracer"

- layouts/shortcodes/latest-lambda-layer-version.html
get on par with new dd lambda python release https://github.com/DataDog/datadog-lambda-python/releases/tag/v74
---
> Bump datadog-lambda-python layer to version 74

- layouts/shortcodes/latest-lambda-layer-version.html
update layer version to match
https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.92.0
https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.92.0
---
> Bump datadog-lambda-js layer to version 92

- content/en/agent/logs/_index.md
Updating to correct path based on feedback [here](https://github.com/DataDog/documentation/commit/8a21a79bea328d6376dc48e0ca762422f08d4233)
On Windows, use the path `<DRIVE_LETTER>:\<PATH_LOG_FILE>\<LOG_FILE_NAME>.log`  
- Verified with product owner
- Ok to merge
---
> Update windows path

- content/en/containers/cluster_agent/admission_controller.md
Reverts DataDog/documentation#18523
> Revert "DOCS-4336 update admission controller docs"

- static/resources/yaml/datadog-agent-aks.yaml
- static/resources/yaml/datadog-agent-all-features.yaml
- static/resources/yaml/datadog-agent-apm.yaml
- static/resources/yaml/datadog-agent-logs-apm.yaml
- static/resources/yaml/datadog-agent-logs.yaml
- static/resources/yaml/datadog-agent-npm.yaml
- static/resources/yaml/datadog-agent-vanilla.yaml
- static/resources/yaml/datadog-agent-windows-all-features.yaml
- static/resources/yaml/datadog-agent-windows-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs.yaml
- static/resources/yaml/datadog-agent-windows-vanilla.yaml
This PR aims to update from public helm chart by running  the update script
---
> Update from public helm chart with update script

- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Adding missing grants to Datadog account in the monitored database.
---
> Adding missing grants to Oracle setup

- content/en/developers/community/libraries.md
Add Pulumi provider
request
---
> add Pulumi

- .github/workflows/synthetics.yml
- Updates the synthetic workflow with a sparse checkout to only grab the files we need
Significantly reduces the job time by not pulling anything but the root of the repo into the job
**72.77%** improvement in speed (this can vary a little depending on how long the synthetics tests actually take)
Old Synthetics Run: https://github.com/DataDog/documentation/actions/runs/5359594933 **7min50s**
New Synthetics Run: https://github.com/DataDog/documentation/actions/runs/5359730791 **2min8s**
---
> Update syntehtics workflow

- content/en/serverless/azure_app_services/azure_app_services_windows.md
Fix a typo in spelling DogStatdD to DogStatsD
Translator caught it
---
> Fix typo DogStatdD to DogStatsD

- content/en/continuous_integration/guides/_index.md
Breaks up the list of CI Visibility guides into feature-based lists. Ready to merge.
Chat with Bryan on Slack
---
> CI Visibility Guides Index Page Edits

- .vale.ini
> (DOCS-5731) Ignore shortcodes

- content/en/security/cspm/_index.md
Update the anchor link to the updated header (ln 35)
Brought up by translation team
---
> Update anchor link to updated header

- local/bin/py/build/configurations/pull_config.yaml
> Actual Commit

- content/en/account_management/billing/serverless.md
Adds a clarification on how we define unique lambda functions
Customers are asking for credits because we do not define how we bill for Lambda@edge (e.g. Wurl)
---
> add lambda@edge clarification

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-java layer to version 11

- content/en/containers/guide/autodiscovery-management.md
> DOCS-5750 autodiscovery management guide refresh

- content/en/database_monitoring/setup_oracle/_index.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
We are enhancing the documentation based on the recent experience with customer onboarding:
- exact commands for installing beta builds,
- added link to the Oracle DBM dashboard,
- sample configuration for multiple databases in a single configuration file,
- improve the migration commands and provide more details about migration steps,
- suggest `reported_hostname` usage for RDS.
Enable smoother onboarding experience and reduce support work.
---
> Enhancing Oracle setup documentation

- content/en/account_management/audit_trail/events.md
Reverts DataDog/documentation#18701
> Revert "[CIAPP-6905] Adding CI Visibility audit events."

- content/en/cloud_cost_management/_index.md
Updates instructions for Azure CCM.
DOCS-5699
---
> (DOCS-5699) Azure CCM updates

- content/en/tracing/service_catalog/_index.md
> update-service-catalog-setup to include UI edit option

- local/bin/py/preview-links-template.mako
- local/bin/py/preview_links.py
Oops. This should fix the preview link poster
---
> (main) Fix preview link poster

- content/en/dashboards/guide/powerpacks-best-practices.md
Add blog link for powerpack docs
---
> Add powerpack blog link

- content/en/account_management/login_methods.md
- content/en/account_management/multi_organization.md
- content/en/account_management/saml/_index.md
Makes some small clarifications and updates relating to SAML.
https://datadoghq.atlassian.net/browse/DOCS-5792
https://datadoghq.atlassian.net/browse/DOCS-5698
https://datadoghq.atlassian.net/browse/DOCS-5437
Ready to merge
---
> Clarify SAML instructions

- content/en/integrations/guide/powered-down-azure-vm-on-infrastructure-list.md
- content/en/integrations/guide/powershell-command-to-install-azure-datadog-extension.md
- content/en/logs/guide/azure-logging-guide.md
- content/en/security/cloud_siem/guide/azure-config-guide-for-cloud-siem.md
Update links to the main Azure doc.
DOCS-5393
---
> (DOCS-5393) Update Azure links

- content/en/profiler/enabling/dotnet.md
> Add AAS in profiling enablement summary

- config/_default/params.en.yaml
update announcement banner at the top
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3773
click on banner, make sure it takes you to dash website and the url for that site includes this url param: `utm_campaign=dg-organic-websites-ww-docs-announcement-announcement-registration-202308dash`
https://docs-staging.datadoghq.com/stefon.simmons/dash-23-announcement-banner/
---
> update banner to promote DASH - WEB-3773

- content/en/tracing/services/service_page.md
creates algolia keyword for Service Page
TSEs request
---
> Add search metadata to Service Page

- content/en/profiler/connect_traces_and_profiles.md
> Add endpoint profiling for Java

- assets/scripts/components/async-loading.js
- config/_default/menus/menus.ja.yaml
minor ja fixes
Slack
https://docs-staging.datadoghq.com/david.jones/fix-ja-navigate/ja/monitors/
---
> ja nav fix

- config/_default/menus/menus.ja.yaml
Update ja side menu to avoid drift
Witnessed a link not working well on ja site
https://docs-staging.datadoghq.com/david.jones/menu-up/ja/
---
> ja menu update

- package.json
- yarn.lock
Update rum and logs sdk so its matching corp
Staying up to date
https://docs-staging.datadoghq.com/david.jones/bump-dd/
---
> update rum & logs

- content/en/profiler/enabling/java.md
> Java profiler - specify OpenJDK support

- content/en/tracing/trace_collection/library_config/php.md
This will add the configuration for the timeline feature to the PHP docs.
Document the latest features in the PHP profiler
---
> Add timeline config for PHP

- content/en/containers/guide/cluster_agent_autoscaling_metrics.md
Fix a small typo
Avoid sounding like a pirate 
---
> Fix typo in cluster agent querying

- content/en/watchdog/_index.md
Updates the alt text of a new image
Accessibility
---
> Update main Watchdog image alt text

- content/en/tracing/service_catalog/_index.md
> Update  service catalog default env selection

- content/en/data_streams/_index.md
- content/en/data_streams/nodejs.md
- layouts/partials/data_streams/setup-languages.html
Update DSM docs to include Node tracing support 
---
> [DOCS-5830] update DSM docs to include Node

- content/en/profiler/enabling/java.md
> Clarify what Datadog Java Profiler is

- translate.yaml
> bump translate file

- content/en/synthetics/metrics.md
> add test_run_steps metric

- content/en/real_user_monitoring/reactnative/_index.md
Updates instructions on how to initialize the React Native application.
[DOCS-5587](https://datadoghq.atlassian.net/browse/DOCS-5587)
---
[DOCS-5587]: https://datadoghq.atlassian.net/browse/DOCS-5587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update React Native initialization doc

- content/en/getting_started/containers/datadog_operator.md
just link-adding. ready to merge
> adding more prominent spec link to operator getting started

- content/en/agent/faq/docker-hub.md
- content/en/containers/cluster_agent/_index.md
- content/en/containers/docker/_index.md
- content/en/containers/kubernetes/installation.md
- content/en/developers/dogstatsd/_index.md
- content/en/tracing/trace_collection/library_injection_local.md
> DOCS-5823 - Update docs mentioning docker hub

- content/en/account_management/rbac/_index.md
- content/en/dashboards/_index.md
- content/en/notebooks/_index.md
- content/en/security/detection_rules/_index.md
- content/en/service_management/service_level_objectives/_index.md
This PR updates the RBAC docs to indicate beta availability of user and team principals.
We want interested users to know about the beta availability of user and team principals.
---
> Update RBAC principal type documentation

- content/en/security/cloud_workload_security/_index.md
Remove the beta note for network detections. Ready to merge.
Request from PM.
---
> Remove CWS network detections beta note

- content/en/data_streams/python.md
update the required version for the Python tracer in the DSM page.
Versions 1.15 and earlier do not include the SQS Python integration, as the integration was added to 1.16. 
---
> update version for Python tracer in DSM

- assets/styles/components/_integrations.scss
- layouts/partials/integrations-carousel/integrations-carousel-modal.html
- layouts/partials/integrations-carousel/integrations-carousel.html
updates ids and classes for synthetic tests.
better target elements for [synthetics](https://dd-corpsite.datadoghq.com/synthetics/tests?query=creator%3A%28%22Stefon%20Simmons%22%29%20status%3A%28OK%29%20%5Bintegrations%20carousel%5D&from_ts=1689012753846&to_ts=1689016353846&live=true)
there should be no change to integration carousel or modal functionality
https://docs-staging.datadoghq.com/stefon.simmons/set-valid-id/integrations
ex:
https://docs-staging.datadoghq.com/stefon.simmons/set-valid-id/integrations/1e/
---
> set proper ids and better class names

- content/en/monitors/manage/search.md
- content/en/monitors/manage/status.md
- Add reference alert div to the main monitor search page
- Add specific query filter syntax and examples to monitor status page
[DOCS-5805](https://datadoghq.atlassian.net/browse/DOCS-5805)
---
[DOCS-5805]: https://datadoghq.atlassian.net/browse/DOCS-5805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add more information on group filter query syntax

- content/en/tracing/service_catalog/_index.md
clarify how RUM applications behave with env selector
small clarification on how RUM applications work with environment dropdown
---
> add RUM application environment behavior

- content/en/getting_started/tracing/_index.md
- content/en/tracing/guide/setting_up_APM_with_cpp.md
> Bump deprecated Ubuntu LTS

- content/en/profiler/enabling/ddprof.md
- content/en/profiler/profiler_troubleshooting/ddprof.md
- Adjust the documentation to the v0.13.0 version that we are about to release.
- Remove a static table of the configuraiton as it is better to access it through a link (which is dynamically updated)
- Remove mentions of pid mode as it is currently flawed (we have an open issue relating to this).
Ensure the documentation is consistent with the state of the proifiler.
---
> Native profiler v0.13.0

- content/en/agent/logs/_index.md
- content/en/agent/logs/advanced_log_collection.md
- content/en/agent/logs/log_transport.md
- content/es/agent/logs/advanced_log_collection.md
- content/es/agent/logs/log_transport.md
- content/ja/agent/logs/_index.md
- content/ja/agent/logs/advanced_log_collection.md
- content/ja/agent/logs/log_transport.md
- content/ko/agent/logs/_index.md
- content/ko/agent/logs/advanced_log_collection.md
- content/ko/agent/logs/log_transport.md
Fixing a nit. Good to merge.
---
> (nit) Fix heading and anchors in Agent logs doc

- content/en/account_management/audit_trail/events.md
> Added event for Agent Flare creation

- content/en/continuous_integration/intelligent_test_runner/_index.md
Add an entry for the ITR Java beta page.
Preview; ready to merge.
---
> Update Partial List

- content/en/continuous_testing/_index.md
Updates the wording in one sentence
Pointed out in Hotjar
Ready to merge
---
> Modify wording

- content/en/tracing/service_catalog/setup.md
remove file renaming step
remove the step of renaming YAMLs 
---
> update backstage import instruction

- content/en/continuous_integration/troubleshooting.md
> [ci-visibility] Update troubleshooting

- content/en/continuous_integration/guides/rum_integration.md
Add a note about a requirement for the ci visibility - RUM integration.
Make it clearer that this requires test visibility enabled.
---
> [ci-visibility] Clarify RUM - CI Visibility integration

- content/en/agent/guide/network.md
Mostly folded in the Database Monitoring entry into the same tab as Remote Configuration because both entries are not available for FED.
Doc Review, ready to merge.
---
> DOCS-4806 Network Traffic Edits

- content/en/opentelemetry/_index.md
Add a link to the Further Reading section
Spread awareness of Datadog's ability to monitor runtime metrics from OpenTelemetry-instrumented apps with Datadog APM
---
> Add Further Reading link

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump dd-trace-dotnet layer to version 9

- layouts/partials/support/support.html
Ticket calls for the line to go under the Twitter and Status badge, but that's beyond my knowledge of our HTML classes and I think this looks fine.
Good to merge after review.
---
> Add Support Terms reference

- content/en/tracing/service_catalog/_index.md
- Brought up in the documentation channel
---
> Update the link to correct reference

- .gitignore
Fixes ignore for the static analysis rules
---
> (maint) Fix ignore rules for static analysis

- content/en/real_user_monitoring/guide/_index.md
- content/en/real_user_monitoring/guide/monitor-kiosk-sessions-using-rum.md
Adds a new guide about using Datadog's SDK to monitor kiosk sessions with RUM
[DOCS-5766](https://datadoghq.atlassian.net/browse/DOCS-5766)
Ready to merge following a review by @nhientrandatadog, rum-browser, and rum-mobile
---
[DOCS-5766]: https://datadoghq.atlassian.net/browse/DOCS-5766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> New monitor kiosk sessions using RUM guide

- content/en/cloud_cost_management/_index.md
Update CCM Azure documentation to add that export names must be unique.
From support tickets we are getting: https://datadoghq.atlassian.net/browse/SCCM-67
---
> Update CCM Azure docs to add precision to export names

- content/en/logs/error_tracking/backend.md
- content/ja/logs/error_tracking/backend.md
Fix typo in code-snippet that makes code incorrect
---
> fix ErrorTracking backend go codesnippet typo

- content/en/agent/guide/network.md
Updated the ip-ranges json sample with `remote-configuration`.
I need help with other languages please!
Language versions
Context: https://dd.slack.com/archives/C0131BFQAF4/p1689004539653439
Related PRs
- ip-ranges updates
-- https://github.com/DataDog/cloudops/pull/36272
-- https://github.com/DataDog/cloudops/pull/36276
-- https://github.com/DataDog/cloudops/pull/36277
-- https://github.com/DataDog/cloudops/pull/36274
-- https://github.com/DataDog/cloudops/pull/36273
- API client updates
-- https://github.com/DataDog/datadog-api-spec/pull/2315
---
> [EDGE-2303] Update ip-ranges json with remote-configuration

- content/en/continuous_integration/guides/ingestion_control.md
> Fixing tipo: permissions to permission

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-extension layer to version 45

- content/en/service_management/workflows/access.md
See [DOCS-5901](https://datadoghq.atlassian.net/browse/DOCS-5901)
Good to merge.
[DOCS-5901]: https://datadoghq.atlassian.net/browse/DOCS-5901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5901] Remove Claim ownership from workflow access doc

- content/en/serverless/guide/datadog_forwarder_java.md
- content/en/serverless/guide/datadog_forwarder_node.md
- content/en/serverless/guide/datadog_forwarder_python.md
- content/en/serverless/guide/datadog_forwarder_ruby.md
- content/en/serverless/guide/serverless_package_too_large.md
- content/en/serverless/installation/dotnet.md
- content/en/serverless/installation/go.md
- content/en/serverless/installation/java.md
- content/en/serverless/installation/nodejs.md
- content/en/serverless/installation/python.md
- content/en/serverless/installation/ruby.md
See [DOCS-5842](https://datadoghq.atlassian.net/browse/DOCS-5842)
---
[DOCS-5842]: https://datadoghq.atlassian.net/browse/DOCS-5842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (DOCS-5842) Remove new ARN from ap1 in serverless

- content/en/continuous_integration/guides/_index.md
- content/en/monitors/guide/_index.md
- content/en/monitors/guide/github_gating.md
Migrate into the Alerting Guides section, does not apply to Datadog Quality Gates.
DOCS-5909, ready to merge
---
> DOCS-5909 Gating your GitHub Actions Deployments with Datadog Monitors Guide

- content/en/account_management/audit_trail/events.md
This adds the Workflows events to the Audit Trail doc.
The Workflows product GA'ed in June, and we want to make sure the documentation is up-to-date.
---
> Adds Workflows events to Audit Trail doc

- content/en/tracing/service_catalog/setup.md
Adds blog link to Service Catalog setup docs.
Tuesday Tasks
---
> Add Backstage blog link to Service Catalog

- content/en/continuous_integration/static_analysis/rules/_index.md
Fixes a typo in the CI static analysis docs. 
Tuesday Tasks
---
> Fix typo in CI docs

- content/en/dashboards/_index.md
- content/en/dashboards/sharing.md
- content/en/getting_started/dashboards/_index.md
Update instructions to generate public URL with current UI instructions.
[DOCS-5664](https://datadoghq.atlassian.net/browse/DOCS-5664)
---
[DOCS-5664]: https://datadoghq.atlassian.net/browse/DOCS-5664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update public URL instructions w current UI elements

- content/en/real_user_monitoring/browser/modifying_data_and_context.md
Indicate that views can't be discarded
Support question
---
> [RUM][Browser] Indicate that views can't be discarded

- content/en/service_management/case_management/_index.md
Case Management x Error Tracking integration is live for all Error Tracking products now, not only for Logs. Specifying "for Logs" is not needed anymore.
---
> Adjust Case Management docs for Error Tracking integration GA

- content/en/getting_started/integrations/aws.md
Removes a broken anchor link.
Tuesday Tasks
---
> Update broken anchor link

- config/_default/menus/menus.en.yaml
- content/en/continuous_testing/_index.md
- content/en/continuous_testing/settings/_index.md
- content/en/mobile_app_testing/_index.md
- content/en/mobile_app_testing/mobile_app_tests/_index.md
- content/en/mobile_app_testing/mobile_app_tests/advanced_options.md
- content/en/mobile_app_testing/mobile_app_tests/results.md
- content/en/mobile_app_testing/mobile_app_tests/steps.md
- content/en/mobile_app_testing/settings/_index.md
- content/en/synthetics/settings/_index.md
- data/partials/home.yaml
Make URL `mobile_testing` --> `mobile_app_testing`.
Chat with Mike on Slack, ready to merge.
---
> Update URL for Mobile Application Testing Documentation

- content/en/observability_pipelines/architecture/_index.md
Removes a broken link. (This sentence should've been removed when we published the original update.)
Link is broken.
---
> Remove broken link

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
The docs wrote `Not recommeded` instead of `Not recommended`. 
Fix a typo.
---
> [APM][.NET] Fix typo on the .NET APM Compatibility Docs

- content/en/dashboards/_index.md
Add note about dashboard requirement in order to delete
[DOCS-5917](https://datadoghq.atlassian.net/browse/DOCS-5917)
---
[DOCS-5917]: https://datadoghq.atlassian.net/browse/DOCS-5917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Note about unstarring dashboards to delete

- content/en/continuous_integration/search/_index.md
Accidentally removed this when doing a batch copy + paste.
Chat with Andrii on Slack, ready to merge.
---
> CI Visibility Search and Manage Edit

- content/en/tracing/trace_collection/library_config/python.md
This was originally missed and should be updated.
---
> Update python.md with correct propagation defaults and behavior

- layouts/shortcodes/latest-lambda-layer-version.html
I'm inspired to create this pull request because I just [published this version](https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.95.0)
---
> Bump datadog-lambda-js layer to version 95

- content/en/continuous_integration/explorer/search_syntax.md
- content/en/continuous_integration/pipelines/_index.md
- content/en/continuous_integration/search/_index.md
- content/en/continuous_integration/tests/_index.md
Cleans up anchor links + removed a beta callout.
---
> Test and Pipeline Visibility Documentation Edits

- content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
Add updated link to the Data Security doc page.
Chat with DeForest on Slack, ready to merge.
---
> Sending Events and Logs to Datadog with Amazon EventBridge API Destinations URL Update

- content/en/integrations/guide/_index.md
- content/en/integrations/guide/cloud-foundry-setup.md
Adds an alias for https://github.com/DataDog/documentation/pull/19046.
Broken link checker in GitLab.
---
> Update Guide List + Add Alias in Cloud Foundry Setup Guide

- content/en/continuous_integration/static_analysis/_index.md
Updates the Other section onboarding to use our new static analyzer versus our old one.
Transitioning our suggestions from our old to new static analyzer now.
---
> [STAT-430] update other section

- .gitlab-ci.yml
updates the ref to the updated docker image which includes the go version update to `v1.20`
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3846
built successfully: [build](https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines?page=1&scope=all&ref=stefon.simmons%2Fgo-v1_20-bump)
should be no change:
https://docs-staging.datadoghq.com/stefon.simmons/go-v1_20-bump/
related to: https://github.com/DataDog/websites-images/pull/137
---
> Stefon.simmons/go v1 20 bump

- content/en/continuous_integration/static_analysis/_index.md
Added Gitleaks to the supported SARIF tools list
We've now tested and support Gitleaks SARIF uploads
---
> [STAT-456] add gitleaks to list

- content/en/developers/authorization/oauth2_in_datadog.md
Add a sentence in the banner.
---
> OAuth in Datadog Edit

- content/en/monitors/types/anomaly.md
Add keywords for `anomaly` and `anomaly monitor`.
Chat with Nils on #documentation Slack, ready to merge.
---
> Update Search Result for Anomaly Monitor Documentation

- content/en/logs/log_collection/javascript.md
Fix Browser SDK `createLogger` usage examples
Examples were wrong, customers were confused.
---
> 📝 fix createLogger examples

- content/en/real_user_monitoring/guide/proxy-rum-data.md
add an example for Browser SDK proxies
Customer are often confused on how to use `ddforward` to forge the upstream query.
---
> 📝 add an example for Browser SDK proxies

- content/en/observability_pipelines/setup/splunk.md
> Pre-DASH Fixes to Use Case Onboarding Docs

- content/en/cloud_cost_management/_index.md
Simplify Azure note about multiple accounts in CCM docs
https://datadoghq.atlassian.net/browse/SCCM-67
---
> [CCM docs] Update Azure note about multiple accounts

- content/en/serverless/google_cloud_run/_index.md
> Adding Log:Trace pivot links

- content/en/api/_index.md
- content/en/tracing/metrics/metrics_namespace.md
- content/en/tracing/trace_collection/proxy_setup/_index.md
Improve metadata noticed by PMs. Ready to merge
> add algolia metadata to a few pages

- content/en/getting_started/cloud_siem/_index.md
Updated the "enable Cloud SIEM" link to point to Landing Page instead of Getting Started page
---
> Updating "enable SIEM" link in the Cloud SIEM getting started guide

- content/en/service_management/workflows/actions_catalog/generic_actions.md
> Update generic_actions.md to seperate Logic Actions from Generic actions

- content/en/service_management/workflows/actions_catalog/_index.md
> Update _index.md to seperate logic steps from generic actions.

- content/en/service_management/workflows/actions_catalog/_index.md
- content/en/service_management/workflows/actions_catalog/logic_actions.md
Adds a link and a small edit. 
Good to merge.
---
> (maint) Add link and small edit

- content/en/containers/guide/podman-support-with-docker-integration.md
Clarifies how to run the Agent on Podman both in rootless and rootful mode.
---
> [podman] Clarify usage of rootless vs rootful containers

- content/en/observability_pipelines/setup/datadog.md
- content/en/observability_pipelines/setup/splunk.md
This PR adds instructions for running both Datadog and Splunk use cases under the AWS Terraform module we released.
---
> Terraform instructions for Splunk/Datadog guides.

- content/en/dashboards/_index.md
Add note on the max width of dashboards
[DOCS-5678](https://datadoghq.atlassian.net/browse/DOCS-5678)
---
[DOCS-5678]: https://datadoghq.atlassian.net/browse/DOCS-5678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add a note about the dashboard max width

- content/en/security/infrastructure_vulnerabilities/setup.md
Fixes a broken anchor link.
Link is broken.
---
> Fix broken anchor link

- content/en/security/infrastructure_vulnerabilities/_index.md
Remove screenshot. 
Request from PM.
---
> Remove screenshot

- content/en/database_monitoring/connect_dbm_and_apm.md
Remove beta banner for Connect Database Monitoring and Traces.
https://docs-staging.datadoghq.com/brett0000FF/DOCS-5905/database_monitoring/connect_dbm_and_apm
Merge Tuesday morning. 
---
> [DOCS-5905] Remove beta banner.

- content/en/tracing/service_catalog/scorecards.md
> Remove private messaging / noindex from Service Catalogs

- content/en/agent/guide/agent-fips-proxy.md
Clarifies the language to make it clear that these other forms of communication are not FIPS-encrypted, but otherwise continue to work
Customer feedback.
---
> [agent FIPS] Clarify language about unsupported communication

- config/_default/params.en.yaml
Updates the CTA banner for Dash start 
---
> Update CTA banner

- config/_default/menus/menus.en.yaml
- content/en/tracing/api_catalog/_index.md
- Adds API Catalog to the left nav
- Updates text and link in banner
Discussion with @idangindi14 for DASH
Ready for merge
---
> Add API Catalog to menu and update banner

- content/en/developers/dogstatsd/_index.md
Added example of how to download the package directly from the Nuget CLI instead of just the link.
To match what the other languages have so that the examples are following certain standards. 
---
> Added example of how to download the package using the CLI

- content/en/metrics/_index.md
Removes a redundant sentence and moves it down to a place where it makes sense.
Tuesday Tasks - Transifex translator pointed this out and they are correct.
---
> remove redundancy

- content/en/mobile_app_testing/_index.md
- content/en/mobile_app_testing/mobile_app_tests/_index.md
- content/en/mobile_app_testing/mobile_app_tests/advanced_options.md
- content/en/mobile_app_testing/mobile_app_tests/results.md
- content/en/mobile_app_testing/mobile_app_tests/steps.md
- content/en/mobile_app_testing/settings/_index.md
Update beta banners + add site region specificity.
Chat with Mike on Slack, ready to merge.
---
> [DOCS-5975] Mobile Application Testing Banner Updates

- config/_default/menus/menus.en.yaml
- content/en/tracing/trace_queries/_index.md
Changes beta statement, adds to the left nav
---
> DOCS-5806 Update beta info for trace queries

- content/en/security/cloud_security_management/_index.md
Removes Infra VM section from CSM overview article.
Section was added in a prior PR, but was supposed to be removed in a later one.
---
> Remove Infra VM section

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 78

- content/en/security/infrastructure_vulnerabilities/setup.md
Fixes product names for Threats and Misconfigurations
Changes to CWS and CSPM to Threats and Misconfigurations to match the new product naming conventions.
Bug fix in docs.
---
> Update CSM product names

- content/en/security/identity_risks/_index.md
- content/en/security/infrastructure_vulnerabilities/_index.md
Adds a link to a blog post for CSM.
DOCS-6000
---
> Add CSM blog post link

- content/en/serverless/azure_app_services/_index.md
> Correct Matrix, and link to container docs

- content/en/dashboards/change_overlays/_index.md
> Small working update to beta callout

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-js layer to version 96

- content/en/dashboards/functions/rate.md
Added info on dt() function shared on this ESC: https://datadoghq.atlassian.net/browse/METS-4941?focusedCommentId=1190368
This was asked by customer on this ticket: https://datadog.zendesk.com/agent/tickets/1275329 and the information was confirmed by engineers on this ESC: https://datadoghq.atlassian.net/browse/METS-4941?focusedCommentId=1190368
---
> Added more info on dt() function

- content/en/security/cloud_workload_security/runtime_anomaly_detection.md
- Makes a tiny grammatical fix
- Replaces an apostrophe to appease the almighty Vale linter
[DOCS-6004](https://datadoghq.atlassian.net/browse/DOCS-6004)
---
[DOCS-6004]: https://datadoghq.atlassian.net/browse/DOCS-6004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tiny grammar fix in runtime anomoly detection

- content/en/agent/remote_config/_index.md
> Updated RC doc for enabling RC on agent by default

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-rb layer to version 20

- content/en/serverless/installation/ruby.md
Reverts DataDog/documentation#19080
> Revert "add ruby custom metrics caveat to use lambda forwarder"

- .gitlab-ci.yml
- Bumps the image to the most recent version with some slack notification improvements and bug fixes
Slack notifications were not sending to webhook channels
Websites images PR https://github.com/DataDog/websites-images/pull/140
Pipeline run with this image: https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines/18732238
With the new notification script, there was a bug where the path was being stripped off the URL so the webhooks weren't sending to their respective channels.
This addresses that issue as well as adding the ability to send preview notifications to as many users as you list `user1/user2/user3/branch-name`.
---
> Update image to latest version

- content/en/containers/docker/_index.md
> (DOCS-5966) Add DD_SITE to docker instructions

- content/en/profiler/connect_traces_and_profiles.md
- content/en/profiler/profile_visualizations.md
> Add link to external Profiler/go/timeline blog post

- content/en/tracing/trace_collection/compatibility/java.md
Improves guidance for beta instrumentations and cleans up links
The links that came from `beta` originally were unclear
---
> Improve beta documentation

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
Update out of date from MS
Add a EOL version from MS
Version is out of date now
---
> [APM] Update .NET 5 EOL date

- content/en/infrastructure/containers/kubernetes_resource_utilization.md
> Update Kubernetes resource utilization known limitations

- content/en/account_management/billing/custom_metrics.md
- content/en/account_management/saml/_index.md
- content/en/logs/log_configuration/online_archives.md
- content/en/network_monitoring/devices/_index.md
- content/en/real_user_monitoring/browser/tracking_user_actions.md
- content/en/tracing/trace_collection/opentracing/_index.md
Tested and this should be good to go
See DOCS-6022
---
> (DOCS-6022) Add algolia search terms

- content/en/serverless/step_functions/troubleshooting.md
Add two more points for troubleshooting
> Update stepfunctions troubleshooting doc

- content/en/agent/troubleshooting/send_a_flare.md
- Update Kubernetes Cluster Agent flare command to modern syntax
- Keep documentation updated and concise
---
> Update Cluster Agent Flare Command

- .github/workflows/code-freeze.yml
Enables merge freeze until current incident is over.
---
> Enable merge freeze

- .github/workflows/code-freeze.yml
> Remove merge freeze

- content/en/tracing/guide/inferred-service-opt-in.md
Adds info about steps to take after opting into global default service name 
Request from PM - Ready to merge, got the 👍 from PM.
---
> [DOCS-6065] Service representation migration info

- content/en/continuous_integration/static_analysis/_index.md
Makes some minor updates to mention SAST in our Static Analysis docs since we now support security-oriented rules.
Release of our SAST rules for Python
---
> Update Static Analysis docs wording to mention SAST

- content/en/tracing/troubleshooting/tracer_startup_logs.md
Updates [Tracer Startup Log documentation](https://docs.datadoghq.com/tracing/troubleshooting/tracer_startup_logs/?code-lang=ruby) to account for new [Ruby changes](https://github.com/DataDog/dd-trace-rb/pull/3020)
---
> Update tracer_startup_logs.md for Ruby changes

- content/en/security/cloud_siem/guide/azure-config-guide-for-cloud-siem.md
There's a separate doc for US3 Azure log collection, updating the link to go directly to that page.
Separate new US3 Azure log collection page.
---
> Update link to Azure log docs

- content/en/security/application_security/enabling/compatibility/java.md
Fixing  broken link
Fix broken link.
Accurate documentation, happy customers.
---
> AVM - Update java.md

- content/en/serverless/step_functions/installation.md
minor change to name of CLI
---
> make nit change to call Datadog Serverless CLI --> Datadog CLI

- content/en/profiler/connect_traces_and_profiles.md
A customer asked for more documentation, specifically around stuff like this.
---
> connect_traces_and_profiles: Go timeline tags and facets

- content/en/monitors/types/watchdog.md
> Removing Beta tag for LAD alerts

- content/en/logs/explorer/facets.md
Adds instructions on how to group log facets.
[DOCS-5520](https://datadoghq.atlassian.net/browse/DOCS-5520) Customer request. 
---
[DOCS-5520]: https://datadoghq.atlassian.net/browse/DOCS-5520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5520] Add instructions on how to group log facets

- content/en/agent/guide/network.md
Not sure why this works, so it probably needs some further exploration, but it fixes the issue for now.
---
> (DOCS-6090) Fix links on Agent Network guide

- content/en/opentelemetry/guide/switch_from_processor_to_connector.md
Quick typo fix.
Thought this was already committed in the original PR.
---
> Typo on New Datadog Connector Page

- content/en/tracing/service_catalog/setup.md
specify servicenow as a supported metadata source
---
> add servicenow as a metadata source

- content/en/tracing/services/resource_page.md
add clarification about underlaying data
---
> Update  dependency map navigator

- content/fr/dashboards/widgets/log_stream.md
Updating the French doc with the correct image for now. Alt text still needs to be translated.
---
> Update link to image

- content/en/continuous_integration/intelligent_test_runner/javascript.md
- layouts/shortcodes/ci-itr-agent.md
- layouts/shortcodes/ci-itr-agentless.md
Improve instructions for ITR for javascript. 
Inspired by https://github.com/DataDog/documentation/pull/19245
---
> [ci-visibility] Improve instructions for Intelligent test runner for Javascript

- content/en/observability_pipelines/setup/splunk.md
Adds site region param and a couple of small style edits.
[DOCS-6096](https://datadoghq.atlassian.net/browse/DOCS-6096)
---
[DOCS-6096]: https://datadoghq.atlassian.net/browse/DOCS-6096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6096] Add site region param to Splunk guide for Obs Pipelines

- content/en/observability_pipelines/setup/datadog.md
Adds site region params and also makes a couple of small style edits.
[DOCS-6102](https://datadoghq.atlassian.net/browse/DOCS-6102)
---
[DOCS-6102]: https://datadoghq.atlassian.net/browse/DOCS-6102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6102] Add site region params to Set Up Obs Pipelines in Datadog

- local/bin/py/build/actions/integrations.py
- local/bin/py/build/configurations/pull_config_preview.yaml
See [DOCS-6094](https://datadoghq.atlassian.net/browse/DOCS-6094).
---
[DOCS-6094]: https://datadoghq.atlassian.net/browse/DOCS-6094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (DOCS-6094) Don't build markdown for dev integrations

- .github/workflows/code-freeze.yml
> Lift freeze

- content/en/tracing/services/services_map.md
• Adding a section to highlight the new "Group by" feature where users can group their services by team or application  • Adding information about filtering by incident status
---
> Service Map Documentation Update

- content/en/tracing/trace_collection/library_config/java.md
Adds documentation for the new and preferred Elasticsearch configuration options
The configuration was updated in dd-trace-java
This should be merged after https://github.com/DataDog/dd-trace-java/pull/5771
---
> Separate documentation for Elasticsearch config

- content/en/tracing/trace_collection/library_config/java.md
> Add dd.http.server.route-based-naming

- content/en/logs/explorer/analytics/_index.md
Updating the doc because it's now possible to aggregate log data w/o the need for facets.
[DOCS-6085](https://datadoghq.atlassian.net/browse/DOCS-6085) TEE request.
---
[DOCS-6085]: https://datadoghq.atlassian.net/browse/DOCS-6085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6085] Update aggregation on Log Analytics

- content/en/database_monitoring/connect_dbm_and_apm.md
- content/en/database_monitoring/guide/_index.md
- content/en/database_monitoring/guide/managed_authentication.md
- content/en/database_monitoring/guide/tag_database_statements.md
- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/rds.md
Adds a new guide around managed authentication. So far it only includes IAM, but we recently added support for Azure managed identity auth as well, which will go out in a future agent release. 
---
> Add doc guide for IAM authentication in the postgres agent

- assets/styles/pages/_reference.scss
- layouts/reference/single.html
- remove the "Advanced" code example under the `Schema` tab
- left align `Options` and `Schema` tabs and add space between
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3933
Click on the `Schema` tab
https://docs-staging.datadoghq.com/stefon.simmons/fix-advanced-code-examples/observability_pipelines/reference/sources/
---
> remove duplicate code example ("Advanced") - [WEB-3933]

- content/en/continuous_integration/static_analysis/_index.md
Setting the correct default value for the `ignore-gitignore`
Noticed the wrong default value.
---
> Set the correct default value for `ignore-gitignore` field

- content/en/serverless/installation/dotnet.md
- content/en/serverless/installation/go.md
- content/en/serverless/installation/java.md
- content/en/serverless/installation/nodejs.md
- content/en/serverless/installation/python.md
- content/en/serverless/installation/ruby.md
Add an alpine support message to the container lambda installation instructions
---
> Add Alpine support message to container lambda installation instructions

- layouts/security_rules/list.html
- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config_preview.yaml
updates out-of-the-box (ootb) rule filter categories. 
- updates build time script (**security rules**) to append updated values to `rule_category` front matter on ***security/default_rules*** pgs
- Note: **default_rules** pages pulled from [security_monitoring repo](https://github.com/DataDog/security-monitoring)
build time category changes:
- removes `Cloud Security Management` category
- changes `Posture Management (Cloud)` to `CSM Misconfigurations (Cloud)`
- changes `Posture Management (Infra)` to `CSM Misconfigurations (Infra)`
- changes `Workload Security` to `CSM Threats`
- adds: 
- `CSM Security Issues` - added to **default_rules** pages that include the `dd_rule_type:combination` tag
- tag source: [security issues](https://github.com/DataDog/security-monitoring/tree/main/posture- …
> update ootb rules pg - [WEB-3923]

- content/en/glossary/terms/security_posture_score.md
Updates the glossary definition for security posture score.
Request from PM.
---
> Update posture score definition

- content/en/security/explorer.md
Small update to match what is in the UI. Ready to merge.
---
> Update to escalate investigation

- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/gcsql.md
- content/en/database_monitoring/setup_sql_server/rds.md
- content/en/database_monitoring/setup_sql_server/selfhosted.md
Updates public docs to show that the agent support monitoring sqlserver 2022 
---
> Update public docs for SQL Server 2022 support

- content/en/agent/guide/environment-variables.md
The config to enable the process-agent was changed in https://github.com/DataDog/datadog-agent/pull/10555, so this PR updates the example to the new way.
---
> Update process config enablement example

- content/en/getting_started/site/_index.md
Add a note referencing dual shipping
Docs on-call request
---
> Link to Dual Shipping guide

- content/en/database_monitoring/setup_sql_server/azure.md
Updates a parameter in the public docs to be consistent with the parameter in the `conf.yaml.example` file:
https://github.com/DataDog/integrations-core/blob/master/sqlserver/datadog_checks/sqlserver/data/conf.yaml.example#L358
Pointed out in docs stack overflow
Ready to merge
---
> Update name parameter

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 79

- content/en/tracing/service_catalog/troubleshooting.md
Updating Service Catalog troubleshooting documentation to create new section about monitors as new click action behavior is released
---
> Monitor troubleshooting documentation update

- content/en/security/misconfigurations/frameworks_and_benchmarks.md
Adds new supported CIS Linux frameworks for CSM Misconfigurations.
Request from PM.
---
> Add Linux CIS frameworks

- content/en/logs/log_configuration/indexes.md
This PR adds a couple of lines to describe the new features around index quota warning thresholds and custom reset times.
Release of new features / functionality.
There's also a PR for updating the image for index_quota.png; this will show the latest version of the feature.
---
> Update indexes.md for daily quota doc updates

- content/en/tracing/trace_queries/_index.md
Fix Typo trace queries docs example
---
> fix typo OR operator example

- content/en/synthetics/private_locations/configuration.md
Add a header for top parameters and another header for all parameters. Ready to merge.
DOCS-6092, chat with @HugoPct on Slack
---
> DOCS-6092 Private Locations Configuration Update

- config/_default/menus/menus.en.yaml
- content/en/service_management/workflows/actions_catalog/saved_actions.md
Decided to rename this page. Good to merge
---
> Rename saved actions page

- content/en/tracing/trace_collection/compatibility/java.md
Corrects the wording for the Java Tracer compatibility. 
[#support-apm](https://dd.slack.com/archives/C4WC8C39Q/p1694036048318439)
[Screenshot of convo](https://a.cl.ly/xQuNK2Wd)
---
> [doc]kris.casey/correct wording for Java compatibility

- local/bin/py/build/actions/integrations.py
- local/bin/py/build/configurations/pull_config_preview.yaml
adds comment to integration .md files (pulled files) at build time that indicates what external repo it was sourced from.
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3893
there should be no ui change. check that no integration pages have changed:
https://docs-staging.datadoghq.com/stefon.simmons/comment-source/integrations/
to test: 
- clone repo locally
- checkout this branch (`stefon.simmons/comment-source`)
- run `make start`
- check that `content/en/integrations` files have a comment above the markdown under the frontmatter.
- ex: `` 
---
> comment source repo - [WEB-3893]

- .vale.ini
- content/en/integrations/kubernetes_state_core.md
- local/bin/js/algolia-index-sync.js
Need to test before merging
---
> Add search terms for ksm

- content/en/containers/cluster_agent/admission_controller.md
> DOCS-6088 - add note on variable in Admission Controller docs

- content/en/tracing/trace_collection/_index.md
Revise beta banner wording to
- Give more context.
- Make a stronger statement about this new feature.
- Highlight key value prop.
https://datadoghq.atlassian.net/browse/DOCS-6138
* Feedback from Irene.
* Reviewing heat maps in RUM and Metabase analytics for this content, it appears that users needed more context before diving into the Single Step APM Instrumentation page.
* https://metabase-analytics.us1.prod.dog/dashboard/36736-apm-docs-dashboard?relative_date=past30days
---
> [DOCS-6138] Revise Single Step Instrumentation Beta Banner

- content/en/getting_started/site/_index.md
Fix a link target
Broken link
---
> Site page: fix broken link

- content/en/service_management/workflows/actions_catalog/saved_actions.md
Redirects a broken link from the app
---
> Add redirect to saved actions

- content/en/synthetics/api_tests/http_tests.md
> Add documentation for new HTTP request bodies

- content/en/tracing/trace_collection/compatibility/java.md
Update jetty supported versions
---
> Update java tracer jetty supported versions

- .github/PULL_REQUEST_TEMPLATE.md
Adds a "please merge" checkbox to PR template
---
> Add merge checkbox to PR template

- content/en/monitors/notify/variables.md
Change message -> messages
Saw it [here](https://docs.datadoghq.com/monitors/notify/variables/?tab=is_alert) and then saw the edit button!
> minor: Update variables.md phrasing to be grammatically correct

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-js layer to version 98

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 80

- content/en/serverless/aws_lambda/configuration.md
Update the security threat monitoring setup with the latest changes.
---
> serverless/aws_lambda/configuration: fix appsec setup

- .gitignore
- content/en/agent/guide/_index.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
This reverts commit 9611831c093f0313bb6ffcf0e0d72187f0957f13.
---
> Revert "(DOCS-6120) Add Datadog Ansible collection (#19667)"

- .gitignore
Removes some gitignore rules that are already covered by a wildcard
---
> (maint) Remove rules covered by wildcard

- content/en/agent/logs/advanced_log_collection.md
Move section into the Configuration tab.
[DOCS-6188](https://datadoghq.atlassian.net/browse/DOCS-6188)
---
[DOCS-6188]: https://datadoghq.atlassian.net/browse/DOCS-6188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6188] Move section to Config tab in Advanced Log Collection

- content/en/tracing/trace_collection/dd_libraries/php.md
Fix incorrect reference link.
https://insights.hotjar.com/sites/1021060/feedback/responses/113704?date=last-6-months&url_contains=%2Ftracing%2Ftrace_collection&frid=95142829
---
> [Hotjar] Fix Incorrect Reference Link

- content/en/containers/docker/integrations.md
we no longer have this category
ready to merge
> DOCS-6173 remove line about autodiscovering integrations

- content/en/security/cloud_siem/investigator.md
Add info on Azure Investigator.
[DOCS-5907](https://datadoghq.atlassian.net/browse/DOCS-5907)
---
[DOCS-5907]: https://datadoghq.atlassian.net/browse/DOCS-5907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5607] Add Azure investigator

- content/en/security/application_security/enabling/compatibility/_index.md
Support for PHP was recently released so we can display this to
customer!
> (asm) Add min php version for ASM OSS

- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Small precision about single span sampling
> single span sampling precision

- content/en/tracing/trace_collection/library_injection_local.md
Add some troubleshooting entries for common problems with the Python library injection.
Customer issues.
---
> Add troubleshooting information for common Python issues

- content/en/integrations/guide/powershell-command-to-install-azure-datadog-extension.md
- content/ja/integrations/guide/powershell-command-to-install-azure-datadog-extension.md
changes:
- update linux typeHandlerVersion to 7.0
- agentVersion to latest
- fix powershell command: Set-AzureVMExtension -> Set-AzVMExtension 
https://learn.microsoft.com/en-us/powershell/module/az.compute/set-azvmextension?view=azps-10.3.0
> [azure][azi-1841] update vm extension public facing docs

- content/en/dashboards/_index.md
There is confusion on what high-density will do for dashboard layouts. Add clarification so customer can search for this Toggle option and understand what it will do to their widgets.
[DOCS-6162](https://datadoghq.atlassian.net/browse/DOCS-6162)
https://datadoghq.atlassian.net/browse/DOCS-6162
[DOCS-6162]: https://datadoghq.atlassian.net/browse/DOCS-6162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add clarification on high density mode for dashboards

- content/en/tracing/trace_pipeline/ingestion_controls.md
- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Public Beta of the remote configuration of agent sampling parameters for APM.
> Public Beta Agent remote sampling rates

- content/en/continuous_integration/troubleshooting.md
> [ci-visibility] Update troubleshooting: junitxml time limit

- content/en/service_management/workflows/build.md
- content/en/service_management/workflows/trigger.md
Adds info on publishing workflows. See DOCS-5776.
> (DOCS-5776) Published workflows

- content/en/tracing/services/services_list.md
Deprecation plan is more concrete - DOCS-6197
> DOCS-6197 Services list deprecation notice update

- content/en/security/application_security/vulnerability_management/_index.md
Updates a sentence describing code-level vulnerabilities. Requested by engineering.
> Modify sentence in Vuln. Management docs

- content/en/getting_started/cloud_siem/_index.md
Adding [new blog post](https://www.datadoghq.com/blog/content-packs/) to further reading section on https://docs.datadoghq.com/getting_started/cloud_siem/ for Tuesday tasks.
> Add blog post link to further reading

- content/en/security/cloud_security_management/mute_issues.md
A translator pointed out that we replaced "finding" with "misconfiguration" everywhere except the alt text for an image.
> [Transfifex] Change language in alt text to match rest of page

- content/en/agent/guide/dual-shipping.md
> (DOCS-6233) Make dual-shipping endpoint dynamic

- content/en/integrations/guide/azure-programmatic-management.md
- Clarify that app registration must take place first
- Provide links for app registration
> (DOCS-6148) Clarify app registration

- content/en/security/application_security/enabling/compatibility/php.md
Was updated here: https://github.com/DataDog/documentation/pull/19730 but the per language page was not done
> Add php version support for ASM vuln OSS

- content/en/tracing/other_telemetry/connect_logs_and_traces/_index.md
Adds algolia search terms to make search better.
[DOCS-6175](https://datadoghq.atlassian.net/browse/DOCS-6175)
---
[DOCS-6175]: https://datadoghq.atlassian.net/browse/DOCS-6175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6175] Add algolia frontmatter for Connect Logs and Traces

- content/en/dashboards/widgets/list.md
- content/en/dashboards/widgets/log_stream.md
- content/en/dashboards/widgets/monitor_summary.md
- content/en/dashboards/widgets/note.md
- content/en/dashboards/widgets/pie_chart.md
- Add `widget_type` to front matter
- Condense API copy
- Change api/v1/dashboards to api/latest/dashboards
Part of ongoing widget audit https://datadoghq.atlassian.net/browse/DOCS-4662
> Widget API audit for list through pie chart

- content/en/continuous_integration/tests/_index.md
This PR adds a new `Supported features` table to the `Test Visibility` section.
> [CIVisibility] Test visibility - Supported features table

- content/en/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum.md
We suspect customers might be searching with the keyword Vercel so want to make sure this guide shows up in results for that as well
> Add mention of Vercel to Next.js doc for search visibility

- content/en/agent/guide/agent-configuration-files.md
- content/en/agent/guide/agent-log-files.md
- content/en/agent/guide/agent-status-page.md
- content/en/agent/guide/how-do-i-uninstall-the-agent.md
- content/en/agent/guide/installing-the-agent-on-a-server-with-limited-internet-connectivity.md
- content/en/agent/guide/integration-management.md
- content/en/agent/guide/network.md
- content/en/agent/guide/secrets-management.md
- content/en/agent/guide/windows-agent-ddagent-user.md
- content/en/agent/remote_config/_index.md
See attached ticket. 
I haven't run the Algolia build on this one. I'm fairly confident these search terms will work fine, so for the review, let's just do a quick typo check
> (DOCS-5900) Add search terms to important agent pages

- content/en/database_monitoring/setup_mysql/aurora.md
- content/en/database_monitoring/setup_mysql/azure.md
- content/en/database_monitoring/setup_mysql/rds.md
- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/rds.md
> Update DBM configs to improve telemetry

- .github/workflows/check_cache_values.yml
- local/bin/py/build/configurations/pull_config_preview.yaml
- local/bin/py/check_cache_values.py
Checks pullconfig values to make sure they're set correctly. Annotates the PR with a warning if they're set incorrectly. Notifies a Slack channel if the PR is merged.
I edited the `pullconfig_preview` file to demonstrate the annotation. We should revert the changes to that file before merging.
> (DOCS-6213) Check pullconfig cache values

- content/en/account_management/audit_trail/events.md
> Add query audit events

- content/en/service_management/workflows/build.md
Translators noticed that a period was missing from this sentence on the doc page.
> Build Workflows Edit

- content/en/developers/custom_checks/write_agent_check.md
> (DOCS-6187) Update link

- .github/CODEOWNERS
- .gitignore
- config/_default/menus/menus.en.yaml
- content/en/developers/guide/_index.md
- content/en/developers/guide/legacy.md
- content/en/developers/integrations/_index.md
- content/en/developers/integrations/agent_integration.md
- content/en/developers/integrations/api_integration.md
- content/en/developers/integrations/check_references.md
- content/en/developers/integrations/create-an-integration-dashboard.md
- content/en/developers/integrations/create-an-integration-recommended-monitor.md
- content/en/developers/integrations/create_a_tile.md
- content/en/developers/integrations/log_integration.md
- content/en/developers/integrations/marketplace_offering.md
- content/en/developers/integrations/oauth_for_integrations.md
- content/en/developers/integrations/python.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
See DOCS-6201
The files themselves don't need a review here. They're simply being moved from another repo where we were publishing them before.
One additional change - I'm moving the "Legacy" doc out of the sidenav and into the developer guides section.
> (DOCS-6201) Stop single-sourcing developer integration docs

- content/en/getting_started/cloud_security_management/_index.md
[DOCS-5846](https://datadoghq.atlassian.net/browse/DOCS-5846)
Updating the CSM Getting started page to include Infra VM and CSM Identity risks.
Ok to merge
[DOCS-5846]: https://datadoghq.atlassian.net/browse/DOCS-5846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5846] Updating instructions for Infra VM And CSM Identity Risks to CSM Getting started page

- content/en/continuous_integration/static_analysis/_index.md
Clarification on `unzip` (it's not an app that users need to download) raised by a translator.
> Static Analysis Edit

- config/_default/menus/menus.en.yaml
> Rename Apps to Apps SDK

- layouts/shortcodes/dbm-mysql-agent-config-examples.md
> Make config example more broadly applicable

- content/en/containers/cluster_agent/commands.md
Adds two envvars to cluster agent docs
> [DOCS-6016] update list of cluster agent envvars

- content/en/logs/guide/azure-logging-guide.md
Blob storage is only supported for US1 and EU. See https://github.com/DataDog/documentation/pull/19799.
[DOCS-6245](https://datadoghq.atlassian.net/browse/DOCS-6245)
[DOCS-6245]: https://datadoghq.atlassian.net/browse/DOCS-6245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6245] Add regions to Azure blob storage

- content/en/tracing/other_telemetry/connect_logs_and_traces/ruby.md
Adds sentence about trace remapper. Requested by customer/SE.
[DOCS-6212](https://datadoghq.atlassian.net/browse/DOCS-6212)
[DOCS-6212]: https://datadoghq.atlassian.net/browse/DOCS-6212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6212] Add trace remapper info to Ruby Connect Logs and Traces

- content/en/tracing/service_catalog/scorecards.md
> Minor wording changes in Scorecards docs

- content/en/continuous_integration/static_analysis/rules/_index.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Adds our `docker-best-practices` data to our index pages.
> [STAT] Add docker-best-practices ruleset

- content/en/real_user_monitoring/browser/modifying_data_and_context.md
- content/ko/real_user_monitoring/browser/modifying_data_and_context.md
This is a spelling correction.
> Jamesleatherman rz patch 1

- .github/workflows/code-freeze.yml
Doc code freeze to troubleshoot build
> Docs code freeze

- .github/workflows/code-freeze.yml
> code freeze off

- content/en/logs/explorer/facets.md
Customer request for clarification.
[DOCS-6230](https://datadoghq.atlassian.net/browse/DOCS-6230)
[DOCS-6230]: https://datadoghq.atlassian.net/browse/DOCS-6230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6230] Clarify sentence about facets

- content/en/continuous_integration/tests/dotnet.md
- content/en/serverless/azure_app_services/azure_app_services_windows.md
There are several places in our docs that were not updated to indicate our .NET 7 support. This PR fixes that.
N/A
> APM > .NET > Add .NET 7 support to docs

- content/en/developers/integrations/create-an-integration-recommended-monitor.md
add required hyphenation to 'integration-recommended'
> hyphenate integration-recommended

- content/en/serverless/azure_container_apps/_index.md
- content/en/serverless/google_cloud_run/_index.md
Removes the message about latest using an older version serverless-init.
> Remove beta warning

- content/en/logs/explorer/search_syntax.md
There was some repetition in the docs for logs
> Fix repetition in logs docs

- content/en/data_security/agent.md
> (DOCS-6045) Replace DigiCert fingerprint

- content/en/agent/troubleshooting/send_a_flare.md
- content/en/cloud_cost_management/_index.md
- content/en/network_monitoring/devices/_index.md
- content/en/network_monitoring/devices/data.md
- content/en/network_monitoring/devices/netflow.md
- content/en/network_monitoring/devices/network_topology_map.md
- content/en/network_monitoring/devices/profiles.md
- content/en/network_monitoring/devices/snmp_metrics.md
- content/en/network_monitoring/devices/snmp_traps.md
- content/en/network_monitoring/devices/troubleshooting.md
- content/en/service_management/events/_index.md
- content/en/universal_service_monitoring/_index.md
Adds site-specific shortcodes and messaging for infra/platform features that are not available across all sites.
> DOCS-5740 site messaging for infra/platform docs

- content/en/monitors/configuration/_index.md
Adds clarification on the minimum length of time you can set for group retention time.
[DOCS-6260](https://datadoghq.atlassian.net/browse/DOCS-6260)
[DOCS-6260]: https://datadoghq.atlassian.net/browse/DOCS-6260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add a minimum group retention time

- content/en/database_monitoring/setup_oracle/selfhosted.md
Remove the references to CDB databases in the non-CDB setup.
> Oracle non-cdb corrections

- content/en/agent/guide/use-community-integrations.md
- content/en/developers/custom_checks/_index.md
- content/en/developers/integrations/create-an-integration-dashboard.md
- content/en/developers/integrations/create-an-integration-recommended-monitor.md
- content/en/developers/integrations/create_a_tile.md
- content/en/developers/write_agent_check.md
- content/en/getting_started/integrations/_index.md
- content/en/integrations/guide/requests.md
- content/en/network_monitoring/devices/snmp_traps.md
Fixing some links to a doc that was renamed.
> (maint) Fix links to agent integration doc

- content/en/continuous_integration/static_analysis/_index.md
- content/en/continuous_integration/static_analysis/rules/_index.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
This PR adds documentation for all our new JS/TS rulesets and their rules.
- new rulesets were added, so I've added them to the pull-config files
- updated frontmatter and the body sections of our rules index page
- added language headings to group rulesets better
- updated the beta banner to include all current supported languages
> [STAT] Update Static Analysis docs

- content/en/tracing/service_catalog/setup.md
> Update Service Catalog Setup

- content/en/service_management/incident_management/incident_settings.md
PM notified that this feature is no longer in beta. Requested the removal of the alert
> Remove beta alert

- content/en/continuous_integration/static_analysis/rules/_index.md
> Static Analysis Rules Header Update

- content/en/developers/dogstatsd/_index.md
> (DOCS-5944) Link to NodeJS integration from DogStatsD

- content/en/sensitive_data_scanner.md
Adds instructions on how to redact sensitive information in tag.
[DOCS-6263](https://datadoghq.atlassian.net/browse/DOCS-6263)
[DOCS-6263]: https://datadoghq.atlassian.net/browse/DOCS-6263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6263] Add instructions on redacting sensitive data in tags

- content/en/account_management/audit_trail/_index.md
> Add export csv docs

- content/en/security/misconfigurations/frameworks_and_benchmarks.md
Add new supported NIST frameworks to CSM Misconfigurations.
> Add NIST frameworks

- content/en/integrations/_index.md
> Add Integrations Extras + Marketplace Aliases

- content/en/logs/log_configuration/parsing.md
Add data matcher example for log parsing.
[DOCS-6208](https://datadoghq.atlassian.net/browse/DOCS-6208)
[DOCS-6208]: https://datadoghq.atlassian.net/browse/DOCS-6208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6208] Add data matcher example

- content/en/serverless/azure_app_services/azure_app_services_container.md
Updating Trace configuration link to https://docs.datadoghq.com/tracing/trace_collection/library_config/, to reflect moved doc.
> Correct Advanced Configuration link

- .gitlab-ci.yml
This updates the docs image to a new version which includes cue-lang cli.
As this currently isn't in use anywhere, it should cause no changes to the site.
> update image to include cue-lang

- content/en/dynamic_instrumentation/_index.md
Add a disclaimer about the potential risk of unintentional leak of PII and secrets when using Dynamic Instrumentation.
- [- ] Please merge after reviewing
This wording was already reviewed by Assistant General Counsel on the Privacy team.
> Update Dynamic Instrumentation docs to explain risk of PII

- content/en/profiler/connect_traces_and_profiles.md
> Profiler - Add a link to Richard's blog post about Java wall clock/timeline

- content/en/account_management/scim/_index.md
> add mention to enterprise tier

- content/en/observability_pipelines/architecture/_index.md
- content/en/observability_pipelines/architecture/advanced_configurations.md
- content/en/observability_pipelines/architecture/availability_disaster_recovery.md
- content/en/observability_pipelines/architecture/capacity_planning_scaling.md
- content/en/observability_pipelines/architecture/networking.md
- content/en/observability_pipelines/architecture/optimize.md
- content/en/observability_pipelines/architecture/preventing_data_loss.md
Add production-level deployment note
[DOCS-6264](https://datadoghq.atlassian.net/browse/DOCS-6264)
[DOCS-6264]: https://datadoghq.atlassian.net/browse/DOCS-6264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6264] Add production-level deployment note

- content/en/containers/amazon_ecs/data_collected.md
Add instructions to collect ECS container insights metrics
There is an additional step needed to collect ECS container insights metrics.
> Update ECS data_collected.md

- static/resources/xml/Datadog-SNow_Update_Set_v2.4.0.xml
> Add new update set for use in documentation

- content/en/logs/log_configuration/parsing.md
Update the data matcher parsing example
> [DOCS-6208] Update data matcher parsing example

- content/en/developers/_index.md
- content/en/developers/community/_index.md
- content/en/developers/community/office_hours.md
- content/en/security/cloud_security_management/_index.md
- content/en/security/cloud_siem/_index.md
- content/en/security/explorer.md
> (TT) Blog links

- content/en/database_monitoring/guide/_index.md
- content/en/database_monitoring/guide/pg15_upgrade.md
- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_postgres/rds.md
- content/en/database_monitoring/setup_postgres/selfhosted.md
Adds DBM setup instructions for PG 15. There are a couple of new steps that depend on both the PG and agent versions, so adding them in the appropriate places.
> Add instructions for PG15.

- content/en/continuous_integration/intelligent_test_runner/python.md
- content/en/standard-attributes/_index.md
Some feedback from our translators
> Feedback from translators

- content/en/tracing/troubleshooting/tracer_startup_logs.md
https://datadoghq.atlassian.net/browse/DOCS-6278
- `dotnet-tracer-managed-{processName}-{timestamp}.log` includes processName and timestamp variables.
- Add variables to `dotnet-tracer-native.log` for consistency.
> [DOCS-6278] Update Tracer Startup Logs logfile name

- content/en/tracing/trace_collection/library_injection_local.md
https://datadoghq.atlassian.net/browse/DOCS-5794
Updates [annotate your pods for library injection](https://docs.datadoghq.com/tracing/trace_collection/library_injection_local/?tab=kubernetes#step-2---annotate-your-pods-for-library-injection) section.
- Add **Container annotation** column with the new annotations.
- Add note about required Agent version below the table.
- Fix a few small errors I noticed in this section unrelated to the main change.
> [DOCS-5794] Document container-specific annotations for local library injection

- content/en/database_monitoring/guide/pg15_upgrade.md
Add a necessary setup step to the PG 15 guide.
> Also add permission change.

- config/_default/menus/menus.ja.yaml
We have `metrics` and `メトリクス` as nav items we should just have one
https://docs-staging.datadoghq.com/david.jones/fix-metric-api-menu/ja/api/latest/
> Fix metric api menu items

- content/en/tracing/trace_collection/single-step-apm.md
Documents new DD_ENV option for single step APM instrumentation.
You can see details about how this works for remote config here: https://app.datadoghq.com/account/settings/agent/latest?platform=ubuntu.
> Document DD_ENV Option for Single Step APM

- content/en/service_management/workflows/access.md
> Update access for WF granular RBAC.md

- content/en/continuous_integration/pipelines/azure.md
Confirmed with Kassen that ADS is not supported.
> Add Not Supported Banner

- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config_preview.yaml
1. updates security rules logic so a rule cannot have two of these rule categories: 
- `csm-misconfigurations-cloud` , `csm-security-issues` or `csm-identity-risks` 
2. adds source comment to security default rule `.md` files
https://datadoghq.atlassian.net/browse/WEB-4062
preview -> https://docs-staging.datadoghq.com/stefon.simmons/exclude-csm-misconfig-cloud-rule/security/default_rules/
- copy the “**AWS IAM role has a large permissions gap**” rule in the search and ensure it shows for `csm identity risks` rule filtering only.
- You may also check that the `NodeList` for these three queries are empty when you run them in the browser dev console:
- `document.querySelectorAll('.cat-csm-misconfigurations-cloud.cat-csm-identity-risks')`
- …
> update ootb rules filtering - [WEB-4062]

- content/en/continuous_integration/static_analysis/_index.md
Fixes a mistake where quotations should be used in the example YAML File in the Static Analysis docs
> Add Missing Quotations

- content/en/continuous_integration/pipelines/buildkite.md
We support infra metrics correlation for buildkite, so I am adding it to the docs
> [CIAPP-7980] Add infra metrics correlation for Buildkite

- content/en/tracing/trace_collection/compatibility/java.md
Updates supported version table to include Java 21.
> Add Java 21 support

- content/en/logs/log_configuration/indexes.md
Add info that user has to update the retention period.
[DOCS-6336](https://datadoghq.atlassian.net/browse/DOCS-6336)
[DOCS-6336]: https://datadoghq.atlassian.net/browse/DOCS-6336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6336] Add info on updating log retention

- .github/CODEOWNERS
Connecting the dots on who is requested on reviews when updates to these doc pages are made.
> Add Some Engineering Teams to CODEOWNERS

- content/en/data_streams/_index.md
- content/en/data_streams/python.md
Update DSM docs specifically with new technologies supported with Python
> Update DSM setup docs

- content/en/security/application_security/vulnerability_management/_index.md
Similar to  [PR 20079](https://github.com/DataDog/documentation/pull/20079) this PR updates the Application Vulnerability Management landing page, re-using some updated screenshots from the AVM getting started guide, and adding verbiage on new functionality.
> [DOCS-6383] updating AVM landing page

- content/en/profiler/connect_traces_and_profiles.md
- content/en/profiler/profile_visualizations.md
> Add Ruby profiler timeline beta

- content/en/logs/log_configuration/archives.md
Adds note about Azure firewall rules.
[DOCS-6305](https://datadoghq.atlassian.net/browse/DOCS-6305)
[DOCS-6305]: https://datadoghq.atlassian.net/browse/DOCS-6305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6305] Add note about Azure firewall rules note for US3 log archive

- config/_default/menus/menus.ko.yaml
- i18n/ko.json
I've adjusted these in Transifex as well, but the file is pretty far from completion, so fixing them here as well in the short term.
> (DOCS-6330) Adjust some Korean strings

- content/en/security/cloud_security_management/workflows.md
found that customers where confused by the security issues example - going back to findings there for the time being
> update workflows examples

- content/en/security/cloud_security_management/setup/csm_enterprise.md
- content/en/security/cloud_security_management/setup/csm_workload_security.md
Add missing instructions to set the proper permissions for the configuration files.
> [CSM] add missing instructions

- content/en/profiler/profile_visualizations.md
> Clarify profiling timeline view entrypoints

- content/en/tracing/guide/_index.md
- content/en/tracing/guide/setting_up_apm_with_kubernetes_service.md
Add a new guide doc for connectivity from Datadog Tracer to Datadog Agent through a Kubernetes Service. The steps are strictly for Helm and Operator, although a sample for the Service for anyone wanting to configure this manually is provided.
Gives the options to use Helm/Operator for the core Agent setup, as well as Admission Controller vs Manual for the APM side.
https://datadoghq.atlassian.net/browse/DOCS-5798
We reference the `service` configuration mode in Admission Controller, but don't really leave a lot of context as to what that is. Adding this to provide that context for the Admission Controller.
This option is also going to be the desired way for environments that can't use the Unix Domain Socket (UDS) or Host Port option - such as EKS Windows environment. So creating this to …
> [DOCS-6149] Add doc for APM instrumented against Kubernetes Service

- content/en/opentelemetry/_index.md
- content/en/opentelemetry/otel_collector_datadog_exporter.md
- content/en/opentelemetry/otlp_ingest_in_the_agent.md
https://datadoghq.atlassian.net/browse/OTEL-969
https://datadoghq.atlassian.net/browse/DOCS-6391
Add instructions on OTLP logs ingestion on the Datadog Agent.
> [opentelemetry][OTEL-969] Add instructions on OTLP logs ingestion

- content/en/profiler/profile_visualizations.md
> Add Richard's blogpost in another timeline place

- content/en/watchdog/alerts/_index.md
Update watchdog alert status facets documentation
> Update alert status for watchdog

- content/en/profiler/enabling/java.md
Conversation with PM and support
> Add note about JDK 11+ requirement for heap and allocation profiles

- content/en/dashboards/widgets/powerpack.md
- Add the widget fields table for powerpack widget
> Add shortcode for the powerpack api shortcode

- content/en/synthetics/multistep.md
Same request body options as the ones in [HTTP Tests](https://docs.datadoghq.com/synthetics/api_tests/http_tests?tab=requestbody).
> Add Some Request Body Types

- content/en/profiler/profile_types.md
> (missed a spot) Java profiler allocation data min JDK version

- content/en/tracing/service_catalog/scorecards.md
> DOCS-6277 Custom scorecards and reports

- content/en/monitors/types/slo.md
- Customers want to create SLO alerts for Synthetic monitors based SLO, but this is not supported.
- https://datadog.stackenterprise.co/questions/7702
> Add alert div for SLO alert limitations

- content/en/tracing/trace_collection/dd_libraries/java.md
https://datadoghq.atlassian.net/browse/DOCS-6338
* User asked about required modules to enable profiling.
* We don't want to provide a list, as this would require a lot of maintenance.
* As a middle ground approach, I added a note that says users can use `jdeps` if they really need to, but this should be done at their own risk.
> [DOCS-6338] Clarify required JVM modules.

- content/en/real_user_monitoring/browser/monitoring_page_performance.md
Revert the documentation about the INP core web vital  (cf: [PR](https://github.com/DataDog/documentation/pull/19983)) since it's not collected yet.
> Revert "Add INP to RUM browser monitoring page (#19983)"

- content/en/continuous_integration/pipelines/gitlab.md
Add a docs link to the Logs Processors doc, in-app links to the Pipeline Setup page.
Chat with Kassen on #support-ci-visibility in Slack.
> GitLab Pipelines Edit

- content/en/account_management/billing/usage_attribution.md
Update list of supported products
> Update list of supported Products

- content/en/real_user_monitoring/heatmaps/_index.md
> Add new blog link

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
- content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Documents that `AWSSDK.DynamoDBv2` package is now available for automatic instrumentation.
> [tracer][dotnet] add `Amazon DynamoDB` integration to docs 

- config/_default/menus/menus.en.yaml
- content/en/logs/log_configuration/flex_logs.md
Make Flex Logs doc public. PM request.
[DOCS-6414](https://datadoghq.atlassian.net/browse/DOCS-6414)
[DOCS-6415]: https://datadoghq.atlassian.net/browse/DOCS-6415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-6414]: https://datadoghq.atlassian.net/browse/DOCS-6414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6414] Make Flex Logs doc public

- content/en/opentelemetry/otlp_ingest_in_the_agent.md
PM wording discussion in slack
> Refine messaging about OTLP ingest in Agent and DD Features

- content/en/cloud_cost_management/azure.md
In the azure setup guide there is a broken link - we want to fix that.
after the fix
> [CCV] fix azure link

- content/en/continuous_integration/search/_index.md
Flips order of Tests and Pipelines, nest every section under the tabs.
> DOCS-6358 Search and Manage CI Pipelines and Tests Edit

- content/en/integrations/guide/_index.md
- content/en/integrations/guide/mongo-custom-query-collection.md
Clarifies the "Datadog-Mongo integration" is the MongoDB integration name, add the `database` option, and consistency nits. 
[DOCS-6384](https://datadoghq.atlassian.net/browse/DOCS-6384)
[DOCS-6384]: https://datadoghq.atlassian.net/browse/DOCS-6384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOCS-6384 MongoDB Custom Metrics Guide Update

- content/en/security/misconfigurations/signals_explorer.md
Resizes screenshots in the CSM Misconfigurations Signal Explorer article.
> Resize CSM screenshots

- content/en/developers/integrations/agent_integration.md
- content/en/developers/integrations/api_integration.md
Adds a section to integration documentation on how to update your integration and bump the integration version if desired.
> Adding info on updating integrations

- content/ja/integrations/steadybit.md
- content/ja/integrations/steadybit_steadybit.md
> Update outdated steadybit urls

- content/en/coscreen/_index.md
- content/en/coscreen/troubleshooting.md
Updates CoScreen docs in accordance with capabilities.
- you can sign in with your Datadog account
- background blurring on macOS
- noise suppression
Also added info from a coscreen support article, [Why does the audio quality degrade...](https://support.coscreen.co/hc/en-us/articles/1500002060342-Why-does-the-audio-quality-degrade-when-using-the-microphone-of-my-Bluetooth-headset-as-input-in-CoScreen-Zoom-and-other-tools-) to the troubleshooting page.
> coscreen docs updates

- content/en/continuous_integration/pipelines/_index.md
Add a terminology table that explains what Datadog CI pipelines are compared to those in external providers.
Chat with Kassen on Slack, already approved.
> DOCS-6359 Pipeline Visibility Update

- content/en/developers/integrations/create-an-integration-recommended-monitor.md
Add a link to the marketplace repo
> Update rec monitor doc

- content/en/observability_pipelines/setup/datadog.md
- content/en/observability_pipelines/setup/splunk.md
- static/resources/yaml/observability_pipelines/cloudformation/datadog.yaml
- static/resources/yaml/observability_pipelines/cloudformation/splunk.yaml
I've created CloudFormation templates for running OPW; these docs detail how customers should use them. They also include a warning that these should **not** be used for production deployments, as there is a crucial lack of durability that needs to be addressed.
> Add steps for using CloudFormation to the quickstart guides.

- content/en/observability_pipelines/setup/_index.md
Make the phrasing more concise.
> Update wording for recommendations in OP setup doc

- content/en/bits_ai/_index.md
- content/en/bits_ai/getting_started.md
- content/en/bits_ai/managing_incidents.md
- content/en/bits_ai/query_examples.md
Updates a beta signup form link for Bits AI.
> Fix outdated Google form link

- content/en/cloud_cost_management/azure.md
> Add backfill information for Azure CCM

- content/en/continuous_integration/static_analysis/rules/_index.md
Updates the wording of a ruleset description
> update ruleset wording

- content/en/continuous_integration/pipelines/_index.md
> Missed One

- content/en/continuous_integration/intelligent_test_runner/_index.md
Make it easier to discover tracked files feature. 
Preview: https://docs-staging.datadoghq.com/juan-fernandez/organize-tracked-files/continuous_integration/intelligent_test_runner/#configuration
> [ci-visibility] Separate excluded branches and tracked files into different sections

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
> Fix build 2: Return of the fixed build

- content/en/continuous_integration/intelligent_test_runner/setup/javascript.md
This PR adds instructions and examples on how to use the unskippable feature of CI Visibility's intelligent test runner. This will allow users to more safely use ITR.
Preview: https://docs-staging.datadoghq.com/juan-fernandez/unskippable-tests-js/continuous_integration/intelligent_test_runner/setup/javascript/?tab=onpremisesciproviderdatadogagent#disabling-skipping-for-specific-tests
> [ci-visibility] Intelligent test runner's unskippable tests for Javascript

- content/en/logs/error_tracking/backend.md
Tests showed the code-snippet is wrong
> [Error-Tracking]: fix go instructions

- content/en/observability_pipelines/troubleshooting.md
Adds a futher reading link to the new OP monitoring doc
> Add link to OP monitoring

- content/en/real_user_monitoring/guide/_index.md
- content/en/real_user_monitoring/guide/mobile-sdk-multi-instance.md
- content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md
Adds 2 Mobile SDK guides in RUM. 
- Upgrading SDK versions (from v1 to v2)
- Using multiple instances of the SDK
Some of the links aren't being generated correctly, I'm not sure why. 
Big tables are also not adapting well to small size of the "main text column". Do you have any suggestions on reformatting?
> Add Mobile SDK Guides

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-js layer to version 99

- content/en/real_user_monitoring/guide/_index.md
- content/en/real_user_monitoring/guide/mobile-sdk-multi-instance.md
Small fixes to two guide titles.
> Fix page titles

- content/en/real_user_monitoring/guide/mobile-sdk-multi-instance.md
Very small fix to change the case of the page title.
> Fix page title case

- content/en/continuous_integration/search/_index.md
Add Teams integration to Search & Manage page
> DOCS-6468 Add teams integration to Search & Manage page

- content/en/data_security/real_user_monitoring.md
DOCS-6461, add client token best practices to the security guide.
> Add security verbiage for client token

- config/_default/menus/menus.en.yaml
- content/en/account_management/teams.md
- content/en/tracing/service_catalog/adding_metadata.md
- content/en/tracing/service_catalog/setup.md
https://datadoghq.atlassian.net/browse/DOCS-6446
This is a reorg, no new content -- check links, redirects, and heading structure
> [DOCS-6446] Update Service Catalog setup section

- content/en/service_management/workflows/build.md
> Add blueprints link to workflow doc

- content/en/real_user_monitoring/session_replay/playlists.md
https://www.datadoghq.com/blog/datadog-rum-session-replay-playlists/
Add this new blog post to the [relevant docs page](https://docs.datadoghq.com/real_user_monitoring/session_replay/playlists/?_gl=1*1txjcpr*_gcl_au*NTc0Nzc5ODA2LjE2OTQ0NjA2MDk.*_ga*MTkwMTMwODAzMi4xNjg2NjY1MTM5*_ga_KN80RDFSQK*MTY5Nzc0NDU0My4yNzMuMS4xNjk3NzQ2NzcxLjAuMC4w*_fplc*MDcyOWZlYVl3bVZQNXlYaGxHd04lMkY2a0V0Y09ES0ZPcmZVdHkyZUFacm5VS3FtcG1kNWNhNUdVRjlzclRBREhvTkh6Q3hqaTE4NE9hUG1OdlZlVHkxSVglMkZ3MkJHYnMlMkJCdkd3MWl5Nms0TlFkZTJpZjVuY3ljUDdRbWNLc0NRJTNEJTNE&_ga=2.83401044.371651871.1697488616-1901308032.1686665139).
> Add blog to further reading.

- content/en/continuous_integration/guides/pipeline_data_model.md
- content/en/continuous_integration/search/_index.md
- content/en/continuous_integration/troubleshooting.md
Add a couple of minor clarifications about CI Pipeline Visibility and two extra troubleshooting sections. 
Our motivation is to avoid confusion among our users, as we have received some complaints about behaviours totally normal that were reported as problems.
> [CI-APP] Update CI Pipeline documentation

- content/en/tracing/guide/inferred-service-opt-in.md
> Update inferred-service-opt-in.md - add configs for dd agent

- content/en/continuous_integration/search/_index.md
Add AI-generated log summaries
New private beta feature for Pipeline Visibility
> Add docs for AI-generated log summaries

- content/en/security/cloud_security_management/_index.md
Adds additional details about the CSM weekly digest report.
> DOCS-6370: Add section for CSM weekly digest report

- i18n/en.json
- i18n/fr.json
- i18n/ja.json
- i18n/ko.json
Updates integration count from 600 to 650
https://datadoghq.atlassian.net/browse/WEB-4125
> [WEB-4125] Update integration count to 650

- local/bin/js/algolia-index-sync.js
Rolling back previous changes which inadvertently removed records from non english languages.
> Roll back Algolia sync job changes

- content/en/getting_started/profiler/_index.md
- New blog post: https://www.datadoghq.com/blog/request-latency-profiling/.
- Add to this page: https://docs.datadoghq.com/getting_started/profiler/.
> Add New Blog Post to Continuous Profiler Doc

- content/en/network_monitoring/performance/network_analytics.md
NPM started supporting cloud service tagging for azure last year, our docs should mention it. (They already do elsewhere)
> Add reference to Azure in NPM cloud tagging docs

- content/en/network_monitoring/devices/network_topology_map.md
Add info about device autodiscovery config at the request of the PM
> Add autodiscovery config info

- content/en/metrics/custom_metrics.md
- Hotjar request to add information on how to send metric units for custom metrics -> only possible through web ui
- Add links for metric units and unit override
> Add note on adding metric units for custom metrics

- content/en/synthetics/api_tests/grpc_tests.md
- content/en/synthetics/api_tests/ssl_tests.md
- content/en/synthetics/api_tests/tcp_tests.md
- content/en/synthetics/api_tests/udp_tests.md
The app does not default to the ports mentioned. The ports mentioned are just placeholder to help users choose one
> change ports mentions

- content/en/cloud_cost_management/aws.md
- content/en/cloud_cost_management/azure.md
> Add cost x metrics info to ccm docs

- content/en/continuous_integration/tests/setup/swift.md
A translator pointed out that there is some typoed syntax in our Swift code example.
> Swift code example typo

- content/en/synthetics/guide/_index.md
- content/en/synthetics/guide/api_test_timing_variations.md
- content/en/synthetics/guide/authentication-protocols.md
- content/en/synthetics/guide/browser-tests-passkeys.md
- content/en/synthetics/guide/browser-tests-totp.md
- content/en/synthetics/guide/browser-tests-using-shadow-dom.md
- content/en/synthetics/guide/custom-javascript-assertion.md
- content/en/synthetics/guide/email-validation.md
- content/en/synthetics/guide/manually-adding-chrome-extension.md
- content/en/synthetics/guide/monitor-usage.md
- content/en/synthetics/guide/popup.md
- content/en/synthetics/guide/reusing-browser-test-journeys.md
- content/en/synthetics/guide/synthetic-test-monitors.md
- content/en/synthetics/guide/synthetic-tests-caching.md
- content/en/synthetics/guide/testing-file-upload-and-download.md
- content/en/synthetics/guide/uptime-percentage-widget.md
- content/en/synthetics/guide/using-synthetic-metrics.md
Use verbs instead of gerunds in Synthetics guide titles.
Chat with Hugo P on Slack.
> Standardize Synthetic Monitoring Guide Titles

- content/en/profiler/enabling/dotnet.md
- content/en/serverless/azure_app_services/azure_app_services_linux.md
- content/en/serverless/azure_app_services/azure_app_services_windows.md
> [.NET Profiler] Update the documentation to enable profiler on AAS

- content/en/profiler/connect_traces_and_profiles.md
- content/en/profiler/guide/_index.md
- content/en/profiler/profile_visualizations.md
> Add Java WallClock official blogpost

- content/en/profiler/enabling/java.md
Mentions that Datadog Profiler is Linux only, JFR is Linux and Windows
> DOCS-6520 Update supported OSes for each Java profiler

- content/en/cloud_cost_management/google_cloud.md
Remove private beta form button link at request of CCM PM (Natasha Goel)
> Remove CCM GCP private beta button linking to form - we want to keep internal and not in public docs

- content/en/observability_pipelines/guide/ingest_aws_s3_logs_with_the_observability_pipelines_worker.md
Use `code-lang` partial to fix the markdown because it's getting oddly rendered (highlighted in red).
> Fix markdown in OP  AWS S3 doc

- static/robots.txt
Updates robots.txt to include sitemap URLs
https://docs-staging.datadoghq.com/nsollecito/robots-txt/robots.txt
> [WEB-3934] Update robots.txt

- content/en/security/application_security/enabling/serverless.md
This PR adds additional steps for newly added capabilities for AWS Lambda for CLI, AWS CDK, and Serverless Plugin.
- Approved by PM
> [DOCS-6517] AWS Lambda additions to CLI, CDK and Serverless plugin

- content/en/opentelemetry/guide/switch_from_processor_to_connector.md
https://datadoghq.atlassian.net/browse/OTEL-1144
Update the guide on datadog connector with the correct collector configs. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/27846.
> [OTEL-1144] Update collector configs with datadog connector

- content/en/tracing/trace_collection/single-step-apm.md
https://datadoghq.atlassian.net/browse/DOCS-6353
Feedback from PM to address customer confusion.
> [DOCS-6353] Clarify beta status of single step instrumentation

- content/en/containers/guide/ad_identifiers.md
In addition to clarifying short name, this page needed a refresh.
> DOCS-6509 - update ad identifiers guide

- README.md
> Improved Readme.md . Changes aim to improve the formatting, clarify steps, and ensure consistency throughout your README

- content/en/metrics/guide/_index.md
- content/en/metrics/guide/micrometer.md
- Give recommended options to send metrics through Datadog Agent when using Micrometer.
- [DOCS-6474](https://datadoghq.atlassian.net/browse/DOCS-6474)
[x]Please merge after reviewing
[DOCS-6474]: https://datadoghq.atlassian.net/browse/DOCS-6474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Micrometer guide to send metric with Agent

- content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md
> Move reference link

- content/en/tracing/service_catalog/setup.md
add instructions & example for user-defined services
> Update service catalog setup.md

- content/en/tracing/service_catalog/troubleshooting.md
Update reference to inferred service beta in Service catalog FAQ
> Update troubleshooting.md add inferred services mention

- content/en/observability_pipelines/architecture/advanced_configurations.md
- content/en/observability_pipelines/architecture/preventing_data_loss.md
- content/en/observability_pipelines/setup/splunk.md
Acknowledgment is spelled incorrectly in a few places. Quick PR to fix those.
> Fix "acknowledgment" typos

- content/en/continuous_integration/search/_index.md
Update a broken link in a tab.
> Search and Manage CI Pipelines and Tests Edit

- content/en/tracing/trace_collection/single-step-apm.md
https://datadoghq.atlassian.net/browse/DOCS-6486
Doc command was incorrect and should reflect what's in the app for single step APM instrumentation.
> [DOCS-6486] Fix Docker command to reflect in-app command.

- general.preview.synthetics.json
adds the following integration carousel synthetics the `Preview Synthetics / synthetic_testing` github action ci/cd pipeline
- runs on pull request
[5wk-kij-2kr] Found test "[DOCS] [Integrations Carousel] Should open modal "
[we3-74z-69s] Found test "[DOCS] [Integrations Carousel] Should navigate in modal"
[8tg-frt-4us] Found test "[DOCS] [Integrations Carousel] Should navigate on desktop from vertical-item controllers"
[xgp-pt3-96s] Found test "[DOCS] [Integrations Carousel] Should navigate 3 items or less"
[tmu-5bd-zz2] Found test " [DOCS] [Integrations Carousel] Should navigate on tablet from arrow controllers"
[a6h-tc7-qxw] Found test "[DOCS] [Integrations Carousel] Should navigate on desktop from arrow controllers"
[732-wgh-aiz] Found test "[DOCS] [Integrations Carousel] Should …
> integration carousel ci cd tests

- content/en/continuous_integration/guides/pipeline_data_model.md
Copy modification for a guide 
> Public API guide docs copy modifications

- content/en/tracing/trace_collection/library_config/php.md
This config exists since a while in dd-trace-php, but was never documented.
> Document DD_TRACE_DB_CLIENT_SPLIT_BY_INSTANCE config

- content/en/continuous_integration/static_analysis/_index.md
Adds a new option for the static analyzer.
> Add option to static analyzer inputs

- content/en/containers/docker/apm.md
Adding UDS set up example for Docker
> Add UDS set up

- content/en/real_user_monitoring/guide/setup-rum-deployment-tracking.md
> Remove beta callout from RUM deployment tracking

- content/en/service_management/events/explorer/navigate.md
Remove further reading partial, there are no links in the front matter.
> Remove further reading partial

- content/en/security/application_security/threats/trace_qualification.md
Adding some additional clarification around how the trace qualification works based on PM feedback.
> [DOCS-6591] small addition to ASM trace qualification page

- content/en/getting_started/cloud_siem/_index.md
Log ingestion redirects to the notification rules page. Redirecting to /integrations
- [ X] Please merge after reviewing
> Fix Log Ingestion Link

- content/en/security/application_security/enabling/nodejs.md
fixes a typo, flagged by transifex
> fixing a dockerfile typo

- content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
> fix spelling of "stream"

- content/en/cloud_cost_management/aws.md
> typo fix on kinesis

- content/en/monitors/guide/non_static_thresholds.md
transifex was getting tripped up on the unconventional use of the word "proxy" here
> reword sentence to have a clearer meaning

- content/en/dynamic_instrumentation/_index.md
> add dynamic instrumentation blog link

- content/en/observability_pipelines/_index.md
- content/en/observability_pipelines/configurations.md
- content/en/observability_pipelines/guide/control_log_volume_and_size.md
- content/en/observability_pipelines/production_deployment_overview.md
For OP docs:
- remove traces
- add beta to metrics
[DOCS-6433](https://datadoghq.atlassian.net/browse/DOCS-6433) - PM request
[DOCS-6433]: https://datadoghq.atlassian.net/browse/DOCS-6433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6433] Remove traces and add beta for metrics in OP docs

- content/en/serverless/installation/python.md
> quick fix to a copy/paste error

- content/en/tracing/service_catalog/adding_metadata.md
add description and example for schema v2.2
> update service catalog schema to support v2.2

- content/en/security/application_security/threats/threat-intelligence.md
needs review by eslam and janis
@netcode @jkirsteins Can you help me with the following:
On line 20, add a link or example of the credential stuffing rule that uses threat intel.
On lines 29>31 add links for the sources.
> updated for structure and suggested use cases.

- content/en/cloud_cost_management/tag_pipelines.md
> Update tag_pipelines.md for reserved

- .gitignore
- config/_default/menus/menus.en.yaml
- content/en/account_management/org_settings/oauth_apps.md
- content/en/developers/authorization/_index.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
The [source has been renamed](https://github.com/DataDog/apps/pull/161). Decided to rename the file to reduce future tech debt.
> Rename UI Extensions

- content/en/dashboards/querying/_index.md
Refined updates for the min/max feature that is being launched to GA.
> Min/Max Feature Update 

- content/en/integrations/guide/azure-graph-api-permissions.md
> quickfix: add a linebreak

- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter.md
A file was removed during reorganization and the setup link no longer pointed to a valid page.
I've mostly copied this from the original setup page, but potentially the organization could use some work.
> Fix setup documentation for Flutter

- content/en/database_monitoring/connect_dbm_and_apm.md
This change updates the DBM/APM documentation to reflect new additions to the support of mysql client libraries in python. The inconsistency of this document was pointed out in https://github.com/DataDog/dd-trace-py/issues/6802.
> update mysql database client support documentation for python tracer

- content/en/profiler/enabling/dotnet.md
- content/en/serverless/azure_app_services/azure_app_services_linux.md
- content/en/serverless/azure_app_services/azure_app_services_windows.md
> GA .NET AAS Profiler

- content/en/database_monitoring/connect_dbm_and_apm.md
Reverts DataDog/documentation#20464
> Revert "update mysql database client support documentation for python tracer"

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump dd-trace-dotnet layer to version 11

- assets/styles/instantsearch/search-page.scss
Updates Search Results page to have proper word-wrap on small screens to fix page layout.
Review this page with the query "dashboard to view all workflow executions" and compare to the live site. Long strings are now broken to fit in the container (bug seen mostly with long inline links)
- https://docs-staging.datadoghq.com/davidweid/update-search-hits-wrap/search/?s=dashboard%20to%20view%20all%20workflow%20executions
- https://docs.datadoghq.com/search/?s=dashboard%20to%20view%20all%20workflow%20executions
> search page break word

- content/en/agent/supported_platforms.md
Updates support for Kubernetes + Docker
Hold on merging for now
> Update supported platforms

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump extension layer to version 50

- content/en/tracing/service_catalog/_index.md
add specification on how to modify language & type
> add version 2.2 support for modifying language and type information

- content/en/agent/supported_platforms.md
Follow-up of #20230, updates a few sections of the supported platforms docs.
> [agent] Small fixes to supported platforms docs

- content/en/tracing/service_catalog/setup.md
Clarifies location of service definition metadata file
> DOCS-6620 Clarify service catalog manual service addition info

- content/en/real_user_monitoring/guide/proxy-rum-data.md
> Add AP1 to the proxy setup table

- content/en/data_security/real_user_monitoring.md
DOCS-6615, clarify that it is the customer's responsibility to obtain any required permissions around using cookies.
> Update cookie permissions copy

- content/en/service_management/events/usage.md
Fix a really simple syntax mistake.
It fixes a syntax mistake. Subtitle is "Examples of what do to with events" instead of "Examples of what to do with events"
> Update usage.md "to do" instead of "do to"

- content/en/serverless/step_functions/troubleshooting.md
Update Step Function Span Support
> Update Step Function Span Support

- content/en/integrations/guide/source-code-integration.md
Some customers are confused on how to use the git-metadata upload command. This PR clarifies (hopefully) the usage.
Before:
After:
> [SCI] Clarify git metadata upload usage

- content/en/tracing/service_catalog/guides/streamlining-development-lifecycle-with-ci-visibility.md
> Small wording change in Service Catalog Guide

- go.mod
- go.sum
enables access to a new icon from `websites-modules`
websites-modules PR: https://github.com/DataDog/websites-modules/pull/267
preview: https://docs-staging.datadoghq.com/websites-modules/generated/267/
> Generated by websites-modules

- content/en/real_user_monitoring/guide/setup-rum-deployment-tracking.md
- Transifex found duplicate word
> Fix duplicate word

- content/en/serverless/aws_lambda/installation/_index.md
- layouts/shortcodes/beta-callout-private.html
Adds a private beta interest form for bulk instrumentation of Lambda Functions (Private Beta)
> Add private beta interest form for Lambda Bulk Instrumentation

- content/en/tracing/service_catalog/scorecards.md
> Adding API documentation to Scorecards docs

- content/en/tracing/guide/agent_tracer_hostnames.md
> Add configuration by language - APM guide hostnames

- content/en/tracing/trace_collection/custom_instrumentation/php.md
Adds mention of our stubs that document our public API
> [APM][PHP] Custom instrumentation: mention our php stubs

- content/en/monitors/types/log.md
Log Monitors don't require facets anymore and any attribute can be used.
> Log Monitors: any attribute can be used
