DataDog/documentation

- content/en/dashboards/guide/custom_time_frames.md
Adds an explanation of time control in URLS to the bottom of the Custom Time Frames guide.
escalated from zendesk
ready to merge
---
> DOCS-5451 time control in urls

- local/bin/py/build/actions/workflows.py
- local/bin/py/build/configurations/pull_config_preview.yaml
Fixes redirects for workflow actions with mixed casing in their filenames
Good to merge
---
> (maint) Fix casing in workflow redirects

- assets/scripts/components/algolia/getHitData.js
- assets/scripts/components/algolia/searchbarHits.js
- assets/scripts/components/algolia/searchpageHits.js
- assets/scripts/helpers/truncateContent.js
- layouts/_default/list.algolia.json
Improve search dropdown highlighting by adjusting content we truncate and also highlighting clientside with JS when algolia stops.
To improve visible matching
https://datadoghq.atlassian.net/browse/WEB-3658
searchbar anywhere: https://docs-staging.datadoghq.com/david.jones/snippet-improve/
search results page: https://docs-staging.datadoghq.com/david.jones/snippet-improve/search/
Testing
- search for "image name instead of the regular" (including quotes)
- search for docker or other keywords such as cloudfront or eks logging
and inspect the results, you should see highlighting more often than not.
Note that while this is an improvement i've noticed that some results still don't highlight anything even though the keywords are appearing. See card for more details
---
> WEB-3658 - highlight adjustments

- content/en/continuous_integration/tests/dotnet.md
- content/en/continuous_integration/tests/java.md
- content/en/continuous_integration/tests/javascript.md
- content/en/continuous_integration/tests/python.md
- content/en/continuous_integration/tests/ruby.md
Reorganize the instructions for agent usage for CI Visibility.
It is confusing that we refer to both `DD_TRACE_AGENT_URL` and `DD_AGENT_HOST` without mentioning its relationship or what takes precedence. 
---
> [ci-visibility] Reorg agent instructions for ci visibility

- config/_default/menus/menus.en.yaml
- content/en/real_user_monitoring/error_tracking/roku.md
Add the Error Tracking documentation for our Roku RUM integration
---
> RUMM-3290 Add Error Tracking page for Roku

- layouts/shortcodes/integration_categories.md
Uses straight quotes instead of curly quotes in the Integration Categories shortcode.
Spotted in Vale output, ready to merge.
---
> Integration Categories Straight Quotes Update 

- config/_default/menus/menus.en.yaml
- content/en/containers/cluster_agent/_index.md
- content/en/containers/cluster_agent/clusterchecks.md
- content/en/containers/cluster_agent/setup.md
- content/en/containers/guide/kubernetes_daemonset.md
- content/en/containers/kubernetes/_index.md
- content/en/containers/kubernetes/apm.md
- content/en/containers/kubernetes/configuration.md
- content/en/containers/kubernetes/installation.md
overhauls k8s installation and configuration pages. this could use an editorial review but should otherwise be good to merge. all information taken directly from datadog-operator repo and helm chart.
> DOCS 5517: updating k8s configuration page 

- layouts/shortcodes/api-scopes.html
Changes how we iterate over the scope data so that we don't miss anything when displaying
Relates to discussions with Austin around missing scopes
https://docs-staging.datadoghq.com/david.jones/scopes-patch/api/latest/scopes/
---
> fix missing scopes

- content/en/tracing/service_catalog/setup.md
add notes about how we translate Backstage YAMLs to Datadog Service Catalog YAMLs
---
> Update Service Catalog Setup to include Backstage YAML support

- content/en/dashboards/widgets/_index.md
- layouts/shortcodes/nextlink.html
- Fixes the issue with widget icons rendering on preview sites, and also updates the sourcing of the images to be served through imigix for optimization
Widget icons don't currently load on preview sites
https://dd.slack.com/archives/C0DESMBQU/p1687890249511809?thread_ts=1687886463.904819&cid=C0DESMBQU
---
> Fix widgets page

- content/en/serverless/azure_support.md
adds an azure support matrix as an faq-type page so it doesn't get search indexed.
> DOCS-4953 azure support matrix

- go.mod
- go.sum
- update the `go.mod` and `go.sum` files to point at the most current version of websites modules
There appears to have been some drift introduced into the master branch for websites modules due to a workflow not being completed. This will fix that drift and set things right so future changes will work as expected.
To test:
- pull this branch down
- run `make start`
- ensure site starts as expected and pages load (mostly the footer/header)
---
> Point go.mod at the latest version

- content/en/account_management/audit_trail/events.md
> [CIAPP-6905] Adding CI Visibility audit events.

- local/bin/py/build/configurations/pull_config_preview.yaml
Enable the preview cache again
It was turned off in a recent commit and can be slow
Nothing to test in preview, just check builds after merge
---
> enable cache

- content/en/developers/authorization/oauth2_endpoints.md
- content/en/developers/authorization/oauth2_in_datadog.md
- content/en/developers/dogstatsd/_index.md
- content/en/developers/dogstatsd/datagram_shell.md
- content/en/developers/guide/query-data-to-a-text-file-step-by-step.md
Addresses broken anchor links in the Developers doc set + https://github.com/DataDog/integrations-core/pull/15099.
Link checker output, ready to merge.
---
> Cleanup Anchor Links in Developers Documentation

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps the python layer to 75
I just released 75
---
> Bump datadog-lambda-python layer to version 75

- .github/CODEOWNERS
Probably good for the web team to look at these files too
---
> (maint) Add corpweb to the go module files

- content/en/agent/guide/dogstream.md
- content/en/agent/logs/advanced_log_collection.md
- content/en/glossary/terms/tail.md
- content/en/logs/guide/container-agent-to-tail-logs-from-host.md
- content/en/logs/guide/custom-log-file-with-heightened-read-permissions.md
- content/en/logs/guide/mechanisms-ensure-logs-not-lost.md
- content/en/logs/log_collection/csharp.md
- content/en/logs/log_collection/go.md
- content/en/logs/log_collection/java.md
- content/en/logs/log_collection/nodejs.md
- content/en/logs/log_collection/php.md
- content/en/logs/log_collection/python.md
- content/en/logs/log_collection/ruby.md
Adds a glossary entry for tail. See <a href="https://github.com/DataDog/documentation/pull/18437">[Update csharp.md](https://github.com/DataDog/documentation/pull/18437)</a>
Preview glossary entry here: 
https://docs-staging.datadoghq.com/heston/glossary-tailing/glossary/#tail
---
> (DOCS-5629) Tail glossary entry

- content/en/continuous_integration/tests/javascript.md
Add a known limitation to the cypress plugin for ci visibility.
Let users know.
https://docs-staging.datadoghq.com/juan-fernandez/add-cypress-after-run-limitation/continuous_integration/tests/javascript/?tab=cypress#cypress-afterrun-event
---
> [ci-visibility] Add cypress' limitation with `after:run`

- content/en/developers/authorization/oauth2_in_datadog.md
Adds a new requirement for the base64url encoding on the code_challenge.
---
> Update OAuth docs on code_challenge

- assets/styles/components/_integrations.scss
fix-carousel height on integrations carousel
`.carousel-item__horizontal` items could extend the inherited height of `.carousel-top-row` due to being a child of a grid display. setting a min-height other than auto fixes it 
check that carousel item doesnt overlap the item description and counter
https://docs-staging.datadoghq.com/stefon.simmons/fix-height-carousel-item/integrations/buoyant_cloud/
---
> fix-carousel height on integrations carousel

- content/en/database_monitoring/setup_postgres/gcsql.md
Fixes an incorrect DB flag for cloud-sql postgres.
---
> `pg_stat_statements.track_utility` is a boolean

- content/en/monitors/guide/template-variable-evaluation.md
round function now support a second parameter: round(var,n). The result of the function is var rounded to the number of digits specified by the param n.
> Round function with digit number param

- content/en/continuous_integration/tests/_index.md
Add benchmark test regressions section in the Branches description of CI Test VIsibility.
Release of a new feature to detect benchmark test regressions.
---
> Add benchmark test regressions section

- content/en/continuous_integration/tests/javascript.md
Add a new section to the javascript docs for CI Visibility explaining the new manual testing API.
Allow users to use the new manual testing API.
https://docs-staging.datadoghq.com/juan-fernandez/add-manual-testing-api/continuous_integration/tests/javascript/?tab=onpremisesciproviderdatadogagent#manual-testing-api
---
> [ci-visibility] Add manual testing API for javascript

- content/en/agent/guide/network.md
- content/es/agent/guide/network.md
- content/fr/agent/guide/network.md
- content/ja/agent/guide/network.md
For customers using APM, the Datadog agent will currently send APM instrumentation telemetry to `instrumentation-telemetry-intake.datadoghq.com`, however, this is not explicitly mentioned in our network documentation on https://docs.datadoghq.com/agent/guide/network/?tab=agentv6v7 . This PR addresses this shortcoming.
Jira: https://datadoghq.atlassian.net/browse/AIT-7693 . This omission in the documentation was originally reported by a customer.
---
> Add the instrumentation telemetry intake endpoint to the public documents for APM

- content/en/serverless/google_cloud_run/_index.md
Fixes the link. Right now the link is pointing to time and space aggregation, which is incorrect.
---
> Fix link to point to correct page for Google Secrets

- content/en/logs/error_tracking/backend.md
- Add information about attributes that need to be added to the Error Logs for the UI to display Error Tracking elements
[DOCS-5791](https://datadoghq.atlassian.net/browse/DOCS-5791)
---
[DOCS-5791]: https://datadoghq.atlassian.net/browse/DOCS-5791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add error tracking attribute info

- content/en/profiler/profile_types.md
- content/en/tracing/trace_collection/library_config/php.md
Document the fact that an active JIT disables PHP allocation profiling.
---
> Document JIT vs allocation profiling

- content/en/continuous_integration/tests/python.md
This removes the "Python test visibility support is in beta" note.
Python test visibility support is going GA.
---
> CIAPP-7029: CI test viz: remove python beta note

- content/en/tracing/trace_collection/library_config/go.md
- content/en/tracing/trace_collection/library_config/java.md
This PR fixes the documentation of `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED` behavior.
The description is not compliant with the RFC nor the documentation.
The issue was brought to eng from support.
There is the same sentence for the Go Tracer. I don't know what the implementation status is or who to contact about it?
---
> Fix DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED documentation

- content/en/agent/logs/advanced_log_collection.md
Add note to [Advanced Log Collection Configurations](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=kubernetes)
We experienced `log_processing_rules` not working several times due to JSON syntax violation.
In Docker/Kubernetes environment, the label/annotation value is just a part of YAML, but it must be correct JSON. 
So suggested to add note to help people debugging misconfiguration.
---
> Add note to help debugging misconfiguration

- content/en/real_user_monitoring/reactnative/advanced_configuration.md
Specify that only error taps are supported for React Native applications
Documentation is currently not clear about this: https://github.com/DataDog/dd-sdk-reactnative/issues/506
An other PR should follow to adapt the frustration signals page to add mobile SDKs setup instructions and specificities.
---
> Mention only error taps are supported for RN

- content/en/continuous_integration/tests/javascript.md
Let users know that the manual testing API is incompatible with already supported frameworks.
Make sure users of already supported frameworks do not try to use the manual testing API (it wouldn't work).
---
> [ci-visibility] Add note about javascript's manual testing API

- content/en/continuous_integration/static_analysis/rules/_index.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
This updates the static analysis landing page and provided minor upgrades to other rules.
We've added a new ruleset, `python-pandas`, that we need to add to the documentation as it's publicly available. We've made incremental changes to existing rules as well.
This cannot be merged until the Static Analysis' source repo PR is merged to `main`: [Source PR](https://github.com/DataDog/datadog-static-analyzer-rule-docs/pull/7)
---
> [STAT-378] update static analysis docs

- content/en/continuous_integration/tests/javascript.md
Adds a section about how to add custom metrics to the JavaScript docs for the CI Visibility team.
There is no previous section about how to add custom metrics, many users have been asking about how to add custom metrics.
---
> Add custom metrics section to javascript

- content/en/security/application_security/enabling/compatibility/_index.md
- content/en/security/application_security/enabling/compatibility/go.md
- content/en/security/application_security/enabling/compatibility/ruby.md
Adds supported version info for Go and Ruby OSS Vuln in ASM. This is ready to merge when approved.
DOCS-5808
---
> DOCS-5808 ASM OSS Vuln - add go and ruby supported version numbers

- content/en/account_management/saml/troubleshooting.md
Remove mention of LastPass/broken docs link.
Flagged by translators in Transifex
---
> Remove 404 Link in SAML Troubleshooting 

- content/en/tracing/trace_collection/library_config/java.md
Clarifies some ambiguous wording about deprecated Java propagation style settings.
Customers have been confused and some has believed that all support for any type of B3 propagation has been deprecated.
---
> Clarify deprecation of Java propagation settings

- content/en/continuous_integration/tests/dotnet.md
- content/en/continuous_integration/tests/java.md
- content/en/continuous_integration/tests/javascript.md
- content/en/continuous_integration/tests/junit_upload.md
- content/en/continuous_integration/tests/python.md
- content/en/continuous_integration/tests/ruby.md
- content/en/continuous_integration/tests/swift.md
- layouts/shortcodes/ci-agent.md
- layouts/shortcodes/ci-agentless.md
- layouts/shortcodes/ci-git-metadata.md
- layouts/shortcodes/ci-information-collected.md
Adds four reusable shortcodes to be used across several language Tests pages. Reattempts https://github.com/DataDog/documentation/pull/18780, ready to merge.
Chat with Romain on Slack
---
> CIAPP-7065 Add Reusable Markdown Shortcodes in Test Visibility Documentation

- content/en/agent/logs/advanced_log_collection.md
following up on #18802 
While looking over updated doc after #18802, 
found some config example have regex escaping note and JSON syntax note and some have regex note only (yes, my oversight).
---
> Add JSON syntax note next to every regex note

- content/en/continuous_integration/tests/dotnet.md
- content/en/continuous_integration/tests/java.md
- content/en/continuous_integration/tests/javascript.md
Adds the language requirement banners back in the Agentless tab.
Chat with Romain on Slack, ready to merge
---
> Add Language Support Banners for Agentless Instructions in Test Visibility Documentation

- content/en/real_user_monitoring/browser/modifying_data_and_context.md
- Adds instructions on how to override default RUM view names specifically for React Native applications.
- Indents previously added code blocks.
[DOCS-5793](https://datadoghq.atlassian.net/browse/DOCS-5793)
Ready to merge following reviews by Nhien and Aymeric.
---
[DOCS-5793]: https://datadoghq.atlassian.net/browse/DOCS-5793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> React Native router instrumentation

- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
Documents the 128-bit trace ID feature flags in the .NET Tracer.
We have improved interopability with 128-bit trace ID's in the .NET Tracer and the features can be enabled with our feature flags.
N/A
---
> APM > .NET > Configuration > Document 128-bit trace ID feature flags

- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
Reverts DataDog/documentation#18759
We got ahead of ourselves. This feature is not ready yet. We can revert this "revert" PR when it's ready.
> Revert "APM > .NET > Configuration > Document 128-bit trace ID feature flags"

- content/en/logs/guide/azure-logging-guide.md
- Add a general note about the Nodejs 16 deprecations.
- [DOCS-5799](https://datadoghq.atlassian.net/browse/DOCS-5799)
- Support has been receiving a number of tickets from customers about this and requested a note to let customers know that we are aware of node runtimes being deprecated and we change them continuously as we hear of new ones.
- Ready to merge after review.
---
[DOCS-5799]: https://datadoghq.atlassian.net/browse/DOCS-5799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add note about nodejs deprecation

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps our node layer to 94
I just published 94.
---
> Bump datadog-lambda-js layer to version 94

- content/en/continuous_integration/pipelines/_index.md
In the current docs search, CI Visibility search results are being displayed after search results for Continuous Testing.
Chat with Kassen, ready to merge.
---
> Bump Search Results for CI Visibility Pipelines Documentation

- content/en/continuous_integration/tests/_index.md
In the current docs search, CI Visibility search results are being displayed after search results for Continuous Testing.
Chat with Kassen, ready to merge.
---
> Bump Search Results for CI Visibility Tests Documentation

- content/en/logs/log_configuration/archives.md
It's not a problem for s3, because enabling object lock forces the use of versioning, and trying to upload the same object just creates a new version.
cf https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html
---
> Remove note specifying not to add object lock for s3 archives

- .github/workflows/preview_link.yml
- local/bin/py/preview-links-template.mako
- local/bin/py/preview_links.py
Attempts to fix an issue where unrelated/unchanged files were being posted in the preview links section:
- Moves most of the filename logic out of the mako file
- Ensures that only markdown files are posted in the preview links
- Changes fetch depth in the workflow to `0`. I suspect this is the main reason why unchanged files are making it into the links section. The [documentation for the action](https://github.com/tj-actions/changed-files#usage) notes that you should set this parameter (but mentions that you can ommit it for PRs, which is why we initially didn't use it). This will probably result in the action taking longer to run, but probably not as long as the preview build itself, so not a big issue.
---
> (ci) Fix preview link poster

- content/en/logs/explorer/watchdog_insights.md
Add the definition of what a severe log anomalies is that is then reflected in the Watchdog feed.
There was no explanation of what consistute a severe anomaly worth being raised on the Watchdog alerts.
---
> details what a severe log anomaly is

- content/en/containers/kubernetes/prometheus.md
Change the wording to clarify that these `kubernetes_container_names` filters are regex formatted, not wildcard formatted. As well as change to bullets to look nicer.
Example can do:
```yaml
- autodiscovery:
kubernetes_annotations:
include:
prometheus.io/scrape: "true"
kubernetes_container_names:
- ^example-.*
```
To match those pods with the annotation and containers starting with the phrase `example-`
Clarify the handling as can create the checks unexpectedly otherwise
https://docs-staging.datadoghq.com/jack.davenport/scrape-rules/containers/kubernetes/prometheus/?tab=kubernetesadv2#advanced-configuration
Code for reference, not a new change has been this way:
- https://github.com/DataDog/datadog-agent/blob/7.46.x/pkg/autodiscovery/common/types/prometheus.go#L251-L267
---
> Fix Prometheus Scrape autodiscovery rules for container name

- content/en/security/application_security/enabling/java.md
- content/en/security/application_security/enabling/nodejs.md
- content/en/security/application_security/vulnerability_management/_index.md
This PR changes naming references from "custom code vulnerability detection" to the new name "code-level vulnerability detection". The changes include changes to the Application Vulnerability management doc, as well as the 2 currently supported libraries for this capability (node.js and java).
Includes also new video for both libraries.
[DOCS-5854](https://datadoghq.atlassian.net/browse/DOCS-5854)
---
[DOCS-5854]: https://datadoghq.atlassian.net/browse/DOCS-5854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOCS-5854 changing custom-code to code-level naming

- content/en/security/security_signal_management/_index.md
Update the time period over which a security signal can be updated.
A security signal can updated within 30 days of being created.
This is the impacted page: https://docs.datadoghq.com/security/security_signal_management
---
> 👌[k9]Update signal update period

- layouts/partials/sidenav/main-sidenav.html
The `.sidenav` searchbar should **not** appear on the `search results` page only.
fixes a bug where the search bar would not show on pages with a [ContentBaseName (defaulted to TranslationBaseName)](https://gohugo.io/variables/files/#prose) of 'search'. 
this included the [search results page](https://docs.datadoghq.com/search/) and all other pages that ended in `/search` (ex: https://docs.datadoghq.com/tracing/trace_explorer/search/)
uses `File.Path` variable to specify the `search results` (`search.md`) page
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3815
https://docs-staging.datadoghq.com/stefon.simmons/web-3815/tracing/trace_explorer/search/
---
> fix sidenav search bar not showing - [WEB-3815]

- content/en/containers/guide/clustercheckrunners.md
See context for this here: https://dd.slack.com/archives/C4UD9L724/p1689091684804119
This new description (credit to Jack Davenport) is more informational and removes the misleading 'Note' section from before that had some customers confused. (this note section: Note: When using a cluster check runner, it is not necessary to enable cluster checks for the regular Datadog Agent.)
In the words of Jack Davenport
its not necessary to enable cluster checks for the regular Datadog Agent - but given Helm and the Operator is managing everything for you that note isn’t really adding anything that the preceding paragraph isn’t covering. Its just adding a wrinkle where there doesn’t need to be. If there was a DaemonSet set of instructions that would make sense to have there.
---
> Update clustercheckrunners.md | Rewriting Summary section at the top

- content/en/synthetics/api_tests/dns_tests.md
- content/en/synthetics/api_tests/grpc_tests.md
- content/en/synthetics/api_tests/http_tests.md
- content/en/synthetics/api_tests/icmp_tests.md
- content/en/synthetics/api_tests/ssl_tests.md
- content/en/synthetics/api_tests/tcp_tests.md
- content/en/synthetics/api_tests/udp_tests.md
- content/en/synthetics/api_tests/websocket_tests.md
- content/en/synthetics/browser_tests/_index.md
- content/en/synthetics/browser_tests/actions.md
- content/en/synthetics/multistep.md
- layouts/shortcodes/synthetics-alerting-monitoring.md
- layouts/shortcodes/synthetics-variables.md
Finds more instances of the `synthetics-variables` shortcode and adds a `synthetics-alerting-monitoring` shortcode.  
DOCS-5829, ready to merge.
---
> DOCS-5829 Use Synthetic Reusable Shortcodes in Synthetic Monitoring Documentation

- content/en/tracing/trace_collection/library_config/java.md
The documented feature is not yet ready to be used by customers.
This commit could be reverted as soon as the feature is ready.
Same as #18878 and #18938 but for Java tracer.
---
> Remove 128-bit trace ID feature flags for Java tracer

- content/en/synthetics/troubleshooting/_index.md
Add a use case where if a user has a login that is not working with the default iframe recorder, that they should record using the pop-up window option using the extension instead of the browser recorder.
Chat with Keith on Slack, ready to merge.
---
> Synthetic Monitoring Troubleshooting Update

- content/ja/tracing/trace_collection/library_injection_local.md
Fix mistranslation of "mutate" in Japanese. 
The word "ミュート" as originally written means "mute" in English. To translate "mutate" into Japanese, "変異" is appropriate (as already in line 87).
The words "mute" and "mutate" are almost opposite in meaning. This can be very confusing.
---
> Fix mistranslation of "mutate" in Japanese

- .gitlab-ci.yml
Fix live pa11y scheduled job to reference `build_live` job
Bug
---
> Swap pa11y dependency

- content/en/serverless/distributed_tracing/_index.md
Change `DD_ENABLE_TRACING` to the correct env variable, `DD_TRACE_ENABLED`.
https://datadoghq.atlassian.net/browse/DOCS-5852
This is the only doc that referenced `DD_ENABLE_TRACING` + the source code references `DD_TRACE_ENABLED`, which led me to believe DD_TRACE_ENABLED is the correct env variable.
---
> [DOCS-5852] Fix Incorrect Env Variable.

- content/en/continuous_integration/static_analysis/_index.md
The `datadog-ci upload sarif` command does not accept a `--site` option. Instead it should be a `DD_SITE` environment variable.
A user reported they followed our docs and they couldn't upload their SARIF report as `--site` was not supported.
---
> [STAT-410] update --site option to env var

- content/en/tracing/other_telemetry/connect_logs_and_traces/php.md
- content/en/tracing/trace_collection/compatibility/php.md
- content/en/tracing/trace_collection/library_config/php.md
Explains the new various way to connect logs and traces in PHP
Adds some necessary documentation on the upcoming **automatic log injection feature** coming on the PHP tracer -datadog/dd-trace-php#2118
---
> Add PHP logs correlation documentation

- content/en/agent/guide/use-community-integrations.md
This PR adds a brief sentence describing how to handle issues if a user's site blocks access to network traffic.
[DOCS-5770](https://datadoghq.atlassian.net/browse/DOCS-5770)
Ready to merge
---
[DOCS-5770]: https://datadoghq.atlassian.net/browse/DOCS-5770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5770] adding info on network access restrictions

- content/en/logs/log_collection/nodejs.md
- content/fr/logs/log_collection/nodejs.md
- content/ja/logs/log_collection/nodejs.md
Fix alignment of `json: true` with the rest of the code:
---
> Logs collection NodeJS: fix misalignment in code snippet

- local/bin/py/build/actions/integrations.py
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Stop removing integrations when encountering a duplicate.
This needs to be refactored to remove after processing is complete but for now lets disable this.
Noticed some integrations were missing as part of the transition from dogweb to integrations-internal-core
Both scenario examples and both should exist on site
(enabled in dogwe, disabled in internal) 
https://docs-staging.datadoghq.com/david.jones/integration-fix/integrations/?q=splunk
(disabled in dogweb, enabled in internal
https://docs-staging.datadoghq.com/david.jones/integration-fix/integrations/?q=onelogin
---
> integration fix

- content/en/integrations/guide/source-code-integration.md
1. Add instructions on how customers can embed git metadata in their deployed artifacts for Python and .NET (adding to the instructions we already had for Go)
2. Add instructions on extra steps customers will need to take if they want to embed git metadata in their deployed artifact if their CI build process runs inside a docker container. These instructions apply to all languages (including Go).
3. 
These instructions will enable developers to introduce Source Code Integration for their services without requiring the assistance of an IT/Ops person.
---
> Source Code Integration: add instructions for embedding git commit metadata for .NET & Python

- content/en/account_management/saml/_index.md
JiT public docs didn't mention that custom roles are also supported. 
Cleaning up an old FR about JiT not supporting custom roles (it does now, wasn't reflected in the public docs)
I didn't update the screenshot, but the UI shown there is very old! (so this specific doc may not have been updated in a while).
Docs team, please feel free to merge this if it's approved! Thanks!
---
> Update JIT public docs to say all roles are supported

- content/en/serverless/azure_app_services/azure_app_services_container.md
This PR adds an example to instrument a Java application within Azure App Service -> Linux Container
There was a support ticket where a customer was trying this use case and it was possible so we should document it
---
> Add Java example for AAS Linux Container

- content/en/monitors/types/log.md
issue in the log samples and breaching values table
---
> solve issue #18922 

- config/_default/menus/menus.en.yaml
- content/en/database_monitoring/connect_dbm_and_apm.md
- content/en/database_monitoring/guide/_index.md
- content/en/tracing/other_telemetry/_index.md
- Rename "Connecting DBM and APM" to "Connect Database Monitoring and Traces".
- Move "Connect Database Monitoring and Traces" out of `/guides` subdirectory up to DBM.
- Redirect and add to nav menu at `/tracing/other_telemetry/`.
- Add alias to redirect old URL to new URL.
- Add new section to Connect APM Data with Other Telemetry page.
https://datadoghq.atlassian.net/browse/DOCS-5646
I purposefully put separate nav bar titles for APM and DBM links because they use different standards "Connecting" vs. "Connect".
- [Update URL in web-ui repo](https://github.com/DataDog/web-ui/pull/97500).
- Determine if we still want to remove beta banner.
---
> [DOCS-5646] Move and Rename DBM Traces Page

- content/en/getting_started/cloud_siem/_index.md
- content/en/integrations/amazon_guardduty.md
- content/fr/integrations/amazon_guardduty.md
- content/ja/getting_started/cloud_siem/_index.md
- content/ja/integrations/amazon_guardduty.md
Renames AWS GuardDuty to Amazon GuardDuty 
To match the marketing name used by AWS
---
> Rename AWS GuardDuty -> Amazon GuardDuty to match the product name

- content/en/tracing/service_catalog/setup.md
removing restriction due to recent update
remove a prior restriction on the feature 
---
> Update backstage import instructions to remove a restriction

- content/en/logs/guide/azure-logging-guide.md
- content/ja/logs/guide/azure-logging-guide.md
https://datadoghq.atlassian.net/browse/AZI-1514
Updates the Azure log forwarder documentation to recommend using NodeJS 18. Also removes a banner referencing the NodeJS 16 end of life.
We have already tested that the log forwarder works correctly with NodeJS 18 and updated the Deploy To Azure button to deploy the function using 18.
NodeJs 16 end of life in Azure
---
> [AZI-1514] update docs to use NodeJS 18 in Azure log forwarder

- content/en/profiler/profiler_troubleshooting/ruby.md
**What does this PR do?**:
This PR extends the Ruby profiler incompatibility list added in https://github.com/DataDog/documentation/pull/17370 with a new known issue with the Phusion Passenger web server, reported by a customer in https://github.com/DataDog/dd-trace-rb/issues/2976 .
**Motivation**:
Make sure the list is kept up-to-date, so customers can reference it.
**Additional Notes**:
Like the `rugged` gem and unlike `mysql2`, there's currently no known versions of Phusion Passenger without this issue.
---
> [PROF-7966] Document Ruby profiler incompatibility with passenger

- content/en/security/cloud_workload_security/setup.md
CWS setup instructions should always include RC instructions. 
https://docs.datadoghq.com/security/cloud_workload_security/setup/?tab=kubernetesoperator
---
> [CWS] Update Datadog Operator for CWS instructions to include RC

- layouts/partials/grouped-item-listings.html
Fix where some actions the icon is under a different object
slack
https://docs-staging.datadoghq.com/david.jones/action-integration-logo/service_management/workflows/actions_catalog/#openai
---
> integration id can be nested under icon sometimes

- content/en/observability_pipelines/guide/_index.md
- content/en/observability_pipelines/setup/splunk.md
Fix the link for the guide index page
Came up on documentation
---
> Fix guide link for Splunk Observability Pipelines

- assets/scripts/components/async-loading.js
- assets/scripts/region-redirects.js
- content/en/agent/guide/private-link.md
- content/en/integrations/guide/azure-native-programmatic-management.md
- content/en/tracing/configure_data_security/_index.md
- layouts/partials/table-of-contents/scraped-toc.html
- layouts/partials/table-of-contents/table-of-contents.html
An alternative solution to the site-region syntax updates:
In some situations using a site-region shortcode with `<` is causing the table of contents to omit items.
This PR resolves this by using the built in `.TableOfContents` for most sections except pages with `<` style site-region shortcodes in which case we load a custom toc that will read the rendered page headers and generate a correct version.
js changes:
- hideTOCItems that are not specific to the selected region.
- hides toc items that have corresponding headers nested in tabs. (this ensures the new scrapped toc works like the hugo tableofcontents)
- adding this function to the async-loading script to hide toc items when a page is accessed by navigating the left nav.
In relation to:
- …
> custom toc testing

- content/en/integrations/kubernetes_state_core.md
`kubernetes_state.configmap.count` and `kubernetes_state.secret.count` metrics were added to the KSM core check for agent `7.46` via this PR [#17314 ](https://github.com/DataDog/datadog-agent/pull/17314)
This PR updates the documentation to reflect these new metrics
---
> Add configmap.count and secret.count metrics to KSM Core documentation

- content/en/tracing/trace_collection/trace_context_propagation/ruby.md
The default value for APM Ruby tracing propagation is not easily understandable from our current documentation.
This PR ensures that the public documentation for Ruby APM reflects the current default values for propagation styles.
The value has not changed: this PR just clarifies the language in this section.
---
> Ruby:Clarify tracer propagation default configuration

- content/en/observability_pipelines/setup/datadog.md
- content/en/observability_pipelines/setup/splunk.md
Update sources list for apt instructions
---
> OPA 535: Update sources list to OP worker instead of Datadog

- content/en/continuous_integration/intelligent_test_runner/_index.md
- content/en/continuous_integration/intelligent_test_runner/swift.md
7/25: I found out we are not waiting for a Python beta doc page to be published for Dash. 
DOCS-5801, ready to merge.
---
> DOCS-5801 Add Three Beta Banners In Intelligent Test Runner Documentation

- content/en/serverless/azure_container_apps/_index.md
Updating Container App docs to include the dockerfile install instructions we have been reviewing in Cloud Run repo. Also includes update to call out additional required environment variables for Container apps.
---
> Update Container Apps docs with new installation structure

- content/en/containers/amazon_ecs/_index.md
New FIPS Proxy version has been released
https://docs-staging.datadoghq.com/nicolas.guerguadj/ecs-fips-0.5.4/containers/amazon_ecs/?tab=awscli#fips-proxy-for-govcloud-environments (US1 Fed site only)
---
> Update FIPS proxy version to 0.5.4

- config/_default/menus/menus.en.yaml
- content/en/service_management/incident_management/zoom_integration.md
Add documentation for installing, using, and removing the Zoom integration for Incident Management. These docs should be private/hidden for now until the integration is approved by Zoom.
Our Zoom App must have publicly accessible documentation to be accepted onto the Zoom App Marketplace
some more context in this thread in slack https://dd.slack.com/archives/C0DESMBQU/p1690312669997819
---
> [incident-app] add zoom integration docs to Incident Management docs

- config/_default/menus/menus.en.yaml
- content/en/account_management/saml/_index.md
- content/en/account_management/saml/mapping.md
Moves the section on user group mapping from the main SAML setup page to its own page.
I need to add some more information on user mapping, and it will make the SAML page too long. Moving the mapping content to its own page makes it easier to understand. The additional user mapping documentation will come in a follow-on PR.
The content in the new `mapping.md` file is copied and pasted from the previous location. It is identical except for one small grammar fix.
ready to merge
---
> Move SAML role mapping to its own page

- content/en/integrations/_index.md
`tcp-queue-length` was originally a disabled integration (https://github.com/DataDog/documentation/pull/8764)
It seems to be enabled again now https://docs.datadoghq.com/integrations/?q=tcp%20queue however clicking on the integration tile redirects you to integrations.
This pr removes the alias we had previous when it was disabled.
Slack
Visiting https://docs-staging.datadoghq.com/david.jones/tcp-queue-enable/integrations/?q=tcp%20queue and clicking on tcp queue length should work https://docs-staging.datadoghq.com/david.jones/tcp-queue-enable/integrations/tcp_queue_length/
also visiting directly should work 
---
> remove tcp queue length alias

- content/en/infrastructure/list.md
Removed link to the Python helper script and upgraded to Python3. 
Included the code directly in the doc instead of depending on a 3rd party gist owned by somebody else.
---
> [cayetano.delgado] Update list.md and include python code

- content/en/containers/cluster_agent/commands.md
This env variable [doesn't exist since a long time ago](https://github.com/DataDog/datadog-agent/commit/25fc4c80d08dc7592b254f79c08ac4ab4344efa8) (5 years) but documentation was never changed
---
> Fix metrics port env variable

- content/en/containers/docker/log.md
Updates the page on [Docker Log collection](https://docs.datadoghq.com/containers/docker/log/?tab=dockercompose) with a note about Docker Compose.
Every now and again customers run in to the issue https://github.com/DataDog/datadog-agent/issues/17804 when trying out the Agent. The reason this issue happens is because Docker Compose does not parse the environment variables and so passes a quoted value to the Agent.
---
> Updating Docker Log collection with note about Docker Compose

- content/en/continuous_integration/intelligent_test_runner/_index.md
- content/en/continuous_integration/intelligent_test_runner/java.md
- content/en/continuous_integration/intelligent_test_runner/swift.md
This PR removes the beta labels from the Intelligent Test Runner documentation.
---
> Remove beta label from ITR docs

- content/en/database_monitoring/setup_oracle/_index.md
It changes the documentation to point to the latest Oracle beta release (0.33)
---
> New Oracle beta release - 0.33

- config/_default/menus/menus.en.yaml
- content/en/database_monitoring/setup_oracle/_index.md
- content/en/database_monitoring/setup_oracle/autonomous_database.md
- content/en/database_monitoring/setup_oracle/exadata.md
- content/en/database_monitoring/setup_oracle/rac.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Removes private beta from Oracle DBM docs.
DOCS-5645
---
> DOCS-5645: Remove private beta from DBM docs

- content/en/security/cloud_workload_security/setup.md
> [CWS] fix the indentation for the daemonset instructions

- layouts/shortcodes/latest-lambda-layer-version.html
Bump datadog-lambda-python layer to version 77
Why not 76? I made a mistake and pushed a broken Python311 layer to some regions. And therefore releasing 77 as a good layer to fix.
---
> Bump datadog-lambda-python layer to version 77

- static/resources/yaml/observability_pipelines/datadog/aws_eks.yaml
- static/resources/yaml/observability_pipelines/datadog/azure_aks.yaml
- static/resources/yaml/observability_pipelines/datadog/google_gke.yaml
- static/resources/yaml/observability_pipelines/quickstart/aws_eks.yaml
- static/resources/yaml/observability_pipelines/quickstart/azure_aks.yaml
- static/resources/yaml/observability_pipelines/quickstart/google_gke.yaml
- static/resources/yaml/observability_pipelines/splunk/aws_eks.yaml
- static/resources/yaml/observability_pipelines/splunk/azure_aks.yaml
- static/resources/yaml/observability_pipelines/splunk/google_gke.yaml
Testing with GKE for the quickstart values failed due to buffer overflows from the available storage on their persistent drives.
I've tuned the values down a little to allow OPW pods to start.
---
> [OPW] Update the buffer values to make cloud deployments easier.

- content/en/developers/ide_integrations/idea/_index.md
- content/en/developers/ide_integrations/vscode/_index.md
Removes the notification that the IDE integrations for IntelliJ and VS Code are in public beta.
The IntelliJ plugin and the VS Code extension will be announced as GA at DASH this week.
https://docs-staging.datadoghq.com/david.gilbert/IDE-1482/developers/ide_integrations/idea/
---
> Remove public beta banners from IntelliJ and VS Code pages.

- content/en/tracing/trace_collection/compatibility/nodejs.md
Fix broken link to NodeJS releases on https://docs.datadoghq.com/tracing/trace_collection/compatibility/nodejs/
Fix broken link to NodeJS releases on https://docs.datadoghq.com/tracing/trace_collection/compatibility/nodejs/
---
> Fix broken link to NodeJS releases

- content/en/security/infrastructure_vulnerabilities/setup.md
Add alias
Adds an alias for the old URL for Infra VM.
---
> Add alias link in Infra VM docs

- content/en/tracing/trace_collection/trace_context_propagation/_index.md
- content/en/tracing/trace_collection/trace_context_propagation/cpp.md
- content/en/tracing/trace_collection/trace_context_propagation/dotnet.md
- content/en/tracing/trace_collection/trace_context_propagation/go.md
- content/en/tracing/trace_collection/trace_context_propagation/java.md
- content/en/tracing/trace_collection/trace_context_propagation/nodejs.md
- content/en/tracing/trace_collection/trace_context_propagation/php.md
- content/en/tracing/trace_collection/trace_context_propagation/python.md
- content/en/tracing/trace_collection/trace_context_propagation/ruby.md
This PR adds some standardization to the Trace Context Propagation page:
- Standardizes references to "W3C" as "W3C Trace Context"
- Standardizes the format of the supported propagators list
I wanted to make sure we were consistent when we refer to the W3C Trace Context headers
N/A
---
> APM > Trace Context Propagation > Standardize W3C text and formatting

- .github/CODEOWNERS
Adds the .NET tracer group as code owners for relevant pages of the documentation.
So that we can beware of changes happening and add comments where needed to make sure the changes are relevant and not misleading.
---
> Update CODEOWNERS to add dotnet-tracing as owners

- content/en/serverless/step_functions/installation.md
There are some observed regression in logs `execution_arn` attribute using `_` connecting the last 2 uuid of Forwarder from v71 to v73. Recommending using tested v74+ that makes the attribute correctly using `:` for connecting.
> update recommended Forwarder version for step functions tracing

- content/en/serverless/azure_container_apps/_index.md
- content/en/serverless/google_cloud_run/_index.md
Switching back to a manual tracer sample, and label Orchestrion information as private beta
---
> Update orchestrion references in Cloud Run and Container App docs

- content/en/containers/cluster_agent/admission_controller.md
* Adds a note for EKS instructions to ensure adequate networking, as otherwise the mutated component times out / cannot be deployed
* Multiple support requests
---
> [DCA Admission controller] Adds instructions for EKS private clusters

- content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
Adds small fixes on the `setup_and_configuration` page for Mobile Session Replay
---
> Fix the docs for Mobile SR setup page

- content/en/watchdog/alerts/_index.md
Change the name of `correlated dashboards` to `related dashboards` on watchdog alerts
The UX was changed to reflect related assets so we needed to change the name in the documentation but reflects in the description that there is a correlation 
---
> Update watchdog alert dashboard description

- content/en/continuous_integration/tests/_index.md
* Remove that TSLV is only supported for agentless (it isn't)
* Add python compatibility with TSLV
* Link to Java compatibility
* Keep users up to date
---
> [ci-visibility] Fix outdated references to test suite level visibility (TSLV)

- layouts/partials/serverless/serverless-apm-recommendations.html
Change [Distributed Tracing with AWS Lambda Serverless Applications](https://docs.datadoghq.com/serverless/distributed_tracing/#runtime-recommendations) page to use the ".NET" logo instead of the ".NET Framework" logo.
Before:
AWS Lambda only supports .NET 6+, not the legacy .NET Framework.
N/A
---
> [Serverless] Fix .NET logo

- content/en/continuous_integration/tests/ruby.md
Removes copy that was accidentally added to the Ruby docs, but does not apply to Ruby.
DOCS-5984
---
> Remove unsupported Agentless mode from Ruby docs

- content/en/database_monitoring/_index.md
- layouts/partials/dbm/dbm-setup-oracle.html
The index page for DBM was missing the Oracle setup tiles, so they've been added here. I also tweaked the appearance of the Oracle setup partial, which was awkwardly laid out due to a long line of text in one of the tiles.
DOCS-5985
---
> Add Oracle setup tiles to DBM > Getting Started

- content/en/serverless/google_cloud_run/_index.md
Fixing the spacing to correct the bullet rendering in the Dockerfile section
---
> Fix Spacing for bullets

- .gitlab-ci.yml
- Sets the correct rule set for the `link_checks:on-schedule` job so that it only runs on schedule and not on every master deploy
Shout out to @kayayarai for catching this, it was running on all master deploys due to the wrong ruleset being applied in CI (and @hestonhoffman for the heads up about it)
---
> Update link check on schedule with correct rules

- assets/scripts/components/algolia/getHitData.js
- assets/scripts/components/algolia/searchbarHits.js
- assets/scripts/components/algolia/searchpageHits.js
Rolling back some work done to manually include `<mark>` element for snippet and title highlighting, to avoid https://dd.slack.com/archives/C0DESMBQU/p1691518439384279
https://dd.slack.com/archives/C0DESMBQU/p1691518439384279
https://docs-staging.datadoghq.com/brian.deutsch/search-results-headers/search/?s=set%20up%20tracing%20on%20a%20teamcity
do some QA on search and make sure results dont have any strange strings/generally look good
---
> Search result title and content snippet mark element rollback

- content/en/security/infrastructure_vulnerabilities/setup.md
Fixes the host setup instructions for CSM Infra VM.
Request by PM.
---
> Fix host setup instructions for CSM Vulnerabilities

- content/en/account_management/billing/containers.md
This makes it clear that DD agent containers are not metered only on the current allocations of 5/10 containers. 
A customer was confused about this applying to their 10/20 allocation plan.
---
> update container billing FAQ for clarity on DD agent metering

- config/_default/menus/menus.en.yaml
- content/en/account_management/api-app-keys.md
- content/en/logs/log_collection/android.md
- content/en/logs/log_collection/reactnative.md
Add the missing React native logs collection page. Also make the client token paragraph more complete, we don't just do Browser monitoring...
---
> Improve mobile logs documentation

- content/en/tracing/other_telemetry/connect_logs_and_traces/dotnet.md
Add information on how to configure log injection in NLog 5.0+
We have updated the tracer internally to use a new way to inject properties. The older version shown for NLog version 4.6+ works as well for 5.0+, but will stop working once NLog 6.0 is released eventually. We want customers that follow documentation to be ready when that release happens.
---
> Update how NLog5.0+ should be used for log injection

- content/en/tracing/trace_collection/compatibility/python.md
Moves pytest from the web framework table to the library table.
pytest fits better under the library header than either web framework or datastore.
---
> Python trace collection compatibility: move pytest from web framework to library

- content/en/account_management/rbac/permissions.md
Updates role-permission docs now that the `standard` permission is deprecated.
https://datadoghq.atlassian.net/browse/ACCESS-1829
I've looked through the repo to find more references to the `standard` permission, but haven't found any so far.
---
> [ACCESS-1829] Have docs reflect `standard` deprecation

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
Updates the list of supported integrations for .NET 
We don't support WCF on .NET Core
Added accidentally in this PR: https://github.com/DataDog/documentation/pull/11200
---
> [APM .NET] Remove WCF from list of supported .NET Core integrations

- config/_default/menus/menus.en.yaml
Add [Single Step APM Instrumentation](https://docs.datadoghq.com/tracing/trace_collection/single-step-apm) to the nav menu.
Request from @vidurkhannadatadog 
Put above Instrumenting with Datadog Tracing Libraries to emphasize the single-step path for users.
---
> [DOCS-6033] Add single step APM to nav menu.

- content/en/continuous_integration/tests/junit_upload.md
> [ci-visibility] Remove duplicated `--report-tags` and `--report-metrics`

- content/en/monitors/types/watchdog.md
Increase the size of images for APM and infrastructure watchdog monitors
Images were fairly small for those two and did not take that much vertical space so increasing the size would improve visibility
---
> increase size of images

- assets/scripts/components/async-loading.js
- assets/scripts/components/copy-code.js
- assets/styles/pages/_global.scss
- layouts/partials/api/code-example.html
- layouts/partials/api/request-body.html
- layouts/partials/api/response.html
- layouts/reference/single.html
- ensures copy btn appears in code examples (request and response) on hover
- load the `click copy btn` event listener and add copy buttons on async loading
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3877
Check that a copy button appears on hover in the top right of any language code examples, request, response examples
- https://docs-staging.datadoghq.com/stefon.simmons/fix-missing-copy-btns/dynamic_instrumentation/enabling/java?tab=commandarguments
- https://docs-staging.datadoghq.com/stefon.simmons/fix-missing-copy-btns/observability_pipelines/reference/sources/
- includes accordion code example:
- https://docs-staging.datadoghq.com/stefon.simmons/fix-missing-copy-btns/api/latest/metrics/
---
> add 'Copy' btn to all code examples

- content/en/profiler/connect_traces_and_profiles.md
Recommends Go 1.21 or newer for using the Go profiling timeline feature.
Go 1.21 has been [released](https://go.dev/blog/go1.21). This Go release includes changes which
significantly reduce thea overhead of data collection for the Go
profiling timeline feature. So, we should recommend that version of Go
(or newer) to users who are interested in the feature.
> Recommend Go 1.21 or newer for profiling timeline beta

- content/en/tracing/service_catalog/_index.md
remove wording about availability in US-FED
---
> clarifying govCloud support

- content/en/security/application_security/enabling/serverless.md
- content/en/serverless/installation/python.md
Updates py runtime.
I was working on the setup while working as my lambda was running at python 3.10 and on the documentation I didn't see python 3.10 mentioned, for a wild guess I checked with `Python310` and verified the arn it worked, therefore I also checked with `Python311` it also got verified, therefore just a small PR.
---
> patch: added missing py runtime updates

- content/en/agent/guide/secrets-management.md
Fix incorrect namespace for rolebinding resource as the rolebinding should  be in the same namespace as the role.
The docs were wrong.
---
> Fix incorrect namespace for rolebinding

- content/en/security/misconfigurations/_index.md
Adds resource evaluation frequency to CSM Misconfigurations overview page.
Request by PM.
---
> CSM Misconfigurations: Add resource evaluation frequency

- content/en/continuous_integration/static_analysis/_index.md
Adds a section detailing with fields that the `static-analysis.datadog.yml` file supports.
We've added support for two new fields, `ignore-paths` and `ignore-gitignore`, that are not documented anywhere.
---
> [STAT-492] Add static-analysis.datadog.yml documentation

- content/en/agent/remote_config/_index.md
- content/en/security/threats/workload_security_rules.md
- content/ja/agent/remote_config/_index.md
The form link to request access to private beta for CWS custom rules deployments is incorrect.  The correct form link is:
https://docs.google.com/forms/d/e/1FAIpQLSe5Emr7y_Jg3ShcC44HlYtalxKgHUocFAz8dq87xSkjfeALTg/viewform
The form link is broken which means customers are not able to request access to the private beta.
---
> Fix private beta link form for CWS custom rules

- config/_default/integration_redirects.yaml
- local/bin/py/build/actions/integrations.py
- local/bin/py/build/configurations/pull_config_preview.yaml
Adds a redirect config for adding custom redirects to integrations. Currently, it's not easy to add redirects when an integration is deleted or renamed.
---
> Add custom redirects for integrations

- content/en/serverless/step_functions/installation.md
Setting `OutputPath` field is not a requirement. It was originally added because demo org has some specific purpose which I believe is not for everyone.
> Remove Outputpath from Step Functions documentation

- content/en/security/infrastructure_vulnerabilities/setup.md
Fix broken link in Further Reading section.
---
> Fix broken link in CSM Vulnerabilities docs

- local/bin/py/translations/orphaned_translations.py
Escapes special characters in file names for the orphaned file finding script
---
> (maint) Escape special characters in orphan script

- content/en/tracing/trace_collection/library_injection_local.md
Adjust the yaml syntax and formatting of the Kubernetes injection options.
In the containers docs we generally use `# (...)` instead of just `...` in the YAML blocks. It displays nicer and if you copy-paste it in, it won't break your syntax.
More importantly though adjust the Deployment syntax to a more valid setup. As the before option isn't spaced right and is lacking a few important configuration keys. 
Clarify the K8s samples and remove the guess work.
---
> Fix Kubernetes yaml syntax and formatting

- content/en/tracing/other_telemetry/connect_logs_and_traces/php.md
Moves the information about adding the first-level `dd` key to monolog 2 section because it doesn't work for monolog 3. Also adds info on adding `extra.dd.trace_id`.
User opened an [issue](https://github.com/DataDog/documentation/issues/18272).
---
> [DOCS-5551] Update connect logs and traces for PHP monolog

- config/_default/integration_redirects.yaml
- local/bin/py/build/actions/integrations.py
There's a better way to add redirects for integrations using front matter cascades with Hugo, so we're going to use that method instead.
---
> Revert "Add custom redirects for integrations (#19376)"

- content/en/security/cloud_siem/log_detection_rules.md
Adds info that the order of a case affects the notifications sent.
SE / PM request
---
> [DOCS-5538] Add case order info to Cloud SIEM log detection doc

- content/en/glossary/terms/flame_graph.md
Remove typo in flame graph definition.
Hotjar feedback [DOCS-6081](https://datadoghq.atlassian.net/browse/DOCS-6081)
Read to merge after review.
---
[DOCS-6081]: https://datadoghq.atlassian.net/browse/DOCS-6081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove extra 'the' in definition

- local/bin/py/build/actions/security_rules.py
At least one of the [security rule filenames use capitalization](https://github.com/DataDog/security-monitoring/blob/main/cloud-siem/log-detection/production/kubernetes/kubernetes-pod-created-with-hostNetwork.md). The filenames are used to insert aliases (redirects) into the docs at build time, and caps don't work in redirects. This should fix it. 
---
> (maint) Fix small security rule redirect issue

- content/en/logs/log_configuration/parsing.md
Consistently use the term `characterAllowList` in the logs keyvalue parser documentation.
The term `characterAllowList` was introduced in the past to replace `characterWhiteList`, and this change handles one missing replacement.
---
> Use consistent naming for keyvalue parser parameters

- content/en/continuous_integration/quality_gates/_index.md
* Update quality-gates docs to suggest the new version of `datadog-ci gate` 
* Add `--timeout` flag description
* Update `DATADOG_APP_KEY` and `DATADOG_API_KEY` to `DD_APP_KEY` and `DD_API_KEY`
* The new version of `datadog-ci gate` contains improved wait time handling, and a new `timeout` flag introduced in https://github.com/DataDog/datadog-ci/pull/1013
* We want customers to use `DD_APP_KEY` and `DD_API_KEY`
---
> Update quality-gates docs

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
This PR removes the "Datadog Internal" bundle from the action catalog page https://docs.datadoghq.com/service_management/workflows/actions_catalog/
Preview link to the catalog https://docs-staging.datadoghq.com/gabriel.plassard/exclude-workflow-internal-from-doc/service_management/workflows/actions_catalog/
---
> Remove the com.datadoghq.internal bundle from the action catalog doc

- assets/scripts/cookie-banner.js
When the GDPR banner first loads, its z-index is set to 999999, however, the code that was set up to update the z-index to -1 after the banner was closed was no longer working as there is a delay now on the banner display.
This is updated to listen for a click event on the relevant buttons and remove the element after the user either Accepts or Rejects the cookies.
https://datadoghq.atlassian.net/browse/WEB-3753
In order to test, you have to be in a GDPR region or use a proxy (encrypt.me) to change your location:
https://docs-staging.datadoghq.com/nsollecito/web-3960/
Wait until the banner loads, click Accept or Reject and make sure you can still click the links in the footer after the element is removed.
---
> [WEB-3753] Update cookie banner script

- content/en/agent/guide/dual-shipping.md
Adding helm instructions for dual shipping orchestrator data. There is no case where you'd add config to the `datadog.yaml` so I removed it to avoid confusion
> Update dual-shipping docs for orchestrator to include helm instuctions

- content/en/monitors/manage/_index.md
Change description of the delete action in the monitor manage doc
Monitor delete is not a permanent action since now the users are able to restore their recently deleted monitors from the settings page.
---
> Change description of the Monitor delete action

- content/en/agent/guide/secrets-management.md
Fix secret documentation broken link.
Merge fd521a41cda245c134e24135ed02738d25748ef5 seems to have broken the link
---
> Fix secret documentation broken link

- content/en/real_user_monitoring/error_tracking/android.md
- content/en/real_user_monitoring/error_tracking/reactnative.md
- content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
This PR updates Android mapping file limit from 200 MB to 300 MB for all Datadog sites except AP1 and GovCloud.
---
> RUM-926: Update the limit for Android mapping file uploads to 300 MB

- content/en/logs/log_configuration/indexes.md
Changes the default log index count from 10 to 100
Product has lifted the default limit, and since the docs say:
> [Contact Datadog support](https://docs.datadoghq.com/help) if you need to increase the maximum number of indexes for your account.
We'd prefer to keep the ticket count down by letting customers know they get 100 by default.
Please hold on merging while I obtain final approval from the Logs Group PM.
---
> Change default log index count from 10 to 100

- content/en/dashboards/widgets/note.md
Adds a small disclaimer that the notes and links widget does not support inline HTML. Unsure if there is perhaps a more appropriate location within the page.
A support request: https://datadoghq.atlassian.net/browse/WEBPS-4961
---
> Add note on Notes and Links page

- content/en/tracing/trace_collection/single-step-apm.md
Update Single Step APM note:
- Ruby is a supported language.
- Only  x86_64 architectures are supported.
Requested by @vidurkhannadatadog 
---
> Add Ruby Support + x86_64 Architectures Only

- content/en/cloud_cost_management/container_cost_allocation.md
Adds information on Cloud Cost Management support for usage-based ECS split cost allocation.
Rolling out ECS split cost allocation to all customers. 
---
> Add ECS split cost info

- content/en/continuous_integration/intelligent_test_runner/javascript.md
Add a note about changing durations for suites that run with intelligent test runner.
Let users know about this ITR quirk. 
https://docs-staging.datadoghq.com/juan-fernandez/add-note-about-test-durations/continuous_integration/intelligent_test_runner/javascript
---
> [ci-visibility] Add note about test duration with ITR 

- content/en/agent/troubleshooting/send_a_flare.md
* No customer runs pre-5.3 agent versions anymore, so no need to mention versions
* Update link to flare code
---
> Remove outdated mentions in send_a_flare.md

- content/en/logs/log_collection/csharp.md
- content/en/logs/log_collection/go.md
- content/en/logs/log_collection/java.md
- content/en/logs/log_collection/nodejs.md
- content/en/logs/log_collection/php.md
- content/en/logs/log_collection/python.md
- content/en/logs/log_collection/ruby.md
Adds service name variables to log collection docs and make path file variable format consistent with it. 
[DOCS-5570](https://datadoghq.atlassian.net/browse/DOCS-5570)
---
[DOCS-5570]: https://datadoghq.atlassian.net/browse/DOCS-5570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5570] Add service name variable to log collection docs

- content/en/containers/kubernetes/distributions.md
* Documents the necessary security context override for the nodeAgent in OpenShift when deploying with the Operator
* With the Helm chart, this security context is set by default, so it works OOTB
* The `format-links.sh` pre-commit also modified the hyperlinks on this page.
* Discussion with container-ecosystems team on moving forward to enable these features within OpenShift when using the Operator : https://dd.slack.com/archives/C037CDX0WJV/p1692983558887469?thread_ts=1690186181.131549&cid=C037CDX0WJV
---
> [OpenShift Operator] Document securityContext for log/apm via socket

- local/bin/py/build/configurations/pull_config_preview.yaml
re-enable cache
defualt should be `true` ([docs](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/2891318774/Preview+Build+Caching))
nothing updated here
https://docs.datadoghq.com/
---
> cache enabled

- content/en/tracing/guide/span_and_trace_id_format.md
This PR updates the trace id generation page with the correct rage for the Ruby tracer.
We've had the trace id for Ruby being an integer from 1 to (2**62)-1 for quite some time: https://github.com/DataDog/dd-trace-rb/blob/09c08622ea7f7ca4e193ea6bca6daec4cde3e8cb/lib/datadog/tracing/utils.rb#L13-L20
---
> Tracing: Update Ruby trace_id generation range

- content/en/integrations/guide/prometheus-metrics.md
Fix an error on an option name. 
Someone discovered a similar error elsewhere (https://github.com/DataDog/integrations-core/pull/15693), cross-checking I found out that this guide makes the same mistake. See for example https://github.com/DataDog/integrations-core/blob/feafdeb3694fbe8990a3ae4a87cd6b382457063f/datadog_checks_base/datadog_checks/base/checks/openmetrics/base_check.py#L25.
---
> Correct name of option in mapping Prometheus metrics guide

- data/partials/home.yaml
Small, non-urgent question on the microcopy for the [Security tile](https://docs.datadoghq.com/) on the [Docs landing page](https://docs.datadoghq.com/): the “in your applications and infrastructure” is causing the tile to need a third row, if we were to remove it, all the tiles would be consistent with two rows. I looked at the Documentation Site’s [landing page heatmap](https://dd-corpsite.datadoghq.com/rum/heatmap/view/clickmap?from_ts=1672560000000&live=false&query=%40application.id%3A3493b4e7-ab12-4852-8836-ba96af7bc745+%40view.name%3A%22%2F%22+%40display.viewport.width%3A%5B768+TO+1280%5D&to_ts=1690411860000) from the start of the year and there’s been no activity with the in your applications and infrastructure, so I’m thinking it may be alright to remove it. Any thoughts?
Posted …
> Small Homepage Security Tile Microcopy Nit

- content/en/logs/log_collection/_index.md
seems like a copy/paste error that the ap1 partial said us5.
> update site in ap1 section to say ap1

- content/en/profiler/enabling/java.md
The Java profiler covers a wide range of providers, this PR clarifies it.
---
> Update Java profiler requirements

- content/en/continuous_integration/guides/add_custom_metrics.md
- content/en/continuous_integration/tests/ruby.md
[Jira issue](https://datadoghq.atlassian.net/browse/CIAPP-7001)
Adds a section for custom metrics on Ruby, link to our custom metrics guide, and Ruby tab to our custom metrics guide
Parity between Ruby documentation and docs for other languages
---
> Add custom metric section for Ruby

- content/en/continuous_integration/tests/ruby.md
Adds information on Minitest support for test visibility in Ruby. Reorders test framework tabs for ruby (rspec, minitest, cucumber) as rspec and minitest are more widely used.
Minitest support was added recently but the docs were not updated yet
---
> Add minitest docs to Test Visibility (Ruby)

- content/en/tracing/trace_collection/library_config/php.md
Add missing documentation for `DD_HTTP_SERVER_ROUTE_BASED_NAMING` in the PHP tracer.
This configuration option was added in 0.89.0 with the PR Datadog/dd-trace-php#2138, and mention was made that it was missing in the issue Datadog/dd-trace-php#2231 
---
> Add DD_HTTP_SERVER_ROUTE_BASED_NAMING documentation

- content/en/account_management/authn_mapping/_index.md
- content/en/account_management/org_settings.md
- content/en/account_management/saml/okta.md
I previously moved the SAML mapping information to its own page on [PR 19145](https://github.com/DataDog/documentation/pull/19145). At that time, I forgot to search for existing links to the anchor. It turns out that there are three references.
This PR updates the existing links to point to the new page.
I'm also using the link formatter, so it reordered the links in one of the files.
correct an error
ready to merge
---
> Update SAML mapping links to target the new page

- content/en/observability_pipelines/setup/datadog.md
This config should now work for everyone, so we can enable it instead of using `vector`.
---
> Use `observability_pipelines_worker` instead of `vector`

- content/en/database_monitoring/setup_mysql/azure.md
- content/en/database_monitoring/setup_postgres/azure.md
We updated the `name` field to be `fully_qualified_domain_name` in a recent agent release. This is a follow on PR to https://github.com/DataDog/documentation/pull/19571, which updated the docs for SQL Server
---
> Update azure YAML block config with fully_qualified_domain_name field

- content/en/tracing/trace_collection/dd_libraries/go.md
Updates Go minimum supported version to 1.18 for Go tracer.
The team confirmed that `dd-trace-go` is no longer possible to compile in versions below 1.18 because some dependencies are using features from that version.
Also, Go 1.21 was released. According to our [support policy](https://github.com/DataDog/dd-trace-go#support-policy), we support "the two latest releases are GA supported and the version before that is in Maintenance. We do make efforts to support older releases, but generally these releases are considered Legacy". This causes sunsetting support for Go 1.17.
---
> Update Go tracer compatibility requirements: Go 1.18 as minimum supported version

- content/en/dashboards/widgets/pie_chart.md
Add correct widget_type and widget shortcode to the Pie Chart docs.
[DOCS-6117](https://datadoghq.atlassian.net/browse/DOCS-6117)
---
[DOCS-6117]: https://datadoghq.atlassian.net/browse/DOCS-6117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add pie chart API fields to widget docs

- content/en/dashboards/widgets/funnel.md
- Add API shortcode for Funnel Widget
Noticed that this didn't have the table that other widgets have.
---
> Add API section for funnel widgets

- content/en/tracing/trace_collection/compatibility/php.md
Updates the Laravel compatibility of the PHP Tracer to include Laravel 9.X & 10.X 
The tests were run in Datadog/dd-trace-php#2237
It was about time to make this official 😅 
---
> Add Laravel 9.x and 10.x compatibility

- assets/scripts/datadog-docs.js
- assets/scripts/region-redirects.js
open external sites (not `docs.datadoghq.com`, `docs-staging.datadoghq.com` or `localhost:1313`) in a new tab.
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3930
check that docs links open in same tab and all other links open in new tab: 
https://docs-staging.datadoghq.com/stefon.simmons/ddog-app-as-external-link
example pages:
- https://docs-staging.datadoghq.com/stefon.simmons/ddog-app-as-external-link/service_management/incident_management/
- https://docs-staging.datadoghq.com/stefon.simmons/ddog-app-as-external-link/real_user_monitoring/error_tracking/ios/?tab=cocoapods#further-reading
---
> open external ddog app links in new tab - [WEB-3930]

- content/en/cloud_cost_management/container_cost_allocation.md
Adds orchestrator explorer as a prereq for CCM shared cost metrics.
Support issue where customer did not have this enabled. They did not have k8s shared cost metrics as a result.
---
> Add orchestrator explorer as a prereq for SCA

- content/en/logs/log_configuration/flex_log.md
- content/en/logs/log_configuration/flex_logs.md
Flex Logs is only supported for US1. Add site regions to doc. Also renames the page to flex_logs.md to be consistent with product name.
[DOCS-6144](https://datadoghq.atlassian.net/browse/DOCS-6144)
---
[DOCS-6144]: https://datadoghq.atlassian.net/browse/DOCS-6144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6144] Add site regions for Flex Logs

- content/en/database_monitoring/setup_oracle/_index.md
- content/en/database_monitoring/setup_oracle/autonomous_database.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Updating documentation for the new Oracle DBM agent release. 
In this release we are changing the naming scheme for the image - we are removing `beta` from the name. Customers are generally using agent for monitoring non-Oracle components, and they were reluctant to use a beta agent for that. But `beta` applies only to the Oracle checks; the other checks are based on the latest stable release. The Oracle setup documentation clearly states that the Oracle checks are still in the beta phase, so we aren't deceiving customers with removing `beta` from the image name.
---
> Oracle 0.34 update

- content/en/tracing/trace_collection/library_config/php.md
Adds some doc on the WordPress configuration options introduced with the 0.91.0 release of the PHP tracer 👍 
---
> Add WordPress tracing configuration options

- layouts/partials/api/curl.html
Replaces `&nbsp;\` html tags with raw value of ` \`
Curl examples are currently broken because `&nbsp` translates to `U+00a0` which breaks the examples when copying them using the `Copy` button.
---
> Use literal value for characters ` \`

- content/en/containers/kubernetes/distributions.md
* Updates the OpenShift documentation to include the SC override for the DCA so it can run `agent ...` commands (thanks to the `auth_token` in `/etc/datadog-agent/`) and use cluster checks from files
* Detailed context is available in : 
* Github original PR : https://github.com/DataDog/datadog-operator/pull/897
* Internal slack discussion : https://dd.slack.com/archives/C037CDX0WJV/p1693386280774969
* This is a "band-aid" while the DCA is not able to properly run for now with `readOnlyRootFilesystem: true` (not specifically in OpenShift, but this is where notably we can see the consequences)
---
> [OpenShift Operator] Add security context override to DCA

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps versioning
Released v48 of the extension
---
> [serverless] Bump datadog-lambda-extension layer to version 48

- content/en/database_monitoring/setup_postgres/rds.md
* Fix the JSON (Docker labels/Kubernetes annotations) for the `tags` parameter
* Pre-commit hooks formatted the hyperlinks to put them in order
* Customer case using service annotations, the DCA is complaining it cannot parse the `tags` parameter since it's the wrong type : 
```
2023-09-06 10:08:50 UTC | CLUSTER | ERROR | (pkg/autodiscovery/configresolver/configresolver.go:456 in func1) | Wrong type for `tags` in config. Expected []interface{}, got string
```
* This is because the YAML to JSON conversion is : 
```
tags:
- "ab:cd"
"tags": [
"ab:cd"
]
```
> [Postgres RDS] Fix JSON tags configuration

- content/en/real_user_monitoring/reactnative/_index.md
Update the steps for supporting `use_frameworks!` to be easier to maintain
The current suggested fix can require a bit of extra work if a lot of libraries need to be build as dynamic frameworks.
This new solution is easier to maintain and has less impact on the project.
---
> Update use_frameworks! docs for React Native

- content/en/serverless/azure_container_apps/_index.md
- content/en/serverless/google_cloud_run/_index.md
Adds alternative instructions for using CMD instead of ENTRYPOINT for instrumenting serverless-init.
---
> Add alternative instructions for ENTRYPOINT in serverless-init

- content/en/tracing/guide/inferred-service-opt-in.md
This PR updates the "inferred-service-opt-in" tracer guidelines page with Python's support for peer service mapping
The work is done in the Python tracer so the documentation needs to be updated to reflect reality
The language is pretty much a copy-paste from the .NET language documentation
---
> Add peer service remapping for python

- content/en/containers/kubernetes/configuration.md
- content/en/integrations/kubernetes_state_core.md
adds config to the troubleshooting section of the Kubernetes State Metrics Core integration (note that this integration lives in the docs repo)
also adds that same config to the kubernetes configuration page
ready to merge
> DOCS-6010 add k8s apiserver timeout config

- content/en/tracing/trace_collection/library_config/php.md
Specify the beta status of the WordPress integration.
This integration is in beta. I think that it should be mentioned.
---
> Specify the beta status of the WordPress integration

- content/en/tracing/trace_collection/custom_instrumentation/php.md
Fix php custom instrumentation code sample typo where brackets don't open and close correctly
Following the php docs and realizing the sample is incorrect
---
> Php custom instrumentation code sample typo

- assets/scripts/components/algolia/getHitData.js
- assets/scripts/helpers/string.js
- Fixes a JS console error when special characters are in the query string (for example try search for `+core`).
- Fixes cases where the search results are still rendering parts of the `<mark>` element in the title and or content.
https://datadoghq.atlassian.net/browse/WEB-4021
- Searches with special chars (such as `+`, `-`) should not result in a JS invalid regex console error.  For example: https://docs-staging.datadoghq.com/brian.deutsch/highlight-result-body-html/search/?s=%2Bcore
- Searches should not result in any part of the `<mark>` element being rendered as plain text in the search results.  For example: https://docs-staging.datadoghq.com/brian.deutsch/highlight-result-body-html/search/?s=%2B
- Test some search queries and confirm the search results still behave as intended.  
- …
> [WEB-4021] Fixes regex error and edge cases with mark element in results.

- content/en/account_management/saml/mapping.md
- content/en/account_management/teams.md
Add information on using the new SAML attribute to Datadog Teams mapping capability:
- Reorganizes the existing SAML mapping page. Adds an introduction and creates separate sections for Roles and Teams.
- Populates the Teams section on the SAML mapping page with instructions for setting up mapping.
- On the Teams page, explains the three different provisioning options.
Document the new feature
https://datadoghq.atlassian.net/browse/DOCS-5819
Ready to merge
---
> Add public docs for the Teams SAML capability

- content/en/real_user_monitoring/browser/_index.md
Add `allowFallbackToLocalStorage` RUM browser SDK  init parameter.
This parameter has been recently added to the browser SDK. 
---
> Add allowFallbackToLocalStorage init parameter

- content/en/tracing/trace_collection/library_injection_local.md
Note that instrumentation is only supported for Ruby on Rails applications and unfrozen Gemfiles.
Requested by @vidurkhannadatadog .
---
> Add Caveats to Ruby Library Injection

- content/en/tracing/trace_collection/library_config/php.md
Update the integration names (see [integrations.h](https://github.com/DataDog/dd-trace-php/blob/master/ext/integrations/integrations.h))
Seems like it is a bit outdated
---
> Update integration names

- content/en/continuous_integration/search/_index.md
- content/en/glossary/terms/flaky_test.md
- content/en/glossary/terms/test_regression.md
- content/en/glossary/terms/test_service.md
- content/en/glossary/terms/wall_time.md
Adds "CI/CD" terminology to the Docs Glossary. Will create a WEB card asking to update the product tag to `Software Delivery`.
Chat with @kayayarai on Slack, thanks for showing me how to get started with contributing terms!
---
> DOCS-5758 Add CI Visibility Vocabulary to Docs Glossary

- content/en/tracing/trace_collection/library_config/nodejs.md
Fixes bug that was causing line 252 to be underlined.
`For more examples of how to work with the library see [API documentation][2].`
https://datadoghq.atlassian.net/browse/DOCS-6174
---
> [DOCS-6174] Fix Underline Bug on Configuring the Node.js Tracing Library Page

- content/en/database_monitoring/setup_oracle/_index.md
Adjusting the setup documentation for the new custom build `7.47.0-dbm-oracle-0.40`.
---
> Adjust the Oracle setup documentation to the custom release 0.40

- content/en/containers/amazon_ecs/_index.md
Update version of the FIPS Proxy
New FIPS Proxy version has been released
https://docs-staging.datadoghq.com/dustin.long/fips-docs-0.5.5/ (US1 Fed site only)
---
> Update FIPS proxy version to 0.5.5

- content/en/tracing/guide/span_and_trace_id_format.md
Correct generated trace and span IDs based on feedback from all APM language teams.
https://datadoghq.atlassian.net/jira/software/projects/DOCS/boards/199?assignee=712020%3A0c2a9bb8-dcff-4533-8eb8-9e0bd4696037&selectedIssue=DOCS-6157
---
> [DOCS-6157] Correct Generated Trace and Span ID Reference

- layouts/partials/grouped-item-listings.html
enable search on parent action on action catalog pg
https://datadoghq.atlassian.net/browse/WEB-3965
https://docs-staging.datadoghq.com/stefon.simmons/improve-action-search/service_management/workflows/actions_catalog/
ex:
searching for "aws autosc" returns AWS AutoScaling
---
> enable search on parent action - [WEB-3965]

- .github/PULL_REQUEST_TEMPLATE.md
Removes the reviewer section from the PR template. We have more detailed internal documentation on reviewing, which makes this section redundant, and we wanted to simplify the template as much as possible.
I also combined the "What does it do?" and "Motivation" sections.
> Remove reviewer checklist and simplify template

- content/en/security/cloud_security_management/setup/csm_enterprise.md
- content/en/security/cloud_security_management/setup/csm_workload_security.md
This PR fixes the CWS installation instructions by ensuring the core agent is aware CWS is enabled.
> ensure the core agent is aware that CWS (runtime-security) is enabled in instructions

- content/en/tracing/troubleshooting/agent_apm_metrics.md
This PR removes the `datadog.trace_agent.receiver.ratelimit` metric from the agent metrics page. This metric is removed in this PR: https://github.com/DataDog/datadog-agent/pull/17917 and in existing agent versions is not usually helpful for users diagnosing issues with their agents.
https://github.com/DataDog/datadog-agent/pull/17917
---
> agent-metrics: remove receiver.ratelimit

- content/en/security/cloud_security_management/setup/csm_enterprise.md
- content/en/security/cloud_security_management/setup/csm_workload_security.md
This PR fixes the security profiles enable instruction:
- fixing the value in helm charts to match https://github.com/DataDog/helm-charts/pull/1171
- remove the instruction when using the operator since it's not available yet there
> [CWS] fix the security profile enable instructions

- content/en/serverless/aws_lambda/profiling.md
Specify which languages are currently supported for continuous profiling in aws lambda. 
Motivation: a customer turned on the profiler in a golang lambda function thinking they would not be billed for it.
This change removes any confusion about exactly which languages are running the beta.
> Specify languages for AWS Lambda Profiling public beta.

- config/_default/menus/menus.en.yaml
Move the "Create a Recommended Monitor" up one so that it sits right below "Create a Dashboard" under Developer nav section
Requested by PM
> Move recommended monitor up in the nav

- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
Splits the example for DD_TRACE_HEADER_TAGS into two: one with key:value pairs and one without.
Chatted with @vidurkhannadatadog about this resolution.
https://datadoghq.atlassian.net/browse/DOCS-6163
Hotjar feedback from a user who was confused by this.
---
> [DOCS-6163] Address User Confusion w/ DD_TRACE_HEADER_TAGS

- content/en/tracing/trace_collection/dd_libraries/php.md
[php tracing] update url to library releases
update url to library releases for php tracing libraries. Old link pointed at service list rather than installation bits.
> [php tracing] update url to library releases

- content/en/security/cloud_security_management/_index.md
- layouts/shortcodes/csm-setup-aws.md
- layouts/shortcodes/csm-setup-azure.md
- layouts/shortcodes/csm-setup-google-cloud.md
Adds a note that the CSM resource evaluation filters only work with hosts that are scanned by cloud integrations. Requested by PM.
> Add note to CSM resource evaluation filters

- content/en/dashboards/functions/rollup.md
I'm not sure if `.rollup()` is somehow used internally, but the previous phrasing is confusing to an end-user (me).
> rollup: repharse

- content/en/security/cloud_security_management/workflows.md
Fixes links to actions that are no longer available in the docs site + removes leftover links from when the article had tabs.
> Fix broken links

- content/en/real_user_monitoring/ios/advanced_configuration.md
- content/fr/real_user_monitoring/ios/advanced_configuration.md
- content/ja/real_user_monitoring/ios/advanced_configuration.md
Fixes order of parameters in objc function for adding RUM error.
https://github.com/DataDog/dd-sdk-ios/blob/743003f8bde42723c38bc5e4ebf199f617fba618/DatadogCore/Tests/DatadogObjc/ObjcAPITests/DDRUMMonitor%2BapiTests.m#L59
Merge this PR as soon as reviewed.
none
> Fix misplaced parameter

- layouts/partials/table-of-contents/scraped-toc.html
Marks the TOC items with safeHTML to avoid being escaped 
https://datadoghq.atlassian.net/browse/WEB-4064
Review: 
https://docs-staging.datadoghq.com/nsollecito/web-4064/account_management/users/#edit-a-users-roles
HTML entity should no longer be escaped
> [WEB-4064] avoid escaping TOC items

- content/en/security/application_security/enabling/compatibility/php.md
[DOCS-6239](https://datadoghq.atlassian.net/browse/DOCS-6239)
Removing Linux GNU arm64 `aarch64-linux-gnu` and Linux MUSL arm64 (`aarch64-linux-musl`) as these are not supported libraries.
ok to merge
[DOCS-6239]: https://datadoghq.atlassian.net/browse/DOCS-6239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6239] removing arm64 references as not supported

- content/en/real_user_monitoring/session_replay/privacy_options.md
Disclose that Session Replay will also mask `data-*` attributes when the `mask` mode is used.
> [RUM][REPLAY] Disclose data-* attributes in mask mode

- content/en/tracing/trace_collection/library_config/nodejs.md
https://datadoghq.atlassian.net/browse/DOCS-6174
* Originally completed this card by just fixing the underline bug.
* After discussing with Vidur, he suggested not making the header hidden at all.
* Note that this anchor is referenced in several other files.
> [DOCS-6174] Make Configuring the Node.js Tracing Library Header Visible

- content/en/monitors/notify/variables.md
Customers are complaining they don't know how to access the issue info when writing monitor notification messages.
The example provided in the doc is actually only working for APM traces but error-tracking also works for logs and rum which have different path.
https://github.com/DataDog/documentation/blob/1a9516226543ab745dd1b972b55df264cc5f0a51/content/en/monitors/notify/variables.md#matching-attributetag-variables
This isn't super nice formatting to try to put so much info into a table cell.
I thought about creating an Error-Tracking section where I could go into more details but I see no other specific product section.
If I had such section I could document other "error" attributes that can differ per traces/rum/logs.
> [Alerting]: fix error-tracking attributes example

- content/en/tracing/trace_collection/compatibility/php.md
The [0.91.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.91.0) release of the tracer includes an enhanced WordPress integration, which is officially compatible with WordPress 6 as well. 
Currently in public beta, it can be opted-in by customers. _Should it be mentioned here?_
> docs: Add WordPress 6 compatibiility

- content/en/tracing/trace_collection/compatibility/php.md
The PHP tracer supports AMQP. However, it is too vague of compatibility as we specifically support [php-amqplib](https://github.com/php-amqplib/php-amqplib), but **not** the [pecl package](https://pecl.php.net/package/amqp/2.1.0) 😔
> docs: Clarify the amqp compatibility

- content/en/tracing/trace_collection/compatibility/java.md
Documents support for [Camel-OpenTelemetry](https://github.com/apache/camel/tree/main/components/camel-opentelemetry) 3.12.0+ via the Java tracer's beta [OpenTelemetry integration](https://docs.datadoghq.com/tracing/trace_collection/otel_instrumentation/java/)
> Document support for Camel-OpenTelemetry 3.12.0+

- .gitlab-ci.yml
Due to the increase in languages, the pa11y job can timeout. This pr increases the timeout for pa11y scheduled runs.
> increase timeout for scheduled pa11y runs

- content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
It fixes an error in the Java implementation of the OpenTelemetry Id conversion. The spanId is already 16 characters long so there is no need to drop the characters. The current implementation fails when trying to parse the resulting empty string
> Fix error in Java implementation

- content/en/tracing/trace_collection/library_config/java.md
https://datadoghq.atlassian.net/browse/DOCS-5132
- Documents `dd.integration.opentelemetry.experimental.enabled` in Configuring the Java Tracing Library page.
- Adds Experimental features section.
- Per Irene, we want to document experimental settings but not legacy settings.
> [DOCS-5132] Document Experimental Open Telemetry Setting

- .gitlab-ci.yml
Removes the live TMs job from the CI. We are running this same test on branches/PRs against changed files. With the size of Docs now and the additional languages, this live job checks the whole site over again which has been timing out the runners. This test is redundant since we perform this check on the branches/PRs.
> Remove live TMs job

- content/en/continuous_integration/quality_gates/_index.md
We have removed support of `DATADOG_*` environment variables from the `datadog-ci gate` command.
https://github.com/DataDog/datadog-ci/pull/1067
> Use "DD_*" environment variables in the quality gates page

- content/en/continuous_integration/intelligent_test_runner/java.md
This change updates CI Visibility Intelligent Test Runner documentation for Java.
Upcoming tracer release will introduce "unskippable tests" feature that will allow to mark specific tests or suites to make sure Intelligent Test Runner never skips them.
A section describing this new feature is added to the Java ITR page.
This PR should be merged after DD Trace Java v1.22.0 is released.
> Add unskippable tests documentation for Java ITR

- content/en/account_management/billing/aws.md
- Add a subsection and information about billing considerations with the [Metric Streaming through Kinesis Data Firehose](https://docs.datadoghq.com/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose/?tab=cloudformation#streaming-vs-polling) metric collection approach
- Add an additional subsection for multiple pieces of information related to EC2 billing considerations
> (DOCS-6205) Add resource exclusion subsections

- content/en/database_monitoring/setup_oracle/_index.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
- Update the version
- Add support for the Oracle non-CDB architecture
- Recommend customers not installing an official release lower than `7.49.0`
- Update the activity view definition
> Update the Oracle setup document to 7.41.1-oracle-dbm-0.2

- content/en/api/_index.md
Turns out the frontmatter in the API docs is overwritten by updates to the API spec, so this is the only way for redirects to stick.
These should redirect once the build completes:
- [https://docs-staging.datadoghq.com/heston/more-redirects/api/latest/downtimes/s](https://docs-staging.datadoghq.com/heston/more-redirects/api/latest/downtimes/s)
- [https://docs-staging.datadoghq.com/heston/more-redirects/api/screenboards/](https://docs-staging.datadoghq.com/heston/more-redirects/api/screenboards/)
> (DOCS-5834) Fix API redirects

- content/en/tracing/trace_collection/trace_context_propagation/python.md
We've had `b3` propagations style deprecated and suggested `b3multi` for some time. With Python tracer version 2.0.0 we remove `b3` propagation style, therefore we should remove it here as well, and customers should use `b3multi` instead.
> Update python.md b3 propagation style configs

- config/_default/menus/menus.en.yaml
- content/en/data_security/kubernetes.md
Adds a **Data Security > Kubernetes** page, linked to in both Data Security and Containers > Kubernetes sections.
> [DOCS-6199] adding k8s data security page

- content/en/network_monitoring/dns/_index.md
There has been some confusion from customers about the timeout shown in NPM DNS monitoring. This PR attempts to add more details on how these timeouts differ from timeouts reported by other non-NPM products.
> Make timeouts clearer for NPM DNS monitoring

- content/en/real_user_monitoring/ios/advanced_configuration.md
- content/en/real_user_monitoring/ios/mobile_vitals.md
- content/en/real_user_monitoring/ios/troubleshooting.md
DOCS-6286
Fixes some 404ing links to an external repo.
> Fix GitHub links to RUM iOS SDK repo

- content/en/profiler/profile_types.md
- content/en/tracing/trace_collection/library_config/php.md
With https://github.com/DataDog/dd-trace-php/pull/2197 we merged exception profiling for PHP into the profiler. This will be released with version `0.92.0`.
Goal is to document the new feature with environment variables and INI settings.
Do not merge as long as `0.92.0` is not released.
> Add PHP exception profiling to docs

- content/en/profiler/profile_types.md
- content/en/tracing/trace_collection/library_config/php.md
With PHP 8.1.21 and 8.2.8 there is now a fix for the JIT vs. allocation profiling topic, so in the PHP Profiler `0.92.0` we'll release an update that allocation profiling will be active despite JIT being enabled for PHP >= 8.1.21 and >= 8.2.8.
This PR should only be merged after `dd-trace-php` in version `0.92.0` got released.
Related PR in the profiler is https://github.com/DataDog/dd-trace-php/pull/2246
> document patched versions for PHP allocation profiling

- content/en/observability_pipelines/setup/datadog.md
- content/en/observability_pipelines/setup/splunk.md
Customers have observed that the Terraform module for OPW has incorrect install instructions. This PR corrects that.
> Update the docs to note correct Terraform usage.

- content/en/monitors/downtimes/_index.md
- content/ja/monitors/downtimes/_index.md
Fix the link in Downtimes documentation page to not link to a "Not found" page.
> Fix links to Manage Downtimes page

- content/en/containers/amazon_ecs/_index.md
Update version of FIPS Proxy since a new FIPS Proxy version has been released
https://docs-staging.datadoghq.com/nicolas.guerguadj/ecs-fips-0.6.0/containers/amazon_ecs/?tab=awscli#fips-proxy-for-govcloud-environments
> Update FIPS proxy version to 0.6.0

- layouts/multi-code-lang/single.html
Certain types of imported content had tables that were too wide for the page, and the nature of the generated markdown meant that they didn’t get wrapped in the div necessary to make the tables side-scroll: https://datadoghq.atlassian.net/browse/WEB-4102
It seemed appropriate to me to try to resolve this at build time instead of using front-end scripting, so I used regex on the appropriate template to add in the wrapping div.
https://docs-staging.datadoghq.com/fitzage/table-fix/tracing/trace_collection/dd_libraries/ruby/#grpc
> add wrapper to tables in imported libraries

- content/en/integrations/adobe_experience_manager.md
- content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
- content/en/integrations/guide/cloud-metric-delay.md
- content/en/integrations/syslog_ng.md
Adds region-specific messaging for integrations
NOTE: the `adobe_experience_manager` and `syslog_ng` integration readmes have been updated. both of these integrations live in the docs repo (this one)
> DOCS-5743 - region-specific messaging for integrations

- assets/scripts/components/copy-code.js
- layouts/shortcodes/dashboards-widgets-api.html
adds copy button to `json` and `yaml` code blocks throughout  docs.
fix duplicate copy button rendering from the **dashboards-widget-api** shortcode.
**Motivation:** https://datadoghq.atlassian.net/browse/WEB-4048
Hover over code examples to see the copy button. click the copy button to copy to clipboard. ensure code example can be pasted.
- json ex : https://docs-staging.datadoghq.com/stefon.simmons/copy-json-yaml-fenced/integrations/guide/aws-manual-setup/?tab=roledelegation#aws-integration-iam-policy
- json ex from pulled integration (.gitignored): https://docs-staging.datadoghq.com/stefon.simmons/copy-json-yaml-fenced/integrations/amazon_elasticbeanstalk/?tab=multiplecontainers#datadog-agent-configuration
- yaml ex: https://docs-staging.datadoghq.com/stefon.simmons/copy-json-yaml-fence …
> add json and yaml copy buttons - [WEB-4048]

- layouts/shortcodes/dbm-postgres-agent-config-examples.md
- layouts/shortcodes/dbm-sqlserver-agent-config-examples.md
DOCS-6314
Use more generic hosts in examples, since the example configs are used across RDS, AWS, etc. setup guides.
> Use generic hosts in examples

- content/en/continuous_integration/pipelines/_index.md
- content/en/infrastructure/containers/kubernetes_resource_utilization.md
- content/en/monitors/types/_index.md
- content/en/tracing/troubleshooting/correlated-logs-not-showing-up-in-the-trace-id-panel.md
- content/ja/containers/kubernetes/apm.md
- content/ja/service_management/events/guides/_index.md
Adds page aliases flagged by the 404 URL Dashboard.
> Add EN and JA Aliases

- content/en/monitors/types/error_tracking.md
Add a note clarifying that Error Tracking "count" monitors on APM spans only work for spans retained by custom retention filters. Basically the same note as https://docs.datadoghq.com/monitors/types/apm/?tab=traceanalytics#monitor-creation but for Error Tracking monitors.
> ET count monitors on APM work only w/ retention filters

- content/en/logs/guide/collect-heroku-logs.md
Remove a mention on a log guide for Heroku integration. This integration has been available for a while, and this mention should not be present anymore.
> Remove beta mention from Heroku

- content/en/infrastructure/process/_index.md
In previous versions of the agent, `process_config.enabled` was indeed a string. This was updated to be a boolean in 7.35 (https://github.com/DataDog/datadog-agent/pull/10555).
> [processes] Update enablement config value

- data/partials/home.yaml
Add incident management tile to the docs landing page, this was requested by the PM
[DOCS-6307](https://datadoghq.atlassian.net/browse/DOCS-6307)
[DOCS-6307]: https://datadoghq.atlassian.net/browse/DOCS-6307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add incident management tile to the docs landing page

- content/en/tracing/guide/ignoring_apm_resources.md
https://datadoghq.atlassian.net/browse/DOCS-4810
* Support noted customer confusion around tag filter syntax.
* Also, there is a lack of Kubernetes Helm examples for ignoring based on span tags.
To resolve:
* Fixed error stating that you can specific span tags to require or reject with a **comma-separated list** in env vars. Tags should be separated by a space, as shown in the example that @ajgajg1134 fixed a few weeks ago (thanks!).
* Added tabs similar to the Ignoring based on resources further down the page. Other than the structure, the only new content is the addition of Kubernetes Helm specific instructions/examples.
> [DOCS-4810] Adjust ignoring based on span tags content

- content/en/tracing/guide/inferred-service-opt-in.md
add message warning about potential monitor update if inferred service names changes
> Update inferred-service-opt-in.md to add notes about updating monitors

- content/en/real_user_monitoring/error_tracking/_index.md
I believe there is a mistake in a sub-title on the [`/real_user_monitoring/error_tracking`](https://docs.datadoghq.com/real_user_monitoring/error_tracking/#upload-crash-reports) page
None
> Fix mistake in subtitle on /real_user_monitoring/error_tracking

- content/en/serverless/aws_lambda/configuration.md
This PR adds the word identifiers to the source type column in the table here:
https://docs.datadoghq.com/serverless/aws_lambda/configuration/?tab=datadogcli#rename-upstream-service-names
This came from feedback from transifex where it was causing confusion in our Japanese translated pages.
From the SME:
```
General is meant to be “General Identifiers” and Specific is meant to be “Specific Identifiers”. For instance if the call always goes through the "xyz" gateway before reaching the downstream service, this would be better to use instead of the lambda_api_gateway key
```
> AWS lambda: clarifying source type per transifex feedback

- content/en/agent/remote_config/_index.md
Use `remoteConfiguration.enabled` instead of `datadog.remoteConfiguration.enabled` as it's prefered. 
See: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L1958C1-L1962C16
> Use remoteConfiguration.enabled

- content/en/monitors/notify/variables.md
This update includes all additional variables that display as available variables when building an Event Monitor.
This brings the documentation into parity with the information provided in DD's event monitor page:
> Update first level attributes for Event in variables.md

- config/_default/menus/menus.en.yaml
- content/en/account_management/rbac/_index.md
- content/en/account_management/rbac/granular_access.md
https://datadoghq.atlassian.net/browse/DOCS-6186
- Moves the section on granular access to its own page for ease of reading and clearer organization.
- Adds an introduction to the RBAC page to describe the different ways you can control access to Datadog resources.
- Adds instructions for the private beta feature of gaining access to restricted resources for admins.
In the future, I plan to create a top-level "Access" page with the introduction, and have RBAC, Granular access, and Permissions as child pages of "Access". That reorganization requires moving the approximately 150 incoming links to the RBAC page, so I'm deferring that work until December when I anticipate I'll have more time.
> Move granular access to its own page

- content/en/containers/kubernetes/installation.md
This PR addresses hotjar feedback where the reader pointed out that the `--name` flag was deprecated on Helm `v3`, the docs stated "for Helm < v3.. use.." (Helm version _less than v3_) the use of the greater than; less than signs can cause confusion, so added clarification that if the reader is using Helm `v2.x` they need to use the `--name` flag. 
Helm `v1.x` is deprecated so no need to say "lower than v3".
> [DOCS-6328] clarifying lower helm versions

- content/en/observability_pipelines/setup/datadog.md
This fixes a small bug in the configuration provided for the Terraform module.
> Add a small fix to the Terraform sample config.

- content/en/monitors/manage/search.md
It updates the docs on the use of wildcards in monitor search to reflect that we now support single character wildcards.
> Update docs on use of wildcards in monitor search

- layouts/shortcodes/appsec-getstarted-with-rc.md
[DOCS-6372](https://datadoghq.atlassian.net/browse/DOCS-6372)
This PR removes the Beta verbiage from the How to enable ASM page and it's relevant library pages , via a reuse shortcode. I elected to keep the banner as it's a nice callout, but just removed the word beta as this feature has been in GA for awhile now and this got missed.
[DOCS-6372]: https://datadoghq.atlassian.net/browse/DOCS-6372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6372] removing Beta from ASM libraries pages

- content/en/security/application_security/enabling/compatibility/php.md
PHP ASM is not compatible with PHP 5.x, this was updated yesterday, however there still remains a note which could cause confusion. This PR removes said note.
> Remove note about ASM compatibility with PHP 5x

- content/en/dashboards/_index.md
Mentions the Universal Access Indicator feature which is a header change on dashboards that tells you if you're a viewer, how you can get edit access (if you're missing the capability and/or granular permission)
We're ready to GA this whenever the public docs are ready to be merged! (So probably in a few days)
My main question is for @urseberry , if my change makes sense? (I thought creating a different section, not under Permissions might be too much? I also thought about adding a single screenshot but thought that might be too much.)
> [ACCESS-1903] Add UAI mention to dashboards public docs under permissions

- content/en/database_monitoring/connect_dbm_and_apm.md
This phrase is nested under the .NET tab, when it should apply to any SQL Server datastores. This change moves it higher up in the doc so that it's more accurate and easier to find.
SQL Server does not support full propagation mode due to the inability for the server to cache statements which contain full trace context.
> Move SQL Server propagation blurb higher up

- content/en/account_management/rbac/permissions.md
On WEB-3821, Stefon added information to the permissions table about which OOTB role has that permission by default. I took an action item to add a line to the page explaining that more powerful roles also get all of the permissions from the less powerful ones, since it's not obvious from the table.
While thinking about where to add the line, I noticed that the introduction to the permissions page could use better organization and additional explanation.
This PR reorganizes and adds explanation to the permissions page introduction. It also adds information about how more powerful OOTB roles inherit all of the permissions of the less powerful ones.
> Rewrite introduction to permissions page

- content/en/tracing/trace_collection/custom_instrumentation/go.md
https://datadoghq.atlassian.net/browse/DOCS-2071
* The Go tracing library is unique in that users need to manage and pass span context manually.
* Added a note to the _Adding spans_ to make sure users are aware before they dive into the docs that follow.
* Linked to Go context library docs.
> [DOCS-2071] Clarify context passing for Go

- content/en/profiler/enabling/ruby.md
Starting with `ddtrace` 1.15.0, the Ruby profiler no longer needs the `google-protobuf` dependency. Thus, I've updated the docs to reflect that.
I did keep a reference to it, assuming that some customers may already have an older `ddtrace` and may want to add profiling to it without upgrading -- feedback welcome on the wording there (or if we don't usually do this kind of reference, we could drop it as well -- the library does have a good error message saying that `google-protobuf` is needed, so customers would spot it quickly).
The 1.15 review is planned to go out on monday, so I've not checked the "merge after reviewing" box.
> Ruby profiler: Remove `google-protobuf` as needed dependency

- assets/scripts/components/grouped-item-listings.js
Add question mark operator to `searchQuery` variable definition statement to resolve js console error `Uncaught TypeError: Cannot read properties of null (reading 'value')`.
Restores tab queryParam functionality when selecting elements from the left side nav.
https://datadoghq.atlassian.net/browse/WEB-4139
https://docs-staging.datadoghq.com/brooklyne.finni/tabs_fix
Navigate to the CSM setup page /security/cloud_security_management/setup/?tab=csmenterprise and select `CSM Workload Security`. The tabs query parameter should be appended to the url and the tabs should be displayed above the code block(s).
Test several other links from the left side nav and ensure that tabs query parameter is appended to the url and that the tabs and tab content appear as expected
> [WEB-4139]Update grouped-item-listings.js

- content/en/tracing/service_catalog/_index.md
Updating Service Catalog documentation to include information about new Cloud Costs lens
> Adding information about new Costs lens

- content/en/tracing/trace_collection/compatibility/python.md
Updates Python compatibility docs to reflect Elasticsearch 8 and OpenSearch support.
Wait for merge/release of https://github.com/DataDog/dd-trace-py/pull/7113
> Update python compatibility to include ES8 and OpenSearch

- content/en/cloud_cost_management/container_cost_allocation.md
This adds instructions for enabling Labels as tags, in order to add labels as tags on cost metrics.
> [CCM] add links to Labels as tags configuration

- content/en/security/application_security/enabling/compatibility/_index.md
- content/en/security/application_security/enabling/compatibility/dotnet.md
- content/en/security/application_security/enabling/compatibility/go.md
- content/en/security/application_security/enabling/compatibility/java.md
- content/en/security/application_security/enabling/compatibility/nodejs.md
- content/en/security/application_security/enabling/compatibility/php.md
- content/en/security/application_security/enabling/compatibility/python.md
- content/en/security/application_security/enabling/compatibility/ruby.md
- layouts/shortcodes/asm-protection-page-configuration.md
Add specific examples per language on how to configure ASM blocking responses. 
Also, adds the compatibility information per language and on the index page
The growing numbers of Ruby customers trying to configure the blocking responses using a tracer version that doesn't support such feature
---
> Add specific language examples on how to configure the ASM blocking responses and compatibility version

- content/en/continuous_integration/intelligent_test_runner/setup/dotnet.md
This PR adds the  documentation for the `unskippable tests` feature in the Intelligent Test Runner for .NET section.
> [CI Visibility] ITR .NET unskippable tests

- content/en/service_management/service_level_objectives/_index.md
This PR removes `(beta)` tags from the SLO page now that user and team based access controls are available to all customers. Similar to https://github.com/DataDog/documentation/pull/20072.
> Remove granular access beta tags from SLO page

- content/en/integrations/guide/source-code-integration.md
Preview: https://docs-staging.datadoghq.com/ronan/sci-improvements/integrations/guide/source-code-integration/?tab=go
Various improvements to the Source Code Integration setup guide:
- Clarify wording: `Link active commits` -> `Tag your telemetry with Git information`, and `Configure your repositories` -> `Synchronize your repository metadata`
- Move `Embed git information in your artifacts on CI` first (since it should be the method we encourage for supported languages), with a short introduction sentence explaining what it does.
- Clarify what repo metadata sync does, what we do and do not store
- For on-prem repositories, mentioned that it's not supported _out of the box_, but added a mention to reach out to support since we still want to track feature requests, and we're able to …
> Source Code Integrations docs improvements

- content/en/tracing/trace_explorer/visualize.md
Corrects a spelling error in the sentence "the data is omitted to avoid displaying inconsistent **of** misleading latency information" to "the data is omitted to avoid displaying inconsistent **or** misleading latency information"
> Correct spelling mistake: "of" instead of "or"

- config/_default/menus/menus.en.yaml
- content/en/tracing/other_telemetry/_index.md
Links profiler page on traces/profiles integration use cases into APM docs on correlating with other telemetry types.
> [DOCS-3899]Add profiler to list of "other telemetry" you can connect traces to

- content/en/watchdog/insights.md
Translator was confused about "lock pressure", which is the same as "lock contention" and shown in the UI, so updating the docs to say "lock contention" instead.
> Update lock pressure wording

- content/en/monitors/guide/change-alert.md
Appears the the values in the table below are the reverse of what is in the screenshot.
Correct error in docs
> Swap values to reflect image

- content/en/observability_pipelines/setup/datadog.md
- content/en/observability_pipelines/setup/splunk.md
- static/resources/yaml/observability_pipelines/datadog/aws_eks_rc.yaml
- static/resources/yaml/observability_pipelines/datadog/azure_aks_rc.yaml
- static/resources/yaml/observability_pipelines/datadog/google_gke_rc.yaml
- static/resources/yaml/observability_pipelines/helm/storageclass.yaml
- static/resources/yaml/observability_pipelines/splunk/aws_eks_rc.yaml
- static/resources/yaml/observability_pipelines/splunk/azure_aks_rc.yaml
- static/resources/yaml/observability_pipelines/splunk/google_gke_rc.yaml
This PR adds two important things to the installation of OPW in Kubernetes environments:
* In EKS environments, the EBS driver is also required for buffers, as well as a `StorageClass` that is compatible with the OPW charts. I've included links to the necessary resources here.
* In addition, for remote configuration installs, ports must be manually specified in the Helm charts. Otherwise, no Load Balancer will be created at all.
> Add some better installation notes for OP in K8s

- content/en/observability_pipelines/setup/_index.md
We are introducing a new toggle in the UI that let's the users to have switch between deployment methods - manual vs remote config (https://a.cl.ly/NQu5J87q). Only users enrolled in remote config are affected but we will be rolling this update out next week. We are updating the docs so that the affected users understand specific edge cases when we roll this out
> Update _index.md to reflect UI updates for RC next week

- content/en/network_monitoring/devices/netflow.md
We support jFlow as part of NetFlow monitoring now - this is also reflected in our pricing page. Proposing this update to keep the NDM page up to date.
> Add jFlow as a supported NetFlow protocol.md

- content/en/dashboards/widgets/alert_graph.md
Specify that query alerts are supported for the Alert Graph widget. It's not supported for trace analytic monitors and service check-based Integration monitors. 
[https://docs-staging.datadoghq.com/dan.chiniara/specify-query-alert-for-alert-graph-widget/dashboards/widgets/alert_graph](https://docs-staging.datadoghq.com/dan.chiniara/specify-query-alert-for-alert-graph-widget/dashboards/widgets/alert_graph)
> dan.chiniara/specify query alert for alert graph widget

- content/en/developers/integrations/python.md
Update docs to loosely match https://datadoghq.dev/integrations-core/setup/#ddev
> Update Agent Integrations developer setup page

- content/en/serverless/google_cloud_run/_index.md
Adds a note to configure the `DD_TRACE_PROPAGATION_STYLE` envvar so that context propagation and log trace correlation work with the W3C header implemented earlier this year.
> DOCS-6388 - update serverless GCR docs with dd_trace_propagation_style

- content/en/security/application_security/enabling/dotnet.md
- content/en/security/application_security/enabling/go.md
- content/en/security/application_security/enabling/java.md
- content/en/security/application_security/enabling/nodejs.md
- content/en/security/application_security/enabling/php.md
- content/en/security/application_security/enabling/python.md
- content/en/security/application_security/enabling/ruby.md
This PR adds an H2 to the right nav of each of the ASM library pages to make it easier for a customer to differentiate how to configure ASM threat detection vs ASM code-level vulnerabilities relative to each library, as it was causing confusion to the user. 
- [] Please merge after reviewing
- Do not merge, waiting for PM approval
> [DOCS-6331] updating ASM library pages with right nav for threat detection

- static/resources/yaml/observability_pipelines/quickstart/aws_eks_rc.yaml
- static/resources/yaml/observability_pipelines/quickstart/azure_aks_rc.yaml
- static/resources/yaml/observability_pipelines/quickstart/google_gke_rc.yaml
This adds a `datadog_agent` source-compatible port to the load balancers we provision for the quickstart use case. This should make it easier to hook up the customers' Datadog Agents to OPW should they go down this installation path.
> Add ports to the quickstart Helm charts.

- content/en/database_monitoring/guide/pg15_upgrade.md
- content/en/database_monitoring/setup_postgres/_index.md
As we're wrapping up testing of Postgres 15 on Google Cloud SQL, this marks it as a supported configuration for DBM and also notes a few recommended configurations to help with the upgrade.
> DBMON-2973 Mark support for Postgres 15 on Google Cloud SQL

- content/en/serverless/google_cloud_run/_index.md
This PR removes a section from the Java tab under Serverless -> Google Cloud Run that isn't relevant. 
Verified with @ceciliawatt
> Update Serverless -> Google Cloud Run Java section 

- content/en/profiler/connect_traces_and_profiles.md
Code Hotspots is moving to public beta for Node.js, so Node.js language-specific sections are required for both it and the related Endpoint profiling feature.
The failing prose check seems to be finding false positives in markup, not actual prose.
> Document Code Hotspots (beta) for Node.js

- .gitlab-ci.yml
- Bumps the timeout to 1h 30m for the algolia sync jobs.    The current job has been timing out: https://dd.slack.com/archives/C3CT8QA11/p1697665327071059
> Bumps timeout for Algolia sync jobs

- data/partials/home.es.yaml
- data/partials/home.fr.yaml
- data/partials/home.yaml
update integrations number from 600 to 650+
https://datadoghq.atlassian.net/browse/WEB-4125
Do not merge right away. Stakeholder will give green light and I will notify docs team.
https://docs-staging.datadoghq.com/renzo.renteria/update-integrations-number/
> update integrations number to 650+

- .github/workflows/synthetics.yml
Bumps the timeout of synthetics action to 15 minutes based on the average docs preview build time found [here](https://dd-corpsite.datadoghq.com/dashboard/4jg-n7c-9kt/pipeline-durations?refresh_mode=sliding&from_ts=1697718816524&to_ts=1697733216524&live=true)
> WEB-4165 | update timeout for preview check on synthetics

- content/en/tracing/trace_collection/library_injection_local.md
- There are two "Configure Docker injection" headings on this page, which prevents us from linking to the sections correctly.
- The links function, but the page doesn't scroll to the heading.
- As a workaround, we can change the anchor so that each section has a unique anchor id.
- I already verified that we only link to this heading in the "Agent and app in separate containers" tabs, so it should be ok to change the one in "Agent on host, app in containers".
> [DOCS-6354] Rename duplicate anchor to fix page scroll

- content/en/tracing/troubleshooting/tracer_debug_logs.md
Adds similar docs to the other language tracers to enable debug logs using environment variables, since it's been supported for a while.
> tracer_debug_logs.md: Add env variable for Go tracer

- content/en/continuous_integration/tests/setup/junit_xml.md
When using Bash that comes with Git for windows command line arguments like `--xpath-tag=test.suite=/testcase/@classname` are converted to `--xpath-tag=test.suite=C:/Program Files/git/testcase/@classname`
Feel free to update the formating if needed.
I think that it helps to raise this issue in the documentation as many arguments start with a slash.
> Add info about Git for Windows path expansion

- .gitlab-ci.yml
- local/bin/js/algolia-index-sync.js
https://datadoghq.atlassian.net/browse/WEB-4172
- Instead of re-indexing all languages on every `master` push, this only updates the English records.   The full index (including all languages) will be re-indexed as part of the nightly scheduled build.    This makes the Algolia job run much faster after each `master` pipeline - from 1hr+ to [6 minutes in the most recent preview run](https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/354081782).
- The Algolia sync indexing job [has been timing out lately](https://dd.slack.com/archives/C3CT8QA11/p1697665327071059).   With Docs scaling / addition of new languages we've seen the indexing times getting slower.    We will continue to work on delivering solutions that improve indexing performance.
> [WEB-4172] Re-index only English pages on master pipelines; full Algolia index during nightly build

- content/en/real_user_monitoring/guide/sampling-browser-plans.md
Describe the new v5 capability of having sessions that reach a certain state to be considered as Browser RUM & Session Replay.
Document the answer given here: https://github.com/DataDog/browser-sdk/issues/1967#issuecomment-1768738309
> Update RUM & Replay sampling guide

- general.preview.synthetics.json
adds the following synthetic tests to the github actions pipeline. these tests run on every docs pull request:
[[bqt-kt3-zvy](https://dd-corpsite.datadoghq.com/synthetics/details/bqt-kt3-zvy?from_ts=1698064231603&to_ts=1698067831603&live=true)] "[DOCS] [Glossary] Should filter terms by product selection"
[[d6h-28c-ij9](https://dd-corpsite.datadoghq.com/synthetics/details/d6h-28c-ij9?from_ts=1698064298935&to_ts=1698067898935&live=true)] "[DOCS] [Glossary] Should filter on page load"
[[dbg-37u-r55](https://dd-corpsite.datadoghq.com/synthetics/details/dbg-37u-r55?from_ts=1698064379255&to_ts=1698067979255&live=true)] "[DOCS] [Glossary] Should add filter value to url params"
See that pipeline and `synthetic_testing` job ran successfully: …
> add glossary tests to github action

- content/en/tracing/trace_collection/library_config/java.md
- content/en/tracing/trace_collection/library_injection_local.md
https://datadoghq.atlassian.net/browse/DOCS-6244
- Add `dd.trace.rate.limit` to Java library docs.
- Note support for this in local library injection docs too.
I need someone from the Java team to verify before merging.
> [DOCS-6244] Add Rate Limit Setting to Java Docs

- content/en/tracing/trace_collection/compatibility/java.md
Update the supported Vert.x versions to reflect recent changes in the Java tracer
See https://github.com/DataDog/dd-trace-java/pull/3557
Web - https://github.com/DataDog/dd-trace-java/pull/3557
Cassandra - https://github.com/DataDog/dd-trace-java/pull/2156
MySQL - https://github.com/DataDog/dd-trace-java/issues/5716
> Update supported vertx versions

- content/en/security/infrastructure_vulnerabilities/setup.md
Since the pull request https://github.com/DataDog/helm-charts/pull/1116 has been merge is simpler to configured the container image and host infrastructure vulnerabilities feature in the Datadog Agent thanks to the helm chart.
Since the pull request https://github.com/DataDog/helm-charts/pull/1116 has been merge is simpler to configured the container image and host infrastructure vulnerabilities feature in the Datadog Agent thanks to the helm chart.
this Pull request update the helm chart instruction for configuring the  infrastructure vulnerabilities feature in the Datadog helm chart.
> Update Infra vulnerability setup documentation

- content/en/account_management/billing/usage_metrics.md
Adding the estimated usage metric for Observability Pipelines to our usage documentation. I think this will need to be added to the translated pages. Who would take care of that?
> Add estimated usage metric for Observability Pipelines to the docs

- content/en/integrations/kubernetes_state_core.md
- content/ja/integrations/kubernetes_state_core.md
The `kubernetes_state.container.status_report.count.waiting` and `kubernetes_state.container.status_report.count.terminated` are duplicated in the documentation https://docs.datadoghq.com/integrations/kubernetes_state_core
They are correct here: https://github.com/DataDog/integrations-core/blob/master/kubernetes_state_core/metadata.csv
English and Japanese documentations updated. Korean documentations seems to be automatically generated.
> [kubernetes_state_core] Fix duplicated kubernetes_state metrics

- content/en/tracing/trace_collection/dd_libraries/python.md
We now support 3.11, per mentioned here: https://docs.datadoghq.com/tracing/trace_collection/compatibility/python/ and here: here:https://ddtrace.readthedocs.io/en/stable/versioning.html#supported-runtimes Not having the latest information in this page has caused confusion for some customers.
We now support 3.11, per mentioned here: https://docs.datadoghq.com/tracing/trace_collection/compatibility/python/ and here: here:https://ddtrace.readthedocs.io/en/stable/versioning.html#supported-runtimes Not having the latest information in this page has caused confusion for some customers.
> Update the latest python runtime version that the dd-tracer supports

- content/en/containers/amazon_ecs/_index.md
New version of FIPS Proxy was released
https://docs-staging.datadoghq.com/nicolas.guerguadj/ecs-fips-0.6.1/containers/amazon_ecs/?tab=awscli#fips-proxy-for-govcloud-environments (US1-Fed site)
> Update FIPS proxy version to 0.6.1

- content/en/database_monitoring/_index.md
Oracle was missing from the overview statement for the types of databases supported even though its shown in the graphical list below
Adds Oracle to the listed text
> Add Oracle to Getting Started overview text

- layouts/shortcodes/aws-permissions.md
Add TransitGateway actions to the AWS permissions shortcode
> (DOCS-6514) Add TransitGateway actions

- content/en/database_monitoring/setup_postgres/gcsql.md
This adds postgres 15 to the list of supported postgres versions in the Google Cloud SQL setup docs page. We missed it when adding support for Postgres 15 on Cloud SQL.
> Add Postgres 15 to supported versions in the Google Cloud SQL Setup Docs Page

- content/en/account_management/billing/usage_metrics.md
- Add reference links for metric monitors and log example showing usage monitor alerts.
- [DOCS-6259](https://datadoghq.atlassian.net/browse/DOCS-6259)
[DOCS-6259]: https://datadoghq.atlassian.net/browse/DOCS-6259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add reference links for metric monitors and logs best practices

- content/en/logs/log_configuration/archives.md
Log Archives is supported in Gov. Removing note.
> Remove gov note from Log Archives

- layouts/partials/integrations-logo.html
This PR removes the warning messages we had for svgs that weren't found. 
Lets revisit other ways to identifiy these and reduce noise in the build logs.
> build disable svg warnings

- .gitlab-ci.yml
Sets some build flags so that the artifacts uploaded at the end of a job are completed faster
Completing in roughly 30s versus the current 2-3mins
We've had the same flags on corp for almost 2yrs without any negative impact
> set artifact compression flags

- content/en/real_user_monitoring/heatmaps/_index.md
Updated to reflect scroll maps and click maps are now two words
> heatmaps-rebranding.md

- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md
Document support for the new architecture of React Native, upcoming in release `1.8.0` of the React Native SDK.
There is no additional step required to use the SDK with the new architecture.
---
> Add React Native new arch support

- assets/styles/components/_integrations.scss
fixes distorted images on integration carousels
motivation: https://datadoghq.atlassian.net/browse/WEB-4203
click into an [integration](https://docs-staging.datadoghq.com/stefon.simmons/fix-integration-carousel-images/integrations/), check that images in the carousel are not stretched.
example pages:
- https://docs-staging.datadoghq.com/stefon.simmons/fix-integration-carousel-images/integrations/yugabytedb_managed/
- https://docs-staging.datadoghq.com/stefon.simmons/fix-integration-carousel-images/integrations/agentil_software_services_5_days/
> fix distorted images on integration carousels - [WEB-4203]

- content/en/security/misconfigurations/frameworks_and_benchmarks.md
Adds NIST Cybersecurity Framework 1.1 to list of supported frameworks for CSM Misconfigurations.
> Add NIST Cybersecurity Framework 1.1

- content/en/agent/configuration/agent-fips-proxy.md
Add reference to the new Agent diagnose CLI in the FIPS instructions
https://docs-staging.datadoghq.com/nicolas.guerguadj/update-diagnose-reference-in-fips-docs/agent/configuration/agent-fips-proxy/?tab=hostorvm#agent-is-unable-to-connect-to-the-proxy
> Add reference to the new diagnose command in the fips documentation

- content/en/tracing/trace_collection/library_config/java.md
Add `dd.jmxfetch.<integration-name>.enabled` / `DD_JMXFETCH_<INTEGRATION_NAME>_ENABLED`
Seems like the pre-commit hook made changes, the only manual change is line 256-260.
> Add Ddd.jmxfetch.<integration-name>.enabled to java docs

- content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/reactnative.md
Document release for React Native SDK v2. It includes:
- updated instructions for installing the SDK
- migration guide for users migrating from v1
- troubleshooting steps
> Document React Native SDK v2

- content/en/database_monitoring/setup_sql_server/_index.md
DOCS-6651, SQL Server 2022 was not in the support table on the DBM setup page for SQL Server.
> Add SQL Server 2022 to the support table

- content/en/serverless/guide/serverless_tracing_and_bundlers.md
Update documentation adding AWS SDK v3 and fix regex expression for AWK SDK for webpack
- Updating documentation to handle AWS SDK v3
- Fixing Webpack exclude list using regex to pick up exclusions
> Updating serverless_tracing_and_bundlers.md documentation to AWS SDK v3 and fixing documentation

- content/en/tracing/metrics/_index.md
Clarify that the two types of APM metrics are different in that trace metrics are calculated in the Datadog Agent whereas runtime metrics are calculated in the tracer library.
> apm: clarify default apm metric collection

- content/en/dashboards/widgets/log_stream.md
- Redirect customers using the log stream widget to the List widget page.
- Log stream is not an individual widget offered on the Dashboard, you can access this functionality through the list widget.
- Change requested by the Dashboard PM
> Redirect users to the list widget

- content/en/database_monitoring/setup_postgres/azure.md
The ssl: parameter no longer uses boolean, but string values. "ssl: true" should now be "ssl: 'require'" in code examples.
The ssl: parameter no longer uses boolean, but string values. "ssl: true" should now be "ssl: 'require'" in code examples.
> Update azure.md for new ssl values

- content/en/real_user_monitoring/session_replay/_index.md
This PR specifies that before v5 of the RUM Browser SDK, which starts Session Replay recordings automatically, that the Session Replay recorder must be started manually
> Specify that Session Replay recordings need to be started manually before v5

- content/en/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum.md
Current instructions for NextJS integration prevent server rendering.
Fixing it to prevent others from struggling with it.
I also found the tip in [here](https://rafaassad.medium.com/integrate-datadog-with-nextjs-591fe126e339) useful, so I included the `NEXT_PUBLIC_`'s one.
> [RUM-sdk][NextJs] Fixes SSR for NextJS13+

- content/en/agent/basic_agent_usage/windows.md
- content/en/agent/faq/agent-downgrade-major.md
- content/en/agent/versions/upgrade_to_agent_v7.md
Updating all links in documentation to use new installers_v2 link to prepare for deprecation of the old link.
https://datadoghq.atlassian.net/browse/WINA-451
> Swap windows installers json link to new one

- content/en/developers/ide_integrations/idea/_index.md
Update the docs to mention that PyCharm is now available and that View in IDE is supported for not only for Java.
> IDE integrations: Mention support for PyCharm and GoLand

- content/en/tracing/service_catalog/setup.md
add inferred service mention to service catalog page
add private beta signup form to service catalog overview
> Update service catalog setup.md

- .gitlab-ci.yml
- config/_default/config.yaml
- layouts/_default/list.algolia.json
- layouts/partials/grouped-item-listings.html
- layouts/partials/header/header.html
- layouts/partials/nav/left-nav-api.html
- layouts/security_rules/single.html
- layouts/shortcodes/integrations.html
- layouts/standard-attributes/list.html
This PR improves performance of the hugo build step
- Cache logo lookups 18s down to 10s cumulative
- left nav api lookups 15s down to <1s cumulative
- defer algolia json creation on preview
- using fileexists over getpage on security_rules/single saves 5s cumulative
- Cache header main nav from websites modules. On docs the top main nav doesn't change page to page.
- Sets `disableSVG: true` for hugo minification of html. This is due to the fact it was modifying svg values in the html unnecessarily this in turn causing us to deploy html files that hadn't really changed.
Showing the hugo build at around 1 min instead of 3-4 mins
- Check logos appear normal on https://docs-staging.datadoghq.com/david.jones/micro-perf/integrations/
- Check left nav on api appears normal …
> hugo micro perf updates

- config/_default/menus/menus.en.yaml
- content/en/account_management/scim/_index.md
- content/en/account_management/scim/azure.md
Datadog now supports SCIM with Okta. When there was only 1 identity provider (Azure), it made sense for all SCIM info to be on one page. Now that there are two, this PR puts Azure on its own page so it's easier to add Okta next.
No new text, just menu updates and moving text onto the new page. I did also add a Further reading section to the main SCIM page.
> Move Azure setup instructions to be a subpage of SCIM

- content/en/real_user_monitoring/browser/monitoring_page_performance.md
Note that RUM SDK v5.1.0 is required for Interaction to Next Paint (INP) metric.
Requested due to this issue: https://github.com/DataDog/browser-sdk/issues/2233.
> Note RUM SDK Requirement for INP

- content/en/monitors/notify/variables.md
Adds `{{audit.attributes.key}}` and `{{audit.message}}` to [Variables doc](https://docs.datadoghq.com/monitors/notify/variables/#?tab=is_alert)
[screenshot](https://a.cl.ly/d5uJ9b8R)
Note: I'm double checking with Audit Trail Team before merging ([slack](https://dd.slack.com/archives/C038LN8RB39/p1698263232051609)).
Preview Page: https://docs-staging.datadoghq.com/dan.chiniara/add-audit-variables-for-monitor-doc/monitors/notify/variables
Related Escalation: https://datadoghq.atlassian.net/browse/MNTS-90191
> dan.chiniara/add-audit-variables-for-monitor-doc

- content/en/monitors/notify/variables.md
Documents alert and warn recovery threshold template variables for Monitors.
> Document Monitor recoverty threshold template variables

- content/en/serverless/aws_lambda/installation/ruby.md
Regarding the AWS Lambda integration for DataDog: The docs currently don't distinguish between x86 & arm64 versions of the `datadog-lambda` ruby gem. The docs don't mention the arm64 existence of those layers nor the necessity to use them.
The status quo is pretty misleading if you're trying to set up an arm64-based ruby lambda function and you're hinted to the arm64-based extension layer, but **not** the arm-based gem/library. The error messages also don't help much.
Picking the correct `...-ARM`-based layer fixes the issue, but their existence isn't mentioned in the docs. This pull request fixes the docs here.
These ARM layers actually exist, see here: https://github.com/DataDog/datadog-lambda-rb/releases/tag/v2.21.0
> Docs: Add hint to arm64 AWS Lambda configuration layers

- content/en/account_management/rbac/granular_access.md
Removes the yellow beta banner & "beta" label in the heading because the "Gain Access" feature is GA as of today. 
Will also remove the beta labels on Confluence docs, so it's consistent.
> Remove beta warning / label since "Gain Access" feature is GA now

- content/en/database_monitoring/guide/managed_authentication.md
- content/en/database_monitoring/setup_postgres/rds.md
Updates docs to make it clear that the `region` parameter in the aws blocks enabled IAM authentication AND this takes precedence over setting the `password` explicitly in your YAML config. This is in response to new customers reporting issues with setting up IAM / accidentally enabling IAM, which causes authentication errors at start up.
> Make documentation around IAM authentication clearer

- content/en/real_user_monitoring/browser/advanced_configuration.md
- content/en/real_user_monitoring/guide/enrich-and-control-rum-data.md
- content/fr/real_user_monitoring/guide/enrich-and-control-rum-data.md
- content/ja/real_user_monitoring/guide/enrich-and-control-rum-data.md
Fix RUM example on using `beforeSend` to collect `fetch` response headers.
* `context.response.headers` is not serializable as JSON. We need to convert it to an object before.
* Also, it's fine to mutate the `event.context` directly. It simplifies the examples a little bit.
> fix fetch headers collection

- content/en/tracing/trace_collection/library_config/java.md
- content/en/tracing/trace_collection/trace_context_propagation/java.md
This PR updates the trace context documentation for Java tracer about changes introduces for re:Invent.
It includes:
* The default propagation style changes, 
* The multiple trace context extraction (`tracestate` propagation and terminated context as span links)
* And the new `DD_TRACE_PROPAGATION_EXTRACT_FIRST` setting to revert back to the previous behavior.
> Update trace context propagation documentation for Java tracer

- config/_default/menus/menus.en.yaml
I added a new guide and included it in the left nav. But apparently that causes weird behavior when navigating between the guide and the main guide index, so I'm removing the guide from the left nav for now.
> Remove CSM guide from left nav

- content/en/tracing/trace_collection/compatibility/nodejs.md
Updates a small portion of the Node.js support documentation , `next` section under web frameworks, to explicitly outline what newer features of Next.js are supported with the Node.js tracer following some Q3 changes, in the hopes of being a reference for customers looking for confirmed support of these features.
> [APM][Node.js] Update Next.js Support Documentation

- content/en/containers/kubernetes/configuration.md
- content/en/infrastructure/containers/_index.md
- content/en/infrastructure/containers/orchestrator_explorer.md
- content/fr/containers/kubernetes/configuration.md
- content/ja/containers/kubernetes/configuration.md
- content/ja/infrastructure/containers/_index.md
- content/ja/infrastructure/containers/orchestrator_explorer.md
[DOCS-6745](https://datadoghq.atlassian.net/browse/DOCS-6745)
Fixing broken links to orchestrator explorer, in this instance just needed to remove the trailing `/`
I went ahead and updated the non-English language pages that were affected too.
[DOCS-6745]: https://datadoghq.atlassian.net/browse/DOCS-6745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6745] fixing broken orchestrator explorer links

- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter.md
Some updated v2 documentation for Flutter got overwritten during the merge from master as part of the reorg. This fixes some of that documentation to be updated for v2
> Fix bad merge for Flutter

- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
- Remove quotes around environment variable values, as some customers mistakenly thought the quotes should actually be part of the value
- Fixed the DD_TRACE_CLIENT_IP_HEADER description on .NET Framework (it looks like it was updated on .NET Core but not .NET Framework)
> Remove quotes around values

- content/en/continuous_integration/dora_metrics/_index.md
Renaming the service catalog extension in the docs example aftet recommendation form the Service catalog team
> [CIVIS] Rename dora_metrics catalog extension to datadoghq.com/dora-metrics

- local/bin/py/build/actions/workflows.py
- local/bin/py/build/configurations/pull_config_preview.yaml
updates `workflow` script to only write to file  the highest versioned action.
motivation: https://datadoghq.atlassian.net/browse/WEB-4206 
prevew:  https://docs-staging.datadoghq.com/stefon.simmons/highest-stable-action-version/service_management/workflows/actions_catalog/#experimental
for review: preview shows actions tagged as `stability: dev` ([this line](https://github.com/DataDog/documentation/pull/20514/files#diff-5ed255a15fad115a8b5602e6a9e0e0aedc0a5cd021281e92046ff9c10868fb58R12)): Do not merge
- the `testAction` actions [here](https://github.com/DataDog/dd-source/blob/main/domains/workflow/actionplatform/apps/wf-actions-worker/src/runner/bundles/com.datadoghq.experimental/manifest.json#L360-L396) should be filtered to only show `testAction:V2` in the …
> get highest versioned stable action - [WEB-4206]

- content/en/database_monitoring/setup_oracle/autonomous_database.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Adding access rights that will be used by the upcoming agent releases `7.50.0` and `7.49.1-oracle-dbm-1.3`.
> [oracle] Add access right for the agent releases 7.50.0 and 7.49.1-oracle-dbm-1.3 (DBMON-3068)

- .gitlab-ci.yml
- layouts/shortcodes/permissions.html
- local/bin/py/build/content_manager.py
- throw an error when rbac perms is not found in preview/live which will exit building the site
- switch from streaming cached artifact to download and extracting
> Exit on missing rbac perms

- layouts/shortcodes/permissions.html
A recent change had incorrect syntax for checking the dev environment, causing local environment builds to not run. This fixes that syntax.
Preview also still builds https://docs-staging.datadoghq.com/fitzage/environment-check/
> fixed dev environment check in permissions shortcode

- content/en/getting_started/application_security/_index.md
- content/en/security/application_security/troubleshooting.md
- content/ja/getting_started/application_security/_index.md
- content/ja/security/application_security/troubleshooting.md
- content/ko/getting_started/application_security/_index.md
- layouts/shortcodes/appsec-getstarted-2-canary.md
- layouts/shortcodes/appsec-getstarted-2-plusrisk.md
- layouts/shortcodes/appsec-getstarted-2.md
The getting started script suggests sending 200 events, but the default rule thresholds in ASM are ">200". So minimum we would need to send "201" events for any chance of triggering a signal.
Bumping the default threshold to 250 to have a bit of a buffer, and eliminate issues where customers can't generate signals.
> [APPSEC] Fix suggested getting-started script threshold

- content/en/profiler/connect_traces_and_profiles.md
Removes a sentence that cautions the user that turning on Endpoint Profiling also turns on Code Hotspots in Node.js; this is no longer the case for few weeks now, we made the features independent of one another.
> PROF-8461: Endpoint profiling no longer turns on code hotspots

- content/en/real_user_monitoring/guide/proxy-rum-data.md
In light of [incident-22155](https://app.datadoghq.com/incidents/22155) we want to recommend customers to avoid sending sensitive data when proxying RUM requests.
Adds a "For security reasons" alert-info block below the instructions to proxy RUM requests.
Also fixes a typo.
> Recommend removal of sensitive HTTP headers

- content/en/profiler/profile_visualizations.md
This PR documents what per-thread filtering capabilities exist for each profiler, as well as what format is used for displaying this information.
We've been showing this data for quite some time, but some of the identifiers were not actually documented anywhere.
> Document per-thread information in the profiler

- content/en/profiler/profiler_troubleshooting/ruby.md
This PR updates the Ruby profiler troubleshooting page by:
* Removing references to an issue that has been fixed for 2+ years
* Updating the signal incompatibility list to reflect that passenger 6.0.19+ is fixed
N/A
> Update Ruby profiler troubleshooting: remove stale entry, add compatible passenger gem version

- content/en/agent/configuration/network.md
Fix the max ratio of disk space. Looking at the code, the max ratio is actually 0.8 instead of 0.95. See for [example here](https://github.com/DataDog/datadog-agent/blob/d0d83686ed7a39dce7a38dd6320f56a059eb2cc9/pkg/config/config.go#L478)
> Fix max disk ratio network.md

- content/en/security/notifications/variables.md
The support was added in this PR: https://github.com/DataDog/logs-backend/pull/60608
The wording is the same as the one in monitors: https://docs.datadoghq.com/monitors/notify/variables/?tab=is_alert#url-encode
> Add support for URL Encode in Signal Notification

- content/en/agent/remote_config/_index.md
Remove "beta" tag for the Dynamic Instrumentation product now that it's GA. We already covered most of this in #20588 , but we left out one entry in the Remote Config docs page.
- [-] Please merge after reviewing
> Remove beta tag for Dynamic Instrumentation

- layouts/partials/rum/rum-getting-started-mobile-advanced.html
DOCS-6741
Preview URL is /real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/
> Remove Otel tile from advanced configuration page

- content/en/tracing/guide/instrument_custom_method.md
Adds OpenTracing deprecation warning and pointer to OTel instructions, to custom instrumentation guide
> DOCS-6711 OpenTracing deprecation warning in custom instrumentation guide

- content/en/serverless/aws_lambda/installation/nodejs.md
As https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.100.0 has been released we can add `Node20-x` to the documentation as part of the https://github.com/DataDog/datadog-lambda-js/issues/436
Additionally, removing node12 on https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.90.0
> Updating documentation with datadog node runtime layer - removing node12 and adding node20

- content/en/database_monitoring/connect_dbm_and_apm.md
Adds a note to our APM-DBM link java tracer docs about prepared statement support for trace propagation. This is a response to some customers filing support tickets after enabling `full` mode, but not seeing any traces in the DBM UI for their samples.
> Add note about java prepared statements

- content/en/database_monitoring/setup_sql_server/troubleshooting.md
> Update troubleshooting to include OLE DB 2019

- content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
The span object is always present, but a non-recording span won't have a context. Additionally `span.context` no longer exists, `get_span_context()` on the `Span` interface replaces it.
This fixes the example `structlog` injector to be inline with recent opentelemetry package releases. A slightly modified version of the code is being used in production.
> Use otel context function and ignore non-recording spans.

- layouts/partials/logs/logs-languages.html
Adds missing tiles for iOS, React Native, Flutter, and Roku.
Fix alt text for Javascript and Android.
[DOCS-6571](https://datadoghq.atlassian.net/browse/DOCS-6571)
[DOCS-6571]: https://datadoghq.atlassian.net/browse/DOCS-6571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6571] Add missing tiles to Log Collection

- content/en/agent/fleet_automation/_index.md
Adds a link to the Fleet Automation page to the beta callout
From Slack. Add a link to the beta callout.
> Add FA link to beta callout

- content/en/glossary/terms/test_service.md
- content/en/glossary/terms/test_suite.md
Add new term for "test suite" in the Docs Glossary for Continuous Testing + CI Visibility, and updates the same definition for "test service" which is a related term.
- [] Please merge after reviewing
> Add "Test Suite" to Docs Glossary

- content/en/observability_pipelines/setup/_index.md
- content/en/observability_pipelines/setup/datadog.md
- content/en/observability_pipelines/setup/datadog_with_archiving.md
- layouts/shortcodes/op-deployment-modes.md
- layouts/shortcodes/op-updating-deployment-modes.md
- Splits the OP Deployment Modes section
- Adds the sections as general reuse shortcodes
- Add sections to Datadog and Datadog with Archiving docs
[DOCS-6801](https://datadoghq.atlassian.net/browse/DOCS-6801)
[DOCS-6801]: https://datadoghq.atlassian.net/browse/DOCS-6801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6801] Split OP deployment modes section

- content/en/continuous_integration/tests/setup/java.md
- content/en/dynamic_instrumentation/enabling/java.md
- content/en/profiler/enabling/java.md
- content/en/security/application_security/enabling/java.md
- content/en/security/application_security/enabling/serverless.md
- content/en/serverless/aws_lambda/installation/java.md
- content/en/serverless/azure_app_services/azure_app_services_container.md
- content/en/serverless/azure_container_apps/_index.md
- content/en/serverless/google_cloud_run/_index.md
- content/en/tracing/guide/inferred-service-opt-in.md
- content/en/tracing/guide/tutorial-enable-java-aws-ecs-ec2.md
- content/en/tracing/guide/tutorial-enable-java-aws-ecs-fargate.md
- content/en/tracing/guide/tutorial-enable-java-aws-eks.md
- content/en/tracing/guide/tutorial-enable-java-container-agent-host.md
- content/en/tracing/guide/tutorial-enable-java-containers.md
- content/en/tracing/guide/tutorial-enable-java-gke.md
- content/en/tracing/guide/tutorial-enable-java-host.md
- content/en/tracing/trace_collection/dd_libraries/java.md
Adds additional options for downloading the Java tracer, using `wget`, `curl`, or `ADD`
My editor removed extraneous whitespace when I did a find-and-replace to add single quotes around the URL. If this is undesired, I can revert this change
> Add alternative options for downloading Java agent

- content/en/cloud_cost_management/_index.md
adds a `Cloud Cost Management` subcategory for display in the title hierarchy on search results.   [First mentioned in this slack thread](https://dd.slack.com/archives/C0DESMBQU/p1701277316279959?thread_ts=1701271042.707909&cid=C0DESMBQU).
[I've created a card](https://datadoghq.atlassian.net/browse/WEB-4324) to look into setting defaults for `subcategory` to avoid this kind of confusion in the future as well.
[In the preview site](https://docs-staging.datadoghq.com/brian.deutsch/ccm-subcategory-search/search/?s=azure), the second search result should specify `Cloud Cost Management`, as compared to [live](https://docs.datadoghq.com/search/?s=azure).   This feels a bit more descriptive.
> adds CCM subcategory for search results display

- layouts/shortcodes/latest-lambda-layer-version.html
Updates the latest layer for dotnet because I just released it.
> Bump dd-trace-dotnet layer to version 14

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
These angle brackets should only be used for variables and not example URLs as they can cause confusion. The npm example above does not use these.
> Remove angle brackets to match previous example

- content/en/security/application_security/threats/threat-intelligence.md
The FireHOL source has been removed due to it being false positive prone, and having it in the docs is misleading.
> [APPSEC] Remove FireHol from threat intel docs

- content/en/security/application_security/threats/threat-intelligence.md
- [APPSEC-15184] Remove abuse.ch and spur references from ASM docs
`abuse.ch` and `spur:malware` threat intelligence sources are a bit too noisy currently, so the forwarding for ASM has been disabled in some situations.
[APPSEC-15184]: https://datadoghq.atlassian.net/browse/APPSEC-15184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APPSEC-15184] Update ASM threat intelligence sources

- content/en/tracing/other_telemetry/connect_logs_and_traces/php.md
- content/en/tracing/trace_collection/custom_instrumentation/php.md
This PR:
- Updates manual logs injection snippets
- The previous snippets were correct while 64-bit trace identifiers were still the defaults; however, this has changed in 0.94.0 and these snippets were no longer correct.
- Clarify Annotations usages
- We've had multiple escalations related to these recently. Let's make it clear it the doc 🙏
> [PHP] Update manual logs injection snippets and Clarify Annotations usages

- content/en/containers/guide/kubernetes_daemonset.md
- content/en/containers/kubernetes/apm.md
- content/en/containers/kubernetes/configuration.md
- layouts/shortcodes/k8s-helm-redeploy.md
- layouts/shortcodes/k8s-operator-redeploy.md
There were some discrepancies in the instructions for enabling APM on helm/operator. This PR updates the K8s APM page, the K8s further configuration page, and the ol' legacy daemonset configuration guide. Also adds two shortcodes for reuse.
> DOCS-6625 updates to k8s apm instructions

- content/en/tracing/trace_collection/compatibility/java.md
Google PubSub instrumentation is now enabled by default from 1.25.0 hence updating the doc
> [java-tracer] Google PubSub is enabled by default

- content/en/security/application_security/enabling/compatibility/php.md
Update the PHP ASM compatibility documentation to include PHP 8.3 and ARM64 support released in `0.95.0`.
> Update PHP ASM compatibility to include PHP 8.3 and ARM64

- content/en/monitors/guide/custom_schedules.md
Removing beta callout from the custom schedule guide since we are moving to a public beta.
> Remove beta callout

- .gitlab-ci.yml
- layouts/partials/algolia/page-sections.json
Fixes a bug in the Algolia indexing job where duplicate objectIDs are being generated.   This results in a) job duration increase and b) certain records being overwritten on each run.   [An example can be seen in any master pipeline](https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/385086072#L196) - where the job output indicates 500+ records are being updated every time it runs.
https://datadoghq.atlassian.net/browse/WEB-4281
- QA the search results and confirm nothing looks broken: https://docs-staging.datadoghq.com/brian.deutsch/dup-object-ids/search/?s=azure
- [check the latest algolia preview job](https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/385580652#L560), only 4 records are being updated (as opposed to 500+).   these will be handled in follow up work.
> [WEB-4281] Fix duplicate objectIDs being generated in Algolia indexing job

- local/bin/py/build/configurations/pull_config_preview.yaml
set default cache to true for preview builds
merged in as `false` here: https://github.com/DataDog/documentation/pull/20119
https://docs-staging.datadoghq.com/stefon.simmons/enable-cache-20119/
> re enable cache

- content/en/network_monitoring/performance/setup.md
The docker compose yaml wasn't formatted correctly.
Fixed YAML in example.
> fixed invalid yaml in the docker compose

- layouts/_default/list.algolia.json
adds a more sensible default for `subcategory` when indexing docs pages.   previously we used the page's title as default, which [caused confusion in at least one case](https://dd.slack.com/archives/C0DESMBQU/p1701277316279959?thread_ts=1701271042.707909&cid=C0DESMBQU).   this update adds more context to the categorical hierarchy when we display search results.
https://datadoghq.atlassian.net/browse/WEB-4324
QA the search results and confirm nothing looks incorrect: https://docs-staging.datadoghq.com/brian.deutsch/search-results-subcategories/search/?s=dashboards
no errors in the indexing job: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/388358669
> [WEB-4324] adds default subcategory for search results hierarchy

- content/en/account_management/audit_trail/events.md
Add new Agent audit events.
[DOCS-6889](https://datadoghq.atlassian.net/browse/DOCS-6869)
Will open a separate PR to reoreder link numbering.
I'll merge this on Wed 12/13/2023.
[DOCS-6889]: https://datadoghq.atlassian.net/browse/DOCS-6889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6889] Add Agent audit events

- content/en/agent/guide/private-link.md
PrivateLink for AP1 is now generally available. As such, we can remove the banner indicating that it is in private beta.
> Remove private beta designation for AP1 PrivateLink

- content/en/tracing/trace_collection/otel_instrumentation/java.md
This PR adds a better definition of which OpenTelemetry features are supported from APM Tracing using the Java tracer library. It also brings few code samples about the most requested use cases. 
There was an increasing number of escalations regarding the usage of this feature.
Providing more details of what is supported from what isn't could be useful to the customers.
I plan to update the page as soon as we get more features covered.
For example, annotations support contribution is in review and could bring more code samples.  Same for the Context API support.
---
> Improve OpenTelemetry Java manual instrumentation documentation

- content/en/observability_pipelines/guide/sensitive_data_scanner_transform.md
Adds new guide for OP SDS transform.
[DOCS-6870](https://datadoghq.atlassian.net/browse/DOCS-6870)
[DOCS-6870]: https://datadoghq.atlassian.net/browse/DOCS-6870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6870] Add OP SDS transform guide

- content/en/tracing/configure_data_security/_index.md
we don't obfuscate client query strings in the go tracer by default
> APM datasecurity golang client query strings

- content/en/glossary/terms/parallelization.md
- content/en/glossary/terms/test_batch.md
- content/en/glossary/terms/test_run.md
This PR adds two glossary terms related to Continuous Testing: parallelization and test runs.
> Adding two glossary terms

- .gitlab-ci.yml
Updates the pally image job settings so we can run pally on preview branches if/when needed. A new image was pushed that was tested to exclude the `ko` directory which was causing the job to timeout when it ran on schedule
Successful pipeline run on preview that excludes `ko`
https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/390116141
> Pally Image Update

- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md
Fixes the description of the `firstPartyHosts` parameter for React Native configuration. It used to be a copy/paste from another parameter.
> Fix first party hosts description for React Native

- content/en/serverless/azure_container_apps/_index.md
This PR fixes the wrong URL to DockerHub in the documentation of Azure Container Apps for the image `datadog/serverless-init`.
> Update _index.md with correct Docker Hub URL

- content/en/logs/guide/log-collection-troubleshooting-guide.md
The Datadog agent user only need the read and execute permissions to tail log files. The agent does not attempt to write anything to the logs files being tailed so it does not need the write permission. This also sends the wrong message to customers and may flag security concerns.
This was brought up in a slack conversation https://dd.slack.com/archives/C046YU1V0SK/p1702457801831989 
Which lead to creating this Jira escalation: https://datadoghq.atlassian.net/browse/AGENT-10762
- [√ ] Please merge after reviewing
> Correcting the needed permissions for the agent user to tail logs

- content/en/infrastructure/containers/configuration.md
Add Horizontal Pod Autoscalers to the orchestrator docs
> Update configuration.md for HPA

- content/en/synthetics/private_locations/_index.md
The current instructions to launch a private location using Docker includes both a --rm flag and a --restart flag in the command. These options are mutually exclusive and cannot be used together in a docker run command.
The intent of the original change to include the --restart flag was to ensure the container restarts when it's not explicitly stopped, so I am removing the --rm flag so there is no conflict in the docker command.
As it stands currently, our example results in an error from docker:
>docker: Conflicting options: --restart and --rm.
> Update docker run command in Private Location documentation to remove conflict

- content/en/continuous_delivery/_index.md
- content/en/continuous_delivery/deployments/_index.md
- content/en/continuous_delivery/deployments/argocd.md
- content/en/continuous_delivery/explorer/_index.md
- content/en/continuous_delivery/explorer/facets.md
- content/en/continuous_delivery/explorer/saved_views.md
- content/en/continuous_delivery/explorer/search_syntax.md
- content/en/continuous_delivery/search/_index.md
Adds beta banner + site region limitation across all CD Visibility doc pages.
Discussion in #cd-visibility on Slack.
> Add Beta Banner + Site Region Information for CD Visibility Documentation

- config/_default/menus/menus.en.yaml
- content/en/account_management/saml/okta.md
Datadog's new recommendation for configuring SAML with Okta is to use the pre-configured Datadog integration in Okta's application library. This PR updates our docs with the current recommendation. Requested in Slack by TEE Chris Choi.
While making the update, I noticed that the Azure and Okta SAML subpages don't show up in the left navigation. David and Heston figured out that the menu items are missing `identifier` tags, which they need to disambiguate from the other Azure and Okta menu items.
> Update SAML with Okta instructions and add identifiers to menu subitems

- .gitignore
Even though we've moved these files, we should keep ignoring them at least for a little while, cos anyone with files from an old build may accidentally add them back in.
> (maint) Add old files back to .gitignore

- layouts/partials/nav/left-nav.html
4th level nav should be disabled except for special cases, this was removed recently when it shouldn't have been.
https://datadoghq.atlassian.net/browse/WEB-4382
introduced in https://github.com/DataDog/documentation/commit/398d4779f8291df8479b827006e3198f7efb31be#diff-dfdaa69dbf684b687cc5616b90c96c3a66145c1ff7c5e8cba24193b9ad3add0e
**Should not show 4th level java, .NET etc. under library compatibility**
https://docs-staging.datadoghq.com/david.jones/web-4382/security/application_security/enabling/compatibility/java/
**Should show 4th level (errors/functions)**
https://docs-staging.datadoghq.com/david.jones/web-4382/observability_pipelines/reference/processing_language/errors/
> WEB-4382 - 4th level should be intentional only

- content/en/integrations/vmware_tanzu_application_service.md
Add two borked links in a site region shortcode. Just noticed it.
> VMware Tanzu Application Service Edit

- content/en/agent/supported_platforms.md
Customers that find that the latest Agent version doesn't support their OS platform/version will need to install a previous version of the Agent that is compatible. This PR just adds a link to the full list of previous installers.
> add list of all Windows installers

- content/en/tracing/trace_collection/library_config/php.md
PHP Exception profiling will be GA with the next release (0.96.0) and the docs should reflect this
PROF-8429
> document GA for exception profiling

- content/en/tracing/trace_collection/library_config/php.md
With https://github.com/DataDog/dd-trace-php/pull/2385 we merged (and released in `0.96.0` today) a setting that allows to enable all experimental features.
> Document PHP "all experimental features"

- content/en/continuous_integration/pipelines/jenkins.md
- content/en/intelligent_test_runner/setup/java.md
- content/en/tests/setup/java.md
Updates Test Visibility documents for Java:
- Scalatest added to list of supported frameworks
- a note added that Jenkins plugin supports Test Visibility configuration starting with v5.6.0
- troubleshooting section now has environment variable names in addition to system property names for tracer config
> Update Test Visibility and ITR docs for Java: add Scalatest support, and other minor updates

- content/en/real_user_monitoring/browser/troubleshooting.md
The Browser SDK is now capable of compressing data before sending it to Datadog. With this feature enabled, the limit to display customer data warning has been increased. This PR adjusts the documentation.
Related SDK PR: https://github.com/DataDog/browser-sdk/pull/2529
> Update documentation related to customer data limit

- layouts/integrations/_markup/render-link.html
removes trailing spaces / new lines after anchors generated by the `render-link` render hook.
jira: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4392
should only effect pages using the `/integrations` layout
preview: https://docs-staging.datadoghq.com/stefon.simmons/remove-unexpected-space-web-4392/integrations/guide/azure-manual-setup/?tab=armtemplate#integrating-through-the-azure-portal
> rm trailing spaces/new lines after links - [WEB-4392] 

- config/_default/menus/menus.en.yaml
- content/en/containers/cluster_agent/admission_controller.md
- content/en/containers/troubleshooting/admission-controller.md
Add a dedicated doc for troubleshooting the Admission Controller. This is a slight follow up to https://github.com/DataDog/documentation/pull/20103 where the Cluster Agent troubleshooting was broken up. This publicizes a lot of our internal troubleshooting scenarios for common problems, distribution specific steps, and networking rules. 
This also adds the new menu option and re-directs the main Admission Controller > Troubleshooting section to this new doc.
Will be checking in with a few more Container teams as well.
Notes for a later PR:
- The core Admission Controller doc could use a few organizational changes for labels / mutate unlabelled. But leaving those for another PR
- Using the `socket` mode in OpenShift is still a work in progress. You can create a SCC to allow the hostPath …
> [DOCS-6854] Add Troubleshooting/Admission Controller doc

- content/en/developers/dogstatsd/unix_socket.md
> (DOCS-5872) DogstatsD with UDS requires additional steps

- content/en/real_user_monitoring/guide/_index.md
Following [PR21074](https://github.com/DataDog/documentation/pull/21074), add the page to the RUM guides index.
> [RUM-2088] Add link to RUM guide index to reference deprecation policy

- content/en/logs/log_collection/javascript.md
- content/en/real_user_monitoring/browser/_index.md
Document the new config parameter allowing to configure the session cookie as partitioned to address the phasing out of third-party cookies by google.
> [RUM-2436][Browser SDK] Document `usePartitionedCrossSiteSessionCookie` config parameter

- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/expo.md
Expo dev client makes `/logs` API calls to the packager every time there is a log. If we track RUM Resources and have SDK Verbosity set to `DEBUG` we end up in a loop creating infinite resources and logs.
We already filter out the most probable URLs for this call, but it can be custom. In that case, we add instructions for users to avoid creating this many calls.
> Add troubleshooting steps for expo logs

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
PM requested that we remove mention of remote configuration from single step instrumentation documentations. This was creating confusion for users.
> Remove mention of "remote config" from single step APM docs

- content/en/security/vulnerabilities/troubleshooting.md
- layouts/shortcodes/csm-prereqs-enterprise.md
- layouts/shortcodes/csm-prereqs-pro.md
This PR bumps the minimum required Helm version for CSM vulnerabilities due to a bug that was fixed in the helm chart.
[DOCS-6803](https://datadoghq.atlassian.net/browse/DOCS-6803)
https://github.com/DataDog/helm-charts/pull/1259
[DOCS-6803]: https://datadoghq.atlassian.net/browse/DOCS-6803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6803] updating Helm version in CSM vulnerabilities prereqs

- content/en/tracing/service_catalog/scorecards.md
The feature is now in public beta, so removing call out to request access for private beta.
> Removing mention of Custom Scorecards private beta

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md
- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/ios.md
- layouts/partials/apm/apm-compatibility.html
- layouts/partials/apm/apm-languages.html
The Tracing Android and iOS pages were not linked anywhere in the docs before.
> [DOCS-6572] Add iOS and Android to DD libraries page.

- config/_default/menus/menus.en.yaml
some items in menus.en.yaml did not have identifiers
it isn't breaking, but ambiguity can lead to unexpected consequences
in the future we should lint for this, but for now this fixes the baseline
preview:
https://docs-staging.datadoghq.com/cswatt/menu-linting/agent/
> adding missing identifiers to menus.en.yaml

- content/en/security/application_security/terms.md
Remove a duplicated term from the ASM terms and concepts page. The term is `user attribution` and it currently exists at both L70 and L76.
> Remove duplicated term in ASM terms and concepts page

- content/en/containers/kubernetes/integrations.md
Configmap name from the `volumes` part of the pod definition does not match the example configmap name in the `configmap` definition. Taking the example as is does not work.
Current example :
`Configmap` definition example : 
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: redis-config-map (note the confirmap name here)
```
`pod` definition update example :
```yaml
volumes:
- name: redisdb-config-map
configMap:
name: redisdb-config-map (note the configmap name here)
```
> Fix configmap name in autodiscovery confirmap example in integration.md

- content/en/serverless/step_functions/installation.md
There should be an `s`.
source code: https://github.com/DataDog/serverless-plugin-datadog/blob/main/src/env.ts#L116
> Fix typo missing `s` in `enableStepFunctionsTracing`

- content/en/agent/supported_platforms.md
Fixes a link for the installers list on this page: https://docs.datadoghq.com/agent/supported_platforms/?tab=windows
> fix broken link to installers_v2

- content/en/containers/guide/autodiscovery-management.md
Fix minor yaml issue. The `env` should be nested under the `nodeAgent` instead to apply to all of the node Agent's containers.
> Fix yaml syntax on operator/pause container option

- content/en/service_management/incident_management/_index.md
This PR removes a notice in Incident Management's us1-fed documentation indicating that the product is not in that environment. The product _is_ available.
N/A
> INA-5429: Update incident management documentation to remove notice about unavailability in us1-fed

- .github/CODEOWNERS
This PR updates codeowners to remove corpweb from the data/api reviews.
These are autogenerated files and do not need review by our team. The codeowner assignment has caused some confusion for contributors to the spec repo thinking its blocked on us.  We should be looped in if there is an issue with autogeneration but beyond that these are editorial changes to review which are good in docs hands.
> docs only to review autogenerated api content

- layouts/shortcodes/dbm-sqlserver-agent-config-examples.md
This fixes the following issues in our DSN/ODBC documentation:
- User/Password are not valid fields for `odbc.ini`, the DD agent doesn't pull credentials from here, and it is generally not best practice to store credentials here. These fields were removed from the example.
- The Server and Port fields are unnecessary. The same information is required to be set in the `conf.yaml` file, so having it in `odbc.ini` is redundant. These fields were also removed from the example.
- There is now explicit clarification that the `driver` field in `conf.yaml` pulls from `odbcinst.ini` with an additional example.
> Update ODBC documentation in dbm-sqlserver-agent-config-examples.md

- content/en/quality_gates/setup/_index.md
Update Quality Gates setup page as we removed DD_BETA_COMMANDS_ENABLED parameter for `datadog-ci gate`.
Merge is blocked by https://github.com/DataDog/datadog-ci/pull/1150
> [CIVIS-8421] Update Quality Gates setup page as we removed DD_BETA_COMMANDS_ENABLED

- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/rds.md
- content/en/database_monitoring/setup_sql_server/selfhosted.md
- Adds documentation about log shipping monitoring for the SQLServer integration, which will be available in agent 7.50+.
> [Database Monitoring] Update sqlserver setup documentation to mention log shipping

- content/en/static_analysis/_index.md
- content/en/static_analysis/rules/_index.md
Adds the new C# rulesets that were added to the rule index page frontmatter section.
> [STAL-992] Add C# rulesets to frontmatter

- content/en/integrations/content_security_policy_logs.md
* the `csp-report.` subdomain hasn't been setup when the AP1 region was created, so the doc is mentioning an inexistent domain `csp-report.browser-intake-ap1-datadoghq.com`
* starting from the latest major release, the Browser SDK doesn't use intake subdomain anymore (`logs.`, `rum.` and `replay.`)
* this allows a simpler setup when deploying new regions
* also it allows a simpler, more secure proxy setup, as all requests can be forwarded to a single domain
Given those two information let's remove the `csp-report.` subdomain as well. New regions will be easier to setup, and it will follow the same pattern as other intake usages.
> remove 'csp-report.' subdomain for CSP report intake URLs

- config/_default/menus/menus.en.yaml
- content/en/infrastructure/containers/container_images.md
- content/en/security/cloud_security_management/setup/csm_enterprise.md
- content/en/security/cloud_security_management/setup/csm_pro.md
- content/en/security/cloud_security_management/troubleshooting/_index.md
- content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md
- layouts/shortcodes/csm-prereqs-enterprise.md
- layouts/shortcodes/csm-prereqs-pro.md
This PR adds additional context in CSM vulnerabilities troubleshooting page and moves the page under the CSM - Troubleshooting on the left nav where it flows better. Also added default version for Datadog operator for image collection.
Check redirects, etc.
> [DOCS-6979] updates to CSM troubleshooting vulnerabilities and moving page

- content/en/security/cloud_security_management/setup/csm_enterprise.md
This change documents how to enable host benchmarks in Kubernetes (Helm and Operator), Docker, Daemonset and Host.
> [CSPM] Document how to enable host benchmarks

- Makefile
bumps `assetlib` to latest version
https://datadoghq.atlassian.net/browse/WEB-4425
https://docs-staging.datadoghq.com/brian.deutsch/assetlib-bump/integrations
`Machine Learning & LLM` is no longer a listed category
`NVIDIA` tile falls under `AI/ML`
> [WEB-4425] Assetlib bump

- content/en/data_security/agent.md
Adds explanation for a common reason why the verify msi command may fail. 
https://datadoghq.atlassian.net/browse/WINA-567
> add digicert update line

- content/en/synthetics/private_locations/configuration.md
Update the misleading description of the `verbosity` option for Synthetics Private location to document how to set it through command line argument or the configuration file **which is not done in the same way**:
- When using the JSON configuration file, the `verbosity` option is a number from `1` to `4` (default `3`: info)
- When using CLI arguments the verbosity is set through `-v`, `-vv`, `-vvv`, `-vvvv` (number of `v`s = verbosity level)
- The default is info log level (`3`, `-vvv`)
- **The `--verbosity <level>` CLI argument option is not recognized**
Verbosity level | CLI argument | JSON config option
-- | -- | --
DEBUG | `-vvvv` | `"verbosity": 4`
INFO (default) | `-vvv` | `"verbosity": 3`
WARNING | `-vv` | `"verbosity": 2`
ERROR | `-v` | `"verbosity": 1`
> [SYNTH-12562] Update Synthetics Private Location `verbosity` option description

- config/_default/menus/menus.en.yaml
I am standardizing the left nav in localized sections. This makes "fixes" to the Essentials > Getting Started section—"fixes" is in quotes because the original version is correct and functional, and this version just puts all the nav items in order, according to weight; also, the weights are now incremented regularly rather than haphazardly.
THERE SHOULD BE NO CHANGES FOR USERS. 
For reviewer: ensure that the nav in this branch's preview (https://docs-staging.datadoghq.com/cswatt/getting-started-nav-audit) match the left nav currently in production. There should be NO CHANGES.
> left nav auditing: getting started

- content/en/real_user_monitoring/error_tracking/expo.md
Document new option added to the Expo config plugin to specify the version of the gradle plugin used to upload Proguard mapping files.
> Document gradle plugin version option in expo

- content/en/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum.md
Updates the RUM Next.js doc to more strongly recommend that customers use the CDN method when using the Next.js app router
> Update RUM Next.js guide to recommend CDN method for Next.js app router

- content/en/infrastructure/containers/container_images.md
* Reorder tabs so that the page defaults to Operator (preferred config method).
* Consistency with Containers and Orchestrator config pages.
> [Container Images] Reorder "K8s (Operator)" to be the first tab for config

- config/_default/menus/menus.en.yaml
- Reorder Metrics left nav menu to match the order of the Metrics Landing Page
- Requested by PM
- [DOCS-7014](https://datadoghq.atlassian.net/browse/DOCS-7014)
[DOCS-7014]: https://datadoghq.atlassian.net/browse/DOCS-7014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Reorder metrics left nav

- layouts/_default/baseof.html
- layouts/_default/section.html
- layouts/multi-code-lang/single.html
quick fix:
removes box shadow from docs baseof. 
- on viewports `<=575px`, a box shadow would appear on the right. 
applies `.table-wrapper` around markdown tables in `section` pages to enable horizontal scroll
jira: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4438
previews:  
- https://docs-staging.datadoghq.com/stefon.simmons/rm-box-shadow-on-base/continuous_integration/pipelines/?tab=githubactions#alert-on-pipeline-data
> Remove box shadow on baseof - [WEB-4438]

- content/en/security/cloud_security_management/setup/csm_enterprise.md
- content/en/security/cloud_security_management/setup/csm_pro.md
This PR re-orders the Kubernetes Operator tab to be first in the list to be consistent with containers docs as we are moving towards having Operator as the preferred installation method.
> Re-ordering Kubernetes Operator/Helm tabns

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
The referenced AWS documentation does not provide a specific example for configuring a Datadog destination, and the patching instructions here still require some trial and error to get right. This PR provides a working example that I have used.
> Added example permission policy

- config/_default/menus/menus.en.yaml
- content/en/security/threat_intelligence.md
changing the name in the left nav from Threat Intel to Threat Intelligence for continuity
> fixing name in left nav

- assets/scripts/datadog-docs.js
- layouts/partials/nav/left-nav.html
keeps left nav open at appropriate place for children (page) paths greater than 4 levels deep.
jira: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4403
preview:  https://docs-staging.datadoghq.com/stefon.simmons/fix-left-nav-deeper-children/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs/
> fix left nav deeper children - [WEB-4403]

- content/en/monitors/types/error_tracking.md
This sentence has been confusing some readers.
When creating a New Issue monitor (`<dd site>/monitors/create/error-tracking`), there is a list of Error Tracking Issues on top of the screen that can be used to find a good evaluation period for the monitor. The contents of this list are not related to the monitor definition.
This PR:
- Rewords the sentence to make the purpose of this list more clear.
- Moving the sentence under step 1 to make clear that it's intended to be used in this step.
> [Error Tracking] Clarify sentence about new issue example list

- content/en/monitors/types/error_tracking.md
This PR updates the docs for Error Tracking monitors:
- Renames the mentioned "Web and Mobile Apps" and "Backend Services" dropdown menu items to "RUM Events" and "Traces" respectively. They have been renamed in the UI a while back:
- The doc currently starts with "Select Web and Mobile Apps from the dropdown menu". This makes it seem like selecting another option is not right. Changing the text to start step 1 with "Select .... from the dropdown menu". This is similar to how it's said in step 2 of the New Issue monitor (on line 81)
> [Error Tracking] Clarify error count monitor creation

- config/_default/menus/menus.en.yaml
- content/en/service_catalog/_index.md
- content/en/service_catalog/adding_metadata.md
- content/en/service_catalog/browsing.md
- content/en/service_catalog/guides/_index.md
- content/en/service_catalog/guides/streamlining-development-lifecycle-with-ci-visibility.md
- content/en/service_catalog/guides/understanding-service-configuration.md
- content/en/service_catalog/guides/upstream-downstream-dependencies.md
- content/en/service_catalog/guides/validating-service-definition.md
- content/en/service_catalog/integrations.md
- content/en/service_catalog/investigating.md
- content/en/service_catalog/scorecards.md
- content/en/service_catalog/service_definition_api.md
- content/en/service_catalog/setup.md
- content/en/service_catalog/troubleshooting.md
[DOCS-6960](https://datadoghq.atlassian.net/jira/software/projects/DOCS/boards/199?assignee=712020%3A0c2a9bb8-dcff-4533-8eb8-9e0bd4696037&selectedIssue=DOCS-6960)
* Move Service Catalog docs [here](https://a.cl.ly/bLuQY1ng?method=GET).
* Update aliases to all pages.
[DOCS-6960]: https://datadoghq.atlassian.net/browse/DOCS-6960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move Service Catalog Docs Outside APM

- content/en/integrations/rsyslog.md
- content/ja/integrations/rsyslog.md
> [rsyslogd] Fix the clear-text port, it should be 10514 as 10516 is the TLS one

- content/en/profiler/profile_types.md
The upcoming dd-trace-rb 1.19.0 release introduces three new profile types for Ruby. These are similar to other profilers, and I've mostly borrowed their description for these profile types, with minimal tweaks.
Ideally, this PR should only be merged after we release 1.19.0, which we plan to do this week. I'll drop a note on this PR once the release is out so it can be merged :)
N/A
> Document Ruby memory-related profile types

- content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps the Llinux AAS wrapper version to v1.9.0
> Bump LInux AAS Version to v1.9.0

- layouts/static-analysis/list.html
fixes search functionality. should be able to search for a `ruleset id`, `rulset description`, `rule name`, or `rule id` to find a rule.
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-search-static-analysis/static_analysis/rules/?search=empty
> each searched word must be a part of rule

- content/en/continuous_integration/pipelines/_index.md
- content/en/continuous_integration/pipelines/github.md
Add running pipelines as new feature for GitHub Actions
> Add running pipelines as feature for GitHub Actions

- content/en/real_user_monitoring/browser/monitoring_page_performance.md
Remove the mention of providing a relative time to the addTiming API since customer can't really provide a relative time that will be relative to the current view start.
They should favour using epoch timestamp instead.
cf https://github.com/DataDog/browser-sdk/issues/2552
> [RUM] remove relative time from add timing API

- content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
Adds a sentence to direct users to Java log collection doc. User request.
[DOCS-6866](https://datadoghq.atlassian.net/browse/DOCS-6866)
[DOCS-6866]: https://datadoghq.atlassian.net/browse/DOCS-6866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add link to Java log collection

- content/en/continuous_integration/pipelines/jenkins.md
In the settings of Datadog Jenkins plugin one can specify which jobs to include/exclude from monitoring.
The included/excluded lists can contain regular expressions, but not glob patterns.
The two have different syntax.
A user was trying to add a glob pattern instead of a regular expression.
> Clarify the usage of regular expressions in included/excluded job lists in DD Jenkins plugin

- layouts/static-analysis/list.html
uses the `language_alias` value to target url params that have a language_alias
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-delete-one-sa/static_analysis/rules/?languages=Docker&languages=Java&languages=CSharp
- clicking the **x** (delete) for the `C#` selection (not the checkbox), should remove the `CSharp` (alias) url param.
> fix `deleteOneSelection` functionality

- data/libraries.yaml
removes the note saying the Go and Java client is in beta
> Remove outdated beta notice for Go and Java api clients

- content/en/real_user_monitoring/session_replay/_index.md
Under "Setup," "Datadog RUM Browser Monitoring" currently links to https://docs.datadoghq.com/real_user_monitoring/session_replay/ - bringing you back to the top of the page.
This PR changes the link to https://docs.datadoghq.com/real_user_monitoring/browser/
> Correct link in RUM Session Replay docs

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps the extension version 
preview: https://docs-staging.datadoghq.com/dylan.yang/bump-datadog-lambda-extension-version-53/serverless/aws_lambda/installation/python/?tab=custom
> Bump datadog-lambda-extension layer to version 53

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
Fix the React Native 'Connect RUM and traces' example. 
This is the type used for the `firstPartyHosts` props:
```typescript
export declare type FirstPartyHost = {
match: string;
propagatorTypes: PropagatorType[];
};
```
> Fix React Native connect RUM and traces example

- local/bin/py/build/configurations/pull_config_preview.yaml
temporarily disables the preview caching mechanism to determine if some transient preview build errors are being caused by this functionality
transient build errors have been reported by the docs team, for example here reported by @hestonhoffman and @aliciascott https://dd.slack.com/archives/C3CT8QA11/p1705515891633269.
it seems the issues are contained to preview builds which could indicate a problem with the caching.
> disables preview cache flag

- content/en/containers/kubernetes/distributions.md
Adds configurations for adding tolerations for GKE Autopilot Spot Pods. DOCS-6912
> DOCS-6912 adding spot instances for k8s distributions

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md
Tiny change to add .NET 8 to the list of supported runtimes. This was already updated in other pages. We have supported .NET 8 since release 2.42.0 of the .NET Client Library (aka tracer).
> [APM .NET Client Library] Add .NET 8 to list of supported runtimes

- assets/scripts/components/algolia.js
`cmd + click` on an item from the search results opens page in a new tab
https://datadoghq.atlassian.net/browse/WEB-4224
https://docs-staging.datadoghq.com/brian.deutsch/cmdclick/search/
- `cmd + click` on a search result link, it should open in a new tab
- regular click should open page in the current tab
- no console/JS errors are introduced
- i don't have a windows keyboard but the same should work using the `ctrl` key
> [WEB-4224] cmd + click opens in new tab from search results

- content/en/containers/kubernetes/control_plane.md
Escaping the `<` isn't working, and the heading appears broken when rendered in the corpsite (heading says **Kubernetes on Rancher Kubernetes Engine (** and then the angle bracket breaks everything). Using the HTML escape `&lt;` also does not work, nor does enclosing `<` in backticks. Consequently, I've replaced the char with the word "before".
> fix heading on k8s control plane page

- layouts/shortcodes/remote-flare.md
Fix a broken link. Need to test it in the main fleet automation page as well to make sure it works
> Fix link to fleet automation in shortcode

- content/en/account_management/billing/apm_tracing_profiler.md
Mitigate this question from Sales:
Hi Team, received the following question from a client looking to onboard Datadog: "I’m trying to get the most accurate info possible, specifically for the APM pricing for containers (ECS and EKS, no Fargate). On your APM Billing page I see If you’re using a container based environment, you get billed for the underlying host deploying the Datadog Agent. If we’re running say 450 containers on 10x EC2 instances – does that mean we’d be billed just for APM on the 10 hosts? Wouldn’t it be deployed as a sidecar/daemon for each pod?"
> Clarify container statement to avoid confusion about Fargate

- content/en/real_user_monitoring/browser/collecting_browser_errors.md
Adds a note clarifying that Error Tracking does not process errors from Browser Extensions
> Adding note about Browser Extensions

- Makefile
- local/bin/py/build/configurations/pull_config_preview.yaml
- local/bin/py/build/update_pre_build.py
Disable jobs building in parallel temporarily, trying to confirm this is the root cause of some transient preview build errors seen in the Docs gitlab recently.    This also re-enables the preview cache mechanism.
https://datadoghq.atlassian.net/browse/WEB-4486
Running build jobs in parallel was a good performance win but may have been causing a race condition which led to random build errors.    We can revisit the parallelism (or alternative approaches to build performance) later on if we can confirm this was the cause.   As a result we may see preview build times creeping back up in the interim.
https://docs-staging.datadoghq.com/brian.deutsch/cache-debug
- make sure site looks good and dynamically built content exists (i.e. integrations, workflows, etc)
> [WEB-4486] Disables build parallelism

- content/en/api/v2/metrics/request.SubmitMetrics.json
replaces hardcoded timestamp on `Submit metrics` api curl code example
jira: https://datadoghq.atlassian.net/browse/WEB-4201
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-api-metric-api-ex/api/latest/metrics/?code-lang=curl
> replace hardcoded timestamp - [WEB-4201]

- config/_default/menus/menus.en.yaml
Adds a child page in the left-hand navigation for [CI Monitors](https://docs.datadoghq.com/monitors/types/ci/) in CI Visibility and Test Visibility sections.
Chat with Jesse on Slack.
> Add Monitors Child Page in CI Visibility and Test Visibility Doc Sets

- content/en/profiler/enabling/supported_versions.md
- content/en/profiler/profile_types.md
Documents beta availability of CPU time profile type for Node.js
> Document Node.js beta CPU time profiler

- content/en/service_management/app_builder/auth.md
Adds the `connections_read` permission and its description to the App Builder authorization page. It was omitted in error. Requested by an engineer.
> Add connections_read to App Builder auth page.

- content/en/data_security/guide/_index.md
- content/en/data_security/guide/tls_ciphers_deprecation.md
This PR adds information on the deprecation of TLS Cipher Suites
[DOCS-7081](https://datadoghq.atlassian.net/browse/DOCS-7081)
[DOCS-7081]: https://datadoghq.atlassian.net/browse/DOCS-7081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7081] TLS Ciphers deprecation notice

- content/en/service_management/incident_management/incident_details.md
Removes a disclaimer in incident_details.md explaining that Incident Management is not available in Fed1 (it is).
> Remove outdated Fed1 disclaimer from incident_details.md

- content/en/security/application_security/threats/inapp_waf_rules.md
- content/en/security/application_security/threats/protection.md
Following the release of the new navigation we want to update the different links we have in ASM threats
Configuration for In App Waf will now be in ASM -> Protection main menu
> (asm) Update doc for protection navigation release

- snippets/markdown.json
We are no longer using the partial to render the Static Analysis rules, we can remove this from the `markdown.json` file!
> No Longer Sourcing Static Analysis Rules This Way

- content/en/tracing/trace_collection/custom_instrumentation/otel_instrumentation/ruby.md
Update the page "Custom Instrumentation of Ruby Applications with the OpenTelemetry API" require the correct Ruby Gem.
> Custom Instrumentation of Ruby Applications with the OpenTelemetry API

- content/en/tracing/configure_data_security/_index.md
The example presents an issue with the spaces between the key value pairs in the docker-compose.yaml file. 
Removing the spaces fixes the issue.
Removes the spaces in the example for docker-compose.yaml.  
Reduces the number of tickets. Due to the fact, that the customers can try the example without any error.
The issue was replicated already and discussed.
> Update Data Security Configure _index.md to fix the example for dockerr-compose.yaml

- config/_default/menus/menus.en.yaml
PM asked that the Serverless section also link to the ECS Fargate integration, as is done in the Containers section.
> DOCS-7137 - add Fargate link to serverless section

- content/en/logs/log_configuration/processors.md
- content/en/tracing/troubleshooting/correlated-logs-not-showing-up-in-the-trace-id-panel.md
Adds note about trace IDs and span IDs not displayed in logs. SE request.
[DOCS-6645](https://datadoghq.atlassian.net/browse/DOCS-6645)
[DOCS-6645]: https://datadoghq.atlassian.net/browse/DOCS-6645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6645] Add note about trace IDs

- content/en/data_streams/_index.md
This PR adds the new blog "Troubleshoot streaming data pipelines directly from APM with Datadog Data Streams Monitoring" to the Data streams doc.
> adding blog link to data streams doc

- content/en/getting_started/opentelemetry/_index.md
Moved `trace_buffer` to the correct place.
And also removed `exporters.logging` as it was not being used.
> Update Getting Started with OTel

- content/en/tracing/guide/send_traces_to_agent_by_api.md
- content/en/tracing/guide/span_and_trace_id_format.md
All Datadog tracing libraries now generate 128-bit IDs by default. Update the Trace and Span ID Formats page to reflect the new paradigm.
- By default, all tracing libraries generate 128-bit trace IDs and 64-bit span IDs. 
- Datadog accepts 128-bit or 64-bit trace IDs, and 64-bit span IDs.
- Trace ID range should be 0, 2^64-1 for all languages (differing from span IDs).
Edit: Removed ID ranges from the new sections after discussing with js team.
> [DOCS-6951] Update trace and span ID page to reflect 128-bit IDs

- content/en/tracing/trace_collection/runtime_config/_index.md
This change updates the table of remote configuration settings version support to reflect the state of dd-trace-py.
> set supported versions for python remote configuration settings

- content/en/security/cloud_siem/log_detection_rules.md
…cated soon
Add a banner to warn the users that suppression queries will be deprecated soon. 
What is the motivation?
To make the users aware that suppression queries will be deprecated so they might be encouraged to either migrate their suppression queries or use global Suppressions feature. 
I copied the banner and the wording that is already available on https://docs.datadoghq.com/security/suppressions/. I am not sure if the migrating part needs to be removed. Please let me know. Thanks
> Add banner to warn the users that suppression queries will be deprecated soon.

- content/en/cloud_cost_management/container_cost_allocation.md
Adds agent version requirements for container cost allocation, as we get a lot of support questions asking why certain things do not work.
Also makes distinction between K8s and ECS more clear.
> [CCM] update requirements for container cost allocation

- content/en/monitors/guide/custom_schedules.md
Updating from 
"After a custom schedule has been enabled on a monitor, the monitor cannot be disabled." to,
"After a custom schedule has been enabled on a monitor, the schedule cannot be disabled. Custom schedules can only be added or removed during monitor creation."
Improving doc accuracy
- [√] Please merge after reviewing
> Change to improve accuracy

- content/en/getting_started/tagging/unified_service_tagging.md
This clarifies the intended usage of the `version` tag in Unified Service Tagging. Currently, some users are setting `version` tags that never change, or that aren't bumped for every code change.
> [SCICM-1575] Add note about version tag uniqueness

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
This PR fixes the helm install command in Single Step APM Instrumentation document. (currently missing datadog/datadog)
It also adds a step 5 after that to prompt users to do a rolling restart on applications for instrumentation to take place in k8 cluster
- Fixes helm install command in the Single Step APM Instrumentation document.
- Adds additional step for rolling restart of k8s application in order for instrumentation to take place.
> Minor Update to Single Step APM Instrumentation

- content/en/tracing/other_telemetry/connect_logs_and_traces/python.md
128-bit log correlation doesn't work yet, with that being the case we need customers to inject the 64-bit trace_id instead, until the backend work is complete.
> Update python.md with trace_id workaround while backend works on fix

- content/en/logs/error_tracking/_index.md
> Remove beta callout from Error Tracking Logs docs

- content/en/tracing/trace_collection/compatibility/java.md
Updates support table to set JDK 21 to GA following testing in https://github.com/DataDog/dd-trace-java/pull/6483 and https://github.com/DataDog/dd-trace-java/pull/6542
The first commit reformats tables without changing any information
The second commit includes JDK 21 support
> Update JDK 21 to GA

- content/en/tracing/trace_collection/compatibility/java.md
Discourages users from loading multiple simultaneous APM Java agents.
> discourage multiple APM agents

- content/en/intelligent_test_runner/setup/python.md
This removes the "beta" banners/notes from the Python Intelligent Test Runner page, and tweaks the page layout to use tabs for the individual test runners (Pytest and Unittest).
The content switches from "how to enable the Intelligent Test Runner" to "how to disable the Intelligent Test Runner".
> [CIVIS-3109] Remove "beta" status from python ITR documentation

- config/_default/menus/menus.en.yaml
A small change to update the left nav menu title for CSM OOTB Rules to match the other security docs.
https://docs-staging.datadoghq.com/deforest/csm-ootb-rules-menu-title/
> Update the left nav menu title for CSM OOTB Rules

- static/resources/yaml/observability_pipelines/quickstart/aws_eks.yaml
- static/resources/yaml/observability_pipelines/quickstart/azure_aks.yaml
- static/resources/yaml/observability_pipelines/quickstart/google_gke.yaml
- static/resources/yaml/observability_pipelines/quickstart/terraform_opw.tf
Remove disk buffers from OPW quickstart configs.
Data buffering in general (and disk buffers in particular) is an advanced topic and should be removed from quickstart configs. So far we've seen too many examples of customers struggling with this configs on an early stages of OPW adoption. The goal is to keep quickstart configs straightforward and simple.
> PRODUCTSA-1134 Remove disk buffers from OPW quickstart configs

- content/en/tests/setup/dotnet.md
- content/en/tests/setup/java.md
- content/en/tests/setup/javascript.md
- content/en/tests/setup/junit_xml.md
- content/en/tests/setup/python.md
- content/en/tests/setup/ruby.md
- content/en/tests/setup/swift.md
Add a link to reserved tags information in Unified Service Tagging docs. A follow up PR will add a section to the Using Tags docs for Test Visibility.
> DOCS-7155 Test Visibility Doc Update

- data/libraries.yaml
Reading the full table you could think the go tracer package is named "tracer", which is false. Fixed this
> Fix dd-trace-go description

- content/en/real_user_monitoring/guide/connect-session-replay-to-your-third-party-tools.md
Fixes the name for the RUM Browser SDK public API method `getSessionReplayLink`.
> Fix typo in getSessionReplayLink function name

- content/en/tracing/trace_collection/compatibility/java.md
This PR simplifies to Java client library compatibility table.
I found the multiple lines and the forth columns hard to understand so I split the compatibility table in two:
* The compatibility for our current tracer
* The compatibility for our legacy tracer (in maintenance)
I also remove duplicated Linux and MacOS content and merge one cell (Java 8 to 17) to make it simpler.
> feat: Make the Java client library compatibility table easier to understand

- content/en/monitors/downtimes/_index.md
This includes an additional example that shows how to perform a boolean or with 2 or more keys. OR is not needed in this scenario which may be confusing without an example.
Release notes on this feature: https://app.datadoghq.com/release-notes/tackle-expected-maintenance-periods-proactively-with-more-flexible-downtimes
> Add downtime example with boolean OR across two different groups

- content/en/real_user_monitoring/guide/best-practices-for-rum-sampling.md
The document mentions "sessions" in all sub sections, however, it lacks the definition of what is a session in the overall structure. 
The present PR updates the document, to provide better visibility of what is a "session". By moving the Learn about what is a session to the Overview section.
This will clarify a lot of pending question about when changing the sampling rate data will change affect the collection of errors. This because, in the documentation about a session it defines what is a session, so customers can understand it.
> Update best-practices-for-rum-sampling.md to give better visibility on how a RUM session is defined

- .gitlab-ci.yml
Migrate pa11y job to use K8s architecture
https://datadoghq.atlassian.net/browse/WEB-4531
Gitlab preview pa11y job started as expected https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/424944917
> Swap pa11y runner

- content/en/agent/troubleshooting/debug_mode.md
This implies this config change is possible outside dedicated containers which isn't accurate.
The log level _can_ be changed by remote config but NOT via the CLI currently.
> trace-agent log level can not be updated from cli

- content/en/monitors/downtimes/_index.md
Reverts DataDog/documentation#21639
Found out that this is not supported, this example evaluates as an AND not an OR. 
`Top level ORs are not supported, for example, service:A OR host:X. This requires two separate Downtimes.`
> Revert "Add downtime example with boolean OR across two different groups"

- go.mod
- go.sum
enable access to `api-catalog` icon from [websites-modules](https://github.com/DataDog/websites-modules/pull/286)
preview: https://docs-staging.datadoghq.com/websites-modules/generated/286/
> Generated by websites-modules - add api-catalog icon

- content/en/containers/kubernetes/tag.md
Adds instructions for Operator and Helm for all the tag extraction rules to use instead of the plain "Containerized Agent". Keeping the "Containerized Agent" instructions but removed the core "Agent" instructions as these were relative to modifying the `datadog.yaml` for host-installs. Which is pretty rare for these types of environments. 
Additionally moved all the extraction options (`xxxAsTags`) down to the the level 3 `###` header and put a new level 2 `##` header for "Tag Extraction" to help group these together. 
- Validated with sample deployments for all options. 
- It may make sense in the future to: 
- adjust all the options so they aren't all using a `{"app": "kube_app"}` mapping. Like I've done here for the Node Labels As Tags option. 
- double check and add any more …
> Add Operator and Helm instructions to Kubernetes Tag Extraction page

- content/en/cloud_cost_management/custom.md
To temporarily mitigate a Public Beta issue with Custom Costs JSON file uploads, make `Tags` a required JSON property that can be empty.
> Temporarily make JSON property Tags required

- content/en/tracing/metrics/runtime_metrics/dotnet.md
Add .NET 8 to the list of supported runtime in the Runtime Metrics page for .NET.
We added general support for .NET 8 a few months ago and neglected to update this page. 
n/a
> [APM > Runtime Metrics > .NET] add .NET 8 as supported runtime

- config/_default/menus/menus.en.yaml
https://github.com/DataDog/documentation/pull/21493 seemed to accidentally remove the config we had for 4th level nav exceptions with Automatic and Custom Instrumentation parent pages.
This PR adds those lines back.
> Fix Instrumentation Left-Nav

- content/en/account_management/scim/_index.md
A customer has to be on Infra Enterprise (aka paying for Enterprise hosts) to have the SCIM feature available (We consider SCIM under Advanced Administrative Tools on https://www.datadoghq.com/pricing/?product=infrastructure#products)
One customer expressed confusion because they thought it was required to be in the "enterprise sales segment" which is just how many employees their company has and not related to how much they pay for Datadog. So I want to clarify that.
I think maybe it's better to say Enterprise plan over account: another enterprise-only feature Usage Attribution is called out here, so my thought is to make it more consistent btwn these 2 pages https://docs.datadoghq.com/account_management/billing/usage_attribution/
> Make it more clear than enterprise account means Infra Enterprise SKU

- content/en/service_catalog/adding_metadata.md
changing from 'service.datadog.yaml' to 'entity.datadog.yaml'
> updating service catalog yaml name for v3

- content/en/cloud_cost_management/custom.md
Remove temporary requirement for an empty `Tags` property when submitting JSON files
> Remove requirement for empty "Tags" JSON property

- content/en/security/cloud_security_management/setup/_index.md
A support ticket came in where the customer as well as the Support Engineer were not able to easily identify which version of the Agent is required at minimum for the CSM features. Adding additional information to make that more clear.
More work needs to be done on this page, but would like to get this small change published, as it's needed in the short term.
> Make it more clear the minimum Agent version for all CSM components

- content/en/getting_started/tagging/_index.md
- content/en/getting_started/tagging/using_tags.md
Add information about using tags in the CI Visibility Explorer for test runs + pipeline executions (two Search and Manage pages in Test Visibility and CI Visibility) in the Getting Started with Tags documentation.
> DOCS-7198 Using Tags + Getting Started with Tags Edit

- static/resources/sh/data_jobs/datadog_emr_job_monitoring_init_v2.sh
Adding those two new options:
- DD_TRACE_AGENT_URL=http://localhost:8126 to force http protocol. Not using http caused some issues on ARM
- DD_TRACE_EXPERIMENTAL_LONG_RUNNING_ENABLED=true to enable long running traces by default
> Data Jobs Monitoring - Additional tracer options for EMR init script

- content/en/tracing/faq/trace_sampling_and_storage.md
Flamegraphs retention 15 days --> 30 days so it's consistent with the information in https://docs.datadoghq.com/developers/guide/data-collection-resolution-retention/#pagetitle
> Flamegraphs retention 15 days --> 30 days

- .gitlab-ci.yml
Allows the live redirect meta job to fail temporarily until #21501 is merged
[Failing Job](https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/429902274)
[Context](https://dd.slack.com/archives/C0DESMBQU/p1707427114217719)
> Temporarily allow live redirect job to fail

- content/en/developers/authorization/oauth2_in_datadog.md
Updating OAuth documentation with new guidelines on usage for `site` and `domain` parameters
> Update info on site/domain params

- content/en/monitors/notify/_index.md
- content/en/monitors/types/metric.md
- Add note that percentile aggregators will not render a snapshot of the graph in notification messages.
- [DOCS-7175](https://datadoghq.atlassian.net/browse/DOCS-7175)
[DOCS-7175]: https://datadoghq.atlassian.net/browse/DOCS-7175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add note about percentile aggregators

- content/en/getting_started/devsecops/_index.md
The DevSecOps bundle include Application Vulnerability Management capabilities. The setup link takes the user to the ASM general setup page, which may lead to activations of Threat Management capabilities, which are not included in teh bundle
> Fixing reference to Application Vulnerability Management

- content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md
Flutter v2 was released a bit back but the migration guide was not added to docs.
refs: RUM-3122
> Update RUM migration guide for Flutter

- content/en/tracing/other_telemetry/connect_logs_and_traces/python.md
When trying to implement the code snippet from the docs, `trace_id` was not defined. Looking through git history, it looks like calling `trace_id` off of span was accidentally dropped off in [this PR](https://github.com/DataDog/documentation/pull/21565/files).
> fix: call trace_id off of span

- content/en/opentelemetry/guide/otlp_delta_temporality.md
Improve the code base of delta temporality documentation section. 
- For most language, there's no consoleExporter, what difficult the initial test. I did add the consoleExporter o Metric Provider for Go and Python, it will help the initial tests for users.
- The consoleExporter on C# language is not configured with the delta temporality, and it can cause confusion on tests when the stdout show cumulative temporality aggregation by default, but the metrics as really are being sent with delta temporality. I did configure also the consoleExporter with delta temporality preference to don't cause any confusion.
- Also, I did configure all exporter with 5s of interval to make the code more interactive. In some languages, it can take 1 min to show the stdout results.
I used this documentation …
> update: improving code examples for go, c# and python language

- content/en/cloud_cost_management/container_cost_allocation.md
CCM is deprecating `*.cpu.allocated` and `*.mem.allocated` metrics. Removing all associated documentation.
Also adding `managed_service_fee` and some additional context around cost calculations for compute.
Please wait to merge until we've fully deprecated for all customers (targeting Jan 29).
> [CCM] remove cpu. and mem.allocated container cost metrics

- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config_preview.yaml
Some rules are displaying which don't currently in the app e.g [cis-kubernetes-1.5.1-5.2.7](https://docs.datadoghq.com/security/default_rules/cis-kubernetes-1.5.1-5.2.7/)
Currently the best indicator for whether we should show or hide these is the isEnabled flag. So this PR specifically checks posture-management for this flag for display.
These rules are likely to be re-evaluated soon and potentially removed or flagged in otherways. So potentially this logic could be removed in the future.
This rule shouldn't exist
https://docs-staging.datadoghq.com/david.jones/rules/security/default_rules/cis-kubernetes-1.5.1-5.2.7/
This should populate with rules still but searching for something like NET_RAW shouldn't return any results
https://docs-staging.datadoghq.com/david.jones/rules/security/defau …
> Rule removals

- Makefile
bumps assetlib version to allow for new fields: https://github.com/DataDog/dd-source/pull/74007
> [ecos 1215] Bump assetlib version

- content/en/metrics/_index.md
- Add algolia tags for "submit metrics" and "metrics submission" to the Metrics landing page.
- Entering "submit metrics datadog" sometimes points users to the Workflows Submit Metrics or other pages that are tangentially related.
- Bumping the main Metrics page as the main starting point for users.
- https://datadoghq.atlassian.net/browse/DOCS-7232
- https://datadoghq.atlassian.net/browse/WEB-3535
> Add algolia tags for metrics submission

- content/en/getting_started/support/_index.md
Adding a banner to our Support page informing customers that Live Chat will not be available on President's Day, February 19th 2024.
This PR adds a callout box to the top of this article, informing our customers that we will not be offering chat during the US Holiday of President's Day. It's intended to be on this docs page only temporarily, and I will submit another PR to remove it immediately after the holiday.
- I think this should be merged no earlier than Wed Feb 14th.
I've reached out about this on slack here: https://dd.slack.com/archives/C0DESMBQU/p1707779550610169
> Add a callout for chat on US holiday

- .github/CODEOWNERS
I discovered in https://github.com/DataDog/documentation/pull/21849 that my team was not requested for review.
Several folders were created in the `content/en/continuous_delivery/` directory as well as other directories for Software Delivery documentation. However, the current `CODEOWNERS` file only match files under the `content/en/continuous_delivery/` folder, and not files in subfolders.
This PR fixes this for all folders my team should review.
> [Software Delivery] Update codeowners

- content/en/tracing/trace_collection/compatibility/python.md
Updated the release support table in our public docs to match those in our ddtrace docs https://ddtrace.readthedocs.io/en/stable/versioning.html#release-support
This notes that version 1.x of the tracer is in Maintenance level of support . Our public docs are not updated with this information and state that v1.x is still in General Availability support.
Updates the release support table in our Python compatibilities doc.
> Update python.md release support table

- content/en/serverless/azure_app_services/azure_app_services_windows.md
Adds .NET 8 to the list of supported frameworks for the AAS extension. Noticed the error while browsing generally.
> [.NET] [AAS] Update supported framework versions

- content/en/continuous_integration/pipelines/azure.md
We very often get questions from customers installing extensions the "Datadog" extension instead of the "Datadog CI Visibility" extension. I tried to emphasize that adding a sentence, but this can be improved.
> [CI Visibility] Clarify Azure extension name

- content/en/monitors/notify/variables.md
Explain sub-monitor enrichment in docs (e.g. `{{a.log.message}}`).
> Add docs on composite monitor enrichment

- content/en/profiler/connect_traces_and_profiles.md
- content/en/tracing/trace_collection/library_config/php.md
With the [`0.98.0`](https://github.com/DataDog/dd-trace-php/releases/tag/0.98.0) release timeline is now default enabled as well as the `EXPERIMENTAL` removed.
> Update Timeline config for PHP

- content/en/cloud_cost_management/custom.md
We've recently added a way for customer to send cost file through the API using a request instead of a multi part file. This documentation change state this change
You can check the result here: https://docs-staging.datadoghq.com/julien.hemery/add-json-request-doc/cloud_cost_management/custom/?tab=csv
> Add documentation of JSON request and CSV file using the API

- content/en/getting_started/support/_index.md
On President's Day, we removed Live Chat for Standard Support customers. We put up a banner on the support docs page to inform customers. This PR removes that banner now that the holiday is over.
Removes the banner informing customers about our chat schedule from the Monday holiday
Discussed in this slack thread: https://dd.slack.com/archives/C0DESMBQU/p1707779550610169
> Removing banner for Holiday Chat Removal

- content/en/cloud_cost_management/tag_pipelines.md
CCM customers want to allocate costs back to teams, services, and environments – and believe Tag Pipelines will help them do that.
Updating the docs to exclude those tags from allocation.
> [CCV-1382] Support reserved tags (env, service, version)

- content/en/monitors/guide/reduce-alert-flapping.md
"Avalanche control" has not been active on monitors for a couple of years (at least) it depended on ASN's sharding scheme which changed.
> [monitors] Remove link to outdated blog post

- content/en/account_management/billing/usage_metrics.md
- [DOCS-7206](https://datadoghq.atlassian.net/browse/DOCS-7206)
- Add Events usage metrics to the estimated usage metrics table
[DOCS-7206]: https://datadoghq.atlassian.net/browse/DOCS-7206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add events usage metrics

- content/en/integrations/guide/source-code-integration.md
Adds the Gitlab tab and related information to the Source Code integration per
[DOCS-7243](https://datadoghq.atlassian.net/browse/DOCS-7243)
[DOCS-7243]: https://datadoghq.atlassian.net/browse/DOCS-7243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7243] updating source code integration

- content/en/code_analysis/software_composition_analysis/generic_ci_providers.md
Adds a missing line to the Bash script for uploading an SBOM with a generic CI provider for the Code Analysis product.
> Fix SBOM Upload Instructions

- content/en/metrics/_index.md
- Clarify that metrics can be aggregated with functions as a whole, rather than just rollup().
- [DOCS-7238](https://datadoghq.atlassian.net/browse/DOCS-7238)
[DOCS-7238]: https://datadoghq.atlassian.net/browse/DOCS-7238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Clarify metrics time aggregation

- content/en/developers/integrations/create_a_tile.md
- content/en/developers/integrations/marketplace_offering.md
- content/en/integrations/adobe_experience_manager.md
- content/en/integrations/kubernetes_audit_logs.md
- content/en/integrations/nxlog.md
- content/en/integrations/rsyslog.md
- content/en/integrations/sinatra.md
- content/en/integrations/syslog_ng.md
- content/en/intelligent_test_runner/setup/dotnet.md
- content/en/intelligent_test_runner/setup/java.md
- content/en/intelligent_test_runner/setup/javascript.md
- content/en/intelligent_test_runner/setup/python.md
- content/en/intelligent_test_runner/setup/swift.md
- content/en/security/cloud_siem/signal_correlation_rules.md
- content/en/tests/setup/_index.md
- content/en/tests/setup/dotnet.md
- content/en/tests/setup/java.md
- content/en/tests/setup/javascript.md
- content/en/tests/setup/junit_xml.md
- content/en/tests/setup/python.md
- content/en/tests/setup/ruby.md
- content/en/tests/setup/swift.md
- content/en/tests/swift_tests.md
In relation to #21896 we discovered we can get in a temporary state of 404 links between redirect passes that run.
This PR fixes current aliases without a leading slash.
> alias cleanup, leading slash

- config/_default/params.yaml
- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/unity.md
- Adds Unity to the list of code lang params
- Hides the Unity page from the mobile setup page
- Edits the private beta text to include "contact your CSM"
- Once we figure out how requests to access this feature should be handled, we can make it visible again. At that point, we can add the Unity logo to the setup page.
> hide unity page for now

- content/en/monitors/types/composite.md
- Add combination example of `ALERT && OK` and `ALERT || OK`
- Fixed the table alignment
- [DOCS-7250](https://datadoghq.atlassian.net/browse/DOCS-7250)
[DOCS-7250]: https://datadoghq.atlassian.net/browse/DOCS-7250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add example for composite monitor combination table

- content/en/security/cloud_security_management/setup/csm_cloud_workload_security/_index.md
Adds an alias redirect for the CSM Threats setup page. Requested by PM.
> Add alias redirect for CSM Threats setup

- content/en/agent/guide/environment-variables.md
Update broken agent config links after [config.go was moved a couple months ago](https://github.com/DataDog/datadog-agent/commit/00b27d48c0dfb3cf41d05ee30c9fd43b647b88b4#diff-a7b6619528f155e64cefe12cc4ba753eb7688c87fdf9d96e1052a12eeb519df5) along with other files.
> Update config.go link after file was moved

- content/en/continuous_integration/_index.md
- content/en/continuous_integration/pipelines/_index.md
- content/en/continuous_integration/pipelines/azure.md
- content/en/continuous_integration/pipelines/buildkite.md
- content/en/continuous_integration/pipelines/circleci.md
- content/en/continuous_integration/pipelines/custom.md
- content/en/continuous_integration/pipelines/custom_tags_and_measures.md
- content/en/continuous_integration/pipelines/github.md
- content/en/continuous_integration/pipelines/gitlab.md
- content/en/continuous_integration/pipelines/jenkins.md
- content/en/continuous_integration/search/_index.md
This PR renames the custom_tags_and_metrics.md page to custom_tags_and_measures.md (while maintaining an alias to the old path). We also rename every outdated mention of "metrics" to "measures" in the continous_integrations pages
Context: https://docs.google.com/document/d/1X9-0eiiNaDsfLMKlVYsGdQs4RDKGZx9jEqLX4NEPAxY
> [CIVIS-9204] Rename mentions of "metrics" to "measures" in CI docs

- content/en/synthetics/private_locations/configuration.md
This PR adds a mention of the HTTPS proxies behavior in the Synthetics Private Location proxy configuration option:
- When using a HTTPS proxy, the Private Location sends an initial [HTTP CONNECT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT) request to the proxy
- A forward-proxy will initiate the tunnel connection to Datadog
- However some customers use a reverse-proxy, that instead forwards the `CONNECT` to Datadog and is not supported
We want to provide a note that reverse-proxies are not supported, and a forward proxy should be use in addition / instead.
> [Synthetics] Private Location: Document the behavior of reverse proxies with Datadog intake

- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config_preview.yaml
Fixes a bug where we should link to compliance not identities in the app when the button is CSM Misconfigurations (infra or cloud)
This work relates to https://datadoghq.atlassian.net/browse/WEB-4345 and #21461 
- Check a csm identity risks rule "view identities" button still links to identities in the app e.g [example rule](https://docs-staging.datadoghq.com/david.jones/secrule-findings/security/default_rules/ciem-aws-ec2-instance-with-update-login-profile/)
- Check a csm misconfigurations rule "view misconfigurations" button links correctly to compliance now instead of identities e.g [example rule](https://docs-staging.datadoghq.com/david.jones/secrule-findings/security/default_rules/cis-kubernetes-1.5.1-4.2.1/)
- Check a csm security rule only has "Show rule in datadog" button e.g …
> updated sec rule findings url

- config/_default/menus/menus.en.yaml
- content/en/tests/setup/junit_xml.md
In our previous [PR](https://github.com/DataDog/documentation/pull/21897), we missed renaming metrics to measures in the `datadog-ci junit` docs and the menu.
Context: https://docs.google.com/document/d/1X9-0eiiNaDsfLMKlVYsGdQs4RDKGZx9jEqLX4NEPAxY
> [CIVIS-9204] Rename metrics to measures in junit docs and menu

- content/en/logs/explorer/watchdog_insights.md
Add details to make it explicit that Insights found in the Log Explorer are now not only log but can come from other products.
- Do not merge yet, as we're still writing the release notes.
> Watchdog Cross-Product Insights in Log Management

- content/en/security/cloud_security_management/setup/_index.md
This PR aims to expand on the CSM Setup page to help customers identify their scope of protection (resource types) when they enable certain CSM features .
> [DOCS-7242] adding scope of protection matrix and EKS support

- content/en/developers/dogstatsd/_index.md
This describes the implementation in https://github.com/DataDog/php-datadogstatsd/pull/148 that adds support for the `DD_DOGSTATSD_URL` environment variable in the php-dogstatsd library.
> Add documentation for DD_DOGSTATSD_URL env var in PHP dogstatsd client

- content/en/agent/configuration/network.md
Small update to the Agent - Network page to add an H3 for "Static IP addresses" as well as algolia search term to make this easier to find.
> [DOCS-7274] updating Network page to make IP Ranges easier to find

- content/en/tests/setup/javascript.md
After https://github.com/DataDog/dd-trace-js/pull/4090 we have more flexibility with the `after:run` event in Cypress. The objective of this PR is to let the user know.
https://docs-staging.datadoghq.com/juan-fernandez/cypress-after-run/tests/setup/javascript/?tab=cypress#cypress-afterrun-event
> [ci-visibility] Cypress `after:run` improvements

- content/en/getting_started/opentelemetry/_index.md
With OTel Collector `0.95.0` the Datadog connector is required.
This PR adds the Datadog connector to the OTel collector configuration.
Since OTel Collector version `0.95.0` this component is required in order to have stats calculation.
> Update Collector configuration

- content/en/service_catalog/adding_metadata.md
add mentions of kind:datastores and kind:queues
> adding more kind support in SC v3

- content/en/continuous_delivery/deployments/argocd.md
Setting the service is a very important part of the setup for Argo CD applications monitoring in Datadog. Currently, it's in a separate section after the default setup. This PR moves it to be part of the main setup to ensure that customers know about it and try to set it when possible.
> Move call to set dd_service annotation

- content/en/profiler/guide/isolate-outliers-in-monolithic-services.md
We've added a public API to support user-provided annotations which
whill appear in Go CPU and goroutine profiles. Document how to use them.
The advice on the "Isolate Outliers in Monolothic Services" is relevant
to this, and most of it applies to Go just as much as Java. Put the
Go-specific bits there.
> [PROF-9132] document Go custom profiler annotations

- content/en/containers/troubleshooting/_index.md
- This PR fixes a link on the Container Troubleshooting page. The third option in the overview was linked to an Amazon ECS doc instead of installing the agent on Kubernetes.
> [Update _index.md] kevin_gleeson

- content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md
Noticed that we put a `.` at the end of `OTEL_EXPORTER_OTLP_ENDPOINT` which definitely doesn't seem correct (and does not match any of the other examples for setting this environment variable on the same page).
N/A
> Remove incorrect '.' in environment variable example

- .gitlab-ci.yml
Updates the image to a new pointer that has work to increase the assumed role timeout for the redirect metadata job to `30` minutes from `15`. 
https://datadoghq.atlassian.net/browse/WEB-4628
Nothing really to test but you can check [this pipeline](https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines/29306185) for a successful run on this image
> WEB-4682 | Update image (redirect metadata work)

- content/en/watchdog/alerts/_index.md
It is possible to disable log anomaly detection but the instruction were not documented.
> add instruction to disable log anomaly detection

- content/en/containers/guide/datadogoperator_migration.md
Adds a deprecation warning for DatadogAgent `v1alpha1` version, similar warning was added to helm charts and the binary
https://github.com/DataDog/helm-charts/pull/1332
https://github.com/DataDog/datadog-operator/pull/1099
> DatadogAgent v1alpha1 deprecation warning

- content/en/infrastructure/faq/set-up-orchestrator-explorer-daemonset.md
Updates instructions for changes introduced in Agent v7.51.0. Orchestrator runs on the main agent container instead of the process-agent container.
> Update instructions to enable Orchestrator for Agent v7.51+

- content/en/tracing/guide/inferred-service-opt-in.md
remove all mentions of DD_TRACE_PEER_SERVICE_DEFAULTS_ENABLED
> Update inferred-service-opt-in.md remove previous config rec

- content/en/tracing/trace_collection/tracing_naming_convention/_index.md
> update link to span tags definition

- content/en/cloud_cost_management/custom.md
- Clarification that dates become UTC timestamps at the 0th hour.
- Clarification that ChargePeriodEnd is "inclusive"
> Small Clarifications for Custom Costs

- content/en/tracing/trace_collection/compatibility/python.md
Drops support for `gevent<20.12`.
> ddtrace: update gevent support

- content/en/agent/configuration/agent-fips-proxy.md
Add a new supported platform for FIPS
https://docs-staging.datadoghq.com/nicolas.guerguadj/add-suse-as-supported-for-fips/agent/configuration/agent-fips-proxy/?tab=hostorvm#supported-platforms-and-limitations
> docs: add SUSE in supported platform for FIPS

- content/en/infrastructure/containers/configuration.md
In the Kubernetes product, we are now using `container.*` metrics to display CPU and memory usage instead of `kubernetes.*`. Since those metrics have been made GA with the datadog-agent `7.33.0`, I'm updating the minimum agent versions required for the orchestration explorer to work.
More context here: https://github.com/DataDog/web-ui/pull/125848
None, minor change
> [CAP-668] Update the minimum agent versions required for the orchestration explorer to work since we are using `container.*` metrics

- content/en/logs/log_configuration/attributes_naming_convention.md
The fields `network.client.ip` and `network.client.port` currently refers explicitly to TCP connection, but other integrations could be using this field more globally. Suggesting removing TCP mentions to make it more generic.
> Removing TCP mentions from Network Standard Attributes

- assets/scripts/components/mobile-nav.js
- assets/scripts/datadog-docs.js
- config/_default/menus/menus.en.yaml
- go.mod
- go.sum
- layouts/partials/nav/left-nav.html
1. adds a menu param (`skip`). used in the `datadog-docs` script to only query and select menu items we want to open. 
- two menu items purposefully have the same `url` param value (i.e. `data_security/pci_compliance/`). In order for the script to select a menu item after the first, we use the `skip` param to ignore certain menu items for opening.
2. includes auto-generated webistes-modules ref update
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4530
preview: https://docs-staging.datadoghq.com/websites-modules/generated/295/logs/
- select **PCI Compliance** under **Log Management > Log Management**. the url should still read `data_security/pci_compliance`, the Log Management menu should close and the **Administration > Data Security** …
> skip opening certain menu items - [WEB-4530]

- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Fix the JSON supplied for applying custom sampling rules. The provided JSON is invalid and won't work
> [APM] [Tracing] Fix JSON used in custom sampling rules

- content/en/security/notifications/variables.md
It adds the documentation for the new template variable added in this [PR](https://github.com/DataDog/logs-backend/pull/66505)
Example:
In the rule message:
Rendered message:
> [SEC-12866] Add documentation about events_matched template variables

- content/en/tracing/trace_collection/custom_instrumentation/otel_instrumentation/java.md
fixing a typo after confirming typo with Java engineers. 
Confirmation can be found here on the function name: https://javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/trace/Span.html
> Update java.md fixing typo

- content/en/real_user_monitoring/error_tracking/mobile/expo.md
Expo users see a `upload sourcemaps from your git repository` warning when looking at an unminified RUM error.
This is because they are uploading their file on the EAS CI tool, which by default does not setup git.
To setup git, an additional configuration option needs to be set.
> Add step to link git to EAS projects

- content/en/integrations/guide/prometheus-host-collection.md
This PR updates 2 `prometheus.` metrics references in  the prometheus host collection guide that are now super-ceded by new metrics.
Namely, `prometheus_url` has been replaced by `openmetrics_endpoint` and `prometheus_metrics_prefix` has been replaced by `raw_metric_prefix`.
https://github.com/DataDog/integrations-core/blob/master/openmetrics/datadog_checks/openmetrics/data/conf.yaml.example#L49-L52
https://github.com/DataDog/integrations-core/blob/master/openmetrics/datadog_checks/openmetrics/data/conf.yaml.example#L59
> [DOCS-7348] upating prometheus host collection 

- content/en/dashboards/_index.md
- content/en/dashboards/sharing.md
- content/en/dashboards/widgets/_index.md
- content/en/logs/guide/correlate-logs-with-metrics.md
- Move `Graph menu` and `Global time selector` from Dashboard landing page to the Widget landing page.
- Part of Dashboard reorg work
> Move widget specific information from landing page to widget page

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
- content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Fixes the package name for the CosmosDb integration, as it appears on NuGet: https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.6.0
N/A
> APM > .NET > Fix package name for Cosmos DB integration

- content/en/tracing/trace_collection/runtime_config/_index.md
With the latest Java tracer release it now supports custom tags for config at runtime. Updating the docs to reflect current support.
https://github.com/DataDog/dd-trace-java/releases/tag/v1.31.0
> update config at runtime java tracer version for tags

- layouts/standard-attributes/list.html
updates the standard attributes pg to make the **product** filter button and **source** tooltip names match.
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4573
preview: https://docs-staging.datadoghq.com/stefon.simmons/update-standard-attributes-source-names/standard-attributes/
- hover over the **SOURCE** column icons. the tooltips should match the product filter button names
- filtering via the buttons should still work
> product and source names match - standard attributes - [WEB-4573]

- data/partials/home.yaml
We're not charging customers for CD Visibility at the moment, we are charging customers for [Test Visibility & ITR](https://www.datadoghq.com/pricing/?product=test-visibility--intelligent-test-runner#products), so I am replacing the `CD Visibility` tile on the Docs Site landing page with a tile for `Test Visibility`.
> Replace CD Visibility Tile with Test Visibility

- content/en/tests/setup/javascript.md
* Let users know about the explicit `after:spec` handler in the cypress plugin.
* Add troubleshooting section for `Cannot find module 'dd-trace/ci/init'` errors. 
* [new troubleshooting section](https://docs-staging.datadoghq.com/juan-fernandez/ci-javascript-improvements/tests/setup/javascript/?tab=cloudciprovideragentless#how-to-fix-cannot-find-module-dd-traceciinit-errors)
* [new after:spec section](https://docs-staging.datadoghq.com/juan-fernandez/ci-javascript-improvements/tests/setup/javascript/?tab=cypress#cypress-afterspec-event)
* [new after:spec section for cypress <10](https://docs-staging.datadoghq.com/juan-fernandez/ci-javascript-improvements/tests/setup/javascript/?tab=cypress#cypress-afterspec-event-1)
> [test-visibility] Improvements to javascript section

- assets/scripts/region-redirects.js
set `site` url param with selected region whether the param already exists or not.
motivation: https://datadoghq.atlassian.net/browse/WEB-4546
preview: https://docs-staging.datadoghq.com/stefon.simmons/update-site-region-url-state/account_management/saml/
- select a region from the region dropdown on the right.
- the `site` param should be appended to the url and the `site` Cookie should be set to the selected region
- the `site` param should not persist when navigating othes pages but the Cookie and dropdown should.
> set `site` param to selected region - [WEB-4546]

- content/en/cloud_cost_management/container_cost_allocation.md
We want to clarify that Persistent volume allocation does not work for pods that are part of a Kubernetes Deployment.
> add clarification on deployment pods

- content/en/observability_pipelines/legacy/reference/sinks.md
- content/en/observability_pipelines/legacy/reference/sources.md
- content/en/observability_pipelines/legacy/reference/transforms.md
- i18n/en.json
- layouts/reference/single.html
enable displaying `legacy` content
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4648
previews: 
- https://docs-staging.datadoghq.com/stefon.simmons/fix-obs-legacy/observability_pipelines/legacy/reference/sources/
- https://docs-staging.datadoghq.com/stefon.simmons/fix-obs-legacy/observability_pipelines/legacy/reference/sinks
- https://docs-staging.datadoghq.com/stefon.simmons/fix-obs-legacy/observability_pipelines/legacy/reference/transforms
> add legacy param

- content/en/tracing/trace_collection/library_config/php.md
With https://github.com/DataDog/dd-trace-php/pull/2434 the PHP profiler can now collect exception messages for exception samples it takes.
> Add exception messages setting for PHP profiler

- static/resources/yaml/observability_pipelines/v2/setup/aws_eks.yaml
- static/resources/yaml/observability_pipelines/v2/setup/azure_aks.yaml
- static/resources/yaml/observability_pipelines/v2/setup/google_gke.yaml
Refactor OP Helm chart values for OPW2.0:
- Remove `datadog.apiKey` and `datadog.pipelineId` from values file; these secrets should be injected via **set** param: `helm install --set datadog.apiKey=<API_KEY>`
- Remove mounted volumes and disk buffering configurations; disk buffering should be disabled by default
- Remove Network LoadBalancer configurations; basic k8s service (`ClusterIP`) is sufficient enough for the quickstart/example setup
This is OPW2.0 work-in-progress.
> [PRODUCTSA-1093] Refine K8S Helm chart values

- content/en/cloudcraft/account-management/enable-sso-with-generic-idp.md
- content/en/cloudcraft/account-management/enable-sso.md
Seems like when rewriting Cloudcraft's SSO documentation we made a copy/paste mistake by refering to Azure AD on the overall documentation. This PR fixes that.
> Fix Cloudcraft's SSO documentation

- content/en/network_monitoring/devices/snmp_traps.md
[DOCS-7375](https://datadoghq.atlassian.net/browse/DOCS-7375)
Removing example stating “limited to only a single v3 user” , and adding new example for multi-user v3, with note this is now supported in Agent `7.51` and higher 
[DOCS-7375]: https://datadoghq.atlassian.net/browse/DOCS-7375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7375] adding support for SNMP v3

- content/en/tracing/trace_collection/compatibility/java.md
JDK-21 virtual threads are no longer in beta.  This remove the beta warning.
[x] Please merge after reviewing
> remove beta warning for JDK-21

- .github/workflows/preview_link.yml
- content/en/agent/basic_agent_usage/aix.md
- content/en/agent/faq/agent_v6_changes.md
- content/en/code_analysis/software_composition_analysis/_index.md
> (maint) Fix env interpolation in preview link action

- content/en/dynamic_instrumentation/expression-language.md
add `@exception` keyword for uncaught exception
add `instanceof` operator for type comparison
> Update expression-language.md for `@exception` and `instanceof`

- content/en/data_security/logs.md
Added the below security rules to the documentation due to recent Cloud SIEM code changes cc @nimishaaa and @clementgbcn 
* Security rules cannot include triggering group-by values in notification title.
* Security rules cannot include message template variables.
* Security rules cannot notify via webhooks.
> added security rules

- content/en/cloud_cost_management/container_cost_allocation.md
To clarify that Persistent volume allocation is currently only supported for pods that are part of a `StatefulSet`.
> Clarify statefulset

- content/en/synthetics/private_locations/_index.md
- content/en/synthetics/private_locations/configuration.md
The Synthetics Windows private location was made generally available a few weeks ago. We recently noticed that Windows private locations that report to `ddog-gov.com` could not start. This is due to a lack of support for FIPS compliance (for communications with Datadog) of this type of private location.
For now, we recommend using the `--disableFipsCompliance` config option to bypass the default behavior and fix their Windows private locations.
> [synthetics] Update documentation about Windows PL requirements

- content/en/containers/kubernetes/configuration.md
Fix YAML spacing
- The Operator's Cluster Agent token rules go under `global`
- The Helm Metrics Provider/HPA goes under the root `clusterAgent` instead of `datadog.clusterAgent`
> Fix YAML spacing for token/hpa

- content/en/tracing/error_tracking/exception_replay.md
https://www.datadoghq.com/blog/exception-replay-datadog/
> Add blog link to Exception Replay page
