- content/en/tracing/trace_explorer/trace_view.md
Improves search results for Trace View page
> [apm] add search tags to trace view page

- content/en/tracing/trace_collection/custom_instrumentation/dotnet.md
Undocument the possibility to have custom instrumentation without automatic instrumentation in .NET. Indeed, we are dropping this feature in our next major release and would like to avoid new customers to use it.
> [APM][.NET] Custom instrumentation requires automatic instrumentation

- content/en/dashboards/_index.md
Requested by support, customers are unaware of "View" restrictions because the Note is at the very bottom of the section.
> Convert note to alert-info

- content/en/tracing/service_catalog/integrations.md
> Updating Service Catalog PagerDuty integrations doc

- content/en/serverless/azure_app_services/azure_app_services_windows.md
Per #documentation, link goes to C# instead of Java docs.
> Fix incorrect link

- content/en/logs/_index.md
- content/en/logs/guide/getting-started-lwl.md
Add and update logs marketecture image. PMM request.
[DOCS-6627](https://datadoghq.atlassian.net/browse/DOCS-6627)
[DOCS-6627]: https://datadoghq.atlassian.net/browse/DOCS-6627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6627] Add and update logs marketecture image

- content/en/dashboards/functions/interpolation.md
- content/en/metrics/guide/interpolation-the-fill-modifier-explained.md
- Add a further reading section between two docs that reference the other
> Add a further reading between two docs pages

- content/en/account_management/scim/azure.md
Follow-on to https://github.com/DataDog/documentation/pull/20601. I realized that in moving the Azure setup content, I left one level of unnecessary nesting. This PR changes all of the headings to be one level bigger and removes the unnecessary and redundant top level heading. Also adds an introductory sentence.
> Reduce heading size

- content/en/account_management/scim/azure.md
Second follow-on to https://github.com/DataDog/documentation/pull/20601 to fix the links that I carelessly broke. Also adds a second line to the introduction.
> Fix the broken links on the SCIM Azure page

- content/en/synthetics/guide/_index.md
- content/en/synthetics/guide/api_test_timing_variations.md
- content/en/synthetics/guide/app-that-requires-login.md
- content/en/synthetics/guide/authentication-protocols.md
- content/en/synthetics/guide/browser-tests-using-shadow-dom.md
- content/en/synthetics/guide/explore-rum-through-synthetics.md
- content/en/synthetics/guide/manually-adding-chrome-extension.md
- content/en/synthetics/guide/rum-to-synthetics.md
- content/en/synthetics/guide/using-synthetic-metrics.md
Recommended Synthetics guide title changes.
Chat with Hugo P on Slack.
> Rename Synthetics Guides

- content/en/serverless/aws_lambda/metrics.md
[DOCS-6730](https://datadoghq.atlassian.net/browse/DOCS-6730)
[DOCS-6730]: https://datadoghq.atlassian.net/browse/DOCS-6730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6730] updating historical timeframe for custom metrics

- content/en/account_management/saml/mapping.md
Mapping SAML attributes went GA today. Remove the beta callout.
> Remove beta callout on SAML teams mapping

- content/en/containers/cluster_agent/admission_controller.md
[DOCS-6663](https://datadoghq.atlassian.net/browse/DOCS-6663)
[DOCS-6663]: https://datadoghq.atlassian.net/browse/DOCS-6663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6663] further clarify how to troubleshoot Admission controller

- content/en/agent/configuration/agent-fips-proxy.md
- content/en/containers/amazon_ecs/_index.md
> Update fips proxy documentation

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md
- content/en/tracing/trace_collection/dd_libraries/ios.md
> RUM-718 docs: update instructions to perform URLSession instrumentation

- content/en/tracing/services/service_page.md
remove reference to features that are often misused and will soon be retired
> remove reference to unsupported use cases given data limitation

- content/en/sensitive_data_scanner.md
Adds links to Terraform resources for SDS.
[DOCS-6679](https://datadoghq.atlassian.net/browse/DOCS-6679)
[DOCS-6679]: https://datadoghq.atlassian.net/browse/DOCS-6679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6679] Add links to Terraform resource for SDS

- content/en/logs/log_configuration/logs_to_metrics.md
Clarify steps to generate a log-based metric. User feedback.
[DOCS-6708](https://datadoghq.atlassian.net/browse/DOCS-6709)
[DOCS-6708]: https://datadoghq.atlassian.net/browse/DOCS-6708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6708] Clarify steps to generate a log-based metric

- content/en/account_management/scim/okta.md
Makes a tiny wording and capitalization fix.
> Tiny wording change to be more direct and fix capitalization

- content/en/containers/amazon_ecs/_index.md
> Update FIPS proxy version to 1.0.0

- config/_default/menus/menus.en.yaml
- content/en/database_monitoring/setup_oracle/troubleshooting.md
- content/en/database_monitoring/troubleshooting.md
> Add a simple Oracle troubleshooting guide

- config/_default/menus/menus.en.yaml
Update the TOC to be consistent with new product name
> Update TOC for new product name

- content/en/continuous_integration/pipelines/_index.md
- content/en/continuous_integration/tests/_index.md
Move ### Supported features section out of the Overview and into the Setup section. 
Chat with Kassen on Slack.
> Test Visibility and Pipeline Visibility Index Page Edits

- content/en/monitors/settings/_index.md
- Add best practice blog to relevant documentation page
> Add blog link to relevant docs page

- content/en/account_management/billing/usage_metrics.md
Added new estimated usage metrics for logs
> Updated estimated usage metrics

- content/en/dashboards/querying/_index.md
Change to min/max example or cross platform
Small update to Min/Max example.
> Minor change to min/max feature

- content/en/serverless/aws_lambda/troubleshooting.md
> Add a redirect for troubleshooting serverless

- content/en/integrations/_index.md
Adds a redirect for z/iris, which we're removing
- Merge after https://github.com/DataDog/marketplace/pull/908
> Redirect z/iris

- snippets/markdown.json
Noticed we didn't have a snippet for highlights
> Add VSCode snippet for code highlights

- content/en/tracing/trace_collection/library_injection_local.md
Small tweak to Local Library Injection.
> [DOCS-6298] Library Injection Tweaks

- content/en/profiler/enabling/java.md
> J9 profiler is now disabled by default

- content/en/infrastructure/process/_index.md
Adds instructions on enabling process monitoring in ECS Fargate + an example code snippet.
> Live Processes Update

- layouts/shortcodes/dbm-postgres-agent-config-examples.md
Since 7.48 we have implemented an auto discovery feature for databases on a database host for the postgres agent
> Add documentation about database autodiscovery for the postgres agent

- content/en/infrastructure/process/_index.md
Last (hopefully) update that rearranges the content in the tab, and drops the version # from the code snippet.
> Live Processes Edit

- content/en/metrics/custom_metrics/dogstatsd_metrics_submission.md
This change aligns our documentation with the agent implementation [here](https://github.com/DataDog/opentelemetry-mapping-go/blob/main/pkg/quantile/agent.go#L73-L80).
> Document Dogstatsd distribution sampling behavior

- layouts/shortcodes/audit-trail-security-platform.md
This PR adds the newly implemented Audit Events/Logs for the K9 Reports (subscribe/unsubscribe from the K9 Weekly Digests).
> [APPSEC-10990] Added audit logs for K9 reports

- content/en/profiler/connect_traces_and_profiles.md
- content/en/profiler/profile_visualizations.md
Document the timeline feature for PHP.
> add timeline for PHP

- content/en/service_management/workflows/access.md
Noticed a small anchor link error that probably happened when Workflow Automation was renamed from Workflows. The rest of the changes are made by the automated link organizer.
> Update the link to the permissions page with the correct anchor

- layouts/shortcodes/latest-lambda-layer-version.html
v12 of datadog-lambda-java was released.
https://datadoghq.atlassian.net/browse/SVLS-3933
> Bump datadog-lambda-java to version 12.

- content/en/tracing/guide/tutorial-enable-python-host.md
Since we explain how to install the dependencies using poetry, we should also explain how to run the project in poetry.
> Add poetry command example to Python tutorial

- content/en/tracing/trace_collection/compatibility/dotnet-core.md
- content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Updates on compatibility following our last release
> [APM][.NET] Changes in v2.42.0

- content/en/serverless/guide/serverless_warnings.md
Add a new Insight type to documentation, before re:Invent, written/approved by Product. 
None.
> Add a new Insight type to documentation.

- content/en/developers/integrations/python.md
https://datadoghq.atlassian.net/browse/WEB-4161
> Use shortcode for ddev versions

- content/en/continuous_integration/dora_metrics/_index.md
Removes restriction - these docs were published yesterday, we have changed a decision to allow more customers to be eligible
> Remove product restriction

- content/en/tracing/trace_collection/trace_context_propagation/python.md
> Update python.md with tracestate propagation and span links behavior

- content/en/tracing/trace_collection/trace_context_propagation/dotnet.md
Documenting the new `DD_TRACE_PROPAGATION_EXTRACT_FIRST` configuration and what it can be used for as the tracer with it has been released.
> Documenting new DD_TRACE_PROPAGATION_EXTRACT_FIRST configuration

- layouts/shortcodes/latest-lambda-layer-version.html
I just shipped the newest version
> Bump dd-trace-dotnet layer to version 13

- layouts/shortcodes/latest-lambda-layer-version.html
v51 of the Extension is now released. Ready to publish update to docs.
> Bump datadog-lambda-extension layer to version 51

- config/_default/menus/menus.en.yaml
- content/en/service_management/app_builder/auth.md
> Add App Builder Authorization page

- content/en/metrics/metrics-without-limits.md
Updated the video example of tag exclusion.
> Updated Link to Tag Exclusion Video

- layouts/shortcodes/latest-lambda-layer-version.html
I just deployed 100 and 101, but better to do this
> Bump datadog-lambda-js layer to version 101

- content/en/agent/fleet_automation/_index.md
Switches from private to public
Wait for @vignesh to give the 👍
> Fleet automation: switch beta

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 83

- .gitlab-ci.yml
- Makefile
- assets/scripts/reference-process.js
- assets/styles/vendor/_chroma-styles.scss
- config/_default/menus/menus.en.yaml
- content/en/observability_pipelines/reference/processing_language/_index.md
- content/en/observability_pipelines/reference/processing_language/errors.md
- content/en/observability_pipelines/reference/processing_language/functions.md
- data/reference/errors.json
- data/reference/functions.json
- layouts/partials/nav/left-nav.html
- layouts/partials/table-of-contents/table-of-contents.html
- layouts/shortcodes/vrl-errors.html
- layouts/shortcodes/vrl-functions.html
Adds vector remap landuage functions and errors reference docs
https://datadoghq.atlassian.net/browse/WEB-3722
https://docs-staging.datadoghq.com/david.jones/vrl-func-errors/observability_pipelines/reference/processing_language/functions/
https://docs-staging.datadoghq.com/david.jones/vrl-func-errors/observability_pipelines/reference/processing_language/errors/
---
> WEB-3722 - vrl functions and errors

- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md
> Simple word fix

- content/en/database_monitoring/setup_oracle/selfhosted.md
Adding hints for view optimization.
> [oracle] dd_session view optimization (DBMON-2996)

- content/en/observability_pipelines/guide/set_quotas_for_data_sent_to_a_destination.md
Adds a OP quota transform doc.
[DOCS-6753](https://datadoghq.atlassian.net/browse/DOCS-6753)
[DOCS-6753]: https://datadoghq.atlassian.net/browse/DOCS-6753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6753] Add OP quota transform doc

- content/en/real_user_monitoring/guide/monitor-kiosk-sessions-using-rum.md
- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
- content/en/real_user_monitoring/guide/tracking-rum-usage-with-usage-attribution-tags.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
Documentation had some code snippets from SDK v1 of our mobile SDKs, this PR updates them to SDK v2.
> Update some remaining references from SDK v1 to SDK v2 for Mobile SDKs

- content/en/real_user_monitoring/connect_rum_and_traces/_index.md
> docs: use dd-sdk-ios V2 APIs to enable APM tracing

- content/en/developers/integrations/log_integration.md
Clarify review guidelines to reduce back & forth with external contributors.
> Updating guide for Creating a Log Integration

- content/en/security/application_security/enabling/serverless.md
[DOCS-6618](https://datadoghq.atlassian.net/browse/DOCS-6618)
[DOCS-6618]: https://datadoghq.atlassian.net/browse/DOCS-6618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6618] removing beta banner for serverless

- content/en/observability_pipelines/guide/set_quotas_for_data_sent_to_a_destination.md
> Small edits for quota doc

- content/en/security/vulnerabilities/_index.md
Update to new blog link on CSM vulnerabilities page under Further reading.
> Update blog links on CSM vulnerabilities page

- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/android.md
Updates a 404 link on the Android Setup doc page.
Flagged by Jade in #documentation on Slack.
> Update 404 Link in RUM Android Setup Documentation

- content/en/integrations/guide/source-code-integration.md
Remove an extra language banner on the Source Code Integration doc page.
> Source Code Integration Edit

- content/en/getting_started/tagging/unified_service_tagging.md
> DOCS-6791 - add note about host information excluded for db/cache spans

- content/en/agent/basic_agent_usage/windows.md
- content/en/containers/docker/_index.md
Fix broken link since supported platforms content was moved to a new [page](https://docs.datadoghq.com/agent/supported_platforms)
> fix supported platforms link

- content/en/serverless/guide/serverless_tagging.md
> DOCS-6681 lambda tags not applied to enhanced metrics

- content/en/developers/community/libraries.md
> (DOCS-6800) Remove old library

- content/en/agent/faq/agent_v6_changes.md
- content/en/agent/faq/linux-agent-2022-key-rotation.md
- content/en/agent/guide/agent-5-autodiscovery.md
- content/en/agent/logs/advanced_log_collection.md
> (Maint) Remove vale errors from Agent docs

- content/en/developers/dogstatsd/data_aggregation.md
- content/en/developers/dogstatsd/datagram_shell.md
- content/en/developers/dogstatsd/dogstatsd_mapper.md
- content/en/developers/dogstatsd/high_throughput.md
- content/en/developers/dogstatsd/unix_socket.md
- content/en/developers/service_checks/dogstatsd_service_checks_submission.md
- content/en/service_management/events/guides/dogstatsd.md
- content/fr/developers/dogstatsd/_index.md
- content/fr/developers/dogstatsd/data_aggregation.md
- content/fr/developers/dogstatsd/datagram_shell.md
- content/fr/developers/dogstatsd/dogstatsd_mapper.md
- content/fr/developers/dogstatsd/high_throughput.md
- content/fr/developers/dogstatsd/unix_socket.md
- content/fr/developers/service_checks/dogstatsd_service_checks_submission.md
- content/ja/developers/dogstatsd/_index.md
- content/ja/developers/dogstatsd/data_aggregation.md
- content/ja/developers/dogstatsd/datagram_shell.md
- content/ja/developers/dogstatsd/high_throughput.md
- content/ja/developers/service_checks/dogstatsd_service_checks_submission.md
- content/ja/service_management/events/guides/dogstatsd.md
- content/ko/developers/dogstatsd/_index.md
- content/ko/developers/dogstatsd/data_aggregation.md
- content/ko/developers/dogstatsd/datagram_shell.md
- content/ko/developers/dogstatsd/dogstatsd_mapper.md
- content/ko/developers/dogstatsd/high_throughput.md
- content/ko/developers/dogstatsd/unix_socket.md
- content/ko/developers/service_checks/dogstatsd_service_checks_submission.md
> (DOCS-6655) Remove old link

- assets/styles/pages/_glossary.scss
- layouts/glossary/list.html
adds core product label under term 
preview:  https://datadoghq.atlassian.net/browse/WEB-4307
-  [x] Please merge after CorpWeb review
https://docs-staging.datadoghq.com/stefon.simmons/add-product-label-to-term/glossary/
> add product label to term - [WEB-4307]

- README.md
> Add SSH key instructions to README

- content/en/observability_pipelines/reference/processing_language/_index.md
- content/en/observability_pipelines/reference/processing_language/errors.md
- content/en/observability_pipelines/reference/processing_language/functions.md
> Add gov note to OP DPL

- content/en/continuous_integration/static_analysis/_index.md
Improves the organization of the integrations for Static Analysis
> Improve organization of Static Analysis integrations

- content/en/profiler/enabling/dotnet.md
The profiler supports .NET 8. Let's make sure this is documented.
> Clarify that the profiler supports .NET 8

- content/en/tracing/service_catalog/scorecards.md
> Clarifying logs correlation calculations

- layouts/shortcodes/latest-lambda-layer-version.html
Update `datadog-lambda-rb` layer version to `22`
N/A
> Bump `datadog-lambda-rb` layer to version `22`

- content/en/containers/kubernetes/log.md
Hotjar: 
[DOCS-6813](https://datadoghq.atlassian.net/browse/DOCS-6813)
[DOCS-6813]: https://datadoghq.atlassian.net/browse/DOCS-6813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6813] Update broken link

- content/en/serverless/azure_app_services/azure_app_services_container.md
- content/en/serverless/azure_container_apps/_index.md
- content/en/serverless/google_cloud_run/_index.md
Reduces Orchestrion-related information as it's in private beta. Requested on Slack.
> reducing orchestrion info

- content/en/tracing/guide/tutorial-enable-python-host.md
- content/en/tracing/trace_collection/dd_libraries/python.md
Fast-pressed https://github.com/DataDog/documentation/pull/20704, Nicholas flagged in #documentation Slack.
> Enabling Tracing for a Python Application on the Same Host as the Datadog Agent Edit

- content/en/getting_started/cloud_siem/_index.md
Adds new instructions for getting started with Cloud SIEM.
[DOCS-6843](https://datadoghq.atlassian.net/browse/DOCS-6843)
I will merge at 4:30pm ET.
[DOCS-6843]: https://datadoghq.atlassian.net/browse/DOCS-6843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6843] Update Getting Started with Cloud SIEM for new SKU

- content/en/continuous_integration/dora_metrics/_index.md
Current docs are incorrect, changed `started_at` to `finished_at` to accurately reflect a limitation
> Update DORA limitation copy 

- content/en/tracing/trace_collection/single-step-apm.md
Disable instrumentation for Kubernetes code snippet was incorrect. Fixing to align with local library injection instructions.
> Fix code snippet in Kubernetes instructions

- content/en/infrastructure/resource_catalog/_index.md
Tuesday Tasks -- adds a blog post.
> Add further reading blog post link

- content/en/tracing/trace_collection/compatibility/nodejs.md
Tuesday Tasks -- This was reported in a Transifex issue.
> Remove duplicate word

- content/en/service_management/events/_index.md
fix event management beta link and supported dc in public documentation
> fix event management beta link and supported dc in public documentation

- content/en/observability_pipelines/reference/processing_language/_index.md
> Update DPL reference docs to explicitly call out that DPL is VRL

- content/en/monitors/types/anomaly.md
Changes mentions of `enterprise-level` and `pro-level` to `enterprise plan` and `pro plan`. This has caused confusion in other parts of the doc site, and this seems to be the only file left with this phrasing.
> Change level to plan

- translate.yaml
Updates the translate config to remove some files
> update translate config

- content/en/tracing/trace_collection/library_config/java.md
Provides generic documentation about the conversion between system properties and environment variables for the Java tracer
> Write catch-all documentation for converting system properties and environment variables

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 85

- content/en/integrations/guide/application-monitoring-vmware-tanzu.md
we've deprecated the name "puppy agent" and now call it the container agent
> replace puppy agent name

- content/en/developers/ide_integrations/idea/_index.md
Minor wording improvement for the Static Analysis JetBrains integration
> Static Analysis JetBrains Wording Improvement

- content/en/data_security/real_user_monitoring.md
- content/en/logs/log_collection/flutter.md
- content/en/real_user_monitoring/dashboards/errors.md
- content/en/real_user_monitoring/dashboards/performance.md
- content/en/real_user_monitoring/dashboards/testing_and_deployment.md
- content/en/real_user_monitoring/dashboards/usage.md
- content/en/real_user_monitoring/guide/monitor-kiosk-sessions-using-rum.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/data_collected/roku.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/roku.md
> Link Checker Fixes

- content/en/tracing/troubleshooting/dotnet_diagnostic_tool.md
Update the diagnostic doc to mention the new dd-dotnet tool. Update the expected outputs.
> Updating the documentation for dd-dotnet

- content/en/partners/_index.md
Updating the list of Dash playlist links to be current and reordering them to be in descending chronological order (most recent first).
> Update Dash Youtube playlist links and reorder from most recent to least recent

- config/_default/menus/menus.en.yaml
- content/en/continuous_integration/pipelines/_index.md
- content/en/continuous_integration/pipelines/custom.md
Adds a new entry `Custom` into the Setup reference table of Pipeline Visibility.
> [CIVIS-8247] Add custom integration to the Pipeline Visibility setup table

- content/en/tracing/metrics/runtime_metrics/dotnet.md
- content/en/tracing/metrics/runtime_metrics/go.md
- content/en/tracing/metrics/runtime_metrics/java.md
- content/en/tracing/metrics/runtime_metrics/nodejs.md
- content/en/tracing/metrics/runtime_metrics/python.md
- content/en/tracing/metrics/runtime_metrics/ruby.md
> DOCS-6868 Add note and link about UDS support for tracing runtime metrics

- content/en/security/application_security/enabling/serverless.md
- content/en/security/application_security/troubleshooting.md
Replaces a missing image in two doc pages.
Flagged by Max in #documentation.
> Enabling ASM for Serverless Edit

- content/en/cloud_cost_management/aws.md
AWS released CUR 2.0, we need to update all setup/documentation of “CUR” to the “Legacy CUR”
More details here: [CUR 2.0](https://docs.google.com/document/d/18I_jEIR65bK3H26AojMsA9crqDW-kID6GFyFpOe3LAQ/edit#heading=h.vw24el6pa3ln)
> [CCV] CUR 2.0 - update public docs following CUR changes

- content/en/continuous_testing/explorer/search_runs.md
Noticed a typo in the Search Runs page - fixed it.
> Fixed typo in page

- content/en/serverless/azure_app_services/_index.md
- [ *] Please merge after reviewing
> Correct Beta label to GA for Java App Service extension

- content/en/account_management/audit_trail/forwarding_audit_events.md
Add note to say audit event forwarding is not available for US1-FED.
PM request.
> Add gov note for audit event forwarding

- content/en/opentelemetry/otlp_ingest_in_the_agent.md
The documentation has a number of typos where `gRPC` is mis-spelled `gPRC`. This changeset fixes them.
> Fix minor typos

- content/en/real_user_monitoring/mobile_and_tv_monitoring/data_collected/_index.md
- layouts/partials/rum/rum-getting-started-mobile-data-collected.html
- layouts/partials/rum/rum-getting-started-mobile-setup.html
Couple of link updates to fix corresponding links in the Data Collected and Setup sections in the RUM doc set.
> DOCS-6903 Cleanup RUM Data Collected + Setup Partial Links

- content/en/logs/error_tracking/backend.md
> Clarify required attributes for Error Tracking

- content/en/account_management/org_settings/cross_org_visibility.md
> Capitalize organization

- content/en/real_user_monitoring/error_tracking/android.md
This reverts commit 21d34e3596a76f85bf49a06eab2396486ca7c130.
> Revert "Update android.md (#21020)"

- .github/CODEOWNERS
- content/en/developers/ide_integrations/idea/_index.md
- content/en/dora_metrics/_index.md
- content/en/static_analysis/_index.md
- content/en/static_analysis/rules/_index.md
Follow up to https://github.com/DataDog/documentation/pull/20816/.
> DOCS-6873 Static Analysis URL Update

- content/en/watchdog/_index.md
- content/en/watchdog/alerts/_index.md
Refactor the Watchdog Home page and the Watchdog alert page.
Initially focused on Watchdog alerts, the goal is to offer more visibility on the different Watchdog capabilities while also clarifying and centralising the information about Watchdog alerts
> Refactoring the Watchdog alert page

- content/en/database_monitoring/guide/managed_authentication.md
- content/en/database_monitoring/setup_postgres/azure.md
- content/en/database_monitoring/setup_sql_server/azure.md
> Update docs to reflect new name of Microsoft Entra ID

- content/en/security/application_security/enabling/compatibility/_index.md
- content/en/security/application_security/enabling/compatibility/dotnet.md
- content/en/security/application_security/enabling/dotnet.md
Adding support for .NET for code-level vulnerabilities
[DOCS-6889](https://datadoghq.atlassian.net/browse/DOCS-6889)
[DOCS-6889]: https://datadoghq.atlassian.net/browse/DOCS-6889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6889] support for .NET for code-level vulnerabilities

- content/en/agent/configuration/agent-fips-proxy.md
Adds a blog link to the Datadog Agent FIPS Compliance doc.
> Add blog link to Datadog Agent FIPS Compliance doc

- content/en/developers/ide_integrations/visual_studio/_index.md
Changes "plugin" to "extension" in the Visual Studio docs. Inconsistency was pointed out by Transifex translator.
> Change plugin to extension in Visual Studio docs 

- content/en/synthetics/guide/synthetic-test-retries-monitor-status.md
Updates image alt text in Synthetics docs. Inconsistency pointed out by a Transifex translator
> Update image alt text in Synthetics docs

- content/en/service_management/service_level_objectives/_index.md
Add a link to the SLO resource in the Datadog Terraform provider
> (DOCS-6600) Add link to Terraform resource

- content/en/synthetics/guide/manage-browser-tests-through-the-api.md
Add  Terraform instructions to the `Manage Your Browser Tests Programmatically` guide
> (DOCS-6600) Add Terraform section

- content/en/logs/log_configuration/_index.md
- content/en/logs/log_configuration/pipeline_scanner.md
- content/fr/logs/log_configuration/_index.md
- content/ja/logs/log_configuration/_index.md
Name consistency `Log Pipeline Scanner` (singular) + updated video for log config page
> Update Pipeline Scanner doc

- content/en/account_management/billing/pricing.md
Update top99p info in pricing.md
* missed NPM Hosts
* updated Profiler Hosts phrasing
Follow-up from https://github.com/DataDog/documentation/pull/21011 and https://github.com/DataDog/documentation/pull/19350.
> Update top99p info for NPM & Profiler Hosts in pricing.md

- content/en/cloud_cost_management/google_cloud.md
[DOCS-6914](https://datadoghq.atlassian.net/browse/DOCS-6914)
[DOCS-6914]: https://datadoghq.atlassian.net/browse/DOCS-6914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6914] small update to clarify BigQuery Data Transfer API

- content/en/static_analysis/rules/_index.md
Adds one word to the Static Analysis Rules docs
> Add Java to Static Analysis rules message box

- content/en/agent/fleet_automation/_index.md
- content/en/agent/troubleshooting/send_a_flare.md
- layouts/shortcodes/remote-flare.md
Updates the flare instructions with the new remote config method of sending a flare. I'm using a partial to make sure the instructions don't stray over time.
> (DOCS-6837) Update flare instructions

- layouts/partials/nav/left-nav.html
Add another case to 4th level
https://docs-staging.datadoghq.com/david.jones/nav-case/tracing/trace_collection/custom_instrumentation/?tab=datadoglibraries
> add exception to 4th level

- content/en/logs/guide/_index.md
- content/en/logs/guide/manage_logs_and_metrics_with_terraform.md
- content/en/metrics/guide/_index.md
Adds a new guide on managing logs and metrics using Terraform.
[DOCS-6598](https://datadoghq.atlassian.net/browse/DOCS-6598)
[DOCS-6598]: https://datadoghq.atlassian.net/browse/DOCS-6598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6598] Add Manage Logs and Metrics with Terraform

- config/_default/menus/menus.en.yaml
- content/en/service_management/events/explorer/_index.md
- content/en/service_management/events/explorer/saved_views.md
- Part of the Event docs overhaul requested by Product team
- [DOCS-6528](https://datadoghq.atlassian.net/browse/DOCS-6528)
[DOCS-6528]: https://datadoghq.atlassian.net/browse/DOCS-6528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add save views docs for Event Management

- content/en/tracing/service_catalog/adding_metadata.md
add description for the custom extensions field
> Update metadata schema description 

- content/en/tracing/service_catalog/_index.md
add more structure to organize use cases and removing some out-dated info
> Update overview page for service catalog 

- config/_default/menus/menus.en.yaml
- content/en/serverless/step_functions/enhanced-metrics.md
Adds a page for enhanced step functions metrics
> DOCS-6929 - adding step functions enhanced metrics page

- content/ja/real_user_monitoring/browser/_index.md
I have found an unnecessary string in the Japanese document and would like to remove it.
> Delete unnecessary strings in Japanese documentation of Browser RUM

- content/en/containers/amazon_ecs/_index.md
Update ECS docs to use the latest fips-proxy version
> Update FIPS proxy version to 1.0.1

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 86

- layouts/shortcodes/latest-lambda-layer-version.html
[I just released it](https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.103.0)
> Bump datadog-lambda-js layer to version 103

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-extension layer to version 52

- assets/scripts/components/api.js
- assets/scripts/datadog-docs.js
fix scrollto distance for left nav
jira:  https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4391
preview: https://docs-staging.datadoghq.com/stefon.simmons/realign-scroll-to-left-nav/api/latest/
> increase distance from top for `left-nav`

- content/en/observability_pipelines/_index.md
- content/en/observability_pipelines/configurations.md
- content/en/observability_pipelines/guide/control_log_volume_and_size.md
- content/en/observability_pipelines/production_deployment_overview.md
Adds a footnote about OP's support for logs and metrics.
Removes mention of metrics in the Control Log Volume guide because it's focused on logs.
[DOCS-6908](https://datadoghq.atlassian.net/browse/DOCS-6908)
[DOCS-6908]: https://datadoghq.atlassian.net/browse/DOCS-6908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6908] Add note about OP logs and metrics support

- .gitignore
I forgot to update the .gitignore path after [doing some restructuring](https://github.com/DataDog/documentation/pull/20827).
> Ignore single sourced ruby file

- assets/scripts/components/table-of-contents.js
- assets/styles/pages/_global.scss
Anchors aren't consistently scrolling properly on Chrome browsers. This is a potential fix to address the issue by updating the DOM ready event to use window.onload instead
URL w/anchor example:
https://docs-staging.datadoghq.com/nsollecito/chrome-scroll-bug/static_analysis/?tab=circleciorbs#setup
> [WEB-4393] Fix anchor scrolling bug on Chrome browser

- assets/scripts/components/dd-browser-logs-rum.js
Updates RUM config to include user interactions for scroll maps
> Update RUM config to include user interactions for scroll maps

- content/en/quality_gates/explorer/_index.md
Just noticed that we could add an H2 and H3 section about Gate details + data (like what exists in the **Rules** tab).
> Quality Gates Explorer Update

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 87

- content/en/security/cloud_security_management/setup/_index.md
- content/en/security/cloud_security_management/setup/csm_enterprise.md
- content/en/security/cloud_security_management/setup/csm_pro.md
- content/en/security/cloud_security_management/setup/csm_workload_security.md
Fixing a discrepancy in the titles for the CSM setup articles.
> Fix CSM Article Titles

- content/en/service_management/case_management/_index.md
Add alert note that this product is not available in the US1-FED site.
> Add alert it's not available in US1-FED site

- content/en/observability_pipelines/working_with_data.md
- Add Datadog Processing Language (DPL) wherever VRL is mentioned
- Remove duplicate information, the remap section that is now in [Datadog Process Language](https://docs.datadoghq.com/observability_pipelines/reference/processing_language/).
- Remove TOML and JSON examples
- Add headers for examples
- Reorder link list
[DOCS-6909](https://docs.datadoghq.com/observability_pipelines/reference/processing_language/) and [DOCS-6161](https://datadoghq.atlassian.net/browse/DOCS-6161)
[DOCS-6909]: https://datadoghq.atlassian.net/browse/DOCS-6909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-6161]: https://datadoghq.atlassian.net/browse/DOCS-6161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6909] Update Working with Data

- content/en/observability_pipelines/guide/control_log_volume_and_size.md
- content/en/observability_pipelines/guide/custom-metrics-governance.md
- Adds DPL whenever VRL is mentioned.
- Updates a couple of links
- Removes a bunch of whitespaces
[DOCS-6161](https://datadoghq.atlassian.net/browse/DOCS-6161)
[DOCS-6161]: https://datadoghq.atlassian.net/browse/DOCS-6161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6161] Add DPL to mentions of VRL

- layouts/shortcodes/latest-lambda-layer-version.html
[I just shipped this version](https://github.com/DataDog/datadog-lambda-js/releases/tag/v7.104.0)
> Bump datadog-lambda-js layer to version 104

- content/en/real_user_monitoring/guide/mobile-sdk-deprecation-policy.md
- content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md
Introduces a Mobile SDK policy guide.
> [RUM-2088] Introduce Mobile SDK deprecation policy

- content/en/real_user_monitoring/session_replay/troubleshooting.md
> Add Web Animations API to unsupported tech

- content/en/real_user_monitoring/feature_flag_tracking/_index.md
Change Feature Flag Status documentation section to include third option, "Active".
> Add explanation of "Active" feature flag status

- assets/scripts/components/table-of-contents.js
- config/development/config.yaml
- layouts/partials/table-of-contents/scraped-toc.html
the [scraped-toc partial](https://github.com/DataDog/documentation/blob/a8aae936b3802d6bb2cdb534a10f2b5f976228d1/layouts/partials/table-of-contents/scraped-toc.html#L28) would encode (sanitize) non-en characters within its hrefs.
removes [DOMException error](https://slack-files.com/T023QM6JUS0-F06BLJ9HQFK-f4036141f1) on non-english pages that were scraped with the [scraped-toc partial](https://github.com/DataDog/documentation/blob/a8aae936b3802d6bb2cdb534a10f2b5f976228d1/layouts/partials/table-of-contents/scraped-toc.html#L28).
- decodes encoded non-en characters:
jira: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4402
preview ja: https://docs-staging.datadoghq.com/stefon.simmons/fix-tabs/ja/integrations/guide/aws-manual-setup/?tab=accesskeysgovcl …
> Remove DOMException Error

- content/en/security/misconfigurations/supported_frameworks.md
Updates CIS Azure version to 2.0.0.
> Update CIS Azure version

- content/en/infrastructure/containers/orchestrator_explorer.md
> update kubernetes yaml history doc

- content/en/database_monitoring/setup_oracle/_index.md
- content/en/database_monitoring/setup_oracle/autonomous_database.md
- content/en/database_monitoring/setup_oracle/exadata.md
- content/en/database_monitoring/setup_oracle/rac.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Removes beta mentions and streamlines Agent installation instructions in the DBM Oracle docs.
DOCS-6977
> Move Oracle to GA (MVP version)

- content/en/observability_pipelines/working_with_data.md
Clarify that it's a YAML configuration.
> Add YAML to specifiy configuration type

- config/_default/params.yaml
- content/en/glossary/terms/cardinality.md
- content/en/glossary/terms/count.md
- content/en/glossary/terms/distribution.md
- content/en/glossary/terms/gauge.md
- content/en/glossary/terms/granularity.md
- content/en/glossary/terms/histogram.md
- content/en/glossary/terms/query.md
- content/en/glossary/terms/rate.md
- content/en/glossary/terms/scope_(metrics).md
- content/en/glossary/terms/space_aggregation.md
- content/en/glossary/terms/template_variable.md
- content/en/glossary/terms/time_aggregation.md
Noticed that there was not metrics product in the glossary
> Add metrics product to glossary and terms

- content/en/tracing/trace_collection/library_injection_local.md
Updates the casing and formatting of the provided gcloud command, as pointed out by a translator
Resource:
https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login
> Clarify gcloud command

- content/en/tracing/trace_collection/compatibility/php.md
The Symfony 7 framework was released last month and the test suite for it was added:
- Datadog/dd-trace-php#2437 
We can now officially update our compatibility :+1:
> Add Symfony 7 compatibility

- content/en/getting_started/integrations/terraform.md
Update the `Getting started with Terraform` guide with new information and links
> (DOCS-6601) Add new resources

- content/en/containers/guide/kubernetes-cluster-name-detection.md
primarily changes an outdated link to a github permalink. also an editing refresh for this page.
> DOCS-6886 - update K8s Cluster Name Detection guide

- content/en/service_management/mobile/_index.md
Requested by a support engineer
> Alert users that mobile app is not available in gov

- content/en/account_management/rbac/granular_access.md
Changes "Gain Access" or "Gain Edit Access" to "Elevate Access" in the public docs to reflect the correct language in the product.
> Update Gain Access language to Elevate Access

- content/en/tracing/trace_collection/_index.md
fixed a small grammatical error.
> Update APM documentation to fix a grammatical error.

- config/_default/menus/menus.en.yaml
> fixing the menu

- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
- Remove a circular link
- Add a new description for the set of instructions
Pointed out by a translator.
> Remove circular link and clarify

- content/en/tracing/service_catalog/_index.md
Adds a new blog post for Tuesday Tasks.
> Adding a new blog post

- content/en/integrations/guide/reference-tables.md
Updating the link because the content was moved.
> Update further reading link

- content/en/security/misconfigurations/_index.md
- content/en/security/misconfigurations/frameworks_and_benchmarks.md
- content/en/security/misconfigurations/supported_frameworks.md
Updates the number of OOTB rules for CSM Misconfigurations.
> Update number of OOTB rules

- content/en/tracing/service_catalog/scorecards.md
> Adding clarification around rule evaluation

- content/en/continuous_integration/pipelines/_index.md
Fix GitHub Actions Terminology
> Fix GitHub Actions Terminology

- content/en/metrics/_index.md
This PR reorganizes our intro to metrics docs section by regrouping related docs in a more intuitive order and also leaves space for upcoming new public docs pages
> Updating the Metrics section of the Docs 

- content/en/opentelemetry/guide/ingestion_sampling_with_opentelemetry.md
- content/en/opentelemetry/otel_collector_datadog_exporter.md
- content/en/opentelemetry/otel_logs.md
This is a workaround to numbers in headings causing a DOM error, see DOCS-7009
> Fix DOM error causing tabs to break

- content/en/metrics/guide/_index.md
Reorganizing metric guides section by theme and to leave room for two new guides for the MWL category
> Updating metrics/guide

- content/en/account_management/saml/okta.md
Removing a sentence recommending users to use the pre-configured Datadog app. Raised by Kai on #documentation Slack.
> Sentence Nit

- content/en/intelligent_test_runner/_index.md
> Fix link to "how it works" section

- content/en/observability_pipelines/reference/processing_language/errors.md
- content/en/observability_pipelines/reference/processing_language/functions.md
Add VRL where DPL is referenced for consistency.
> Add VRL reference

- content/en/agent/logs/advanced_log_collection.md
Adds a link to main log collection doc based on user feedback in Hotjar.
[DOCS-6812](https://datadoghq.atlassian.net/browse/DOCS-6812)
[DOCS-6812]: https://datadoghq.atlassian.net/browse/DOCS-6812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6812] Add link to main log collection doc

- content/en/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/_index.md
Add a note about Browser Session Replay being disabled when mobile Web View Tracking is enabled.
Also remove some duplication from the bottom of the page.
> [rum] Add note about SR in web view tracking

- content/en/security/cloud_security_management/troubleshooting/_index.md
Removes an alias that is breaking the docs build.
> Remove unnecessary alias

- content/en/security/application_security/api-inventory/_index.md
I missed adding a link on this page to the in-app for this new feature.
> [ASM API Security] Updating in-app link that was missing

- content/en/tracing/trace_collection/library_config/dotnet-core.md
Make the namespace explicit in the description of DD_TRACE_METHODS to clear some confusion.
> Change the wording for DD_TRACE_METHODS (.net)

- config/_default/menus/menus.en.yaml
- content/en/security/cloud_security_management/troubleshooting/_index.md
- content/en/security/cloud_security_management/troubleshooting/threats.md
This PR simply re-works the landing page to be links to 2 distinct troubleshooting docs (moving contents of previous landing page into its own page (threats.md) )
> CSM Troubleshooting rework landing page

- content/en/getting_started/integrations/_index.md
[DOCS-6962](https://datadoghq.atlassian.net/browse/DOCS-6962)
[DOCS-6962]: https://datadoghq.atlassian.net/browse/DOCS-6962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6962] adding permissions section

- content/en/security/suppressions.md
Clarify suppression queries based on what happens in the UI. Currently, the docs say that you can click the button to migrate your suppression queries, but all the button does is jump to the Suppression Rules section.
> Clarify suppression queries

- content/en/tests/_index.md
> [CIVIS-8486] Add clarification for nested test.configuration tags

- content/en/real_user_monitoring/guide/monitor-electron-applications-using-browser-sdk.md
> Remove beta label from RUM electron page

- content/en/security/cloud_security_management/guide/writing_rego_rules.md
Removes beta note. Requested by PM.
> Remove beta note from Custom Rules article

- content/en/account_management/audit_trail/events.md
- layouts/shortcodes/audit-trail-security-platform.md
Reorders link list in doc. 
Also bumps the shorcode link list to start at 1001 to avoid conflicts with the main page.
> Reorder links for Audit Trail Events doc

- content/en/tracing/service_catalog/scorecards.md
> Small Page Title Nit

- content/en/tracing/service_catalog/adding_metadata.md
add sign-up form for schema v3.0
> add schema v3.0 private beta sign-up

- content/en/getting_started/integrations/aws.md
- content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
- content/es/getting_started/integrations/aws.md
- content/fr/getting_started/integrations/aws.md
- content/ja/getting_started/integrations/aws.md
- content/ko/getting_started/integrations/aws.md
Adds OAM permissions that are required for us to properly detect cross-account streams (https://datadoghq.atlassian.net/browse/AWSMC-176)
Also updating the permission list for the docs in Spanish, since every other language has been kept up to date.
> [aws-ints] Add OAM permissions for cross-account streams

- content/en/continuous_integration/pipelines/jenkins.md
Adds instructions for declaratively configuring Test Visibility in Jenkins using 'datadog' step.
> Document declarative configuration of Test Visibility in Jenkins using 'datadog' step

- go.mod
- go.sum
Updates to latest websites modules to deploy changes to partner nav items
https://datadoghq.atlassian.net/browse/WEB-4400
https://docs-staging.datadoghq.com/websites-modules/generated/280
> Latest websites modules with partner nav change

- content/en/api/latest/_index.md
- content/en/getting_started/api/_index.md
Add a note about using the Datadog authentication environment with the Datadog Postman collection
> (DOCS-6995) Add Postman auth note

- content/en/logs/error_tracking/_index.md
ET Logs is still in beta but we are planning to start billing soon. Until we are GA the pricing page will not be live. Thus, we want to give customers a warning that we will begin billing soon and an idea of the pricing plan
> Error Tracking Logs: Update beta callout

- content/en/agent/guide/use-community-integrations.md
Corrects the Agent installation command.
Noticed by a community member and verified by Heston.
> Use correct Agent command in Docker instructions

- content/en/integrations/guide/cluster-monitoring-vmware-tanzu.md
Updates the installation instructions for the VMware Tanzu Cluster Monitoring Tile.
> [PLINT-15] Update VMware Tanzu Cluster Monitoring Docs

- data/api/v1/full_spec.yaml
This PR refresh the billing hourly usage endpoint documentation with all new products/billing dimension that have been added since 2023.
> Refresh list of billing dimensions

- content/en/service_management/workflows/_index.md
- content/en/service_management/workflows/access.md
- content/en/service_management/workflows/actions_catalog/generic_actions.md
- content/en/service_management/workflows/actions_catalog/logic_actions.md
- content/en/service_management/workflows/actions_catalog/saved_actions.md
- content/en/service_management/workflows/build.md
- content/en/service_management/workflows/connections.md
- content/en/service_management/workflows/trigger.md
Fixes docs search for workflow automation
> Add search terms for workflow automation

- content/en/account_management/teams.md
Adds Notebooks to the table of products that use Teams. Adds link to the Notebooks page.
> Add that Teams is now supported on Notebooks

- content/en/tracing/trace_collection/custom_instrumentation/otel_instrumentation/java.md
This PR updates the custom instrumentation samples using Java Tracer and OpenTelemetry.
The feature is still in Beta and gets improved over time, meaning we need to update the samples too.
> Update OpenTelemetry custom instrumentation documentation

- content/en/dashboards/functions/rollup.md
- content/en/metrics/_index.md
Adding some links to calendar aligned query functionality
Letting customers pivot to learn about more advanced calendar aligned metric queries control from the intro doc
> Updating intro to metrics query for calendar aligned queries

- content/en/security/cloud_security_management/_index.md
- content/en/security/cloud_security_management/guide/public-accessibility-logic.md
- content/en/security/cloud_security_management/guide/resource_evaluation_filters.md
- content/en/security/cloud_security_management/guide/writing_rego_rules.md
- content/en/security/cloud_security_management/setup/_index.md
- content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md
- content/en/security/cloud_security_management/workflows.md
- content/en/security/identity_risks/_index.md
- content/en/security/misconfigurations/compliance_rules.md
- content/en/security/misconfigurations/custom_rules.md
- content/en/security/misconfigurations/findings.md
- content/en/security/misconfigurations/frameworks_and_benchmarks.md
- content/en/security/misconfigurations/signals_explorer.md
- content/en/security/misconfigurations/supported_frameworks.md
- content/en/security/threats/_index.md
- content/en/security/vulnerabilities/_index.md
DOCS-6945. Audit sweep of CSM docs for US1-Fed support. Also updates existing site region partials to ensure consistent verbiage across docs.
> DOCS-6945: Update supported sites for CSM

- content/en/developers/integrations/oauth_for_integrations.md
changing wording to reflect in app wording
changing wording to reflect in app wording
> Update wording oauth_for_integrations.md

- general.preview.synthetics.json
Removes the Integration tests. should no longer run in `Preview Synthetics/synthetic testing` github job
> rm integration tests

- content/en/metrics/custom_metrics/dogstatsd_metrics_submission.md
Changes all code examples on this page to run in infinite loops. more specifically
- updates Java examples to run in infinite loops
- updates C# examples, which already run infinitely, to look like the running infinitely is intentional
- updates Go examples to explicitly say `for true`
> DOCS-7080 - infinite loops in DogStatsD metrics submissions examples

- content/en/real_user_monitoring/browser/data_collected.md
> Clarify availability of status code in RUM

- content/en/security/suppressions.md
Remove the info because it's no longer in the UI.
> Update Suppressions doc

- content/en/getting_started/cloud_siem/_index.md
Adds info about the Cloud SIEM digest.
[DOCS-5313](https://datadoghq.atlassian.net/browse/DOCS-5313)
[DOCS-5313]: https://datadoghq.atlassian.net/browse/DOCS-5313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-5313] Add Cloud SIEM digest info

- content/en/security/cloud_security_management/setup/windows.md
moving from private to public beta
> move from private to public beta

- content/en/real_user_monitoring/browser/_index.md
> Add missing initialization parameter

- content/en/glossary/terms/flaky_test.md
- content/en/glossary/terms/test_regression.md
- content/en/glossary/terms/test_service.md
- content/en/glossary/terms/test_suite.md
- content/en/glossary/terms/wall_time.md
Update the anchor links in several terms for Test Visibility in the Glossary.
> Test Visibility Glossary Terms Update

- content/en/dynamic_instrumentation/_index.md
The name of the permission was wrong. This PR uses the correct name instead.
> Fix DI capture variables permission name

- content/en/serverless/azure_app_services/azure_app_services_container.md
- content/en/serverless/azure_app_services/azure_app_services_linux.md
- content/en/serverless/azure_app_services/azure_app_services_windows.md
- layouts/shortcodes/aas-workflow-linux.md
- layouts/shortcodes/aas-workflow-windows.md
- static/resources/yaml/serverless/aas-workflow-linux.yaml
- static/resources/yaml/serverless/aas-workflow-windows.yaml
Adds two shortcode snippets to explain zero downtime deployments.
for docs reviewer: this is all approved by serverless team!
> DOCS-6956 AAS zero downtime workflows

- content/en/database_monitoring/guide/managed_authentication.md
Clarifies set up instructions around creating the IAM role & giving it the proper permissions in the database
> Improve documentation for IAM managed auth for postgres

- content/en/logs/log_collection/javascript.md
- content/en/real_user_monitoring/browser/_index.md
> Add link to CSP documentation on relevant pages

- content/en/api/latest/_index.md
Add info about setting up the Datadog Authentication environment in Postman
> (DOCS-7073) Add Postman auth info

- content/en/database_monitoring/setup_oracle/autonomous_database.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Adding grants for Oracle lock monitoring.
> Oracle lock grants (DBMON-3279)

- content/en/profiler/profiler_troubleshooting/php.md
We had a customer reaching out to us that they would like to enable the profiler but they are concerned about a possible overhead and would like to activate the profiler in a minimal configuration/overhead mode. Then I saw that the troubleshooting page for PHP is slim, so I added some stuff.
> Add PHP troubleshooting

- static/resources/xml/Datadog-Snow_Update_Set_v2.4.2.xml
> Add new update set 2.4.2

- content/en/security/cloud_siem/investigate_security_signals.md
Adds a link to the main threat intelligence doc.
> Add link to threat intelligence doc

- content/en/logs/log_collection/ios.md
> Add note about associating logs with RUM views

- content/en/security/_index.md
> Add Writing Blog Link

- content/en/containers/kubernetes/prometheus.md
Adds note to warn customers to use the advanced configuration lest they incur a billing situation
> DOCS-6895 - add note on Kubernetes Prometheus and OpenMetrics re billing/config

- content/en/opentelemetry/guide/semantic_mapping.md
Moves update to fork from @ringerc https://github.com/DataDog/documentation/pull/20967/files  into a branched PR
> Add missing attributes to otel semantic conventions mapping docs [on branch]

- content/en/security/cloud_siem/investigator.md
Remove note because all three major cloud providers are supported now.
> Update investigator doc

- content/en/metrics/summary.md
Fixing https://github.com/DataDog/documentation/pull/20905/files#diff-39c24777aecb950ee52c3d1023a9f32bf2121aa21a7c15229bd2e1f1a96f41a2R146
> Fix oxford comma and curly brackets in image 

- content/en/agent/configuration/secrets-management.md
I don't think there's supposed to be a backslash (`\`) here.
> Remove stray slash

- content/en/agent/remote_config/_index.md
Small link update that was nested in a tab.
> Remote Configuration Link Fix

- content/en/real_user_monitoring/mobile_and_tv_monitoring/integrated_libraries/_index.md
Add instructions for the React Native Apollo Client integration.
> Add React Native Apollo Client integration

- content/en/real_user_monitoring/retention_analysis/_index.md
updated the link to be the new one for retention analysis for [1]
> new link.md

- content/en/static_analysis/rules/_index.md
> [STAL] Update rulesets descriptions in frontmatter

- content/en/data_security/logs.md
> Change PCI HTTP to HTTPS

- content/en/infrastructure/process/_index.md
- Updating the LP doc to mention this featureset is available in Enterprise plan.
- Will be linked from the new (currently developed) AWS Fargate x Live Processes blog so helpful to maintain that association.
> [Live Processes] Add a blurb about Enterprise plan

- content/en/database_monitoring/setup_oracle/autonomous_database.md
- content/en/database_monitoring/setup_oracle/rds.md
- content/en/database_monitoring/setup_oracle/selfhosted.md
Add grants for the new `oracle.tablespace.maxsize` metric
> Add grants for oracle.tablespace.maxsize metric (DBMON-3217)

- config/_default/menus/menus.en.yaml
- content/en/service_management/case_management/_index.md
- content/en/service_management/case_management/create_case.md
- content/en/service_management/case_management/projects.md
- content/en/service_management/case_management/settings.md
- content/en/service_management/case_management/troubleshooting.md
- content/en/service_management/case_management/view_and_manage/_index.md
- Case management new features
- General Overhaul of content and information organization
- [DOCS-6850](https://datadoghq.atlassian.net/browse/DOCS-6850)
Do not merge
[DOCS-6850]: https://datadoghq.atlassian.net/browse/DOCS-6850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Case Management documentation overhaul

- content/en/dashboards/widgets/list.md
Adds Watchdog as a source for the List widget as it was recently added
> add Watchdog as source for the List Widget

- layouts/shortcodes/latest-lambda-layer-version.html
Bump datadog-lambda-java to version 13
> Bump datadog-lambda-java to version 13

- content/en/service_management/mobile/_index.md
Datadog mobile app is now available for US-FED, per [DOCS-7101](https://datadoghq.atlassian.net/browse/DOCS-7101) , so removing the Gov banner.
[DOCS-7101]: https://datadoghq.atlassian.net/browse/DOCS-7101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7101] Update Datadog mobile app - remove Gov banner

- content/en/account_management/billing/aws.md
Adds examples for AWS resource exclusion.
> DOCS-7119 - adding examples for resource exclusion

- content/en/account_management/_index.md
adds a fed section, as daily/weekly digests are not supported in fed
> DOCS-7111 adding fed section

- content/en/synthetics/apm/_index.md
> Quota note for synthetics apm docs

- content/en/cloud_cost_management/aws.md
- adding new metrics
- improving metric descriptions + providing advice
- adding tag sources
> [CCM] add AWS metric and tag source documentation

- content/en/serverless/aws_lambda/installation/dotnet.md
- content/en/serverless/aws_lambda/installation/java.md
On the Java and .NET pages for AWS Lambda installation, a new tab for AWS SAM.
> DOCS-7094 - adding SAM instructions for Java and .NET

- assets/scripts/build-api-pages.js
- layouts/partials/api/code-example.html
- layouts/partials/api/curl.html
- layouts/partials/api/request-body.html
https://datadoghq.atlassian.net/browse/WEB-4501
There isn't anything different to QA right now as none of the endpoints are using multipart/form
> WEB-4501 - multipart support in api

- content/en/security/application_security/threats/inapp_waf_rules.md
Just released new navigation menu under ASM - Protection - In-app WAF, updating this doc to reflect this change.
> [ASM] Update inapp_waf_rules.md

- content/en/serverless/aws_lambda/installation/nodejs.md
- content/en/serverless/aws_lambda/installation/python.md
Adds more explicit context for using Terraform with Python and Node.js.
> DOCS-6619 - Update Lambda Terraform docs

- config/_default/menus/menus.en.yaml
Please ensure that this update doesn't actually make any changes to how the menu is rendered.
> menu friend - standardizing

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump dd-trace-dotnet layer to version 15

- content/en/database_monitoring/setup_oracle/_index.md
Adding the blog link to this page
> updating blog link

- content/en/service_management/app_builder/_index.md
- content/en/service_management/app_builder/build.md
> Add link to AI opt-in alert

- content/en/continuous_integration/pipelines/custom_tags_and_metrics.md
- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
Config to specify languages and library versions in single step instrumentation is being added to Host and Docker.
> [DOCS-7133] Add specifying library config for Host and Docker.

- content/en/data_jobs/kubernetes.md
> Fix DJM K8s Spark Submit Typo

- content/en/real_user_monitoring/guide/_index.md
- content/en/real_user_monitoring/guide/proxy-mobile-rum-data.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md
Adds documentation guide on how to setup a proxy for mobile SDKs
> Adds guide for setting up mobile SDKs proxy

- Makefile
> Bump assetlib version

- content/en/continuous_integration/guides/pipeline_data_model.md
Minor update in CI Visibility docs. The behaviour of our product has changed since the last time.
> [CIVIS-8950] Minor update of CI Visibility docs

- content/en/developers/integrations/python.md
- Update python.md to mention Python 3.11 and not 3.9. 
- We bumped the Python version to 3.11 https://github.com/DataDog/integrations-core/pull/15997
Noticed working on https://github.com/DataDog/integrations-core/pull/16720
> Update python.md to mention Python 3.11 and not 3.9

- content/en/service_management/workflows/build.md
> (DOCS-7038) Expand on tags,services,teams

- content/en/security/misconfigurations/supported_frameworks.md
Updates the supported PCI framework for CSM Misconfigurations to 4.0. Requested by PM.
> Update PCI framework support for CSM Misconfigurations

- content/en/logs/log_collection/csharp.md
SE/Customer request
[DOCS-6888](https://datadoghq.atlassian.net/browse/DOCS-6888)
[DOCS-6888]: https://datadoghq.atlassian.net/browse/DOCS-6888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-6888] Update C# Log collection doc for NLog

- content/en/continuous_delivery/deployments/argocd.md
Clarifying docs by specifying the type of application to modify in one step.
> Mark that applications are from Argo CD

- content/en/synthetics/guide/create-api-test-with-the-api.md
Add information about creating local variables with builtins
> (DOCS-7145) Add local variables note and links

- content/en/tests/setup/dotnet.md
This PR fixes the CI Visibility compatibility table for .NET by:
- Adding missing 5 and 8 major versions
- Changing `Language` with `Framework`
> [CI Visibility] - Fix CI Visibility .NET compatibility table

- content/en/service_catalog/setup.md
> update catalog entries management section

- content/en/integrations/guide/source-code-integration.md
> Profiling source code preview now works for all granularities

- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_postgres/aurora.md
> Postgres Aurora 15 support

- content/en/dashboards/guide/quick-graphs.md
- Remove the beta callout, this feature is in GA
- [DOCS-7088](https://datadoghq.atlassian.net/browse/DOCS-7088)
[DOCS-7088]: https://datadoghq.atlassian.net/browse/DOCS-7088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove beta callout

- content/en/security/cloud_security_management/troubleshooting/_index.md
Updates the link text on the CSM Troubleshooting page.
> Update link text on CSM Troubleshooting page

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-js layer to version 105

- content/en/dashboards/guide/context-links.md
- Add example use case for multiple variables in context links
- [DOCS-7008](https://datadoghq.atlassian.net/browse/DOCS-7008)
[DOCS-7008]: https://datadoghq.atlassian.net/browse/DOCS-7008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add example for multiple variable usage

- layouts/shortcodes/integrations.html
https://datadoghq.atlassian.net/browse/WEB-4529
Updates some of the referencing of integrations on Ja so that it will load images correctly as it does on En
https://docs-staging.datadoghq.com/david.jones/jaint/ja/integrations/
> WEB-4529 - update logo display for ja integrations

- assets/styles/components/_grouped-item-listings.scss
- layouts/security_rules/single.html
- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config_preview.yaml
adds `View Rule In Datadog` button and a view signals button that directs users to the product. 
- view signals button can read as:
- `View Signals`  for Cloud SIEM, Application Security and CSM Threat rules
- `View Identity Risks` for CSM Identity Risks rules
- `View Misconfigurations` for CSM Misconfiguration rules
realigns  the`.rule-specification` section's elements to include the new buttons
jira: https://datadoghq.atlassian.net/browse/WEB-4345
preview: https://docs-staging.datadoghq.com/stefon.simmons/sec-ootb-deeplinks/security/default_rules/
- Filter for rules by category. Ensure the deeplink buttons on the rule pg display the correct text according to the rule category,  and direct you to **Datadog**.
rule pg preview examples:
- …
> security ootb deeplinks - [WEB-4345]

- content/en/observability_pipelines/setup/_index.md
Add link to End User License Agreement to OP setup doc.
[DOCS-7170](https://datadoghq.atlassian.net/browse/DOCS-7170)
[DOCS-7170]: https://datadoghq.atlassian.net/browse/DOCS-7170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7170] Add link to End User License Agreement

- content/en/logs/_index.md
- content/en/sensitive_data_scanner/_index.md
Add links to PCI Compliance doc.
> Add links to PCI Compliance doc

- content/en/cloud_cost_management/custom.md
> Replace markdown tables with html tables and inline styles

- content/en/agent/faq/log-collection-with-docker-socket.md
- content/en/containers/kubernetes/log.md
Mostly reorganizes and improves some old content.
> DOCS-5755/7083 - K8s log collection refresh

- content/en/cloud_cost_management/_index.md
Add Custom Costs + SaaS Cost Integrations sections in the Setup partial for CCM. Chat with Natasha on Slack.
> Cloud Cost Management Index Page Update

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md
- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/ios.md
> Add note about billing for client side tracing (iOS and Android)

- content/en/serverless/aws_lambda/installation/go.md
The code snippet was missing some imports. Making sure that the example can by copy pasted easily for customers is great
> Update serverless Go example code snippet

- content/en/service_catalog/adding_metadata.md
> Adding v3 metadata info

- content/en/agent/logs/advanced_log_collection.md
Add a note and small edits.
[DOCS-7982](https://datadoghq.atlassian.net/browse/DOCS-7082)
> [DOCS-7982] Add note and small edits

- local/bin/py/build/actions/security_rules.py
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
- Remove old glob rules that aren't needed
- Exclude deprecated dir on cloud-siem
This page should exist and not redirect
https://docs-staging.datadoghq.com/david.jones/skip-deprecated/security/default_rules/okta-mfa-push-fatigue/
Also check rules looks normal 
https://docs-staging.datadoghq.com/david.jones/skip-deprecated/security/default_rules/
> Update security monitoring glob rules

- content/en/database_monitoring/setup_mysql/azure.md
- content/en/database_monitoring/setup_mysql/troubleshooting.md
> Add note about Flexible Server support

- content/en/security/suppressions.md
Adds a note about suppression queries.
[DOCS-7177](https://datadoghq.atlassian.net/browse/DOCS-7177)
[DOCS-7177]: https://datadoghq.atlassian.net/browse/DOCS-7177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7177] Add note about suppression queries

- content/en/database_monitoring/guide/_index.md
- content/en/database_monitoring/guide/pg15_upgrade.md
- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_postgres/aurora.md
- content/en/database_monitoring/setup_postgres/rds.md
- content/en/database_monitoring/setup_postgres/selfhosted.md
> Adding Postgres 16 support (DBMON-3519)

- content/en/infrastructure/process/_index.md
reflects hotjar feedback; removes a misleading link, deprioritizes DaemonSet-related info, adds an Operator tab.
> DOCS-7153 - fixing up infra process page

- content/en/account_management/audit_trail/_index.md
Add info
[DOCS-7216](https://datadoghq.atlassian.net/browse/DOCS-7216)
[DOCS-7216]: https://datadoghq.atlassian.net/browse/DOCS-7216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7216] Add info on API key auditing

- content/en/glossary/terms/impossible_travel.md
- content/en/glossary/terms/investigator.md
- content/en/glossary/terms/notification_rules.md
- content/en/glossary/terms/pipeline.md
- content/en/glossary/terms/remote_configuration.md
- content/en/glossary/terms/security_signal.md
- content/en/glossary/terms/signal_correlation.md
Add  a couple of glossary terms.
[DOCS-7121](https://datadoghq.atlassian.net/browse/DOCS-7121)
[DOCS-7121]: https://datadoghq.atlassian.net/browse/DOCS-7121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7121] Add glossary terms

- content/en/synthetics/private_locations/_index.md
Adds a note to ensure that the latest image is pulled when using Docker for PL and upgrading
Hakuna Matata
> Add small note to upgrading PL regarding `latest` docker tag

- content/en/account_management/billing/usage_metrics.md
> Add error tracking estimated usage metric

- content/en/containers/amazon_ecs/_index.md
Bump latest FIPS Proxy version in the ECS documenation
> Update FIPS proxy version to 1.1.1

- content/en/monitors/configuration/_index.md
- Add a reference link from main docs to the guide.
> Add link to aggregator guide

- content/en/service_catalog/guides/best-practices.md
adding a couple more links for easier nvigation
> Update service catalog best-practice

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 88

- content/en/agent/basic_agent_usage/ubuntu.md
Move the installation instructions to their own line + remove passive voice
> (DOCS-7085) Pull out installation instructions

- content/en/serverless/step_functions/troubleshooting.md
Adding the  Forwarder upgrade troubleshooting details for Step Functions Tracing based on what we have learned from customers so far.
> Add Forwarder upgrade troubleshooting details for Step Functions Tracing

- content/en/coscreen/troubleshooting.md
Adds a paragraph about CoScreen and Windows admin mode.
> DOCS-7211 - adding a note on coscreen

- content/en/tracing/services/services_map.md
add clarification to prevent future customer confusion based on escalation
> clarify service map behavior services_map.md

- content/en/security/cloud_security_management/setup/_index.md
- content/en/security/cloud_security_management/setup/csm_cloud_workload_security/agent/windows.md
Moves alias for the CSM Windows instructions. Requested by PM.
> Move CSM Windows alias

- content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
Added note that only Otel 0.7 is supported. 
Motivation: incident-24986
> add otel 0.7 clarification to doc

- content/en/data_streams/_index.md
Remove 'Kinesis' from the Python runtime row for now - cleaning up the official languages/queueing technologies we support
> update DSM public docs

- content/en/real_user_monitoring/browser/monitoring_page_performance.md
> Clarify metric unit

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
- informs customers on how to build an app which uses our native modules
- also instructs how to alleviate a common graphql issue
- N/A
> add Node.js esbuild native module instructions

- content/en/security/cloud_security_management/_index.md
https://datadoghq.atlassian.net/browse/WEB-4509
https://docs-staging.datadoghq.com/brian.deutsch/search-result-headings/search/?s=CSM%20Setup
Pages coming up under `Cloud Security Management` fall have a title heading in the results like `Documentation >> Cloud Security Management >> ...`
> [WEB-4509] updates subcategory for cloud security management results

- content/en/containers/faq/_index.md
- content/en/containers/faq/package-server-manager-openshift.md
Adds a requested FAQ page about an OpenShift error.
> DOCS-7208 adding openshift scc faq

- content/en/mobile_app_testing/mobile_app_tests/steps.md
- content/en/service_management/workflows/trigger.md
> Fix typos in image alt text

- content/en/profiler/enabling/php.md
This PR will add latest features (PHP Fibers and Timeline) as well as switch from setting environment variables to use the `datadog-setup.php` script to setup and configure the profiler.
> Update Enabling PHP with latest features and `datadog-setup.php`

- content/en/universal_service_monitoring/setup.md
Adds documentation for enabling istio monitoring
> usm: Add istio monitoring documentation

- content/en/security/cloud_security_management/setup/csm_enterprise/agent/windows.md
we have a new version of the beta, so this just updates the link to point to the newest build
> update beta agent installer link

- content/en/security/cloud_security_management/setup/csm_cloud_workload_security/agent/windows.md
Updates Agent installer link for Windows setup instructions for CSM Workload Security.
> Update Agent installer link

- content/en/getting_started/opentelemetry/_index.md
> Fix anchor in OTel Getting Started

- content/en/synthetics/private_locations/configuration.md
> [SYN] Add PAC file support

- content/en/profiler/enabling/dotnet.md
Adding a note on the correct LD_PRELOAD when setting APM with SSI
> Note LD_PRELOAD for linux with SSI

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-extension layer to version 55

- content/en/developers/community/libraries.md
Looks like this integration no longer exists. Probably replaced by the official integration.
> (maint) Remove dead link

- content/en/dashboards/change_overlays/_index.md
> Add blog link to Change Overlay

- content/en/developers/authorization/oauth2_in_datadog.md
Editing the OAuth docs with a typo to the URL that uses the site parameter
> Quick update to site param URL

- go.mod
- go.sum
> Modules bump

- go.mod
- go.sum
Reverts DataDog/documentation#21755
> Revert "Modules bump"

- content/en/developers/community/libraries.md
> Update link for K6 metrics configuration

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/java.md
Adds some information recommending users test Release Candidate versions
> add RC note to setup doc

- general.preview.synthetics.json
- Updates the synthetics to hit the new endpoint for static analysis rules
https://dd-corpsite.datadoghq.com/synthetics/tests?query=static%20analysis&from_ts=1707758214326&to_ts=1707761814326&live=true
> Update synthetics for static analysis

- content/en/security/application_security/software_composition_analysis/_index.md
I had an incorrect link for Code Analysis
> Fixing code analysis link

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
This updates the example version of the .NET Tracer for single step APM. The listed version has known issues and should be upgraded.
N/A
> APM > Single Step > Update dotnet version in example

- content/ja/tracing/trace_collection/compatibility/nodejs.md
This pull request adds a Japanese translation of the support note for Next.js, which exists in the English version.
English version
https://github.com/DataDog/documentation/blob/92567592ed69bc5c23d666ee193506ce513536a1/content/en/tracing/trace_collection/compatibility/nodejs.md?plain=1#L85
> Update nodejs.md / update Next.js note

- content/en/containers/kubernetes/apm.md
> Fix default Socket name of APM

- content/en/service_catalog/investigating.md
add sectional structure and updated some details
> Update investigating-a-service .md

- content/en/database_monitoring/guide/managed_authentication.md
This PR updates the `managed authentication` example for Postgres on Azure and AWS
>  [DBMON-3147] update postgres managed authentication for aws and azure

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/python.md
Conflicting information on documentation
- To ensure consistency in documentation for Python Tracer Library compatibility with Python Version.
- [ X ] Please merge after reviewing
Please read slack thread here on #support-apm (https://dd.slack.com/archives/C4WC8C39Q/p1707993361403619)
> Documentation update on Python Tracer Compatibility

- content/en/developers/authorization/oauth2_endpoints.md
fixing incorrect endpoint url in oauth docs
> Fixing endpoint URL 

- config/_default/menus/menus.en.yaml
Adds some missing nav items back
https://docs-staging.datadoghq.com/david.jones/op-refnav/observability_pipelines/reference/sources/
> op ref left nav

- content/en/getting_started/support/_index.md
> Remove button from holiday support note

- content/en/integrations/guide/reference-tables.md
- content/en/logs/explorer/advanced_search.md
Adds beta note for filter with subqueries.
Remove beta for filtering with Ref Tables.
> Add beta for subqueries and remove beta for filter with ref tables

- content/en/tracing/troubleshooting/dotnet_diagnostic_tool.md
Fix some typos and rewrite some sentences to be clearer.
Original page: https://docs.datadoghq.com/tracing/troubleshooting/dotnet_diagnostic_tool/
> [APM] Update `dotnet_diagnostic_tool.md`

- content/en/getting_started/devsecops/_index.md
Changes Application Vulnerability Management to Software Composition Analysis in the DevSecOps getting started guide.
> Change AVM to SCA

- content/en/service_catalog/investigating.md
switching tab orders in docs to match in-app display
> update tab info on SC side panel

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
> Clarify note for Kubernetes single step instrumentation

- .gitignore
File is showing up after running the build
> (maint) Add single-sourced file to gitignore

- content/en/dora_metrics/_index.md
Update DORA Metrics beta access form callout. We have enough customers in the beta and will convert private beta access form to a waitlist. 
- [  ] Please merge after reviewing
> Update DORA Metrics beta access form callout 

- content/en/service_catalog/setup.md
> Update service entry management in SC

- content/en/data_security/logs.md
Remove the security rule restrictions from HIPAA, no longer relevant and also update the sharing function
> Update HIPAA restrictions

- layouts/shortcodes/latest-lambda-layer-version.html
I released this last week but forgot this PR
> feat: Bump datadog-lambda-js to 106

- content/en/tracing/trace_collection/library_config/php.md
New INIs for the newest tracer version.
> Add new PHP log INIs

- content/en/security/application_security/enabling/compatibility/php.md
This PR adds RoadRunner to the list of compatible frameworks with PHP ASM.
> [ASM-PHP] Add roadrunner compatibility

- content/en/containers/guide/ad_identifiers.md
> DOCS-7282 - Fix Docker label syntax

- content/en/network_monitoring/devices/_index.md
Add a link to the main Network Devices page in Datadog
> Add link to Network Devices page in-app

- content/en/service_management/incident_management/incident_settings.md
> Add new incidents slack features

- content/en/security/cloud_siem/log_detection_rules.md
Add suppression rule section to Log Detection doc.
[DOCS-7150](https://datadoghq.atlassian.net/browse/DOCS-7150)
[DOCS-7150]: https://datadoghq.atlassian.net/browse/DOCS-7150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7150] Add suppression rule section to Log Detection

- content/en/agent/guide/use-community-integrations.md
Updates the Using Community Integrations guide to be a bit more explicit about what you have to do in a containerized env.
> being more explicit for containerized envs in the Community Integrations guide

- content/en/logs/log_configuration/archives.md
Adds a note for log archives. PM request.
[DOCS-7300](https://datadoghq.atlassian.net/browse/DOCS-7300)
[DOCS-7300]: https://datadoghq.atlassian.net/browse/DOCS-7300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7300] Add note for log archives

- content/en/tracing/trace_collection/compatibility/java.md
Add hazelcast to beta supported java frameworks
> Add hazelcast to beta supported java frameworks

- snippets/markdown.json
> Add whatsnext snippet

- content/en/agent/configuration/proxy.md
updating logs config parameter use_http to force_use_http to match the parameter syntax in main
> Update proxy.md - replacing logs config option use_http with force_use_http

- content/en/account_management/multi_organization.md
- content/en/account_management/org_settings/cross_org_visibility.md
- content/en/account_management/org_settings/cross_org_visibility_api.md
DOCS-7185
- Split cross-org visibility docs: move the API docs onto their own page.
- Add UI instructions to the main cross-org page
- On the multi-org page, reorganize introduction and add links to the cross-org visibility page.
> Document cross-org visibility UI

- layouts/partials/rum/rum-error-tracking-mobile.html
> (maint) Fix link issue in Rum mobile

- content/en/service_catalog/adding_metadata.md
shuffling page layout since many customers find it hard to locate v3 information
> Updating service catalog schema v3 info in docs

- content/en/account_management/billing/aws.md
Clarify where to apply a configuration
> (DOCS-6205) Clarify phrasing

- content/en/account_management/teams.md
https://datadoghq.atlassian.net/browse/DOCS-7247
Based on Hotjar feedback. Got the list of allowed characters from Ali Mahmoud in Slack. Source of truth is web-ui: https://github.com/DataDog/web-ui/blob/7ea07bc2d9828ec3f495650ae7e1b71e9643b749/packages/apps/teams/lib/shared/validate-team-handle.ts
> Document allowed characters for team handle and team name

- content/en/dora_metrics/_index.md
We've done some changes to the endpoint for incidents and the API docs were already updated but there is a manually written example here that was still pending.
> [CIVIS][DORA] Update doc examples about DORA Metrics incidents API

- content/en/service_catalog/adding_metadata.md
get rid of repetitive title and small style change
> service catalog schema v3 - minor style adjustment

- content/en/tracing/guide/tutorial-enable-java-aws-ecs-fargate.md
Link to AWS Developer docs for user profiles has changes. Updating link.
> [DOCS-7273] fixing link in Tracer - Java - ECS Fargate

- content/en/infrastructure/process/_index.md
- content/en/watchdog/_index.md
> Add blog post link for Watchdog Insights and Live Processes

- content/en/service_management/incident_management/_index.md
Adds documentation for statuspage integration with Incident App.
Documentation from statuspage integration:
https://github.com/DataDog/dogweb/pull/112795
> [statuspage] - documentation for incident app

- content/en/database_monitoring/database_hosts.md
> Add blocking queries to supported Oracle features

- config/_default/menus/menus.en.yaml
- content/en/security/misconfigurations/compliance_rules.md
- content/en/security/misconfigurations/custom_rules.md
- content/en/security/misconfigurations/findings/_index.md
Renames several CSM articles.
Preview: https://docs-staging.datadoghq.com/deforest/csm-rename-articles/security/misconfigurations/
> Rename CSM articles

- translate.yaml
> (maint) Update path for workflows translation exclusion

- content/en/security/application_security/code_security/_index.md
- content/en/security/application_security/threats/library_configuration.md
- content/en/security/application_security/troubleshooting.md
This PR consolidates the "how to disable ASM, SCA and Code Security" instructions on the ASM troubleshooting page.
> [DOCS-7305] updating ASM troubleshooting

- content/en/integrations/guide/reference-tables.md
- content/en/logs/explorer/advanced_search.md
Update limits on referent tables. PM request.
> Update reference table limits

- content/en/cloudcraft/_index.md
Small update to Cloudcraft landing page that we missed in the initial transfer - re-sizing image and adding a further reading link.
> [DOCS-7325] updating Cloudcraft landing page

- content/en/agent/configuration/agent-fips-proxy.md
> Add note to FIPS Proxy setup page

- content/en/tracing/guide/inferred-service-opt-in.md
Details in https://github.com/DataDog/datadog-agent/pull/23284
AIT-9878
> Deprecate peer_service_aggregation

- content/en/tracing/trace_collection/library_injection_local.md
Remove note from library injection page as it's causing confusion.
> Remove note from library injection page

- content/en/infrastructure/process/_index.md
The steps to enable process collection in the live process docs has not been updated to reflect the changes from this PR: https://github.com/DataDog/datadog-agent/pull/10555#issuecomment-1136396057
We are updating `DD_PROCESS_AGENT_ENABLED` to `DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED` for Docker and Kubernetes installation steps.
> [PROCAPPS-683] Update process collection enablement steps 

- content/en/real_user_monitoring/guide/proxy-rum-data.md
Mentions the replay endpoint in addition to general rum in the RUM proxy guide
> Mention replay endpoint in RUM proxy guide

- content/en/opentelemetry/collector_exporter/otlp_receiver.md
- content/en/opentelemetry/guide/otlp_delta_temporality.md
> Remove redundant redirects

- content/en/database_monitoring/connect_dbm_and_apm.md
Changed term from "jdbc-datastore" to "jdbc-datasource".
Fixed typo that caused confusion.
> Update connect_dbm_and_apm.md - correct term to be "jdbc-datasource"

- content/en/containers/kubernetes/configuration.md
This change provides clear instructions on where to sent environment variables when using the Datadog operator and helm chart.
> Update helm and operator env var configuration

- content/en/dora_metrics/_index.md
Explains how to query DORA Metrics and events outside of the provided page.
> [CIVIS] Update DORA Metrics docs about querying

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md
Add caveat for setting `CORECLR_PROFILER_PATH` with Alpine Linux.
> Add note for Alpine Linux to Configuring process environment variables

- content/en/api/_index.md
- content/en/continuous_integration/search/_index.md
- local/bin/py/build/configurations/pull_config_preview.yaml
Please double-check that the redirects work in preview before merging 🙇
> Add redirects

- content/en/tracing/guide/inferred-service-opt-in.md
> Update inferred-service-opt-in.md minor fix

- content/en/tracing/services/service_page.md
Update Latency by Status to Latency by Error (this is what is shown to users)
To learn about the documentation update process by fixing a small error on a page that covers my product scope
- [ X] Please merge after reviewing
> Small correction on service_page.md

- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_postgres/azure.md
> Postgres 15 on Azure support

- content/en/database_monitoring/setup_mysql/_index.md
- content/en/database_monitoring/setup_postgres/_index.md
- content/en/database_monitoring/setup_sql_server/_index.md
This PR updates the DBM agent overhead significant figures.
> update dbm agent integraiton overhead significant figures

- content/en/database_monitoring/setup_postgres/azure.md
> Add support for Postgres 16 on Azure (DBMON-3522)

- content/en/continuous_integration/pipelines/_index.md
- content/en/tests/_index.md
The [Test Visibility](https://docs.datadoghq.com/tests/#supported-features) and [Pipeline Visibility](https://docs.datadoghq.com/continuous_integration/pipelines/?tab=githubactions#supported-features) landing pages have a Supported Features matrix with terminology (bolded in purple) that is ranking second in the Docs Site search results.
Raised in [#support-ci-visibility](https://dd.slack.com/archives/C0279FZSTNH/p1709598767330109) on Slack.
> Add Supported Features to Algolia Tags for Test and Pipeline Visibility Doc Pages

- content/en/service_catalog/adding_metadata.md
update to newest version v3 examples
> service catalog v3 schema update

- content/en/containers/guide/_index.md
- content/en/containers/guide/changing_container_registry.md
- content/en/containers/guide/sync_container_images.md
- layouts/shortcodes/container-images-table.md
This new documentation shows how customer can synchronize and use Datadog container images with their own repository.
> feat(containers): add sync_container_images guide

- config/_default/menus/menus.en.yaml
> Clarify Service Catalog Menu Item

- .gitlab-ci.yml
Bumps the image to our latest version
Nothing here to review besides a successful pipeline run, this change to for posterity since this is a shared image and will have no effect on documentation jobs and there are no breaking changes 
Pipeline run: https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines/29528186
> Bump image to latest version

- content/en/getting_started/application_security/_index.md
Updating broken link and in-app nav instructions and screenshot as this has changed since the re-naming of AVM to SCA and general onboarding flow.
> [DOCS-7380] Update Getting started with ASM link to in-app

- content/en/database_monitoring/setup_sql_server/_index.md
- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/gcsql.md
- content/en/database_monitoring/setup_sql_server/troubleshooting.md
This PR updates sql server 2012 support with known limitations.
> update sql server 2012 support with known limitations

- content/en/database_monitoring/connect_dbm_and_apm.md
https://github.com/DataDog/dd-trace-js/pull/4140
https://github.com/DataDog/dd-trace-js/issues/4139
this is an issue for customer since a few versions ago, and the doc is causing confusion and errors.
> `none` mode should be `disabled` mode

- content/en/agent/guide/integration-management.md
- content/en/agent/troubleshooting/integrations.md
Add a clarifying note that partner/community integrations need to be re-installed after the agent has been upgraded
> Update integration-management with note about partner ints

- content/en/database_monitoring/setup_postgres/_index.md
Updating the compatibility matrix for Postgres 16 on Azure support.
> Compatibility matrix update - Postgres 16 on Azure

- content/en/database_monitoring/guide/tag_database_statements.md
> Add example for multiple tags

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump dd-trace-java layer version to 14

- config/_default/menus/menus.en.yaml
- content/en/monitors/downtimes/_index.md
- content/en/monitors/downtimes/examples.md
- content/en/monitors/guide/_index.md
- Add child page to the left navigation
- Remove anchor links that are no longer applicable
- Remove guide from index
- Add algolia tags
> Esther documentation edits to PR

- content/en/security/threat_intelligence.md
We recently updated the mapping of our threat intelligence feeds to different categories. This PR reflect those changes in the documentation
> SECRES-1770 - Update the documentation for Threat Intel category following recent feed updates

- config/_default/menus/menus.en.yaml
Adding new [Test Visibility & ITR icon](https://www.datadoghq.com/pricing/?product=test-visibility--intelligent-test-runner#products) from `websites-modules` to the Docs Site nav.
> Use Test Visibility & Intelligent Test Runner Icon in the Left Hand Navigation

- content/en/code_analysis/static_analysis_rules/_index.md
Adds `Go` ruleset frontmatter.
> Update Static Analysis frontmatter

- content/en/synthetics/settings/_index.md
- Reorders Default settings for Synthetic Test settings to match how it appears in the UI
- Adds info about Enforced tags for Synthetic Test settings
Needs a review from the synthetics team.
> Enforced tags settings for synthetic tests

- layouts/shortcodes/latest-lambda-layer-version.html
Bumping this because I just ran the release to all regions + govcloud.
> Bump datadog-lambda-js layer to version 107

- content/en/glossary/terms/instrumentation.md
- content/en/glossary/terms/span_summary.md
- content/en/tracing/glossary/_index.md
> APM Glossary Fixes

- content/en/developers/ide_integrations/idea/_index.md
- content/en/developers/ide_integrations/visual_studio/_index.md
- content/en/developers/ide_integrations/vscode/_index.md
Adds further reading links for Tuesday Tasks.
> Add further reading links

- content/en/infrastructure/process/_index.md
Fix a typo in the introduction of the Processes documentation
> Fix typo in Processes documentation

- config/_default/menus/menus.en.yaml
- content/en/metrics/open_telemetry/otlp_metric_types.md
- content/en/opentelemetry/schema_semantics/host_metadata.md
- content/en/opentelemetry/schema_semantics/hostname.md
Documents schema semantics for mapping OpenTelemetry semantic conventions to hostnames.
> [OTEL-1156][opentelemetry] Add guide on hostname resolution

- content/en/opentelemetry/schema_semantics/_index.md
> Add Hostname Mapping Page to Schema and Semantics

- content/en/opentelemetry/ingestion_sampling_with_opentelemetry.md
The original paragraph mentions 3 scenarios but the image and the text above only mention two scenarios.
> fix opentelemetry docs

- content/en/agent/guide/_index.md
- content/en/agent/guide/azure-private-link.md
Adds a guide to the Agent section about using Azure Private Link.
> DOCS-6863 - Azure Private Link

- content/en/security/cloud_security_management/review_remediate/jira.md
- content/en/security/cloud_security_management/review_remediate/mute_issues.md
- content/en/security/cloud_security_management/review_remediate/workflows.md
Adds product identifier tags to Cloud Security Management Review and Remediate docs
> Add product identifier tags to CSM Review and Remediate docs

- .github/workflows/check_cache_values.yml
- .github/workflows/code-freeze.yml
- .github/workflows/gif_check.yml
- .github/workflows/preview_link.yml
See https://securitylab.github.com/advisories/GHSL-2023-271_changed-files/
Fix a security vulnerabilit related to the usage of the "changed-files" GitHub action in this repository
> fix usage of "changed-files" GitHub action

- content/en/tracing/trace_explorer/query_syntax.md
> (maint) Add redirect to query syntax doc

- content/en/data_streams/_index.md
updating DSM docs with support for SQS
> updating_sqs.md

- content/en/account_management/teams.md
Raised by Thibault in #documentation on Slack.
> Datadog Teams Doc Update

- content/en/dashboards/widgets/alert_value.md
- content/en/dashboards/widgets/change.md
- content/en/dashboards/widgets/funnel.md
- content/en/dashboards/widgets/geomap.md
- content/en/dashboards/widgets/iframe.md
- content/en/dashboards/widgets/list.md
- content/en/dashboards/widgets/scatter_plot.md
- content/en/dashboards/widgets/service_summary.md
- content/en/dashboards/widgets/slo.md
- content/en/dashboards/widgets/treemap.md
- Add more information where possible to Widget intro section
- [DOCS-7202](https://datadoghq.atlassian.net/browse/DOCS-7202)
[DOCS-7202]: https://datadoghq.atlassian.net/browse/DOCS-7202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Initial overhaul of widget overview

- content/en/real_user_monitoring/platform/_index.md
Adds a relevant further reading item to the RUM Platform page.
> Add a further reading page

- content/en/glossary/terms/security_posture_score.md
Updates the security posture score formula.
> Update security posture score formula

- content/en/service_management/app_builder/auth.md
Requested by Wes Auyeung, an engineer working on App Builder
https://datadoghq.atlassian.net/browse/DOCS-7437
> Update subject heading and permission names for App Builder access

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 91

- content/en/security/threat_intelligence.md
- fruad -> fraud
- Flagged during translation
> Fix typo in Threat Intelligence

- content/en/containers/kubernetes/tag.md
- Fix yaml example for Pod annotations as tags.
- Flagged during translation.
>  Fix Pod Annotations as Tags Example

- content/en/service_catalog/_index.md
add dependencies management use cases
> Update service catalog overview

- content/en/real_user_monitoring/guide/proxy-rum-data.md
Add note about proxy implementation requirement to avoid malicious usage of the proxy
> [DOCS-7412] Browser RUM proxy extra note

- content/en/watchdog/alerts/_index.md
- Text says three places but lists four. Fixed.
- Flagged during translation.
> Correct Number of Places Watchdog Alerts Are Found

- content/en/security/threats/_index.md
The CSM threats team is introducing a new feature in private beta. We'd like to add a banner so that customers who are interested in it could notify our PM by filling out a google form. The form has been approved by our PM @paragbaxi .
> Active protection banner

- content/en/service_catalog/_index.md
> update service catalog use cases

- content/en/metrics/guide/micrometer.md
Micrometer docs site was updated, so the further reading took users to an archived page. Adjusted to point to new location.
> [Hotjar] Point to new docs site for micrometer

- content/en/security/cloud_security_management/setup/fargate.md
> [CWS] adapt the fargate instruction for the 7.52 agent version

- content/en/real_user_monitoring/browser/troubleshooting.md
Based on troubleshooting experience we want to clarify this technical limitation in the docs.
> [RUM-2702] Documenting the session-application-cookie relation

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-js layer to version 108

- content/en/service_catalog/adding_metadata.md
adding additional info about v3.0
> Update schema v3.0 info

- content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
> Remove inaccurate sentence from OpenTelemetry docs

- content/en/dashboards/widgets/_index.md
Add links for **View related logs**, **View related logs**, and **View related logs** in the **Graph menu** section.
> Dashboards Widgets Doc Edit

- content/en/code_analysis/static_analysis/_index.md
Remove a temporal word per the documentation style guide
> Remove temporal word

- content/en/security/application_security/enabling/compatibility/go.md
- content/en/security/application_security/enabling/go.md
> ASM Go setup enhancement

- content/en/database_monitoring/connect_dbm_and_apm.md
DOCS-7338
Approved by Casey Culligan, no need to wait for DBM approval.
> Add Oracle support for APM <> DBM

- layouts/shortcodes/csm-windows-setup.md
With the imminent release of agent 7.52, CSM for Windows moves out of beta status and is available in default builds of the agent. This PR removes the beta notices, and updates links to point to regular agent install page (indicating that we require 7.52 or higher).
PLEASE DO NOT MERGE THIS PR YET
> CSM for windows: move out of beta/custom build status

- content/en/tests/setup/python.md
Fixes a typo in datadog python test tracing documentation
> Update python.md - Fix typo

- config/_default/menus/menus.en.yaml
Simply moving Crash Reporting up a few levels under Mobile and TV Monitoring because it's a hot topic for app developers.
> Move Crash Reporting up

- content/en/service_management/incident_management/guides/jira.md
Address a copy nit found in a quick skim.
> Integrate Jira with Datadog Incident Management Guide Edit

- content/en/security/cloud_security_management/setup/fargate.md
> [CWS] update with the latest image

- content/en/glossary/terms/security_posture_score.md
> DOCS-7460: Update posture score defintion

- content/en/monitors/types/forecasts.md
> Correct WatchDog Forecast documentation

- content/en/api/latest/_index.md
- content/en/getting_started/api/_index.md
Update Postman collection links and instructions
> (DOCS-7402) Update Postman collection links and instructions

- config/_default/menus/menus.en.yaml
> (OTEL) Replace guide in menu

- content/en/opentelemetry/guide/migration.md
> (OTEL) Add missing instruction

- content/en/cloudcraft/advanced/_index.md
- content/en/cloudcraft/advanced/auto-layout-via-api.md
Add a new article to the Cloudcraft documentation describing how to mimic the web UI's **Auto Layout** feature using the developer API and simple command-line tools.
Not really sure I like the title. Suggestions are welcome!
Please wait until the Cloudcraft team has reviewed the content before going ahead with the review and merging of the article.
> [CLOUDCRAFT-388] Automate Snapshots of Cloud Accounts via the Cloudcraft API

- content/en/dashboards/widgets/check_status.md
- content/en/dashboards/widgets/slo_list.md
- Add more information on the widgets in the Overview
- [DOCS-7202](https://datadoghq.atlassian.net/browse/DOCS-7202)
[DOCS-7202]: https://datadoghq.atlassian.net/browse/DOCS-7202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add info for check status and slo list

- content/en/security/cloud_security_management/setup/fargate.md
> [CWS] fix cws-instrumentation on fargate eks

- content/en/security/cloud_security_management/setup/_index.md
removing beta tags for Windows CSM threats
> move Windows CSM out of beta

- content/en/metrics/guide/micrometer.md
This PR updates the link to the "Micrometer Prometheus" section.
N/A
> Update link to "Micrometer Prometheus"

- layouts/shortcodes/csm-windows-setup.md
Adds a section to CSM Windows docs for File Integrity Monitoring beta. Request from PM.
> Add FIM section to CSM Windows docs

- content/en/cloud_cost_management/azure.md
> Update Azure to say no CSP support

- content/en/account_management/teams.md
- content/en/monitors/notify/_index.md
- Add configuration instructions to setup notification channels to Teams
- Audit Teams instructions with the UI
- Add reference link from Monitors docs
> Add Teams Notification feature

- content/en/developers/custom_checks/write_agent_check.md
Add a sentence about custom check scripts being readable and executable by the Agent user. 
In a follow-up PR, we should provide more information about the default Agent user for each OS in the the relevant basic usage pages.
> (DOCS-7483)(Agent) Custom check file permissions

- content/en/mobile_app_testing/_index.md
- content/en/mobile_app_testing/mobile_app_tests/_index.md
- content/en/mobile_app_testing/mobile_app_tests/advanced_options.md
- content/en/mobile_app_testing/mobile_app_tests/results.md
- content/en/mobile_app_testing/mobile_app_tests/steps.md
- content/en/mobile_app_testing/settings/_index.md
[DOCS-7526](https://datadoghq.atlassian.net/browse/DOCS-7526)
[DOCS-7526]: https://datadoghq.atlassian.net/browse/DOCS-7526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7526] adding support for US5 and EU - updating banners

- assets/scripts/components/global-modals.js
- assets/scripts/utms.js
This brings docs in line with the signup query param logic that already exists on corp. This ensures that all UTM cookies and/or query params are persisted to the signup URL when clicking the Free Trial CTA. This is used by marketing-ops to track conversions and other signup metrics.
https://datadoghq.atlassian.net/browse/WEB-4695
**Test query params**
1.  https://docs-staging.datadoghq.com/ccole/add-signup-utm-logic/?utm-medium=testing&utm-source=testing&utm-campaign=testing
2. Click `Free Trial` on homepage
3. Inspect the signup iframe, open dev console, and confirm that the iframe URL includes the query params `?dd-utm-medium=testing&dd-utm-source=testing&dd-utm-campaign=testing`
**Test cookies**
1. Open URL without query params …
> Add app signup UTM logic

- content/en/developers/integrations/agent_integration.md
> Updatethe Python version used for `ddev` in agent_integration.md

- static/resources/sh/data_jobs/datadog_databricks_job_monitoring_init.sh
- static/resources/sh/data_jobs/datadog_databricks_job_monitoring_init_without_logs.sh
- static/resources/sh/data_jobs/datadog_emr_job_monitoring_init_v2.sh
Improve Data Job Monitoring scripts to include agent's host tag enhancements.
> Update Data Job Monitoring init script

- content/en/getting_started/_index.md
> Add high-level content to Getting Started index

- content/en/service_management/workflows/trigger.md
> (DOCS-7530) Trigger incident from monitor

- content/en/agent/basic_agent_usage/windows.md
Part 1: See ticket for details
> (DOCS-7475)(Agent) Replace Windows uninstall cmd

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 92

- content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps the version of the release for Linux.
> Bump AAS Linux version to v1.10.4

- local/bin/py/integration-finder.py
Catches an error that caused the script to fail if you had a dirty branch checked out. Kind of hard to test, but it looks like this:
```
make find-int int=aerospike
Updating dogweb: prod
Updating integrations-core: master
Updating integrations-extras: master
WARNING:Failed to update integrations-extras: master
Continuing without updating the repo. To resolve, check integrations-extras for a dirty feature branch and commit, stash, or reset any changes. Then try again.
Updating integrations-internal-core: main
Updating marketplace: master
You can find aerospike here:
- ../integrations-core/aerospike/README.md
- https://github.com/DataDog/integrations-core/blob/master/aerospike/README.md
```
This isn't part of our build, so it shouldn't need to be reviewed by the web team.
> (maint)(docsdev) Catch int-finder error

- config/_default/params.en.yaml
Updates the translate status text in params to be grammatically correct. While reviewing a different PR, I noticed it could use an update.
> Update params translate status banner

- content/en/dashboards/widgets/slo.md
- content/en/service_management/service_level_objectives/monitor.md
> clarify language for 5000 groups

- content/en/service_management/workflows/access.md
> (DOCS-7547)(Workflows) RBAC updates

- content/en/continuous_integration/_index.md
> adding blog link to CI docs

- content/en/account_management/billing/aws.md
- content/en/containers/troubleshooting/_index.md
- content/en/getting_started/integrations/aws.md
- content/en/integrations/guide/aws-integration-and-cloudwatch-faq.md
- content/en/integrations/guide/aws-manual-setup.md
- content/en/integrations/guide/cloud-metric-delay.md
Update mentions of Kinesis Data Firehose to Amazon Data Firehose per the service's [recent renaming](https://aws.amazon.com/about-aws/whats-new/2024/02/amazon-data-firehose-formerly-kinesis-data-firehose/)
> (DOCS-7342) Update service name

- content/en/containers/guide/ad_identifiers.md
Customer was confused as to whether the container must match all identifiers in the list or any one of them. Added a line to clarify.
> DOCS-7281: Update ad_identifiers.md

- content/en/agent/guide/use-community-integrations.md
Update the doc to include Marketplace as customers have been confused how to install Marketplace integrations on containerized environments
> Update community ints doc.md

- content/en/monitors/notify/variables.md
The example within the 'Dynamic Links' section of the logs currently has an incorrect link. 
It should be changed from "logs>?from_ts" to "logs?from_ts".
- [V] Please merge after reviewing
> Modify the example within the 'Dynamic Links' section of the logs

- content/en/integrations/guide/aws-manual-setup.md
- Add a note about specifying IAM conditions
- Minor formatting updates to other notes on the page
> (DOCS-7456) Add conditions note

- assets/scripts/components/algolia.js
Reverts DataDog/documentation#22424
> Revert "[WEB-4688] fixes instant search console warnings"

- content/en/account_management/billing/_index.md
Adds permissions details to the billing page. A user had submitted feedback that they saw a discrepancy between what the screenshots show and our docs. Verified with PM that what the views differ based on the type of contract.
[DOCS-7448](https://datadoghq.atlassian.net/browse/DOCS-7448)
[DOCS-7448]: https://datadoghq.atlassian.net/browse/DOCS-7448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update billing permissions details

- content/en/account_management/audit_trail/events.md
Add missing link and reorder links.
> Add missing link and reorder links on Audit Trail events page

- content/en/security/cloud_security_management/review_remediate/workflows.md
Page needed a couple edits due to UI changes. There's also now an easier way to grab the team and other data, which makes a JS step unnecessary.
> (DOCS-7351) Workflows: Revise workflows CSM doc

- content/en/agent/basic_agent_usage/windows.md
> (Agent) Update uninstall command

- content/en/service_management/service_level_objectives/_index.md
Remove outdated vimeo video from docs.
Change was requested by PM
> Remove video

- content/en/opentelemetry/_index.md
Guide more readers to our migration guide.
> Add warning banner to OpenTelemetry landing page

- content/en/api_catalog/_index.md
- content/en/cloud_cost_management/_index.md
- content/en/logs/_index.md
- content/en/logs/explorer/analytics/patterns.md
- content/en/monitors/types/cloud_cost.md
- content/en/security/application_security/api-inventory/_index.md
Adds the following blogs to our docs as part of Tuesday Tasks:
- https://www.datadoghq.com/blog/filter-logs-by-subqueries-with-datadog/
- https://www.datadoghq.com/blog/google-cloud-cost-management/
- https://www.datadoghq.com/blog/primary-risks-to-api-security/
> Add recent blog links

- content/en/logs/explorer/search_syntax.md
Adds information about Full-text search.
[DOCS-7373](https://datadoghq.atlassian.net/browse/DOCS-7373)
[DOCS-7373]: https://datadoghq.atlassian.net/browse/DOCS-7373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7373] Add full-text search

- content/en/code_analysis/static_analysis/setup.md
Adds instructions and examples for new options in the Static Analysis rules configuration to allow customization of how rules are applied to a repository
> Add new options for flexible Static Analysis rule config

- content/en/code_analysis/static_analysis/_index.md
Updates the supported languages for Static Analysis
> Update supported languages for Static Analysis

- layouts/shortcodes/latest-lambda-layer-version.html
Releasing v56 of Datadog Lambda Extension
> Bump datadog-lambda-extension layer to version 56

- content/en/agent/troubleshooting/send_a_flare.md
> (DOCS-7597)(Agent) Reorder flare methods

- content/en/agent/logs/_index.md
> (DOCS-7586)(Agent) Update Windows log path

- content/en/data_streams/_index.md
fixes video that I didn't catch was an .mov
> fixing video

- content/en/security/application_security/threats/protection.md
"leveraging" here should be "leverage":
> To leveraging protection capabilities for your service:
But I'll just make it simpler:
> To use protection capabilities with your service:
> ASM Protection topic typo 

- content/en/service_catalog/integrations.md
Inform users that on-call integrations are unsupported for Service Catalog in govcloud
> Govcloud limitation for Service Catalog On-Call Integrations

- content/en/tracing/trace_pipeline/_index.md
Change: 'understand how requests flow through you microservices' -> 'understand how requests flow through your microservices'
> Fix typo in Trace Pipeline docs

- content/en/account_management/teams/_index.md
https://datadoghq.atlassian.net/browse/DOCS-7431
Document Teams UI changes. The Teams UI recently had a refresh.
This is the first of 2 planned PRs.
This PR moves the Teams page into a directory and updates some of the UI instructions.
The follow-on PR will document the new Teams detail page.
> Document Teams UI changes

- content/en/tests/setup/javascript.md
Add note about the usage of `--exit` with mocha.
> [ci-visibility] Add note about mocha's `--exit` 

- content/en/data_streams/_index.md
- content/en/security/cloud_security_management/misconfigurations/signals_explorer.md
- content/en/security/cloud_security_management/setup/csm_cloud_workload_security/_index.md
- content/en/security/threats/security_signals.md
Adds the following blog links to docs:
- [Monitor SQS with Data Streams Monitoring](https://www.datadoghq.com/blog/data-streams-monitoring-sqs/)
- [Secure your Windows workloads with Datadog Cloud Security Management](https://www.datadoghq.com/blog/datadog-csm-windows/)
> Add blog links for Tuesday Tasks

- content/en/security/cloud_security_management/setup/fargate.md
> [CWS] add pidmode so that we collect infra metrics

- static/resources/json/datadog-agent-ecs-fargate.json
> [CWS] fix fargate task def sample

- config/_default/menus/menus.en.yaml
Quick fix to add URL parameter for the Bits AI landing page.
> Fix bits ai URL for menu

- content/en/dashboards/change_overlays/_index.md
- content/en/notebooks/_index.md
Update Dashboard and Notebooks docs with UI navigation updates
**Do not merge, pending release**
> Dashboard and Notebooks update for new nav changes

- content/en/monitors/_index.md
- content/en/monitors/downtimes/_index.md
- content/en/monitors/settings/_index.md
Align docs navigation references to new UI changes
**Do not merge** pending release
> Update docs for new monitors app nav

- content/en/service_management/app_builder/_index.md
Deletes "Get started faster with AI" section from document as requested by PM
> (DOCS-7637) Remove reference to generating with AI

- content/en/developers/authorization/oauth2_endpoints.md
- content/en/developers/authorization/oauth2_in_datadog.md
Deletes references to developer platform being in beta, as requested by PM
> (DOCS-7638) delete non-singled-sourced references to developers beta

- content/en/database_monitoring/data_collected.md
Add Oracle Metrics Referring to this page: https://docs.datadoghq.com/database_monitoring/query_metrics/
> Update data_collected.md add Oracle Metrics

- content/en/security/cloud_security_management/guide/public-accessibility-logic.md
Add documentation for AKS and AWS lambda.
Following https://github.com/DataDog/dd-source/pull/83897 https://github.com/DataDog/dd-source/pull/83596
> feat(public-accessibility-logic): Add AKS and AWS Lambda

- assets/styles/pages/_global.scss
fix shortcodes tables responsiveness
jira: https://datadoghq.atlassian.net/browse/WEB-4740
preview: https://docs-staging.datadoghq.com/renzo.renteria/fix-shortcodes-tables/network_monitoring/devices/data/
> table layout fixed

- .github/workflows/code-freeze.yml
> Undo code freeze

- assets/styles/pages/_global.scss
update containers max-width to match xl update on corp
https://docs-staging.datadoghq.com/renzo.renteria/xxl-udpate/
> match xxl max-width to corp

- .github/workflows/vale_linter.yml
- missed an `actions/checkout` update on my last PR
> Bump actions/checkout

- content/en/cloud_cost_management/azure.md
In response to #incident-26609, this PR updates the Azure setup docs to reflect new fields that show up for some beta customers.
> Update Azure docs to reflect new export fields

- content/en/opentelemetry/collector_exporter/deployment.md
- content/en/opentelemetry/collector_exporter/otel_collector_datadog_exporter.md
- content/en/opentelemetry/schema_semantics/hostname.md
Link to recently added hostnames guide
> [opentelemetry] Redirect to new hostnames guide

- content/en/cloud_cost_management/azure.md
In response to #incident-26609, this PR updates the Azure setup docs to reflect new fields that show up for some beta customers.
> [CCV] Update Azure docs to reflect new export experience

- assets/styles/pages/_global.scss
- layouts/shortcodes/get-metrics-from-git.html
fix overlapping text and table bugs
Jira: https://datadoghq.atlassian.net/browse/WEB-4762
Preview: [Browser Log Collection](https://docs-staging.datadoghq.com/renzo.renteria/fix-overlapping-text/logs/log_collection/javascript/) 
[NDM Data Collected](https://docs-staging.datadoghq.com/renzo.renteria/fix-overlapping-text/network_monitoring/devices/data/)
> table wrapper for overflow-x

- content/en/monitors/notify/_index.md
- content/en/observability_pipelines/guide/set_quotas_for_data_sent_to_a_destination.md
This PR fixes the format and content of the Notification page of Monitors.
> Update _index.md of Notification

- content/en/service_management/case_management/settings.md
Explain to Case Management users how to set up ServiceNow bidirectional syncing.
> Adding ServiceNow bisync instructions

- content/en/service_management/mobile/_index.md
Clarifying login via QR code flow
- bug fix "UDID" > "UUID"
- update to reflect login via QR code behavior
- [ X] Please merge after reviewing
> Update QR code login section

- package.json
We've been running into the local build loop issue a lot more recently. The problem seems to stem from macOS triggering multiple CHMOD changes, possibly in an interaction with VSCode. This seems to fix the issue locally, but I'm not sure what the broader implications are.
> (maint) Fix local build loop issue

- content/en/cloudcraft/getting-started/using-bits-menu.md
Update the list of AWS and Azure components supported by the Bits Menu feature in Cloudcraft.
> Update list of supported components for Cloudcraft's Bits Menu

- content/en/continuous_integration/guides/pipeline_data_model.md
Updates the `My Recent Commits` title to `Recent Code Changes` title, reflected in the Software Delivery UI.
> Pipeline Data Model Doc Edit

- content/en/security/application_security/enabling/serverless.md
- screenshot is CSM.
- should be ASM > Signals
- remove screenshot because this page is changing soon and would need to be updated again. I don’t think the screenshot is critical.
> DOCS-7693 remove screenshot

- content/en/integrations/guide/prometheus-metrics.md
[DOCS-7418](https://datadoghq.atlassian.net/browse/DOCS-7418)
[DOCS-7418]: https://datadoghq.atlassian.net/browse/DOCS-7418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7418] adding table to map openmetrics to datadog metrics 

- content/en/code_analysis/software_composition_analysis/_index.md
Adds a list of package manager and lockfiles support by Static SCA
> SCA Package Managers

- content/en/security/application_security/enabling/serverless.md
Update ASM test part to use our own rule
> Update ASM test part to use our own rule

- content/en/cloud_cost_management/recommendations/_index.md
Doc for the ALB documentation stands out: it mentions the evaluation time frame when no other does and it doesn't say "Unused" when ELB / NLB recs do. This PR fixes that!
> [CCR] Tweak load balancer documentation

- content/en/code_analysis/software_composition_analysis/generic_ci_providers.md
Replaces the use of Trivy with OSV Scanner
> Update SBOM Instructions to OSV Scanner

- content/en/continuous_testing/_index.md
- content/en/database_monitoring/_index.md
- content/en/profiler/_index.md
- content/en/security/cloud_security_management/misconfigurations/_index.md
Add Learning Center Callout to the for Postgres Database, Code performance testing, Synthetic testing in CI/CD , and CSM Misconfigurations docs
[DOCS-7140](https://datadoghq.atlassian.net/browse/DOCS-7140)
Related to https://github.com/DataDog/documentation/pull/22582
[DOCS-7140]: https://datadoghq.atlassian.net/browse/DOCS-7140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7140] learning center callout

- config/_default/menus/menus.en.yaml
- content/en/service_management/events/_index.md
- Fix the link for broken link in [Event Correlation update PR](https://github.com/DataDog/documentation/pull/22586)
> Fix link for broken link

- content/en/network_monitoring/devices/data.md
[DOCS-7589](https://datadoghq.atlassian.net/browse/DOCS-7589)
this fix https://datadoghq.atlassian.net/browse/WEB-4740 fix caused some undesirable behavior, so , I disabled the TOC and moved the Events and Service checks to the top of the page. So re-opening this PR :) 
[DOCS-7589]: https://datadoghq.atlassian.net/browse/DOCS-7589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7711] removing TOC and on NDM data collected page/ restructuring

- content/en/code_analysis/_index.md
Clarifies that in the context of Code Analysis, Static Analysis and SCA are scan types not products
> Clarify Scan Types Wording

- content/en/developers/integrations/oauth_for_integrations.md
This PR clarifies when OAuth support is required for an integration, and when it does not apply. It also removes outdated UI Extension documentation. Finally, it adds a number of tweaks to help improve readability. 
Please merge as soon as you've reviewed. Thanks.
> Update developer OAuth integration documentation

- content/en/cloud_cost_management/azure.md
Azure released a new way of creating exports. We're actively working in getting a long term solution but in the meantime, we ask customers to disable the experience.
We are still getting support tickets so we're adding more details to the docs.
> [CCV] Update CCM azure docs

- content/en/security/application_security/threats/add-user-info.md
Fixed link to dependencies for ASM SDK
> Fixed link to dependencies for ASM SDK

- config/_default/menus/menus.fr.yaml
- config/_default/menus/menus.ja.yaml
This PR updates the ja/fr side nav to match en as far as structure but retain as much translations as possible
https://datadoghq.atlassian.net/browse/WEB-4779
https://docs-staging.datadoghq.com/david.jones/nav-update/fr/agent/?tab=Linux
https://docs-staging.datadoghq.com/david.jones/nav-update/ja/agent/?tab=Linux
> WEB-4779 - Nav update

- content/en/security/cloud_security_management/setup/_index.md
Updates setup table for CSM Misconfigurations. Requested by PM.
> Update setup table for CSM Misconfigurations

- content/en/getting_started/synthetics/private_location.md
- content/en/synthetics/private_locations/_index.md
[DOCS-7724](https://datadoghq.atlassian.net/browse/DOCS-7724)
[DOCS-7724]: https://datadoghq.atlassian.net/browse/DOCS-7724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-7724] updating private locations docs with EULA

- content/en/monitors/types/real_user_monitoring.md
Added space missing in first sentence.
Added missing space in "Overview" section.
> Add missing space in "Overview" section

- content/en/security/cloud_siem/guide/google-cloud-config-guide-for-cloud-siem.md
- Update pub/sub -> Pub/Sub topic for clarity and compliance with Google Cloud naming conventions
- Minor editorial update for active voice
> (DOCS-6971) Update Pub/Sub casing

- content/en/getting_started/application_security/software_composition_analysis.md
Replaces out of date nav references with names of the target pages. 
See [spreadsheet](https://docs.google.com/spreadsheets/d/13-9fGbmoD9fFXHVsiXdKO6xJDGnnWndJvOWKOvX6Yns/edit#gid=193793479) for more details on overall effort
> Replaces references to locations in nav

- content/en/standard-attributes/_index.md
> Update db.sql.table type

- content/en/code_analysis/github_pull_requests.md
Changes instructions to match wording in the UI for GitHub App
> Rename Code Analysis GitHub App Feature

- content/en/database_monitoring/architecture.md
1. Add Oracle Metrics Guide Page link.
2. Change order aline with the other contents.
> Update architecture.md to add Oracle Metrics Page Link

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/java.md
Adds a support link to the note regarding release candidates
> add support link to RC note

- content/en/database_monitoring/setup_sql_server/azure.md
- content/en/database_monitoring/setup_sql_server/rds.md
- content/en/database_monitoring/setup_sql_server/selfhosted.md
- layouts/shortcodes/dbm-alwayson.md
- layouts/shortcodes/dbm-sqlserver-agent-config-examples.md
Puts AlwaysOn information into a shortcode so that it can be in all the tabs (reducing the chance that people skip over the info and go straight to the tabs), and makes the most important part bolder.
Note: Doesn't do the same thing on all pages because some of them need different language, or the content is already in a shortcode. In the case of Azure and GCSQL, I just made more of the text bold.
> (DOCS-6444) Make AlwaysOn information more prominent

- content/fr/agent/guide/environment-variables.md
> (DOCS-7545) Fix broken link

- content/en/observability_pipelines/_index.md
Adds blog links for Observability Pipelines. Tuesday Tasks.
> Add blog links for Observability Pipelines

- content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md
> Add note about enriching custom metrics to OTLP Ingest docs

- content/en/account_management/teams/manage.md
Documents the new team customization options on the team detail page.
> Document team management UI DOCS-7431

- content/en/profiler/guide/_index.md
- content/en/profiler/guide/save-cpu-in-production-with-go-pgo.md
> PGO - simplify titles

- layouts/partials/dbm/dbm-data-collected.html
> Add Oracle link to Data Collected page

- content/en/profiler/guide/save-cpu-in-production-with-go-pgo.md
> PGO - explain how to check where PGO is enabled

- content/en/security/cloud_security_management/setup/fargate.md
> [CWS] improve EKS instruction

- .github/workflows/validate_filenames.yml
- Adds `AM` to the diff filter to ensure we catch any modified or added files
- Adds `...` between the two shas to ensure we only are getting changes between the base branch and the pull request
https://github.com/DataDog/documentation/actions/runs/8787286821/job/24112143932?pr=22783 - run with all files checked
We discovered a bug on corp where false positives were thrown due to the diff strategy picking up changes in branches that were out of date with master. The `...` should ensure git is only getting the changes specifically made in the PR.
> Update diff strategy for filename validation

- .github/workflows/validate_filenames.yml
- Reverts the change that would check all files and scopes the diff to only the `static` directory
> Only check the static diff

- content/en/code_analysis/static_analysis/_index.md
Link to YAML setup instructions in Ignore Violations section 
Motivation: I couldn't find the instructions at first when I came to this section 
> Link to YAML setup instructions in Ignore Violations section 

- content/en/security/cloud_security_management/misconfigurations/frameworks_and_benchmarks/_index.md
Fixes a broken link (URL was updated incorrectly in a recent PR). DOCS-7768.
> DOCS-7768: Fix broken link

- content/en/monitors/configuration/_index.md
- Add the specific UI text so users can search for this feature in the docs.
- [DOCS-7726](https://datadoghq.atlassian.net/browse/DOCS-7726)
**Do not merge**: Pending approval from requestor.
[DOCS-7726]: https://datadoghq.atlassian.net/browse/DOCS-7726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add UI specific text

- content/en/dora_metrics/setup/deployments.md
> [CIVIS-9788] Add CLT breakdown metrics to documentation

- content/en/account_management/rbac/granular_access.md
Update Granular access page with supported resources
> Update Granular Access page with supported resources

- content/en/dashboards/functions/rate.md
Adds a section for the throughput function.
> Document throughput function

- content/en/tracing/trace_collection/trace_context_propagation/dotnet.md
Updated documentation based on latest releases:
https://github.com/DataDog/dd-trace-dotnet/pull/5115
> Adding latest propagation changes

- content/en/agent/fleet_automation/_index.md
- content/en/agent/remote_config/_index.md
Removing UI navigation from the Agent docs
> (Agent) Navigation updates

- content/en/tracing/trace_collection/custom_instrumentation/java/otel.md
Minor clarification to support table.
> clarify table

- content/en/glossary/terms/trace_metric.md
- Change navigation instructions to be static link to the Metrics Summary page
- Remove reference to video that includes the navigation UI
> Update trace metrics glossary for new Nav UI changes

- content/en/service_management/workflows/_index.md
See [DOCS-7748](https://datadoghq.atlassian.net/browse/DOCS-7748)
[DOCS-7748]: https://datadoghq.atlassian.net/browse/DOCS-7748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (Workflows) Nav updates

- content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
This PR clarifies a sentence that is causing confusion for translators.
> Clarify sentence

- content/en/infrastructure/containers/kubernetes_resource_utilization.md
- content/en/infrastructure/list.md
- content/en/infrastructure/process/_index.md
- content/en/infrastructure/process/increase_process_retention.md
- Audit docs to make sure it's in line with the new UI navigation
- Add ui instructions for **Infrastructure > Hosts**, because it's not as obvious on how to find this page
- Remove outdate image
> Update Infrastructure in app docs for new ui nav

- content/en/service_management/app_builder/_index.md
- content/en/service_management/app_builder/auth.md
- content/en/service_management/app_builder/build.md
- content/en/service_management/app_builder/embedded_apps.md
- Removes another instance of "create with AI" content, which the PM asked to have removed from the docs.
- A bunch of copy editing.
> Removes 'create with AI' content; copy-editing

- .prettierignore
- config/_default/menus/main.en.yaml
- content/en/error_tracking/apm.md
- content/en/error_tracking/custom_grouping.md
- content/en/error_tracking/explorer.md
- content/en/error_tracking/logs.md
- content/en/error_tracking/rum.md
- content/en/error_tracking/suspect_commits.md
- content/en/logs/error_tracking/custom_grouping.md
- content/en/logs/error_tracking/explorer.md
- content/en/logs/error_tracking/suspect_commits.md
- content/en/real_user_monitoring/error_tracking/_index.md
- content/en/real_user_monitoring/error_tracking/custom_grouping.md
- content/en/real_user_monitoring/error_tracking/explorer.md
- content/en/real_user_monitoring/error_tracking/suspect_commits.md
- content/en/tracing/error_tracking/custom_grouping.md
- content/en/tracing/error_tracking/explorer.md
- content/en/tracing/error_tracking/suspect_commits.md
- layouts/partials/table-of-contents/table-of-contents.html
DOCS-7608
Do not merge this, thanks!
> Cross-link Error Tracking documentation

- config/_default/menus/main.en.yaml
- content/en/observability_pipelines/dual_ship_logs/splunk_hec.md
- content/en/observability_pipelines/dual_ship_logs/splunk_tcp.md
- content/en/observability_pipelines/dual_ship_logs/sumo_logic_hosted_collector.md
- content/en/observability_pipelines/log_volume_control/splunk_tcp.md
- content/en/observability_pipelines/log_volume_control/sumo_logic_hosted_collector.md
- content/en/observability_pipelines/split_logs/splunk_hec.md
- content/en/observability_pipelines/split_logs/splunk_tcp.md
- content/en/observability_pipelines/split_logs/sumo_logic_hosted_collector.md
- layouts/shortcodes/observability_pipelines/log_source_configuration/splunk_hec.md
- layouts/shortcodes/observability_pipelines/log_source_configuration/splunk_tcp.md
- layouts/shortcodes/observability_pipelines/log_source_configuration/sumo_logic.md
- layouts/shortcodes/observability_pipelines/prerequisites/datadog_agent_destination_only.md
- layouts/shortcodes/observability_pipelines/prerequisites/splunk_hec.md
- layouts/shortcodes/observability_pipelines/prerequisites/splunk_tcp.md
- layouts/shortcodes/observability_pipelines/processors/filter_syntax.md
- layouts/shortcodes/observability_pipelines/processors/quota.md
> Correct inaccuracies in Observability Pipelines docs

- content/en/developers/integrations/create-a-cloud-siem-detection-rule.md
- content/en/developers/integrations/create-an-integration-dashboard.md
- content/en/developers/integrations/create-an-integration-recommended-monitor.md
- content/en/developers/integrations/log_pipeline.md
- content/en/developers/service_checks/_index.md
See [DOCS-7748](https://datadoghq.atlassian.net/browse/DOCS-7748)
[DOCS-7748]: https://datadoghq.atlassian.net/browse/DOCS-7748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (Developer) Nav updates

- content/en/security/application_security/code_security/_index.md
Update the list of possible detectable vulnerabilities with IAST (Code Security).
> [ASM][IAST] Update vulnerabilities list

- content/en/opentelemetry/collector_exporter/_index.md
- content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md
- Move OOTB Dashboards section to more relevant page.
- This section doesn't make sense on OTLP Ingest page, because it's only supported with OTel Collector, not DD Agent.
> Move OOTB OTel Dashboard Section

- content/en/security/default_rules/_index.md
> DOCS-7785: Update OOTB rules page for attack paths

- content/en/sensitive_data_scanner/_index.md
- content/en/sensitive_data_scanner/investigate_sensitive_data_issues.md
- Update Sensitive data scanner documentation reference to navigation to match current UI
> [Sensitive Data Scanner] nav reference update

- content/en/tracing/trace_collection/custom_instrumentation/opentracing/dotnet.md
DOCS-2919 - adds a link to related info
> [DOCS-2919] Add link to info about trace propagation

- content/en/continuous_integration/pipelines/jenkins.md
Reorder the tabs so the Agentless mode (which is recommended) is displayed first, and the Agent-based mode is displayed second.
Flagged in #ci-visibility-provider-integrations on Slack.
> Set up Tracing on a Jenkins Pipeline Doc Update

- content/en/code_analysis/static_analysis/_index.md
> Static Analysis Doc Edit

- content/en/logs/explorer/_index.md
- content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
> (DOCS-7342) Update blog links

- content/en/tests/_index.md
The feature is not ready for usage yet.
> [test-visibility] Remove flaky test retries from feature table

- content/en/cloud_cost_management/aws.md
- content/en/dashboards/widgets/profiling_flame_graph.md
- content/en/infrastructure/_index.md
- content/en/integrations/_index.md
- content/en/opentelemetry/_index.md
- content/en/profiler/compare_profiles.md
- content/en/quality_gates/explorer/_index.md
- content/en/security/default_rules/_index.md
- local/bin/py/build/configurations/pull_config_preview.yaml
> (DOCS-7779)(maint) Add redirects

- content/en/code_analysis/static_analysis/setup.md
Adds clarification on the GitHub App permissions needed by Code Analysis
> Add Code Analysis GitHub Permissions

- content/en/security/cloud_security_management/identity_risks/_index.md
- content/en/security/cloud_security_management/setup/_index.md
Adds Azure support for CSM Identity Risks.
> Add Azure support for CSM Identity Risks

- layouts/shortcodes/latest-lambda-layer-version.html
> Bump datadog-lambda-python layer to version 93

- content/en/cloudcraft/getting-started/connect-an-azure-aks-cluster-with-cloudcraft.md
Updates an image's alt text to match the image's content, as pointed out by a translator
> Update alt text

- content/en/security/application_security/threats/attacker-explorer.md
> fix typo in attacker-explorer.md

- content/en/cloudcraft/faq/_index.md
- content/en/cloudcraft/faq/how-cloudcraft-connects-to-azure.md
Add an article informating customers how we connect to their Azure accounts, just like we did for AWS.
Please wait until the Cloudcraft team has reviewed the content before going ahead with the review and merging of the article.
> [CLOUDCRAFT-532] How does Cloudcraft connect to my Azure account?

- content/en/tracing/llm_observability/_index.md
- content/en/tracing/llm_observability/basic-tracing-concepts.md
- content/en/tracing/llm_observability/nested_page_example.md
- content/en/tracing/llm_observability/sdk_quickstart.md
> [WIP] alex.holachek/initial llm obs docs

- content/en/dynamic_instrumentation/_index.md
Add a note on the limitations around Dynamic Instrumentation
> Add a note on Dynamic Instrumentation limitations

- content/en/mobile_app_testing/mobile_app_tests/_index.md
- content/en/real_user_monitoring/guide/alerting-with-conversion-rates.md
While working on a different PR, I noticed there were still a few straggling mentions of UX Monitoring that needed to be updated to Digital Experience.
> Update remaining mentions of UX Monitoring

- content/en/service_management/incident_management/_index.md
Add ServiceNow to Incident Management integration section with link to integration doc
> Add ServiceNow integration link

- content/en/security/cloud_security_management/setup/agentless_scanning/_index.md
> Fix numbering in disabling agentless setup doc

- config/_default/menus/main.en.yaml
- content/en/intelligent_test_runner/_index.md
- content/en/intelligent_test_runner/setup/ruby.md
- layouts/partials/continuous_integration/ci-itr-setup.html
Adds documentation for intelligent test runner in Ruby ahead of public beta start
> [CIVIS-9767] add documentation for ITR in Ruby

- content/en/monitors/types/event.md
Matching the faceting-limitations info from the Logs and RUM docs as it also applies here
https://docs.datadoghq.com/monitors/types/log/#define-the-search-query
> Add faceting details to event.md

- content/en/tracing/trace_collection/trace_context_propagation/_index.md
- content/en/tracing/trace_collection/trace_context_propagation/cpp.md
- content/en/tracing/trace_collection/trace_context_propagation/dotnet.md
- content/en/tracing/trace_collection/trace_context_propagation/go.md
- content/en/tracing/trace_collection/trace_context_propagation/nodejs.md
- content/en/tracing/trace_collection/trace_context_propagation/php.md
- content/en/tracing/trace_collection/trace_context_propagation/python.md
- content/en/tracing/trace_collection/trace_context_propagation/ruby.md
Updates the default propagation style across languages
> Change default propagation to datadog,tracecontext

- content/en/containers/docker/apm.md
User feedback requested default values for this table. I've added defaults, in addition to data type and whether each parameter is required. I've also restructured this table into a headless list.
> DOCS-7549 - Docker APM envvar table revamp

- content/en/code_analysis/github_pull_requests.md
Clicking on "see the setup instructions" didn't scroll down to the setup section due to a missing space
> Fixing broken link 

- content/en/code_analysis/github_pull_requests.md
Adds a clarification for how GitHub Actions should be configured to enable PR Comments correctly
> Add Clarification About GitHub Actions

- content/en/opentelemetry/integrations/kafka_metrics.md
> Fix Typo in OTel Kafka Metrics Banner

- content/en/integrations/_index.md
> Add temporary alias to fix 404

- content/en/security/cloud_security_management/setup/fargate.md
Fixes a link in the CSM Fargate docs.
> Fix link in CSM Fargate docs

- content/en/code_analysis/github_pull_requests.md
Slight wording fix so there isn't a new bulleted list starting at 1 with nothing after it
> Replace Number with Note
