DataDog/documentation

content/en/cloud_cost_management/aws.md
Adjusts the language around the usage of AWS Billing Conductor to configure Cloud Cost Management
~~I am still getting this reviewed within the CCM team so I've put this in Draft~~
=> CCM adjust language around Billing Conductor

content/en/tracing/trace_collection/compatibility/go.md
Clarify for users that you need to initialize the Go tracer before configuring integrations.
=> [DOCS-7390] Tracer must be initialized before configuration integrations

content/en/profiler/enabling/ruby.md
This PR updates the "Enabling the Ruby profiler" page to use the `ddprofrb` command as a replacement for the `ddtracerb` command that was deprecated in https://github.com/DataDog/dd-trace-rb/pull/3501 .
The old command is still going to be kept around for a while longer, and emits a deprecation warning when used.
The dd-trace-rb release containing this change fix (1.21.0) has not yet been released, so I'm queuing this documentation change but ask that we don't merge it yet, and I'll come back and leave a note once the release is out.
N/A
=> Update "Enabling the Ruby profiler" to use the new `ddprofrb` command

content/en/profiler/profiler_troubleshooting/ruby.md
This PR updates the Ruby troubleshooting documentation, now that a new workaround exists and is auto-applied (<https://github.com/DataDog/dd-trace-rb/pull/3473>).
This clarifies that using the "no signals" workaround is no longer the recommended way to solve this issue.
The dd-trace-rb release containing the fix (1.21.0) has not yet been released, so I'm queuing this documentation change but ask that we don't merge it yet, and I'll come back and leave a note once the release is out. 
N/A
=> [PROF-9147] Document workaround for Ruby gc_finalize_deferred

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/php.md, content/en/tracing/trace_collection/compatibility/php.md
Windows support has been released with the version [0.98.0](https://github.com/DataDog/dd-trace-php/releases/tag/0.98.0) of the tracer for PHP7.2+.
This PR adds related documentation and important notes while trying to trace PHP applications on Windows.
=> docs: PHP Tracer Windows Support

content/en/monitors/guide/how-to-set-up-rbac-for-monitors.md
As we are moving on with the locked deprecation, we updated the public doc explaining that locked monitors will no longer be supported after March 27, 2024.
=> Update locked deprecation guide

config/_default/menus/menus.en.yaml
We have this list of [Setup pages](https://docs.datadoghq.com/continuous_integration/pipelines/?tab=githubactions#setup) on the Pipeline Visibility landing page, and we want to add the [Custom Pipelines child page](https://docs.datadoghq.com/continuous_integration/pipelines/custom/) in the left hand navigation. 
Requested by Will McMullen on Slack.
=> Add Custom Pipelines in Left Hand Nav

static/resources/sh/data_jobs/datadog_emr_job_monitoring_init_v2.sh
Adding the two tags:
- `init_script_version:1` to track which version of the script is used 
- `cluster_id` with the same value as `job_flow_id`, to have a unified tagging for cluster_id with other technologies
=> Data Jobs Monitoring - Add tags to EMR init script

content/en/data_jobs/kubernetes.md
By adding the parameter `-Ddd.trace.experimental.long-running.enabled=true` to the spark submit command
=> Data Jobs Monitoring - Enable long running spans parameter in k8s

content/en/monitors/notify/_index.md
Datadog teams can now support notification channels. When a notification channel is set and the team handle is used in a monitor message the notification will be redirected to that notification channel for that team
=> Team handles can be used in montior notifcations

assets/styles/vendor/_chroma-styles.scss
The Docs team has been using the code highlight shortcode more and more often. This is really useful, but the default style looks out of place from our normal color scheme. This update tweaks the style look better and more consistent.
**Before**:
**After**:
[Preview](https://docs-staging.datadoghq.com/brett0000FF/code-hl-style/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=kubernetes)
=> [Hackathon Q1 2024] Improve Line Highlight Style for Code Blocks

content/en/security/application_security/enabling/go.md
Fix the placement of the notes I wrote in #22256 because I did not know what `{{< tabs >}}` meant
=> asm: go: fix build notes placement

content/en/dashboards/guide/how-to-use-terraform-to-restrict-dashboard-edit.md
* We released https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/restriction_policy - got a note there that dashboard support is in private beta.
* For dashboards, existing customers that use is_read_only or restricted_roles need to be careful and not use both at the same time, so we offer some additional guidance through Support for now.
* Main goal here is to note document that Terraform Restriction Policies for dashboards are currently in private beta.
Drive-by change - refresh old docs:
1. `is_read_only` has been deprecated years ago, `restricted_roles` is marked as deprecated now too: https://docs.datadoghq.com/api/latest/dashboards/#create-a-new-dashboard
2. So, removing the old `is_read_only` -> `restricted_roles` migration guidance.
=> Update "How to use Terraform to restrict the editing of a dashboard"

content/en/real_user_monitoring/error_tracking/browser.md, content/en/real_user_monitoring/error_tracking/mobile/android.md, content/en/real_user_monitoring/error_tracking/mobile/expo.md, content/en/real_user_monitoring/error_tracking/mobile/flutter.md, content/en/real_user_monitoring/error_tracking/mobile/ios.md, content/en/real_user_monitoring/error_tracking/mobile/reactnative.md
We have bumped the limit of file size for source maps to 500 MB – on all DC but AP1 – with the PR [#55048](https://github.com/DataDog/datacenter-config/pull/55048) on the datacenter config and the PR [#65065](https://github.com/DataDog/logs-backend/pull/65065) on the Logs back-end to increase the timeout related to the upload step and accommodate larger files.
After a few weeks of testing and polishing, we are now confident in sharing this information with all customers.
This PR:
- Updates the RUM / Error Tracking pages for Browser and Mobile SDKs to display the correct limitations
- Add limitations on pages where it was missing
- Make the placement of this limitation consistent across pages
=> Update values for max debug symbol file size

content/en/profiler/guide/isolate-outliers-in-monolithic-services.md
Instructions for specifying custom context in Java profiles were missing the required step of telling the backend which of the instrumented context keys to analyze at intake.
=> [profiling] Fix missing instructions for Java custom context

content/en/network_monitoring/devices/snmp_metrics.md
As of agent 7.52, Network Device Monitoring exposes the ability to send ICMP pings to devices as part of the SNMP check. This PR adds documentation on how to configure this functionality inside the agent.
=> [NDM] Add documentation for ping

content/en/monitors/notify/variables.md
This PR add a mention of the new `issue.link` template variable for Error Tracking monitors alongside the existing ones.
=> Advertise issue.link template variable in Error Tracking monitors 

content/en/tracing/trace_collection/compatibility/python.md
@federico.mon@datadoghq.com confirmed that we only support Celery 4.4.x onwards
Updating the Celery Supported version
=> Update Celery supported version

content/en/profiler/profile_types.md
This PR updates the Ruby profile types documentation to match the same changes in https://github.com/DataDog/documentation/pull/22301:
* Allocation is now in beta
* Bumped the minimum versions to v1.21.1+
* Allocation works in all Rubies
In the past few releases we did a number of important performance improvements, so I'm bumping the minimum versions we state for allocation + heap + timeline as otherwise running older versions means running with known performance pitfalls.
Finally, I've clarified that allocation profiling actually works on all Rubies we support, not only Ruby 2.7. This was an oversight on my earlier PR to add this documentation, and doesn't actually reflect the code. Oops :)
N/A
=> [NO-TICKET] Update Ruby profile types

README.md
Removes the build instructions from the README.
- External users cannot run the build, so it doesn't make sense to cover it in such detail here.
- The build setup instructions weren't complete and made it a little difficult to onboard new writers.
The README now links to the build instructions in Confluence.
=> (maint) Remove build instructions from README

layouts/shortcodes/pci-apm.md, layouts/shortcodes/pci-logs.md
Clarified Audit Trail requirement for PCI in Logs and APM to be automatically turned on when PCI is enabled for a given org, if not already turned on.
=> PCI audit trail req

content/en/profiler/connect_traces_and_profiles.md
This PR tweaks the Ruby timeline prerequisites section to:
1. Mention that it's enabled starting from `dd-trace-rb` 1.21.1+ (See https://github.com/DataDog/dd-trace-rb/releases#:~:text=Profiler%20timeline%20feature%20is%20now%20on%20by%20default for details)
2. Drop the outdated mention for how to enable it on older versions. In particular, I don't think we should keep it since we've since made a number of performance improvements, so we really want to encourage folks to move to 1.21.1 instead of trying the feature with known performance pitfalls.
3. Document how to enable showing GC information in timeline. (See https://github.com/DataDog/dd-trace-rb/releases#:~:text=Performance%20improvements%20to%20Garbage%20Collection%20Profiling%20%2B%20Timeline%20view%20support for details)
N/A
=> [NO-TICKET] Update Ruby timeline prerequisites

content/en/profiler/connect_traces_and_profiles.md
Reverts DataDog/documentation#22349
Will fix this in a separate PR, the formatting doesn't match what's in current master branch.
=> Revert "[NO-TICKET] Update Ruby timeline prerequisites"

content/en/profiler/connect_traces_and_profiles.md
Reverts DataDog/documentation#22357
=> Revert "Revert "[NO-TICKET] Update Ruby timeline prerequisites""

content/en/code_analysis/static_analysis_rules/_index.md
Adds frontmatter for the Ruby rulesets.
=> Add Ruby rules to landing page.

content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md
Add a note to .NET Tracer's `DD_TRACE_ENABLED` configuration option to clarify what happens if it is set as an environment variable (as opposed to other configuration methods).
=> [APM > .NET] Add note about the effect of configuring `DD_TRACE_ENABLED` as env var

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
The latest Agent release changed behavior of `libVersions`.
Previously, all tracing libraries were injected, even if only one library was configured in `libVersions`. Now, only the libraries a user configures are injected.
Updated docs to reflect the new functionality. Additionally, moved container registry table from Injecting libraries locally so users can find the latest versions better.
=> Update Specifying library versions section for k8s

local/bin/py/build/actions/pull_and_push_folder.py, local/bin/py/build/update_pre_build.py
Local builds should always fail when an error is encountered while processing a single-sourced file. For the `pull_and_push_folder` action, we should always know which file the build failed on.
It sometimes takes us a while to chase down broken builds because:
- The local build doesn't always behave the same way as the prod build. It gives warnings instead of errors, which are more difficult to spot, and doesn't fail in the same way as the prod build
- It's not always clear which file the build is hanging on
=> (docs-build) Improve docs troubleshooting feedback

.github/CODEOWNERS
The current codeowners don't match exactly what we want: I opened https://github.com/DataDog/documentation/pull/22369 which does not request a review from `ci-app-backend`. I am not sure why, though I don't think we should overcomplicate our codeowners file and we should simply match all files in subdirectories. In addition, this makes it consistent with the rest of the codeowners file.
=> Update CODEOWNERS for Software delivery

content/en/continuous_integration/pipelines/_index.md, content/en/continuous_integration/pipelines/awscodepipeline.md
Add documentation for the running pipelines feature for AWS CodePipeline
=> [CIVIS-9536] Add documentation for AWS CodePipelines running pipelines

content/en/service_management/events/guides/email.md
Events API emails is unsupported on GovCloud (US1-FED)
=> (DOCS-7297)(Srvce-mngmnt) Clarify support

content/en/agent/basic_agent_usage/redhat.md
Updates the Basic Agent Usage for RHEL page with the deprecation of v6 for Agent versions 7.52.0 and above: https://github.com/DataDog/datadog-agent/releases/tag/7.52.0
As a result, I added a heading and slightly rearranged the formatting for clarity
=> Update Basic Agent Usage for RHEL page with deprecation

content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md
The `DdSdkReactNativeConfiguration` has been deprecated in favour of `DatadogProviderConfiguration`, this should be reflected in the docs.
=> Replace old configuration class by new one in RN docs

README.md
Moves the local branch step down in the README, as it's an optional step for most internal contributors and is likely to trip some people up. Also shuffled/reworded some of the other steps.
=> (maint) Move local branch language in README

content/en/integrations/guide/source-code-integration.md
Minor improvements on the SCI setup instructions:
- Move the GitLab tab in second position, so that "Other Git providers" comes last
- Add the "Validation" section in the GitLab tab as well, since it's relevant as well
- Make wording / spacing consistent with the "Other Git providers" tab
- Add the warning about self-managed instances, which require contacting support to enable
- Update the repository URL in the example to something that isn't GitHub, since the prefered way for GitHub is to use the GitHub Apps integration
=> [Source Code Integration] Improvements to GitLab tab

content/en/agent/configuration/network.md
Add the contimage-intake.datadoghq.com & contlcycle-intake.datadoghq.com endpoints to the [Network Traffic](https://docs.datadoghq.com/agent/configuration/network/?tab=agentv6v7) public documentation.
=> [PROCS-3870] Add contimage and contlcycle endpoints to Network Traffic doc

content/en/opentelemetry/ingestion_sampling_with_opentelemetry.md
Update content on Ingestion Sampling page to accurately state that trace metrics are computed in the Datadog Connector, not the Exporter.
Link to migration guide just to be safe.
=> Update Ingestion Sampling Page to Reflect Datadog Connector Change

content/en/dashboards/functions/rollup.md
We've updated the default interval logic for time series graphs, including lowering the minimum intervals substantially. The docs don't yet reflect these changes, so this PR updates them to describe the system more accurately and in a bit more detail
=> Update rollup.md to include the updates to interval logic and minimum interval logic

assets/scripts/components/dd-browser-logs-rum.js
adds `Partitioned` attribute when generating `_dd_device_id` cookie.   this is needed ahead of the end of 3rd party cookies due to the presence of `Same-Site=None` attribute
https://datadoghq.atlassian.net/browse/WEB-4682
https://docs-staging.datadoghq.com/brian.deutsch/web-4682-device-id-partitioned/
- no console errors present.
=> [web-4682] partitioned `device_id` cookie

content/en/integrations/guide/_index.md, content/en/integrations/guide/deprecated-oracle-integration.md
The Oracle Python integration will be deprecated in the next Agent release. This document preserves the configuration steps for the older Agent releases.
=> Deprecating Oracle Python integration (DBMON-3776)

config/_default/menus/menus.en.yaml
Corrects the generate metrics page URL so that the page loads correctly.
=> Fix generate metrics url

content/en/logs/guide/sending-events-and-logs-to-datadog-with-amazon-eventbridge-api-destinations.md
Adds a note that Amazon EventBridge is unsupported on GovCloud. Request from support. Complement to https://github.com/DataDog/dogweb/pull/116270
=> DOCS-7478: add gov region warning to logs guide

content/en/opentelemetry/integrations/runtime_metrics/java.md
Add documentation for runtime metric mappings introduced in v2.0.0 of OpenTelemetry Java: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0
=> Add stable OTel JVM metric mappings

content/en/real_user_monitoring/browser/advanced_configuration.md
- Adds a link to the RUM Data Security page from the Browser Advanced Configuration page, as per request in [DOCS-7428](https://datadoghq.atlassian.net/browse/DOCS-7428)
[DOCS-7428]: https://datadoghq.atlassian.net/browse/DOCS-7428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Link to data security from browser adv config

content/en/code_analysis/software_composition_analysis/_index.md, content/en/code_analysis/static_analysis/_index.md
Replaces "lens" with "tabs" to describe the in-app navigation for Software Delivery.
Raised in [#docs-backroom](https://dd.slack.com/archives/GGHR55PNV/p1711684863189569) on Slack.
=> Code Analysis Doc Edit

content/en/tracing/trace_collection/compatibility/php.md
Laravel 11.X compatibility is now tested through DataDog/dd-trace-php#2606.
This PR updates the public doc accordingly.
=> docs: Add Laravel 11.x support

content/en/tracing/trace_collection/library_config/php.md
Motivation: [This Slack Message](https://dd.slack.com/archives/C4WC8C39Q/p1711979945661959)
This PR adds the missing PHP configuration option `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED` to the public doc. It reuses Java's description.
=> docs(php): Add `DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED` documentation

content/en/account_management/audit_trail/events.md
Adds an audit event for a viewed session replay.
[DOCS-6935](https://datadoghq.atlassian.net/browse/DOCS-6935)
[DOCS-6935]: https://datadoghq.atlassian.net/browse/DOCS-6935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-6935] Add audit event for a viewed session replay

content/en/continuous_integration/pipelines/_index.md
We have several reports from customers finding this table confusing.
This PR does three things:
- fixing the CircleCI terminology: the pipeline level on Datadog maps to workflows in CircleCI, the job level maps to job in CircleCI, and we don't support steps in Datadog for this provider.
- Deleting useless rows: some providers don't have stages. I don't think that this is useful to show that we support stages in Datadog (we have a level for that) though this concept does not exist in the provider. We were showing "Stage" in the Datadog column and empty in the provider column.
- Replaces _\A pipeline's step granularity is not available in Datadog._ by a row in the corresponding step level for the provider, indicating that this is not available in Datadog.
=> [CIVIS] fix CI providers terminology

content/en/real_user_monitoring/platform/connect_rum_and_traces.md
Fixing the wrong iOS code snippets in [Connect RUM and Traces](https://docs.datadoghq.com/real_user_monitoring/platform/connect_rum_and_traces/?tab=iosrum). They referenced `Trace` module, instead of `RUM`.
=> RUM-3834 Fix iOS snippets in `connect_rum_and_traces.md`

content/en/intelligent_test_runner/setup/python.md, content/en/tests/setup/python.md
Adds instructions to install the `coverage` package when setting up the Intelligent Test Runner for Python.
This also moves the "known limitations" in the test visibility setup page for Python to their own level-2 header for better visibility. Prior to this, the known limitations seemed easy to miss in the documentation (since they didn't appear in the "On this page" section).
=> Intelligent Test Runner: add installing coverage package to Python setup instructions

content/en/agent/guide/linux-key-rotation-2024.md
Change the suggested command for red had-like systems. The current one was not ok on `amazonlinux2`, see [customer request](https://datadog.zendesk.com/agent/tickets/1631027)
Tested on RHEL, CentOS, SUSE, fedora, rockylinux and amazonlinux
Thanks to @mirzanurkic-dd
=> fix(linux key rotation): Use a more direct command that works on every system

content/en/tracing/trace_collection/compatibility/java.md
DOCS-7386
- Java tracer support for GraalVM Native Image is coming out of beta.
- Documenting this on Java Compatibility page after discussion with @tushar-datadog .
=> Document GraalVM Native Image support for Java

content/en/service_management/app_builder/_index.md, content/en/service_management/app_builder/auth.md, content/en/service_management/app_builder/build.md, content/en/service_management/app_builder/embedded_apps.md
Adds a note to all App Builder pages saying that App Builder is not available for US1-FED
=> (DOCS-7499) Add note saying App Builder is not available in US1-FED

content/en/account_management/billing/usage_metrics.md
The previous language is incorrect. This metric does not represent **all** indexed spans. 
`datadog.estimated_usage.apm.indexed_spans` only correlates to spans indexed by tag-based retention filters.
For further details please see the following:
- Customer ticket about this issue: https://datadog.zendesk.com/agent/tickets/1624809
- Slack thread:  https://dd.slack.com/archives/C4WC8C39Q/p1712186448749259
=> Update description for indexed_spans usage

go.sum
Too many new lines at the end of go.sum is causing some strange hugo errors. This PR fixes this.
=> remove newlines to fix go.sum issues

content/en/profiler/enabling/php.md
The PHP Profiler in version `0.99.0+` supports PHP ZTS builds
=> Add note about PHP ZTS support

config/_default/menus/menus.en.yaml, content/en/account_management/teams/_index.md, content/en/account_management/teams/manage.md
Follow-on PR to https://github.com/DataDog/documentation/pull/22549 and number 2 of 3 PRs for DOCS-7431 to document the new Teams UI.
- This PR creates a new subpage, Team Management.
- Creates a link to Team Management from the Teams page.
- Moves team management content to the new page
- Renumbers the links.
The new Teams UI has more features than the previous version. Adding all of the features to the existing page would make it too long. This PR creates a new Team Management subpage with instructions for managing an individual team. Documentation for managing Teams in general stays on the overview page.
A follow-on PR to this one will document the new customization features on the team detail page.
=> Create Team Management subpage

content/en/real_user_monitoring/error_tracking/browser.md
Adds `report` type errors to the ones tracked by Error Tracking.
Error Tracking also tracks these, but they are not mentioned here.
Addition to https://github.com/DataDog/documentation/pull/22501
=> Add "report" errors to types tracked for Error Tracking

content/en/tracing/trace_collection/compatibility/php.md
Support for CakePHP 3+ has been added and tested with DataDog/dd-trace-php#2618
Support for CodeIgniter 3 has been added and tested with DataDog/dd-trace-php#2515
=> docs: Update CakePHP & CodeIgniter support

content/en/security/cloud_security_management/setup/csm_enterprise/agent/linux.md
Found a minor typo on one of our public docs: [Enabling CSM Enterprise on Linux](https://docs.datadoghq.com/security/cloud_security_management/setup/csm_enterprise/agent/linux). This PR removes the second `and`
=> Fix typo in "Enabling CSM Enterprise on Linux"

.github/workflows/merge_label_check.yml
Adds a check that fails if the "Do Not Merge" label is present. This is part of an ongoing rollout of merge safety features for the docs repo.
Demo PR that you can label/unlabel: [Demo PR](https://github.com/DataDog/jen.gilbert-actions-sandbox/pull/63)
=> Add merge label check

content/en/real_user_monitoring/_index.md, content/en/real_user_monitoring/browser/monitoring_page_performance.md, content/en/real_user_monitoring/explorer/_index.md, content/en/real_user_monitoring/guide/remotely-configure-rum-using-launchdarkly.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/mobile_vitals/_index.md
As per discussion with @MaelNamNam to improve accuracy of the terms used - in some cases, we don't offer metrics OOTB in RUM, so we are technically referring to custom metrics
- Removes mentions of "metrics" in RUM docs and replaces them with "telemetry" or "data points" unless we're actually talking about metrics
=> [RUM] Replace mentions of metrics with telemetry

content/en/synthetics/apm/_index.md
Add the support of W3C Trace Context to the Synthetic APM page; it was added months ago and we missed this update.
Changes:
- Add tabs to reflect the two traces we now support
- Add the support of W3C Trace Context to the page.
=> [SYNTH-13322] Add support of W3C Trace Context to the Synthetic APM page

content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Updates env var assignment examples for client libraries.  `@env` was probably taken from the agent config and incorrectly applied to the tracer lib doc portion also.
- replaces `@env` with `export`
- replaces `@env` with `set` for .NET since it's probably used on Windows.
- adds single quotes around JSON as needed otherwise assignment fails in bash, zsh, etc.  Single quotes aren't needed in Windows CMD shell. 
=> update @env to export

layouts/_default/list.redirects.txt
- Adds any file with `external_redirect` frontmatter to the `redirects.txt` file that is generated at build time to leverage our post deploy redirect meta job in S3. This will prevent the momentary content flash that currently happens when `external_redirect` is used in `_index.md` files.
https://datadoghq.atlassian.net/browse/WEB-4759
https://docs.datadoghq.com/api/ - current `external_redirect` (there is usually a flash of content before the page redirects correctly)
https://docs-staging.datadoghq.com/devin.ford/WEB-4759/api - shouldn't see a page flash on the redirect here
Another good example is the `/meta` route
=> WEB-4759 | Add external_redirects to redirects.txt

content/en/database_monitoring/setup_oracle/autonomous_database.md, content/en/database_monitoring/setup_oracle/exadata.md, content/en/database_monitoring/setup_oracle/rac.md, content/en/database_monitoring/setup_oracle/rds.md, content/en/database_monitoring/setup_oracle/selfhosted.md, content/en/database_monitoring/setup_oracle/troubleshooting.md, layouts/shortcodes/dbm-supported-oracle-agent-version.md
Fix references to old links, configuration directory, and minimal supported release.
=> Changes for renamed Oracle check (DBMON-3903)

content/en/metrics/open_telemetry/otlp_metric_types.md
Documents that OTLP histograms with a count of 0 are not sent. Relates to DataDog/opentelemetry-mapping-go/pull/317
=> [opentelemetry] Document that we don't send histograms with a count of 0

content/fr/synthetics/browser_tests/_index.md
- Fix typo: Cookies instead of Cookirs
[ x ] Please merge after reviewing
=> Fix typo in word cookies

layouts/static-analysis/list.html
uses the default C# (`csharp`) icon for the **Languages** filter on page load instead of the `NET` icon.
preview: 
- loading this page should add the `C#` filter selection to the `Languages` filter toggler. The icon to the left of `C#` should match the `C#` results displayed under the `Search` bar.
- https://docs-staging.datadoghq.com/stefon.simmons/fix-csharp-icon-static-analysis/code_analysis/static_analysis_rules/?languages=CSharp
- loading this page should not add any selections. Select `C#` from the `Languages` filter. Refresh the page. the icon should match the  results for `C#`.
- https://docs-staging.datadoghq.com/stefon.simmons/fix-csharp-icon-static-analysis/code_analysis/static_analysis_rules/
=> use csharp icon for `C#` language filter

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
Corrects operator YAML indentation of `features`, I stumbled on this during local setup.
=> Fix operator yaml indentation

.github/workflows/validate_filenames.yml
Borrowed from the web team. Enforces standardization of filenames so we don't run into Git weirdness with capital letters.
=> (maint) Add GitHub action to validate filenames

content/en/continuous_integration/pipelines/gitlab.md
GitLab deprecated the `runner.tags` `config.toml` section in the 15.8 release, changes the documentation to reflect this.
- Changelog: https://docs.gitlab.com/ee/update/deprecations.html#registration-tokens-and-server-side-runner-arguments-in-gitlab-runner-register-command
- Design specification: https://gitlab.com/gitlab-org/gitlab/-/issues/380872
=> Update according to GitLab deprecation

content/en/data_security/real_user_monitoring.md, content/en/getting_started/site/_index.md, content/en/real_user_monitoring/browser/_index.md
- Adds a graf about shared responsibility between Datadog and developers as a response to the incident described in [RUM-4002](https://datadoghq.atlassian.net/browse/RUM-4002) to the RUM Data Security page
- References this graf in each snippet in the Browser setup page
- Adds a similar graf to the Getting Started: Sites page
The legal team needs to review this before it gets merged.
[RUM-4002]: https://datadoghq.atlassian.net/browse/RUM-4002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Shared Responsibility graf for RUM and Sites Getting Started

content/en/security/audit_trail.md, content/en/security/detection_rules/_index.md, content/en/security/notifications/_index.md, content/en/security/notifications/rules.md, content/en/security/notifications/variables.md, content/en/security/security_inbox.md, content/en/security/threat_intelligence.md
DOCS-7421. Adds product identifier tags to Security Overview docs.
=> DOCS-7421: Add product identifier tags to Security Overview docs

content/en/security/application_security/enabling/single_step/code_security.md, content/en/security/application_security/enabling/tracing_libraries/code_security/dotnet.md, content/en/security/application_security/enabling/tracing_libraries/code_security/java.md, content/en/security/application_security/enabling/tracing_libraries/code_security/nodejs.md
This PR removes duplicated 1 click enablement callouts on the Code Security pages for ASM and additionally updates the supported languages for code security for single step instrumentation
=> updating code security supported languages and duplicate callout

config/_default/menus/menus.en.yaml, content/en/code_analysis/troubleshooting/_index.md
Adds a Troubleshooting page to the Code Analysis section.
=> DOCS-7655 Adds Code Analysis Troubleshooting Doc Page

content/en/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/_index.md
We had a few users confused about whether they could use regular expressions and if subdomains were being matched with webview tracking.
Looking at the [browser SDK implementation](https://github.com/DataDog/browser-sdk/blob/fd44db8f0a9e6b0e08396deb182eebf69a3ef4d3/packages/core/src/transport/eventBridge.ts#L54), we allow subdomains but not regex.
=> Specify hosts pattern matching for webview tracking

content/en/continuous_integration/pipelines/gitlab.md
We had several customers reaching out because they cannot see GitLab logs after enabling the feature. This is because:
- either they do not realise that their storage DNS must resolve to an IP
- or that they do not allowed access from outside to their storage.
This PR clarifies that, by:
- changing the "note" to a "warning"
- linking to the GitLab `endpoint` doc so that people are aware this endpoint should resolve
- adding the IP range that Datadog servers will be using so that people can protect their storage behind that list.
=> [CIVIS] improve GitLab logs collection warning

content/en/tests/_index.md, content/en/tests/setup/javascript.md
* Remove "Git metadata upload" section, as it's not there for languages other than JS and it adds confusion. 
* Remove unnecessary Intelligent Test Runner reference.
* Remove `(except for Ruby)`, since that's no longer the case.
=> [ci-visibility] Clarify git upload and other small improvements

content/en/service_management/app_builder/embedded_apps.md
Small PR to update the code snippet and move the `dashboard` context variable under a `global` namespace.
=> Update embedded_apps.md to have correct code snippet

content/en/cloud_cost_management/container_cost_allocation.md
Azure container costs are now in public beta, no need to contact support anymore to access it.
=> Update Azure container costs as it is no longer in private beta

content/en/glossary/terms/absolute_change.md, content/en/glossary/terms/baseline_mean.md, content/en/glossary/terms/baseline_standard_deviation.md, content/en/glossary/terms/performance_regression_(Test Visibility).md, content/en/glossary/terms/relative_change.md, content/en/glossary/terms/standard_deviation_change.md, content/en/glossary/terms/test_duration.md, content/en/glossary/terms/test_regression.md, content/en/glossary/terms/test_run.md, content/en/glossary/terms/test_service.md, content/en/glossary/terms/test_suite.md
Updates some existing Test Visibility terms to clarify they are for Test Visibility and adds seven new terms from the CI Tests dashboard performance regression section.
=> DOCS-7683 Adds CI Test Visibility Terminology to the Docs Glossary

content/en/account_management/billing/_index.md
Changes the text of a status from "???" to "INACTIVE." As verified in the UI, the possible states for a host in the infrastructure list are "ACTIVE" and "INACTIVE." Noticed and pointed out by Alla Igityan, a sales engineer.
=> On billing page, correct host status from ??? to INACTIVE

assets/styles/pages/_glossary.scss, layouts/glossary/list.html
unstick the glossary filter buttons section on scroll
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4792
preview: https://docs-staging.datadoghq.com/stefon.simmons/adjust-glossary-filter-section/glossary/
=> unstick glossary filters - [WEB-4792]

content/en/logs/log_collection/java.md
* Currently only have a file example
* K8s/containers more likely to use console output
Currently there's no specific example of how to do console/stdout output for Java logs in the docs, only file. In a K8s and container world, we're more likely to use console output and it was a bit of trial and error for me to figure it out, it'd be nice to have that directly in the docs. 
I didnt do an example for Tinylog because it doesn't seem to have a non-file based json formatter
=> adds a console output example for Java

content/en/security/suppressions.md
Remove the suppressions migration section after auto-migration is complete
=> Update suppressions.md after migration of legacy suppressions

content/en/profiler/enabling/java.md
Adding a mention that the live-heap is in alpha and should not be enabled in production
=> Java live-heap alpha mention addition

content/en/profiler/enabling/java.md
This PR fixes a couple of code blocks on the Java profiler documentation page.
Before:
After:
=> Code blocks fix Java profiler

content/en/tracing/guide/trace_ingestion_volume_control.md
Removed from code in https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/8a8d576674f50a9ad84bacf6760c2777876616aa
=> Remove deprecated Datadog Processor mention

content/en/code_analysis/static_analysis/_index.md
Adds information about an additional syntax/capability for the no-dd-sa comment for ignoring violations
=> Add no-dd-sa:<rule-name> example

config/_default/menus/main.en.yaml, data/partials/home.yaml
Ideally we would like to use the `Flaky Test` icon in Druids for the Test Visibility docs, but that is not available in `websites-modules` yet. While we wait for a custom icon for Test Visibility, replacing it with the CI Visibility icon (as ITR should have one standalone icon).
=> CMTY-47 Remove ITR Icon for Test Visibility Documentation

content/en/universal_service_monitoring/setup.md
Adds documentation to enable USM to capture HTTP/2 and gRPC traffic.
=> Add http2 monitoring documentation

content/en/integrations/guide/add-event-log-files-to-the-win32-ntlogevent-wmi-class.md
Removes backticks from a title, because
- it doesn't render properly (it renders as backticks; it does not render a `<code>` style)
- in some languages, `Win32_NTLogEvent` is how you start the sentence, and a backtick character at the beginning of a line appears to cause issues.
=> remove backticks from title

content/en/serverless/aws_lambda/profiling.md
Update the table since it is misleading. The column for ‘minimum tracer version’ is referring to the runtime library layer. It should refer versions of the tracing library.
=> Update profiling.md table

content/en/tracing/trace_collection/custom_instrumentation/java/dd-api.md
https://github.com/DataDog/documentation/issues/22774
- Document `noParent` argument for Java trace annotations.
- Clean up section to better adhere to our style.
=> Add noParent argument for Java trace annotations

assets/styles/pages/_global.scss
Fixes over-padding of definition list items.
Tested locally; looks good at any point in the list (first, middle, last) to me.
=> Fixes over-padding of definition list items

content/en/database_monitoring/guide/aurora_autodiscovery.md
The 7.53 version of the agent has been released, so customers no longer need to install a beta version
=> Update minimum agent version for Aurora auto-discovery feature

content/en/tests/setup/junit_xml.md
JUnit XML was the only technology for test visibility that was showing this info about git metadata upload, and we already have this information in another section: https://docs.datadoghq.com/tests/#use-ci-tests-data.
=> [test-visibility] Remove unnecessary paragraph

content/en/getting_started/tagging/unified_service_tagging.md, content/en/tracing/guide/setting_up_APM_with_cpp.md, content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/cpp.md, content/en/tracing/trace_collection/compatibility/cpp.md, content/en/tracing/trace_collection/custom_instrumentation/cpp/dd-api.md, content/en/tracing/trace_collection/library_config/cpp.md, content/en/tracing/trace_collection/runtime_config/_index.md, content/en/tracing/trace_collection/trace_context_propagation/cpp.md, content/en/tracing/trace_pipeline/ingestion_mechanisms.md, data/libraries.yaml
Historically, the C++ implementation was based on OpenTracing. Since late 2022, we developed our Datadog tracer for C++ that are now in use for all our proxy integrations. The goal of this PR is to replace any mention and code related to [dd-opentracing-cpp](https://github.com/DataDog/dd-opentracing-cpp) to [dd-trace-cpp](https://github.com/DataDog/dd-trace-cpp).
🚀
=> Update C++ documentations

translate.yaml
https://datadoghq.atlassian.net/browse/WEB-4831
@hestonhoffman confirming the two exceptions under `content/en/**/faq` can be safely removed: https://dd.slack.com/archives/C0DESMBQU/p1714497363983109
no UI changes
=> [web-4831] ignoring all faq paths from translation pipeline

data/libraries.yaml
Adds a new subcategory for Rust under [API and DogStatsD client libraries](https://docs.datadoghq.com/developers/community/libraries/#api-and-dogstatsd-client-libraries), with two initial entries for `cadence` and `metrics-exporter-statsd`.
N/A
=> Update metrics libraries for Rust.

content/en/tracing/trace_explorer/trace_view.md
Fix for https://datadoghq.atlassian.net/browse/DOCS-7127. Added Code Hotspots tab to Trace View because that was missing.
=> Add Code Hotspots tab to Trace View

content/en/tracing/metrics/runtime_metrics/java.md
This had a link to `https://github.com/DataDog/integrations-core/search?q=jmx_metrics&unscoped_q=jmx_metrics`, and although `integrations-core` is a public repo, search is restricted. Removing this link as it won't work for anyone external.
=> DOCS-7643: Remove non-public link

content/en/security/cloud_security_management/setup/_index.md, content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md
Adds OS compatibility matrix. See DOCS-7786 for more details.
=> DOCS-7786: Add OS compatibility matrix for CSM Vulnerabilities

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/expo.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/roku.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/unity.md
Setting the sampling rate for RUM sessions is very important to customers and should not be hidden within advanced configuration instructions. The instructions have been moved or added to all setup pages as per [DOCS-7658](https://datadoghq.atlassian.net/browse/DOCS-7658).
Should be reviewed by @MaelNamNam or at least one person on the rum-mobile team before merging.
[DOCS-7658]: https://datadoghq.atlassian.net/browse/DOCS-7658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add sample RUM session info for all frameworks

content/en/tests/code_coverage.md
Swap ordering of the language tabs for Code Coverage. 
Requested by Fernando on Slack.
=> Code Coverage Edit

assets/styles/vendor/_chroma-styles.scss
- Unindented lines are getting overlapped by the line highlight style.
- Tweak the margins and position to fix this.
Example from @cswatt :
Link to example that's broken now: https://docs.datadoghq.com/containers/kubernetes/installation/?tab=helm#container-registries.
^ Verify this looks ok now in the preview build. Here's what it looks like locally for me:
=> Fix Code Block Highlight

layouts/partials/integration-labels/integration-labels.html
adds support to avoid rendering `integration_version` in specific integrations
jira: https://datadoghq.atlassian.net/browse/WEB-4787
`integration_version` label is not rendered in the `oracle` integration page: https://docs-staging.datadoghq.com/brian.deutsch/web-4787-remove-oracle-int-version-label/integrations/oracle/?tab=linux
label still appears on other pages for example: https://docs-staging.datadoghq.com/brian.deutsch/web-4787-remove-oracle-int-version-label/integrations/active_directory/
=> support blocklist to not render integration version

content/en/tracing/guide/ignoring_apm_resources.md
- properly differentiates between the client and server http blocklists
- they behave differently and really cannot be treated the same
- the current example is wrong and confusing
=> fix ambiguous http blocklist syntax

content/en/cloud_cost_management/container_cost_allocation.md
Azure container costs are now GA, we dont need to show the beta label anymore
=> Remove beta label from Azure container costs in CCM

content/en/infrastructure/containers/container_images.md
The Datadog Agent has 2 types of Container Image Collection:
- Image Metadata collection, enabled by default
- SBOM collection, not enabled by default and part of the CSM Pro and Enterprise plan
In order to prevent users to accidentally enable the SBOM collection, this PR splits the enablement instructions for each one of them.
=> [Container Images] Split instructions for Container Image and SBOM collection

content/en/agent/configuration/dual-shipping.md
…cription
DD agent doesn't support dual shipping data to "other internal infrastructure" other than another DD organizations. This has been quite confusing to our customers and sets the wrong expectations.
=> Update dual-shipping.md to remove "other internal infrastructure"

content/en/tracing/trace_collection/library_injection_local.md
Remove instructions for installing APM single step beta libraries with deb/rpm commands. Those instructions will not be supported soon.
=> remove_ssi_instructions

content/en/cloudcraft/getting-started/_index.md, content/en/cloudcraft/getting-started/activate-aws-marketplace-cloudcraft-subscription.md
Add a new article to the Cloudcraft documentation describing how a customer can activate their Cloudcraft subscription bought through the AWS Marketplace.
Please wait until the Cloudcraft team has reviewed the content before going ahead with the review and merging of the article.
=> [CLOUDCRAFT-389] Activate your AWS Marketplace Cloudcraft subscription

.gitlab-ci.yml
There was a misconfiguration with the `notranslate` manual Gitlab job which is preventing pipelines from moving past `post-deploy` stage. This should unblock.
=> Remove notranslate manual job

content/en/security/application_security/enabling/compatibility/dotnet.md, content/en/security/application_security/enabling/compatibility/go.md, content/en/security/application_security/enabling/compatibility/java.md, content/en/security/application_security/enabling/compatibility/nodejs.md, content/en/security/application_security/enabling/compatibility/php.md, content/en/security/application_security/enabling/compatibility/python.md, content/en/security/application_security/enabling/compatibility/ruby.md
Renames Vulnerability Management for OSS support to Software Composition Analysis.
=> Rename OSS to SCA

content/en/real_user_monitoring/session_replay/browser/_index.md
Added info about how to disable session replay for sdks older than v5. A customer just wasn't able to find this info on our docs.
Got info from:
https://docs.datadoghq.com/real_user_monitoring/guide/browser-sdk-upgrade/#sdk-initialization-parameters
=> Add info about how to disable session replay for older sdks

local/bin/py/add_notranslate_tag.py
In order for the Transifex workflow to trigger, it has to detect that a _new_ `notranslate` tag has been added to a record. This PR updates are script to clear out existing tags on the targeted strings, and then readd `notranslate`
=> Update notranslate script

data/partials/home.ja.yaml
=> (maint) Fix incorrect link on JA homepage

content/en/data_jobs/kubernetes.md
Fix incorrectly formatted yaml file in data_jobs/kubernetes.md.
The incorrectly formatted yaml will not correctly set `features.admissionController.enabled` to `true` and `features.admissionController.mutateUnlabelled` to `false` as intended by the documentation.
=> fix incorrectly formated yaml file in data_jobs/kubernetes.md

Makefile
Bumps the assetlib library to the latest version. Mostly includes updates to the Manifest serializer for newer fields, and removal of Deprecated Classifier tags since we removed them from all individual integrations. 
https://docs-staging.datadoghq.com/nick/bump_assetlib/integrations/
=> [ECOS-141] Bump assetlib to latest version

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md, content/en/tracing/trace_collection/automatic_instrumentation/ssi-0-13-1.md
=> Add note about Single Step Instrumentation version

go.mod, go.sum
`redis-enterprise` tile not surfacing on /integrations
https://docs-staging.datadoghq.com/brian.deutsch/websites-source-mod-bump/integrations
locally:
=> bump sources version

content/en/tests/troubleshooting/_index.md
There was a missing link in the docs. This PR fixes it.
=> [CIVIS] Fixing missing link

.gitlab-ci.yml
Bump job timeout to 4 hours:
Timed out at 2 hours
https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/507843844
=> Increase notranslate job timeout

layouts/glossary/list.html
translations of `core_product` coming from Transifex is breaking builds.   this is a bandaid to allow builds to pass as we work towards a better long term solution of the core problem with translated keys.
jira https://datadoghq.atlassian.net/browse/WEB-4887
translations pipeline passing now https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/509011251
https://docs-staging.datadoghq.com/brian.deutsch/glossary-en-sot/glossary (nothing changed here)
=> [WEB-4487] filter out invalid core products but allow build to pass

content/en/observability_pipelines/archive_logs/datadog_agent.md, content/en/observability_pipelines/archive_logs/splunk_hec.md, content/en/observability_pipelines/archive_logs/splunk_tcp.md, content/en/observability_pipelines/archive_logs/sumo_logic_hosted_collector.md, content/en/observability_pipelines/dual_ship_logs/datadog_agent.md, content/en/observability_pipelines/dual_ship_logs/splunk_hec.md, content/en/observability_pipelines/dual_ship_logs/splunk_tcp.md, content/en/observability_pipelines/dual_ship_logs/sumo_logic_hosted_collector.md, content/en/observability_pipelines/log_volume_control/splunk_hec.md, content/en/observability_pipelines/log_volume_control/splunk_tcp.md, content/en/observability_pipelines/log_volume_control/sumo_logic_hosted_collector.md, content/en/observability_pipelines/sensitive_data_redaction/datadog_agent.md, content/en/observability_pipelines/sensitive_data_redaction/splunk_hec.md, content/en/observability_pipelines/sensitive_data_redaction/splunk_tcp.md, content/en/observability_pipelines/sensitive_data_redaction/sumo_logic_hosted_collector.md, content/en/observability_pipelines/split_logs/datadog_agent.md, content/en/observability_pipelines/split_logs/splunk_hec.md, content/en/observability_pipelines/split_logs/splunk_tcp.md, content/en/observability_pipelines/split_logs/sumo_logic_hosted_collector.md, layouts/shortcodes/observability_pipelines/processors/add_processors.md, layouts/shortcodes/observability_pipelines/processors/add_processors_sds.md
- Move image from the parent page to general reuse shortcode.
- Add a new processor shortcode for SDS use case.
=> Add image to shortcode

content/en/containers/kubernetes/log.md
Revamp the troubleshooting section for Kubernetes Log Collection documentation to clear up the confusion between DD_LOGS_CONFIG_TAGGER_WARMUP_DURATION and DD_LOGS_CONFIG_EXPECTED_TAGS_DURATION
Revamp the troubleshooting section for Kubernetes Log Collection documentation to clear up the confusion between DD_LOGS_CONFIG_TAGGER_WARMUP_DURATION and DD_LOGS_CONFIG_EXPECTED_TAGS_DURATION
We've seen frequent cases of these issues and want to allow customers to use these configurations appropriately.
=> [DOCS-7911] Update log.md

content/en/database_monitoring/setup_mysql/aurora.md, content/en/database_monitoring/setup_postgres/aurora.md
Adds direct note in setup docs on how to use the new auto discovery feature in the agent
=> Add direct link to auto discovery docs in mysql/postgres aurora setup

content/en/opentelemetry/schema_semantics/service_entry_spans.md
Add minimum version requirement for feature and fix typo.
=> Update OTel service entry span mapping docs

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
There's an extra "```swift" at the top of this docs page that needs to be removed.
=> Remove duplicate swift markdown syntax

content/en/account_management/billing/custom_metrics.md, content/en/metrics/custom_metrics.md
The standard integrations list is in the billing doc which doesn't make sense it should be in the main doc that lists all the other metric submission methods.
=> Migrate Standard integrations section

content/en/real_user_monitoring/platform/connect_rum_and_traces.md, content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md
This PR updates Java code snippets for `DatadogInterceptor` and `TracingInterceptor` classes to align their current state (previous snippets were wrong as-is causing confusion when customers used them).
Also this PR changes snippet type from `java` to `kotlin` where is was set in a wrong way.
=> Android SDK: Update Java code snippets for `DatadogInterceptor` and `TracingInterceptor`

content/en/service_management/app_builder/components.md
Fixes a link that is currently pointing to Workflows, when it should be pointing to App Builder.
=> Fix link copy-paste error

content/en/real_user_monitoring/feature_flag_tracking/_index.md
This commit removes the  beta status of Feature Flag Tracking.
=> Remove "beta" from Feature Flag Tracking

content/en/real_user_monitoring/browser/advanced_configuration.md, content/en/real_user_monitoring/browser/data_collected.md, content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
This commit removes the beta status of Feature Flag Tracking including the callouts.
=>  Remove "beta" callouts from Feature Flag Tracking

content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Add .NET Framework 4.8.1 to the list of supported runtimes.
[DOCS-7949](https://datadoghq.atlassian.net/browse/DOCS-7949)
[DOCS-7949]: https://datadoghq.atlassian.net/browse/DOCS-7949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [APM > .NET Tracer] Add .NET 4.8.1 to list of supported runtimes

config/_default/menus/main.en.yaml, content/en/observability_pipelines/_index.md, content/en/observability_pipelines/setup_opw.md
Adds a new OP doc on setting up env vars.
[DOCS-7840](https://datadoghq.atlassian.net/browse/DOCS-7840)
[DOCS-7840]: https://datadoghq.atlassian.net/browse/DOCS-7840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7840] Add OP setup/bootstrap doc

content/en/real_user_monitoring/guide/browser-sdk-upgrade.md, content/en/real_user_monitoring/platform/connect_rum_and_traces.md
- Adds details about the traceparent header as per customer feedback in [DOCS-7869](https://datadoghq.atlassian.net/browse/DOCS-7869).
- Adds the word "the" to a sentence
[DOCS-7869]: https://datadoghq.atlassian.net/browse/DOCS-7869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add details about the traceparent header

.gitlab-ci.yml
fix typo for activating the virtualenv in the job
=> fixes typo

content/en/containers/amazon_ecs/_index.md
Bump latest FIPS Proxy version in the ECS documenation
https://docs-staging.datadoghq.com/nicolas.guerguadj/ecs-fips-1.1.2/containers/amazon_ecs/?tab=awscli&site=gov#fips-proxy-for-govcloud-environments
=> Update FIPS proxy version to 1.1.2

content/en/coscreen/_index.md
CoScreen's shared terminal is no longer called CoTerm. Changing docs to give it a generic name, "shared terminal" or "collaborative terminal". Removing screenshot of onboarding dialog that no longer appears. Also removing the note that the terminal closes when unshared, which is also no longer true.
=> DOCS-7919 - Rename CoTerm

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
While testing functionality for another guide, I noticed that the Docker command is:
- Missing a backslash.
- Has a mismatched API Key placeholder.
=> Fix Docker command

content/en/tracing/trace_collection/library_config/php.md
The correct term is directive for www.conf
=> docs: typo directive instead of directory

content/en/opentelemetry/schema_semantics/semantic_mapping.md
Adds a new section on how to configure resource attributes as tags setting.
=> [content/en/opentelemetry/schema_semantics] Document metrics mapping of schema semantics

content/en/integrations/guide/application-monitoring-vmware-tanzu.md
Removes Step number 5 from the installation steps of the Application Monitoring Tile.
This step is only valid for the cluster monitoring tile, for the application monitoring tile the Datadog API Key is injected for each application independently either via their application manifest, env variable, etc..
=> Fix Installation Steps for the VMWare Tanzu Application Monitoring Tile

content/en/containers/kubernetes/distributions.md
Fixes CONTINT-4015
Clarifies the behavior for AKS when `spec.nodeName` is set. Makes it clearer for users that they should not be setting both Kubelet host and `tlsVerify: false` in the same configuration.
=> [containers] Update documentation to make AKS spec.nodeName setting more clear

content/en/synthetics/api_tests/http_tests.md
adding an additional api error and link to the api failure page
=> include link to http api test error page

content/en/tracing/trace_collection/compatibility/dotnet-core.md, content/en/tracing/trace_collection/compatibility/dotnet-framework.md
- update .NET Core page to mention both ".NET" and ".NET Core" runtimes in a few places, or simply ".NET" when referring to both runtimes.
- consistency between .NET [Core] page and .NET Framework page
- consistency when calling the product ".NET Tracer" or "Datadog APM for .NET Core" or ""Datadog APM for .NET Framework" (it's a single library)
=> [APM > .NET Tracer] Update compatibility page

content/en/cloud_cost_management/aws.md
Updates the language in the setup doc to match the new configuration process before AWS deprecates the old page.
=> CCM Update CCM AWS setup instructions to match new AWS UI

content/en/real_user_monitoring/error_tracking/mobile/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/supported_versions/ios.md
Fixed links manually because link checker failed me.
=> Fix iOS error reporting links

content/en/tracing/troubleshooting/_index.md
The public docs had not been updating since the default limit of env x service combos was raised from 1000 to 5000; this change therefore corrects an error in the docs.
none!
=> Update Data Volume Guidelines with 5000 default limit on env/service combos

content/en/tracing/llm_observability/_index.md, content/en/tracing/llm_observability/api.md, content/en/tracing/llm_observability/quickstart.md, content/en/tracing/llm_observability/sdk.md, content/en/tracing/llm_observability/trace_an_llm_application.md
This PR adds the following details to the SDK documentation:
- Reorganize sections (key features and setup are top level, rest are in `Advanced tracing`)
- Introduce tracing using function decorators instead of context managers, move context/inline methods into `Advanced tracing`
- Instructions for submitting custom eval metrics using SDK
- Embedding documentation adds model_name/model_provider args
- Span starting documentation adds session_id/ml_app args
- Decorator documentation adds detail about name arg
- Annotation documentation adds detail about input_data arg for embedding spans, output_data arg for retrieval spans
- In-code configuration documentation for `LLMObs.enable()`
In addition, this makes a change to some other LLM Observability pages:
- API documentation to rename `Eval …
=> LLMObs SDK documentation edits

.gitignore, config/_default/menus/main.en.yaml, content/en/account_management/org_settings/oauth_apps.md, content/en/developers/authorization/_index.md, local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
Hides references to UI Extensions. The main page is moved to /developers/faq/ui_extensions/ so it will not be discoverable unless someone is given the URL or has the old URL bookmarked.
=> (DOCS-8008) Hide UI extension references

content/en/security/application_security/enabling/compatibility/nodejs.md, layouts/shortcodes/asm-libraries-capabilities.md
Remove dd-trace-js v3.x references from ASM documentation pages because it is in end-of-life and not supported anymore.
=> Remove dd-trace-js v3.x references from ASM documentation pages

content/en/security/default_rules/_index.md
A previous change has removed any reference to the term "Beta" detection. This change is adding the phrase back in.
=> add phrase to indicate that rules are tagged as beta

content/en/logs/guide/collect-heroku-logs.md
[DOCS-7986](https://datadoghq.atlassian.net/browse/DOCS-7986)
Hotjar feedback.
Reviewing the logs API endpoint documentation it does appear to want the `ddtags`  instead of explicitly passing env
https://docs.datadoghq.com/api/latest/logs/#send-logs
Updated the API to be: `drains:add '<https://http-intake.logs.datadoghq.com/api/v2/logs/?dd-api-key=<DD_API_KEY>>&ddsource=heroku&ddtags=env:<ENV>&service=<SERVICE>&host=<HOST>' -a <APPLICATION_NAME>` 
[DOCS-7986]: https://datadoghq.atlassian.net/browse/DOCS-7986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7986] Update collect-heroku-logs.md

local/bin/py/add_notranslate_tag.py
updates the `notranslate` nightly job to perform bulk updates in batches of 150 (transifex limit on bulk operations at once).   this was needed as the job wasn't working beyond the first 150 previously.
strings tagged as notranslate here have the source string translated and reviewed: https://app.transifex.com/datadog/documentation_loc/translate/#fr_FR/config__default_menus_main_en_yaml/490726492
this ran under 2min on my local, so i don't expect a huge impact on runtime in gitlab
=> [WEB-4933] updates `notranslate` job to run bulk updates in batches

content/en/dashboards/widgets/alert_graph.md
https://datadoghq.atlassian.net/browse/MNTS-90650
Clarifies that the alert graph widget does not support custom scheduling monitors at the moment.
Doc update. Look at this [line](https://docs-staging.datadoghq.com/dan.chiniara/update-alert-graph-widget-doc/dashboards/widgets/alert_graph/). 
We refer to non-custom scheduled monitors as default in the [custom scheduled doc](https://docs.datadoghq.com/monitors/guide/custom_schedules/?tab=day#alerting-behavior-of-monitors-with-custom-schedules).
=> Clarify default scheduled for alert graph widget

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
https://datadoghq.atlassian.net/browse/DOCS-7897
Struggled to figure out the right flow/formatting. Main goal of this PR is to clarify requirements for importing and initializing the tracer. 
For non-ESM applications, the steps are to either (a) add tracer in code, or (b) add tracer via command line arguments. 
For ESM applications, the steps are the same -- to either (a) add tracer in code, or (b) add tracer via command line arguments -- BUT with the additional step that regardless of whether (a) or (b) was used, an additional command line argument must be used (`--loader` or `--import` depending on Node.js version). 
I would've like to figure out a way to specify the full command line for ESM applications -- in other words, to merge the "Option 2: Add the tracer via command line …
=> Node.js updates for ESM support

content/en/code_analysis/static_analysis/generic_ci_providers.md
Adds information about diff-aware scanning setup for Generic CI Providers for Datadog Static Analysis
=> Add diff-aware scanning information to generic CI

content/en/agent/basic_agent_usage/amazonlinux.md, content/en/agent/basic_agent_usage/centos.md, content/en/agent/basic_agent_usage/deb.md, content/en/agent/basic_agent_usage/fedora.md, content/en/agent/basic_agent_usage/redhat.md, content/en/agent/basic_agent_usage/ubuntu.md, content/en/containers/docker/_index.md, layouts/shortcodes/apm-ssi-uninstall-linux.md
https://datadoghq.atlassian.net/browse/DOCS-7937
Per this JIRA ticket ^^, adding instructions for uninstalling Single Step Instrumentation (if user installed Agent via SSI and then uninstalls the Agent, they need to perform additional steps to uninstall SSI as well). Using shortcode for Linux pages since there are a handful of them. Added section to Docker page. Cecelia mentioned she would create a ticket to add an "Uninstall Agent" section to this page. For now, just added the "Uninstall SSI" section.
=> Add SSI Uninstall Steps to Agent Pages

content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps version of Azure App Service Linux Wrapper to 1.10.5 following the latest release.
https://github.com/DataDog/datadog-aas-linux/releases/tag/v1.10.5
=> Bump Version of Azure App Service Linux Wrapper to 1.10.5

content/en/getting_started/support/_index.md
Adding a banner to indicate that we will not provide Chat Support message on Memorial Day 2024.
The Support team does not provide Chat Support during US holidays. This banner is intended to inform customers of this change.
I reached out about this on slack here: https://dd.slack.com/archives/C0DESMBQU/p1716473847069609
=> Add "No Chat Support" message for Memorial Day 2024

content/en/intelligent_test_runner/setup/python.md, content/en/tests/setup/python.md
Removes the max supported `pytest` versions for Test Visibility and the Intelligent Test Runner because incompatibilities with `8.x` have been resolved.
=> CI test visibility and ITR: remove max pytest version

content/en/getting_started/opentelemetry/_index.md, content/en/opentelemetry/schema_semantics/semantic_mapping.md
Related to https://datadoghq.atlassian.net/browse/DOCS-7357
For OTel apps, unified service tagging currently works only for metrics and traces, not logs. This is something being worked on this quarter by the dev team. I'll make a note to myself to circle back next quarter to remove these warnings once logs are supported.
=> Add warning about unified tagging not working for logs for otel apps

config/_default/menus/main.en.yaml, content/en/observability_pipelines/log_volume_control/_index.md, content/en/observability_pipelines/log_volume_control/datadog_agent.md, content/en/observability_pipelines/log_volume_control/splunk_hec.md, content/en/observability_pipelines/log_volume_control/splunk_tcp.md, content/en/observability_pipelines/log_volume_control/sumo_logic_hosted_collector.md
Adds the Datadog Agent source page for the Log Volume Control use case. The doc uses mostly existing general reuse shortcodes so there isn't a lot of new content to review.
[DOCS-7981](https://datadoghq.atlassian.net/browse/DOCS-7981)
[DOCS-7981]: https://datadoghq.atlassian.net/browse/DOCS-7981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7981] Add Datadog Agent source to log volume control

content/en/agent/guide/windows-agent-ddagent-user.md
This PR updates the documentation for the `ddagentuser` to include that, starting with 7.51, it is also a member of the "Performance Log Users" group.
=> Document ddagentuser is now part of the Performance Log Users group

content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps version of Azure App Service Linux Wrapper to 1.10.6 following the latest release.
https://github.com/DataDog/datadog-aas-linux/releases/tag/v1.10.6
=> Bump Version of Azure App Service Linux Wrapper to 1.10.6

content/en/containers/docker/_index.md
Update the process collection environment variable from `DD_PROCESS_AGENT_ENABLED` to `DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED`. This was added in agent version 7.35.0 (https://github.com/DataDog/datadog-agent/pull/10555) and is also consistent with the current [Processes public docs](https://docs.datadoghq.com/infrastructure/process/?tab=docker#installation)
=> [docker] Update process collection environment variable

content/en/account_management/scim/_index.md, content/en/account_management/scim/azure.md, content/en/account_management/scim/okta.md
DOCS-8009
Adds and clarifies content in the SCIM documentation as requested by a Technical Support Engineer
- Adds a callout drawing attention the the Enterprise plan prerequisite for SCIM
- Copies the **Prerequisites** section from the main SCIM page to the child pages for setting up SCIM for Okta and Azure.
- Fixes the configuration URLs for Okta and Azure to be region-specific.
- Renumbers the links to maintain their sequential order.
=> Note Enterprise prerequisite and site-region for SCIM

content/en/tracing/troubleshooting/_index.md
- Links to span tags are broken. Span tags are not defined in the APM glossary, just the main glossary.
- Change link.
=> Broken Links on Data Volume Guidelines Page

content/en/getting_started/support/_index.md
Removing a banner indicating that we do not offer chat support during US holiday of Memorial Day. This should be merged on Tuesday May 28th.
Reverts a previous PR (https://github.com/DataDog/documentation/pull/23335). The previous PR added a banner to indicate that chat support will not be offered on the US holiday of Memorial Day. This PR removes that banner after the holiday is over.
Please Merge on Tuesday May 28th!
Discussed in Slack: https://dd.slack.com/archives/C0DESMBQU/p1716473847069609
=> Revert "No Chat" message after memorial Day Weekend

package.json, yarn.lock
bumps `datadog-ci` dependency to latest version
had a notification containing this:
[sourcemaps upload job ran successfully](https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/524741905) (the two warnings existed previous to these changes)
https://docs-staging.datadoghq.com/brian.deutsch/datadog-ci-bump/
=> bumps datadog-ci dependency

content/en/profiler/enabling/go.md, content/en/profiler/enabling/java.md, content/en/profiler/enabling/nodejs.md, content/en/profiler/enabling/python.md, content/en/profiler/enabling/ruby.md
Source code integration is an important feature that makes profiling flame graphs more intuitive and easier to explore. Encouraging users to set it up at the same time as they're configuring the profiler is desirable. Profiling currently supports the integration for Java, Python, Node.js, Go and Ruby.
=> [PROF-9825] Add source code integration step to profiling setup docs

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
Syntax for event names is incorrect for iOS. See screenshot from XCode below for the correct names:
=> update ios syntax to use correct event names

config/_default/menus/main.en.yaml, content/en/security/cloud_security_management/setup/_index.md, content/en/security/cloud_security_management/vulnerabilities/hosts_containers_compatibility.md
Moves the CSM Vulnerabilities hosts and containers compatibility table to its own article.
=> Move CSM Vulnerabilities hosts and containers compatibility

content/en/code_analysis/static_analysis/generic_ci_providers.md
Adds a beta banner for diff-aware scanning for generic CI providers in Static Analysis.
Requested by Kassen in Jira.
=> DOCS-8107 Generic CI Providers Doc Update

assets/styles/components/_collapsible-section.scss
updates font size and padding on `collapse-content` shortcode component
https://docs-staging.datadoghq.com/stefon.simmons/update-collapse-content-styles/service_management/app_builder/components/
=> update font and padding

content/en/developers/dogstatsd/datagram_shell.md
Clarifies hostname default for DogStatsD events
=> (DOCS-7398)(DEV) Clarify hostname default

content/en/observability_pipelines/best_practices_for_scaling_observability_pipelines.md, content/en/observability_pipelines/legacy/production_deployment_overview.md
There isn't a buffer option for OP 2.0 so removing it from the docs.
[DOCS-7980](https://datadoghq.atlassian.net/browse/DOCS-7980)
[DOCS-7980]: https://datadoghq.atlassian.net/browse/DOCS-7980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7980] Remove buffer in OP docs

content/en/real_user_monitoring/error_tracking/mobile/android.md, content/en/real_user_monitoring/error_tracking/mobile/flutter.md, content/en/real_user_monitoring/error_tracking/mobile/ios.md, content/en/real_user_monitoring/error_tracking/mobile/reactnative.md
As per [DOCS-8090](https://datadoghq.atlassian.net/browse/DOCS-8090), adds deobfuscation and mapping details to the following mobile error tracking pages:
- Android
- Flutter
- iOS 
- React Native
[DOCS-8090]: https://datadoghq.atlassian.net/browse/DOCS-8090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [rum mobile] Update deobfuscation docs for mobile error tracking

content/en/tracing/llm_observability/api.md
Document tags field for evaluation metircs API
=> [LLM Observability] Add tagging information to API

config/_default/menus/main.en.yaml
Add link to Cloud Cost Monitors in the CCM navigation.
Requested by Kayla on Jira.
=> DOCS-8116 Add Cloud Cost Monitors to Docs Navigation

layouts/shortcodes/latest-lambda-layer-version.html
This PR bumps the lambda extension version to 58
=> Bump datadog-lambda-extension layer to version 58

content/en/synthetics/troubleshooting/_index.md
update the docs on how resource and step durations are computed inside a synthetics test.
=> update synthetics resource docs

assets/scripts/components/codetabs.js
https://datadoghq.atlassian.net/browse/WEB-4932
Fixes weird table of contents behavior reported in the above ticket.
1. Visit a page with tabs and a table of contents, like this one: https://docs-staging.datadoghq.com/fitzage/anchor-fix/real_user_monitoring/browser/advanced_configuration/?tab=npm
2. Click on one of the table of contents links.
3. Click the same table of contents link again. It should work correctly instead of jumping to the top of the page.
=> fixes anchor links in chrome on pages with tabs

content/en/real_user_monitoring/browser/data_collected.md
As per [DOCS-8097](https://datadoghq.atlassian.net/browse/DOCS-8097), made the following updates to make sure we're not manually updating the available list in multiple places:
- Removed list of default attributes for RUM Browser and replaced them with a link to the Standard Attributes page.
- Updates the remaining links accordingly
[DOCS-8097]: https://datadoghq.atlassian.net/browse/DOCS-8097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [rum] Single source RUM Browser default attributes

content/en/universal_service_monitoring/setup.md
Adds an item to the compatibility box that GKE Autopilot is not supported
=> DOCS-8086 - Note USM limitation

content/en/observability_pipelines/log_volume_control/datadog_agent.md, content/en/observability_pipelines/split_logs/datadog_agent.md, layouts/shortcodes/observability_pipelines/prerequisites/splunk_hec_destination_only.md, layouts/shortcodes/observability_pipelines/prerequisites/sumo_logic_destination_only.md
This PR has no new content, but does the following:
- Splits up prereqs shortcodes for Splunk HEC and Sumo Logic so that there are destination-only shortcodes for the Split Logs use case docs.
- Removes Splunk HEC and Sumo Logic tabs from Datadog Agent source prereqs for Log Volume Control. There are no tabs on the other sources.
[DOCS-8066](https://datadoghq.atlassian.net/browse/DOCS-8066)
[DOCS-8066]: https://datadoghq.atlassian.net/browse/DOCS-8066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8066] update prereq shortcode and update docs

content/en/integrations/_index.md
Reverts DataDog/documentation#23492 -- integration merging logic has not yet been implemented, so users are currently unable to load Snowflake agent-based integration docs
=> Revert "(DOCS-8102) Add Snowflake redirect"

content/en/tracing/trace_collection/custom_instrumentation/_index.md, content/en/tracing/trace_collection/custom_instrumentation/java/dd-api.md, layouts/shortcodes/otel-custom-instrumentation-lang.md
- Users were missing the OTel API alert banner that links to more details. They were looking for information about when to use OpenTelemetry with Datadog. Tweaked alert banner message to emphasize that.
- Noted OpenTracing is legacy in the tab name.
- Noted that Datadog Java tracer is built on OpenTracing, so the code examples are correct as-is.
=> Custom Instrumentation Tweaks

content/en/tests/setup/javascript.md
Parallel mode support is already released for cucumber and mocha as of these releases:
* [v5.15.0](https://github.com/DataDog/dd-trace-js/releases/tag/v5.15.0)
* [v4.39.0](https://github.com/DataDog/dd-trace-js/releases/tag/v4.39.0)
https://docs-staging.datadoghq.com/juan-fernandez/remove-parallel-mode-restriction/tests/setup/javascript/?tab=cloudciprovideragentless#known-limitations
=> [test-visibility] Remove parallel mode restrictions

assets/scripts/components/dd-browser-logs-rum.js, package.json, yarn.lock
bump `browser-rum` and `browser-logs` `v5.20.0`
- also updated `addLoggerGlobalContext` to `setGlobalContextProperty` due to error after bumping browser-logs to 5.20.0 [here](https://dd-corpsite.datadoghq.com/rum/sessions?query=%40type%3Aview%20env%3Apreview%20%40view.name%3A%22%2Fstefon.simmons%2F%3F%2Fwatchdog%22%20%40view.error.count%3A1&agg_m=count&agg_m_source=base&agg_q=%40application.name%2Csdk_version&agg_q_source=base%2Cbase&agg_t=count&cols=&config_rum_raw_event_tab=true&event=AgAAAY_k4V7A9492hwAAAAAAAAAYAAAAAEFZX2s0VjdBQUFBaW00cEVBamFOc2FXQwAAACQAAAAAMDE4ZmU1MDktNWRlMy00NDNjLWE1ZmYtYzdkYWUzM2UwNmNk&fromUser=false&funnel=%5B%5D&p_tab=issues&p_tab_h_event=AgAAAY_k3w2-G9vqzgAAAAAAAAAYAAAAAEFZX2szeFFzQUFBd0ZFMk5lSGV6TndBQQAAACQAAAAAMDE4ZmU0ZGYtM2U0OS00ZTBkLTljODItNzNiNjI0YjY1Njhm&sa …
=> bump browser -rum and -logs v5.20 - [WEB-4984]

content/en/agent/configuration/proxy.md, content/en/agent/logs/log_transport.md, content/en/agent/logs/proxy.md, content/es/agent/configuration/proxy.md, content/es/agent/logs/log_transport.md, content/es/agent/logs/proxy.md, content/fr/agent/configuration/proxy.md, content/fr/agent/logs/log_transport.md, content/fr/agent/logs/proxy.md, content/ja/agent/logs/log_transport.md, content/ja/agent/logs/proxy.md, content/ko/agent/configuration/proxy.md, content/ko/agent/logs/log_transport.md, content/ko/agent/logs/proxy.md
The `logs_config.use_tcp` option is deprecated. Replace with `logs_config.force_use_tcp`.
The rest of the changes are just whitespace changes from editor formatting (removing trailing whitespace and newlines).
=> Remove references to deprecated `logs_config.use_tcp` option

content/en/real_user_monitoring/error_tracking/mobile/reactnative.md
Adds documentation for new environment variable that can be used to override the release version of the uploaded sourcemaps on Android and iOS.
=> Added RN docs for DATADOG_RELEASE_VERSION env var

content/en/intelligent_test_runner/setup/ruby.md, content/en/tests/setup/ruby.md
Test visibility has been fully migrated to datadog-ci gem v1.0 - I change the documentation to reflect that
=> [SDTEST-188] Changes after ruby test visibility library major release

.gitlab-ci.yml
add `pipeline_source` tag to `DEFAULT_TAGS` sent to Datadog
motivation: be able to filter by how the pipeline was triggered (i.e. `push`, `schedule`)
preview (no change): https://docs-staging.datadoghq.com/stefon.simmons/add-pipeline-source-as-tag/
=> add pipeline source tag

.gitignore
I missed including one of the single sourced files in our .gitignore, so it shows up as a changed file whenever someone pulls from master. This PR should fix that.
File to ignore: `content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/ruby_v1.md`
=> Ruby v2 Cleanup

assets/scripts/components/algolia.js
fixes a bug only reproducible on android devices, where the keyboard immediately appears and disappears when the search input is in focus.
https://datadoghq.atlassian.net/browse/WEB-4864
https://docs-staging.datadoghq.com/brian.deutsch/WEB-4864-android-search-issue/
no UI regressions/console errors stem from these changes.   check the instant search functionality across homepage and side nav at various screen sizes.
=> [web-4864] fixing android keyboard issue on search

config/_default/menus/main.en.yaml, content/en/cloud_cost_management/monitors/_index.md
Use a full page reuse partial so the page breadcrumbs are **DOCS > CLOUD COST MANAGEMENT > MONITORS**.
Requested by Kayla on Jira.
=> DOCS-8116 Use Full Page Reuse for Cloud Cost Monitors Documentation

content/en/continuous_integration/pipelines/awscodepipeline.md, content/en/continuous_integration/pipelines/azure.md, content/en/continuous_integration/pipelines/circleci.md, content/en/continuous_integration/pipelines/github.md, content/en/continuous_integration/pipelines/gitlab.md, content/en/continuous_integration/pipelines/jenkins.md
This patch adds some extra information to the docs of all of CI Visibility's supported providers that mention how the collected logs for the respective provider can be identified and indexed.
=> [CIVIS-9922] Improve logs correlation docs for CI providers

content/en/opentelemetry/guide/otel_demo_to_datadog.md
This PR adds a the setting `span_name_as_resource_name` to the connector config, as this is required to have Traces and Metrics stats aligned.
```yaml
traces:
span_name_as_resource_name: true
```
=> Update connector configuration

content/en/tracing/llm_observability/quickstart.md, content/en/tracing/llm_observability/sdk.md
This PR updates the LLM Observability SDK instructions to match the ddtrace 2.9 release, including
- Install ddtrace off the latest release, no longer install a specific git branch/commit
- Replace a deprecated env var name `DD_LLMOBS_APP_NAME` to `DD_LLMOBS_ML_APP`
=> [LLMObs] Update docs to match ddtrace 2.9 release

content/en/serverless/aws_lambda/installation/nodejs.md, content/en/serverless/aws_lambda/installation/python.md
Bumps the lambda-datadog Terraform module version to 1.1.0 and updates the Datadog Lambda Layers to the latest supported versions.
https://github.com/DataDog/terraform-aws-lambda-datadog
=> Bumps lambda-datadog Terraform Module Version to 1.1.0 and Datadog Lambda Layers to Latest Supported Versions

content/en/logs/guide/_index.md, content/en/logs/guide/delete_logs_with_sensitive_data.md
Adds a new guide on how to delete logs with sensitive data.
[DOCS-8148](https://datadoghq.atlassian.net/browse/DOCS-8148)
[DOCS-8148]: https://datadoghq.atlassian.net/browse/DOCS-8148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8148] Delete logs with sensitive data

assets/styles/components/_collapsible-section.scss
=> Enhance styling for p level with collapse-content shortcode

assets/styles/components/_collapsible-section.scss
Stop hardcoding text size for collapse-content. It will now use the normal size of our headings. Style for this shortcode is based on the `level` param. For example, `level=h4`.
This change is an add on to: https://github.com/DataDog/documentation/pull/23603.
https://docs-staging.datadoghq.com/brett0000FF/fix-collapse-text-size/
=> Stop hardcoding collapse-content text size

content/en/developers/ide_plugins/idea/_index.md
We are adding "Open in IDE" support for PhpStorm, with RubyMine and other IDEs coming in the future. By making the wording here generic we don't have to update it every time we add support for a new IDE in this specific feature (generally, if an IDE is supported, you can use "Open in IDE" with it).
=> IDE Integrations/Open in IDE: Do not list specific IDEs/languages

content/en/intelligent_test_runner/_index.md
Adds a sentence to the tracked files documentation in ITR about tracked files being always relative to the repository's root
=> ITR tracked files: add info that tracked files are always relative to repo's root

content/en/data_jobs/databricks.md, content/en/data_jobs/emr.md
Update Data Jobs Monitoring setup guide to indicate the last stable version of the init script is now `1.2.0` instead of `1.0.0`.
=> update the last stable version of data jobs init scripts to 1.2.0

content/en/service_management/app_builder/_index.md, content/en/service_management/app_builder/auth.md, content/en/service_management/app_builder/build.md, content/en/service_management/app_builder/components/_index.md, content/en/service_management/app_builder/components/tables.md, content/en/service_management/app_builder/connections/_index.md, content/en/service_management/app_builder/connections/http_request.md, content/en/service_management/app_builder/embedded_apps.md, content/en/service_management/app_builder/expressions.md
Edits the beta banner because App Builder is now in public beta. Also adds it to some pages where it was missing, and adds the govcloud disclaimer to some places where it was missing.
=> change beta banner (and add it where it was missing)

content/en/synthetics/browser_tests/actions.md
Adding the name of browsers that support the DD Test recorder extension
=> Specify Browsers compatible for the Browser test recorder

content/en/real_user_monitoring/browser/tracking_user_actions.md, content/en/real_user_monitoring/session_replay/browser/privacy_options.md
This PR adds documentations on a new privacy configuration concerning action names in RUM Browser SDK. 
When the user opt-in for enablePrivacyForActionName, we mask action names when no action name attributes given or no html override.
=> Add documentation for masking action name options

content/en/opentelemetry/ingestion_sampling_with_opentelemetry.md
Adds a note about the `hash_seed` parameter that was missing originally.
=> [OTEL][Sampling] Document using hash_seed when using the probabilistic sampling

layouts/shortcodes/notifications-email.md
Adds recommended next steps for email issues when it comes to notifications 
I'm checking with the Monitors Product Team about the wording. Changes can be seen on [this preview page](https://docs-staging.datadoghq.com/dan.chiniara/add-troubleshooting-for-missing-notifications-from-email/monitors/notify/).
=> dan.chiniara/add troubleshooting for missing notifications from email

assets/styles/instantsearch/searchbar-with-dropdown.scss
fix font for numbers in search input
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5002
preview: type into the search bars. the numbers should be linear.
- home: https://docs-staging.datadoghq.com/stefon.simmons/fix-font-feature-search/monitors/
- search page: https://docs-staging.datadoghq.com/stefon.simmons/fix-font-feature-search/search/
- left nav and on mobile: https://docs-staging.datadoghq.com/stefon.simmons/fix-font-feature-search/opentelemetry/
=> fix number font in search bar

content/en/service_management/app_builder/components/_index.md
Now that collapsible heading sizes are more scaled, bumping the level down so that they are a bit smaller on the page.
=> Change size of collapsible headings

content/en/getting_started/integrations/aws.md
What does this PR do? What is the motivation?
Add the required permissions to run the Datadog Integration Stack.
https://datadoghq.atlassian.net/browse/CLOUDS-4831
Merge instructions
I'm checking with the Monitors Product Team about the wording. Changes can be seen on [this preview page](https://docs-staging.datadoghq.com/dan.chiniara/add-troubleshooting-for-missing-notifications-from-email/monitors/notify/).
Please merge after reviewing
=> Add the required permissions to run the Datadog Integration Stack

content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md
Notes that UDS is not supported on <.NET Core 3.1 or .NET Framework
=> [.NET] [Tracing] Add note that UDS is not supported in <.NET Core 3.1

content/en/integrations/guide/source-code-integration.md
Azure Devops Services is the managed, SaaS version of Azure Devops Server (see https://learn.microsoft.com/en-us/azure/devops/user-guide/about-azure-devops-services-tfs?view=azure-devops)
It is supported by Source Code Integration. This PR clarifies that we support both in the provider support table.
=> [SCI] Add Azure Devops Services to the list of supported providers

content/en/opentelemetry/ingestion_sampling_with_opentelemetry.md
Makes it clear that the new probabilistic sampler requires 128 bit trace IDs. We recently ran into a support case where a customer was using an older version of a tracer without this support and had disconnected traces when trying to use the probabilistic sampler.
=> probabilistic sampler requires 128 bit trace ids

content/en/data_jobs/databricks.md
This update is to call out some important steps in data jobs monitoring setup wrt the access token permission during Databricks Integration setup:
* the token needs to never expire.
* the token needs to have Can View ACL permissions to Databricks Jobs.
* call out an alternative way of generating access token (as service principal is recommended way of managing identity in Databricks for automated tools)
=> update data jobs monitoring setup guide wrt databricks integration permissions

content/en/security/guide/aws_fargate_config_guide.md
This PR updates the fargate CWS setup documentation to use the public.ecr.aws images instead of the dockerhub ones since ECS/EKS run on AWS it makes sense to use AWS registries by default.
=> fargate-cws: use `public.ecr.aws` ecr instead of dockerhub

content/en/continuous_integration/pipelines/gitlab.md
We introduced a wrong link on Gitlab Parameters https://github.com/DataDog/documentation/commit/d3610e597f4104892b15786e632baa1bc319ca44#diff-b703ed66ac92efe1b5fc580406e438b49a3870819301c3eee3a2b8d7d8d4f81dR39 in the compatibility list. There was no link before so I am simply removing it
=> Remove wrong link on gitlab parameters

content/en/security/cloud_security_management/identity_risks/_index.md, content/en/security/cloud_security_management/setup/_index.md
DOCS-7926. Add GCP support CSM Identity Risks.
=> DOCS-7926: Add GCP support

Makefile
I relaxed the resource_type validation so that new changes to the enum will not be forward breaking. The manifests-validator delancie job will handle validating the enum.
Note: the assetlib schema will no longer validate the manifest.tile.resources.resource_type field, so if you want to specifically add validations around that, you would just need to update your validator to import [TILE_RESOURCE_TYPES](https://github.com/DataDog/dd-source/blob/5e75ee953c5ff1a27a030931d62758d86f1e51bd/domains/assets/shared/libs/python/assetlib/constants.py#L59). However, I don’t think you would need to since the manifets-validator will be doing the validation, and IIRC all validators are dependent on that job
=> [ecos 1482] Bump Assetlib

content/en/tracing/llm_observability/api.md, content/en/tracing/llm_observability/sdk.md, content/en/tracing/llm_observability/submit_evaluations.md
This PR updates the `ml_app` naming guidelines and adds a reference to Datadog's naming custom metrics documentation to inform users on acceptable custom evaluation labels.
=> update custom eval metric and ml_app naming guidelines

snippets/markdown.json
- `kind` is no longer a user defined parameter.
- https://github.com/DataDog/documentation/pull/23721
=> Remove kind from frontmatter snippet

content/en/data_streams/java.md
Today, customers setting up DSM have services named `kafka` in APM. Which is not useful.
Recommending them to override that service name by default to `DD_SERVICE`.
=> Ask to update service name in documentation

config/_default/menus/main.en.yaml
Add cloud provider tabs as child pages in the TOC.
Requested by Natasha on Slack.
=> DOCS-8264 Container Cost Allocation Navigation Update

content/en/tests/correlate_logs_and_tests/_index.md
Fixes the default value of `DD_AGENTLESS_LOG_SUBMISSION_ENABLED` environment variable: logs submission is disabled by default.
=> Fix default value for the DD_AGENTLESS_LOG_SUBMISSION_ENABLED env var

content/en/serverless/step_functions/installation.md
We added `propagateUpstreamTrace` to `serverless-plugin-datadog / step functions` and `--propagate-upstream-trace` to `datadog-ci / step functions`. This updates the docs for instrumenting AWS step functions.
n.b. wait until https://github.com/DataDog/serverless-plugin-datadog/pull/492 is merged
=> Add propagate upstream trace flags to Serverless / Step Functions

content/en/synthetics/mobile_app_testing/settings/_index.md
Our automation tooling does not support apps built with Flutter SDK: it would help stating it clearly in our documentation
=> add a note about Mobile Application Testing not supporting Flutter SDK for now

content/en/developers/integrations/api_integration.md
The API Integration Guide refers to "agent-based integrations". 
It should refer to API Integrations
Text is accurate.
The API Integration Guide refers to "agent-based integrations". 
It should refer to API Integrations
N/A
=> API Integration Guide should refer to API integrations, not agent-based integrations.

config/_default/menus/main.en.yaml
- Explicitly point to file path instead of relying on redirect.
- Fixes condition when user clicks Android or iOS from Custom Instrumentation nav.
=> Point to correct file path for Android and iOS pages

content/en/tracing/trace_collection/compatibility/php.md
Alert box link is broken because it's formatted with Markdown instead of HTML.
=> Fix link in PHP alert box

content/en/data_jobs/emr.md
It's not clear to customer what Amazon EMR release version the Data Jobs Monitoring support at the moment, this is causing confusion and unsuccessful setup for customers. This PR is to call out the supported versions: Amazon EMR 6.6.0 and above.
=> Call out the supported Amazon EMR release versions for DJM

content/en/universal_service_monitoring/setup.md
Removed the helm version requirement for the Kafka monitoring feature
=> Update setup.md - Remove Kafka helm version requirement

content/en/intelligent_test_runner/troubleshooting/_index.md
Updates the troubleshooting section of Intelligent Test Runner.
=> [SDTEST] Update troubleshooting section of Intelligent Test Runner

content/en/tracing/other_telemetry/connect_logs_and_traces/java.md
Adds a note to say that auto injection of trace correlation is available for certain frameworks.
[DOCS-7381](https://datadoghq.atlassian.net/browse/DOCS-7381)
[DOCS-7381]: https://datadoghq.atlassian.net/browse/DOCS-7381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7381] Add note to Java logs and trace correlation

content/ja/integrations/_index.md
We removed kind and opted for a `custom_kind` keyword recently. This change also needed to apply to ja integrations. I've added this as a cascade param until they make their way through translations with the new param.
https://docs-staging.datadoghq.com/david.jones/integrations/ja/integrations/
=> ja integrations inconsistencies

content/en/security/cloud_security_management/setup/supported_deployment_types.md
Removes the beta tag for Agentless Scanning in the supported deployment types table.
=> Remove beta tag from supported deployments table

content/en/agent/logs/_index.md
Adds note about ending a log line with a newline character.
[DOCS-8014](https://datadoghq.atlassian.net/browse/DOCS-8014)
[DOCS-8014]: https://datadoghq.atlassian.net/browse/DOCS-8014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8014] Add note to Agent Logs collection doc

content/en/agent/guide/agent-v6-python-3.md, content/en/agent/logs/advanced_log_collection.md, content/en/agent/troubleshooting/hostname_containers.md, content/en/containers/cluster_agent/admission_controller.md, content/en/containers/cluster_agent/clusterchecks.md, content/en/containers/cluster_agent/commands.md, content/en/containers/cluster_agent/endpointschecks.md, content/en/containers/cluster_agent/setup.md, content/en/containers/guide/cluster_agent_autoscaling_metrics.md, content/en/containers/guide/clustercheckrunners.md, content/en/containers/kubernetes/apm.md, content/en/containers/kubernetes/control_plane.md, content/en/containers/kubernetes/distributions.md, content/en/containers/kubernetes/prometheus.md, content/en/containers/kubernetes/tag.md, content/en/tracing/configure_data_security/_index.md, content/en/tracing/guide/ignoring_apm_resources.md, content/en/tracing/guide/setting_up_apm_with_kubernetes_service.md, layouts/shortcodes/k8s-helm-redeploy.md
This PR:
- Adds Operator support where there is Helm support, and vice versa
- Standardizes "Operator" in tabs to "Datadog Operator"
- Standardizes the helm config file to be called `datadog-values.yaml`
- Puts the operator tab ahead of the helm tab where possible
=> DOCS-7988 - Feature parity for Operator and Helm

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
Update the Node.js tracer docs to match the README.md documentation in the dd-trace-js repo, specifically adding information about version 4 and 5 of the tracer.
=> Update nodejs.md with new version info

content/en/intelligent_test_runner/setup/python.md
Updates the minimum pytest version supported by the Intelligent Test Runner to `7.2.0`. There was previously a typo specifying `6.8.0` which was never a valid version.
=> Fix minimum pytest version supported by ITR

content/en/database_monitoring/connect_dbm_and_apm.md
Clarifies that Aurora MySQL v3 is required for full DBM/APM propagation.
=> Clarify Aurora 3 requirement

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md
As per https://datadoghq.atlassian.net/browse/DOCS-8150:
- Moves the custom attributes section for React Native from the setup page to advanced configuration page
- Renames the section title from "Track custom attributes" to "Track custom global attributes" to be consistent with naming for other platforms
=> [rum] Move custom global attributes for React Native

content/en/containers/guide/autodiscovery-management.md
Small clarification as the annotation you can put on the pod like `ad.datadoghq.com/exclude: true` is only for excluding/blocking - it is not for allowing. As all pods/containers are monitored by default. 
There is no `ad.datadoghq.com/include: true` type of annotation.
=> Clarify containers pod exclusion annotation

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md
Adds details on how to retrieve session IDs for Android, iOS, Flutter, and React Native, as per https://datadoghq.atlassian.net/browse/DOCS-7945.
=> [rum] DOCS-7945 Retrieve Session ID at runtime for Android/iOS/Flutter

content/en/containers/kubernetes/integrations.md
* Clarifies the Agent conf.d directory being `/etc/datadog-agent/conf.d`
* Fixes the `mountPath` in the example ConfigMap so it's the proper path
=> [Kubernetes integrations] Clarify conf.d directory and fix mountPath

content/en/database_monitoring/troubleshooting.md
In our DBM Troubleshooting docs [here](https://docs.datadoghq.com/database_monitoring/troubleshooting/#query-bind-parameters-cannot-be-viewed), we had the following line:
_In a future release, settings to expose the un-obfuscated query bind parameters are planned._
As a best practice, we should never mention or commit to future releases in our public-facing docs, so this PR removes this line.
N/A
=> Remove mention of a future release related to query param deobfuscation

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md
- Breaks down the many options available for manual instrumentation of the React Native SDK into separate paragraphs instead of them being in one long snippet, as per https://datadoghq.atlassian.net/browse/DOCS-8151
Not sure if there is enough detail for some of these options, so definitely open to feedback and suggestions.
=> [rum] Break down React Native manual instrumentation options

content/en/error_tracking/dynamic_sampling.md
Removes the beta banners for Error Tracking Dynamic Sampling documentation.
This feature will start to be rolled out (silently) to some customers next week. We link to this documentation page from Datadog, so non-beta users can start encountering it.
Keeping the `private: true` because the feature is not announced yet and won't be rolled out to all customers at once.
<s>Please **don't** merge after reviewing. Will merge as soon as we start rolling out.</s>
Can be merged now!
=> [Error Tracking] Remove beta tag from Dynamic Sampling documentation

content/en/monitors/notify/variables.md
`{{ citest.error.message }}` does not work as template variable for grabbing the error message. You must use `{{ citest.attributes.error.message}}`.
This PR fixes that.
=> [test visibility monitors] Remove `error.message` 

content/en/containers/docker/prometheus.md
This PR changes the Dockerfile snippet that specifies how to set labels for OpenMetrics/Prometheus autodiscovery.
When defining the value of the docker label `com.datadoghq.ad.instances`, the current implementation escapes double quotes using `\"` which is not necessary given that the json is encapsulated by `'`.  
There is also an additional `"` that is not needed within the first array which has been removed.
The new snippets allow the labels to be set on an image properly to allow for Autodiscovery.
=> Update prometheus.md with proper dockerfile label syntax

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md
- "For more information see the **guide to uploading Android source mapping files**" linked to the wrong place.
- A link reference already existed for [8], and a new one wasn't created when the content was created: https://github.com/DataDog/dd-sdk-android/commit/c1774144cab5671462ddc650e51afe98fabe672a.
- Replaced the link reference to point to the correct place: [Upload your mapping file](https://docs.datadoghq.com/real_user_monitoring/error_tracking/mobile/android/?tab=us#upload-your-mapping-file).
=> [DOCS-8248] Fix link in Tracing Android Applications

content/en/serverless/aws_lambda/installation/dotnet.md, content/en/serverless/aws_lambda/installation/java.md, content/en/serverless/aws_lambda/installation/nodejs.md, content/en/serverless/aws_lambda/installation/python.md
* Updates the Lambda Extension Installation Instructions for .NET and Java to reference the [lambda-datadog](https://registry.terraform.io/modules/DataDog/lambda-datadog/aws/latest) Terraform module instead of the old approach.
* Updates Python and Node documentation to reference latest version (`1.2.0`) of the Datadog Lambda Terraform Module.
* Updates Python documentation to reference latest supported layer version (`96`).
Follows https://github.com/DataDog/documentation/pull/23263
=> Update Lambda Extension Installation Instructions for Datadog Lambda Terraform Module (.NET and Java)

.gitlab-ci.yml
Points the CI to our new build image with an updated version of ubuntu and python.
https://docs-staging.datadoghq.com/jackie.robson/update-build-image/
=> WEB-5022 | update ubuntu and python

content/en/real_user_monitoring/browser/setup.md
We want to recommend masking action names in the default config
Make `enablePrivacyForActionName: true` as default setting.
=> Add enablePrivacyForActionName in default configuration docs

content/en/tracing/trace_collection/compatibility/nodejs.md
- dd-trace-js supports GraphQL Yoga as of https://github.com/DataDog/dd-trace-js/pull/3610.
- Note this on the Node.js compatibility page.
=> Document GraphQL Yoga Support for Node.js

assets/styles/pages/_global.scss
Some links were displaying a default blue hover color instead of the datadog purple. This was caused by the default bootstrap link color CSS variable.
Resetting this variable to the correct link hover color solved the problem.
https://datadoghq.atlassian.net/browse/WEB-4977
https://docs-staging.datadoghq.com/fitzage/anchor-fix/account_management/rbac/permissions/#log-management [scroll down to table with logs_live_tail linked in the first column to see the fixed example]
https://docs-staging.datadoghq.com/fitzage/anchor-fix/service_management/workflows/actions_catalog/
=> reset bootstrap hover color variable to fix link hover color issues

content/en/synthetics/platform/private_locations/_index.md
Specifies that `.pem` files mounted to private locations should be mounted to a `.pem` file and not directly to the `/certs` directory to clear up some confusion
=> Small update to root cert mounting instructions for PL

content/en/real_user_monitoring/browser/setup.md
Introduce `enablePrivacyForActionName` in RUM sdk setup configuration.
=> Add enablePrivacyForActionName in RUM browser setup parameter list

layouts/shortcodes/latest-lambda-layer-version.html
This PR updates the lambda extension version to latest (v59).
=> Bump datadog-lambda-extension layer to version 59

content/en/logs/log_collection/_index.md
We handle a nesting of 20 right now. The doc is mentioning 10, so I fix the number here.
=> Correct documentation about json nesting for logs

content/en/glossary/terms/intelligent_retention_filter.md, content/en/tracing/guide/trace_queries_dataset.md, content/en/tracing/trace_explorer/_index.md, content/en/tracing/trace_pipeline/trace_retention.md
We recently made a change to include spans indexed by the intelligent retention filter in dashboards and notebooks: see more [here](https://docs.google.com/document/d/1orsLsMowaf_p6qmY-RAChiT0YvH8uBZw081rOCRa9aY/edit?usp=drive_open&ouid=104493353650582068529).
Updating the documentation accordingly
=> Updates docs for multi-index apm dashboard queries

content/en/continuous_integration/pipelines/awscodepipeline.md, content/en/continuous_integration/pipelines/github.md, content/en/continuous_integration/pipelines/gitlab.md
Pipelines with status `running` also encapsulate queued and waiting pipelines. We do not have statuses for those yet so this PR marks this as a known limitation.
=> [SDCI] Clarify running pipelines limitations

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md
Adds documentation for new `useAccessibilityLabel` introduced for the first time in RN SDK v2.4.0.
The parameter has been introduced for privacy reasons. By default the SDK will try to resolve the action names by using the elements accessibility label, if available. This could lead to PIIs leaking, as it happened in previous instances such as [incident-28493](https://dd.enterprise.slack.com/archives/C07AJ9VEL1Y).
Setting `useAccessibilityLabel` to false will disable this default behaviour.
=> [RN-v2.4.0] useAccessibilityLabel config parameter

content/en/tracing/trace_collection/compatibility/nodejs.md
- deletes the "coming soon" line for the Node.js `kafka-node` library
- there is no ongoing effort to support this library
- a line for this also exists in the Japanese translation; should it be removed in this PR as well?
=> node: kafka-node has been "coming soon" for 4 years

content/en/code_analysis/software_composition_analysis/_index.md, content/en/code_analysis/static_analysis/_index.md
This PR updates the Code Analysis docs lefthand menu to specify product names:
- Static Analysis (SAST)
- Software Composition Analysis (SCA)
Motivation:
- Searchability and discoverability: SAST and SCA are widely recognizable industry terms
- Align with billable SKUs being created this week
=> Add (SAST) and (SCA) to Code Analysis SKU names

content/en/serverless/guide/agent_configuration.md
Remove the `apm_config.log_throttling` config from the serverless documentation.
This config has been deprecated since 7.54.0 (released more than a month ago) by https://github.com/DataDog/datadog-agent/pull/24353.
=> Remove log_throttling config from Serverless documentation

config/_default/menus/main.en.yaml
Add (SAST) and (SCA) to product names in nav. PM request.
Related to https://github.com/DataDog/documentation/pull/24051.
=> Update Code Analysis nav items

config/_default/menus/main.en.yaml, content/en/error_tracking/issue_states copy.md, content/en/error_tracking/issue_states.md, content/en/error_tracking/regression_detection.md
- Makes Regression Detection its own section in the nav based on Oli feedback ([DOCS-8398](https://datadoghq.atlassian.net/browse/DOCS-8398)).
- Cross references the landing page and the regression detection page in Further Reading.
[DOCS-8398]: https://datadoghq.atlassian.net/browse/DOCS-8398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Separate Regression Detection in Error Tracking

layouts/partials/algolia/api-pages-full-index.json
new `x-merge-override` field / missing `tags` field in the api spec broke the build
=> fixes api page indexing

content/en/synthetics/guide/custom-javascript-assertion.md
Changes `=` to `===` in `return document.querySelector("<SELECTORS>").checked = true;`
Motivation: Strict equality comparison in JavaScript is done using `===`. Single `=` is used to assign, which is not what this code snippet is meant to do.
No
=> Fix JavaScript equality symbol

content/en/tracing/trace_collection/library_config/go.md
Adds information about various envvars that are supported in dd-trace-go, along with their default values.
Motivated by #23787
=> Update Go Tracing Configuration doc to reflect more of the env vars we support

content/en/monitors/notify/variables.md
Adding `host` as part of the keys which can be leveraged as variables in log monitors.
=> Update variables.md to add {{log.host}}

local/bin/py/add_notranslate_tag.py
we are incorrectly tagging the heading in the data home partial as not to be translated. This pr fixes this tagging issue.
No changes to preview, this will run as part of the scheduled job
=> notranslate tag update

content/en/code_analysis/_index.md, content/en/code_analysis/ide_plugins/_index.md, content/en/code_analysis/software_composition_analysis/_index.md, content/en/code_analysis/software_composition_analysis/generic_ci_providers.md, content/en/code_analysis/software_composition_analysis/setup.md, content/en/code_analysis/static_analysis/_index.md, content/en/code_analysis/static_analysis/generic_ci_providers.md, content/en/code_analysis/static_analysis/setup.md, content/en/code_analysis/static_analysis_rules/_index.md
Adds acronyms (SCA + SAST) and additional search terms to the Code Analysis doc pages for better search results! i.e. a search for "Static Analysis" directs a user to the Code Analysis section, not the Security > Software Composition Analysis section.
Chat with Kassen on Slack
A redo of https://github.com/DataDog/documentation/pull/24053.
=> Add Algolia Tags in Code Analysis Documentation

content/en/continuous_testing/environments/multiple_env.md
Updates the parameter name from `--start-url` to `--override startURL`. Had a couple of customer support questions about this.
Chat with Hakan on Slack
=> Testing Multiple Environments Update

config/_default/menus/main.en.yaml
Makes the LastPass navigation entry match the page title. It previously said NoPassword, which is an outdated legacy name. Noticed by a couple of product managers.
The [actual documentation page](https://docs.datadoghq.com/account_management/saml/lastpass/) mentions NoPassword, but is titled LastPass.
=> Make LastPass nav entry consistent with page title

content/en/code_analysis/static_analysis_rules/_index.md
When you search "Static Analysis" in the Docs Site, the individual Static Analysis Rules pages clog up the search results. We instead would like the documentation for Static Analysis (like the Setup pages) to show up first, so removing the search tags from the Static Analysis Rules section.
=> Remove Search Tags for Static Analysis Rules Results

content/en/profiler/enabling/java.md, content/en/profiler/profiler_troubleshooting/java.md
It updates the Java profiler related documentation to the new ability to set the maximum stack depth for the collected data via the standard configuration options (system property and env variable).
See [PROF-8797]
[PROF-8797]: https://datadoghq.atlassian.net/browse/PROF-8797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update the Java profiler docs for setting the maximum stack depth

content/en/logs/guide/logs-rbac-permissions.md
- Outdated UI image for Logs permissions
- [DOCS-6538](https://datadoghq.atlassian.net/browse/DOCS-6538)
[DOCS-2311]: https://datadoghq.atlassian.net/browse/DOCS-2311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-6538]: https://datadoghq.atlassian.net/browse/DOCS-6538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove outdated UI image

content/en/profiler/guide/save-cpu-in-production-with-go-pgo.md
Fix links that were broken in https://github.com/DataDog/documentation/pull/23671.
Add space between Further reading and reference links.
=> Fix reference links for PGO docs

layouts/shortcodes/csm-windows-setup.md
Removes beta banner for CSM Windows File Integrity Monitoring.
=> Remove CSM Windows FIM beta banner

content/en/serverless/step_functions/installation.md
Updating the version because it was missed with the last release
> Lambda traces will be disjoint from Step Function traces to support 128 bit trace IDs. Please upgrade your Lambda Node Layer version to v9.112.0 and Datadog Lambda Python Layer version to v6.95.0 on your Lambda functions to resolve this issue. Please reach out to Datadog support if you have any questions.
=> Update Layer Version for Step Fn

data/libraries.yaml
Update ruby trace gem name from 'ddtrace' to 'datadog'
=> Update ruby tracer gem name in libraries.yaml

content/en/getting_started/synthetics/private_location.md, content/en/synthetics/platform/private_locations/_index.md
[DOCS-8414](https://datadoghq.atlassian.net/browse/DOCS-8414)
[DOCS-8414]: https://datadoghq.atlassian.net/browse/DOCS-8414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8414] fixing msi installer on synthetics private locations

content/en/dashboards/functions/smoothing.md
This fixes the description of "span" for EWMA to be accurate.  EWMA (logically) uses all data points (with diminishing weights for older data), so the existing description is wrong.
Unfortunately, I couldn't find a good standard description of what the span actually *is*.  The technical definition is that it sets the smoothing constant (also not a standardized term) to 2/(span+1).  I chose a description based on [this stackoverflow post](https://stats.stackexchange.com/questions/534210/what-does-span-mean-in-exponential-moving-average) which is not the most helpful, but gives some guidance on what the span does while being correct.
(See also my comment on TSQ-851)
=> Update description of "span" for EWMA.

content/en/synthetics/browser_tests/actions.md
Making the mandatory `return` statement more clear that if a falsy step is returned the test will fail. 
[DOCS-8429](https://datadoghq.atlassian.net/browse/DOCS-8429)
[DOCS-8429]: https://datadoghq.atlassian.net/browse/DOCS-8429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8429] Update Testing Browser steps/ Javascript

config/_default/menus/main.en.yaml, content/en/observability_pipelines/_index.md, content/en/observability_pipelines/advanced_configurations.md, layouts/shortcodes/observability_pipelines/configure_log_archive/google_cloud_storage/instructions.md, layouts/shortcodes/observability_pipelines/destination_settings/chronicle.md, layouts/shortcodes/observability_pipelines/processors/enrichment_table.md
- Renames Setup to Advanced Configuration.
- Move nav item lower
- Add info on referencing files in Kubernetes
[DOCS-8428](https://datadoghq.atlassian.net/browse/DOCS-8428)
[DOCS-8428]: https://datadoghq.atlassian.net/browse/DOCS-8428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8428] Rename setup doc and add referencing files in k8s

content/en/agent/guide/upgrade_between_minor_versions.md
In https://github.com/DataDog/documentation/pull/24164 the linux tab had left Agent 7 in the text, this PR fixes this error.
=> Remove missed reference to Agent 7 in upgrade documentation

content/en/synthetics/browser_tests/actions.md
reverting this PR: https://github.com/DataDog/documentation/pull/23663/files as we do not support edge officially with the recorder
changing the content of our docs to remove explicit support for edge with the recorder
=> reverting docs -> unlist edge support

config/_default/menus/main.en.yaml, content/en/error_tracking/monitors.md, content/en/logs/error_tracking/monitors.md, content/en/real_user_monitoring/error_tracking/monitors.md, content/en/tracing/error_tracking/monitors.md
=> Adding error tracking monitors to the error tracking doc navs

content/en/code_analysis/static_analysis/generic_ci_providers.md
- fixes a typo in the typo (missing `-`)
- updates note to include messaging that we fallback to a full scan when unable to complete a diff-aware scan
=> [STAL-2445] Update diff-aware section

content/en/tracing/troubleshooting/_index.md
Updates allowed span tag value length to 25K, since this is what we actually enforce.
See escalation for motivation and testing:
https://datadoghq.atlassian.net/browse/APMS-12177
=> Update span tag length limitation

content/en/observability_pipelines/archive_logs/datadog_agent.md, content/en/observability_pipelines/dual_ship_logs/datadog_agent.md, content/en/observability_pipelines/log_volume_control/datadog_agent.md, content/en/observability_pipelines/sensitive_data_redaction/datadog_agent.md, content/en/observability_pipelines/split_logs/datadog_agent.md, layouts/shortcodes/observability_pipelines/log_source_configuration/datadog_agent.md
Removes the header from the Datadog Agent shortcode and adds it to the markdown docs.
=> Remove header from Datadog Agent shortcode and add to docs

content/en/developers/integrations/python.md
Update download instructions. It was reported by a partner to not be working. I tested it locally and found that the github link ,although valid, redirects to another endpoint where the download can be started:
```
< HTTP/2 302
< server: GitHub.com
< date: Thu, 18 Jul 2024 14:45:53 GMT
< content-type: text/html; charset=utf-8
< vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
< location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/47203045/b39303d6-edd5-4156-aa9c-de3a12d52999?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240718%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240718T144553Z&X-Amz-Expires=300&X-Amz-Signature=e8a1506e7071c19619b7b599eb8f88e69d353796450f18ab951d150dc …
```
=> Update to include redirects

content/en/containers/guide/auto_conf.md
Adding more explicit example for override section in Datadog operator `datadog-agent.yaml`
Per customer's request adding more explicit example: https://datadog.zendesk.com/agent/tickets/1775321
https://docs.datadoghq.com/containers/guide/auto_conf/?tab=datadogoperator#disable-auto-configuration
=>  Update auto_conf.md - override section in Datadog operator `datadog-agent.yaml`

content/en/tracing/guide/inferred-service-opt-in.md
Follow-up from this [PR](https://github.com/DataDog/documentation/pull/24213) that adds lighter setting instructions for more recent Agent version
=> Inferred services - add old agent instructions back

content/en/logs/error_tracking/backend.md
Error-Tracking looks for `error.kind` not `error.type` https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/processing/processing-common/src/main/java/com/dd/logs/processing/processors/errortracking/rawevent/LogsRawEventMapper.java#L64
=> [Error-Tracking]: Logs uses `error.kind` not `error.type`

content/en/tracing/trace_collection/compatibility/php.md, content/en/tracing/trace_collection/library_config/php.md
The implementation of the OpenAI Integration was just merged in the PHP Tracing Library: https://github.com/DataDog/dd-trace-php/pull/2685
This updates the corresponding public doc.
=> docs: Add PHP OpenAI compatibility & doc

content/en/logs/log_collection/reactnative.md
Updates docs to include a description of the new custom error fingerprint in DdLogs.
=> RN v2.4.2: update docs with new custom error fingerprint argument

content/en/logs/log_configuration/processors.md
- Clarify status remapper that starts with `err` maps to ERROR
- [DOCS-8003](https://datadoghq.atlassian.net/browse/DOCS-8003)
- Pending Logs team approval
[DOCS-8003]: https://datadoghq.atlassian.net/browse/DOCS-8003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clarify status remapper requirement

content/en/security/application_security/threats/add-user-info.md
We updated the Out-of-the-Box rule to use a different event name. This PR reflect this change in the documentation. The change is backward compatible
=> Update the payment.failure event to match the rule

content/en/agent/troubleshooting/send_a_flare.md, content/en/tracing/troubleshooting/tracer_debug_logs.md
Reverts DataDog/documentation#22047.
This feature is not working properly due to a bug, so I was asked to remove the documentation for the time being.
Please merge after reviewing, thank you!
=> Revert "Document tracer flares"

content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/reactnative.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/unity.md
Removed the alias from each of the framework pages so that users can be directed to the landing page (correct behavior) instead of a specific framework (incorrect behavior).
=> [DOCS-8510] Remove aliases from mobile troubleshooting pages

layouts/shortcodes/dbm-mongodb-agent-beta-install-docker.md, layouts/shortcodes/dbm-mongodb-agent-beta-install-kubernetes.md, layouts/shortcodes/dbm-mongodb-agent-beta-install-linux.md
This PR updates the DBM for MongoDB beta agent installation script to include guides to change DD_SITE. This change makes the beta customers (especially those on trials and has not installed datadog-agent before) aware of the need of choosing right DD_SITE the first time they install the agent. We've noticed a customer in us3 was getting API key errors due to DD_SITE set to `datadoghq.com`
=> [dbm] update dbm mongodb beta installation script to include guides to DD_SITE

assets/scripts/components/async-loading.js, layouts/partials/language-region-select.html
fixes the language-selector redirect
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5122 
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-lang-dropdown-async-web-5122/ja/agent/basic_agent_usage/chef/
- starting at the `/ja` link above, navigate to another page via the left nav. Change the **Language** via the language dropdown on the right. The page should redirect to translated current page instead of redirecting you to the previous page above
=> Fix Language Selection Bug - [WEB-5122]

content/en/getting_started/tagging/using_tags.md
- Remove references to outdated UI images. Most of the content is still correct and hyperlinks to the Logs docs which remains the source of truth.
- [DOCS-8422](https://datadoghq.atlassian.net/browse/DOCS-8422)
[DOCS-8422]: https://datadoghq.atlassian.net/browse/DOCS-8422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove references to outdated images

content/en/observability_pipelines/advanced_configurations.md
Adds which env vars have priority.
[DOCS-8278](https://datadoghq.atlassian.net/browse/DOCS-8278)
[DOCS-8278]: https://datadoghq.atlassian.net/browse/DOCS-8278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8278] Add configuration options ranking

content/en/logs/explorer/search.md
Hyperlink logs full-text search to the wikipedia definition of what a full-text search is.
[DOCS-8388](https://datadoghq.atlassian.net/browse/DOCS-8388)
Do not merge
[DOCS-8388]: https://datadoghq.atlassian.net/browse/DOCS-8388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add reference link for full-text search

content/en/tracing/metrics/metrics_namespace.md
https://datadoghq.atlassian.net/browse/DOCS-8345
Update trace metrics page to reflect the fact that in some cases, 100% of application traffic is NOT used for metrics. Pulled info from this Confluence page: https://datadoghq.atlassian.net/wiki/spaces/TS/pages/558104577/APM+Trace+metrics#Sampling-Impact-on-Trace-Metrics
=> Add details about sampling impact on trace metrics

layouts/shortcodes/asm-libraries-capabilities.md
Fix the Python version for the minimal Code Security supported version from "2.93" to "2.9.3".
=> Fix Python version in Python Code Security

content/en/sensitive_data_scanner/_index.md
Adds the excluded namespaces for SDS.
[DOCS-7354](https://datadoghq.atlassian.net/browse/DOCS-7354)
[DOCS-7354]: https://datadoghq.atlassian.net/browse/DOCS-7354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-7354] Add SDS excluded namespaces

content/en/continuous_integration/pipelines/teamcity.md
TeamCity configuration parameters should not have Password type
=> TeamCity configuration parameters should not have Password type

go.mod, go.sum
`websites-sources` version is out of date.  `HCP Terraform` integrations tile not surfacing as a result of this.
`HCP Terraform` tile is showing here: https://docs-staging.datadoghq.com/brian.deutsch/web-sources-bump/integrations/?q=hcp
Otherwise, no changes https://docs-staging.datadoghq.com/brian.deutsch/web-sources-bump/
=> Updates `websites-sources` module reference

content/en/security/threats/supported_linux_distributions.md
CWS now supports kernels 4.14 and higher. This PR improves the supported kernel support table to make it clearer which OS and kernels are supported.
=> [CWS] improve kernel version support table (4.14+)

content/en/cloud_cost_management/_index.md, layouts/shortcodes/learning-center-callout.html
Adds a front matter param to hide the image in the learning center callout
https://datadoghq.atlassian.net/browse/WEB-5081
- [] Please merge after reviewing
Preview
https://docs-staging.datadoghq.com/ccole/learning-center-callout-update/cloud_cost_management/
=> Conditionally hide image in learning center callout

content/en/service_management/incident_management/_index.md
This document is outdated. When an incident is declared by a Slack user without a connected Datadog account, the incident commander simply becomes unassigned- not 'Slack app user'. I also mentioned that users must enable anonymous declaration in settings before this is even possible. Open to feedback on that wording since the actual setting is named: **Allow users to declare incidents without a connected Slack account**
I removed some redundant copy as well.
Updating in response to a customer support [ticket](https://datadoghq.atlassian.net/browse/SOCE-1291) that was confused by the documentation here and the actual behavior of incidents declared from Slack.
=> Update incident commander assignment copy

content/en/opentelemetry/interoperability/instrumentation_libraries.md, content/en/tracing/trace_collection/compatibility/dotnet-core.md, content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Documents .NET drop in support for the OpenTelemetry API.
Note: We previously had this page in our regular tracing library compatibility page so most of the content was simply moved to this new central location.
=> opentelemetry(apm): document .NET drop in support

assets/scripts/components/async-loading.js
Removes `Maximum Call Stack Size` `RangeError`s on Integrations pages.
**motivation**: [Error Tracking](https://dd-corpsite.datadoghq.com/logs/error-tracking?query=service%3Adocs%20%22call%20stack%22&et-side=data&fromUser=true&issueId=cffc54dc-0e3a-11ef-8eb2-da7ad0900002&refresh_mode=sliding&source=all&track=rum&view=spans&from_ts=1722261305264&to_ts=1722347705264&live=true). also related [PR](https://github.com/DataDog/documentation/pull/23659)
- Selecting h1-h3 headers throws errors on `integrations` pages. 
- the error occurs because the popstate on the page is being triggered on anchor clicks
**preview**: https://docs-staging.datadoghq.com/stefon.simmons/fix-broken-anchors-max-call-stack-errs/integrations/guide/source-code-integration/?tab=net#host
- click on the h1-h3 headers. no …
=> removes Maximum Call Stack RangeErrors

content/en/tracing/trace_collection/library_injection_local.md
These configuration files have not seen much usage through the public beta. To minimize the surface area we are removing them for the GA launch. If the requirement arises then this functionality will be added back.
=> Remove documentation for SSI configuration files

content/en/opentelemetry/collector_exporter/configuration.md, content/en/opentelemetry/collector_exporter/otel_collector_datadog_exporter.md, content/en/opentelemetry/collector_exporter/otlp_receiver.md, content/en/opentelemetry/guide/migration.md, content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md, layouts/shortcodes/otel-endpoint-note.md
- Our configuration examples are missing the Datadog Connector and endpoints. Added where missing.
- The Configuration page in the left-nav is seemingly missing non-OOTB config. Copied content back into Configuration page. (Note: Need to clean up this duplicated content in another PR).
**Note for Docs reviewer**: The content in `/opentelemetry/collector_exporter/configuration.md` is not new. It's duplicated, so it doesn't need an editorial review.
=> Include Receiver Endpoints and Datadog Connector in Config Examples

content/en/tests/code_coverage.md
Let users know that there's an issue with using `all` option in `nyc` (see [nyc docs](https://github.com/istanbuljs/nyc?tab=readme-ov-file#common-configuration-options)).
https://docs-staging.datadoghq.com/juan-fernandez/add-known-limitation-to-nyc/tests/code_coverage/?tab=javascripttypescript#known-limitations
=> [test visibility] Add known limitation to code coverage for Javascript

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md, content/en/tracing/trace_collection/library_injection_local.md
The instrumentation has been updated to use the standard /var/run/datadog/ path for the unix sockets rather than a custom directory.
=> Fix docker instrumentation commands

content/en/agent/basic_agent_usage/_index.md, content/es/agent/basic_agent_usage/_index.md, content/fr/agent/basic_agent_usage/_index.md, content/ko/agent/basic_agent_usage/_index.md
=> (Agent) Fix GUI port

content/en/data_security/guide/tls_ciphers_deprecation.md
There was security discussion around [this article](https://jviide.iki.fi/http-redirects) re: returning an error rather than redirecting. Let's remove this wording until we have a concrete plan and new date.
=> remove https redirect wording

content/en/agent/configuration/dual-shipping.md
* Motivation : https://github.com/DataDog/datadog-agent/issues/27168
* Clarify how to avoid exposing api keys in clear text in configmap to dual-ship in Kubernetes
* Uses tabs to separate Helm/Operator configs
* Corrects the Operator config and provides an example
* Removes reference to `v1alpha1` operator config which is deprecated / removed in next Operator release
=> [Dual-shipping] Clarify Kubernetes-specific part, provide examples, correct nits

local/bin/py/build/actions/integrations.py
We add a method to process `metric-spec.yaml` files instead of the standard `csv` for generating the metric tables for docs. This is for an ongoing effort to replace the usage of csv files for integrations. We also create a method to reformat the metric spec yaml files into yaml files that are used by the `get-metric-from-git` partial.
https://datadoghq.atlassian.net/browse/AWSMC-1286
**Testing:** The `format_metric_spec_yaml()` was tested to make sure the reformatted yaml files were identical to the ones produced when generated from csvs.
=> Modify script for processing yaml metric spec

content/en/code_analysis/faq/_index.md, content/en/code_analysis/software_composition_analysis/generic_ci_providers.md
1. Our instructions to run `osv-scanner` can be confusing. We are updating them to avoid any confusion for our customers.
2. Windows is now supported, updating the FAQ for it.
=> Update instructions to run osv-scanner

data/partials/home.yaml
Adds a product tile for LLM Observability on the Docs Site home page.
=> DOCS-8441 Add Tile to Docs Home Page

local/bin/py/build/actions/workflows.py, local/bin/py/build/configurations/pull_config_preview.yaml
We think an issue with the source files in the Azure Network Workflows bundle is causing the build to run out of memory. This excludes the bundle to prevent the issue. Long-term, we'd like to stop generating these files and instead deep link to each action in the app.
I tested this on an older dd-source commit, but once a new PR is up, we should point this PR it at that branch instead for testing.
=> (Workflows) Exclude azure network bundle

layouts/shortcodes/dbm-mongodb-agent-setup-docker.md, layouts/shortcodes/dbm-mongodb-agent-setup-kubernetes.md, layouts/shortcodes/dbm-mongodb-agent-setup-linux.md
This PR updates DBM for MongoDB documentation to point user directly to the new DBM for MongoDB cluster view after setup.
=> [dbm] update dbm for mongodb doc to point user to the mongo cluster view

content/en/service_management/app_builder/build.md, content/en/service_management/app_builder/expressions.md
* Moves relevant expressions image (previously labeled as to do with "variables", which is wrong) to the expressions page.
* Adds a link from Build Apps to Expressions
=> (DOCS-8619) App Builder - move from build to expressions

content/en/monitors/guide/template-variable-evaluation.md
Clarifying that last_triggered_at_epoch is UTC based
https://datadoghq.atlassian.net/browse/MNTS-90869
Clarifying that last_triggered_at_epoch is UTC based, as that may be confusing if users are expected to route a notification at a certain time of day
=> MNTS-90869 - Update template-variable-evaluation.md

content/en/synthetics/platform/private_locations/_index.md
This commit adds an important Note message about the ordering of SSL certificates
=> Update _index.md to mention ordering of SSL certs

.gitlab-ci.yml, Makefile
this PR ensures we are always pulling in the latest data from `websites-sources` as part of the docs build.    Currently it's a manual process where we pull the latest module reference, commit it, and make a PR which needs to be reviewed by websites and docs.   There are PRs merged daily in `websites-sources` which contain relevant data (specifically to integrations at the moment).  We have seen questions and complaints about delays in integration tiles surfacing in the Docs site after publishing; this should address those issues.
One item to note is how this change affects local dev flow.   `go.sum` and `go.mod` need to be checked in due to the inclusion of `websites-modules`.   Running `make start` locally will download the latest from `websites-sources`, but may also cause changes to …
=> [web-5165] pin websites-sources module to main

content/en/opentelemetry/integrations/log_collection.md
Add docs for adding custom tags to OTel logs through the ddtags attribute. Corresponding collector docs: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34439
=> Add docs for ddtags in OTel logs

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md, content/en/real_user_monitoring/platform/connect_rum_and_traces.md, content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/ios.md, content/es/tracing/trace_collection/automatic_instrumentation/dd_libraries/ios.md, content/ko/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
Some customers get confused that `SessionDelegate` is something we provide from docs.
Made it explicit with name and `<` & `>`
=> docs: make clear delegate type explicit that it is customer type

content/en/monitors/types/cloud_cost.md
There was a recent support issue caused because this delay is not documented or otherwise clear to end users. They were comparing the values reported by the monitor to their own dashboards and metric explorer. This is also important if they use templated links to dashboards in their monitor template.
=> CCM add text on cost monitor evaluation delay period

content/en/database_monitoring/setup_postgres/aurora.md
As raised by support (and verified via [other docs](https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=helm)), `instances` should be on the same level as `init_config`. Other lines are indented properly.
=> DOCS-8586 - helm config indentation fix

.github/CODEOWNERS
- Updates the codeowner file to scope specific paths to webops platform
- Removes the dual codeowners from website build and configuration files
- Moves the webops platform section under the top docs/corpweb section (making things easier to navigate/find)
After incident web-incident-30 we discovered that the websites team had some blindspots as well as missing approvals from pull requests that altered the way build scripts run. Due to github limitations, if there are 2 codeowners for a file, it will accept an either/or approval instead of requiring both to merge. This is a first step in a larger remediation around how approvals are required.
=> Update to CODEOWNES scope

config/_default/config.yaml
specifies that `static/images` should be mounted to the `assets/images` directory in the hugo virtual filesystem before building files.
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5144
preview: e.g. https://docs-staging.datadoghq.com/stefon.simmons/rm-dup-mounted-images/account_management/audit_trail/
- check on pages with images. there should be no broken images on the page. 
- check that image `srcset` attribute file name is still [fingerprinted](https://gohugo.io/hugo-pipes/fingerprint/) (`attributes.14eb439122bddb3283b02721dea0ff5c.png`) for cache busting.
```html
```
- check that local build (`public/images`) has only fingerprinted images.
=> removes duplicate images in build folder - [WEB-5144]

layouts/partials/continuous_integration/ci-pipelines-getting-started.html
adjust `continuous_integration/ci-pipelines-getting-started` partial template styles
- instead of 3 `.row`s, have one `.row` with multiple columns
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5185
preview: https://docs-staging.datadoghq.com/stefon.simmons/logo-styling-fix-web5185
=> adjust logo grid rows and alignment - [WEB-5185]

content/en/service_management/case_management/create_case.md, content/en/service_management/case_management/create_notifications_and_third_party_tickets.md, content/en/service_management/case_management/projects.md, content/en/service_management/case_management/settings.md, content/en/service_management/case_management/troubleshooting.md
- Case management is not supported for US1-FED, but it's only stated on the parent page, which confused customers reading the child pages.
- https://datadoghq.atlassian.net/browse/DOCS-8646
=> Add alert, case management not supported on us1-fed

content/en/code_analysis/static_analysis_rules/_index.md
Adds the PHP ruleset names to the static analysis rulesets
Related:
https://github.com/DataDog/datadog-static-analyzer-rule-docs/pull/63
https://github.com/DataDog/datadog-static-analyzer-rule-docs/pull/64
https://github.com/DataDog/datadog-static-analyzer-rule-docs/pull/65
=> [STAL-2612] docs: add php ruleset names to static analysis rulesets

content/en/logs/guide/aws-eks-fargate-logs-with-kinesis-data-firehose.md
Add a note so users that are on the newer Kinesis Firehose plugin know to use the `kinesis_firehose` variable.
https://datadoghq.atlassian.net/browse/DOCS-8011
=> Add note about the newer plugin name variable

content/en/tracing/guide/ignoring_apm_resources.md
C++ tracer also writes user_agent instead of http.useragent
[APMS-12915](https://datadoghq.atlassian.net/browse/APMS-12915)
[APMS-12915]: https://datadoghq.atlassian.net/browse/APMS-12915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ignoring apm resource - user_agent - C++

content/en/security/application_security/threats/setup/compatibility/ruby.md
Update ASM Ruby Compatibility requirements with GraphQL, and also update the compatible Ruby versions/interpreters
=> Update ASM Ruby Compatibility requirements with GraphQL

config/_default/config.yaml
revert changes here: https://github.com/DataDog/documentation/pull/24466/files
- need to investigate issues with icons and some images not building locally
preview: https://docs-staging.datadoghq.com/stefon.simmons/revert-asset-mount-changes/
- [https://docs-staging.datadoghq.com/stefon.simmons/revert-asset-mount-changes/account_management/audit_trail/](https://docs-staging.datadoghq.com/stefon.simmons/revert-asset-mount-changes/account_management/audit_trail/)
- https://docs-staging.datadoghq.com/stefon.simmons/revert-asset-mount-changes/account_management/org_settings/cross_org_visibility/
check that images including icons are loading locally and in preview
=> revert #24466 - fix local image builds 

content/en/code_analysis/static_analysis/generic_ci_providers.md
Add clarification for diff-aware scanning:
- first scan always a full scan
- all scans on default branch are full scans
- enabled by default for github actions
=> Clarification for diff-aware scanning

content/en/opentelemetry/schema_semantics/hostname.md
Clarifies in what order resource attributes are used to determine hostnames. Make sure to mention that these are 'resource attributes' explicitly everywhere. Relates to OTELS-306
=> [OTELS-306][opentelemetry] Clarify in what order resource attributes are used to determine hostnames

assets/scripts/config/regions.config.js, content/en/cloud_cost_management/custom.md
Removed the tabs so we can use the dynamic site region selector for the API endpoints in the code snippets in the Configure Custom Costs section.
When you click `US3` in the site region selector, the values for `api.datadoghq.com` should change to `api.us3.datadoghq.com/api/v2/cost/custom_costs` in the code snippets.
Discussion with Natasha and Dave on Slack
=> DOCS-8682 Custom Costs Update

layouts/partials/nav/left-nav-api.html
Fixes the left nav for `/ja/` api site. string.TrimLeft was cutting off too much of the relpermlink. 
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5181
preview: https://docs-staging.datadoghq.com/stefon.simmons/left-nav-ja/ja/api/latest/
- check that the left nav opens for diff lang sites (ja, ko, en etc.)
=> fixes `/ja` API left sub nav - [WEB-5181]

content/en/serverless/step_functions/troubleshooting.md
Added a new bullet that mentions how to enable trace generation at the forwarder-level for Step Functions
=> Update SF Troubleshooting Page

content/en/agent/basic_agent_usage/windows.md
This PR re-works the "Basic Agent Usage" page for Windows to emphasize the 2 different critical pathways a customer can take to install the Datadog Agent.
Therefore, it de-emphasizes the importance of installing via GUI or command line by removing them from the tabs and instead replacing them with the `Standard` installation and `Domain` installation.
Some simple steps to setup a `Group Managed Service Account` was added, and this can be moved to its own guide if necessary.
=> Improve the Windows Agent docs

content/en/serverless/guide/serverless_warnings.md
This PR adds three new serverless warnings to our docs: overallocated provisioned concurrency, under provisioned, and deprecated runtime. These three warnings will be added to the UI shortly after this docs update.  
The overallocated provisioned concurrency warning is generated when provisioned concurrency utilization for a function is consistently below 60% and can help customers optimize their functions for cost.
The under provisioned warning is generated when a function's CPU utilization consistently averages above 80%.
The deprecated runtime warning is generated when a function is using a deprecated runtime as outlined in https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-deprecated.
=> [SVLS] Add descriptions for three new serverless warnings 

layouts/shortcodes/aws-resource-collection.md
Fix a missing permission for AWS resource crawler.
=> docs(aws): Adding GetRuleGroup for wafv2

content/en/observability_pipelines/_index.md
=> Add links to component docs in OP landing page

content/en/synthetics/browser_tests/_index.md
Remove recorder support for edge browsers as this is something we cannot provide support for. 
N/A
N/A
=> revert docs page -> remove edge support

local/bin/py/build/actions/integrations.py
We want metric specs files to no longer be in the base directory but in the `assets/metrics/` directory. This PR changes the captured file path to find `metric-spec.yaml`. 
```
>>> glob.glob(f"{dirname(file_name)}{sep}**{sep}metric-spec.yaml", recursive=True)
['./amazon_network_manager/assets/metrics/metric-spec.yaml']
PREVIOUS
>>> glob.glob("{path}{sep}*metric-spec.yaml".format(path=dirname(file_name), sep=sep))
[]
```
=> update glob capture for metric specs

.github/CODEOWNERS
We need a catch-all to make sure webops own the rest of the local directory.
=> (maint) Fix codeowners for local

content/en/code_analysis/faq/_index.md, content/en/code_analysis/software_composition_analysis/generic_ci_providers.md, content/en/code_analysis/static_analysis/generic_ci_providers.md, content/en/code_analysis/static_analysis/setup.md
Removing the `--service` and `--env` switches for code analysis products as they are no longer used.
=> Removing `--env` and `--service` for code analysis products

layouts/shortcodes/dbm-mongodb-agent-beta-install-docker.md, layouts/shortcodes/dbm-mongodb-agent-beta-install-kubernetes.md, layouts/shortcodes/dbm-mongodb-agent-beta-install-linux.md, layouts/shortcodes/dbm-mongodb-agent-setup-docker.md, layouts/shortcodes/dbm-mongodb-agent-setup-kubernetes.md
This PR bumps up dbm for mongodb beta agent to `7.57.0-dbm-mongo-1.5`
=> [dbm] bump up dbm for mongodb beta agent version

content/en/synthetics/browser_tests/_index.md
Add in extra note to let users know that HTTP Basic authentication can be used for websites that request user credentials via a browser system prompt
=> Update _index.md to include a note saying HTTP Basic can be used for prompts that request user credentials

content/en/cloud_cost_management/saas_costs.md
Fix tab order of Elastic Cloud for consistency between config and data collected sections. This does not include any text updates. 
=> Consistent tab order for CCM integrations 

content/en/getting_started/tracing/_index.md, content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md, content/en/tracing/trace_collection/library_injection_local.md, static/resources/sh/data_jobs/datadog_emr_job_monitoring_init_v2.sh
This will pin users copying the commands to the latest major version of the libraries. This will give the user automatic fixes and features without the risk of breaking changes.
[](https://datadoghq.atlassian.net/browse/APMON-1258)
=> Pin the APM libraries to major versions

content/en/security/application_security/_index.md
Add a section on Code Security to the Application Security Management homepage. Code Security is only present in the navigation, but being one of the major branches of this product, it should be more visible from the homepage.
Copy provided by @gorkavicente.
=> Add IAST section to ASM homepage

content/en/coscreen/_index.md, content/en/service_management/incident_management/_index.md
You can launch CoScreen meetings from an incident details page. This PR adds this information to both the CoScreen page and the Incident Management index page.
=> adding integration between coscreen an incident management

layouts/partials/cloud_cost/cost-integrations.html
Breaking up the line of 8 integration tiles into two rows of 4 for clarity.
Chat with Kari on Slack
docs-staging.datadoghq.com/alai97/saas-cost-integrations-image-sizing/cloud_cost_management/saas_costs
=> Separate SaaS Cost Integrations Partial Into Two Rows

content/en/service_management/app_builder/queries.md
Adds the order of operations for query execution.
=> (DOCS-8707) - query order of operations

content/en/code_analysis/_index.md
No content is being changed in this update. We are shuffling the header sections around to show users the Setup instructions first (like setting up the repository, setting up GitHub integration, using IDE integrations, and then looking at the scan results) as opposed to what it is now (in a different order).
> What I'm hearing is that customers aren't finding info on DD hosted scans, so maybe find a way to push it upward in the page, or put it in a heading?
Chat with Kari on Slack
=> Code Analysis Documentation Edit

content/en/containers/amazon_ecs/_index.md, content/es/containers/amazon_ecs/_index.md, content/fr/containers/amazon_ecs/_index.md, content/ja/containers/amazon_ecs/_index.md, content/ko/containers/amazon_ecs/_index.md
fips-proxy has [released 1.1.4](https://github.com/DataDog/fips-proxy/releases/tag/1.1.4) and this PR updates the respective documentation to mention that version instead of 1.1.3
=> [ASCII-2204] Update the fips-proxy version to latest 1.1.4 release in docs

content/en/service_management/app_builder/components/_index.md, content/en/service_management/app_builder/events.md
* Documents tab and text area components on Components page
* Adds related content to Events page
* Adds event reaction item to misc places on Components page where there is a new option
=> (DOCS-8744) - document App Builder tab and text area components

content/en/dora_metrics/deployments/deployment_api.md
Remove service validation for DORA deployments from APIs
=> Remove service validation for DORA deployments from APIs

content/en/continuous_integration/troubleshooting.md
Gitlab variables sometimes do not get reported to us due to a Gitlab bug. Added a troubleshooting section referring the gitlab issue.
=> [ci-visibility] Add troubleshooting section for missing gitlab variables

content/en/network_monitoring/devices/snmp_traps.md
Adding back the Agent version required for v3 multiple user setup for SNMP traps as it was inadvertently removed.
=> [DOCS-8738] adding supported Agent version for v3 traps

content/en/database_monitoring/database_hosts.md
Remove a reference to an image that isn't in the repo. I wrote the original PR that introduces the issue, and both images were still on my machine. In looking at them, it seems one image was intended to replace the other, they have nearly identical contents but the one I've kept in this PR includes an expanded details pane.
DOCS-8755
=> Remove reference to missing image

content/en/code_analysis/software_composition_analysis/_index.md, layouts/partials/code_analysis/languages-getting-started.html, layouts/partials/code_analysis/sca-getting-started.html
Add a language partial for the SCA product landing page + adjusts the TS size for Static Analysis partial.
Received feedback that the bulleted list of supported languages was confusing on the [SCA landing page](https://docs.datadoghq.com/code_analysis/software_composition_analysis/#set-up-software-composition-analysis) so we are adding a partial here to display the supported languages for SCA, which is different from Static Analysis.
=> DOCS-8729 Software Composition Analysis Update

content/en/logs/guide/azure-logging-guide.md
adding small note of clarification, due to customer suggestion.
this PR adds a small note that clarifies a type of log that is not able to be sent to datadog via the native process, per a customer request:
"Specifically this verbiage: "Configuration is done through the [Datadog resource in Azure](https://learn.microsoft.com/en-us/azure/partner-solutions/datadog/overview). This replaces the Azure Event Hub process for log forwarding. See the [Azure Native Logging Guide](https://docs.datadoghq.com/logs/guide/azure-native-logging-guide/) for more information." 
That led me to believe I can just get logs from my Log analytics workspace directly into Datadog without using event hub."
=> small note added azure-logging-guide.md

content/en/integrations/nxlog.md
- TCP is not supported for US5 or AP1 regions
- [DOCS-6643](https://datadoghq.atlassian.net/browse/DOCS-6643)
[DOCS-6643]: https://datadoghq.atlassian.net/browse/DOCS-6643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add alert that TCP is not supported for US5 or AP1

content/en/account_management/billing/aws.md
The current wording doesn't explain that the tags set in the Limit Metric Collection correspond with tags set on the AWS resource. This has led to confusion with customers and I think specifying that the tags need to be set on the AWS tile **and** on the AWS resource(s) would help prevent confusion.
=> Update AWS Resource Exclusion Wording

content/en/containers/kubernetes/tag.md
DOCS-8739
updates the Agent version number that supports namespace labels as tags.
=> change Agent version for namespace labels support

layouts/shortcodes/svl-init-dotnet.md
This should follow changes made here: https://github.com/DataDog/datadog-lambda-extension/pull/366 
https://docs-staging.datadoghq.com/dylan/sls-init-dotnet/serverless/google_cloud_run/?code-lang=dotnet
=> [SVLS-5280][incident-29739] Update docs to simplify serverless-init .NET tracer installation

content/en/logs/log_configuration/flex_logs.md
Flex Logs Starter will be the only compute that can be enabled as part of the GA but there are no docs that describes what it is in the docs. It’s a bit of a unique case compared to the other sizes since the pricing for it is a single, bundled volume + compute cost vs the decoupled cost of everything else.
=> Add Flex Logs Starter to docs

content/en/serverless/step_functions/installation.md
Clarify that `DD_TRACE_ENABLED` is a _tag_ on StepFunctions, and `DD_STEP_FUNCTION_TRACE_ENABLED` is an environment variable on the forwarder.
=> Fix StepFunction DD_TRACE_ENABLED

Makefile
Bump the version of assetlib that was created as a part of https://datadoghq.atlassian.net/browse/ECOS-1473
The GitLib job where assetlib was created can be found here: https://gitlab.ddbuild.io/DataDog/dd-source/-/jobs/613674229
=> [ECOS-1473] Bump AssetLib

content/en/logs/log_collection/javascript.md
- Customer noticed a parameter `sendLogsAfterSessionExpiration` from this [PR](https://github.com/DataDog/browser-sdk/pull/2578) was missing from the public docs.
- [DOCS-8603](https://datadoghq.atlassian.net/browse/DOCS-8603)
Do not merge: Pending Product team review
[DOCS-8603]: https://datadoghq.atlassian.net/browse/DOCS-8603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Browser Log parameter

content/en/network_monitoring/performance/network_analytics.md
I inadvertently replaced this diagram with a different one in a previous PR, but this diagram is still needed, so adding it back with some additional verbiage.
Note: this diagram was already/still in the `/static/images` folder at this location so there was no need to commit it to this branch.
=> [DOCS-8436] adding back image to network analytics

content/en/monitors/types/error_tracking.md
We're adding "unified" template variables to Error Tracking monitors.
This PR adds the list of additional template variables available for alert messages for Error Tracking monitors only.
The backend's not deployed yet, please don't merge upon approval.
Will explicitly ask for it, thanks.
=> Add list of new template variables available for Error Tracking monitor alert message

content/en/tracing/configure_data_security/_index.md, content/en/tracing/trace_collection/custom_instrumentation/cpp/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/dotnet/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/dotnet/otel.md, content/en/tracing/trace_collection/custom_instrumentation/nodejs/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/php/dd-api.md, content/en/tracing/troubleshooting/_index.md
- error.msg is now error.message.
- Replace remaining references in the docs.
=> Replace error.msg attribute with error.message

content/ja/logs/guide/best-practices-for-log-management.md
DOCS-8769. 
A problem was reported with the anchor links not working in the Japanese Best Practices for Logs article. In Transifex, the links were already reviewed; however, the actual anchor links are still in English. I unreviewed the strings and added a comment asking for the anchor links to be translated into Japanese. In the meantime, this PR is to fix the anchor links while we wait for the translators to update the doc.
Staging preview: https://docs-staging.datadoghq.com/deforest/fix-anchor-links-ja-docs/ja/logs/guide/best-practices-for-log-management
=> Fix anchor links in Best Practices for Logs Japanese docs

content/en/code_analysis/software_composition_analysis/generic_ci_providers.md, content/en/code_analysis/software_composition_analysis/setup.md, content/en/code_analysis/static_analysis/generic_ci_providers.md, content/en/code_analysis/static_analysis/setup.md
We've added a new application scope, `code_analysis_read`, for both products, Static Analysis and Software Composition Analysis.
=> [STAL-2778] Include details about new app key scopes

content/en/serverless/step_functions/enhanced-metrics.md
The `aws.states.enhanced.task.execution.tasks_timed_out` enhanced metric isn't implemented in the Reducer
Removing from our docs until we add this feature
=> Remove un-implemented metric

content/en/tests/setup/dotnet.md, content/en/tests/setup/java.md, content/en/tests/setup/javascript.md, content/en/tests/setup/python.md, layouts/shortcodes/ci-autoinstrumentation.md
This patch adds documentation for GitLab and CircleCI test visibility autoinstrumentation. This also unifies this new docs with the existing GitHub actions + Jenkins autoinstrumentation docs.
**This won't be merged until we've released the CircleCI autoinstrumentation**
=> [SDTEST-592] Add documentation for GitLab+CircleCI autoinstrumentation

content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md
Removes the View Related Metrics entry from the CSM Vulnerabilities troubleshooting page.
=> Remove view related metrics from CSM Vulnerabilities troubleshooting

content/ja/integrations/container.md, content/ja/integrations/network.md, content/ja/integrations/process.md, layouts/shortcodes/integrations.html
https://datadoghq.atlassian.net/browse/WEB-5256
Fixes 3 integrations that are linking to non existing pages because they are using the translation in the url
Updates the template to also rely on the english name for the url, so this won't matter if this comes back in the future.
Clicking the tile in the results should go to a page:
https://docs-staging.datadoghq.com/david.jones/web-5256/ja/integrations/?q=%E3%83%97%E3%83%AD%E3%82%BB%E3%82%B9
The following links should work
https://docs-staging.datadoghq.com/david.jones/web-5256/ja/integrations/container/
https://docs-staging.datadoghq.com/david.jones/web-5256/ja/integrations/network/
https://docs-staging.datadoghq.com/david.jones/web-5256/ja/integrations/process/
=> WEB-5256 - Fix names for links on ja integrations

assets/scripts/components/algolia/getHitData.js, assets/scripts/components/algolia/searchbarHits.js, assets/scripts/components/algolia/searchpageHits.js, layouts/_default/list.algolia.json, local/bin/js/algolia-index-sync.js
https://datadoghq.atlassian.net/browse/WEB-5210
Currently we show search results down to the section which doesn't always make sense.  For example, [this search](https://docs.datadoghq.com/search/?s=azure) for `Azure`, it's leading the user to the `Troubleshooting` section which doesn't make sense based on their search. 
Discussed w/ the team and we felt like these results are likely providing more confusion than value to the customer.
This PR is removing all section results in favor of showing full page results in the UI to remove any confusion.
https://docs-staging.datadoghq.com/brian.deutsch/web-5210-section-results/search/?s=azure
https://docs-staging.datadoghq.com/brian.deutsch/web-5210-section-results/search/?s=unified%20service%20tags
=> [web-5210] remove sections from docs search links

content/en/containers/kubernetes/prometheus.md
Corrects example in documentation to use string type. This matches the example found [here](https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/datadog-agent-with-prometheus-autodiscovery-advanced-config.yaml#L10).
=> Switch additionalConfigs to string

content/en/integrations/guide/cloud-metric-delay.md
Change the Cloudflare metric delay documentation amount
Customers are confused about the metric delays so we are updating it to the correct information
=> [SAASINT-2703] Update metric delay documentation

content/en/containers/guide/auto_conf.md
Main motivation we currently have the duplicate "Datadog Operator" and "Operator" tab. So remove the "Operator" tab. Also renamed the "DaemonSet" to "Containerized Agent" to better match manual DaemonSet, Docker, or ECS setups. 
See live doc: https://docs.datadoghq.com/containers/guide/auto_conf/?tab=datadogoperator#disable-auto-configuration
Preview doc: https://docs-staging.datadoghq.com/jack.davenport/adjust_ignore_tabs/containers/guide/auto_conf
=> Adjust tabs for DD_IGNORE_AUTOCONF examples

content/en/account_management/billing/usage_monitor_apm.md, content/en/agent/basic_agent_usage/windows.md, content/en/getting_started/monitors/_index.md, content/en/infrastructure/process/_index.md, content/en/monitors/manage/status.md, content/en/monitors/types/anomaly.md, content/en/monitors/types/apm.md, content/en/monitors/types/composite.md, content/en/monitors/types/event.md, content/en/monitors/types/forecasts.md, content/en/monitors/types/host.md, content/en/monitors/types/integration.md, content/en/monitors/types/log.md, content/en/monitors/types/network.md, content/en/monitors/types/process.md, content/en/monitors/types/process_check.md, content/en/monitors/types/watchdog.md, content/en/real_user_monitoring/guide/monitor-your-rum-usage.md, content/en/service_management/service_level_objectives/guide/slo-checklist.md, content/en/service_management/service_level_objectives/monitor.md
- Noticed that monitors links using the old `monitors#create` were not redirecting to the current `monitors/create` page.
- Replaced any references in the docs using the old URL to the new URL
=> Replace monitors#create with monitors/create url link

content/en/real_user_monitoring/error_tracking/mobile/expo.md, content/en/real_user_monitoring/error_tracking/mobile/reactnative.md
This PR fixes some typos on the React Native and expo docs:
- Write `source map(s)` instead of `sourcemap(s)` to remain consistent with Web UI
- Use "debug symbols" as a generic term
=> Fix debug symbols typos related to React Native

content/en/profiler/enabling/go.md, content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/go.md
Orchestrion adds code to start the continuous profiler to Go programs.
It needs to be enabled at run time by setting the
`DD_PROFILING_ENABLED=true` environment variable. Explain this in both the
Orchestrion and profiler doc pages.
=> Explain how to enable profiling for Go programs built with Orchestrion

content/en/serverless/step_functions/installation.md
Our installation docs say to use `DD_STEP_FUNCTION_TRACE_ENABLED` when it should be `DD_STEP_FUNCTIONS_TRACE_ENABLED`
=> Fix env var typo

content/en/real_user_monitoring/browser/setup.md
Updates the beta flag text so it doesn't look like the entire setup page is in private beta, as per [DOCS-8778](https://datadoghq.atlassian.net/browse/DOCS-8778).
[DOCS-8778]: https://datadoghq.atlassian.net/browse/DOCS-8778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Browser injection beta flag text

content/en/dashboards/functions/timeshift.md
Reflecting some product changes in the documentation:
- calendar_timeshift is now available everywhere
- explain better the arguments and their possible values
- reorder the page content to make calendar_timeshift more visible
- "before" functions are being deprecated (except hour_before)
=> Update Timeshift docs with "before" functions deprecation

content/en/profiler/profile_types.md, content/en/profiler/profiler_troubleshooting/java.md
Adds a section about adjusting the subsampling rate for live heap profiling in the troubleshooting guide.
Related to [PROF-10303]
This also subsumes changes from #18743 and makes the profile type format for Java compatible with other runtimes
[PROF-10303]: https://datadoghq.atlassian.net/browse/PROF-10303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Mention the Java liveheap subsampling in troubleshooting

content/en/tracing/trace_collection/compatibility/java.md
The documentation for building native binaries from Java apps using Graal neglects to mention an environment variable that _must_ be set to enable the profiler in native mode. This updates the documentation for affected `dd-trace-java` versions.
=> Update native image build instructions

content/en/real_user_monitoring/guide/proxy-rum-data.md
- Adds a note about needing to use the `\` escape character when setting up a RUM alternative proxy JSP web apps, as per [DOCS-8726](https://datadoghq.atlassian.net/browse/DOCS-8726).
[DOCS-8726]: https://datadoghq.atlassian.net/browse/DOCS-8726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note about JSP apps for RUM proxy config

content/en/logs/guide/best-practices-for-log-management.md
A section "Alert when an indexed log volume passes a specified threshold" refers to the down arrow next to Download as CSV but in UI there is "More..." button instead.
In reality:
=> Updated best-practices-for-log-management.md

content/en/logs/guide/control-sensitive-logs-data.md
This PR updates the documentation to correct an error which states that using NOT in a sensitive outline query would allow using to see anything but matching logs but using NOT actually means the opposite. Users can see all logs that do not match this query.  
Incorrect:
Note: Using NOT in the sensitive outline query restricts users from seeing anything BUT matching logs.
=> Update control-sensitive-logs-data.md to rectify NOT query wording

content/en/agent/configuration/agent-commands.md, content/en/containers/cluster_agent/_index.md
The motivation started with a [customer Zendesk ticket](https://datadog.zendesk.com/agent/tickets/1795585). The feedback there was there was confusion about getting the status of the Cluster Agent. The user expected to see the Datadog Cluster Agent integration there.
This update provides:
- A link from the Agent Status documentation to the Cluster Agent documentation
- A section in the Cluster Agent documentation clarifying how we monitor the Cluster Agent using the integration, and
- A link to the Cluster Agent integration documentation.
I'm also editing the Cluster Agent integration docs to provide similar information
=> Add context to cluster agent commands

static/config/99datadog-windows.config
The example for dd-trace-dotnet was hardcoded. 
Since there's no "latest" msi endpoint today, it needs to be updated manually but the previous example didn't make that clear. 
I updated the instructions to make it clear to find the applicable msi, and also explain that `02_setup-APM1` and `03_setup-APM2` are just examples for tracing IIS.
=> Update 99datadog-windows.config example

content/en/llm_observability/quickstart.md
The quickstart is the main entrypoint for people using LLM Obs. Customers tend to copy & paste env var setup from examples. We added `DD_LLMOBS_AGENTLESS_ENABLED` to the quickstart command because someone running the quickstart script locally may not have the agent up and running. 
Add a clarification so that they don't set env var in production environments where the agent is running
=> [ML-OB] clarify agentless env var

content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/codepush.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/expo.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/roku.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/unity.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/reactnative.md
Moves the "Sending data when device is offline" section from Troubleshooting to Setup for all mobile SDK pages and adds to them if they weren't there before, as per [DOCS-8447](https://datadoghq.atlassian.net/browse/DOCS-8447).
[DOCS-8447]: https://datadoghq.atlassian.net/browse/DOCS-8447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8447] Move Sending data for offline devices section

content/en/logs/log_collection/_index.md, content/en/logs/troubleshooting/_index.md
- Add a note about truncated messages on indexed logs.
- [DOCS-8336](https://datadoghq.atlassian.net/browse/DOCS-8336)
- Do not merge, waiting for eng approval
[DOCS-8336]: https://datadoghq.atlassian.net/browse/DOCS-8336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a note about truncated message on indexed logs

content/en/real_user_monitoring/guide/best-practices-for-rum-sampling.md
Sample rate is specified as a range between 0 to 1 in the best practice article, but the actual code and documentation specifies it as a range between 0 to 100.
This change aligns the numbers to be consistent.
N/A
=> Use correct sample rate range in RUM docs

content/en/tests/setup/javascript.md
Cypress does not support autoinstrumentation, as it does not work with NODE_OPTIONS, so we are adding a note for this.
=> [test-visibility] do not offer auto instrumentation for cypress

content/en/database_monitoring/setup_mongodb/mongodbatlas.md
Fixed a typo where "Sharded cluster" is mentioned in the Replica Set tab
The PR is to fix a typo where the word "Sharded cluster" is used instead of "Replica set"
=> Fix sharded cluster reference for Replica Set --  mongodbatlas.md

content/en/logs/log_collection/javascript.md
Documentation is missing closing bracket in example code
=> Add missing closing bracket

content/en/tracing/trace_collection/compatibility/java.md
Adds troubleshooting information for a known bug with GraalVM Native Images causing the Java tracer and profiler to (silently) misconfigure
If this looks good stylistically, please merge. Feedback on clarity and conciseness are welcome.
=> Added documentation for system properties not working in Graal native images

content/en/account_management/rbac/granular_access.md
- Adds Security Suppressions to the table
- Fixes the link to Detection Rules' permissions section
[DOCS-8925](https://datadoghq.atlassian.net/browse/DOCS-8925)
[DOCS-8925]: https://datadoghq.atlassian.net/browse/DOCS-8925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8925] Add suppressions to table and fix detection rule link

content/en/real_user_monitoring/browser/setup.md
It appears that the site setting is not required. This PR corrects that misunderstanding.
=> rum: change `site` to an optional setting

content/en/opentelemetry/interoperability/instrumentation_libraries.md
Updates the minimum required version for otel drop in support for dd-trace-go to 1.67.0. Span events was added in 1.67.0.
Context: https://datadoghq.atlassian.net/browse/APMAPI-167 and https://github.com/DataDog/dd-trace-go/pull/2780
=> Update minimum version of dd-trace-go for otel dropin support to 1.67.0

content/en/agent/configuration/network.md
Kubelet checks connect to the localhost only.
=> remove kubelet from outbound network connections

content/en/opentelemetry/agent/install_agent_with_collector.md
* Add `datadog.site` config to the Agent example config
* Add `exporters.datadog.api.site` config to the OTel Collector config
* Remove K8S instructions (outside of the scope of the OTel docs)
The following doc is private -- the Datadog Agent with embedded OpenTelemetry Collector is in private beta.
=> Add Datadog intake to the agent and collector configs

content/en/tracing/trace_collection/custom_instrumentation/dotnet/otel.md, content/en/tracing/trace_collection/custom_instrumentation/go/otel.md, content/en/tracing/trace_collection/custom_instrumentation/nodejs/otel.md, content/en/tracing/trace_collection/custom_instrumentation/php/otel.md, content/en/tracing/trace_collection/custom_instrumentation/python/otel.md, content/en/tracing/trace_collection/custom_instrumentation/ruby/otel.md
Documents support for OTEL SpanEvents and provides examples of how to use the APIs so that OTEL users can simply add then to their spans and view in DD.
=> Documenting Current Support for Span Events

config/_default/params.yaml
Removing a YAML key that is causing parse errors in the customizable docs project. The removal should have no impact, as the removed key was being overwritten by another instance of the same key later in the block.
I verified this change with websites first, see the [Slack thread](https://dd.slack.com/archives/C3CT8QA11/p1725644441643029).
=> Remove duplicate key in site params YAML

content/en/real_user_monitoring/guide/monitor-kiosk-sessions-using-rum.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/data_collected/android.md
Adds the missing APIs for Android SDK to the following pages, as per [DOCS-8447](https://datadoghq.atlassian.net/browse/DOCS-8447):
- https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/android/?tab=kotlin
- https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android/?tab=kotlin
- https://docs.datadoghq.com/real_user_monitoring/guide/monitor-kiosk-sessions-using-rum/?tab=android
Should be validated by the RUM mobile team prior to merging.
[DOCS-8447]: https://datadoghq.atlassian.net/browse/DOCS-8447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8447] Add missing APIs for Android SDK

content/en/tracing/metrics/metrics_namespace.md
Customer support ticket which identified that the formula for calculating the average latency with host tag filters is not up-to-date.
Flagged by Yoshiya on #documentation Slack
=> Metrics Namespace Edit

content/en/profiler/enabling/dotnet.md
Removes the profiling SSI enablement instructions for .NET, as this scenario isn't yet supported
=> [Profiling][.NET]Remove single-step instrumentation tab from .NET Profiler instructions

content/en/security/application_security/serverless/_index.md
DOCS-8949
revised references to files inside the dd-lib-{js,dotnet}-init container images.
Updated the ASM Serverless docs so that they are inline with the corresponding APM doc and do not instruct users to ref files inside dd-lib-{js,dotnet}-init container images.
=> DOCS-8949 revised dd-lib-{js,dotnet}-init refs

content/en/data_jobs/kubernetes.md
This PR updates the extraJavaOption parameter following a discussion on [E2E Pipeline Visibility](https://docs.google.com/document/d/1n_UgcWS_r8mY1OSJgRpGujCOQuc_o5pxXyYtoJcaKVI/edit) in DJM. The option now used is the new `DD_DATA_JOBS_ENABLED` and the line that disabled all other dd integrations is removed, so that S3 spans are collected.
The spark conf are duplicated from the `driver` to the `executors` to inject the tracer on that side as well, which is required to collect the execution spans.
=> Update DJM k8s documentation to enable all integrations

content/en/security/application_security/_index.md
in the product we have a URL that directs to non-existing page: https://docs.datadoghq.com/security/application_security/getting_started/
The frontend team will change this URL to this one — https://docs.datadoghq.com/security/application_security/.
So I'm adding the redirect for now.
=> adding a redirect for a product URL

content/en/tracing/trace_collection/library_config/java.md
https://datadoghq.atlassian.net/browse/DOCS-8566
Add information about `dd.grpc.client.error.statuses` and `dd.grpc.server.error.statuses`
=> Add grpc parameters

content/en/security/cloud_security_management/agentless_scanning/_index.md, content/en/security/cloud_security_management/agentless_scanning/deployment_methods.md, content/en/security/cloud_security_management/setup/agentless_scanning/cloudformation.md, content/en/security/cloud_security_management/setup/agentless_scanning/terraform.md
Fixes a couple of broken links in Further Reading sections. These links were relics from a previous version of the docs info architecture (albeit, one that was never actually published). Just to be safe, I added aliases for the broken links.
These were the two links that were broken (should now redirect):
- https://docs.datadoghq.com/security/cloud_security_management/guide/agentless_aws_integration
- https://docs.datadoghq.com/security/cloud_security_management/guide/agentless_terraform
=> Fix links and add aliases

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/java.md
The previous changes suggested were not the recommended way to pass environment variables to Tomcat according to the documentation here: https://github.com/apache/tomcat/blob/main/bin/catalina.bat which says:
WHEN RUNNING TOMCAT AS A WINDOWS SERVICE:
...
The configuration that controls Windows Services is stored in the Windows Registry, and is most conveniently maintained using the "tomcat@VERSION_MAJOR@w.exe" maintenance utility.
I tried my best to format the instructions as previously done but feel free to edit so it is more inline with how we write documentation.
Current instructions on how to trace tomcat services running as Windows Services are incorrect
=> Changes to Tracing Tomcat as a Windows Service

content/en/opentelemetry/agent/agent_with_custom_components.md, content/en/opentelemetry/agent/install_agent_with_collector.md, content/en/opentelemetry/agent/migration.md
Replace the Agent `datadog/agent-dev:nightly-*` images with the stable `datadog/agent:7-ot-*` images.
Following docs are private -- the Agent with embedded OTel Collector is in Private Beta
=> [Private Beta] Use the stable images for the Agent with embedded OTel Collector

content/en/ddsql_editor/reference/tags.md
This PR removes references to `metrics` tables and `aggr` syntax from the public docs. The `metrics` data source is not exposed by default, and `aggr` is an internal-only syntax in the process of being deprecated.
=> remove references to aggr and metrics from DDSQL Editor docs

content/en/real_user_monitoring/explorer/_index.md
Add the following sentence in the "Search and filter" section
> Use autocomplete suggestions to view facets and recent queries.
As per the case https://datadog.zendesk.com/agent/tickets/1843523 where customer highlighted they did not see details as to how the suggestion work in RUM explorer
=> add autocomplete statement in Search

content/en/continuous_integration/pipelines/jenkins.md
Updates Datadog Jenkins plugin configuration instructions.
The plugin may be configured to report the data - including job logs - to Datadog Agent.
In this case additional configuration changes need to be done in the Agent config.
This PR adds a reference to the relevant Agent documentation page.
=> Jenkins plugin configuration: add a reference to custom log collection config in DD Agent

content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/expo.md
Adds a missing quote around EU1 in code example
There was a missing double quote in the code example for setting up an Expo app
=> Fix simple typo

content/en/error_tracking/frontend/_index.md, content/en/error_tracking/frontend/logs.md
Adds an alias to the standalone error tracking docs that didn't have one.
=> add alias to standalone frontend

content/en/cloud_cost_management/recommendations/_index.md
Add Algolia search tags to the Cloud Cost Recommendations doc page.
User reported that this page was not appearing in the search results on the Docs Site.
=> DOCS-9011 Cloud Cost Recommendations Edit

content/en/real_user_monitoring/platform/connect_rum_and_traces.md
Motivation would be [this support ticket](https://datadog.zendesk.com/agent/tickets/1843263). A customer thought that setting UST parameters like service wasn't supported for the CDN installation method because they were commented out.
Our [primary installation instructions](https://docs.datadoghq.com/real_user_monitoring/browser/setup/#npm) have these optional parameters commented out for all installation methods. The goal of the change is to be consistent with the primary installation instructions so customers don't read too deeply into the examples thinking there should be a difference when one isn't explicitly noted.
=> Update npm installation example code

content/en/dora_metrics/deployments/deployment_api.md
Adding a line [to this page](https://docs.datadoghq.com/dora_metrics/deployments/deployment_api/?tab=apicurl) about optionally adding `team` to a request . This api currently accepts the attribute but it is not shown in the docs.
=> SDCD-415: updating dora deployment documentation to clarify the optional `team` attribute

layouts/partials/continuous_integration/ci-pipelines-getting-started.html
Refactors CI Visibility provider partial + replaces Azure DevOps icon with the Azure Pipelines icon.
https://docs-staging.datadoghq.com/alai97/update-azure-icon/continuous_integration/#increase-efficiency-through-seamless-integrations
=> DOCS-8724 CI Visibility Partial Update

content/en/monitors/guide/template-variable-evaluation.md
There is a bug where `is_match` currently does a conversion of strings that are numeric to their numeric value back to a string - this in turn causes a bug that incorrectly matches "19" and "01". 
To avoid this, we recommend using `is_exact_match` instead for these subexpressions.
=> Update docs to recommend using `is_exact_match` instead of `is_match` for a notification routing example

content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/reactnative.md
Proposed change: 
Make sure you have not set `sessionSamplingRate` to something other than 100 (100 is the default value), or else your session might not be sent.
Previously: 
Make sure you have not set `sessionSamplingRate` to something other than 100 (100 is the default value), or else your session might be sent.
=> Fix typo in Troubleshooting React Native SDK docs

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/android.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/reactnative.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/android.md
This PR makes our doc consistent across our different SDKs, by putting the tracking consent information in the setup page and under the Session sampling paragraph
=> Clean docs about tracking consent in Mobile RUM SDKs

assets/styles/components/_learning-center-callout.scss, layouts/shortcodes/learning-center-callout.html
fixes the `learning-center-callout` styles.
motivation: https://datadoghq.atlassian.net/browse/WEB-5348
- a `<div>` in the callout overextended it's container and overlapped an alert box link in mobile view making it not clickable.
preview: 
- https://docs-staging.datadoghq.com/stefon.simmons/fix-learning-center-callout/continuous_integration/
- callout without image
- https://docs-staging.datadoghq.com/stefon.simmons/fix-learning-center-callout/containers/kubernetes/apm/?tab=datadogoperator 
- callout with image
=> adjust learning center callout styles

content/en/synthetics/api_tests/grpc_tests.md
Images aren't rendering inside some indented tabs. Un-indent the image shortcode to fix.
=> Broken Images on GRPC Testing Page

content/en/tests/auto_test_retries/_index.md
We no longer consider the feature beta.
Additionally, I've documented `DD_CIVISIBILITY_FLAKY_RETRY_ENABLED` and `DD_CIVISIBILITY_FLAKY_RETRY_COUNT` for javascript.
=> [Test visibility] Remove beta from auto test retries

content/en/serverless/step_functions/troubleshooting.md
Removes the note that says legacy Lambda API isn't supported
We recently added span linking support for this case in https://github.com/DataDog/logs-backend/pull/78707
=> SFN Legacy Lambda Support

content/en/error_tracking/frontend/_index.md
Adds '/frontend/` to the mobile URLs so that they work
=> Add frontend to Error Tracking urls

content/en/tracing/trace_collection/compatibility/go.md
Links in Go compatibility link to non-existent section headings.
=> Fix links for dd-trace-go

content/en/security/application_security/threats/add-user-info.md
Document we can disable auto-user-id collection with remote config.
=> security/appsec/threats/add-user-info.md: add remote config disablement

.github/workflows/synthetics.yml, datadog-ci.preview.json
Updates synthetics test configuration. Adds an override for the new `WEBSITE` environment variable.
- sets `WEBSITE` to be `https://docs-staging.datadoghq.com/${{env.CI_COMMIT_REF_NAME}}/` when a test is triggered via the **Preview Synthetic Github workflow** (CI pipeline)
- **NOTE**: should set this variable to `https://docs.datadoghq.com/` in your Datadog synthetic test if referenced
motivation:  comment: https://datadoghq.atlassian.net/browse/WEB-5329?focusedCommentId=1899923 
- Browser tests should test the same site.
- should allow the `Navigate to URL` step of our synthetics tests to be a dynamic docs url.
preview: [test yq3-qs9-b8k](https://dd-corpsite.datadoghq.com/synthetics/details/yq3-qs9-b8k?from_ts=1727030282240&to_ts=1727116682240&live=true) 
- Triggering via **Preview …
=> add `WEBSITE` variable for tests

content/en/dynamic_instrumentation/symdb/java.md
Update minimum dd-trace-java version required for Dynamic Instrumentation Autocomplete and Search to 1.39.1
Please wait for the reviewers I specified before merging.
=> Update minimum dd-trace-java version required for Dynamic Instrumentation Autocomplete and Search

content/en/tests/setup/junit_xml.md
We don't consider it beta anymore: very few, if any, customer issues with it. 
https://docs-staging.datadoghq.com/juan-fernandez/remove-beta-from-standalone-binary/tests/setup/junit_xml/?tab=linux#standalone-binary
=> [test visibility] Remove beta flag from `datadog-ci` standalone binary

config/_default/menus/main.en.yaml, content/en/service_management/workflows/limits.md, content/en/service_management/workflows/trigger.md
Add a page for workflow automation rate limits and throttles
=> (DOCS-8996) Add limits page for Workflow Automation

content/en/continuous_delivery/deployments/argocd.md
Update the CD Visibility <> Argo CD configuration guide to separate the trigger into two sets of conditions.
This is done to cover an edge case: the Argo CD notification deduplication logic will not send the notification when the application transitions between two states that match the conditions. For example, if the application transitions from `phase: Running, health: Healthy` to `phase: Succeeded, health: Healthy`, it will only send a notification for the first state but not for the second.
Separating into these two conditions ensures the notification is sent in both cases. We can keep `Succeeded`, `Failed` and `Error` in the same condition because they are terminal states and it should not be possible to transition between them.
=> Separate ArgoCD trigger into two conditions

content/en/service_catalog/service_definitions/_index.md
Fix URL linked to "[JSON schema for Datadog service definitions](https://raw.githubusercontent.com/DataDog/schema/main/service-catalog/version.schema.json)"
=> Fix 404-ing link in Service Catalog docs

content/en/opentelemetry/otlp_endpoint.md, content/en/opentelemetry/otlp_metrics.md
Mention header-based allowlist in OTLP metrics endpoint. Follow-up of https://github.com/DataDog/documentation/pull/25241
=> [OTEL-2079] Mention header-based allowlist in OTLP metrics endpoint

content/en/tracing/trace_collection/compatibility/php.md
For more granular details, please take a look at the motivating escalation: [APMS-13221](https://datadoghq.atlassian.net/browse/APMS-13221?focusedCommentId=1894494)
TLDR is that this version was marked as supported long ago while it never was, and nobody complained ever since :-)
This PR updates the doc to reflect the reality.
[APMS-13221]: https://datadoghq.atlassian.net/browse/APMS-13221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(php): Yii v1.1 is NOT supported

content/en/database_monitoring/setup_mongodb/mongodbatlas.md, content/en/database_monitoring/setup_mongodb/selfhosted.md, layouts/shortcodes/dbm-mongodb-agent-data-collected.md
The Metrics section of the DBM MongoDB data collected shortcode appears in two articles. Each article requires the link in the Metrics section to point to a different URL. That's not possible, so as an alternative solution, we've decided to move the section outside of the shortcode.
=> Move Metrics section out of shortcode

content/en/tracing/trace_collection/compatibility/nodejs.md
Docs still suggest starting with require dd-trace/initialize when it should be dd-trace/init.
=> Fix out of date docs

content/en/serverless/guide/serverless_warnings.md
This PR adds a new "Reaching Maximum Duration" warning to the serverless documentation. This warning is generated when a function's invocation approached the maximum duration limit of 15 minutes. The related PR to add the insight in web-ui is here: https://github.com/DataDog/web-ui/pull/158680/
=> [SVLS] Add warning for function reaching maximum duration

content/en/security/application_security/threats/add-user-info.md
Clarify remote configuration is required to remotely disable automated user id collection
=> security/appsec/threats/add-user-info.md: expanding remote config disablement

content/en/profiler/enabling/ssi.md
Adds documentation for enabling Profiling+SSI support on Kubernetes.
=> Document Profiling+SSI beta k8s support

content/en/integrations/guide/source-code-integration.md, layouts/shortcodes/sci-microsoft-sourcelink.md
Put the the instructions on .pdb files at the top level of .NET instructions (previously they only appear under SourceLink, which is misleading as without .pdbs, we will not have any file path / line number information available, and so Source Code Integration would provide a degraded experience.
Please wait for review from @jminuscula before merging.
=>  SCICM-2609

content/en/cloud_cost_management/saas_costs.md, layouts/partials/cloud_cost/cost-integrations.html
Adds an H3 section header so when users click on the integration tile, they are redirected to the instructions instead of the generic Setup section.
Requested by Natasha over Slack
=> SaaS Cost Integrations Update

content/en/service_management/workflows/build.md
Adds a link ref number that was mistakenly left off.
=> fix dropped link reference number

content/en/tests/setup/javascript.md
Let users know that they no longer need to pass `DD_CIVISIBILITY_MANUAL_API_ENABLED` to use the manual testing API.
https://docs-staging.datadoghq.com/juan-fernandez/remove-beta-from-manual-api/tests/setup/javascript/?tab=ciproviderwithautoinstrumentationsupport#manual-testing-api
=> [test visibility] Remove beta flag from testing manual API for Javascript

content/en/account_management/audit_trail/events.md
"Security Notification events" was missing in the list of Product-Specific Events at the top of the page, which might make it a bit hard for the users to recognize this type of event.
Add "Security Notification events" in the list of Product-Specific Events list at the top of the page, so that the users can recognize it exits in this category more easily.
=> Update events.md - security-notification-events missing in Product-Specific Events list

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/integrated_libraries/flutter.md
Adds some undocumented things from the Flutter SDK
=> DOCS-8450: Adding Flutter API

content/en/logs/guide/how-to-set-up-only-logs.md
- Add a danger alert for APM customers, so they don't disable metric collection
- Requested by PM
=> Add alert on disabling metric collection

content/en/tracing/trace_collection/library_config/cpp.md, content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md, content/en/tracing/trace_collection/library_config/go.md, content/en/tracing/trace_collection/library_config/nodejs.md, content/en/tracing/trace_collection/library_config/php.md, content/en/tracing/trace_collection/library_config/python.md
- Add note the library config pages: "**Note**: `DD_TRACE_SAMPLE_RATE` is deprecated in favor of `DD_TRACE_SAMPLING_RULES`."
- We are leaving the options for now and going with a note because many customers still use SAMPLE_RATE.
=> Note that DD_TRACE_SAMPLE_RATE is deprecated

content/en/network_monitoring/performance/network_analytics.md
Per the PM these features are going straight to GA in the near future, but we need to remove them from the docs for now as we can't sign up customers at the moment for the private beta, so the PM requested to remove this section from the docs until its ready for GA.
=> Update Network Analytics to remove private beta features

.github/workflows/bump_synthetics_worker_version.yml, local/bin/py/version_getter.py
The workflow that updates the synthetic-worker version was failing on the `commit` command when it didn't find any changes to the target file. Although the workflow wasn't broken (it just exited if no change was found), this behavior was confusing. This PR checks the existing version and writes a GitHub output variable that we can use to conditionally run the `commit` and `push` steps in the workflow. This should prevent the workflow from failing if there's nothing to commit.
test run: https://github.com/DataDog/documentation/actions/runs/11147491598/job/30981945184
=> (maint) Prevent workflow from failing on no-op

content/en/tracing/other_telemetry/connect_logs_and_traces/opentelemetry.md
* The latest tracing library versions support 128-bit IDs.
* So, OTel traces and logs should be automatically correlated.
* Add note that the manual steps on this page are only required for older versions.
**Open questions**
* When did this change happen?
=> Add Info Alert to Correlating OpenTelemetry Traces and Logs

content/en/network_monitoring/devices/snmp_traps.md
https://dd.slack.com/archives/C0245LJKD5F/p1727860554119579
on the support-ndm channel on Slack, there was a message about not seeing traps appear - after some digging i realized the docs have a typo (`source:snmp_traps`) vs `source:snmp-traps`
Cleaning it up so it doesn't happen again 😅 
Example on [Staging](https://dd.datad0g.com/logs?query=source%3Asnmp-traps%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727902120496&to_ts=1727903020496&live=true) with the right source ID
=> [NDM] Fix source for SNMP traps docs

content/en/security/threats/workload_security_rules/custom_rules.md
Remediating [VULN-7645](https://datadoghq.atlassian.net/browse/VULN-7645) by removing "At a minumum" which could mislead users to give too much permission to their custom rules file.
[VULN-7645]: https://datadoghq.atlassian.net/browse/VULN-7645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove "At a minimum" from permission suggestion

content/en/dashboards/_index.md
The hyperlink should go to https://docs.datadoghq.com/dashboards/list/. It currently goes to https://docs.datadoghq.com/dashboards/configure/ (same as first item in list).
=> [easy] fix broken in link Dashboards Overview page

content/en/tracing/configure_data_security/_index.md
DD_INSTRUMENTATION_TELEMETRY_ENABLED is not a valid config option. changing to the correct env var
=> changing DD_INSTRUMENTATION_TELEMETRY_ENABLED to DD_APM_TELEMETRY_ENABLED

content/en/agent/basic_agent_usage/windows.md
The install command is missing a " at the end of the DDAGENTUSER_NAME value
=> Correct the install command

content/en/observability_pipelines/advanced_configurations.md, layouts/shortcodes/observability_pipelines/configure_log_archive/google_cloud_storage/instructions.md, layouts/shortcodes/observability_pipelines/destination_settings/chronicle.md, layouts/shortcodes/observability_pipelines/processors/enrichment_table.md
Removes the "Referencing files in Kubernetes" section and any links to it.
[DOCS-8767](https://datadoghq.atlassian.net/browse/DOCS-8767)
[DOCS-8767]: https://datadoghq.atlassian.net/browse/DOCS-8767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8767] Remove referencing files in kubernetes section

content/en/quality_gates/setup/_index.md
Add indication about the required permission for the application keys used to trigger Quality Gates Evaluations
N/A
=> Add indication about required permission for Quality Gates Evaluations

layouts/shortcodes/observability_pipelines/processors/set_env_vars.md
This is part of the OP 2.2 release.
Adds info about which env vars are blocked.
Preview: https://docs-staging.datadoghq.com/may/add-blocked-env-vars/observability_pipelines/processors/set_environment_variables#blocked-environment-variables
=> Add blocked env vars for processor

content/en/agent/configuration/secrets-management.md
This PR updates the PowerShell sample code documentation to read from the special variable `$input` instead of `Read-Host`.
Indeed, this matches the behavior expected by the Agent, because `Read-Host` does not support piping input.
https://datadoghq.atlassian.net/browse/WINA-1095
=> Use `$input` instead of `Read-Host` for PowerShell secret example

config/_default/menus/main.en.yaml, go.mod, go.sum
update websites-modules and use the `on-call` icon
motivation: https://datadoghq.atlassian.net/browse/WEB-5395
- this change was reverted ([reference](https://github.com/DataDog/documentation/pull/25599)) but should be good to go live now.
preview: https://docs-staging.datadoghq.com/stefon.simmons/iupdate-web-modules-version/service_management/on-call/
- new icon should show in left nav next to `On-Call`
=> update web modules and add on-call icon

content/en/logs/log_configuration/flex_logs.md
Update Flex Logs docs to include retention length options, these currently only exist in the pricing page
=> Update Flex Logs docs to include retention length options

static/resources/yaml/datadog-agent-aks.yaml, static/resources/yaml/datadog-agent-all-features.yaml, static/resources/yaml/datadog-agent-apm.yaml, static/resources/yaml/datadog-agent-logs-apm.yaml, static/resources/yaml/datadog-agent-logs.yaml, static/resources/yaml/datadog-agent-npm.yaml, static/resources/yaml/datadog-agent-vanilla.yaml, static/resources/yaml/datadog-agent-windows-all-features.yaml, static/resources/yaml/datadog-agent-windows-apm.yaml, static/resources/yaml/datadog-agent-windows-logs-apm.yaml, static/resources/yaml/datadog-agent-windows-logs.yaml, static/resources/yaml/datadog-agent-windows-vanilla.yaml
Updating the sample manifests with latest Helm configs (`3.73.2`) and Agent version (`7.57.2`). A little outdated with last being June 2023.
=> Update sample configs for 7.57.2 Agent/Helm Chart 3.73.2

layouts/shortcodes/dbm-mongodb-agent-config-sharded-cluster.md
This PR adds `sharded_data_distribution` to mongodb sharded cluster configuration.
=> [dbm] add sharded_data_distribution to mongos

content/en/llm_observability/setup/auto_instrumentation.md
Adds a tracer (`ddtrace`) version column to our auto-instrumentation table, which is the version the LLMObs auto-instrumentation was introduced to the Python tracer.
We are not including Gemini in this PR, we'll have another PR that documents our Gemini support, and part of that PR will include the tracer version that introduced the LLMObs integration.
=> [MLOB-1616] Add tracer version to auto-instrumentation table

content/en/opentelemetry/agent/install_agent_with_collector.md, content/en/opentelemetry/agent/migration.md
The GCR is a default container registry used in Datadog's Helm charts. Updating `otel-agent` docs for the consistency.
=> Use GCR in the Otel Agent examples

config/_default/menus/main.en.yaml, content/en/account_management/saml/entra.md
First PR in a series of changes to rename Azure Active Directory to Microsoft Entra ID.
This PR has the following changes:
- Renames the filename of the Azure Active Directory doc for SAML setup from `azure.md` to `entra.md`
- Updates text in the Azure Active Directory doc for SAML setup to say "Microsoft Entra ID"
- Updates a few outdated links
- Creates an alias from `account_management/saml/azure/` to `account_management/saml/entra/`
A follow-on PR will update existing links in the documentation repo from `azure` to `entra`.
=> Rename Azure Active Directory to Microsoft Entra ID, Part 1

content/en/opentelemetry/interoperability/instrumentation_libraries.md
=> Add Python and .NET code samples for OpenTelemetry

content/en/network_monitoring/network_path/_index.md, content/en/network_monitoring/network_path/list_view.md, content/en/network_monitoring/network_path/path_view.md, content/en/network_monitoring/network_path/setup.md, content/en/network_monitoring/performance/_index.md
Changing Network path from Private beta to "in Preview"
=> updating Network path docs to in Preview

content/en/network_monitoring/devices/guide/device_profiles.md
Changing private beta callout to "in Preview"
This one has no discrepancy in the app as far as labels are concerned, I was waiting on the form URL to update but per last update on this issue, these can still be merged in the time being.
=> Changing private beta callout to "in Preview"

assets/styles/pages/_api.scss
update api docs styles to fix overlapping headers.
- wrapper for accordion should should expand and shrink when interacted with
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5393
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-api-docs-heading-overlap/api/latest/synthetics/#create-a-browser-test
- change viewport width. headers should not overlap other elements on the page. 
- expand and collapse the accordion. headers move with the expanding element
=> fix header overlap (api/) - [WEB-5393]

content/en/serverless/step_functions/installation.md
On this page: https://docs.datadoghq.com/serverless/step_functions/installation/?tab=custom, make this part collapsable:
This part is for Step Function -> Lambda trace linking. In a later PR, I'll add a section for Step Function -> Step Function trace linking. I want to make both sections collapsable to avoid making the page too long and scaring our developers.
This PR addresses comments on @cswatt  PR https://github.com/DataDog/documentation/pull/25517. Because she won't be back until Oct 21, I'm creating this new PR.
=> Make SFN->Lambda trace linking doc collapsable

content/en/containers/amazon_ecs/_index.md
[DOCS-9163](https://datadoghq.atlassian.net/browse/DOCS-9163)
Updates setup instructions on the Amazon ECS page for Network Path, adding "private beta" label as well to match Network Path docs for the time-being.
[DOCS-9163]: https://datadoghq.atlassian.net/browse/DOCS-9163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9163]Network path setup for ECS

repository.datadog.yml
Adds the `Send PR Approval Status` job to the ignore list for merge queue. I believe the skipped jobs are causing the queue to stall
=> Add Send PR Approval Status to ignore list

content/en/network_monitoring/network_path/setup.md
Adding a warning about increased log ingestion when using autodiscovery of network path, this is being fixed in a future release but we want to add the warning for the time being.
Do not merge yet, waiting on PM approval
=> [DOCS-9219] add logs generation warning to network path docs

content/en/database_monitoring/setup_postgres/_index.md
Adds a table for supported versions for Postgres, similar to the table on setting up MySQL: https://docs.datadoghq.com/database_monitoring/setup_mysql/#mysql-versions-supported
Table was removed previously but adding AlloyDB re-enforces that it should be there as we do not support every version for each hosting type anymore. [[Github PR](https://github.com/DataDog/documentation/pull/24910)]
Also removes the note below the icons, as it is not accurate, we’ve added support for Alloy DB since this comment.
Google Cloud also does not support 9.6 as per [this](https://docs.datadoghq.com/database_monitoring/setup_postgres/gcsql?tab=host#:~:text=Supported%20PostgreSQL%20versions)
=> Adding table for supported versions & removing note

static/resources/yaml/observability_pipelines/v2/setup/values.yaml
When installing a worker in obs-pipelines, if you want to deploy to k8s, you need to select a cloud provider to pick the right `values.yaml` file. 3 are available but they are exactly the same. Therefore, I'm making another copy called `values.yaml` temporarily so that we can deploy the current fix. In a later PR, I will remove the 3 other files.
With this PR, the UI will be able to point where a file that, when downloaded, its name is `values.yaml` and we can update the installation script accordingly.
=> OPA-2471: de-duplicate the multiple k8s config files

content/en/account_management/safety_center.md
Safety Center is going GA, so we need to remove the beta callout from the documentation.
https://datadoghq.atlassian.net/browse/SFTY-1061
N/A
=> [SFTY-1061] Remove Safety Center beta callout

assets/scripts/components/global-modals.js
This PR fixes the translation on the signup modal by removing an extra `?` from the language parameter on the signup's URL.
=> [ONBOARDING-68] Fix Signup Form Translation

content/en/serverless/step_functions/installation.md
The highlighted lines in the public doc "[Install Serverless Monitoring for AWS Step Functions](https://docs.datadoghq.com/serverless/step_functions/installation/?tab=custom)" are not accurate:
I think we should only highlight the lines that users need to add, i.e.
```
"Payload.$": "States.JsonMerge($$, $, false)",
```
```
"Execution.$": "$$.Execution",
"State.$": "$$.State",
"StateMachine.$": "$$.StateMachine"
```
=> Fix highlighted lines of code in Step Function installation doc

content/en/containers/kubernetes/control_plane.md
In RHOCP 4.14, the `kube-etcd-client-cert` secret has been relocated from the `openshift-monitoring` namespace to the `openshift-etcd-operator` namespace, and it is named as the `etcd-metric-client` secret. Updating the OpenShift4 `etcd` instructions to reflect this
=> [DOCS-9193] updating RH Open shift v4.x instructions

content/en/agent/configuration/dual-shipping.md
- Adds info about using OP for dual shipping.
[DOCS-8979](https://datadoghq.atlassian.net/browse/DOCS-8979)
[DOCS-8979]: https://datadoghq.atlassian.net/browse/DOCS-8979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8979] Add OP info to dual ship doc

content/en/profiler/enabling/java.md
After some discussion with customers and @r1viollet + @jbachorik, we've decided to add the full name of the tool to the profiling page (which links to the tracer page's instructions on using Graal NI) to aid with search discovery for profiling customers .
=> Small fix to improve page search-ability for Graal NI profiling

.gitlab-ci.yml
- Adds a resource group to `build_live` with variables to set a first in first out order
- Updates rules so mergequeue only has to run a few jobs since the checks will have been validated prior to approval
This PR will introduce a queue system for the `build_live` job as a follow up to `incident #31242`. The build live job is set to allow 1 job to run at a time, so as merges to `master` occur, they will join the queue if a job is already running to prevent any deployment sync issues as we experienced during the incident. This will also not prevent updates from going out in a timely fashion unlike canceling the previously running job. This will allow the build and deploy to complete prior to moving onto the next merge to master, but won't delay in a scenario where 4 PRs are merged 10 …
=> Add resourece groups to build_live and adjust mergequeue jobs

config/_default/menus/main.en.yaml
Removes the anchor to otel on the Connect RUM and Traces from the nav, as it is a confusing user experience, per [DOCS-8075](https://datadoghq.atlassian.net/browse/DOCS-8075).
[DOCS-8075]: https://datadoghq.atlassian.net/browse/DOCS-8075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove anchor from nav

content/en/dynamic_instrumentation/_index.md, content/en/dynamic_instrumentation/enabling/php.md, content/en/error_tracking/backend/exception_replay.md, layouts/partials/dynamic_instrumentation/dynamic-instrumentation-languages.html
With PHP 1.4 DI and exception replay are now supported.
=> Mention PHP for exception replay and dynamic instrumentation

content/en/service_management/events/guides/email.md
Events via email feature was migrated to a new service, this PR updates public documentation to inform about restriction/changes applied
N/A
=> [ECT-99] Update events via email documentation

content/en/tracing/guide/send_traces_to_agent_by_api.md
Update the documentation here to indicate that 128-bit trace IDs must be split across the trace ID field and the tag `_dd.p.tid`
=> Update 128-bit trace id instructions

content/en/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/_index.md
As per [DOCS-9243](https://datadoghq.atlassian.net/browse/DOCS-9243), the links on the mobile RUM webviews page were not lining up correctly and this PR fixes that.
[DOCS-9243]: https://datadoghq.atlassian.net/browse/DOCS-9243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix links on webview page

content/en/serverless/aws_lambda/installation/dotnet.md, content/en/serverless/aws_lambda/installation/java.md, content/en/serverless/aws_lambda/installation/nodejs.md, content/en/serverless/aws_lambda/installation/python.md
Bumps the lambda-datadog Terraform module version to 1.5.0 and updates the Datadog Lambda Layers to the latest supported versions.
- https://github.com/DataDog/terraform-aws-lambda-datadog/pull/21
- https://github.com/DataDog/terraform-aws-lambda-datadog/pull/18
=> Bumps lambda-datadog Terraform Module Version to 1.5.0 and Datadog Lambda Layers to Latest Supported Versions

content/en/tracing/guide/adaptive_sampling.md, content/en/tracing/guide/resource_based_sampling.md
=> Add PHP to resource_based_sampling and adaptive_sampling guide

content/en/service_catalog/customize/_index.md
add more links to internal docs and avoid linking out to GitHub repo directly
- add more references to newly created internal doc sections and avoid linking directly to raw schema file in GitHub
- add concrete examples of v3 features as we get closer for the GA release
=> Update _index.md for catalog curation

content/en/synthetics/guide/browser-tests-passkeys.md
[DOCS-9134](https://datadoghq.atlassian.net/browse/DOCS-9134)
This cleans up a link to Virtual Authenticator and adds a note to help the user understand the recommendation to combine user creation and authentication in the same step.
[DOCS-9134]: https://datadoghq.atlassian.net/browse/DOCS-9134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9134] fixing link and changing verbiage

content/en/agent/troubleshooting/send_a_flare.md, content/en/tracing/troubleshooting/tracer_debug_logs.md
We unpublished (reverted) some new documentation because the feature in question wasn't quite ready. The PM has requested that it be re-published.
=> Restore tracer flares documentation

content/en/agent/configuration/agent-fips-proxy.md
Remove references to beta in the FIPS documentation
=> docs: remove reference to beta in FIPS documentation

content/en/integrations/guide/aws-manual-setup.md, content/en/logs/log_configuration/archives.md
- Add information about setting up log archives with the AWS integration using role delegation for US1-FED users
- Remove outdated warnings about role delegation not being supported for US1-FED users
=> (DOCS-9263) Add log archives note

content/en/containers/kubernetes/distributions.md
GKE Autopilot supports compute classes for dedicated hardware, and like their GKE Spot Pods, sort of silently manages these with Tainted nodes. Autopilot will automatically add Tolerations to the workloads you specify, however, you need to do this manually to the Agent. 
https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-compute-classes
Additionally does some minor cleanup and removes the Operator steps for Spot Pods, since the Operator does not support Autopilot anyway. 
From customer requests.
=> Add details for GKE Autopilot compute class + cleanup

content/en/monitors/types/error_tracking.md
This adds a space after `be` to fix a tiny formatting issue in `error_tracking.md` that was creating a `mailto` link where it shouldn't be.
A bit difficult to replicate the formatting issue here in GitHub description, so best seen -> https://docs.datadoghq.com/error_tracking/monitors/?tab=highimpact#new-issue-monitors-do-not-take-into-account-issue-age at the bottom of the paragraph.
=> Add space to fix code formatting in `error_tracking.md`

content/en/tracing/trace_collection/compatibility/go.md
Shopify/sarama is deprecated, so update the links to use https://github.com/IBM/sarama instead
=> Modify Go library docs to use updated Sarama library links

content/en/security/application_security/code_security/setup/_index.md, content/en/security/application_security/software_composition_analysis/setup/_index.md, content/en/security/application_security/threats/setup/_index.md, content/en/security/application_security/threats/threat_management_setup.md
Use of `traces` in ASM prereqs wasn't clear enough. Needed 'web traces'.
=> revised use of traces to include web traces type

content/en/getting_started/tagging/unified_service_tagging.md, content/en/opentelemetry/interoperability/environment_variable_support.md, content/en/opentelemetry/schema_semantics/semantic_mapping.md
Add semantic mapping of the new OTel semantic convention `deployment.environment.name` -> `env`
The old convention `deployment.environment` has been deprecated in favor of `deployment.environment.name` in [OpenTelemetry semantic conventions v1.27.0](https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.27.0). 
Datadog agent supports the new convention starting 7.58.0
Datadog exporter supports the new convention starting v0.110.0
> :warning: Do not merge until new Agent and Exporter release.
For now the old convention `deployment.environment` is still preferred in the examples as it works in all previous Datadog agent and Datadog exporter versions.
=> [OTEL-2071] OTel semantic mapping deployment.environment.name to env

.github/workflows/codeowner_review_status.yml
- Update the workflow to only run once a PR is reviewed. Since we require at least 1 reviewer to merge, the PR will be blocked until a review is completed, then the workflow will trigger and check to ensure that required codeowners have approved the PR. If they have the job will pass
=> Add job update step if PR approved

content/en/account_management/saml/okta.md
In GovCloud, SAML users who use Okta as the identity provider must manually configure the Datadog application. The current instructions tell people to use the preconfigured application in Okta's application catalog, which doesn't work for GovCloud.
This PR adds a warning for GovCloud users and redirects them to the legacy instructions.
Requested by support: https://datadoghq.atlassian.net/browse/DOCS-9253
=> Add warning for SAML Okta users in GovCloud

content/en/product_analytics/guide/rum_and_product_analytics.md
As per PM request:
- Removes Session Replay from the features table and adds it as an FAQ that links to the pricing page instead
- Adds a missing link
=> Update Session Replay and add link

content/en/tracing/trace_collection/custom_instrumentation/go/dd-api.md
This PR adds a warning about closing spans that were not created by the customer but by a SDK integration. We now consider it noteworthy because it created an issue where ASM was being disabled backend side because the data that where supposed to be sent via those spans weren't because it was closed of by the user code.
=> Add warning about closing spans in APM Go SDK Docs

content/en/developers/ide_plugins/idea/_index.md, content/en/developers/ide_plugins/visual_studio/_index.md
Add the opt-out of telemetry section in the JetBrains and Visual Studio plugin documentation
=> [IDE] Add the opt-out of telemetry section in the JetBrains and Visual Studio plugin documentation

content/en/containers/kubernetes/integrations.md
Ticket: https://datadog.zendesk.com/agent/tickets/1886059
Customer followed our doc, but the agent returned "python module not found " error. When the customer used "postgres", it worked.
Our official integration here is postgres: https://github.com/DataDog/integrations-core/tree/master/postgres.
This is shown in the Annotations tab: 
However the Operator & Helm tab currently show postgresql:
Using postgresql is throwing the error "no python module found"
=> Update postgresql to postgres for  Datadog Operator & Helm

layouts/_default/list.redirects.txt, local/bin/py/build/actions/security_rules.py, local/bin/py/build/configurations/pull_config_preview.yaml
- Adds the ability to redirect a security rule based on the rule id
- Updates the redirect meta list to exclude these redirects
https://datadoghq.atlassian.net/browse/WEB-5450
https://docs-staging.datadoghq.com/devin.ford/WEB-5450/security/default_rules/9ga-poq-w7v should redirect you to https://docs-staging.datadoghq.com/devin.ford/WEB-5450/security/default_rules/aws-lambda-vpcaccess/
=> [WEB-5450] Bring back security rule shortlinks

.gitlab-ci.yml, config/_default/config.yaml, config/_default/languages.yaml, content/en/metrics/custom_metrics/historical_metrics.md, layouts/_default/list.search.json, layouts/partials/algolia/api-pages-full-index.json, local/bin/js/typesense_sync.cjs, package.json, typesense.config.json
- enables the typesense indexing job in live, so we can run typesense and algolia in parallel as we prepare to switch over.
- adds a `search.json` output for typesense specifically so no current Algolia processes are changed.
- `typesense_sync` job ran successfully in preview: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/680879329
- live typesense job is uncommented in gitlab config
- Current Algolia jobs are not affected by these changes
=> enables typesense live syncing job

content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
The feature flags collection does not require to add the `enableExperimentalFeatures` init param for a while now. We should not tell customers to use `enableExperimentalFeatures` as they are meant to be internal only (in general).
=> Adjust feature flags collection docs

.github/workflows/check_cache_values.yml, .github/workflows/codeowner_review_status.yml, .github/workflows/datadog-static-analysis.yml, .github/workflows/gif_check.yml, .github/workflows/label.yml, .github/workflows/merge_label_check.yml, .github/workflows/preview_link.yml, .github/workflows/synthetics.yml, .github/workflows/vale_linter.yml, .github/workflows/validate_filenames.yml
- Adds a concurrency check to most workflows to allow a new workflow to cancel a previously running one
- Ignores translations branches for most workflows
- Adds a manual dispatch for synthetics if docs wanted to run it against a translations PR
https://datadoghq.atlassian.net/browse/WEB-5466
=> [WEB-5466] Exclude translation PRs and add concurrency to avoid rate limiting in github actions

content/en/sensitive_data_scanner/_index.md
Adds a keyword dictionary section for OOTB rules.
[DOCS-9339](https://datadoghq.atlassian.net/browse/DOCS-9339)
[DOCS-9339]: https://datadoghq.atlassian.net/browse/DOCS-9339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9339] Add keyword dictionary section for OOTB rules

content/en/tests/auto_test_retries/_index.md
The PR adds the .NET tab for the automatic test retries feature in Test Visibility.
=> [CI Visibility] .NET auto test retries feature

.gitlab-ci.yml
`typesense-sync` live job is failing because the package needs to be installed in the runner.   it works in preview because we are building the site on demand in the preview job.
see example of failing build: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/683461882
=> fix failing typesense sync live job 

content/en/serverless/aws_lambda/installation/nodejs.md
This PR adds a disclaimer to in the Serverless Nodejs installation instructions to make it clear to customers not to have `datadog-lambda-js` installed in both the `node_modules` and as a lambda layer. 
This is already mentioned under the `Custom` tab, but the vast majority of people reading this page will only be following the `Datadog CLI`, `Serverless Framework`, or `AWS SAM` tabs where it is not explicitly stated to only install the Lambda library in one place.
It's common for users to install the Lambda layers as instructed by the documentation, but then then see import errors in their code, causing them to run `npm install datadog-lambda-js`. Now they will have the Lambda library installed in two places, which will (1) increase package size and cold start duration, and (2) break …
=> Add warning to Serverless Nodejs installation instructions

content/en/database_monitoring/setup_mongodb/mongodbatlas.md
Explicitly read access to `config` database for MongoDB Atlas. This is because the built-in `readAnyDatabase` role from MongoDB Atlas does not provide read access to `config` database.
=> [dbm] explicitly grant read access to config database

layouts/shortcodes/observability_pipelines/install_worker/kubernetes.md
Adds info about using self-hosted and self-managed Kubernetes clusters.
[DOCS-8176](https://datadoghq.atlassian.net/browse/DOCS-8176)
[DOCS-8176]: https://datadoghq.atlassian.net/browse/DOCS-8176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8176] Add info about self-hosted and self-managed Kubernetes clusters

content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
Updates the AWS CloudWatch Metric Streams with Amazon Data Firehose to provide a warning box about the metric streams not respecting the metric filtering provided by the AWS Integration tile. The motivation was a [customer ticket](https://datadog.zendesk.com/agent/tickets/1883938).
I've also fixed the links on the page. For instance, the first link was incorrectly linking to Amazon's own pricing, instead of our cloud metric delay docs.
=> Mirza nurkic/warn about namespace filtering

content/en/tracing/guide/inferred-service-opt-in.md, content/en/tracing/guide/service_overrides.md
* Address feedback from [this thread](https://dd.slack.com/archives/G016KHR5TTL/p1729025714480719).
* Not clear if these are two different features.
* Would be good to link between these more.
* Fix: Newly added anchor links were broken on the service overrides page.
Additionally, the **Global default service naming migration** duplicated some content from the service overrides guide. I consolidate this and linked off to the service overrides guide.
=> Link between Inferred Services and Service Overrides content

content/en/database_monitoring/setup_sql_server/azure.md, content/en/database_monitoring/setup_sql_server/gcsql.md, content/en/database_monitoring/setup_sql_server/troubleshooting.md, layouts/shortcodes/dbm-sqlserver-agent-config-examples.md
Adds curly braces to code samples. Note that the original request was to remove the curly braces, but after speaking to Engineering, they've recommended that we instead add them to all of the samples.
=> DOCS-9227: Add curly braces to SQL Server code samples

content/en/llm_observability/setup/sdk/_index.md
This PR fixes the parameter `model=...` to `model_name=...` to align with the actual [parameter name](https://github.com/DataDog/dd-trace-py/blob/105018feb6f3a6c049535c8ff2241229ede2be7d/ddtrace/llmobs/decorators.py#L19) and what is present on the [documentation page already ](https://docs.datadoghq.com/llm_observability/setup/sdk/#arguments).
```
/merge
```
=> Update _index.md to fix model_name parameter in llm() decorator

content/en/data_jobs/kubernetes.md
Remove two old host tags we used to ask customers to add to their `datadog.yaml` . They were used for billing but we are moving to a different billing logic, emitting the metric at spans ingestion.
These host tags are thus no longer requried and are adding confusion in DJM customer support workflow.
Please note that we are not ready yet to merge the PR!
=> [DJM K8s documentation] Remove two old host tags

content/en/data_streams/go.md
- Update sarama library url to non-deprecated library in data streams Go example.
Related to #25833
=> Update Sarama library url in data streams Go example

content/en/security/application_security/threats/exploit-prevention.md
This PR updates the tracer version that is required for Lfi and SqlI vulnerabilities. The lates version of the tracer supports both. The version that we used to associate to the Lfi vulnerability is no longer valid since many false positives were detected under versions prior to 3.4.0
```
/merge
```
=> Update RASP features matrix for .Net

content/en/llm_observability/setup/sdk/_index.md
We don't mention `user_*` tags for our session tracking feature, we should document those as well
- add a table of session tracking tabs
- update code example to include user tags
```
/merge
```
=> [mlobs] improve docs for user session tracking

content/en/data_jobs/airflow.md
Add setup guide for Data Jobs Monitoring for Airflow running on Astronomer.
For customers running Airflow with Astronomer, this setup guide would provide them the necessary guidance for unblocking them to try the preview of Data Jobs Monitoring for Airflow running on Astronomer. And it allows us gather direct feedbacks from customer as we continue to evolve the product.
=> DJM for Airflow on Astronomer

content/en/logs/log_configuration/parsing.md
- [DOCS-9241](https://datadoghq.atlassian.net/browse/DOCS-9241)
- Add learning center course to the docs as a callout and as a link in the further reading section
```
/merge
```
[DOCS-9241]: https://datadoghq.atlassian.net/browse/DOCS-9241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add learning center course to docs

content/en/account_management/audit_trail/events.md
This PR adds an entry to our documentation for a new audit event involving IP Allowlist modifications by Datadog Support, which are being added as a part of [Customer Transparency](https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/2679212146/Customer+Transparency+Expose+Critical+Support+Actions+in+Audit+Trail).
The related PR: https://github.com/DataDog/dd-source/pull/131740
The deployment PR referenced above has been merged, and this one can be merged once it has been reviewed.
Please merge after reviewing.
=> [INTR-88] Adding IP Allowlist modification by support to audit event docs

content/en/containers/docker/integrations.md, content/en/containers/guide/autodiscovery-with-jmx.md, content/en/containers/kubernetes/integrations.md
A few small follow up changes to:
- https://github.com/DataDog/documentation/pull/25980
In brief:
- Removed the `spec.containers[i].image` from Docker as that is Kubernetes specific
- I had previously put had `<SHORT_IMAGE>` in the JMX Docs instead of `<CONTAINER_IDENTIFIER>` so fixed that
- `ad_identifiers` is specific to the file setup, so took it out of the `<CONTAINER_NAME>` section for AD annotations
```
/merge
```
=> Small follow up changes to CONTAINER_NAME/CONTAINER_IMAGE adjustment

content/en/agent/guide/private-link.md, content/en/containers/cluster_agent/admission_controller.md, content/en/containers/datadog_operator.md, content/en/logs/log_configuration/_index.md, content/en/synthetics/platform/private_locations/_index.md
Adds links to Architecture docs.
[DOCS-8947](https://datadoghq.atlassian.net/browse/DOCS-8947)
```
/merge
```
[DOCS-8947]: https://datadoghq.atlassian.net/browse/DOCS-8947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8947] Add links to architecture docs

content/en/opentelemetry/otlp_endpoint.md
The value of `dd-otlp-source` is not meant to be `datadoghq.com` etc. It should be the org name of allowlisted partners.
```
/merge
```
=> Correct the value for header dd-otlp-source in otlp intake doc

content/en/database_monitoring/connect_dbm_and_apm.md
Breaks up `ADO.NET` into `System.Data.SqlClient` and `Microsoft.Data.SqlClient`
We don't fully support `ADO.NET` for DBM, but we _do_ support it via these two namespaces.
```
/merge
```
=> Change `ADO.NET` to more specific namespaces

content/en/universal_service_monitoring/setup.md
Adding values to disable SELinux for the system-probe container when enabling Istio monitoring, when using the Bottlerocket distribution on Kubernetes clusters.
Istio monitoring will not work on Bottlerocket without these values.
=> USM: add recommended values for Bottlerocket when using Helm

content/en/dashboards/sharing/shared_dashboards.md
This PR updates the documentation of [this section](https://docs.datadoghq.com/dashboards/sharing/shared_dashboards/#dashboards-cannot-be-shared-by-deactivated-users). We do not automatically pause public dashboards that are shared by a deactivated user, so instead, the docs are updated to reflect the current behavior.
=> Fix behavior of deactivated sharer

content/en/dashboards/widgets/query_value.md
Querying for percentile aggregations can be done in query value widgets for some product areas and distribution metrics where percentiles are enabled. Looking to add that note and a troubleshooting point about it.
Motivation for adding some content here is from a [support ticket](https://datadog.zendesk.com/agent/tickets/1869162) and related [technical escalation](https://datadoghq.atlassian.net/browse/WEBPS-5734) that led a customer to beleive that there was a problem with their rum data or with our platform, when in reality they were just experiencing expected behavior due to how the statistics worked out in the particular scenario.
Happy to receive feedback or reword anything.
=> Add note about percentile aggregations

content/en/tracing/troubleshooting/tracer_debug_logs.md
remove "These logs are not sent to the Datadog Agent in the flare and are stored in a separate path depending on your logging configuration."  that is not true
```
/merge
```
=> Modify some sentences in "review debug logs" related to tracer flare  

content/en/llm_observability/configuration/_index.md, local/bin/py/placehold_translations.py
updates the placeholder translation processing by adjusting regex used to split `frontmatter` and `content` to account for 0 or more spaces after `---`.
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5532
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-fm-in-content-translations
- check that this page https://docs-staging.datadoghq.com/stefon.simmons/fix-fm-in-content-translations/llm_observability/configuration/ looks good on all translated pages (i.e. en, ko, ja, fr)
- Isnt showing frontmatter in content. rendering further reading links
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming …
=> rm trailing space - placeholder translation script - [WEB-5532]

content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md
Three main things:
- Updates the categorization of several .NET configs into the appropriate category
- Updates the descriptions so that they match between the .NET Core and .NET Framework pages
- Adds a Trace context propagation section with documentation of the propagation configurations, with a link to the primary Trace Context Propagation page
```
/merge
```
=> Update categorization of APM .NET Library configurations

content/en/opentelemetry/_index.md
- [DOCS-9400](https://datadoghq.atlassian.net/browse/DOCS-9400)
- Adds Understanding OpenTelemetry course callout to further reading section
[DOCS-9400]: https://datadoghq.atlassian.net/browse/DOCS-9400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DOCS-9400 adding callout to Understanding OpenTelemetry course

content/en/serverless/aws_lambda/metrics.md, content/en/serverless/custom_metrics/_index.md, content/es/serverless/aws_lambda/metrics.md, content/es/serverless/custom_metrics/_index.md, content/ja/serverless/custom_metrics/_index.md, content/ko/serverless/aws_lambda/metrics.md, content/ko/serverless/custom_metrics/_index.md
Adds an example shutdown hook to AWS Lambda java custom metrics examples. This code is required so that all metrics are flushed before shutdown.
```
/merge
```
=> Add shutdown hook to java lambda custom metrics examples.

content/en/dora_metrics/setup/failures.md
We are in the processes of changing the mapping rules for DORA failures when we get PagerDuty alerts. This PR provides details into those new mapping rules and modifies the rules that were already written for clarity.
=> SDCD-437: Updating pagerduty service mapping logic in dora setup page

content/en/logs/guide/how-to-set-up-only-logs.md
- Update the Helm chart configuration to collect logs only in Kubernetes
- [DOCS-9388](https://datadoghq.atlassian.net/browse/DOCS-9388)
```
/merge
```
[DOCS-9388]: https://datadoghq.atlassian.net/browse/DOCS-9388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Kubernetes configuration to collected logs only

translate.yaml
OP legacy docs do not need to be translated.
```
/merge
```
=> Exclude legacy op docs from translations

content/en/security/application_security/threats/setup/compatibility/_index.md, content/en/security/application_security/threats/setup/compatibility/ruby.md
updated Ruby version support for API Sec to 2.4.0
Updates version number
Merge after reviews.
=> DOCS-9032 Ruby version support for API Sec

content/en/containers/troubleshooting/admission-controller.md
Minor change to the Rancher section of the troubleshooting documentation. Clarifying that we need access to port 8000, similar to how Rancher needs access through port 9443. The Datadog Cluster Agent/Admission Controller itself does not need port 9443 access. 
From customer request.
```
/merge
```
=> Clarify port 9443 in the Rancher troubleshooting

content/en/real_user_monitoring/browser/advanced_configuration.md
There was a typo in the documentation and RUM was not capitalized.
=> Fix typo and capitalization in advanced config docs

content/en/data_jobs/airflow.md
This doc update removes the requirement for a preview signup, allowing users to try the Data Jobs Monitoring preview directly.
Remove onboarding frictions.
=> Update the callout of Data Jobs Monitoring for Apache Airflow

content/en/serverless/step_functions/merge-step-functions-lambda.md
This field is never used. Removing it to avoid confusing customers.
Please merge it after review. Thanks!
=> Remove `AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID`

content/en/getting_started/containers/datadog_operator.md
Adds `site` to the example YAML for the operator setup and clarify app key config
There is no mention of the `global.site` field in the example YAML. Without going through the linked CRD field spec, users who are not using the default site datadoghq.com will struggle to get the agent running. The error messages received lead down a "bad credentials" rabbit hole which does not make it immediately obvious that the site might be wrong, so I think it is a good idea to point out this needs to be set, here, on the getting started pages. 
I've also expanded on adding the app key as again, I think this is something most people will need, and it is better to be explicit about this. 
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create …
=> Update datadog_operator.md: Add `site` to the sample YAML

content/en/integrations/guide/aws-terraform-setup.md, content/es/integrations/guide/aws-terraform-setup.md, content/fr/integrations/guide/aws-terraform-setup.md, content/ja/integrations/guide/aws-terraform-setup.md, content/ko/integrations/guide/aws-terraform-setup.md
Updates our suggested terraform code to attach the SecurityAudit policy which is now required by default. Tested this locally and was able to run the updated terraform to attach the policy to our role.
```
/merge
```
=> [aws-ints] updating terraform to attach security-audit policy

local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
This PR, in addition to removing a file that is no longer needed, changes the pull config to only pull the CWS documentation from the release branch of the agent and not from main. This will allow us to make sure new features are not available in the documentation before they are available to users through the agent.
The downside of this is that PR will be required for every release to update the release branch.
```
/merge
```
=> [CWS-3524] pull CWS documentation from release branch (and not main)

assets/styles/pages/_global.scss
- update font-size for definition lists in main body content to match the font size of `p`, `ol`, and `ul` in main body content
```
/merge
```
https://docs-staging.datadoghq.com/carlos/update-def-lists-fontsize/api_catalog/#key-terminology
=> Update font-size for definition lists to match main body text

content/en/tracing/error_tracking/_index.md
[JIRA ticket
](https://datadoghq.atlassian.net/browse/APMDT-4564)
'Span tag' has been changed to 'span attribute' according to this document: https://docs.google.com/document/d/1hVjAaNxDHRv8X29WtaMdSDnfHbSdSSJ7KaJQzGWCxu8/edit?tab=t.0#heading=h.bm61zafc1pcl
```
/merge
```
=> [APMDT-4564] Span tag vs. Span attribute naming convention

content/en/agent/configuration/secrets-management.md
This PR fixes a broken URL that was fixed in the Datadog Agent repository.
See https://github.com/DataDog/datadog-agent/pull/30854
```
/merge
```
=> Fix broken URL for secret feature and add example script for permissions

content/en/product_analytics/user_retention.md
- Per PM request, removes the data retention on the Product Analytics page with the intention of adding it back in later when we have the updated Data Retention page.
```
/merge
```
=> [DOCS-9450] Remove data retention section on PA

layouts/glossary/list.html
suppresses `/glossary` pg warnings on non-en pgs by only showing warnings if building english pages.
motivation: example: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/699672034#L533
```
WARN  Ignoring invalid core_product tag “신서틱(Synthetic) 모니터링”
WARN  Ignoring invalid core_product tag “보안”
WARN  Ignoring invalid core_product tag “인프라스트럭처 모니터링”
```
preview: 
- docs: https://docs-staging.datadoghq.com/stefon.simmons/suppress-glossary-warnings/glossary/
-  should be no visual change
- build: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/699694989
- should not see any build warnings for invalid core_product tag
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the …
=> suppress glossary warnings on non-en pgs

content/en/tracing/trace_collection/custom_instrumentation/ruby/otel.md
Clarify that there are two separate configuration blocks: one for Ruby Datadog configuration; and the other for OpenTelemetry configuration. This has come up as a source of confusion where it can be understood that both Datadog and OpenTelemetry configurations go inside the Datadog configuration block.
```
/merge
```
=> Clarify the Ruby OpenTelemetry configuration block difference

layouts/shortcodes/dbm-mongodb-before-you-begin.en.md
https://dd.slack.com/archives/C027TGQFUMR/p1730924543747039
A customer was confused that it was only 7.58.0 and not versions above as well
```
/merge
```
=> Explicit 7.58.0+ as minimum mongo version

assets/scripts/lang-redirects.js, config/_default/languages.yaml, layouts/partials/language-region-select.html
1. adds `Espanol` to the language dropdown. 
1. enable language redirects and `lang_pref` cookie
Motivation: Related to https://github.com/DataDog/documentation/pull/25922
- nightly build for docs ran which was able to index spanish content in typesense. should be able to search for spanish pages.
Preview: https://docs-staging.datadoghq.com/stefon.simmons/es-lang-dropdown/es
- search should show spanish results
- `Espanol` should show in the lang dropdown on non-es pages.
- check that the `lang-pref` cookie is properly set after you select a language from the dropdown
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the …
=> add Spanish selector to language dropdown

content/en/metrics/explorer.md
A prime use case of Quick Graphs is to provide alternate visualizations for metrics that are not present in Metrics Explorer. This change documents Quick Graphs in the same place as Metrics Explorer to improve discoverability.
```
/merge
```
=> Have Metrics Explorer page point to Quick Graphs page

content/en/account_management/billing/usage_metrics.md, content/en/metrics/guide/custom_metrics_governance.md
Adding `datadog.estimated_usage.metrics.custom.by_tag` and `datadog.estimated_usage.metrics.custom.ingested.by_tag` as per new Preview feature.
=> Update Usage Attribution to add new Preview metrics

content/en/infrastructure/process/_index.md, content/en/monitors/types/process.md
A customer was asking if live process monitors are an enterprise-only function. This PR adds Live Process Monitoring to the docs to explain that it is a pro feature as well.
```
/merge
```
=> Update LP docs to explain that LP monitoring is also enterprise

content/en/real_user_monitoring/browser/setup/_index.md
* `content/en/real_user_monitoring/browser/setup/_index.md` contains an alias to `/real_user_monitoring/browser/setup/client/`
* `content/en/real_user_monitoring/browser/setup/client.md` contains an alias to `/real_user_monitoring/browser/setup`
This causes a redirection loop because pages are redirecting to each other. This makes the page inaccessible.
Removing the `_index.md` file fixes the issue. Those pages are working correctly:
* https://docs-staging.datadoghq.com/benoit/remove-browser-rum-setup-redirection/real_user_monitoring/browser/setup/ is redirecting to `...setup/client`
* https://docs-staging.datadoghq.com/benoit/remove-browser-rum-setup-redirection/real_user_monitoring/browser/setup/client is displayed correctly.
Merge queue is enabled in this repo. To have it automatically …
=> 🐛 remove browser/setup/_index.html to solve redirection loop

content/en/real_user_monitoring/browser/setup/_index.md
- Removes an alias to fix a redirect loop
```
/merge
```
Still verifying if this solves the problem.
=> Remove Browser RUM redirect
