content/en/security/cloud_security_management/setup/fargate.md

[CWS] add fargate entrypoint instruction

---

content/en/service_management/mobile/_index.md

- Update instructions and link to the page users should be directed to
- Remove outdated image

Small update to mobile app

---

assets/styles/pages/_standard-attributes.scss

remove overflow for standard attributes table
https://datadoghq.atlassian.net/browse/WEB-4839
https://docs-staging.datadoghq.com/renzo.renteria/prevent-table-overflow-x/standard-attributes/

standard attributes table css

---

content/en/integrations/guide/oracle-check-upgrade-7.50.1.md

Explicitly mention that the Agent configuration is required for each RAC node.

Add RAC note to the Oracle upgrade guide

---

content/en/logs/log_configuration/indexes.md

Updating daily quota documentation to say that it takes effect immediately.

Update indexes.md docs for daily quota taking effect immediately.

---

content/en/profiler/connect_traces_and_profiles.md
content/en/profiler/profile_visualizations.md

Fix PHP Timeline NTS vs ZTS

---

content/en/security/cloud_security_management/agentless_scanning/_index.md
content/en/security/cloud_security_management/setup/agentless_scanning/_index.md

Adds a note to the CSM Agentless Scanning docs to clarify that Agentless Scanning is not supported in US1-FED.

Add US1-FED notes for CSM Agentless Scanning

---

content/en/account_management/teams/manage.md

Replace the non-word "unhide" with "reveal"

Replace a non-word with a more accurate description

---

content/en/watchdog/insights.md

Use the correct spelling of "address." Noticed by a translator.

Correct spelling of address

---

layouts/shortcodes/latest-lambda-layer-version.html

Bumps version of Lambda Extension, per the new release.

Bump datadog-lambda-extension layer to version 57

---

content/en/security/cloud_security_management/agentless_scanning/_index.md

Updates note in CSM Agentless Scanner docs. Requested by PM.

Update note in CSM Agentless Scanner docs

---

content/en/service_catalog/service_definitions.md

add v3.0 schema details and example
add details for schema v3.0

Update service_definitions.md - add v3 details

---

content/en/agent/remote_config/_index.md

(Agent) Link to flare from remote config doc

---

content/en/containers/guide/operator-eks-addon.md
content/en/integrations/guide/application-monitoring-vmware-tanzu.md
content/en/integrations/guide/cluster-monitoring-vmware-tanzu.md
content/en/real_user_monitoring/error_tracking/mobile/android.md

- Update API Key link to the current application URL
- Saw this link in another PR and noticed that it reverts the UI to the old navigation.

Update API link

---

content/en/service_management/app_builder/_index.md
content/en/service_management/app_builder/auth.md
content/en/service_management/app_builder/build.md
content/en/service_management/app_builder/embedded_apps.md
content/en/service_management/workflows/_index.md
content/en/service_management/workflows/access.md
content/en/service_management/workflows/actions/_index.md
content/en/service_management/workflows/actions/data_transformation.md
content/en/service_management/workflows/actions/flow_control.md
content/en/service_management/workflows/actions/http.md
content/en/service_management/workflows/build.md
content/en/service_management/workflows/connections.md
content/en/service_management/workflows/saved_actions.md
content/en/service_management/workflows/trigger.md

[DOCS-7889](https://datadoghq.atlassian.net/browse/DOCS-7889)
[DOCS-7889]: https://datadoghq.atlassian.net/browse/DOCS-7889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(workflows)(app-builder) Add Slack links

---

content/en/getting_started/containers/datadog_operator.md

Remove App Key requirement from Datadog Operator docs.
[Slack discussion](https://dd.slack.com/archives/C4TQDFK1P/p1714740777366399)

Remove App Key requirement

---

content/en/security/cloud_security_management/agentless_scanning/_index.md

Docs team Tuesday tasks: add blog link to documentation

Add Agentless scanning blog link

---

content/en/security/cloud_security_management/agentless_scanning/_index.md

Fix spelling mistake in Agentless docs

---

content/en/service_catalog/service_definitions.md

tiny change to remove an extra word

Update service_definitions.md - typo fix

---

content/en/data_streams/_index.md

Update the tags on the data streams monitoring payload size metric

Update /index DSM docs - remove two tags

---

content/en/getting_started/site/_index.md

Add specific country location to EU site description

---

content/en/database_monitoring/setup_mysql/aurora.md
content/en/database_monitoring/setup_mysql/rds.md

Tweak reasoning behind RDS installation integration

---

content/en/glossary/terms/flame_graph.md
content/en/glossary/terms/timeline_view.md

https://datadoghq.atlassian.net/browse/DOCS-6043
Updated Flame Graph definition and added term for Timeline View.

Glossary updates for Code Profiling and APM

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-framework.md

Clarify the example shared in the Notes section of the installation guide regarding using only one apm solution in your application.
This is a duplicate of the following PR for DotNet core docs - [link to PR](https://github.com/DataDog/documentation/pull/23024)

Update dotnet-framework.md installation note

---

content/en/observability_pipelines/dual_ship_logs/_index.md

Remove Datadog. It was already removed from the nav but not from this page.

Remove datadog source

---

content/en/service_management/service_level_objectives/_index.md

update csv export docs

---

content/en/tests/guides/flaky_test_management.md

Add a section for flaky tests propagation.

Add section for flaky test propagation

---

assets/scripts/datadog-docs.js

fix docs navigation when going back in history
Wait for CorpWeb review approval
case described in jira ticket: https://datadoghq.atlassian.net/browse/WEB-4875
preview: https://docs-staging.datadoghq.com/renzo.renteria/navigation/opentelemetry/schema_semantics/service_entry_spans/?tab=otelcollectoranddatadogexporter

remove check for event state in popstate listener

---

content/en/account_management/org_settings/service_accounts.md

DOCS-7742 requested by a support engineer.
Disabling a service account requires additional permissions besides what was originally stated in the document. Updated the document to add the appropriate permission.

Describe the permissions needed to disable a service account

---

content/en/real_user_monitoring/session_replay/browser/_index.md

Update a code sample in a div to use HTML formatting

Fix code sample

---

content/en/code_analysis/static_analysis/_index.md

* Visual Studio is now supported too.
* We now support many JetBrains family IDEs, not just IntelliJ IDEA.

Static Analysis: Update supported IDEs

---

content/en/developers/integrations/log_pipeline.md

Add a note at the top of the doc that these are required for log integrations

update log doc

---

content/en/agent/remote_config/_index.md

Default and custom agent rule will be soon GA so we don't need a reference to a private/public beta

[CWS-2092] - Remove beta tags for remote agent rules update

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-js layer to version 109

Bump datadog-lambda-js layer to version 109

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/java.md

FIX - Continuous typo

---

Makefile

Include new assetlib changes for new optional manifest.tile.resources field

[ecos 1397] Bump Assetlib

---

content/en/tests/search/_index.md

Fixing broken links after this PR https://github.com/DataDog/documentation/pull/23060

[CIVIS] Fix broken links

---

content/en/glossary/terms/short_image.md

DOCS-7836: Add "short image" to glossary

---

layouts/shortcodes/csm-setup-google-cloud.md

DOCS-7891: Update GCP instructions

---

content/en/security/cloud_security_management/identity_risks/_index.md
content/en/security/cloud_security_management/vulnerabilities/_index.md

Adds video walkthroughs for CSM Identity Risks and CSM Vulnerabilities. Requested by PM.

Add video walkthroughs for CSM Identity Risks and CSM Vulnerabilities

---

content/en/getting_started/application_security/software_composition_analysis.md

Rename download SBOM references as we work through the requirements to call the file a valid SBOM
Please merge after reviewing

Remove SBOM reference

---

content/en/monitors/recommended/_index.md

- Correct Overview regarding contributors to Recommended monitors
- Fix is requested by PM

Correct overview statement

---

content/en/tracing/llm_observability/sdk.md

LLM Observability updated SDK setup docs

---

content/en/code_analysis/static_analysis/_index.md
content/en/code_analysis/static_analysis/setup.md

Fixes invalid yaml examples for Static Analysis

Fix Invalid Static Analysis YAML

---

content/en/tests/early_flake_detection/_index.md

Add the versions we support for early flake detection. 
https://docs-staging.datadoghq.com/juan-fernandez/add-compatibility-efd/tests/early_flake_detection/

[test-visibility] Add version compatibility for early flake detection

---

.gitlab-ci.yml
local/bin/py/add_notranslate_tag.py

The current no translate tagging job is timing out. This update should be faster using bulk updates

faster notranslate tagging

---

content/en/tracing/llm_observability/quickstart.md
content/en/tracing/llm_observability/sdk.md
content/en/tracing/llm_observability/trace_an_llm_application.md

delete in-code config section in LLM Obs docs

---

.gitlab-ci.yml

python3 and allow job to be run manually on master builds if needed

fixes to notranslate tag job

---

content/en/dashboards/widgets/timeseries.md

- Add new sorting feature for Timeseries widgets.
- [DOCS-7565](https://datadoghq.atlassian.net/browse/DOCS-7565)
**Do not merge** Pending release
[DOCS-7565]: https://datadoghq.atlassian.net/browse/DOCS-7565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add sorting feature for timeseries widget

---

content/en/security/cloud_security_management/setup/fargate.md

Removes private from Fargate beta note. Requested by PM.

Update CSM private beta note

---

content/en/service_management/app_builder/_index.md

Per requests from PM:
* Adds more cross-linking between pages
* Replaces link to Workflows with in-app Action Catalog link
* Updates number of integrations (but also makes it more maintainable by not putting a specific number)

App Builder - Small cross-linking tweaks

---

content/en/observability_pipelines/setup_opw.md

Update OPW setup notes

---

content/en/service_management/events/_index.md

Blog posts May 12,2024

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md

Removes a sentence about what version Swift became available in, as it happened 2 years ago and is no longer relevant.
Related to [DOCS-7982](https://datadoghq.atlassian.net/browse/DOCS-7982).
[DOCS-7982]: https://datadoghq.atlassian.net/browse/DOCS-7982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[RUM] remove swift version detail

---

content/en/logs/log_configuration/flex_logs.md

Adds "Artifact Repository Management" example for direct to Flex Logs tier list.

Add "Artifact Repository Management" example for Flex Logs tier

---

content/en/tracing/trace_collection/compatibility/dotnet-core.md

Adds additional known bugs in the .NET runtime that can affect customers

[.NET] [Tracing] Document known runtime bugs affecting the tracer

---

content/en/service_catalog/adding_metadata.md

Update service catalog by modifying the v3 examples

---

layouts/shortcodes/observability_pipelines/log_source_configuration/datadog_agent.md

Fix OP Datadog config example

---

local/bin/py/add_notranslate_tag.py

Adds a number of other relevant data files to be notranslate tagged.

add other useful yaml files to notranslate

---

content/en/synthetics/api_tests/errors.md

add http errors to our public docs so it's referenced for customers

update api test error docs

---

content/en/database_monitoring/connect_dbm_and_apm.md

Remove outdated note now that DBM <> APM is supported in MySQL

---

config/_default/menus/main.en.yaml
content/en/service_management/case_management/_index.md
content/en/service_management/case_management/create_notifications_and_third_party_tickets.md
content/en/service_management/case_management/create_notifications_and_tickets.md
content/en/service_management/case_management/settings.md
content/en/service_management/case_management/view_and_manage/_index.md

[Case Management] creating a section dedicated to notifications and tickets

---

content/en/security/cloud_security_management/identity_risks/_index.md

Suggesting changes to reflect AWS IAM Access Analyzer integration and some other minor improvements in our docs.

Update _index.md to reflect AWS IAM Access Analyzer integration

---

content/en/getting_started/integrations/azure.md

there was a missing open single quote

tiny link fix

---

config/_default/menus/main.en.yaml
content/en/tracing/llm_observability/api.md
content/en/tracing/llm_observability/sdk.md
content/en/tracing/llm_observability/submit_evaluations.md
content/en/tracing/llm_observability/trace_an_llm_application.md

This PR adds a new page `Submitting evaluations` to the LLMObs documentation, duplicating and pulling out the SDK/API instructions for submitting evaluations into the new page to make easier for users to find.

LLMObs submitting evaluations page

---

content/en/continuous_integration/pipelines/azure.md

[CIVIS] Add Azure Pipelines to documentation

---

content/en/containers/docker/log.md

Fix a typo in docs :)
Motivation: help the world

Fixed typo in log.md of docker instructions.

---

content/en/opentelemetry/integrations/kafka_metrics.md

These are Kafka metrics, not container metrics. Previous sentence had a typo was copied over from the containers page.

fix copy paste typo

---

content/en/service_catalog/service_definitions.md

add DELETE endpoint per customer feedback
add DELETE example per customer feedback

Update service_definitions.md add DELETE endpoint

---

content/en/serverless/azure_support.md

Clarify that `Node` is `Node.js`, as this is causing confusion for translators

Update Node table header

---

config/_default/menus/main.en.yaml

fixing Mobile app advanced options menu

---

content/en/security/application_security/enabling/single_step/code_security.md
content/en/security/application_security/enabling/single_step/threat_detection.md

Cherry-pick from #22371 
Document support about ASM Single Step Installation for Kubernetes Helm Chart

[ASM] Single Step ASM Helm chart

---

content/en/cloud_cost_management/aws.md
content/en/continuous_integration/explorer/export.md
content/en/continuous_integration/search/_index.md

Noticed some broken links in the docs.

Small Anchor Link Fixes

---

content/en/agent/basic_agent_usage/windows.md

Forgot to commit this to a PR I was reviewing

(Agent) Small link fix

---

content/en/agent/logs/_index.md

(DOCS-7740)(Agent)(logs) Clarify start position

---

content/en/database_monitoring/setup_mysql/aurora.md

Add a missing word to avoid confusion with instance parameter groups

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/unity.md

Minor change to the Unity SDK setup starting with 1.1.0 (which is currently available)

Minor update to Unity SDK setup

---

layouts/shortcodes/observability_pipelines/processors/quota.md

Adds info about OP quota processor's name. Eng request.
[DOCS-8037](https://datadoghq.atlassian.net/browse/DOCS-8037)
[DOCS-8037]: https://datadoghq.atlassian.net/browse/DOCS-8037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8037] Add info about OP quota processor name

---

config/_default/params.yaml
content/en/glossary/terms/flame_graph.md
content/en/glossary/terms/profile.md
content/en/glossary/terms/timeline_view.md

Title says it all. Per this JIRA ticket: https://datadoghq.atlassian.net/browse/DOCS-7976

Update "Code Profiling" Glossary tag to "Continuous Profiler"

---

content/en/dora_metrics/_index.md
content/en/dora_metrics/data_collected/_index.md
content/en/dora_metrics/deployments/_index.md
content/en/dora_metrics/deployments/apm.md
content/en/dora_metrics/deployments/deployment_api.md
content/en/dora_metrics/failures/_index.md
content/en/dora_metrics/failures/incident_api.md
content/en/dora_metrics/failures/pagerduty.md
content/en/dora_metrics/setup/_index.md

Use Yellow Beta Banner Instead of Beta Callouts

---

content/en/logs/error_tracking/backend.md

Feature Request: https://github.com/DataDog/dd-trace-php/issues/2628
Logs-Backend PR: https://github.com/DataDog/logs-backend/pull/70267

docs: Update PHP Error Tracking via Logs

---

content/en/tracing/trace_explorer/trace_queries.md

- Add documentation for the exclusion `NOT` operator
- Fix the retention documentation for Trace Queries: trace queries are now based on diversity sampling and 1% flat sampling

Exclusion operator docs + fix trace queries retention docs

---

content/en/serverless/aws_lambda/installation/java.md

We've supported Java21 since launch, but these docs weren't updated

Lambda Java21 docs

---

content/en/security/threats/workload_security_rules/custom_rules.md

- Changes one clause in a sentence to clarify File integrity monitoring (FIM), as requested by the PM for CSM Threats.
It's just a change to a couple words so I didn't file a ticket.

Update FIM description in Creating Custom Detection Rules

---

content/en/service_catalog/guides/troubleshooting.md
content/en/tracing/guide/inferred-service-opt-in.md
content/en/tracing/services/service_page.md

This PR clarifies what the beta is about and what are the breaking changes entailed by opting-in to the experience.

Inferred service dependencies guide changes

---

content/en/tracing/trace_pipeline/ingestion_mechanisms.md

Clarify expected behavior for max_tps

---

config/_default/menus/main.en.yaml

Add the Analytics page to RUM, in prep for Product Analytics

Add RUM analytics page to nav

---

content/en/logs/guide/azure-native-logging-guide.md

Add a note about potential impacts to Azure App Service when enabling logs in the Datadog resource

Add App Service logs note

---

content/en/cloudcraft/components-aws/lambda.md

Typo caught by translators (Tuesday Tasks)

Update Cloudcraft Lambda

---

go.mod
go.sum

update websites-modules ref which includes new `product-analytics` icon.

Websites modules/generated/322

---

content/en/synthetics/troubleshooting/_index.md

I've added a reference (related to a question asked by our customers) to the cause of resource / step duration discrepancies

update Synthetics troubleshooting docs

---

content/en/logs/log_configuration/_index.md

Remove unnecessary video that includes the old nav.
Also update text based on new nav.

Update log configuration doc

---

content/en/continuous_integration/search/_index.md

Add section for "Pipeline Unified Trace" for CI Visibility.

Add docs for unified trace in CI Visibility

---

content/en/data_jobs/databricks.md

Admin settings in Databricks UI was renamed to just "Settings"

Databricks settings rename - From Admin Settings to Settings

---

content/en/tests/setup/javascript.md

Fix a rendering error.
https://docs-staging.datadoghq.com/juan-fernandez/fix-rendering-error-js/tests/setup/javascript/?tab=playwright#adding-custom-measures-to-tests vs 
how it looks in production: https://docs.datadoghq.com/tests/setup/javascript/?tab=playwright#adding-custom-tags-to-tests

[test-visibility] Fix rendering error in JS - playwright instructions

---

content/en/security/application_security/enabling/tracing_libraries/threat_detection/dotnet.md
content/en/security/application_security/enabling/tracing_libraries/threat_detection/java.md
content/en/security/application_security/enabling/tracing_libraries/threat_detection/nodejs.md

removing a duplicate call out in some of the Enabling ASM docs

removing duplicate callout in enabling ASM docs

---

layouts/shortcodes/apm-ssi-uninstall-linux.md

To address comment on this PR - https://github.com/DataDog/documentation/pull/23210 - that I overlooked.

Update SSI uninstall steps for linux

---

content/en/network_monitoring/devices/_index.md
content/en/network_monitoring/devices/data.md
content/en/network_monitoring/devices/netflow.md
content/en/network_monitoring/devices/network_topology_map.md
content/en/network_monitoring/devices/profiles.md
content/en/network_monitoring/devices/snmp_metrics.md
content/en/network_monitoring/devices/snmp_traps.md
content/en/network_monitoring/devices/troubleshooting.md

[DOCS-8094](https://datadoghq.atlassian.net/browse/DOCS-8094)
[DOCS-8094]: https://datadoghq.atlassian.net/browse/DOCS-8094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8094] removing Gov callout from NDM docs

---

content/en/containers/kubernetes/distributions.md

https://datadoghq.atlassian.net/browse/DOCS-8054
Removed lines from yaml file that are now default configurations. Added section for adding Datadog site.

Update GKE yaml 

---

content/en/metrics/custom_metrics.md

Change "customer metrics" to "custom metrics"
https://datadoghq.atlassian.net/browse/DOCS-8062

Fix typo on Custom Metrics page

---

content/en/agent/_index.md
content/en/agent/basic_agent_usage/aix.md
content/en/agent/basic_agent_usage/amazonlinux.md
content/en/agent/basic_agent_usage/centos.md
content/en/agent/basic_agent_usage/deb.md
content/en/agent/basic_agent_usage/fedora.md
content/en/agent/basic_agent_usage/oracle.md
content/en/agent/basic_agent_usage/osx.md
content/en/agent/basic_agent_usage/redhat.md
content/en/agent/basic_agent_usage/source.md
content/en/agent/basic_agent_usage/suse.md
content/en/agent/basic_agent_usage/ubuntu.md
content/en/agent/basic_agent_usage/windows.md
content/en/agent/guide/how-do-i-uninstall-the-agent.md
layouts/shortcodes/uninstall-agent.html

Based on user feedback, improves search for uninstalling the Agent.
Also adds a shortcode that generates a list of links to each platform doc on the uninstallation guide to help users find the right page.

(DOCS-8073)(Agent) Improve search - uninstalling the Agent

---

content/en/security/cloud_security_management/guide/_index.md
content/en/security/cloud_security_management/guide/active-protection.md
content/en/security/threats/_index.md
content/en/security/threats/investigate_agent_events.md
content/en/security/threats/workload_security_rules/_index.md

DOCS-8069
PM requested we focus specifically on crypto mining instead of general threats
Originally we release the Active Protection feature for all threat types. PM wants to focus on just crypto mining threat. So I revised the related content to just cover the crypto mining threat type.

DOCS-8069 refocused topic on crypto mining

---

layouts/shortcodes/apm-ssi-uninstall-linux.md

Update link in SSI uninstall shortcode

---

content/en/tracing/llm_observability/quickstart.md
content/en/tracing/llm_observability/sdk.md

Add links to Jupyter examples repository

---

content/fr/network_monitoring/devices/network_topology_map.md

PM would like the beta and gov banner removed from the french copy of these docs, and meanwhile I'll flag this as more urgent in transifex to get the rest of the updates in sooner.
Thanks!

removing banner from French docs

---

content/en/continuous_integration/explorer/_index.md
content/en/continuous_integration/explorer/facets.md

Update descriptions for test, pipeline, and common facets + improves linking from the Docs Glossary and doc pages.

DOCS-7560 CI Visibility Explorer + Search Test Run or Pipeline Execution Edits

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-js layer to version 110

---

config/_default/menus/main.en.yaml
content/en/network_monitoring/devices/device_topology_map.md

some minor nits from PM request - the in-app title changed to "Device Topology Map", so changing it in the docs to match, created alias to old page, and removed the `is_beta` flag since I forgot :)

fixing title, alias and removing is_beta flag

---

config/_default/menus/main.en.yaml
content/en/security/cloud_siem/content_packs.md

Adds a new doc for Cloud SIEM Content Packs and adds a nav entry for it.
[DOCS-7434](https://datadoghq.atlassian.net/browse/DOCS-7434)
[DOCS-7434]: https://datadoghq.atlassian.net/browse/DOCS-7434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-7434] Cloud SIEM Content Packs doc

---

content/en/real_user_monitoring/browser/setup.md

Had to remove an alias and update a broken link.

[rum] Browser SDK fix index and broken link

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/cpp.md
content/en/tracing/trace_collection/compatibility/cpp.md
content/en/tracing/trace_collection/library_config/cpp.md
content/en/tracing/troubleshooting/tracer_debug_logs.md

A new version of `dd-trace-cpp` has been released. This PR includes updates introduced in the new version, such as support for Windows.
🪟

cpp: update related to v0.2.1

---

content/en/real_user_monitoring/browser/tracking_user_actions.md

This PR adds a section on how click action names are built in RUM Browser SDK

Add action name computation starategies to rum browser documentation

---

content/en/service_management/app_builder/components/_index.md

Adds info about the fact that you can use basic Markdown syntax including images
Approved by PM over slack

Add info about Markdown syntax support

---

content/en/tracing/trace_collection/proxy_setup/_index.md

This PR update NGINX download instructions.

proxy: update NGINX download instructions

---

content/en/infrastructure/containers/orchestrator_explorer.md
content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md

Fixes some typos and errors found by the translators

Fix small errors

---

content/en/security/application_security/code_security/_index.md

X-XSS-Protection detection is not supported (and not planned, since the header is considered obsolete).

Amend list of vulnerabilities supported by Code security

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md

I noticed a small error in the Single Step Instrumentation docs while testing a new Getting Started guide. DD_ENV should be set with something like `staging`, not `env:staging`.

Single Step Instrumentation Quick Fix

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-js layer to version 111

---

content/en/security/application_security/enabling/compatibility/nginx.md
content/en/security/application_security/enabling/tracing_libraries/threat_detection/nginx.md
layouts/partials/security-platform/appsec-languages.html

Documents nginx AppSec functionality starting in version 1.2.0 of the datadog nginx module.

Initial docs for nginx/appsec

---

assets/styles/pages/_global.scss

fix the table layout on viewport widths `>=1200px`
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4975
previews:
- examples of tables on docs:
- https://docs-staging.datadoghq.com/stefon.simmons/web-4975/agent/supported_platforms/?tab=linux#service-checks-1
- https://docs-staging.datadoghq.com/stefon.simmons/web-4975/account_management/audit_trail/events/?tab=macos#audit-events
-  https://docs-staging.datadoghq.com/stefon.simmons/web-4975/network_monitoring/devices/data

fix table  layout

---

content/en/opentelemetry/integrations/runtime_metrics/java.md

Add more descriptions to OTel JVM runtime metrics

---

content/en/opentelemetry/ingestion_sampling_with_opentelemetry.md

New DD Agent probabilistic sampling option

---

content/en/getting_started/opentelemetry/_index.md
content/en/opentelemetry/schema_semantics/semantic_mapping.md

Chatted with Dinesh. Warning label is not accurate, so removing it.

Update Getting Started guide to remove incorrect warning label 

---

content/en/containers/kubernetes/prometheus.md

DOCS-8085 - Update github link

---

content/en/integrations/_index.md

Redirect users from `integrations/snowflake` to `integrations/snowflake_web`

(DOCS-8102) Add Snowflake redirect

---

content/en/cloudcraft/getting-started/generate-api-key.md

Update Cloudcraft's "Generate an API Key" article to follow the style guide more closely and include better information on security.

[CLOUDCRAFT-717] Update "Generate an API Key" article

---

content/en/integrations/_index.md

Reverts DataDog/documentation#23506

Revert "Revert "(DOCS-8102) Add Snowflake redirect""

---

content/en/real_user_monitoring/platform/connect_rum_and_traces.md

Update phrasing of sentence to be more clear. Flagged by eng.

[RUM / traces] Update supported libraries description

---

assets/styles/pages/_global.scss

fix table formatting
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-4988
preview: 
- https://docs-staging.datadoghq.com/stefon.simmons/web-4988/account_management/rbac/permissions/#synthetic-monitoring
- https://docs-staging.datadoghq.com/stefon.simmons/web-4988/account_management/billing/usage_metrics/#types-of-usage
- https://docs-staging.datadoghq.com/stefon.simmons/web-4988/network_monitoring/devices/data/?site=us

fix table formatting - [WEB-4988]

---

content/en/containers/guide/auto_conf.md
content/en/containers/guide/autodiscovery-examples.md
content/en/containers/guide/autodiscovery-management.md
content/en/containers/kubernetes/integrations.md

An atomic batch of updates to Autodiscovery docs.

DOCS-7696 (OKR3) - Autodiscovery edits, pt 1

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-python layer to version 95

---

CONTRIBUTING.md

Correct the language information about translated source and add link formatting info.

Fix contribution guidelines advice about Fr contributions

---

content/en/service_catalog/manage_entries.md

update callout for beta sign-up

---

content/en/monitors/types/outlier.md

https://datadoghq.atlassian.net/browse/DOCS-8000
Docs exist for the feedback in this ticket, but adding a link to make it (hopefully) easier to find.

Add link to additional outlier docs in Further Reading

---

content/en/real_user_monitoring/guide/upload-javascript-source-maps.md

Add a link to the Sourcemaps reference in GitHub to the `Further reading` section

Add source code link

---

content/en/logs/log_configuration/forwarding_custom_destinations.md

Update forwarding_custom_destinations.md with retry info

---

content/en/security/cloud_siem/investigate_security_signals.md

Adds content about viewing signals for specific use cases.
One of two PRs for [DOCS-7851](https://datadoghq.atlassian.net/browse/DOCS-7851)
[DOCS-7851]: https://datadoghq.atlassian.net/browse/DOCS-7851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-7851] Expand on view signals for Cloud SIEM Investigate Security Signals

---

content/en/synthetics/api_tests/icmp_tests.md

We now support ICMP tests on Windows Private Locations

Update ICMP docs for Windows support

---

content/en/observability_pipelines/archive_logs/datadog_agent.md
content/en/observability_pipelines/archive_logs/splunk_hec.md
content/en/observability_pipelines/archive_logs/splunk_tcp.md
content/en/observability_pipelines/archive_logs/sumo_logic_hosted_collector.md
content/en/observability_pipelines/dual_ship_logs/datadog_agent.md
content/en/observability_pipelines/dual_ship_logs/splunk_hec.md
content/en/observability_pipelines/dual_ship_logs/splunk_tcp.md
content/en/observability_pipelines/dual_ship_logs/sumo_logic_hosted_collector.md
content/en/observability_pipelines/log_volume_control/datadog_agent.md
content/en/observability_pipelines/log_volume_control/splunk_hec.md
content/en/observability_pipelines/log_volume_control/splunk_tcp.md
content/en/observability_pipelines/log_volume_control/sumo_logic_hosted_collector.md
content/en/observability_pipelines/split_logs/datadog_agent.md
content/en/observability_pipelines/split_logs/splunk_hec.md
content/en/observability_pipelines/split_logs/splunk_tcp.md
content/en/observability_pipelines/split_logs/sumo_logic_hosted_collector.md

Adds SDS processor tab to all use case source docs. SDS processor is available for all use cases and not just the Sensitive Data Redaction one.
[DOCS-8182](https://datadoghq.atlassian.net/browse/DOCS-8182)
[DOCS-8182]: https://datadoghq.atlassian.net/browse/DOCS-8182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8182] Add SDS processor tabs to all OP use case source docs

---

content/en/cloud_cost_management/saas_costs.md

Fully remove the `Tag Type` column from the Data Collected table in the SaaS Cost Integrations doc page.

SaaS Cost Integrations Edit

---

content/en/observability_pipelines/best_practices_for_scaling_observability_pipelines.md

Remove unsupported telemetry from OP docs.

Remove metrics and traces from OP docs

---

content/en/cloudcraft/faq/delete-account.md

This PR clarifies a few points in the article that made confused people, leading to them contacting support about it.

[CLOUDCRAFT-715] Update Cloudcraft's "How do I delete my account?" article

---

local/bin/py/add_notranslate_tag.py
translate.yaml

bugfix for `notranslate` job, adds `category` to translate from `platforms.yaml`
no UI changes

[WEB-4999] `notranslate` tagging job fix

---

content/en/developers/guide/dogshell-quickly-use-datadog-s-api-from-terminal-shell.md

Rename the name of a command from `status check` to `service check`, which matches the file in https://github.com/DataDog/datadogpy/tree/master/datadog/dogshell.
Flagged by a user in Hotjar.

Dogshell Edit

---

content/en/serverless/step_functions/troubleshooting.md

Please do not merge after review. I'll merge it when backend change is deployed. Thanks!

Update Lambda layer version for Step Functions troubleshooting

---

content/en/tracing/trace_collection/span_links/_index.md

Updates to columns with the versions where the relevant feature has been released.
- https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.53.0
- https://github.com/DataDog/dd-trace-rb/releases/tag/v2.0.0

Documenting SpanLinks Support for .NET and Ruby

---

content/en/cloudcraft/account-management/cancel-subscription.md

Make the article clearer, explain things with more details, and follow the style guide more closely.
I'm not sure if the title follows the style guide. Maybe it should be "Cancel your Cloudcraft subscription" instead?

[CLOUDCRAFT-716] Update Cloudcraft's "Cancel your Cloudcraft Subscription" article

---

content/en/data_security/hipaa_compliance.md
content/en/data_security/logs.md
layouts/shortcodes/hipaa-customers.md

Preview: 
- https://docs-staging.datadoghq.com/heston/DOCS-8204/data_security/logs/
- https://docs-staging.datadoghq.com/heston/DOCS-8204/data_security/hipaa_compliance/#hipaa-compliant-log-management

(DOCS-8204)(Data Sec) Single-source HIPAA doc

---

content/en/watchdog/insights.md

filtering on a outlier makes it disapear

watchdog insights

---

content/en/monitors/types/slo.md
content/en/service_management/service_level_objectives/guide/_index.md

minor changes to links

---

assets/scripts/components/async-loading.js

This needs more discovery into the root issue, but this PR should fix the integrations filtering issue until we have a better solution in place
https://docs-staging.datadoghq.com/nsollecito/web-5018/integrations/
https://datadoghq.atlassian.net/browse/WEB-5018

[WEB-5018] temp fix for filtering issue on integrations page

---

content/en/synthetics/platform/private_locations/_index.md

Update Windows PL version in tandem with our Linux image

Update Windows PL version

---

content/en/dora_metrics/failures/pagerduty.md

Update PagerDuty approach in case of URL match

---

content/en/profiler/guide/save-cpu-in-production-with-go-pgo.md

pgo: use double quotes in example to prevent user errors

---

layouts/shortcodes/observability_pipelines/prerequisites/datadog_agent.md

Add port to datadog agent address

---

content/en/tracing/trace_collection/compatibility/dotnet-core.md

Documents a runtime bug that can impact customers

[APM] [.NET] Document runtime bug that can affect us

---

content/en/getting_started/synthetics/private_location.md

Change version of Windows PL installer on public docs

Update version for Win PL installer on public docs

---

content/en/cloudcraft/components-aws/documentdb.md
content/en/cloudcraft/components-aws/ebs.md
content/en/cloudcraft/components-aws/rds.md
content/en/cloudcraft/components-aws/s3.md

Fix a typo repeated across a few Cloudcraft component articles regarding 2D/3D colors.

Fix typo with 2D/3D view colors in Cloudcraft component articles

---

content/en/account_management/org_settings/cross_org_visibility.md

Cross-org visibility queries now work on both public and private dashboards. Updating the wording in the "scope" section to remove "private."

Update cross-org visibility scope to include public dashboards

---

content/en/cloudcraft/faq/account-data-storage.md

Adds a missing backtick, as reported internally.

Add missing backtick Cloudcraft

---

content/en/service_management/app_builder/_index.md
content/en/service_management/app_builder/auth.md
content/en/service_management/app_builder/build.md
content/en/service_management/app_builder/components/_index.md
content/en/service_management/app_builder/components/tables.md
content/en/service_management/app_builder/connections/_index.md
content/en/service_management/app_builder/connections/http_request.md
content/en/service_management/app_builder/embedded_apps.md
content/en/service_management/app_builder/expressions.md

Removes beta banner when App Builder goes GA on Monday 6/17/24 (where does the time go???)

Remove beta banner for GA on 6/17/24

---

content/en/security/cloud_security_management/setup/_index.md

Updates to the CSM setup page to add most up-to-date for support for Windows hosts. 
Also, removing the `cloud` infrastructure as it makes it seem like we only support Cloud environments. The CSM product works on all environments, cloud or on-prem or hybrid.

CSM Setup - add a row for Windows support

---

content/en/dynamic_instrumentation/expression-language.md

Fix typo on Expression Language page.

---

content/en/universal_service_monitoring/additional_protocols.md
content/en/universal_service_monitoring/setup.md

usm: Remove beta from istio monitoring

---

content/en/containers/amazon_ecs/_index.md

Cleans up this page, updates instructions to align with current state of AWS console, removes outdated information.

Revamp Containers > Amazon ECS page

---

content/en/security/application_security/enabling/compatibility/serverless.md

Update Serverless Compatibility Requirements for Application Security

---

content/en/security/application_security/enabling/compatibility/go.md

Update Go Compatibility Requirements for Application Security

---

content/en/security/application_security/threats/exploit-prevention.md

Just adding back one sentence the PM requested but was removed during an editing pass.

Update exploit prevention topic with note

---

content/en/continuous_integration/search/_index.md

This PR adds a new small section for CI Pipelines providing a brief explanation about Critical Path.

Add critical path section for CI Pipelines

---

content/en/security/cloud_siem/content_packs.md

Need to update the content pack documentation with new content packs.

update with new content packs

---

config/_default/menus/main.en.yaml

Reorder LLM Observability pages

---

content/en/security/application_security/enabling/tracing_libraries/code_security/_index.md

Update Code Security enablement page

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump dd-trace-java layer version to 15

---

content/en/data_jobs/_index.md
content/en/data_jobs/databricks.md
content/en/data_jobs/emr.md
content/en/data_jobs/kubernetes.md

DOCS-7920 - Data Jobs Monitoring GA

---

content/en/bits_ai/managing_incidents.md

Small updates to the wording on the Bits AI for Incident Management docs.

Update Bits for Incident Management docs

---

content/en/tracing/trace_collection/proxy_setup/_index.md

Updates the configuration step for ingress-nginx.

Update Ingress-NGINX configuration

---

content/en/synthetics/platform/private_locations/_index.md

[DOCS-8272] Update Synthetics link

---

content/en/continuous_testing/cicd_integrations/_index.md

Links from the Integration section are 404-ing, URL should be `continuous_testing`, not `synthetics`.

Continuous Testing and CI/CD Edit

---

content/en/service_management/app_builder/_index.md

Tuesday tasks - add blog link for app builder

Add blog for Tuesday Tasks

---

content/en/security/cloud_security_management/guide/tuning-rules.md

- Change **Event** tab to **Events** tab

Fix tab name

---

content/en/network_monitoring/performance/network_analytics.md

Network Analytics Edit

---

content/en/getting_started/opentelemetry/_index.md

Add service.version for unified service tagging config

---

content/en/serverless/step_functions/_index.md

[DASH] Step Functions GA

---

content/en/tracing/trace_collection/custom_instrumentation/nodejs/dd-api.md

Update Node.js dd-api.md: Fix broken links to datadoghq.dev

---

content/en/cloud_cost_management/_index.md
content/en/cloud_cost_management/datadog_costs/_index.md

Adds a link for [Datadog Costs](https://docs.datadoghq.com/cloud_cost_management/datadog_costs) in the Setup section of the Cloud Cost Management landing page.

Cloud Cost Management Edit

---

content/en/profiler/enabling/dotnet.md
content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md
content/ja/profiler/enabling/dotnet.md

Very small cosmetic change to make the sample command look more like the real file.

Fix template for dotnet tracer tar file in some docs

---

config/_default/menus/main.en.yaml

Add Bitrise to Child Page Names in Navigation

---

content/en/getting_started/tracing/_index.md

Add link to APM Enabling Tracing tutorials in APM Getting Started

---

content/en/monitors/configuration/_index.md
content/en/monitors/manage/search.md
content/en/monitors/manage/status.md
content/en/monitors/notify/_index.md

We did a batch renaming of `Say what's happening` headers recently and missed a couple of links.

Small Anchor Link Cleanup (Monitors)

---

content/en/network_monitoring/performance/setup.md

[DOCS-8273](https://datadoghq.atlassian.net/browse/DOCS-8273)
[DOCS-8273]: https://datadoghq.atlassian.net/browse/DOCS-8273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8273] small fix to NPM k8s setup

---

content/en/logs/log_configuration/archives.md

Updated the IP Ranges link to use region param shortcode.
[DOCS-8160](https://datadoghq.atlassian.net/browse/DOCS-8160)
[DOCS-8160]: https://datadoghq.atlassian.net/browse/DOCS-8160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8160] Update IP ranges link to use region param shortcode

---

content/en/logs/explorer/live_tail.md

Adds a link to the Log Search Syntax page.
[DOCS-7400](https://datadoghq.atlassian.net/browse/DOCS-7400)
[DOCS-7400]: https://datadoghq.atlassian.net/browse/DOCS-7400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-7400] Add link to search syntax

---

content/en/service_management/workflows/build.md

(DOCS-8319)(Workflows) Notifications

---

content/en/dashboards/_index.md

This is to highlight the recently launched Discovering Graph Widgets course

Adding call out for new Discovering Graph Widgets in the Datadog Learning Center

---

content/en/llm_observability/auto_instrumentation.md
content/en/llm_observability/core_concepts.md
content/en/llm_observability/quickstart.md
content/en/llm_observability/sdk.md
content/en/llm_observability/span_kinds.md
content/en/llm_observability/submit_evaluations.md
content/en/llm_observability/trace_an_llm_application.md

remove all beta label for llm obs

---

content/en/security/application_security/code_security/_index.md
content/en/security/application_security/enabling/compatibility/dotnet.md
content/en/security/application_security/enabling/compatibility/go.md
content/en/security/application_security/enabling/compatibility/java.md
content/en/security/application_security/enabling/compatibility/nginx.md
content/en/security/application_security/enabling/compatibility/nodejs.md
content/en/security/application_security/enabling/compatibility/php.md
content/en/security/application_security/enabling/compatibility/python.md
content/en/security/application_security/enabling/compatibility/ruby.md
content/en/security/application_security/enabling/single_step/code_security.md
content/en/security/application_security/enabling/tracing_libraries/code_security/_index.md
content/en/security/application_security/troubleshooting.md
layouts/shortcodes/asm-libraries-capabilities.md

DOCS-8331
Code Security is now GA.

removing Beta note

---

content/en/product_analytics/_index.md

- Adds the new Product Analytics blog to the Further Reading section of the docs

[PA] Crosslink product analytics blog in docs

---

content/en/infrastructure/process/_index.md

Clarify collection of process metrics during real-time mode.

[processes] Update real-time monitoring documentation

---

content/en/tracing/trace_collection/trace_context_propagation/python.md

fix b3multi typo

---

config/_default/menus/main.en.yaml
content/en/real_user_monitoring/session_replay/_index.md

- Adds details about Extended Retention for RUM
- Adds Playlists back to the RUM menu

[RUM] Add details for extended retention

---

content/en/tracing/trace_collection/compatibility/java.md

Fix opensearch supported versions for java tracer

---

content/en/agent/remote_config/_index.md

Update remote configuration documentation to reflect configuration precedence

Add RC configuration order precedence

---

content/en/tracing/trace_pipeline/ingestion_mechanisms.md

Fix typo your -> you're in  ingestion_mechanisms.md.

Fix typo your -> you're in  ingestion_mechanisms.md

---

content/en/service_management/app_builder/connections/http_request.md
content/en/service_management/workflows/actions/http.md
content/en/service_management/workflows/private_actions/_index.md
content/en/service_management/workflows/private_actions/private_action_credentials.md

Replaces form link with new beta signup page

(Workflows/Apps) Replace beta link

---

content/en/database_monitoring/setup_postgres/aurora.md

Add service annotation example for multiple instances

---

content/en/database_monitoring/setup_mysql/aurora.md
content/en/database_monitoring/setup_postgres/aurora.md

Make DBM Aurora autodiscovery setup steps more prominent

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/data_collected/android.md

- Adds details to how Datadog batches and uploads RUM data for transparency, as per [DOCS-8232](https://datadoghq.atlassian.net/browse/DOCS-8232)
[DOCS-8232]: https://datadoghq.atlassian.net/browse/DOCS-8232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[rum] Add data upload details for Android SDK

---

content/en/tracing/guide/ignoring_apm_resources.md

[DOCS-8312](https://datadoghq.atlassian.net/browse/DOCS-8312)
[DOCS-8312]: https://datadoghq.atlassian.net/browse/DOCS-8312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8312] fixing link

---

content/en/dashboards/guide/graphing_json.md
content/en/dashboards/guide/query-to-the-graph.md
content/en/dashboards/widgets/group.md
content/en/dashboards/widgets/timeseries.md
content/en/glossary/terms/slo_list.md
content/en/glossary/terms/slo_summary.md
content/en/glossary/terms/test_service.md
content/en/glossary/terms/timeboard.md
content/en/glossary/terms/topology_map.md
content/en/metrics/explorer.md
content/en/tracing/trace_explorer/query_syntax.md

Replace outdated anchor links in the Dashboards docs and Glossary terminology.

Dashboards + Glossary Terms Link Update

---

content/en/agent/logs/advanced_log_collection.md

Adds a beta callout.
[DOCS-8340](https://datadoghq.atlassian.net/browse/DOCS-8340)
[DOCS-8340]: https://datadoghq.atlassian.net/browse/DOCS-8340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8340] Add beta callout fo SDS using Agent

---

content/en/network_monitoring/devices/guide/device_profiles.md

adding beta form callout to Device Onboarding page

---

content/en/containers/guide/cluster_agent_autoscaling_metrics.md
content/en/dashboards/guide/version_history.md
content/en/dashboards/widgets/split_graph.md
content/en/integrations/guide/azure-programmatic-management.md
content/en/serverless/guide/agent_configuration.md
content/en/tracing/trace_collection/custom_instrumentation/android/otel.md

Fixes issues pointed out by our translators.

TT Translation Fixes

---

content/en/bits_ai/_index.md
content/en/getting_started/application_security/software_composition_analysis.md
content/en/network_monitoring/network_path/_index.md
content/en/security/cloud_siem/entities_and_risk_scoring.md

Tuesday tasks. Add blog links to further reading.

Add blog links to further reading

---

content/en/llm_observability/_index.md

Update OAI usage disclaimer (approved by legal)

---

.gitlab-ci.yml

- updates to the latest image with slack notifier updates
https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/558236125 - pipeline run with notifications sent
https://github.com/DataDog/websites-images/pull/213 - Image PR

Update image to latests

---

content/en/database_monitoring/connect_dbm_and_apm.md

Update dd-trace-py packages supporting DBM from release [2.9.0](https://github.com/DataDog/dd-trace-py/releases/tag/v2.9.0)
Update docs.
Please merge once reviewed and approved 👍 

Update connect_dbm_and_apm.md with newly supported python DBM libs

---

content/en/network_monitoring/performance/setup.md

update the path of system probe file for Windows

Failed Connections Windows docs

---

content/en/account_management/guide/_index.md
content/en/account_management/guide/relevant-usage-migration.md

https://datadoghq.atlassian.net/browse/DOCS-8282
New guide for an upcoming API endpoint migration requested by the product manager.
Note: I am aware that the code highlighting does not extend across the full width of the comment. I will file a bug with Websites to address that.
Note: Much of the upcoming example JSON is invalid, because it is supposed to provide a visual, imprecise example. I raised my concern on some of the formatting with the PM, and she will work to fix it in a follow-up.

Add relevant usage migration guide

---

content/en/network_monitoring/devices/netflow.md

From hotjar feedback
[DOCS-8348](https://datadoghq.atlassian.net/browse/DOCS-8348)
[DOCS-8348]: https://datadoghq.atlassian.net/browse/DOCS-8348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8348] Update netflow phrasing

---

.gitignore

(maint) Add single-sourced threat files to ignore

---

content/en/cloud_cost_management/datadog_costs/_index.md

Adds two anchor links to the respective sections in the Plan and Usage docs.
Requested by Natasha over Slack.

Datadog Costs Edit

---

content/en/observability_pipelines/setup_opw.md

Adds the location of directories and files.
[DOCS-8279](https://datadoghq.atlassian.net/browse/DOCS-8279)
[DOCS-8279]: https://datadoghq.atlassian.net/browse/DOCS-8279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8279] Add location of directories and files

---

content/en/infrastructure/resource_catalog/_index.md

Update the recent changes section to:
- provide a link to the private beta signup
- mention prerequisite configuration of resource collection

Update recent changes section

---

content/en/account_management/billing/_index.md
content/en/account_management/billing/pricing.md

Fixes discrepancy in language used to describe host billing.

DOCS-4169 Change wording of billing pages to match each other

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md

Chiseled containers contain no shell, so we cannot run the usual commands in there.
I added some instructions, but they feel a little bit out of place since they are docker commands, while other instructions are just a line of bash.
If you think those instructions belong somewhere else, please advise.
I wrote a [personal blog post](https://medium.com/p/00b1db18f4b9) explaining it in more details.

Add documentation on how to setup tracer for chiseled containers

---

content/en/universal_service_monitoring/setup.md

Remove "beta or limited support" text from additional features

---

content/en/continuous_delivery/deployments/argocd.md

Add docs for multiservice ArgoCD applications support

Add docs for multiservice ArgoCD applications support

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/flutter.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/ios.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/troubleshooting/reactnative.md

Standardizing the docs about offline mode for our mobile SDK
N/A

Standardize mobile SDK offline mode docs

---

content/en/developers/ide_plugins/idea/_index.md

There's a typo in the name of IntelliJ IDEA. That's the only place we used "IDEA" instead of "IntelliJ IDEA" as far as I can tell.

Fix IDE name

---

content/en/tracing/guide/inferred-service-opt-in.md

Inferred services private beta guide - Fix agent configuration instructions

---

content/en/opentelemetry/schema_semantics/hostname.md

OpenTelemetry has different kinds of attributes. The attributes referred to in this page are resource attributes. I add the qualifier in several places here to make it clearer

Explicitly state that these are resource attributes

---

content/en/account_management/org_settings/ip_allowlist.md

agent flare submission is now exempt from IP allowlist enforcement. Updating docs to say this.

Update ip_allowlist docs

---

content/en/agent/configuration/dual-shipping.md
content/en/agent/configuration/network.md
content/en/agent/configuration/proxy.md

Add netpath (Network Path) to proxy documentation

Add netpath to proxy documentation

---

content/en/tests/setup/dotnet.md
content/en/tests/setup/java.md
content/en/tests/setup/javascript.md
content/en/tests/setup/python.md

This PR updates Test Visibility setup docs for .NET, Java, JS and Python.
A link to Test Visibility Github Action is added for this languages.

Update Test Visibility docs: add links to Github Action

---

content/en/mobile/_index.md

Noticed searches for "Datadog mobile app" or "mobile app" or "mobile device" were only turning up results for Synthetics mobile app testing, so added some search terms to help locate this page better.

Datadog mobile app: adding algolia terms

---

content/en/serverless/_index.md

Update _index.md since StepFunctions is GA

---

content/en/synthetics/platform/private_locations/configuration.md

[DOCS-8390](https://datadoghq.atlassian.net/browse/DOCS-8390)
[DOCS-8390]: https://datadoghq.atlassian.net/browse/DOCS-8390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8390] adding windows path for private locations

---

content/en/containers/docker/integrations.md
content/en/containers/guide/_index.md
content/en/containers/guide/ad_identifiers.md
content/en/containers/guide/auto_conf.md
content/en/containers/guide/container-discovery-management.md
content/en/containers/guide/template_variables.md
content/en/containers/kubernetes/integrations.md

Pulling AD guides into their own section in the container guide index, cleaning up some of them.

[DOCS-7700] - Consolidate autodiscovery guides

---

content/en/getting_started/tagging/unified_service_tagging.md
content/en/opentelemetry/ingestion_sampling_with_opentelemetry.md
content/en/opentelemetry/schema_semantics/semantic_mapping.md

- DOCS-8334
- DOCS-6193
Currently, our OpenTelemetry documentation only includes mappings from OTel resource attributes to Datadog reserved attributes: [OpenTelemetry Semantic Conventions and Datadog Conventions](https://docs.datadoghq.com/opentelemetry/schema_semantics/semantic_mapping/?tab=datadogexporter#unified-service-tagging).
- Users are looking for this info on our main [Unified Service Tagging page](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes).
- This information needs more elaboration and examples.
- Add new [OpenTelemetry section to Unified Service Tagging page](https://docs-staging.datadoghq.com/brett0000FF/DOCS-8334/getting_started/tagging/unified_service_tagging/?tab=kubernetes#opentelemetry).
- Show example with environment …

[DOCS-8334] Add unified service tagging info for OpenTelemetry

---

content/en/cloud_cost_management/aws.md

Updated the wording for net amortized cost in AWS for CCM.

update the wording for net amortized cost in AWS

---

local/bin/js/algolia-index-sync.js

When users search for "SCA" or "Software Composition Analysis," the two phrases are aranked equally in Algolia.

DOCS-8344 Add Code Analysis Acronyms to Algolia

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-extension layer to version 60

---

config/_default/menus/main.en.yaml
content/en/agent/guide/_index.md
content/en/agent/guide/upgrade_between_minor_versions.md
content/en/agent/guide/upgrade_to_agent_6.md
content/en/agent/guide/version_differences.md
content/en/agent/upgrade.md

Moves info on versioning/upgrading older versions to the guide section and moves the Agent 7 upgrade page to the main nav.

(DOCS-8296)(Agent) Move upgrade / versioning

---

content/en/data_jobs/databricks.md
content/en/data_jobs/emr.md

New latest version of DJM init script is `v1.3.1`
My IDE also removed some whitespace from the modified files

Bump latest version of DJM init scripts

---

content/en/tests/setup/javascript.md

Let users know about our [vitest](https://github.com/vitest-dev/vitest) integration.

[test-visibility] Add support for `vitest`

---

.vale.ini

Update `.vale.ini` to use the Vocab added to `datadog-vale` in [this PR](https://github.com/DataDog/datadog-vale/pull/65), which should be merged first.

(DOCS-7599) Add Vocab

---

content/en/serverless/aws_lambda/installation/dotnet.md
content/en/serverless/aws_lambda/installation/java.md
content/en/serverless/aws_lambda/installation/nodejs.md
content/en/serverless/aws_lambda/installation/python.md

Bumps the lambda-datadog Terraform module version to 1.3.0
https://github.com/DataDog/terraform-aws-lambda-datadog

Bumps lambda-datadog Terraform Module Version to 1.3.0

---

content/en/universal_service_monitoring/setup.md

usm docs fixes

---

content/fr/logs/log_collection/android.md
content/ja/logs/log_collection/android.md

- Updates the repo name to match the updated one in the English file because the translation is taking too long at the moment.

Update repo name in fr and ja

---

content/en/getting_started/_index.md

Bump Code Analysis above CoScreen in Getting Started doc page.
Chat with Kassen on Slack

Getting Started Edit

---

content/en/continuous_testing/environments/multiple_env.md

The parameter name is `startUrl`, not `startURL`.
Chat with Hakan on Slack

Testing Multiple Environments Update (Take 2)

---

content/en/account_management/audit_trail/_index.md

Add note to say that the list view doesn't have the export to a schedule option.
[DOCS-8409](https://datadoghq.atlassian.net/browse/DOCS-8409)
[DOCS-8409]: https://datadoghq.atlassian.net/browse/DOCS-8409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8409] Add note about exporting option in the list view

---

content/en/tests/setup/javascript.md

Show the correct instructions. I missed a couple of important bits in https://github.com/DataDog/documentation/pull/24102.

[test visibility] Fix vitest instructions

---

layouts/shortcodes/dbm-mongodb-agent-beta-install-docker.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-kubernetes.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-linux.md
layouts/shortcodes/dbm-mongodb-agent-config-replica-set.md
layouts/shortcodes/dbm-mongodb-agent-config-sharded-cluster.md
layouts/shortcodes/dbm-mongodb-agent-config-standalone.md
layouts/shortcodes/dbm-mongodb-agent-setup-docker.md
layouts/shortcodes/dbm-mongodb-agent-setup-kubernetes.md

This PR updates DBM for MongoDB private beta doc to
- bump up dbm mongo private beta agent version 
- update configuration to include database autodiscovery

[DBM] bump up dbm mongo private beta agent and updates config to include database autodiscovery

---

content/ja/agent/basic_agent_usage/windows.md

(maint) Fix link in JA Windows doc

---

content/en/glossary/terms/span_tag.md
content/en/glossary/terms/trace_context_propagation.md
content/en/tracing/glossary/_index.md

- Add trace context propagation definition.

Add New APM Definitions to Glossary

---

content/en/database_monitoring/_index.md

This PR adds DBM for MongoDB (private beta) to the DBM landing page.

add mongodb private beta to dbm landing page

---

content/en/tracing/troubleshooting/tracer_startup_logs.md

Add info on enabling startup logs for Ruby

---

content/en/service_management/workflows/build.md

(Workflows) Remove beta banner for AI

---

content/en/agent/basic_agent_usage/amazonlinux.md
content/en/agent/basic_agent_usage/centos.md
content/en/agent/basic_agent_usage/deb.md
content/en/agent/basic_agent_usage/fedora.md
content/en/agent/basic_agent_usage/oracle.md
content/en/agent/basic_agent_usage/osx.md
content/en/agent/basic_agent_usage/redhat.md
content/en/agent/basic_agent_usage/suse.md
content/en/agent/basic_agent_usage/ubuntu.md
content/en/agent/basic_agent_usage/windows.md
content/en/agent/guide/_index.md
content/en/agent/guide/agent-5-commands.md
content/en/agent/guide/agent-5-log-files.md
content/en/agent/guide/install-agent-5.md
content/en/agent/guide/windows-flare-agent-5.md

Nothing new here. Just moving stuff around.

(DOCS-8224) Remove references to Agent 5 and 6

---

content/en/observability_pipelines/archive_logs/datadog_agent.md
content/en/observability_pipelines/archive_logs/fluent.md
content/en/observability_pipelines/archive_logs/http_client.md
content/en/observability_pipelines/archive_logs/splunk_hec.md
content/en/observability_pipelines/archive_logs/splunk_tcp.md
content/en/observability_pipelines/archive_logs/sumo_logic_hosted_collector.md
content/en/observability_pipelines/archive_logs/syslog.md

Add GCP link and update other links

---

layouts/_default/list.algolia.json

fixes algolia template which had an uncaught reference to `.File` without wrapping in a check first

fixing algolia template

---

content/en/service_catalog/service_definitions.md

adding mention of multiple ownership feature as it often comes up in customer conversations.
adding mention of multiple ownership feature in v3 overview as it often comes up in customer conversations.

update v3 feature list for service catalog

---

content/en/profiler/guide/save-cpu-in-production-with-go-pgo.md

PGO has been GA'ed, see [announcement](https://www.datadoghq.com/blog/datadog-pgo-go/).
https://datadoghq.atlassian.net/browse/PROF-9958

remove beta warning for pgo, it's ga now

---

content/en/service_management/app_builder/connections/http_request.md
content/en/service_management/workflows/actions/http.md

Adds reference to OAuth and JWT to hopefully improve search hits.

(Workflows) Improve http 2-step search

---

content/en/agent/guide/upgrade_between_minor_versions.md

While investigating an issue I noticed this page was out of date, this brings the documentation up to date with in-app instructions.

Update instructions for Agent upgrade between minor versions

---

content/en/network_monitoring/devices/snmp_traps.md

[DOCS-8440](https://datadoghq.atlassian.net/browse/DOCS-8440)
[DOCS-8440]: https://datadoghq.atlassian.net/browse/DOCS-8440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8440] adding logs_enabled to SNMP traps

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-python layer to version 97

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-js layer to version 113

---

content/en/serverless/azure_container_apps/_index.md

Remove apostrophes around datadoghq.com in Azure Container App documentation since it results in an invalid value for `DD_SITE`.

Remove Apostrophes around datadoghq.com in Azure Container App Documentation

---

content/en/database_monitoring/guide/aurora_autodiscovery.md

Aurora DB autodiscovery with DBM was previously in beta and is now GA. This PR removes the beta banner.
N/A

Remove beta label for DBM Aurora autodiscovery functionality

---

content/en/agent/remote_config/_index.md

Updates Remote Config environment support.

(Agent) Update remote config supported environments

---

assets/styles/components/_schema-table.scss

fixes `word-break` in schema-tables.
motivation:  https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5092
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-tablecontent-overflow/api/latest/usage-metering/#get-usage-across-your-account

fix word break in schma table

---

content/en/tracing/trace_pipeline/ingestion_mechanisms.md

Remove broken redirect

---

content/en/agent/basic_agent_usage/osx.md
content/en/agent/configuration/agent-commands.md

Clarifies restart commands for macOS.

(DOCS-8346)(Agent) Clarify restart for macos

---

content/en/tracing/_index.md

- New link to Getting Started with APM Tracing.
- Small typo fix.

Link to Getting Started Guide from Landing Page

---

layouts/shortcodes/dbm-mongodb-agent-beta-install-docker.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-kubernetes.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-linux.md
layouts/shortcodes/dbm-mongodb-agent-setup-docker.md

This PR bumps up the DBM for MongoDB beta agent version.

bump up mongodb dbm beta agent version

---

content/en/opentelemetry/interoperability/instrumentation_libraries.md

Quick Edits to OpenTelemetry Instrumentation Libraries Page

---

content/en/service_management/workflows/trigger.md

Hold off on merging til this goes live

(Workflows) Remove beta banner

---

content/en/tracing/trace_collection/library_injection_local.md

This setting did not get much usage in the public beta is being removed for GA.

library injection: remove blob configuration

---

content/en/serverless/guide/serverless_tracing_and_bundlers.md

Update the documentation on using bundlers with DD trace and the AWS CXDK
- [ X ] Please merge after reviewing

Add AWS CDK & esbuild docs to serverless

---

content/en/observability_pipelines/dual_ship_logs/_index.md

Remove alias

---

content/en/service_management/app_builder/expressions.md

(App Builder) nav bug workaround

---

assets/scripts/build-api-pages.js

Handle extensions for operations.

---

content/en/agent/supported_platforms.md

(DOCS-7830) Update Windows Support

---

content/en/tracing/guide/inferred-service-opt-in.md

Document list of peer tags, derived from https://github.com/DataDog/datadog-agent/blob/main/pkg/trace/stats/peer_tags.ini

List of peer.* tags for inferred dependencies beta

---

content/en/service_catalog/manage_entries.md

update description for auto-populated section and add reference to the inferred service doc page.
update description for auto-populated section and add reference to the inferred service doc page.

Update manage_entries.md to reference inferred service beta

---

content/en/metrics/custom_metrics.md

- Hotjar feedback to add Marketplace integrations as a source of custom metrics
- [DOCS-8483](https://datadoghq.atlassian.net/browse/DOCS-8483)
- Verified by Erica:
[DOCS-8483]: https://datadoghq.atlassian.net/browse/DOCS-8483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clarify marketplace integrations are custom metrics

---

content/en/service_management/app_builder/expressions.md

Adds headings for the disable sections so that people can link to them easily

Add headings for disable sections

---

content/en/quality_gates/setup/_index.md

Noticed the [creation workflow for a Quality Gate Rule](https://app.datadoghq.com/ci/quality-gates/rule/create) nests GitHub checks as the last step in the process, so updating the Setup doc page accordingly.

Quality Gates Setup Edit

---

content/en/integrations/guide/azure-programmatic-management.md

- Update the API key parameter
- Add a missing curly brace

Update API key param

---

content/en/containers/guide/operator-eks-addon.md

Next addon release includes Operator which support agent sidecar autoinjection for pods schedule on EKS Fargate instances. PR adds a callout on top of the page.

Add a note to EKS Addon guide about sidecar auto-injection support

---

content/en/network_monitoring/network_path/_index.md

[NETPATH-236] add note about network traffic generation

---

content/en/tracing/troubleshooting/_index.md

Support receives requests from customers using APM that ask questions about this message in the APM UI with some regularity (often raising it as an issue/bug). There's not information about this scenario in our public docs to understand this, creating the need to contact Datadog Support.

Add info for missing error message and stack trace

---

content/en/code_analysis/ide_plugins/_index.md
content/en/code_analysis/software_composition_analysis/_index.md
content/en/code_analysis/software_composition_analysis/setup.md
content/en/code_analysis/static_analysis/_index.md
content/en/code_analysis/static_analysis/generic_ci_providers.md
content/en/code_analysis/static_analysis/setup.md

Update Code Analysis overview & setup documentation. Motivation: Reflect updated onboarding and improve organization

Update Code Analysis overview & setup documentation 

---

layouts/shortcodes/observability_pipelines/configure_existing_pipelines/source_env_vars/http_client.md
layouts/shortcodes/observability_pipelines/source_settings/http_client.md

Updates the HTTP Client source.
[DOCS-8527](https://datadoghq.atlassian.net/browse/DOCS-8527)
[DOCS-8527]: https://datadoghq.atlassian.net/browse/DOCS-8527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8527] Update OP http client

---

content/en/code_analysis/software_composition_analysis/setup.md

Link Fixes

---

content/en/standard-attributes/_index.md

- Remove duplicated description that was overriding `http.request_id`.
- Add log to `http.version`.

Small Fixes to Standard Attributes Table

---

content/en/cloud_cost_management/saas_costs.md

Remove redundant public beta alerts

---

content/en/network_monitoring/network_path/setup.md

As we are onboarding more customers to the private beta of network path, we need to have setup instructions for configuring static paths in addition to dynamic paths.

[DOCS-8496] Adding Static paths setup to Network Path docs

---

content/en/tracing/guide/inferred-service-opt-in.md

There's a typo on the word "library".

fix library typo

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-extension layer to version 62

---

README.md

Make a small tweak to the README regarding branch naming conventions. Slack handle is recommended but not required. Forward slash is required for the build to run.

Small clarification on branch name requirements

---

content/en/cloud_cost_management/_index.md
content/en/containers/kubernetes/_index.md
content/en/continuous_integration/_index.md
content/en/database_monitoring/_index.md
content/en/getting_started/_index.md
content/en/getting_started/dashboards/_index.md
content/en/infrastructure/_index.md
content/en/logs/_index.md
content/en/metrics/_index.md
content/en/metrics/custom_metrics.md
content/en/monitors/_index.md
content/en/network_monitoring/_index.md
content/en/real_user_monitoring/_index.md
content/en/security/cloud_security_management/_index.md
content/en/security/cloud_siem/_index.md
content/en/serverless/_index.md
content/en/service_management/incident_management/_index.md
content/en/service_management/service_level_objectives/_index.md
content/en/synthetics/_index.md
content/en/tracing/_index.md

- Add a callout for the TEM enablement webinar sessions
- https://datadoghq.atlassian.net/browse/DOCS-8195
**Pending TEM team approval**

Add TEM callouts

---

content/en/getting_started/opentelemetry/_index.md

Add link to new OTel learning center content from the Getting Started guide.

Link to OTel Learning Center Callout from Docs

---

config/_default/menus/main.en.yaml

I forgot this in my initial PR. Whoops.

Add page to left nav

---

content/en/service_catalog/scorecards.md

Remove mention of metric name in Scorecards docs

---

content/en/network_monitoring/network_path/setup.md

Adding additional config information to Static paths, and linking to the config examples, adding more verbiage on static paths vs dynamic paths.
Do not merge, waiting on Eng and PM approval

[DOCS-8550] adding additional configs to network path static paths

---

config/_default/menus/main.en.yaml
content/en/code_analysis/faq/_index.md

We add a list of frequently asked questions that customers asked us during calls. This way, we can easily refer them to the list of questions and customers can proactively learn about the capabilities of our tools.

Code Analysis: add FAQ

---

content/en/code_analysis/troubleshooting/_index.md

This PR adds more error cases customers had. Customers will find the resolution to these issues in the page instead of asking a customer success manager.

Add glibc error

---

content/en/tracing/trace_collection/custom_instrumentation/go/otel.md

Documents an example using the AddEvent API for Go tracer.
https://github.com/DataDog/dd-trace-go/pull/2780

Document Span Events for Go

---

content/en/code_analysis/faq/_index.md

Clarify our support for WIndows.

Add question on Windows

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/android.md

We updated the logic around the DatadogInterceptor and TracingInterceptor in the Datadog RUM Android SDK and we need to update also the code snippets related with this.

Update the Android SDK DatadogInterceptor code snippets

---

content/en/serverless/step_functions/troubleshooting.md

Add troubleshooting for intermittently missing Step Functions traces
https://docs.google.com/document/d/13rKm3AoK_ez4EMuVvQcKb7PIcZ1GPIpj_g3CfSGVvQw/edit

Add troubleshooting for intermittently missing Step Functions traces

---

content/en/service_management/workflows/build.md

(Workflows) Input parameters are immutable

---

content/en/logs/log_collection/ios.md
content/en/real_user_monitoring/guide/mobile-sdk-upgrade.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/ios.md
content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/ios.md
content/en/tracing/trace_collection/custom_instrumentation/ios/otel.md

Fulfills a request made during a security review of [this PR](https://github.com/DataDog/documentation/pull/24142).
DOCS-8402

List SPM as the recommended package manager

---

content/en/service_catalog/scorecards.md

Adding details around custom rule evaluation

---

content/en/containers/kubernetes/distributions.md

Adding a containerd check is no longer necessary and results in an error.

remove outdated OKE info

---

content/en/tracing/troubleshooting/faq_apm.md

APM Troubleshooting Common Issues - Add Expanders

---

README.md

(maint) Update link to build setup guide

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md

add note to enable admission controller if using k8s

---

content/en/intelligent_test_runner/setup/swift.md

- The repo name appears to be a typo as per feedback described in [DOCS-8605](https://datadoghq.atlassian.net/browse/DOCS-8605).
Please wait for a reviewer on CI team to approve before merging. Thanks!
[DOCS-8605]: https://datadoghq.atlassian.net/browse/DOCS-8605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8605] Correct Swift repo name in Intelligent Test Runner

---

content/en/security/cloud_security_management/setup/agent/linux.md

Adds a link to the Agent docs. Requested by PM.

Add link to Agent docs

---

content/en/opentelemetry/_index.md

Custom instrumentation with OTel APIs is no longer beta. Remove mention of beta but leave the banner for now to help users find it.

Remove beta banner for OTel instrumentation

---

content/en/tracing/troubleshooting/faq_apm.md

This PR adds progamming language tabs to the APM FAQ documentation

added programming languages to the apm faq doc

---

content/en/logs/guide/logs-rbac-permissions.md
content/en/logs/guide/logs-rbac.md

Reverts DataDog/documentation#24433

Revert "Remove assumptions and add alert for feature flag"

---

config/_default/menus/api.ja.yaml

JA api nav is out of date
https://docs-staging.datadoghq.com/brian.deutsch/ja-api-nav/ja/api/latest/

Latest JA translated API nav

---

content/en/dashboards/ddsql_editor/reference/_index.md
content/en/dashboards/ddsql_editor/reference/data_types.md
content/en/dashboards/ddsql_editor/reference/expressions_and_operators.md
content/en/dashboards/ddsql_editor/reference/statements.md
content/en/dashboards/ddsql_editor/reference/tags.md

This clarifies some of the DDSQL editor language features to improve precision.

DDSQL Editor Clarifications

---

layouts/shortcodes/observability_pipelines/processors/dedupe.md

Clarify what example it is.
[DOCS-8492](https://datadoghq.atlassian.net/browse/DOCS-8492)
[DOCS-8492]: https://datadoghq.atlassian.net/browse/DOCS-8492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8492] Edit text

---

.github/workflows/code-freeze.yml

Unfreeze repo

---

content/en/real_user_monitoring/guide/_index.md
content/en/real_user_monitoring/guide/monitor-capacitor-applications-using-browser-sdk.md

- Adds a new guide on how to monitor Capacitor applications with the Browser SDK, as per [DOCS-8518](https://datadoghq.atlassian.net/browse/DOCS-8518).
[DOCS-8518]: https://datadoghq.atlassian.net/browse/DOCS-8518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Monitor Capacitor applications guide Browser SDK

---

content/en/service_catalog/_index.md

Adding new blog to Service Catalog docs

Adding blog to Service Catalog docs

---

content/en/database_monitoring/_index.md
content/en/database_monitoring/setup_mongodb/_index.md
content/en/database_monitoring/setup_mongodb/mongodbatlas.md
content/en/database_monitoring/setup_mongodb/selfhosted.md

This PR updates the DBM for MongoDB to public beta.

[dbm] change dbm for mongodb to public beta

---

content/en/dashboards/ddsql_editor/reference/aggregation_functions.md
content/en/dashboards/ddsql_editor/reference/data_types.md
content/en/dashboards/ddsql_editor/reference/expressions_and_operators.md
content/en/dashboards/ddsql_editor/reference/scalar_functions.md
content/en/dashboards/ddsql_editor/reference/statements.md

Updates the DDSQL documentation for ddsql editor to be more accurate to feature set available in DDSQL

[ddsql] update documentation

---

config/_default/menus/main.en.yaml
content/en/database_monitoring/setup_postgres/alloydb.md

Add AlloyDB DBM installation instructions

---

content/en/code_analysis/git_hooks/_index.md

Change script language so that we do not have the leading `$` character in the bash script.

Change script language

---

content/en/database_monitoring/setup_postgres/alloydb.md

This PR removes the `kind` frontmatter due to build issues

Remove kind

---

content/en/security/application_security/threats/protection.md

Update the link to Protection Settings that was broken as the place in the UI was modified

Update link for protection settings

---

content/en/cloud_cost_management/saas_costs.md

Fixes required permission names to align with the integration text. See [WEBINT-1477](https://datadoghq.atlassian.net/browse/WEBINT-1477) which includes screenshots.
I'll have someone in CCM review.
[WEBINT-1477]: https://datadoghq.atlassian.net/browse/WEBINT-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEBINT-1477 Fix Cloud Cost Management Mongodb costs permission text

---

content/en/security/application_security/threats/exploit-prevention.md

We recently release support for more library for exploit prevention, this is to reflect that in the documentation

(asm) Update exploit prevention support matrix

---

content/en/database_monitoring/setup_mongodb/mongodbatlas.md
content/en/database_monitoring/setup_mongodb/selfhosted.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-docker.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-kubernetes.md
layouts/shortcodes/dbm-mongodb-agent-beta-install-linux.md
layouts/shortcodes/dbm-mongodb-agent-data-collected.md
layouts/shortcodes/dbm-mongodb-agent-setup-docker.md

This PR updates dbm for mongodb doc to
- Bump the beta agent version
- Include a new `Data Collected` section

[dbm] update dbm for mongodb doc to include data collected

---

content/en/dashboards/ddsql_editor/reference/data_types.md
content/en/dashboards/ddsql_editor/reference/scalar_functions.md

Fixes some typos & adds an example for `timestamp 'now'` for DDSQL

[ddsql] tweaks & typos

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-extension layer to version 63

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-js layer to version 115

---

content/en/logs/explorer/facets.md

Adds a search term to the log facets page to help raise it in search results. Motivated by feedback from Nicholas Devlin.

Add log facets search term to log facets page

---

content/en/network_monitoring/network_path/setup.md

[Network Path] Fix indent
Reference: https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L1654-L1675

[Network Path] Fix indent

---

content/en/security/application_security/_index.md
content/en/security/application_security/code_security/setup/_index.md
content/en/security/application_security/serverless/_index.md
content/en/security/application_security/serverless/compatibility/_index.md
content/en/security/application_security/software_composition_analysis/setup/_index.md
content/en/security/application_security/threats/setup/single_step/_index.md
content/en/security/application_security/threats/setup/threat_detection/_index.md
content/en/security/application_security/threats/setup/threat_detection/dotnet.md
content/en/security/application_security/threats/setup/threat_detection/go.md
content/en/security/application_security/threats/setup/threat_detection/nginx.md
content/en/security/application_security/threats/setup/threat_detection/nodejs.md
content/en/security/application_security/threats/setup/threat_detection/php.md
content/en/security/application_security/threats/setup/threat_detection/python.md
content/en/security/application_security/threats/setup/threat_detection/ruby.md

added redirects where possible.
splitting some single topics into multiple topics made perfect redirects impossible. In those cases, I redirect to the root of the ASM docs.

adding redirects post-reorg

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md

Update the instructions to remove Singe Step on Linux VMs

Update instructions for Removing single step

---

content/en/code_analysis/faq/_index.md

We are introducing a new way to map services to static analysis event. This new documentation explains how the mapping works.

Add documentation on servicemapping

---

content/en/quality_gates/setup/_index.md

Had a customer who ran into an onboarding issue because they used an incorrect environment variable.
Chat with Mark [on Slack](https://dd.slack.com/archives/C04UY71LCTV/p1722437778576249)
Adds a note that `DATADOG_SITE` is not supported, but `DD_SITE` is.

Quality Gates Setup Documentation Edit

---

content/en/account_management/org_settings.md

- The format of this page follows the format of the in-app [Organization Settings](https://app.datadoghq.com/organization-settings/preferences) page. This PR update the docs so that the Log and Monitor information is relocated to the appropriate section (General > Preferences)
- https://datadoghq.atlassian.net/browse/DOCS-8564

Move org settings info to appropriate section

---

content/en/continuous_delivery/deployments/argocd.md

Change service label for multi-service discovery in Argo CD

Change service label for multi-service discovery in Argo CD

---

Makefile

[INTPLAT-183] Update Makefile

---

content/en/product_analytics/journeys/sankey.md

Reference link out to the Dashboard Sankey widget

---

content/en/sensitive_data_scanner/guide/redact_all_emails_except_from_specific_domain_logs.md

Small edit to title of SDS guide

---

content/en/cloud_cost_management/multisource_querying/_index.md

(DOCS-8601)(CCM) Update beta banner

---

content/en/synthetics/api_tests/dns_tests.md

[DOCS-8651](https://datadoghq.atlassian.net/browse/DOCS-8651)
[DOCS-8651]: https://datadoghq.atlassian.net/browse/DOCS-8651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8651] Update dns_tests.md

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-python layer to version 98

---

content/en/tests/auto_test_retries/_index.md

Let users know about this limitation with https://github.com/americanexpress/jest-image-snapshot
https://docs-staging.datadoghq.com/juan-fernandez/known-limitation-image-snapshot/tests/auto_test_retries/?tab=javascript#known-limitations

[test visibility] Add known limitation to auto test retries for Javascript

---

content/en/llm_observability/_index.md

Add a further reading section and blog link

Add further reading

---

content/en/serverless/aws_lambda/distributed_tracing.md

fix env var

---

content/en/serverless/aws_lambda/distributed_tracing.md

Clarify trace propagation in our tracing docs

---

config/_default/menus/main.en.yaml
content/en/observability_pipelines/destinations/_index.md

- Adds the individual processors and destinations to the nav (like the sources).
- Small updates to header names and correctly alphabetize destinations
[DOCS-8685](https://datadoghq.atlassian.net/browse/DOCS-8685)
[DOCS-8685]: https://datadoghq.atlassian.net/browse/DOCS-8685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8685] Add OP processors and destintations to nav

---

content/en/agent/supported_platforms.md

Slack conversation. All support for 2016+ is the same, so keeping it to one line.

(Agent) Update Windows support

---

content/en/agent/configuration/network.md

We got some feedback that the existing layout was confusing (and didn't explicitly mention tracing and the profiler).

(DOCS-8337)(Agent) Port layout update

---

content/en/security/upcoming_changes_notification_rules.md

added some more details on changes, as well as a hyperlink to the detection rules page filtered for rules having notifications configured

refresh ahead of full migration

---

content/en/code_analysis/faq/_index.md

Explain to customer how team mapping work for static analysis.

Explain how team mapping work

---

content/en/service_management/app_builder/queries.md

Adds polling interval and mocked outputs documentation
Approved by PM over Slack

(DOCS-8560) App Builder - Add polling interval and mocked outputs

---

content/en/profiler/enabling/python.md

Add row for timeline feature 

---

.gitlab-ci.yml

- Updates the image to the pinned version
- With the runner cache, we can not use the `latest` tag since updates are not getting used in the runner (translations failure last night for example)

Update image to pinned version

---

content/en/database_monitoring/connect_dbm_and_apm.md

Introducing full mode for APM/DBM for SQL Server.

APM/DBM full mode for SQL Server

---

content/en/cloud_cost_management/saas_costs.md

Deleting incorrect tag from OpenAI

---

content/en/tracing/trace_collection/library_injection_local.md

Waiting for engineering review.
Suggesting a change for admission controller's troubleshooting tip.
Based on CONS-6515

TLS Version unsupported case

---

content/en/infrastructure/resource_catalog/_index.md

A quick fix requested by Jessica Yang.

Make heading consistent with others

---

content/en/tests/containers.md

Add descriptions and up-to-date links to third party provider documentation for DD tracer environment variables. There is some mention of non-inclusive language here (surrounding Jenkins) and we choose to keep it in because it's the Jenkins vocabulary.
- [] Please merge after reviewing

DOCS-8676 Tests in Containers Doc Update

---

content/en/service_management/service_level_objectives/ootb_dashboard.md

update score info

---

layouts/partials/code_analysis/languages-getting-started.html

Add a tile for PHP in the language selector section of the Static Analysis product landing page.
https://docs-staging.datadoghq.com/alai97/add-static-analysis-language-tile/code_analysis/static_analysis

DOCS-8711 Static Analysis Update

---

content/ja/serverless/azure_app_services/azure_app_services_container.md

cleaning up stray ja file

---

content/en/tests/containers.md

Missed this Vale check; use straight quotes instead of smart quotes.

Tests in Containers Edit

---

content/en/llm_observability/setup/auto_instrumentation.md

Remove an additional supported version of the Langchain integration on the Auto Instrumentation doc page.
Chat with Yun and Michael on Slack

Auto Instrumentation Edit

---

content/en/dashboards/ddsql_editor/reference/aggregation_functions.md
content/en/dashboards/ddsql_editor/reference/scalar_functions.md

Cleaning up some issues I noticed
- Unnecessary heading
- Table formatting

Fix issues in DDSQL Editor docs

---

content/en/service_catalog/service_definitions.md

adding mention and reference to `codeLocation` field and link Code Analysis FAQ
adding mention and reference to `codeLocation` field and link Code Analysis FAQ

Update service_definitions.md v3

---

content/en/database_monitoring/setup_mongodb/mongodbatlas.md
content/en/database_monitoring/setup_mongodb/selfhosted.md
layouts/shortcodes/dbm-mongodb-before-you-begin.md
layouts/shortcodes/dbm-mongodb-beta-new-features

Add a new `New Features in Beta` section to DBM for MongoDB beta. This section highlights the new features in the latest beta agent and also help beta customers to find out they need to upgrade to the latest beta agent to access the new features.

[dbm] dbm for mongo beta new features

---

config/_default/menus/main.en.yaml
content/en/code_analysis/how_it_works/_index.md

Converts this doc page from a traditional Q&A-style FAQ to a "How It Works" doc page. 
We do not make promises about features being released in the public documentation: `Custom rule availability is planned for all beta customers at the end of Q3 2024.`.

DOCS-8704 Add How Code Analysis Works Documentation

---

layouts/shortcodes/notifications-integrations.md

DOCS-8700
Added MS Teams and ServiceNow to Integrations section.
Needs review by Enterprise Sales Engineer.

Updated topic with MS Teams and ServiceNow

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/go.md

Update private beta form for Orchestrion

---

.gitlab-ci.yml
content/en/logs/_index.md

- Updates the image to the latest version (fixes missing build output in gitlab)
Pipeline run https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/609215666

Point to latest image

---

content/en/security/cloud_security_management/guide/public-accessibility-logic.md

We now have public accessibility for other cloud providers, so we need this page to be more cloud-provider agnostic

[SEC-15088] Fix aws-specific paragraph

---

config/_default/menus/main.en.yaml
content/en/code_analysis/faq/_index.md

Converting this doc page back to an FAQ.
Chat with Julien and Kassen in #documentation on Slack

Add Code Analysis Frequently Asked Questions

---

content/en/tracing/trace_collection/compatibility/nodejs.md

fix nodejs.md complex framework usage formatting

---

content/en/dashboards/widgets/_index.md
content/en/notebooks/_index.md
content/en/observability_pipelines/processors/_index.md

For Tuesday Tasks:
- Added [Transform and enrich your logs with Datadog Observability Pipelines](https://www.datadoghq.com/blog/observability-pipelines-transform-and-enrich-logs/)

Add new blogs to docs

---

content/en/watchdog/insights.md

[DOCS-8699](https://datadoghq.atlassian.net/browse/DOCS-8699)
[DOCS-8699]: https://datadoghq.atlassian.net/browse/DOCS-8699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8699] fix watchdog links

---

content/en/real_user_monitoring/browser/advanced_configuration.md

Very simple fix: the original was referencing the wrong link. Updated after seeing a [HotJar comment](https://insights.hotjar.com/sites/1021060/surveys/responses/950698?prid=758885816) about it.

[rum] Fix feature flag link

---

content/en/security/application_security/how-appsec-works.md

Update Overview Section in How AppSec Works

---

content/en/service_management/service_level_objectives/ootb_dashboard.md

update ootb dashboard docs

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-extension layer to version 64

---

content/en/llm_observability/setup/api.md

Adds a note on the IO message section explaining how Datadog infers the IO value from the message.

DOCS-8728 LLM Observability API Reference Edit

---

content/en/monitors/guide/reduce-alert-flapping.md

Add document link for Composite Monitor and improve explanation.

Taka2noda patch 3

---

content/en/observability_pipelines/sources/splunk_hec.md
content/en/observability_pipelines/sources/splunk_tcp.md
content/en/observability_pipelines/sources/sumo_logic.md
content/en/observability_pipelines/sources/syslog.md

Update shortcodes to the correct ones.

Fix shortcodes for OP sources

---

content/en/security/upcoming_changes_notification_rules.md

small cleanup on notif migration doc following feedback

---

content/en/tracing/trace_explorer/search.md

Removing a misleading sentence

---

content/en/llm_observability/setup/_index.md
content/en/llm_observability/setup/sdk/_index.md

Instrumentation examples are bit outdated, customers have been directly copy pasting the logic in them which results in issues. This PR updates the instrumentation examples to contain more guidance on best practices.

[MLOBS] Update instrumentation examples in SDK docs

---

content/en/llm_observability/_index.md

Updates the spacing of the line break in the **## Use integrations with LLM Observability** section. Just noticed this.

LLM Observability Product Landing Page Edit

---

content/en/agent/configuration/agent-fips-proxy.md

(Agent) Rework FAQ in FIPS proxy doc

---

content/en/agent/basic_agent_usage/aix.md
content/en/getting_started/agent/_index.md
content/en/monitors/types/host.md

(Agent) Monitor AIX Agent uptime

---

content/en/security/application_security/troubleshooting.md

Update how to disable Code Security

---

content/en/tracing/trace_collection/compatibility/java.md

https://github.com/DataDog/dd-trace-java/pull/4634

Document Undertow compatibility for dd-trace-java

---

content/en/serverless/aws_lambda/metrics.md

Add context on Metrics Summary and outgoing links from Serverless Custom Metrics Page

---

content/en/llm_observability/setup/api.md

Add documentation for `Document` IO type and add clarification for setting IO values

[MLOBS] Update IO in API docs

---

content/en/logs/log_collection/csharp.md

- Refactor the code blocks for regions
- Add a note that references out to the package docs
- Remove example code to try and direct traffic to the package for more detailed examples.

Refactor serilog sink and reference out to the package docs

---

content/en/data_security/pci_compliance.md
layouts/shortcodes/pci-apm.md
layouts/shortcodes/pci-logs.md

Updating the onboarding documentation for PCI customers
- [ X ] Please merge after reviewing

Pci stages

---

content/en/security/application_security/code_security/setup/dotnet.md

Update Code Security enablement for .NET

---

content/en/security/application_security/code_security/setup/nodejs.md

Update Code Security enablement for Node.js

---

content/en/account_management/org_settings/ip_allowlist.md

Adds a note about a scenario that comes up sometimes in support tickets, but isn't documented clearly publicly.
I'll happily apply any suggested changes to reword the additional content.

Add note about mobile application access to IP Allowlist documentation

---

content/en/logs/guide/ease-troubleshooting-with-cross-product-correlation.md
content/es/logs/guide/ease-troubleshooting-with-cross-product-correlation.md
content/fr/logs/guide/ease-troubleshooting-with-cross-product-correlation.md
content/ja/logs/guide/ease-troubleshooting-with-cross-product-correlation.md
content/ko/logs/guide/ease-troubleshooting-with-cross-product-correlation.md

Existing trace and parent ids are outdated. (See related [discussion thread](https://dd.slack.com/archives/C044Y691H5Y/p1723103257089589?thread_ts=1723103103.816329&cid=C044Y691H5Y)). Update to the latest ones found in the OTel Repo. (See [here](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx))

Update the OpenTracing trace id to OTel specific ones

---

content/en/llm_observability/setup/auto_instrumentation.md

This PR adds missing detail about langchain integration supporting embeddings
PR that introduced the change : https://github.com/DataDog/dd-trace-py/pull/9850

Add langchain embedding support

---

content/en/logs/guide/reduce_data_transfer_fees.md
content/en/logs/log_collection/_index.md
content/en/logs/log_configuration/flex_logs.md

- New guide to reduce data transfer fees using cloud provider private links
- [DOCS-7886](https://datadoghq.atlassian.net/browse/DOCS-7886)
Do not merge, pending PM review
[DOCS-7886]: https://datadoghq.atlassian.net/browse/DOCS-7886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

New guide to reduce data transfer fees

---

content/en/account_management/org_settings/ip_allowlist.md

Inaccurate description of the location for the IP Allowlist settings, reported in Reported in #support-aaa

Update IP Allowlist docs: wrong section in Org Settings

---

content/en/observability_pipelines/sources/http_client.md

Fix typo. Confirmed with eng.
[DOCS-8749](https://datadoghq.atlassian.net/browse/DOCS-8749)
[DOCS-8749]: https://datadoghq.atlassian.net/browse/DOCS-8749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8749] Update http_client.md

---

content/en/product_analytics/heatmaps.md

Adds a redirect from RUM heatmaps to Product Analytics, as per [DOCS-8788](https://datadoghq.atlassian.net/browse/DOCS-8788)
[DOCS-8788]: https://datadoghq.atlassian.net/browse/DOCS-8788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add redirect from RUM Heatmaps to PA

---

content/en/agent/guide/windows-agent-ddagent-user.md

Add a version to an old note for a feature that was adding starting in 7.40.0
https://github.com/DataDog/datadog-agent/releases/tag/7.40.0

Add Agent version to old note

---

content/en/containers/kubernetes/log.md

- Make recommended configuration more noticeable 
- Add a new section for notes and reference it at the top of the section
- [DOCS-8486](https://datadoghq.atlassian.net/browse/DOCS-8486)
[DOCS-8486]: https://datadoghq.atlassian.net/browse/DOCS-8486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make the recommended configurations noticeable

---

layouts/shortcodes/aws-resource-collection.md

[AWSX-1003](https://datadoghq.atlassian.net/browse/AWSX-1003)
[AWSX-1003]: https://datadoghq.atlassian.net/browse/AWSX-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AWSX-1003 Add to the default set of permissions when integrating an AWS account for CCM

---

content/en/agent/basic_agent_usage/windows.md

See attached ticket. Also made a couple of minor edits. 
- Made some assumptions here, open to edits
- Not sure if these instructions apply to the Active Dir section. I can remove it if necessary.

(Agent) Add Windows installation directory note

---

.github/CODEOWNERS

XPQ team able to QA and review changes made to the References docs.

Add XPQ team as codeowners to DDSQL references

---

content/en/continuous_integration/search/_index.md

[ci-app] Update provider support list for CI Visibility's job log collection

---

content/en/dashboards/configure/_index.md

In accordance with approved changes here: https://docs.google.com/document/d/181YTocRCP8j4A1N4h6v8GFqvIaisTffFTYo18I5oQL0/edit#heading=h.h9v7ke3znd2x
Remove Enterprise package limits on Dashboard View Restrictions feature
No

Update _index.md to reflect View Restrictions packaging changes

---

layouts/shortcodes/csm-windows-setup.md

Adds a very important space in the configuration instructions for the CSM VM feature on Windows

add very important space to CSM Windows VM instructions

---

content/en/continuous_integration/pipelines/_index.md
content/en/continuous_integration/pipelines/custom.md

Adds instructions from the [in-app setup](https://app.datadoghq.com/ci/setup/pipeline?provider=custom) to the Custom Pipelines API doc page.

DOCS-8763 Send Custom Pipelines to Datadog Update

---

content/en/metrics/guide/custom_metrics_governance.md

The anchor link doesn't go to the expected section in the page

Update anchor link

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
content/en/tracing/trace_collection/compatibility/nodejs.md

- adds additional links to the complex framework usage section
- makes it easier for users to discover the caveats of the next.js and nest.js frameworks

crosslink to Node.js complex framework usage

---

content/en/opentelemetry/agent/install_agent_with_collector.md

- Replace existing command in Deploy the Agent with the OpenTelemetry Collector.
- New command uses config in otel-config.yaml.

Add new helm command.

---

content/en/profiler/enabling/ssi.md

We want to direct customers participating in the beta for Continuous Profiler + SSI to an instruction page. This is a private page, only accessible through direct link. Once Continuous Profiler + SSI transitions to public beta we will update supported public documentation, until then we'll use this page.

PROF-10397: Instructions for Continuous Profiler + SSI beta

---

local/bin/js/algolia-index-sync.js

Add a synonym to our internal search to help users find content where we use OTel or OpenTelemetry.
Preview: https://docs-staging.datadoghq.com/brett0000FF/otel-synonym/search/?s=otel

OpenTelemetry OTel Synonym

---

content/en/database_monitoring/setup_postgres/_index.md

The table doesn't provide much info since every box but one is checked. Removing and adding a sentence to declutter while covering the same info.

Remove table from Setting up Postgres page

---

content/en/real_user_monitoring/session_replay/mobile/_index.md

DOCS-8846
added note clarifying that we do not support session replay on smart TVs or wearables

add note about session replay support

---

content/en/tracing/guide/resource_based_sampling.md

This PR adds the minimum version for C++ required to support resource-based sampling.

Resource-base sampling: Update minimum version for C++

---

content/en/getting_started/tagging/assigning_tags.md

Add detail about how to specify multiple tags via DD_TAGS, and update the provided example

Add DD_TAGS detail

---

content/en/cloud_cost_management/_index.md
content/en/cloud_cost_management/aws.md
content/en/cloud_cost_management/azure.md
content/en/cloud_cost_management/container_cost_allocation.md
content/en/cloud_cost_management/custom.md
content/en/cloud_cost_management/datadog_costs/_index.md
content/en/cloud_cost_management/google_cloud.md
content/en/cloud_cost_management/multisource_querying/_index.md
content/en/cloud_cost_management/recommendations/_index.md
content/en/cloud_cost_management/saas_costs.md
content/en/cloud_cost_management/tag_pipelines.md
content/ja/cloud_cost_management/tag_pipelines.md

Removing the warning for Gov customers on CCM documentation 
https://datadoghq.atlassian.net/browse/CCC-167

[CCC-167] Remove Govcloud warning for CCM

---

config/_default/menus/main.en.yaml

Removing this `Frequently Asked Questions` page which currently redirects users to the Getting Started with Code Analysis doc page.

Remove Frequently Asked Questions in Navigation Menu

---

content/en/tests/auto_test_retries/_index.md

Adds documentation on auto test retries for Ruby because this feature is released

[SDTEST-437] Auto test retries for Ruby

---

content/en/metrics/units.md

- Add a reference note to the unit override guide
- [DOCS-8787](https://datadoghq.atlassian.net/browse/DOCS-8787)
[DOCS-8787]: https://datadoghq.atlassian.net/browse/DOCS-8787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add reference to unit override guide

---

content/en/logs/workspaces/_index.md

Add blog to Log Workspaces

---

content/en/monitors/guide/how-to-set-up-rbac-for-monitors.md

- Remove locked information
- Add references for the Restriction Policies API
- Changes requested by PM
**Do not merge**, pending PM final review

Remove locked info and add Restriction policies api

---

content/en/cloud_cost_management/azure.md

Added a bolded note section under a field to make sure users pay special notice to the step during setup.

Update azure.md to include note under `Overwrite Data` field

---

content/en/account_management/audit_trail/events.md
content/en/developers/ide_plugins/vscode/_index.md
content/en/getting_started/dashboards/_index.md
content/en/getting_started/integrations/aws.md
content/en/getting_started/integrations/azure.md
content/en/infrastructure/containers/orchestrator_explorer.md
content/en/logs/explorer/advanced_search.md
content/en/logs/explorer/analytics/patterns.md
content/en/logs/explorer/analytics/transactions.md
content/en/logs/log_configuration/online_archives.md
content/en/logs/log_configuration/pipelines.md
content/en/logs/log_configuration/processors.md
content/en/logs/log_configuration/rehydrating.md
content/en/logs/troubleshooting/_index.md
content/en/monitors/types/log.md
content/en/network_monitoring/devices/snmp_traps.md
content/en/opentelemetry/agent/install_agent_with_collector.md
content/en/security/cloud_siem/log_detection_rules.md
content/en/tracing/services/service_page.md
content/en/tracing/trace_explorer/trace_view.md
content/en/watchdog/insights.md

- Make the docs consistent, change Logs Explorer to Log Explorer to match the UI.
- I changed some of the image alts, but that's not a priority.
- https://datadoghq.atlassian.net/browse/DOCS-8490

Make Log Explorer consistent

---

local/bin/py/build/configurations/pull_config.yaml
local/bin/py/build/configurations/pull_config_preview.yaml

DOCS-8750
Adding search term metadata to improve ranking for 2 topics.

DOCS-8750 added search terms

---

content/en/observability_pipelines/destinations/_index.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/syslog.md
content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/_index.md
content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/syslog.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/_index.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/syslog.md
content/en/observability_pipelines/set_up_pipelines/log_volume_control/_index.md
content/en/observability_pipelines/set_up_pipelines/log_volume_control/syslog.md
content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/_index.md
content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/syslog.md
content/en/observability_pipelines/set_up_pipelines/split_logs/_index.md
content/en/observability_pipelines/set_up_pipelines/split_logs/syslog.md
content/en/observability_pipelines/sources/_index.md
content/en/observability_pipelines/sources/syslog.md

- Fixes case for mentions of rsyslog and syslog-ng.
[DOCS-8663](https://datadoghq.atlassian.net/browse/DOCS-8663)
[DOCS-8663]: https://datadoghq.atlassian.net/browse/DOCS-8663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8663] Fix rsyslog and syslog-ng case in Obs Pipelines docs

---

content/en/ddsql_editor/guide/ddsql_use_cases.md

- Fix wording of an example title

Fix example title in DDSQL Editor doc

---

content/en/cloud_cost_management/azure.md

Correct details on which Azure scopes are supported for MCA accounts
https://datadoghq.atlassian.net/browse/CCV-2124

Fix supported azure scopes

---

content/en/agent/configuration/dual-shipping.md
content/en/agent/guide/private-link.md
content/en/logs/guide/docker-logs-collection-troubleshooting-guide.md
content/en/serverless/aws_lambda/configuration.md

(Agent) Update to force_use_http

---

content/en/profiler/_index.md
content/en/security/_index.md

- https://www.datadoghq.com/blog/continuous-profiler-context-attributes/
- https://www.datadoghq.com/blog/investigate-denial-of-service-attacks/

Add Blog Links to Relevant Docs

---

config/_default/menus/main.fr.yaml
config/_default/menus/main.ja.yaml
config/_default/menus/main.ko.yaml

Update the left nav translated entries to assist with https://datadoghq.atlassian.net/browse/DOCS-8842
https://docs-staging.datadoghq.com/david.jones/left-menu/ja/

menu update

---

.github/workflows/code-freeze.yml

initiating code freeze on documentation repo

initiating Code freeze due to GH outage

---

.github/workflows/code-freeze.yml

GH is now stable so lifting the freeze

lifting freeze

---

content/en/profiler/enabling/dotnet.md
content/en/profiler/enabling/go.md
content/en/profiler/enabling/java.md
content/en/profiler/enabling/nodejs.md
content/en/profiler/enabling/php.md
content/en/profiler/enabling/python.md

Add lambda support clarification for profiling

---

layouts/shortcodes/observability_pipelines/configure_existing_pipelines/destination_env_vars/syslog.md
layouts/shortcodes/observability_pipelines/configure_existing_pipelines/source_env_vars/syslog.md
layouts/shortcodes/observability_pipelines/destination_env_vars/syslog.md
layouts/shortcodes/observability_pipelines/destination_settings/syslog.md
layouts/shortcodes/observability_pipelines/log_source_configuration/syslog.md

Fixes case for mentions of rsyslog and syslog-ng.
[DOCS-8663](https://datadoghq.atlassian.net/browse/DOCS-8663)
[DOCS-8663]: https://datadoghq.atlassian.net/browse/DOCS-8663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8663] Fix rsyslog and syslog-ng case (part 2)

---

content/en/sensitive_data_scanner/_index.md

- Updates OP section.
- Clean up links
[DOCS-8500](https://datadoghq.atlassian.net/browse/DOCS-8500)
[DOCS-8500]: https://datadoghq.atlassian.net/browse/DOCS-8500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8500] Update OP section in SDS doc

---

content/en/agent/guide/private-link.md

Add a note on configuration based on Agent version

---

content/en/observability_pipelines/set_up_pipelines/archive_logs/datadog_agent.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/fluent.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/http_client.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/splunk_hec.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/splunk_tcp.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/sumo_logic_hosted_collector.md
content/en/observability_pipelines/set_up_pipelines/archive_logs/syslog.md
content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/fluent.md
content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/http_client.md
content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/syslog.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/fluent.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/http_client.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/syslog.md
content/en/observability_pipelines/set_up_pipelines/log_volume_control/fluent.md
content/en/observability_pipelines/set_up_pipelines/log_volume_control/http_client.md
content/en/observability_pipelines/set_up_pipelines/log_volume_control/syslog.md
content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/fluent.md
content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/http_client.md
content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/syslog.md
content/en/observability_pipelines/set_up_pipelines/split_logs/fluent.md
content/en/observability_pipelines/set_up_pipelines/split_logs/http_client.md
content/en/observability_pipelines/set_up_pipelines/split_logs/syslog.md

- Fixes headers
- Adds missing sentence.

Fix headers and add missing sentence in OP docs

---

content/en/real_user_monitoring/session_replay/mobile/troubleshooting.md

Added extra information to the Mobile Session Replay troubleshooting section with regard to replays that may appear broken due to missing images.

Add images section to troubleshooting in MSR

---

content/en/dashboards/sharing/public_dashboards.md

- Remove notes on APM limitation for Dashboard public sharing. This is not applicable.

Remove APM note

---

content/en/llm_observability/setup/auto_instrumentation.md

Clarifies the use case for manual instrumentation vs. auto instrumentation for users who are confused.
Raised in #support-ml-obs on Slack

LLM Observability Auto Instrumentation Update

---

content/en/metrics/custom_metrics/_index.md

Added example on what a unique tag value combination is

Added example to custom metrics page detailing "a unique tag value combination"

---

README.md

- Add link to the ReadME so internal staff can find their username quickly

Add link to the slack account settings

---

README.md

How to locate Slack username

---

local/bin/py/build/actions/security_rules.py
local/bin/py/build/configurations/pull_config_preview.yaml

unexpected tag value for some new sec rules
security rules look good: https://docs-staging.datadoghq.com/brian.deutsch/sec-rule-fail/security/default_rules/#all
build passed: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/628819682
example of problematic tag value: https://github.com/DataDog/security-monitoring/blob/811ac6491d0f40434e594647fe667da2b14e6eef/posture-management/application-security/unauth-route-sensitive-data-predictable-ids.json#L7

fix pipelines

---

content/en/account_management/_index.md

- Digest emails are only available in US1 and EU1 regions
- [DOCS-8895](https://datadoghq.atlassian.net/browse/DOCS-8895)
[DOCS-8895]: https://datadoghq.atlassian.net/browse/DOCS-8895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a site warning for limited availability

---

content/en/serverless/azure_app_services/azure_app_services_linux.md

Update the version of the DataDog/datadog-aas-linux datadog_wrapper to the latest.

Update datadog-aas-linux version in azure_app_services_linux.md

---

content/en/security/application_security/code_security/setup/_index.md

Instructions to setup Code Security (aka IAST) with SSI+Docker do not match our in-app instructions. I changed this to match what we show in app.

Align IAST SSI documentation with in-app instructions

---

content/en/security/security_inbox.md

Several smaller updates requested by PM. See DOCS-8897 for details.

DOCS-8897: Security Inbox updates

---

content/en/dashboards/guide/_index.md
content/en/dashboards/guide/is-read-only-deprecation.md

Formatting and copy suggestions

---

content/en/serverless/aws_lambda/metrics.md

Add clarity to our Enhanced Metrics page about the ways to get Metrics from AWS Lambda

---

config/_default/menus/main.en.yaml
content/en/observability_pipelines/processors/_index.md
content/en/observability_pipelines/processors/add_hostname.md
content/en/observability_pipelines/processors/edit_fields.md
content/en/observability_pipelines/processors/enrichment_table.md
content/en/observability_pipelines/processors/filter.md
content/en/observability_pipelines/processors/grok_parser.md
content/en/observability_pipelines/processors/parse_json.md
content/en/observability_pipelines/processors/quota.md
content/en/observability_pipelines/processors/reduce.md
content/en/observability_pipelines/processors/sample.md
content/en/observability_pipelines/processors/sensitive_data_scanner.md

- Separates out processors to individual docs
- Updates the nav to link to the new docs
[DOCS-8863](https://datadoghq.atlassian.net/browse/DOCS-8863)
[DOCS-8863]: https://datadoghq.atlassian.net/browse/DOCS-8863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8863] Add individual processor docs

---

content/en/observability_pipelines/sources/_index.md

Adding back the list of sources for consistency with Processors and Destinations. Also PM request.

Add back source list

---

content/en/mobile/_index.md

Note that the log-in button seems to have different verbiage on different mobile platforms, so I just used "log-in button" as a general reference.

Add more detail to mobile log-in steps

---

content/en/security/guide/aws_fargate_config_guide.md

Adding simple instructions to set up SCA in applications that run in AWS Fargate
Adding simple instructions to set up SCA in applications that run in AWS Fargate

Adding SCA for Fargate instructions

---

content/en/database_monitoring/connect_dbm_and_apm.md

Adding full APM/DBM mode for SQL Server and .Net.

Add full APM/DBM mode for SQL Server and .Net

---

content/en/universal_service_monitoring/setup.md

feature is no longer in beta, and enabled by default on Windows non-IIS hosts

USM Windows non-IIS services no longer in beta

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
content/en/tracing/trace_collection/library_injection_local.md

Updates the default version of the .NET library used for SSI library-injection to v3
https://datadoghq.atlassian.net/browse/APMON-1390

[SSI][.NET]Update the default version used for .NET for SSI to v3

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md

updated operator install instruction to include helm repo update

updated operator install instruction

---

config/_default/menus/main.en.yaml
content/en/observability_pipelines/processors/_index.md
content/en/observability_pipelines/processors/dedupe.md
layouts/shortcodes/observability_pipelines/processors/dedupe.md

- Adds the deduplicate processor reference doc (no new content)
- Adds nav item
- Adds link to new doc on main processor list
- Makes a couple of small edits

Add deduplicate processor ref doc

---

content/en/service_management/app_builder/components/_index.md

Documents the new file input component

(DOCS-8969) Add file input component documentation

---

content/en/database_monitoring/setup_sql_server/azure.md

(DBM) Fix some broken links

---

content/en/security/application_security/threats/exploit-prevention.md

Update the Exploit Prevention compatibility matrix with the new features in dd-trace-java v1.39.0

Update Exploit Prevention compatibility for dd-trace-java v1.39.0

---

content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md

- Users are looking for AWS Lambda content on **OTLP Ingestion by the Datadog Agent**.
- Add new tab with brief content and link to serverless docs for more info.

Link to AWS Lambda Instructions from OTLP Ingestion Page

---

content/en/api/v2/incidents/request.CreateIncident.json

- Add more examples for the notification_handles parameter
- [DOCS-8944](https://datadoghq.atlassian.net/browse/DOCS-8944)
- https://github.com/DataDog/datadog-api-spec/pull/3100
[DOCS-8944]: https://datadoghq.atlassian.net/browse/DOCS-8944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add notification_handles attribute examples

---

content/en/logs/guide/azure-logging-guide.md

Add a note about region limitations

Add region note

---

content/en/getting_started/database_monitoring/_index.md

https://datadoghq.atlassian.net/browse/DOCS-8644
According to this ticket ^^, DBM is supported for GovCloud, so I am removing the warning label that says it is not supported.

Remove "unsupported" warning for DBM on US1-FED

---

content/en/tracing/guide/ignoring_apm_resources.md

https://datadoghq.atlassian.net/browse/DOCS-8576
A user that "cannot" should be changed to "can". "Cannot" is actually the correct word here, but I added a bit to the sentence to clarify the reasoning.

Clarify sentence about dropping traces

---

content/en/security/cloud_security_management/setup/agent/_index.md
content/en/security/cloud_security_management/setup/agentless_scanning/_index.md
content/en/security/cloud_security_management/setup/cloudtrail_logs.md

Removes aliases that point to the same file location.

Remove unnecessary aliases

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-extension layer to version 65

---

content/en/logs/guide/azure-logging-guide.md

Update the casing of a tab for consistency

Fix tab casing

---

content/en/getting_started/devsecops/_index.md

Update DevSecOps enablement instructions

---

content/en/infrastructure/list.md

update the page to add a note to address a commonly asked question

---

content/en/cloud_cost_management/recommendations/_index.md

Add four more recommendation types with descriptions on the CCM Recommendations doc page.

DOCS-8880 Cloud Cost Recommendations Update 

---

content/en/agent/remote_config/_index.md

added a feature that developed using Remote Config

---

content/en/observability_pipelines/troubleshooting.md

Updates the Troubleshooting doc to use the destinations batching shortcode.

Use destination batching shortcode

---

content/en/service_management/app_builder/components/_index.md
content/en/service_management/app_builder/events.md
content/en/service_management/app_builder/queries.md

* documents fetch state function
* adds link from post query hook section to state function section

(DOCS-8981) Adds documentation for fetch query state function

---

content/en/security/application_security/code_security/setup/_index.md

Update Code Security enablement

---

content/en/account_management/api-app-keys.md
content/en/api/latest/scopes/_index.md

We recently updated Application Key scopes so that they are compatible with any permissions on Datadog. Previously, they shared the same set of permissions as authorization scopes for OAuth applications. Now that they are separated, we don't want to suggest that Application Key scopes are still limited, so we're removing the backlinks from each page.

[ACCESS-2693] Scopes docs update

---

content/en/opentelemetry/agent/_index.md

added two links to cross reference

---

content/en/cloud_cost_management/container_cost_allocation.md

Documents data transfer cost allocation features.

[CCA-182] add ccm networking docs

---

content/en/security/application_security/code_security/_index.md

Update code-level vulnerabilities list

---

content/en/opentelemetry/interoperability/instrumentation_libraries.md

Adds details on what we trace from OTEL and how customers could get that feature working, also links to an incoming sandbox which I need to merge before merging this PR.
The Sandbox link will give a 404 until the sandbox PR is merged(still looking for owner): https://github.com/DataDog/trace-examples/pull/126

Adding PHP Drop In Support

---

content/en/tracing/trace_collection/library_config/nodejs.md
content/ja/tracing/trace_collection/library_config/nodejs.md

- There was duplication of the tag DD_TRACE_DEBUG in the documentation on the Node.js, removed for a cleaner documentation.

Update node.js library configuration: Remove duplication DD_TRACE_DEBUG

---

content/en/security/cloud_security_management/guide/agent_variables.md
content/en/security/cloud_security_management/setup/agent/linux.md

Removes unused variables for CSM Vulnerabilities.

Remove unused variables

---

content/en/developers/integrations/oauth_for_integrations.md

(DOCS-9008) remove beta banner

---

config/_default/menus/main.en.yaml

Moves OP Troubleshooting to bottom of OP section.

Move OP troubleshooting in nav

---

assets/scripts/config/regions.config.js
content/en/opentelemetry/otlp_metrics.md

Add draft of private beta docs for OTLP metrics intake endpoint.

OTLP Metrics Intake Endpoint

---

content/en/opentelemetry/otlp_metrics.md

Fix Anchor in OTLP Metric Endpoint

---

content/en/network_monitoring/performance/setup.md

Due to product lifecycle changes, this particular feature is currently in private beta, however, the PM is putting this on pause for the time-being and asked to have it removed from the docs for now :)

Removed Failed connections from NPM setup page

---

data/synthetics_worker_versions.json

Update windows-pl version manually as:
- it is an urgent update (#incident-30449)
- the automation workflow has been [broken](https://github.com/DataDog/documentation/actions/workflows/bump_synthetics_worker_version.yml)

[s8s] Bump windows-pl to 1.51.0

---

content/en/intelligent_test_runner/_index.md

Documenting a known limitation of a feature we recently released.

[SDTEST] Update ITR PR labels docs - document a known limitation

---

content/en/infrastructure/containers/orchestrator_explorer.md

removes an outdated mention of a beta. can be merged at any time, doesn't have to wait for the lifecycle update situation

remove outdated beta mention

---

content/en/account_management/plan_and_usage/cost_details.md

remove beta mention for cost summary

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-rb layer to version 23

---

content/en/security/application_security/how-appsec-works.md
content/en/security/application_security/threats/library_configuration.md
content/en/tracing/configure_data_security/_index.md

DOCS-8948
updates for ASM collecting User Data by default for account takeover (ATO) protection
Waiting for PM and Legal reviews

updates for account takeover (ATO) protection

---

content/en/real_user_monitoring/error_tracking/mobile/android.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/android.md

This API is already mentioned few lines above.

Remove API reference duplication in Advanced setup of Android RUM SDK

---

content/en/network_monitoring/performance/_index.md
content/en/universal_service_monitoring/_index.md

Adds blog links to NPM and USM docs.

Add blog links to NPM and USM docs

---

content/en/account_management/authn_mapping/_index.md

This mention is 5 years old. Just removing it and rephrasing as general advice.

update outdated beta mention

---

content/en/opentelemetry/collector_exporter/configuration.md

I've tried to follow this instruction but figured out this config does not work. And proposing the correct config on this commit.

Fix collector.yaml for misconfiguration

---

content/en/security/application_security/api-inventory/_index.md

- Users were unaware which asm product was required for API security to work
- We also noticed that for the .NET tracer, an environment variable had to be enable. This will not be required in future version of the tracers (release date TBD).

[ASM] Add clarifications to the API Security page

---

content/en/tests/code_coverage.md

Let users know about total code coverage for vitest.
Additionally, I've slightly re-orged the section. I think it looks better now.
https://docs-staging.datadoghq.com/juan-fernandez/total-code-coverage-vitest/tests/code_coverage/?tab=javascripttypescript

[test visibility] Total code coverage for vitest

---

layouts/partials/dynamic_instrumentation/symbol-database-languages.html

Preview: https://docs-staging.datadoghq.com/ojung/DEBUG-2827-open-beta-symdb-for-dotnet-fix/dynamic_instrumentation/symdb/

Add dotnet to symdb language overview

---

content/en/tracing/trace_collection/compatibility/java.md

Fixes a typo resulting in the incorrect command being provided to users.

Fix missing character causing argument to be parsed incorrectly

---

content/en/real_user_monitoring/guide/enable-rum-shopify-store.md

Remove association of RUM and funnels.

Funnels is not part of RUM

---

content/en/account_management/billing/azure.md

I'm attempting to update the wording of "Configuration Tab" to "Metric Collection Tab", which is what it is correctly called in the UI.

Azure VM Exclusion wording update

---

content/ja/serverless/azure_app_services/azure_app_services_windows.md

There is a slight delay in this doc page being updated due to an untranslated string in Transifex, so while the HTML has been fixed, the change has not made in GitHub yet so we are implementing this page fix temporarily to improve how the [live doc page](https://docs.datadoghq.com/ja/serverless/azure_app_services/azure_app_services_windows/?tab=net) renders.

Temporarily Fix Page Formatting in Azure App Service - Windows Code (JA)

---

content/en/monitors/quality/_index.md

Better explain that both muted and partially muted monitor are part of the suggestion

Muted monitor suggestion fix

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump dd-trace-dotnet layer to version 16

---

content/en/service_management/events/_index.md

Removes beta references. The product is already GA, this reference just got missed and is incorrect.

Remove beta references

---

config/_default/menus/main.en.yaml

Reorders pages in the left nav
Preview link: https://docs-staging.datadoghq.com/neko/DOCS-8485-appb-nav/service_management/app_builder/

(DOCS-8485) - App Builder - reorder left nav

---

content/en/dora_metrics/setup/deployments.md

Remove Extra Alias

---

content/en/monitors/types/netflow.md
content/en/network_monitoring/devices/device_topology_map.md

The NetFlow Monitoring page link was 404'ing, so this PR batch replaces instances of the old link to the live page link.
Flagged by Jackie in #documentation Slack

Update NetFlow Monitoring Page Links

---

content/en/product_analytics/heatmaps.md

[DOCS-8955] Add information about heatmap backgrounds

---

content/en/agent/configuration/secrets-management.md

This PR adds an example PowerShell script to process secrets.

Add PowerShell example in secret management

---

.gitlab-ci.yml
layouts/_default/list.algolia.json
layouts/partials/algolia/api-page-index.json
layouts/partials/algolia/page-sections.json
local/bin/js/typesense_sync.cjs
package.json
typesense.config.json
yarn.lock

This PR is for the build pipeline jobs and does the following:
* Adds indexing to typesense as well as the existing algolia
* Updates index to have consistent fields across all records
There shouldn't be any frontend impact but at least check the search box is still showing results.
https://docs-staging.datadoghq.com/david.jones/search/
[Example pipeline](https://gitlab.ddbuild.io/DataDog/documentation/-/pipelines/44998841) with both index jobs running sucessfully

Search indexes

---

content/en/security/application_security/threats/add-user-info.md

Expand on what we do for anonymization.

sec/appsec/add-user-info.md: expand on anonymization

---

content/en/error_tracking/backend/_index.md

Did not rename the product phases to align with the larger initiative with new product launch phases.

Update backend standalone error tracking preview sign up link

---

content/en/tracing/guide/adaptive_sampling.md

- Remove "simple" term.
- Indent image in instructions.

Minor style tweaks to adaptive sampling page

---

content/en/database_monitoring/setup_mysql/_index.md
content/en/database_monitoring/setup_mysql/rds.md
content/en/database_monitoring/setup_mysql/selfhosted.md
content/en/database_monitoring/setup_mysql/troubleshooting.md

This PR adds DBM for MySQL support compatibility for MariaDB.

[dbm] add dbm for mariadb support compatibility

---

content/en/dora_metrics/setup/failures.md

From Slack. Fixes a broken shortcode. These sometimes don't render properly in tabs unless you use HTML

(maint) Replace markdown table to fix shortcode

---

content/en/observability_pipelines/set_up_pipelines/archive_logs/datadog_agent.md
content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/datadog_agent.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/datadog_agent.md
content/en/observability_pipelines/set_up_pipelines/log_volume_control/datadog_agent.md
content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/datadog_agent.md
content/en/observability_pipelines/set_up_pipelines/split_logs/datadog_agent.md
content/en/observability_pipelines/sources/datadog_agent.md
layouts/shortcodes/observability_pipelines/log_source_configuration/datadog_agent.md
layouts/shortcodes/observability_pipelines/log_source_configuration/datadog_agent_kubernetes.md

- Adds tabs for Agent configuration and helm chart values instructions.
- Adds helm chart values instructions.
[DOCS-8992](https://datadoghq.atlassian.net/browse/DOCS-8992)
[DOCS-8992]: https://datadoghq.atlassian.net/browse/DOCS-8992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8992] Add helm chart values instructions for connecting Agent to Worker

---

content/en/monitors/_index.md
content/en/monitors/notify/_index.md
content/en/monitors/notify/variables.md

- Add new monitor learning center course to further reading
- Remove enablement session callout

Add new learning center courses and remove enablement callout

---

content/en/monitors/types/error_tracking.md

New Error Tracking monitor behavior documentation update

---

.github/workflows/bump_synthetics_worker_version.yml
.github/workflows/bump_versions.yml
.github/workflows/check_cache_values.yml
.github/workflows/code-freeze.yml
.github/workflows/datadog-static-analysis.yml
.github/workflows/gif_check.yml
.github/workflows/preview_link.yml
.github/workflows/synthetics.yml
.github/workflows/vale_linter.yml
.github/workflows/validate_filenames.yml

Makes a small update to our GitHub workflows to improve security.
I'll ask websites for approval, then ask the docs team for a courtesy approval. Thanks!

Don't let the checkout action store the token

---

content/en/real_user_monitoring/browser/advanced_configuration.md

Add documentation for custom view specific context with current and new APIs.

[RUM 6317] Add documentation for view context feature

---

content/en/llm_observability/configuration/_index.md

reduces redundancy on OAI policy

---

content/en/service_management/case_management/create_case.md

- I found some case creations workflows that didn't match the UI

Updated workflow for creating a case

---

content/en/integrations/guide/source-code-integration.md

https://datadoghq.atlassian.net/browse/SCICM-2626

[SCICM-2626] Remove PHP tagging instructions

---

content/en/account_management/saml/_index.md

Information on Azure Entra ID requested on https://datadoghq.atlassian.net/browse/DOCS-9038. I added additional section headers for clarity.

Add note on Azure Entra ID attributes for SAML

---

content/en/security/cloud_security_management/setup/agent/kubernetes.md

Fix documentation regarding uncompressed layers

---

content/en/real_user_monitoring/browser/monitoring_page_performance.md

Docs currently don't note that custom vital names cannot have spaces or special characters. Ideally this would give something like a regex that matches all valid names, but I don't know that regex.

Add note about custom vital names

---

content/en/service_catalog/enrich_default_catalog/_index.md

add links to service override and instruction for removing 'noisy' services
add links to service override and instruction for removing 'noisy' services

add details on inferred service experience

---

content/en/observability_pipelines/set_up_pipelines/log_enrichment/fluent.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/http_client.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/splunk_hec.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/splunk_tcp.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/sumo_logic_hosted_collector.md
content/en/observability_pipelines/set_up_pipelines/log_enrichment/syslog.md

Fix typos in Log Enrichment source docs

---

content/en/security/cloud_security_management/setup/supported_deployment_types.md

Update CSM VM deployment types

---

content/en/logs/guide/_index.md
content/en/logs/guide/aws-account-level-logs.md

Add a new guide for setting up AWS account-level log subscriptions

(DOCS-8698) Add AWS account-level logs guide

---

content/en/tests/early_flake_detection/_index.md

Use new nomenclature
https://docs-staging.datadoghq.com/juan-fernandez/rename-beta-efd/tests/early_flake_detection/?tab=javascripttypescript

[test visibility] Rename beta to preview in early flake detection

---

content/en/tests/early_flake_detection/_index.md

Let users know about the new supported versions.
https://docs-staging.datadoghq.com/juan-fernandez/efd-new-support/tests/early_flake_detection/?tab=javascripttypescript#compatibility

[test visibility] New supported versions for Early Flake Detection

---

content/en/monitors/types/metric.md

- Clarify the wording on the definition for full window
- [DOCS-9112](https://datadoghq.atlassian.net/browse/DOCS-9112)
[DOCS-9112]: https://datadoghq.atlassian.net/browse/DOCS-9112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clarify definition of full window

---

layouts/shortcodes/observability_pipelines/processors/remap.md

Small update to the drop field description. Eng request.

Update drop field description

---

content/en/service_management/on-call/_index.md
content/en/service_management/on-call/escalation_policies.md
content/en/service_management/on-call/pages.md
content/en/service_management/on-call/processing_rules.md
content/en/service_management/on-call/profile_settings.md
content/en/service_management/on-call/schedules.md
content/en/service_management/on-call/teams.md

Adds a warning to the On-Call section pages.

DOCS-9158 - On-Call is not available for US1-Fed

---

data/synthetics_worker_versions.json

Manual bump of windows-pl version as the automation workflow has been [broken]
(https://github.com/DataDog/documentation/actions/workflows/bump_synthetics_worker_version.yml)

[s8s] release windows-pl 1.52

---

content/en/product_analytics/user_retention.md

Refines the prereq statement for User Retention
@maxime-matheron let me know if this could be further improved!

Refine prereq for User Retention

---

content/en/network_monitoring/network_path/setup.md

[network_path] update static path example

[network_path] update static path example

---

content/en/security/cloud_security_management/setup/agentless_scanning/_index.md
content/en/security/cloud_security_management/setup/agentless_scanning/cloudformation.md
content/en/security/cloud_security_management/setup/agentless_scanning/quick_start.md

Adds a note about Agentless Scanning costs. Requested by PM.

Add note about Agentless Scanning costs

---

content/en/getting_started/tagging/unified_service_tagging.md

Add support information for ECS Fargate with Fluent Bit

---

content/en/security/cloud_security_management/guide/active-protection.md
content/en/security/threats/workload_security_rules/custom_rules.md

DOCS-9121
Updates a permission name.
Waiting for tech review as this is a security perm.

update kill action permission name in CWS

---

content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md

Add uncompressedlayers troubleshooting for Helm in CSM VM

---

content/en/serverless/azure_app_services/azure_app_services_linux.md

Release Azure App Services Linux v1.10.9

---

content/en/network_monitoring/devices/getting_started.md

Remove beta labels for SD-WAN - change to "in Preview" as these products are not quite ready for GA

Remove beta labels for SD-WAN

---

content/en/profiler/guide/solve-memory-leaks.md

The Memory Leaks section works for either Go or Java, but both require the Datadog Kubernetes integration.

Update requirements for memory leak workflow

---

content/en/account_management/saml/okta.md

due to a change in Okta, we require that customers currently add a leading forward slash to the company ID in Okta
See previously closed PR
https://github.com/DataDog/documentation/pull/25575

Update DD <> Okta SAML instructions to add a leading / to company ID

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump datadog-lambda-python layer to version 99

---

content/en/database_monitoring/setup_mongodb/_index.md
content/en/database_monitoring/setup_mongodb/mongodbatlas.md
content/en/database_monitoring/setup_mongodb/selfhosted.md

This PR adds `MongoDB 8.0` to the DBM for MongoDB support list.

[dbm] support mongodb 8.0

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md

- adds `clearAllData`
- under initialization parameters, adds `bundleLogsWithRum` and `bundleLogsWithTraces`

DOCS-8449 - Add missing APIs for React Native

---

content/en/getting_started/code_analysis/_index.md

Fix errors in the instructions to set up service catalog for code analysis.
Please merge after approval.

update service catalog instructions

---

config/_default/menus/main.en.yaml
go.mod
go.sum

Reverts DataDog/documentation#25588

Revert "Adds `on-call` icon - [WEB-5395]"

---

content/en/security/cloud_siem/security_operational_metrics.md

Fix the timestamps of the Security Operational Metrics.

Fix the timestamps of the Security Operational Metrics

---

content/en/cloud_cost_management/tag_pipelines.md

Add a sentence to the public docs about full support for tag pipelines on all cloud cost metrics.

CCM clarify Cloud Cost pipeline applicability

---

layouts/partials/integrations-carousel/integrations-carousel-modal.html
layouts/partials/integrations-carousel/integrations-carousel.html

update integration carousel media endpoint
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5388
preview:  https://docs-staging.datadoghq.com/stefon.simmons/update-integration-carousel-img-endpoint/integrations/
- example: https://docs-staging.datadoghq.com/stefon.simmons/update-integration-carousel-img-endpoint/integrations/agentil_software_sap_netweaver/
- select another integration page that has a carousel. the image src should look like `https://s3.amazonaws.com/dd-app-listings/<app_id>/media/<image>`

update integration carousel media endpoint - [WEB-5388]

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md
content/es/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/reactnative.md

Updates the docs as part of [RUM-5418](https://datadoghq.atlassian.net/browse/RUM-5418) and [this PR](https://github.com/DataDog/dd-sdk-reactnative/pull/726) in the React Native RUM SDK.
CC'ing @plousada @marco-saia-datadog as reviewers
[RUM-5418]: https://datadoghq.atlassian.net/browse/RUM-5418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[RUM-5418] Update docs for new React Native SDK API

---

content/en/synthetics/_index.md
content/en/synthetics/browser_tests/_index.md

Updates the Further reading links to the new Synthetic Monitoring course on the learning center

[DOCS-9188] updating learning center course

---

content/en/opentelemetry/integrations/trace_metrics.md
content/en/opentelemetry/schema_semantics/host_metadata.md
content/en/opentelemetry/schema_semantics/service_entry_spans.md

Updating all docs to reflect [product lifecycle changes](https://datadoghq.atlassian.net/wiki/spaces/PM/pages/3310617880/Updated+Product+Lifecycle+DatadogunreadCommentMark=67c51abe-864c-419a-90ef-79e6e4934f84).

Lifecycle Update: OTel semantic conventions.

---

content/en/account_management/api-app-keys.md

Remove a link that looks to have been missed in [this PR](https://github.com/DataDog/documentation/pull/25228)

Remove link

---

config/_default/menus/main.en.yaml
content/en/account_management/rbac/granular_access.md
content/en/security/access_control.md
content/en/security/detection_rules/_index.md
content/en/security/suppressions.md
layouts/shortcodes/security-products/detection-rules-granular-access.md
layouts/shortcodes/security-products/suppressions-granular-access.md

- Adds the Security Access Control doc
- Adds nav item for new doc
[DOCS-8925](https://datadoghq.atlassian.net/browse/DOCS-8925)
[DOCS-8925]: https://datadoghq.atlassian.net/browse/DOCS-8925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-8925] Add Security Access Control doc

---

content/en/observability_pipelines/advanced_configurations.md

- Adds a note about unique data dirs for multiple OP Workers.

[DOCS-9002] Add note about using unique data dirs

---

content/en/observability_pipelines/legacy/setup/datadog.md

Updates a single word to be more accurate.

Single word change in observability pipelines

---

content/en/serverless/step_functions/troubleshooting.md

- Add note to recommend updating Step Functions and Lambda Forwarder
- Add warning for log pipelines

SFN Troubleshooting Updates

---

content/en/security/cloud_security_management/setup/agent/kubernetes.md
content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md

Update CSM K8s setup for VM to fix uncompressedLayers issues

---

content/en/product_analytics/heatmaps.md

Adds a small piece of detail about heatmap backgrounds in PA.

One more note about backgrounds

---

content/en/service_management/incident_management/describe.md

- UI modal for declaring an incident was updated, current image is outdated.
- Remove the image reference

Remove outdated image

---

content/en/logs/guide/apigee.md

- The image wasn't rendering because of the relative path
- [DOCS-9191](https://datadoghq.atlassian.net/browse/DOCS-9191)
[DOCS-9191]: https://datadoghq.atlassian.net/browse/DOCS-9191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update apigee image reference

---

content/en/sensitive_data_scanner/_index.md

- Updates Preview callouts.
[DOCS-9092](https://datadoghq.atlassian.net/browse/DOCS-9092)
[DOCS-9092]: https://datadoghq.atlassian.net/browse/DOCS-9092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DOCS-9092 ]Update SDS preview callouts

---

content/en/metrics/summary.md

 added new metrics origin mapping table to docs

---

content/en/serverless/guide/serverless_warnings.md

[Ticket](https://datadoghq.atlassian.net/browse/SVLS-3645)
RecursiveInvocationsDropped is being supported by serverless, so we are adding docs for it to the correct docs page.

Add Recursive Invocations Dropped documentation

---

content/en/database_monitoring/setup_postgres/azure.md

The following PR added documentation how to install PostgreSQL 16:
https://github.com/DataDog/documentation/pull/22054/files 
But the list of supported versions were not updated [here](https://docs.datadoghq.com/database_monitoring/setup_postgres/azure?tab=singleserver#:~:text=Supported%20PostgreSQL%20versions)

Update supported PostgreSQL versions

---

content/en/security/application_security/threats/exploit-prevention.md

This PR updates the library compatibility matrix for customers to know what type of exploit prevention is available in what language.
Note: We are de-releasing SQLi because of too much false positive detection

[APPSEC-54925] Update Exploit Prevention Compatibility Matrix

---

content/en/real_user_monitoring/error_tracking/mobile/reactnative.md

It should be written as `Xcode`, not as `XCode`.

Fix Xcode spelling
