content/en/cloud_cost_management/recommendations/_index.md
This page is still marked private even though the product is public
=> Remove private property from CCM page

content/en/serverless/step_functions/installation.md
The indent in the example code is wrong. This PR fixes the indent.
=> Fix indent in Step Function example code

content/en/serverless/step_functions/installation.md
Add doc for the custom way of linking the trace of a Step Function with the trace of a nested Step Function.
=> Add doc for SFN->SFN custom trace linking

content/en/service_catalog/software_templates.md
Buttom-->Button
Spelling incorrect in docs
=> Spelling update software_templates.md

content/en/account_management/audit_trail/events.md
- Add missing Audit Trail events.
[DOCS-8748](https://datadoghq.atlassian.net/browse/DOCS-8748)
[DOCS-8748]: https://datadoghq.atlassian.net/browse/DOCS-8748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-8748] Add missing audit trail events (part 1)

content/en/security/cloud_siem/security_operational_metrics.md
Add the unit of the Security Operational Metrics
=> Add the unit of the Security Operational Metrics

content/en/network_monitoring/network_path/setup.md
This PR removes the previous number of workers of 10 as it was causing confusion, adding more information to make it more clear that 4 is the default.
=> Update Network Path setup docs

content/en/opentelemetry/collector_exporter/deployment.md, content/en/opentelemetry/troubleshooting.md
- Reorganized the Deployment page to make it easier to read.
- Added hostname metadata collection step for both DaemonSet and Gateway deployments.
- Added Gateway deployment section to Troubleshooting page.
=> Add more hostname setting info

content/en/service_management/service_level_objectives/ootb_dashboard.md
=> Update Score info for SLO dashboard

CONTRIBUTING.md
=> parallel build test 1

content/en/continuous_integration/_index.md, content/en/security/_index.md, content/en/security/cloud_security_management/_index.md
=> (TT) Blog posts

content/en/opentelemetry/interoperability/instrumentation_libraries.md
=> Hygiene related changes to drop in support page

content/en/tracing/guide/service_overrides.md
=> Small changes to service overrides guide

content/en/service_catalog/investigating.md
add more details on common use cases to link in other doc contents
rearranging content to improve sturcture
- add more details on common use cases to link in other doc contents
- rearranging content to improve information structure  (pull out infra information up top)
=> Update investigating.md [service catalog]

content/en/service_management/events/pipelines_and_processors/_index.md
- Add more information and context to Event Management Pipelines
- Add a further reading
=> Add more information and context to event pipelines docs

content/en/service_catalog/service_definitions/v3-0.md
updating an outdated example of linking codeLocation for v3 entities
updating an outdated example of linking codeLocation for v3 entities
=> Update v3-0.md to reflect the updated code location example

content/en/cloud_cost_management/saas_costs.md
This PR moves a table to the correct section
=> Move mongodb table

content/en/cloudcraft/faq/security-audits.md, content/en/cloudcraft/faq/soc2-report.md
Update the SOC2 and security audit FAQ entries to point them to the Datadog Trust Center.
=> [CLOUDCRAFT-962] Update Cloudcraft's SOC2 and security audit FAQ entries

content/en/serverless/step_functions/installation.md
=> Add sampling information for Step Function

content/en/dashboards/_index.md
This is to highlight the recently launched Discovering Table, List, SLO, and Architecture Widgets
course
=> Adding call out for new Discovering Table, List, SLO, and Architecture Widgets

content/en/synthetics/platform/private_locations/_index.md
=> Update Synthetics/Private locations page

layouts/partials/dbm/dbm-setup-postgres.html
Add a logo and link for Google Cloud Alloy DB under the Postgres heading
=> Update DBM partial to include Google Cloud AlloyDB

content/en/continuous_integration/pipelines/jenkins.md, content/en/glossary/terms/custom_span.md
Adds a troubleshooting section regarding infra correlation. You have to follow some steps and, even if you do them properly, you may not see anything in Datadog. This is because sometimes a restart on Jenkins is needed.
=> Add troubleshooting for Jenkins infra correlation

content/en/tracing/other_telemetry/connect_logs_and_traces/php.md
I found the current doc a little confusing.
##Preview
https://docs-staging.datadoghq.com/cecile/phplogscorrelation/tracing/other_telemetry/connect_logs_and_traces/php/
=> PHP trace correlation identifiers - try to make it a little clearer

content/en/continuous_integration/pipelines/custom_tags_and_measures.md
Fixing unclear information on how to add more than one tag and measure
=> [SDCI] Clarify documentation on tags and measures

content/en/sensitive_data_scanner/_index.md, layouts/shortcodes/sds-scanning-rule.md
- Moves instructions out of shortcode because it doesn't apply to both sections. 
- Adds missing first step.
=> Update scanning rules instructions

content/en/tracing/troubleshooting/tracer_debug_logs.md
Mirror https://github.com/DataDog/documentation/pull/25812 changes; just using correct branch naming convention.
=> tracer_debug_logs Version Format

content/en/continuous_delivery/deployments/argocd.md
=> Add server-side apply mention on Argo CD monitoring

content/en/agent/configuration/network.md
=> (Agent) Add installation URLs to networking

content/en/service_management/on-call/profile_settings.md
=> DOCS-9313 - Supported notification methods for On-Call

content/en/containers/guide/changing_container_registry.md, content/en/containers/kubernetes/installation.md
This PR documents the new Azure Container Registry.
We need to update the doc for all other languages.
If any other place lists all registries, the ACR needs to be documented too.
=> Document Azure Container Registry

content/en/real_user_monitoring/guide/enable-rum-woocommerce-store.md
Remove mention of funnel from RUM guide, since it's now part of Product Analytics.
=> [DOCS-9201] Remove funnel mention from RUM Woocommerce guide

content/en/data_security/real_user_monitoring.md
- Adds specific note about data retention for Sessions, Views, and Actions.
=> [DOCS-9214] Update RUM/PA data retention

content/en/observability_pipelines/sources/_index.md
- Adds missing sources to the source index page.
=> Add google pubsub, http server, logstash to OP source index

content/en/tracing/trace_collection/custom_instrumentation/android/otel.md, content/en/tracing/trace_collection/custom_instrumentation/cpp/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/dotnet/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/dotnet/otel.md, content/en/tracing/trace_collection/custom_instrumentation/go/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/go/otel.md, content/en/tracing/trace_collection/custom_instrumentation/ios/otel.md, content/en/tracing/trace_collection/custom_instrumentation/java/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/java/otel.md, content/en/tracing/trace_collection/custom_instrumentation/nodejs/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/nodejs/otel.md, content/en/tracing/trace_collection/custom_instrumentation/php/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/php/otel.md, content/en/tracing/trace_collection/custom_instrumentation/python/dd-api.md, content/en/tracing/trace_collection/custom_instrumentation/python/otel.md, content/en/tracing/trace_collection/custom_instrumentation/ruby/otel.md
Fixing balance of brevity and grammar in Custom Instrumentation titles.
=> Update Custom Instrumentation Titles

content/en/tracing/trace_collection/library_config/java.md
Hotjar feedback
[DOCS-9213](https://datadoghq.atlassian.net/browse/DOCS-9213)
DO NOT MERGE.. Waiting on Engineering approval for this setting.
[DOCS-9213]: https://datadoghq.atlassian.net/browse/DOCS-9213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9213] updating dd.trace.span.tags

content/en/tracing/guide/adaptive_sampling.md
update the url of adaptive_sampling beta form
=> Fix  adaptive_sampling form url for beta request

content/en/data_jobs/airflow.md
Add call out in the setup step to ask customer to verify the version constraint is met, otherwise, the install could fail.
=> Call out version compatibility check in data jobs monitoring for airflow - Amazon MWAA

content/en/account_management/guide/manage-datadog-with-terraform.md, content/en/account_management/rbac/permissions.md, content/ja/account_management/rbac/permissions.md
Modifies and expands the Datadog Role documentation. Out-of-the-box roles are now refered to as managed roles. And managed roles can no longer be edited by end users
cc @DataDog/aaa-core-access
=> managed roles docs

content/en/security/cloud_siem/content_packs.md
Adds new content packs.
[DOCS-9282](https://datadoghq.atlassian.net/browse/DOCS-9282)
[DOCS-9282]: https://datadoghq.atlassian.net/browse/DOCS-9282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9282] Add new content packs

content/en/security/cloud_security_management/setup/supported_deployment_types.md
CSM Vulnerabilities Windows GA
=> CSM Vulnerabilities Windows GA

content/en/quality_gates/_index.md
Docs team Tuesday tasks: add links to new blog posts to documentation to drive traffic to the blog.
=> Add flaky test blog link

layouts/shortcodes/observability_pipelines/processors/generate_metrics.en.md
- Adds note about custom metrics and billing.
[DOCS-9352](https://datadoghq.atlassian.net/browse/DOCS-9352)
```
/merge
```
[DOCS-9352]: https://datadoghq.atlassian.net/browse/DOCS-9352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9352] Add note about custom metrics for generate metrics processor

content/en/service_management/workflows/private_actions/use_private_actions.md
Documents how to edit a Private Action Runner's allowlist after creation.
=> PAR - edit allowlist

content/en/data_streams/manual_instrumentation.md
=> DOCS-9341: adding languages for manual instrumentation

static/resources/json/airflow_ust.json
Adding a JSON reference file in resources. Going to be linked to from an update to the Airflow integration in integrations-core.
```
/merge
```
=> adding a JSON resource

content/en/data_streams/manual_instrumentation.md
this isn't just Java anymore
```
/merge
```
=> small title fix

content/en/metrics/summary.md
Please merge PR after review -- Thanks!
=> Remove standard/custom identifier for custom metrics

content/en/metrics/metrics-without-limits.md
Remove outdated information about obtaining unqueried metrics reports
```
/merge
```
=> (DOCS-9325) Update unqueried metrics info

content/en/dashboards/guide/query-to-the-graph.md
Fix a typo and a grammatical error
```
/merge
```
=> Fix typo and grammatical error

content/en/agent/logs/advanced_log_collection.md, content/en/containers/docker/integrations.md, content/en/containers/guide/ad_identifiers.md, content/en/containers/guide/autodiscovery-with-jmx.md, content/en/containers/kubernetes/integrations.md, content/en/containers/kubernetes/log.md, content/en/containers/kubernetes/prometheus.md, content/en/containers/kubernetes/tag.md
Replaces <CONTAINER_IDENTIFIER> with <CONTAINER_NAME> or <CONTAINER_IMAGE> where appropriate!
```
/merge
```
=> DOCS-9358 - making <CONTAINER_IDENTIFIER> edits to docs repo

content/en/containers/amazon_ecs/_index.md
Adds note on requirements. Requested by Fred Shad.
```
/merge
```
=> DOCS-9119 - Add note on required network settings and permissions

content/en/database_monitoring/_index.md, content/en/database_monitoring/setup_mongodb/_index.md, content/en/database_monitoring/setup_mongodb/mongodbatlas.md, content/en/database_monitoring/setup_mongodb/selfhosted.md
Remove DBM for MongoDB beta banner and prepare for GA.
```
/merge
```
=> Remove DBM for MongoDB beta banner

assets/styles/pages/_global.scss, content/en/sensitive_data_scanner/library_rules.md
fix ordered list (`<ol>`) styles.
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-5459
preview: https://docs-staging.datadoghq.com/neko/WEB-5449-example/sensitive_data_scanner/library_rules/
=> fix ordered list styles - [WEB-5459]

content/en/developers/dogstatsd/_index.md
- I noticed a table was rendering incorrectly while perusing the docs.
- This should fix it by removing an improper newline.
```
/merge
```
=> dogstatsd table rendering incorrectly

content/en/developers/integrations/oauth_for_integrations.md
Add note about regenerating client secret
Please merge this once approved.
```
/merge
```
=> OAuth Integrations - Troubleshooting

content/en/tracing/configure_data_security/_index.md
Adds note that a feature isn't supported on gov, but is enabled by default so it needs to be disabled to avoid errors.
```
/merge
```
=> DOCS-8966 - GovCloud note for instrumentation telemetry

content/en/security/cloud_security_management/setup/cloudtrail_logs.md
c.f. https://dd.slack.com/archives/C062AMWS1SS/p1730266075407119
As per https://dd.slack.com/archives/C04D8QU7C93/p1730292242783949 I'd like to also have someone from the CSM team review this
=> CSM Identity risks: remove incorrect pre-requisite

content/en/account_management/billing/containers.md
=> DOCS-9343 - Update containers billing

content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
apps are no longer RUM specific. removing this from the docs + adding ET
```
/merge
```
=> Update SCI docs

content/en/error_tracking/frontend/browser.md
=> Update link to create ET app

content/en/error_tracking/frontend/browser.md
Remove mistaken mention of RUM
```
/merge
```
=> Remove mention of RUM

content/en/service_management/workflows/private_actions/private_action_credentials.md
This is the same change seen [here](https://github.com/DataDog/documentation/pull/26019), but with branch naming that will build and merge correctly.
```
/merge
```
=> Fix PAR configuration docs

content/en/tracing/trace_pipeline/ingestion_controls.md
=> Fix remote config link

content/en/tracing/trace_collection/proxy_setup/_index.md
Small update to remove some outdated content.
```
/merge
```
=> DOCS-9198 Removing outdated Istio content

.gitlab-ci.yml, package.json, yarn.lock
updates typesense sync package
see: https://github.com/DataDog/corp-node-packages/pull/86
```
/merge
```
=> Updates typesense sync package

config/_default/menus/main.en.yaml, content/en/database_monitoring/setup_mongodb/troubleshooting.md, content/en/database_monitoring/troubleshooting.md, layouts/shortcodes/dbm-mongodb-agent-config-replica-set.en.md, layouts/shortcodes/dbm-mongodb-agent-config-sharded-cluster.en.md, layouts/shortcodes/dbm-mongodb-agent-config-standalone.en.md
This PR adds DBM for MongoDB troubleshooting page. The troubleshooting page currently contains the 2 commonly seen issue from beta:
1. cluster name with uppercase characters or spaces
2. MongoDB Atlas connection issue due to TLS not enabled
```
/merge
```
=> [dbm] add dbm for mongodb troubleshooting

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-python layer to version 100

content/en/account_management/saml/okta.md
Recreation of [this PR](https://github.com/DataDog/documentation/pull/26051/files) with branch name that will preview.
```
/merge
```
=> Update okta.md to add missing EDIT step when configuring Okta SAML Team/Role Mapping

content/en/security/cloud_security_management/agentless_scanning/_index.md, content/en/sensitive_data_scanner/_index.md
- Renames Data Security to Cloud Storage.
- Updates Cloud Storage section in SDS and Agentless Scanning docs.
[DOCS-9373](https://datadoghq.atlassian.net/browse/DOCS-9373)
```
/merge
```
[DOCS-9373]: https://datadoghq.atlassian.net/browse/DOCS-9373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9373] Update Cloud Storage scanning sections

content/en/logs/explorer/calculated_fields/_index.md, content/en/security/_index.md, content/en/service_management/case_management/_index.md, content/en/service_management/events/_index.md, content/en/service_management/incident_management/_index.md
=> Add further reading links for new blog posts

config/_default/params.en.yaml
Updates the translation disclaimer to use "Should" instead of "May" - it sounds better and is more grammatically correct.
```
/merge
```
=> Update translation disclaimer

content/en/database_monitoring/setup_mongodb/mongodbatlas.md
This PR adds DBM for MongoDB Atlas supported cluster tiers.
```
/merge
```
=> [dbm] add supported mongodb atlas cluster tiers

content/en/security/application_security/software_composition_analysis/_index.md
Clearly highlight the definition of Datadog Severity Score in a separate section for visibility.
Merge after review.
=> update definition of CVSS score

content/en/monitors/configuration/_index.md
-[DOCS-9311](https://datadoghq.atlassian.net/browse/DOCS-9311)
```
/merge
```
[DOCS-9311]: https://datadoghq.atlassian.net/browse/DOCS-9311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add max time for rolling time windows

content/en/logs/log_collection/_index.md
- Noticed code block included the reference links
- Add missing backticks to close off the text block
```
/merge
```
=> Add missing backticks

content/en/serverless/step_functions/merge-step-functions-lambda.md
=> Update SFN -> Lambda merging instructions

typesense.config.json
Updates preset to include stopwords in query search parameters
```
/merge
```
Check search results:
https://docs-staging.datadoghq.com/nsollecito/ts-stopwords/
=> Adds stopwords to search query config

content/en/security/cloud_security_management/_index.md
Adds "CSM" and "Cloud Security Management" as search terms for the Cloud Security Management docs home page.
```
/merge
```
=> Updating search terms

content/en/logs/explorer/calculated_fields/expression_language.md
- PM requested fixes to some quirks in the documentation.
- Made all formula examples monospace for uniform formatting.
```
/merge
```
=> Fix code quirks

content/en/agent/guide/why-should-i-install-the-agent-on-my-cloud-instances.md
This PR adds a shortcode to make the number of integrations render dynamically
```
/merge
```
=> Add integration count shortcode

content/en/account_management/teams/_index.md
Clicking on an individual team now opens the teams detail page, not a side panel. Updating the docs to match the UI.
```
/merge
```
=> Update team detail UI description

content/en/tracing/trace_collection/compatibility/python.md
Clarifies what the Python compatibility tables were referring to as it could be misread easily to think that it is referring to the Python runtime versions and whatnot.
```
/merge
```
=> Clarify what the Python tables are referring to

content/en/security/cloud_siem/log_detection_rules.md
- Moves the rules case example to the correct section.
[DOCS-9039](https://datadoghq.atlassian.net/browse/DOCS-9039)
```
/merge
```
[DOCS-9039]: https://datadoghq.atlassian.net/browse/DOCS-9039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9039] Move rule case example

content/en/security/cloud_security_management/guide/eBPF-free-agent.md, content/en/security/threats/workload_security_rules/_index.md
Small typo in the product name, it should be CSM threats and not CMS
```
/merge
```
=> fix CMS -> CSM typo in CSM threats ebpf free pages

content/en/tracing/services/inferred_services.md
=> Fix service representation broken links

content/en/network_monitoring/devices/snmp_metrics.md
Can be merged ASAP
```
/merge
```
=> Update min version for new autodiscovery syntax

content/en/observability_pipelines/advanced_configurations.md
- Adds info on OPW and proxies
[DOCS-9199](https://datadoghq.atlassian.net/browse/DOCS-9199)
```
/merge
```
[DOCS-9199]: https://datadoghq.atlassian.net/browse/DOCS-9199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9199] Add proxy info

content/en/infrastructure/process/_index.md
Live Processes is releasing a flag to reduce the footprint of the agent. Update the Live Processes documentation to include instructions for Helm and Operator.
```
/merge
```
=> Add new process collection in core agent flag

config/_default/menus/main.en.yaml
=> (maint) Fix broken link

content/en/dynamic_instrumentation/symdb/_index.md, content/en/dynamic_instrumentation/symdb/java.md
Autocomplete and search are automatically enabled for a service from version 1.42.0. 
```
/merge
```
=> Change autocomplete and search to GA for java

content/en/error_tracking/backend/exception_replay.md
=> Update exception replay sensitive data setup

content/en/service_management/service_level_objectives/_index.md, content/en/service_management/service_level_objectives/monitor.md
=> update no data for monitor slos

content/en/opentelemetry/_index.md
restores order of footnote hyperlinks on OpenTelemetry `_index.md`
```
/merge
```
Fixes #26168
=> revert bug from #26506

content/en/serverless/aws_lambda/opentelemetry.md
Removes beta flag, adds note about not supporting custom metrics
```
/merge
```
=> Update extension OTLP endpoint

content/en/tests/correlate_logs_and_tests/_index.md
Adds the documentation for enabling agentless log submission in .NET
```
/merge
```
=> [CI Visibility] .NET logs submission

content/en/llm_observability/terms/_index.md
these two screenshots are not great examples
```
/merge
```
=> DOCS-9430 - screenshot removal

content/en/continuous_integration/pipelines/jenkins.md
Improves Datadog Jenkins plugin troubleshooting instructions.
Some steps are added to troubleshoot missing pipelines data or logs data.
```
/merge
```
=> Improve Jenkins plugin troubleshooting instructions

content/en/tracing/configure_data_security/_index.md
This clarifies the wording to let customers know that this is for Datadog usage. Pending confirmation from APM agent team
```
/merge
```
=> Clarify that APM telemetry is for Datadog usage

content/en/dashboards/sharing/shared_dashboards.md
- Update the docs to reflect new dashboards features.
```
/merge
```
=> Add new info on embeddable dashboards

config/_default/menus/main.en.yaml
=> Change menu item name to be more consistent with other items.

content/en/infrastructure/resource_catalog/_index.md
=> Add note about secret security

content/en/service_management/workflows/_index.md
Add learning center course to further reading list for Workflow Automation
```
/merge
```
=> Add learning center course to further reading list for Workflow Automation

content/en/infrastructure/containers/configuration.md
Add documentation for explaining how to configure the orchestrator explorer to collect custom resources.
```
/merge
```
=> Add docs for collecting CRs

content/en/tracing/trace_collection/tracing_naming_convention/_index.md
=> Update to the definition of span tag and attributes

content/en/service_catalog/_index.md, content/en/tracing/services/inferred_services.md, content/en/tracing/services/resource_page.md, content/en/tracing/services/service_page.md, content/en/tracing/trace_explorer/query_syntax.md, content/en/tracing/trace_explorer/trace_view.md
=> Opening service representation beta docs to EU1

content/en/opentelemetry/collector_exporter/log_collection.md
=> Remove recursive alias

content/en/administrators_guide/_index.md, content/en/administrators_guide/build.md, content/en/administrators_guide/plan.md, content/en/administrators_guide/run.md
Just a few small adjustments to this guide
```
/merge
```
=> Administrator's Guide updates

layouts/shortcodes/notifications-email.en.md
Adding a note to specify that for monitoring notifications, we don't support email addresses that contain slashes.
```
/merge
```
=> Add note about email addresses containing slashes for monitoring notifications

content/en/logs/log_configuration/archives.md
- Add a us-fed1 note about sending logs outside of Datadog environment.
- [DOCS-9437](https://datadoghq.atlassian.net/browse/DOCS-9437)
```
/merge
```
[DOCS-9437]: https://datadoghq.atlassian.net/browse/DOCS-9437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note about GovCloud custom destinations

content/en/containers/troubleshooting/_index.md
=> (Containers)(DOCS-9169) ECS Fargate timeouts

go.mod, go.sum
Updates websites sources versions.
```
/merge
```
=> (maint) Update go files

content/en/service_catalog/_index.md, content/en/tracing/services/inferred_services.md, content/en/tracing/services/resource_page.md, content/en/tracing/services/service_page.md, content/en/tracing/trace_explorer/query_syntax.md, content/en/tracing/trace_explorer/trace_view.md
=> open service representation GA docs to US1

content/en/agent/basic_agent_usage/osx.md
=> (Agent) System-wide LaunchDaemon uninstallation macOS

content/en/data_streams/java.md
=> Update Java list of supported libraries

content/en/agent/logs/proxy.md
=> (Logs) Fix further reading

content/en/security/application_security/threats/add-user-info.md
`Remote Configuraton` feels like a columbian reggaeton band
~Remote Configuraton~ +Remote Configuration
```
/merge
```
=> Fix typo in add-user-info.md

layouts/shortcodes/latest-lambda-layer-version.html
Latest `datadog-lambda-python` release.
```
/merge
```
=> Bump datadog-lambda-python layer to version 102

content/en/tracing/trace_collection/library_config/nodejs.md
- documents new env vars and links to guide
YOLO
N/A
=> Explain the Node.js AWS SDK payload tagging env vars

content/en/database_monitoring/recommendations/index.md
=> [DBMON-4054] Long running query docs

content/en/dashboards/widgets/wildcard.md
- Add a Vega-lite tutorial for exploring data
```
/merge
```
=> Add a further reading reference

content/en/account_management/org_settings/domain_allowlist.md, content/en/account_management/org_settings/domain_allowlist_api.md
https://datadoghq.atlassian.net/browse/DOCS-9499
Domain Allowlist is going GA. Update the page frontmatter so it gets indexed. Update the callouts to reflect the correct status.
```
/merge
```
=> Domain Allowlist GA

content/en/serverless/aws_lambda/distributed_tracing.md
PR adds documentation for Span Auto-linking, a new feautre that the Serverless team is going to launch at re:invent.
```
/merge
```
=> Add initial docs for Serverless Span Autolinking 

content/en/opentelemetry/collector_exporter/otel_collector_datadog_exporter.md
=> Update container overview dashboard beta to new

content/en/account_management/safety_center.md
=> remove beta flag for safety center

content/en/account_management/audit_trail/_index.md
=> Update API key auditing beta -> Preview

content/en/security/cloud_security_management/setup/supported_deployment_types.md
Fargate support is now GA. Updated Cloud Security Supported Deployment Types.
=> list Fargate support as GA

content/en/tracing/trace_collection/_index.md, content/en/tracing/trace_collection/automatic_instrumentation/_index.md, content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm.md
=> Lifecycle Update: Single Step Instrumentation

content/en/api_catalog/_index.md, content/en/api_catalog/add_entries.md, content/en/api_catalog/add_metadata.md, content/en/api_catalog/api_catalog_api.md, content/en/api_catalog/endpoint_discovery.md, content/en/api_catalog/explore_apis.md, content/en/api_catalog/monitor_apis.md, content/en/api_catalog/owners_and_tags.md, content/en/api_catalog/troubleshoot.md
=> Lifecycle Update: API Catalog

content/en/network_monitoring/devices/guide/device_profiles.md
Update form URL on device profiles page
```
/merge
```
=> Update form URL on device profiles page

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-extension layer to version 66

content/en/database_monitoring/guide/managed_authentication.md
Just fixing a minor typo.
```
/merge
```
=> fixed minor typo

content/en/profiler/enabling/dotnet.md, content/en/serverless/azure_app_services/azure_app_services_windows.md, content/en/tracing/metrics/runtime_metrics/dotnet.md, content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md, content/en/tracing/trace_collection/compatibility/dotnet-core.md
Update documentation about recently released support for .NET 9
```
/merge
```
=> [.NET] Add support for .NET 9

content/en/error_tracking/backend/_index.md
Updates the preview link for Error Tracking as part of the product lifecycle updates
```
/merge
```
=> Update preview link for Error Tracking

content/en/tracing/guide/ddsketch_trace_metrics.md
Update tags to match the tags we mark as available here: https://docs.datadoghq.com/tracing/metrics/metrics_namespace/#latency-distribution
I confirmed in the metric explorer that they are available: 
Fixed PR from before: https://github.com/DataDog/documentation/pull/26092
```
/merge
```
=> Update available metric tags

content/en/serverless/step_functions/installation.md, content/en/serverless/step_functions/merge-step-functions-lambda.md
Doc refinement based on the most recent updates in the DD Forwarder.
```
/merge
```
=> Step Functions doc refinement based on the most recent update

content/en/developers/community/libraries.md, data/libraries.yaml
Update the libraries data to remove deprecated/archived repos
=> Brandon.west/libraries audit

config/_default/menus/main.en.yaml, content/en/security/cloud_security_management/misconfigurations/kspm.md
Moves the KSPM article up one level in the nav hierarchy. Requested by PM.
```
/merge
```
=> Move KSPM article up one level

content/en/account_management/billing/aws.md
Updates the list of services available for tag filtering to reflect a recent feature release.
=> Add Step Functions to list of services for tag filtering

content/en/tracing/trace_collection/library_config/dotnet-core.md, content/en/tracing/trace_collection/library_config/dotnet-framework.md
=> Remove merge notation

content/en/service_catalog/apis.md
adding API references for v3.0 which is releasing this week
adding API references for v3.0 which is releasing this week
```
/merge
```
=> Update service catalog apis.md

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-python layer to version 103

content/en/integrations/guide/source-code-integration.md
Adds additional clarification about handling minification for TypeScript when trying to use Datadog's Source Code Integration
```
/merge
```
=> Add TypeScript minification wording to SCI docs

layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md
The config is written incorrectly here. `database_autodiscovery` takes a boolean instead of an object.
```
/merge
```
=> Update SQLServer Autodiscovery boolean

content/en/logs/log_configuration/archives.md
=> Add note for intelligent tiering storage class

content/en/cloud_cost_management/recommendations/_index.md
The goal of this PR is to add released workload aware ccm recommendations to recommendations docs 
[Here is our google doc we made a draft of the documented recs for](https://docs.google.com/document/d/1mMUvVwj-qHdnZEFUiy1tAAobvNpGuteVMvaRCseN6iY/edit?tab=t.0)
Local validation
```
/merge
```
=> Add ccm workload aware recommendations to documentation

content/en/tests/flaky_test_management/auto_test_retries.md, content/en/tests/flaky_test_management/early_flake_detection.md
This PR fixes some Test optimization pages for the Go library.
Here:
And here:
```
/merge
```
=> [Test Visibility] - Fix Go pages

content/en/tracing/services/inferred_services.md
=> Add docs to explain the blocked-ip-address case

content/en/tracing/guide/inferred-service-opt-in.md
Fixes anchor link on tracing guide.
```
/merge
```
=> Fixes anchor link on tracing guide

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-js layer to version 116

content/en/data_jobs/databricks.md
The word "Manually" is misspelled as "Manaully"
=> Update typo in databricks.md

config/_default/menus/main.en.yaml
just addin' guide
```
/merge
```
=> add DSM guides to nav

content/en/tracing/services/inferred_services.md
Removes the term "Datadog Agent," as some of the configurations are not Datadog Agent configurations. h/t Ethan Grab
```
/merge
```
=> Make line more general

content/en/serverless/step_functions/merge-step-functions-lambda.md
Adds a manual setup guide for the new multi-level tracing merging feature. This can be referenced from the blog post as a way for customers to use this feature on day 1 before we have options with CDK or CI tools,
```
/merge
```
=> Multi-Level Step Functions Trace Merging Instructions

assets/scripts/components/integrations.js
Updates the existing search functionality on the Integrations page so that multiple terms can be searched, resulting in a more complete search experience.
https://datadoghq.atlassian.net/browse/WEB-5206
https://docs-staging.datadoghq.com/nsollecito/integration-keywords/integrations/?q=apache%20flink#all
vs
https://docs.datadoghq.com/integrations/?q=apache%20flink#all
```
/merge
```
=> [WEB-5206] Update integrations keyword search functionality 

content/en/service_management/case_management/create_notifications_and_third_party_tickets.md
Updates the docs to reflect limitations for Change Management.
Nothing specific, CHM is being turned on 11/24.
```
/merge
```
=> [CaseM] update jira/snow syncing docs

content/en/serverless/step_functions/merge-step-functions-lambda.md
AWS has published a doc on JSONata that's a better resource than the blog we originally linked
```
/merge
```
=> Update JSONata link to AWS doc

content/en/database_monitoring/setup_mongodb/selfhosted.md
This PR adds `Supported MongoDB editions` to MongoDB self-hosted setup doc to clarify both `Community` and `Enterprise` editions are supported.
```
/merge
```
=> [dbm] add supported mongodb edition to self-hosted

content/en/security/cloud_security_management/severity_scoring.md
- Fix the link checker
- Update the link to the detection rule reference
```
/merge
```
=> Update the detection rules link

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-python layer to version 104

content/en/product_analytics/journeys/_index.md
=> Clarify session requirement for conversion calculations

content/en/logs/log_collection/javascript.md
Document usePciIntake init parameter in [Browser Log Collection](https://docs.datadoghq.com/logs/log_collection/javascript/)
```
/merge
```
=> Document usePciIntake

content/en/containers/amazon_ecs/_index.md
=> Update FIPS proxy version to 1.1.6

content/en/dashboards/functions/rollup.md
There should be a hyphen in "calendar-aligned." We are introducing a tooltip for widgets with these rollups, and we want the text to match what's in the docs.
```
/merge
```
=> Update rollup.md to have hyphen in "calendar-aligned"

content/en/integrations/guide/azure-portal.md, content/en/logs/guide/azure-native-logging-guide.md
Update Azure Active Directory to Microsoft Entra ID
```
/merge
```
=> (DOCS-8718) Update Azure Active Directory

content/en/service_management/workflows/trigger.md
Adds documentation for new trigger method for workflows.
```
/merge
```
=> (DOCS-9610) GitHub triggers for workflows

content/en/data_streams/dotnet.md, content/en/data_streams/go.md, content/en/data_streams/java.md, content/en/data_streams/nodejs.md, content/en/data_streams/python.md
I put the last feature we worked on in "recommended tracer version". For example, for NodeJS Kafka, the last feature was adding Cluster ID tagging in 5.25
```
/merge
```
=> Data streams: Update supported languages in all languages

content/en/mobile/_index.md
https://datadoghq.atlassian.net/browse/DOCS-9570
Adds documentation for the new Mobile Traces feature. For re:Invent. Drafted by the product manager, edited by me.
```
/merge
```
=> Add mobile traces

content/en/serverless/aws_lambda/installation/dotnet.md, content/en/serverless/aws_lambda/installation/go.md, content/en/serverless/aws_lambda/installation/java.md, content/en/serverless/aws_lambda/installation/nodejs.md, content/en/serverless/aws_lambda/installation/python.md, content/en/serverless/aws_lambda/installation/ruby.md
Docs changes for optimized extension GA
ready to merge whenever
```
/merge
```
=> [reinvent] optimized extension

content/en/dynamic_instrumentation/enabling/php.md, layouts/partials/dynamic_instrumentation/dynamic-instrumentation-languages.html
=> Make PHP private

content/en/monitors/notify/variables.md
Fix template variable example for Error Tracking monitors
=> Fix template variable example for Error Tracking monitors

content/en/serverless/aws_lambda/installation/dotnet.md, content/en/serverless/aws_lambda/installation/java.md, content/en/serverless/aws_lambda/installation/nodejs.md, content/en/serverless/aws_lambda/installation/python.md, content/es/serverless/aws_lambda/installation/dotnet.md, content/es/serverless/aws_lambda/installation/java.md, content/es/serverless/aws_lambda/installation/nodejs.md, content/es/serverless/aws_lambda/installation/python.md, content/fr/serverless/aws_lambda/installation/java.md, content/ja/serverless/aws_lambda/installation/nodejs.md, content/ja/serverless/aws_lambda/installation/python.md
=> chore: update lambda terraform docs

content/en/cloudcraft/getting-started/connect-amazon-eks-cluster-with-cloudcraft.md
Updates the "Connect an Amazon EKS Cluster with Cloudcraft" Cloudcraft article to include information about private clusters.
=> [CLOUDCRAFT-1030] Update "Connect an Amazon EKS Cluster with Cloudcraft"

content/en/service_management/workflows/limits.md
Update the time limit for a workflow from 24 hours to 7 days.
```
/merge
```
=> (DOCS-9651) Update workflow time limit

content/en/opentelemetry/guide/otel_demo_to_datadog.md
This PR adds a new instruction on how to enable Feature Flags in the OpenTelemetry Demo.
```
/merge
```
=> Add Feature Flag UI

config/_default/params.yaml
Fixes a build warning.
Check here: https://docs-staging.datadoghq.com/heston/core_product_update/glossary/?product=cloud-network-monitoring
```
/merge
```
=> (maint) Update core_product name

content/en/data_streams/java.md, content/en/data_streams/manual_instrumentation.md, content/en/data_streams/nodejs.md, content/en/data_streams/python.md
- removes info/alert box on manual instrumentation page
- updates java snippet on manual instrumentation page
- adds link to manual instrumentation page on java, nodejs, and python setup pages
```
/merge
```
=> Various updates to manual instrumentation for DSM

content/en/dashboards/functions/rollup.md, content/en/monitors/guide/troubleshooting-monitor-alerts.md
- Documentation request from Support
- Add a note to help customers troubleshooting "No Data" status
- [DOCS-9408](https://datadoghq.atlassian.net/browse/DOCS-9408)
```
/merge
```
[DOCS-9408]: https://datadoghq.atlassian.net/browse/DOCS-9408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note about rollup and require full window interaction

content/en/tracing/trace_collection/proxy_setup/_index.md
=> Fix typo in proxy trace collection docs

content/en/dashboards/widgets/wildcard.md
- Add an introduction to clarify that you can setup a widget one of two ways, prevent confusion on whether both are needed to configure a wildcard widget.
```
/merge
```
=> Add an intro to subsections

content/en/agent/guide/version_differences.md
Change the wording for Agent6 & 7 difference: newest features are not delivered in Agent 6 so the python version is not the only difference anymore.
```
/merge
```
=> feat(agent): Change the wording for Agent6 & 7 difference

content/en/monitors/notify/variables.md
Clarify template variables for Error Tracking monitors
```
/merge
```
=> Clarify template variables for Error Tracking monitors

content/en/universal_service_monitoring/setup.md
Covers #23462. (Istio wording has already been fixed)
```
/merge
```
=> (USM) Remove beta wording

content/en/getting_started/opentelemetry/_index.md
* The Calendar sample application was updated, making our getting started guide outdated.
* Update the Java example to reference the new getDate() function.
```
/merge
```
=> [DOCS-8479] Fix Java Example in OTel Getting Started

content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
Small update of the docs regarding feature flags support for Unity and Kotlin Multiplatform SDKs.
Also updated some links to save 1 redirect.
```
/merge
```
=> Add note about feature flags support for Unity and Kotlin Multiplatform SDKs

content/en/account_management/billing/usage_metrics.md
=> (Account Management) Note on fargate tasks

content/en/account_management/billing/usage_metrics.md
Adds some CSS to force code values to wrap so that the table won't horizontally scroll as easily on narrower screens.
```
/merge
```
=> Adds custom style to specific page to make tables readable on narrower screens

content/en/developers/dogstatsd/unix_socket.md
Recreates #26418 with some minor edits. The original PR didn't use our preferred branch naming convention.
```
/merge
```
=> (Developers) DogStatsD instructions for EKS/ECS

content/en/monitors/types/watchdog.md
- Add a note about how log anomalies are found
- [DOCS-9634](https://datadoghq.atlassian.net/browse/DOCS-9634)
```
/merge
```
[DOCS-9634]: https://datadoghq.atlassian.net/browse/DOCS-9634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note about log anomalies in Watchdog monitors

content/en/service_management/events/correlation/intelligent.md
Update Intelligent Correlation section header from "Preview" to "Enable"
```
/merge
```
=> Update intelligent.md header title

assets/scripts/config/regions.config.js
=> adding a region param key

content/en/containers/kubernetes/installation.md
Adds an info box about limitations to the cluster name
```
/merge
```
=> DOCS-9623: cluster name note

content/en/llm_observability/setup/sdk/python.md
Should be LLMObs not LLMOBs.
```
/merge
```
=> [LLMObs] fix python typo

content/en/security/cloud_security_management/agentless_scanning/_index.md, content/en/security/cloud_security_management/setup/_index.md
We only scan running AMI through agentless. This PR makes it more explicit by adding 'running' for Agentless AMI scanning in the text. 
```
/merge
```
=> [AGENTLESS] Specify 'running' for Agentless AMI scanning

content/en/account_management/billing/vsphere.md
Updates vSphere billing docs to reflect ESXi billing 
```
/merge
```
=> Update vSphere billing page

content/en/developers/integrations/log_pipeline.md
=> Small updates and typo fixes to doc

content/en/logs/log_collection/kotlin-multiplatform.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/setup/kotlin-multiplatform.md
This PR updates iOS SDK version for Kotlin Multiplatform SDK 0.4.0 release.
```
/merge
```
=> Update iOS SDK version for Kotlin Multiplatform SDK 0.4.0 release

content/en/real_user_monitoring/browser/setup/client.md
Fixes broken link by adding link to within the tab.
```
/merge
```
=> Fix broken link in Browser setup

content/en/tracing/troubleshooting/tracer_startup_logs.md
- Ruby content was accidentally put in the C++ tab https://github.com/DataDog/documentation/pull/19401/.
- This branch moves the Ruby content to the Ruby tab and reverts the removed C++ content.
```
/merge
```
=> Tracer Startup Log Correction

content/en/service_management/events/correlation/configuration.md
adds a note about event correlation not being supported in govcloud (other requested page already has this note)
```
/merge
```
=> DOCS-9367: event correlation support in govcloud

content/en/containers/kubernetes/distributions.md
adds note about datadog site to operator resource for AKS
```
/merge
```
=> DOCS-9675: adding datadog site note

content/en/infrastructure/resource_catalog/_index.md
Add information for setting up Azure resource change collection
```
/merge
```
=> (DOCS-9683) Add Azure resource collection

content/en/service_management/workflows/build.md
Adds a section linking to the API
```
/merge
```
=> Add link to Workflows API

content/en/real_user_monitoring/browser/setup/client.md
=> update code snippet for TS, ET standalone

content/en/real_user_monitoring/browser/setup/client.md
Adds a note that provides more clarity around initializing the Browser SDK for RUM with TypeScript
```
/merge
```
=> [DOCS-9689] Add note to Typescript code snippet for RUM

content/en/logs/log_collection/java.md
- Clarify that configurations are examples, it's up to the reader to customize to their setups.
- Minor formatting fixes throughout.
- [DOCS-8986](https://datadoghq.atlassian.net/browse/DOCS-8986)
```
/merge
```
[DOCS-8986]: https://datadoghq.atlassian.net/browse/DOCS-8986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clarify where configurations are examples

content/en/database_monitoring/connect_dbm_and_apm.md
Tracing prepared statements in Java/Postgres.
```
/merge
```
=> Tracing prepared statements in Java/Postgres

content/en/network_monitoring/cloud_network_monitoring/setup.md
Adding Agent 7.59 requirement
```
/merge
```
=> Update setup for TCP failed connections

content/en/service_management/service_level_objectives/monitor.md
=> remove replay docs since feature is deprecated

content/en/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/_index.md
This content was added using an H4, but it should actually be within a tab.
```
/merge
```
=> Move Kotlin content into tab

content/en/real_user_monitoring/guide/enable-rum-shopify-store.md
Adds a note about the lack of support for Shopify Extensibility
```
/merge
```
=> Add note no support for Shopify Checkout Extensibility

content/en/metrics/custom_metrics/powershell_metrics_submission.md
- Update the metric submission endpoint
- Add a further reading to the API docs
```
/merge
```
=> Update metrics submission endpoint

content/en/real_user_monitoring/session_replay/browser/_index.md
=> [RUM-7047] Update the doc about the force session replay recording

content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
Add documentation for iOS SwiftUI support in Mobile Session Replay.
```
/merge
```
=> RUM-7382 [Mobile Session Replay] Add SwiftUI Feature Flag

content/en/integrations/guide/storage-monitoring-setup.md
- [YES ] Ready for merge
```
/merge
```
=> Add post setup form for collecting bucket info

config/_default/menus/main.en.yaml, content/en/agent/guide/_index.md, content/en/agent/guide/dogstream.md, content/en/agent/guide/upgrade.md
Moves the upgrade doc to Agent guides. PM request.
```
/merge
```
=> (Agent) Move upgrade doc to guides

content/en/api_catalog/_index.md
=> add deprecation message to API Catalog

content/en/agent/basic_agent_usage/centos.md
Small capitalization fix (CentOs -> CentOS)
```
/merge
```
=> Capitalize OS in CentOS

content/en/integrations/guide/source-code-integration.md
This PR adds instructions on how to configure Source Code Integration for PHP.
- Note: Serverless is currently not supported for PHP.
```
/merge
```
=> Add instructions for PHP on Datadog Source Code Integration setup page

content/en/monitors/guide/_index.md
- fix guide links
```
/merge
```
=> Fix guide links

content/en/logs/log_configuration/pipelines.md
- Add note that integration pipelines cannot be deleted, only disabled.
- https://datadoghq.atlassian.net/browse/DOCS-9710
```
/merge
```
=> Add note about integration pipeline deletion

content/en/real_user_monitoring/browser/advanced_configuration.md
Adds more strongly worded recommendation on setting user attributes for RUM.
```
/merge
```
=> [DOCS-9624] Update section on adding user info

content/en/security/cloud_security_management/agentless_scanning/_index.md
Adding a note to explain that AWS accounts containing AMIs must use Datadog's AWS integration for the AMIs to appear in Datadog.
```
/merge
```
=> Add note on AMI/AWS permissions

content/en/service_management/workflows/datastore.md
This PR updates the feature request form link of the datastore product
```
/merge
```
=> update datastore request form link

content/en/tracing/troubleshooting/quantization.md
Update the replace tags example to use a space character, most resource names look more like `GET /blah`, those underscores may have confused a customer who was working on trying to get this working.
```
/merge
```
=> Small update to APM replace tags example

content/en/tracing/trace_collection/automatic_instrumentation/_index.md
=> Remove Preview from SSI tab

content/en/continuous_integration/guides/_index.md
* Duplicate of https://github.com/DataDog/documentation/pull/26844 with correct branch name.
```
/merge
```
=> (Update Branch Name) Fix critical path guide title in the index

content/en/continuous_integration/pipelines/jenkins.md
Fix naming of variable that was wrong. 
```
/merge
```
=> Fix env variable

content/en/data_streams/nodejs.md
A client asked about whether we support node with `kafkajs` which they use since the docs say `kafka-node` and I looked into it and we actually support kafkajs and the docs were wrong. This corrects that
```
/merge
```
=> Correct DSM documentation to have the correct node library for instrumenting Kafka

content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
=> Replace link that no longer exists.

content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
Builds upon https://github.com/DataDog/documentation/pull/26861:
- Updates links to the ones used after big mobile reorg
- Alphabetizes the mobile platforms
```
/merge
```
=> Update links and reorder on Feature Flag guide

layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md
([DOCS-9783](https://datadoghq.atlassian.net/browse/DOCS-9783))
```
/merge
```
[DOCS-9783]: https://datadoghq.atlassian.net/browse/DOCS-9783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update index usage metrics config

layouts/shortcodes/latest-lambda-layer-version.html
Just released Node Lambda layer v118: https://github.com/DataDog/datadog-lambda-js/releases
```
/merge
```
=> Bump datadog-lambda-js layer to version 118

content/en/database_monitoring/connect_dbm_and_apm.md
Adding APM/DBM full mode support for Oracle/Java.
```
/merge
```
=> Adding APM/DBM full mode support for Oracle/Java

content/en/integrations/guide/_index.md, content/en/integrations/guide/reference-tables.md
Requested copy by PM
- [DOCS-9757](https://datadoghq.atlassian.net/browse/DOCS-9757)
```
/merge
```
[DOCS-9757]: https://datadoghq.atlassian.net/browse/DOCS-9757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update reference tables guide

content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/advanced_configuration.md
Fixes the SDK Verbosity entry in the table and updates the description with more info, which was verified by Eng.
```
/merge
```
=> Update SDK Verbosity description

layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md
Reverts [26874](https://github.com/DataDog/documentation/pull/26874). New config values haven't been released yet.
```
/merge
```
=> Revert commit

content/en/account_management/billing/usage_metrics.md
- Add a reference to OOTB estimated usage dashboards
- [DOCS-9782](https://datadoghq.atlassian.net/browse/DOCS-9782)
```
/merge
```
[DOCS-9782]: https://datadoghq.atlassian.net/browse/DOCS-9782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reference estimated usage dashboards

content/en/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/_index.md
Adds a note so users know what to do if they see unrecognized version numbers in their web view tracking reporting.
```
/merge
```
=> [DOCS-9454] Add note for web view tracking with version handling info

content/en/synthetics/guide/reusing-browser-test-journeys.md
Clarifies some confusing wording pointed out by a translator.
```
/merge
```
=> Clarify wording describing login subtest

content/en/containers/docker/log.md
The `DD_SITE` line needs the backslash.
`-e DD_SITE=<DD_SITE> \`
```
/merge
```
=> Correct syntax in the doc en/containers/docker/log.md

content/en/tracing/trace_collection/compatibility/nodejs.md
Correcting the Node documentation for instrumenting Complex Frameworks. Motivated by a customer escalation.
=> Update Complex Framework commands

.github/CODEOWNERS
Changes serverless docs codeowners from `Serverless Product` to `Serverless`
```
/merge
```
=> Update CODEOWNERS - serverless

content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps linux wrapper to v1.10.13
```
/merge
```
=> Bump AAS-WRAPPER to version v1.10.13

content/en/logs/guide/control-sensitive-logs-data.md
- Add a reference link out to RBAC Roles
- [DOCS-8675](https://datadoghq.atlassian.net/browse/DOCS-8675)
```
/merge
```
[DOCS-8675]: https://datadoghq.atlassian.net/browse/DOCS-8675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add a reference link to roles

content/en/network_monitoring/devices/troubleshooting.md
=> fixing Error message

snippets/markdown.json
- Add collapse content to snippets
```
/merge
```
=> Add collapse content snippset

content/en/glossary/terms/forwarder_(Agent).md
=> fixes a typo in the glossary

content/es/integrations/mongodb_atlas.md
Fixes the supported OS values for the Spanish translation of the MongoDB Atlas integration. This issue was reported in DOCS-9768.
```
/merge
```
=> Update supported OS values for MongoDB Atlas 

content/en/network_monitoring/devices/_index.md
missing space. see something, say something
```
/merge
```
=> quick typo fix

snippets/markdown.json
- Add reuse full page snippet.
- Add HTML check mark snippet.
- Add logged-in user check snippet.
```
/merge
```
=> [Q4 Hackathon] Add More Entries to Snippets

snippets/markdown.json
=> Remove quotes from expanded param

content/en/real_user_monitoring/session_replay/mobile/privacy_options.md, content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
Introduces Session Replay documentation for React Native, for the upcoming official v2.5.0 release
=> [RUM-7156] React Native Session Replay Documentation

content/en/monitors/guide/_index.md, content/en/monitors/guide/composite_use_cases.md, content/en/monitors/types/composite.md
- Add a guide for the most common composite monitor use cases
- [DOCS-9772](https://datadoghq.atlassian.net/browse/DOCS-9772)
```
/merge
```
[DOCS-9772]: https://datadoghq.atlassian.net/browse/DOCS-9772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Composite monitor use cases

go.mod, go.sum
update websites-modules ref. 
motivation: https://datadoghq.atlassian.net/browse/WEB-5731
preview:  https://docs-staging.datadoghq.com/websites-modules/generated/383
```
/merge
```
=> add new `security-code-security` icon - [WEB-5731]

content/en/tracing/trace_collection/library_config/_index.md
Fixes inconsistent spacing
```
/merge
```
=> Fix inconsistent spacing in configs

content/en/tracing/trace_collection/library_config/_index.md
Fix improper spacing introduced by #26951
```
/merge
```
=> Fix improper spacing introduced by #26951

content/en/account_management/rbac/data_access.md
=> Add CI Visibility to datasets

content/en/account_management/billing/azure.md
Requested by a TSE on https://datadoghq.atlassian.net/browse/DOCS-9752
- Corrects the spelling of "collection"
- Points a link about custom metrics to the correct heading
```
/merge
```
=> Correct minor problems on Azure billing page

content/en/data_jobs/databricks.md
=> Fix Content Rendering Issue

content/en/database_monitoring/connect_dbm_and_apm.md
Clarify which DBMS products support prepared statement tracing, as the document was unclear.
```
/merge
```
=> Clarify DBMS support for prepared statements tracing

content/en/monitors/notify/variables.md
- Clarify attribute and tag variables in monitor messages
- General formatting to move some content in collapse blocks
- [DOCS-8882](https://datadoghq.atlassian.net/browse/DOCS-8882)
```
/merge
```
[DOCS-8882]: https://datadoghq.atlassian.net/browse/DOCS-8882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add clarification on monitor attributes and tags

content/en/logs/guide/how-to-set-up-only-logs.md
- Clarify which level to set the `enable_payloads` attribute
- [DOCS-9815](https://datadoghq.atlassian.net/browse/DOCS-9815)
```
/merge
```
[DOCS-9815]: https://datadoghq.atlassian.net/browse/DOCS-9815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clarify where to set `enable_payloads` attribute

content/en/serverless/aws_lambda/configuration.md, content/en/serverless/aws_lambda/installation/dotnet.md
Explains how to use the Datadog .NET tracer when working in AWS Lambda with our Datadog Lambda Layer for .NET.
```
/merge
```
=> Document how to properly install .NET tracer for AWS Lambda.

config/_default/menus/main.en.yaml
Adds a new top-level nav section for Actions, matching the recent change in the app itself.
```
/merge
```
Preview link example:
https://docs-staging.datadoghq.com/neko/DOCS-9621-top-level-reorg/service_management/workflows/
=> (DOCS-9621) Add new top-level nav section for Actions to match app

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-extension layer to version 68

content/en/mobile/_index.md
Small fix in mobile app's first paragraph
```
/merge
```
=> Fix mobile apps intro paragraph

data/partials/home.yaml
Adds App Builder to the landing page
```
/merge
```
=> (DOCS-9661) Add app builder to landing page

content/en/agent/troubleshooting/permissions.md
See [DOCS-9234](https://datadoghq.atlassian.net/browse/DOCS-9234). 
```
/merge
```
[DOCS-9234]: https://datadoghq.atlassian.net/browse/DOCS-9234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (Agent) Add information about system-wide macOS install

content/en/llm_observability/configuration/_index.md
This PR updates configuration page for ML Observability. The metrics to keep track usage of tokens for customer's LLM Accounts is being released, and we would like to update documentation to allow users to access these metrics. The PR adds brief paragraph about the metrics and how they can be used. 
```
/merge
```
=> [MLOB] Update Documentation for Configurations Page for ML Observability

content/en/security/cloud_security_management/misconfigurations/kspm.md
Adding a few rows to the setup table for GKE
```
/merge
```
=> Add GKE support to KSPM docs

content/en/service_management/events/_index.md
=> Add comm for monitor event aggregation key update

config/_default/menus/main.en.yaml, content/en/security/automation_pipelines/_index.md, content/en/security/automation_pipelines/mute.md, content/en/security/automation_pipelines/security_inbox.md
Changes Vulnerability Pipeline to Automation Pipelines to match the UI.
```
/merge
```
=> Update Automation Pipelines feature name

content/en/cloud_cost_management/azure.md, content/en/cloud_cost_management/google_cloud.md
=> Adding delay note to gcp and azure docs

content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/setup.md
I did a big comb through to look for discrepancies between the mobile docs post a big restructure, but just found a few minor errors.
```
/merge
```
=> Minor fix in iOS RUM mobile setup page

content/en/integrations/guide/azure-programmatic-management.md
Update a Terraform parameter
```
/merge
```
=> Update Terraform param

content/en/security/application_security/threats/setup/compatibility/nodejs.md
Include a small note for a requirement in the Node.js Threat Protection Capability
```
/merge
```
=> Node.js Threat Protection Capability requirement note

content/en/security/application_security/threats/exploit-prevention.md
=> Add command injection for Exploit Prevention in Java

content/en/infrastructure/containers/amazon_elastic_container_explorer.md
=> update ecs explorer doc

content/en/security/security_inbox.md
Changes Vulnerability Pipeline to Automation Pipelines to match the UI. Related to [27049](https://github.com/DataDog/documentation/pull/27049). This PR updates an article that I forgot to update in the original PR.
```
/merge
```
=> Change Vulnerability Pipeline to Automation Pipelines

content/en/database_monitoring/connect_dbm_and_apm.md
Updates the prepared statements note to clarify that the extra roundtrip has a minimal impact on latency. Requested by PM.
```
/merge
```
=> Update prepared statements note

content/en/account_management/guide/access-your-support-ticket.md
Requested on https://datadoghq.atlassian.net/browse/DOCS-9848
This update is required due to changes we have made to our Zendesk Instance to allign with the latest HIPAA requirements here: [Security Configuration Requirements for HIPAA or HDS Enabled Accounts on Zendesk](https://support.zendesk.com/hc/en-us/articles/4408828395802-Security-Configuration-Requirements-for-HIPAA-or-HDS-Enabled-Accounts-on-Zendesk#:~:text=Secure%20Agent%20authentication,to%20%E2%80%9CRecommended%E2%80%9D%3B).
```
/merge
```
=> Add password requirements to support page

content/en/opentelemetry/otlp_logs.md
=> Add Preview banner to logs intake endpoint

layouts/shortcodes/dbm-sqlserver-agent-setup-kubernetes.en.md
Add missing commas to json block nested within yaml config file in "Configure with Kubernetes service annotations" section for SQL Server DBM setup. 
```
/merge
```
=> DOCS-9812 

content/en/dora_metrics/setup/deployments.md
=> Adding limitation on maximum number of commits considered

content/en/cloudcraft/faq/account-data-storage.md
It seems like we forgot to update the type of SOC2 available to Cloudcraft, so this PR fixes that.
=> [CLOUDCRAFT-1085] Update SOC2 type

config/_default/menus/main.en.yaml, content/en/actions/actions_catalog/_index.md, content/en/actions/private_actions/_index.md, content/en/actions/private_actions/private_action_credentials.md, content/en/actions/private_actions/use_private_actions.md, content/en/getting_started/workflow_automation/_index.md, content/en/service_catalog/customize/_index.md, content/en/service_catalog/navigating.md, content/en/service_catalog/software_templates.md, content/en/service_management/app_builder/_index.md, content/en/service_management/app_builder/build.md, content/en/service_management/app_builder/connections/http_request.md, content/en/service_management/app_builder/private_actions/_index.md, content/en/service_management/app_builder/private_actions/private_action_credentials.md, content/en/service_management/app_builder/private_actions/use_private_actions.md, content/en/service_management/workflows/_index.md, content/en/service_management/workflows/access.md, content/en/service_management/workflows/actions/http.md, content/en/service_management/workflows/build.md, content/en/service_management/workflows/connections.md
…eading
Moves Actions Catalog and Private Actions out of App Builder/Workflows and up to the Actions level of the nav hierarchy.
```
/merge
```
=> (DOCS-9621) Reorg some content from appb and workflows into Actions heading

content/en/serverless/azure_app_services/azure_app_services_linux.md
Bumps the linux AAS Wrapper 
```
/merge
```
=> Bump AAS-WRAPPER to version v1.10.14

content/ja/logs/guide/azure-logging-guide.md
Fix a broken image address in the Japanese documentation. This change has also been made in Transifex, but opening this PR separately due to some recent issues with the translation PR.
```
/merge
```
=> Fix image address

content/en/network_monitoring/devices/ping.md, content/en/network_monitoring/devices/sd-wan.md
Adding VeloCloud to SD-WAN page and small fix to the ping page.
```
/merge
```
=> [DOCS-9758] adding VeloCloud support

content/en/network_monitoring/devices/troubleshooting.md
Since `7.61` was released yesterday we have better logging that I have documented for the Autodiscovery section on this page.
```
/merge
```
=> [DOCS-9704] Additional information on Autodiscovery

content/en/service_management/on-call/_index.md
=> Remove private beta notice from On-Call docs

content/en/tracing/guide/setting_up_APM_with_cpp.md, content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/cpp.md
Update for v1.0.0 c++ release.
```
/merge
```
=> update cpp documentation for v1.0.0 release

content/en/tracing/trace_collection/compatibility/php.md
It's available since 1.5, update the docs.
```
/merge
```
=> Add PHP 8.4 compatibility

content/en/data_streams/dotnet.md, content/en/data_streams/java.md, content/en/data_streams/nodejs.md, content/en/data_streams/python.md
=> DSM - various notes on setup pages

config/_default/menus/main.es.yaml, config/_default/menus/main.fr.yaml, config/_default/menus/main.ja.yaml, config/_default/menus/main.ko.yaml
=> (Agent)(JA) Remove upgrade from nav

content/en/data_jobs/databricks.md, content/en/data_jobs/emr.md, layouts/shortcodes/djm-install-troubleshooting.en.md
As part of the [new installer script roll-out plan](https://docs.google.com/document/d/1cQ_xlv8uAts4YQvFYUXbwTBD_xyzv9hCYzzFszsVQz8/edit?usp=sharing) (step 4), this PR updates the script link in the DJM on EMR documentation page to the new installer script. This will allow future customers to use the new installer script.
Please don't merge yet
```
/merge
```
=> [DJM] New installer script for EMR

content/en/data_jobs/dataproc.md
As part of the [new installer script roll-out plan](https://docs.google.com/document/d/1cQ_xlv8uAts4YQvFYUXbwTBD_xyzv9hCYzzFszsVQz8/edit?usp=sharing) (step 4), this PR updates the script link in the DJM on Dataproc documentation page to the new installer script. This will allow future customers to use the new installer script.
Please don't merge yet
```
/merge
```
=> [DJM] New installer script for Dataproc

content/en/tracing/troubleshooting/tracer_debug_logs.md
Re-adds an accidental deletion of tracer flare documentation.
```
/merge
```
=> [Fix] Readd tracer flare docs

content/en/cloud_cost_management/recommendations/_index.md
Clones https://github.com/DataDog/documentation/pull/27013
- [] Ready for merge
```
/merge
```
=> [DOCS-9843] Add Azure to CCM Recommendations table

layouts/integrations/_markup/render-image.html, layouts/shortcodes/site-region.html
uses [RenderString](https://gohugo.io/methods/page/renderstring/) instead of [markdownify](https://gohugo.io/functions/transform/markdownify/)
https://docs-staging.datadoghq.com/brian.deutsch/fix-integration-images/integrations/microsoft_teams/
```
/merge
```
https://docs-staging.datadoghq.com/brian.deutsch/fix-integration-images/
=> test render string

content/en/logs/log_collection/javascript.md, content/en/real_user_monitoring/browser/setup/client.md, content/en/real_user_monitoring/guide/monitor-your-nextjs-app-with-rum.md
=> update browser sdk snippets to include v6

content/en/security/threat_intelligence.md, content/ja/security/threat_intelligence.md
Add ASM as a new Threat Intel feed (Platform Level Flagged IPs)
```
/merge
```
=> Add ASM as a new Threat Intel feed (Platform Level Flagged IPs)

content/en/monitors/types/cloud_cost.md
=> Adding note about historical data for anomaly monitors

content/en/developers/integrations/oauth_for_integrations.md
Formatting is rendering incorrectly in the [Create or update your pull request](https://docs.datadoghq.com/developers/integrations/oauth_for_integrations#create-or-update-your-pull-request) section.
```
/merge
```
=> Update Spacing in OAuth for Integrations Page

content/en/getting_started/tagging/assigning_tags.md
I realized too late that https://github.com/DataDog/documentation/pull/27186 didn't have a slash in the branch name. I'm duplicating the PR so we can get it merged in quickly.
```
/merge
```
=> Duplicate Jake's PR into branch with slash

content/en/agent/configuration/network.md
Adds LLM Obs intake endpoint to the network traffic page
```
/merge
```
=> add llmobs intake

content/en/tracing/trace_collection/proxy_setup/_index.md
Add instructions to instrument ingress-nginx.
```
/merge
```
=> Add ingress-nginx injection method

content/en/observability_pipelines/live_capture.md
Adds permissions information for Live Capture.
```
/merge
```
=> [DOCS-9871] Add permissions section

content/en/cloud_cost_management/recommendations/_index.md
Clarified public docs on how we compute over-provisioned containers.
```
/merge
```
=> clarify over-provisioned containers description

content/en/opentelemetry/troubleshooting.md
- Add more troubleshooting scenarios.
- Reformat structure to be more user-focused and consistent.
```
/merge
```
=> OTel Troubleshooting Update

content/en/tests/setup/java.md
Includes Weaver as a supported framework in Test Optimization for Java. It also provides instructions for test running using SBT.
```
/merge
```
=> Include Weaver as a supported framework in Test Optimization for Java

layouts/shortcodes/aws-permissions.en.md
- add ec2:GetAllowedImagesSettings
```
/merge
```
=> [AWSX] Update AWS integration role documentation

content/en/agent/logs/advanced_log_collection.md, content/en/sensitive_data_scanner/_index.md
Remove SDS via Agent. PM request.
[DOCS-9912](https://datadoghq.atlassian.net/browse/DOCS-9912)
```
/merge
```
[DOCS-9912]: https://datadoghq.atlassian.net/browse/DOCS-9912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-9912] Remove SDS via agent

content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/advanced_configuration.md
Per customer feedback, updates a React Native initialization parameter so that it matches the same one that is mentioned later in the doc.
```
/merge
```
=> [DOCS-9908] Update RUM react initialization parameter

config/_default/menus/main.en.yaml
* Adding OTel integrations to left-nav to make it easier for users to navigate.
```
/merge
```
=> Add child pages for OTel integrations

content/en/monitors/_index.md, content/en/monitors/types/_index.md
- Add new monitor course as reference in the docs
```
/merge
```
=> Add learning center courses to docs

content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/advanced_configuration.md
A customer opened a support ticket pointing out a typo in the React Native documentation.
```
/merge
```
=> Fix capitalization and typo

content/en/security/cloud_security_management/setup/agentless_scanning/cloudformation.md, content/en/security/cloud_security_management/setup/agentless_scanning/quick_start.md, layouts/shortcodes/cloud-siem-aws-setup-cloudformation.en.md
Updates Cloud Security Management AWS instructions to match latest UI updates.
```
/merge
```
=> Update CSM AWS instructions to match latest UI

content/en/service_management/app_builder/build.md
```
/merge
```
FYI approved by PM over slack
=> (DOCS-9615) Add info on tagging in App Builder

content/en/logs/guide/azure-logging-guide.md
Update the NodeJS version in the azure log forwarder deployment docs. Node 18 is being deprecated soon. We already successfully tested the forwarder with Node 20.
```
/merge
```
=> Upgrade recommended NodeJS version for Azure log forwarder

content/en/monitors/downtimes/examples.md
=> Remove Sensitive Info

content/en/network_monitoring/cloud_network_monitoring/network_analytics.md, content/en/network_monitoring/cloud_network_monitoring/setup.md
Adding metrics for CNM Failed Connections which goes GA tomorrow.
Ok to merge after the Eng review.
```
/merge
```
=> [DOCS-9932] adding metrics for Failed Connections

content/en/service_management/on-call/pages.md
=> Remove mentions

.github/workflows/vale_linter.yml, content/en/agent/basic_agent_usage/_index.md
Skips vale checks when no actionable changes are found (For example, PRs that only delete lines)
Example of passing job: https://github.com/DataDog/documentation/actions/runs/12955364445/job/36139327902?pr=27285
```
/merge
```
=> (maint) Fix vale check on line deletions

layouts/shortcodes/mapping-table.html
add more context to websites-sources data being consumed by Docs.
preview: https://docs-staging.datadoghq.com/stefon.simmons/update-mapping-table-sc-notes/opentelemetry/integrations/docker_metrics/?tab=host
- should be no visual change
```
/merge
```
=> update note - mapping table

content/en/database_monitoring/connect_dbm_and_apm.md
Moves note to warning alert box. Requested by PM.
```
/merge
```
=> Move note to warning alert box

content/en/bits_ai/_index.md
=> DOCS 9928: US1-Fed does not support Bits AI

content/en/network_monitoring/cloud_network_monitoring/network_analytics.md
small update to reflect the `gateway_public_ip` is the NAT gateway.
```
/merge
```
=> Update network_analytics tag

content/en/cloud_cost_management/azure.md, content/ja/cloud_cost_management/azure.md
Update Azure CCM docs to reflect we can support MCA at all scopes
```
/merge
```
=> Update Azure CCM docs to reflect we can support MCA at all scopes

config/_default/menus/main.en.yaml
changing IAST to Runtime Code Analysis (IAST)
=> Update menu with Runtime Code Analysis (IAST)

content/en/real_user_monitoring/session_replay/mobile/_index.md
Mobile Session Replay is now GA. We should remove all mentions of preview/beta
```
/merge
```
=> Remove 'preview' callout from Mobile Session Replay page

content/en/monitors/status/status_page.md
Live processes monitors are now available in the new monitor status page
=> Update list of unsupported monitor type

assets/scripts/config/regions.config.js, content/en/data_jobs/databricks.md
=> DOCS-9594 adding API IPs to allowlist

content/en/integrations/guide/aws-manual-setup.md
Add a disclaimer to the Access Keys tab
```
/merge
```
=> (DOCS-9936) Add disclaimer

content/en/sensitive_data_scanner/_index.md
=> Small edits to SDS landing

content/en/logs/guide/azure-logging-guide.md
This reverts commit 53b3825ca1533a03394b80742e4bfcffa4d00454.
Revert the update to nodeJS 20. Some customers have reported issues on version 20 and we need to do more work to support it.
```
/merge
```
=> Revert "Upgrade nodejs version (#27260)"

content/en/tests/flaky_test_management/auto_test_retries.md, content/en/tests/flaky_test_management/early_flake_detection.md
Specify `Weaver` as a not supported framework in EFD and ATR pages.
```
/merge
```
=> Indicate Weaver is not supported in EFD and ATR pages

content/en/monitors/types/cloud_cost.md
We are going to change the algorithm in the cost monitor backend for anomalies and changes the frontend to reflect that as well. The change is about the `seasonality`, we are going to change from `monthly` to `weekly` that's why we are updatingt the documentation.
```
/merge
```
=> [CCM][Docs] Anomaly Monitor - Update from 4 to 1 month of historical data needed

content/en/real_user_monitoring/feature_flag_tracking/setup.md
The Feature Flag tracking snippet for NPM was incorrect.
```
/merge
```
=> Fix code snippet in Feature Flag tracking

content/en/containers/cluster_agent/admission_controller.md, content/en/developers/dogstatsd/datagram_shell.md
Add the DogStatsD Datagram changes that were introduced for Origin Detection
```
/merge
```
=> chore(dogstatsd): add new datagram specs

content/en/llm_observability/configuration/_index.md
=> LLM configuration -> settings

content/en/logs/guide/azure-logging-guide.md
Update the NodeJS version in the azure log forwarder deployment docs. Node 18 is being deprecated soon. We already successfully tested the forwarder with Node 20. Previously we updated but found a problem, which has now been fixed.
```
/merge
```
=> Upgrade nodejs version

content/en/change_tracking/_index.md, content/en/cloud_cost_management/_index.md, content/en/security/_index.md
=> Add related blog links

content/en/synthetics/troubleshooting/_index.md
Fixes a small typo in the docs.
```
/merge
```
=> Fix typo in documentation

content/en/tracing/trace_pipeline/ingestion_controls.md
Fix capitalisation in the precedence section of ingestion_controls.md
```
/merge
```
=> Fix capitalisation ingestion_controls.md

content/en/security/application_security/threats/threat-intelligence.md
https://datadoghq.atlassian.net/browse/DOCS-9964
Doc-to-app link update
=> DOCS-9964 Update threat intelligence link to app

content/en/developers/integrations/check_references.md
Add details on a new column we support where integration developers can provide a list of example tags that are associated with the metrics from their integration
Please merge when approved
```
/merge
```
=> update integration docs

layouts/shortcodes/latest-lambda-layer-version.html
=> Release new java layer version.

content/en/integrations/guide/storage-monitoring-setup.md
Change references to Resource Catalog (Storage Monitoring now lives under Infrastructure) and clarify set up steps
- [YES ] Ready for merge
```
/merge
```
=> content update

content/en/tests/flaky_test_management/early_flake_detection.md
The feature is no longer in preview.
=> [test optimization] Remove preview tag from Early Flake Detection

content/en/notebooks/notebooks_new.md
There's an extra line and header in the table. Removed it to fix the formatting.
```
/merge
```
=> Fix table formatting

content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/integrated_libraries.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/setup.md
With the new release of KMP SDK it is needed to update docs as well a bit.
```
/merge
```
=> Update Kotlin Multiplatform SDK documentation for 0.5.0 release

content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/integrated_libraries.md, content/en/real_user_monitoring/platform/connect_rum_and_traces.md
Following the change in https://github.com/DataDog/dd-sdk-kotlin-multiplatform/pull/137 we need to update documentation as well.
```
/merge
```
=> Rename traceSamplingRate to traceSampleRate in Kotlin Multiplatform SDK documentation

content/en/service_management/workflows/build.md
Fix a link reported in Hotjar
```
/merge
```
=> Fix broken context variables link

content/en/dashboards/sharing/scheduled_reports.md
Scheduled reports have been released in govcloud, so we should remove the warning banner pictured below.
**Before change:**
**After change (preview):**
https://dd.slack.com/archives/C027J9N1K44/p1738688359294219
```
/merge
```
=> [reporting, CRP-1138, DBNBK-246] Remove govcloud reporting warning

content/en/serverless/azure_app_services/azure_app_services_linux.md
=> Bump AAS-WRAPPER to version v1.10.15

content/en/tracing/trace_collection/compatibility/java.md, content/en/tracing/trace_collection/library_config/java.md
Update java compatibility for Ignite and add documentation for cassandra keyspace extraction
```
/merge
```
=> Update java compatibility for Ignite and add documentation for cassandra keyspace extraction

content/en/data_jobs/kubernetes.md
Explain logs collection setup for Data Jobs Monitoring on K8s. It's basically the same as the [regular process for Logs on containers](https://docs.datadoghq.com/containers/kubernetes/log/?tab=helm#log-collection), so we link this page and integrate the key parts in our existing doc page.
Not ready to merge before @warrierr approves
```
/merge
```
=> [DJM] Logs setup guidelines on K8s

content/en/cloud_cost_management/saas_costs.md
Adds docs around new object tags feature. There is more information about object tags for cost per query but that is behind a FF so it will be added to these docs once cost per query is GA
```
/merge
```
=> Snowflake CCM Object Tags Docs

content/en/cloud_cost_management/multisource_querying/_index.md
=> Review preview from CCM multisource

layouts/shortcodes/latest-lambda-layer-version.html
=> [serverless] bump version

content/en/tracing/trace_collection/compatibility/python.md
=> clarify pylons is only in dd-trace-py 1.x

content/en/security/code_security/software_composition_analysis/_index.md
Broken link to https://app.datadoghq.com/security/configuration/code-security/setup
=> fix broken link to Code Sec setup page

README.md
Based on recent observations, it takes around 35 minutes for the deploy to complete: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/792580223
Listing this in the README is helpful if you're waiting for a deploy to complete but don't know how long it usually takes.
```
/merge
```
=> Add note about deploy time to README.md

content/en/agent/fleet_automation/remote_management.md
=> (Agent) Update requirements for remote management

content/en/account_management/saml/mapping.md
Clarifying behavior when JIT and role mapping are both enabled
```
/merge
```
=> greg.saville/update_jit_and_role_mapping_docs

content/en/dashboards/widgets/_index.md
Support requested update.
```
/merge
```
=> Remove alert on permissions for copy paste

content/en/llm_observability/setup/api.md
Updated the overview statement to mention you can use the SDKs not only for Python, but also for Node.js. The documentation link stays the same.
```
/merge
```
=> update overview statement to include Node.js SDKs

content/en/ddsql_editor/reference_tables.md
=> Update Doc Link

config/_default/menus/main.en.yaml, content/en/security/cloud_siem/detection_rules/attack_map.md
- Adds ATT&CK Map doc
- Adds nav item
```
/merge
```
=> [DOCS-9937] Add ATT&CK Map doc

content/en/integrations/guide/aws-organizations-setup.md
This note will let customers know that it's expected for the AWS Management account to NOT be integrated.
Tickets:
https://datadog.zendesk.com/agent/tickets/1973125
https://datadog.zendesk.com/agent/tickets/1568148
```
/merge
```
=> Add section for AWS Management account

content/en/service_management/service_level_objectives/ootb_dashboard.md
Removing signup link for now to reduce discoverability since we are in the process of moving this feature
```
/merge
```
=> remove signup link

content/en/tracing/metrics/runtime_metrics/python.md
=> Remove beta banner for Python runtime metrics

content/en/monitors/status/status_page.md, content/en/observability_pipelines/_index.md, content/en/sensitive_data_scanner/_index.md
Adding blog links to further reading
```
/merge
```
=> update blogs on further reading links

content/en/reference_tables/_index.md
Jin [asked](https://dd.slack.com/archives/C0DESMBQU/p1739225345287429) for help adding some comments in an existing code sample :)
```
/merge
```
=> Add comments to reference table code sample

content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/monitoring_app_performance.md
Fixing the page title, it referred to Android, but this is iOS doc.
=> Fix title in RUM > ... > Monitoring App Performance

content/en/account_management/saml/okta.md
From a Slack conversation in #support-aaa, the company ID can have 2 formats: the uuid style currently documented, or an old style with no dashes. Removing the bit about the format because it's wrong.
Also took the time to make the headings unique and descriptive.
```
/merge
```
=> Remove incorrect company ID format and add detail to headers

assets/styles/components/_schema-table.scss
Updates api schema tables to indent at the 5th level too
https://datadoghq.atlassian.net/browse/WEB-5993
```
/merge
```
expand the schema tables and visual check this url and other api endpoints
https://docs-staging.datadoghq.com/david.jones/indent/api/latest/action-connection/#create-a-new-action-connection
=> WEB-5993 - schema table indent 5th level

layouts/shortcodes/sci-dd-setuptools-unified-python.en.md, layouts/shortcodes/sci-dd-setuptools-unified-python.fr.md, layouts/shortcodes/sci-dd-setuptools-unified-python.ja.md, layouts/shortcodes/sci-dd-setuptools-unified-python.ko.md
=> Fix dd-trace python link in sci setup

content/en/database_monitoring/guide/sql_deadlock.md
Add deadlocks support for Azure DB.
```
/merge
```
=> Add deadlocks support for Azure DB

content/en/containers/guide/operator-advanced.md
Added the namespace also in the operator, otherwise this config won't work
Added the -n in the operator configuration otherwise the installation won't produce results (agent containers won't be scheduled)
```
/merge
```
=> Massimo.sporchia/modify operator install instructions

content/en/monitors/types/audit_trail.md
- Add a note about the limitation for creating Audit Trail monitors
- [DOCS-9938](https://datadoghq.atlassian.net/browse/DOCS-9938)
```
/merge
```
[DOCS-9938]: https://datadoghq.atlassian.net/browse/DOCS-9938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add limitation note for audit trail monitors

content/en/logs/guide/azure-logging-guide.md
Adds a banner to the log forwarding guide to notify customers of the new automated log forwarding solution.
```
/merge
```
=> [AZINTS-3129] Add Automated Log Forwarding Banner

content/en/logs/log_collection/ios.md
- Update directions to specify when to create the Logger
- [DOCS-9929](https://datadoghq.atlassian.net/browse/DOCS-9929)
```
/merge
```
[DOCS-9929]: https://datadoghq.atlassian.net/browse/DOCS-9929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Specify when to create logger

layouts/integrations/_markup/render-image.html
https://datadoghq.atlassian.net/browse/WEB-5964
```
/merge
```
https://docs-staging.datadoghq.com/brian.deutsch/web-5964-preview-bucket/integrations/airbrake/
view source of the image here, it should point to `dd-app-listings-staging`
=> Use staging bucket to pull integration images in non prod environments

content/en/monitors/types/audit_trail.md
=> copy paste error

content/en/synthetics/guide/browser-tests-totp.md
As per internal feedback:
- Added one line to provide clarity around where customers would obtain their secret key / QR code
```
/merge
```
=> [DOCS-9374] Add specific detail about auth app

content/en/metrics/guide/dynamic_quotas.md
Ready to merge after approval.
=> Updated Dynamic Quotas Documentation

content/en/software_catalog/use_cases/api_management.md, content/en/software_catalog/use_cases/appsec_management.md, content/en/software_catalog/use_cases/cloud_cost_management.md, content/en/software_catalog/use_cases/dependency_management.md, content/en/software_catalog/use_cases/dev_onboarding.md
Fix the circular aliases introduced in #27469 and identified by the documentation build.
```
/merge
```
=> Remove circular aliases

config/_default/menus/main.en.yaml
Update the `pre` value for Software Catalog to pull the service catalog icon.
```
/merge
```
=> Update software catalog icon

config/_default/menus/main.en.yaml, content/en/security/cloud_siem/detection_rules/mitre_attack_map.md
Update mention of ATT&CK Map to MITRE ATT&CK Map. PM request.
```
/merge
```
=> Update to MITRE ATT&CK Map

content/en/security/code_security/software_composition_analysis/setup_runtime/_index.md
quick fix to remove duplicate heading
```
/merge
```
=> removing duplicate heading

content/en/containers/guide/container-discovery-management.md
Updates the container inclusion/exclusion image filters documentation.
It explicitly states how the image name filter is used to include/exclude metrics or logs, and gives detailed and correct examples.
Wait for 7.62 to be released.
```
/merge
```
=> [CONTP-537] update container image inclusion/exclusion filters examples, and clarify the matching logic of image filter

content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/advanced_configuration.md
📦⛑️ Fixing various code snippets that I found in RUM > iOS > Advanced Configuration.
=> Fix code snippets in RUM > iOS > Advanced Configuration

content/en/continuous_integration/pipelines/github.md
This PR adds an explanation to the infrastructure correlation section of the Github CI Visibility documentation, since this feature has been GA for the last week.
```
/merge
```
=> [SDCI-1054] Add Actions Runner Controller infra corr setup explanation

content/en/observability_pipelines/set_up_pipelines/archive_logs/amazon_data_firehose.md
Remove SDS update because it's not available yet.
```
/merge
```
=> Remove SDS update from Archive Logs for Firehose

content/en/observability_pipelines/set_up_pipelines/_index.md
Fix list and update links.
```
/merge
```
=> Fix OP Setup list and links

content/en/monitors/status/status_page.md
Synthetics montiors are now available in the new monitor status page
=> Update status_page doc

content/en/tests/setup/dotnet.md, content/en/tests/setup/java.md, content/en/tests/setup/javascript.md, content/en/tests/setup/python.md, content/en/tests/setup/ruby.md, content/en/tests/setup/swift.md, content/en/tests/troubleshooting/_index.md
Words inspired by @nikita-tkachenko-datadog 
```
/merge
```
=> [test optimization] Better `DD_TEST_SESSION_NAME` explanation

content/en/containers/kubernetes/distributions.md
=> DOCS-9734: cleanup kubernetes distro

content/en/integrations/guide/aws-integration-troubleshooting.md
Add information about a Datadog tool for removing AWS host tags
```
/merge
```
=> (DOCS-9965) Add remove_lingering_aws_host_tags.py link

content/en/account_management/saml/_index.md
DOCS-10062
Customers are seeing this new behavior and are confused. Adds a sentence explaining that Datadog sends email verification codes to people using SP-initiated SAML login.
Also reorganizes and rewords existing content for readability and style.
```
/merge
```
=> Document one time login codes for SP-initiated SAML login

content/en/monitors/guide/_index.md
- No content change, product team requested a reorganization of the Monitor Guides index page.
- [DOCS-10063](https://datadoghq.atlassian.net/browse/DOCS-10063)
```
/merge
```
[DOCS-10063]: https://datadoghq.atlassian.net/browse/DOCS-10063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reorg monitor guides index

content/en/containers/amazon_ecs/_index.md
=> [AGENTRUN-117] Update FIPS proxy version to 1.1.7

config/_default/segments.yaml
adds an initial segment config and a test item. 
Note this doesn't affect the current build, in order to use the segment you need to pass in cli flags
```
/merge
```
=> add segment config

content/en/tracing/trace_collection/compatibility/nodejs.md
=> update nodejs express docs version

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
https://datadoghq.atlassian.net/browse/DOCS-10149
Adding PHP to the APM libraries list on the SSI page under Linux host.
```
/merge
```
=> Add PHP to list

.github/CODEOWNERS
What does this PR do?
---------------------
The `cloud-cost-management-visibility` team is being renamed to `ccm-planning`.
Who will it impact?
-------------------
@DataDog/cloud-cost-management-visibility + @DataDog/ccm-planning 
```
/merge
```
=> [CCM] Update codeowners

content/en/service_management/incident_management/incident_settings/property_fields.md
We're launching a new type of property field called text arrays. This updates the public docs to reflect the new type in the "Property Fields" subpage.
(description language approved by @shahgahmed)
```
/merge
```
=> INA-6986: Update property fields page with new text array type

content/en/data_jobs/emr.md
=> [DJM EMR page] Disable log collection by default

content/en/dynamic_instrumentation/enabling/php.md
=> Hide PHP in Dynamic Instrumentation tabs

layouts/shortcodes/observability_pipelines/destination_batching.en.md
Add missing batch parameters for OP destinations.
```
/merge
```
=> Add missing batch parameters

content/en/tracing/trace_collection/custom_instrumentation/go/migration.md
Improve v2check docs after customer feedback.
```
/merge
```
=> fix(tracing/trace_collection/custom_instrumentation): improve go v2check docs

content/en/data_streams/_index.md
=> Data Streams is available in ap1

content/en/logs/log_configuration/flex_logs.md
Fix a small typo in the flex docs.
```
/merge
```
=> 🔤 Fix typo in flex logs doc

content/en/security/cloud_siem/investigator.md
Updating the investigator docs page with new changes to copy on the feature itself and also adding the new Datadog audit investigator as a tab.
```
/merge
```
=> Adding Datadog Investigator

content/en/api/latest/_index.md
My smallest and most inconsequential PR yet, and that is perhaps saying something! This is a single-character typo fix.
(Edit - I then went back and fixed a _second_ character, thereby doubling my impact. No need to call me a hero.)
```
/merge
```
=> Add apostrophe to possessive

content/en/database_monitoring/connect_dbm_and_apm.md
This PR updates `Correlate Database Monitoring and Traces` page to include mongodb. 
```
/merge
```
=> Add mongodb to Correlate Database Monitoring and Traces

content/en/infrastructure/containers/amazon_elastic_container_explorer.md
Processes tab doesn't exist anymore => they have been added to the RelatedEntityTable above
| [Before](https://docs.datadoghq.com/infrastructure/containers/amazon_elastic_container_explorer/?tab=taskdefinition) | [After](https://docs-staging.datadoghq.com/christine.chun/update-ecs-doc-remove-processes-tab/infrastructure/containers/amazon_elastic_container_explorer/?tab=taskdefinition) |
|--------|--------|
| <img width="798" alt="Screenshot 2025-02-19 at 17 37 06" src="https://github.com/user-attachments/assets/5ec87375-3f88-43b0-91c1-e5ec8c36ef4b" /> | ![Screenshot 2025-02-20 at 10 01 47](https://github.com/user-attachments/assets/567523f4-f257-4bc4-b6fa-1b7d05dc4404) |
Merge queue is enabled in this repo. To have it automatically merged after it receives the required …
=> Update ecs explorer doc - remove processes in listed tabs

content/en/service_management/incident_management/incident_settings/property_fields.md
Addressing comments on https://github.com/DataDog/documentation/pull/27680.
```
/merge
```
=> INA-6986: Update property fields page descriptions

content/en/tracing/trace_collection/automatic_instrumentation/_index.md
=> Removing BETA Label from SSI

content/en/account_management/plan_and_usage/usage_details.md
fixing a typo - credit to @jesspanganiban :) 
```
/merge
```
=> fixing typo in usage details page

content/en/dynamic_instrumentation/_index.md, content/en/dynamic_instrumentation/enabling/nodejs.md
Update the Dynamic Instrumentation for Node.js docs, with information about newly added source map support.
Also bump the minimum required version to the version that has source maps support.
```
/merge
```
=> Dynamic Instrumentation for Node.js: Document source map support

content/en/dashboards/widgets/timeseries.md
- Add feature for partial data
- [DOCS-10100](https://datadoghq.atlassian.net/browse/DOCS-10100)
```
/merge
```
[DOCS-10100]: https://datadoghq.atlassian.net/browse/DOCS-10100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add sentence on graphing partial data

content/en/change_tracking/_index.md
Adds SQL Server to tracked changes table. Requested by PM.
```
/merge
```
=> Add SQL Server to tracked changes table

content/en/network_monitoring/devices/supported_devices.md
Link in NDM 'generic profile' section previously linked to:
https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/sinetica-eagle-i.yaml
But now links to:
https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/default_profiles/generic-device.yaml
```
/merge
```
=> Update NDM generic profile link

content/en/account_management/plan_and_usage/cost_details.md
Fix typo in plan and usage page
```
/merge
```
=> Fix typo in cost_details.md

content/en/mobile/datadog_for_intune.md
Fixing an issue I noticed while on-call - if the angle brackets aren't escaped, the whole thing just disappears. Escaping them so we can see them now 🙂 
```
/merge
```
=> Escape inline angle brackets

content/en/glossary/terms/security_posture_score.md
See [Slack thread](https://dd.slack.com/archives/C02G5J4FB0E/p1739911992529299) - a customer was confused about their custom compliance framework calculation worked. One team effort later, we have some clearer wording 💪🏻 
```
/merge
```
=> Clarify security posture score definition

content/en/tracing/trace_collection/compatibility/java.md
Instrumentation for Apache Pekko was added here: https://github.com/DataDog/dd-trace-java/pull/5858.
```
/merge
```
=> [DOCS-10182] Note Apache Pekko Support

content/en/dashboards/guide/is-read-only-deprecation.md
The migration and shutdown of this attribute is now in progress. We'd like to keep this document in place until its completed; the dates are no longer relevant. 
```
/merge
```
=> [easy] Remove dates from is_read_only migration doc

content/en/monitors/notify/variables.md
- Add a note clarifying group_by tagging behavior
- Clarify examples
- [DOCS-10098](https://datadoghq.atlassian.net/browse/DOCS-10098)
```
/merge
```
[DOCS-10098]: https://datadoghq.atlassian.net/browse/DOCS-10098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note clarifying group_by tagging behavior

content/en/logs/guide/azure-logging-guide.md
Reverts DataDog/documentation#27569
We've had plenty of customers sign up, so we can take it down now.
=> [AZINTS-3181] Remove Automated Log Forwarding Banner

content/en/cloud_cost_management/azure.md
=> remove mca subscription note

config/_default/menus/main.en.yaml
Update the metrics TOC per DOCS-10184
```
/merge
```
=> (DOCS-10184) Update metrics TOC

content/en/integrations/guide/powershell-command-to-install-azure-datadog-extension.md, content/fr/integrations/guide/powershell-command-to-install-azure-datadog-extension.md, content/ja/integrations/guide/powershell-command-to-install-azure-datadog-extension.md, content/ko/integrations/guide/powershell-command-to-install-azure-datadog-extension.md
Updates the typehandler version to the latest. It has already been updated in the Azure Portal Marketplace Offering, but the CLI docs have not been updated.
```
/merge
```
=> [CLOUDS-5729] update typeHandlerVersion in documentation

content/en/tracing/trace_collection/library_config/php.md
This addresses DOCS-10208 and DOCS-10207. Adds clarity around PHP-FPM vs non-PHP-FPM config settings and the impact of clear_env=yes variable. 
```
/merge
```
=> DOCS-10208

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
Re-do of this guy - https://github.com/DataDog/documentation/pull/27782 - but in proper branch format so we can run all the checks.
```
/merge
```
=> document instrumentation at *import* time before init

config/_default/params.ja.yaml, config/_default/params.ko.yaml
=> (QUICK-FIX) Fix KO/JA banners

local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
Pull the CWS agent documentation from the 7.63.x branch now that this agent version has been released.
```
/merge
```
=> Pull CWS agent documentation from 7.63 release

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/compatibility.md
Adds a "Tracer libraries" section to the SSI Compatibility page to clarify minimum supported versions for each tracer library.
```
/merge
```
=> DOCS-10217

content/en/cloud_cost_management/saas_costs.md
clarify how much data is available at setup
```
/merge
```
=> Confluent Cloud initially has 12 months of cost history

content/en/real_user_monitoring/session_replay/mobile/troubleshooting.md
Fix section of troubleshooting guide that claims swiftUI and jetpack compose are not supported.
```
/merge
```
=> Fix compose and swiftui in mobile troubleshooting guide

content/en/real_user_monitoring/browser/advanced_configuration.md
Update the documentation about error context, recently merged 
pr => https://github.com/DataDog/browser-sdk/pull/3320
```
/merge
```
=> Update documentation about error context 

content/en/tests/test_impact_analysis/_index.md, content/es/tests/test_impact_analysis/_index.md, content/ja/tests/test_impact_analysis/_index.md
Docs were outdated. We deprecated long ago the `Intelligent Test Runner Activation Write` permission.
```
/merge
```
=> [SDTEST][NOTICKET] Update TIA docs

content/en/tracing/guide/_index.md, content/en/tracing/guide/resource_based_sampling.md
- Add resource-based sampling and service overrides guides to index.
- Remove private param on resource-based sampling.
```
/merge
```
=> Resource Based Sampling Visibility

content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/_index.md
=> Update Runtime SCA Compatibility Requirements

layouts/shortcodes/latest-lambda-layer-version.html
Bump lambda layer versions
```
/merge
```
=> [serverless] bump lambda layer versions

content/en/coterm/_index.md
oops just confirmed this
```
/merge
```
=> fix shim command

content/en/tracing/trace_collection/custom_instrumentation/nodejs/otel.md
Updates Nodejs otel api docs to use the correct tracer instance in the examples
```
/merge
```
=> fix otel nodejs docs

content/en/network_monitoring/network_path/setup.md
=> [Network Path] add setup instructions to windows tab

content/en/security/application_security/threats/setup/single_step/_index.md, content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md, content/en/tracing/trace_collection/library_injection_local.md
SSI PHP support is going GA tomorrow (Feb. 28). 
We can now provide instructions to install it by default.
```
/merge
```
=> [SSI] Add PHP to the list of supported languages (GA)

content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
The React Native integration for Session Replay is now GA. These changes update the docs accordingly. 
```
/merge
```
Do not merge without eng review.
=> [DOCS-8397] Update mobile session replay react native setup

content/en/agent/guide/use-community-integrations.md
This PR moves the note about using "sudo" closer to command where it should be used. This prevents users from missing the note if the command fails and they stop reading.
Edit - Changed the "install" word to "installation" as suggested by the bot.
```
/merge
```
=> Move note about sudo in "community integration install" higher.

content/en/continuous_integration/pipelines/azure.md
Adds a new item to the list of needed webhooks. 
We have started using this hook to enrich some of our pipelines.
```
/merge
```
=> [SDCI-1025] Add new build complete hook to list

content/en/dynamic_instrumentation/_index.md, content/en/dynamic_instrumentation/enabling/nodejs.md
Bump the minimum required Node.js tracer version for use with Dynamic Instrumentation because the old version had a serious bug.
```
/merge
```
=> Dynamic Instrumentation for Node.js: Bump min required tracer version

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
Follow-up of https://github.com/DataDog/documentation/pull/27861, but specifically for the kubernetes instructions
```
/merge
```
=> [SSI] Add PHP to the kubernetes instructions

content/en/service_management/on-call/guides/configure-mobile-device-for-on-call.md
This PR adds a link to the Datadog On-Call contact card in the mobile device configuration guide.
=> [oncall] Add contact card link to mobile device guide

content/en/sensitive_data_scanner/_index.md
=> add alias to sensitive data scanner

content/en/opentelemetry/agent/agent_with_custom_components.md, content/en/opentelemetry/agent/install_agent_with_collector.md, content/en/opentelemetry/agent/migration.md, data/versions.yaml, layouts/shortcodes/version.html
- Add `version.html` to pull version numbers from `versions.yaml`
- Apply these to embedded Collector docs.
- **Goal**: Reduce manual effort keeping the docs up-to-date with frequent version changes.
```
/merge
```
=> Re-use Embedded Collector Versions

content/en/serverless/aws_lambda/installation/nodejs.md
=> DOCS-9719 - clarify serverless AWS lambda 

content/en/getting_started/tagging/_index.md
[DOCS-10161](https://datadoghq.atlassian.net/browse/DOCS-10161)
An internal user noticed we are lacking some information on tag inheritance, since this is such a complex topic, I elected to just surface this on the Getting Started with Tagging page so it's easier to find, with a link to how to fix host-level tag inheritance problems. 
```
/merge
```
[DOCS-10161]: https://datadoghq.atlassian.net/browse/DOCS-10161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOCS-10161] adding more info on tag inheritance

content/en/agent/guide/fips-agent.md
Just updating the msi build link. 
```
/merge
```
=> update Windows FIPS agent link

CONTRIBUTING.md
- Added more guidance based on user feedback research project.
```
/merge
```
=> [DOCS-6031] Update CONTRIBUTING.md

content/en/account_management/audit_trail/events.md
Quality Gates is a separate product and we would like to reflect this by putting its events in a separate category
```
/merge
```
=> :memo: [LOGSAC-853] Move quality gates events to its own category

content/en/logs/log_collection/kotlin_multiplatform.md, content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/setup.md
This PR removes the mentions of "preview" for Kotlin Multiplatform SDK and also specifies the versions of iOS SDK to be used for the GA release.
```
/merge
```
=> Prepare GA release of Kotlin Multiplatform SDK

content/en/monitors/guide/_index.md
Added Notification Message Best Practice to the Index.
=> Added Notification Message Best Practice to the Index.

content/en/security/code_security/_index.md
=> Update Code Security Capabilities Description

content/en/database_monitoring/connect_dbm_and_apm.md
Update warning when instrumenting prepared statements for APM<->DBM connection. Addressing ask in https://datadoghq.atlassian.net/browse/SDBM-1544.
```
/merge
```
=> Update DBM APM docs

content/en/agent/basic_agent_usage/aix.md, content/es/agent/basic_agent_usage/aix.md, content/ja/agent/basic_agent_usage/aix.md, content/ko/agent/basic_agent_usage/aix.md
Updates list of AIX versions supported by Unix Agent.
https://datadoghq.atlassian.net/browse/CECO-2010
```
/merge
```
=> Update AIX version list supported by Unix Agent

content/en/serverless/aws_lambda/configuration.md
Removes outdated banner
```
/merge
```
=> SVL - remove outdated banner

content/en/security/cloud_security_management/_index.md
Chris flagged that we only mention AWS IAM in our identity risk summary on the CSM landing page. This is a very minor PR to add in Azure and GCP.
```
/merge
```
=> Add CSPs to identity risks summary

content/en/tests/setup/junit_xml.md
This PR fix the windows download link and also add a snippet for CircleCI.
Changes:
- Fix Windows url.
- Add CircleCI snippet.
```
/merge
```
=> test-optimization: fix link and add circleci snippet

content/en/dashboards/guide/powerpacks-best-practices.md, content/en/dashboards/widgets/powerpack.md
- Add instructions for deleting a powerpack
- Remove outdate images and update instructions for customizing powerpacks
- [DOCS-10232](https://datadoghq.atlassian.net/browse/DOCS-10232)
```
/merge
```
[DOCS-10232]: https://datadoghq.atlassian.net/browse/DOCS-10232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add and update information for powerpacks

config/_default/menus/main.en.yaml, content/en/security/code_security/secret_scanning/_index.md, content/en/security/code_security/secret_scanning/generic_ci_providers.md, content/en/security/code_security/secret_scanning/github_actions.md
We want to document our secrets scanning features
Add secrets scanning documentation
=> Add secrets scanning documentation

content/en/serverless/aws_lambda/installation/go.md
Removes an extra "string" that is repeated twice.
```
/merge
```
=> Remove repeated word

data/synthetics_worker_versions.json
Manual bump of windows-pl version
```
/merge
```
=> [S8S] build: ⬆️ bump release windows PL version to 1.55.0

content/en/opentelemetry/agent/install_agent_with_collector.md, content/en/opentelemetry/agent/migration.md
=> Note the EKS Fargate environments are not supported for embedded Collector

content/en/logs/guide/azure-logging-guide.md
Reverts DataDog/documentation#27787
=> [AZINTS-3226] Automated Log Forwarding Banner Back up again

content/en/security/code_security/secret_scanning/_index.md
Secrets scanning is in beta, we should tell customers to contact their CSM to get access.
Add a banner
=> Add preview banner with secrets scanning

content/en/tracing/trace_explorer/trace_view.md
Adding new ss to reflect the changes on UI
```
/merge
```
=> Update the screenshot

layouts/shortcodes/google-cloud-integrations.md
Updates the Google BigQuery URL to the correct one.
```
/merge
```
=> Update google cloud bigquery link

layouts/shortcodes/observability_pipelines/configure_existing_pipelines/install_worker/docker.en.md
=> Fix OP shortcode typo

content/en/containers/kubernetes/distributions.md
=> Remove note about CNM not support on GKE Autopilot (it is supported now)

content/en/containers/amazon_ecs/_index.md
=> Update FIPS proxy version to 1.1.8

content/en/account_management/audit_trail/events.md
=> Fix table and anchor link

content/en/containers/kubernetes/installation.md
Clarify the UID that Datadog recommends.
```
/merge
```
=> Clarify recommended UID for Unprivileged installation

layouts/shortcodes/latest-lambda-layer-version.html
Bumps `datadog-lambda-py` to latest version
https://github.com/DataDog/datadog-lambda-python/releases
```
/merge
```
=> Bump datadog-lambda-py version

content/en/agent/basic_agent_usage/_index.md
This reverts commit f4e435e33afedd80a2629d34b322a287a7265363.
```
/merge
```
=> Revert "(maint) Redirect broken link (#27989)"

content/en/tracing/trace_collection/proxy_setup/httpd.md
* Headings should be h2s to show in ON THIS PAGE section.
```
/merge
```
=> Fix Apache Proxy Tracing Headings

content/en/dashboards/faq/historical-data.md
- Add new information to the Historical Data FAQ
- [DOCS-10272](https://datadoghq.atlassian.net/browse/DOCS-10272)
```
/merge
```
[DOCS-10272]: https://datadoghq.atlassian.net/browse/DOCS-10272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add information to historical data faq

config/_default/menus/main.en.yaml, content/en/service_management/case_management/notifications_integrations.md, content/en/service_management/case_management/view_and_manage/_index.md
- Move "View and Manage a Case" out from "Projects" to parent level
- Move "Create notifications and third party tickets" out from "Projects" to parent level
- Rename "Create notifications and third party tickets" to "Notifications and Integrations", added an alias
- Minor copy edit
```
/merge
```
=> Update order of Case management docs

content/en/real_user_monitoring/platform/connect_rum_and_traces.md
To be more accurate on the documentation regarding making preflight requests.
```
/merge
```
=> 👷 [RUM-8909] Rewording to be accurate on the documentation

content/en/tracing/trace_pipeline/ingestion_mechanisms.md
https://datadoghq.atlassian.net/browse/DOCS-10244
Updates out-of-date variable name.
```
/merge
```
=> DOCS-10244

content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
- Remove region restriction from PrivateLink support note
- Minor copy updates
```
/merge
```
=> (DOCS-10270) Remove PrivateLink region restriction

content/en/software_catalog/_index.md
https://datadoghq.atlassian.net/browse/DOCS-10290
Updates Getting Started links on Software Catalog landing page.
```
/merge
```
=> DOCS-10290

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-extension layer to version 73

layouts/shortcodes/latest-lambda-layer-version.html
Bumps layer versions
https://github.com/DataDog/datadog-lambda-java/releases/tag/v19
https://github.com/DataDog/datadog-lambda-extension/releases/tag/v73
```
/merge
```
=> Bump datadog-lambda-java and datadog-lambda-extension Lambda layer versions

layouts/shortcodes/observability_pipelines/processors/add_env_vars.en.md
Add allowlist info and env var.
```
/merge
```
=> [DOCS-10317] Add allowlist section to Add Env Var processor

content/en/database_monitoring/setup_mysql/_index.md
This PR updates DBM MariaDB supported version 11.1 to 11.4 (LTS). 
```
/merge
```
=> update mariadb 11.1 to 11.4 (LTS)

content/en/observability_pipelines/destinations/google_cloud_storage.md, layouts/shortcodes/observability_pipelines/configure_log_archive/google_cloud_storage/instructions.en.md
Revert instructions to what it was previously, which was correct.
```
/merge
```
=> Fix OP Google Cloud Storage instructions

content/en/tracing/guide/serverless_enable_aws_xray.md
This sentence is displayed as code, which is wrong.
This PR changes it to regular text format.
```
/merge
```
=> Fix format in serverless_enable_aws_xray.md

content/en/data_jobs/databricks.md
=> Fix broken repo link

content/en/integrations/guide/azure-programmatic-management.md
Update the type_handler_version parameter's value
```
/merge
```
=> (DOCS-9994) Update type_handler_version

layouts/shortcodes/latest-lambda-layer-version.html
=> Bump datadog-lambda-extension layer to version 74

content/en/security/code_security/troubleshooting/_index.md
Add a message on where diff-aware is available.
Please merge once approved
=> Add message on diff-aware

content/en/security/cloud_security_management/setup/agentless_scanning/compatibility.md
Fix the documentation stating that we do not support AWS CMK with Agentless while we do now.
```
/merge
```
=> [AGENTLESS] AWS CMKs are supported

content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/amazon_data_firehose.md, content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/amazon_s3.md, content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/kafka.md, content/en/observability_pipelines/set_up_pipelines/generate_metrics/amazon_data_firehose.md, content/en/observability_pipelines/set_up_pipelines/generate_metrics/amazon_s3.md, content/en/observability_pipelines/set_up_pipelines/generate_metrics/kafka.md, content/en/observability_pipelines/set_up_pipelines/log_enrichment/amazon_data_firehose.md, content/en/observability_pipelines/set_up_pipelines/log_enrichment/amazon_s3.md, content/en/observability_pipelines/set_up_pipelines/log_enrichment/kafka.md, content/en/observability_pipelines/set_up_pipelines/log_volume_control/amazon_data_firehose.md, content/en/observability_pipelines/set_up_pipelines/log_volume_control/amazon_s3.md, content/en/observability_pipelines/set_up_pipelines/log_volume_control/kafka.md, content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/amazon_data_firehose.md, content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/amazon_s3.md, content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/kafka.md, content/en/observability_pipelines/set_up_pipelines/split_logs/amazon_data_firehose.md, content/en/observability_pipelines/set_up_pipelines/split_logs/amazon_s3.md, content/en/observability_pipelines/set_up_pipelines/split_logs/kafka.md
Adds the same missing shortcode and text to 18 OP setup pages. Just checking one preview should be good enough.
```
/merge
```
=> Add missing shortcode and text

content/en/opentelemetry/instrument/_index.md
=> Small Edit to Supported Telemetry

content/en/cloud_cost_management/recommendations/_index.md
Updates the table of available cost recommendations with our gcp recs
```
/merge
```
=> Add first release of gcp recs to available recs

content/en/serverless/aws_lambda/metrics.md
Adds file descriptor and threads enhanced metrics for AWS Lambda.
```
/merge
```
=> Add new Lambda enhanced metrics

content/en/security/code_security/static_analysis/setup/_index.md
=> Update Static Code Analysis (SAST) Setup

content/ja/service_management/on-call/_index.md
=> Remove preview callout from Japanese docs

content/en/getting_started/devsecops/_index.md, content/es/getting_started/devsecops/_index.md, content/ja/getting_started/devsecops/_index.md, content/ko/getting_started/devsecops/_index.md, data/partials/home.es.yaml, data/partials/home.ja.yaml, data/partials/home.ko.yaml, data/partials/home.yaml, i18n/en.json, i18n/es.json, i18n/fr.json, i18n/ja.json, i18n/ko.json, layouts/shortcodes/translate.html
Updates the integration count to 850 on docs site
https://datadoghq.atlassian.net/browse/WEB-5935
https://docs-staging.datadoghq.com/brooklyne.finni/increment_integrations_count/integrations/
```
/merge
```
=> [WEB-5935]update integration count to 850

content/en/metrics/custom_metrics/historical_metrics.md
Restrict content to supported sites
```
/merge
```
=> (DOCS-10365) Add site restriction

content/en/dashboards/widgets/powerpack.md
Add a note that Powerpack layouts cannot be edited on timeboards
[DOCS-10358](https://datadoghq.atlassian.net/browse/DOCS-10358)
```
/merge
```
[DOCS-10358]: https://datadoghq.atlassian.net/browse/DOCS-10358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note about powerpack limitations on timeboards

content/en/metrics/custom_metrics/historical_metrics.md
Reverts DataDog/documentation#28170
=> Revert "(DOCS-10365) Add site restriction"

content/en/dashboards/template_variables.md
- Add note to reference historical data faq
- [DOCS-10367](https://datadoghq.atlassian.net/browse/DOCS-10367)
```
/merge
```
[DOCS-10367]: https://datadoghq.atlassian.net/browse/DOCS-10367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add note on historical data

content/en/data_jobs/_index.md
Add warning that DJM is not available yet in us1-fed DC.
Thanks !
```
/merge
```
=> Add warning that DJM is not available in us1-fed

content/en/containers/guide/container-discovery-management.md
- moved line about environment variable behavior to be more visible
- specified "container name"
```
/merge
```
=> DOCS-10372: update Container Discovery Management guide with small changes

content/en/all_guides.md
need to adjust format of shortcode for docs replatforming migration
should be no change on preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-all-guides/all_guides/
```
/merge
```
=> adjust shortcode formatting `/all_guides`

content/en/cloud_cost_management/budgets.md
=> Update to new nav

content/en/cloud_cost_management/custom.md, content/en/cloud_cost_management/saas_costs.md
=> Update other files

content/en/synthetics/guide/email-validation.md
=> [DOCS-10386] adding Gov callout

content/en/account_management/_index.md
escape non-html content 
should see `<Organization name>` in content
preview: should see https://docs-staging.datadoghq.com/stefon.simmons/patch-content-fix-accountmanagement/account_management
```
/merge
```
=> escape non-html content

content/en/serverless/azure_app_services/_index.md
A refresh. Function Apps has its own section (and, on Microsoft's end, is not really part of App Services at this point)
```
/merge
```
=> DOCS-10305 - Edits to Azure App Services index

content/en/metrics/custom_metrics/historical_metrics.md
Clarifies the metric type supported for historical metrics ingestion
```
/merge
```
=> (DOCS 10348) Clarify availability

content/en/mobile/_index.md
=> update mobile saml login to include default browser

content/en/cloud_cost_management/recommendations/_index.md
=> Update copy to include other 2 clouds

content/en/getting_started/synthetics/private_location.md
=> Fix Bolding in Getting Started with Private Locations

content/en/security/code_security/secret_scanning/_index.md
Add preview link for secret scanning.
Please merge one accepted.
=> Add Secret Scanning Preview

content/en/tracing/trace_collection/library_config/go.md
=> Fix Runtime Metrics Broken Link

content/en/synthetics/platform/private_locations/_index.md
In-app installation instructions are for Docker and Docker Compose (Docker Composer does not exist...yet!)
```
/merge
```
=> Composer --> Compose

content/en/security/suppressions.md
=> Adding ASM to the prod availability list

content/en/synthetics/api_tests/grpc_tests.md
The "Restrict access" section is an H3 across the rest of the Synthetic API Test pages, so I'm suggesting that we make this one consistent with the other pages too!
```
/merge
```
=> Make header H3

layouts/shortcodes/observability_pipelines/processors/remap_ocsf.md
Adds new OCSF mappings.
```
/merge
```
=> [DOCS-10395] Add 2.4 OCSF mappings

content/en/data_jobs/databricks.md
=> [DJM Databricks] Redirect users compute on shared policy to manual install

Makefile
=> [IXP-203] Update Makefile

content/en/account_management/audit_trail/_index.md
Add Cloud SIEM info and links in Audit Trail doc.
```
/merge
```
=> Add Cloud SIEM info to Audit Trail

content/en/opentelemetry/guide/migrate/migrate_operation_names.md
=> Add one line warning to OTLP operation name v2 migration instructions

content/en/security/_index.md
Adds a section on SDS in Security Overview.
```
/merge
```
=> [DOCS-10195] Add SDS section to Security Overview

content/en/logs/guide/azure-automated-log-forwarding.md
Adds instructions for uninstalling Azure Automated Log Forwarding.
```
/merge
```
=> [AZINTS-3245] Add Uninstall Instructions

content/en/agent/remote_config/_index.md
I was scrolling through this topic and noticed some things displaying a bit oddly, so I decided to fix them. No meaningful changes in here, just edits to whitespace, punctuation, and markdown.
```
/merge
```
=> Fix indentation and remove some hyphens on remote config doc

content/en/security/application_security/guide/standalone_application_security.md
Fixing the required python version for standalone ASM. Following from https://github.com/DataDog/documentation/pull/24644
```
/merge
```
=> fix(standalone): correct python version

content/en/cloud_cost_management/recommendations/_index.md
Fix the prerequisites for our gcp cloudsql recs
```
/merge
```
=> Update gcp cloudsql recommendation prerequisites

assets/scripts/components/integrations.js, layouts/shortcodes/integrations.html
Updates on-page integrations search logic to prioritize keyword matches when there is an exact phrase. Refactors integrations logic to improve performance.
https://datadoghq.atlassian.net/browse/WEB-6172
```
/merge
```
https://docs-staging.datadoghq.com/nsollecito/web-6172/integrations/
Compare filtering by keyword for multiple words with live site: "temporal cloud"
The appropriate tiles should appear first in the results; Also ensure prior changes to improve the filtering of "apache flink" for example still work as expected
=> [WEB-6172] Fix unexpected results for multi-word search phrases

content/en/synthetics/troubleshooting/_index.md
Update troubleshooting guide for private location IPv4 issues
=> Update troubleshooting guide for private location IPv4 issues

content/en/llm_observability/configuration/_index.md
This PR updates just one line on the configuration page to indicate the model we will be using to run evaluations. 
```
/merge
```
=> [MLOB-2424] Update Docs

content/en/security/code_security/iast/setup/_index.md
=> Update Runtime Code Analysis (IAST) Compatibility Requirements for .NET

content/en/tracing/trace_collection/runtime_config/_index.md
https://dd.slack.com/archives/C4WC8C39Q/p1742485297157529 This table is the only place where we use javascript instead of Node.js in the docs for APM
```
/merge
```
=> Change javascript to Node.js

content/en/security/code_security/iast/_index.md
=> Update Runtime Code Analysis (IAST) Overview Page

content/en/serverless/google_cloud_run/_index.md
A few sentences appear twice. This PR removes the first appearance.
```
/merge
```
=> Remove duplicate content in Google Cloud Run doc

package.json, typesense.config.json, yarn.lock
- Bumps to `typesense-sync` `v1.1.0`
- Defines a schema in the typesense config file
```
/merge
```
- Typesense job passed here: https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/858031304
- No search changes in preview: https://docs-staging.datadoghq.com/brian.deutsch/typesense-update/
=> Typesense updates

content/en/software_catalog/manage.md
Remove dupe image and update "this table" to be more descriptive. 
```
/merge
```
=> Remove dupe image from Software Catalog Manage page

content/en/tracing/trace_collection/compatibility/go.md
Fix a broken link for the mgo tracing.
_What_ Slack username? Do I have to Join the DataDog Slack to create a PR here?!
```
/merge
```
=> Fix links for mgo integration

content/en/observability_pipelines/_index.md, content/en/security/_index.md
- Add security and observability blog to the further reading
- Tuesday Tasks
```
/merge
```
=> Add security blog to further reading

content/en/tracing/trace_collection/custom_instrumentation/android/otel.md
https://datadoghq.atlassian.net/browse/DOCS-10337
Add missing parentheses
```
/merge
```
=> DOCS-10337

content/en/cloud_cost_management/anomalies.md
Coming from https://github.com/DataDog/documentation/pull/27775
```
/merge
```
=> [CCM] adding description to image / fixing image extension

content/en/error_tracking/explorer.md
Document the sorting options of the Error Tracking explorer.
```
/merge
```
=> [error-tracking] document sorting options in the explorer

content/en/database_monitoring/setup_mysql/aurora.md, content/en/database_monitoring/setup_mysql/azure.md, content/en/database_monitoring/setup_mysql/gcsql.md, content/en/database_monitoring/setup_mysql/rds.md, content/en/database_monitoring/setup_mysql/selfhosted.md, layouts/shortcodes/dbm-mysql-agent-config-examples.en.md
Add MySQL schema collection documentation. I've split the configuration and the granting portions to their respective sections of the mySQL docs.
```
/merge
```
=> MySQL Schema Collection Docs

content/en/logs/log_collection/_index.md
- Fix the logging endpoint for US1-FED
- [DOCS-10419](https://datadoghq.atlassian.net/browse/DOCS-10419)
```
/merge
```
[DOCS-10419]: …
=> Fix logging endpoints for US1-FED

content/en/tracing/metrics/metrics_namespace.md
- Customers are confused by older metrics we have to measure latency.
- This change deemphasizes the old options and more strongly recommends using latency distribution metrics.
- Note: Approved by PM offline.
```
/merge
```
=> Reorganize to prioritize latency metrics

content/en/getting_started/integrations/google_cloud.md
This PR adds a link to a Terraform module for managing the log forwarding infrastructure
```
/merge
```
=> [DOCS-10445] Add Terraform module link

content/en/security/code_security/static_analysis/setup/_index.md
Fixes broken image URLs in the static analysis docs.
```
/merge
```
Please wait for the preview before merging/reviewing!
=> Static Analysis - Fix image URL

content/en/continuous_delivery/features/code_changes_detection.md
Add dora-metrics extension reference in Changes Detection
```
/merge
```
=> Add dora-metrics extension reference in Changes Detection

content/en/security/cloud_security_management/guide/related-logs.md, layouts/shortcodes/related-logs-supported-resources.html
Uses a data file to populate the list of cloudtrail related log aws resources
```
/merge
```
See Prerequisites and list
https://docs-staging.datadoghq.com/david.jones/web-6080/security/cloud …
=> related logs from data

content/en/actions/private_actions/_index.md
- Add a note on requirement for private actions runner installation
- [DOCS-10442](https://datadoghq.atlassian.net/browse/DOCS-10442)
```
/merge
```
[DOCS-10442]: …
=> Add alert on private actions requirement

content/en/database_monitoring/setup_mysql/aurora.md, content/en/database_monitoring/setup_mysql/azure.md, content/en/database_monitoring/setup_mysql/gcsql.md, content/en/database_monitoring/setup_mysql/rds.md, content/en/database_monitoring/setup_mysql/selfhosted.md, content/en/database_monitoring/setup_mysql/troubleshooting.md
Adds documentation to enable collection of index metrics on mySQL. Previously, this information was only in https://docs.datadoghq.com/integrations/mysql/?tab=host#prepare-mysql, making it difficult to find. 
Added both to set up docs, and troubleshooting docs.  …
=> Add mySQL index metric privileges 

content/en/cloud_cost_management/recommendations/_index.md
Clarify recommendation dependencies / setup for Azure
Reviewing as draft within team before opening to documentation review
=> CCR add azure prerequisites and fix azure vm prereqs

content/en/account_management/saml/okta.md
Removing the '**' before  company ID.
```
/merge
```
=> Fixing typo in SAML setting in Okta

content/en/network_monitoring/cloud_network_monitoring/network_analytics.md
=> [DOCS-10223] adding more info to unresolved traffic

content/en/logs/log_configuration/logs_to_metrics.md, content/en/logs/log_configuration/pipelines.md, content/en/logs/log_configuration/processors.md, content/en/observability_pipelines/processors/_index.md, content/en/observability_pipelines/set_up_pipelines/_index.md, content/en/observability_pipelines/set_up_pipelines/generate_metrics/_index.md
- Add a reference link between Log Management and Observability Pipelines
- Requested by Logs team
```
/merge
```
=> Add alerts to reference between Logs and Observability Pipelines

content/en/actions/datastore/_index.md
Fixes naming inconsistency between https://app.datadoghq.com/actions/datastores and docs
```
/merge
```
=> [ACTDS-138] Rename Apps Datastore to Actions Datastore

content/fr/integrations/servicenow.md
The link has already been replaced in the other languages, so this bring the doc in line with the others
```
/merge
```
=> (maint) Update link

content/en/real_user_monitoring/guide/enable-rum-shopify-store.md
Unindexing this guide because there has been multiple user feedback about how it is outdated now that Liquid checkout is deprecated and Checkout Extensibility is mandatory. 
```
/merge
```
=> Unindex RUM Shopify guide

content/en/integrations/content_security_policy_logs.md
Per request from Group PM, adds a blog post to the integrations page.
```
/merge
```
=> Add Content Security Policy blog post to integrations

content/en/security/cloud_security_management/misconfigurations/compliance_rules.md
Fixes a broken link to a security rule that has been renamed. Related to https://github.com/DataDog/documentation/issues/28281
```
/merge
```
=> Update link to security rule

local/bin/py/build/configurations/pull_config.yaml, local/bin/py/build/configurations/pull_config_preview.yaml
Pull the CWS agent documentation from the 7.64.x branch now that this agent version has been released.
```
/merge
```
=> Pull CWS agent documentation from 7.64 release

layouts/shortcodes/observability_pipelines/log_source_configuration/syslog.en.md
This is workaround fix. For some reason, the usual `<` gets render into the HTML in doc.
```
/merge
```
=> [DOCS-10441] Fix code sample

content/en/network_monitoring/devices/supported_devices.md
Very very small update to fix a link.
```
/merge
```
=> Update filename to fix link

layouts/shortcodes/dbm-mysql-agent-config-examples.en.md
Clarify mySQL schema permissions, why we need them, point to mySQL documentation, and give even more nuanced permission options. 
```
/merge
```
=> Improve mySQL schema permission description

config/_default/menus/main.en.yaml, content/en/getting_started/security/_index.md, content/en/getting_started/security/application_security.md, content/en/getting_started/security/cloud_security_management.md, content/en/getting_started/security/cloud_siem.md
Phase 1:
- alphabetizing the list (with the exception of Learning Center and Support)
- moving all the Security Getting started pages under a new Security heading
```
/merge
```
=> [DOCS-8805] restructure of Getting started

content/en/llm_observability/setup/auto_instrumentation.md
Updates auto-instrumentation support with the LLM Observability Node.js SDK.
```
/merge
```
=> Update LLM Observability Node.js Auto-instrumentation

content/en/infrastructure/process/increase_process_retention.md, content/en/service_management/on-call/_index.md, content/en/synthetics/_index.md
Adding new links for Tuesday Tasks 🫡 
```
/merge
```
=> Add new further reading links from blog

content/en/dynamic_instrumentation/_index.md
https://datadoghq.atlassian.net/browse/DOCS-10387
```
/merge
```
=> DOCS-10387

content/en/llm_observability/ragas_evaluations.md
1. customizations link to header was broken
2. links to ragas docs should point to the version we support, not latest
1. customizations link to header was broken
2. links to ragas docs should point to the version we support, not latest …
=> [MLOB] fix ragas links

content/en/tracing/metrics/runtime_metrics/_index.md
=> Note that JMX metrics are  not supported in AWS Lambda environments

content/en/containers/amazon_ecs/_index.md
=> Update FIPS proxy version to 1.1.9

content/en/developers/integrations/agent_integration.md
Updates the Python version from 3.11 to 3.12 in the "Create an Agent Integration" page.
Added this page to our Python upgrade [runbook](https://datadoghq.atlassian.net/wiki/spaces/AI/pages/4268982429/Upgrading+Python+Runbook) so that we don't forget to update this. …
=> Update Python version in "Create an Agent Integration" page

content/en/infrastructure/containers/amazon_elastic_container_explorer.md
=> Mention DD_ECS_TASK_COLLECTION_ENABLED is enabled by default

content/en/continuous_integration/search/_index.md
[SDCI-657](https://datadoghq.atlassian.net/browse/SDCI-657)
Remove doc related to the unified span as we are going to remove it from the UI
[web-ui PR](https://github.com/DataDog/web-ui/pull/192858) removing the reference to this doc
DO NOT merge before the web-ui PR mentioned above
To have your …
=> [SDCI-657][ci-app] Remove unified span doc from CI doc page

content/en/actions/private_actions/private_action_credentials.md
=> [ACTP][documentation] Reorder par credentials tabs

content/en/observability_pipelines/destinations/google_cloud_storage.md, layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_google_cloud_storage.en.md
Adds an alert box that the GCS destination only supports ACL.
```
/merge
```
=> [DOCS-10423] Add alert box about Access Control Lists

.gitignore
Prevent Cursor config files from showing up in git changes.
```
/merge
```
=> Ignore Cursor config files

config/_default/menus/main.en.yaml
Secrets Scanning → Secret Scanning
=> left nav Secrets Scanning → Secret Scanning

layouts/shortcodes/csm-setup-azure.en.md
To make full use of CIEM detections for Cloud Security, specific permissions should be enabled for the Microsoft Graph API. This adds a link from the Cloud Security docs to an existing docs page with more information about setting up those permissions.
https://docs-staging.datadoghq.com/nick.allen/link-to-microsoft-graph-api-perms/security/cloud_security_management/setup/cloud_integrations/?tab=azure
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your …
=> Link to more information about Microsoft Graph API permissions

layouts/shortcodes/latest-lambda-layer-version.html
Bump lambda layer version for dd-trace-dotnet to v20
```
/merge
```
=> Bump dd-trace-dotnet-aws-lambda-layer verison to v20

content/en/getting_started/security/_index.md
Fixes the index page to re-name the title appropriately, re-order links, and add a missing Code Security link to the Getting Started - Security - Index page.
```
/merge
```
=> Update Getting Started with Security

snippets/markdown.json
This adds a specific gov-region snippet that integrates the region-param within the snippet.
```
/merge
```
=> adding Gov snippet
