DataDog/documentation

- content/en/monitors/notify/variables.md
The is_exact_match considers only the numeric values when used with numbers. Added a description that clarifies this scenario.
> Update is_match and is_exact_match description

- config/_default/menus/main.en.yaml
- content/en/opentelemetry/collector_exporter/log_collection.md
- content/en/opentelemetry/integrations/_index.md
* Move Log Collection out of Integrations and under Collector Config.
* Remove mention on Integrations page.
```
/merge
```
> Move Log Collection out of OTel Integrations

- static/resources/yaml/datadog-agent-aks.yaml
- static/resources/yaml/datadog-agent-all-features.yaml
- static/resources/yaml/datadog-agent-apm.yaml
- static/resources/yaml/datadog-agent-logs-apm.yaml
- static/resources/yaml/datadog-agent-logs.yaml
- static/resources/yaml/datadog-agent-npm.yaml
- static/resources/yaml/datadog-agent-vanilla.yaml
- static/resources/yaml/datadog-agent-windows-all-features.yaml
- static/resources/yaml/datadog-agent-windows-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs.yaml
- static/resources/yaml/datadog-agent-windows-vanilla.yaml
Re-generate the sample kubernetes manifests by executing the `generate.sh` script of the `static/resources/yaml` directory  in order to update the datadog agent version to `7.59.0`.
```
/merge
```
> Re-generate the k8s sample manifests with Helm chart 3.79.1

- content/en/synthetics/platform/private_locations/configuration.md
Updating Windows command line instruction to correctly point to the .exe for the config file.
Updating Windows command line instruction to correctly point to the .exe for the config file.
```
/merge
```
> Updating Windows command line instruction

- .gitlab-ci.yml
uses update pa11y image. [more info here](https://github.com/DataDog/websites-images/pull/241)
motivation: https://datadoghq.atlassian.net/browse/WEB-5575
preview: 
1. docs: https://docs-staging.datadoghq.com/stefon.simmons/update-pa11y-image/
- no visual change
1. build (`run_pa11y` manual execution): 
- run_pa11y should succeed  
- https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/705652810
```
/merge
```
> update pa11y image ref

- content/en/containers/kubernetes/tag.md
This PR updates the kubernetes tag documentation page to include kubernetes resource labels and annotations as tags.
This is a new feature that was introduced in 7.58.0. ([feature PR](https://github.com/DataDog/datadog-agent/pull/27369))
Should be merged when:
- The operator v1.10.0 is released
> [CONTP-377] add docs for kubernetes resources labels/annotations as tags

- content/en/security/threats/workload_security_rules/custom_rules.md
This PR fixes the instruction to deploy manually the CWS default policy.
```
/merge
```
> [CWS] fix manual default policy deployment

- content/en/dashboards/guide/is-read-only-deprecation.md
We're extending the shutdown date for this API attribute to Friday, December 13th. 
I'd like to merge this on Friday, November 15th to align with the comms that'll be sent out to customers. 
```
/merge
```
> Extend Dashboards is_read_only deprecation date

- content/en/tests/setup/junit_xml.md
- content/en/tests/setup/python.md
- content/en/tests/setup/ruby.md
- content/en/tests/setup/swift.md
> Bryan.lee/patch 4

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-kinesis-firehose-destination.md
Add instructions on how to authenticate with Secrets Manger.
AWS released support of Amazon Data Firehose with AWS Secrets Manager. 
https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-data-firehose-integration-secrets-manager/
Some customers don't know how to do this. See the slack channel.
https://dd.slack.com/archives/CMD6QSA3D/p1731635858928549
AWS doc on how to do this. I have verified it in our sandbox.
https://docs.aws.amazon.com/firehose/latest/dev/secrets-manager-whats-secret.html
```
/merge
```
> Add support for secret manager

- content/en/database_monitoring/setup_mysql/rds.md
the helm yaml config should be mysql.yaml instead of postgres.yaml for the setup_mysql doc
```
/merge
```
> docs: fix kubernetes config file name

- content/en/developers/dogstatsd/_index.md
The "[Install the DogStatsD client](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent&code-lang=php#install-the-dogstatsd-client)" section refers to an old version of the `datadog/php-datadogstatsd` client library.
I updated the snippet to use the latest minor version (1.6.*) of the library.
```
/merge
```
> Update php-datadogstatsd to the latest minor version

- content/en/tracing/trace_collection/compatibility/nodejs.md
* Express 5 was released, which we do not support ([raised by support team](https://datadoghq.atlassian.net/browse/DOCS-9421)).
* This makes the current entry >4 invalid.
* Change the cell to say `4.x` to encompass all 4.0 and all minor versions.
```
/merge
```
> Express 5 is not supported for Node.js

- content/en/tracing/guide/tutorial-enable-java-host.md
The doc uses the old unversioned link.
>
install_script.sh is deprecated. Please use one of
* https://s3.amazonaws.com/dd-agent/scripts/install_script_agent6.sh to install Agent 6
* https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh to install Agent 7
```
/merge
```
> Update install link in tutorial-enable-java-host.md

- content/en/agent/configuration/network.md
As of this writing, Dogstatsd does not support dualstack e.g. listen on multiple IP addresses returned by `localhost`.
Golang library will prefer IPv4 `localhost` --> `127.0.0.1` and will only open the port on that IPv4 address.
Traffic bound for `::1` or `fe80::1` will not reach Dogstatsd and will be misconstrued as missing metrics/data
> Dogstatsd listens on IPv4 only default

- .github/workflows/synthetics.yml
- .gitlab-ci.yml
- repository.datadog.yml
- Ignores the synthetic preview job when it comes to the merge queue
- This job is a bit flaky due to the fluctuating build times, this will be moved into the mq worker in the near future, but this should alleviate some of the friction around mq and the job failing due to timeout for now
```
/merge
```
> Ignore syntehtics for mq

- layouts/shortcodes/csm-agentless-exclude-resources.en.md
Fix the tag to exclude resources from being scanned by the Agentless scanning.
The tag was correct prior to #24801 
```
/merge
```
> Fix Agentless resources filtering tag

- layouts/shortcodes/beta-callout-private.html
- layouts/shortcodes/beta-callout.html
- layouts/shortcodes/callout.html
All the times we use `{{< callout ...>}}` or `{{< beta-callout ...>}}` or `{{< beta-callout-private ...>}}`, the heading defaults to "Join the Beta" or "Join the Private Beta". This updates that messaging to "Join the Preview".
> update beta -> preview messaging in shortcodes

- content/en/real_user_monitoring/error_tracking/mobile/ios.md
Per user feedback, removed mentions of bitcode from the Error Tracking setup page for iOS because of an Apple update that made it irrelevant.
```
/merge
```
> [DOCS-9303] Remove bitcode mention from iOS Error Tracking

- content/en/serverless/step_functions/installation.md
- content/en/serverless/step_functions/merge-step-functions-lambda.md
> DOCS-9376 - update step functions install

- content/en/tracing/trace_collection/compatibility/java.md
The disabled by default integration list was inaccurate - this makes it complete.
This was populated using this [Github search](https://github.com/search?q=repo%3ADataDog%2Fdd-trace-java+++%40Override+++public+boolean+defaultEnabled%28%29+%7B+++++return+false%3B+++%7D&type=code&p=2)
Note that this does not include [Servlet](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/servlet/src/main/java/datadog/trace/instrumentation/servlet/http/HttpServletInstrumentation.java) since I was suspicious about it actually being disabled
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR …
> Update Java's disabled by default integrations

- config/_default/menus/main.en.yaml
Domain Allowlist is going GA. Its formerly private docs need to be made public and discoverable.
https://datadoghq.atlassian.net/browse/DOCS-9499
Follow-on to https://github.com/DataDog/documentation/pull/26346, where I forgot to do this step.
```
/merge
```
> Add Domain Allowlist to the left navigation

- content/en/continuous_integration/pipelines/github.md
Change links for two terms.
```
/merge
```
> docs: fix links for terms

- content/en/serverless/step_functions/merge-step-functions-lambda.md
The 2 href links in the introduction of [this page](https://docs.datadoghq.com/serverless/step_functions/merge-step-functions-lambda/) are inverted.
This PR fixes the issue.
> Fix mixed links in merge-step-functions-lambda.md

- config/_default/menus/main.en.yaml
- content/en/service_catalog/manage.md
- content/en/service_catalog/scorecards/_index.md
- content/en/service_catalog/scorecards/custom_rules.md
- content/en/service_catalog/scorecards/scorecard_configuration.md
- content/en/service_catalog/scorecards/using_scorecards.md
- content/en/service_catalog/service_definitions/_index.md
- content/en/service_catalog/service_definitions/v2-0.md
- content/en/service_catalog/service_definitions/v2-1.md
- content/en/service_catalog/service_definitions/v2-2.md
- content/en/service_catalog/service_definitions/v3-0.md
Renames Service Catalog headings. Requested by PM.
```
/merge
```
> DOCS-9556: Rename Service Catalog headings

- content/en/cloud_cost_management/container_cost_allocation.md
Document `allocated_spend_type` for data transfer. Also, clarify allocation strategy for data transfer.
```
/merge
```
> document allocated_spend_type for data transfer

- content/en/real_user_monitoring/browser/setup/server.md
- Adds steps for how to manually instrument RUM for nginx web servers
```
/merge
```
Needs PM/eng review before merging.
> [DOCS-9537] Add manual steps for nginx browser RUM

- content/en/security/threats/supported_linux_distributions.md
DOCS-9375
List the Linux kernel versions supported by the eBPF-less solution (ptrace-based Datadog Agent).
> Linux kernel versions supported by the eBPF-less solution

- content/en/getting_started/tagging/assigning_tags.md
Quick fix. Update the `DD_TAGS` environment variable syntax to use space separated not "comma and space" separated. The comma space actually puts that comma in the tag like below. 
```
$ agent status
...
host tags:
key1:value1,
key2:value2
```
Our other docs say space separated so we have consistency there. Ex: https://docs.datadoghq.com/containers/docker/?tab=standard#global-options
```
/merge
```
> Update DD_TAGS to space separated

- layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md
SQLServer schema collection doesn't work in the current agent for sqlserver less than 2017. We are putting out a fix for this which will come out in a future agent release.
```
/merge
```
> Add SQLServer version constraint to schema collection docs

- content/en/logs/explorer/advanced_search.md
> Remove "Preview" label from Log Subqueries docs

- content/en/opentelemetry/agent/install_agent_with_collector.md
- content/en/opentelemetry/agent/migration.md
Update the image tag for the `otel-agent` to the latest `7.59.0-v1.1.0-ot-beta-jmx` version.
```
/merge
```
The following docs are private -- the Datadog Agent with embedded OpenTelemetry Collector is in Preview (fka Private Beta).
> [Preview] Bump image tag for the Agent with embedded OTel collector

- content/en/service_catalog/service_definitions/_index.md
Adding Limited Availability Label to YAML extensions until giving pending commercialization discussions.
Adding Limited Availability Label to YAML extensions until giving pending commercialization discussions.
```
/merge
```
> Add Limited Availability Label to YAML Extensions

- content/en/continuous_testing/troubleshooting.md
Making this docs change so that users are aware that CI failed runs don't factor into a synthetics test's monitor evaluation.
```
/merge
```
> Add a note on CI runs not triggering s8s monitors

- layouts/shortcodes/ci-itr-activation-instructions.en.md
- layouts/shortcodes/ci-itr-activation-instructions.fr.md
- layouts/shortcodes/ci-itr-activation-instructions.ja.md
- layouts/shortcodes/ci-itr-activation-instructions.ko.md
Test impact analysis docs still mentioned Intelligent Test Runner in a couple of places.
> fix test impact analysis activation instructions - still referred to Intelligent Test Runner

- content/en/integrations/guide/amazon-eks-audit-logs.md
Index should be `kubernetes.audit`, not `kubernetes.aduit`
> Fix typo in kubernetes audit index for EKS

- content/en/database_monitoring/setup_mongodb/mongodbatlas.md
This PR adds additional clarifications to the MongoDB Atlas setup docs where customer needs to use network utility command tools like `dig` or `nslookup` to resolve the SRV connection string.
```
/merge
```
> [dbm] clarify mongodb atlas setup with using dig to resolve SRV

- content/en/security/cloud_security_management/setup/without_infrastructure_monitoring.md
This is a new PR, replicating changes already approved in https://github.com/DataDog/documentation/pull/26466 - just with a branch name without a typo in it, so our flows work 😬
```
/merge
```
> CSM without infra monitoring edits - now with fixed branch name!

- layouts/shortcodes/integrations.html
We are filtering integrations on `custom_kind` which in some cases is being translated on ja pages and causing them to not appear. This PR updates the filtering to go based off the directory path e.g we want `/integrations/` but not `/integrations/guides` etc.
```
/merge
```
Something like aws rds integration should appear 
https://docs-staging.datadoghq.com/david.jones/int-ja-kinds/ja/integrations/?q=rds
> DOCS-9529 - replace filter on custom kind with dir path

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/go.md
Removes the last occurrences of `dd:ignore` that were left behind, when the current form is `orchestrion:ignore`.
> fix: remove leftover occurrences of dd:ignore (plus misc. tweaks)

- content/en/service_catalog/customize/import_entries_backstage.md
I shouted at computers for a solid hour after copy/pasting the pagerduty annotation names from these docs to my backstage yaml failed to appease the Datadog service catalog import gods. Hopefully less computers will be verbally abused as a result of this contribution.
> Fix 'pagerduty' typo in import_entries_backstage.md

- content/en/tracing/trace_collection/library_config/go.md
To prevent losing data in case of a SIGTERM it's useful to explicitly stop the tracer so it flushes any outstanding data before the program exits.
```
/merge
```
> Add handling SIGTERM to go tracer example (APMSP-1534)

- content/en/tracing/services/inferred_services.md
> [Service Representation] Document precedence order of peer attributes

- content/en/infrastructure/containers/orchestrator_explorer.md
Found typo while reading doc
```
/merge
```
> fix horizontalpodautoscalers acronym in Orchestrator Explorer documentation

- content/en/containers/amazon_ecs/_index.md
- content/en/integrations/rsyslog.md
- content/en/logs/_index.md
- content/en/network_monitoring/performance/_index.md
- content/en/tracing/trace_collection/automatic_instrumentation/_index.md
See https://datadoghq.atlassian.net/browse/DOCS-9452 - adding Architecture Center links into the docs.
```
/merge
```
> [Documentation repo] Add Architecture Center links to docs pages

- config/_default/menus/main.en.yaml
- content/en/opentelemetry/guide/_index.md
- content/en/opentelemetry/guide/combining_otel_and_datadog_metrics.md
Please see https://datadoghq.atlassian.net/browse/DOCS-9592 - we got a request to make this page only accessible if customers have the direct link. Changes I made:
- Removed sidebar link
- Removed link from OTel guides page
- Added parameter to hide page from search
```
/merge
```
> Remove OTel/DD Metrics page links and search

- content/en/agent/guide/azure-private-link.md
Add explicit table entry for OTel Collector with Datadog Exporter logs endpoint (not clear otherwise which logs endpoint to use)
```
/merge
```
> Add OTel Collector Logs endpoint for private link

- content/en/synthetics/troubleshooting/_index.md
Following customer cases, we're updating the documentation to include a mention on how to debug the mobile recorder when encountering errors (due to security checks)
> Include mobile s8s troubleshooting

- config/_default/menus/main.en.yaml
- content/en/security/cloud_siem/entities_and_risk_scoring.md
Fixes a broken image link in the Cloud SIEM docs. Also updates the left nav menu to match the article title. Requested by PM.
```
/merge
```
> Fix image link in Cloud SIEM docs

- assets/scripts/components/dd-browser-logs-rum.js
- assets/scripts/components/global-modals.js
Add dd-device-id and dd-session-id to signup URL to improve tracking attribution
https://datadoghq.atlassian.net/browse/WEB-5641
```
/merge
```
https://docs-staging.datadoghq.com/ccole/signup-utm-device-session-id/
1. Click on any free trial CTA
2. Inspect the iframe URL
You should see a new query params appended e.g. `&dd-session-id=XXX&dd-device-id=XXX`
> Add RUM session ID for signup tracking

- content/en/profiler/enabling/ruby.md
This PR documents the setting introduced in version 2.4.0 of the Datadog Ruby library (https://github.com/DataDog/dd-trace-rb/pull/3984) to have the Ruby profiler directly read from the opentelemetry context.
This allows customers that want to use the opentelemetry Ruby library together with profiling to get the full profiler feature set.
(I've also gone ahead and did some small tweaks to the text: Suggest using the latest version in the config example; Suggest using Ruby 3.1+ in the requirements).
Ready to go asap :)
N/A
> [NO-TICKET] Document Ruby profiler setting for reading from opentelemetry context

- content/en/metrics/metrics-without-limits.md
This came up in a [support ticket](https://datadoghq.atlassian.net/browse/METS-6039) with a customer who we found wasn't able to manage tags for their metrics because they were submitted without a data type. For reference there's [this bit in our front-end code](https://github.com/DataDog/web-ui/blob/16e9d41475877cb04ef704b183b65d8b3e5119af/javascript/datadog/metrics/components/MetricsSummary/ManageTagsModal/ManageTagsButton.tsx#L83-L86) that enforces this.
> Add note for required detail for tag management

- content/en/security/application_security/threats/setup/single_step/_index.md
- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
- content/en/tracing/trace_collection/library_injection_local.md
Remove Ruby from the language list installed by default for SSI
Previously, in https://github.com/DataDog/documentation/pull/26269, I removed the `DD_APM_INSTRUMENTATION_LIBRARIES` env var when it wasn't required. 
Because no `DD_APM_INSTRUMENTATION_LIBRARIES` means "install java, js, python, ruby and dotnet".
However, we don't want ruby to be installed anymore by default, so we must restore the `DD_APM_INSTRUMENTATION_LIBRARIES` env var with just java, js, python and dotnet set.
```
/merge
```
> Remove Ruby from the language list installed by default for SSI

- .gitlab-ci.yml
The no translate job is failing on missing six module, resolve by installing manually for now
```
/merge
```
> Fix failing no_translate job

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
Removes the recommendation about using `-musl` tags for .NET SSI tags - this isn't required with the latest versions of the .NET SSI images.
```
/merge
```
> [.NET SSI] Don't recommend using `-musl` images for SSI

- content/en/profiler/connect_traces_and_profiles.md
Removes references to the "Breakdown" or "Code Hotspots" feature from the docs since it's no longer present in the product.
```
/merge
```
> [PROF] Remove references to "Breakdown" feature

- content/en/profiler/enabling/ruby.md
- content/en/profiler/enabling/supported_versions.md
- content/en/profiler/profile_types.md
This PR adds the Ruby GVL profiling feature to the documentation. This feature was introduced in https://github.com/DataDog/dd-trace-rb/pull/3929 and mentioned in the 2.4.0 release notes https://github.com/DataDog/dd-trace-rb/releases/tag/v2.4.0 but we had not yet updated the docs to mention it.
N/A
> [NO-TICKET] Add Ruby GVL profiling to documentation

- content/en/security/guide/aws_fargate_config_guide.md
By default, the CWS/CSM threats agent does not send events to logs anymore but to a specific track called agent events with a separate explorer and UI page. This PR fixes the documentation to not mention logs anymore, but directly the agent events (and related links).
```
/merge
```
> [CWS] remove usage of logs in the fargate setup docs and replace with agent events

- content/en/logs/log_configuration/pipelines.md
- Add clarification note on adding scoped permissions to pipelines
- [DOCS-9351](https://datadoghq.atlassian.net/browse/DOCS-9351)
```
/merge
```
[DOCS-9351]: https://datadoghq.atlassian.net/browse/DOCS-9351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add clarification on log permissions scoped to pipelines

- content/es/real_user_monitoring/mobile_and_tv_monitoring/setup/android.md
- Undoes Spanish translations for code snippets on the Android Setup page, as they would not work
```
/merge
```
> [DOCS-9671] Undo translation of RUM code snippets to Spanish

- assets/scripts/components/dd-browser-logs-rum.js
https://datadoghq.atlassian.net/browse/WEB-5663
Updates browser RUM configuration for site:
- add `defaultPrivacyLevel` set to `mask-user-input` to match other DD websites
- update config based on being version 5+
- update `enableExperimentalFeatures` to be `zero_lcp_telemetry` to match corpsite (remove no longer applicable `clickmap`
- remove `trackFrustrations`, which is now handled by `trackUserInteractions`
- add `trackResources` and `trackLongTasks` (match corpsite) 
Preview: https://docs-staging.datadoghq.com/davidweid/update-browser-rum/
Example:
- [Now has text visible](https://dd-corpsite.datadoghq.com/rum/replay/sessions/a4ae13b4-b35e-47fa-b080-1fccd8035a54?applicationId=3493b4e7-ab12-4852-8836-ba96af7bc745&seed=5d9ca422-baf2-4e56-86fd-2f4aebd47bdb&ts=1733854148363) vs [didn't …
> [WEB-5663] Update RUM configuration privacy level

- content/en/service_management/incident_management/guides/statuspage.md
The Incident App team received a customer support inquiry about the Statuspage integration not displaying on an incident for some of the users in an org. After closer inspection, it was was discovered that those users did not have the Integrations Read permission. This isn't explicitly mentioned in the public docs, so adding it (along with Incidents Write) to make onboarding easier for orgs that decide to use this integration.
```
/merge
```
> Update Statuspage integration docs to explicitly list required permissions

- content/en/opentelemetry/agent/agent_with_custom_components.md
The PR fixes BYOC instructions for `otel-agent`: we should use fixed `7.59.x` version for the `manifest.yaml` file, otherwise customers will get version mismatch error (`0.115` version in the manifest file in the `main` branch; `0.104` is the OCB version that is embedded in the Agent image).
```
/merge
```
> Fix otel-agent BYOC flow docs

- content/en/security/cloud_security_management/setup/agent/kubernetes.md
DOCS-9687.
Prerequisites was "Datadog Agent version 7.46 or later." but we are updating it to advise the user to use the latest version with links to docs and UI.
> revise Agent info in Prerequisites

- .github/workflows/approved_status.yml
- Changes use of action `tibdex/github-app-token` to official GitHub one in workflows
> ci(workflows): use official GitHub action for token generation

- content/en/security/application_security/threats/setup/threat_detection/_index.md
Eng Mgr asked for a redirect for a URL in a support request. A lot of files in this section have been moved, so if this URL has been around awhile a redirect should probably be added to the correct target topic.
Tested redirect locally. Worked fine.
> adding redirect to ASM Threats

- .github/workflows/approved_status.yml
- Fixes use of `create-github-app-token` action with correct field name
> ci(workflows): fix use of create-github-app-token

- content/en/logs/log_configuration/archives.md
- As part of the FedRamp High program, we want to document that FIPS endpoints for uploading to customer owned S3 buckets cannot be used when the S3 bucket name contains a dot. This is because of a limitation on the AWS side.
- Relevant `logs-backend` PR - https://github.com/DataDog/logs-backend/pull/86237
- Wording was stamped by Camille Dollé (Logs IO Manager) and Karim Rafoul (TPM for Logs) and Pranay Kamat (PM Director for Logs).
- https://datadoghq.atlassian.net/browse/LOGSI-159
```
/merge
```
> Document FIPS limitation for buckets with dot

- content/en/agent/troubleshooting/permissions.md
This PR updates the `permissions.md` file to:
1. Add `sudo` to the command requiring elevated privileges.
2. Standardize the syntax structure of the commands for consistency with other examples (e.g., line 47).
The motivation is to improve consistency and clarity in the documentation, ensuring that users can follow the commands easily and without confusion.
```
/merge
```
I closed the previously approved PR and reopened it to align the branch name. #26644
> Update chown command on permissions.md

- content/en/real_user_monitoring/session_replay/browser/privacy_options.md
Clarifies the default privacy setting for browser session replay
```
/merge
```
> Clarify browser session replay privacy default setting

- content/en/real_user_monitoring/session_replay/browser/privacy_options.md
This is a tiny PR that moves the note higher to the more relevant section.
```
/merge
```
> Move note about default Session Replay privacy setting higher

- content/en/cloud_cost_management/google_cloud.md
Adding context on the `gcp.cost.ondemand` metric, which we have had for some time.
```
/merge
```
> Add on demand metric for GCP

- content/en/logs/workspaces/sql_reference.md
- Add a return type column
- Move the examples out to a collapse content
```
/merge
```
> Add return type to workspace sql reference

- content/en/logs/guide/how-to-set-up-only-logs.md
Added a small change to the docs to include to disable container collection.
This is needed to completely disable the process agent so that container collection gets disabled completely. Just setting `datadog.processAgent.enabled` to `false` does not disable container collection on the Live Containers View.
```
/merge
```
> Include to disable container collection

- README.md
the previous link went to page on finding the Profile ID, which is not the Slack username needed.
> Update README.md with link to finding Slack username 

- content/en/database_monitoring/setup_postgres/troubleshooting.md
Clarifies that `schema_with_pg_stat_statements` is not an actual schema that exists, and is a placeholder/variable that needs to be replaced
```
/merge
```
> Clarify schema_with_pg_stat_statements in troubleshooting.md

- content/en/synthetics/api_tests/http_tests.md
This change updates our docs so customers have further context on AUTH errors and why the retry mechanism is disabled for these specific errors. 
```
/merge
```
> Update s8s API error docs to include AUTH errors

- content/en/opentelemetry/agent/install_agent_with_collector.md
When site / api key are unset, converged agent will source these params from core agent config.
See converter README: https://github.com/DataDog/datadog-agent/tree/main/comp/otelcol/converter.
```
/merge
```
> Mention converged agent sources API key / site from core agent config

- content/en/tracing/trace_collection/compatibility/java.md
- Native images do not support UDS.
- If a user has these configured, this leads to an error.
- Workaround is to explicitly configure the ports.
```
/merge
```
> Add native image troubleshooting for UDS error

- content/en/llm_observability/setup/sdk/nodejs.md
- content/en/llm_observability/setup/sdk/python.md
This PR updates the LLM Observability SDK setup documentation, specifically related to `DD_API_KEY`. It is still marked as a required field/configuration but currently it is only required if the user is in agentless mode (i.e. without the Datadog agent).
This PR also makes minor whitespace removal in the SDK setup files.
```
/merge
```
> [MLOB] Update api key documentation for agentless mode

- content/en/getting_started/synthetics/private_location.md
- content/en/synthetics/platform/private_locations/_index.md
- content/es/synthetics/platform/private_locations/_index.md
- content/ja/getting_started/synthetics/private_location.md
- local/bin/py/version_getter.py
Windows PL moved from `staging` bucket to `prod`.
As the new bucket has no permission to list the content, the bump script uses `installers.json` file to identify the latest version.
```
/merge
```
> [SYNTH-16307] move windows-pl to prod bucket

- .github/workflows/vale_linter.yml
Large JSON files are causing the Vale action to time out.
```
/merge
```
> (maint) Vale should ignore JSON

- content/en/synthetics/platform/settings/_index.md
Update doc to mention that MFA GV can currently only be used with SHA1 algorithm and not SHA256.
> MFG GV hashing algorithm

- content/en/security/application_security/software_composition_analysis/setup/_index.md
two instances of "Settings" do not include links to the UI even though the reference link is the topic MD.
Adding the link references in this commit.
> fix missing links in SCA setup

- content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
Add documentation for Android Session Replay Jetpack Compose Setup
```
/merge
```
> RUM-7315: Add documentation for Android Session Replay Jetpack Compose Setup

- content/en/synthetics/platform/private_locations/configuration.md
Kubernetes were not mentioned at all at Private Location Configuaration page, but it is possible to use K8 and customers often ask about this on Technical Support
https://github.com/DataDog/helm-charts/tree/main/charts/synthetics-private-location
Page:
https://docs.datadoghq.com/synthetics/platform/private_locations/configuration/?tab=docker#customize-your-private-location 
```
/merge
```
> Add K8 tab to PL Config page

- content/en/continuous_delivery/deployments/argocd.md
Two main things:
1. Improves the current Argo CD documentation by merging the three steps to create the setup into a single one.
2. Add a section to mention how to improve the reported Argo CD duration by taking resources start up into account.
```
/merge
```
> Add PostSync Hook option to change Argo CD duration reported

- content/en/serverless/guide/serverless_warnings.md
Originally said "older than 2 hours", but this can vary by user's settings. Updated to say "iterator age was too high"
```
/merge
```
> Fix Serverless Warning Iterator age

- content/en/serverless/step_functions/installation.md
To enable tracing at forwarder level, I think we should set the `DD_STEP_FUNCTIONS_TRACE_ENABLED ` environment variable, not `DdStepFunctionsTraceEnabled`, because I see some forwarder is using the former and the former appears a lot in the codebase.
Need someone on Cloud Tracing team to confirm this. cc @avedmala 
```
/merge
```
> Fix Step Function installation doc

- content/en/serverless/aws_lambda/distributed_tracing.md
We just added support for Span Auto Linking on Node.js. This updates the documentation to list the supported Node.js versions.
```
/merge
```
> Add Node.js Supported Versions to Serverless Span Auto Linking Docs

- content/en/tracing/guide/ignoring_apm_resources.md
- Docs are unclear how to format `DD_APM_IGNORE_RESOURCES` with multiple values.
- Added a "Using `DD_APM_IGNORE_RESOURCES`" example.
- Added a note clarifying that the variable takes a comma-separate list of strings.
Template:
https://github.com/DataDog/datadog-agent/blob/aa3b2b0448f8555c4ed54cba4e1f730ab3d09fcd/pkg/config/config_template.yaml#L1289
```
/merge
```
> Show DD_APM_IGNORE_RESOURCES example with comma separated list.

- content/en/error_tracking/troubleshooting.md
- content/en/real_user_monitoring/browser/collecting_browser_errors.md
Now that we're fingerprinting console errors we should remove this text from our docs
```
/merge
```
> update docs removing the exception to console errors

- content/en/monitors/guide/troubleshooting-monitor-alerts.md
- content/en/monitors/types/metric.md
Mentions that `N/A` groups are not included in monitors. It's currently a feature request. 
https://datadoghq.atlassian.net/browse/FRMNTS-3812
example link 1: [Troubleshooting Monitor Alerts](https://docs-staging.datadoghq.com/dan.chiniara/add-N/A-groups/monitors/guide/troubleshooting-monitor-alerts/#verify-the-presence-of-data)
example link 2: [Metric Monitors](https://docs-staging.datadoghq.com/dan.chiniara/add-N/A-groups/monitors/types/metric/?tab=threshold#define-the-metric)
> dan.chiniara/add N/A groups explainer to "Verify the presence of data" and "Define the metric"

- content/en/service_management/on-call/schedules.md
Extends documentation for On-Call schedules. In particular, layer end times as well as how to export on-call shifts into 3rd party calendars.
```
/merge
```
> On-Call schedules end-time and export

- content/en/real_user_monitoring/mobile_and_tv_monitoring/android/error_tracking.md
Small improvement for Android deobfuscation docs: added some clarifications and change language for the code snippets from `groovy` to `kotlin`.
```
/merge
```
> RUM-4007: Improve Android deobfuscation docs

- content/en/containers/cluster_agent/admission_controller.md
- content/en/containers/guide/_index.md
- content/en/containers/guide/cluster_agent_disable_admission_controller.md
Adds a Container Guide on how to properly disable the Cluster Agent Admission Controllers.
```
/merge
```
> feat(admission): add instruction to remove Datadog Admission Controllers

- content/en/opentelemetry/otlp_logs.md
- Content is undefined for AP1 and Gov endpoints.
- This is because the site unsupported.
- To fix this, I'm wrapping all of the config content to prevent it from displaying at all for unsupported sites.
```
/merge
```
> Datadog OTLP Logs Intake Endpoint: Hide Config Content for Unsupported Sites

- content/en/dynamic_instrumentation/enabling/_index.md
- content/en/dynamic_instrumentation/enabling/dotnet.md
- content/en/dynamic_instrumentation/enabling/java.md
- content/en/dynamic_instrumentation/enabling/php.md
- content/en/dynamic_instrumentation/enabling/python.md
- content/en/dynamic_instrumentation/enabling/ruby.md
- layouts/partials/dynamic_instrumentation/dynamic-instrumentation-languages.html
Adds Ruby to the dynamic instrumentation languages.
```
/merge
```
> DEBUG-2334 Ruby DI documentation page

- snippets/markdown.json
- Tooltips missing from our snippets.
- Added choices to collapse-content entry.
- Added new expanded option to collapse-content.
To test this, you would have to pull down the branch locally and try to add the snippets to a markdown file with `;;tooltip...`.
```
/merge
```
> [Q4 Docs Hackathon] Add Tooltip Entries to VSCode Snippets

- content/en/synthetics/platform/settings/_index.md
Remediation for [VULN-7734](https://datadoghq.atlassian.net/browse/VULN-7734)
Synthetics global variable have their own restriction controls, but the behavior on the test results and test recorder changes depending if the variable was already being used or not.
Recorder behavior:
Removing access to a global variable already used in a test will **still** display it in the variables list and steps. Changing this behavior could lead to confusion on steps missing critical info to be properly displayed. The variable value remain unnacessible. 
Results behavior:
Removing access to a global variable already used in a test will **still** display it in the test results and screenshots in case the value is being used as plain text. Removing access to the test and result in question can lead to …
> :memo: Adds explanation on restricted variable behavior

- content/en/agent/guide/agent-5-architecture.md
- content/en/agent/guide/agent-5-autodiscovery.md
- content/en/agent/guide/agent-5-check-status.md
- content/en/agent/guide/agent-5-commands.md
- content/en/agent/guide/agent-5-configuration-files.md
- content/en/agent/guide/agent-5-debug-mode.md
- content/en/agent/guide/agent-5-flare.md
- content/en/agent/guide/agent-5-kubernetes-basic-agent-usage.md
- content/en/agent/guide/agent-5-log-files.md
- content/en/agent/guide/agent-5-permissions-issues.md
- content/en/agent/guide/agent-5-ports.md
- content/en/agent/guide/agent-5-proxy.md
- content/en/agent/guide/agent-6-commands.md
- content/en/agent/guide/agent-6-configuration-files.md
- content/en/agent/guide/agent-6-log-files.md
- content/en/agent/guide/install-agent-5.md
- content/en/agent/guide/install-agent-6.md
- content/en/agent/guide/upgrade_to_agent_6.md
Google is taking users to guides for older versions of the Agent.
```
/merge
```
> (Agent) Unindex guides from older Agent versions

- content/en/logs/guide/logs-rbac.md
- Revise the contents of the guide
- Remove references to permission scoping
- [DOCS-8584](https://datadoghq.atlassian.net/browse/DOCS-8584)
```
/merge
```
[DOCS-8584]: https://datadoghq.atlassian.net/browse/DOCS-8584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revise guide and remove scoping information

- content/en/dashboards/sharing/shared_dashboards.md
This PR updates the documentation on Embedded Shared Dashboards to be more accurate by replacing "domain" with "base URL"
Embedded shared dashboards is a newly launched feature that allows you to allowlist websites that you can embed a dashboard in. We've had some confused customers because they were not sure what exactly to put in the allowlist. The docs currently say the allowlist is a "domain" allowlist (ex: `google.com`), but it is actually implemented as a base URL allowlist: (ex: `https://google.com`).
Example:
If your website URL is "https://datadoghq.atlassian.net/wiki/spaces/x", you should put "https://datadoghq.atlassian.net" in the allowlist.
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the …
> [Shared Dash] Replace "domain" with "base url"

- content/en/developers/ide_plugins/vscode/_index.md
We removed the Synthetics feature of the VS Code extension last week, we need to update the documentation accordingly. 
```
/merge
```
> Remove all mentions of the synthetics feature in the VS Code extension documentation

- layouts/_default/baseof.html
- layouts/integrations/single.html
Helps with custom_kind translations causing carousel to not appear.
https://datadoghq.atlassian.net/browse/DOCS-9768
Similar changes to https://github.com/DataDog/documentation/pull/26387
```
/merge
```
https://docs.datadoghq.com/ja/integrations/mongodb_atlas/
vs
https://docs-staging.datadoghq.com/david.jones/custom-kind-carousel/ja/integrations/mongodb_atlas/
Also test random integrations images at top still appear https://docs-staging.datadoghq.com/david.jones/custom-kind-carousel/integrations/
> fix integration carousel bugs

- content/en/opentelemetry/otlp_logs.md
- Adding `site-region` around the content broke our dynamic endpoint placeholders inside code blocks.
- This PR swaps out the dynamic value to be a placeholder, ${YOUR_ENDPOINT}.
- This should be replaced with the endpoint listed in the Configuration alert.
```
/merge
```
> Fix broken endpoint param

- content/en/logs/guide/_index.md
- content/en/logs/guide/fluentbit.md
- The integration docs should pull from the the integration-extras repo, but the log collection docs was overriding that automation.
- [DOCS-9143](https://datadoghq.atlassian.net/browse/DOCS-9143)
- Integration-extras documentation: https://github.com/DataDog/integrations-extras/pull/2576
```
/merge
```
[DOCS-9143]: https://datadoghq.atlassian.net/browse/DOCS-9143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move fluent bit log collection to logs guide

- content/en/network_monitoring/devices/snmp_traps.md
- content/en/network_monitoring/devices/troubleshooting.md
- Adds instructions on how to setup a port number under 1024
- Links to the instructions on the troubleshooting page
- Adds a Further Reading partial that was missing from the SNMP Traps page
```
/merge
```
> [DOCS-9806] Update SNMP Trap docs

- content/en/data_streams/dotnet.md
> Update dotnet docs dsm

- content/en/account_management/plan_and_usage/usage_details.md
Add instructions for enabling allotted and committed pills in total usage cards.
Requested by a support engineer on https://datadoghq.atlassian.net/browse/DOCS-9571
```
/merge
```
> Add instructions for viewing usage pills

- content/en/error_tracking/troubleshooting.md
- content/en/tracing/error_tracking/_index.md
This PR removes all references to entry span fingerprinting limitations.
```
/merge
```
> [error-tracking] Remove entry span fingerprinting limitation

- content/en/dashboards/widgets/slo.md
As of 1/7/2024, it is no longer required to enter a target for the global time window in order to see error budget and status information. We now use the primary target of the SLO by default (unless overridden by the user).
```
/merge
```
> Update SLO widget docs for global target setting

- Makefile
- Makefile.config.example
- go.mod
- go.sum
- removes rbac script from makefile
- removes api and app key variable instantiation from makefile (no longer necessary since rbac api call is not happening in docs build anymore)
https://docs-staging.datadoghq.com/brian.deutsch/web-5767-rbac-migration/account_management/rbac/permissions
green build https://gitlab.ddbuild.io/DataDog/documentation/-/jobs/757247813
RBAC permissions page should be mirroring what's in prod.  Otherwise should be no local build issues from removing the api and app key definitions locally (RBAC api call was the only relevant use of them locally)
> [web-5767] removes rbac script from local docs build

- content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md
Includes Operator specific instructions for Opentelemetry configuration. 
```
/merge
```
> add operator instructions for OTel receiver configs

- content/en/tracing/guide/inferred-service-opt-in.md
- content/en/tracing/guide/service_overrides.md
- Remove mention of Preview from Inferred Service opt-in and Service Overrides.
- Make these docs public (remove private).
```
/merge
```
> Remove Preview Mentions from Inferred Service Docs

- content/en/dashboards/guide/_index.md
This PR updates the deadline set in the title of the `Dashboards API: Migrate from is_read_only` guide in the Graphing Guides list (from `November 30, 2024` to `December 13, 2024`).
```
/merge
```
> date update graphing guides

- content/en/logs/log_configuration/flex_logs.md
- Add statement on capacity of Flex logs compute for multi-org accounts
- Update disable instructions to match UI
```
/merge
```
> Explicitly state compute capacity for multi-org accounts

- content/en/logs/log_configuration/archives.md
- For GCS (Google Cloud Storage) Logs Rehydrations we only support rehydrating from the following storage Classes (Standard, Coldline and Nearline)
- We should document this in the public docs.
```
/merge
```
> Add documentation for GCS unsupported storage classes

- assets/styles/components/_collapsible-section.scss
Fix the duplicated collapsible marker element visible on Safari and Safari + Chrome mobile:
https://docs.datadoghq.com/fr/metrics/overview/
Fixed:
https://docs-staging.datadoghq.com/lisianetu/fix-collapsible-elements/metrics/overview/
```
/merge
```
> [FIX] hide collapsible element markers on safari and mobile

- content/en/account_management/billing/ci_visibility.md
The documentation page is not clear about what CI Visibility excludes from billing: commits from bots and made from the GitHub UI are not billed, however if the noreply email is set as the author and committer of the user, the commit gets billed. This PR fixes that.
```
/merge
```
> [CIVIS] Better explain billing exclusions for CI Visiblity

- content/en/real_user_monitoring/platform/connect_rum_and_traces.md
This PR documents the new `tracestate` header that will be generated by V6 of the browser SDK when using the `tracecontext` propagator. The header was added in [this PR](https://github.com/DataDog/browser-sdk/pull/3163).
This PR shouldn't be merged until V6 of the browser SDK is released.
> Document new tracestate header for tracecontext propagator

- content/en/logs/workspaces/sql_reference.md
- Add new supported functions in the Workspaces SQL Reference docs
- [DOCS-9732](https://datadoghq.atlassian.net/browse/DOCS-9732)
**Do not merge** Waiting for final approval from PM
```
/merge
```
[DOCS-9732]: https://datadoghq.atlassian.net/browse/DOCS-9732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add new functions for workspaces sql docs

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md
- Several issues have been opened by customers who are using `com.datadog.trace.api.GlobalTracer` instead of `io.opentracing.util.GlobalTracer`.
- Add explicit import statement to the code example in question.
```
/merge
```
> Clarify correct import for Android SDK

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
> [AWSX] Update send-aws-services-logs-with-the-datadog-lambda-function.md

- content/en/security/application_security/threats/setup/compatibility/java.md
Adds gRPC as a supported framework to the java security matrix:
```
/merge
```
> appsec/java: explicit we don't support grpc request blocking

- content/en/continuous_integration/pipelines/custom.md
We added a new field called `provider_name` which will allow customers to specify the provider name. Up until now we always used `custom`. There will be another PR for the API spec
```
/merge
```
> [CI Visibility] Add CI provider name to custom pipeline example

- layouts/shortcodes/latest-lambda-layer-version.html
Bumps datadog-lambda-rb to layer version 24
https://github.com/DataDog/datadog-lambda-rb/releases/tag/v3.24.0
```
/merge
```
> Bump datadog-lambda-rb layer to version 24

- content/en/developers/ide_plugins/visual_studio/_index.md
> (dev) Add VS instructions for using custom URL

- content/en/continuous_integration/pipelines/github.md
We currently give instructions in order to disable CI Visibility that are difficult for people to perform, because most of the time, they are not an administrator of their GitHub organization. There is a way to disable CI Visibility for GitHub Actions directly in the Datadog UI, and this PR documents that.
No concerns.
```
/merge
```
> [SDCI] update instructions to disable CI Visibility for GitHub Actions

- config/_default/menus/main.en.yaml
- content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/_index.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/web_view_tracking.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/_index.md
- Removes the Web View Tracking from Unity docs because it doesn't make sense for this platform
```
/merge
```
> [DOCS-9873] Remove web view tracking from Unity docs

- content/en/security/cloud_security_management/setup/agentless_scanning/azure_resource_manager.md
- content/en/security/cloud_security_management/setup/agentless_scanning/cloudformation.md
- content/en/security/cloud_security_management/setup/agentless_scanning/quick_start.md
- content/en/security/cloud_security_management/setup/agentless_scanning/terraform.md
Adds brackets around inline icons in Cloud Security Management setup docs.
```
/merge
```
> Add brackets around icons

- content/en/tracing/trace_collection/library_config/go.md
Adds that metrics are submitted to the agent from the Go tracer including tags from `DD_TAGS` environment variables.
Source: https://github.com/DataDog/dd-trace-go/pull/3067
```
/merge
```
> fix: clarify that APM metrics include tags from DD_TAGS

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
This PR updates the CWS documentation pull config to pull the documentation from agent 7.61 now that it has been released.
```
/merge
```
> update pull config to bump CWS documentation to 7.61

- content/en/serverless/step_functions/redrive.md
Updates the redrive page to add details and limitations for redrive traces
```
/merge
```
> Step Functions Redrive Tracing

- content/en/network_monitoring/netflow/_index.md
> add alias for Netflow Monitoring

- content/en/tracing/services/inferred_services.md
Under Set up inferred services, added note to indicate that configurations are enabled by default in v7.60.0 of Agent.
Under Set up inferred services, added note to indicate that configurations are enabled by default in v7.60.0 of Agent.
This was confirmed by the eng team, please see [slack thread](https://dd.slack.com/archives/C04KJSX93BJ/p1736955019784649) 
```
/merge
```
> Update about default config in newer Agent versions

- .github/workflows/vale_linter.yml
- content/en/agent/basic_agent_usage/amazonlinux.md
Pinning Vale to a slightly older version to get around a bug. Moving forward, we should probably stick to using a specific version of Vale instead of allowing the action to use the latest version. That way we can test the updates before we use them in CI.
```
/merge
```
> (maint) Pin Vale to a specific version

- layouts/integrations/_markup/render-image.html
- local/bin/py/build/configurations/pull_config_preview.yaml
overwrite image src under the `integrations` dir to point to proper location in s3 so app and docs are pulling from the same source of truth.   this happens if images are inlined in the integration readmes and dont use the docs hugo img shortcode.  See incident-33967 for more
```
/merge
```
https://docs-staging.datadoghq.com/david.jones/irender/integrations/
> Use render image hook so images from upstream integration readmes point to correct dir in S3

- content/en/real_user_monitoring/mobile_and_tv_monitoring/android/advanced_configuration.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/android/setup.md
- content/en/real_user_monitoring/platform/connect_rum_and_traces.md
- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md
Constructors for these classes are deprecated and builders should be used instead.
```
/merge
```
> Change Android SDK `DatadogInterceptor` and `TracingInterceptor` creation snippets from constructor to builder

- content/en/profiler/enabling/go.md
- content/en/profiler/enabling/supported_versions.md
Our docs currently say we support, at a minimum, Go 1.19 for the Go
profiler. However, we don't any more, and haven't for a while. Our
policy is now to align our Go version support with the official Go
project policy, which is to support the latest two major releases.
Change the Go profiling docs to reflect that. This should help prevent
the docs from going stale as new versions of Go/our library are
released.
```
/merge
```
> profiling: document Go version support explicitly

- content/en/integrations/guide/aws-manual-setup.md
Updates our manual role based aws integration docs to properly display which partitions are valid based on the user using either a fed or commercial datadog instance.
https://docs-staging.datadoghq.com/saleel/fix-region-conditional-on-aws-manual-setup-docs/integrations/guide/aws-manual-setup/?tab=roledelegation&site=gov (see how step 2 is displayed)
https://docs.datadoghq.com/integrations/guide/aws-manual-setup/?tab=roledelegation#setup (missing in prod)
```
/merge
```
> Fix region conditional on AWS manual role based setup docs

- layouts/shortcodes/code-block.html
- We noticed that code blocks are still collapsible, even when `collapsible="false"`
- (They only were not collapsible when `collapsible` wasn't set)
- It seems like this is because `{{ if $collapsible }}` evaluated to `true`, regardless of what we set.
- Updated the line to `{{ if eq $collapsible "true" }}` which seems to fix things.
**Verifying**
- [Example where collapsible="false"](https://docs-staging.datadoghq.com/brett.blue/collapsible-fix/integrations/guide/azure-programmatic-management/?tab=windows#terraform)
- [Example where collapsible="true"](https://docs-staging.datadoghq.com/brett.blue/collapsible-fix/account_management/org_settings/cross_org_visibility_api/#payload)
- [Example where collapsible is not set](https://docs-staging.datadoghq.com/brett.blue/collapsible-fix/getting …
> Make code block collapsible parameter work correctly

- content/en/tracing/trace_collection/library_config/go.md
- Missing `DD_TRACE_AGENT_URL`, noted in https://github.com/DataDog/documentation/issues/26299.
- Added new entry for this option under Traces.
- Also added note to `DD_TRACE_AGENT_PORT` and `DD_AGENT_HOST` indicating priority.
```
/merge
```
> DD_TRACE_AGENT_URL in Go Library Config

- content/en/infrastructure/containers/container_images.md
- content/en/security/cloud_security_management/setup/agent/kubernetes.md
- content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md
See [Slack thread](https://dd.slack.com/archives/C04G2K21B08/p1736963127234069) - a customer was having issues getting their Agent to generate a customer SBOM, and we linked it to the image streaming feature in GKE. I've added some notes to tell users to disable the image streaming feature so they can enable SBOM collection in CSM Vulnerabilities.
```
/merge
```
> Add notes about disabling GKE for SBOM collection

- content/en/data_jobs/airflow.md
Add log collection step to DJM on MWAA setup guidelines. The two steps are taken from [MWAA integration doc](https://docs.datadoghq.com/integrations/amazon_mwaa/#log-collection).
Merge readiness: Not ready for merge, requires a `web-ui` change for the trace correlation to work.
```
/merge
```
> Two-step log collection guideline

- content/en/opentelemetry/schema_semantics/semantic_mapping.md
Add explanation for Span Type logic applied to OTel spans. Remove the "black box" from our approach
- [ X ] Ready for merge
```
/merge
```
> [OTEL-2370] add Span.Type tables for otel

- content/en/tracing/configure_data_security/_index.md
We redact path segments that contain any digits. e.g. `abc123` will be redacted.
```
/merge
```
> Correct obfuscation documentation

- content/en/cloud_cost_management/datadog_costs/_index.md
Looks like reference numbers were [bumped by 1 in this PR](https://github.com/DataDog/documentation/pull/26818/files#diff-2a0d38184a546c7c1afd64fd42c146decfcd014c92da5d521852a4c18becef2aL77) causing doc links to lead to the wrong page. A recent CCM customer support issue would have been solved by correct links here.
```
/merge
```
> fix ref numbers

- layouts/shortcodes/dbm-mongodb-agent-data-collected.en.md
This PR adds additional notes to explain the limitations about MongoDB slow queries collection with `getLog` command. 
```
/merge
```
> [dbm] add additional note to the getlog limitation

- content/en/serverless/guide/gcr_serverless_init.md
We've seen issues with port conflicts when using serverless init, specifically when a customer is running multiple container instances per app. The recommended approach in this case is to utilize the sidecar, plus we want to push customers away from serverless init
> Updates the language on the serverless init cloud run page to push customers to use the sidecar

- content/en/account_management/org_settings/oauth_apps.md
https://datadoghq.atlassian.net/browse/ACCESS-2850
Removes references to the unreleased `org_authorized_apps_read` and `org_authorized_apps_write` permissions. It seems there are no plans to release them anytime soon, so not sure when the old text will be restored...
It doesn't look like the OAuth Apps page is visible to those with the Datadog Standard Role, so I removed that too.
```
/merge
```
> [ACCESS-2850] Replace references to `org_authorized_apps_read/write` to `org_management`

- content/en/continuous_integration/pipelines/gitlab.md
This PR updates the documentation to reflect the new GA feature of Gitlab K8s infra correlation for job spans.
```
/merge
```
> [SDCI-880] Add K8s explanation for infra correlation for Gitlab

- content/en/opentelemetry/agent/agent_with_custom_components.md
- content/en/opentelemetry/agent/install_agent_with_collector.md
- content/en/opentelemetry/agent/migration.md
- Bump `otel-agent` version to the latest stable `7.61.0`
- Add missing `datadog.site` param to the migration guide
- Add temporary fix for log level issue by explicitly setting `datadog.logLevel` param to a lowercase value, eg. `info`, `debug`, etc.
```
/merge
```
> Bump otel-agent version to 7.61 

- content/en/dynamic_instrumentation/enabling/ruby.md
Update minimum Ruby tracer version for dynamic instrumentation to 2.9.0 since there have been several issues fixed in 2.9.0.
```
/merge
```
> Update minimum Ruby tracer version for dynamic instrumentation to 2.9.0

- content/en/agent/configuration/proxy.md
- content/en/agent/guide/agent-5-proxy.md
- content/es/agent/configuration/proxy.md
- content/fr/agent/configuration/proxy.md
- content/ko/agent/configuration/proxy.md
the haproxy-app.agent.datadoghq.com is pointing to `metrics.agent.datadoghq.com.`
see:
```
dig haproxy-app.agent.datadoghq.com
; <<>> DiG 9.10.6 <<>> haproxy-app.agent.datadoghq.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44042
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;haproxy-app.agent.datadoghq.com. IN    A
;; ANSWER SECTION:
haproxy-app.agent.datadoghq.com. 300 IN CNAME   metrics.agent.datadoghq.com.
```
All proxy should send there metrics to the fqnd with metrics.agent.{site} in order to properly go throw private link.
see also: https://docs.datadoghq.com/agent/guide/private-link/?tab=connectfromsameregion#setup
> proxy configuration: update recommended fqdn to metrics.agent.{site}

- content/en/serverless/guide/datadog_forwarder_node.md
1. Replace the package `datadog-cdk-constructs` with `datadog-cdk-constructs-v2`. `datadog-cdk-constructs` is for AWS CDK v1, [which has reached its end of support on 2023/06/01](https://aws.amazon.com/blogs/devops/cdk-v1-end-of-support/). We have also removed `datadog-cdk-constructs` v1 from our codebase in 2024.
2. Replace `Datadog` class with `DatadogLambda`, which is the recommended API to instrument a Lambda function using Datadog CDK Construct.
```
/merge
```
> Update datadog_forwarder_node.md to use CDK Construct v2

- content/en/logs/log_collection/csharp.md
The `https://` is required when configuring the URL. The lack of this led to some confusion and an issue report: https://github.com/DataDog/serilog-sinks-datadog-logs/issues/127
Reopened https://github.com/DataDog/documentation/pull/27235 with correct branch name.
```
/merge
```
Closes: https://github.com/DataDog/serilog-sinks-datadog-logs/issues/127
> Include URL protocol in serilog documentation

- content/en/logs/log_collection/javascript.md
updates content/en/logs/log_collection/javascript.md
- Clarifies that Browser Logs SDK can be used without the Browser RUM SDK;
- Clarifies the sessionSampleRate in the context of the Browser Logs SDK.
```
/merge
```
> Update content/en/logs/log_collection/javascript.md: Clarify Browser logs can be used without Browser SDK and sessionSampleRate

- content/en/llm_observability/quickstart.md
Adds Node.js code blocks for the LLM Observability Quickstart guide.
```
/merge
```
> [MLOB-2058] Add Node.js Quickstart Sections for LLM Observability

- content/en/opentelemetry/integrations/host_metrics.md
- content/en/opentelemetry/integrations/kafka_metrics.md
- We now have a shortcode to automatically source metric mapping tables for OTel integrations. (https://github.com/DataDog/documentation/pull/27169)
- Applied this to host and kafka integrations.
```
/merge
```
> Replace mapping tables with semantic-core shortcodes

- config/_default/menus/main.en.yaml
- content/en/getting_started/synthetics/mobile_app_testing.md
This fixes a bad redirect due to the weighting of Getting Started taking precedence.
Adds a new file under getting_started/synthetics/mobile_app_testing with `include_markdown` shortcode so it will pull in the relevant file . I tested both pages and they work now!
```
/merge
```
> fixing redirect due to weighting

- content/en/continuous_integration/pipelines/gitlab.md
Adds an explanation that jobs shorter than 15s might not have the infrastructure correlation, since the infra information might never be sent properly, due to the default collection check interval value being 15s.
This value can be decreased by customers, which would improve the situation.
> [SDCI-880] Add new warning on Gitlab K8s infra correlation

- content/en/security/code_security/static_analysis/static_analysis_rules/_index.md
This adds our (Code Analysis's) new Kotlin security ruleset.
```
/merge
```
Related to https://github.com/DataDog/datadog-static-analyzer-rule-docs/pull/100
> [K9VULN-1928] docs(code-analysis): add kotlin-security ruleset

- content/en/containers/kubernetes/configuration.md
> DOCS-9797: Updates to further configuration page for kubernetes

- content/en/dynamic_instrumentation/expression-language.md
This pull request includes updates to the documentation for the Dynamic Instrumentation Expression Language. The changes clarify the availability of certain variables and provide additional information on collection operations.
Documentation updates:
* [`content/en/dynamic_instrumentation/expression-language.md`](diffhunk://#diff-da2f021d6516ed91d9d4cdf85a6edae072affa4e6de289ab5b45ec342b4d8ac5L36-R38): Added a note specifying that certain variables (`@return`, `@duration`, `@exception`) are only available when instrumenting an entire method, not for individual lines of code.
* [`content/en/dynamic_instrumentation/expression-language.md`](diffhunk://#diff-da2f021d6516ed91d9d4cdf85a6edae072affa4e6de289ab5b45ec342b4d8ac5R54-R55): Added information about the `@it` variable, which provides …
> doc: add a note about available contextual variables for line probes

- content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/advanced_configuration.md
Adds `view.referrer` to iOS list of attributes changed through event mappers
```
/merge
```
> Add missing ios view referrer on view mapper

- content/en/error_tracking/frontend/browser.md
- content/en/error_tracking/troubleshooting.md
- content/en/real_user_monitoring/browser/collecting_browser_errors.md
There was a mixup and network errors should've never be taken into account by error tracking. Updating the docs to reflect the fix.
Can be merged anytime
```
/merge
```
> update docs regarding network source

- content/en/logs/log_configuration/archives.md
Reverts DataDog/documentation#26897
The PR making the content of the documentation true has been reverted (see https://github.com/DataDog/logs-backend/pull/90915), we should also clean up the documentation
> Revert "Add documentation for GCS unsupported storage classes"

- content/en/observability_pipelines/destinations/_index.md
Adds info about unresolvable behavior for templated fields.
Child PR of: https://github.com/DataDog/documentation/pull/26921
```
/merge
```
> [DOCS-9171] Add unresolvable behavior template syntax

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md
- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-framework.md
- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
- Remove the v2.14.0 instructions since `dd-trace-dotnet` [v2.14.0 was released more than two years ago](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.14.0).
- remove the notes regarding "Starting v2.14.0, you don't need to set `CORECLR_PROFILER`..."
- remove `CORECLR_PROFILER` from the snippets
- Remove configuration note about `DD_TRACE_ENABLED` since it is not longer correct since v3.
- Restore warnings about adding the env vars _globally_. (common mistake by users)
```
/merge
```
> APM .NET SDK - remove obsolete instructions and restore lost warnings

- content/en/tracing/trace_collection/trace_context_propagation/_index.md
Adding .NET to the list of tracers supports baggage header.
```
/merge
```
> .NET tracer now supports baggage for trace context propagation

- content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/advanced_configuration.md
This PR adds an example of `RumResourceAttributesProvider` usage for Kotlin Multiplatform SDK.
```
/merge
```
> Add an example of `RumResourceAttributesProvider` usage for Kotlin Multiplatform SDK

- content/en/data_jobs/databricks.md
Update the latest stable version to `1.7.1` in our djm databricks documentation page. 
```
/merge
```
> [DJM Documentation] Set latest stable version to 1.7.1

- content/en/monitors/configuration/_index.md
Adds the heading "Notification grouping" to the section discussing that feature. Previously this term was only contained in an image, which Alerting Product stated was making it hard to google this info. It also makes the overall "Set alert aggregation" section more clear and uniform.
- [√] Ready for merge
```
/merge
```
> Notifcation Grouping header

- content/en/opentelemetry/interoperability/otlp_ingest_in_the_agent.md
Document workarounds on failed OTLP ingestion pipelines in Agent v7.61.0+. This is related to https://github.com/DataDog/datadog-agent/issues/32947.
```
/merge
```
> [OTEL-2371] Document workarounds on failed OTLP ingestion pipelines in Agent

- content/en/containers/amazon_ecs/apm.md
This page has an example task definition linked above, which shows a value of 512 for the memory. Updating this page example to align with the [example task definition](https://docs.datadoghq.com/resources/json/datadog-agent-ecs-apm.json). (256 -> 512)
```
/merge
```
> Update memory value in task definition example

- content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/data_collected.md
Noticed this page had a circular redirect so this PR corrects it.
```
/merge
```
> Remove self-redirect for Kotlin Multiplatform

- content/en/database_monitoring/connect_dbm_and_apm.md
Add a SQL normalization parameter to APM/DBM. The Agent `7.63` introduces the normalization to improve APM/DBM correlation.
```
/merge
```
> Add SQL normalization parameter to APM/DBM

- content/en/synthetics/explore/_index.md
Update index.md to make it clearer that facets values might come from test the user doesn't have access to. 
```
/merge
```
> Update _index.md | make it clearer that facets value include restricted tests

- content/en/data_security/agent.md
Reflecting https://github.com/DataDog/datadog-agent/pull/33644 change (Agent 7.64 release)
```
/merge
```
> logs.processed and logs.sent metrics will not be emitted

- content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/setup.md
Currently, our documentation advises the use of `traceSamplingRate` to set the sampling rate in [this document](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/setup/?tab=rum#initialize-the-rum-ktor-plugin-to-track-network-events-made-with-ktor). Looking at the repo, this argument is actually called `traceSampleRate`. This PR fixes the argument name.
You can see the correct argument name being used [here](https://github.com/DataDog/dd-sdk-kotlin-multiplatform/blob/233abeb3c38780c75c67e633f466edb8e0554076/integrations/ktor/src/commonMain/kotlin/com/datadog/kmp/ktor/DatadogKtorPlugin.kt#L35), and the fact that traceSamplingRate is not present in the repository [here](https://github.com/search?q=repo%3ADataDog%2Fdd-sdk-kotlin-multiplatform%20trace …
> Fix invalid argument in KMP example

- content/en/dynamic_instrumentation/enabling/dotnet.md
- content/en/dynamic_instrumentation/enabling/java.md
- content/en/dynamic_instrumentation/enabling/nodejs.md
- content/en/dynamic_instrumentation/enabling/php.md
- content/en/dynamic_instrumentation/enabling/python.md
- content/en/dynamic_instrumentation/enabling/ruby.md
1. Add a Node.js page to the Dynamic Instrumentation (DI) documentation
2. Replicate minor changes to the shared "template" in the other languages
3. Add "Limited Preview" callout with link to waiting list to all languages being in Limited Preview (Node.js and Ruby)
4. Add "Limitations" section to all languages being in Limited Preview (Node.js and Ruby)
```
/merge
```
> Add Node.js DI documentation page

- content/en/logs/log_collection/_index.md
- content/es/logs/log_collection/_index.md
- content/fr/logs/log_collection/_index.md
- content/ja/logs/log_collection/_index.md
- content/ko/logs/log_collection/_index.md
- Updates AP1's browser Intake endpoint, which is `browser-intake-ap1-datadoghq.com`, not `logs.browser-intake-ap1-datadoghq.com`.
- Fixes a copypasta error: should have been AP1 instead of US5.
```bash
❯ host logs.browser-intake-ap1-datadoghq.com
Host logs.browser-intake-ap1-datadoghq.com not found: 3(NXDOMAIN)
❯ host browser-intake-ap1-datadoghq.com
<result>
```
```
/merge
```
> [docs] Fix AP1 browser-intake endpoint

- content/en/tests/code_coverage.md
- content/en/tests/flaky_test_management/auto_test_retries.md
- content/en/tests/flaky_test_management/early_flake_detection.md
- content/en/tests/setup/go.md
- content/en/tests/test_impact_analysis/setup/go.md
Removes the Preview warnings/flags from the Go library
```
/merge
```
> [Test Optimization] Remove Preview warning to the Go library

- content/en/tracing/metrics/runtime_metrics/nodejs.md
- content/en/tracing/metrics/runtime_metrics/ruby.md
Remove the public beta notice from Node.js runtime metrics and Ruby runtime metrics. This feature has been used in production for years now, we want to declare our support for it in its current form.
```
/merge
```
[APMAPI-1135]
[APMAPI-1135]: https://datadoghq.atlassian.net/browse/APMAPI-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [APM] Update runtime metrics preview notice for Node.js and Ruby libraries

- content/en/observability_pipelines/destinations/_index.md
Makes some small tweaks to the Template Syntax docs for OP, specifically the table detailing the default behavior when template fields cannot be resolved:
- For the Google Chronicle destination, the default log-type should be `DATADOG` instead of `vector_dev`
- Changed some language around the the other destinations to make it slightly more accurate
> [DOCS] Tweak Template Syntax-related docs for OP

- content/en/profiler/enabling/dotnet.md
- content/en/profiler/profiler_troubleshooting/dotnet.md
We faced customer cases where the profiling documentation could be misleading when APM is deployed with Single Step Instrumentation. So, the enabling and troubleshooting parts of the .NET profiling documentation are updated to be more explicit.
```
/merge
```
> [Profiling .NET] Update the .NET profiling doc to support Single Step APM Instrumentation

- content/en/data_jobs/emr.md
In the code snippet that customers copy paste as EMR cluster init action, add the env var to turn on logs collection. Flag it as optional.
Merge readiness: Not ready yet
```
/merge
```
> [DJM-585] Add logs env var in code snippet - EMR

- content/en/service_management/incident_management/analytics.md
- content/en/service_management/incident_management/incident_settings/information.md
We're launching a feature that allows users to edit timestamps of an incident. This adds a section in the information settings docs to reflect this change and a note in the analytics section.
(copy approved by @shahgahmed)
```
/merge
```
> [INA-6626] Update incident management settings and analytics docs to reflect timestamp overrides

- content/en/dashboards/sharing/scheduled_reports.md
Updates public docs for Scheduled Reports to reflect you can also send Slack reports to private Slack channels.
BEFORE: https://docs.datadoghq.com/dashboards/sharing/scheduled_reports/
AFTER: https://docs-staging.datadoghq.com/vickie/CRP-1288-slack-recipient-private-channels/dashboards/sharing/scheduled_reports/
```
/merge
```
Additional Notes
----
Recent similar PRs: 
- https://github.com/DataDog/documentation/pull/27078
- https://github.com/DataDog/documentation/pull/27273
> [DBNBK-207, CRP-1288] private slack channels are also supported

- content/en/observability_pipelines/destinations/_index.md
Adds documentation on the template syntax fallback behavior for the Splunk destination's `Source Type` field
> [Docs] Update OP docs for fallback template syntax behavior for Splunk source_type field

- content/en/profiler/profile_types.md
This modifies the original Java profile types documentation from 2020 to more accurately reflect the wallclock profiling from functionality, based on some internal discussions with sales & support engineering recently.
```
/merge
```
> Adjustments to the 2020 description of wallclock profiling for the JVM

- content/en/tests/setup/java.md
Updates documentation for Test Optimization for Java.
Instructions on how to add custom tags and measures to test spans are extended with OpenTelemetry API.
The reason for adding OpenTelemetry API is that OpenTracing API used in existing instructions has been deprecated.
```
/merge
```
> Add OpenTelemetry API instructions for custom test tags

- content/en/real_user_monitoring/mobile_and_tv_monitoring/flutter/troubleshooting.md
When using `flutter build ios-framework` and using the resulting artifacts, a dependency is missing. Add a Troubleshooting item to address it.
refs: RUM-7170
> Add troubleshooting item for Flutter

- content/en/llm_observability/setup/auto_instrumentation.md
Updates the LLM Observability Python auto-instrumentation page to accurately depict which versions of OpenAI/LangChain we have tracing support for (we dropped v0, v0.1 support in ddtrace>=3.0 respectively)
```
/merge
```
> [MLOB] reflect python openai/langchain tracing support versions

- content/en/data_streams/manual_instrumentation.md
Adds `.Net` entry based on https://dd.slack.com/archives/C05C61J554L/p1738011042428139
```
/merge
```
> Update manual_instrumentation.md adding .Net entry

- content/en/developers/ide_plugins/idea/_index.md
Removes references to the JetBrains Toolbox, which is no longer required by the Datadog plugin for JetBrains IDEs.
```
/merge
```
> Remove references to the JetBrains Toolbox

- content/en/profiler/profiler_troubleshooting/dotnet.md
- content/en/profiler/profiler_troubleshooting/java.md
- content/en/profiler/profiler_troubleshooting/python.md
- content/en/profiler/profiler_troubleshooting/ruby.md
`/tracing/troubleshooting/` no longer has a `#tracer-debug-logs` anchor since #24686, now it has a `#debugging-and-logging` one. This went on undetected since August 2024.
```
/merge
```
JIRA: [PROF-11317]
[PROF-11317]: https://datadoghq.atlassian.net/browse/PROF-11317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix anchors in profiler troubleshooting docs

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
The document already has a bundling section describing Esbuild, but a lot of customers encounter the same problem with Next.js, so we should provide Next.js-specific information too to have easily accessible piece of knowledge about it that we can point them to.
```
/merge
```
JIRA: [PROF-11291]
[PROF-11291]: https://datadoghq.atlassian.net/browse/PROF-11291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Next.js-specific bundling information

- content/en/sheets/_index.md
We have a new feature on Sheets that we'd like to document.
```
/merge
```
> Add documentation for the new Sheets pivot table visualization feature

- content/en/security/code_security/software_composition_analysis/setup_static/_index.md
- content/es/getting_started/code_analysis/_index.md
- content/ja/continuous_integration/static_analysis/github_actions.md
- content/ja/getting_started/code_analysis/_index.md
- content/ko/continuous_integration/static_analysis/github_actions.md
This PR removes deprecated input fields in examples for using our github actions. The reason for this is because the fields are deprecated, and are subject to removal in the future.
```
/merge
```
> [K9VULN-3470] docs(code-analysis): remove deprecated fields in Code Analysis' GitHub actions

- content/en/security/cloud_security_management/agentless_scanning/deployment_methods.md
Better explain cost to users. Describe auto scaling.
```
/merge
```
> Clarify expected agentless costs

- config/_default/menus/main.en.yaml
- content/en/profiler/profiler_troubleshooting/nodejs.md
Profilers for all languages have a troubleshooting page, only Node.js didn't have one. Since we're encountering some repeated support questions for Node.js, it's very useful to have a page that collects the usual answers to the more frequent ones.
```
/merge
```
JIRA: [PROF-11319]
[PROF-11319]: https://datadoghq.atlassian.net/browse/PROF-11319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add a Node.js profiler troubleshooting page

- content/en/containers/guide/cluster_agent_autoscaling_metrics.md
Remove the samples for the HPA `autoscaling/v2beta1` options to clean up and simplify the steps leaving only the `autoscaling/v2` configuration. 
For reference, `/v2` was added in Kubernetes 1.23 (Dec 2021) and `/v2beta1` was deprecated in this version and removed in Kubernetes 1.25. Kubernetes 1.25 is pretty old by now and for major distributions:
- AKS ended support 1.28 in Jan 2025 
- GKE ended support 1.26 in June 2024
- EKS ended support of 1.25 in May 2024 
So should be fine to remove, pretty much everyone should be at least on 1.25 by now, or at least using the `/v2` structure. 
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming …
> Remove deprecated HPA /v2beta1 samples for cleanup

- content/en/real_user_monitoring/guide/browser-sdk-upgrade.md
Fix a typo in the RUM initialization documentation where `compressIntakeRequest` is mentioned, but the actual parameter name is `compressIntakeRequests` (plural).
> 📝 [Readme] - fix typo in compressIntakeRequests parameter

- layouts/partials/profiling/profiling-troubleshooting.html
- Add NodeJS tile for troubleshooting index page, links to https://docs.datadoghq.com/profiler/profiler_troubleshooting/nodejs/
```
/merge
```
> Add NodeJS troubleshooting tile

- layouts/shortcodes/observability_pipelines/processors/remap.en.md
Caye flagged in Slack that we had some broken anchor links in a shortcode file. I've gone ahead and fixed them.
```
/merge
```
> Fix path notation anchor links

- config/_default/menus/main.ja.yaml
Per the linked Jira ticket, the Japanese menu item URL's are out of sync from the English pages and therefore not showing the content on the page. Upon reviewing Transifex I can see that the new page names and pages _are_ there and at least mostly translated, but the Japanese menu file is not yet updated. Per [slack](https://dd.slack.com/archives/GGHR55PNV/p1738599593027609) conversation, I am updating the ja menu file until the translation gets updated.
```
/merge
```
> [DOCS-9971] fixing Japanese menu

- content/en/opentelemetry/agent/agent_with_custom_components.md
- content/en/opentelemetry/agent/install_agent_with_collector.md
- content/en/opentelemetry/agent/migration.md
- Pin Dockerfile version to the latest stable release (`7.61`) instead of `main`
- Bump components version to v0.114.0 in OCB manifest file
- Switch to tagged versions of Dockerfile and OCB manifest instead of using branch (`7.61.x`)
- Update `docker build ...` command to set build args to use agent version `7.61.0` (the default build arg agent version in the `7.61.x` branch [is still set to `7.57`](https://github.com/DataDog/datadog-agent/blob/7.61.0/Dockerfiles/agent-ot/Dockerfile.agent-otel#L1-L2))
```
/merge
```
> feat(otel-agent): Pin Dockerfile version in BYOC docs

- content/en/tests/setup/dotnet.md
- content/en/tests/setup/java.md
- content/en/tests/setup/javascript.md
- content/en/tests/setup/python.md
- content/en/tests/setup/ruby.md
- content/en/tests/setup/swift.md
* Make `DD_TEST_SESSION_NAME` more prominent. 
* Try to reduce the importance of `DD_ENV` and `DD_SERVICE`
```
/merge
```
> [test optimization] Add test session name `DD_TEST_SESSION_NAME` instructions

- content/en/security/application_security/_index.md
- content/en/security/application_security/how-appsec-works.md
Remove references to Code Security capabilities (SCA and runte code security) in the ASM home
Pls merge 
> Update ASM home to remove references to Code Security capabilities

- config/_default/menus/main.en.yaml
- content/en/data_streams/_index.md
- content/en/developers/integrations/agent_integration.md
- content/en/developers/integrations/api_integration.md
- content/en/developers/integrations/create-a-cloud-siem-detection-rule.md
- content/en/developers/integrations/create-an-integration-monitor-template.md
- content/en/integrations/guide/azure-manual-setup.md
- content/en/integrations/guide/azure-programmatic-management.md
- content/en/monitors/guide/monitor_best_practices.md
- content/en/monitors/guide/troubleshooting-monitor-alerts.md
- content/en/monitors/templates/_index.md
- content/en/monitors/types/cloud_network_monitoring.md
- content/en/service_catalog/scorecards/scorecard_configuration.md
- Monitor product is changing "Recommended Monitors" to "Monitor Templates"
- [DOCS-9785](https://datadoghq.atlassian.net/browse/DOCS-9785)
**Do not merge**: waiting for final approval from product
```
/merge
```
[DOCS-9785]: https://datadoghq.atlassian.net/browse/DOCS-9785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replace Recommended with monitor templates

- translate.yaml
prevents translated data partials being added to transifex as sources
```
/merge
```
Worth noting `The fnmatch module in Python does not natively support the {} syntax for grouping multiple patterns like some shells do` which is why every file to ignore has to be listed out per language.
> [web-6011] prevents translated data partials being added to transifex as sources

- content/en/llm_observability/setup/sdk/python.md
Updates the `AWS Lambda setup` section with some more specific wording to alleviate onboarding friction while we work on addressing `DD_EXTENSION_VERSION` (which is a know incompatibility with the `next` version for LLMObs) issues.
The change specifies that:
- all serverless + LLMObs users need to set `DD_TRACE_ENABLED=true`
- if they are expecting APM traces in addition to LLMObs, they need to unset `DD_EXTENSION_VERSION` if using `Datadog-Extension` version less than 67, otherwise if using version >= 67 set `DD_EXTENSION_VERSION=compatibility`
- if they are not expecting APM traces/only expecting LLMObs traces, they need to set `DD_LLMOBS_AGENTLESS_ENABLED=true`
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, …
> [MLOB-2227] Update LLM Observability + AWS Lambda instructions

- content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/advanced_configuration.md
Minor fix for some C# syntax in the Unity documentation
> Fix C# syntax for AddUserExtraInfo documentation

- content/en/llm_observability/setup/auto_instrumentation.md
Reverts DataDog/documentation#27324
Reverting temporarily since ddtrace 3.0.0 version is not yet released.
> Revert "[MLOB] reflect python openai/langchain tracing support versions"

- content/en/service_management/events/guides/usage.md
Documents a constraint for this functionality, shared by a TEE [here](https://datadoghq.atlassian.net/browse/SOCE-1517?focusedCommentId=2034728).
This similar to the constraint on [Logs custom metrics](https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/), but it has yet to be publicly documented for Events:
> Only logs ingested with a timestamp within the past 20 minutes are considered for aggregation.
```
/merge
```
> Document timestamp constraint of Event Custom Metrics

- content/en/data_jobs/dataproc.md
This PR tells DJM users how to setup Dataproc logs collection by redirecting them to the log setup section of the Dataproc integration.
```
/merge
```
> [DJM-637] Add step redirecting to integration Log setup

- content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/setup.md
We identified an issue with using on of iOS SDK APIs, where it can disrupt existing app behaviors when applied within a `List`. Recognizing this as a known issue in our SDK, we are adding a warning to the documentation to inform developers and prevent misuse.
For more context see: https://github.com/DataDog/dd-sdk-ios/pull/2192
> RUM-8504 Add warning on instrumenting SwiftUI actions

- content/en/real_user_monitoring/mobile_and_tv_monitoring/flutter/advanced_configuration.md
Per internal feedback:
- Adds a link to Integrated Libraries for the view functions that got moved there from Advanced Configuration
- Removes unused links from Flutter Advanced Configuration
```
/merge
```
Should have Eng review/approval before merging.
> [DOCS-9473] Add Flutter integrated libraries link and fix links

- content/en/real_user_monitoring/browser/advanced_configuration.md
RUM View name behavior is a common source of confusion amongst customers ([example ticket](https://datadog.zendesk.com/agent/tickets/1748310)).
In particular, the word `alphanumeric` is not specific enough because it can include special characters. In reality, all the SDK is checking for is the presence of a number in the URL path segment ([reference](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/2962292956/How+are+url_path_group+fields+computed+from+url_path+ones)).
This explanation is slightly more specific and will hopefully reduce customer confusion.
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add …
> Update View name explanation

- content/en/monitors/status/status_page.md
Custom schedule monitors are now supported in the new monitor status page
> Status page doc update

- config/_default/menus/main.en.yaml
- content/en/serverless/azure_functions/_index.md
> DOCS-9940: Serverless Monitoring for Azure Functions

- content/en/containers/kubernetes/control_plane.md
Amazon recently added new functionality that allows the Agent to collect metrics for the `kube_scheduler` and `kube_controller_manager`. This PR updates the docs with the required steps to enable metric collection.
```
/merge
```
> Update the EKS section to reflect the new endpoints Amazon exposed

- content/en/agent/troubleshooting/windows_containers.md
- content/en/containers/kubernetes/data_collected.md
That Windows Containers Troubleshooting page seems to have not been updated in a long time, so I also did some formatting and edits there.
Otherwise, this PR makes the list of available `kubernetes.*` metrics for Windows containers a bit more visible.
```
/merge
```
> DOCS-10022: Call out limited kubernetes.* metrics for Windows

- layouts/partials/integrations-carousel/integrations-carousel-modal.html
- layouts/partials/integrations-carousel/integrations-carousel.html
https://datadoghq.atlassian.net/browse/WEB-6028
images in the integration carousel component should dynamically set the s3 bucket based on env
integrations in review should have images uploaded to staging bucket but may not be in prod bucket.
```
/merge
```
- check an integration page featuring the image carousel, for example: [buoyant](https://docs-staging.datadoghq.com/brian.deutsch/test-int-forked/integrations/buoyant_inc_buoyant_cloud/).  Inspect the source of the images and confirm the s3 bucket is `dd-app-listings-staging`.   All …
> [web-6028] integration carousel images bucket is dynamic per env

- content/en/agent/configuration/network.md
Adds additional allowlist rules for locked-down kubernetes environments (source: [link](https://github.com/DataDog/helm-charts/blob/main/charts/datadog-operator/values.yaml))
```
/merge
```
> Additional allowlist rules for locked-down kubernetes environments

- content/en/logs/workspaces/sql_reference.md
- Add new functions and syntax, requested by product team
- [DOCS-10039](https://datadoghq.atlassian.net/browse/DOCS-10039)
```
/merge
```
[DOCS-10039]: https://datadoghq.atlassian.net/browse/DOCS-10039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update workspaces with new functions and syntax

- content/en/opentelemetry/guide/_index.md
- content/en/opentelemetry/guide/migrate_operation_names.md
- New guide instructing how to opt-in to new operation name mappings.
```
/merge
```
> New Operation Name Mappings Migration Guide

- content/en/tests/setup/dotnet.md
- content/en/tests/setup/java.md
- content/en/tests/setup/javascript.md
- content/en/tests/setup/python.md
- content/en/tests/setup/ruby.md
- content/en/tests/setup/swift.md
- content/en/tests/troubleshooting/_index.md
This is a follow-up of https://github.com/DataDog/documentation/pull/27639, which improved the explanation of the `DD_TEST_SESSION_NAME` environment variable for Test Optimization. 
This PR updates the test command example for .NET to include just the test command (similar to examples in other languages), instead of also including the variable assignment. Also adds a few other small edits.
```
/merge
```
I've added the original contributor of https://github.com/DataDog/documentation/pull/27639 (@juan-fernandez) as a reviewer to make sure …
> [test optimization] Follow-up: Better DD_TEST_SESSION_NAME explanation

- content/en/profiler/enabling/dotnet.md
Changes `DD_PROFILING_ENABLED:true` to the correct value of `DD_PROFILING_ENABLED=1`.
https://github.com/DataDog/datadog-aas-linux/issues/115
```
/merge
```
> Fix DD_PROFILING_ENABLED Value for Azure App Service

- content/en/serverless/azure_app_services/azure_app_services_container.md
Adds a tab for .NET instructions to Azure App Services install for Linux containers. Previously information was hidden in [this guide](https://docs.datadoghq.com/serverless/guide/azure_app_service_linux_sidecar/).
```
/merge
```
> DOCS-10117: Add .NET instructions to AAS

- content/en/real_user_monitoring/feature_flag_tracking/setup.md
- content/en/real_user_monitoring/guide/setup-feature-flag-data-collection.md
- layouts/partials/rum/rum-feature-flag-tracking.html
#26999 was merged yesterday (Feb 10) but between the time it was created & merged the docs for Feature Flags was changed/consolidated on #25073 so it is not showing up on the [live docs website](https://docs.datadoghq.com/real_user_monitoring/feature_flag_tracking/setup).
So this updates it to use the new URL format & include the instructions on the new document.
> fix(docs): Update Growthbook Feature Flag integration docs

- content/en/serverless/aws_lambda/configuration.md
Update serverless doc to clarify that overall trace metrics for a Lambda function are *only* calculated based on sampled invocations, not on 100% of traffic as would be the case with host-based tracing. 
Discussed during this escalation: https://datadoghq.atlassian.net/browse/APMS-13513
> Clarify trace metric dependence on sampling

- content/en/real_user_monitoring/browser/setup/server.md
* Add instructions on how to onboard with injection in the server for RUM
* Small changes in the already existing content for clarity
```
/merge
```
> Adapt RUM server onboarding to include httpd

- content/en/account_management/audit_trail/events.md
Add missing documentation for app datastore event to audit docs
Document containing all the information: https://docs.google.com/document/d/1fmW7e_bFEOHNymt9HP7J47ktAh2RfPr7KZTSfk6h-Fk/edit?tab=t.0
```
/merge
```
> :memo: [LOGSAC-838] Add app datastore events to audit docs

- content/en/sensitive_data_scanner/setup/cloud_storage.md
Adds a Set Up SDS for Cloud Storage doc.
Child of: https://github.com/DataDog/documentation/pull/27159
[DOCS-9479](https://datadoghq.atlassian.net/browse/DOCS-9480)
```
/merge
```
[DOCS-9479]: https://datadoghq.atlassian.net/browse/DOCS-9479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-9479] Set up SDS for Cloud Storage

- content/en/profiler/enabling/python.md
The "code provenance" feature is enabled by default in the Python integration, so the section to enable it explicitly is not needed.
I think it was [enabled by default](https://github.com/DataDog/dd-trace-py/blob/a5e3552f94982d69332ae158c5ef77b3a0204ebe/ddtrace/settings/profiling.py#L197) (accidentally?) by [this PR 2 years ago](https://github.com/DataDog/dd-trace-py/pull/5643).
This default value can be seen in dd-trace-py docs:
```
/merge
```
> Python profiling: remove section to enable code provenance

- content/en/api/latest/rate-limits/_index.md
- content/en/api/v1/rate-limits/_index.md
- content/en/api/v2/rate-limits/_index.md
We are updating our rate limit documentation to show new metrics available to all customers on seeing their own usage. Related to ENGDOC-144
This is related to ENGDOC-144
> Rate Limit Visibility Documentation Updates

- content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
Correct invalid examples of `datadog-ci sourcemaps` usage.
https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps has examples which result in errors when you run them. https://github.com/DataDog/datadog-ci/blob/master/src/commands/sourcemaps/README.md, for comparison, has a correct example. Update the examples to use a correct arguments syntax.
```
/merge
```
> correct datadog-ci sourcemaps examples

- content/en/metrics/custom_metrics/_index.md
The note "Marketplace integrations emit custom metrics." is redundant because the previous bullet point "Metrics submitted by Marketplace integrations" already conveys the same information. This PR removes the unnecessary note to improve clarity and avoid duplication in the documentation.
Let me know if you’d like any refinements! 🚀
```
/merge
```
> Remove redundant note about custom metrics

- config/_default/params.en.yaml
- config/_default/params.ja.yaml
https://datadoghq.atlassian.net/browse/WEB-5938: Adds UTMs to announcement banner link to DASH site
```
/merge
```
Homepage: https://docs-staging.datadoghq.com/davidweid/update-announcement-banner-link/
> Add UTMs to DASH link in announcement banner

- content/en/metrics/nested_queries.md
@Stoovles flagged a typo in our docs - the descriptions for `is_greater` and `is_less` were the same. This PR makes them different 🙂 
```
/merge
```
> Fix description for is_less function

- content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/integrated_libraries.md
Adding `SDWebImage` as one of the supported libraries in RUM network instrumentation, along `Alamofire` and `Apollo GraphQL`. 
```
/merge
```
> RUM-mobile - Add SDWebImage to supported integrations

- content/en/security/threat_intelligence.md
- Update Threat Intel docs to add `disposable_email` category
- [Product initiative](https://datadoghq.atlassian.net/wiki/spaces/Attacks/pages/4531947103/New+user+behaviour+-+Disposable+e-mail+use)
```
/merge
```
> Update Threat Intel docs to add disposable_email category

- content/en/account_management/audit_trail/events.md
Add missing documentation for event management event to audit docs
Document containing all the information: https://datadoghq.atlassian.net/wiki/spaces/LA/pages/edit-v2/4534108512#Event-management
```
/merge
```
> 📝 [LOGSAC-839] Add event management events to audit docs

- content/en/security/code_security/guides/_index.md
There's an unnecessary `=` character on the Code Security > Guides page. This PR removes it to keep the page clean.
```
/merge
```
> Remove extraneous `=` character from Code Security Guides page

- content/en/real_user_monitoring/error_tracking/mobile/ios.md
Per internal feedback, added a limitation to iOS Error Tracking about symbols support
```
/merge
```
> [DOCS-9879] Add iOS symbols limitation for Error Tracking

- config/_default/menus/main.en.yaml
- go.mod
- go.sum
(Generated by websites-modules)
add new ddsql icon to top level DDSQL Editor menu item
motivation: https://datadoghq.atlassian.net/browse/WEB-6061
preview: https://docs-staging.datadoghq.com/websites-modules/generated/395/ddsql_editor/
- check that left menu has new icon
```
/merge
```
> add new `ddsql` icon

- content/en/developers/ide_plugins/_index.md
- content/en/developers/ide_plugins/idea/_index.md
- content/en/getting_started/code_security/_index.md
- content/en/security/code_security/dev_tool_int/ide_plugins/_index.md
Since version 1.8.6 the Datadog Plugin support WebStorm too. Add it to the list of supported JetBrains IDEs.
> Add WebStorm as supported IDE

- content/en/synthetics/platform/private_locations/_index.md
As a part of the FedRAMP High project the Synthetics team has built a new FIPS-compliant Private Location image. Customers who need FIPS compliance with the Datadog product will need to switch to using the new FIPS-compliant image. 
Eventually we would like to drop FIPS support from the current image. It is mentioned in a couple of places but [this mention of disabling it](https://github.com/DataDog/documentation/blob/c31c551847134990558abdcba193fee575c8186e/content/en/synthetics/platform/private_locations/configuration.md#L175-L179) would need to have a "after this version this flag is not supported" message. I am also curious if there's a pattern for a deprecation like this? As a part of the PR to update the removal of that flag would I also just add a note that PL versions after and …
> Doc updates to include new FIPS Synthetics PL image

- content/en/opentelemetry/otlp_endpoint.md
- content/en/opentelemetry/otlp_metrics.md
Setting otlphttp endpoint as described in the guide would not work properly - it would result in 404s. If you use the general "endpoint" option in otlphttp exporter, the exporter appends `/v1/traces` or `/v1/metrics` to the given endpoint for each signal, which means the final URL is wrong. Setting `traces_endpoint` and `metrics_endpoint` for their respective signals instead is correct.
```
/merge
```
> Update otlphttp config for OTLP direct ingest endpoints

- content/en/notebooks/notebooks_legacy.md
Snapshots don't work for all widgets and data sources. I found this out the hard way because I glanced over the documentation and got the impression everything could become a snapshot.
This PR adds a notification that informs a notebook editor how to check in snapshots view if all the desired widgets will turn into snapshots.
Honestly, I don't need this to be merged because I can't provide the translations for all languages. I just need something in documentation that will avoid writing my own documentation which might get stale.
``` …
```
> Add info on snapshots limitations notebooks_legacy.md

- content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/nodejs.md
new PR because old PR (gorkavicente-runtime-sca-nodejs-requirements) wasn't following naming convention
> Update Runtime SCA Node.js Requirements

- content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/php.md
new PR because old PR (gorkavicente-runtime-sca-php-requirements) didn't follow naming convention
> Update Runtime SCA PHP Requirements

- content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/nginx.md
new PR because old PR (gorkavicente-runtime-sca-nginx-requirements) didn't follow naming convention
> Update Runtime SCA Nginx Requirements

- content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/java.md
new PR because old PR (gorkavicente-runtime-sca-java-requirements) doesn't follow naming conventions
> Update Runtime SCA Java Requirements

- content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/dotnet.md
new PR because old PR (gorkavicente-runtime-sca-dotnet-requirements) didn't follow the naming conventions
> Update Runtime SCA .NET Requirements

- content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/go.md
new PR because old PR (gorkavicente-runtime-sca-go-requirements) didn't follow naming convention
> Update Runtime SCA Go Requirements

- content/en/tracing/guide/resource_based_sampling.md
The Ruby Tracer supports resource-based sampling since v2.4.0.
```
/merge
```
> Update ruby version for resource based sampling

- content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/setup.md
Remove the "preview" designation at the top of the Unity setup documentation in RUM
> Remove "Preview" from Unity docs

- content/en/opentelemetry/agent/install_agent_with_collector.md
Document installation process of the Agent with Embedded OpenTelemetry Collector using Datadog Operator.
```
/merge
```
> OTAGENT-261 Add Datadog Operator instructions to `otel-agent` installation guide

- static/resources/yaml/datadog-agent-aks.yaml
- static/resources/yaml/datadog-agent-all-features.yaml
- static/resources/yaml/datadog-agent-apm.yaml
- static/resources/yaml/datadog-agent-logs-apm.yaml
- static/resources/yaml/datadog-agent-logs.yaml
- static/resources/yaml/datadog-agent-npm.yaml
- static/resources/yaml/datadog-agent-vanilla.yaml
- static/resources/yaml/datadog-agent-windows-all-features.yaml
- static/resources/yaml/datadog-agent-windows-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs-apm.yaml
- static/resources/yaml/datadog-agent-windows-logs.yaml
- static/resources/yaml/datadog-agent-windows-vanilla.yaml
Updates the sample K8s manifests using the `generate.sh` so that they represent the latest helm chart version.
```
/merge
```
> [CTK-4694] Update K8s sample manifests with latest helm chart

- config/_default/params.yaml
The regular docs build allows duplicate YAML keys, but the customizable docs build doesn't, since each page relies much more heavily on YAML configuration to function correctly. This PR removes the older key, which in my understanding should have no impact to the regular build, since the older key is being overwritten now. But please let me know if this assumption is not correct!
```
/merge
```
> Remove overwritten YAML key causing cdocs build error

- content/en/agent/guide/environment-variables.md
Document EnvVar precedence over local config file.
Also mentioned in the following but it makes sense to be mentioned on this page as well
- https://docs.datadoghq.com/agent/configuration/proxy/?tab=linux#environment-variables
- https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration/?tab=npm#environment-variables
```
/merge
```
> Document EnvVar precedence

- content/en/service_management/incident_management/incident_settings/integrations.md
This PR updates the documentation for incident integration settings to include:
- The 'Add important links to the incident channel’s bookmarks' setting for Slack channels
- I'll be referencing this in a future Zoom docs update.
- Zoom integration
```
/merge
```
> [INA-7075] Update incident integration settings docs to include Zoom and slack channel bookmarks

- content/en/database_monitoring/recommendations/index.md
We now support our unused index recommendation for sqlserver and mongo.
> Update supported DBM recommendation types

- content/en/logs/log_collection/javascript.md
Updates the description for the beforeSend callback function with more details
```
/merge
```
> [DOCS-10034] Update Browser SDK beforeSend callback function details

- content/en/tracing/trace_pipeline/ingestion_controls.md
The links in the Minimum Version Required column of the table link to seemingly random pages. It seems like they made have previously been specified in a meaningful way, but are now inappropriately re-using random links from elsewhere on the page. This PR removes those links.
```
/merge
```
> Remove random links from Ingestion Control page

- content/en/synthetics/platform/private_locations/_index.md
[DOCS-10245](https://datadoghq.atlassian.net/browse/DOCS-10245)
The root certificates section was getting mangled with the tabs from the Install section, the root certificates section actually was not suppose to have any "install" instructions, just the paragraph as is, there was also a duplicate section of tabs there that should have been in the health check section. Not sure what happened but cleaned this up now by moving all of the install "tabs" to "collapse" sections,  and fixed the links where they were broken.
```
/merge
``` …
> [DOCS-10245] Moving installation tabs to collapse headers

- content/en/data_jobs/databricks.md
- content/en/data_jobs/dataproc.md
- content/en/data_jobs/emr.md
Switch to using the new installer script for Databricks so that new customers reading the documentation to set up DJM will directly use the installer script.
Update and clarify the note on script versions for all platforms now that they're all aligned and using the installer.
Merge readiness: Not ready yet
```
/merge
```
> [Data Jobs Monitoring] Use djm installer script in Databricks manual install tabs

- config/_default/menus/main.en.yaml
In the menu, `Secrets Scanning` should be below `Software Composition Analysis`
Change the menu numbering.
> Menu ordering: put secrets below SCA

- content/en/containers/datadog_operator/crd_monitor.md
Fix example manigest.
Previously, Dashboard manigest was used. 
Replaced with manifest in https://github.com/DataDog/datadog-operator/blob/main/examples/datadogmonitor/metric-monitor-test.yaml
> [CONS-7115] Fix example manifest

- content/en/logs/log_configuration/parsing.md
- Add a note letting customers know that Logs parsing matchers are not universally supported across all Logs products, specifically Log Explore and Workspaces.
- @usmankhan-dd 
```
/merge
```
> Add note about parsing support for query-time vs ingest-time

- content/en/data_jobs/airflow.md
Remove the OpenLineage installation guidelines for Airflow DJM on Astronomer as OpenLineage is already there. This streamlines the DJM onboarding and makes sure we don't introduce version conflicts on OpenLineage.
```
/merge
```
> [DJM Airflow on Astro] Remove OL install as it's already there on Astro

- content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
I guess the current content is a typo. I had the error mentioned below on my environment following the current document and I was able to solve it with this PR's correction.
* Error I had: `Cannot access 'Companion': it is internal in 'ComposeExtensionSupport'`
```
/merge
```
You see `MaterialExtensionSupport()` in the same way above the line in question, which works just fine.
> Adding "()" at the end of "ComposeExtensionSupport"

- content/en/agent/basic_agent_usage/_index.md
https://docs.datadoghq.com/agent/basic_agent_usage// is 404ing. I don't see an obvious double-slash, but we can at least redirect. 
[This should redirect](https://docs-staging.datadoghq.com/heston/DOCS-10302/agent/basic_agent_usage//)
```
/merge
```
> (maint) Redirect broken link

- content/en/monitors/notify/_index.md
Users can automatically create a case from a monitor notification when the monitor transitions. 
Adding a cross link to case management documentation that explains how to do that in details
> Add link to case management doc

- content/en/tracing/trace_collection/library_config/java.md
* Missing documentation for `DD_TRACE_CLIENT_IP_ENABLED` and subsequently `dd.appsec.enabled` in Java config docs.
```
/merge
```
> Document DD_TRACE_CLIENT_IP_ENABLED and dd.appsec.enabled in Java config

- content/en/tracing/trace_collection/compatibility/php.md
Support for CakePHP 3.x was added in early 2024: https://github.com/DataDog/dd-trace-php/tree/f514dc232cd52e375ef0f1e387705a5e24515172/src/DDTrace/Integrations/CakePHP
```
/merge
```
> Add CakePHP 3.x support

- assets/scripts/components/codetabs.js
fixes page jump on synced tab navigation by calculating window Y-axis position based on previously active tab position. (related to [#27974](https://github.com/DataDog/documentation/pull/27974))
previews: 
- https://docs-staging.datadoghq.com/stefon.simmons/fix-page-jump-on-tabs2/real_user_monitoring/feature_flag_tracking/setup/?tab=android#flagsmith-integration
- https://docs-staging.datadoghq.com/stefon.simmons/fix-page-jump-on-tabs2/dora_metrics/setup/deployments/?tab=apiorcli#selecting-and-configuring-a-deployment-data-source
``` …
```
>  fix page jumps on synced tab navigation

- layouts/_default/list.redirects.txt
We already deal with leading and trialing slashes from the redirects file aliases. However if multiple `/` exist this ends up creating a bad path via the redirect we generate in a post deploy which in turn conflicts with regular deploys.
This PR normalizes the initial alias string so that multiple slashes just become one and in turn avoid deploy conflicts.
e.g
```
/foo///bar////baz/foo///    ->    /foo/bar/baz/foo/
```
```
/merge
```
> replace multi / in alias with just one

- content/en/tracing/trace_pipeline/_index.md
- content/en/tracing/trace_pipeline/trace_retention.md
- Add clarity to vague sentences in trace retention and trace pipeline docs.
- Specifically, clarify that indexed spans include the corresponding trace; however, the other spans that make up the trace are only queryable if they are also indexed.
```
/merge
```
> Add clarity around trace retention

- content/en/serverless/step_functions/redrive.md
After a recent bug fix in the backend, we no longer have the limitation of not being able to trace fast redrives
```
/merge
```
> Remove Redrive Limitation Note

- content/en/profiler/enabling/supported_versions.md
- content/en/profiler/profile_types.md
- content/en/tracing/trace_collection/library_config/php.md
Adds I/O profiling for PHP to the docs. Granted, `v1.7.2` looks oddly specific, but this is due to a bug in `v1.7.0` that got fixed in the `v1.7.2` release which made sure that nearly no I/O was sampled before version `v1.7.2`.
```
/merge
```
> Add PHP I/O profiling

- content/en/coterm/_index.md
CoTerm can now be installed from `coterm.datadoghq.com`, which is nicer for branding than the current `update.coscreen.org`. This PR just updates the URL in the docs.
> Update CoTerm install URL

- config/_default/menus/main.en.yaml
- content/en/account_management/billing/containers.md
Product has requested that this page be added to the nav and have a link to the Container Discovery Management guide.
```
/merge
```
> DOCS-10102: Make containers billing page more discoverable

- content/en/metrics/summary.md
Remove the preview indicator from the query activity facet
```
/merge
```
> (DOCS-10350) Remove preview indicator

- assets/scripts/components/expression-evaluator.js
- assets/scripts/components/expression-language-parser.js
- assets/scripts/tests/expression-language-parser.test.js
- assets/styles/components/_expression-evaluator.scss
- content/en/dynamic_instrumentation/expression-language.md
- layouts/shortcodes/expression-repl.html
This pull request introduces a new REPL (Read-Eval-Print Loop) feature for the Expression Language allowing interactive experimentation with expressions directly within the documentation. The most important changes include adding the REPL setup in the JavaScript component, defining the styles for the REPL, updating the documentation to include the REPL, and creating a shortcode for the REPL.
Note that this is part two of #28079 
```
/merge
```
> feat: add an interactive REPL for EL evaluation

- content/en/getting_started/synthetics/mobile_app_testing.md
- content/en/synthetics/mobile_app_testing/_index.md
- content/en/synthetics/mobile_app_testing/mobile_app_tests/advanced_options.md
- content/en/synthetics/mobile_app_testing/mobile_app_tests/restricted_networks.md
- content/en/synthetics/mobile_app_testing/mobile_app_tests/results.md
- content/en/synthetics/mobile_app_testing/mobile_app_tests/steps.md
- content/en/synthetics/mobile_app_testing/settings/_index.md
Missed fixing some further reading links with the Mobile App reorg
```
/merge
```
> [DOCS-10351] fixing broken further reading links

- content/en/tests/test_impact_analysis/setup/ruby.md
Removes phrase that rails parallel testing is not supported for Test Impact Analysis, because it is supported now.
```
/merge
```
> [SDTEST-179] Remove phrase that rails parallel testing is not supported for Test Impact Analysis

- content/en/security/application_security/threats/inapp_waf_rules.md
There were several instances of in-app WAF in the content. 
The correct case is In-App WAF. 
That is the name of the feature and used in the UI.
> Correct case of In-App WAF feature name

- content/en/real_user_monitoring/browser/tracking_user_actions.md
Since v5 (2023) the Browser SDK collects Click actions most of the time, all those bullet points are not relevant anymore. Replaced with a mention about rage clicks, which should be more relevent.
```
/merge
```
> 📝 adjust click collection documentation

- content/en/api/latest/data-deletion/_index.md
- content/en/api/v2/data-deletion/_index.md
This endpoint was [created](https://github.com/DataDog/documentation/pull/26227), but the documentation was removed [[PR](https://github.com/DataDog/documentation/pull/26804)]. However, the _index.md files were not removed and caused it to show up in Google search results that led to a blank page.
```
/merge
```
> Remove documentation files for data deletion API

- content/en/database_monitoring/connect_dbm_and_apm.md
Adding warning that monitors might break when changing the obfuscation mode in APM trace agent.
```
/merge
```
> Add warning for changed SQL text

- content/en/logs/log_configuration/indexes.md
In the documentation for log indexes under `Exclusion Filters`, the second step uses the word "pipeline" rather than "index." This caused confusion for a user in the [Datadog Public Slack channel](https://datadoghq.slack.com/archives/C8PV5LVDX/p1741712562340849).
```
/merge
```
> Change the word pipeline to index in index documentation

- content/en/getting_started/devsecops/_index.md
On the "Getting Started with the DevSecOps Bundles" documentation page, there are a total of 3 broken links, one under each bundle tab.
The broken links relate to:
> After you install the Agent, enable Software Composition Analysis (SCA) for your environment.
> After you install the Agent, configure ASM for your environment.
**BEFORE**: I have attached a recording of the behavior that lead to the broken links.
https://github.com/user-attachments/assets/849531d6-c2ce-415d-8424-05e7b585d424
**AFTER**:
I changed the links to what I believe would be the best course of action [[SCA](https://docs.datadoghq.com/security/code_security/software_composition_analysis/)] [[ASM](https://docs.datadoghq.com/security/application_security/)], but please let me know if I should redirect to a different …
> fixed broken links for sca + asm in each tab for devsecops tiers

- content/en/network_monitoring/cloud_network_monitoring/setup.md
- content/en/network_monitoring/network_path/setup.md
This documents how to set up static paths on kubernetes.
This PR documents how to set up "individual paths" tracing for Network Path in Kubernetes.
This PR is dependent on [\[NPM-3754\] Add config to enable traceroute in sysprobe](https://github.com/DataDog/helm-charts/pull/1744) which creates a new version of the Agent helm chart.
```
/merge
```
[NPM-3754]: https://datadoghq.atlassian.net/browse/NPM-3754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NPM-3754] Document how to set up static paths on k8s

- content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/advanced_configuration.md
Updates the Advanced Configuration guide to include documentation regarding addViewLoadingTime API exposed by React Native SDK release v2.6.4 as described on  [RUM-6479](https://datadoghq.atlassian.net/browse/RUM-6479).
[RUM-6479]: https://datadoghq.atlassian.net/browse/RUM-6479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RUM-6479 - Add documentation for RumMonitor#addViewLoadingTime API on React Native guide

- content/en/database_monitoring/connect_dbm_and_apm.md
I [fixed the bug leading to application_name inflation](https://github.com/DataDog/dd-go/pull/174279) and Im now updating the documentation accordingly.
```
/merge
```
> Fix application_name inflation

- config/_default/menus/main.en.yaml
- content/en/security/code_security/iast/_index.md
- content/en/security/code_security/iast/security_controls/_index.md
- Add IAST security controls documentation
- Update supported IAST vulnerability list with vulnerability codes
```
/merge
```
> IAST Security Controls 

- .github/workflows/gif_check.yml
- .github/workflows/preview_link.yml
This PR pins the `tj-actions/changed-files` GitHub action to a SHA corresponding to a version that is not compromised. For details on the compromise, see:
- https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
- https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
Compromised versions leak CI secrets, so this repo's CI secrets will need to be rotated.
```
/merge
```
> hotfix: pin tj-actions/changed-files by SHA

- content/en/coterm/_index.md
- content/en/coterm/install.md
- content/en/coterm/usage.md
[CoTerm can now be installed via Homebrew](https://github.com/Homebrew/homebrew-cask/pull/205004), on macOS only. This PR mentions that in the CoTerm docs.
CoTerm now has [a page where you can view all recordings in your org](https://app.datadoghq.com/terminal-streams). This PR links to that page in the usage docs. 
It also unintentionally includes a few tiny formatting cleanups (sorry for the noise, VS Code makes them automatically when saving a Markdown file).
```
/merge
```
> CoTerm: Mention Homebrew install method and explorer page

- layouts/shortcodes/observability_pipelines/install_worker/linux_rpm.en.md
Adds an alert box for OP Linux RPM installation.
Preview: https://docs-staging.datadoghq.com/may/add-worker-apt-alert-box/observability_pipelines/set_up_pipelines/dual_ship_logs/amazon_data_firehose/?tab=linuxrpm#install-the-observability-pipelines-worker
```
/merge
```
> [DOCS-10378] Add alert box for linux RPM

- content/en/serverless/azure_app_services/azure_app_services_windows.md
- it was incorrecting linking to the general Metrics page
- I removed the link because the next link in the same sentence correctly links to the Azure Portal Guide and section needed
> fixing link in azure_app_services_windows.md

- content/en/integrations/guide/aws-cloudwatch-metric-streams-with-kinesis-data-firehose.md
DOCS-10385. Moves the site availability note to an alert box.
```
/merge
```
> DOCS-10385: Move site availability note to alert box

- content/en/software_catalog/_index.md
This PR fixes an issue where the definition list in the Key Terminology section of the Software Catalog page was unintentionally split due to the Note block 🙏
```
/merge
```
> Fix formatting issue in `Software Catalog` `Key Terminology` section

- content/en/network_monitoring/cloud_network_monitoring/setup.md
Removes note about CNM not support on GKE autopilot as it is supported now. This was missed in a previous PR https://github.com/DataDog/documentation/pull/27954
```
/merge
```
> Remove note about CNM not supported on GKE Autopilot

- content/en/error_tracking/backend/exception_replay.md
Exception Replay is still in private java, allowing us to update the required version without constraints. Version `1.47.0` includes important stability fixes, making it the preferred requirement over the previous `1.35.0`.
> [Exception Replay Docs] Bump `dd-trace-java` required version from `1.35.0` -> `1.47.0`

- content/en/infrastructure/process/_index.md
There is a new GA feature for creating custom rules to tag the commandline of processes. This provides guidance on where these rules can be defined and possible use cases.
[CTK-4763
](https://datadoghq.atlassian.net/browse/CTK-4763)
```
/merge
```
> Add a section for defining rules for process tags

- content/en/synthetics/troubleshooting/_index.md
Add the requirements for ICMP tests on Private Locations (net_raw capability and escalated privileges).
> Requirements for ICMP tests on Private Locations

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Per [DOCS-10126: Advertise branch naming convention as a hard requirement](https://datadoghq.atlassian.net/browse/DOCS-10126), this PR updates descriptions of our branch naming convention (`<username>/<branch_name>`) in contributor-facing content to make it clear that this is required for PRs to pass CI.
```
/merge
```
> [DOCS-10126] Explain branch naming convention as a hard requirement

- content/en/monitors/notify/_index.md
- content/en/service_management/incident_management/declare.md
- content/en/service_management/incident_management/incident_settings/_index.md
Incident app has a feature that allows automatically creating incidents from monitors using @incident- mentions in a monitor's notification message. This is similar to the way cases can be automatically created from monitors. This PR adds some explanation on this feature.
```
/merge
```
> Update documentation with automatic incident creation from monitors

- content/en/security/application_security/guide/_index.md
We already redirect from this guide to a copy in the Code Security section. 
We should delete the original since SCA is not part of ASM now.
> remove SCA guide from ASM section

- content/en/logs/log_collection/reactnative.md
- Update react native logs page to suggest to use DatadogProviderConfiguration instead of DdSdkReactNativeConfiguration
```
/merge
```
> [RUM] Update react native logs to suggest to use DatadogProviderConfiguration instead of DdSdkReactNativeConfiguration

- content/en/security/code_security/iast/security_controls/_index.md
Updates IAST security controls documentation with Node.js information:
- Compatibility requirements
- Examples
```
/merge
```
> IAST Security Controls - Node.js

- content/en/continuous_delivery/features/code_changes_detection.md
We add the same GitLab references of [this PR](https://github.com/DataDog/documentation/pull/27931) to the changes detection docs (they'll be merged together).
```
/merge
```
> Add GitLab references to Changes Detection docs

- content/en/opentelemetry/ingestion_sampling.md
This PR fixes a broken link on the **"Ingestion Sampling with OpenTelemetry"** page.  
The link in question was meant to direct users to instructions on how to configure the OpenTelemetry Collector, but it currently points to a page about head-based sampling instead.
It looks like the link was unintentionally replaced in [this PR](https://github.com/DataDog/documentation/pull/23481/files#diff-c612b782556f66748b7627c7c962ffcdf0832a8098ed819c44150e6f5ae1cf53L135-R141), so this change restores it to the correct reference.
To have your PR …
> Fix broken link on `Ingestion Sampling with OpenTelemetry` page

- content/en/data_security/agent.md
Adds a new telemetry metric that the agent will collect. 
Do not merge this PR until agent 7.64 is available. 
```
/merge
```
> Add auto_multi_line_aggregator_flush agent telemetry metric + description

- content/en/containers/kubernetes/control_plane.md
* Remove the differences between Helm and Operator Agent installation. Both methods support the same set of metrics for EKS control plane.
* Switch to autodiscovery v2 as it's easier to configure multiple checks
* Rely on tls_ca_cert instead of ignoring TLS handshake
* Remove some white spaces …
> [EKS control plane metrics] Unify both operator and Helm configuration

- content/en/tracing/other_telemetry/connect_logs_and_traces/dotnet.md
Adds a note about the trace-id and span-id being 64-bit decimal numbers.
[APMAPI-1205]
```
/merge
```
[APMAPI-1205]: https://datadoghq.atlassian.net/browse/APMAPI-1205?atlOrigin=eyJpIjoiNWRk …
> .NET Trace <> Log Correlation: Adds clarification that the trace-id and span-id correlation identifiers are 64-bit decimal numbers

- content/en/database_monitoring/guide/aurora_autodiscovery.md
I _think_ this will fix the doc reference to the IAM authentication page from the Aurora Autodiscovery page. Right now the raw markdown is shown on the page rather than the actual link to documentation page …
> Fix reference to IAM authentication from Aurora Autodiscovery

- content/en/tracing/metrics/metrics_namespace.md
This PR fixes minor formatting inconsistencies in the trace metrics documentation, including
- Ensuring the `Note` block is visually separated from the description
- Displaying `Metric Type` as a separate block for better clarity
- Renaming `XRay` to `X-Ray` to align with the official naming
To …
> Fix minor formatting issues in trace metrics documentation

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
https://datadoghq.atlassian.net/browse/DOCS-10418
```
/merge
```
> DOCS-10418

- content/en/service_management/workflows/trigger.md
This PR adds Software Catalog triggers to the Workflow Automation Triggers page, as requested by Dan Green (Software Catalog PM)
```
/merge
```
> [WF-10420] Add the software catalog trigger to the public docs

- content/en/security/code_security/static_analysis/setup/_index.md
The instructions for ignoring a path are wrong. This changes fixes it.
Merge after review
> Static Analysis: fix ignore instructions

- content/en/serverless/aws_lambda/installation/python.md
Replace class name and variable name `Datadog` with `DatadogLambda` because the former has been removed in the latest version of the CDK construct.
```
/merge
```
> Update example code for instrumenting Python Lambda using CDK

- content/en/observability_pipelines/install_the_worker.md
- content/en/observability_pipelines/troubleshooting.md
- Adds uninstall instructions
- Adds troubleshooting error
```
/merge
```
> [DOCS-10461] Add uninstall instructions and troubleshooting section

- content/en/serverless/step_functions/merge-step-functions-lambda.md
Updates our Step Functions + Lambda trace merging page to
* Show off new use cases
* Better organize the page as its getting longer
* Remove confusing/overly verbose language
```
/merge
```
> Update SFN Trace Merging

- content/en/tests/flaky_test_management/auto_test_retries.md
- content/en/tests/flaky_test_management/early_flake_detection.md
EFD and ATR were initially available as beta features in dd-trace-py 2.18. They are now available by default in dd-trace-py 3.x. This PR removes the beta warning and updates the minimum ddtrace version to 3.0.0. …
> [Test Optimization] Remove beta warning for EFD and ATR in Python

- content/en/watchdog/insights.md
If you look at the online version, the paragraph under graph_filter_tag.png is a smaller font than the rest of the document. I believe this is because it is missing a space above the paragraph. It's possible that the transform is trying to make that text into an image caption. Tested with Pandoc and it validated my assumption (it was a successful test).
Fix the font sizing on the text below the graph_filter_tag.png image.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it …
> Fix font variation

- content/en/tracing/services/services_map.md
- Clarify that while you can query nodes up to 30 days, only nodes with data appear in the graph.
- [DOCS-10484](https://datadoghq.atlassian.net/browse/DOCS-10484)
```
/merge
``` …
> Add clarification on node visualization for service map

- content/en/synthetics/explore/results_explorer/search_runs.md
As these facets have now been rolled out to all orgs and datacenters, we are removing the v0 and v1 references. I was having fits with the first table getting the Facets column aligned properly so ended up using HTML for this table to get it to display correctly :)  …
> [DOCS-10258] remove v0/v1 references from Synthetics facets

- content/en/tracing/trace_collection/custom_instrumentation/python/dd-api.md
This change points the dd-trace-api-py documentation link to a prettier HTML version than the previous bare YAML file.
> update dd-trace-api-py docs link to be prettier

- content/en/continuous_testing/environments/multiple_env.md
This PR fixes incorrect documentation about URL substitution syntax in Continuous Testing. The documentation previously claimed support for sed syntax and different delimiters, which was incorrect. The changes remove this misleading information.
To have your PR automatically merged after it …
> [SYNTH-18711] Update comment about sed syntax support

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
> Remove preview labels for k8s SSI

- layouts/shortcodes/sci-microsoft-sourcelink.en.md
- layouts/shortcodes/sci-microsoft-sourcelink.fr.md
- layouts/shortcodes/sci-microsoft-sourcelink.ja.md
- layouts/shortcodes/sci-microsoft-sourcelink.ko.md
Related to issue #https://github.com/DataDog/documentation/issues/28281. The Bitbucket link in the shortcode was flagged for returning a 404. This PR updates the link to use the correct URL. 
**Note**: Because the link is broken, I went ahead and updated the links in the translated versions of the shortcode. …
> Fix Bitbucket link in shortcodes

- content/en/integrations/guide/storage-monitoring-setup.md
Update the existing private Storage Monitoring setup docs with Google cloud storage support
Would love some guidance on alternatives to stagger the S3 & GCS setup instructions.
> Update Storage Monitoring setup docs with GCS instructions

- content/en/real_user_monitoring/browser/setup/client.md
Related to issue #https://github.com/DataDog/documentation/issues/28281. The example URL was rendering on the page as a clickable link. This PR fixes it by wrapping the URL in backticks. …
> Make example URL non-clickable in RUM Browser Monitoring docs 

- content/en/serverless/aws_lambda/installation/ruby.md
ddtrace gem was used for 1.x, from 2.0 it must be replaced with `datadog`: https://github.com/DataDog/dd-trace-rb/releases/tag/v2.0.0
Using the `ddtrace` gem results in mysterious circular require warnings.
```
/merge
```
> Update AWS Lambda containerized ruby instructions with new gem name

- content/en/account_management/org_settings/cross_org_visibility_api.md
When writing synthetic [tests](https://github.com/DataDog/terraform-config/pull/32976/files#diff-00b055ff406ac59521c957be38784622c32facbaf86a39e0259982518b1c4072) for cross org, we noticed that the
[documentation](https://docs.datadoghq.com/account_management/org_settings/cross_org_visibility_api/#api-endpoint) incorrectly stated that api and app key need to be passed in as query parameters. 
The app and api key need to be passed in as request headers for the cross org api to work properly. See linked synthetic test PR for usage of these headers. 
Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR …
> Update cross org api docs to include auth headers 

- content/en/real_user_monitoring/browser/setup/server.md
No need to explicitly call out Remote Configuration.
```
/merge
```
> Updated some of the wording and removed explicit callouts to RC Preview

- content/en/observability_pipelines/advanced_configurations.md
Related to issue #https://github.com/DataDog/documentation/issues/28281. The example URL was rendering on the page as a clickable link. This PR fixes it by wrapping the URL in backticks. …
> Make example URL non-clickable in OP Advanced Configurations doc

- content/en/integrations/guide/_index.md
- content/en/integrations/guide/azure-count-metric.md
- content/en/integrations/guide/azure-status-metric.md
Remove remaining references to the azure status (`azure.*.status`) metric, which has been deprecated since 2023 and no longer exists in the product. I've change the name of the file that used to describe it and the azure count metric to refer only to count, but retained the old name as an alias so we don't break any links. 
If your branch doesn't follow this format, rename it …
> [AZINTS-3322] Remove Azure status metric references

- content/en/actions/connections/_index.md
You can now use connection groups in App Builder, so we want to remove this warning box.
```
/merge
```
> [APPS-2242] Remove connection groups warning

- content/en/opentelemetry/guide/otel_demo_to_datadog.md
Address Hotjar feedback:
> To configure the OpenTelemetry Collector, open src/otelcollector/otelcol-config-extras.yml and add the following to the file: is incorrect hostname: "otelcol-docker" should be hostname: "otel-collector-docker" based on the docker-compose.yml file service name.
To have …
> Fix hostname in Sending Data from the OpenTelemetry Demo to Datadog

- content/en/observability_pipelines/destinations/_index.md
Fix supported field for Elasticsearch to `Index`. 
```
/merge
```
> [DOCS-10549] Fix Elasticsearch template syntax field

- content/en/serverless/aws_lambda/installation/ruby.md
Follow-up for #28548 , replacing other references too.
https://github.com/DataDog/dd-trace-rb/releases/tag/v2.0.0
```
/merge
```
> Further replacements of ddtrace with datadog gem

- content/en/synthetics/guide/monitor-usage.md
Add link to Datadog's Pricing page for browser tests
> Add link to Datadog's Pricing page for browser tests

- content/en/serverless/aws_lambda/troubleshooting.md
1. The link is partially broken. It points to a section which has been renamed, so the link actually goes to the top of the page.
2. The link points to a README file in GitHub instead of to our doc site, which doesn't have translation support.
Change the broken link to one pointing to Datadog's doc site and make it point to the correct section.
If your branch doesn't follow …
> Fix doc for troubleshooting Lambda

- content/en/real_user_monitoring/session_replay/browser/_index.md
Add a callout that using the force option will not force start sampling of a session, it will only force start a replay of an already sampled session.
Internally there has been some confusion around the force option, specifically thinking that it would force start sampling of the entire session, not just force start the replay of an already sampled session. Added a callout to clarify the behavior.
- [ x ] Ready for merge
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check …
> Force Session Replay update

- content/en/serverless/azure_functions/_index.md
This PR updates the Python Azure Function instrumentation instructions to use `ddtrace.auto` instead of `patch_all().
In the upcoming release of v3.4.0 of the Python Tracer `patch_all()` will be deprecated. `ddtrace.auto` is recommended to use instead.
https://github.com/DataDog/dd-trace-py/releases/tag/v3.4.0 …
> Use ddtrace.auto in favor of patch_all for python azure function instrumentation

- assets/scripts/components/table-of-contents.js
- package.json
- yarn.lock
Update the Cdocs build to use the hooks interface [shipped in v1.1.3](https://github.com/DataDog/corp-node-packages/pull/103) of the Cdocs-Hugo integration.
This PR is against a feature branch. It doesn't require your review unless you're @hestonhoffman.
Staging link: https://docs-staging.datadoghq.com/jen.gilbert/cdocs-hooks-refactor/real_user_monitoring/guide/proxy-mobile-rum-data
> Update the TOC logic to use the new Cdocs hooks interface

- content/en/synthetics/platform/private_locations/_index.md
This PR moves this callout/alert to the Permissions section and simplifies the wording. Also uses a red alert box to make the alert more prominent.
Additionally added the VULN # to the commit for tracking. …
> moving alert to permissions section/ VULN-7528

- content/en/logs/workspaces/sql_reference.md
In preparation for the GA release for Log Workspaces, we're reviewing public documentation and updating them to match the latest SQL functionality supported by the product. 
This PR focusses on:
- Fixing incorrect parameters for existing functions
- Ensuring consistent type and variable names in the function definitions
- Adding supported extraction types, cast target types, and date/time formatting options
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with …
> Update SQL reference guide for Log Workspaces

- content/en/logs/workspaces/sql_reference.md
A follow-up of #28591 where we're adding documentation for new functions that are now supported in Log Workspaces. This is in preparation for our GA launch. 
Adding documentation for the following functions: 
- `cardinality`
- `array_position`
- `strpos`
- `string_to_array`
- `split_part`
- `array_agg`
- `unnest`
Jira: https://datadoghq.atlassian.net/browse/LOGSQ-830
If your …
> Add documentation for new SQL functions available for Log Workspaces

- content/en/account_management/audit_trail/events.md
This PR adds a new Infrastructure Monitoring section to the Audit Trail Events documentation. It includes two new events for Container Image Trends configuration:
- Enable Container Image Trends
- Disable Container Image Trends
This addition helps users track and audit changes to Container Image Trends settings in their Datadog account.
If your branch doesn't follow this …
> [CXP-2003] Add Infrastructure Monitoring section to Audit Trail Events

- content/en/dynamic_instrumentation/enabling/nodejs.md
The Node.js tracer now supports templates and conditions (from version 5.48.0), so these two items are now removed from the list of unsupported features
Do not merge until version 5.48.0 have been released to npm: https://www.npmjs.com/package/dd-trace
I'll make sure to tick the "Ready for merge" check box below once it's ready.
If your branch doesn't follow this format, rename …
> [Debugger] Update Node.js docs

- content/en/synthetics/mobile_app_testing/_index.md
- content/es/synthetics/mobile_app_testing/_index.md
- content/ja/synthetics/mobile_app_testing/_index.md
- content/ko/synthetics/mobile_app_testing/_index.md
This documentation fix prevents customers from encountering issues when trying to configure mobile application version paths in their CI pipelines. Using the incorrect field name (config) would just cause the field to be skipped, while the correct field name (testOverrides) allows proper test execution using the specified mobile application.
The change ensures the documentation accurately reflects the required JSON structure for successful mobile app test configuration in CI environments.
The field is correctly used here : https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration/?tab=npm#test-files
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward …
> Fixed wrong field name in json template in mobile app testing documentation

- content/en/error_tracking/error_grouping.md
Added the React Native Tab with content from [eng](https://datadoghq.atlassian.net/browse/DOCS-9781)
The push seems to imply a modification of the entire page's content.
```
/merge
```
> DOCS-9781- added the react native content

- content/en/data_jobs/databricks.md
The DD API IPs are not required to be allowed in Databricks workspaces. The addition to the docs was a mistake – In the context of DJM, when a user "adds a workspace" the user is simply creating an integration account via the /integrations page; IPs do not need to be allow-listed for this. 
The webhook IPs are used, and the docs for them are in the preceding paragraph.
If your …
> [DJM-732] Remove DD API IPs from required IPs

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
The Dynamic Instrumentation feature does not support bundling and should therefore not be turned on if the users application is bundled (the feature is disabled by default).
The reason why it doesn't support bundling is that the feature relies on Node.js Worker Threads, and the bundler doesn't correctly re-write the call to start the worker thread (like it does with all `require` calls). Instead Node.js just tries to start the worker thread as if the code wasn't bundled, and hence can't find the file to load in the worker thread at the expected location. This will result in the worker thread emitting an error like this:
```
Error: Cannot find module 'path/to/app/root/devtools_client/index.js'
at Module._resolveFilename (node:internalmodules/cjs/loader:1077:15)
at Module._load …
```
> [nodejs] Add info about bundling the debugger

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
Fixing Typo in the SSI configuration docs. Per this changelog, the configuration should be `ddTraceVersions` instead of `ddTracerVersions` per this [Changelog](https://github.com/DataDog/datadog-agent/blob/5c3c17908079421d4b663c6dea60b2965efe623f/CHANGELOG-DCA.rst#new-features)
Fixes a typo for SSI configuration settings …
> Fix typo in SSi docs

- content/en/tests/correlate_logs_and_tests/_index.md
Adds documentation for agentless logs submission in Ruby. Fixes small issue with agentless logs submission page: .NET and Swift agentless instructions were outside of agentless tab.
``` …
```
> [SDTEST-426] docs for agentless logs submission in Ruby

- content/en/real_user_monitoring/mobile_and_tv_monitoring/unity/advanced_configuration.md
API for the Unity `AddError` method was incorrect. I updated it with a better example.
> Fix incorrect Unity `AddError` documentation.

- content/en/security/sensitive_data_scanner/scanning_rules/custom_rules.md
Currently, `security/sensitive_data_scanner/guide/best_practices_for_creating_custom_rules/` contains a link to `security/sensitive_data_scanner/regular_expression_syntax` that doesn't work.
I've opted to add `security/sensitive_data_scanner/regular_expression_syntax` as an alias to what I assume is the intended page, both to fix this particular link but also to allow external links to that page to work.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with …
> Add alias to SDS custom rules page

- content/en/agent/fleet_automation/_index.md
Updated permissions table to add new permissions, hierarchy of Send Remote Flare, updated use case sentence. Approved by @vignesh
Originated from @ethandebnath7702's PR: https://github.com/DataDog/documentation/pull/28793
To have your PR automatically merged after it receives the required …
> Update Fleet Automations permissions table

- content/en/profiler/enabling/java.md
Java Profiler enablement docs are not explicitly stating support (or the lack of) for Java 21.
This simple change is fixing that issue
```
/merge
```
> Clarify support for Java 21

- content/en/serverless/google_cloud_run/_index.md
Problem: The Terraform code for instrumenting Google Cloud Run is wrong. I tried to follow the doc to add "labels", which resulted in an error:
> An argument named "labels" is not expected here.
This PR fixes the way to add labels. Labels should be at: `google_cloud_run_service.template.metadata.labels`. See more in the doc: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#argument-reference
I tested it and it worked.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a …
> Fix Terraform code for Google Cloud Run

- content/en/serverless/google_cloud_run/functions_gen1.md
Updated example nodejs function to include the SCL initialization line and to initialize the trace handler prior to invocation.
```
/merge
```
> Update functions_gen1.md example nodejs function

- content/en/serverless/aws_lambda/configuration.md
Fix incorrect link for "Datadog AWS integration", bug because of an incorrect link numbering.
The "Datadog AWS integration" link was incorrectly linking to https://app.datadoghq.com/security/appsec?column=time&order=desc
[See live documentation](https://docs.datadoghq.com/serverless/aws_lambda/configuration/?tab=datadogcli#connect-telemetry-using-tags)
> Fix link on AWS Lambda documentation

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
While you can set these environment variables in `ddTraceConfigs` it might lead to a mismatch between infrastructure labels and the service.
```
/merge
```
There is other work to follow up with linking to UST configuration (labelsAsTags, specifically)
> Remove mention of DD_SERVICE/DD_ENV on SSI configuration

- content/en/cloudcraft/getting-started/connect-amazon-eks-cluster-with-cloudcraft.md
Update the Cloudcraft EKS documentation to remove usage of `aws-auth ConfigMap` as it's deprecated, and use access entries instead.
Instructions need to be updated in `web-ui` too. @srividya-rajagopalan should this wait to be merged until I send the PR for that part?
Please wait until someone from the Cloudcraft team review the changes before merging.
> [CLOUDCRAFT 1192] Update EKS documentation to reflect modern expectations

- content/en/agent/basic_agent_usage/windows.md
- content/en/agent/guide/fips-agent.md
- content/en/agent/guide/windows-agent-ddagent-user.md
By default, `msiexec` does not print if it succeeds or fails, and it puts a log file in a temporary directory with a random filename. This makes it difficult for customers and support to collect the installer log file.
Improve customer experience by
- print message if the installer fails
- include the logfile parameter with a known file path
also switches from code fence to code-block so we get the nice copy button
https://datadoghq.atlassian.net/browse/WINA-1361
Would be nice to add `SITE={{< region-param key="dd_site" code="true">}}` but it doesn't seem to be supported in code-block
> add msiexec exit code and log file params

- content/en/serverless/azure_app_services/azure_app_services_linux.md
v1.11.0 of the Datadog Linux Wrapper script for Azure App Services was recently released. This PR updates the documentation to point to this latest version of the script.
https://github.com/DataDog/datadog-aas-linux/releases/tag/v1.11.0 …
> Bump version of azure app services linux wrapper to 1.11.0

- content/en/security/application_security/threats/setup/threat_detection/gcp-service-extensions.md
- layouts/shortcodes/appsec-getstarted-2-plusrisk.en.md
- Add a new tab for installation with Terraform scripts
- Rework categories (specially environment variable configuration)
- Reword for better understandability
- Add a note about opened ports …
> Update GCP Service Extensions documentation

- content/en/database_monitoring/setup_postgres/aurora.md
On the live documentation site, the link to the Aurora autodiscovery setup guide does not link to the correct address, and this PR should fix that.
```
/merge
```
> fix link to Aurora autodiscovery guide

- content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/advanced_configuration.md
This update reflects a change introduced in version **2.6.5** of the React Native SDK. The method previously used for setting user information—`setUser`—has been renamed to `setUserInfo`. This PR updates the documentation accordingly to ensure consistency with the current SDK API. 
[PR introducing the change](https://github.com/DataDog/dd-sdk-reactnative/pull/818)
- Please confirm that passing an empty object to `setUserInfo` is the recommended way to clear user data upon logout.
**Note:** It was clarified that the correct way to clear the user object it's by using `setUser` by @sbarrio on the review comment.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash …
> [RUM] React Native - Update setUser method to setUserInfo

- content/en/dynamic_instrumentation/enabling/nodejs.md
As the title says. While 5.39.0 still technically will work, version 5.48.0 is recommended for the best experience, as it supports all the features available in the UI.
```
/merge
```
> [Debugger] Bump minimum Node.js tracer version

- content/en/synthetics/mobile_app_testing/mobile_app_tests/restricted_networks.md
This PR breaks out the IP addresses on the Mobile App Restricted networks page by regions, with the addition of Mobile App [testing devices in the EU region](http://localhost:1313/synthetics/mobile_app_testing/#devices), we needed to break out this page for users in the EU region testing on restricted networks.
Also adds gov callout
If your branch doesn't follow this format, …
> [DOCS-10699] add regions to restricted networks page

- package.json
- yarn.lock
This bumps the Cdocs package version to enable improved logging around key characteristics of the Cdocs environment.
We recently had a broken Cdocs build in the merge queue, and it surfaced two issues I wanted to resolve:
- It was not obvious that the customization config was missing, I just knew that this was logically the problem. We never want such a fundamental issue to be that opaque.
- Even knowing the config was likely missing, the cause was still difficult to pin down. Several factors contribute to how the configuration is resolved, such as the default language detected by Cdocs.
Compilation logic is not impacted, but just to verify as a reviewer:
- You can view the relevant changes in https://github.com/DataDog/corp-node-packages/pull/107, which passed all checks.
- You can see …
> Improve Cdocs logging to catch environment issues

- content/en/agent/logs/log_transport.md
The [log transport doc](https://docs.datadoghq.com/agent/logs/log_transport/?tab=tcp&site=gov) mentions that the USfed site supports TCP but [it does not](https://docs.datadoghq.com/logs/log_collection/?tab=tcp&site=gov#custom-log-forwarding).  This PR changes that …
> Added that TCP is not available for gov site

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/java.md
This PR removes the use of the deprecated stackdepth setting: The `FlightRecorderOptions=stackdepth=256` is now set automatically and not the recommended way of controlling stack depth any more.
See https://github.com/DataDog/documentation/pull/24446 where this was removed from the profiler docs, but I noticed this reference was still left behind on this page.
If your branch …
> [PROF-11671] Remove use of deprecated stackdepth setting

- content/en/error_tracking/backend/getting_started/single_step_instrumentation.md
- content/en/error_tracking/guides/enable_apm.md
- content/en/error_tracking/guides/enable_infra.md
Update datadog operator setup instructions for standalone backend error tracking, to remove redundant`features.apm.enabled:true` flag.
> [error tracking] Remove redundant `features.apm.enabled:true` config

- content/en/tracing/trace_collection/library_config/java.md
- content/en/tracing/troubleshooting/quantization.md
* Adds tracer-specific config for quantization of APM data.
* Documents `dd.trace.http.server.path-resource-name-mapping` which was missing. [Added here](https://github.com/DataDog/dd-trace-java/pull/2761).
* Links to related Java and PHP options in Library Config pages.
To have your PR …
> Explain Tracer Options for Quantization of APM Data

- content/en/integrations/guide/storage-monitoring-setup.md
> [AZINTS-3391] add azure storage monitoring setup

- content/en/tests/setup/junit_xml.md
We don't use the `test.bundle` tag for computing test fingerprints for JUnitXML tests ([code](https://github.com/DataDog/logs-backend/blob/prod/domains/event-platform/libs/processing/processing-common/src/main/java/com/dd/logs/processing/processors/CITestFingerprintProcessor.java#L78)).
This was causing confusion for a customer.
> [SDTEST-1941] Remove `test.bundle` tag mention from JUnitXML fingerprint computation

- assets/scripts/components/dd-browser-logs-rum.js
adds a custom rum action for cdocs
thought it would be interesting see users interacting once usage ramps up
```
/merge
```
https://docs-staging.datadoghq.com/brian.deutsch/web-6385-rum-acti …
> [web-6385] custom rum action for cdocs

- layouts/_default/baseof.html
broken hugo build in sources due to markdoc-assets partial not being in the repo and not running cdocs there.
```
/merge
```
> [web-6390] fix sources integration preview by not rendering markdoc-assets

- content/en/database_monitoring/data_collected.md
Adds a query retention period to the Database Monitoring Data Collected doc. Requested by PM.
```
/merge
```
> DBM: Add query retention period section

- content/en/cloud_cost_management/budgets.md
> Add notes about API creation

- content/en/cloud_cost_management/_index.md
We have recently tightened up our enforcement of the Cloud Cost Management Read and Write permissions. As a result, we want to provide some more granular detail to users regarding the behavior of the permissions.
Happy to take any feedback for how to structure this! …
> [CCC-695] Add details for CCM Read/Write permissions

- Makefile
The pull and push file action seems to be failing when you don't have the dd-source repo cloned locally. It's affecting our preview builds as well. I think it's because of the way we're sparse cloning the repo in the Makefile. This adds the extra directory we need to prevent the build from failing locally and in preview 🤞  …
> Add files to dd-source clone

- content/en/cloud_cost_management/recommendations/_index.md
> Cost Recommendations ga updates

- content/en/real_user_monitoring/rum_without_limits/metrics.md
> [RUM][RWOL] Fix name of rum.measure.view.time_spent metric

- content/en/network_monitoring/network_path/setup.md
Adds missing config to the Windows setup docs for Network Path Static paths , and moves the Helm Agent version requirement to the top of the tab as it was in the wrong place
```
/merge
```
> [DOCS-10691] Fix windows setup on Network path docs

- content/en/account_management/rbac/granular_access.md
- content/en/actions/private_actions/use_private_actions.md
This PR adds to Private Actions documentation to cover runner permissions handling:
- updates the doc `use_private_actions`
- adds runner to the list of grace resources in `account_management`
This PR doesn't do the i18n for this new part.
To have your PR automatically merged after it receives …
> [ACTP-631] add permissions handling to private action runner docs

- content/en/real_user_monitoring/session_replay/mobile/setup_and_configuration.md
Currently, our documentation for Mobile Session Replay Setup has two step 3s in the [React Native](https://docs.datadoghq.com/real_user_monitoring/session_replay/mobile/setup_and_configuration/?tab=reactnative) and [Kotlin multiplatform](https://docs.datadoghq.com/real_user_monitoring/session_replay/mobile/setup_and_configuration/?tab=kotlinmultiplatform) tabs. 
This fixes the issue in the React Native tab, but it's unclear to me why the issue on the Kotlin page is present -- Github renders the numbers correctly.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, …
> Fix numbering for Mobile Session Replay Setup guide

- content/en/security/application_security/serverless/_index.md
Reverting the flag name change from enableAAP -> enableASM. The correct flag is listed in our serverless framework repository: https://github.com/DataDog/serverless-plugin-datadog. Though we renamed the product, the flag stayed the same in the code. 
To have your PR automatically merged after it …
> Update _index.md enableAAP -> enableASM

- content/en/tests/setup/junit_xml.md
This part of the documentation was incorrect, manually providing the source file is not an alternative as using the Github Integration at the moment. Instead, it is a workaround if the user's plugin does not generate XML files with the source file.
To have your PR automatically merged after it …
> [SDTEST] Junitxml manually providing source file fixes

- content/en/developers/ide_plugins/idea/_index.md
- content/en/developers/ide_plugins/visual_studio/_index.md
- content/en/developers/ide_plugins/vscode/_index.md
Resolves [DOCS-10722](https://datadoghq.atlassian.net/browse/DOCS-10722) by adding a site region alert to all IDE plugin docs pages for the US1-FED site.
```
/merge
```
[DOCS-10722]: …
> [DOCS-10722] Add site region alert to all IDE plugin pages

- content/en/tracing/trace_collection/library_config/java.md
Add the `dd.jdk.socket.enabled` option from [this PR](https://github.com/DataDog/dd-trace-java/pull/8314) to our documentation.
```
/merge
```
Not sure if this config option should be …
> Update java.md for `dd.jdk.socket.enabled` config option

- content/en/serverless/step_functions/installation.md
Add doc for instrumenting Step Functions using AWS SAM.
```
/merge
```
> [SVLS-3965] Add doc for instrumenting Step Functions using AWS SAM

- content/en/opentelemetry/setup/ddot_collector/install.md
Explicitly add required `DD_OTELCOLLECTOR_ENABLED` env variable to the `otel-agent` collector.
This fix is required for Operator v1.14; after 1.15 release we could remove it.
> OTAGENT-391 Add otel-agent evn var to enable OTel Collector

- content/en/profiler/enabling/dotnet.md
- content/en/profiler/profile_types.md
We got customer cases where the Allocated Memory samples were not available in our UI. This is expected in .NET Framework so we need to change the documentation and our UI to make it explicit …
> [Profiling] Update the status of Allocated Memory; not available for .NET Framework

- content/en/integrations/faq/list-of-api-source-attribute-value.md
Previously the search term used the alias of the integrations which didn't work for searching in Event Explorer. Fix the search terms to use source_type_name values with spaces replaced by underscores.
To have your PR automatically merged after it receives the required reviews, add the following …
> Fix the integrations sources search term

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs.md
Improve the Node.js tracer documentation to avoid confusion when working with ES Modules.
```
/merge
```
> Document advanced Node.js tracer init options

- content/en/security/code_security/troubleshooting/_index.md
Updates the text to mention single backslashes and not double backslashes
> Changed double backslashes to single

- content/en/dora_metrics/setup/deployments.md
Removes a limitation that was added incorrectly: for rebased branches and commits, we consider the timestamp at which the original commit was created. This is the desired logic, so no need to make any clarification about it.
> Remove incorrect DORA limitation about rebase

- content/en/integrations/guide/aws-manual-setup.md
- Update the instructions to reflect changes in AWS
- Updates for style, clarity, and consistency
```
/merge
```
> [DOCS-10783] Update instructions

- content/en/integrations/guide/azure-troubleshooting.md
- content/en/logs/guide/azure-logging-guide.md
Updates the docs due to the migration of the event hub forwarder to nodejs model v4: https://github.com/DataDog/datadog-serverless-functions/pull/934
```
/merge
```
> [AZINTS] update event hub forwarder installation docs

- content/en/observability_pipelines/advanced_configurations.md
- content/en/observability_pipelines/troubleshooting.md
Adds info about the `/health` endpoint that load balancers can use to check the health of the Worker.
```
/merge
```
> [DOCS-9475] Add /health endpoint to docs

- content/en/dashboards/sharing/scheduled_reports.md
Slack reports are not supported in govcloud, but the docs don't make that clear. This adds a warning explaining that.
Screenshot from preview build:
```
/merge
```
> [CRP-1138, reporting] Add warning to scheduled report docs, slack is unsupported in gov

- content/en/tests/setup/python.md
Explains and adds details about the `pytest-xdist` incompatibilities when used together with `ddtrace`.
```
/merge
```
> update docs regarding pytest-xdist incompatibilities

- content/en/opentelemetry/integrations/runtime_metrics/_index.md
> Remove workaround styling from OTel runtime metrics

- content/en/real_user_monitoring/correlate_with_other_telemetry/apm/_index.md
Docs linked to the Setup page which had no section for Automatic Resource Tracking. Moved to the Advanced Configuration page under "Automatically track resources"
None
> Fix broken link in Correlate RUM and Traces for Flutter

- content/en/synthetics/platform/private_locations/_index.md
This PR migrates the Install collapse section which was quite large, back into tabs format to take advantage of the new tab cdocs layout for large sets of tabs.
```
/merge
```
> Synthetics Private locations: restructure install collapse section into tabs

- content/en/security/application_security/exploit-prevention.md
DOCS-10913
EM has asked for this update because all of PHP is not supported in the end because not enabled by default.
> DOCS-10913 remove php support in Exploit Prevention

- content/en/tracing/troubleshooting/tracer_debug_logs.md
Remove Python from the list of languages that support tracer flare.
```
/merge
```
> [APM][Tracer Flare] Unlist Python

- content/en/data_security/data_retention_periods.md
The docs update to Error Tracking retention from [this change](https://github.com/DataDog/documentation/pull/27418/files) got lost on the new data retention page.
```
/merge
```
> fix Error Tracking retention docs

- content/en/infrastructure/containers/_index.md
- content/en/infrastructure/process/_index.md
- content/en/infrastructure/process/increase_process_retention.md
- content/en/monitors/types/process.md
Changes in this PR include:
- Remove reference to dedicated process agent where appropriate, as process and container collection now runs in the core agent by default on Linux
- Remove references to deprecated `DD_PROCESS_AGENT_ENABLED` config, replacing with new configs.
- Link to recently-released processes custom tagging functionality where appropriate
- Various grammatical and spelling fixes
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, …
> [CXP-2151] Updates to Processes and Containers documentation

- content/en/serverless/aws_lambda/profiling.md
There was a typo in Minimum layer version requirement for nodejs. Its mentioned as 87, but our latest release is 78
```
/merge
```
> Update Minimum layer version for nodejs profiling

- config/_default/menus/main.en.yaml
- content/en/serverless/aws_lambda/configuration.md
- content/en/serverless/aws_lambda/fips-compliance.md
- content/en/serverless/aws_lambda/installation/_index.md
- content/en/serverless/aws_lambda/installation/dotnet.md
- content/en/serverless/aws_lambda/installation/go.md
- content/en/serverless/aws_lambda/installation/java.md
- content/en/serverless/aws_lambda/installation/nodejs.md
- content/en/serverless/aws_lambda/installation/python.md
- content/en/serverless/aws_lambda/installation/ruby.md
Adds documentation for proper FIPS usage in AWS Lambda
```
/merge
```
> AWS Lambda FIPS

- content/en/security/code_security/software_composition_analysis/setup_static/_index.md
Since we can only infer certain default branches on the backend, this PR explicitly adds them to avoid ambiguity.
> [K9VULN-4829] Update note to include inferable default branches

- content/en/software_catalog/endpoints/explore_endpoints.md
Docs previously stated that endpoint ownership information was inherited from an associated service definition. Correcting this to clarify that this is inherited from an API definition.
``` …
```
> Correcting incorrect information in APM docs

- content/en/getting_started/opentelemetry/_index.md
When going through the getting started page for OpenTelemetry at Datadog, there is a mismatch between the files the instructions say to access and the actual files in the demo repository for the Java Calendar demo. 
The instructions refer to `docker-compose-otel.yml` but this file was renamed previously to `docker-compose-otelcol.yml`. I updated all references to this file in the instructions to address the correct file name.
Also, the instructions refer to this line of code in the demo repo: `OTEL_LOGS_EXPORTER=otlp`
This code was previously removed due to otlp being the default value for exporting logs and thus having no effect.
I removed the corresponding step from the instructions, and adjusted the next step accordingly.
> Update instructions to match the demo repo

- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
The current Ingestion Mechanism page recommends the use of [DD_APM_MAX_TPS, which is deprecated](https://github.com/DataDog/datadog-agent/blob/ab26c905a9d39daf8e41dd9e7b4f3e408d69fe41/pkg/config/config_template.yaml#L1174).
While much of the text has been edited to reflect this deprecation (i.e. the yaml field has been updated), it looks like two smaller aspects were left unedited.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such as broken …
> Do not suggest deprecated variable name

- content/en/monitors/guide/alert_aggregation.md
- content/en/real_user_monitoring/mobile_and_tv_monitoring/android/setup.md
- content/en/tracing/trace_collection/custom_instrumentation/android/otel.md
This pull request updates documentation for Android setup and custom instrumentation, focusing on improving clarity and providing additional examples. The most important changes include adding instructions for using `DatadogInterceptor` with `OkHttpClient` and updating code snippets to correct terminology for accessing tracers.
* Added instructions for using `DatadogInterceptor` as a network interceptor with `OkHttpClient` to automatically create RUM resources and Spans for network requests. Included Kotlin and Java code examples.
* Clarified that `TracingInterceptor` can be used instead of `DatadogInterceptor` if only Spans are needed, without RUM resources.
* Updated Kotlin and Java code snippets to replace `tracerProvider` with `tracer` for accessing tracers via …
> Update the Android  OkHttp instrumentation docs and fix some Otel docs

- content/en/security/code_security/static_analysis/generic_ci_providers.md
- content/en/security/code_security/troubleshooting/_index.md
This is a continuation to https://github.com/DataDog/documentation/pull/29452 as I missed a couple cases where this note was displayed on different pages.
> [K9VULN-4829] Update all default branch notices

- content/en/security/sensitive_data_scanner/scanning_rules/_index.md
- content/en/security/sensitive_data_scanner/scanning_rules/library_rules.md
Add preview box for Human Name PII Detection
```
/merge
```
> [DOCS-10927] Add preview box for human name PII detection

- content/en/profiler/enabling/java.md
Update Minimum requirement- enabling CPU profile type for DD profiler
Current:
Its mentioned as JDK11+ which is wrong
Modification:
Follow the minimum requirement section.
```
/merge
```
> Update Minimum requirement- enabling CPU profile type

- content/en/real_user_monitoring/browser/advanced_configuration.md
Updates the advanced configuration from the Browser SDK, to set the usr.id as required attribute after the version 6.4.0.
- [Changelog 6.4.0](https://github.com/DataDog/browser-sdk/blob/main/CHANGELOG.md#v640)
- [PR: 3562](https://github.com/DataDog/browser-sdk/pull/3262)
> [RUM] Browser SDK: Update usr.id to required in advanced configuration

- config/_default/menus/main.en.yaml
- content/en/llm_observability/evaluations/_index.md
- content/en/llm_observability/evaluations/ootb_evaluations.md
- content/en/llm_observability/evaluations/submit_evaluations.md
- content/en/llm_observability/guide/_index.md
- content/en/llm_observability/setup/_index.md
- content/en/llm_observability/terms/_index.md
- Standardize around "Submit Custom Evaluations" for evals submitted via the API/SDK. The [original review](https://github.com/DataDog/documentation/pull/29421#discussion_r2103320152) suggested to use "submit evaluations" but we would like to more clearly distinguish between this feature and OOTB evals.
- Clean up further reading links to point to the top level Evaluations section
- Reduce verbiage for the "Select and enable evaluations" section, create sub bullet points, highlight optional steps
> [MLOB-2691] Small Evaluations documentation fixes

- content/en/tracing/trace_collection/custom_instrumentation/nodejs/dd-api.md
Describes the new `dd-trace-api` module, to be used with `dd-trace` in Node.js. Much like the similar module for Python, this exists so that single-step users don't have to opt out in order to use the API.
> add dd-trace-api doc for Node.js

- content/en/service_management/incident_management/guides/_index.md
- content/en/service_management/incident_management/zoom_integration.md
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Reverts DataDog/documentation#29480
> Revert "Add a reference links to incident integrations"

- content/en/logs/workspaces/_index.md
Adds a link to the SQL syntax documentation to the Logs Workspaces public documentation. Requested by the Workspaces team.
Currently there's no link here:
> Add SQL syntax docs link to workspaces docs

- content/en/tracing/trace_collection/library_config/dotnet-core.md
- content/en/tracing/trace_collection/library_config/dotnet-framework.md
Updates the note about the `DD_TRACE_METHODS` configuration value in the .NET tracer, pointing users towards the Continuous Profiler instead.
```
/merge
```
If the consensus is that this is …
> [.NET] Point users of `DD_TRACE_METHODS` to the Continuous Profiler

- .github/PULL_REQUEST_TEMPLATE.md
- repository.datadog.yml
- Due to the delay in github reporting status updates, we're going to disable the ability to use `/merge` for now and will use the integrated system of the merge button in github
```
/merge …
```
> Disable the merge queue

- content/en/containers/monitoring/autoscaling.md
Make some minor updates to the autoscaling documentation:
* Use a newer agent version
* Update some typos in the operator configuration
* Configure collection of the new `datadogpodautoscaler` resource version
* Configure local fallback
* Remove fields that are available by default in helm
[6/5/2025] Merge queue has been disabled on …
> [container autoscaling] Update autoscaling docs to use newer agent version

- content/en/dashboards/widgets/retention.md
- content/en/logs/explorer/search.md
- content/en/notebooks/advanced_analysis/_index.md
Product features not available for USFED1 sites:
- Notebooks Advanced Analysis
- Retention widget
- typo in NLQ …
> Add limitation for USFED1

- content/en/tracing/trace_collection/compatibility/go.md
The old link returned a 404. I went up a directory and navigated to the v2 link.
from:
https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/confluentinc/confluent-kafka-go/v2
To:
https://pkg.go.dev/github.com/DataDog/dd-trace-go/contrib/confluentinc/confluent-kafka-go/kafka.v2/v2
Updates the kafka v2 link. The existing link returns a 404. …
> Update go.md to reflect correct link

- content/en/security/code_security/software_composition_analysis/setup_static/_index.md
This adds a section to our documentation that details our new Reachability Analysis feature.
> [K9VULN-5598] Add section for reachability analysis 

- content/en/observability_pipelines/set_up_pipelines/_index.md
> [DOCS-11173] Add preview for OP API/TF

- content/en/tracing/trace_collection/library_config/java.md
Updates the note about the `DD_TRACE_METHODS` configuration value in the Java tracer, pointing users towards the Continuous Profiler instead. Similar to https://github.com/DataDog/documentation/pull/29581.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed …
> [Java] Point users of DD_TRACE_METHODS to the Continuous Profiler

- content/en/account_management/org_settings/cross_org_visibility.md
https://datadoghq.atlassian.net/browse/DOCS-11114
https://datadoghq.atlassian.net/browse/DOCS-10482
Additions and fixes to Cross-Org Management:
- Add mention of Log Management support
- Clarify site requirement
- Add granular access control for connections
- Clean up some wording …
> DASH updates for Cross Org Visibility

- content/es/llm_observability/setup/api.md
Update the eval-metrics API endpoint from `v1` to `v2` in Spanish.
This is the case for other languages such as English or French. …
> Update eval-metrics API endpoint in Spanish

- content/en/tracing/trace_collection/library_config/_index.md
- content/en/tracing/trace_collection/trace_context_propagation/_index.md
- Adds `DD_TRACE_BAGGAGE_TAG_KEYS` in configuration docs and APM trace context propagation docs. 
- Adds configuration for baggage limits including `DD_TRACE_BAGGAGE_MAX_ITEMS` and `DD_TRACE_BAGGAGE_MAX_BYTES`
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been …
> Adding Baggage Span Tags docs

- content/en/containers/guide/cluster_agent_autoscaling_metrics.md
This is to document `DD_EXTERNAL_METRICS_PROVIDER_ENABLE_DATADOGMETRIC_AUTOGEN` in case customers want to disable the auto generated DatadogMetric behavior mentioned in this section of the public docs: https://docs.datadoghq.com/containers/guide/cluster_agent_autoscaling_metrics/?tab=datadogoperator#migration
> Include how to disable dcaautogen behavior

- content/en/tracing/trace_collection/compatibility/java.md
Document the agreed end-of-life date for Java SDK version 0.x. …
> Add End-of-life date for Java SDK 0.x

- content/en/agent/faq/proxy_example_haproxy.md
This PR adds install.datadoghq.com to the HAProxy configuration example per customer request.
**Note:** The URL is _not_ datacenter-specific! …
> chore(fleet): Add HAProxy example for install.datadoghq.com

- content/en/containers/guide/container-discovery-management.md
- content/en/containers/kubernetes/log.md
1. Provides more context on autodiscovery log filtering 
2. Explains relation between Agent config filtering and pod annotation filtering …
> Autodiscovery filtering doc updates [CONTP-828]

- layouts/partials/table-of-contents/table-of-contents.html
[page with changes](https://docs-staging.datadoghq.com/jackie.robson/add-custom-processors-functions-toc/observability_pipelines/processors/custom_processor/)
[page with ToC for comparison (no changes)](https://docs-staging.datadoghq.com/jackie.robson/add-custom-processors-functions-toc/internal_developer_portal/software_catalog/entity_model/)
[Jira Ticket](https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?jql=assignee%20%3D%20712020%3A206da1a2-8512-4e6b-8cb0-928de2146e7c&selectedIssue=WEB-6643)
Adding in TOC for observability pipelines customs processor page.
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the …
> add in condition to fill in toc for custom processor page

- content/en/tracing/trace_collection/proxy_setup/istio.md
This PR updates Istio's instruction to configure environment variables. The `apm.datadoghq.com/env` annotation is not working with Istio's sidecar injection, instead, we recommend setting env variables via `istio.proxy.io/config` annotation.
I move the deployment section before the env var configuration because I do think it's more important.
> tracing: update istio env variable configuration

- content/en/real_user_monitoring/correlate_with_other_telemetry/apm/_index.md
Based on internal feedback:
- Uses a more realistic and safe RegExp example
- Clarifies that RegExp is matched as a substring, not just a prefix
- Adds a warning about the risks of overly broad RegExp patterns and CORS errors
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the …
> [DOCS-11147] Update regex examples for connect RUM with traces

- content/en/agent/configuration/secrets-management.md
Remove '$' since one is automatically added when showing bash script. Adding one manually produce double dollar signs.
None
> Remove '$' since one is automatically added when showing bash script

- content/en/security/cloud_security_management/misconfigurations/frameworks_and_benchmarks/custom_frameworks.md
Docs incorrectly said that we support cloud config and infra config rules, when we just support cloud config (see [slack](https://dd.slack.com/archives/C02G5J4FB0E/p1750410520500859))
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation …
> Removing "infra config" from supported rules in custom frameworks

- content/en/synthetics/browser_tests/_index.md
Synthetics has added a new advanced option called Blocked Requests. We’d like to add a new Blocked Requests tab to the existing [Advanced Options documentation](https://docs.datadoghq.com/synthetics/browser_tests/?tab=requestoptions#advanced-options), in the same way as other advanced options.
> [DOCS-11285] Document new blocked requests option for Synthetics browser tests

- content/en/cloud_cost_management/container_cost_allocation.md
Customers 
https://datadoghq.atlassian.net/browse/CCA-870
Right now we only support gpu pod allocation for nvidia based requests, some customers have other requests and we do not support them …
> Add note about how CCM only supports nvidia based gpu requests

- content/en/serverless/azure_app_services/_index.md
- content/en/serverless/azure_app_services/azure_app_services_container.md
- content/en/serverless/azure_app_services/azure_app_services_linux.md
- content/en/serverless/guide/azure_app_service_linux_containers_serverless_init.md
Improves the AAS documentation to be more clear about how to get set up with Datadog Azure App Services Monitoring:
installing the Datadog Azure Integration and AAS instrumentation. 
Also includes the automated setup which is now GA in the Datadog CLI
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have …
> [SVLS-7025] improve AAS documentation

- content/en/ddsql_reference/ddsql_default.md
> Add json functions to default ddsql reference

- content/en/agent/guide/upgrade_between_minor_versions.md
Combine the upgrading the Agent docs to look like:  …
> Upgrading Agent Docs Changes

- config/_default/params.yaml
Adds US1-FED unsupported banner to IaC Security docs. …
> DOCS-11294: Add unsupported banner to IaC Security docs

- content/en/tracing/trace_collection/library_config/java.md
The default value for dd.jdk.socket.enabled is now set to true after the dd-trace-java 1.50.0 release ([notes reference](https://github.com/DataDog/dd-trace-java/releases/tag/v1.50.0#:~:text=%F0%9F%90%9B%20Turn%20JDK%20socket%20support%20on%20by%20default%20(%238752%20%2D%20%40sarahchen6))).
[6/5/2025] Merge queue has been disabled on …
> Update java.md dd.jdk.socket.enabled default value to true

- content/en/profiler/automated_analysis.md
- content/en/profiler/enabling/full_host.md
Adding correct public preview links and enabling banner for Automated Analysis and Full host …
> updated public preview link with real link

- content/en/logs/guide/mechanisms-ensure-logs-not-lost.md
Document the `logs_config.close_timeout` configuration setting …
> [ AGNTLOG-172 ] document the close_timeout setting for log rotations in the datadog agent

- content/en/datadog_cloudcraft/overlays.md
This is a very quick PR to add wording that mentions the identity risks layer in Cloudcraft, which just went GA. I'm going to follow it up with a more in-depth PR to add images with the sensitive data layer, which is going to be GA in the next week or so.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have …
> Add identity risk layer wording to Cloudcraft

- config/_default/menus/main.en.yaml
- content/en/observability_pipelines/processors/tags.md
- layouts/shortcodes/observability_pipelines/processors/parse_json.en.md
- Updates the Parse JSON description.
- Changes the Tags Processor doc title to Tags.
- Renames the Tags Processor file to Tags and adds alias for previous name.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of …
> Update parse json and tags processor

- content/en/integrations/guide/azure-manual-setup.md
Add a section about the required permission in Azure and Datadog …
> [DOCS-11197] Add permissions section

- content/en/serverless/aws_lambda/installation/go.md
- content/en/serverless/aws_lambda/installation/nodejs.md
- content/en/serverless/aws_lambda/installation/python.md
This PR updates the lambda installation instructions to include adding Datadog to a lambda function using [SST](https://sst.dev/) v3 for Node, Python, and Go. (Note: SST v3 supports Node, Python, Go, and Rust, but we don't have Rust installation instructions).
These instructions will help customers using SST v3 add Datadog to their lambda functions. 
> [SVLS-5132] Add SST v3 deployment instructions to public documentation

- content/en/containers/guide/aws-batch-ecs-fargate.md
This is to include log collection with Firelens/Fluenbit with AWS Batch with ECS Fargate as recently, AWS announced support for this: https://docs.datadoghq.com/containers/guide/aws-batch-ecs-fargate/?tab=awscli
> Update doc to include log collection for AWS Batch with ECS Fargate

- content/en/account_management/billing/custom_metrics.md
- content/en/metrics/custom_metrics/historical_metrics.md
Please feel free to propose changes to the format!
> Added Custom Metrics Billing Updates

- content/en/integrations/guide/source-code-integration.md
- content/en/profiler/profile_visualizations.md
- content/en/watchdog/insights.md
- content/es/integrations/guide/source-code-integration.md
- content/es/watchdog/insights.md
- content/fr/watchdog/insights.md
- content/ja/integrations/guide/source-code-integration.md
- content/ja/watchdog/insights.md
- content/ko/integrations/guide/source-code-integration.md
- content/ko/watchdog/insights.md
The routes for the profiling view where updated with [web-ui/pull/123038](https://github.com/DataDog/web-ui/pull/123038) but the documentation was not updated.
PR aims to update all mentions of "/profiling/search" to "/profiling/explorer" in order to have the correct routing to Profile > Explorer. …
> [PROF-11936] Remove deprecated profiling routes

- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/compatibility.md
Remove hard-coded language versions and point to tracer compatibility docs instead. Add a note to clarify how version compatibility works for SSI/tracers/runtimes. …
> Update SSI Compatibility doc 

- content/en/security/application_security/setup/compatibility/nodejs.md
After releasing dd-trace-js v5.57.0 we are officially supporting Fastify in AAP ASM, This PR aims to add doc for fastify in ASM
> Add fastify to nodejs documentation - security

- content/en/synthetics/browser_tests/test_results.md
Making the description of Relative Time clearer that it refers to specific time point, not duration or ratio which current description sounds like. …
> Update relative time description

- content/en/synthetics/troubleshooting/_index.md
Add section on security policy for running PL containers with read-only root file system
> Add section on security policy for running PL containers with read-only root file system

- content/en/cloud_cost_management/recommendations/_index.md
Adds entries in the CCM recommendations table for 4 released GCP recommendations. I've confirmed that all 4 of these are fully released and are generating recommendations. See [this widget](https://app.datadoghq.com/s/yB5yjZ/f4f-yu3-y3y)
> CCR add documentation for 4 more GCP recommendations

- content/en/opentelemetry/integrations/_index.md
- Our current note on metric pricing for OTel integrations is causing confusion.
- Revise and clarify content + move to dedicated section. …
> Clarify OTel Metric Pricing 

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/python.md
- The `tracer.configure()` examples in the main Python tracing doc used parameters (`hostname`, `port`) that were removed in `dd-trace-py` v3.
- This was misleading for customers performing a fresh installation and resulted in a support ticket.
- This change removes the deprecated examples and updates the section to recommend configuring via environment variables.
Related, adding v3 migration guide in a separate PR: https://github.com/DataDog/documentation/pull/30246
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to …
> Remove outdated dd-trace-py configuration instructions

- content/en/synthetics/multistep.md
In https://github.com/DataDog/documentation/pull/30284 we added documentation for subtests in Multistep API tests here: https://docs.datadoghq.com/synthetics/multistep/?tab=http#subtests
This is a small follow-up update which clarifies that only **Multistep** API tests may be added as subtests to Multistep API tests — regular API tests are not supported. 
> Only Multistep API tests can be added as subtests to Multistep API tests (API tests not supported)

- content/en/logs/log_collection/java.md
Use fully qualified class name instead of the "simple" class name to match what APM tracers capture.
See [this slack thread](https://dd.slack.com/archives/C017T36E0SH/p1751622532388579) for the full context.
W/ a fully qualified class name of `java.lang.IllegalArgumentException`, before this PR the logger would log only `IllegalArgumentException` while after this PR it'll log `java.lang.IllegalArgumentException` and it's consistent w/ what the APM tracers do.
> Use fully qualified class name to play better w/ error tracking

- content/en/monitors/quality/_index.md
- Add a section for resolving noisy monitors on Monitor Quality page.
> Add section on noisy monitors to Monitor Quality

- content/en/logs/log_collection/java.md
The Java Log Collection docs are missing an example of a JSON layout template for the Log4j 2 appender. This template is necessary for Java apps to emit logs in JSON format, but the docs don't provide one. As someone who doesn't work with Java regularly, it took me quite a while to track down a working example. Judging from this Slack thread, I wasn’t the only one who ran into this.
https://dd.slack.com/archives/C4W013KEU/p1749835158457139
I have added the following to this doc page:
- Adds a full example for Log4j 2's JSON format log template layout file, MyLayout.json
- Adds an instruction to remove dd.trace_id and dd_span.id from the template layout examples, if the log and trace correlation is not used.
Please have a Java Log Collection PM or an APM Injection Platform PM review these …
> Adds examples for Log4j 2's JSON format log template layout

- content/en/tests/flaky_management/_index.md
Documenting the new flaky test metric we expose for our customers under Flaky Test Management.
**Do not merge after reviewing.** We are still working to release this feature.
> [SDTEST-1786] Document new flaky tests metric of Flaky Test Management

- content/en/observability_pipelines/set_up_pipelines/archive_logs/_index.md
- content/en/observability_pipelines/set_up_pipelines/dual_ship_logs/_index.md
- content/en/observability_pipelines/set_up_pipelines/generate_metrics/_index.md
- content/en/observability_pipelines/set_up_pipelines/log_enrichment/_index.md
- content/en/observability_pipelines/set_up_pipelines/log_volume_control/_index.md
- content/en/observability_pipelines/set_up_pipelines/sensitive_data_redaction/_index.md
- content/en/observability_pipelines/set_up_pipelines/split_logs/_index.md
- Makes all use cases docs private. They have already been removed from the nav in a previous PR (https://github.com/DataDog/documentation/pull/30280) …
> [DOCS-11274] Add private frontmatter for OP use cases docs

- Makefile
This aims to solve the missing placeholder pages from integrations problem.
- separates `placeholders` from the `make dependencies` chain so it can happen further down the line.   we don't generate placeholders locally, so there's no need to call on it in the Makefile.
- update `make update_websites_sources_module` to use `hugo mod vendor`, copy the sourced integrations markdown files from websites-sources into docs, and remove the vendor directory immediately.  this should only happen in the CI.  the `_vendor` folder is already gitignored and there is logic to prevent it from running locally anyway, so it would never be committed.
new order of operations would be:
- `dependencies`
- `update_websites_sources_module`
- `placeholders`
...
- `build_site`
now we have the integrations in the …
> [docseng-37] copy sourced integrations earlier in the build process to generate placeholder pages

- content/en/profiler/profile_types.md
What does this PR do? 
This PR updates the documentation to reflect that Datadog's Node.js profiler supports for CPU profiling.
> Update profile_types details on Node.js

- content/en/tracing/trace_collection/compatibility/python.md
Provides clear expectations to customers around when particular versions of dd-trace-py will move between support levels, from GA to Maintenance and from Maintenance to EOL …
> specify when releases move between support levels

- content/en/logs/log_configuration/processors.md
- Add docs for logs threat intel processor 
- [DOCS-9903](https://datadoghq.atlassian.net/browse/DOCS-9903?atlOrigin=eyJpIjoiMjVjMWNiNzQxZWU4NDFjYTk4Y2FjOTBhZmYwMjE1N2MiLCJwIjoiaiJ9)
[DOCS-9903]: https://datadoghq.atlassian.net/browse/DOCS-9903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add logs threat intel processor

- content/en/real_user_monitoring/browser/tracking_user_actions.md
Received external feedback (more of a question) about what limits there are on actions. This PR answers the question, and reorders links. …
> [DOCS-11310] RUM actions limit

- content/en/llm_observability/sdk/auto_instrumentation.md
Openai Responses endpoint support is added in python ddtrace v3.10.0, updating the documentation to include this method. …
> Add auto instrumentation for OpenAI Responses

- layouts/shortcodes/observability_pipelines/log_source_configuration/datadog_agent.en.md
- layouts/shortcodes/observability_pipelines/log_source_configuration/datadog_agent_kubernetes.en.md
> [DOCS-11477] Update OP Agent connection info

- content/en/error_tracking/_index.md
- content/en/error_tracking/suspect_commits.md
- Adds the [Troubleshoot root causes with GitHub commit and ownership data in Error Tracking](https://www.datadoghq.com/blog/error-tracking-and-github/) to the following Error Tracking pages:
- https://docs.datadoghq.com/error_tracking/
- https://docs.datadoghq.com/error_tracking/suspect_commits/ …
> Add blog to 2 Error Tracking pages

- assets/styles/components/_product-availability-labels.scss
- content/en/ddsql_reference/_index.md
- layouts/shortcodes/product-availability.html
all
updates the `product-availability` shortcode. 
- allows for a subset of `products` to be rendered
motivation: https://datadoghq.atlassian.net/jira/software/projects/DOCSENG/boards/10954?selectedIssue=DOCSENG-40
preview: https://docs-staging.datadoghq.com/stefon.simmons/docseng-40/ddsql_reference/ …
> allows subset in `product-availability` shortcode - [DOCSENG-40]

- .vale.ini
Follow-up to https://github.com/DataDog/datadog-vale/pull/72. If that PR gets merged, then this one can also get merged so we can use the new rules in the docs repo. …
> Add AWS file to docs repo Vale ini

- content/en/tracing/guide/init_resource_calc.md
- content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/kubernetes.md
https://datadoghq.atlassian.net/browse/DOCS-10936
Create a page that describes how init container resources are calculated. This is information that only a small subset of users want/need to know, so we want a page to point them to, but we don't need the content to be super visible. I've added a link to it from the Further Reading section of the K8s SSI home page. We can reconsider placement if/when we get feedback to warrant that. 
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such …
> Add page on init container resource calc

- content/en/tracing/trace_pipeline/generate_metrics.md
alert is using a span instead of a div and the span is causing a formatting error
> fixing formatting for alert

- content/en/serverless/azure_app_services/_index.md
- content/en/serverless/azure_app_services/azure_app_services_linux.md
The main motivation was:
- Fix the value for `CORECLR_PROFILER_PATH` environment variable (was wrong and would not work for most users)
- Clean up installation instructions for .NET tracer
While I was in here:
- Fix a broken URL
- Bonus: fix `Node` => `Node.js` (branding is important 😉)
(Edit) After some PR feedback:
- reordered, removed, and cleaned up ~more~ all links
- switched from tables to lists for the env vars to improve readability
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your …
> Serverless > Azure App Services Linux > Update .NET instructions

- content/en/database_monitoring/guide/sql_extended_events.md
Update XE documentation based off of feedback from Rockstar trial. 2 MB max memory buffer was still hitting the 4 MB overflow issue, so suggesting 1 MB now.  …
> Update ring buffer size recommendation and filter datadog queries

- content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/setup.md
Updated the public documentation to clearly state that the Datadog SDK and RUM should be initialized in `AppDelegate` to ensure accurate telemetry (e.g., application startup duration). 
Also added guidance for SwiftUI apps using [`@UIApplicationDelegateAdaptor`](https://developer.apple.com/documentation/swiftui/uiapplicationdelegateadaptor).
If your branch doesn't follow this format, rename it or create a new branch …
> [RUM-8832] Clarify SDK and RUM initialization timing requirements in `setup.md`

- content/en/tracing/trace_pipeline/ingestion_mechanisms.md
Fix java tracer resource sampling example  using system property:
When 
`-Ddd.trace.sampling.rules='[{\"service\": \"my-service\", \"resource\": \"GET /checkout\", \"sample_rate\":1},{\"service\": \"my-service\", \"sample_rate\":0.2}]' ` is set, the sampling rule is actually not applied to the spans and an log error is written
`ERROR datadog.trace.agent.common.sampling.TraceSamplingRules - Couldn't parse Trace Sampling Rules from JSON: `
The correct configuration is 
`-Ddd.trace.sampling.rules='[{"service": "my-service", "resource": "GET /checkout", "sample_rate":1},{"service": "my-service", "sample_rate":0.2}]' `
> Fix java tracer resource sampling example

- content/en/service_management/events/guides/dogstatsd.md
- adding tags to Java example at customer request
- fixed syntax error where there was a `.` with no following method
From @binitapoudel1 : 
> However, customer raised a case where they stated that if we could include tags also in our java example config that would be helpful:
> Update Java example with tags

- content/en/tracing/configure_data_security/_index.md
This undocumented feature automatically detects and redacts Primary Account Numbers (PANs) found in trace metadata across all programming languages.
The documentation now includes:
- Updates to the data category tables to reflect that credit card numbers are collected by libraries and obfuscated by the Agent.
- A new "Credit Card" tab under the Agent Trace Obfuscation section with configuration details.
If your …
> Add Credit Card Numbers to Data Security Page

- content/en/tests/flaky_management/_index.md
We've recently released a new feature for the Flaky Test Management product which categorizes your flaky tests with AI. We want to document its behavior.
> [SDTEST-2055] Add documentation for AI flaky test categorization

- content/en/cloud_cost_management/setup/azure.md
1. Updates the instructions for backfilling Azure cost data. There is a manual way to do this which we have documented internally. We decided to expose this publicly so customers can do this on their own without support.
2. Remove duplicate step in setup instructions
> [CCM] update instructions for backfilling Azure data

- content/en/serverless/google_cloud_run/functions_1st_gen.md
Removes the setting `DD_TRACE_STATS_COMPUTATION_ENABLED` from Google Cloud Run Functions 1st gen docs. This setting enables a configuration that is no longer maintained by the APM teams. We're actively working on another supported approach for trace stats in this environment. …
> remove trace metrics configuration from google cloud run functions 1st gen docs

- content/en/dashboards/sharing/scheduled_reports.md
Slack support in Fed has been built and Scheduled Dashboards has been enabled in fed:
https://sdp.ddbuild.io/#/feature-flags/reporting-slack-support
https://sdp.ddbuild.io/#/feature-flags/dashboard_report_scheduling_slack_recipients
Since Scheduled Dashboards is now working in fed, removing this warning from documentation.
> [documentation] Remove fed note since scheduled dashboards is enabled in fed

- content/en/agent/guide/environment-variables.md
Our [documentation](https://docs.datadoghq.com/agent/guide/environment-variables/#using-environment-variables-in-systemd-units) explicitly states that the DD_TAGS environment variable should be defined with values separated by spaces. This guidance is reflected in the systemd units section.
However, upon reviewing both the Install-Datadog.ps1 script for Windows hosts and the install_script_agent7.sh for Linux-based systems, we found that both scripts expect the tags to be separated by commas, not spaces.
This inconsistency could lead to confusion or misconfigured tags depending on how users follow the documentation versus the install scripts.
Here is the snippet of the [install_script_agent7.sh](https://install.datadoghq.com/scripts/install_script_agent7.sh):
```
host_tags=  # A …
```
> Update environment-variables.md using comma as a separator

- assets/scripts/components/instantsearch.js
- assets/scripts/datadog-docs.js
https://datadoghq.atlassian.net/browse/WEB-5827 …
> fixes to glossary scrolling

- content/en/synthetics/platform/test_coverage/_index.md
https://github.com/DataDog/documentation/pull/30655 removed one of two tabs of content on this page; this PR removes the tab structure entirely because it doesn't make sense to have a single remaining tab. I also removed a couple places that still referred to the removed content (API endpoints testing). …
> [DOCS-11603] Remove single tab and stray references to removed content

- content/en/security/application_security/setup/go/dockerfile.md
This PR adds a page on how to design a dockerfile for us in an standard AAP setup. …
> [APPSEC-58034] AAP for Go Dockerfiles

- content/en/security/application_security/setup/go/troubleshooting.md
This PR adds a page to detail errors logs and known setups where teh user can get stuck installing AAP for Go …
> [APPSEC-58246] AAP for Go Troubleshooting

- layouts/shortcodes/observability_pipelines/source_settings/datadog_agent.en.md
Adds TLS info to the Datadog Agent source shortcode. …
> Add TLS option to Datadog Agent source

- content/en/integrations/guide/source-code-integration.md
For now, point to the Preview signup page. Once we publish GitLab integration docs we can update the link again
Broken link is breaking the build. …
> Fix link in Source Code Integration docs

- content/en/serverless/aws_lambda/installation/dotnet.md
- content/en/serverless/aws_lambda/installation/go.md
- content/en/serverless/aws_lambda/installation/java.md
- content/en/serverless/aws_lambda/installation/nodejs.md
- content/en/serverless/aws_lambda/installation/python.md
- content/es/serverless/aws_lambda/installation/dotnet.md
- content/es/serverless/aws_lambda/installation/java.md
- content/es/serverless/aws_lambda/installation/nodejs.md
- content/es/serverless/aws_lambda/installation/python.md
- content/fr/serverless/aws_lambda/installation/java.md
- content/ja/serverless/aws_lambda/installation/nodejs.md
- content/ja/serverless/aws_lambda/installation/python.md
- layouts/shortcodes/latest-lambda-layer-version.html
This PR:
- bumps the terraform lambda module version in the docs from 3.1.0 to 3.2.0
- bumps the node layer, python layer, and extension layer versions used in the examples to latest versions …
> Bump terraform module version to 3.2.0 and make all layer versions use shortcuts

- content/en/llm_observability/instrumentation/auto_instrumentation.md
Adds notes for DeepSeek auto-instrumentation under our OpenAI auto-instrumentation docs. Because DeepSeek is sorta a "subset" because using it programmatically requires using the `openai` SDKs, I've decided to put it there, along with the versions of the tracers/LLMOBs SDKs that support them.
[6/5/2025] Merge queue has been disabled …
> [MLOB] add DeepSeek auto-instrumentation support alongside OpenAI auto-instrumentation support

- content/en/serverless/google_cloud_run/containers_sidecar.md
- content/en/serverless/google_cloud_run/functions.md
Fix broken link to serverless/google_cloud_run/containers_in_process …
> Ian.bucad/fix 404 google cloud run in process

- content/en/deployment_gates/setup.md
This is just an alternative proposed by @gturbat to move the API instructions into a separate tab
> Move API instructions to a separate tab

- layouts/shortcodes/observability_pipelines/configure_existing_pipelines/destination_env_vars/splunk_hec.en.md
- layouts/shortcodes/observability_pipelines/prerequisites/splunk_hec_destination_only.en.md
> [DOCS-11126] Add note about Splunk HEC token env var

- layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_amazon_s3.en.md
> Update OP Amazon S3 destination

- translate.yaml
shortcodes without a `.en.md` extension shouldn't be translated.   reason being that it causes issues in hugo to have a shortcode like `file.md` (english) and then `file.fr.md`.   these don't end up being committed to docs which is good, but they do end up in the queue which can cause issues.   lets just ignore them altogether.
i tested the glob pattern here https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2F%2A%2A%2F%2A.js&matches=false&tests=%2F%2F%20This%20will%20match%20as%20it%20ends%20with%20%27.js%27&tests=%2Fhello%2Fworld.js&tests=%2F%2F%20This%20won%27t%20match%21&tests=%2Ftest%2Fsome%2Fglobs
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, …
> [web-6889] adds glob to ignore shortcodes without en.md

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
This PR adds some language around limitations for AWS log autosubscription. More specifically, we've had a few support cases raising issues when logs are published in buckets in different accounts and the triggers aren't created.
This is due to a lambda limitation that makes it so that we can't trigger an AWS Lambda function from notifications emitted from a different account/region.
- [ X] Ready for merge
> [CLOUDS_6404] feat(doc): add autosubscription limitation language

- content/en/cloud_cost_management/tag_pipelines.md
Adding backfill information to tag pipelines page.
Adds tag pipelines backfill information to public docs. …
> Update tag_pipelines to include backfill date

- content/en/tracing/trace_collection/library_config/go.md
Removes a note in Go SDK configuration that sampling rules configuration is in preview, which has been GA for a while. …
> Go SDK configuration: Remove preview note for sampling rules

- content/en/tests/code_coverage.md
- content/en/tests/setup/junit_xml.md
Updates inline links in the Code Coverage callouts to point to the new product docs. We couldn't link to the docs until they were published via https://github.com/DataDog/documentation/pull/30798. Previously we linked to the Preview signup page, but the callout button takes care of that. …
> Update links to new Code Coverage product docs [DOCS-11678]

- layouts/partials/code_security/languages-getting-started.html
Terraform was moved to IaC. It's no longer in Code Security.
> removing Terraform card

- content/en/security/code_security/static_analysis/setup/_index.md
Document these fields, which have existed for a while but were undocumented. …
> Document the static analyzer's rule config 'severity' and 'category' fields

- layouts/shortcodes/get-metrics-from-git.html
allows for a list of `metric_namespaces`
motivation: https://datadoghq.atlassian.net/browse/DOCSENG-90
preview: https://docs-staging.datadoghq.com/stefon.simmons/docseng-90-get-metrics-bug/synthetics/platform/metrics/#general-metrics
- see that the `General Metrics` section renders a table with content …
> bug fix: `get-metrics-from-git` - [DOCSENG-90]

- content/en/opentelemetry/setup/ddot_collector/_index.md
Add routing connector to DDOT included components as follow up to https://github.com/DataDog/datadog-agent/pull/37623
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use …
> [OTAGENT-411] Add routing connector to DDOT included components

- content/en/database_monitoring/database_hosts.md
Database cluster grouping has been updated which we can see here:
https://github.com/DataDog/web-ui/pull/211279
It uses both `dbclusteridentifier` and `region` now, so this doc will reflect that …
> Update database_hosts.md regarding grouping

- content/en/infrastructure/process/_index.md
> DOCS-11557: update live processes page

- content/en/real_user_monitoring/feature_flag_tracking/setup.md
Changes `replace` to `replaceAll` so that the command gets all the special characters in the flag, not just one.
> DOCS-9554/Issue 26355 Update RUM command for feature flag special characters

- content/en/deployment_gates/setup.md
Variables do not render well in code blocks:
This PR adds placeholders and instructions to repace the DD_SITE variable …
> Fix incorrect API urls in Deployment Gates code examples

- content/en/tracing/trace_collection/trace_context_propagation/_index.md
- Updates the list of supported languages for feature adding baggage to span tags …
> Add languages to Baggage span tags

- content/en/serverless/azure_functions/_index.md
Fix the package id for .NET Azure Functions. See https://www.nuget.org/packages/Datadog.AzureFunctions.
`Datadog.Azure.Functions` ➡️ `Datadog.AzureFunctions` …
> Serverless > Azure Functions > .NET: fix nuget package id

- content/en/code_coverage/setup.md
This PR adds Troubleshooting section to Code Coverage set up docs.
The section describes common issues encountered during Code Coverage set up and how to fix them. …
> Add Troubleshooting section to Code Coverage docs

- content/en/dashboards/guide/getting_started_with_wildcard_widget.md
Remove extra image reference that is breaking collapse-content formatting on Getting Started with Wildcard Widget.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use …
> Remove extra image reference to fix collapse-content

- content/en/observability_pipelines/destinations/http_client.md
- content/en/observability_pipelines/performance.md
- layouts/shortcodes/observability_pipelines/destination_settings/amazon_opensearch.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/amazon_security_lake.md
- layouts/shortcodes/observability_pipelines/destination_settings/chronicle.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/crowdstrike_ng_siem.md
- layouts/shortcodes/observability_pipelines/destination_settings/datadog.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_amazon_s3.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_azure_storage.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_google_cloud_storage.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/elasticsearch.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/microsoft_sentinel.md
- layouts/shortcodes/observability_pipelines/destination_settings/new_relic.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/opensearch.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/sentinelone.md
- layouts/shortcodes/observability_pipelines/destination_settings/socket.md
- layouts/shortcodes/observability_pipelines/destination_settings/splunk_hec.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/sumo_logic.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/syslog.en.md
Add `in Preview` for buffering options. …
> Buffering option is in preview

- content/en/security/detection_rules/_index.md
DOCS-11462
Adds a section on the MITRE ATT&CK map feature to the main Security detection rules page. MITRE ATT&CK map now supports 3 products, instead of just one, so it needs to be covered in the overview section.
> MITRE ATT&CK map content updated for new product support

- layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_azure_storage.en.md
- layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_google_cloud_storage.en.md
> [DOCS-11537] Add note about leading slash for GCS and Azure Storage

- content/en/serverless/google_cloud_run/containers/in_process/dotnet.md
- content/en/serverless/google_cloud_run/containers/in_process/go.md
- content/en/serverless/google_cloud_run/containers/in_process/java.md
- content/en/serverless/google_cloud_run/containers/in_process/nodejs.md
- content/en/serverless/google_cloud_run/containers/in_process/php.md
- content/en/serverless/google_cloud_run/containers/in_process/python.md
- content/en/serverless/google_cloud_run/containers/in_process/ruby.md
- layouts/shortcodes/gcr-configure-env-vars.en.html
Add documentation about the `service` label and info bars linking to our GCP sample apps. …
> Add GCP Sample Apps & Service Label

- content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md
Updating a guide to reflect added support for log autosubscription for Amazon Route53 DNS query logs
> [AWSX-1557] feat(autosub): add support for Route53 DNS query logs

- config/_default/menus/main.en.yaml
- content/en/service_management/incident_management/declare.md
- content/en/service_management/incident_management/describe.md
- content/en/service_management/incident_management/response_team.md
This PR updates Incident Management documentation to extract content from the "Describe incident" page that has nothing to do with describing the incident.
Specifically, it:
* Moves content about declaring an incident to the "Declare incident" page.
* Moves content about managing a response team to a new "Response team" page.
* Strikes content related to notifications, which is already sufficiently covered by other pages.
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such as broken …
> INA-7891: Extract off-topic sections from "Describe incident" documentation

- content/en/data_streams/setup/language/dotnet.md
- content/en/data_streams/setup/language/java.md
- content/en/data_streams/setup/language/nodejs.md
- content/en/data_streams/setup/language/python.md
**Problem:**
The "Datadog Agent" link in Data Streams Monitoring setup pages was incorrectly redirecting to AWS documentation instead of `/agent`. This occurred because shortcodes included in these pages (like `monitoring-sqs-pipelines`) contained `[1]` link references that overrode the main file's `[1]: /agent` reference.
**Solution:**
Changed the Datadog Agent link reference from `[1]` to `[10]` in all affected language setup files to avoid conflicts with shortcode references.
**Files Changed:**
- `content/en/data_streams/setup/language/python.md`
- `content/en/data_streams/setup/language/nodejs.md` 
- `content/en/data_streams/setup/language/java.md`
- `content/en/data_streams/setup/language/dotnet.md`
**Testing:**
Verified that the "Datadog Agent v7.34.0 or later" links now correctly …
> Fix conflicting markdown link references in Data Streams Monitoring setup docs

- assets/scripts/config/regions.config.js
- content/en/opentelemetry/setup/agentless/logs.md
- content/en/opentelemetry/setup/agentless/traces.md
The intake now handles the standard OpenTelemetry HTTP paths without the need of additional header.
https://opentelemetry.io/docs/specs/otlp/#otlphttp-request
Simplify the documentation by:
- using the standard OTLP path (`/v1/logs` and `/v1/traces`)
- removing the need of `dd-protocol=otlp` HTTP header …
> OpenTelemetry: Update the HTTP path and headers for logs and traces

- layouts/shortcodes/observability_pipelines/source_settings/socket.md
Use HTML tables for the Socket source doc because the Framing column is getting cut off. PM request.
- Replace markdown table with HTML table so that widths can be manually adjusted.
Preview: https://docs-staging.datadoghq.com/may/fix-table-widths-socket-source/observability_pipelines/sources/socket/ …
> [DOCS-11638] Use HTML table for Socket source doc

- Makefile
- layouts/shortcodes/multifilter-search.html
we get latest sources when running `make start` not `make start-no-pre-build`.   some data was missing locally from more recent commits to sources. …
> get latest sources when running `start no-pre-build`

- content/en/synthetics/platform/private_locations/_index.md
Updates the link for the synthetics FIPS PL. Some customers have run into issues with the current link requiring docker hub authentication.
> Use updated dockerhub link for synthetics FIPS PL 

- content/en/agent/logs/advanced_log_collection.md
Reverts DataDog/documentation#30449
Now that 7.69.0 has been released we can publish the associated documentation.
> docs: Add new processing rule exclude_truncated to not ingest truncated logs

- content/en/serverless/azure_app_services/azure_app_services_windows.md
@aniket-datadog noticed that we had an improperly labelled tab. I renamed the tab and switched the order for consistency with the rest of the doc. …
> Azure App Services - rename/reorder .NET tab

- assets/styles/components/_tab-toggle.scss
3rd attempt at fixing the z-index for tabs.
- removes bottom border line of active tab
**motivation**: https://datadoghq.atlassian.net/browse/DOCSENG-113
**previews**: tabs should still work. design should be intact. there should be no tab that overlaps the leftnav search window
- https://docs-staging.datadoghq.com/stefon.simmons/fix-tab-z-index-3/tracing/other_telemetry/connect_logs_and_traces/dotnet/?s=attr&tab=microsoftextensionslogging
- https://docs-staging.datadoghq.com/stefon.simmons/fix-tab-z-index-3/api/latest/?s=attr&tab=ruby
- https://docs-staging.datadoghq.com/stefon.simmons/fix-tab-z-index-3/security/cloud_siem/detection_rules/?tab=impossibletravel#define-a-search-query
Your branch name MUST follow the `<name>/<description>` …
> fix z-index - attempt 3

- content/en/tracing/dynamic_instrumentation/expression-language.md
Remove outdated error behavior from public expression language documentation …
> fix(di): remove `UNDEFINED` error statement from EL doc

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core.md
- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-framework.md
- Fix badly constructed sentence.
- Instead of linking to 2 specific products (AWS Lambda and Azure App Services), just link to the main Serverless page, because we support more products now and there are too many to list here.
- ~Fix URLs to use the `[text][1]` syntax.~ Looks like we can't do that inside "alert" divs.
[6/5/2025] …
> APM .NET library: fix link to serverless docs

- content/en/serverless/step_functions/distributed-maps.md
- content/en/serverless/step_functions/merge-step-functions-lambda.md
This PR expands the documentation related to Step Function trace merging and updates the related JSONata strings, which propagate Datadog Context more effectively.
This is ready to merge once it is approved.
> [SVLS-7298] Add support for merging upstream traces with Step Function

- content/en/security/workload_protection/setup/agent/kubernetes.md
Added note about enabling `clusterRole.allowCreatePodsExec` for RBAC issues.
> Add RBAC troubleshooting note for Kubernetes agent

- content/en/actions/workflows/variables.md
I noticed that this link was broken on [this page](https://docs.datadoghq.com/actions/workflows/variables/)
> fix link to inline-javascript-expression page

- .github/CODEOWNERS
- content/en/ddsql_reference/_index.md
I'd like to add an example of what happens in DDSQL when a resource has multiple values for the same tag key. This is a potential stumbling-block for customers and I'd like to be sure that it's well-documented in case customers run into this
Ready to go
> [ddsql] Add examples of multi-valued tags handling to DDSQL tags documentation

- content/en/serverless/google_cloud_run/containers/in_container/dotnet.md
- content/en/serverless/google_cloud_run/containers/in_container/go.md
- content/en/serverless/google_cloud_run/containers/in_container/java.md
- content/en/serverless/google_cloud_run/containers/in_container/nodejs.md
- content/en/serverless/google_cloud_run/containers/in_container/php.md
- content/en/serverless/google_cloud_run/containers/in_container/python.md
- content/en/serverless/google_cloud_run/containers/in_container/ruby.md
- content/en/serverless/google_cloud_run/containers/sidecar/dotnet.md
- content/en/serverless/google_cloud_run/containers/sidecar/go.md
- content/en/serverless/google_cloud_run/containers/sidecar/java.md
- content/en/serverless/google_cloud_run/containers/sidecar/nodejs.md
- content/en/serverless/google_cloud_run/containers/sidecar/php.md
- content/en/serverless/google_cloud_run/containers/sidecar/python.md
- content/en/serverless/google_cloud_run/containers/sidecar/ruby.md
- Explain where to find the latest dd-trace-java version
- Recommend `DD_LOGS_INJECTION=true` for supported runtimes
- Clarify that only *distribution* metric type is supported in serverless
> [Cloud Run] Minor improvements to logging, metrics, and Java tracer install

- content/en/network_monitoring/devices/ping.md
Yesterday I pushed a PR to change the wording on this but I read the vale rule incorrectly, this capitalizes Autodiscovery as it should be :)  …
> Fix capitalization in ping.md autodiscovery section

- content/en/internal_developer_portal/software_catalog/entity_model/_index.md
In the `service.datadog.yaml` file modified, `owner` and `additionalOwners` belong under the `metadata` block.  The schema [here](https://github.com/DataDog/schema/blob/3542c9e9e3637f4ba404fa90b4c308d85a39b32f/service-catalog/v3/metadata.schema.json#L32) agrees.
[6/5/2025] Merge queue has been disabled on the documentation repo. If …
> Fix white-space in example service.datadog.yaml file

- content/en/internal_developer_portal/software_catalog/entity_model/entity_types.md
> Update API docs in IDP

- content/en/logs/log_configuration/processors.md
This is a follow up of https://github.com/DataDog/documentation/pull/31339 that contained a typo
> Fix typo in logs pipeline array processor API doc

- content/en/ddsql_reference/_index.md
This PR updates the DDSQL data type and type literal docs to resolve three post-merge comments from https://github.com/DataDog/documentation/pull/31252.
N/A
> [DDSQL] data type and type literal doc updates

- content/en/tracing/trace_collection/compatibility/java.md
Java 24+ introduces warnings on JNI native access and sun.misc.Unsafe memory access. This PR adds a line to our `Known Issues` acknowledging the warnings and including information on how to suppress the warnings if desired. The changes relate to #31403 
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have …
> Update java tracer known issues to acknowledge warnings for Java 24+

- content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/java.md
Java 24+ introduces warnings on JNI native access and `sun.misc.Unsafe` memory access. This PR adds a Note so that customers know how to suppress the warnings if desired. …
> Update java tracer setup to recommend suppressing warnings for Java 24+

- content/en/error_tracking/guides/sentry_sdk.md
Removes the "Preview" callout for the Sentry SDK feature for Error Tacking. Feature is GA.
> Remove preview label for Sentry SDK Error Tracking

- content/en/data_security/data_retention_periods.md
- content/en/security/code_security/software_composition_analysis/setup_runtime/_index.md
- content/en/security/code_security/software_composition_analysis/setup_static/_index.md
- content/en/security/code_security/static_analysis/setup/_index.md
This PR adds clarification to our documentation which states that Datadog does not store/retain customer code when performing Code Security Scans.
This also updates the product name in the data retention table.
> Code Security Data Retention Notes

- content/en/containers/troubleshooting/cluster-agent.md
- content/en/containers/troubleshooting/cluster-and-endpoint-checks.md
The commands in the following docs did not include `--`:
https://docs.datadoghq.com/containers/troubleshooting/cluster-agent
https://docs.datadoghq.com/containers/troubleshooting/cluster-and-endpoint-checks/#dispatching-logic-in-the-cluster-agent
`kubectl exec -it` commands without the double dashes is deprecated and users will either run into a deprecated notice when running these commands or are blocked completely in newer Kubernetes versions with the following message:
```
error: exec [POD] [COMMAND] is not supported anymore. Use exec [POD] -- [COMMAND] instead
See 'kubectl exec -h' for help and examples
```
> Include -- in cluster agent commands

- content/en/profiler/enabling/nodejs.md
- content/en/profiler/enabling/supported_versions.md
Updates the minimum Node.js version requirement for profiler. It's been the case for a while that Node.js profiler minimum requirement is version 18.
> Update minimum Node.js version requirement for profiler

- .github/chainguard/self.version_getter_shared.create-pr.yaml
- .github/workflows/bump_private_action_version.yml
- .github/workflows/bump_synthetics_worker_version.yml
- .github/workflows/version_getter_shared.yml
- content/en/actions/app_builder/components/_index.md
- data/private_action_runner_version.json
- local/bin/py/version_getter.py
Modifies the existing python script to support both `synthetics-windows-pl` and `private-action-runner`. Uses a shared workflow for retrieving and updating version numbers. …
> (ddev) Dynamically update action version

- content/en/profiler/enabling/full_host.md
The current configuration information for local symbol upload is outdated as users will no longer need to upload local symbols manually. However, if the user wants to upload local symbols manually or add debug information, we provided the instructions to do so.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you …
> [PROF-12448] Remove current symbol upload instructions and add manual symbol upload info

- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
Synthetics readme [moved](https://github.com/DataDog/datadog-ci/pull/1820), this pr fixes the build for this  …
> synthetic readme location change

- content/en/llm_observability/evaluations/ootb_evaluations.md
Closes [MLOB-3890](https://datadoghq.atlassian.net/browse/MLOB-3890)
[MLOB-3890]: https://datadoghq.atlassian.net/browse/MLOB-3890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MLOB-3890] Add supported languages for Language Mismatch eval

- content/en/logs/explorer/search_syntax.md
The public docs are out of sync with our internal docs.
https://datadoghq.atlassian.net/wiki/spaces/EP/pages/978223114/Query+Language+syntax+and+functionalities#Free-text-search
> Update search_syntax to include missing attributes for free text search

- content/en/service_management/status_pages/_index.md
We've renamed "private" status pages to "internal" status pages to reflect their usage appropriately. They aren't truly private as they as visible to everyone in the Datadog organization. …
> Rename "private" status pages to "internal"

- content/en/security/notifications/rules.md
You can now test finding notifications in Security! This is a very small PR to remove mention of the old limitation.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use …
> Remove security notification testing limitation

- content/en/tracing/trace_collection/compatibility/java.md
This PR updates the Java support policy to include LTS version 25 and a note for GraalVM 25. …
> Update Java tracer supported versions

- content/en/error_tracking/backend/exception_replay.md
- content/en/tracing/dynamic_instrumentation/_index.md
- content/en/tracing/dynamic_instrumentation/enabling/dotnet.md
- content/en/tracing/dynamic_instrumentation/enabling/java.md
- content/en/tracing/dynamic_instrumentation/enabling/nodejs.md
- content/en/tracing/dynamic_instrumentation/enabling/php.md
- content/en/tracing/dynamic_instrumentation/enabling/python.md
- content/en/tracing/dynamic_instrumentation/enabling/ruby.md
- content/en/tracing/dynamic_instrumentation/symdb/_index.md
- content/es/tracing/dynamic_instrumentation/_index.md
- content/es/tracing/dynamic_instrumentation/enabling/java.md
- content/es/tracing/dynamic_instrumentation/enabling/ruby.md
- content/es/tracing/dynamic_instrumentation/symdb/_index.md
- content/es/tracing/error_tracking/exception_replay.md
Bumps to minimum agent version for Live Debugger, Dynamic Instrumentation, and Exception Replay to v7.49.0 …
> feat(debugger): bump minimum agent version from v7.44/45 to v7.49

- content/en/opentelemetry/getting_started/otel_demo_to_datadog.md
The folder was renamed at https://github.com/open-telemetry/opentelemetry-demo/pull/1841 a couple of months ago and our documentation is now stale.
I was interested in the demo and noticed this mismatch following the steps.
n/a
> Update file name following otel change

- content/en/tracing/trace_collection/compatibility/nodejs.md
- adds two recently supported node.js integrations
- no PR dependencies, the referenced integrations are already publicly available
> apm: add recently supported Node.js integrations

- content/en/serverless/google_cloud_run/functions/dotnet.md
- layouts/shortcodes/gcr-install-sidecar-terraform.md
- The .NET Function tracer path changed in v3 of dd-trace-dotnet, so the docs need to be fixed
- Add a link to the Terraform module in Container sidecar instrumentation
> [Cloud Run] Fix .NET Function tracer path & add link to Terraform module

- content/en/tracing/trace_collection/compatibility/dotnet-framework.md
Add .NET Framework 4.7.1 to the list of compatible versions. I was always supported, but we missed it or it was lost somehow. …
> APM > .NET > Add missing .NET Framework 4.7.1 compatibility entry

- assets/scripts/components/instantsearch.js
- assets/styles/instantsearch/searchbar-with-dropdown.scss
This PR add a11y to search bar, by allowing `up` and `down` + quick nav to targets .
https://datadoghq.atlassian.net/browse/DOCSENG-142 …
> [DOCSENG-142]: Add a11y to Algolia search feature

- content/en/account_management/org_settings/cross_org_visibility.md
Access-focused updates to support usage by HIPAA organizations. Requested and reviewed by privacy counsel.
- Removes HIPAA ineligibility for Cross-org
- Adds detail to access controls via GRACE on source or destination org, and respecting DAC of connection creator
- Adds additional notice of caution for HIPAA orgs
- [x ] Ready for merge
> Update Cross-Org Docs for HIPAA

- content/en/tracing/trace_pipeline/trace_retention.md
The name of the appsec default retention filter `App and API Protection Monitoring Default` was wrong, correct it to the good value which is `App and API Protection Default`
> Update appsec default retention filter name

- content/en/error_tracking/frontend/browser.md
- content/en/real_user_monitoring/guide/upload-javascript-source-maps.md
- content/es/error_tracking/frontend/browser.md
- content/es/real_user_monitoring/error_tracking/browser.md
- content/es/real_user_monitoring/guide/upload-javascript-source-maps.md
- content/fr/real_user_monitoring/error_tracking/browser.md
- content/fr/real_user_monitoring/guide/upload-javascript-source-maps.md
- content/ja/real_user_monitoring/guide/upload-javascript-source-maps.md
- content/ko/real_user_monitoring/error_tracking/browser.md
Changes to the datadog-ci repository have caused some links to become broken. This PR updates the path in the URL to be correct
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, …
> Update GitHub links for datadog-ci sourcemaps

- content/en/bits_ai/mcp_server/setup/_index.md
This PR updates the MCP server documentation to mention that remote authentication now works for AWS Q CLI (but a small tweak to the Q config is required). …
> MCP server: Document fix for AWS Q CLI

- content/en/network_monitoring/devices/sd-wan.md
- content/es/network_monitoring/devices/sd-wan.md
For the Velocloud integration, we want to update "VMware Velocloud" references to just "Velocloud" (due to changes in ownership as a company). This includes all consumer-facing assets and documentation.
Corresponding web UI PR: https://github.com/DataDog/web-ui/pull/234761
Corresponding ICS PR: https://github.com/DataDog/integrations-internal-core/pull/2192
> [SAASINT-4692] Velocloud: Remove 'VMware' from integration copy/docs/references

- content/en/logs/reports/_index.md
Once Scheduled CSV reports go GA, the `Scheduled CSV Reports are in Preview` callout in our public docs will be stale.
Do not merge until the corresponding feature flag (`widget_log_list_reporting`) is GA in commercial DCs.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR …
> Scheduled CSV Reports: remove preview callout

- content/en/serverless/aws_lambda/metrics.md
- content/en/serverless/custom_metrics/_index.md
The Datadog Lambda Extension has supported historical metrics for a long time, I was only made aware of this when a support person asked me to clarify these docs.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of …
> feat: datadog lambda extension supports timestamped metrics

- layouts/_default/list.search.json
- layouts/partials/algolia/page-sections.json
- local/bin/py/build/configurations/pull_config.yaml
- local/bin/py/build/configurations/pull_config_preview.yaml
exclude section headers (i.e. `h2`) from search on the auto-generated resource catalog pages.
https://datadoghq.atlassian.net/browse/DOCSENG-52 …
> [docseng-52] exclude headers from resource catalog pages from search

- assets/scripts/config/regions.config.js
- content/en/opentelemetry/setup/agentless/metrics.md
- content/en/opentelemetry/setup/otlp_ingest/metrics.md
Update OTLP metrics endpoint to new URL. See https://datadoghq.atlassian.net/wiki/spaces/FEG/pages/5374215320/Open+telemetry+unique+FQDN for context.
The new URL does not need allowlist. So as part of this change, the followings are removed:
- The banner saying this endpoint is in preview
- The `dd-otlp-source` header which is used to allowlist platform partners
- Troubleshooting section that mentions allowlists
If …
> Update OTLP metrics endpoint to new URL

- content/en/agent/fleet_automation/remote_management.md
This PR removes the documentation entry suggesting users to run `datadog-installer purge` as remote agent management is now shipped as part of regular deb/rpm packages and no longer requires specific instructions to uninstall on linux.
> (fleet) drop uninstall instructions for remote agent management

- content/en/infrastructure/containers/configuration.md
Context: Custom Resource Definitions (CRDs) are collected by default without user configuration, but custom resources are not.
Today: Starting in Agent [v7.71](https://github.com/DataDog/datadog-agent/pull/40898), we’re enabling OOTB CR collection by default (More details: [OOTB CR Collection in the Datadog Agent](https://docs.google.com/document/d/11JnEMWqQI0kwJkP689Mv3lHalktUmjyXY3cSqA0n8eo/edit?tab=t.0#heading=h.fi8uu9iock2v) ). The Agent will automatically collect:
Argo Rollouts (v1alpha1)
Karpenter (v1, all resources)
Karpenter AWS (v1, all resources)
Karpenter Azure (v1beta1, all resources)
Try it [here](https://docs-staging.datadoghq.com/christine.chun/add-automated-cr-collection/infrastructure/containers/configuration?tab=datadogoperator#collect-custom-resources)
> [CAP-2893] Add Table for automatically collected CRs

- config/_default/menus/main.en.yaml
- content/en/security/code_security/static_analysis/_index.md
- content/en/security/code_security/static_analysis/setup/_index.md
- Updates broken section hyperlinking in Code Security SAST home page
- Renames side menu option "GitHub Pull Requests" to "Pull Request Comments" as PR comments support more than just GitHub now
- Minor copy tweaks 
Merge after approval please 
- [ x ] Ready for merge
> Update broken linking

- content/en/llm_observability/experiments/_index.md
summary evaluators were released as part of[ 3.15](https://github.com/DataDog/dd-trace-py/pull/14629), add docs on its usage …
> add docs on summary evals

- Makefile
allows for building Docs locally w/ `websites-sources` _feature branch_ content stored in `S3`.
- e.g. `make start-sources FF_S3_PATH=<websites-sources feature branch>` will pull down data/content from a the deployed `<websites-sources feature branch>`
**motivation**: no way to preview `websites-sources` content before pushing content to `main`
**preview (no change)**: https://docs-staging.datadoghq.com/stefon.simmons/allow-local-web-sources-previews/
run locally: `make start-source FF_S3_PATH=<some websites-sources feature branch that has been deployed to S3>`
- should build site with `websites-sources` feature branch content stored in S3
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). …
> allows local previews of `websites-sources` content using `FF_S3_PATH`

- .github/workflows/gif_check.yml
- .github/workflows/preview_link.yml
- .github/workflows/synthetics.yml
- fixes the branch call to be in the env argument and passed to the function …
> Fix env var setting

- content/en/tracing/trace_collection/compatibility/java.md
Updating the vertx versions supported at the moment to include vertx v5
We support up to v5: https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent/instrumentation/vertx/vertx-web
> Including vertx v5 as supported version

- content/en/tracing/dynamic_instrumentation/expression-language.md
Removes deprecated `count` expression language operator from the list of examples. …
> fix(debugger): remove deprecated count() from expression examples
