DataDog/documentation

content/en/service_management/on-call/pages.md

Docs for paging a team via email. 
```
/merge
```

Pagea a Team via email

---

content/en/opentelemetry/setup/intake_endpoint/otlp_metrics.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. One of the Further reading links in this doc was flagged for returning a 404. This PR updates the link to the new (correct) URL.
To have your PR automatically merged after it receives the required reviews, add the following …

Update OTel link

---

content/en/service_management/on-call/pages.md

David is right here: https://github.com/DataDog/documentation/pull/28467#discussion_r2022348696
```
/merge
```

Move email documentation

---

layouts/shortcodes/csm-setup-azure.en.md

CIEM detections on Azure rely on additional Microsoft Graph API permissions. Without these, detections silently fail to trigger—impacting 14 detection types.  The docs should emphasize that Identity Risks are not addressed without these permissions.
https://docs-staging.datadoghq.com/nick.allen/highlight-impact-missing-graph-api-perms/security/cloud_security_management/setup/cloud_integrations?tab=azure.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with …

Highlight the impact of missing graph API permissions

---

content/en/llm_observability/ragas_evaluations.md

The ragas team reached out to suggest a change in the documentation ("Ragas is an open-source library for evaluating and improving LLM applications. Ragas also provides LLM and non-LLM-based metrics to help assess the performance of your LLM application offline and in production.")
A couple links also broke from a previous PR that I made which specified the wrong path for v0.1.21 ragas docs version - this pr fixes them
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any …

[MLOB] fix links in ragas and apply suggestion from ragas team

---

content/en/tracing/trace_collection/compatibility/dotnet-core.md

Documents a known .NET runtime bug that could affect customers when using the .NET library
N/A

[.NET] Add documentation of known bug

---

content/en/real_user_monitoring/session_replay/mobile/privacy_options.md

Some Android snippets had wrong filename, fixing it.
```
/merge
```

Remove wrong build.gradle filename mention for Android Session Replay privacy snippets

---

content/en/monitors/guide/non_static_thresholds.md

- Images inside tabs weren't rendering, fixed spacing to resolve
- [DOCS-10496](https://datadoghq.atlassian.net/browse/DOCS-10496)
```
/merge
```
[DOCS-10496]: …

Fix image bug

---

content/en/observability_pipelines/advanced_configurations.md

Add RC requirement for OP API key.
```
/merge
```

[DOCS-10483] Add RC requirement OP API key

---

content/en/account_management/_index.md

- Updates the note for US1-FED account management
- [DOCS-10456](https://datadoghq.atlassian.net/browse/DOCS-10456)
```
/merge
```
[DOCS-10456]: …

Update the Gov note for account management to include username/email

---

content/en/notebooks/notebooks_legacy.md
content/en/notebooks/notebooks_new.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. Two of the Further reading links in the Notebook docs were flagged for returning 404s. Upon review, it looks like the blog posts were moved. This PR updates the links to use the new URL directly.
**Note**: The blog post contains broken image links. I reached out to the Writing team to let them know.
If …

Fix blog post links in Notebook docs

---

content/en/developers/ide_plugins/vscode/_index.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. One of the links in this doc was flagged for returning a 404. Upon review, it appears to be outdated but redirects correctly. This PR updates the link to use the new URL directly.
To have your PR automatically merged after …

Update VS Code doc link

---

content/en/error_tracking/backend/_index.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. The preview signup link was flagged for returning a 404. Upon review, it looks like the URL might have moved. This PR updates the link to the correct URL.
To have your PR automatically merged after it receives the required …

Fix preview signup link in Backend Error Tracking doc

---

content/en/opentelemetry/setup/otlp_ingest_in_the_agent.md

Update a warning in OTLP ingestion to reflect the correct versions.
```
/merge
```

[OTEL-2371] update a warning in agent otlp ingestion

---

content/en/continuous_integration/pipelines/github.md
content/en/continuous_integration/pipelines/gitlab.md

This PR adds a link to the Failed Job Analysis in GitLab features table
```
/merge
```

Add link to Job Failure Analysis guide in GitLab and GitHub Actions

---

content/en/network_monitoring/cloud_network_monitoring/setup.md

Small change to add `shell` to the code snippet for Docker setup as it was missing and therefore was not invoking the "Copy" button in the snippet.
```
/merge
```

Fix code snippet on CNM setup page

---

content/en/account_management/saml/google.md

Previously, this document was adjusted to change the `signed assertion` checkbox instructions to be `checked` instead of `unchecked`
After confirming internally with the relevant team, this should be left unchecked, and not checked. This PR is to revert the change
This is a nuance specific to Google as an IdP, in a broad sense we expect assertions to be signed, but that is not what the functionality of this checkbox does. Enabling it results in assertion validation issues when using Google as an IdP.
As noted here: https://support.google.com/a/answer/6087519?hl=en#zippy=%2Cstep-add-the-custom-saml-app:~:text=(Optional)%20To%20indicate%20that%20your%20service%20provider%20requires%20the%20entire%20SAML%20authentication%20response%20to%20be%20signed%2C%20check%20the%20Signed%20response%20box …

Update Google IdP instructions to clarify signed assertion checkbox should be left unchecked

---

content/en/datadog_cloudcraft/_index.md

An internal user pointed out that the Resource Collection link should point to AWS resource collection setup, not CSM resource collection.
```
/merge
```

Update resource collection link

---

content/en/tracing/trace_collection/compatibility/python.md

Related to issue #https://github.com/DataDog/documentation/issues/28281 . 2 links in this doc are returning 404s/500s. Upon review, they appear to be outdated. This PR updates them to use the new URLs directly. …

Update Tracing Python Compatibility Links

---

content/en/security/guide/aws_fargate_config_guide.md

Update links. **Not** ready for merge until the following PR is merged:
https://github.com/DataDog/integrations-core/pull/19991
```
/merge
```

[DOCS-10533] Update links

---

content/en/containers/guide/kubernetes-legacy.md

Related to issue #https://github.com/DataDog/documentation/issues/28281 . 2 links in this doc are returning 404s. Upon review, they appear to be outdated. This PR updates them to use the new URLs directly. …

Update kubernetes legacy links

---

content/en/profiler/enabling/ruby.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. One of the links in this doc was flagged for returning a 404. This PR updates the link to the new (correct) URL. It also converts several inline links to the standard numbered destination link format.
- Old link: https://formulae.brew.sh/formula/pkg-config
- New link: https://formulae.brew.sh/formula/pkgconf
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such as broken …

Fix Continuous Profiler link

---

content/en/continuous_integration/pipelines/teamcity.md

Related to issue #[28281](https://github.com/DataDog/documentation/issues/28281): three links in this doc were flagged for returning 404s. Upon review, they appear to be outdated but redirect correctly. This PR updates them to use the new URLs directly.
To have your PR automatically merged after …

Update Continuous Integration TeamCity links

---

content/en/getting_started/logs/_index.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. One of the links in this doc was flagged for returning a 404. This PR updates the link to the correct URL.
``` …
```

Fix link in Logs Getting Started guide

---

content/en/agent/faq/hostname-starting-with-ec2-default-prefix.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. The link in this FAQ was flagged for returning a 404. This PR updates the link to the correct URL.
```
/merge
```

Fix broken link in Agent FAQ

---

content/en/monitors/downtimes/_index.md

Grammatical and clarity changes
Made some changes to shorten a sentence, standardize the use of Manage Downtimes page, and change some words to be more English as a Second Language (ESL) -friendly.
Line 30: Offline is used on multiple other Datadog doc pages (instead of off-line).
Line 64: Rewrote the 256 character limit sentence because "at most" is not as ESL friendly as "maximum". Maximum is also industry standard and heavily used throughout Datadog docs. My goals were to 1) Remove "instance" because "example" is a more ESL-friendly word. 2) Shorten it and remove a few of the -ing words that were making the sentence hard to read. If you want to keep it as is, or only keep part of my changes, just propose your changes in a comment and I will amend my commit.
The screenshot for the …

Grammar and consistency changes

---

content/en/data_security/guide/tls_ciphers_deprecation.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. One of the links in this doc was flagged for returning a 404. This PR updates the link to the correct URL.
``` …
```

Fix link in TLS ciphers deprecation notice doc

---

content/en/monitors/notify/notification_rules.md

Adding link to sign up for Notification Rule preview

Notification Rule preview banner

---

content/en/security/application_security/threats/setup/compatibility/nodejs.md
content/en/security/code_security/iast/setup/_index.md
content/en/tracing/trace_collection/compatibility/nodejs.md

Related to issue #https://github.com/DataDog/documentation/issues/28281 
```
/merge
```

Update MongoDB Driver link in Node JS Security page

---

content/en/synthetics/platform/private_locations/_index.md

Fix typo in the Fargate with AWS Secret Manager Section. "secret" should be "secrets"
```
/merge
```

Fix typo for Fargate Secrets definition

---

content/en/security/code_security/iast/setup/compatibility/nodejs.md
content/en/security/code_security/software_composition_analysis/setup_runtime/compatibility/nodejs.md

Related to issue https://github.com/DataDog/documentation/issues/28281. The MongoDB link in these docs were flagged for returning a 404. This PR updates the links to the correct URL.
``` …
```

DOCS-10500: Broken external link to node-mongodb-native core

---

content/en/synthetics/platform/private_locations/_index.md

Adds a note to the Private locations doc to explain expected behavior when editing a test.
```
/merge
```

[DOCS-10450] adding note on permissions

---

content/es/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-framework.md

Fixing an incorrect translation. This was brought up in Slack here: https://dd.slack.com/archives/C0DESMBQU/p1743104299289079. I also made the change in Transifex.
```
/merge
```

Update language for .NET Framework versions on Spanish site

---

content/en/serverless/aws_lambda/installation/nodejs.md

Replace class name and variable name `Datadog` with `DatadogLambda` because the former has been removed in the latest version of the CDK construct.
```
/merge
```

Update example code for instrumenting Node.js Lambda using CDK

---

content/en/account_management/rbac/granular_access.md

Update GRACE public docs to include Integration Accounts and Integration Webhooks, following these docs: https://datadoghq.atlassian.net/wiki/spaces/AAA/pages/2532147341/Adding+Granular+Access+Controls+to+a+New+Product#6.-Update-the-public-documentation
https://datadoghq.atlassian.net/browse/CHATINTS-759
Waiting for the release of Granular Access controls for the Microsoft Teams integration.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such as …

[docs] add integration accounts and integration webhooks to granular access doc

---

content/en/serverless/aws_lambda/installation/dotnet.md
content/en/serverless/aws_lambda/installation/go.md
content/en/serverless/aws_lambda/installation/java.md
content/en/serverless/aws_lambda/installation/nodejs.md

Fixes links to serverless sample GitHub repository
- [X ] Ready for merge
```
/merge
```

james.eastham/update-serverless-sample-links

---

content/en/tracing/trace_pipeline/trace_retention.md

Typo fix didn't get applied before https://github.com/DataDog/documentation/pull/28349 was merged.
```
/merge
```

Fix typo with retention filter docs

---

content/en/actions/private_actions/_index.md

Adds a blog link to the Private Actions doc.
```
/merge
```

Add blog link to Private Actions doc

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md

Correct branch name for #28555 (that was done in the UI)
```
/merge
```

Update to remove agent override (only keep clusterAgent)

---

content/en/actions/connections/_index.md

Connections Group is supported by both Workflows and App Builder, docs only list workflows.
```
/merge
```

Make connections group generic for workflows and app builder

---

snippets/markdown.json

Now that we can [anchor directly to accordions](https://github.com/DataDog/documentation/pull/28531), I've added the ID parameter into the collapsible content shortcode snippet to make it easier to do 🎉  …

Add ID parameter to collapse-content snippet

---

content/en/developers/faq/_index.md
content/en/developers/faq/hubot-script-request-snapshots-in-chat-using-the-datadog-api.md

Related to issue #https://github.com/DataDog/documentation/issues/28281. The link in this FAQ points to a NPM package that no longer exists. This PR removes the FAQ and adds an alias redirect. …

DOCS-10514: Remove hubot faq

---

content/en/synthetics/troubleshooting/_index.md

Include section for iOS entitlements

Update _index.md to include iOS entitlements for MAT

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/advanced_configuration.md

Add note for usage of RUM attributes

---

layouts/shortcodes/latest-lambda-layer-version.html

java and python layer version update

---

assets/styles/components/_collapsible-section.scss

[New feature to scroll](https://github.com/DataDog/documentation/pull/28531) to collapse-content changed rounded corners to square.
This change should re-round the corners without breaking the new scroll functionality.
Testing:
- Should scroll to collapsed section: https://docs-staging.datadoghq.com/brett.blue/collapse-content-fix/security/cloud_security_management/setup/agentless_scanning/enable/?tab=newawsaccount#quick-start-setup
- Corners should be rounded.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch …

Fix rounded corners on collapse content shortcode

---

content/en/security/cloud_security_management/_index.md

Adding some information PMs identified as missing from the CSM landing page, and which was confusing users
```
/merge
```

CSM: fill knowledge gaps PMs identified

---

content/en/observability_pipelines/destinations/azure_storage.md

[DOCS-10562] Fix link and text in OP Azure Storage destination doc

---

content/en/real_user_monitoring/browser/optimizing_performance.md

Add a blog link to the RUM Browser Monitoring docs.
```
/merge
```

Add blog link to RUM Browser Monitoring doc

---

content/en/api/latest/scopes/_index.md

- **Issue this resolves**: There's a disconnect between the scopes referenced in-app and the public docs. This makes sure the information listed in both are the same so customers are not confused between the two.
- Original fix from AAA: https://github.com/DataDog/documentation/pull/25405/files
- https://datadoghq.atlassian.net/browse/DOCS-10420
If your branch doesn't follow …

Update the auth scopes shortcode to permissions partial

---

content/en/security/application_security/guide/standalone_application_security.md

Add the version of dd-trace-rb that includes APM Disablement v2
```
/merge
```

Update standalone_application_security.md to add Ruby version

---

content/en/tracing/trace_collection/library_config/java.md

Related to issue https://github.com/DataDog/documentation/issues/28550. 
```
/merge
```

Fix the JmxFetch default checkPeriod

---

content/en/tracing/services/deployment_tracking.md

Updated the example values (in `deployment_tracking.md`) based on the description and calculation mentioned for the example
```
/merge
```

fix: update example values in deployment_tracking.md

---

content/en/software_catalog/navigating.md
content/en/software_catalog/troubleshooting.md
content/en/tracing/guide/setting_primary_tags_to_scope.md
content/en/tracing/troubleshooting/_index.md

Updates for primary tags feature

---

content/en/data_jobs/databricks.md

Out of the three install methods, Managed by Datadog actually requires a token with workspace `Admin` permission. In the paragraph above we only require the token to have `CAN VIEW` acess causing confusion for customers on Managed install.
Merge readiness: not ready
To have your PR automatically merged after it …

[DJM Databricks page] Note on admin permission required for managed install

---

content/en/logs/guide/azure-logging-guide.md

Update a site restriction note per DOCS-10550
```
/merge
```

[DOCS-10550] Update Blob Storage restriction note

---

layouts/shortcodes/observability_pipelines/destination_settings/datadog.en.md
layouts/shortcodes/observability_pipelines/destination_settings/splunk_hec.en.md

Adds compression info for Datadog and Splunk destinations.
```
/merge
```

[DOCS-9879/10551] Add OP compression info for Datadog and Splunk destinations

---

content/en/observability_pipelines/troubleshooting.md

Adds section about no Worker logs in the troubleshooting doc.
```
/merge
```

[DOCS-9300] Add Worker logs to troubleshooting

---

content/en/agent/configuration/network.md

CNM and USM are missing from the list of endpoints for auditing purposes. Customer was unable to find them in the list and asked support.
```
/merge
```

Add CNM and USM to endpoints

---

layouts/shortcodes/observability_pipelines/source_settings/http_server.en.md

Adds a note about HTTP Server bytes encoding and raw log stored in the message field.
```
/merge
```

[DOCS-10520] Add note about HTTP Server bytes encoding and raw log

---

content/en/tracing/guide/ignoring_apm_resources.md

Address https://github.com/DataDog/documentation/issues/28312 which noted that our docs still use the deprecated `FilterRequestsOnUrl` option.
```
/merge
```

Replace deprecated FilterRequestsOnUrl with DD_TRACE_SAMPLING_RULES for dd-trace-py

---

content/en/synthetics/platform/private_locations/_index.md

The config section under liveness probes was inadvertently removed in a previous PR, worked with the Support and Engineering teams to understand the missing configs and add them back.
Also moved the Root certificate sections above this section (not new just moved)
thank you!
To have your PR …

[DOCS-10499] updating liveness probes

---

content/en/logs/guide/setting-file-permissions-for-rotating-logs.md

- Remove a link that's no longer available
- [DOCS-10503](https://datadoghq.atlassian.net/browse/DOCS-10503)
```
/merge
```
[DOCS-10503]: …

Remove unavailable reference link

---

content/en/containers/kubernetes/distributions.md

Updating AKS distro information with help of Jack Davenport
```
/merge
```

K8s AKS distro update

---

content/en/monitors/types/cloud_cost.md

[CCM] remove preview message, anomalies is GA

---

content/en/real_user_monitoring/browser/advanced_configuration.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/flutter/error_tracking.md

Addressing broken links that were reported in the following Jira cards:
- https://datadoghq.atlassian.net/browse/DOCS-10498
- https://datadoghq.atlassian.net/browse/DOCS-10501
```
/merge …
```

Fix broken RUM browser and Flutter URLs

---

content/en/tracing/guide/ddsketch_trace_metrics.md
content/en/tracing/metrics/metrics_namespace.md

Remaining updates on primary tags feature

---

config/_default/menus/main.es.yaml
config/_default/menus/main.fr.yaml
config/_default/menus/main.ja.yaml
config/_default/menus/main.ko.yaml

Temporarily fix the translated nav. Chatted with websites about this.
Preview: https://docs-staging.datadoghq.com/may/fix-cloud-siem-translated-nav/es/security/cloud_siem/
```
/merge
```

[DOCS-10572] Fix translated Cloud SIEM navs

---

content/en/opentelemetry/agent/migration.md
content/en/opentelemetry/guide/migrate/migrate_operation_names.md

Fix link with new path.

---

data/synthetics_worker_versions.json

Manual bump of windows-pl version
```
/merge
```

build: ⬆️ bump PL version to 1.56.0

---

content/en/service_management/on-call/schedules.md

Add export entire schedule documemtation

---

content/en/security/code_security/static_analysis/setup/_index.md

Internal customers asked us to document our SARIF
Document the SARIF format and explains what parts are important

Documenting SARIF format

---

content/en/observability_pipelines/advanced_configurations.md

[DOCS-10578] Update advanced_configurations.md

---

content/en/opentelemetry/setup/intake_endpoint/otlp_logs.md

Fix Troubleshooting section spacing

---

config/_default/menus/main.en.yaml
content/en/developers/faq/_index.md
content/en/developers/faq/hubot-script-request-snapshots-in-chat-using-the-datadog-api.md
content/en/real_user_monitoring/error_tracking/browser.md
content/en/real_user_monitoring/error_tracking/error_grouping.md
content/en/real_user_monitoring/error_tracking/troubleshooting.md

This PR is meant to test the re-use full page markdown on an Error Tracking Documentation
```
/merge
```

Using the resuse full page markdown shortcode to fix some page jumps

---

content/en/glossary/terms/device_namespace.md
content/en/glossary/terms/device_profile.md
content/en/glossary/terms/mib.md
content/en/glossary/terms/oid.md
content/en/glossary/terms/ping.md
content/en/glossary/terms/sd-wan.md
content/en/glossary/terms/sysoid.md

Adding missing NDM terms to the glossary
```
/merge
```

updating NDM glossary terms

---

config/_default/menus/main.en.yaml
content/en/tracing/other_telemetry/rum/_index.md

- When clicking the Correlate Traces with with RUM page, it was jumping to the same page in the APM section due to a hierarchy issue. This fixes that by giving APM its own page with a content reuse shortcode. …

[rum] Fix jump for correlate traces with RUM

---

content/en/security/cloud_security_management/setup/agentless_scanning/enable.md
layouts/shortcodes/cloud-siem-aws-setup-cloudformation.en.md

DOCS-10581. Updates Cloud Security Management docs to match new onboarding flow.
```
/merge
```

DOCS-10581: Cloud Security Management onboarding updates

---

content/en/developers/dogstatsd/dogstatsd_mapper.md

Removes quotes in examples.
```
/merge
```

(dev) Fix examples

---

content/en/data_jobs/databricks.md
content/en/data_jobs/dataproc.md
content/en/data_jobs/emr.md

Update DJM init scripts version to 0.12.9 which was released today
```
/merge
```

[DJM] Update scripts version to 0.12.9

---

content/en/opentelemetry/setup/intake_endpoint/otlp_metrics.md
content/en/opentelemetry/setup/intake_endpoint/otlp_traces.md

- We have info on dd-otlp-source header in the Troubleshooting section, but it's getting missed.
- Add new explicit alert box after code example to make sure readers don't miss it.
``` …
```

Clarify dd-otlp-source header for OTLP intake endpoint

---

layouts/shortcodes/appsec-getstarted-2-canary.ko.md

You are getting sleepy, veeeery sleepy...
```
/merge
```

Fix random typo I found in KO

---

content/en/service_management/incident_management/incident_settings/information.md

The explanation of the private incidents setting is not accurate so I'm updating it.
```
/merge
```

Update private incidents in the incident management settings docs

---

content/en/account_management/rbac/granular_access.md

[docs] add actions and remediations resources to granular access control page

---

content/en/security/cloud_security_management/severity_scoring.md

was linking to a detection rule, the URL of that detection rule seems to have changed
```
/merge
```

fix the link checker

---

content/en/integrations/guide/aws-manual-setup.md

Propose using inline policies instead of attached policies during role creation. Inline policies has a larger character quota https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html
To have your PR automatically merged after it receives the required reviews, add the following …

[AWSX-1558] Update AWS Integration manual setup page to use inline policies

---

content/en/logs/workspaces/sql_reference.md

This PR aims to standardize the case sensitivity of SQL functions in the documentation. We're taking an approach where: =
- lower case function names are used in tables when listing down functions 
- upper case function names are used in sample SQL queries where other key words are also in all upper case
This formatting behavior is also seen in docs like [Postgres](https://www.postgresql.org/docs/current/functions-window.html) and personally prefer it as lower case function names are easier on the eyes when reading a list, and upper case function names in SQL they're more widely used. 
Jira: https://datadoghq.atlassian.net/browse/LOGSQ-830
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and …

Standardize case sensitivity for SQL functions

---

content/en/actions/datastore/_index.md

this adds the "limitations" section to the Actions Datastore docs
```
/merge
```

add limitations to datastore docs

---

content/en/service_management/case_management/automation_rules.md

- Add note on limited support for us1-fed
- Add more content to the overview
```
/merge
```

Add note on us1-fed support and edited overview

---

content/en/logs/workspaces/sql_reference.md

The `INTERVAL` data type behaves slightly differently as we only support unit types < `month`. Adding an explicit list of supported unit types in our documentation. 
Jira: https://datadoghq.atlassian.net/browse/LOGSQ-830
To have your PR automatically merged after it receives the required …

Provide a list of supported interval time units

---

content/en/database_monitoring/setup_postgres/_index.md

Adds support for Postgres 17 to DBM docs. Requested by PM.
```
/merge
```

Add support for Postgres 17

---

content/en/bits_ai/query_examples.md

Removes NLQ for CCM as it's no longer available.  This caused some confusion for demoers in the Demo Org.  [[slack thread](https://dd.slack.com/archives/CB3576362/p1744231661692589?thread_ts=1744231347.949159&cid=CB3576362)]
I asked in [#nlq-feedback channel](https://dd.slack.com/archives/C05BDAKGKT3/p1744233398919749?thread_ts=1744232590.375709&cid=C05BDAKGKT3) and NLQ for CCM was removed: https://datadoghq.atlassian.net/wiki/spaces/DA/pages/4198137981/NLQ+Product+Locations#Graveyard
It looks like it could come back later in the future.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab …

Removes CCM section for Natural Language Queries

---

content/en/synthetics/mobile_app_testing/_index.md

This adds a note to correlating RUM data with MAT for business opportunities / customer engagement. 
```
/merge
```

Add mention of RUM SDK within MAT docs

---

content/en/profiler/enabling/supported_versions.md

Adds the Memory Leaks workflow to the supported features by language table.
```
/merge
```

Add Memory Leaks to profiling feature table.

---

content/en/real_user_monitoring/guide/best-practices-for-rum-sampling.md

Updates the language around contacting support to "create a ticket" for changing the sampling rate to "create a feature request" for clarity.
```
/merge
```

[DOCS-10630] Update sampling feature request language

---

content/en/agent/logs/_index.md

This PR adds a walkthrough to add logging to Windows PL.
```
/merge
```

Add Windows PL logging docs

---

content/en/network_monitoring/devices/ping.md

The instances section was improperly indented and should be on the same level as `init_config`.
Before: https://github.com/DataDog/documentation/pull/26588/files#diff-142a0fd918ababc5ab6ff25eceffab59e162b6e57c41889e9108f917d22b2a20L202-L217
To have your PR automatically merged after it receives …

[DOCS-10590] fixing ping config

---

content/en/opentelemetry/guide/migrate/ddot_collector.md
content/en/opentelemetry/setup/ddot_collector/custom_components.md
content/en/opentelemetry/setup/ddot_collector/install.md
content/es/opentelemetry/agent/agent_with_custom_components.md
content/es/opentelemetry/agent/install_agent_with_collector.md
data/versions.yaml

1. Removes obsolete `datadog/connector` config
2. Removes `agent_tag_jmx` in favor of `agent_tag`
3. Updates DDOT Collector version, Agent and branch version to the GA release v7.65
4. Makes OTel and DD Agent configs consistent across examples
5. Reverts completed `datadog-values.yaml`/`datadog-agent.yaml` files (we needed to remove it only in one place, not all of them)
6. Hides "Instrument the application" implementation details. We don't have a good example of instrumentation in our docs; it's better to keep it in a collapsed block rather than remove it completely.
7. Add UST instructions (OpenTelemetry Resource Attributes environment variable **and** Kubernetes labels on the deployments and pods level)
Merge queue is enabled in this repo. …

OTAGENT-318 Fixes for DDOT GA release

---

content/en/logs/guide/azure-logging-guide.md

Expand the existing archive setup instructions with links and additional detail
```
/merge
```

[DOCS-10394] Expand archiving setup instructions

---

content/en/containers/docker/tag.md
content/en/containers/kubernetes/tag.md
content/en/developers/dogstatsd/_index.md
content/en/getting_started/tagging/assigning_tags.md
content/en/tracing/trace_collection/tracing_naming_convention/_index.md

Adds context about the Container Tags and Cardinality for DogStatsD Custom Metrics and APM Traces.
```
/merge
```

chore(cardinality): improve documentation

---

content/en/opentelemetry/setup/ddot_collector/custom_components.md

Add explicit instructions to keep `datadog/agent` image name to ensure that all platform features work correctly.
```
/merge
```

feat(otel-agent): Add instructions for BYOC image name

---

content/en/getting_started/tracing/_index.md
content/en/security/application_security/threats/setup/single_step/_index.md
content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
content/es/getting_started/tracing/_index.md
content/es/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md
content/ja/getting_started/tracing/_index.md
content/ja/security/application_security/threats/setup/single_step/_index.md
content/ja/tracing/trace_collection/automatic_instrumentation/single-step-apm/_index.md

Updates the SSI instructions for the Python SDK to use major version 3 (the current major version). This aligns the docs with the UI which already shows version 3.
```
/merge
```
None

Update SSI instructions to use the current major version for the Python SDK

---

layouts/shortcodes/integration_categories.en.md
layouts/shortcodes/integration_categories.fr.md
layouts/shortcodes/integration_categories.ja.md
layouts/shortcodes/integration_categories.ko.md

Updates integration categories to match the in-app options. Integration validations are currently failing because incorrect values are being submitted by partners who are copying them from our docs. …

Dd dominic/update integration categories

---

content/en/software_catalog/endpoints/_index.md

Add disclaimer that Endpoint Observability is not available for FED.
```
/merge
```

Endpoint Obs not available on gov

---

content/en/data_security/data_retention_periods.md
content/en/security/cloud_security_management/troubleshooting/threats.md
content/en/service_management/incident_management/declare.md

Updates references to security products to match new product names. 
```
/merge
```

Update security product names

---

content/en/data_streams/guide/metrics-and-tags.md

Updates wording based on discussion in https://dd.slack.com/archives/C06P5GB4UT1/p1744828701814349
```
/merge
```

Update edge pathway_type description in metrics-and-tags.md

---

content/en/logs/log_collection/kotlin_multiplatform.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/setup.md

This PR adds iOS SDK version used in the new KMP SDK release.
```
/merge
```

Update iOS SDK version for the KMP SDK 1.1.0 release

---

content/en/security/threat_intelligence.md

Reverts DataDog/documentation#28785

Revert "Add Cloud SIEM threat intel categories"

---

go.mod
go.sum

https://datadoghq.atlassian.net/browse/WEB-6311
updates the go.sum versioning to receive latest websites modules version to get latest icons.
```
/merge
```

Websites modules/generated/407

---

content/en/agent/configuration/network.md

A customer had a question about what "all other Agent data" consisted of. These changes make it more explicit. It's possible we may want to reorder this entry but I'll leave it to you all to decide where it fits best on the page :) …

Call out more Agent data types explicitly

---

content/en/tracing/guide/ignoring_apm_resources.md

Sampling achieves a different result than filtering, so this docs PR attempts to clarify that.
```
/merge
```

[APM] clarify "sampling" vs "filtering" in the Ignore Resources doc

---

content/en/agent/basic_agent_usage/aix.md

Small edit to test the required approval check.
```
/merge
```

(Agent) Use UNIX instead of Unix

---

content/en/bits_ai/query_examples.md

Legal here, Datadog is legally obligated to add "Built with Llama" to its product documentation for any GenAI feature that is powered by LLama LLMs. Please do not remove this blue blox without legal approval and we'll likely need to put it else where.  Additional information is available at prodlegel-862. https://datadoghq.atlassian.net/browse/PRODLEGAL-862
Llama License is available at https://www.llama.com/llama3_1/license/
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to …

Legal Notice to comply with Llama License

---

content/en/data_streams/dotnet.md
content/en/data_streams/go.md
content/en/data_streams/nodejs.md
content/en/data_streams/python.md

Disclose a limitation of DSM & Kafka when using a broker with a message format version that is too old to support Kafka Haeders.
```
/merge
```

Add Kafka Message Version Notes For DSM Kafka Monitoring

---

content/en/security/code_security/software_composition_analysis/setup_static/_index.md

Document third-party SBOM upload
1. Explain the standards we support
2. Explain the constraints of the data model we support
3. Add the command example that shows how to upload the file
Please edit as much as you need and merge once approved

Document third-party SBOM upload

---

config/_default/menus/main.en.yaml

Pricing page was missing from the Left Nav and numbering was incorrect.
```
/merge
```

fix pricing page and numbering

---

content/en/security/_index.md

DOCS-10670
- added Workload Protection
- added Code Security

updating Sec overview with new prod names DOCS-10670

---

content/en/continuous_integration/troubleshooting.md

Update CI documentation based on current limitations on job processing
```
/merge
```

Add pipeline jobs limitations description

---

content/en/containers/guide/operator-eks-addon.md

Remove the hard-coded EKS private registry and insert placeholder instead.
Customers are just copy/pasting this config, not realizing that it is an example for a private registry configuration (I guess we own this registry?), and then encountering an authentication error as they do not have access to this registry.
If your branch doesn't follow this format, rename it or create …

Update operator-eks-addon.md - EKS private registry

---

layouts/shortcodes/latest-lambda-layer-version.html

feat: Bump lambda extension to 77

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/compatibility.md

PHP SSI support is GA for a few months. Also, we support PHP 8.4.
```
/merge
```

PHP Single Step Instrumentation is GA

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/android/setup.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/flutter/setup.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/setup.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/setup/expo.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/react_native/setup/reactnative.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/roku/setup.md

This PR removes a wrong statement on how configuring the session sample rate does not apply to Error Tracking.
```
/merge
```

[error-tracking][documentation] Update documentation on session sample rate for Error Tracking

---

content/en/logs/workspaces/sql_reference.md

Document the concat function
https://datadoghq.atlassian.net/browse/LOGSQ-876

Document concat (||) function WIP

---

content/en/notebooks/_index.md

Add aliases for notebooks docs
```
/merge
```

Add notebook aliases

---

config/_default/params.en.yaml

Update link of announcement banner
```
/merge
```

[WEB-6243] update announcement banner link

---

content/en/tracing/metrics/runtime_metrics/_index.md

Add missing aliases for Runtime Metrics

---

content/en/notebooks/_index.md

Reverts DataDog/documentation#28937

Revert "Add notebook aliases"

---

content/en/error_tracking/error_grouping.md

Reordered the tabs to be in alphabetical order from Android to React
```
/merge
```

DOC 9781 - Reordered the tabs

---

content/en/software_catalog/service_definitions/v3-0.md

Removes note that is no longer true
```
/merge
```

Removes note that is no longer true from Software Catalog v3

---

content/en/security/application_security/threats/setup/compatibility/php.md

Update PHP ASM Support page with:
- Make explicitly clear Windows is not supported
- Remove SCA incompatibility
- Update supported framework versions
```
/merge
```

Update PHP ASM support page

---

content/en/data_jobs/airflow.md

Specify how to customize env tags in Airflow DJM

---

content/en/real_user_monitoring/browser/advanced_configuration.md

- A few minor edits to RUM since some PRs weren't reviewed by docs
```
/merge
```

Minor rum edits

---

content/en/actions/datastore/_index.md

Removes the "preview" callout, now that we have GA-ed! 🎉 
```
/merge
```

remove "preview" callout from datastore docs

---

content/en/observability_pipelines/destinations/amazon_s3.md

Adds Snowflake section.
```
/merge
```

[DOCS-10642] Add Snowflake section to OP Amazon S3 destination

---

content/en/data_streams/dotnet.md
content/en/data_streams/go.md
content/en/data_streams/java.md
content/en/data_streams/nodejs.md
content/en/data_streams/python.md
layouts/shortcodes/data-streams-monitoring/monitoring-rabbitmq-pipelines.md

Add recommendation for installing the RabbitMQ integration, so that all graphs under Data Streams Monitoring fully populate.
```
/merge
```

add recommendation for RabbitMQ integration

---

content/en/security/code_security/software_composition_analysis/setup_static/_index.md
content/en/security/code_security/troubleshooting/_index.md

This PR will change the link of the repository settings in SCA Setup and Troubleshooting pages to point to "Link Source Code".
```
/merge
```

[SCA] Change Repo Settings Link in SCA Setup + Troubleshooting page

---

content/en/data_jobs/databricks.md

Remove line that implies a token can have no expiry. Replace with line that instructs user to set token expiration to max allowed (730 days). 
This also has the nice side effect of making the bullet points under "Important" all pertain to access permissions.
To have your PR automatically merged …

[DJM] Update Databricks doc to correctly reflect token expiration

---

content/en/network_monitoring/network_path/_index.md
content/en/network_monitoring/network_path/setup.md

Remove CNM requirement for Network Path
```
/merge
```

Remove CNM requirement for Network Path

---

content/en/security/code_security/static_analysis/setup/_index.md

Document how we map SARIF to CVSS mapping
Write down our mapping rules
Please edit as much as needed and merge once it's good.

Document SARIF to CVSS severity mapping

---

content/en/infrastructure/resource_catalog/_index.md

We are updating the product name to Resource Changes. This will be reflected in the side UI. We are changing our documentation and links to support this.
```
/merge
```

Update Recent Changes to Resource Changes to support new UI and naming

---

content/en/error_tracking/explorer.md
content/en/tracing/error_tracking/_index.md

Improve APM Error Tracking documentation:
- List some notable error attributes that can be used to filter.
- Document `error.handling`, in particular the difference between APM and RUM.
- Reword the conditions to get an error span tracked in Error Tracking.
To have your PR automatically merged …

improve documentation of APM Error Tracking

---

content/en/tracing/trace_collection/library_config/_index.md

This is a dupe of [this PR](https://github.com/DataDog/documentation/pull/28920), recreated to follow proper branch name conventions.
```
/merge
```

Update experimental docs

---

content/en/opentelemetry/instrument/instrumentation_libraries.md

I saw this typo in a PR from when I was on call, and decided to check to see if it was anywhere else. Overwhelmingly, it wasn't.
```
/merge
```

Fix lowercase "t" in "OpenTelemetry"

---

local/bin/py/build/configurations/pull_config.yaml
local/bin/py/build/configurations/pull_config_preview.yaml

Pull the CWS agent documentation from the 7.66.x branch.
Most notably, this will include the CSM Threats product renaming to Workload Protection introduced by this PR https://github.com/DataDog/datadog-agent/pull/36070
To have your PR automatically merged after it receives the required reviews, …

Pull CWS agent documentation from 7.66.x branch

---

content/en/agent/guide/fips-agent.md

remove Preview from FIPS Agent docs

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/android.md

https://datadoghq.atlassian.net/browse/DOCS-10490
Add import statements to code samples in Kotlin Extensions section, and adjust indentations.
```
/merge
```

DOCS-10490

---

content/en/data_security/agent.md

Add the `service_discovery.discovered_services` metric to the list of collected telemetry, to reflect latest changes on the agent. This telemetry is only collected if the Service Discovery feature of the Agent is enabled.
To have your PR automatically merged after it receives the required …

agent data security: add service discovery to telemetry content

---

content/en/serverless/aws_lambda/configuration.md

Add AWS MSK to the table for renaming services.
Motivation: https://github.com/DataDog/datadog-lambda-extension/pull/666
```
/merge
```

Add MSK to Serverless Configuration Page

---

content/en/observability_pipelines/destinations/amazon_s3.md

Clarify that you only need to set up Log Archive if you want to archive and rehydrate.
```
/merge
```

Update Amazon S3 destination docs

---

layouts/shortcodes/observability_pipelines/processors/remap_ocsf.md

Remove preview.
```
/merge
```

Remove preview for Remap OCSF

---

content/en/security/cloud_security_management/misconfigurations/frameworks_and_benchmarks/supported_frameworks.md

Small PR to fix a broken link for one of our external framework providers 🙂 
```
/merge
```

Fix broken SOC 2 link

---

content/en/dashboards/widgets/timeseries.md

This feature is deprecated.
- Remove the option to compare to previous time periods. This feature is deprecated.
```
/merge
```

Remove feature for time comparison

---

config/_default/menus/main.en.yaml

Replace Datastore logo
```
/merge
```

(Actions) Replace Datastore logo

---

layouts/shortcodes/observability_pipelines/processors/remap_ocsf_library_mapping.md

Add OCSF library mapping for Microsoft Defender
```
/merge
```

[DOCS-10738] Add Microsoft 365 Defender OCSF library mapping

---

content/en/dashboards/widgets/wildcard.md

Add external link to [datadog_dashboard_json](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard_json) resource in the [Wilcard Widget](https://docs.datadoghq.com/dashboards/widgets/wildcard/) doc page, under the Terraform integration section.
No special considerations …

Docs / Add external link to datadog_dashboard_json resource

---

content/en/logs/log_configuration/pipelines.md

- Clarify that pipeline tags have no impact on logs and add a use case.
- https://github.com/DataDog/documentation/issues/28172
- [DOCS-10661](https://datadoghq.atlassian.net/browse/DOCS-10661) …

Clarify use case for pipeline tags

---

content/en/account_management/billing/product_allotments.md
content/en/getting_started/devsecops/_index.md
content/en/infrastructure/containers/container_images.md
content/en/security/cloud_security_management/misconfigurations/kspm.md

A small PR to remove the Cloud Security SKU names from the docs, which have caused confusion in the past as those SKUs have changed over time.
```
/merge
```

Remove Cloud Security SKUs from docs

---

content/en/cloud_cost_management/container_cost_allocation.md

We often get customers asking about these details. This information is already in the docs but it is not easy to find. This PR helps to clarify it some more and direct users to the correct fully detailed doc on tag extraction.
Note that I left the lines that look like this as I thought it adds extra clarity but if that is too redundant I can remove it
> **Note**: Only _tags_ from pods and nodes are added to cost metrics. To include labels, enable labels as tags for [nodes][101] and [pods][102].
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a …

Clarify tag extraction docs for CCM

---

content/en/opentelemetry/integrations/_index.md

Explain standard vs custom metric pricing for OTel integrations

---

content/en/monitors/configuration/_index.md
content/en/monitors/types/log.md

- Add a note clarifying the rolling window for log monitors
- [DOCS-10648](https://datadoghq.atlassian.net/browse/DOCS-10648)
```
/merge
```
[DOCS-10648]: …

Add a note about log monitor rolling window

---

content/en/security/code_security/dev_tool_int/github_pull_requests/_index.md

This is an old screenshot for Code Analysis. The UI has changed.

removing outdated screenshot

---

content/en/security/workload_protection/troubleshooting/threats.md

we changed CSM -> Workload Protection

correcting product name in Workload Protection troubleshooting

---

content/en/agent/guide/fips-agent.md

Recommended change from Fed team to simply have the (US1-FED) not both (US1-FED or GovCloud) as they are the same thing.
```
/merge
```

DOCS-10769 - Update fips-agent.md

---

content/en/infrastructure/containers/container_images.md
content/en/security/cloud_security_management/setup/agent/docker.md
content/en/security/cloud_security_management/setup/agent/kubernetes.md
content/en/security/cloud_security_management/troubleshooting/vulnerabilities.md
content/es/infrastructure/containers/container_images.md
content/ja/infrastructure/containers/container_images.md
content/ko/infrastructure/containers/container_images.md

Since few quarter CSM pro allow customer to have CSM vm for hosts and container images for the same price.
```
/merge
```

[K9VULN-4927] Update CSM vm config

---

content/en/containers/amazon_ecs/_index.md

Update FIPS proxy version to 1.1.10
```
/merge
```

Update FIPS proxy version to 1.1.10

---

content/en/integrations/_index.md

Redirect an integration's former URL to its new one
**Not** ready to merge
```
/merge
```

[DOCS-10702] Redirect integration

---

content/en/opentelemetry/setup/ddot_collector/custom_components.md

Updates BYOC instructions for DDOT GA release (7.65.0)

feat(otel-agent): Update BYOC instructions for GA release

---

content/en/api/latest/rate-limits/_index.md

updating the rate limit to 250k

---

content/en/llm_observability/setup/auto_instrumentation.md

This PR fixes some wrong links in our autoinstrumentation page (which were messed up due to a preivous merge conflict).
```
/merge
```

Fix links to LLMObs autoinstrumentation docs

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/integrated_libraries.md

Adding OpenAPI Generator alongside other supported libraries on iOS.
```
/merge
```

Update supported libraries with OpenAPI generator

---

content/en/security/cloud_security_management/misconfigurations/_index.md

Fixes an anchor link in the Cloud Security Misconfigurations overview doc.
```
/merge
```

Fix anchor link in Cloud Security Misconfigurations

---

content/en/cloud_cost_management/container_cost_allocation.md

Clarifies that CCM only supports GKE Autopilot as an agentless kubernetes experience. 
```
/merge
```

clarify GKE Autopilot support

---

content/en/integrations/faq/list-of-api-source-attribute-value.md

Updating this so customers can use the example query in the event explorer
```
/merge
```

edit example query so it works

---

assets/scripts/components/codetabs.js
assets/styles/components/_tab-toggle.scss
assets/styles/pages/_global.scss
content/en/tracing/metrics/runtime_metrics/_index.md

Reverts DataDog/documentation#28476

Revert "[Q1 2025 Hackathon] Update Tab Styling"

---

content/en/database_monitoring/connect_dbm_and_apm.md

This PR adds `dd-trace-py` support for APM DBM correlation for MongoDB. 
```
/merge
```

Add dd-trace-py support for APM DBM for MongoDB

---

content/en/data_security/data_retention_periods.md

The document explains the profile retention period for Continuous Profiler in a confusing way.
Current details in Doc :
1. Profiles (not displayed in the UI): 8 days
2. Profiles (displayed in the UI): 1 year
Explanation:
Here profiles represent single profiles, and we have 8 days retention period for all profiles which are not opened.
Also we save single profiles of interest, (ie profiles which are opened in between for details) for 1 year. This is send to the long retention S3
The current wordings in the doc seems to be bit confusing
So updated to below:
1. Individual profiles (not opened in the UI): 8 days
2. Individual profiles (opened in the UI at least once): 1 year
Merge queue is enabled in this repo. Your branch name MUST follow the …

Update data_retention_periods.md -Retention period for Profiler

---

content/en/logs/workspaces/use_cases/analyze_login_attempts.md

Fix typo in "[Analyze Login Attempts for e-PHI](https://docs.datadoghq.com/logs/workspaces/use_cases/analyze_login_attempts/)" Log Workspaces use case
```
/merge
```

Fix typo in "Analyze Login Attempts for e-PHI" Log Workspaces use case

---

content/en/opentelemetry/guide/_index.md
content/en/opentelemetry/setup/ddot_collector/_index.md

Fix blog link for DDOT Collector

---

content/en/serverless/azure_app_services/azure_app_services_linux.md

Continuous profiler now support Node profiler for Linux Azure App Services
```
/merge
```
JIRA: [PROF-10802]
[PROF-10802]: https://datadoghq.atlassian.net/browse/PROF-10802?atlOrigin=eyJpIjo …

Update azure_app_services_linux.md - Add Continuous profiler support for node.js

---

content/en/data_streams/setup/language/dotnet.md
content/en/data_streams/setup/language/nodejs.md
content/en/data_streams/setup/language/python.md

[DSM] Add keep service name env variable to all languages rather than just Java

---

content/en/observability_pipelines/set_up_pipelines/_index.md

Fix links in OP Set Up Pipelines

---

content/en/integrations/syslog_ng.md

Remove a notice about unsupported DCs for syslog NG. This was fake news.
```
/merge
```

Remove notice about unsupported DC

---

content/en/agent/configuration/fips-compliance.md

Aliases are not working for this page because the frontmatter says "alias." This PR replaces "alias" with the correct "aliases."
```
/merge
```

Replace alias with aliases so the aliases work

---

content/en/security/code_security/troubleshooting/_index.md

We've identified a use-case that's not supported by Datadog-hosted scanning that's not documented.
```
/merge
```

Add section to troubleshooting guide for invalid paths and Datadog-hosted scans

---

content/en/data_security/data_retention_periods.md

This naming change got missed so a quick PR to update it to Cloud Network Monitoring
```
/merge
```

fix name on data retention page

---

layouts/shortcodes/latest-lambda-layer-version.html

chore: Datadog Lambda Extension v78

---

layouts/shortcodes/observability_pipelines/processors/dedupe.en.md
layouts/shortcodes/observability_pipelines/processors/parse_xml.md
layouts/shortcodes/observability_pipelines/processors/remap.en.md
layouts/shortcodes/observability_pipelines/processors/sds_custom_rules.md
layouts/shortcodes/observability_pipelines/processors/sds_library_rules.md
layouts/shortcodes/observability_pipelines/processors/split_array.md

Adds another example for Path Notation.
Same update for all files (find and replace).
Preview: https://docs-staging.datadoghq.com/may/add-another-path-notation-example/observability_pipelines/processors/dedupe#path-notation-example …

[DOCS-10745] Add another example to path notation

---

content/en/product_analytics/guide/rum_and_product_analytics.md

Per PM request, updated the link which currently takes users to the infrastructure pricing page instead of the session replay pricing page.
```
/merge
```

Update session replay link

---

content/en/observability_pipelines/update_existing_pipelines.md

Adds linke to the API and TF for updating a pipeline.
```
/merge
```

Add links to API and TF

---

content/en/data_streams/setup/language/java.md

DOCS-10754: DSM - Self-hosted Kafka connectors instrumentation for Java

---

layouts/shortcodes/latest-lambda-layer-version.html

chore: Datadog Lambda Python 108 Release

---

content/en/data_streams/setup/language/java.md
content/en/data_streams/setup/technologies/kafka.md

A more informative parenthetical about limited support for kafka-client 3.7
```
/merge
```

DOCS-10599 - DSM kafka-client better parenthetical

---

content/en/security/code_security/troubleshooting/_index.md

This adds another section to the Code Security troubleshooting docs for the services/teams feature.

Add section for services/teams not updating

---

content/en/database_monitoring/setup_postgres/azure.md

- From #documentation, someone noticed that the config lists AWS fields for Azure setup instructions.
```
/merge
```

Replace AWS fields with Azure

---

content/en/continuous_integration/troubleshooting.md
content/en/security/code_security/static_analysis/generic_ci_providers.md
content/en/tests/troubleshooting/_index.md
content/es/continuous_integration/troubleshooting.md
content/es/security/code_security/troubleshooting/_index.md
content/es/tests/troubleshooting/_index.md
content/fr/continuous_integration/troubleshooting.md
content/fr/tests/troubleshooting/_index.md
content/ja/continuous_integration/troubleshooting.md
content/ja/tests/troubleshooting/_index.md
content/ko/continuous_integration/troubleshooting.md
content/ko/tests/troubleshooting/_index.md

The old path `/ci/settings/repository` is being deprecated and the new path is `/source-code/repositories`.
```
/merge
```

Update link to Repo settings

---

content/en/data_jobs/airflow.md

Docs for how to set up logs collection for Airflow on K8s. 
```
/merge
```

[DJM-781] Docs for Airflow on K8s logs collection

---

content/en/monitors/manage/_index.md

- Make the instructions generic and non-specific to the UI.
- [DOCS-10775](https://datadoghq.atlassian.net/browse/DOCS-10775)
```
/merge
```
[DOCS-10775]: …

Make instructions generic

---

content/en/security/code_security/static_analysis/setup/_index.md

Fix severities and put the correct SARIF severities in the list/table.

Fix SARIF severities

---

content/en/data_security/data_retention_periods.md

Adds Database Monitoring query metrics to data retention periods table.
```
/merge
```

DOCS-10846: Add DBM query metrics

---

content/en/real_user_monitoring/browser/advanced_configuration.md

The current link is incorrect - this updates to the correct link.
```
/merge
```

Fix link to beforeSend guide

---

content/en/tracing/live_debugger/_index.md

Adding a demo video to the Live Debugger docs to help preview customers get onboarded. Demo video was self-recorded and edited by the debugger team due to lack of bandwidth on the video team. We will replace this demo video with a formally-produced version when the video team has bandwidth (likely after DASH), but an informal  version is necessary now to make the Live Debugger preview a success.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, …

Live Debugger - Add DIY demo video to the docs

---

content/en/network_monitoring/devices/supported_devices.md

Fixes some broken links on the NDM Supported devices page
```
/merge
```

[DOCS-10839] fixing links

---

config/_default/params.yaml
layouts/partials/api/get-endpoint.html

https://datadoghq.atlassian.net/browse/WEB-6430
```
/merge
```
This shouldn't change any current endpoints 
e.g https://docs-staging.datadoghq.com/david.jones/endpoint-support/api/latest/ip- …

Support other endpoint urls 

---

content/en/tracing/trace_collection/compatibility/java.md
content/en/tracing/trace_collection/library_config/java.md

Add dd-trace-java websocket documentation

---

content/en/observability_pipelines/install_the_worker/worker_commands.md

Adds a sentence about how to find the component ID.
```
/merge
```

Add to the tap command

---

content/en/getting_started/containers/datadog_operator.md

- Fix the alignment so that the code examples fall in line with the numbered list.
```
/merge
```

Fix the code alignment with the numbered list

---

content/en/tracing/troubleshooting/tracer_debug_logs.md

There's a conflict between the warning and the prereqs. This PR clarifies the supported languages.
```
/merge
```

[Tracer Flare] fix supported tracer sentence

---

content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md

Fix typo in AWS Integration IAM Policy:
`cloudtrail.ListTrails -> cloudtrail:ListTrails`
Fix typo in AWS Integration IAM Policy.
```
/merge
```

Fix typo in send-aws-services-logs-with-the-datadog-lambda-function.md

---

content/en/getting_started/security/cloud_siem.md

Adds small section on how to disable Cloud SIEM.
```
/merge
```

Add disable Cloud SIEM section

---

content/en/synthetics/guide/browser-tests-using-shadow-dom.md

This PR adds a callout note with information that we now support testing a Shadow DOM via normal browser recording steps, but maintains the workaround instructions in the doc.
```
/merge …
```

[DOCS-10776] Update open shadow DOM

---

content/en/service_management/events/guides/email.md

Adds new specifications for 'Events with Email' documentation to reflect the new usages we have developed.
```
/merge
```

Adds new specifications for 'Events with Email' documentation

---

content/en/continuous_integration/pipelines/custom_tags_and_measures.md

Fix Windows datadog-ci download url

---

content/en/real_user_monitoring/rum_without_limits/_index.md

It was not clear why the + Filter button was missing from the Performance Summary page. This note provides an explanation.
```
/merge
```

Add note about no filter button for RWOL

---

assets/scripts/components/copy-code.js

adds copy button to `sql` markdown fenced codeblocks
- adjusts script to allow for case insensitive matches
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-6066
preview: https://docs-staging.datadoghq.com/stefon.simmons/copy-btn-sql-WEB-6066/database_monitoring/setup_oracle/selfhosted/?tab=multitenant#create-the-datadog-user
- check that `SQL` code blocks have a copy button
- there are also `shell` and `yaml` codeblocks on the page that should still have copy buttons
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not …

add copy btn to sql codeblocks - [WEB-6066]

---

content/en/partners/getting_started/_index.md

Fix link to blog from Partner docs

---

content/en/tracing/metrics/runtime_metrics/_index.md

We had temporary HTML on the Runtime Metrics page to better distinguish tab content. This is no longer needed with [the new tab styling](https://github.com/DataDog/documentation/pull/29189). …

Remove HTML on Runtime Metrics page for new site-wide tab style.

---

content/en/service_management/on-call/automations.md

https://datadoghq.atlassian.net/browse/DOCS-10864
```
/merge
```

Add gov callout on on call automation page

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/compatibility.md

Add Python 3.13 and also change K8s support status from Preview to GA.
```
/merge
```

Update SSI Compatibility page to include Python 3.13 support

---

content/en/llm_observability/configuration/_index.md
content/en/llm_observability/terms/_index.md

This pr adds documentation about the enriched Failure to Answer options. The Failure to Answer options are described [here](https://docs.google.com/document/d/1-dsbGsjOMml32hhCX1HOVXJee1VwfEOzcvl8RYnDcso/edit?tab=t.0#heading=h.8d3o7vtyu1y1).
To have your PR automatically merged after it receives …

added failure to answer configuration option explanation

---

layouts/shortcodes/latest-lambda-layer-version.html

Bump Lambda Layer Versions

---

content/en/opentelemetry/getting_started/_index.md

(maint) Remove circular redirect

---

content/en/real_user_monitoring/browser/setup/server/nginx.md

Update nginx available versions

---

content/en/observability_pipelines/best_practices_for_scaling_observability_pipelines.md

Add info for high throughput
```
/merge
```

Add info for high throughput

---

content/en/security/code_security/software_composition_analysis/setup_static/_index.md
content/en/security/code_security/static_analysis/setup/_index.md

Provide clear instructions to associate a full repo with the service.
Add the snippet that should be used. It should cover all the cases where a repository is used for one service.
Please address any typo/mistakes and merge once okay.

add default glob

---

content/en/data_jobs/emr.md

Callout K8s docs for EMR on EKS
```
/merge
```

Callout K8s docs for EMR on EKS

---

content/en/agent/faq/_index.md

(Agent) Remove the word deprecation from title

---

content/en/logs/workspaces/_index.md

- Workspaces is GA, remove the Preview banner
```
/merge
```

Remove Preview banner

---

content/en/service_management/case_management/view_and_manage/_index.md

- [DOCS-10866](https://datadoghq.atlassian.net/browse/DOCS-10866)
```
/merge
```
[DOCS-10866]: https://datadoghq.atlassian.net/browse/DOCS-10866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

Add availability alert

---

content/en/integrations/guide/source-code-integration.md

Updated the Node.js instructions to be more specific about the source map requirements for transpiled Node applications. 
```
/merge
```

Update Node.js source map instructions on SCI docs

---

content/en/opentelemetry/setup/ddot_collector/_index.md

- We received feedback that the current sentence makes it sound like we won't contribute to Community-based components (which isn't true).
```
/merge
```

Adjust Community Supported Component messaging

---

content/en/logs/explorer/search.md

- Add note about NLQ being powered by Llama per license
```
/merge
```

Add note about llama

---

content/en/network_monitoring/cloud_network_monitoring/setup.md

From a comment in the documentation channel, the name Kubernetes can be used for both Operator and Helm, this PR changes the Kubernetes tab name to Helm as it should be, and un-bolds some wording that doesn't need to be bolded.
Also updates the Helm chart to link to the correct section
To have …

[DOCS-10920] change tab name

---

content/en/reference_tables/_index.md

Add a note about site restrictions for Google Cloud
```
/merge
```

[DOCS-10862] Add site restriction note

---

content/en/containers/amazon_ecs/tags.md

Add a note about tags
```
/merge
```

[DOCS-10840] Add tags note

---

content/en/tracing/trace_collection/proxy_setup/nginx.md

Add missing instructions for Helm.
```
/merge
```

proxy(nginx): add extraEnvs in helm snippet

---

content/en/account_management/teams/_index.md

Adding a preview page for the Teams <> GitHub integration

---

content/en/infrastructure/containers/amazon_elastic_container_explorer.md

The ecs crawler has changed the frequency at which it runs. This requires us to update the docs to tell users how long tasks might stick around.
```
/merge
```

[Orch] Update docs around ecs task timeout

---

content/en/monitors/types/event.md

- Add a note: Event monitors do not alert on monitor events as this can create an endless loop.
- [DOCS-10778](https://datadoghq.atlassian.net/browse/DOCS-10778)
```
/merge
``` …

Add note about event monitors

---

layouts/shortcodes/pci-logs.en.md

- Align code with numbered list
- Remove brackets from example config
- [DOCS-10791](https://datadoghq.atlassian.net/browse/DOCS-10791)
```
/merge
```
[DOCS-10791]: …

Remove brackets from configuration

---

content/en/data_jobs/databricks.md
content/en/data_jobs/emr.md

In the config env var sections of all databricks tabs and for EMR, document the effect of `DD_LOGS_CONFIG_PROCESSING_RULES` with a link to the specific Datadog docs page that presents how to use it. …

[DJM-801] Document DD_LOGS_CONFIG_PROCESSING_RULES

---

content/en/opentelemetry/setup/agentless/_index.md

sending traces -> sending telemetry
```
/merge
```

Update 'Datadog OTLP Intake Endpoint' doc wording

---

content/en/actions/datastore/_index.md
content/en/actions/private_actions/_index.md
content/en/actions/private_actions/private_action_credentials.md
content/en/actions/private_actions/use_private_actions.md
content/en/actions/workflows/variables.md
content/en/llm_observability/cluster_map/_index.md
content/en/llm_observability/configuration/_index.md
content/en/llm_observability/guide/_index.md
content/en/llm_observability/guide/llm_observability_and_apm.md
content/en/llm_observability/guide/ragas_quickstart.md
content/en/llm_observability/setup/auto_instrumentation.md

See:
[DOCS-10870](https://datadoghq.atlassian.net/browse/DOCS-10870)
[DOCS-10871](https://datadoghq.atlassian.net/browse/DOCS-10871)
[DOCS-10872](https://datadoghq.atlassian.net/browse/DOCS-10871)
[DOCS-10873](https://datadoghq.atlassian.net/browse/DOCS-10873)
[DOCS-10874](https://datadoghq.atlassian.net/browse/DOCS-10874) …

(maint) Adds support banners to serveral pages

---

content/en/monitors/notify/variables.md

Update is_match behaviour with empty string

Update is_match behaviour with empty string

---

content/en/network_monitoring/network_path/setup.md

Adds Helm instructions to the Network Path setup docs for dynamic paths, and updates links.
```
/merge
```

[DOCS-8678] update Helm config for network path

---

.gitignore
.vscode/markdoc.code-snippets
.vscode/settings.json
content/en/real_user_monitoring/guide/proxy-mobile-rum-data.mdoc.md
markdoc.config.json

This adds snippets and other VS Code support for Cdocs (Markdoc).
Most of the changes are to support Markdoc's language server, which requires certain configurations to be in place. I also reformatted the existing `.mdoc.md` file according to how the language server prefers to format the file, just to avoid random annoying diffs later.
I'll be testing the snippets heavily throughout the pilot, so their accuracy isn't a huge deal, and they will likely continue to evolve. Feel free to skim those.
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab pipeline will not run, and you won't get a …

Set up VS Code support for Markdoc

---

content/en/agent/basic_agent_usage/windows.md

Fixing some parameters in the Windows Installation documentation to match what is in the UI. 
```
/merge
```

DOCS-10440 - Windows Agent installation

---

content/en/agent/remote_config/_index.md

@jgibbons-cp noticed that we had anchor links that didn't do anything. This PR updates those links so they do.
```
/merge
```

Fix outdated anchor link

---

content/en/serverless/azure_app_services/azure_app_services_linux.md

v1.12.0 of the Datadog Linux Wrapper script for Azure App Services was recently released. This PR updates the documentation to point to this latest version of the script.
https://github.com/DataDog/datadog-aas-linux/releases/tag/v1.12.0 …

Bump version of azure app services linux wrapper to 1.12.0

---

content/en/error_tracking/backend/exception_replay.md
content/en/tracing/error_tracking/exception_replay.md

Edits to the Exception Replay doc, including title fix and several content updates.
```
/merge
```

Exception Replay doc title and content fixes

---

content/en/getting_started/tagging/assigning_tags.md

Add info and a link about account-level tags being assigned to logs
```
/merge
```

[DOCS-10938] Add logs detail

---

content/en/security/application_security/threats/add-user-info.md

- There were nested tabs on this page that somehow worked prior to the tab style update.
- This PR converts these nested tabs to collapsible sections.
- Currently broken: https://docs.datadoghq.com/security/application_security/how-it-works/add-user-info?tab=java#adding-business-logic-information-login-success-login-failure-any-business-logic-to-traces
If your branch doesn't …

App Sec Add User Info Tab Fix

---

content/en/getting_started/tracing/_index.md

https://datadoghq.atlassian.net/browse/DOCS-10965
```
/merge
```

DOCS-10965

---

content/en/metrics/types.md

adding the flush time interval to the histogram example

---

content/en/profiler/automated_analysis.md

Add preview banner to Automated Analysis Docs

---

content/en/account_management/api-app-keys.md

https://datadoghq.atlassian.net/browse/DOCS-10516
App keys scopes must be manually assigned. Nothing comes by default.
```
/merge
```

Remove incorrect information about app key scopes

---

content/en/security/application_security/how-it-works/add-user-info.md

- Editing the correct file.
- https://github.com/DataDog/documentation/pull/29440 edited a duplicate, incorrect file?
```
/merge
```

Redo Redo App Sec Tab Fix

---

content/en/security/application_security/setup/compatibility/gcp-service-extensions.md
content/en/security/application_security/setup/standalone/gcp-service-extensions.md
content/en/security/application_security/setup/threat_detection/gcp-service-extensions.md
content/en/security/application_security/threats/setup/compatibility/gcp-service-extensions.md
content/en/security/application_security/threats/setup/standalone/gcp-service-extensions.md
content/en/security/application_security/threats/setup/threat_detection/gcp-service-extensions.md

From a recent PR (#28511), the GCP SE page has been updated. But concurrently a new PR (#28653) was merged that duplicated the content of `/threat_detection/` under `/standalone/`. The initial PR missed the update to the duplicated content. The full content of `/threats/setup/` was also duplicated into `/setup/` (thus duplicated the page 4 times).
Basically this PR:
- Copy the update GCP Page (+ its compatibility page) over all the relevant folders
- Update all mention of `AAP` to `App and API Protection`
- Update all mention of `Api & API Protection` to `App and API Protection`
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your …

Synchronise outdated GCP SE page for AAP

---

content/en/logs/log_configuration/flex_logs.md

Add note on how to enable flex compute

---

content/en/security/cloud_siem/detection_rules/_index.md

Add the new detection rule type, Content Anomaly.
```
/merge
```

[DOCS-10959] Add Content Anomaly to Cloud SIEM Detection Rules

---

content/en/database_monitoring/setup_sql_server/troubleshooting.md

Removed "# example uses windows authentication" comment from an example that does not use windows authentication.
Windows Auth is enabled with `Trusted_Connection=yes;`-- this example does not have that and therefore this comment is unnecessary/confusing
To have your PR automatically merged …

Remove inaccurate comment from yaml example

---

content/en/network_monitoring/cloud_network_monitoring/network_analytics.md

This PR adds a section to help explain why traffic flows may differ from client - server, and server - client.
Additionally removes out-dated time picker screenshot/section that is not needed. …

[DOCS-10829] Update network analytics page

---

data/libraries.yaml

Update libraries.yaml to fix an old entry

remove outdated dd-trace-go entry, update description

---

content/en/security/cloud_security_management/setup/agentless_scanning/enable.md

Update Agentless scanning permissions.

Update Agentless permissions

---

content/en/opentelemetry/setup/agentless/metrics.md

Add more clarification to dd-otlp-source for metric intake endpoint

---

content/en/real_user_monitoring/session_replay/mobile/privacy_options.md

Adds a section to the Fine Grained Masking with the steps to set up privacy overrides on Session Replay for React Native.
Wait for version 2.8.0 of the React Native SDK before merging.
``` …
```

Add documentation for React Native Privacy Overrides

---

content/en/real_user_monitoring/correlate_with_other_telemetry/apm/_index.md

Corrected the URLs used - from `/how-are-rum-resources-linked-to-traces` to `/how-rum-resources-are-linked-to-traces`
```
/merge
```

Corrected URLs

---

config/_default/menus/main.en.yaml
content/en/mobile/widgets.md

DOCS-11010, adds a few existing docs pages into the nav.
```
/merge
```

Add pages to nav

---

config/_default/menus/main.en.yaml
content/en/observability_pipelines/sources/http_server.md
content/en/observability_pipelines/sources/lambda_forwarder.md
layouts/shortcodes/observability_pipelines/lambda_forwarder/deploy_forwarder.md
layouts/shortcodes/observability_pipelines/lambda_forwarder/pipeline_setup.md

Add docs for Lambda Forwarder. Move instructions from HTTP Server source into shortcodes.
**For docs reviewer**:
The two chunks of content getting deleted are just being moved to two shortcodes so don't necessarily need an editorial review. 
To have your PR automatically merged after it receives …

Add lambda nav item

---

content/en/tracing/trace_collection/compatibility/java.md

Vertx >=5 is not supported. Updating the compatibility doc
```
/merge
```

limit java vertx compatibility to < 5.x

---

content/en/agent/logs/_index.md

Added
logs_config:
use_sourcehost_tag: true
```
/merge
```

Tells users how to collect tcp/udp sender IP address

---

.github/workflows/codeowner_review_status.yml

- Set the update pr and status to always so we get a pass/fail status for the required job
```
/merge
```

Always run update job

---

content/en/security/threat_intelligence.md

- [As requested by Michael Bentley](https://dd.slack.com/archives/C07QHELL0D6/p1747410413829859?thread_ts=1747144528.858599&cid=C07QHELL0D6) we are changing the entity type to `Domain` 
``` …
```

Update Threat Intel docs

---

layouts/shortcodes/observability_pipelines/install_worker/kubernetes.md
static/resources/yaml/observability_pipelines/v2/setup/values.yaml

[DOCS-10925] Add link to full values.yaml file

---

.github/CODEOWNERS
repository.datadog.yml

Now that we have a single source of truth for the approval job, we should ignore the github reporting of the trigger jobs just for sanity and to eliminate any question on if mergequeue is blocking due to one of these jobs being in a failure state
Newly added ignored jobs:
- Documentation Team Approval Check / check-documentation-team-approval (pull_request_review)
- Documentation Team Approval Check / check-documentation-team-approval (pull_request)
Also updates the CODEOWNERS file to have platform as the required review `repository.datadog.yml`
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, …

Ignore the non required approval jobs for mq

---

content/en/product_analytics/_index.md
content/en/product_analytics/analytics_explorer/_index.md
content/en/product_analytics/heatmaps.md
content/en/product_analytics/journeys/_index.md
content/en/product_analytics/journeys/funnel_analysis.md
content/en/product_analytics/journeys/pathways.md
content/en/product_analytics/troubleshooting.md
content/en/product_analytics/user_retention.md

This is a very quick PR to remove the Product Analytics Preview callout from the PANA docs
```
/merge
```

Remove the Product Analytics Preview callout from the PANA docs

---

content/en/observability_pipelines/sources/kafka.md
layouts/shortcodes/observability_pipelines/source_settings/kafka.md

[DOCS-11013] Add librdkafka section

---

content/en/cloud_cost_management/setup/saas_costs.md

An update to the admin key functionality has led to the need to update the documentation.

[SAASINT-4057][openai][ccm] Documentation changes for admin key support

---

content/en/network_monitoring/network_path/setup.md

This PR adds setup directions for using Network Path via Autodiscovery. Autodiscovery is a feature the Agent has which allows the agent to dynamically pick up integrations to run.
``` …
```

[netpath] Add docs on how to setup autodiscovery

---

content/en/internal_developer_portal/self_service_actions/_index.md

Add alias for self service actions

---

snippets/markdown.json

Sorry, I wouldn't have slept this weekend if I didn't fix this first
```
/merge
```

Fix typo in snippet

---

content/en/internal_developer_portal/software_catalog/set_up/discover_entities.md

Fix links on Discover Entities page

---

content/en/data_jobs/databricks.md
content/en/data_jobs/dataproc.md
content/en/data_jobs/emr.md

Update our DJM docs so that the version pinning example is the current installation script version
```
/merge
```

update to current version 0.13.3

---

content/en/security/application_security/_index.md

Update the Disable AAP link with the new post-renaming anchor for ease of navigation.
```
/merge
```

Update Disable AAP link to correct anchor

---

content/en/ddsql_reference/ddsql_default.md

DDSQL Editor is going GA with the new aligned customer-facing SQL dialect, so we can update the DDSQL Reference documentation to point to it as well.
Updates this page to reference DDSQL Editor as well as Logs Workspaces: https://docs.datadoghq.com/ddsql_reference/ddsql_default/

[ddsql][DDSQL-1276] Update documentation links and references for DDSQL Editor

---

content/en/opentelemetry/setup/agentless/metrics.md

Fix code examples in OTLP metrics endpoint. Keys in JSON strings must be quoted to be parsed correctly.
```
/merge
```

Fix code examples in OTLP metrics endpoint

---

content/en/llm_observability/setup/auto_instrumentation.md

Adds LiteLLM to our list of auto-instrumented libraries for LLM Observability.
```
/merge
```

[MLOB-2777] add litellm documentation

---

content/en/observability_pipelines/troubleshooting.md

Add OP troubleshooting item.
```
/merge
```

[DOCS-10930] Add port forwarding troubleshooting

---

content/en/service_management/status_pages.md

- Requested by the PM to update the preview banner from Limited Availability to Preview
```
/merge
```

Product is in Preview

---

content/en/agent/supported_platforms.md

Clarifies on the Agent platform support page that the Unix Agent is a separate project and not Agent 6/7. It re-uses the note that is on https://docs.datadoghq.com/agent/basic_agent_usage/aix/ …

Clarify Unix Agent platform support

---

content/en/bits_ai/_index.md

Remove preview form

---

content/en/security/cloud_siem/guide/azure-config-guide-for-cloud-siem.md

The linked template doesn't exist any more. The latest template could be confirmed in another public doc. 
https://docs.datadoghq.com/logs/guide/azure-logging-guide/?tab=eventhub#setup
Motivation:https://dd.slack.com/archives/C02FPP4JQHX/p1749060381482899
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have …

Update Azure template

---

content/en/tracing/trace_collection/proxy_setup/apigateway.md

Update code sample for AWS CDK

---

content/en/tracing/trace_collection/proxy_setup/istio.md

Temporarily remove Istio Sampling section

---

content/en/account_management/audit_trail/events.md

approved by @vignesh
View Agent Audit Trail Events in Fleet Automation …

v2- View Agent Audit Trail Events in Fleet Automation

---

content/en/tracing/guide/aws_payload_tagging.md

1. This information is available under the "Language-specific Configuration"
2. It also conflicts with the documentation under language-specific section, which should be the source of truth.
------------------------------------------------------------------------------------------------------------------------
[6/5/2025] Merge queue …

Remove duplicate info in aws_payload_tagging.md

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/compatibility.md

Adding details about latest supported version of .NET for the SSI feature. …

Adds .NET 9 to SSI Compatibility

---

config/_default/menus/main.en.yaml
content/en/security/application_security/overview/_index.md

Avoid confusion with the "Overview" link being actually about the "Attack Summary" page documentation, and not a product overview documentation as one would expect from such a title.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation …

AAP: rename Overview into Attack Summary 

---

content/en/observability_pipelines/processors/custom_processor.md

Add info about requesting access

---

content/en/data_jobs/databricks.md

add preview callout for Databricks Serverless Job Monitoring

---

content/en/ddsql_editor/_index.md
content/en/ddsql_reference/ddsql_default.md
content/en/ddsql_reference/ddsql_preview.md

- Last updates before DASH
- Requested by PM …

Add updates for ddsql docs

---

content/en/internal_developer_portal/overview_pages.md

dev homepage updates

---

content/en/dora_metrics/setup/deployments.md

Adds link to the Preview form for GitLab Integration to the DORA Metrics docs. …

Add GitLab Preview Form

---

content/en/containers/monitoring/autoscaling.md

adds formulas for default idle cost and savings estimates. this PR also reformats the section, but the only net addition is the formulas. …

add cost formulas to autoscaling

---

content/en/network_monitoring/network_path/_index.md
content/en/network_monitoring/network_path/list_view.md
content/en/network_monitoring/network_path/path_view.md
content/en/network_monitoring/network_path/setup.md

Network Paths (individual paths only) going GA
Do **NOT** Merge. Want to get approval on this so I can merge it on June 9th. 🙇 
```
/merge
```

[DOCS-10972] update callout for GA

---

content/en/agent/remote_config/_index.md

(Agent) Fix typo

---

content/en/dynamic_instrumentation/_index.md

Remove Beta labels from DI docs

---

content/en/account_management/teams/manage.md

https://datadoghq.atlassian.net/browse/DOCS-10596
Github Connection is an available configuration option for Teams. Bringing the Teams doc up to date with reality. …

Add Github connection to team settings

---

content/en/real_user_monitoring/browser/optimizing_performance/recommendations.md

URL should be `~/recommendations` instead of `~/rum_recommendations` …

Update RUM Recommendations URL

---

content/en/product_analytics/charts/pathways.md

adding an alias to Pathways

---

go.mod
go.sum

need to update websites-modules version on docs to ensure the status page is available.
motivation: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-6649
preview: https://docs-staging.datadoghq.com/stefon.simmons/investigation-status-page/agent/?tab=Linux
- check that status page icon exists in left nav
If your branch doesn't follow this format, rename it or create a new branch …

update websites-modules - fix status page icon - [WEB-6649]

---

layouts/shortcodes/observability_pipelines/destination_settings/datadog_archives_amazon_s3.en.md

- Adds note about leading slash
- Adds note about assume role …

[DOCS-11171] Update Amazon S3 destination

---

content/en/security/cloud_security_management/misconfigurations/signals_explorer.md

we wont get to this until later in the year, so changing "early 2025" to "second half of 2025" …

Update signal deprecation date

---

content/en/integrations/guide/storage-monitoring-setup.md

This PR adds a further reading section with two blog links …

[DOCS-11112] Add blog links

---

content/en/integrations/guide/azure-programmatic-management.md
content/en/logs/guide/azure-logging-guide.md

This PR adds a new blog link to a couple of Azure integration guides …

[DOCS-11123] Add blog links

---

content/en/service_management/service_level_objectives/metric.md

Warning threshold is lower than target percentage …

Update metric.md - Warning threshold is lower than target percentage

---

content/en/llm_observability/setup/sdk/python.md

Documentation bug fix and clarity improvement

---

content/en/security/code_security/dev_tool_int/github_pull_requests/_index.md

Reverts DataDog/documentation#29911

Revert "[K9VULN-5717] Add step for SCA comment setup "

---

content/en/llm_observability/setup/sdk/java.md

[MLOB-2882] add link for JAR download

---

content/en/agent/fleet_automation/_index.md

[DASH][GA] Agent Upgrade instructions causing confusion

---

assets/scripts/components/expression-language-parser.js
assets/scripts/tests/expression-language-parser.test.js
content/en/dynamic_instrumentation/expression-language.md
layouts/shortcodes/expression-language-simulator.html

Reorganize expression language examples
- provide examples for both sequential collections and maps
- use variable for string expression examples, like with collections
- expose both len and count, as both are supported; use len consistently in examples
- use same variables for the demo and examples
- remove examples with any(filter(...)) and all(filter(...)) that rely on collections being truthy, it's too complicated; just use any and all which take precondition as second parameter
- remove "+ Capture Variables" unclickable button
Merge queue is enabled in this repo. Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass in CI, the GitLab …

docs(debugger): reorganize expression language examples

---

content/en/tracing/trace_collection/custom_instrumentation/java/dd-api.md

Addressing a very old JIRA ticket :) https://datadoghq.atlassian.net/browse/DOCS-1768 
Updating the banner at the top of the page to clarify that the opentracing-api should be declared as a dependency. 
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by …

Clarify opentracing-api dependency

---

content/en/watchdog/alerts/_index.md

Fix SQLServer link

---

content/en/serverless/google_cloud_run/_index.md
content/en/serverless/google_cloud_run/functions.md
content/en/serverless/google_cloud_run/functions_gen1.md

Adds documentation for GCP Go Cloud Run Functions Gen 1 for Go
Includes a Go Example 
```
/merge
```

Create doc for GCP cloud run function gen 1 SCL Golang

---

content/en/internal_developer_portal/software_catalog/entity_model/_index.md

Update schema store link

---

content/en/developers/ide_plugins/visual_studio/_index.md

IDE-4611 update visual studio docs

---

content/en/dora_metrics/setup/deployments.md
content/en/dora_metrics/setup/failures.md

SDCD-1144: adding information about custom_tags in DORA setup pages

---

content/en/agent/faq/proxy_example_haproxy.md

Following https://github.com/DataDog/documentation/pull/29874, this PR adds the required agent instructions to be able to leverage the install.datadoghq.com proxy
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of …

chore(fleet): Add required datadog.yaml config for installer HAProxy config

---

content/en/service_management/on-call/_index.md

Removes OpsGenie from migration docs as this hasn't been released yet. …

Remove non-existent capability

---

content/en/profiler/profiler_troubleshooting/java.md

Addressing temp folder issues in the troubleshooting section as it makes a lot of sense, given how frequently they come up in support. …

Update java.md -Update troubleshooting steps for Java profiler

---

content/en/agent/logs/auto_multiline_detection.md

JSON aggregation docs initial release

---

content/en/actions/private_actions/private_action_credentials.md
content/es/actions/private_actions/private_action_credentials.md

We want to change the location used by runner configuration files from /etc/dd-action-runner to /etc/dd-action-runner/config so we're updating all places where we specify the value. This PR change the configuration for the documentation.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to …

[ACTP-745] update PAR configuration directory

---

content/en/datadog_cloudcraft/_index.md
content/en/logs/log_configuration/forwarding_custom_destinations.md
content/en/metrics/guide/custom_metrics_governance.md
content/en/observability_pipelines/guide/get_started_with_the_custom_processor.md
content/en/tracing/trace_explorer/tag_analysis.md

Add blog links to docs

---

content/en/security/application_security/policies/_index.md

DOCS-11273
added a redirect from /security/application_security/threats/protection > /security/application_security/policies. It was causing issues with a link from the UI.

adding missing redirect to fix UI issue

---

content/en/llm_observability/evaluations/ootb_evaluations.md

- Mention `BYOK` (abbreviated) to help with the branding this dashboard ("BYOK Token usage")
- Add link to Dashboard from the related metrics section

[MLOB-2995] Update LLMO Evaluations doc with BYOK token dashboard

---

content/en/bits_ai/bits_ai_dev_agent.md
content/en/bits_ai/bits_ai_sre/_index.md
content/en/bits_ai/mcp_server.md
content/en/containers/monitoring/autoscaling.md
content/en/data_jobs/_index.md
content/en/data_streams/_index.md
content/en/llm_observability/_index.md
content/en/llm_observability/agent_monitoring.md
content/en/logs/log_configuration/flex_logs.md
content/en/product_analytics/_index.md
content/en/security/cloud_siem/_index.md
content/en/service_management/incident_management/_index.md
content/en/service_management/on-call/_index.md
content/en/tracing/recommendations/_index.md

second batch of blog links

---

content/en/service_management/on-call/guides/configure-mobile-device-for-on-call.md

https://datadoghq.atlassian.net/browse/DOCS-11230
Corrects an invalid setting location.  …

Fix incorrect android setting location

---

content/en/containers/amazon_ecs/_index.md

Update FIPS proxy version to 1.1.13
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, …

[AGENTRUN-497] Update FIPS proxy version to 1.1.13

---

content/en/network_monitoring/network_path/setup.md

This PR updates the docs for Windows Client support on windows.
https://datadoghq.atlassian.net/browse/WINA-1510
Waiting on `7.67` of the agent to be released. 
```
/merge
```

Update NetPath Docs for Windows Clients

---

layouts/shortcodes/dbm-sqlserver-agent-config-examples.en.md

We're recommending to users that they install the SQLServer agent + integrations on each individual replica server instead of the previous approach (external instance connected to the listener endpoint). 
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed …

Update AlwaysOn documentation to move away from the listener endpoint

---

content/en/account_management/api-app-keys.md
content/en/account_management/org_settings/service_accounts.md

API and Application Keys documentation (content/en/account_management/api-app-keys.md):
- Added conditional formatting using {{< site-region region="ap2,gov" >}} to show one-time read warning only for AP2 and GovCloud users
- Removed redundant note from the Notes section
- Service Accounts documentation (content/en/account_management/org_settings/service_accounts.md):
- Updated existing warning to use conditional formatting with {{< site-region region="ap2,gov" >}}
- Warning now only appears for users who have selected AP2 or GovCloud regions
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you …

Add region-specific warnings for one-time read application keys in AP2 and GovCloud

---

content/en/reference_tables/_index.md

DOCS-10813, add clarification requested by a customer. …

Clarify when change events are generated

---

content/en/continuous_delivery/deployments/argocd.md
content/en/continuous_delivery/features/rollbacks_detection.md

Adds docs on the new ci/cd correlation mechanism for CD Visibility …

Add documentation for ci cd correlation

---

content/en/agent/fleet_automation/remote_management.md

The Agent MSI allows users to upgrade without re-providing the password option. But the option must be provided to 7.66 or later to enable remote updates.
https://datadoghq.atlassian.net/browse/WINA-1587

Add Windows Agent User prerequisite

---

content/en/security/cloud_siem/open_cybersecurity_schema_framework.md

Fix links and update title per PMM and PM request. …

[DOCS-11312] Fix links and update title

---

content/en/synthetics/guide/custom-javascript-assertion.md

DOCS-11293. Adds a note stating that JS assertions aren't supported in Windows private locations. …

DOCS-11293: Add note to Custom JavaScript Assertions doc

---

content/en/serverless/azure_container_apps/_index.md

* Adds `DD_SITE` variable to Azure Container Apps documentation …

Add datadog site to az-ca doc

---

content/en/agent/fleet_automation/_index.md

Improving clarity and reflecting suggestions from management cc: @vignesh …

Make Audit Events instructions clearer in Fleet Automation docs

---

content/en/database_monitoring/guide/sql_extended_events.md

Fix a visual bug in docs.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or you …

Fix sql block not being terminated

---

layouts/shortcodes/latest-lambda-layer-version.html

update python layer version

---

content/en/integrations/guide/cluster-monitoring-vmware-tanzu.md

Improve the installation steps of PCF (aka VMWare Tanzu Application Services) where some users might miss selecting all the desired tiles, not just the datadog tile in order to install Datadog in all their hosts.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been …

Improve vmware tanzu application service installation steps

---

content/en/security/application_security/troubleshooting.md

Updates the doc to include another flag that is stored with in the PHP ini file.
When the PHP tracer is installed with the --appsec-enabled flag, it also adds the datadog.appsec.enabled = On flag to the php.ini files found on the system. In a recent case, we had some difficulty disabling the product: https://datadog.zendesk.com/agent/tickets/2110494
If your branch doesn't follow this format, …

Update AAP disable for PHP

---

content/en/monitors/guide/_index.md

- These guides were dropped in the last [index reorg](https://datadoghq.atlassian.net/browse/DOCS-10063), this PR adds them back to the index.
- No new content to review

Re-add dropped guide references

---

content/en/logs/guide/flex_compute.md

Users can now click to interact with the graphs to see audit trail history of logs, or the associated dashboard
Add information about new capabilities available for the compute usage graphs on the Flex Logs Controls page - users can now click to interact with top dashboards experiencing slowdowns graph and top users experiencing slowdowns graph.  …

kelly-kong/Add information about new features to docs

---

content/en/metrics/guide/custom_metrics_governance.md

Please merge after approval - thanks :)

Add Navattic walk-through of Metrics Governance tools in Custom Metrics Best Practices

---

layouts/_default/baseof.html
layouts/partials/integrations-carousel/integrations-carousel-modal.html
layouts/partials/integrations-carousel/integrations-carousel.html

fixes the integrations carousel modal display. `media` key from [data source](https://github.com/DataDog/websites-sources/blob/main/content/en/integrations/crest-data-systems-pfsense.md?plain=1) no longer has a `tile` parent.
motivation: https://datadoghq.atlassian.net/jira/software/projects/DOCSENG/boards/10954?selectedIssue=DOCSENG-25
preview: https://docs-staging.datadoghq.com/stefon.simmons/fix-integrations-carousel-modal/integrations/crest-data-systems-pfsense/
- clicking on an integration image in the carousel, should open a modal. 
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't …

fix integrations carousel modal - [DOCSENG-25]

---

content/en/metrics/guide/custom_metrics_governance.md

Fix pronoun

---

package.json
yarn.lock

Bump geo-locate version to support AP2 signup. This logic won't have any effect until the geo-locate marketing lambda is updated.
Related to this corp-node-package update: https://github.com/DataDog/corp-node-packages/pull/127
https://datadoghq.atlassian.net/browse/WEB-6668
http://docs-staging.datadoghq.com/ccole/signup-add-ap2
Signup iframe should load as expected
If your branch doesn't follow this format, rename it …

Bump geo-locate version

---

content/en/synthetics/platform/private_locations/dimensioning.md

Explained 150mCores as a unit for partial CPU cores, commonly used in Kubernetes and container environments. Useful for anyone unfamiliar with this notation, including myself. …

Clarified meaning of 150mCores

---

content/en/account_management/audit_trail/events.md

Add Test Optimization Default settings Audit event.

Add default settings audit event

---

config/_default/menus/main.en.yaml
content/en/containers/monitoring/autoscaling.md

Improve Autoscaling documentation and correct some settings that are now automatically handled.

Correct some errors in Autoscaling doc

---

assets/scripts/config/regions.config.js

(fix) Fix ap2 parameter

---

content/en/cloud_cost_management/_index.md
content/en/cloud_cost_management/custom_allocation_rules.md
content/en/cloud_cost_management/recommendations/_index.md
content/en/notebooks/_index.md

Adds "Further Reading" links to related blog post on FinOps that mentions/links to the docs. …

Add links to recent FinOps blog

---

layouts/shortcodes/observability_pipelines/destination_settings/datadog.en.md

[DOCS-11317] Update compression for OP Datadog destination

---

.github/chainguard/websites-modules.generate-go-mod.sts.yaml

- adds trust policy for websites modules interactions on docs …

Add Websites Modules trust policy

---

content/en/data_jobs/kubernetes.md

Stop asking customers to add a Datadog app key on top of the API key as only the API key is necessary for DJM to work.
- Ready for merge after @warrierr approves
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of …

[DJM]App_key is unnecessary in DJM setup

---

content/en/real_user_monitoring/session_replay/mobile/privacy_options.mdoc.md

Update Mobile Privacy Options page with SwiftUI API
Jira (internal): [RUM-10478](https://datadoghq.atlassian.net/browse/RUM-10478)
[RUM-10478]: https://datadoghq.atlassian.net/browse/RUM-10478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Mobile Privacy Options page with SwiftUI API

---

content/en/serverless/aws_lambda/installation/go.md

remove v2 rec

---

content/en/security/cloud_siem/historical_jobs.md

[DOCS-11209] Add banner to historical jobs doc

---

.github/chainguard/websites-modules.generate-go-mod.sts.yaml

- Updates keys and values for the trust policy in WM …

Policy keys and values

---

content/en/actions/private_actions/use_private_actions.md

Document network access requirements for the private action runners

[ACTP-623] PAR network access requirements

---

content/en/tracing/trace_collection/compatibility/java.md

See https://github.com/DataDog/dd-trace-java/pull/8848 …

Kotlin Coroutines instrumentation is now enabled by default

---

.gitignore
package.json
translate.yaml
yarn.lock

DOCSENG-3
- Bump the Cdocs version to one that supports automatically creating *.ast.json files (see [the Cdocs integration changelog](https://github.com/DataDog/corp-node-packages/blob/master/packages/cdocs-hugo-integration/CHANGELOG.md) for the list of differences between this version and the former version)
- Ignore *.ast.json files, which are for translation purposes and do not need to be in version control
- Add *.ast.json files to the list of files processed by Transifex
✅ This PR has passed the [relevant Cdocs QA](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/4972677218/Customizable+Docs+QA+checklist).
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, …

Prep for JSON translation of Markdoc

---

content/en/llm_observability/evaluations/ootb_evaluations.md

Document the fact that OOTB eval users need a structured output compatible model for the Azure LLM provider.

[MLOB-3136] Mention structured output support for azure BYOK eval

---

content/en/dashboards/widgets/_index.md

- Add a reference link to the Datadog Clipboard from the Dashboard widget page.
- Update the keyboard shortcut commands

Add reference for datadog clipboard

---

content/en/network_monitoring/devices/snmp_traps.md

Binding to ports below 1024 (like SNMP Trap port 162) requires elevated permissions. To enable this, the agent binary needs an additional capability set.
The existing instructions point to an outdated binary path:
`/opt/datadog-agent/bin/agent/agent`
Current path is:
`/opt/datadog-packages/datadog-agent/stable/bin/agent/agent`
This update fixes the path reference in the documentation. Verified the current path with  `v7.67.0`
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such as …

Updated Datadog Agent binary path

---

content/en/cloud_cost_management/recommendations/_index.md

Add GCP and K8s recs docs
https://docs-staging.datadoghq.com/jack.finkel/07-02-add_k8s_and_gcp_recs_to_ccm_recs_docs/cloud_cost_management/recommendations/ …

Add k8s and GCP recs to ccm recs docs

---

content/en/llm_observability/sdk/_index.md

fixing borked site code

---

config/_default/menus/main.en.yaml
content/en/real_user_monitoring/ownership_of_views.md

- Unindex this product from search as it's not GA …

Remove from search

---

config/_default/config.yaml
go.mod
go.sum
layouts/iac_security/list.html
local/bin/py/build/configurations/pull_config.yaml
local/bin/py/build/configurations/pull_config_preview.yaml

remove `kics` from pull configs
using websites-sources to get the `kics` repo content
update the template to look for `group-id` instead of `group_id` frontmatter.
preview: https://docs-staging.datadoghq.com/stefon.simmons/kics-docs-ws/security/code_security/iac_security/iac_rules/
- the rules should show now.
[6/5/2025] Merge queue …

Stefon.simmons/kics docs ws

---

content/en/security/cloud_security_management/setup/agent/kubernetes.md

The instructions regarding daemonset based deployments were suggesting to modify the `system-probe` container when both `agent` and `security-agent` had to be modified. Besides, the instructions are very incomplete -missing securityContext, pod annotations and missing bind mounts) and hard to keep in sync with the Helm charts. …

Remove documentation regarding CSM and daemonsets

---

content/en/security/cloud_security_management/misconfigurations/frameworks_and_benchmarks/custom_frameworks.md

Update custom frameworks docs to reflect support for infra config rules

---

content/en/containers/docker/integrations.md

DOCS-11041: file-mounting instructions for docker AD

---

content/en/serverless/azure_app_services/azure_app_services_linux.md

chore: fix datadog-ci parameter typo

---

content/en/ddsql_reference/_index.md

- Add product availability for Notebooks in DDSQL Reference
- [DOCS-11416](https://datadoghq.atlassian.net/browse/DOCS-11416)
[DOCS-11416]: https://datadoghq.atlassian.net/browse/DOCS-11416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Notebooks to DDSQL Reference

---

translate.yaml

these pages are mostly code samples and data heavy.  no need for translations so let's reduce the noise by ignoring in the pipeline. …

ignore IAC rules for transifex

---

content/en/security/code_security/static_analysis/_index.md

Update for typo

---

.htmltest.yml

(maint) Remove config from htmltest

---

content/en/observability_pipelines/processors/custom_processor.md

Adds preview link.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or you need help, …

[DOCS-11434] Add preview link to Custom Processor

---

content/en/agent/troubleshooting/send_a_flare.md

approved by @shanelhuang 
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or you …

Update flare command

---

config/_default/menus/main.en.yaml
content/en/observability_pipelines/sources/filebeat.md
content/en/observability_pipelines/sources/logstash.md

Moves filebeat content to a separate doc. No net new docs content.
Adds nav item. …

[DOCS-11307] Move Filebeat content in Logstash to a separate doc

---

data/api/v2/full_spec.yaml
data/api/v2/translate_actions.json

This PR adds a disclaimer regarding a library version requisite for the event creation V2 API.

Update CreateEvent to include new disclaimer

---

.htmltest.yml

Lets enable concurrency with htmltest again but with some conservative settings …

htmltest concurrency

---

content/en/monitors/types/database_monitoring.md

The issue is that we incorrectly state that the Database Monitoring Monitor can group by five facets when we can actually group by four.
https://datadog.zendesk.com/agent/tickets/2161618
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation …

Corrected the amount of facets we can group by

---

content/en/database_monitoring/setup_postgres/aurora.md
content/en/database_monitoring/setup_postgres/rds/_index.md

We support version 17 of Postgres for both RDS and Aurora but it wasn't made known in the respective docs. …

Update Postgres Supported Versions

---

content/en/logs/log_collection/_index.md

Fix typo for Supported Endpoints. Site should be AP2 for AP2 endpoints. …

Update _index.md typo from AP1 to AP2

---

content/en/real_user_monitoring/rum_without_limits/_index.md

Received user feedback via docs survey that this sentence showed up twice in the docs, but it wasn't clear what it meant or who or what is making the sampling decisions. This PR removes the duplicate sentence and clarifies what it is and does.
> Enable traceContextInjection: sampled to defer sampling decisions to backend tracers for sessions where the decision is not to keep the trace.
If your branch doesn't follow …

[DOCS-11371] Clarify sampling decisions in RWOL

---

content/en/integrations/_index.md

This is a temporary fix to the build. There is a bug in websites-sources which is causing the deprecated pingdom v1 integration to be added back to the docs constantly. That doc has a broken link. I'd prefer to link to the v3 integration, but changes would be overwritten by the sources pipeline. I'll come back and fix this once the other bug is sorted out. …

Redirect pingdom

---

content/en/tests/setup/java.md

- Adds a clarification about the build tools necessary for the `weaver` test framework to be supported by Test Optimization …

Specify build tool for Weaver support in Java test setup

---

layouts/integrations/single.html

Support the banner on integration guide pages …

banner on integration guide pages

---

content/en/metrics/custom_metrics/historical_metrics.md

Updated HMI Billing Calculation Example

---

content/en/opentelemetry/setup/ddot_collector/custom_components.md

Fixes DDOT Dockerfile link
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or you …

Fix DDOT Dockerfile link

---

customization_config/en/traits/general.yaml

A Cdocs preview participant noticed the reference to an `env` trait, which doesn't exist. The `env` trait had been updated to `platform` to avoid confusion with Hugo's `env` variable, and this reference got missed.
As long as you don't see build errors, this should be good to go. The internal notes text is not used for anything programmatic, it's just there for writer guidance.
If your branch doesn't follow this …

Update reference to deprecated trait

---

content/en/account_management/rbac/_index.md
content/en/administrators_guide/_index.md
content/en/administrators_guide/build.md
content/en/administrators_guide/getting_started.md
content/en/administrators_guide/plan.md

A few small updates to the Datadog Admin guide and fixing a broken link. …

updates to Administrator's guide

---

.github/CODEOWNERS

update service.datadog.yaml codeowners entry

---

content/en/security/guide/aws_fargate_config_guide.md

Update ECS Fargate VM detection via agentless

---

layouts/shortcodes/observability_pipelines/configure_log_archive/google_cloud_storage/instructions.en.md

Small edit to OP GCS destination doc

---

content/en/llm_observability/sdk/auto_instrumentation.md

Bumps the `ddtrace` version for LangGraph auto-instrumentation in our LLMObs docs …

[MLOB-3313] bump documented `ddtrace` version for LangGraph auto-instrumentation

---

translate.yaml

Adds .mdoc.md files to Transifex's ignore list, because we'll be translating the corresponding .ast.json files instead. …

Ignore .mdoc.md for Transifex

---

config/_default/menus/main.en.yaml
content/en/security/application_security/security_signals/attacker-explorer.md
content/en/security/application_security/terms.md

The Attacker Explorer was renamed to Attackers Explorer. Updating the docs.

Attacker Explorer renamed to Attackers Explorer

---

layouts/actioncatalog/list.html

updates action catalog links
motivation: https://datadoghq.atlassian.net/jira/software/projects/DOCSENG/boards/10954?selectedIssue=DOCSENG-41
preview: https://docs-staging.datadoghq.com/stefon.simmons/docseng-41/actions/actions_catalog
- should link directly to action in the app. …

update action catalog links - [DOCSENG-41]

---

content/en/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function.md

Update subscription filters note

---

content/en/continuous_delivery/deployments/argocd.md

We were missing this small part in the docs. …

Add images caveheat to docs

---

content/en/security/cloud_security_management/_index.md
content/en/security/cloud_security_management/misconfigurations/_index.md

Follow up to #30429. I'd missed updating some image filenames, so this ensures that everything is up to date 🙂  …

Fix a couple of missed image filenames

---

content/en/security/code_security/_index.md

Added an enrollment form call out for Supply Chain Security

Supply Chain Security enrollment form

---

content/en/security/notifications/rules.md

[DOCS-11481] Add test notification info

---

Makefile.config.example

Updates the template to use ddtool.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, …

(maint) Update Makefile.config template

---

content/en/serverless/aws_lambda/remote_instrumentation.md

… instrumentation
- [x ] Ready for merge …

Add improvements to Remote Instrumentation docs

---

content/en/data_jobs/airflow.md

Data Jobs Monitoring on Google Cloud compser guidelines as new tab of the DJM for Airflow page. …

[DJM-357] Add composer tab in DJM Airflow page

---

content/en/deployment_gates/_index.md

Fix broken deployment gate link

---

content/en/cloud_cost_management/setup/aws.md

Adds a note to a few places in the CCM AWS setup docs to be more clear about how long it could take for the data to populate before users see it in the UI after configuration. …

Add clarity to CCM AWS

---

layouts/shortcodes/hipaa-customers.en.md

Adds note about BAA & cross org.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or …

BAA users cannot use Cross-Organization Visibility

---

content/en/cloud_cost_management/recommendations/_index.md

Add ECS Task Recommenation to Docs

---

content/en/real_user_monitoring/mobile_and_tv_monitoring/android/advanced_configuration.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/android/data_collected.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/advanced_configuration.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/ios/data_collected.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/advanced_configuration.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/roku/advanced_configuration.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/roku/data_collected.md
content/en/standard-attributes/_index.md

-(Per reader feedback) Adds supported platforms for the standard attribute, `usr.name`
- Updates all headers in mobile data collected and advanced config pages for consistency …

[DOCS-8952] Add supported platforms for usr.name and update headers

---

content/en/internal_developer_portal/_index.md

team hierarchy preview

---

content/en/integrations/guide/aws-manual-setup.md

Add a note about setting the page to the correct site …

[DOCS-11513] Add site note

---

content/en/internal_developer_portal/software_catalog/entity_model/_index.md

https://datadoghq.atlassian.net/browse/DOCS-11540 …

add codeLocations search term to entity model index

---

content/en/database_monitoring/connect_dbm_and_apm.md

This PR adds warnings to enabling prepared statement tracing when using RDS proxy. Enabling prepared statements tracing causes increased pinned connections on the RDS proxy.  …

[SDBM-1870] add warnings to enabling prepared statement tracing when using rds proxy

---

content/en/llm_observability/evaluations/_index.md

Link to permissions from LLMO Evaluations. It's necessary to have LLMO write permissions to use LLMO evals, yet this is not mentioned in the docs.

Link to permissions from LLMO Evaluations

---

.claude/settings.local.json
CLAUDE.md

(maint) Claude doc

---

config/_default/menus/main.en.yaml
content/en/llm_observability/instrumentation/api.md
content/en/llm_observability/instrumentation/custom_instrumentation.md
content/en/llm_observability/quickstart.md

llmobs: guide users on next steps after quickstart

---

content/en/serverless/azure_app_services/azure_app_services_linux.md

* Adding a missing configuration option on the manual tab
* Making changes to the php script for customers that do not use a custom nginx configuration. 
Follow the typical merge process
N/A

Adding additional configuration option; making php instructions clearer

---

content/en/watchdog/faulty_cloud_saas_api_detection.md

removed the google apis from the list as it is not supported
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button …

Remove google apis

---

content/en/llm_observability/instrumentation/sdk.md

Adds back the LLM Observability AWS Lambda guide that was dropped in a recent refactor PR …

[MLOB-3421] add back LLM Observability AWS Lambda guide

---

Makefile.config.example
content/en/security/workload_protection/_index.md

added redirect cascade for files pulled from an external repo

fixing redirects

---

content/en/internal_developer_portal/software_catalog/entity_model/_index.md

https://datadoghq.atlassian.net/browse/DOCS-11556
- Tweaks the description of "custom extensions" to be a bit more clear and thorough.
- Changes the code example to v3.
- Adds references to `extensions` usage for DORA metrics and CD visibility
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access …

Update Custom Extensions content

---

content/en/account_management/rbac/permissions.md
content/en/getting_started/_index.md
content/en/glossary/terms/preview.md

Adds a couple links to the very useful list of Preview features/products. Customer reported not being able to find it from the docs. 

[docs-11587] Increase visibility of Product Preview Program from Docs

---

config/_default/menus/main.en.yaml
content/en/agent/logs/_index.md
content/en/agent/logs/advanced_log_collection.md
content/en/agent/logs/agent_tags.md

Added a new page for information on Agent tags that are automatically added to logs.

Add a new page for Agent Tags

---

content/en/security/sensitive_data_scanner/setup/telemetry_data.md

Adds missing excluded namespaces.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or …

[DOCS-11544] Add tabs and update lists for SDS excluded namespaces

---

content/en/tracing/troubleshooting/tracer_debug_logs.md

@wantsui realised we are not showing the option if the tracer isn't connected with the agent.  …

[APM][Flare] Add a note in case tracer flare is missing

---

content/en/llm_observability/experiments/_index.md

- Adding cookbook links
- Updated the header hierarchy
- Removed "project" mentions for now

LLM Experiments cookbooks

---

content/en/security/code_security/_index.md

Added a further readings section and a blog post relevant to this doc.  …

Update Code Security _index.md

---

content/en/llm_observability/_index.md

Added a blog post relevant to this doc. …

Update  LLM _index.md

---

content/en/network_monitoring/cloud_network_monitoring/setup.md

This adds a new blog to a documentation …

Update cloud network monitoring setup.md

---

layouts/shortcodes/latest-lambda-layer-version.html

Update Serverless layer versions

---

layouts/shortcodes/collapse-content.html

Fixes some accidental string concatenation in the collapsable sections shortcode. …

(maint) Fix collapsable expand setting

---

content/en/agent/faq/fips_proxy.md

Update FIPS proxy version to 1.1.14
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, …

[AGENTRUN-588] Update FIPS proxy version references to 1.1.14

---

assets/scripts/components/tooltip.js

* I noticed that the tooltip shortcode wasn't displaying properly on hover. However, after reloading the page, it worked as expected.
* Tooltips weren't working on initial page load because the script loaded after DOMContentLoaded fired.
All of these should appear without needing to refresh the page now:
- [DSM and DBM N/A tooltips](https://docs-staging.datadoghq.com/brett.blue/tooltip-bug-fix/opentelemetry/compatibility/)
- [Profile types Preview tooltip (glossary type)
](https://docs-staging.datadoghq.com/brett.blue/tooltip-bug-fix/profiler/enabling/supported_versions/#profile-types)
If you want to compare with existing (bugged) behavior:
- [DSM and DBM compatibility](https://docs.datadoghq.com/opentelemetry/compatibility/#supported-datadog-features)
- [Profile …

[bug] Fix tooltip.js race condition

---

config/_default/menus/main.en.yaml
content/en/llm_observability/monitoring/querying.md

DOCS-11576: LLM Obs span/trace query page

---

content/en/opentelemetry/setup/ddot_collector/_index.md

- The existing banner lacked nuance and caused confusion for customers.
- The new banner clearly explains the two scenarios for customers: one where they can use DDOT and one where they can't.
[PREVIEW](https://docs-staging.datadoghq.com/brett.blue/DOCS-11606/opentelemetry/setup/ddot_collector/?site=gov)
[6/5/2025] Merge queue has …

Clarify FedRamp/FIPS compliance banner for DDOT Collector

---

config/_default/menus/main.en.yaml
content/en/getting_started/internal_developer_portal/_index.md

…ng section from IDP GS page
The PM has asked to remove this page from the TOC because development work is paused. However, we want to keep the page alive in case there are folks using it. The goals is just to make it less discoverable.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the …

Remove Overview Pages from TOC

---

content/en/network_monitoring/cloud_network_monitoring/setup.md

This feature didn't make it to GA yet and customer are expecting it to work , causing escalations. …

Update CNM Fargate - adds back callout

---

content/en/security/application_security/how-it-works/add-user-info.md

We have V2 of the business logic events SDK. Here is update with migration guide.
None.
None.

Update ruby application security add user info documentation

---

content/en/integrations/guide/azure-troubleshooting.md

Add a section with a warning about monitoring subscriptions with multiple app registrations …

[DOCS-11571] Add multiple app registrations info

---

layouts/shortcodes/observability_pipelines/destination_settings/microsoft_sentinel.md

Preview: https://docs-staging.datadoghq.com/may/update-msentinel/observability_pipelines/destinations/microsoft_sentinel/ …

[DOCS-10730] Update OP MS Sentinel doc

---

content/en/account_management/rbac/granular_access.md
content/en/service_management/on-call/_index.md

https://docs-staging.datadoghq.com/d.marin/grace/service_management/on-call/#granular-access-control …

[On-Call] Add on-call granular access doc

---

config/_default/params.en.yaml
config/_default/params.es.yaml
config/_default/params.fr.yaml
config/_default/params.ja.yaml
config/_default/params.ko.yaml

Update the announcement banner on docs
JIRA:
https://datadoghq.atlassian.net/browse/WEB-6836
Preview:
https://docs-staging.datadoghq.com/lisianetu/web-6836/ …

[WEB-6836] update announcement banner

---

content/en/security/code_security/dev_tool_int/github_pull_requests/_index.md

Reverts DataDog/documentation#29937 as the functionality is no longer supported

Revert "[K9VULN-5717] Add steps for SCA"

---

content/en/account_management/scim/entra.md

A note was added to the SCIM documentation for Entra ID that implied SCIM as a whole was not available, however, this only applies to Team Provisioning and not User Provisioning, leading to user confusion when trying to set up SCIM
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the …

Adjust Entra ID SCIM note to be more clear

---

content/en/opentelemetry/setup/agentless/traces.md

fix internal link on doc page
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or you …

Fix internal link on page of OTLP Trace Intake doc

---

content/en/llm_observability/evaluations/ootb_evaluations.md

[MLOB-3038] add description and examples for each enriched option

---

layouts/shortcodes/latest-lambda-layer-version.html

Update java layer to match latest [release](https://github.com/DataDog/datadog-lambda-java/releases/tag/v24) …

update latest lambda layer version

---

content/en/tracing/trace_collection/compatibility/java.md

Update Java v0 support level to End-of-life now the published EOL date has been reached. …

Update Java v0 support level to End-of-life

---

config/_default/menus/main.en.yaml
content/en/data_streams/dead_letter_queues.md

Documentation for the Dead Letter Queue feature in DSM …

Added DLQ documentation

---

content/en/serverless/aws_lambda/remote_instrumentation.md

This PR updates the lambda remote instrumentation docs with the following changes:
- Fix `roles` -> `permissions`
- Note that tags are treated as case-insensitive 
- Note that layer versions, extension version, logging, tracing are all configurable
- Clarify that functions are considered manually instrumented only when Datadog Layers or environment variables are already present
- Fix the instructions about skipping small-memory functions
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, …

[SVLS] Add tag case insensitivity and small fixes in remote instrumentation docs

---

content/en/account_management/billing/pricing.md

This PR updates details on the pricing page around the pricing for Incident Management. Specifically, it differentiates the pricing mechanisms for organizations on the legacy usage-based Incident Management plan from those on a seat-based plan. It also provides more detail about what makes a user an "active user" in the usage-based plan, including a correction ("closing" an incident DOES and always has made you an active user).
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any issues with your PR, such as …

INA-7891: Update pricing.md to better reflect Incident Management pricing

---

content/en/security/application_security/exploit-prevention.md

This PR update the matrix where RASP compatibility is shown. PHP was not supported but now it is. …

Update RASP php compatibility

---

assets/styles/components/_multifilter-search.scss

fixes bug where you are unable to scroll long dropdown menus within the `multifilter-search` component
motivation: https://datadoghq.atlassian.net/jira/software/projects/DOCSENG/boards/10954?selectedIssue=DOCSENG-95
preview: https://docs-staging.datadoghq.com/stefon.simmons/docseng-95-bug/cloud_cost_management/recommendations/#recommendation-and-resource-descriptions
- select the `Resource Type` dropdown. you should be able to vertically scroll to all items 
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview makes it easier for us to check any …

bug fix: enable scrolling long dropdown forms on `multifilter-search` component - [DOCSENG-95]

---

layouts/partials/logs/logs-cloud.html

WE recently added Oracle Cloud Infrastructure as Cloud source for logs. WE need to reflect this in the documentation too. …

[LOGSXP-3837] Add OCI to Cloud source for logs

---

content/en/observability_pipelines/sources/azure_event_hubs.md

Update image size

---

content/en/service_management/on-call/triggering_pages/_index.md

[On-Call] Fix links

---

content/en/actions/app_builder/components/_index.md
content/en/actions/app_builder/events.md

This PR adds links to the new [Build Self-Serve Apps with App Builder for Third-Party Integrations](https://learn.datadoghq.com/courses/app-builder-integration) course to two Docs pages on App Builder …

Link new App Builder Learning Center course to relevant Docs pages

---

content/en/remote_configuration/_index.md
content/en/security/sensitive_data_scanner/setup/cloud_storage.md
content/en/security/workload_protection/_index.md

(Remote config) Update instructions

---

content/en/network_monitoring/network_path/setup.md

Add minimum Windows version requirement for `tcp_method: syn_socket` option

add minimum Windows version

---

content/en/dashboards/template_variables.md

- Lists out the widgets that support this feature.
- Requested by product team

Add list of supported widgets

---

content/en/security/cloud_security_management/misconfigurations/frameworks_and_benchmarks/supported_frameworks.md

Add CIS AWS v5.0.0 to CloudSec frameworks list

---

content/en/service_management/case_management/customization.md

Clarify the link text to indicate that it's an anchor link, as this has caused some confusion for users.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash …

Clarify link text

---

content/en/monitors/notify/notification_rules.md

- Add a 1000 rules per org limit note
- [DOCS-11669](https://datadoghq.atlassian.net/browse/DOCS-11669)
[DOCS-11669]: https://datadoghq.atlassian.net/browse/DOCS-11669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add rule limit

---

content/en/observability_pipelines/monitoring/_index.md

[DOCS-11126] Add time window average for metrics

---

content/en/integrations/guide/azure-manual-setup.md
content/en/integrations/guide/azure-programmatic-management.md
content/en/monitors/guide/monitor_best_practices.md
content/en/monitors/templates/_index.md
content/en/network_monitoring/cloud_network_monitoring/_index.md
content/en/partners/getting_started/delivering-value.md

- Cherry picked commits from https://github.com/DataDog/documentation/issues/30628
- Replaces Recommended Monitors with Monitor Templates

Update monitor template references in docs

---

content/en/logs/explorer/search_syntax.md

Current list of special characters is outdated. You can test it on https://app.datadoghq.com/logs
It just updates outdated docs, no need to wait for another release.

Update list of special characters

---

content/en/service_management/incident_management/incident_settings/information.md

Updates the "Information" page of Incident Management settings documentation to include detail about new features and expand on the features we've delivered in recent years. …

INA-7891: Update Incident Management settings "information" page

---

layouts/partials/cloud_cost/cost-integrations.html

fixes links for tiles. 
links for the tiles were not updated. this page contains an alias for the old path but Hugo aliases redirect to the `.Permalink` which does not include the query params / tab name from the originally clicked link
**motivation**: https://datadoghq.atlassian.net/jira/software/projects/DOCSENG/boards/10954?selectedIssue=DOCSENG-94
**preview**: https://docs-staging.datadoghq.com/stefon.simmons/docseng-94/cloud_cost_management/setup/saas_costs/
- selecting a tile under **Overview** like **MongoDB** should take you to the appropriate **MongoDB** tab under **Configure your SaaS accounts**
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request …

fix tile links on `saas_costs` page - DOCSENG-94

---

content/en/security/code_security/software_composition_analysis/_index.md

…ycle
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or you need help, reach out in …

Update Software Composition Analysis adding the Vulnerabilities Lifecycle

---

content/en/observability_pipelines/destinations/datadog_logs.md

- Add info about Azure Private Link
- Add region shortcodes for Azure and AWS Private Link …

[DOCS-11788] Add Azure Private Link to OP Datadog Logs destination

---

content/en/security/cloud_siem/threat_intelligence.md

[DOCS-11762] Add domain to Cloud SIEM Threat Intel

---

content/en/security/notifications/_index.md

Code Security was missing in the products list

adding Code Security to the supported products list

---

layouts/shortcodes/observability_pipelines/configure_existing_pipelines/destination_env_vars/crowdstrike_ng_siem.md

[DOCS-11719] Update OP Crowdstrike destination env var

---

content/en/service_management/incident_management/response_team.md

Fixes a typo and broken link in the Incident Settings documentation. …

Fix typo and broken link.

---

content/en/llm_observability/evaluations/submit_evaluations.md
content/en/serverless/aws_lambda/lwa.md
content/en/tracing/guide/local_sdk_injection.md

Replace mentions of `NodeJS` and `JavaScript` with the correct `Node.js`. …

APM SDK Injection (and others): fix "Node.js"

---

content/en/logs/log_configuration/logs_to_metrics.md

- [DOCS-11721](https://datadoghq.atlassian.net/browse/DOCS-11721)
**Do not merge** pending SME approval
[DOCS-11721]: https://datadoghq.atlassian.net/browse/DOCS-11721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add a note about N/A values for datadog_is_excluded

---

content/en/llm_observability/monitoring/cluster_map.md

- Update the https://docs.datadoghq.com/llm_observability/monitoring/cluster_map/ documentation to mention that spans clustering can take up to 24h …

[MLOB-3305] Update LLM Obs clusters documentation

---

assets/styles/components/_tab-toggle.scss

fixes z index to avoid code lang tabs overlapping the typsense search window
**motivation**: https://datadoghq.atlassian.net/browse/DOCSENG-113
**preview**: https://docs-staging.datadoghq.com/stefon.simmons/fix-overlap-docseng-113/api/latest/?s=attr
- while the search window is open, scroll the page. the lang tabs should be behind along with the rest of the page content
If your branch doesn't follow this format, …

fix z-index on `.code-lang-list-container` - DOCSENG-113

---

content/en/network_monitoring/devices/snmp_metrics.md

- Adds de-duplication setting config to the SNMP Autodiscovery docs
- Re-formats some badly formatted yaml …

[DOCS-11792] add de-duplication setting to SNMP docs 

---

content/en/logs/log_configuration/archives.md
content/es/logs/log_configuration/archives.md
content/fr/logs/log_configuration/archives.md
content/ja/logs/log_configuration/archives.md
content/ko/logs/log_configuration/archives.md

fix font for `*Logging without Limits は Datadog, Inc. の商標です。`. add extra line in markdown to separate `<br>` element that messes with the text's font on a `ja` page. It was removing the `<p>` tag from around the rendered text
- adding extra line on all translated pages and `en`
**motivation**: https://datadoghq.atlassian.net/jira/software/projects/DOCSENG/boards/10954?selectedIssue=DOCSENG-111
**preview**: https://docs-staging.datadoghq.com/stefon.simmons/docseng-111-ja-fix/ja/logs/log_configuration/archives/?tab=awss3#その他の参考資料
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch …

fix font on `ja` page- [DOCSENG-111]

---

content/en/tracing/other_telemetry/connect_logs_and_traces/ruby.md

Connecting logs and traces using the logging library [lograge](https://github.com/roidrage/lograge) in Ruby has a caveat that a specific configuration is need.
This PR points the user to a page in our documentation that explains the process of configuring `lograge` correctly. …

Update lograge compatibility for Ruby logging

---

config/_default/config.yaml

Trying to resolve some intermittent failures in the build by bumping the hugo build timeout setting. …

bump hugo timeout

---

assets/styles/components/_tab-toggle.scss

motivation: https://datadoghq.atlassian.net/browse/DOCSENG-113
preview: click tabs. check that tabs work correctly
- https://docs-staging.datadoghq.com/stefon.simmons/fix-tab-z-ndex/api/latest/?s=attr&tab=python-legacy
- https://docs-staging.datadoghq.com/stefon.simmons/fix-tab-z-ndex/security/cloud_siem/detection_rules/?tab=threshold#define-a-search-query …

fix z-index on tabs - [DOCSENG-113]

---

content/en/cloudcraft/components-aws/ec2.md
content/es/cloudcraft/components-aws/ec2.md
content/es/cloudcraft/components-aws/elasticache.md
content/es/cloudcraft/components-aws/elasticsearch.md
content/es/cloudcraft/components-aws/rds.md
content/ja/cloudcraft/components-aws/ec2.md
content/ko/cloudcraft/components-aws/ec2.md

Found typo while looking at translation PR. Fixed typo in as many places as I could find it. …

Fix `leaseContractLenght` typo across languages

---

content/en/data_jobs/airflow.md
content/en/data_jobs/kubernetes.md

i don't know why changing the heading level makes the tabs work, but it does …

fixing tabs on DJM pages

---

content/en/service_management/on-call/guides/configure-mobile-device-for-on-call.md

Fix broken link in On-Call mobile phone set up link

---

content/en/cloud_cost_management/planning/budgets.md

Adds a reference link about how to create a budget-based monitor from the budget page. …

[CCM] Link to monitor page

---

content/en/security/cloud_siem/open_cybersecurity_schema_framework.md

Add new integrations that support OCSF pipelines. …

[DOCS-11817] Add integrations to list of supported OCSF pipelines

---

data/partials/platforms.yaml

This adds a cloud foundry docs that include a link to the in-app Agent installation flow. …

Agent Basic Usage - Cloud Foundry docs 

---

content/en/real_user_monitoring/browser/setup/server/java.md

Removes the troubleshooting section per PM request. …

[RUM] remove troubleshooting section from java servlet doc

---

content/en/data_streams/data_pipeline_lineage.md
content/en/data_streams/dead_letter_queues.md
content/en/data_streams/live_messages.md
content/en/data_streams/metrics_and_tags.md
content/en/data_streams/setup/_index.md

adds warnings about limited us1-fed support to more DSM pages …

DOCS-11787: gov warnings for DSM

---

content/en/network_monitoring/network_path/_index.md
content/en/network_monitoring/network_path/setup.md

Removes Limited Availability callouts for Network Path/ keeping "experimental" wording on Dynamic paths per PM. …

removing preview callout for Network Path GA

---

content/en/serverless/google_cloud_run/containers/in_process/dotnet.md
content/en/serverless/google_cloud_run/containers/in_process/go.md
content/en/serverless/google_cloud_run/containers/in_process/java.md
content/en/serverless/google_cloud_run/containers/in_process/nodejs.md
content/en/serverless/google_cloud_run/containers/in_process/php.md
content/en/serverless/google_cloud_run/containers/in_process/python.md
content/en/serverless/google_cloud_run/containers/in_process/ruby.md
content/en/serverless/google_cloud_run/containers/sidecar/dotnet.md
content/en/serverless/google_cloud_run/containers/sidecar/go.md
content/en/serverless/google_cloud_run/containers/sidecar/java.md
content/en/serverless/google_cloud_run/containers/sidecar/nodejs.md
content/en/serverless/google_cloud_run/containers/sidecar/php.md
content/en/serverless/google_cloud_run/containers/sidecar/python.md
content/en/serverless/google_cloud_run/containers/sidecar/ruby.md
layouts/shortcodes/gcr-configure.html

[Cloud Run] Add metrics instructions

---

content/en/serverless/azure_app_services/azure_app_services_windows.md

one link was going to the wrong number! …

DOCS-11855 link fix

---

content/en/synthetics/guide/otp-email-synthetics-test.md

Adds product identifier at the top and other small fixes/improvements …

Small updates to Extract a one time passcode guide

---

content/.gitignore

Sync the Cdocs .gitignore with the latest build image. …

Sync the Cdocs .gitignore

---

config/_default/menus/main.en.yaml
content/en/cloud_cost_management/setup/saas_costs.md

Received internal feedback that the SaaS Cost - [Snowflake Integration page](https://docs.datadoghq.com/cloud_cost_management/setup/saas_costs/?tab=snowflake#setup) was missing details from the [Snowflake Integration page](https://docs.datadoghq.com/integrations/snowflake-web/).
- Adds a line and screenshot that includes a link on finding the Snowflake account URL
- Links to the Snowflake integration for the steps about creating roles and key-value pair authentication so as to not duplicate that info
- Adds a link to the Cloud Cost metrics section of the Snowflake integration page
- I also changed the anchor so that when clicking on an integration on the SaaS Cost integration page, users will be taken to a section that's a lot closer to the actual integration they clicked on
Merge …

[DOCS-11798] Consolidate CCM setup for Snowflake

---

content/en/cloud_cost_management/setup/saas_costs.md

Noticed a link that should be corrected. …

[CCM] correct link

---

content/en/security/cloud_security_management/guide/agent_variables.md

Document flags to denylist, passlist containers from cloud security

---

content/en/security/cloud_security_management/vulnerabilities/_index.md

CSM VM - GovCloud GA: remove preview banner

---

content/en/getting_started/continuous_testing/_index.md

A couple of months ago, we removed the integration of the Synthetics product in the VS Code extension. We updated the documentation for the extension, but forgot to update the Synthetics one.  …

Remove mentions of the VS Code extension support for Synthetics

---

content/en/security/code_security/static_analysis/github_actions.md

Our GitHub action should only be used with the `push` trigger. Using it with other event trigger in GitHub Action may cause issues.
Merge when approved.

[K9VULN-7901] Add documentation about event trigger

---

content/en/integrations/guide/storage-monitoring-setup.md

Update S3 Inventory casing

---

content/en/data_jobs/airflow.md

Because we flag that DJM is not compatible with Dataplex, some customers may disable Dataplex when creating their Composer env.
In that case, OL listener is disabled by GCP in the env. We make sure it's enabled by adding this config key. Note that this config key is not harmful, even for customers with Dataplex enabled.
[6/5/2025] …

[DJM] Ask customers to force enable OL

---

content/en/glossary/terms/system.md

https://datadoghq.atlassian.net/browse/DOCS-11872 …

Add 'system' to glossary 

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/troubleshooting.md

https://datadoghq.atlassian.net/browse/DOCS-11917 …

clarify two env vars for enabling debug logging

---

.vscode/markdoc.code-snippets
.vscode/markdown.code-snippets

Adds more aliases for notes/alerts. Cos these are hard to find sometimes.  …

(maint) Add more aliases for alerts

---

content/en/tests/flaky_management/_index.md

This add the version of the Go libraries that support the Test Management features …

[Test Optimization] Add Go versions supporting Flaky Test Management features

---

content/en/network_monitoring/devices/ping.md

Revise ping settings configuration instructions for Autodiscovery for clarity and to reduce confusion.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash …

[DOCS-11889] Revise ping settings configuration instructions

---

content/en/actions/workflows/build.md

Add a new section on the "Build workflows" page of the workflow-automation documentation, on updating published workflows and managing drafts. …

Add workflow draft documentation

---

content/en/sheets/_index.md

We added new data sources to the Sheets product so we want to update the public documentation accordingly. …

[SHEETS-2095] Add new data sources in Sheets public documentation

---

content/en/agent/fleet_automation/remote_management.md

customers running 7.69+ dont have to follow older instructions, can simply set the DD_REMOTE_UPDATES to true …

small patch to reflect simpler enablement for 7.69

---

local/bin/py/integration-finder.py

Remove dogweb from integration finder

---

content/en/service_management/on-call/cross_org_paging.md

Cross Org Paging Permissions Fix

---

content/en/opentelemetry/mapping/semantic_mapping.md

Replace footnote that was accidentally removed in https://github.com/DataDog/documentation/commit/7615b09687dae556b76c08a78e47df5f4d59014c#diff-dcf9ea37b17a6c902bd2161b58b7f1d01b761a39520c562db75d11eb27d11615R31
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been …

Replace deployment.environment.name footnote.

---

content/en/security/code_security/static_analysis/setup/_index.md

Update SAST Setup Page

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/troubleshooting.md

Removing instructions for unsupported tracer version override …

Remove section about manually updating tracer version

---

content/en/cloudprem/ingest_logs/datadog_agent.md

Quick formatting fix

---

content/en/tracing/trace_collection/automatic_instrumentation/single-step-apm/troubleshooting.md

add section to ssi troubleshooting guide about storage requirements

---

content/en/logs/log_collection/kotlin_multiplatform.md
content/en/real_user_monitoring/mobile_and_tv_monitoring/kotlin_multiplatform/setup.md

This PR updates the reference to the iOS SDK versions for the KMP SDK releases: now we won't use the table, we will point to the actual file in the SDK repo. …

Update iOS SDK version reference for the KMP SDK releases

---

content/en/ddsql_reference/_index.md

- Add description and example for the `USING` clause. …

Add description of `USING`

---

content/en/cloud_cost_management/recommendations/_index.md
content/en/synthetics/_index.md
content/en/synthetics/api_tests/_index.md

- Remove link to blog post that was deprecated
- Add new blog post link …

Update blog links for Tuesday Tasks

---

config/_default/menus/main.en.yaml
content/en/internal_developer_portal/onboarding_guide.md

https://datadoghq.atlassian.net/browse/DOCS-11913 …

IDP Onboarding Guide

---

layouts/shortcodes/aws-permissions.md
layouts/shortcodes/aws-resource-collection-permissions.md

switch to use data from websites sources but the render on docs. 
Intention to keep sources as a data source …

shortcodes here but data from sources

---

content/en/error_tracking/frontend/browser.md

Corrects link due to misnumbering.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, …

[DOCS-11943] Fix browser ET link

---

content/en/reference_tables/_index.md
content/es/reference_tables/_index.md

Noticed a broken URL resulting in 404 error because of an extra space in the further reading links of reference tables documentation page. This PR removes the extra space for both English and Spanish content
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been …

Fix broken url in further reading

---

layouts/shortcodes/latest-lambda-layer-version.html

Released v86 of Lambda Extension
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or …

Bump lambda extension version to 86

---

content/en/real_user_monitoring/correlate_with_other_telemetry/profiling/_index.md

Adds SDK version requirement and updates a percentage, per PM request. …

[DOCS-11981] Small RUM Profiling updates

---

content/en/account_management/org_settings/cross_org_visibility_api.md

The Org Connection Update API has just been made public. This documentation change updates the org connection API documentation to include a section on the new update endpoint.
Verified by checking the [staging docs](https://docs-staging.datadoghq.com/amy.li/docs/account_management/org_settings/cross_org_visibility_api/#update-a-connection).
If your branch doesn't follow this format, rename it or create a new branch …

Add update API to OrgConnection documentation

---

layouts/shortcodes/mainland-china-disclaimer.en.md

This PR updates a reference link number, as it's currently causing issues by overlapping with other reference links (as demonstrated by the `AWS integration configuration page` link in [this section](http://localhost:1313/integrations/guide/aws-manual-setup/?site=us&tab=roledelegation#complete-the-setup-in-datadog))
[6/5/2025] Merge …

[DOCS-11975] Update link

---

local/bin/py/build/configurations/pull_config.yaml
local/bin/py/build/configurations/pull_config_preview.yaml

Pull the CWS agent documentation from the 7.70.x branch now that this version has been released to customers. …

Pull CWS agent documentation from 7.70.x branch

---

content/en/logs/log_collection/android.md
content/en/logs/log_collection/ios.md

RUM-10436: Add documentation to Logs global attributes

---

content/en/ddsql_reference/_index.md

- Improve `Syntax` table readability using a description list.  …

Format  DDSQL Syntax table as description list

---

content/en/logs/guide/access-your-log-data-programmatically.md

Remove a section of the docs with deprecated options (shown as deprecated [here](https://docs.datadoghq.com/api/latest/logs/#search-logs-post) and confirmed by the logs team) …

Remove deprecated options

---

content/en/actions/workflows/_index.md

- update workflow action count
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash and Merge** button to merge the PR. If you don't have write access, or …

[WF] Update workflow action count

---

content/en/synthetics/notifications/advanced_notifications.md

Adding a callout to provide an example of `{{{` triple curly brackets on the Synthetic Monitors advanced notifications page. …

[DOCS-12025] adding information about triple curly braces

---

.github/workflows/bump_private_action_version.yml
.github/workflows/bump_synthetics_worker_version.yml

Updates workflows to point at correct SHA …

Update workflow shas

---

content/en/cloud_cost_management/recommendations/_index.md

Adds a line item to the CCM Recs table in documentation. We're missing that rec. …

Add Cloudtrail Trails to CCM Recs table

---

content/en/data_security/data_retention_periods.md

Update the retention for Error Tracking error samples. This has been extended to 30 days for all customers.
https://datadoghq.atlassian.net/browse/ERRORT-5653

Update Error Tracking samples retention

---

content/en/agent/fleet_automation/remote_management.md

Quick grammatical fix on this

---

content/en/actions/app_builder/components/_index.md

Adds a new component description on this page https://docs.datadoghq.com/actions/app_builder/components/
Needs to be merged before EOM as this will be linked to from another section …

add integration logo documentation

---

content/en/llm_observability/instrumentation/sdk.md

Documents optional ML application configuration for SDK usage, specifying that they default to the value of `DD_SERVICE`, or a propagated ML application. …

[MLOB-3636] Add LLM Observability Documentation for Optional ML Application

---

layouts/partials/algolia/glossary.json
layouts/partials/algolia/page-sections.json
layouts/partials/algolia/standard-attributes.json

Reverts DataDog/documentation#31568

Revert "fix: deprecated lang arg"

---

content/en/monitors/types/apm.md
content/en/tracing/trace_pipeline/trace_retention.md

Add a precision about the fact that indirectly indexed spans are not evaluated by trace analytics monitors: view comprehensive explanation [here](https://dd.slack.com/archives/C07QJ00MTUL/p1755707097958319?thread_ts=1754059580.236669&cid=C07QJ00MTUL)
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write …

Trace-level retention filters evaluation edge case

---

content/en/serverless/azure_app_service/windows_code.md

Fix for this issue: https://github.com/DataDog/documentation/pull/31472#discussion_r2349494471 …

[SVLS] fix windows code links

---

content/en/security/workload_protection/supported_linux_distributions.md

Update the outdated list of supported distros by Workload Protection. …

Update distros supported by Workload Protection

---

layouts/shortcodes/gcr-install-sidecar-datadog-ci.md

[Cloud Run] Fix datadog-ci link

---

content/en/bits_ai/mcp_server/setup/_index.md

[SYNTH-21756](https://datadoghq.atlassian.net/browse/SYNTH-21756)
https://github.com/DataDog/dd-source/pull/268350/s introduces 2 new synthetics tools on the datadog MCP server under the synthetics toolset: `edit_synthetics_tests` and `synthetics_test_wizard`. 
This PR updates the documentation to reflect that, and also moves the existing `get_synthetics_tests` tool to the end of the list to group it with the 2 others.
wait for https://github.com/DataDog/dd-source/pull/268350/s to be merged
Your branch name MUST follow the `<name>/<description>` convention and include the forward slash (`/`). Without this format, your pull request will not pass CI, the GitLab pipeline will not run, and you won't get a branch preview. Getting a branch preview …

[SYNTH-21756] Update MCP documentation with new synthetics tools

---

content/en/cloud_cost_management/recommendations/_index.md

remove duplicate VM Instance Downsize entry

---

content/en/llm_observability/quickstart.md

Adds Java to Quickstart doc, alongside Node and Python …

Add Java to QuickStart LLM

---

content/es/developers/ide_plugins/vscode/_index.md

This PR fixes some formatting issues in the Spanish documentation …

Fix formatting issues in VS Code documentation

---

content/en/database_monitoring/guide/_index.md

This PR adds `Capturing SQL Query Parameter Values With Database Monitoring` to the guide index. …

add parameterized_queries to guide index

---

content/en/synthetics/mobile_app_testing/devices.md
content/en/synthetics/mobile_app_testing/mobile_app_tests/restricted_networks.md

Removes duplicate Gov callout from a few lingering pages on Mobile App testing as these are replaced now by the [partial](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/5201857960/Documenting+site+support#Use-the-params.yaml-file)
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access …

removing duplicate Gov callout

---

content/en/serverless/azure_app_service/linux_code.md

Correct linux code manual instructions

---

content/en/llm_observability/experiments/_index.md

Update preview URL of Github Link
Update preview URL of Github Link to avoid 404 error …

Update _index.md to avoid 404 error

---

content/en/mobile/enterprise_configuration.md

Converting table of variables to a list
Updating the Intune table for the mobile app into a list in order to make it more easy for users to read. …

Update Intune table to list

---

content/en/tracing/trace_collection/automatic_instrumentation/dd_libraries/php.md

Clarify a note about Windows support in the PHP APM tracer. The note is not about that _Windows_ itself supports, it's about what the _tracer_ supports on Windows. …

Update warning note for Windows PHP tracing

---

content/en/gpu_monitoring/setup.md

Fixes the description of the `gpu.runtimeClassName` setting …

gpu: improve explanation for runtimeClassName setting

---

content/en/error_tracking/backend/exception_replay.md

Update the Exception Replay PHP min tracer version to 1.12.1

---

content/en/synthetics/platform/settings/_index.md

add documentation for RUM data collection with MAT

add documentation for RUM data collection with MAT

---

content/en/getting_started/_index.md

exchange software catalog for idp in getting started landing page

---

content/en/service_management/status_pages/_index.md

Temporarily removes the section for configuring a custom domain for Status Pages from our public documentation. This feature has been disabled for longer than we'd have like due to resource constraints with our partner and the documentation is a source of confusion.
We'll be adding this back once we've resolved the issue with our partner.
If your branch doesn't follow this format, rename it or create a new branch and …

Temporarily remove custom domain configuration from Status Pages docs

---

content/en/network_monitoring/devices/troubleshooting.md

- Requested by support to reduce support tickets
- We have in the section immediately below, commands to check if UFW firewall is blocking traffic but don't really explain very well what it is. …

[DOCS-12072] adding alert info for firewalls to NDM Troubleshooting page

---

content/en/database_monitoring/setup_postgres/selfhosted.md

Fixes conflicting link references for https://datadoghq.atlassian.net/browse/DOCS-12105?atlOrigin=eyJpIjoiZDQ0MzA3ZDFkYmI4NDdjYjk0MDQwOGVlMDY1YWQ5YzYiLCJwIjoiaiJ9. Also updates an external postgres URL to reference an evergreen "current version" URL instead of a version-specific page. …

(DOCS-12105)(DBM) Link reference updates

---

content/en/agent/fleet_automation/remote_management.md

One line remote agent management change

---

content/en/llm_observability/experiments/_index.md

Added section for Automated Experiments (CI/CD) and a Github Actions section with an example workflow.

added ci/cd example for github actions

---

CONTRIBUTING.md
content/en/service_management/status_pages/_index.md

Updates our `CONTRIBUTING.md` file with new rules, some clarifications and rephrasing, etc. No huge structural changes. …

Update contributing file

---

content/en/llm_observability/_index.md
content/en/llm_observability/evaluations/_index.md
content/en/llm_observability/evaluations/managed_evaluations.md
content/en/llm_observability/evaluations/ootb_evaluations.md
content/en/llm_observability/monitoring/cluster_map.md
content/en/llm_observability/terms/_index.md

- Updating the instructions to create and edit evals to follow the new UX
- Update terminology from ootb evals to managed evals to be consistent with the new UI

Update documentation for managed eval creation

---

content/en/actions/app_builder/_index.md
content/en/actions/app_builder/access_and_auth.md
content/en/actions/app_builder/build.md
content/en/actions/app_builder/embedded_apps.md
content/en/actions/app_builder/expressions.md
content/en/actions/app_builder/queries.md

This PR updates broken links and old names of Blueprint examples in App Builder pages. 

update App Builder links

---

content/en/monitors/notify/variables.md

- Clarify this is not the reference source for all attributes, only an example
- Users can see the full list of available attributes in the app
- [DOCS-11895](https://datadoghq.atlassian.net/browse/DOCS-11895)
[DOCS-11895]: https://datadoghq.atlassian.net/browse/DOCS-11895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add information on monitor attributes

---

content/en/bits_ai/bits_ai_sre/investigate_alerts.md

Reordered/reformatted a few sections for clarity …

Bits Docs Updates

---

content/en/account_management/org_settings/custom_landing.md

Adds a note requested by a TSE saying that free trial users can't use custom landing pages. …

DOCS-11821 Describe restriction on custom landing page during free trial

---

config/_default/menus/main.en.yaml
content/en/llm_observability/evaluations/_index.md
content/en/llm_observability/evaluations/external_evaluations.md
content/en/llm_observability/evaluations/managed_evaluations.md
content/en/llm_observability/evaluations/ragas_evaluations.md
content/en/llm_observability/evaluations/submit_nemo_evaluations.md

Rename submit custom evaluations to external evaluations. Align on new consistent naming.

[MLOB-3979] Rename submit custom evaluations to external evaluations

---

content/en/tracing/services/inferred_services.md

Helping a PM make an update. Essentially a clone of https://github.com/DataDog/documentation/pull/31722.
[6/5/2025] Merge queue has been disabled on the documentation repo. If you have write access to the repo, the PR has been reviewed by a Documentation team member, and all of the required checks have passed, you can use the **Squash …

Add link to inferred entities

---

content/en/logs/log_collection/javascript.md

Some changes were applied to the Browser SDK Logs package to support Worker runtime environment. Add this information
to the documentation. …

Add Worker support to the documentation

---

content/en/service_management/incident_management/integrations/status_pages.md

- Add a placeholder page for Datadog Status Pages in Incident integration.

Add placeholder for status pages integration

---

content/en/service_management/incident_management/integrations/slack/_index.md

Link out to the integration permissions from the incident management docs

Add reference to permissions

---

layouts/shortcodes/observability_pipelines/configure_existing_pipelines/destination_env_vars/crowdstrike_ng_siem.md

Small edit

---

content/en/network_monitoring/cloud_network_monitoring/network_analytics.md

- adds new TCP Metrics to network analytics page (connections cancels, host unreachable, network unreachable)
- alphabetizes the list …

[DOCS-12186] adding new TCP Metrics to network analytics page

---

content/en/bits_ai/bits_ai_sre/investigate_alerts.md

Hi, we have updated our Bits AI SRE requirements and the updates to the doc attempt to express the new changes succinctly. …

Bits AI SRE category updates

---

content/en/integrations/guide/high_availability.md

Adds new integrations that are now supported by HA Agent. …

[DOCS-12224] updating Integrations list

---

config/_default/params.yaml

Network Path is now available for US FED customers. …

[DOCS-12184] remove Gov callout from Network Path

---

content/en/tracing/other_telemetry/connect_logs_and_traces/java.md

Updates the documentation to explicitly state the requirement for the dd-trace-api dependency when using manual injection, addressing user confusion reported in a ticket. …

Clarify dependencies for Java Log Correlation

---

content/en/real_user_monitoring/platform/generate_metrics.md

Adds a note about custom metric sources for RUM, per internal feedback. …

Add custom metrics source note

---

content/en/cloud_cost_management/recommendations/_index.md

As described in title, adding the GCP Integration resource collection blurb for ccm recs. …

Adding GCP Integration resource collection blurb in ccm Recs.

---

content/en/real_user_monitoring/browser/monitoring_page_performance.md

The CWV Course has been replaced. This PR updates the link. …

Update link for CWV Course
